
** 大暦
*** 大暦元年
# year 0766
# p 

春，
正月，
乙酉，
敕復補國子學生。
# p 

丙戌，
以戸部尚書 rm#r00276@劉晏 爲 dm#dm07883@都畿 、 dm#dm04660@河南 、 dm#dm04984@淮南 、 dm#dm04476@江南 、 dm#dm05139@湖南 、 dm#dm06881@荊南 、 dm#dm02400@山南東道 轉運、常平、鑄錢、鹽鐵等使，
侍郎 rm#r03064@第五琦 爲 dm#dm00444@京畿 、 dm#dm08283@關内 、 dm#dm04672@河東 、 dm#dm00785@劍南 、 dm#dm02401@山南西道 轉運等使，
分理天下財賦。
# p 

 rm#r00462@周智光 至 dm#dm06938@華州 ，
益驕横，
召之，
不至，
上命 rm#xjts22060@杜冕 從 rm#r01213@張獻誠 於 dm#dm02398@山南 以避之；
 rm#r00462@智光 遣兵於 dm#dm01377@商山 邀之，
不獲。

 rm#r00462@智光 自知罪重，
乃聚亡命、無頼子弟，
衆至數萬，
縱其剽掠以悦其心，
留 dm#dm08281@關中 所漕米二萬斛，
藩鎭貢獻，
往往殺其使者而奪之。
# p 

二月，
丁亥朔，
釋奠于國子監。

命宰相帥常參官、 rm#r04309@魚朝恩 帥六軍諸將往聽講，
子弟皆服朱紫爲諸生。

 rm#r04309@朝恩 既貴顯，
乃學講經爲文，
僅能執筆辨章句，
遽自謂才兼文武，
人莫敢與之抗。
# p 

辛卯，
命有司脩國子監。
# p 

 rm#r00165@元載 專權，
恐奏事者攻訐其私，
乃請：
「百官凡論事，
皆先白長官，
長官白宰相，
然後奏聞。

」
仍以上旨諭百官曰：
「比日諸司奏事煩多，
所言多讒毀，
故委長官、宰相先定其可否。」

# p 

刑部尚書 rm#r04147@顏眞卿 上疏，
以爲：
「郎官、御史，
陛下之耳目。

今使論事者先白宰相，
是自掩其耳目也。

陛下患羣臣之爲讒，
何不察其言之虚實！

若所言果虚宜誅之，
果實宜賞之。

不務爲此，
而使天下謂陛下厭聽覽之煩，
託此爲辭以塞諫爭之路，
臣竊爲陛下惜之！

 rm#r01602@太宗 著門司式云：
『其無門籍人，
有急奏者，
皆令門司與仗家引奏，
無得關礙。』

所以防壅蔽也。

 y@天寶 以後，
 rm#r01824@李林甫 爲相，
深疾言者，
道路以目。

上意不下逮，
下情不上達，
蒙蔽喑嗚，
卒成幸 dm#dm07197@蜀 之禍。

陵夷至于今日，
其所從來者漸矣。

夫人主大開不諱之路，
羣臣猶莫敢盡言，
況令宰相大臣裁而抑之，
則陛下所聞見者不過三數人耳。

天下之士從此鉗口結舌，
陛下見無復言者，
以爲天下無事可論，
是 rm#r01824@林甫 復起於今日也！

昔 rm#r01824@林甫 雖權，
羣臣有不諮宰相輒奏事者，
則託以他事陰中傷之，
猶不敢明令百司奏事皆先白宰相也。

陛下儻不早寤，
漸成孤立，
後雖悔之，
亦無及矣！」

 rm#r00165@載 聞而恨之，
奏 rm#r04147@眞卿 誹謗；
乙未，
貶 dm#dm02449@峽州 別駕。

# p 

己亥，
命大理少卿 rm@楊濟 脩好於吐蕃。

# p 

壬子，
以 rm#r02067@杜鴻漸 爲 dm#dm02401@山南西道 ‧ dm#dm00781@劍南東‧西川 副元帥、 dm#dm00784@劍南西川 節度使，
以平 dm#dm07197@蜀 亂。

# p 

以 dm#dm01437@四鎭 、 dm#dm00860@北庭 行營節度使 rm#r04182@馬璘 兼 dm#dm07810@邠寧 節度使。

 rm#r04182@璘 以 rm#r02349@段秀實 爲三使都虞候，
卒有能引弓重二百四十斤者，
犯盜當死，
 rm#r04182@璘 欲生之，
 rm#r02349@秀實 曰：
「將有愛憎而法不一，
雖 rm@韓 、 rm@彭 不能爲理。」

 rm#r04182@璘 善其議，
竟殺之。

 rm#r04182@璘 處事或不中理，
 rm#r02349@秀實 力爭之。

 rm#r04182@璘 有時怒甚，
左右戰栗，
 rm#r02349@秀實 曰：
「 rm#r02349@秀實 罪若可殺，
何以怒爲！

無罪殺人，
恐渉非道。」

 rm#r04182@璘 拂衣起，
 rm#r02349@秀實 徐歩而出；
良久，
 rm#r04182@璘 置酒召 rm#r02349@秀實 謝之。

自是軍州事皆咨 rm#r02349@秀實 而後行。

 rm#r04182@璘 由是在 dm#dm07810@邠寧 ，
聲稱殊美。


# p 

癸丑，
以 dm#dm02401@山南西道 節度使 rm#r01213@張獻誠 兼 dm#dm00782@劍南東川 節度使，
 dm#dm07804@邛州 刺史 rm#xjts22355@柏茂琳 爲 dm#dm07799@邛南 防禦使；
以 rm#r00914@崔旰 爲 dm#dm06857@茂州 刺史，
充 dm#dm07314@西山 防禦使。

三月，
癸未，
 rm#r01213@獻誠 與 rm#r00914@旰 戰于 dm#dm04052@梓州 ，
 rm#r01213@獻誠 軍敗，
僅以身免，
旌節皆爲 rm#r00914@旰 所奪。
# p 

夏，
五月，
 dm#dm04695@河西 節度使 rm#xjts22601@楊休明 徙鎭 dm#dm04617@沙州 。

# p 

秋，
八月，
國子監成；
丁亥，
釋奠。

 rm#r04309@魚朝恩 執易升高座，
講「鼎覆餗」
以譏宰相。

 rm#r02687@王縉 怒，
 rm#r00165@元載 怡然。

 rm#r04309@朝恩 謂人曰：
「怒者常情，
笑者不可測也。」

# p 

 rm#r02067@杜鴻漸 至 dm#dm07197@蜀 境，
聞 rm#r01213@張獻誠 敗而懼，
使人先達意於 rm#r00914@崔旰 ，
許以萬全。

 rm#r00914@旰 卑辭重賂以迎之，
 rm#r02067@鴻漸 喜；
進至 dm#dm03147@成都 ，
見 rm#r00914@旰 ，
但接以温恭，
無一言責其干紀，
州府事悉以委 rm#r00914@旰 。

又數薦之於朝，
因請以節制讓 rm#r00914@旰 ，
以 rm#xjts22355@柏茂琳 、 rm#xjts23016@楊子琳 、 rm@李昌巎 各爲本州刺史。

上不得已從之。

壬寅，
以 rm#r00914@旰 爲 dm#dm03147@成都 尹、 dm#dm07316@西川 節度行軍司馬。
日與將佐高會
# p 

甲辰，
以 rm#r04309@魚朝恩 行内侍監、判國子監事。

中書舍人 dm#dm00427@京兆  rm@常袞 上言：
「成均之任，
當用名儒，
不宜以宦者領之。」

丁未，
命宰相以下送 rm#r04309@朝恩 上。

# p 

 dm#dm00427@京兆 尹 rm#r04338@黎幹 自 dm#dm00975@南山 引澗水穿漕渠入 dm#dm08170@長安 ，
功竟不成。
# p 

冬，
十月，
乙未，
上生日，
諸道節度使獻金帛、器服、珍玩、駿馬爲壽，
共直緡錢二十四萬。

 rm@常袞 上言，
以爲：
「節度使非能男耕女織，
必取之於人。

斂怨求媚，
不可長也。

請卻之。」

上不聽。
# p 

 dm#dm00427@京兆 尹 rm#r03064@第五琦 什一税法，
民苦其重，
多流亡。

十一月，
甲子，
日南至，
赦，
改元，
悉停什一税法。

# p 

十二月，
癸卯，
 rm#r00462@周智光 殺 dm#dm08316@陜州 監軍 rm#xjts04694@張志斌 。

 rm#r00462@智光 素與 dm#dm08316@陜州 刺史 rm#xjts10061@皇甫温 不協，
 rm#xjts04694@志斌 入奏事，
 rm#r00462@智光 館之，
 rm#xjts04694@志斌 責其部下不肅，
 rm#r00462@智光 怒曰：
「 rm#r00144@僕固懷恩 不反，
正由汝輩激之。

我亦不反，
今日爲汝反矣！」

叱下斬之，
臠食其肉。

朝士舉選人，
畏 rm#r00462@智光 之暴，
多自 dm#dm01227@同州 竊過，
 rm#r00462@智光 遣將將兵邀之於路，
死者甚衆。

戊申，
詔加 rm#r00462@智光 檢校左僕射，
遣中使 rm#xjts27244@餘元仙 持告身授之。

 rm#r00462@智光 慢罵曰：
「 rm#r00462@智光 有大功於天下國家，
不與平章事而與僕射！

且 dm#dm01227@同 、 dm#dm06927@華 地狹，
不足展材，
若益以 dm#dm08315@陜 、 dm#dm07186@虢 、 dm#dm01376@商 、 dm#dm07920@鄜 、 dm#dm01476@坊 五州，
庶猶可耳。」

因歴數大臣過失，
且曰：
「此去 dm#dm08170@長安 百八十里，
 rm#r00462@智光 夜眠不敢舒足，
恐踏破 dm#dm08170@長安 城，
至於挾天子令諸侯，
惟 rm#r00462@周智光 能之。」

 rm#xjts27244@元仙 股慄。

 rm#xjts01384@郭子儀 屡請討 rm#r00462@智光 ，
上不許。
# p 

 rm#xjts01384@郭子儀 以 dm#dm04651@河中 軍食常乏，
乃自耕百畝，
將校以是爲差，
於是士卒皆不勸而耕。

 y@是歳 ，
 dm#dm04651@河中 野無曠土，
軍有餘糧。

# p 

以 dm#dm08458@隴右 行軍司馬 rm#r03921@陳少遊 爲 dm#dm04008@桂管 觀察使。

 rm#r03921@少遊 ，
 dm#dm01088@博州 人也，
爲吏強敏而好賄，
善結權貴，
以是得進。

既得 dm#dm04001@桂州 ，
惡其道遠多瘴癘；
宦官 rm#r06744@董秀 掌樞密，
 rm#r03921@少遊 請歳獻五萬緡，
又納賄於 rm#r00165@元載 子 rm#xjts03362@仲武 。

内外引薦，
數日，
改 dm#dm02224@宣歙 觀察使。

*** 二年
# year 0767
# p 

春，
正月，
丁巳，
密詔 rm#xjts01384@郭子儀 討 rm#r00462@周智光 ，
 rm#xjts01384@子儀 命大將 rm#r02462@渾瑊 、 rm#r01775@李懷光 軍于 dm#dm05102@渭 上；
 rm#r00462@智光 麾下聞之，
皆有離心。

己未，
 rm#r00462@智光 大將 rm#xjts15879@李漢惠 自 dm#dm01227@同州 帥所部降於 rm#xjts01384@子儀 。

壬戌，
貶 rm#r00462@智光  dm#dm05403@澧州 刺史。

甲子，
 dm#dm06938@華州 牙將 rm#xjts19637@姚懷 、 rm#xjts13679@李延俊 殺 rm#r00462@智光 ，
以其首來獻。
# p 

 dm#dm05005@淮西 節度使 rm#r03193@李忠臣 入朝，
以收 dm#dm06938@華州 爲名，
帥所部兵大掠，
自 dm#dm05384@潼關 至 dm#dm07587@赤水 二百里間，
財畜殆盡，
官吏有衣紙或數日不食者。

己巳，
置 dm#dm05384@潼關 鎭兵二千人。
# p 

壬申，
分 dm#dm00785@劍南 置 dm#dm03818@東川 觀察使，
鎭 dm#dm07730@遂州 。

# p 

二月，
丙戌，
 rm#xjts01384@郭子儀 入朝。

上命 rm#r00165@元載 、 rm#r02687@王縉 、 rm#r04309@魚朝恩 等互置酒於其第，
一會之費至十萬緡。

上禮重 rm#xjts01384@子儀 ，
常謂之大臣而不名。
# p 

 rm#xjts01532@郭曖 嘗與 rm#r03705@昇平公主 爭言，
 rm#xjts01532@曖 曰：
「汝倚乃父爲天子邪？
我父薄天子不爲！」

公主恚，
奔車奏之。

上曰：
「此非汝所知。

彼誠如是，
使彼欲爲天子，
天下豈汝家所有邪！」

慰諭令歸。

 rm#xjts01384@子儀 聞之，
囚 rm#xjts01532@曖 ，
入待罪。

上曰：
「鄙諺有之：
『不癡不聾，
不作家翁。』

兒女子閨房之言，
何足聽也！」

 rm#xjts01384@子儀 歸，
杖 rm#xjts01532@曖 數十。
# p 

夏，
四月，
庚子，
命宰相、 rm#r04309@魚朝恩 與吐蕃盟于 dm#dm06760@興唐寺 。

# p 

 rm#r02067@杜鴻漸 請入朝奏事，
以 rm#r00914@崔旰 知 dm#dm07316@西川 留後。

六月，
甲戌，
 rm#r02067@鴻漸 來自 dm#dm03147@成都 ，
廣爲貢獻，
因盛陳利害，
薦 rm#r00914@旰 才堪寄任；
上亦務姑息，
乃留 rm#r00914@鴻漸 復知政事。

秋，
七月，
丙寅，
以 rm#r00914@旰 爲 dm#dm07316@西川 節度使，
 rm#xjts21955@杜濟 爲 dm#dm03818@東川 節度使。

 rm#r00914@旰 厚斂以賂權貴，
 rm#r00165@元載 擢 rm#r00914@旰 弟 rm@寛 至御史中丞，
 rm@寛 兄 rm@審 至給事中。
# p 

丁卯，
 rm#r04309@魚朝恩 奏以先所賜莊爲 dm#dm06344@章敬寺 ，
以資 rm#r03056@章敬太后 冥福，
於是窮壯極麗，
盡都市之財不足用，
奏毀 dm#dm03617@曲江 及 dm#dm06942@華清宮 館以給之，
費逾萬億。

 dm#dm00029@衞州 進士 rm#xjts00338@高郢 上書，
略曰：
「先太后聖徳，
不必以一寺増輝；
國家永圖，
無寧以百姓爲本。

捨人就寺，
何福之爲！」

又曰：
「無寺猶可，
無人其可乎！」

又曰：
「陛下當卑宮室，
以 rm#rt0008@夏禹 爲法，
而崇塔廟踵 rm#r03249@梁武 之風乎！」

又上書，
略曰：
「古之明王積善以致福，
不費財以求福；
脩徳以消禍，
不勞人以禳禍。

今興造急促，
晝夜不息，
力不逮者隨以榜笞，
愁痛之聲盈於道路，
以此望福，
臣恐不然。」

又曰：
「陛下迴正道於内心，
求微助於外物，
徇左右之過計，
傷皇王之大猷，
臣竊爲陛下惜之！」

皆寢不報。

# p 

始，
上好祠祀，
未甚重佛。

 rm#r00165@元載 、 rm#r02687@王縉 、 rm#r02067@杜鴻漸 爲相，
三人皆好佛；
 rm#r02687@縉 尤甚，
不食葷血，
與 rm#r02067@鴻漸 造寺無窮。

上嘗問以「佛言報應，
果爲有無？」
 rm#r00165@載 等奏以：
「國家運祚靈長，
非宿植福業，
何以致之！

福業已定，
雖時有小災，
終不能爲害，
所以 rm#r00793@安 、 rm#xjts23917@史 悖逆方熾而皆有子禍；
 rm#r00144@僕固懷恩 稱兵内侮，
出門病死；
囘紇、吐蕃大舉深入，
不戰而退：
此皆非人力所及，
豈得言無報應也！」

上由是深信之，
常於禁中飯僧百餘人；
有寇至則令僧講仁王經以禳之，
寇去則厚加賞賜。

胡僧 rm#r00026@不空 ，
官至卿監，
爵爲國公，
出入禁闥，
勢移權貴，
 dm#dm00444@京畿 良田美利多歸僧寺。

敕天下無得箠曳僧尼。

造 dm#dm08061@金閣寺 於 dm#dm00395@五臺山 ，
鑄銅塗金爲瓦，
所費鉅億；
縉給中書符牒，
令 dm#dm00394@五臺 僧數十人散之四方，
求利以營之。

 rm#r00165@載 等毎侍上從容，
多談佛事，
由是中外臣民承流相化，
皆廢人事而奉佛，
政刑日紊矣。

# p 

八月，
庚辰，
 dm#dm09004@鳳翔 等道節度使、左僕射、平章事 rm#r00795@李抱玉 入朝，
固讓僕射，
言辭確至，
上許之；
癸丑，
又讓 dm#dm09004@鳳翔 節度使，
不許。
# p 

丁酉，
 rm#r02067@杜鴻漸 飯千僧，
以使 dm#dm07197@蜀 無恙故也。

# p 

九月，
吐蕃衆數萬圍 dm#dm08619@靈州 ，
遊騎至 dm#dm05344@潘原 、 dm#dm02186@宜祿 ；
詔 rm#xjts01384@郭子儀 自 dm#dm04651@河中 帥甲士三萬鎭 dm#dm04928@涇陽 ，
 dm#dm08170@京師 戒嚴。

甲子，
 rm#xjts01384@子儀 移鎭 dm#dm01853@奉天 。

# p 

山獠陷 dm#dm04001@桂州 ，
逐刺史 rm@李良 。

# p 

冬，
十月，
戊寅，
 dm#dm03677@朔方 節度使 rm#xjts24772@路嗣恭 破吐蕃於 dm#dm08619@靈州 城下，
斬首二千餘級；
吐蕃引去。
# p 

十二月，
庚辰，
盜發 rm#xjts01384@郭子儀 父冢，
捕之，
不獲。

人以爲 rm#r04309@魚朝恩 素惡 rm#xjts01384@子儀 ，
疑其使之。

 rm#xjts01384@子儀 自 dm#dm01853@奉天 入朝，
朝廷憂其爲變；
 rm#xjts01384@子儀 見上，
上語及之，
 rm#xjts01384@子儀 流涕曰：
「臣久將兵，
不能禁暴，
軍士多發人冢。

今日及此，
乃天譴，
非人事也。」

朝廷乃安。
# p 

 y@是歳 ，
復以 dm#dm08135@鎭西 爲 dm#dm02061@安西 。


# p 

 rm#xjts27042@新羅王憲英 卒，
子 rm#xjts27059@乾運 立。
*** 三年
# year 0768
# p 

春，
正月，
乙丑，
上幸 dm#dm06344@章敬寺 ，
度僧尼千人。
# p 

贈 rm#r01077@建寧王倓 爲 rm#r01077@齊王 。

# p 

二月，
癸巳，
 dm#dm01379@商州 兵馬使 rm#r00292@劉洽 殺防禦使 rm#xjts10499@殷仲卿 ，
尋討平之。
# p 

甲午，
 rm#xjts01384@郭子儀 禁無故軍中走馬。

 rm@南陽夫人 乳母之子犯禁，
都虞候杖殺之。

諸子泣訴於 rm#xjts01384@子儀 ，
且言都虞候之横，
 rm#xjts01384@子儀 叱遣之。

明日，
以事語僚佐而歎息曰：
「 rm#xjts01384@子儀 諸子，
皆奴材也。

不賞父之都虞候而惜母之乳母子，
非奴材而何！」

# p 

庚子，
以後宮 rm@獨孤氏 爲貴𡚱。
# p 

三月，
乙巳朔，
日有食之。
# p 

夏，
四月，
戊寅，
 dm#dm02401@山南西道 節度使 rm#r01213@張獻誠 ，
以疾舉從父弟右羽林將軍 rm#r01212@獻恭 自代，
上許之。
# p 

壬寅，
 dm#dm07316@西川 節度使 rm#r00914@崔旰 入朝。
# p 

初，
上遣中使徵 rm@李泌 於 dm#dm07225@衡山 ，
既至，
復賜金紫，
爲之作書院於 dm#dm07069@蓬莱殿 側，
上時衣汗衫、躡屨過之，
自給、舍以上及方鎭除拜、軍國大事，
皆與之議。

又使 rm#r04309@魚朝恩 於 dm#dm05916@白花屯 爲 rm@泌 作外院，
使與親舊相見。
# p 

上欲以 rm@泌 爲門下侍郎、同平章事，
 rm@泌 固辭。

上曰：
「機務之煩，
不得晨夕相見，
誠不若且居密近，
何必署敕然後爲宰相邪！」

後因端午，
王、公、𡚱、主各獻服玩，
上謂 rm@泌 曰：
「先生何獨無所獻？」
對曰：
「臣居禁中，
自巾至履皆陛下所賜，
所餘惟一身耳，
何以爲獻！」

上曰：
「朕所求正在此耳。」

 rm@泌 曰：
「臣身非陛下有，
誰則有之？」
上曰：
「先帝欲以宰相屈卿而不能得，
自今既獻其身，
當惟朕所爲，
不爲卿有矣！」

 rm@泌 曰：
「陛下欲使臣何爲？」
上曰：
「朕欲卿食酒肉，
有室家，
受祿位，
爲俗人。

」
 rm@泌 泣曰：
「臣絶粒二十餘年，
陛下何必使臣隳其志乎！」

上曰：
「泣復何益！

卿在九重之中，
欲何之？」
乃命中使爲 rm@泌 葬二親，
又爲 rm@泌 娶 rm@盧氏 女爲妻，
資費皆出縣官。

賜第於 dm#dm00654@光福坊 ，
令 rm@泌 數日宿第中，
數日宿 dm#dm07071@蓬莱院 。
# p 

上與 rm@泌 語及 rm#r01077@齊王倓 ，
欲厚加褒贈，
 rm@泌 請用 rm#r03770@岐 、 rm#r03598@薛 故事贈太子，
上泣曰：
「吾弟首建 dm#dm08626@靈武 之議，
成中興之業，
 rm#r03770@岐 、 rm#r03598@薛 豈有此功乎！

竭誠忠孝，
乃爲讒人所害。

曏使尚存，
朕必以爲太弟。

今當崇以帝號，
成吾夙志。」

乙卯制，
追諡 rm#r01077@倓 曰 rm#r01077@承天皇帝 ；
庚申，
葬 dm#dm08748@順陵 。

# p 

 rm#r00914@崔旰 之入朝也，
以弟 rm@寛 爲留後，
 dm#dm05469@瀘州 刺史 rm#xjts23016@楊子琳 帥精騎數千乘虚突入 dm#dm03147@成都 ；
朝廷聞之，
加 rm#r00914@旰 檢校工部尚書，
賜名 rm#r00914@寧 ，
遣還鎭。
# p 

六月，
壬辰，
 dm#dm02689@幽州 兵馬使 rm#xjts09851@朱希彩 、經略副使 dm#dm03464@昌平  rm#r01577@朱泚 、 rm#r01577@泚 弟 rm#r01579@滔 共殺節度使 rm#r01773@李懷仙 ，
 rm#xjts09851@希彩 自稱留後。

閏月，
 dm#dm03140@成徳軍 節度使 rm#r01157@李寶臣 遣將將兵討 rm#xjts09851@希彩 ，
爲 rm#xjts09851@希彩 所敗；
朝廷不得已宥之。

庚申，
以 rm#r02687@王縉 領 dm#dm06013@盧龍 節度使；
丁卯，
以 rm#xjts09851@希彩 領 dm#dm02689@幽州 留後。領知
# p 

 rm#xjts08759@崔寛 與 rm#xjts23016@楊子琳 戰，
數不利，
秋，
七月，
 rm#r00914@崔寧 妾 rm#xjts08146@任氏 出家財數十萬，
募兵得數千人，
帥以撃 rm#xjts23016@子琳 ，
破之；
 rm#xjts23016@子琳 走。
# p 

乙亥，
 rm#r02687@王縉 如 dm#dm02689@幽州 ，
 rm#xjts09851@朱希彩 盛兵嚴備以逆之。

 rm#r02687@縉 晏然而行，
 rm#xjts09851@希彩 迎謁甚恭。

 rm#r02687@縉 度終不可制，
勞軍，
旬餘日而還。

# p 

囘紇可敦卒，
庚辰，
以右散騎常侍 rm#r03245@蕭昕 爲弔祭使。

囘紇庭詰 rm#r03245@昕 曰：
「我於 dyn#ch100@唐 有大功，
 dyn#ch100@唐 奈何失信，
市我馬，
不時歸其直？」
 rm#r03245@昕 曰：
「囘紇之功，
 dyn#ch100@唐 已報之矣。

 rm#r00144@僕固懷恩 之叛，
囘紇助之，
與吐蕃連兵入寇，
逼我郊畿。

及 rm#r00144@懷恩 死，
吐蕃走，
然後囘紇懼而請和，
我 dyn#ch100@唐 不忘前功，
加惠而縱之。

不然，
匹馬不歸矣。

乃囘紇負約，
豈 dyn#ch100@唐 失信邪！」

囘紇慙，
厚禮而歸之。
# p 

丙戌，
内出盂蘭盆賜 dm#dm06344@章敬寺 。

設七廟神座，
書尊號於旛上，
百官迎謁於 dm#dm00660@光順門 。

自 y@是歳 以爲常。
# p 

八月，
壬戌，
吐蕃十萬衆寇 dm#dm08626@靈武 。

丁卯，
吐蕃尚贊摩二萬衆寇 dm#dm07812@邠州 ，
 dm#dm08170@京師 戒嚴；
 dm#dm07810@邠寧 節度使 rm#r04182@馬璘 撃破之。

# p 

庚午，
 dm#dm04672@河東 節度使、同平章事 rm#r03665@辛雲京 薨，
以 rm#r02687@王縉 領 dm#dm04672@河東 節度使，
餘如故。
# p 

九月，
壬申，
命 rm#xjts01384@郭子儀 將兵五萬屯 dm#dm01853@奉天 以備吐蕃。

# p 

丁丑，
 rm#r02525@濟王環 薨。

# p 

壬午，
 dm#dm03677@朔方 騎將 rm#r02845@白元光 撃吐蕃，
破之。

壬辰，
 rm#r02845@元光 又破吐蕃二萬衆於 dm#dm08626@靈武 。

 dm#dm09004@鳳翔 節度使 rm#r00795@李抱玉 使右軍都將 dm#dm06688@臨洮  rm@李晟 將兵五千撃吐蕃，
 rm@晟 曰：
「以力則五千不足用；
以謀則太多。」

乃將千人出 dm#dm01701@大震關 ；
至 dm#dm06688@臨洮 ，
屠吐蕃 dm#dm02138@定秦堡 ，
焚其積聚，
虜堡帥慕容谷種而還。

吐蕃聞之，
釋 dm#dm08619@靈州 之圍而去。

戊戌，
 dm#dm08170@京師 解嚴。兼行
# p 

 dm#dm05334@潁州 刺史 rm@李岵 以事忤 dm#dm05226@滑亳 節度使 rm#r00071@令狐彰 ，
 rm#r00071@彰 使節度判官 rm#xjts19584@姚奭 按行 dm#dm05334@潁州 ，
因代 rm@岵 領州事，
且曰：
「 rm@岵 不受代，
即殺之。」

 rm@岵 知之，
因激怒將士，
使殺 rm#xjts19584@奭 ，
與 rm#xjts19584@奭 同死者百餘人。

 rm@岵 走依 dm#dm04660@河南 節度使 rm#r02827@田神功 於 dm#dm04541@汴州 。

冬，
十月，
乙巳，
 rm#r00071@彰 表言其状，
 rm@岵 亦上表自理。

上命給事中 rm@賀若察 往按之。

# p 

丁卯，
 rm#xjts01384@郭子儀 自 dm#dm01853@奉天 入朝。


# p 

十一月，
丁亥，
以 dm#dm02689@幽州 留後 rm#xjts09851@朱希彩 爲節度使。

# p 

 rm#xjts01384@郭子儀 還 dm#dm04651@河中 。

 rm#r00165@元載 以吐蕃連歳入寇，
 rm#r04182@馬璘 以 dm#dm01437@四鎭 兵屯 dm#dm07810@邠寧 ，
力不能拒，
而 rm#xjts01384@郭子儀 以 dm#dm03677@朔方 重兵鎭 dm#dm04651@河中 ，
深居腹中無事之地，
乃與 rm#xjts01384@子儀 及諸將議，
徙 rm#r04182@璘 鎭 dm#dm04924@涇州 ，
而使 rm#xjts01384@子儀 以 dm#dm03677@朔方 兵鎭 dm#dm07812@邠州 ，
曰：
「若以邊土荒殘，
軍費不給，
則以内地租税及運金帛以助之。」

諸將皆以爲然。

十二月，
己酉，
徙 rm#r04182@馬璘 爲 dm#dm04920@涇原 節度使，
以 dm#dm07808@邠 、 dm#dm02291@寧 、 dm#dm03083@慶 三州隸 dm#dm03677@朔方 。

 rm#r04182@璘 先往城 dm#dm04924@涇州 ，
以都虞候 rm#r02349@段秀實 知 dm#dm07812@邠州 留後。

# p 

初，
 dm#dm01437@四鎭 、 dm#dm00860@北庭 兵遠赴中原之難，
久羈旅，
數遷徙，
 dm#dm01437@四鎭 歴 dm#dm04537@汴 、 dm#dm07186@虢 、 dm#dm09004@鳳翔 ，
 dm#dm00860@北庭 歴 dm#dm03102@懷 、 dm#dm06430@絳 、 dm#dm07920@鄜 然後至 dm#dm07808@邠 ，
頗積勞弊。

及徙 dm#dm04924@涇州 ，
衆皆怨誹。

刀斧兵馬使 rm#xjts01852@王童之 謀作亂，
期以辛酉旦警嚴而發。

前夕，
有告之者；
 rm#r02349@秀實 陽召掌漏者，
怒之，
以其失節，
令毎更來白，
輒延之數刻，
遂四更而曙，
 rm#xjts01852@童之 不果發。

 rm#r02349@秀實 欲討之而亂迹未露，
恐軍中疑其冤。

告者又云，
「今夕欲焚馬坊草，
因救火謀作亂。

」
中夕，
火果起，
 rm#r02349@秀實 命軍中行者皆止，
坐者勿起，
各整部伍，
嚴守要害。

 rm#xjts01852@童之 白請救火，
不許。

及旦，
捕 rm#xjts01852@童之 及其黨八人，
皆斬之。

下令曰：
「後徙者族，
流言者刑！」

遂徙于 dm#dm04919@涇 。

# p 

癸亥，
 dm#dm07316@西川 破吐蕃萬餘衆。

# p 

 dm#dm02660@平盧 行軍司馬 rm#xjts01781@許杲 將卒三千人駐 dm#dm05450@濠州 不去，
有窺 dm#dm04984@淮南 意，
 dm#dm04984@淮南 節度使 rm#r00908@崔圓 令副使 dm#dm00634@元城  rm#r01242@張萬福 攝 dm#dm05450@濠州 刺史；
 rm#xjts01781@杲 聞，
即提卒去，
止 dm#dm05847@當塗 。

 y@是歳 ，
上召 rm#r01242@萬福 ，
以爲 dm#dm01327@和州 刺史、行營防禦使，
討 rm#xjts01781@杲 。

 rm#r01242@萬福 至州，
 rm#xjts01781@杲 懼，
移軍 dm#dm00156@上元 ，
又北至 dm#dm04089@楚州 大掠，
 dm#dm04984@淮南 節度使 rm#r04008@韋元甫 命 rm#r01242@萬福 追討之；
未至 dm#dm05006@淮陰 ，
 rm#xjts01781@杲 爲其將 rm#xjts00425@康自勸 所逐。

 rm#xjts00425@自勸 擁兵繼掠，
循 dm#dm04981@淮 而東，
 rm#r01242@萬福 倍道追而殺之，
免者什二三。

 rm#r04008@元甫 將厚賞將士，
 rm#r01242@萬福 曰：
「官健常虚費衣糧，
無所事。

今方立小功，
不足過賞，
請用三分之一。」

*** 四年
# year 0769
# p 

春，
正月，
丙子，
 rm#xjts01384@郭子儀 入朝，
 rm#r04309@魚朝恩 邀之遊 dm#dm06344@章敬寺 。

 rm#r00165@元載 恐其相結，
密使 rm#xjts01384@子儀 軍吏告 rm#xjts01384@子儀 曰：
「 rm#r04309@朝恩 謀不利於公。」

 rm#xjts01384@子儀 不聽。

吏亦告諸將，
將士請衷甲以從者三百人。

 rm#xjts01384@子儀 曰：
「我，
國之大臣，
彼無天子之命，
安敢害我！

若受命而來，
汝曹欲何爲！」

乃從家僮數人而往。

 rm#r04309@朝恩 迎之，
驚其從者之約。

 rm#xjts01384@子儀 以所聞告，
且曰：
「恐煩公經營耳。」

 rm#r04309@朝恩 撫膺捧手流涕曰：
「非公長者，
能無疑乎！」


# p 

壬午，
流 rm@李岵 於 dm#dm01831@夷州 。

# p 

乙酉，
 rm#xjts01384@郭子儀 還 dm#dm04651@河中 。

# p 

辛卯，
賜 rm@李岵 死。
# p 

二月，
壬寅，
以 dm#dm00427@京兆 之好畤、 dm#dm09004@鳳翔 之 dm#dm09098@麟遊 、 dm#dm03584@普潤 隸神策軍，
從 rm#r04309@魚朝恩 之請也。
# p 

 rm#xjts23016@楊子琳 既敗還 dm#dm05469@瀘州 ，
招聚亡命，
得數千人，
沿江東下，
聲言入朝；
 dm#dm04938@涪州 守捉使 rm#xjts02443@王守仙 伏兵 dm#dm09145@黄草峽 ，
 rm#xjts23016@子琳 悉擒之，
撃 rm#xjts02443@守仙 於 dm#dm02991@忠州 ，
 rm#xjts02443@守仙 僅以身免。

 rm#xjts23016@子琳 遂殺 dm#dm01550@夔州 別駕 rm#xjts04872@張忠 ，
據其城。

 dm#dm06881@荊南 節度使 rm#r00001@衞伯玉 欲結以爲援，
以 dm#dm01550@夔州 許之，
爲之請於朝。

 dm#dm08406@陽曲 人 rm#r00272@劉昌裔 説 rm#xjts23016@子琳 遣使詣闕請罪，
 rm#xjts23016@子琳 從之。

乙巳，
以 rm#xjts23016@子琳 爲 dm#dm02449@峽州 團練使。


# p 

初，
 rm#r00144@僕固懷恩 死，
上憐其有功，
置其女宮中，
養以爲女。

囘紇請以爲可敦，
夏，
五月，
辛卯，
册爲 rm#xjts09428@崇徽公主 ，
嫁囘紇可汗。

壬辰，
遣兵部侍郎 rm#r01844@李涵 送之，
 rm@涵 奏祠部郎中 dm#dm07185@虞郷  rm#r03191@董晉 爲判官。

六月，
丁酉，
公主辭行，
至囘紇牙帳。

囘紇來言曰：
「 dyn#ch100@唐 約我爲市馬，
既入，
而歸我賄不足，
我於使人乎取之。」

 rm@涵 懼，
不敢對，
視 rm#r03191@晉 ，
 rm#r03191@晉 曰：
「吾非無馬而與爾爲市，
爲爾賜不既多乎！

爾之馬歳至，
吾數皮而歸資，
邊吏請致詰也。

天子念爾有勞，
故下詔禁侵犯。

諸戎畏我大國之爾與也，
莫敢校焉。

爾之父子寧而畜馬蕃者，
非我誰使之！」

於是其衆皆環 rm#r03191@晉 拜。

既又相帥南面序拜，
皆舉兩手曰：
「不敢有意大國。」


# p 

戊申，
 rm#r02687@王縉 表讓副元帥、都統、行營使。

許之
# p 

辛酉，
 rm#xjts01384@郭子儀 自 dm#dm04651@河中 遷于 dm#dm07812@邠州 ，
其精兵皆自隨，
餘兵使裨將將之，
分守 dm#dm04651@河中 、 dm#dm08619@靈州 。

軍士久家 dm#dm04651@河中 ，
頗不樂徙，
往往自 dm#dm07808@邠 逃歸；
行軍司馬 rm#r00575@嚴郢 領留府，
悉捕得，
誅其渠帥，
衆心乃定。

# p 

秋，
九月，
吐蕃寇 dm#dm08619@靈州 ；
丁丑，
 dm#dm03677@朔方 留後 rm#xjts28791@常謙光 撃破之。
# p 

 dm#dm04672@河東 兵馬使 rm#xjts03114@王無縱 、 rm#r05259@張奉璋 等恃功驕蹇，
以 rm#r02687@王縉 書生，
易之，
多違約束。

 rm#r02687@縉 受詔發兵詣 dm#dm09056@鹽州 防秋，
遣 rm#xjts03114@無縱 、 rm#r05259@奉璋 將歩騎三千赴之。

 rm#r05259@奉璋 逗遛不進，
 rm#xjts03114@無縱 托他事入 dm#dm01774@太原 城；
 rm#r02687@縉 悉擒斬之，
幷其黨七人，
諸將悍戾者殆盡，
軍府始安。
# p 

冬，
十月，
 rm#xjts28791@常謙光 奏吐蕃寇 dm#dm01406@嗚沙 ，
首尾四十里。

 rm#xjts01384@郭子儀 遣兵馬使 rm#r02462@渾瑊 將鋭兵五千救 dm#dm08619@靈州 ，
 rm#xjts01384@子儀 自將進至 dm#dm03083@慶州 ，
聞吐蕃退，
乃還。

# p 

黄門侍郎、同平章事 rm#r02067@杜鴻漸 以疾辭位，
壬申，
許之；
乙亥，
薨。

 rm#r02067@鴻漸 病甚，
令僧削髮，
遺令爲塔以葬。

# p 

丙子，
以左僕射 rm#r03411@裴冕 同平章事。

初，
 rm#r00165@元載 爲 dm#dm03346@新平 尉，
 rm#r03411@冕 嘗薦之，
故 rm#r00165@載 舉以爲相，
亦利其老病易制。

受命之際，
蹈舞仆地，
 rm#r00165@載 趨而扶之，
代爲謝詞。

十二月，
戊戌，
 rm#r03411@冕 薨。
*** 五年
# year 0770
# p 

春，
正月，
己巳，
羌酋白對蓬等各帥部落内屬。

# p 

觀軍容宣慰處置使、左監門衞大將軍兼神策軍使、内侍監 rm#r04309@魚朝恩 ，
專典禁兵，
寵任無比，
上常與議軍國事，
勢傾朝野。

 rm#r04309@朝恩 好於廣座恣談時政，
陵侮宰相，
 rm#r00165@元載 雖強辯，
亦拱默不敢應。
# p 

神策都虞候 rm#r00237@劉希暹 ，
都知兵馬使 rm#xjts02815@王駕鶴 ，
皆有寵於 rm#r04309@朝恩 ；
 rm#r00237@希暹 説 rm#r04309@朝恩 於北軍置獄，
使坊市惡少年羅告富室，
誣以罪惡，
捕繋地牢，
訊掠取服，
籍沒其家貲入軍，
幷分賞告捕者；
地在禁密，
人莫敢言。

 rm#r04309@朝恩 毎奏事，
以必允爲期；
朝廷政事有不豫者，
輒怒曰：
「天下事有不由我者邪！」

上聞之，
由是不懌。
# p 

 rm#r04309@朝恩 養子 rm#xjts10620@令徽 尚幼，
爲内給使，
衣緑，
與同列忿爭，
歸告 rm#r04309@朝恩 。

 rm#r04309@朝恩 明日見上曰：
「臣子官卑，
爲儕輩所陵，
乞賜之紫衣。」

上未應，
有司已執紫衣於前，
 rm#xjts10620@令徽 服之，
拜謝。

上強笑曰：
「兒服紫，
大宜稱心。」


# p 

 rm#r00165@元載 測知上指，
乘間奏 rm#r04309@朝恩 專恣不軌，
間，
古莧翻。

請除之；
上亦知天下共怨怒，
遂令 rm#r00165@載 爲方略。

 rm#r04309@朝恩 毎入殿，
常使射生將 rm#xjts26599@周皓 將百人自衞，
又使其黨 dm#dm08320@陝州 節度使 rm#xjts10061@皇甫温 握兵於外以爲援；
 rm#r00165@載 皆以重賂結之，
故 rm#r04309@朝恩 陰謀密語，
上一一聞之，
而 rm#r04309@朝恩 不之覺也。
# p 

辛卯，
 rm#r00165@載 爲上謀，
徙 rm#r00795@李抱玉 爲 dm#dm02401@山南西道 節度使，
以 rm#xjts10061@温 爲 dm#dm09004@鳳翔 節度使，
外重其權，
實内 rm#xjts10061@温 以自助也。

 rm#r00165@載 又請割 dm#dm07888@郿 、 dm#dm07186@虢 、 dm#dm02321@寶雞 、 dm#dm07933@鄠 、 dm#dm06019@盩厔 隸 rm#r00795@抱玉 ，
 dm#dm06772@興平 、 dm#dm04228@武功 、 dm#dm01753@天興 、 dm#dm03177@扶風 隸神策軍，
 rm#r04309@朝恩 喜於得地，
殊不以 rm#r00165@載 爲虞，
驕横如故。

# p 

壬辰，
加 dm#dm04660@河南 尹 rm#r01145@張延賞 爲 dm#dm03788@東京 留守；
罷 dm#dm04660@河南 等道副元帥，
以其兵屬留守。

 rm#r01145@延賞 ，
 rm#r01126@嘉貞 之子也。

# p 

二月，
戊戌，
 rm#r00795@李抱玉 徙鎭 dm#dm06019@盩厔 ，
軍士憤怒，
大掠 dm#dm09004@鳳翔 坊市，
數日乃定。
# p 

 rm#r00237@劉希暹 頗覺上意異，
以告 rm#r04309@魚朝恩 ，
 rm#r04309@朝恩 始疑懼。

然上毎見之，
恩禮益隆，
 rm#r04309@朝恩 亦以此自安。

 rm#xjts10061@皇甫温 至 dm#dm08170@京師 ，
 rm#r00165@元載 留之未遣，
因與 rm#xjts10061@温 及 rm#xjts26599@周皓 密謀誅 rm#r04309@朝恩 。

既定計，
 rm#r00165@載 白上。

上曰：
「善圖之，
勿反受禍！」

# p 

三月，
癸酉，
寒食，
上置酒宴貴近於禁中，
 rm#r00165@載 守中書省。

宴罷，
 rm#r04309@朝恩 將還營，
上留之議事，
因責其異圖。

 rm#r04309@朝恩 自辯，
語頗悖慢，
 rm#xjts26599@皓 與左右擒而縊殺之，
外無知者。

上下詔，
罷 rm#r04309@朝恩 觀軍容等使，
内侍監如故。

詐云「 rm#r04309@朝恩 受詔乃自縊」，
以尸還其家，
賜錢六百萬以葬。
# p 

丁丑，
加 rm#r00237@劉希暹 、 rm#xjts02815@王駕鶴 御史中丞，
以慰安北軍之心。

丙戌，
赦 dm#dm00444@京畿 繋囚，
命盡釋 rm#r04309@朝恩 黨與，
且曰：
「北軍將士，
皆朕爪牙，
竝宜仍舊。

朕今親御禁旅，
勿有憂懼。」

# p 

己丑，
罷度支使及 dm#dm08283@關内 等道轉運、常平、鹽鐵使，
其度支事委宰相領之。

# p 

敕 rm#xjts10061@皇甫温 還鎭于 dm#dm08318@陝 。

# p 

 rm#r00165@元載 既誅 rm#r04309@魚朝恩 ，
上寵任益厚，
 rm#r00165@載 遂志氣驕溢；
毎衆中大言，
自謂有文武才略，
古今莫及，
弄權舞智，
政以賄成，
僭侈無度。

吏部侍郎 rm#r02239@楊綰 ，
典選平允，
性介直，
不附 rm#r00165@載 ；
 dm#dm02527@嶺南 節度使 rm#r01319@徐浩 ，
貪而佞，
傾南方珍貨以賂 rm#r00165@載 。

 rm#r00165@載 以 rm#r02239@綰 爲國子祭酒，
引 rm#r01319@浩 代之。

 rm#r01319@浩 ，
 dm#dm07613@越州 人也。

 rm#r00165@載 有丈人自 dm#dm02214@宣州 來，
從 rm#r00165@載 求官，
 rm#r00165@載 度其人不足任事，
但贈 dm#dm04656@河北 一書而遣之。

丈人不悦，
行至 dm#dm02689@幽州 ，
私發書視之，
書無一言，
惟署名而已。

丈人大怒，
不得已試謁院僚，
判官聞有 rm#r00165@載 書，
大驚，
立白節度使，
遣大校以箱受書，
館之上舍，
留宴數日，
辭去，
贈絹千匹。

其威權動人如此。辛卯
# p 

夏，
四月，
庚子，
 dm#dm05139@湖南 兵馬使 rm#xjts09517@臧玠 殺觀察使 rm#xjts08838@崔灌 ；
 dm#dm05403@澧州 刺史 rm#xjts23016@楊子琳 起兵討之，
取賂而還。

# p 

 dm#dm04920@涇原 節度使 rm#r04182@馬璘 屡訴本鎭荒殘，
無以贍軍，
上諷 rm#r00795@李抱玉 以 dm#dm07947@鄭 、 dm#dm05327@潁 二州讓之；
乙巳，
以 rm#r04182@璘 兼 dm#dm07951@鄭潁 節度使。
# p 

庚申，
 rm#r02687@王縉 自 dm#dm01774@太原 入朝。

# p 

癸未，
以左羽林大將軍 rm#r03659@辛京杲 爲 dm#dm05139@湖南 觀察使。
# p 

 dm#dm06881@荊南 節度使 rm#r00001@衞伯玉 遭母喪，
六月，
戊戌，
以殿中監 rm#r02646@王昂 代之。

 rm#r00001@伯玉 諷大將 rm#xjts23015@楊鉥 等拒 rm#r02646@昂 留己；
甲寅，
詔起復 rm#r00001@伯玉 鎭 dm#dm06881@荊南 如故。


# p 

秋，
七月，
 dm#dm00444@京畿 饑，
米斗千錢。
# p 

 rm#r00237@劉希暹 内常自疑，
有不遜語，
 rm#xjts02815@王駕鶴 以聞。

九月，
辛未，
賜 rm#r00237@希暹 死。
# p 

吐蕃寇 dm#dm04394@永壽 。

# p 

冬，
十一月，
 rm#xjts01384@郭子儀 入朝。

# p 

上悉知 rm#r00165@元載 所爲，
以其任政日久，
欲全始終，
因獨見，
深戒之；
 rm#r00165@載 猶不悛，
上由是稍惡之。

# p 

 rm#r00165@載 以 rm@李泌 有寵於上，
忌之，
言「 rm@泌 常與親故宴於北軍，
與 rm#r04309@魚朝恩 親善，
宜知其謀。」

上曰：
「北軍，
 rm@泌 之故吏也，
故朕使之就見親故。

 rm#r04309@朝恩 之誅，
 rm@泌 亦預謀，
卿勿以爲疑。」

 rm#r00165@載 與其黨攻之不已；
會 dm#dm04509@江西 觀察使 rm#r04285@魏少遊 求參佐，
上謂 rm@泌 曰：
「 rm#r00165@元載 不容卿，
朕今匿卿於 rm#r04285@魏少遊 所。

俟朕決意除 rm#r00165@載 ，
當有信報卿，
可束裝來。」

乃以 rm@泌 爲 dm#dm04509@江西 判官，
且屬 rm#r04285@少遊 使善待之。

*** 六年
# year 0771
# p 

春，
二月，
壬寅，
 dm#dm04695@河西 、 dm#dm08458@隴右 、 dm#dm02401@山南西道 副元帥兼 dm#dm05401@澤潞 、 dm#dm02401@山南西道 節度使 rm#r00795@李抱玉 上言：
「凡所掌之兵，
當自訓練。

今自 dm#dm04650@河 、 dm#dm08457@隴 達於 dm#dm03171@扶 、 dm#dm03295@文 ，
綿亙二千餘里，
撫御至難。

若吐蕃道 dm#dm02437@岷 、 dm#dm08457@隴 道岷、隴倶下，
臣保固 dm#dm00067@汧 、 dm#dm08457@隴 則不救 dm#dm04038@梁 、 dm#dm02437@岷 ，
進兵 dm#dm03171@扶 、 dm#dm03295@文 則寇逼 dm#dm08290@關輔 ，
首尾不贍，
進退無從。

願更擇能臣，
委以 dm#dm02398@山南 ，
使臣得專備 dm#dm08461@隴坻 。」

詔許之。

道岷、隴兩道
# p 

 rm#xjts01384@郭子儀 還 dm#dm07812@邠州 。

# p 

嶺南蠻酋 rm#xjts12251@梁崇牽 自稱 dm#dm02608@平南 十道大都統，
據 dm#dm02240@容州 ，
與西原蠻 rm#xjts04466@張侯 、 rm#xjts03503@夏永 等連兵攻陷城邑，
前 dm#dm02243@容管 經略使 rm#r00160@元結 等皆寄治 dm#dm07050@蒼梧 。

經略使 rm#r02690@王翃 至 dm#dm07130@藤州 ，
以私財募兵，
不數月，
斬賊帥 rm#xjts26928@歐陽珪 ，
馳詣 dm#dm02733@廣州 ，
見節度使 rm#xjts14812@李勉 ，
請兵以復 dm#dm02240@容州 ；
 rm#xjts14812@勉 以爲難，
 rm#r02690@翃 曰：
「大夫如未暇出兵，
但乞移牒諸州，
揚言出千兵爲援，
冀藉聲勢，
亦可成功。」

 rm#xjts14812@勉 從之。

 rm#r02690@翃 乃與 dm#dm06542@義州 刺史 rm#xjts26327@陳仁璀 、 dm#dm07130@藤州 刺史 rm#xjts17416@李曉庭 等結盟討賊。

 rm#r02690@翃 募得三千餘人，
破賊數萬衆；
攻 dm#dm02240@容州 ，
拔之，
擒 rm#xjts12251@梁崇牽 ，
前後大小百餘戰，
盡復 dm#dm02240@容州 故地。

分命諸將襲西原蠻，
復 dm#dm08939@鬱林 等諸州。
# p 

先是，
 dm#dm05842@番禺 賊帥 dm#dm08847@馮崇道 ，
 dm#dm04001@桂州 叛將 rm#xjts09808@朱濟時 ，
皆據險爲亂，
陷十餘州，
官軍討之，
連年不克；
 rm@李勉 遣其將 rm@李觀 與 rm@翃 併力攻討，
悉斬之，
三月，
 dm#dm00381@五嶺 皆平。
# p 

 dm#dm04656@河北 旱，
米斗千錢。
# p 

夏，
四月，
己未，
 dm#dm05403@澧州 刺史 rm#xjts23016@楊子琳 入朝，
上優接之，
賜名 rm#xjts23016@猷 。

# p 

庚申，
以典内 rm#r06744@董秀 爲内常侍。

# p 

吐蕃請和；
庚辰，
遣兼御史大夫 rm@呉損 使于吐蕃。

# p 

 dm#dm03147@成都 司録 rm#r01708@李少良 上書言 rm#r00165@元載 姦贓陰事，
上置 rm#r01708@少良 於客省。

 rm#r01708@少良 以上語告友人 rm#xjts19207@韋頌 ，
殿中侍御史 rm#xjts26051@陸珽 以告 rm#r00165@載 ，
 rm#r00165@載 奏之。

上怒，
下 rm#r01708@少良 、 rm#xjts19207@頌 、 rm#xjts26051@珽 御史臺獄。

御史奏 rm#r01708@少良 、 rm#xjts19207@頌 、 rm#xjts26051@珽 凶險比周，
離間君臣，
五月，
戊申，
敕付 dm#dm00427@京兆 ，
皆杖死。
# p 

秋，
七月，
丙午，
 rm#r00165@元載 奏，
凡別敕除文、武六品以下官，
乞令吏部、兵部無得檢勘，
從之。

時 rm#r00165@載 所奏擬多不遵法度，
恐爲有司所駁故也。


# p 

八月，
丁卯，
 dm#dm05005@淮西 節度使 rm#r03193@李忠臣 將兵二千屯 dm#dm01853@奉天 防秋。

# p 

上益厭 rm#r00165@元載 所爲，
思得士大夫之不阿附者爲腹心，
漸收 rm#r00165@載 權。

丙子，
内出制書，
以 dm#dm04858@浙西 觀察使 rm#r01826@李栖筠 爲御史大夫，
宰相不知，
 rm#r00165@載 由是稍絀。

# p 

九月，
吐蕃下 dm#dm08677@青石嶺 ，
軍于 dm#dm07819@那城 ；
 rm#xjts01384@郭子儀 使人諭之，
明日，
引退。
# p 

 y@是歳 ，
以尚書右丞 rm#r04122@韓滉 爲戸部侍郎、判度支。

自兵興以來，
所在賦斂無度，
倉庫出入無法，
國用虚耗。

 rm#r04122@滉 爲人廉勤，
精於簿領，
作賦斂出入之法，
御下嚴急，
吏不敢欺；
亦値連歳豐穰，
邊境無寇，
自是倉庫蓄積始充。

 rm#r04122@滉 ，
 rm#xjts20586@休 之子也。

*** 七年
# year 0772
# p 

春，
正月，
甲辰，
囘紇使者出鴻臚寺，
掠人子女；
所司禁之，
毆撃所司，
以三百騎犯 dm#dm08009@金光 、 dm#dm03754@朱雀門 。

是日，
宮門皆閉，
上遣中使 rm#xjts25735@劉清潭 諭之，
乃止。

# p 

三月，
 rm#xjts01384@郭子儀 入朝；
丙午，
還 dm#dm07812@邠州 。


# p 

夏，
四月，
吐蕃五千騎至 dm#dm08619@靈州 ，
尋退。

# p 

五月，
乙未，
赦天下。
# p 

秋，
七月，
癸巳，
囘紇又出鴻臚寺，
逐 dm#dm08170@長安 令 rm#r03689@邵説 至 dm#dm01262@含光門 街，
奪其馬；
 rm#r03689@説 乘他馬而去，
弗敢爭。
# p 

 dm#dm06013@盧龍 節度使 rm#xjts09851@朱希彩 既得位，
悖慢朝廷，
殘虐將卒；
孔目官 rm#xjts18136@李懷瑗 因衆怒，
伺間殺之。

未知所從；
經略副使 rm#r01577@朱泚 營於城北，
其弟 rm#r01579@滔 將牙内兵，
潛使百餘人於衆中大言曰：
「節度使非 rm#r01577@朱副使 不可；」
衆皆從之。

 rm#r01577@泚 遂權知留後，
遣使言状。

冬，
十月，
辛未，
以 rm#r01577@泚 爲檢校左常侍、 dm#dm02689@幽州 ‧ dm#dm06013@盧龍 節度使。

# p 

十二月，
辛未，
置 dm#dm04414@永平軍 於 dm#dm05229@滑州 。
*** 八年
# year 0773
# p 

春，
正月，
 dm#dm03524@昭義 節度使、 dm#dm06029@相州 刺史 rm@薛嵩 薨。

子 rm#r03287@平 ，
年十二，
將士脅以爲帥，
 rm#r03287@平 僞許之；
既而讓其叔父 rm@崿 ，
夜奉父喪，
逃歸郷里。

壬午，
制以 rm@崿 知留後。

# p 

二月，
壬申，
 dm#dm04412@永平 節度使 rm#r00071@令狐彰 薨。

 rm#r00071@彰 承 dm#dm05225@滑 、 dm#dm00454@亳 離亂之後，
治軍勸農，
府廩充實。

時藩鎭率皆跋扈，
獨 rm#r00071@彰 貢賦未嘗闕；
歳遣兵三千詣 dm#dm00446@京西 防秋，
自齎糧食，
道路供饋皆不受，
所過秋豪不犯。

疾亟，
召掌書記 dm#dm08926@高陽  rm#r04345@齊映 ，
與謀後事，
 rm#r04345@映 勸 rm#r00071@彰 請代人，
遣子歸私第；
 rm#r00071@彰 從之，
遺表稱：
「昔 rm#r04309@魚朝恩 破 rm#r00385@史朝義 ，
欲掠 dm#dm05229@滑州 ，
臣不聽，
由是有隙。

及 rm#r04309@朝恩 誅，
値臣寢疾，
以是未得入朝，
生死愧負。

臣今必不起，
倉庫畜牧，
先已封籍，
軍中將士，
州縣官吏，
按堵待命。

伏見吏部尚書 rm#r00276@劉晏 、工部尚書 rm@李勉 可委大事，
願速以代臣。

臣男 rm@建 等，
今勒歸 dm#dm03880@東都 私第。」

 rm#r00071@彰 薨，
將士欲立 rm@建 ，
 rm@建 誓死不從，
舉家西歸。

三月，
丙子，
以 rm@李勉 爲 dm#dm04412@永平 節度使。
# p 

吏部侍郎 rm#r01319@徐浩 、 rm#xjts21190@薛邕 ，
皆 rm#r00165@元載 、 rm#r02687@王縉 之黨；
 rm#r01319@浩 妾弟 rm#xjts10463@侯莫陳怤 爲 dm#dm06521@美原 尉，
 rm#r01319@浩 屬 dm#dm00427@京兆 尹 rm#xjts21955@杜濟 虚以知驛奏優，
又屬 rm#xjts21190@邕 擬 dm#dm08170@長安 尉。

 rm#xjts10463@怤 參臺，
御史大夫 rm#r01826@李栖筠 劾奏其状，
敕禮部侍郎 dm#dm06979@萬年  rm@于劭 等按之。

 rm@劭 奏 rm#xjts21190@邕 罪在赦前，
應原除，
上怒。

夏，
五月，
乙酉，
貶 rm#r01319@浩  dm#dm03478@明州 別駕，
 rm#xjts21190@邕  dm#dm04211@歙州 刺史；
丙戌，
貶 rm#xjts21955@濟  dm#dm03781@杭州 刺史，
 rm@劭  dm#dm04001@桂州 長史，
朝廷稍肅。

# p 

辛卯，
 rm#r03771@鄭王邈 薨，
贈 rm#xjts15965@昭靖太子 。

# p 

囘紇自 y@乾元 以來，
歳求和市，
毎一馬易四十縑，
動至數萬匹，
馬皆駑瘠無用；
朝廷苦之，
所市多不能盡其數，
囘紇待遣、繼至者常不絶於鴻臚。

至是，
上欲悦其意，
命盡市之。

秋，
七月，
辛丑，
囘紇辭歸，
載賜遺及馬價，
共用車千餘乘。

# p 

八月，
己未，
吐蕃六萬騎寇 dm#dm08626@靈武 ，
踐秋稼而去。

# p 

辛未，
 dm#dm02689@幽州 節度使 rm#r01577@朱泚 遣弟 rm#r01579@滔 將五千精騎詣 dm#dm04924@涇州 防秋。

自 rm#r00793@安祿山 反，
 dm#dm02689@幽州 兵未常爲用，
 rm#r01579@滔 至，
上大喜，
勞賜甚厚。

# p 

壬申，
囘紇復遣使者 rm@赤心 以馬萬匹來求互市。

# p 

九月，
壬午，
 dm#dm02972@循州 刺史 rm#xjts03770@哥舒晃 殺 dm#dm02527@嶺南 節度使 rm#r05115@呂崇賁 ，
據 dm#dm02527@嶺南 反。
# p 

癸未，
 dm#dm03544@晉州 男子 rm@郇模 ，
以麻辮髮，
持竹筐葦席，
哭於東市。

人問其故，
對曰：
「願獻三十字，
一字爲一事；
若言無所取，
請以席裹尸，
貯筐中，
棄於野。」

 dm#dm00427@京兆 以聞。

上召見，
賜新衣，
館於客省。

其言「團」
者，
請罷諸州團練使也；
「監」
者，
請罷諸道監軍使也。

# p 

 dm#dm08946@魏博 節度使 rm#r02821@田承嗣 爲 rm#r00793@安 、 rm#r00380@史 父子立祠堂，
謂之四聖，
且求爲相；
上令内侍 rm#r05164@孫知古 因奉使諷令毀之。

冬，
十月，
甲辰，
加 rm#r02821@承嗣 同平章事以褒之。
# p 

 dm#dm08619@靈州 破吐蕃萬餘衆。

吐蕃衆十萬寇 dm#dm04919@涇 、 dm#dm07808@邠 ，
 rm#xjts01384@郭子儀 遣 dm#dm03677@朔方 兵馬使 rm#r02462@渾瑊 將歩騎五千拒之。

庚申，
戰于 dm#dm02186@宜祿 。

 rm#r02462@瑊 登 dm#dm09147@黄萯原 望虜，
命據險布拒馬以備其馳突。

宿將 rm#xjts23910@史抗 、 rm#xjts12523@温儒雅 等意輕 rm#r02462@瑊 ，
不用其命；
 rm#r02462@瑊 召使撃虜，
則已醉矣；
見拒馬，
曰：
「野戰，
烏用此爲！」

命撤之。

叱騎兵衝虜陳，
不能入而返；
虜躡而乘之，
官軍大敗，
士卒死者什七八，
居民爲吐蕃所掠千餘人。
# p 

甲子，
 rm#r04182@馬璘 與吐蕃戰于 dm#dm09044@鹽倉 ，
又敗。

 rm#r04162@璘 爲虜所隔，
逮暮未還，
 dm#dm04920@涇原 兵馬使 rm@焦令諶 等與敗卒爭門而入。

或勸行軍司馬 rm#r02349@段秀實 乘城拒守，
 rm#r02349@秀實 曰：
「大帥未知所在，
當前撃虜，
豈得苟自全乎！」

召 rm@令諶 等讓之曰：
「軍法，
失大將，
麾下皆死。

諸君忘其死邪！」

 rm@令諶 等惶懼拜請命。

 rm#r02349@秀實 乃發城中兵未戰者悉出，
陳于東原，
且收散兵，
爲將力戰状。

吐蕃畏之，
稍卻。

既夜，
 rm#r04182@璘 乃得還。
# p 

 rm#xjts01384@郭子儀 召諸將謀曰：
「敗軍之罪在我，
不在諸將。

然 dm#dm03677@朔方 兵精聞天下，
今爲虜敗，
何策可以雪恥？」
莫對。

 rm#r02462@渾瑊 曰：
「敗軍之將，
不當復預議。

然願一言今日之事，
惟理瑊罪，
不則再見任。」

 rm#xjts01384@子儀 赦其罪，
使將兵趣 dm#dm03717@朝那 。

虜既破官軍，
欲掠 dm#dm00067@汧 、 dm#dm08457@隴 。

 dm#dm09056@鹽州 刺史 rm#r00780@李國臣 曰：
「虜乘勝必犯郊畿，
我掎其後，
虜必返顧。」

乃引兵趣 dm#dm06276@秦原 ，
鳴鼓而西。

虜聞之，
至 dm#dm05956@百城 ，
返，
 rm#r02462@渾瑊 邀之於隘，
盡復得其所掠；
 rm#r04182@馬璘 亦出精兵襲虜輜重于 dm#dm05344@潘原 ，
殺數千人，
虜遂遁去。


# p 

乙丑，
以 dm#dm04509@江西 觀察使 rm#xjts24772@路嗣恭 討 rm#xjts03770@哥舒晃 。兼嶺南節度使
# p 

初，
 rm#r00165@元載 嘗爲 dm#dm07317@西州 刺史，
知 dm#dm04695@河西 、 dm#dm08458@隴右 山川形勢。

是時，
吐蕃數爲寇，
 rm#r00165@載 言於上曰：
「 dm#dm01437@四鎭 、 dm#dm00860@北庭 既治 dm#dm04924@涇州 ，
無險要可守。

 dm#dm08463@隴山 高峻，
南連 dm#dm06278@秦嶺 ，
北抵 dm#dm01648@大河 。

今國家西境盡 dm#dm05344@潘原 ，
而吐蕃戍 dm#dm03252@摧沙堡 ，
 dm#dm01114@原州 居其中間，
當 dm#dm08463@隴山 之口，
其西皆監牧故地，
草肥水美，
 dm#dm02650@平涼 在其東，
獨耕一縣，
可給軍食，
故壘尚存，
吐蕃棄而不居。

毎歳盛夏，
吐蕃畜牧 dm#dm08673@青海 ，
去塞甚遠，
若乘間築之，
二旬可畢。

移 dm#dm00446@京西 軍戍 dm#dm01114@原州 ，
移 rm#xjts01384@郭子儀 軍戍 dm#dm04924@涇州 ，
爲之根本，
分兵守 dm#dm06130@石門 、 dm#dm03728@木峽 ，
漸開 dm#dm08458@隴右 ，
進達 dm#dm02061@安西 ，
據吐蕃腹心，
則朝廷可高枕矣。」

幷圖地形獻之，
密遣人出 dm#dm08463@隴山 商度功用。

會 dm#dm04540@汴宋 節度使 rm#r02827@田神功 入朝，
上問之，
對曰：
「行軍料敵，
宿將所難，
陛下奈何用一書生語，
欲舉國從之乎！」

 rm#r00165@載 尋得罪，
事遂寢。

# p 

有司以囘紇 rm@赤心 馬多，
請市千匹。

 rm#xjts01384@郭子儀 以爲如此，
逆其意太甚，
自請輸一歳俸爲國市之。

上不許。

十一月，
戊子，
命市六千匹。
*** 大暦九年
# year 0774
# p 

春，
正月，
壬寅，
 rm#r02827@田神功 薨於 dm#dm08170@京師 。

# p 

 dm#dm05404@澧朗 鎭遏使 rm#xjts23016@楊猷 自 dm#dm05403@澧州 沿江而下，
出境至 dm#dm07895@鄂州 ，
詔聽入朝。

 rm#xjts23016@猷 遂泝 dm#dm05294@漢江 而上，
 dm#dm02970@復州 、 dm#dm07856@郢州 皆閉城自守，
 dm#dm02400@山南東道 節度使 rm#r02124@梁崇義 發兵備之。
# p 

二月，
辛未，
 dm#dm02952@徐州 軍亂，
刺史 rm#r02122@梁乘 逾城走。

# p 

諫議大夫 rm@呉損 使吐蕃，
留之累年，
竟病死虜中。

# p 

庚辰，
 dm#dm04540@汴宋 兵防秋者千五百人，
盜庫財潰歸，
 rm#r02827@田神功 薨故也。

己丑，
以 rm#xjts24347@神功 弟 rm#r02828@神玉 知 dm#dm04540@汴宋 留後。
# p 

癸巳，
 rm#xjts01384@郭子儀 入朝，
上言：
「 dm#dm03677@朔方 ，
國之北門，
中間戰士耗散，
什纔有一。

今吐蕃兼 dm#dm04650@河 、 dm#dm08457@隴 之地，
雜羌、渾之衆，
勢強十倍。

願更於諸道各發精卒，
成四、五萬人，
則制勝之道必矣。」

# p 

三月，
戊申，
以皇女 rm@永樂公主 許妻 dm#dm08946@魏博 節度使 rm#r02821@田承嗣 之子 rm@華 。

上意欲固結其心，
而 rm#r02821@承嗣 益驕慢。

# p 

以 dm#dm05404@澧朗 鎭遏使 rm#xjts23016@楊猷 爲 dm#dm04823@洮州 刺史、 dm#dm08458@隴右 節度兵馬使。
戊午
# p 

夏，
四月，
甲申，
 rm#xjts01384@郭子儀 辭還 dm#dm07812@邠州 ，
復爲上言邊事，
至涕泗交流。
# p 

壬辰，
赦天下。
# p 

五月，
丙午，
 rm#xjts23016@楊猷 自 dm#dm05403@澧州 入朝。

# p 

 dm#dm04920@涇原 節度使 rm#r04182@馬璘 入朝，
諷將士爲己表求平章事。

丙寅，
以 rm#r04182@璘 爲左僕射。

# p 

六月，
 dm#dm06013@盧龍 節度使 rm#r01577@朱泚 遣弟 rm#r01579@滔 奉表請入朝，
且請自將歩騎五千防秋；
上許之，
仍爲先築大第於京師以待之。
# p 

癸未，
 dm#dm06752@興善寺 胡僧 rm#r00026@不空 卒，
贈開府儀同三司、司空，
賜爵 rm#r00026@肅國公 ，
諡曰 rm#r00026@大辯正廣智不空三藏和尚 。

# p 

 dm#dm08170@京師 旱，
 dm#dm00427@京兆 尹 rm#r04338@黎幹 作土龍祈雨，
自與巫覡更舞。

彌月不雨，
又祷於 rm@文宣王 。

上聞之，
命撤土龍，
減膳節用。

秋，
七月，
戊午，
雨。
# p 

 rm#r01577@朱泚 入朝，
至 dm#dm07077@蔚州 ，
有疾，
諸將請還，
俟間而行。

 rm#r01577@泚 曰：
「死則輿尸而前！」

諸將不敢復言。

九月，
庚子，
至 dm#dm08170@京師 ，
士民觀者如堵。

辛丑，
宴 rm#r01577@泚 及將士於 dm#dm02831@延英殿 ，
犒賞之盛，
近時未有。


# p 

壬寅，
囘紇出鴻臚寺，
白晝殺人，
有司擒之；
上釋不問。
# p 

甲辰，
命 rm#xjts01384@郭子儀 、 rm#r00795@李抱玉 、 rm#r04182@馬璘 、 rm#r01577@朱泚 分統諸道防秋之兵。

# p 

冬，
十月，
壬申，
 rm#r00134@信王瑝 薨。

乙亥，
 rm#r02444@梁王璿 薨。

# p 

 dm#dm08946@魏博 節度使 rm#r02821@田承嗣 誘 dm#dm03524@昭義 將吏使作亂。

*** 十年
# year 0775
# p 

春，
正月，
丁酉，
 dm#dm03524@昭義 兵馬使 rm#xjts05714@裴志清 逐留後 rm@薛崿 ，
帥其衆歸 rm#r02821@承嗣 。

 rm#r02821@承嗣 聲言救援，
引兵襲 dm#dm06029@相州 ，
取之。

 rm@崿 奔 dm#dm04839@洺州 ，
上表請入朝，
許之。

# p 

辛丑，
 rm#xjts01384@郭子儀 入朝。
# p 

壬寅，
 rm#r00588@壽王瑁 薨。

# p 

乙巳，
 rm#r01577@朱泚 表請留闕下，
以弟 rm#r01579@滔 知 dm#dm02689@幽州 、 dm#dm06013@盧龍 留後，
許之。
# p 

 dm#dm03524@昭義 裨將 rm#xjts21513@薛擇 爲 dm#dm06029@相州 刺史，
 rm#r03318@薛雄 爲 dm#dm00029@衞州 刺史，
 rm#xjts21590@薛堅 爲 dm#dm04839@洺州 刺史，
皆 rm@薛嵩 之族也。

戊申，
上命内侍 rm@魏知古 如 dm#dm08950@魏州 諭 rm#r02821@田承嗣 ，
使各守封疆；
 rm#r02821@承嗣 不奉詔，
癸丑，
遣大將 rm#xjts07204@盧子期 取 dm#dm04839@洺州 ，
 rm#xjts23055@楊光朝 攻 dm#dm00029@衞州 。

魏孫
# p 

乙卯，
 dm#dm07316@西川 節度使 rm#r00914@崔寧 奏破吐蕃數萬於 dm#dm07314@西山 ，
斬首萬級，
捕虜數千人。
# p 

丙辰，
詔：
「諸道兵有逃亡者，
非承制敕，
無得輒召募。」

# p 

二月，
乙丑，
 rm#r02821@田承嗣 誘 dm#dm00029@衞州 刺史 rm#r03318@薛雄 ，
 rm#r03318@雄 不從，
使盜殺之，
屠其家，
盡據 dm#dm06025@相 、 dm#dm00026@衞 四州之地，
自置長吏，
掠其精兵良馬，
悉歸 dm#dm08950@魏州 ；
逼 rm#r04303@魏知古 與共巡 dm#dm06175@磁 、 dm#dm06025@相 二州，
使其將士割耳剺面，
請 rm#r02821@承嗣 爲帥。

# p 

辛未，
立皇子 rm#r02952@述 爲 rm#r02952@睦王 ，
 rm#xjts16125@逾 爲 rm#xjts16125@郴王 ，
 rm#r01349@連 爲 rm#r01349@恩王 ，
 rm#r03067@遘 爲 rm#r03067@鄜王 ，
 rm#xjts16031@迅 爲 rm#xjts16031@隨王 ，
 rm#xjts15863@造 爲 rm#r01343@忻王 ，
 rm#r04135@暹 爲 rm#r04135@韶王 ，
 rm#r00562@運 爲 rm#r00562@嘉王 ，
 rm#r03058@遇 爲 rm#r03058@端王 ，
 rm#xjts16042@遹 爲 rm#r01330@循王 ，
 rm#r01355@通 爲 rm#r01355@恭王 ，
 rm@達 爲 rm@原王 ，
 rm#r03977@逸 爲 rm#r03977@雅王 。

# p 

丙子，
以 dm#dm06938@華州 刺史 rm#xjts14105@李承昭 知 dm#dm03524@昭義 留後。

# p 

 dm#dm04709@河陽 三城使 rm#xjts28804@常休明 ，
苛刻少恩。

其軍士防秋者歸，
 rm#xjts28804@休明 出城勞之，
防秋兵與城内兵合謀攻之，
 rm#xjts28804@休明 奔 dm#dm03880@東都 ；
軍士奉兵馬使 rm#xjts03201@王惟恭 爲帥，
大掠，
數日乃定。

上命監軍 rm#xjts23982@冉庭蘭 慰撫之。

# p 

三月，
甲午，
 dm#dm08320@陝州 軍亂，
逐兵馬使 rm@趙令珍 。

觀察使 rm#xjts17292@李國清 不能禁，
卑辭，
徧拜將士，
乃得脱去。

軍士大掠庫物。

會 dm#dm05005@淮西 節度使 rm#r03193@李忠臣 入朝，
過 dm#dm08315@陜 ，
上命 rm#r03193@忠臣 按之；
將士畏 rm#r03193@忠臣 兵威，
不敢動。

 rm#r03193@忠臣 設棘圍，
令軍士匿名投庫物，
一日，
獲萬緡，
盡以給其從兵爲賞。

# p 

乙巳，
 rm@薛崿 、 rm#xjts28804@常休明 皆詣闕請罪，
上釋不問。
# p 

初，
 dm#dm03139@成徳 節度使 rm#r01157@李寶臣 、 dm#dm04964@淄青 節度使 rm#xjts13396@李正己 ，
皆爲 rm#r02821@田承嗣 所輕。

 rm#r01157@寶臣 弟 rm#xjts15554@寶正 娶 rm#r02821@承嗣 女，
在 dm#dm08950@魏州 ，
與 rm#r02821@承嗣 子 rm#xjts24298@維 撃毬，
馬驚，
誤觸 rm#xjts24298@維 死；
 rm#r02821@承嗣 怒，
囚 rm#xjts15554@寶正 ，
以告 rm#r01157@寶臣 。

 rm#r01157@寶臣 謝教敕不謹，
封杖授 rm#r02821@承嗣 ，
使撻之；
 rm#r02821@承嗣 遂杖殺 rm#xjts15554@寶正 ，
由是兩鎭交惡。

及 rm#r02821@承嗣 拒命，
 rm#r01157@寶臣 、 rm@正己 皆上表請討之，
上亦欲因其隙討 rm#r02821@承嗣 。

夏，
四月，
乙未，
敕貶 rm#r02821@承嗣 爲 dm#dm04410@永州 刺史，
仍命 dm#dm04672@河東 、 dm#dm03139@成徳 、 dm#dm02689@幽州 、 dm#dm04964@淄青 、 dm#dm05005@淮西 、 dm#dm04412@永平 、 dm#dm04540@汴宋 、 dm#dm04709@河陽 、 dm#dm05401@澤潞 諸道發兵前臨 dm#dm08946@魏博 ，
若 rm#r02821@承嗣 尚或稽違，
即令進討；
罪止 rm#r02821@承嗣 及其姪 rm#r02819@悦 ，
自餘將士弟姪苟能自拔，
一切不問。

# p 

時 rm#r01579@朱滔 方恭順，
與 rm#r01157@寶臣 及 dm#dm04672@河東 節度使 rm#xjts21614@薛兼訓 攻其北，
 rm#r01776@正己 與 dm#dm05005@淮西 節度使 rm#r03193@李忠臣 等攻其南。

五月，
乙未，
 rm#r02821@承嗣 將 rm#xjts03456@霍榮國 以 dm#dm06177@磁州 降。

丁未，
 rm#r01776@李正己 攻 dm#dm02976@徳州 ，
拔之。

 rm#r03193@李忠臣 統 dm#dm04412@永平 、 dm#dm04709@河陽 、 dm#dm03102@懷 、 dm#dm05399@澤 歩騎四萬進攻 dm#dm00029@衞州 。

六月，
辛未，
 rm#r02821@田承嗣 遣其將 rm#xjts05714@裴志清 等攻 dm#dm00712@冀州 ，
 rm#xjts05714@志清 以其衆降 rm#r01157@李寶臣 。

甲戌，
 rm#r02821@承嗣 自將圍 dm#dm00712@冀州 ，
 rm#r01157@寶臣 使 dm#dm08928@高陽軍 使 rm#r01268@張孝忠 將精騎四千禦之，
 rm#r01157@寶臣 大軍繼至；
 rm#r02821@承嗣 燒輜重而遁。

 rm#r01268@孝忠 ，
本奚也。

# p 

 rm#r02821@田承嗣 以諸道兵四合，
部將多叛而懼，
秋，
八月，
遣使奉表，
請束身歸朝。

# p 

辛巳，
 rm#xjts01384@郭子儀 還 dm#dm07812@邠州 。

 rm#xjts01384@子儀 嘗奏除州縣官一人，
不報，
僚佐相謂曰：
「以令公勳徳，
奏一屬吏而不從，
何宰相之不知體！」

 rm#xjts01384@子儀 聞之，
謂僚佐曰：
「自兵興以來，
方鎭武臣多跋扈，
凡有所求，
朝廷常委曲從之；
此無他，
乃疑之也。

今 rm#xjts01384@子儀 所奏事，
人主以其不可行而置之，
是不以武臣相待而親厚之也；
諸君可賀矣，
又何怪焉！」

聞者皆服。

# p 

己丑，
 rm#r02821@田承嗣 遣其將 rm#xjts07204@盧子期 寇 dm#dm06177@磁州 。


# p 

九月，
戊申，
囘紇白晝刺市人腸出，
有司執之，
繋 dm#dm06979@萬年 獄；
其酋長 rm@赤心 馳入縣獄，
斫傷獄吏，
劫囚而去。

上亦不問。

# p 

壬子，
吐蕃寇 dm#dm06701@臨涇 ，
癸丑，
寇 dm#dm08464@隴州 及 dm#dm03584@普潤 ，
大掠人畜而去；
百官往往遣家屬出城竄匿。

丙辰，
 dm#dm09004@鳳翔 節度使 rm#r00795@李抱玉 奏破吐蕃於 dm#dm06536@義寧 。

# p 

 rm#r01157@李寶臣 、 rm#r01776@正己 會于 dm#dm04064@棗強 ，
進圍 dm#dm07514@貝州 ，
 rm#r02821@田承嗣 出兵救之。

兩軍各饗士卒，
 dm#dm03139@成徳 賞厚，
 dm#dm02660@平盧 賞薄；
既罷，
 dm#dm02660@平盧 士卒有怨言，
 rm#r01776@正己 恐其爲變，
引兵退，
 rm#r01157@寶臣 亦退。

 rm#r03193@李忠臣 聞之，
釋 dm#dm00029@衞州 ，
南渡 dm#dm04650@河 ，
屯 dm#dm08413@陽武 。

 rm#r01157@寶臣 與 rm#r01579@朱滔 攻 dm#dm05209@滄州 ，
 rm#r02821@承嗣 從父弟 rm#xjts24270@庭玠 守之；
 rm#r01157@寶臣 不能克。
# p 

吐蕃寇 dm#dm04924@涇州 ，
 dm#dm04920@涇原 節度使 rm#r04182@馬璘 破之於 dm#dm05956@百里城 。

戊午，
命 dm#dm06013@盧龍 節度使 rm#r01577@朱泚 出鎭 dm#dm01853@奉天 行營。

# p 

冬，
十月，
辛酉朔，
日有食之。


# p 

 rm#xjts07204@盧子期 攻 dm#dm06177@磁州 ，
城幾陷；
 rm#r01157@李寶臣 與 dm#dm03524@昭義 留後 rm#xjts14105@李承昭 共救之，
大破 rm#xjts07204@子期 于 dm#dm05042@清水 ，
擒 rm#xjts07204@子期 送 dm#dm08170@京師 ；
斬之。

 dm#dm04660@河南 諸將又大破 rm#r02819@田悦 於 dm#dm08355@陳留 ；
 rm#r02821@田承嗣 懼。
# p 

初，
 rm#xjts13396@李正己 遣使至 dm#dm08950@魏州 ，
 rm#r02821@承嗣 囚之，
至是，
禮而遣之，
遣使盡籍境内戸口、甲兵、穀帛之數以與之，
曰：
「 rm#r02821@承嗣  y@今年 八十有六，
溘死無日，
諸子不肖，
 rm#r02819@悦 亦孱弱，
凡今日所有，
爲公守耳，
豈足以辱公之師旅乎！」

立使者於庭，
南向，
拜而授書；
又圖 rm#xjts13396@正己 之像，
焚香事之。

 rm#xjts13396@正己 悦，
遂按兵不進。

於是 dm#dm04660@河南 諸道兵皆不敢進。

 rm#r02821@承嗣 既無南顧之虞，
得專意北方。
# p 

上嘉 rm#r01157@李寶臣 之功，
遣中使 rm#xjts24938@馬承倩 齎詔勞之；
將還，
 rm#r01157@寶臣 詣其館，
遺之百縑，
 rm#xjts24938@承倩 詬詈，
擲出道中，
 rm#r01157@寶臣 慙其左右。

兵馬使 rm#r02656@王武俊 説 rm#r01157@寶臣 曰：
「今公在軍中新立功，
豎子尚爾，
況寇平之後，
以一幅詔書召歸闕下，
一匹夫耳，
不如釋 rm#r02821@承嗣 以爲己資。」

 rm#r01157@寶臣 遂有玩寇之志。


# p 

 rm#r02821@承嗣 知 dm#dm06863@范陽  rm#r01157@寶臣 郷里，
心常欲之，
因刻石作讖云：
「二帝同功勢萬全，
將 rm@田 爲侶入 dm#dm02691@幽燕 ，」
密令瘞 rm#r01157@寶臣 境内，
使望氣者言彼有王氣，
 rm#r01157@寶臣 掘而得之。

又令客説之曰：
「公與 rm#r01579@朱滔 共取 dm#dm05209@滄州 ，
得之，
則地歸國，
非公所有。

公能捨 rm#r02821@承嗣 之罪，
請以 dm#dm05209@滄州 歸公，
仍願從公取 dm#dm06863@范陽 以自效。

公以精騎前驅，
 rm#r02821@承嗣 以歩卒繼之，
蔑不克矣。」

 rm#r01157@寶臣 喜，
謂事合符讖，
遂與 rm#r02821@承嗣 通謀，
密圖 dm#dm06863@范陽 ，
 rm#r02821@承嗣 亦陳兵境上。
# p 

 rm#r01157@寶臣 謂 rm#r01579@滔 使者曰：
「聞 rm#xjts09949@朱公 儀貌如神，
願得畫像觀之。」

 rm#r01579@滔 與之。

 rm#r01157@寶臣 置於射堂，
與諸將共觀之，
曰：
「眞神人也！」

 rm#r01579@滔 軍於 dm#dm05786@瓦橋 ，
 rm#r01157@寶臣 選精騎二千，
通夜馳三百里襲之，
戒曰：
「取貌如射堂者。」

時兩軍方睦，
 rm#r01579@滔 不虞有變，
狼狽出戰而敗，
會衣他服得免。

 rm#r01157@寶臣 欲乘勝取 dm#dm06863@范陽 ，
 rm#r01579@滔 使 dm#dm08475@雄武軍 使 dm#dm03464@昌平  rm#r00256@劉怦 守留府。

 rm#r01157@寶臣 知有備，
不敢進。
# p 

 rm#r02821@承嗣 聞 dm#dm02688@幽 、恆兵交，
即引軍南還，
使謂 rm#r01157@寶臣 曰：
「 dm#dm04653@河内 有警，
不暇從公，
石上讖文，
吾戲爲之耳！」

 rm#r01157@寶臣 慙怒而退。

 rm#r01157@寶臣 既與 rm#r01579@朱滔 有隙，
以 rm#r01268@張孝忠 爲 dm#dm03494@易州 刺史，
使將精騎七千以備之。

# p 

丙寅，
貴𡚱 rm@獨孤氏 薨，
丁卯，
追諡 rm#r02570@貞懿皇后 。

# p 

十一月，
丁酉，
 rm#r02821@田承嗣 將 rm#xjts10288@呉希光 以 dm#dm05480@瀛州 降。
# p 

 dm#dm02527@嶺南 節度使 rm#xjts24772@路嗣恭 擢流人 rm#xjts06612@孟瑤 、 rm#xjts23541@敬冕 爲將，
討 rm#xjts03770@哥舒晃 。

 rm#xjts06612@瑤 以大軍當其衝，
 rm#xjts23541@冕 自間道輕入，
丁未，
克 dm#dm02733@廣州 ，
斬 rm#xjts03770@哥舒晃 及其黨萬餘人。
# p 

 rm#xjts24772@嗣恭 之討 rm#xjts03770@晃 也，
 dm#dm02243@容管 經略使 rm#r02690@王翃 遣將將兵助之；
 dm#dm07296@西原 賊帥 rm#xjts03663@覃問 乘虚襲 dm#dm02240@容州 ，
 rm@翃 伏兵撃擒之。
# p 

十二月，
囘紇千騎寇 dm#dm01538@夏州 ，
州將 rm@梁榮宗 破之於 dm#dm05527@烏水 。

 rm#xjts01384@郭子儀 遣兵三千救 dm#dm01538@夏州 ，
囘紇遁去。

# p 

 rm#r00165@元載 、 rm#r02687@王縉 奏 dm#dm08950@魏州 鹽貴，
請禁鹽入其境以困之。

上不許，
曰：
「 rm#r02821@承嗣 負朕，
百姓何罪！」

# p 

 rm#r02821@田承嗣 請入朝，
 rm#xjts13396@李正己 屡爲之上表，
乞許其自新。

*** 十一年
# year 0776
# p 

春，
正月，
壬辰，
遣諫議大夫 rm#r02021@杜亞 使 dm#dm08950@魏州 宣慰。

# p 

辛亥，
 dm#dm07316@西川 節度使 rm#r00914@崔寧 奏破吐蕃四節度及突厥、吐谷渾、氐、羌羣蠻衆二十餘萬，
斬首萬餘級。

# p 

二月，
庚辰，
 rm#r02821@田承嗣 復遣使上表，
請入朝。

上乃下詔，
赦 rm#r02821@承嗣 罪，
復其官爵，
聽與家屬入朝，
其所部拒朝命者，
一切不問。
# p 

辛巳，
増 dm#dm03677@朔方 五城戍兵，
以備囘紇。

# p 

三月，
戊子，
 dm#dm04709@河陽 軍亂，
逐監軍 rm#xjts23982@冉庭蘭 出城，
大掠三日。

 rm@庭蘭 成備而入，
誅亂者數十人，
乃定。

# p 

五月，
 dm#dm04540@汴宋 留後 rm#r02828@田神玉 卒。

都虞候 rm#xjts13521@李靈曜 殺兵馬使、 dm#dm05457@濮州 刺史 rm#xjts06659@孟鑒 ，
北結 rm#r02821@田承嗣 爲援。

癸巳，
以 dm#dm04412@永平 節度使 rm@李勉 兼 dm#dm04537@汴 、 dm#dm02093@宋 等八州留後。

乙未，
以 rm#xjts13521@靈曜 爲 dm#dm05457@濮州 刺史，
 rm#xjts13521@靈曜 不受詔。

六月，
戊午，
以 rm#xjts13521@靈曜 爲 dm#dm04540@汴宋 留後，
遣使宣慰。


# p 

秋，
九月，
 rm#r02821@田承嗣 遣兵寇 dm#dm05229@滑州 ，
敗 rm@李勉 。
九七
# p 

吐蕃寇 dm#dm06130@石門 ，
入 dm#dm08225@長澤川 。

# p 

八月，
丙寅，
加 dm#dm06013@盧龍 節度使 rm#r01577@朱泚 同平章事。

# p 

 rm#xjts13521@李靈曜 既爲留後，
益驕慢，
悉以其黨爲管内八州刺史、縣令，
欲效 dm#dm04656@河北 諸鎭。

甲申，
詔 dm#dm05005@淮西 節度使 rm#r03193@李忠臣 、 dm#dm04412@永平 節度使 rm@李勉 、 dm#dm04709@河陽 三城使 rm#r04181@馬燧 討之。

 dm#dm04984@淮南 節度使 rm#r03921@陳少遊 、 dm#dm04964@淄青 節度使 rm#xjts13396@李正己 皆進兵撃 rm#xjts13521@靈曜 。
# p 

 dm#dm04540@汴宋 兵馬使、攝節度副使 rm#xjts15374@李僧惠 ，
 rm#xjts13521@靈曜 之謀主也。

 dm#dm02098@宋州 牙門將 rm@劉昌 遣僧 rm#xjts27205@神表 潛説 rm#xjts15374@僧惠 ；
 rm#xjts15374@僧惠 召問計，
 rm@昌 爲之泣陳逆順。

 rm#xjts15374@僧惠 乃與 dm#dm04540@汴宋 牙將 rm#xjts00254@高憑 、 rm@石隱金 遣 rm#xjts27205@神表 奉表詣 dm#dm08170@京師 ，
請討 rm#xjts13521@靈曜 。

九月，
壬戌，
以 rm#xjts15374@僧惠 爲 dm#dm02098@宋州 刺史，
 rm#xjts00254@憑 爲 dm#dm03641@曹州 刺史，
 rm@隱金 爲 dm#dm07905@鄆州 刺史。僧曾
# p 

乙丑，
 rm#r03193@李忠臣 、 rm#r04181@馬燧 軍于 dm#dm07949@鄭州 ，
 rm#xjts13521@靈曜 引兵逆戰；
兩軍不意其至，
退軍 dm#dm05214@滎澤 ，
 dm#dm05005@淮西 軍士潰去者什五六。

 dm#dm07949@鄭州 士民皆驚，
走入 dm#dm03880@東都 。

 rm#r03193@忠臣 將歸 dm#dm05005@淮西 ，
 rm#r04181@燧 固執不可，
曰：
「以順討逆，
何憂不克，
奈何自棄功名！」

堅壁不動。

 rm#r03193@忠臣 聞之，
稍收散卒，
數日皆集，
軍勢復振。

# p 

戊辰，
 rm#xjts13396@李正己 奏克 dm#dm07903@鄆 、 dm#dm05457@濮 二州。

壬申，
 rm#xjts15374@李僧惠 敗 rm#xjts13521@靈曜 兵于 dm#dm08496@雍丘 。

冬，
十月，
 rm#r03193@李忠臣 、 rm#r04181@馬燧 進撃 rm#xjts13521@靈曜 ，
 rm#r03193@忠臣 行 dm#dm04537@汴 南，
 rm#r04181@燧 行 dm#dm04537@汴 北，
屡破 rm#xjts13521@靈曜 兵；
壬寅，
與 rm#r03921@陳少遊 前軍合，
與 rm#xjts13521@靈曜 大戰於 dm#dm04541@汴州 城西，
 rm#xjts13521@靈曜 敗，
入城固守。

癸卯，
 rm#r03193@忠臣 等圍之。
# p 

 rm#r02821@田承嗣 遣 rm#r02819@田悦 將兵救 rm#xjts13521@靈曜 ，
敗 dm#dm04412@永平 、 dm#dm04964@淄青 兵於 dm#dm00906@匡城 ，
乘勝進軍 dm#dm04541@汴州 ，
營於城北數里。

丙午，
 rm#r03193@忠臣 遣裨將 rm#xjts14253@李重倩 將輕騎數百夜入其營，
縱横貫穿，
斬數十人而還，
營中大駭；
 rm#r03193@忠臣 、 rm#r04181@燧 因以大軍乘之，
鼓譟而入，
 rm#r02819@悦 衆不戰而潰。

 rm#r02819@悦 脱身北走，
將士死者相枕藉，
不可勝數。

 rm#xjts13521@靈曜 聞之，
開門夜遁，
 dm#dm04541@汴州 平。

 rm#xjts14253@重倩 ，
本奚也。

丁未，
 rm#xjts13521@靈曜 至 dm#dm08724@韋城 ，
 dm#dm04412@永平 將 rm#xjts22037@杜如江 擒之。乙巳
# p 

 rm#r04181@燧 知 rm#r03193@忠臣 暴戾，
以己功讓之，
不入 dm#dm04539@汴城 ，
引軍西屯 dm#dm03917@板橋 。

 rm#r03193@忠臣 入城，
果專其功；
 dm#dm02098@宋州 刺 rm@史李僧 惠與之爭功，
 rm#r03193@忠臣 因會撃殺之；
又欲殺 rm@劉昌 ，
 rm@昌 遁逃得免。
# p 

甲寅，
 rm@李勉 械送 rm#xjts13521@李靈曜 至 dm#dm08170@京師 ；
斬之。


# p 

十二月，
丁亥，
 rm#xjts13396@李正己 、 rm#r01157@李寶臣 竝加同平章事。
# p 

 dm#dm04920@涇原 節度使 rm#r04182@馬璘 疾亟，
以行軍司馬 rm#r02349@段秀實 知節度事，
付以後事。

 rm#r02349@秀實 嚴兵以備非常，
丙申，
 rm#r04182@璘 薨，
軍中奔哭者數千人，
喧咽門屏，
 rm#r02349@秀實 悉不聽入。

命押牙 rm#xjts25010@馬頔 治喪事於内，
 rm#xjts15879@李漢惠 接賓客於外，
妻妾子孫位於堂，
宗族位於庭，
將佐位於前，
牙士卒哭於營伍，
百姓各守其家。

有離立偶語於衢路，
輒執而囚之；
非護喪從行者無得遠送。

致祭拜哭，
皆有儀節，
送喪近遠，
皆有定處，
違者以軍法從事。

都虞候 rm#xjts23871@史廷幹 、兵馬使 rm#xjts08466@崔珍 、十將 rm#xjts04979@張景華 謀因喪作亂，
 rm#r02349@秀實 知之，
奏 rm#xjts23871@廷幹 入宿衞，
徙 rm#xjts08466@珍 屯 dm#dm08637@靈臺 ，
補 rm#xjts04979@景華 外職，
不戮一人，
軍府晏然。

# p 

 rm#r04182@璘 家富有無算，
治第 dm#dm08170@京師 ，
甲於勳貴，
中堂費二十萬緡，
他室所減無幾，
其子孫無行，
家貲尋盡。


# p 

戊戌，
 dm#dm03524@昭義 節度使 rm#xjts14105@李承昭 表稱疾篤；
以 dm#dm05401@澤潞 行軍司馬 rm#r01783@李抱眞 兼知 dm#dm06175@磁 、 dm#dm07814@邢 兩州留後。

# p 

庚戌，
加 dm#dm05005@淮西 節度使 rm#r03193@李忠臣 同平章事，
仍領 dm#dm04541@汴州 刺史，
治 dm#dm04541@汴州 。

*** 十二年
# year 0777
# p 

春，
三月，
乙卯，
兵部尚書、同平章事、 dm#dm09004@鳳翔 ‧ dm#dm03110@懷澤潞 ‧ dm#dm06286@秦隴 節度使 rm#r00795@李抱玉 薨，
弟 rm#r01783@抱眞 仍領 dm#dm03110@懷澤潞 留後。
# p 

癸亥，
以 dm#dm04672@河東 行軍司馬 rm#r04319@鮑防 爲 dm#dm04672@河東 節度使。

 rm#r04319@防 ，
 dm#dm07274@襄州 人也。
# p 

 rm#r02821@田承嗣 竟不入朝，
又助 rm#xjts13521@李靈曜 ，
上復命討之。

 rm#r02821@承嗣 乃復上表謝罪。

上亦無如之何，
庚午，
悉復 rm#r02821@承嗣 官爵，
仍令不必入朝。

# p 

中書侍郎、同平章事 rm#r00165@元載 專横，
黄門侍郎、同平章事 rm#r02687@王縉 附之，
二人倶貪。

 rm#r00165@載 妻 rm#xjts03046@王氏 及子 rm#xjts03366@伯和 、 rm#xjts03362@仲武 ，
 rm#r02687@縉 弟、妹及尼出入者，
爭納賄賂。

又以政事委羣吏，
士之求進者，
不結其子弟及主書 rm#xjts08025@卓英倩 等，
無由自達。

上含容累年，
 rm#r00165@載 、 rm#r02687@縉 不悛。

# p 

上欲誅之，
恐左右漏泄，
無可與言者，
獨與左金吾大將軍 rm#r00413@呉湊 謀之。

 rm#r00413@湊 ，
上之舅也。

會有告 rm#r00165@載 、 rm#r02687@縉 夜醮圖爲不軌者，
庚辰，
上御 dm#dm02831@延英殿 ，
命 rm#r00413@湊 收 rm#r00165@載 、 rm#r02687@縉 於政事堂，
又收 rm#xjts03362@仲武 及 rm#xjts08025@卓英倩 等繋獄。

命吏部尚書 rm#r00276@劉晏 與御史大夫 rm#r01844@李涵 等同鞫之，
問端皆出禁中，
仍遣中使詰以陰事，
 rm#r00165@載 、 rm#r02687@縉 皆伏罪。

是日，
先杖殺左衞將軍、知内侍省事 rm#r06744@董秀 於禁中，
乃賜 rm#r00165@載 自盡於 dm#dm06979@萬年縣 。

 rm#r00165@載 請主者：
「願得快死！」

主者曰：
「相公須受少汚辱，
勿怪！」

乃脱穢韈塞其口而殺之。

 rm#r02687@王縉 初亦賜自盡，
 rm#r00276@劉晏 謂 rm#r01844@李涵 等曰：
「故事，
重刑覆奏，
況大臣乎！

且法有首從，
宜更稟進止。」

 rm#r01844@涵 等從之。

上乃貶 rm#r02687@縉  dm#dm03988@栝州 刺史。

 rm#r00165@載 妻 rm#xjts03046@王氏 ，
 rm#r02632@忠嗣 之女也，
及子 rm#xjts03366@伯和 、 rm#xjts03362@仲武 、 rm#xjts03346@季能 皆伏誅。

有司籍 rm#r00165@載 家財，
胡椒至八百石，
他物稱是。

# p 

夏，
四月，
壬午，
以太常卿 rm#r02239@楊綰 爲中書侍郎，
禮部侍郎 rm@常袞 爲門下侍郎，
竝同平章事。

 rm#r02239@綰 性清儉簡素，
制下之日，
朝野相賀。

 rm#xjts01384@郭子儀 方宴客，
聞之，
減坐中聲樂五分之四。

 dm#dm00427@京兆 尹 rm#r04338@黎幹 ，
騶從甚盛，
即日省之，
止存十騎。

中丞 rm@崔寛 ，
第舍宏侈，
亟毀撤之。
# p 

癸未，
貶吏部侍郎 rm#r02224@楊炎 、諫議大夫 rm#r04118@韓洄 、 rm#r00342@包佶 、起居舍人 rm#xjts20790@韓會 等，
皆 rm#r00165@載 黨也。

 rm#r02224@炎 ，
 dm#dm09004@鳳翔 人。

 rm#r00165@載 常引有文學才望者一人親厚之，
異日欲以代己，
故 rm#r02224@炎 及於貶。

 rm#r04118@洄 ，
 rm#r04122@滉 之弟。

 rm#xjts20790@會 ，
 dm#dm01077@南陽 人也。

上初欲盡誅 rm#r02224@炎 等，
 rm#r00413@呉湊 諫救百端，
始貶官。
十餘人
# p 

丁酉，
吐蕃寇 dm#dm09164@黎 、 dm#dm08477@雅州 ；
 dm#dm07316@西川 節度使 rm#r00914@崔寧 撃破之。
# p 

 rm#r00165@元載 以仕進者多樂 dm#dm08170@京師 ，
惡其逼己，
乃制俸祿，
厚外官而薄京官，
京官不能自給，
常從外官乞貸。

 rm#r02239@楊綰 、 rm@常袞 奏京官俸太薄；
己酉，
詔加京官俸，
歳約十五萬六千餘緡。

# p 

五月，
辛亥，
詔自都團練使外，
悉罷諸州團練守捉使。

又令諸使非軍事要急，
無得召刺史及停其職務，
差人權攝。

又定諸州兵，
皆有常數，
其召募給家糧、春冬衣者，
謂之「官健」；
差點土人，
春夏歸農、秋冬追集、給身糧醤菜者，
謂之「團結」。

自兵興以來，
州縣官俸給不一，
重以 rm#r00165@元載 、 rm#r02687@王縉 隨情徇私，
刺史月給或至千緡、或數十緡，
至是，
始定節度使以下至主簿、尉俸祿，
掊多益寡，
上下有敍，
法制粗立。

# p 

庚午，
上遣中使發 rm#r00165@元載 祖父墓，
斲棺棄尸，
毀其家廟，
焚其木主。

戊寅，
 rm#xjts08025@卓英倩 等皆杖死。

 rm#xjts08025@英倩 之用事也，
弟 rm#r00349@英璘 横於郷里。

及 rm#xjts08025@英倩 下獄，
 rm#r00349@英璘 遂據險作亂；
上發禁兵討之，
乙巳，
 dm#dm08028@金州 刺史 rm#xjts06357@孫道平 撃擒之。
# p 

上方倚 rm#r02239@楊綰 ，
使釐革弊政，
會 rm#r02239@綰 有疾，
秋，
七月，
己巳，
薨。

上痛悼之甚，
謂羣臣曰：
「天不欲朕致太平，
何奪朕 rm#r02239@楊綰 之速！」

# p 

八月，
癸未，
賜 dm#dm03818@東川 節度使 rm#xjts15273@鮮于叔明 姓 rm@李氏 。

# p 

 rm#r00165@元載 、 rm#r02687@王縉 之爲相也，
上日賜以内廚御饌，
可食十人，
遂爲故事。

癸卯，
 rm@常袞 與 rm#r01577@朱泚 上言：
「餐錢已多，
乞停賜饌。」

許之。

 rm@袞 又欲辭堂封，
同列不可而止。

時人譏 rm@袞 ，
以爲：
「朝廷厚祿，
所以養賢，
不能，
當辭位，
不當辭祿。」


# p 

臣 rm@光 曰：
「君子恥食浮於人；
 rm@袞 之辭祿，
廉恥存焉，
與夫固位貪祿者，
不猶愈乎！

詩云：『彼君子兮，不素餐兮！』如 rm@袞 者，
亦未可以深譏也。」

# p 

 rm#r02239@楊綰 、 rm@常袞 薦 dm#dm05146@湖州 刺史 rm#r04147@顏眞卿 ，
上即日召還；
甲辰，
以爲刑部尚書。

 rm#r02239@綰 、 rm@袞 又薦 dm#dm04984@淮南 判官 dm#dm04534@汲 人 rm#r03890@關播 ，
擢爲都官員外郎。

# p 

九月，
辛酉，
以 dm#dm01437@四鎭 、 dm#dm00860@北庭 行營兼 dm#dm04920@涇原 、 dm#dm07951@鄭潁 節度副使 rm#r02349@段秀實 爲節度使。

 rm@秀實 軍令簡約，
有威惠，
奉身清儉，
室無姬妾，
非公會，
未嘗飮酒聽樂。
# p 

吐蕃八萬衆軍於 dm#dm01114@原州 北 dm#dm08225@長澤監 ，
己巳，
破 dm#dm03419@方渠 ，
入 dm#dm03214@拔谷 ；
 rm#xjts01384@郭子儀 使裨將 rm#r01775@李懷光 救之，
吐蕃退。

庚午，
吐蕃寇 dm#dm01476@坊州 。
# p 

冬，
十月，
乙酉，
 dm#dm07316@西川 節度使 rm#r00914@崔寧 奏大破吐蕃於 dm#dm03703@望漢城 。

# p 

先是，
秋霖，
 dm#dm04652@河中府 池鹽多敗。

戸部侍郎判度支 rm#r04122@韓滉 恐鹽戸減税，
丁亥，
奏雨雖多，
不害鹽，
仍有瑞鹽生。

上疑其不然，
遣諫議大夫 dm#dm06555@義興  rm#r03223@蒋鎭 往視之。

# p 

吐蕃寇 dm#dm09056@鹽 、 dm#dm01538@夏州 ，
又寇長武；
 rm#xjts01384@郭子儀 遣將拒卻之。

# p 

以 dm#dm04414@永平軍 押牙 dm#dm00906@匡城  rm#r00292@劉洽 爲 dm#dm02098@宋州 刺史。

仍以 dm#dm02093@宋 、 dm#dm04727@泗 二州隸 dm#dm04414@永平軍 。
# p 

 dm#dm00427@京兆 尹 rm#r04338@黎幹 奏秋霖損稼，
 rm#r04122@韓滉 奏 rm#r04338@幹 不實；
上命御史按視，
丁未，
還奏，
「所損凡三萬餘頃。」

 dm#dm05106@渭南 令 rm@劉澡 阿附度支，
稱縣境苗獨不損；
御史 rm#xjts23610@趙計 奏與 rm#xjts05644@澡 同。

上曰：
「霖雨溥博，
豈得 dm#dm05106@渭南 獨無！」

更命御史 rm@朱敖 視之，
損三千餘頃。

上歎息久之，
曰：
「縣令，
字人之官，
不損猶應言損，
迺不仁如是乎！」

貶 rm#xjts05644@澡  dm#dm01019@南浦 尉，
 rm@計  dm#dm05403@澧州 司戸，
而不問 rm#r04122@滉 。

# p 

十一月，
壬子，
 dm#dm02401@山南西道 節度使 rm#r01212@張獻恭 奏破吐蕃萬餘衆於 dm#dm02437@岷州 。

# p 

丙辰，
 rm#r03223@蒋鎭 還，
奏言「瑞鹽實如 rm#r04122@韓滉 所言」，
仍上表賀，
請宣付史臣，
錫以嘉名。

上從之，
賜號 dm#dm02319@寶應靈應池 。

時人醜之。幷置神祠
# p 

十二月，
丙戌，
 rm#r01577@朱泚 自 dm#dm04924@涇州 還 dm#dm08170@京師 。

# p 

丁亥，
 rm#r00914@崔寧 奏破吐蕃十餘萬衆，
斬首八千餘級。

# p 

庚子，
以 rm#r01577@朱泚 兼 dm#dm08458@隴右 節度使，
知 dm#dm04695@河西 、 dm#dm05401@澤潞 行營。
# p 

 dm#dm02660@平盧 節度使 rm#xjts13396@李正己 先有 dm#dm04961@淄 、 dm#dm08642@青 、 dm#dm09204@齊 、 dm#dm04887@海 、 dm#dm05863@登 、 dm#dm06953@莱 、 dm#dm04580@沂 、 dm#dm02259@密 、 dm#dm02976@徳 、 dm#dm04071@棣 十州之地，
及 rm#xjts13521@李靈曜 之亂，
諸道合兵攻之，
所得之地，
各爲己有，
 rm#xjts13396@正己 又得 dm#dm03636@曹 、 dm#dm05457@濮 、 dm#dm02948@徐 、 dm#dm00663@兗 、 dm#dm07903@鄆 五州，
因自 dm#dm08665@青州 徙治 dm#dm07905@鄆州 ，
使其子前 dm#dm04961@淄州 刺史 rm@納 守 dm#dm08665@青州 。

 rm#xjts13396@正己 用刑嚴峻，
所在不敢偶語；
然法令齊一，
賦均而輕，
擁兵十萬，
雄據東方，
鄰藩皆畏之。

是時 rm#r02821@田承嗣 據 dm#dm08945@魏 、 dm#dm01088@博 、 dm#dm06025@相 、 dm#dm00026@衞 、 dm#dm04838@洺 、 dm#dm07512@貝 、 dm#dm05414@澶 七州，
 rm#r01157@李寶臣 據 dm#dm03017@恆 、 dm#dm03494@易 、 dm#dm07617@趙 、 dm#dm02116@定 、 dm#dm05013@深 、 dm#dm00712@冀 、 dm#dm05208@滄 七州，
各擁衆五萬；
 rm#r02124@梁崇義 據 dm#dm07261@襄 、 dm#dm07938@鄧 、 dm#dm01472@均 、 dm#dm03162@房 、 dm#dm02970@復 、 dm#dm07856@郢 六州，
有衆二萬；
相與根據蟠結，
雖奉事朝廷而不用其法令，
官爵、甲兵、租賦、刑殺皆自專之，
上寛仁，
一聽其所爲。

朝廷或完一城，
増一兵，
輒有怨言，
以爲猜貳，
常爲之罷役；
而自於境内築壘、繕兵無虚日。

以是雖在 dm#dm00255@中國 名藩臣，
而實如蠻貊異域焉。癸卯，以納爲青州刺史
*** 十三年
# year 0778
# p 

春，
正月，
辛酉，
敕毀 dm#dm05901@白渠 支流碾磑以漑田。

 rm#r03705@昇平公主 有二磑，
入見於上，
請存之。

上曰：
「吾欲以利蒼生，
汝識吾意，
當爲衆先。」

公主即日毀之。
# p 

戊辰，
囘紇寇 dm#dm01774@太原 ，
 dm#dm04672@河東 押牙 dm#dm04731@泗水  rm#r01932@李自良 曰：
「囘紇精鋭遠來求鬬，
難與爭鋒；
不如築二壘於歸路，
以兵戍之。

虜至，
堅壁勿與戰，
彼師老自歸，
乃出軍乘之。

二壘抗其前，
大軍蹙其後，
無不捷矣。」

留後 rm#r04319@鮑防 不從，
遣大將 rm#xjts06926@焦伯瑜 等逆戰；
癸酉，
遇虜於陽曲，
大敗而還，
死者萬餘人。

囘紇縱兵大掠。

二月，
 dm#dm00485@代州 都督 rm#r01110@張光晟 撃破之於 dm#dm06517@羊武谷 ，
乃引去。

上亦不問囘紇入寇之故，
待之如初。
# p 

己亥，
吐蕃遣其將 rm#xjts24942@馬重英 帥衆四萬寇 dm#dm08619@靈州 ，
奪 dm#dm01503@填漢 、 dm#dm02966@御史 、 dm#dm02380@尚書 三渠水口以弊屯田。

# p 

三月，
甲戌，
囘紇使還，
過 dm#dm04651@河中 ，
 dm#dm03677@朔方 軍士掠其輜重，
因大掠坊市。
# p 

夏，
四月，
甲辰，
吐蕃寇 dm#dm08619@靈州 ，
 dm#dm03677@朔方 留後 rm#xjts28791@常謙光 撃破之。
# p 

六月，
戊戌，
 dm#dm08458@隴右 節度使 rm#r01577@朱泚 獻猫鼠同乳不相害者以爲瑞；
常袞帥百官稱賀。

中書舍人 rm#r00975@崔祐甫 獨不賀，
曰：
「物反常爲妖。

猫捕鼠，
乃其職也，
今同乳，
妖也。

何乃賀爲！

宜戒法吏之不察奸、邊吏之不禦寇者，
以承天意。」

上嘉之。

 rm#r00975@祐甫 ，
 rm@沔 之子也。

秋，
七月，
以 rm#r00975@祐甫 知吏部選事。

 rm#r00975@祐甫 數以公事與 rm@常袞 爭，
由是惡之。
壬子
# p 

戊午，
 rm#xjts01384@郭子儀 奏以囘紇猶在塞上，
邊人恐懼，
請遣 dm#dm07812@邠州 刺史 rm#r02462@渾瑊 將兵鎭 dm#dm03230@振武軍 ，
從之。

囘紇始去。

# p 

辛未，
吐蕃將 rm#xjts24942@馬重英 二萬衆寇 dm#dm09056@鹽 、 dm#dm03083@慶 二州，
 rm#xjts01384@郭子儀 遣 dm#dm03677@朔方 都虞候 rm#r01775@李懷光 撃卻之。河東
# p 

八月，
乙亥，
 dm#dm03139@成徳 節度使 rm#r01157@李寶臣 請復姓 rm@張 ，
許之。

# p 

吐蕃二萬衆寇 dm#dm08081@銀 、 dm#dm09094@麟州 ，
略黨項雜畜，
 rm#xjts01384@郭子儀 遣 rm#r01775@李懷光 撃破之。
# p 

上悼念 rm#r02570@貞懿皇后 不已，
殯於内殿，
累年不忍葬；
丁酉，
始葬于 dm#dm06908@莊陵 。

# p 

九月，
庚午，
吐蕃萬騎下 dm#dm08677@青石嶺 ，
逼 dm#dm04924@涇州 ；
詔 rm#xjts01384@郭子儀 、 rm#r01577@朱泚 與 rm#r02349@段秀實 共卻之。
# p 

冬，
十二月，
丙戌，
以吏部尚書、轉運‧鹽鐵等使 rm#r00276@劉晏 爲左僕射，
知三銓及使職如故。

# p 

 rm#xjts01384@郭子儀 入朝，
命判官 dm#dm00427@京兆  rm#r02068@杜黄裳 主留務。

 rm#r01775@李懷光 陰謀代 rm#xjts01384@子儀 ，
矯爲詔書，
欲誅大將 rm#xjts12523@温儒雅 等。

 rm#r02068@黄裳 察其詐，
以詰 rm#r01775@懷光 ；
 rm#r01775@懷光 流汗服罪。

於是諸將之難制者，
 rm#r02068@黄裳 矯 rm#xjts01384@子儀 之命，
皆出之於外，
軍府乃安。
# p 

以給事中 rm#r02021@杜亞 爲 dm#dm04509@江西 觀察使。
# p 

上召 dm#dm04509@江西 判官 rm@李泌 入見，
語以 rm#r00165@元載 事，
曰：
「與卿別 y@八年 ，
乃能誅此賊。

頼太子發其陰謀，
不然，
幾不見卿。」

對曰：
「臣昔日固嘗言之。

陛下知羣臣有不善，
則去之；
含容太過，
故至於此。」

上曰：
「事亦應十全，
不可輕發。」

上因言：
「朕面屬卿於 rm#xjts24772@路嗣恭 ，
而 rm#xjts24772@嗣恭 取 rm#r00165@載 意，
奏卿爲 dm#dm07172@虔州 別駕。

 rm#xjts24772@嗣恭 初平 dm#dm02527@嶺南 ，
獻琉璃盤，
徑九寸，
朕以爲至寶。

及破 rm#r00165@載 家，
得 rm#xjts24772@嗣恭 所遺 rm#r00165@載 琉璃盤，
徑尺。

俟其至，
當與卿議之。」

 rm@泌 曰：
「 rm#xjts24772@嗣恭 爲人，
小心，
善事人，
畏權勢，
精勤吏事而不知大體。

昔爲縣令，
有能名；
陛下未暇知之，
而爲 rm#r00165@載 所用，
故爲之盡力。

陛下誠知而用之，
彼亦爲陛下盡力矣。

 dm#dm07172@虔州 別駕，
臣自欲之，
非其罪也。

且 rm#xjts24772@嗣恭 新立大功，
陛下豈得以一琉璃盤罪之邪！」

上意乃解，
以 rm#xjts24772@嗣恭 爲兵部尚書。

# p 

 rm#xjts01384@郭子儀 以 dm#dm03677@朔方 節度副使 rm#xjts04953@張曇 性剛率，
謂其以武人輕己，
銜之；
孔目官 rm@呉曜 爲 rm#xjts01384@子儀 所任，
因而構之。

 rm#xjts01384@子儀 怒，
誣奏 rm#xjts04953@曇 扇動軍衆，
誅之。

掌書記 rm#xjts00338@高郢 力爭之，
 rm#xjts01384@子儀 不聽，
奏貶 rm#xjts00338@郢  dm#dm05659@猗氏 丞。

既而僚佐多以病求去，
 rm#xjts01384@子儀 悔之，
悉薦之於朝，
曰：
「 rm@呉曜 誤我。」

遂逐之。

# p 

 rm@常袞 言於上曰：
「陛下久欲用 rm@李泌 ，
昔 rm#rt0520@漢宣帝 欲用人爲公卿，
必先試理人，
請且以爲刺史，
使周知人間利病，
俟報政而用之。」


*** 十四年
# year 0779
# p 

春，
正月，
壬戌，
以 rm@李泌 爲 dm#dm05403@澧州 刺史。

# p 

二月，
癸未，
 dm#dm08946@魏博 節度使 rm#r02821@田承嗣 薨。

有子十一人，
以其姪中軍兵馬使 rm#r02819@悦 爲才，
使知軍事，
而諸子佐之。

甲申，
以 rm#r02819@悦 爲 dm#dm08946@魏博 留後。

# p 

 dm#dm05005@淮西 節度使 rm#r03193@李忠臣 ，
貪殘好色，
將吏妻女美者，
多逼淫之，
悉以軍政委妹壻節度副使 rm#xjts04891@張惠光 。

 rm#xjts04891@惠光 挾勢暴横，
軍州苦之。

 rm#r03193@忠臣 復以 rm#xjts04891@惠光 子爲牙將，
暴横甚於其父。

左廂都虞候 rm#r01719@李希烈 ，
 rm#r03193@忠臣 之族子也，
爲衆所服。

 rm#r01719@希烈 因衆心怨怒，
三月，
丁未，
與大將 rm#xjts03305@丁暠 等殺 rm#xjts04891@惠光 父子而逐 rm#r03193@忠臣 。

 rm#r03193@忠臣 單騎奔 dm#dm08170@京師 ，
上以其有功，
使以檢校司空、同平章事留 dm#dm08170@京師 ；
以 rm#r01719@希烈 爲 dm#dm07086@蔡州 刺史、 dm#dm05005@淮西 留後。

以 dm#dm04412@永平 節度使 rm@李勉 兼 dm#dm04541@汴州 刺史，
増領 dm#dm04537@汴 、 dm#dm05327@潁 二州，
徙鎭 dm#dm04541@汴州 。

# p 

辛酉，
以 dm#dm02243@容管 經略使 rm#r02690@王翃 爲 dm#dm04651@河中 少尹、知府事。

 dm#dm04672@河東 副元帥留後部將 rm#r00178@凌正 暴横，
 rm#r02690@翃 抑之。

 rm#r00178@正 與其徒乘夜作亂，
 rm#r02690@翃 知之，
故縮漏水數刻以差其期，
賊驚，
潰走，
擒 rm#r00178@正 ，
誅之，
軍府乃安。
# p 

 dm#dm03139@成徳 節度使 rm#r01157@張寶臣 既請復姓，
又不自安，
更請賜姓；
夏，
四月，
癸未，
復賜姓 rm@李 。

# p 

五月，
癸卯，
上始有疾，
辛酉，
制皇太子監國。

是夕，
上崩于 dm#dm06403@紫宸 之内殿，
遺詔以 rm#xjts01384@郭子儀 攝冢宰。

癸亥，
 rm@徳宗 即位，
在諒陰中，
動遵禮法；
嘗召 rm#r04087@韓王迥 食，
食馬齒羹，
不設鹽、酪。

# p 

 rm@常袞 性剛急，
爲政苛細，
不合衆心。

時羣臣朝夕臨，
 rm@袞 哭委頓，
從吏或扶之。

中書舍人 rm#r00975@崔祐甫 指以示衆曰：
「臣哭君前，
有扶禮乎！」

 rm@袞 聞，
益恨之。

會議羣臣喪服，
 rm@袞 以爲：
「禮，
臣爲君斬衰三年。

 rm#rt0515@漢文 權制，
猶三十六日。

 rm#r01837@高宗 以來，
皆遵 dyn#ch129@漢 制。

及 rm#xjts00542@玄宗 、 rm#r01661@肅宗 之喪，
始服二十七日。

今遺詔云，
『天下吏人，
三日釋服。』

古者卿大夫從君而服，
皇帝二十七日而除，
在朝羣臣亦當如之。」

 rm#r00975@祐甫 以爲：
「遺詔，
無朝臣、庶人之別。

朝野内外，
莫非天下，
凡百執事，
孰非吏人！

皆應釋服。」

相與力爭，
聲色陵厲。

 rm@袞 不能堪，
乃奏 rm#r00975@祐甫 率情變禮，
請貶 dm#dm05376@潮州 刺史；
上以爲太重，
閏月，
壬申，
貶 rm#r00975@祐甫 爲 dm#dm04660@河南 少尹。三日
# p 

初，
 rm#r01661@肅宗 之世，
天下務殷，
宰相常有數人，
更直決事，
或休沐各歸私第，
詔直事者代署其名而奏之，
自是踵爲故事。

時 rm#xjts01384@郭子儀 、 rm#r01577@朱泚 雖以軍功爲宰相，
皆不預朝政，
 rm@袞 獨居政事堂，
代二人署名奏 rm#r00975@祐甫 。

 rm#r00975@祐甫 既貶，
二人表言其非罪，
上問：
「卿向言可貶，
今云非罪，
何也？」
二人對，
初不知。

上初即位，
以 rm@袞 爲欺罔，
大駭。

甲辰，
百官衰絰，
序立于 dm#dm03668@月華門 ，
有制，
貶 rm@袞 爲 dm#dm05376@潮州 刺史，
以 rm#r00975@祐甫 爲門下侍郎、同平章事，
聞者震悚。

 rm#r00975@祐甫 至 dm#dm03519@昭應 而還。

既而羣臣喪服竟用 rm@袞 議。
# p 

上時居諒陰，
庶政皆委於 rm#r00975@祐甫 ，
所言無不允。

初，
 y@至徳 以後，
天下用兵，
諸將競論功賞，
故官爵不能無濫。

及 y@永泰 以來，
天下稍平，
而 rm#r00165@元載 、 rm#r02687@王縉 秉政，
四方以賄求官者相屬於門，
大者出於 rm#r00165@載 、 rm#r02687@縉 ，
小者出於 rm#xjts08025@卓英倩 等，
皆如所欲而去。

及 rm@常袞 爲相，
思革其弊，
杜絶僥幸，
四方奏請，
一切不與；
而無所甄別，
賢愚同滯。

 rm#r00975@崔祐甫 代之，
欲收時望，
推薦引拔，
常無虚日；
作相未二百日，
除官八百人，
前後相矯，
終不得其適。

上嘗謂 rm#r00975@祐甫 曰：
「人或謗卿，
所用多渉親故，
何也？」
對曰：
「臣爲陛下選擇百官，
不敢不詳愼。

苟平生未之識，
何以諳其才行而用之。」

上以爲然。
# p 

臣 rm@光 曰：
「臣聞用人者，
無親疏、新故之殊，
惟賢、不肖之爲察。

其人未必賢也，
以親故而取之，
固非公也；
苟賢矣，
以親故而捨之，
亦非公也。

夫天下之賢，
固非一人所能盡也，
若必待素識熟其才行而用之，
所遺亦多矣。

古之爲相者則不然，
舉之以衆，
取之以公。

衆曰賢矣，
己雖不知其詳，
姑用之，
待其無功，
然後退之，
有功則進之；
所舉得其人則賞之，
非其人則罰之。

進退賞罰，
皆衆人所共然也，
己不置豪髮之私於其間。

苟推是心以行之，
又何遺賢曠官之足病哉！」

# p 

詔罷省四方貢獻之不急者，
又罷 dm#dm04062@梨園 使及樂工三百餘人，
所留者悉隸太常。


# p 

 rm#xjts01384@郭子儀 以司徒、中書令領 dm#dm04651@河中 尹、 dm#dm08619@靈州 大都督、 dm#dm01394@單于 ‧ dm#dm08123@鎭北 大都護、 dm#dm08283@關内 ‧ dm#dm04672@河東 副元帥、 dm#dm03677@朔方 節度、 dm#dm08283@關内 支度‧鹽池‧六城水運大使、押蕃部幷營田及 dm#dm04714@河陽道 觀察等使，
權任既重，
功名復大，
性寛大，
政令頗不肅，
 rm#xjts00683@代宗 欲分其權而難之，
久不決。

甲申，
詔尊 rm#xjts01384@子儀 爲尚父，
加太尉兼中書令，
増實封滿二千戸，
月給千五百人糧、二百馬食，
子弟、諸壻遷官者十餘人，
所領副元帥諸使悉罷之；
以其裨將 dm#dm04672@河東 、 dm#dm03677@朔方 都虞候 rm#r01775@李懷光 爲 dm#dm04651@河中 尹、 dm#dm07808@邠 ‧ dm#dm02291@寧 ‧ dm#dm03083@慶 ‧ dm#dm03533@晉 ‧ dm#dm06430@絳 ‧ dm#dm03068@慈 ‧ dm#dm08451@隰 節度使，
以 dm#dm03677@朔方 留後兼 dm#dm08619@靈州 長史 rm#xjts28791@常謙光 爲 dm#dm08619@靈州 大都督、 dm#dm07297@西受降城 ‧ dm#dm02148@定遠 ‧ dm#dm01738@天徳 ‧ dm#dm09056@鹽 ‧ dm#dm01532@夏 ‧ dm#dm07470@豐 等軍州節度使，
 dm#dm03230@振武軍 使 rm#r02462@渾瑊 爲 dm#dm01395@單于大都護 、 dm#dm03783@東 ‧ dm#dm00253@中 二 dm#dm01138@受降城 ‧ dm#dm03228@振武 ‧ dm#dm08123@鎭北 ‧ dm#dm06439@綏 ‧ dm#dm08081@銀 ‧ dm#dm09094@麟 ‧ dm#dm00812@勝 軍州節度使，
分領其任。

# p 

丙戌，
詔曰：
「 dm#dm05400@澤州 刺史 rm@李鷃 上慶雲圖。

朕以時和年豐爲嘉祥，
以進賢顯忠爲良瑞，
如卿雲、靈芝、珍禽、奇獸、怪草、異木，
何益於人！

布告天下，
自今有此，
無得上獻。」

内莊宅使上言諸州有官租萬四千餘斛，
上令分給所在充軍儲。

先是，
諸國屡獻馴象，
凡四十有二，
上曰：
「象費豢養而違物性，
將安用之！」

命縱於 dm#dm06883@荊山 之陽，
及豹、貀、鬬雞、獵犬之類，
悉縱之；
又出宮女數百人。

於是中外皆悦，
 dm#dm04964@淄青 軍士，
至投兵相顧曰：
「明主出矣，
吾屬猶反乎！」


# p 

戊子，
以 dm#dm05005@淮西 留後 rm#r01719@李希烈 爲節度使。

# p 

辛卯，
以 dm#dm04709@河陽 鎭遏使 rm#r04181@馬燧 爲 dm#dm04672@河東 節度使。

 dm#dm04672@河東 承 dm#dm05939@百井 之敗，
騎士單弱，
 rm#r04181@燧 悉召牧馬廝役，
得數千人，
教之數月，
皆爲精騎。

造甲必爲長短三等，
稱其所衣，
以便進趨。

又造戰車，
行則載兵甲，
止則爲營陳，
或塞險以遏奔衝；
器械無不精利。

居一年，
得選兵三萬。

辟 dm#dm00663@兗州 人 rm#r01148@張建封 爲判官，
署 rm#r01932@李自良  dm#dm00485@代州 刺史，
委任之。

# p 

兵部侍郎 rm#r04338@黎幹 ，
狡險諛佞，
與宦官特進 rm#r00253@劉忠翼 相親善。

 rm#r00253@忠翼 本名 rm#r00253@清潭 ，
恃寵貪縱。

二人皆爲衆所惡。

時人或言 rm#r04338@幹 、 rm#r00253@忠翼 嘗勸 rm#xjts00683@代宗 立 rm#xjts08040@獨孤貴𡚱 爲皇后，
𡚱子 rm#r04087@韓王迥 爲太子。

上即位，
 rm#r04338@幹 密乘轝詣 rm#r00253@忠翼 謀事；
事覺，
丙申，
 rm#r04338@幹 、 rm#r00253@忠翼 竝除名長流，
至 dm#dm07121@藍田 ，
賜死。
# p 

以戸部侍郎判度支 rm#r04122@韓滉 爲太常卿，
以吏部尚書 rm#r00276@劉晏 判度支。

先是 rm#r00276@晏 、 rm#r04122@滉 分掌天下財賦，
 rm#r00276@晏 掌 dm#dm04476@江南 、 dm#dm02398@山南 、 dm#dm04501@江淮 、 dm#dm02527@嶺南 ，
 rm#r04122@滉 掌 dm#dm08283@關内 、 dm#dm04672@河東 、 dm#dm00785@劍南 ，
至是，
 rm#r00276@晏 始兼之。

上素聞 rm#r04122@滉 掊克過甚，
故罷其利權，
尋出爲 dm#dm03544@晉州 刺史。
江河
# p 

 y@至徳初 ，
 rm#r03064@第五琦 始榷鹽以佐軍用，
及 rm#r00276@劉晏 代之，
法益精密。

初歳入錢六十萬緡，
末年所入逾十倍，
而人不厭苦。

 y@大暦末 ，
計一歳所入總一千二百萬緡，
而鹽利居其太半。

以鹽爲漕傭，
自 dm#dm04475@江 、 dm#dm04981@淮 至 dm#dm05115@渭橋 ，
率萬斛，
傭七千緡，
自 dm#dm04981@淮 以北，
列置巡院，
擇能吏主之，
不煩州縣而集事。征賦
# p 

六月，
己亥朔，
赦天下。
# p 

 dm#dm07316@西川 節度使 rm#r00914@崔寧 、 dm#dm04412@永平 節度使 rm@李勉 竝同平章事。

# p 

詔：
「天下冤滯，
州府不爲理，
聽詣三司使，
以中丞、舍人、給事中各一人，
日於朝堂受詞。

推決尚未盡者，
聽撾登聞鼓。

自今無得復奏置寺觀及請度僧尼。」

於是撾登聞鼓者甚衆。

右金吾將軍 rm#r03464@裴諝 上疏，
以爲：
「訟者所爭皆細故，
若天子一一親之，
則安用吏理乎！」

上乃悉歸之有司。


# p 

制：
「應山陵制度，
務從優厚，
當竭帑藏以供其費。」

刑部員外郎 rm#r00069@令狐峘 上疏諫，
其略曰：
「臣伏讀遺詔，
務從儉約，
若制度優厚，
豈顧命之意邪！」

上答詔，
略曰：
「非唯中朕之病，
抑亦成朕之美，
敢不聞義而徙！」

 rm#r00069@峘 ，
 rm#xjts27098@徳棻 之玄孫也。

# p 

庚子，
立皇子 rm#r01964@誦 爲 rm#r01964@宣王 ，
 rm#r03137@謨 爲 rm#r03137@舒王 ，
 rm#r03670@諶 爲 rm#r03670@通王 ，
 rm#r03351@諒 爲 rm#r03351@虔王 ，
 rm#r03112@詳 爲 rm#r03112@肅王 。

乙巳，
立皇弟 rm#r02869@迺 爲 rm#r02869@益王 ，
 rm@傀 爲 rm@蜀王 。

# p 

丙午，
舉 y@先天 故事，
六品以上清望官，
雖非供奉、侍衞之官，
日令二人更直待制，
以備顧問。

# p 

庚戌，
以 rm#r01577@朱泚 爲 dm#dm09004@鳳翔 尹。

# p 

 rm#xjts00683@代宗 優寵宦官，
奉使四方者，
不禁其求取。

嘗遣中使賜𡚱族，
還，
問所得頗少，
 rm#xjts00683@代宗 不悦，
以爲輕我命；
𡚱懼，
遽以私物償之。

由是中使公求賂遺，
無所忌憚。

宰相嘗貯錢於閤中，
毎賜一物，
宣一旨，
無徒還者；
出使所歴州縣，
移文取貨，
與賦税同，
皆重載而歸。

上素知其弊，
遣中使 rm#xjts06876@邵光超 賜 rm#r01719@李希烈 旌節；
 rm#r01719@希烈 贈之僕、馬及縑七百匹，
黄茗二百斤。

上聞之，
怒，
杖 rm#xjts06876@光超 六十而流之。

於是中使之未歸者，
皆潛棄所得於山谷，
雖與之，
莫敢受。
# p 

甲子，
以神策都知兵馬使、右領軍大將軍 rm#xjts02815@王駕鶴 爲 dm#dm03880@東都 園苑使，
以司農卿 rm#r02849@白琇珪 代之，
更名 rm#r02849@志貞 。

 rm#xjts02815@駕鶴 典禁兵十餘年，
權行中外，
上恐其生變；
 rm#r00975@崔祐甫 召 rm#xjts02815@駕鶴 與語，
留連久之，
 rm#r02849@琇珪 已視事矣。詔下
# p 

 rm#xjts13396@李正己 畏上威名，
表獻錢三十萬緡；
上欲受之恐見欺，
卻之則無辭。

 rm#r00975@崔祐甫 請遣使慰勞 dm#dm04964@淄青 將士，
因以 rm#xjts13396@正己 所獻錢賜之，
使將士人人戴上恩；
又諸道聞之，
知朝廷不重貨財。

上悦，
從之。

 rm#xjts13396@正己 大慙服。

天下以爲太平之治，
庶幾可望焉。

# p 

秋，
七月，
戊辰朔，
日有食之。
# p 

禮儀使、吏部尚書 rm#r04147@顏眞卿 上言：
「 y@上元中 ，
政在宮壼，
始増祖宗之諡；
 rm#r02004@玄宗 末，
姦臣竊命，
累聖之諡，
有加至十一字者。

按 dyn#ch103@周 之 rm#rt0063@文 、 rm#rt0064@武 ，
稱文不稱武，
言武不稱文，
豈盛徳所不優乎？
蓋羣臣稱其至者故也。

故諡多不爲褒，
少不爲貶。

今累聖諡號太廣，
有踰古制，
請自 rm#r01656@中宗 以上皆從初諡，
 rm#r01797@睿宗 曰 rm#r01797@聖眞皇帝 ，
 rm#r02004@玄宗 曰 rm#r02004@孝明皇帝 ，
 rm#r01661@肅宗 曰 rm#r01661@宣皇帝 ，
以省文尚質，
正名敦本。」

上命百官集議，
儒學之士，
皆從 rm#r04147@眞卿 議；
獨兵部侍郎 rm#xjts19341@袁傪 ，
官以兵進，
奏言：
「陵廟玉册、木主皆已刊勒，
不可輕改，」
事遂寢。

不知陵中玉册所刻，
乃初諡也。

# p 

初，
 rm#xjts00683@代宗 之世，
事多留滯，
四夷使者及四方奏計，
或連歳不遣，
乃於 dm#dm01174@右銀臺門 置客省以處之；
及上書言事失職、未敍，
亦置其中，
動經十歳。

常有數百人，
幷部曲、畜産動以千計，
度支廩給，
其費甚廣。

上悉命疏理，
拘者出之，
事竟者遣之，
當敍者任之，
歳省穀萬九千二百斛。孟浪者
# p 

壬申，
毀 rm#r00165@元載 、 rm#r04182@馬璘 、 rm#r00253@劉忠翼 之第。

初，
 y@天寶中 ，
貴戚第舍雖極奢麗，
而垣屋高下，
猶存制度，
然 rm#r02009@李靖 家廟已爲 rm@楊氏 馬廐矣。

及 rm#r00793@安 、 rm#xjts23917@史 亂後，
法度墮弛，
大臣將帥競治第舍，
各窮其力而後止，
時人謂之木妖。

上素疾之，
故毀其尤者，
仍命 rm@馬氏 獻其園，
隸宮司，
謂之 dm#dm01860@奉成園 。
宦官
# p 

癸丑，
減常貢宮中服用錦千匹、服玩數千事。丑酉
# p 

庚辰，
詔囘紇諸胡在 dm#dm08170@京師 者，
各服其服，
無得效 dm#dm06927@華 人。

先是囘紇留 dm#dm08170@京師 者常千人，
商胡僞服而雜居者又倍之，
縣官日給饔餼，
殖貲産，
開第舍、市肆，
美利皆歸之，
日縱貪横，
吏不敢問。

或衣 dm#dm06927@華 服，
誘取妻妾，
故禁之。

# p 

辛卯，
罷天下榷酒收利。

# p 

上之在東宮也，
國子博士 dm#dm04651@河中  rm@張渉 爲侍讀，
即位之夕，
召 rm@渉 入禁中，
事無大小皆咨之；
明日，
置於翰林爲學士，
親重無比。

乙未，
以 rm@渉 爲右散騎常侍，
仍爲學士。

# p 

八月，
甲辰，
以 dm#dm07742@道州 司馬 rm#r02224@楊炎 爲門下侍郎，
 dm#dm03102@懷州 刺史 rm#r00521@喬琳 爲御史大夫，
竝同平章事。

上方勵精求治，
不次用人，
卜相於 rm#r00975@崔祐甫 ，
 rm#r00975@祐甫 薦 rm#r02224@炎 器業，
上亦素聞其名，
故自遷謫中用之。

 rm#r00521@琳 ，
 dm#dm01774@太原 人，
性粗率，
喜詼諧，
無他長，
與 rm@張渉 善，
 rm@渉 稱其才可大用，
上信 rm@渉 言而用之；
聞者無不駭愕。
# p 

 rm#xjts00683@代宗 之世，
吐蕃數遣使求和，
而寇盜不息，
 rm#xjts00683@代宗 悉留其使者，
前後八輩，
有至老死不得歸者；
俘獲其人，
皆配 dm#dm04475@江 、 dm#dm02525@嶺 。

上欲以徳懷之，
乙巳，
以 dm#dm08448@隨州 司馬 rm@韋倫 爲太常少卿，
使于吐蕃，
悉集其俘五百人，
各賜襲衣而遣之。

# p 

協律郎 rm#r02417@沈既濟 上選舉議，
以爲：
「選用之法，
三科而已：
曰徳也，
才也，
勞也。

今選曹皆不及焉；
考校之法，
皆在書判、簿歴、言詞、俯仰而已。

夫安行徐言，
非徳也；
麗藻芳翰，
非才也；
累資積考，
非勞也。

執此以求天下之士，
固未盡矣。

今人未土著，
不可本於郷閭；
鑒不獨明，
不可專於吏部。

臣謹詳酌古今，
謂五品以上及羣司長官，
宜令宰臣進敍，
吏部、兵部得參議焉。

其六品以下或僚佐之屬，
許州、府辟用，
其牧守、將帥或選用非公，
則吏部、兵部得察而舉之。

罪其私冒不愼舉者，
小加譴黜，
大正刑典。

責成授任，
誰敢不勉！

夫如是，
則賢者不獎而自進，
不肖者不抑而自退，
衆才咸得而官無不治矣。

今選法皆擇才於吏部，
試職於州郡，
若才職不稱，
紊亂無任。

責於刺史，
則曰命官出於吏曹，
不敢廢也；
責於侍郎，
則曰量書判、資考而授之，
不保其往也；
責於令史，
則曰按由歴、出入而行之，
不知其他也。

黎庶徒弊，
誰任其咎！

若牧守自用，
則罪將焉逃！

必州郡之濫，
獨換一刺史則革矣。

如吏部之濫，
雖更其侍郎無益也。

蓋人物浩浩，
不可得而知，
法使之然，
非主司之過。

今諸道節度、都團練、觀察、租庸等使，
自判官、副將以下，
皆使自擇，
縱其間或有情故，
大舉其例，
十猶七全。

則辟吏之法，
已試於今，
但未及於州縣耳。

利害之理，
較然可觀。

曏令諸使僚佐盡受於選曹，
則安能鎭方隅之重，
理財賦之殷乎！」

 rm#r02417@既濟 ，
 dm#dm01275@呉 人也。

# p 

初，
 dm#dm07230@衡州 刺史 rm#r00535@曹王皋 有治行，
 dm#dm05139@湖南 觀察使 rm#r03659@辛京杲 疾之，
陷以法，
貶 dm#dm05376@潮州 刺史。

時 rm#r02224@楊炎 在 dm#dm07742@道州 ，
知其直，
及入相，
復擢爲 dm#dm07230@衡州 刺史。

始，
 rm#r00535@皋 之遭誣在治，
念太𡚱老，
將驚而戚，
出則囚服就辯，
入則擁笏垂魚，
即貶于 dm#dm05376@潮 ，
以遷入賀；
及是，
然後跪謝告實。

 rm#r00535@皋 ，
 rm#r01527@明 之玄孫也。

# p 

 dm#dm03677@朔方 、 dm#dm07810@邠寧 節度使 rm#r01775@李懷光 既代 rm#xjts01384@郭子儀 ，
 dm#dm07808@邠 府宿將 rm#xjts23910@史抗 、 rm#xjts12523@温儒雅 、 rm@龐仙鶴 、 rm@張獻明 、 rm#xjts18187@李光逸 功名素出 rm#r01775@懷光 右，
皆怏怏不服。

 rm#r01775@懷光 發兵防秋，
屯 dm#dm08208@長武 城，
軍期進退，
不時應令。

監軍 rm#xjts06714@翟文秀 勸 rm#r01775@懷光 奏令宿衞，
既離營，
使人追捕，
誣以他罪，
且曰：
「 dm#dm09146@黄萯 之敗，
職爾之由！」

盡殺之。懷光遣之
# p 

九月，
甲戌，
改 dm#dm05005@淮西 曰 dm#dm04995@淮寧 。
# p 

 dm#dm07316@西川 節度使、同平章事 rm#r00914@崔寧 ，
在 dm#dm07197@蜀 十餘年，
恃地險兵強，
恣爲淫侈，
朝廷患之而不能易；
至是，
入朝，
加司空，
兼山陵使。
# p 

 rm#xjts26851@南詔王閤羅鳳 卒，
子 rm#xjts26550@鳳迦異 前死，
孫 rm#xjts24529@異牟尋 立。

冬，
十月，
丁酉朔，
吐蕃與 dm#dm01049@南詔 合兵十萬，
三道入寇，
一出 dm#dm06857@茂州 ，
一出 dm#dm03171@扶 、 dm#dm03295@文 ，
一出 dm#dm09164@黎 、 dm#dm08476@雅 ，
曰：
「吾欲取 dm#dm07197@蜀 以爲東府。」

 rm#r00914@崔寧 在 dm#dm08170@京師 ，
所留諸將不能禦，
虜連陷州、縣，
刺史棄城走，
士民竄匿山谷。

上憂之，
趣 rm#r00914@寧 歸鎭。

 rm#r00914@寧 已辭，
 rm#r02224@楊炎 言於上曰：
「 dm#dm07197@蜀 地富饒，
 rm#r00914@寧 據有之，
朝廷失其外府，
 y@十四年 矣。

 rm#r00914@寧 雖入朝，
全師尚守其後，
貢賦不入，
與無 dm#dm07197@蜀 同。

且 rm#r00914@寧 本與諸將等夷，
因亂得位，
威令不行。

今雖遣之，
必恐無功；
若其有功，
則義不可奪。

是 dm#dm07197@蜀 地敗固失之，
勝亦不得也。

願陛下熟察。」

上曰：
「然則奈何？」
對曰：
「請留 rm#r00914@寧 ，
發 rm#r01577@朱泚 所領 dm#dm06863@范陽 兵數千人，
雜禁兵往撃之，
何憂不克！

因而得内親兵於其腹中，
 dm#dm07197@蜀 將必不敢動，
然後更授他帥，
使千里沃壤復爲國有，
是因小害而收大利也。」

上曰：
「善。」

遂留 rm#r00914@寧 。
# p 

初，
 rm#r04182@馬璘 忌 dm#dm04920@涇原 都知兵馬使 rm@李晟 功名，
遣入宿衞，
爲右神策都將。

上發禁兵四千人，
使 rm@晟 將之，
發 dm#dm07808@邠 、 dm#dm08457@隴 、 dm#dm06863@范陽 兵五千，
使金吾大將軍 dm#dm02072@安邑  rm#r01490@曲環 將之，
以救 dm#dm07197@蜀 。

 dm#dm03818@東川 出兵，
自 dm#dm04498@江油 趨 dm#dm05869@白垻 ，
與 dm#dm02398@山南 兵合撃吐蕃、 dm#dm01049@南詔 ，
破之。

 dm#dm06863@范陽 兵追及於 dm#dm00104@七盤 ，
又破之，
遂克 dm#dm06452@維 、 dm#dm06857@茂 二州。

 rm@李晟 追撃於 dm#dm01652@大渡河 外，
又破之。

吐蕃、 dm#dm01049@南詔 飢寒，
隕於崖谷死者八九萬人。

吐蕃悔，
怒殺誘導使之來者。

 rm#xjts24529@異牟尋 懼，
築 dm#dm06852@苴咩城 ，
延袤十五里，
徙居之。

吐蕃封之爲 rm#xjts24529@日東王 。
# p 

上用法嚴，
百官震悚。

以山陵近，
禁人屠宰；
 rm#xjts01384@郭子儀 之隸人潛殺羊，
載以入城，
右金吾將軍 rm#r03464@裴諝 奏之。

或謂 rm#r03464@諝 曰：
「 rm#xjts01384@郭公 有社稷大功，
君獨不爲之地乎？」
 rm#r03464@諝 曰：
「此乃吾所以爲之地也。

 rm#xjts01384@郭公 勳高望重，
上新即位，
以爲羣臣附之者衆，
吾故發其小過，
以明 rm#xjts01384@郭公 威權不足畏也。

如此，
上尊天子，
下安大臣，
不亦可乎！」

# p 

己酉，
葬 rm#r01617@睿文孝武皇帝 于 dm#dm00638@元陵 ；
廟號 rm#xjts00683@代宗 。

將發引，
上送之，
見轀輬車不當馳道，
稍指丁未之間，
問其故，
有司對曰：
「陛下本命在午，
不敢衝也。」

上哭曰：
「安有枉靈駕而謀身利乎！」

命改轅直午而行。

 rm#r01661@肅宗 、 rm#xjts00683@代宗 皆喜陰陽鬼神，
事無大小，
必謀之卜祝，
故 rm#xjts02025@王嶼 、 rm#r04338@黎幹 皆以左道得進。

上雅不之信，
山陵但取七月之期，
事集而發，
不復擇日。

# p 

十一月，
丁丑，
以 dm#dm03544@晉州 刺史 rm#r04122@韓滉 爲 dm#dm07147@蘇州 刺史、 dm#dm04855@浙江東 ‧ dm#dm07286@西 觀察使。

# p 

 rm#r00521@喬琳 衰老耳聵，
上或時訪問，
應對失次，
所謀議復疏闊。

壬午，
以 rm#r00521@琳 爲工部尚書，
罷政事。

上由是疏 rm@張渉 。


# p 

 rm#r02224@楊炎 既留 rm#r00914@崔寧 ，
二人由是交惡。

 rm#r02224@炎 託以北邊須大臣鎭撫，
癸巳，
以 dm#dm00444@京畿 觀察使 rm#r00914@崔寧 爲 dm#dm01394@單于 ‧ dm#dm08123@鎭北 大都護、 dm#dm03677@朔方 節度使，
鎭 dm#dm01476@坊州 。

以 dm#dm06881@荊南 節度使 rm#r01145@張延賞 爲 dm#dm07316@西川 節度使。

又以 dm#dm08641@靈鹽 節度都虞候 dm#dm07988@醴泉  rm#r02040@杜希全 知 dm#dm08619@靈 、 dm#dm09056@鹽州 留後；
 dm#dm00485@代州 刺史 rm#r01110@張光晟 知 dm#dm01394@單于 ‧ dm#dm03228@振武 等城、 dm#dm06439@綏 ‧ dm#dm08081@銀 ‧ dm#dm09094@麟 ‧ dm#dm00812@勝州 留後；
 dm#dm02812@延州 刺史 rm#xjts13847@李建徽 知 dm#dm07920@鄜 、 dm#dm01476@坊 、 dm#dm00293@丹州 留後。

時 rm#r00914@寧 既出鎭，
不當更置留後，
 rm#r02224@炎 欲奪 rm#r00914@寧 權，
且窺其所爲，
令三人皆得特奏事，
仍諷之使伺 rm#r00914@寧 過失。

# p 

十二月，
乙卯，
立 rm#r01964@宣王誦 爲皇太子。
# p 

舊制，
天下金帛皆貯於左藏，
太府四時上其數，
比部覆其出入。

及 rm#r03064@第五琦 爲度支、鹽鐵使，
時 dm#dm08170@京師 多豪將，
求取無節，
 rm#r03064@琦 不能制，
乃奏盡貯於 dm#dm01663@大盈 内庫，
使宦官掌之，
天子亦以取給爲便，
故久不出。

由是以天下公賦爲人君私藏，
有司不復得窺其多少，
校其贏縮，
殆二十年。

宦官領其事者三百餘員，
皆蠶食其中，
蟠結根據，
牢不可動。

 rm#r02224@楊炎 頓首於上前曰：
「財賦者，
國之大本，
生民之命，
重輕安危，
靡不由之，
是以前世皆使重臣掌其事，
猶或耗亂不集。

今獨使中人出入盈虚，
大臣皆不得知，
政之蠹敝，
莫甚於此。

請出之以歸有司。

度宮中歳用幾何，
量數奉入，
不敢有乏。

如此，
然後可以爲政。」

上即日下詔：
「凡財賦皆歸左藏，
一用舊式，
歳於數中擇精好者三、五千匹，
進入 dm#dm01663@大盈 。」

 rm#r02224@炎 以片言移人主意，
議者稱之。
# p 

丙寅晦，
日有食之。
# p 

 dm#dm05139@湖南 賊帥 rm#xjts02945@王國良 阻山爲盜，
上遣都官員外郎 rm#r03890@關播 招撫之。

辭行，
上問以爲政之要，
對曰：
「爲政之本，
必求有道賢人與之爲理。」

上曰：
「朕比以下詔求賢，
又遣使臣廣加搜訪，
庶幾可以爲理乎！」

對曰：
「下詔所求及使者所薦，
惟得文詞干進之士耳，
安有有道賢人肯隨牒舉選乎！」

上悦。
# p 

 rm#r00975@崔祐甫 有疾，
上令肩輿入中書，
或休假在第，
大事令中使咨決。
# p 

徳宗神武孝文皇帝一
** 建中
*** 建中元年
# year 0780
# p 

春，
正月，
丁卯朔，
改元。

羣臣上尊號曰 rm#r01333@聖神文武皇帝 ；
赦天下。

始用 rm#r02224@楊炎 議，
「命黜陟使與觀察、刺史約百姓丁産，
定等級，
改作兩税法。

比來新舊徵科色目，
一切罷之；
二税外輒率一錢者，
以枉法論。」

# p 

 dyn#ch100@唐 初，
賦斂之法曰租、庸、調，
有田則有租，
有身則有庸，
有戸則有調。

 rm#xjts00542@玄宗 之末，
版籍浸壞，
多非其實。

及 y@至徳 兵起，
所在賦斂，
迫趣取辦，
無復常準。

賦斂之司増數而莫相統攝，
各隨意増科，
自立色目，
新故相仍，
不知紀極。

民富者丁多，
率爲官、爲僧以免課役，
而貧者丁多，
無所伏匿，
故上戸優而下戸勞。

吏因縁蠶食，
旬輸月送，
不勝困弊，
率皆逃徙爲浮戸，
其土著百無四五。

至是，
 rm#r02224@炎 建議作兩税法：
先計州縣毎歳所應費用及上供之數而賦於人，
量出以制入。

戸無主、客，
以見居爲簿；
人無丁、中，
以貧富爲差；
爲行商者，
在所州縣税三十之一，
使與居者均無僥利。

居人之税，
秋、夏兩徵之。

其租、庸、調雜傜悉省，
皆總統於度支。

上用其言，
因赦，
令行之。民
# p 

初，
左僕射 rm@劉晏 爲吏部尚書，
 rm#r02224@楊炎 爲侍郎，
不相悦。

 rm#r00165@元載 之死，
 rm@晏 有力焉。

及上即位，
 rm@晏 久典利權，
衆頗疾之，
多上言轉運使可罷；
又有風言 rm@晏 嘗密表勸 rm#xjts00683@代宗 立 rm@獨孤𡚱 爲皇后者。

 rm#r02224@楊炎 爲宰相，
欲爲 rm#r00165@元載 報仇，
因爲上流涕言：
「 rm@晏 與 rm#r04338@黎幹 、 rm#r00253@劉忠翼 同謀，
臣爲宰相不能討，
罪當萬死。」

 rm#r00975@崔祐甫 言：
「茲事曖昧，
陛下已曠然大赦，
不當復究尋虚語。」

 rm#r02224@炎 乃建言：
「尚書省，
國政之本，
比置諸使，
分奪其權，
今宜復舊。」

上從之。

甲子，
詔天下錢穀皆歸金部、倉部，
罷 rm@晏 轉運、租庸、青苗、鹽鐵等使。
子午
# p 

二月，
丙申朔，
命黜陟使十一人分巡天下。

先是，
 dm#dm08946@魏博 節度使 rm#r02819@田悦 事朝廷猶恭順，
 dm#dm04656@河北 黜陟使 rm#r02439@洪經綸 ，
不曉時務，
聞 rm#r02819@悦 軍七萬人，
符下，
罷其四萬，
令還農。

 rm#r02819@悦 陽順命，
如符罷之。

既而集應罷者，
激怒之曰：
「汝曹久在軍中，
有父母妻子，
今一旦爲黜陟使所罷，
將何資以自衣食乎！」

衆大哭。

 rm#r02819@悦 乃出家財以賜之，
使各還部伍。

於是軍士皆徳 rm#r02819@悦 而怨朝廷。

# p 

 rm#r00975@崔祐甫 以疾，
多不視事；
 rm#r02224@楊炎 獨任大政，
專以復恩讎爲事，
奏用 rm#r00165@元載 遺策城 dm#dm01114@原州 ，
又欲發 dm#dm00683@兩京 、 dm#dm08283@關内 丁夫浚 dm#dm07478@豐州  dm#dm08370@陵陽渠 ，
以興屯田。

上遣中使詣 dm#dm04920@涇原 節度使 rm#r02349@段秀實 ，
訪以利害，
 rm#r02349@秀實 以爲：
「今邊備尚虚，
未宜興事以召寇。」

 rm#r02224@炎 怒，
以爲沮己，
徵 rm#r02349@秀實 爲司農卿。

丁未，
 dm#dm07810@邠寧 節度使 rm#r01775@李懷光 兼 dm#dm01437@四鎭 、 dm#dm00860@北庭 行營、 dm#dm04920@涇原 節度使，
使移軍 dm#dm01114@原州 ，
以 dm#dm01437@四鎭 、 dm#dm00860@北庭 留後 rm#xjts25212@劉文喜 爲別駕。

 dm#dm00427@京兆 尹 rm#r00575@嚴郢 奏：
「按 dm#dm03677@朔方 五城，
舊屯沃饒之地，
自喪亂以來，
人功不及，
因致荒廢，
十不耕一。

若力可墾闢，
不俟浚渠。

今發 dm#dm00683@兩京 、 dm#dm08290@關輔 人於 dm#dm07478@豐州 浚渠營田，
計所得不補所費，
而 dm#dm08290@關輔 之人不免流散，
是虚畿甸而無益軍儲也。」

疏奏，
不報。

既而 dm#dm08370@陵陽渠 竟不成，
棄之。
# p 

上用 rm#r02224@楊炎 之言，
託以奏事不實，
己酉，
貶 rm@劉晏 爲 dm#dm02991@忠州 刺史。


# p 

癸丑，
以 dm#dm05401@澤潞 留後 rm#r01783@李抱眞 爲節度使。

# p 

 rm#r02224@楊炎 欲城 dm#dm01114@原州 以復 dm#dm06273@秦 、 dm#dm01114@原 ，
命 rm#r01775@李懷光 居前督作，
 rm#r01577@朱泚 、 rm#r00914@崔寧 各將萬人翼其後。

詔下 dm#dm04924@涇州 爲城具，
 dm#dm04919@涇 之將士怒曰：
「吾屬爲國家西門之屏，
十餘年矣。

始居 dm#dm07812@邠州 ，
甫營耕桑，
有地著之安。

徙屯 dm#dm04924@涇州 ，
披荊榛，
立軍府；
坐席未暖，
又投之塞外。

吾屬何罪而至此乎！」

 rm#r01775@李懷光 始爲 dm#dm07810@邠寧 帥，
即誅 rm#xjts12523@温儒雅 等，
軍令嚴峻；
及兼 dm#dm04920@涇原 ，
諸將皆懼，
曰：
「彼五將何罪而爲戮？
今又來此，
吾屬能無憂乎！」

 rm#xjts25212@劉文喜 因衆心不安，
據 dm#dm04924@涇州 ，
不受詔，
上疏復求 rm#r02349@段秀實 爲帥，
不則 rm#r01577@朱泚 。

癸亥，
以 rm#r01577@朱泚 兼 dm#dm01437@四鎭 、 dm#dm00860@北庭 行營、 dm#dm04920@涇原 節度使，
代 rm#r01775@懷光 。

# p 

三月，
翰林學士、左散騎常侍 rm#xjts04571@張渉 受前 dm#dm05139@湖南 觀察使 rm#r03659@辛京杲 金，
事覺；
上怒，
欲置于法。

 rm#r03193@李忠臣 以檢校司空、同平章事、奉朝請，
言於上曰：
「陛下貴爲天子，
而先生以乏財犯法，
以臣愚觀之，
非先生之過也。」

上意解，
辛未，
放渉歸田里。

 rm#r03659@辛京杲 以私忿杖殺部曲，
有司奏 rm#r03659@京杲 罪當死，
上將從之。

 rm#r03193@李忠臣 曰：
「 rm#r03659@京杲 當死久矣！」

上問其故。

 rm#r03193@忠臣 曰：
「 rm#r03659@京杲 諸父兄弟皆戰死，
獨 rm#r03659@京杲 至今尚存，
臣故以爲當死久矣。」

上憫然，
左遷 rm#r03659@京杲 諸王傅。

 rm#r03193@忠臣 乘機救人，
多此類。
# p 

 rm#r02224@楊炎 罷度支、轉運使，
命金部、倉部代之。

既而省職久廢，
耳目不相接，
莫能振舉，
天下錢穀無所總領。

癸巳，
復以諫議大夫 rm#r04118@韓洄 爲戸部侍郎、判度支，
以金部郎中 dm#dm06979@萬年  rm#r02023@杜佑 權 dm#dm04475@江 、 dm#dm04981@淮 水陸轉運使，
皆如舊制。

# p 

 rm#xjts25212@劉文喜 又不受詔，
欲自邀旌節；
夏，
四月，
乙未朔，
據 dm#dm04924@涇州 叛，
遣其子質於吐蕃以求援。

上命 rm#r01577@朱泚 、 rm#r01775@李懷光 討之，
又命神策軍使 rm#xjts05021@張巨濟 將禁兵二千助之。

# p 

吐蕃始聞 rm#r04006@韋倫 歸其俘，
不之信，
及俘入境，
各還部落，
稱：
「新天子出宮人，
放禽獸，
英威聖徳，
洽於 dm#dm00255@中國 。」

吐蕃大悦，
除道迎 rm#r04006@倫 。

贊普即發使隨 rm#r04006@倫 入貢，
且致賻贈。

癸卯，
至 dm#dm08170@京師 ，
上禮接之。

既而 dm#dm07197@蜀 將上言：
「吐蕃豺狼，
所獲俘不可歸。」

上曰：
「戎狄犯塞則撃之，
服則歸之。

撃以示威，
歸以示信。

威信不立，
何以懷遠！」

悉命歸之。

# p 

 rm#xjts00683@代宗 之世，
毎元日、冬至、端午、生日，
州府於常賦之外競爲貢獻，
貢獻多者則悦之。

武將、姦吏，
縁此侵漁下民。

癸丑，
上生日，
四方貢獻皆不受。

 rm#xjts13396@李正己 、 rm#r02819@田悦 各獻縑三萬匹，
上悉歸之度支以代租賦。

# p 

五月，
戊辰，
以 rm#r04006@韋倫 爲太常卿；
乙酉，
復遣 rm#r04006@倫 使吐蕃。

 rm#r04006@倫 請上自爲載書，
與吐蕃盟；
 rm#r02224@楊炎 以爲非敵，
請與 rm#xjts01384@郭子儀 輩爲載書以聞，
令上畫可而已，
從之。

# p 

 rm#r01577@朱泚 等圍 rm#xjts25212@劉文喜 於 dm#dm04924@涇州 ，
杜其出入，
而閉壁不與戰，
久之不拔。

天方旱，
徵發餽運，
内外騷然，
朝臣上書請赦 rm@文喜 以蘇疲人者，
不可勝紀。

上皆不聽，
曰：
「微孼不除，
何以令天下！」

 rm@文喜 使其將 rm#r00285@劉海賓 入奏，
 rm#r00285@海賓 言於上曰：
「臣乃陛下藩邸部曲，
豈肯附叛臣，
必爲陛下梟其首以獻。

但 rm@文喜 今所求者節而已，
願陛下姑與之，
 rm@文喜 必怠，
則臣計得施矣。」

上曰：
「名器不可假人，
爾能立效固善，
我節不可得也。」

使 rm#r00285@海賓 歸以告 rm@文喜 ，
而攻之如初。

減御膳以給軍士，
城中將士當受春服者，
賜豫如故。

於是衆知上意不可移。

時吐蕃方睦於 dyn#ch100@唐 ，
不爲發兵，
城中勢窮。

庚寅，
 rm#r00285@海賓 與諸將共殺 rm@文喜 ，
傳首，
而 dm#dm01114@原州 竟不果城。
# p 

自上即位，
 rm#xjts13396@李正己 内不自安，
遣參佐入奏事；
會 dm#dm04924@涇州 捷奏至，
上使觀 rm@文喜 之首而歸。

 rm#r01776@正己 益懼。
# p 

六月，
甲午朔，
門下侍郎、同平章事 rm#r00975@崔祐甫 薨。


# p 

術士 rm#r02118@桑道茂 上言：
「陛下不出數年，
暫有離宮之厄。

臣望 dm#dm01853@奉天 有天子氣，
宜高大其城以備非常。」

辛丑，
命 dm#dm00427@京兆 發丁夫數千，
雜六軍之士，
築 dm#dm01853@奉天 城。

# p 

初，
囘紇風俗朴厚，
君臣之等不甚異，
故衆志專一，
勁健無敵。

及有功於 dyn#ch100@唐 ，
 dyn#ch100@唐 賜遺甚厚，
 rm#xjts06084@登里可汗 始自尊大，
築宮殿以居婦人，
有粉黛文繡之飾；
 dm#dm00255@中國 爲之虚耗，
而虜俗亦壞。

及 rm#xjts00683@代宗 崩，
上遣中使 rm#xjts12236@梁文秀 往告哀，
 rm#xjts06084@登里 驕不爲禮。

九姓胡附囘紇者，
説 rm#xjts06084@登里 以 dm#dm00255@中國 富饒，
今乘喪伐之，
可有大利。

 rm#xjts06084@登里 從之，
欲舉國入寇。

其相 rm#xjts27186@頓莫賀達干 ，
 rm#xjts06084@登里 之從父兄也，
諫曰：
「 dyn#ch100@唐 ，
大國也，
無負於我，
吾 y@前年 侵 dm#dm01774@太原 ，
獲羊馬數萬，
可謂大捷，
而道遠糧乏，
比歸，
士卒多徒行者。

今舉國深入，
萬一不捷，
將安歸乎！」

 rm#xjts06084@登里 不聽。

 rm#xjts27186@頓莫賀 乘人心之不欲南寇也，
舉兵撃殺之，
幷九姓胡二千人，
自立爲 rm#xjts27186@合骨咄祿毘伽可汗 ，
遣其臣 rm#xjts23950@聿達干 與 rm#xjts12236@梁文秀 倶入見，
願爲藩臣，
垂髮不翦，
以待詔命。

乙卯，
命 dm#dm00427@京兆 少尹 dm#dm06718@臨漳  rm#r02468@源休 册 rm#xjts27186@頓莫賀 爲 rm#xjts27186@武義成功可汗 。

# p 

秋，
七月，
丙寅，
 dm#dm07827@邵州 賊帥 rm#xjts02945@王國良 降。

 rm#xjts02945@國良 本 dm#dm05139@湖南 牙將，
觀察使 rm#r03659@辛京杲 使戍 dm#dm04252@武岡 ，
以扞西原蠻。

 rm#r03659@京杲 貪暴，
 rm#xjts02945@國良 家富，
 rm#r03659@京杲 以死罪加之；
 rm#xjts02945@國良 懼，
據縣叛，
與西原蠻合，
聚衆千人，
侵掠州縣，
瀕湖千里，
咸被其害。

詔 dm#dm06880@荊 、 dm#dm09181@黔 、 dm#dm04804@洪 、 dm#dm03996@桂 諸道合兵討之，
連年不能克。

及 rm#r00535@曹王皋 爲 dm#dm05139@湖南 觀察使，
曰：
「驅疲甿，
誅反仄，
非策之得者也。」

乃遺 rm#xjts02945@國良 書，
言：
「將軍非敢爲逆，
欲救死耳。

我與將軍倶爲 rm#r03659@辛京杲 所構，
我已蒙聖朝湔洗，
何心復加兵刃於將軍乎！

將軍遇我，
不速降，
後悔無及。」

 rm#xjts02945@國良 且喜且懼，
遣使乞降，
猶疑未決。

 rm#r00535@皋 乃假爲使者，
從一騎，
越五百里，
抵 rm#xjts02945@國良 壁，
鞭其門，
大呼曰：
「我 rm@曹王 也，
來受降！」

舉軍大驚。

 rm#xjts02945@國良 趨出，
迎拜請罪。

 rm#r00535@皋 執其手，
約爲兄弟，
盡焚攻守之具，
散其衆，
使還農。

詔赦 rm#xjts02945@國良 罪，
賜名 rm#xjts02945@惟新 。

# p 

辛巳，
遙尊上母 rm@沈氏 爲皇太后。

# p 

 dm#dm06881@荊南 節度使 rm#r01058@庾準 希 rm#r02224@楊炎 指，
奏 dm#dm02991@忠州 刺史 rm#r00276@劉晏 與 rm#r01577@朱泚 書求營救，
辭多怨望，
又奏召補州兵，
欲拒朝命，
 rm#r02224@炎 證成之；
上密遣中使就 dm#dm02991@忠州 縊殺之，
己丑，
乃下詔賜死。

天下冤之。
# p 

初，
 rm#r00793@安 、 rm#xjts23917@史 之亂，
數年間，
天下戸口什亡八九，
州縣多爲藩鎭所據，
貢賦不入，
朝廷府庫耗竭，
 dm#dm00255@中國 多故，
戎狄毎歳犯邊，
所在宿重兵，
仰給縣官，
所費不貲，
皆倚辦於 rm#r00276@晏 。

 rm#r00276@晏 初爲轉運使，
獨領 dm#dm08323@陝東 諸道，
 dm#dm08328@陝西 皆度支領之，
末年兼領，
未幾而罷。


# p 

 rm#r00276@晏 有精力，
多機智，
變通有無，
曲盡其妙。

常以厚直募善走者，
置遞相望，
覘報四方物價，
雖遠方，
不數日皆達使司，
食貨輕重之權，
悉制在掌握，
國家獲利而天下無甚貴甚賤之憂。

常以爲：
「辦集衆務，
在於得人，
故必擇通敏、精悍、廉勤之士而用之；
至於句檢簿書，
出納錢穀，
必委之士類；
吏惟書符牒，
不得輕出一言。」

常言：
「士陷贓賄，
則淪棄於時，
名重於利，
故士多清脩；
吏雖潔廉，
終無顯榮，
利重於名，
故吏多貪汚。」

然惟 rm#r00276@晏 能行之，
他人效者終莫能逮。

其屬官雖居數千里外，
奉教令如在目前，
起居語言，
無敢欺紿。

當時權貴，
或以親故屬之者，
 rm#r00276@晏 亦應之，
使俸給多少，
遷次緩速，
皆如其志，
然無得親職事。

其場院要劇之官，
必盡一時之選。

故 rm#r00276@晏 沒之後，
掌財賦有聲者，
多 rm#r00276@晏 之故吏也。事雖至細雖至細
# p 

 rm#r00276@晏 又以爲戸口滋多，
則賦税自廣，
故其理財以愛民爲先。

諸道各置知院官，
毎旬月，
具州縣雨雪豐歉之状白使司，
豐則貴糴，
歉則賤糶，
或以穀易雜貨供官用，
及於豐處賣之。

知院官始見不稔之端，
先申至，
某月須如干蠲免，
某月須如干救助，
及期，
 rm#r00276@晏 不俟州縣申請，
即奏行之，
應民之急，
未嘗失時，
不待其困弊、流亡、餓殍，
然後賑之也。

由是民得安其居業，
戸口蕃息。

 rm#r00276@晏 始爲轉運使，
時天下見戸不過二百萬，
其季年乃三百餘萬；
在 rm#r00276@晏 所統則増，
非 rm#r00276@晏 所統則不増也。

其初財賦歳入不過四百萬緡，
季年乃千餘萬緡。常愛養
# p 

 rm#r00276@晏 專用榷鹽法充軍國之用。

時自 dm#dm07433@許 、 dm#dm04460@汝 、 dm#dm07947@鄭 、 dm#dm07938@鄧 之西，
皆食 dm#dm04672@河東 池鹽，
度支主之；
 dm#dm04537@汴 、 dm#dm05225@滑 、 dm#dm01356@唐 、 dm#dm07083@蔡 之東，
皆食海鹽，
 rm#r00276@晏 主之。

 rm#r00276@晏 以爲官多則民擾，
故但於出鹽之郷置鹽官，
收鹽戸所煮之鹽轉鬻於商人，
任其所之，
自餘州縣不復置官。

其江嶺間去鹽郷遠者，
轉官鹽於彼貯之。

或商絶鹽貴，
則減價鬻之，
謂之常平鹽，
官獲其利而民不乏鹽。

其始 dm#dm04475@江 、 dm#dm04981@淮 鹽利不過四十萬緡，
季年乃六百餘萬緡，
由是國用充足而民不困弊。

其 dm#dm04672@河東 鹽利，
不過八十萬緡，
而價復貴於海鹽。

# p 

先是，
運 dm#dm08286@關東 穀入 dm#dm08170@長安 者，
以河流湍悍，
率一斛得八斗至者，
則爲成勞，
受優賞。

 rm#r00276@晏 以爲 dm#dm04475@江 、 dm#dm04537@汴 、 dm#dm04650@河 、 dm#dm05102@渭 ，
水力不同，
各隨便宜，
造運船，
教漕卒，
 dm#dm04475@江 船達 dm#dm03246@揚州 ，
 dm#dm04537@汴 船達 dm#dm04705@河陰 ，
 dm#dm04650@河 船達 dm#dm05102@渭 口，
 dm#dm05102@渭 口達 dm#dm01771@太倉 ，
其間縁水置倉，
轉相受給。

自是毎歳運穀或至百餘萬斛，
無斗升沈覆者。

船十艘爲一綱，
使軍將領之，
十運無失，
授優勞，
官其人。

數運之後，
無不斑白者。

 rm#r00276@晏 於 dm#dm03241@揚子 置十場造船，
毎艘給錢千緡。

或言「所用實不及半，
虚費太多。」

 rm#r00276@晏 曰：
「不然，
論大計者固不可惜小費，
凡事必爲永久之慮。

今始置船場，
執事者至多，
當先使之私用無窘，
則官物堅牢矣。

若遽與之屑屑校計錙銖，
安能久行乎！

異日必有患吾所給多而減之者；
減半以下猶可也，
過此則不能運矣。」

其後五十年，
有司果減其半。

及 y@咸通中 ，
有司計費以給之，
無復羨餘，
船益脆薄易壞，
漕運遂廢矣。

# p 

 rm#r00276@晏 爲人勤力，
事無閒劇，
必於一日中決之，
不使留宿，
後來言財利者皆莫能及之。
# p 

八月，
甲午，
 dm#dm03228@振武 留後 rm#r01110@張光晟 殺囘紇使者 rm@董突 等九百餘人。

 rm@董突 者，
 rm#xjts27186@武義可汗 之叔父也。

 rm#xjts00683@代宗 之世，
九姓胡常冒囘紇之名，
雜居 dm#dm08170@京師 ，
殖貨縱暴，
與囘紇共爲公私之患；
上即位，
命 rm@董突 盡帥其徒歸國，
輜重甚盛。

至 dm#dm03228@振武 ，
留數月，
厚求資給，
日食肉千斤，
他物稱是，
縱樵牧者暴踐果稼，
 dm#dm03228@振武 人苦之。

 rm#r01110@光晟 欲殺囘紇，
取其輜重，
而畏其衆強，
未敢發。

九姓胡聞其種族爲新可汗所誅，
多道亡，
 rm@董突 防之甚急；
九姓胡不得亡，
又不敢歸，
乃密獻策於 rm#r01110@光晟 ，
請殺囘紇。

 rm#r01110@光晟 喜其黨自離，
許之。

上以 dm#dm08320@陝州 之辱，
心恨囘紇；
 rm#r01110@光晟 知上旨，
乃奏稱：
「囘紇本種非多，
所輔以強者，
羣胡耳。

今聞其自相魚肉，
 rm#xjts27186@頓莫賀 新立，
 rm#xjts06084@移地健 有孼子，
及國相、梅録各擁兵數千人相攻，
國未定。

彼無財則不能使其衆，
陛下不乘此際除之，
乃歸其人，
與之財，
正所謂借寇兵齎盜糧者也。

請殺之。」

三奏，
上不許。

 rm#r01110@光晟 乃使副將過其館門，
故不爲禮；
 rm@董突 怒，
執而鞭之數十。

 rm#r01110@光晟 勒兵掩撃，
幷羣胡盡殺之，
聚爲京觀。

獨留一胡，
使歸國爲證，
曰：
「囘紇鞭辱大將，
且謀襲據 dm#dm03228@振武 ，
故先事誅之。」

上徵 rm#r01110@光晟 爲右金吾將軍，
遣中使 rm#xjts02692@王嘉祥 往致信幣。

囘紇請得專殺者以復讎，
上爲之貶 rm#r01110@光晟 爲 rm#r02952@睦王 傅以慰其意。
董突突董
# p 

加 dm#dm06013@盧龍 、 dm#dm08458@隴右 、 dm#dm04920@涇原 節度使 rm#r01577@朱泚 兼中書令，
 dm#dm06013@盧龍 、 dm#dm08458@隴右 節度如故。

以 rm#r03137@舒王謨 爲 dm#dm01437@四鎭 、 dm#dm00860@北庭 行軍、 dm#dm04920@涇原 節度大使，
以 dm#dm04924@涇州 牙前兵馬使 dm#dm04651@河中  rm#r00621@姚令言 爲留後。

 rm@謨 ，
 rm@邈 之子也，
早孤，
上子之。
丁未
# p 

癸丑，
詔贈太后父、祖、兄、弟官，
及自餘宗族男女拜官封邑者告第告身，
凡百二十有七通；
中使以馬負而賜之。
# p 

九月，
壬午，
將作奏 dm#dm02221@宣政殿 廊壞，
十月魁岡，
未可脩。

上曰：
「但不妨公害人，
則吉矣。

安問時日！

」
即命脩之。
# p 

 y@大暦 以前，
賦斂出納俸給皆無法，
長吏得專之；
重以 rm#r00165@元 、 rm#r02687@王 秉政，
貨賂公行，
天下不按贓吏者殆二十年。

惟 dm#dm04509@江西 觀察使 rm#xjts24772@路嗣恭 按 dm#dm07172@虔州 刺史 rm@源敷翰 ，
流之。

上以 dm#dm02224@宣歙 觀察使 rm#xjts21190@薛邕 ，
文雅舊臣，
徵爲左丞；
 rm#xjts21190@邕 去 dm#dm02214@宣州 ，
盜隱官物以巨萬計，
殿中侍御史 rm#xjts24533@員㝢 發之。

冬，
十月，
己亥，
貶 dm#dm07710@連山 尉。

於是州縣始畏朝典，
不敢放縱。
# p 

上初即位，
疏斥宦官，
親任朝士，
而 rm@張渉 以儒學入侍，
 rm#xjts21190@薛邕 以文雅登朝，
繼以贓敗。

宦官武將得以藉口，
曰：
「南牙文臣贓動至巨萬，
而謂我曹濁亂天下，
豈非欺罔邪！」

於是上心始疑，
不知所倚仗矣。
# p 

中書舍人 rm#r04221@高參 請分遣諸 rm@沈 訪求太后，
庚寅，
以 rm#r02952@睦王述 爲奉迎使，
工部尚書 rm#r00521@喬琳 副之，
又命諸沈四人爲判官，
與中使分行諸道求之。

# p 

十一月，
初令待制官外，
更引朝集使二人，
訪以時政得失，
遠人疾苦。

# p 

先是，
公主下嫁者，
舅姑拜之，
婦不答。

上命禮官定公主拜見舅、姑及壻之諸父、兄、姉之儀，
舅、姑坐受於中堂，
兄、姉立受於東序，
如家人禮。

有縣主將嫁，
擇用丁丑，
是日，
上之從父妹卒，
命罷之。

有司奏：
「供張已備，
且殤服不足廢事。」

上曰：
「爾愛其費，
我愛其禮。」

卒罷之。

 y@至徳 以來，
國家多事，
公主、郡、縣主多不以時嫁，
有華髮者，
雖居禁中，
或十年不見天子；
上始引見諸宗女，
尊者致敬，
卑者存慰，
悉命嫁之。

所齎小大之物，
必經心目。

己卯、庚辰二日，
嫁 dm#dm02434@嶽陽 等九十一縣主。
諸父九凡
# p 

吐蕃見 rm#r04006@韋倫 再至，
益喜。

十二月，
辛卯朔，
 rm#r04006@倫 還，
吐蕃遣其相 rm#xjts01677@論欽明思 等入貢。

# p 

 y@是歳 ，
册太子母 rm@王氏 爲淑𡚱。
# p 

天下税戸三百八萬五千七十六，
籍兵七十六萬八千餘人，
税錢一千八十九萬八千餘緡，
穀二百一十五萬七千餘斛。

*** 二年
# year 0781
# p 

春，
正月，
戊辰，
 dm#dm03139@成徳 節度使 rm#r01157@李寶臣 薨。

 rm#r01157@寶臣 欲以軍府傳其子行軍司馬 rm#r01762@惟嶽 ，
以 y@其年 少闇弱，
豫誅諸將之難制者 dm#dm05016@深州 刺史 rm#r01213@張獻誠 等，
至有十餘人同日死者。

 rm#r01157@寶臣 召 dm#dm03494@易州 刺史 rm#r01268@張孝忠 ，
 rm#r01268@孝忠 不往，
使其弟 rm#xjts04828@孝節 召之。

 rm#r01268@孝忠 使 rm#xjts04828@孝節 謂 rm#r01157@寶臣 曰：
「諸將何罪，
連頸受戮！

 rm#r01268@孝忠 懼死，
不敢往，
亦不敢叛，
正如公不入朝之意耳。」

 rm#xjts04828@孝節 泣曰：
「如此，
 rm#xjts04828@孝節 必死。」

 rm#r01268@孝忠 曰：
「往則併命，
我在此，
必不敢殺汝。」

遂歸，
 rm#r01157@寶臣 亦不之罪也。

兵馬使 rm#r02656@王武俊 ，
位卑而有勇，
故 rm#r01157@寶臣 特親愛之，
以女妻其子 rm#xjts16369@士眞 ，
 rm#xjts16369@士眞 復厚結其左右；
故 rm#r01268@孝忠 、 rm#r02656@武俊 獨全。

# p 

及薨，
孔目官 rm#xjts23140@胡震 ，
家僮 rm#xjts02254@王他奴 勸 rm#r01762@惟嶽 匿喪二十餘日，
詐爲 rm#r01157@寶臣 表，
求令 rm#r01762@惟嶽 繼襲，
上不許；
遣給事中 dm#dm04534@汲 人 rm#r02803@班宏 往問 rm#r01157@寶臣 疾，
且諭之。

 rm#r01762@惟嶽 厚賂 rm#r02803@宏 ，
 rm#r02803@宏 不受，
還報。

 rm#r01762@惟嶽 乃發喪，
自爲留後，
使將佐共奏求旌節，
上又不許。

# p 

初，
 rm#r01157@寶臣 與 rm#xjts13396@李正己 、 rm#r02821@田承嗣 、 rm#r02124@梁崇義 相結，
期以土地傳之子孫。

故 rm#r02821@承嗣 之死，
 rm#r01157@寶臣 力爲之請于朝，
使以節授 rm#r02819@田悦 ；
 rm#xjts00683@代宗 從之。

 rm#r02819@悦 初襲位，
事朝廷禮甚恭，
 dm#dm04672@河東 節度使 rm#r04181@馬燧 表其必反，
請先爲備。

至是悦屡爲 rm@惟嶽 請繼襲，
上欲革前弊，
不許；
或諫曰：
「 rm@惟嶽 已據父業，
不因而命之，
必爲亂。」

上曰：
「賊本無資以爲亂，
皆藉我土地，
假我位號，
以聚其衆耳。

曏日因其所欲而命之多矣，
而亂日益滋。

是爵命不足以已亂而適足以長亂也。

然則 rm@惟嶽 必爲亂，
命與不命等耳。」

竟不許。

 rm#r02810@悦 乃與 rm#xjts13396@李正己 各遣使詣 rm@惟嶽 ，
潛謀勒兵拒命。
# p 

 dm#dm08946@魏博 節度副使 rm#xjts24270@田庭玠 謂 rm#r02819@悦 曰：
「爾藉伯父遺業，
但謹事朝廷，
坐享富貴，
不亦善乎！

奈何無故與 dm#dm03017@恆 、 dm#dm07903@鄆 共爲叛臣！

爾觀兵興以來，
逆亂者誰能保其家乎？
必欲行爾之志，
可先殺我，
無使我見 rm@田氏 之族滅也。」

因稱病臥家。

 rm#r02819@悦 自往謝之，
 rm#xjts24270@庭玠 閉門不内，
竟以憂卒。

# p 

 dm#dm03139@成徳 判官 rm#r03688@邵眞 聞 rm@李惟嶽 之謀，
泣諫曰：
「先相公受國厚恩，
大夫衰絰之中，
遽欲負國，
此甚不可。」

勸 rm@惟嶽 執 rm#xjts13396@李正己 使者送 dm#dm08170@京師 ，
且請討之，
曰：
「如此，
朝廷嘉大夫之忠，
則旄節庶幾可得。」

 rm@惟嶽 然之，
使 rm#r03688@眞 草奏。

長史 rm#xjts24405@畢華 曰：
「先公與二道結好二十餘年，
奈何一旦棄之！

且雖執其使，
朝廷未必見信。

 rm#xjts13396@正己 忽來襲我，
孤軍無援，
何以待之！」

 rm@惟嶽 又從之。
# p 

前 dm#dm02124@定州 刺史 rm#r03544@谷從政 ，
 rm@惟嶽 之舅也，
有膽略，
頗讀書，
 rm#r02656@王武俊 等皆敬憚之，
爲 rm#r01157@寶臣 所忌，
 rm@從政 乃稱病杜門。

 rm@惟嶽 亦忌之，
不與圖事，
日夜獨與 rm#xjts23140@胡震 、 rm#xjts02254@王他奴 等計議，
多散金帛以悦將士。

 rm@從政 往見 rm@惟嶽 曰：
「今海内無事，
自上國來者，
皆言天子聰明英武，
志欲致太平，
深不欲諸侯子孫專地。

爾今首違詔命，
天子必遣諸道致討。

將士受賞，
皆言爲大夫盡死；
苟一戰不勝，
各惜其生，
誰不離心！

大將有權者，
乘危伺便，
咸思取爾以自爲功矣。

且先相公所殺高班大將，
殆以百數，
撓敗之際，
其子弟欲復仇者，
庸可數乎！

又，
相公與 dm#dm02689@幽州 有隙，
 rm#r01579@朱滔 兄弟常切齒於我，
今天子必以爲將；
 rm#r01579@滔 與吾撃柝相聞，
計其聞命疾驅，
若虎狼之得獸也，
何以當之！

昔 rm#r02821@田承嗣 從 rm#r00793@安 、 rm#xjts23917@史 父子同反，
身經百戰，
凶悍聞於天下，
違詔舉兵，
自謂無敵；
及 rm#xjts07204@盧子期 就擒，
 rm#xjts10288@呉希光 歸國，
 rm#r02821@承嗣 指天垂泣，
身無所措。

頼先相公按兵不進，
且爲之祈請，
先帝寛仁，
赦而不誅，
不然，
 rm#xjts24378@田氏 豈有種乎！

況爾生長富貴，
齒髮尚少，
不更艱危，
乃信左右之言，
欲效 rm#r02821@承嗣 所爲乎！

爲爾之計，
不若辭謝將佐，
使 rm#r01764@惟誠 攝領軍府，
身自入朝，
乞留宿衞，
因言 rm#r01764@惟誠 且留攝事。

恩命決於聖志；
上必悦爾忠義，
縱無大位，
不失榮祿，
永無憂矣。

不然，
大禍將及。

吾亦知爾素疏忌我，
顧以舅甥之情，
事急，
不得不言耳！」

 rm@惟嶽 見其言切，
益惡之。

 rm#r03544@從政 乃復歸，
杜門稱病。

 rm#r01764@惟誠 者，
 rm@惟嶽 之庶兄也，
謙厚好書，
得衆心，
其母妹爲 rm#xjts13396@李正己 婦。

是日，
 rm@惟嶽 送 rm#r01764@惟誠 於 rm#xjts13396@正己 ，
 rm#xjts13396@正己 使復姓 rm@張 ，
遂仕 dm#dm04964@淄青 。

 rm@惟嶽 遣 rm#xjts02254@王他奴 詣 rm#r03544@從政 家，
察其起居，
 rm#r03544@從政 飮藥而卒；
且死，
曰：
「吾不憚死，
哀 rm@張氏 今族滅矣！」

之際至悔之何及左右
# p 

 rm#xjts25212@劉文喜 之死也，
 rm#xjts13396@李正己 、 rm#r02819@田悦 等皆不自安；
 rm#r00276@劉晏 死，
 rm#xjts13396@正己 等益懼，
相謂曰：
「我輩罪惡，
豈得與 rm#r00276@劉晏 比乎！

」
會 dm#dm04541@汴州 城隘，
廣之，
東方人訛言「上欲東封，
故城 dm#dm04541@汴州 。」

 rm#xjts13396@正己 懼，
發兵萬人屯 dm#dm03641@曹州 ；
 rm#r02819@田悦 亦完聚爲備，
與 rm#r02124@梁崇義 、 rm@李惟嶽 遙相應助，
 dm#dm04660@河南 士民騷然驚駭。
# p 

 dm#dm04412@永平 舊領 dm#dm04537@汴 、 dm#dm02093@宋 、 dm#dm05225@滑 、 dm#dm00454@亳 、 dm#dm08348@陳 、 dm#dm05327@潁 、 dm#dm04727@泗 七州，
丙子，
分 dm#dm02093@宋 、 dm#dm00454@亳 、 dm#dm05327@潁 別爲節度使，
以 dm#dm02098@宋州 刺史 rm#r00292@劉洽 爲之；
以 dm#dm04730@泗州 隸 dm#dm04984@淮南 ；
又以 dm#dm03880@東都 留守 rm#xjts24772@路嗣恭 爲 dm#dm03102@懷 ‧ dm#dm07947@鄭 ‧ dm#dm04460@汝 ‧ dm#dm08318@陝 四州、 dm#dm04709@河陽 三城節度使。

旬日，
又以 dm#dm04412@永平 節度使 rm@李勉 都統 rm#r00292@洽 、 rm#xjts24772@嗣恭 二道，
仍割 dm#dm07949@鄭州 隸之，
選嘗爲將者爲諸州刺史，
以備 rm#xjts13396@正己 等。

# p 

初，
 rm#r04220@高力士 有養女嫠居 dm#dm03788@東京 ，
頗能言宮中事，
女官 rm#xjts16260@李眞一 意其爲 rm#xjts08032@沈太后 ，
詣使者具言其状。

上聞之，
驚喜。

時 rm@沈氏 故老已盡，
無識太后者。

上遣宦官、宮人往驗視之，
年状頗同，
宦官、宮人不審識太后，
皆言是。

 rm@高氏 辭稱實非太后，
驗視者益疑之，
強迎入 dm#dm00199@上陽宮 。

上發宮女百餘人，
齎乘輿服御物就 dm#dm00199@上陽宮 供奉。

左右誘諭百方，
 rm@高氏 心動，
乃自言是。

驗視者走馬入奏，
上大喜。

二月，
辛卯，
上以偶日御殿，
羣臣皆入賀。

詔有司草儀奉迎。

 rm@高氏 弟 rm#r01816@承悦 在 dm#dm08170@長安 ，
恐不言，
久獲罪，
遽自言本末。

上命 rm#r04220@力士 養孫 rm@樊景超 往覆視，
 rm@景超 見 rm@高氏 居内殿，
以太后自處，
左右侍衞甚嚴。

 rm@景超 謂 rm@高氏 曰：
「姑何自置身於俎上！」

左右叱 rm@景超 使下，
 rm@景超 抗聲曰：
「有詔，
太后詐僞，
左右可下。

」
左右皆下殿。

 rm@高氏 乃曰：
「吾爲人所強，
非己出也。」

以牛車載還其家。

上恐後人不復敢言太后，
皆不之罪，
曰：
「吾寧受百欺，
庶幾得之。」

自是四方稱得太后者數四，
皆非是，
而眞太后竟不知所之。

# p 

御史中丞 rm#r02881@盧𣏌 ，
 rm#r02897@奕 之子也，
貌醜，
色如藍，
有口辯；
上悦之，
丁未，
擢爲大夫，
領 dm#dm00444@京畿 觀察使。

 rm#xjts01384@郭子儀 毎見賓客，
姬妾不離側。

 rm#r02881@𣏌 嘗往問疾，
 rm#xjts01384@子儀 悉屏侍妾，
獨隱几待之。

或問其故，
 rm#xjts01384@子儀 曰：
「 rm#r02881@𣏌 貌陋而心險，
婦人輩見之必笑，
他日 rm#r02881@𣏌 得志，
吾族無類矣！」

# p 

 rm#r02224@楊炎 既殺 rm#r00276@劉晏 ，
朝野側目，
 rm#xjts13396@李正己 累表請 rm#r00276@晏 罪，
譏斥朝廷。

 rm#r02224@炎 懼，
遣腹心分詣諸道，
以宣慰爲名，
實使之密諭節度使云：
「 rm#r00276@晏 昔朋附姦邪，
請立 rm#rx0063@獨孤后 ，
上自惡而殺之。」

上聞而惡之，
由是有誅 rm#r02224@炎 之志，
隱而未發。

乙巳，
遷 rm#r02224@炎 爲中書侍郎，
擢 rm#r02881@盧𣏌 爲門下侍郎，
竝同平章事，
不專任 rm#r02224@炎 矣。

 rm#r02881@𣏌 蕞陋，
無文學，
 rm#r02224@炎 輕之，
多託疾不與會食；
 rm#r02881@𣏌 亦恨之。

 rm#r02881@𣏌 陰狡，
欲起勢立威，
小不附者必欲置之死地，
引太常博士 rm#r03431@裴延齡 爲集賢殿直學士，
親任之。

# p 

丙午，
更 dm#dm04540@汴宋 軍曰 dm#dm02225@宣武 。

# p 

 dm#dm03228@振武 節度使 rm#xjts19516@彭令芳 苛虐，
監軍 rm#xjts25743@劉惠光 貪婪；
乙卯，
軍士共殺之。


# p 

發 dm#dm00446@京西 防秋兵萬二千人戍 dm#dm08286@關東 。

上御 dm#dm03700@望春樓 宴勞將士，
神策軍士獨不飮，
上使詰之，
其將 rm#xjts26526@楊惠元 對曰：
「臣等發 dm#dm01853@奉天 ，
軍帥 rm#xjts05021@張巨濟 戒之曰：
『此行大建功名，
凱還之日，
相與爲歡。』

故不敢奉詔。」

及行，
有司縁道設酒食，
獨 rm#xjts26526@惠元 所部瓶罌不發。

上深歎美，
賜書勞之。

 rm#xjts26526@惠元 ，
 dm#dm02627@平州 人也。
苟未捷勿飮酒
# p 

三月，
置 dm#dm00049@州 於 dm#dm07886@郾城 。

# p 

辛巳，
以 dm#dm04561@汾州 刺史 rm#r02690@王翃 爲 dm#dm03230@振武軍 使、 dm#dm08123@鎭北 ‧ dm#dm06439@綏 ‧ dm#dm08081@銀 等州留後。

# p 

遣殿中少監 rm#r00952@崔漢衡 使于吐蕃。

# p 

 rm#r02124@梁崇義 雖與 rm#xjts13396@李正己 等連結，
兵勢寡弱，
禮數最恭。

或勸其入朝，
 rm#r02124@崇義 曰：
「 rm#r00120@來公 有大功於國，
 y@上元中 爲閹宦所讒，
遷延稽命；
及 rm#xjts00683@代宗 嗣位，
不俟駕入朝，
猶不免族誅。

吾歳久釁積，
何可往也！」

 dm#dm04995@淮寧 節度使 rm#r01719@李希烈 屡請討之，
 rm#r02124@崇義 懼，
益脩武備。

流人 rm#xjts01499@郭昔 告 rm#r02124@崇義 爲變，
 rm#r02124@崇義 聞之，
請罪，
上爲之杖 rm#xjts01499@昔 ，
遠流之；
使金部員外郎 rm#r01935@李舟 詣 dm#dm07274@襄州 諭旨以安之。

 rm#r01935@舟 嘗奉使詣 rm#xjts25212@劉文喜 ，
爲陳禍福，
 rm#xjts25212@文喜 囚之，
會帳下殺 rm#xjts25212@文喜 以降，
諸道跋扈者聞之，
謂 rm#r01935@舟 能覆城殺將。

至 dm#dm07274@襄州 ，
 rm#r02124@崇義 惡之；
 rm#r01935@舟 又勸 rm#r02124@崇義 入朝，
言頗切直，
 rm#r02124@崇義 益不悦。

及遣使宣慰諸道，
 rm#r01935@舟 復詣 dm#dm07274@襄州 ，
 rm#r02124@崇義 拒境不内，
上言「軍中疑懼，
請易以他使。」

時 dm#dm00688@兩河 諸鎭方猜阻，
上欲示恩信以安之，
夏，
四月，
庚寅，
加 rm#r02124@崇義 同平章事，
妻子悉加封賞，
賜以鐵券；
遣御史 rm#xjts04790@張著 齎手詔徵之，
仍以其裨將 rm#xjts20163@藺杲 爲 dm#dm07942@鄧州 刺史。

# p 

五月，
丙寅，
以軍興，
増商税爲什一。

# p 

 rm#r02819@田悦 卒與 rm#xjts13396@李正己 、 rm@李惟嶽 定計，
連兵拒命，
遣兵馬使 rm#xjts06642@孟祐 將歩騎五千北助 rm@惟嶽 。

 rm@薛嵩 之死也，
 rm#r02821@田承嗣 盜據 dm#dm04838@洺 、 dm#dm06025@相 二州，
朝廷獨得 dm#dm07814@邢 、 dm#dm06175@磁 二州及 dm#dm06694@臨洺縣 。

 rm#r02819@悦 欲阻山爲境，
曰：
「 dm#dm07814@邢 、 dm#dm06175@磁 如兩眼，
在吾腹中，
不可不取。」

乃遣兵馬使 rm#xjts00456@康愔 將八千人圍 dm#dm07817@邢州 ，
別將 rm#xjts22843@楊朝光 將五千人柵於 dm#dm07824@邯鄲 西北以斷 dm#dm03524@昭義 救兵，
 rm#r02819@悦 自將兵數萬圍臨洺；
 dm#dm07817@邢州 刺史 rm@李共 、 dm#dm06692@臨洺 將 rm@張伾 堅壁拒守。
共洪
# p 

 dm#dm07514@貝州 刺史 rm#xjts06764@邢曹俊 ，
 rm#r02821@田承嗣 舊將也，
老而有謀，
 rm#r02819@悦 寵信牙官 rm@扈崿 而疏之，
及攻 dm#dm06692@臨洺 ，
召 rm#r00533@曹俊 問計，
 rm#r00533@曹俊 曰：
「兵法十圍五攻；
尚書以逆犯順，
勢更不侔。

今頓兵堅城之下，
糧竭卒盡，
自亡之道也。

不若置萬兵於 dm#dm02500@崞口 以遏西師，
則 dm#dm04656@河北 二十四州皆爲尚書有矣。」

諸將惡其異己，
共毀之，
 rm#r02819@悦 不用其策。

# p 

六月庚寅，
以 dm#dm04855@浙江東 ‧ dm#dm07286@西 觀察使、 dm#dm07147@蘇州 刺史 rm#r04122@韓滉 爲 dm#dm05367@潤州 刺史、 dm#dm04855@浙江東 ‧ dm#dm07286@西 節度使，
名其軍曰 dm#dm08133@鎭海 。
# p 

 rm#xjts04790@張著 至 dm#dm07284@襄陽 ，
 rm#r02124@梁崇義 益懼，
陳兵而見之。

 rm#xjts20163@藺杲 得詔不敢發，
馳見 rm#r02124@崇義 請命。

 rm#r02124@崇義 對 rm#xjts04790@著 號泣，
竟不受詔。

 rm#xjts04790@著 復命。
# p 

癸巳，
進 rm#r01719@李希烈 爵 rm#r01719@南平郡王 ，
加漢 dm#dm00933@南 、 dm#dm05275@漢北 兵馬招討使，
督諸道兵討之。

 rm#r02224@楊炎 諫曰：
「 rm#r01719@希烈 爲 rm#r03193@董秦 養子，
親任無比，
卒逐 rm#r03193@秦 而奪其位。

爲人狼戾無親，
無功猶倔強不法，
使平 rm#r02124@崇義 ，
何以制之！」

上不聽。

 rm#r02224@炎 固爭之，
上益不平。
# p 

 dm#dm06881@荊南 牙門將 rm#r00409@呉少誠 以取 rm#r02124@梁崇義 之策干 rm#r01719@李希烈 ，
 rm#r01719@希烈 以 rm#r00409@少誠 爲前鋒。

 rm#r00409@少誠 ，
 dm#dm02689@幽州  dm#dm05352@潞 人也。

# p 

時内自 dm#dm08281@關中 ，
西曁 dm#dm07197@蜀 、 dm#dm05271@漢 ，
南盡 dm#dm04475@江 、 dm#dm04981@淮 、 dm#dm08257@閩 、 dm#dm07606@越 ，
北至 dm#dm01774@太原 ，
所在出兵，
而 rm#xjts13396@李正己 遣兵扼 dm#dm02952@徐州  dm#dm05813@甬橋 、 dm#dm05100@渦口 ，
 rm#r02124@梁崇義 阻兵 dm#dm07284@襄陽 ，
運路皆絶，
人心震恐。

 dm#dm04475@江 、 dm#dm04981@淮 進奉船千餘艘，
泊 dm#dm05100@渦口 不敢進。

上以 dm#dm01327@和州 刺史 rm#r01242@張萬福 爲 dm#dm05450@濠州 刺史。

 rm#r01242@萬福 馳至 dm#dm05100@渦口 ，
立馬岸上，
發進奉船，
 dm#dm04964@淄青 將士停岸睥睨不敢動。
和利
# p 

辛丑，
 dm#dm04571@汾陽  rm#r03707@忠武王郭子儀 薨。

 rm#xjts01384@子儀 爲上將，
擁強兵，
 rm#r02986@程元振 、 rm#r04309@魚朝恩 讒毀百端，
詔書一紙徵之，
無不即日就道，
由是讒謗不行。

嘗遣使至 rm#r02821@田承嗣 所，
 rm#r02821@承嗣 西望拜之曰：
「此膝不屈於人若干年矣！」

 rm#xjts13521@李靈曜 據 dm#dm04541@汴州 作亂，
公私物過 dm#dm04537@汴 者皆留之，
惟 rm#xjts01384@子儀 物不敢近，
遣兵衞送出境。

校中書令考凡二十四，
月入俸錢二萬緡，
私産不在焉；
府庫珍貨山積。

家人三千人，
八子、七壻皆爲朝廷顯官；
諸孫數十人，
毎問安，
不能盡辯，
頷之而已。

 rm#r00144@僕固懷恩 、 rm#r01775@李懷光 、 rm#r02462@渾瑊 皆出麾下，
雖貴爲王公，
常頤指役使，
趨走於前，
家人亦以僕隸視之。

天下以其身爲安危殆三十年，
功蓋天下而主不疑，
位極人臣而衆不疾，
窮奢極欲而人不非之，
年八十五而終。

其將佐至大官，
爲名臣者甚衆。

# p 

壬子，
以 dm#dm03102@懷 、 dm#dm07947@鄭 、 dm#dm04709@河陽 節度副使 rm@李艽 爲 dm#dm04709@河陽 、 dm#dm03102@懷州 節度使，
割 dm#dm03857@東畿 五縣隸焉。

# p 

 dm#dm00860@北庭 、 dm#dm02061@安西 自吐蕃陷 dm#dm04650@河 、 dm#dm08457@隴 ，
隔絶不通，
 dm#dm00516@伊西 、 dm#dm00860@北庭 節度使 rm#xjts13483@李元忠 、 dm#dm01437@四鎭 留後 rm#r03725@郭昕 帥將士閉境拒守，
數遣使奉表，
皆不達，
聲問絶者十餘年；
至是，
遣使間道歴諸胡自囘紇中來，
上嘉之。

秋，
七月，
戊午朔，
加 rm#xjts13483@元忠  dm#dm00860@北庭 大都護，
賜爵 rm#xjts15675@寧塞郡王 ；
以 rm#r03725@昕 爲 dm#dm02061@安西 大都護、 dm#dm01437@四鎭 節度使，
賜爵 rm#r03725@武威郡王 ；
將士皆遷七資。

 rm#xjts13483@元忠 姓名，
朝廷所賜也，
本姓 rm#no@曹 ，
名 rm#xjts13483@令忠 ；
 rm#r03725@昕 ，
 rm#xjts01384@子儀 弟也。


# p 

 rm#r01719@李希烈 以久雨未進軍，
上怪之，
 rm#r02881@盧𣏌 密言於上曰：
「 rm#r01719@希烈 遷延，
以 rm#r02224@楊炎 故也。

陛下何愛 rm#r02224@炎 一日之名而墮大功；
不若暫免 rm#r02224@炎 相以悦之，
事平復用，
無傷也。」

上以爲然。

庚申，
以 rm#r02224@炎 爲左僕射，
罷政事。

以前 dm#dm04412@永平 節度使 rm#r01266@張鎰 爲中書侍郎、同平章事。

 rm#r01266@鎰 ，
 rm#r01275@齊丘 之子也。

以 dm#dm03677@朔方 節度使 rm#r00914@崔寧 爲右僕射。

# p 

丙子，
贈故 dm#dm00514@伊州 刺史 rm#r03372@袁光庭 工部尚書。

 rm#r03372@光庭  y@天寶末 爲 dm#dm00514@伊州 刺史，
吐蕃陷 dm#dm04650@河 、 dm#dm08457@隴 ，
 rm#r03372@光庭 堅守累年，
吐蕃百方誘之，
不下。

糧竭兵盡，
城且陷，
 rm#r03372@光庭 先殺妻子，
然後自焚。

 rm#r03725@郭昕 使至，
朝廷始知之，
故贈官。
# p 

辛巳，
以 dm#dm07810@邠寧 節度使 rm#r01775@李懷光 兼 dm#dm03677@朔方 節度使。

# p 

癸未，
 dm#dm04672@河東 節度使 rm#r04181@馬燧 ，
 dm#dm03524@昭義 節度使 rm#r01783@李抱眞 ，
神策先鋒都知兵馬使 rm@李晟 ，
大破 rm#r02819@田悦 於 dm#dm06692@臨洺 。

# p 

時 rm#r02819@悦 攻 dm#dm06692@臨洺 ，
累月不拔，
城中食且盡，
府庫竭，
士卒多死傷。

 rm#r01103@張伾 飾其愛女，
使出拜將士曰：
「諸君守戰甚苦，
 rm#r01103@伾 家無他物，
請鬻此女爲將士一日之費。」

衆皆哭，
曰：
「願盡死力，
不敢言賞。」

 rm#r01783@李抱眞 告急於朝，
詔 rm#r04181@馬燧 將歩騎二萬與 rm#r01783@抱眞 討 rm#r02819@悦 ，
又遣 rm#r01807@李晟 將神策兵與之倶；
又詔 dm#dm02689@幽州 留後 rm#r01579@朱滔 討 rm#xjts18219@惟嶽 。

# p 

 rm#r04181@燧 等軍未出險，
先遣使持書諭 rm#r02819@悦 ，
爲好語，
 rm#r02819@悦 謂 rm#r04181@燧 畏之，
不設備。

 rm#r04181@燧 與 rm#r01783@抱眞 合兵八萬，
東下 dm#dm01515@壼關 ，
軍于 dm#dm07824@邯鄲 ，
撃 rm#r02819@悦 支軍，
破之。

 rm#r02819@悦 方急攻 dm#dm06692@臨洺 ，
分 rm@李惟嶽 兵五千助 rm#xjts22843@楊朝光 。

明日，
 rm#r04181@燧 等進攻 rm@朝光 柵，
 rm#r02819@悦 將萬餘人救之，
 rm#r04181@燧 命大將 rm#r01932@李自良 等禦之於 dm#dm08514@雙岡 ，
令之曰：
「 rm#r02819@悦 得過，
必斬爾！」

 rm#r01932@自良 等力戰，
 rm#r02819@悦 軍卻。

 rm#r04181@燧 推火車焚 rm#xjts22843@朝光 柵，
斬 rm#xjts22843@朝光 ，
獲首虜五千餘級。

居五日，
 rm#r04181@燧 等進軍至 dm#dm06692@臨洺 ，
 rm#r02819@悦 悉衆力戰，
凡百餘合，
 rm#r02819@悦 兵大敗，
斬首萬餘級。

 rm#r02819@悦 引兵夜遁，
 dm#dm07817@邢州 圍亦解。

# p 

時 dm#dm02660@平盧 節度使 rm#xjts13396@李正己 已薨，
子 rm@納 祕之，
領軍務。

 rm#r02819@悦 求救於 rm@納 及 rm@李惟嶽 ，
 rm@納 遣大將 rm@衞俊 將兵萬人，
 rm@惟嶽 遣兵三千人救之。

 rm#r02819@悦 收合散卒，
得二萬餘人，
軍于 dm#dm04837@洹水 ；
 dm#dm04964@淄青 軍其東，
 dm#dm03139@成徳 軍其西，
首尾相應。

 rm#r04181@馬燧 帥諸軍進屯 dm#dm07971@鄴 ，
奏求 dm#dm04709@河陽 兵自助；
詔 dm#dm04709@河陽 節度使 rm@李艽 將兵會之。

# p 

八月，
 rm@李納 始發喪，
奏請襲父位，
上不許。
# p 

 rm#r02124@梁崇義 發兵攻 dm#dm04516@江陵 ，
至 dm#dm01436@四望 ，
大敗而歸，
乃收兵 dm#dm07261@襄 、 dm#dm07938@鄧 。

 rm#r01719@李希烈 引軍循 dm#dm05271@漢 而上，
與諸道兵會；
 rm#r02124@崇義 遣其將 rm#xjts06719@翟暉 、 rm#xjts22125@杜少誠 逆戰於 dm#dm07221@蠻水 ，
 rm#r01719@希烈 大破之；
追至 dm#dm00016@疎口 ，
又破之。

二將請降，
 rm#r01719@希烈 使將其衆先入 dm#dm07284@襄陽 慰諭軍民。

 rm#r02124@崇義 閉城拒守，
守者開門爭出，
不可禁。

 rm#r02124@崇義 與妻赴井死，
傳首 dm#dm08170@京師 。
# p 

 dm#dm06863@范陽 節度使 rm#r01579@朱滔 將討 rm@李惟嶽 ，
軍于 dm#dm06918@莫州 ；
 rm#r01268@張孝忠 將精兵八千守 dm#dm03494@易州 ，
 rm#r01579@滔 遣判官 rm#xjts21780@蔡雄 説 rm#r01268@孝忠 曰：
「 rm@惟嶽 乳臭兒，
敢拒朝命；
今 dm#dm03524@昭義 、 dm#dm04672@河東 軍已破 rm#r02819@田悦 ，
 dm#dm04995@淮寧  rm@李僕射 克 dm#dm07284@襄陽 ，
計 dm#dm04660@河南 諸軍，
朝夕北向，
 dm#dm03017@恆 、 dm#dm08945@魏 之亡，
可佇立而須也。

使君誠能首舉 dm#dm03494@易州 以歸朝廷，
則破 rm@惟嶽 之功自使君始，
此轉禍爲福之策也。」

 rm#r01268@孝忠 然之，
遣牙官 rm#r02996@程華 詣 rm#r01579@滔 ，
遣録事參軍 rm#xjts19798@董稹 奉表詣闕，
 rm#r01579@滔 又上表薦之；
上悦。

九月，
辛酉，
以 rm#r01268@孝忠 爲 dm#dm03139@成徳 節度使。

命 rm@惟嶽 護喪歸朝，
 rm@惟嶽 不從。

 rm#r01268@孝忠 徳 rm#r01579@滔 ，
爲子 rm#r01237@茂和 娶 rm#r01579@滔 女，
深相結。
# p 

壬戌，
加 rm#r01719@李希烈 同平章事。
# p 

初，
 rm#r01719@李希烈 請討 rm#r02124@梁崇義 ，
上對朝士亟稱其忠。

黜陟使 rm@李承 自淮西還，
言於上曰：
「 rm#r01719@希烈 必立微功；
但恐有功之後，
偃蹇不臣，
更煩朝廷用兵耳！」

上不以爲然。
# p 

 rm#r01719@希烈 既得 dm#dm07284@襄陽 ，
遂據之爲己有，
上乃思 rm@承 言。

時 rm@承 爲 dm#dm04651@河中 尹，
甲子，
以 rm@承 爲 dm#dm02400@山南東道 節度使。

上欲以禁兵送上，
 rm@承 請單騎赴鎭；
至 dm#dm07284@襄陽 ，
 rm#r01719@希烈 置之外館，
迫脅萬方，
 rm@承 誓死不屈，
 rm#r01719@希烈 乃大掠闔境所有而去。

 rm@承 治之期年，
軍府稍完。

 rm#r01719@希烈 留牙將於 dm#dm07274@襄州 ，
守其所掠財，
由是數有使者往來。

 rm@承 亦遣其腹心 rm#xjts09519@臧叔雅 往來 dm#dm07433@許 、 dm#dm07083@蔡 ，
厚結 rm@希烈 腹心 rm#r00465@周曾 等，
與之陰圖 rm#r01719@希烈 。

# p 

初，
 rm#xjts20022@蕭嵩 家廟臨 dm#dm03617@曲江 ，
 rm#xjts00542@玄宗 以娯遊之地，
非神靈所宅，
命徙之。

 rm#r02224@楊炎 爲相，
惡 dm#dm00427@京兆 尹 rm#r00575@嚴郢 ，
左遷大理卿；
 rm#r02881@盧𣏌 欲陷 rm#r02224@炎 ，
引 rm#r00575@郢 爲御史大夫。

先是，
 rm#r02224@炎 將營家廟，
有宅在 dm#dm03880@東都 ，
憑 dm#dm04660@河南 尹 rm#xjts23770@趙惠伯 賣之，
 rm#xjts23770@惠伯 買以爲官廨，
 rm#r00575@郢 按之，
以爲有羨利。

 rm#r02881@𣏌 召大理正 rm#xjts24272@田晉 議法，
 rm#xjts24272@晉 以爲：
「律，
監臨官市買有羨利，
以乞取論，
當奪官。」

 rm#r02881@𣏌 怒，
貶 rm#xjts24272@晉  dm#dm07230@衡州 司馬。

更召他吏議法，
以爲：
「監主自盜，
罪當絞。」

 rm#r02224@炎 廟正直 rm#xjts20022@蕭嵩 廟地，
 rm#r02881@𣏌 因譖 rm#r02224@炎 ，
云「茲地有王氣，
故 rm#xjts00542@玄宗 令 rm#xjts20022@嵩 徙之；
 rm#r02224@炎 有異志，
故於其地建廟。」

冬，
十月，
乙未，
 rm#r02224@炎 自左僕射貶 dm#dm02498@崖州 司馬；
未至 dm#dm02498@崖州 百里，
縊殺之。

 rm#xjts23770@惠伯 自 dm#dm04651@河中 尹貶 dm#dm07530@費州  dm#dm01556@多田 尉；
尋亦殺之。遣中使護送
# p 

辛巳，
册太子𡚱 rm@蕭氏 。
# p 

癸卯，
祫太廟。

先是，
 rm@太祖 既正東向之位，
 rm#xjts17657@獻 、 rm@懿 二祖皆藏西夾室，
不饗；
至是，
復奉 rm#xjts17657@獻祖 東嚮而饗之。

# p 

 dm#dm02952@徐州 刺史 rm@李洧 ，
 rm@正己 之從父兄也。

 rm@李納 寇 dm#dm02098@宋州 ，
 dm#dm02926@彭城 令 dm#dm01774@太原  rm#xjts09993@白季庚 説 rm@洧 舉州歸國；
 rm@洧 從之，
遣攝巡官 rm#xjts08653@崔程 奉表詣闕，
且使口奏，
幷白宰相，
以「 dm#dm02952@徐州 不能獨抗 rm@納 ，
乞領 dm#dm02948@徐 、 dm#dm04887@海 、 dm#dm04580@沂 三州觀察使，
況 dm#dm04887@海 、 dm#dm04580@沂 二州，
今皆爲 rm@納 有。

 rm@洧 與刺史 rm#r02495@王渉 、 rm#xjts24998@馬萬通 素有約，
苟得朝廷詔書，
必能成功。」

 rm@程 自外來，
以爲宰相一也，
先白 rm#r01266@張鎰 ，
 rm#r01266@鎰 以告 rm#r02881@盧𣏌 。

 rm#r02881@𣏌 怒其不先白己，
不從其請。

戊申，
加 rm@洧 御史大夫，
充招諭使。
# p 

十一月，
戊午，
以 rm@永樂公主 適檢校比部郎中 rm@田華 ，
上不欲違先志故也。

# p 

 rm@蜀王傀 更名 rm@遂 。

傀遂遂遡
# p 

辛酉，
 dm#dm02225@宣武 節度使 rm#r00292@劉洽 ，
 dm#dm06232@神策 都知兵馬使 rm#r01490@曲環 ，
 dm#dm05229@滑州 刺史 dm#dm07276@襄平  rm@李澄 ，
 dm#dm03677@朔方 大將 rm#xjts00838@唐朝臣 ，
大破 dm#dm04964@淄青 、 dm#dm08946@魏博 之兵於 dm#dm02952@徐州 。

# p 

先是，
 rm@李納 遣其將 rm#xjts02562@王温 會 dm#dm08946@魏博 將 rm@信都崇慶 共攻 dm#dm02952@徐州 ，
 rm@李洧 遣牙官 dm#dm05190@温 人 rm#r02653@王智興 詣闕告急。

 rm#r02653@智興 善走，
不五日而至。

上爲之發 dm#dm03677@朔方 兵五千人，
以 rm#xjts00838@朝臣 將之，
與 rm#r00292@洽 、 rm#r01490@環 、 rm@澄 共救之。

時 dm#dm03677@朔方 軍資裝不至，
旗服弊惡，
 dm#dm02225@宣武 人嗤之曰：
「乞子能破賊乎！」

 rm#xjts00838@朝臣 以其言激怒士卒，
且曰：
「都統有令，
先破賊營者，
營中物悉與之。」

士皆憤怒爭奮。
# p 

 rm@崇慶 、 rm#xjts02562@温 攻 dm#dm02926@彭城 ，
二旬不能下，
請益兵於 rm@納 ；
 rm@納 遣其將 rm@石隱金 將萬人助之，
與 rm#r00292@劉洽 等相拒於 dm#dm00109@七里溝 。

日向暮，
 rm#r00292@洽 引軍稍卻，
 dm#dm03677@朔方 馬軍使 rm#r02213@楊朝晟 言於 rm#xjts00838@唐朝臣 曰：
「公以歩兵負山而陳，
以待兩軍，
我以騎兵伏於山曲，
賊見懸軍勢孤，
必搏之；
我以伏兵絶其腰，
必敗之。」

 rm#xjts00838@朝臣 從之。

 rm@崇慶 等果將騎二千踰橋而西，
追撃官軍，
伏兵發，
横撃之；
 rm@崇慶 等兵中斷，
狼狽而返，
阻橋以拒官軍。

其兵有爭橋不得，
渉水而渡者。

 rm#r02213@朝晟 指之曰：
「彼可渉，
吾何爲不渉！

」
遂渉水撃，
據橋者皆走，
 rm@崇慶 等兵大潰；
 rm#r00292@洽 等乘之，
斬首八千級，
溺死過半。

 dm#dm03677@朔方 軍盡得其輜重，
旗服鮮華，
乃謂 dm#dm02225@宣武 人曰：
「乞子之功，
孰與 dm#dm02093@宋 多？」
 dm#dm02225@宣武 人皆慚。

官軍乘勝逐北，
至 dm#dm02952@徐州 城下，
 dm#dm08946@魏博 、 dm#dm04964@淄青 軍解圍走，
 dm#dm04475@江 、 dm#dm04981@淮 漕運始通。

# p 

己巳，
詔削 rm@李惟嶽 官爵；
募所部降者，
赦而賞之。

# p 

甲申，
 dm#dm04984@淮南 節度使 rm#r03921@陳少遊 遣兵撃 dm#dm04893@海州 ，
其刺史 rm#r02495@王渉 以州降。

# p 

十二月，
 rm@李納  dm#dm02261@密州 刺史 rm#xjts24998@馬萬通 乞降；
丁酉，
以爲 dm#dm02261@密州 刺史。

# p 

 rm#r00952@崔漢衡 至吐蕃，
贊普以敕書稱貢獻及賜，
全以臣禮見處；
又，
 dm#dm08566@雲州 之西，
當以 dm#dm07539@賀蘭山 爲境，
邀 rm#r00952@漢衡 更請之。

丁未，
 rm#r00952@漢衡 遣判官與吐蕃使者入奏。

上爲之改敕書、境土，
皆如其請。

# p 

加 rm#r04181@馬燧  dm#dm08946@魏博 招討使。
*** 三年
# year 0782
# p 

春，
正月，
 dm#dm04709@河陽 節度使 rm#r01938@李艽 引兵逼 dm#dm00029@衞州 ，
 rm#r02819@田悦 守將 rm@任履虚 詐降，
既而復叛。

# p 

 rm#r04181@馬燧 等諸軍屯于 dm#*dm05315@漳 濱。

 rm#r02819@田悦 遣其將 rm#xjts03195@王光進 築月城以守 dm#dm08207@長橋 ，
諸軍不得渡。

燧以鐵鎖連車數百，
實以土嚢，
塞其下流，
水淺，
諸軍渉渡。

時軍中乏糧，
 rm#r02819@悦 等深壁不戰。

 rm#r04181@燧 命諸軍持十日糧，
進屯 dm#dm00596@倉口 ，
與 rm#r02819@悦 夾 dm#dm04837@洹水 而軍。

 rm#r01783@李抱眞 、 rm@李艽 問曰：
「糧少而深入，
何也？」
 rm#r04181@燧 曰：
「糧少則利速戰，
今三鎭連兵不戰，
欲以老我師；
我若分軍撃其左右，
 rm#r02819@悦 必救之，
則我腹背受敵，
戰必不利。

故進軍逼 rm#r02819@悦 ，
所謂攻其所必救也。

彼苟出戰，
必爲諸君破之。」

乃爲三橋逾 dm#dm04837@洹水 ，
日往挑戰，
 rm#r02819@悦 不出。

 rm#r04181@燧 令諸軍夜半起食，
潛師循 dm#dm04837@洹水 直趨 dm#dm08950@魏州 ，
令曰：
「賊至，
則止爲陳。」

留百騎撃鼓鳴角於營中，
仍抱薪持火，
俟諸軍畢發，
則止鼓角匿其旁；
俟 rm#r02819@悦 軍畢渡，
焚其橋。

軍行十里所，
 rm#r02819@悦 聞之，
帥 dm#dm04964@淄青 、 dm#dm03139@成徳 歩騎四萬踰橋掩其後，
乘風縱火，
鼓譟而進。

 rm#r04181@燧 按兵不動，
先除其前草莽百歩爲戰場，
結陳以待之，
募勇士五千餘人爲前列。

 rm@悦 軍至，
火止，
氣衰，
 rm#r04181@燧 縱兵撃之，
 rm#r02819@悦 軍大敗。

 dm#dm06232@神策 、 dm#dm03524@昭義 、 dm#dm04709@河陽 軍小卻，
見 dm#dm04672@河東 軍捷，
還鬬，
又破之。

追奔至，
三橋已焚，
 rm#r02819@悦 軍亂，
赴水溺死不可勝紀，
斬首二萬餘級，
捕虜三千餘人，
尸相枕藉三十餘里。

# p 

 rm#r02819@悦 收餘兵千餘人走 dm#dm08950@魏州 。

 rm#r04181@馬燧 與 rm#r01783@李抱眞 不協，
頓兵 dm#dm02669@平邑 浮圖。

 rm#r02819@悦 夜至南郭，
大將 rm#xjts17567@李長春 閉關不内，
以俟官軍，
久之，
天且明，
 rm#xjts17567@長春 乃開門内之。

 rm#r02819@悦 殺 rm#xjts17567@長春 ，
嬰城拒守。

城中士卒不滿數千，
死者親戚，
號哭滿街。

 rm#r02819@悦 憂懼，
乃持佩刀，
乘馬立府門外，
悉集軍民，
流涕言曰：
「 rm#r02819@悦 不肖，
蒙 dm#dm04964@淄青 、 dm#dm03139@成徳 二丈人保薦，
嗣守伯父業，
今二丈人即世，
其子不得承襲，
 rm#r02819@悦 不敢忘二丈人大恩，
不量其力，
輒拒朝命，
喪敗至此，
使士大夫肝腦塗地，
皆 rm#r02819@悦 之罪也。

 rm#r02819@悦 有老母，
不能自殺，
願諸公以此刀斷 rm#r02819@悦 首，
持出城降 rm#r04181@馬僕射 ，
自取富貴，
無爲與悦倶死也！」

因從馬上自投地。

將士爭前抱持 rm#r02819@悦 曰：
「尚書舉兵徇義，
非私己也。

一勝一負，
兵家之常。

某輩累世受恩，
何忍聞此！

願奉尚書一戰，
不勝則以死繼之。」

 rm#r02819@悦 曰：
「諸公不以 rm#r02819@悦 喪敗而棄之，
 rm#r02819@悦 雖死，
敢忘厚意於地下！」

乃與諸將各斷髮，
約爲兄弟，
誓同生死；
悉出府庫所有及斂富民之財，
得百餘萬，
以賞士卒；
衆心始定。

復召 dm#dm07514@貝州 刺史 rm#xjts06764@邢曹俊 ，
使之整部伍，
繕守備，
軍勢復振。
遷延不進
# p 

 rm#r01905@李納 軍於 dm#dm05459@濮陽 ，
爲 dm#dm04660@河南 軍所逼，
奔還 dm#dm05457@濮州 ，
徵援兵於 dm#dm08950@魏州 。

 rm#r02819@田悦 遣軍使 rm#r03060@符璘 將三百騎送之，
 rm#r03060@璘 父 rm#r03059@令奇 謂 rm#r03060@璘 曰：
「吾老矣，
歴觀 rm#r00793@安 、 rm#xjts23917@史 輩叛亂者，
今皆安在！

 rm#xjts24378@田氏 能久乎！

汝因此棄逆從順，
是汝揚父名於後世也。」

齧臂而別。

 rm#r03060@璘 遂與其副 rm#xjts13913@李瑤 帥衆降於 rm#r04181@馬燧 。

 rm#r02819@悦 收族其家，
 rm#r03059@令奇 慢罵而死。

 rm#xjts13913@瑤 父 rm#xjts13484@再春 以 dm#dm01088@博州 降，
 rm#r02819@悦 從兄 rm#xjts24370@昂 以 dm#dm04839@洺州 降，
 rm#xjts03195@王光進 以 dm#dm08207@長橋 降。

 rm#r02819@悦 入城旬餘日，
 rm#r04181@馬燧 等諸軍始至城下，
攻之，
不克。
# p 

丙寅，
 rm@李惟嶽 遣兵與 rm#xjts06642@孟祐 守 dm#dm03779@束鹿 ，
 rm#r01579@朱滔 、 rm#r01268@張孝忠 攻拔之，
進圍 dm#dm05016@深州 。

 rm@惟嶽 憂懼，
掌書記 rm#r03688@邵眞 復説 rm@惟嶽 ，
密爲表，
先遣弟 rm#r01763@惟簡 入朝；
然後誅諸將之不從命者，
身自入朝，
使妻父 dm#dm00712@冀州 刺史 rm#xjts27398@鄭詵 權知節度事，
以待朝命。

 rm#r01763@惟簡 既行，
 rm#xjts06642@孟祐 知其謀，
密遣告 rm#r02819@田悦 。

 rm#r02819@悦 大怒，
使衙官 rm#xjts10987@扈岌 往見 rm@惟嶽 ，
讓之曰：
「尚書舉兵，
正爲大夫求旌節耳，
非爲己也。

今大夫乃信 rm#r03688@邵眞 之言，
遣弟奉表，
悉以反逆之罪歸尚書，
自求雪身，
尚書何負於大夫而至此邪！

若相爲斬 rm#r03688@邵眞 ，
則相待如初；
不然，
當與大夫絶矣。」

判官 rm#xjts24405@畢華 言於 rm@惟嶽 曰：
「 rm#r02819@田尚書 以大夫之故陷身重圍，
大夫一旦負之，
不義甚矣。

且 dm#dm08946@魏博 、 dm#dm04964@淄青 兵強食富，
足抗天下，
事未可知，
奈何遽爲二三之計乎！」

 rm@惟嶽 素怯，
不能守前計，
乃引 rm#r03688@邵眞 ，
對 rm#xjts10987@扈岌 斬之；
發 dm#dm03139@成徳 兵萬人，
與 rm#xjts06642@孟祐 倶圍 dm#dm03779@束鹿 。

丙寅，
 rm#r01579@朱滔 、 rm#r01268@張孝忠 與戰於束鹿城下，
 rm@惟嶽 大敗，
燒營而遁。

# p 

兵馬使 rm#r02656@王武俊 爲左右所構，
 rm@惟嶽 疑之，
惜其才，
未忍除也。

 dm#dm03779@束鹿 之戰，
使 rm#r02656@武俊 爲前鋒，
私自謀曰：
「我破 rm#r01579@朱滔 ，
則 rm@惟嶽 軍勢大振，
歸，
殺我必矣。」

故戰不甚力而敗。
# p 

 rm#r01579@朱滔 欲乘勝攻 dm#dm03023@恆州 ，
 rm#r01268@張孝忠 引軍西北，
軍于 dm#dm06558@義豐 。

 rm#r01579@滔 大驚，
 rm#r01268@孝忠 將佐皆怪之，
 rm#r01268@孝忠 曰：
「 dm#dm03023@恆州 宿將尚多，
未易可輕。

迫之則幷力死鬬，
緩之則自相圖。

諸君第觀之，
吾軍 dm#dm06558@義豐 ，
坐待 rm@惟嶽 之殄滅耳。

且 rm#xjts09820@朱司徒 言大而識淺，
可與共始，
難與共終也！」

於是 rm#r01579@滔 亦屯 dm#dm03779@束鹿 ，
不敢進。
# p 

 rm@惟嶽 將 rm#r01052@康日知 以 dm#dm07623@趙州 歸國，
 rm@惟嶽 益疑 rm#r02656@王武俊 ，
 rm#r02656@武俊 甚懼。

或謂 rm@惟嶽 曰：
「先相公委腹心於 rm#r02656@武俊 ，
使之輔佐大夫，
又有骨肉之親。

 rm#r02656@武俊 勇冠三軍，
今危難之際，
復加猜阻；
若無 rm#r02656@武俊 ，
欲使誰爲大夫卻敵乎！」

 rm@惟嶽 以爲然，
乃使歩軍使 rm@衞常寧 與 rm#r02656@武俊 共撃 dm#dm07623@趙州 ，
又使 rm#r02613@王士眞 將兵宿府中以自衞。


# p 

癸未，
 rm#r03363@蜀王遂 更名 rm#r03363@遡 。

# p 

 dm#dm04984@淮南 節度使 rm#r03921@陳少遊 拔 dm#dm04887@海 、 dm#dm02259@密 二州，
 rm@李納 復攻陷之。

# p 

 rm#r02656@王武俊 既出 dm#dm03023@恆州 ，
謂 rm@衞常寧 曰：
「 rm#r02656@武俊 今幸出虎口，
不復歸矣！

當北歸 rm#r01268@張尚書 。

」
 rm@常寧 曰：
「大夫暗弱，
信任左右，
觀其勢終爲 rm#r01579@朱滔 所滅。

今天子有詔，
得大夫首者，
以其官爵與之，
中丞素爲衆所服，
與其出亡，
曷若倒戈以取大夫，
轉禍爲福，
特反掌耳；
事苟不捷，
歸 rm#r01268@張尚書 ，
未晩也。」

 rm#r02656@武俊 深以爲然。

會 rm@惟嶽 使要藉 rm#xjts01275@謝遵 至 dm#dm07623@趙州 城下，
 rm#r02656@武俊 引 rm#xjts01275@遵 同謀取 rm@惟嶽 ；
 rm#xjts01275@遵 還，
密告 rm#r02613@王士眞 。

閏月，
甲辰，
 rm#r02656@武俊 、 rm@常寧 自 dm#dm07623@趙州 引兵還襲 rm@惟嶽 ；
 rm#xjts01275@遵 與 rm#r02613@士眞 矯 rm@惟嶽 命，
啓城門内之。

黎明，
 rm#r02656@武俊 帥數百騎突入府門；
 rm#r02613@士眞 應之於内，
殺十餘人。

 rm#r02656@武俊 令曰：
「大夫叛逆，
將士歸順，
敢違拒者族！」

衆莫敢動。

遂執 rm@惟嶽 ，
收 rm#xjts27398@鄭詵 、 rm#xjts24405@畢華 、 rm@王它奴 等，
皆殺之。

 rm#r02656@武俊 以 rm@惟嶽 舊使之子，
欲生送之 dm#dm08170@長安 。

 rm@常寧 曰：
「彼見天子，
將復以叛逆之罪歸咎於中丞。」

乃縊殺之，
傳首 dm#dm08170@京師 。

 dm#dm05016@深州 刺史 rm#xjts23074@楊榮國 ，
 rm@惟嶽 姉夫也，
降於 rm#r01579@朱滔 ；
 rm#r01579@滔 使復其位。

# p 

復榷天下酒，
惟 dm#dm07290@西京 不榷。

# p 

二月，
戊午，
 rm@李惟嶽 所署 dm#dm02124@定州 刺史 rm#xjts22507@楊政義 降。

時 dm#dm04656@河北 略定，
惟 dm#dm08950@魏州 未下；
 dm#dm04660@河南 諸軍攻 rm@李納 於 dm#dm05457@濮州 ，
 rm@納 勢日蹙。

朝廷謂天下不日可平；
甲子，
以 rm#r01268@張孝忠 爲 dm#dm03494@易 、 dm#dm02116@定 、 dm#dm05208@滄 三州節度使，
 rm#r02656@王武俊 爲 dm#dm03018@恆冀 都團練觀察使，
 rm#r01052@康日知 爲 dm#dm05019@深趙 都團練觀察使，
以 dm#dm02976@徳 、 dm#dm04071@棣 二州隸 rm#r01579@朱滔 ，
令還鎭。

 rm@滔 固請 dm#dm05016@深州 ，
不許，
由是怨望，
留屯 dm#dm05016@深州 。

 rm#r02656@王武俊 素輕 rm#r01268@張孝忠 ，
自以手誅 rm@李惟嶽 ，
功在 rm#r01052@康日知 上，
而 rm@孝忠 爲節度使，
己與 rm#r01052@康日知 倶爲都團練使，
又失 dm#dm07617@趙 、 dm#dm02116@定 二州，
亦不悦。

又詔以糧三千石給 rm#r01579@朱滔 ，
馬五百匹給 rm#r04181@馬燧 。

 rm#r02656@武俊 以爲朝廷不欲使故人爲節度使，
 dm#dm08946@魏博 既下，
必取 dm#dm03018@恆冀 ，
故分其糧馬以弱之，
疑，
未肯奉詔。
# p 

 rm#r02819@田悦 聞之，
遣判官 rm#xjts02222@王侑 、 rm#xjts01766@許士則 間道至 dm#dm05016@深州 ，
説 rm#r01579@朱滔 曰：
「司徒奉詔討 rm@李惟嶽 ，
旬朔之間，
拔束鹿，
下 dm#dm05016@深州 ，
 rm@惟嶽 勢䠞，
故 rm@王大夫 因司徒勝勢，
得以梟 rm@惟嶽 之首，
此皆司徒之功也。

又天子明下詔書，
令司徒得 rm@惟嶽 城邑，
皆隸本鎭；
今乃割 dm#dm05016@深州 以與 rm#r00931@日知 ，
是自棄其信也。

且今上志欲掃清 dm#dm04671@河朔 ，
不使藩鎭承襲，
將悉以文臣代武臣，
 dyn#ch123@魏 亡，
則 dyn#ch125@燕 、 dyn#ch122@趙 爲之次矣；
若 dyn#ch123@魏 存，
則 dyn#ch125@燕 、 dyn#ch122@趙 無患。

然則司徒果有意矜 dm#dm08946@魏博 之危而救之，
非徒得存亡繼絶之義，
亦子孫萬世之利也。」

又許以 dm#dm07514@貝州 賂 rm@滔 。

 rm#r01579@滔 素有異志，
聞之，
大喜，
即遣 rm#xjts02222@王侑 歸報 dm#dm08950@魏州 ，
使將士知有外援，
各自堅。

又遣判官 rm#xjts02018@王郅 與 rm#xjts01766@許士則 倶詣 dm#dm03023@恆州 ，
説 rm#r02656@王武俊 曰：
「大夫出萬死之計，
誅逆首，
拔亂根，
 rm#r01052@康日知 不出 dm#dm07623@趙州 ，
豈得與大夫同日論功！

而朝廷褒賞略同，
誰不爲大夫憤邑者！

今又聞有詔支糧馬與鄰道，
朝廷之意，
蓋以大夫善戰，
恐爲後患，
先欲貧弱軍府，
俟平 dm#dm08945@魏 之日，
使 rm@馬僕射 北首，
 rm#xjts09820@朱司徒 南向，
共相滅耳。

 rm#xjts09820@朱司徒 亦不敢自保，
使 rm#xjts02018@郅 等效愚計，
欲與大夫共救 rm#r02819@田尚書 而存之。

大夫自留糧馬以供軍；
 rm#xjts09820@朱司徒 不欲以 dm#dm05016@深州 與 rm#r01052@康日知 ，
願以與大夫，
請早定刺史以守之。

三鎭連兵，
若耳目手足之相救，
則他日永無患矣！」

 rm#r02656@武俊 亦喜，
許諾，
即遣判官 rm#xjts03024@王巨源 使於 rm#r01579@滔 ，
且令知 dm#dm05016@深州 事，
相與刻日舉兵南向。

 rm#r01579@滔 又遣人説 rm#r01268@張孝忠 ，
 rm#r01268@孝忠 不從。
無敵
# p 

 dm#dm02225@宣武 節度使 rm#r00292@劉洽 攻 rm@李納 於 dm#dm05457@濮州 ，
克其外城。

 rm@納 於城上涕泣求自新，
 rm@李勉 又遣人説之，
癸卯，
 rm@納 遣其判官 rm#r01382@房説 以其母弟 rm@經 及子 rm#xjts17059@成務 入見。

會中使 rm#xjts12007@宋鳳朝 稱 rm@納 勢窮蹙，
不可捨，
上乃囚 rm#r01382@説 等於禁中，
 rm@納 遂歸 dm#dm07905@鄆州 ，
復與 rm#r02819@田悦 等合。

朝廷以 rm@納 勢未衰，
三月，
乙未，
始以 dm#dm02952@徐州 刺史 rm@李洧 兼 dm#dm02948@徐 、 dm#dm04887@海 、 dm#dm04580@沂 都團練觀察使，
 dm#dm04887@海 、 dm#dm04580@沂 已爲 rm@納 所據，
 rm@洧 竟無所得。

# p 

 rm@李納 之初反也，
其所署 dm#dm02976@徳州 刺史 rm#xjts13474@李西華 備守甚嚴，
都虞候 rm#xjts16369@李士眞 密毀 rm#xjts13474@西華 於 rm@納 ，
 rm@納 召 rm#xjts13474@西華 還府，
以 rm#r02613@士眞 代之。

 rm#r02613@士眞 又以詐召 dm#dm04071@棣州 刺史 rm@李長卿 ，
 rm@長卿 過 dm#dm02976@徳州 ，
 rm#r02613@士眞 劫之，
與同歸國。

夏，
四月，
戊午，
以 rm#r02613@士眞 、 rm@長卿 爲二州刺史。

 rm#r02613@士眞 求援於 rm#r01579@朱滔 ，
 rm#r01579@滔 已有異志，
遣大將 rm@李濟時 將三千人聲言助 rm#r02613@士眞 守 dm#dm02976@徳州 ，
且召 rm#r02613@士眞 詣 dm#dm05016@深州 議軍事，
至則留之，
使 rm#xjts09808@濟時 領州事。

# p 

庚申，
吐蕃歸曏日所俘掠兵民八百人。

# p 

上遣中使發 dm#dm06013@盧龍 、 dm#dm03018@恆冀 、 dm#dm03492@易定 兵萬人詣 dm#dm08950@魏州 討 rm#r02819@田悦 。

 rm#r02656@王武俊 不受詔，
執使者送 rm#r01579@朱滔 ，
 rm#r01579@滔 言於衆曰：
「將士有功者，
吾奏求官勳，
皆不遂；
今欲與諸君敕裝共趨 dm#dm08950@魏州 ，
撃破 rm#r04181@馬燧 以取温飽，
何如？」
皆不應。

三問，
乃曰：
「 dm#dm02689@幽州 之人，
自 rm#r00793@安 、 rm#xjts23917@史 之反，
從而南者無一人得還，
今其遺人痛入骨髓。

況太尉、司徒皆受國寵榮，
將士亦各蒙官勳，
誠且願保目前，
不敢復有僥冀。」

 rm#r01579@滔 默然而罷。

乃誅大將數十人，
厚撫循其士卒。
# p 

 rm#r01052@康日知 聞其謀，
以告 rm#r04181@馬燧 ，
 rm#r04181@燧 以聞。

上以 dm#dm08950@魏州 未下，
 rm#r02656@王武俊 復叛，
力未能制 rm#r01579@滔 ，
壬戌，
賜 rm#r01579@滔 爵 rm@通義郡王 ，
冀以安之。

 rm#r01579@滔 反謀益甚，
分兵營於 dm#dm07623@趙州 以逼 rm#r01052@康日知 ，
以 dm#dm05016@深州 授 rm#xjts03024@王巨源 ，
 rm#r02656@武俊 以其子 rm#r02613@士眞 爲 dm#dm03017@恆 、 dm#dm00712@冀 、 dm#dm05013@深 三州留後，
將兵圍 dm#dm07623@趙州 。

# p 

 dm#dm04955@涿州 刺史 rm#r00256@劉怦 聞 rm#r01579@滔 欲救 rm#r02819@田悦 ，
以書諫之曰：
「今 dm#dm03464@昌平 故里，
朝廷改爲 dm#dm01788@太尉郷 、 dm#dm01177@司徒里 ，
此亦丈夫不朽之名也。

但以忠順自持，
則事無不濟。

竊思近日務大樂戰，
不顧成敗而家滅身屠者，
 rm#r00793@安 、 rm#xjts23917@史 是也。

 rm#r00256@怦 忝密親，
默而無告，
是負重知。

惟司徒圖之，
無貽後悔。」

 rm#r01579@滔 雖不用其言，
亦嘉其盡忠，
卒無疑貳。與滔同縣人，其母，滔之姑也，滔使知幽州留後
# p 

 rm#r01579@滔 將起兵，
恐 rm#r01268@張孝忠 爲後患，
復遣牙官 rm#xjts21780@蔡雄 往説之。

 rm#r01268@孝忠 曰：
「昔者司徒發 dm#dm02689@幽州 ，
遣人語 rm#r01268@孝忠 曰：
『 rm@李惟嶽 負恩爲逆』，
謂 rm#r01268@孝忠 歸國即爲忠臣。

 rm#r01268@孝忠 性直，
用司徒之教。

今既爲忠臣矣，
不復助逆也。

且 rm#r01268@孝忠 與 rm#r02656@武俊 皆出夷落，
深知其心最喜翻覆。

司徒勿忘鄙言，
他日必相念矣！」

 rm#xjts21780@雄 復欲以巧辭説之，
 rm#r01268@孝忠 怒，
欲執送 dm#dm08170@京師 ；
 rm#xjts21780@雄 懼，
逃歸。

 rm#r01579@滔 乃使 rm#r00256@劉怦 將兵屯要害以備之。

 rm#r01268@孝忠 完城礪兵，
獨居強寇之間，
莫之能屈。
# p 

 rm#r01579@滔 將歩騎二萬五千發 dm#dm05016@深州 ，
至 dm#dm03779@束鹿 ；
詰旦將行，
吹角未畢，
士卒忽大亂，
喧譟曰：
「天子令司徒歸 dm#dm02689@幽州 ，
奈何違敕南救 rm#r02819@田悦 ！

」
 rm#r01579@滔 大懼，
走入驛後堂避匿。

 rm#xjts21780@蔡雄 與兵馬使 rm@宗頊 等矯謂士卒曰：
「汝輩勿喧，
聽司徒傳令。」

衆稍止。

 rm#xjts21780@雄 又曰：
「司徒將發 dm#dm06863@范陽 ，
恩旨令得 rm@李惟嶽 州縣即有之，
司徒以 dm#dm02689@幽州 少絲絋，
故與汝曹竭力血戰以取 dm#dm05016@深州 ，
冀得其絲絋以寛汝曹賦率，
不意國家無信，
復以 dm#dm05016@深州 與 rm#r01052@康日知 。

又，
朝廷以汝曹有功，
賜絹人十匹，
至 dm#dm08950@魏州 西境，
盡爲 rm#r04181@馬僕射 所奪。

司徒但處 dm#dm06863@范陽 ，
富貴足矣；
今茲南行，
乃爲汝曹，
非自爲也。

汝曹不欲南行，
任自歸北，
何用喧悖，
乖失軍禮！」

衆聞言，
不知所爲，
乃曰：
「敕使何得不爲軍士守護賞物！」

遂入敕使院，
擘裂殺之。

又呼曰：
「雖知司徒此行爲士卒，
終不如且奉詔歸鎭。」

 rm#xjts21780@雄 曰：
「然則汝曹各還部伍，
詰朝復往 dm#dm05016@深州 ，
休息數日，
相與歸鎭耳。」

衆然後定。

 rm#r01579@滔 即引軍還 dm#dm05016@深州 ，
密令諸將訪察唱率爲亂者，
得二百餘人，
悉斬之，
餘衆股慄；
乃復引軍而南，
衆莫敢前卻。

進，
取 dm#dm02294@寧晉 ，
留屯以待 rm#r02656@王武俊 。

 rm#r02656@武俊 將歩騎萬五千取 dm#dm00636@元氏 ，
東趣 dm#dm02294@寧晉 。


# p 

 rm#r02656@武俊 之始誅 rm@李惟嶽 也，
遣判官 rm#r00702@孟華 入見。

 rm#r00702@華 性忠直，
有才略，
應對慷慨；
上悦，
以爲 dm#dm03018@恆冀 團練副使。

會 rm#r02656@武俊 與 rm#r01579@朱滔 有異謀，
上遽遣 rm#r00702@華 歸諭旨。

 rm#r00702@華 至，
 rm#r02656@武俊 已出師，
 rm#r00702@華 諫曰：
「聖意於大夫甚厚，
苟盡忠義，
何患官爵之不崇，
土地之不廣！

不日天子必移 rm#xjts00447@康中丞 於他鎭，
 dm#dm05013@深 、 dm#dm07617@趙 終爲大夫之有，
何苦遽自同於逆亂乎！

異日無成，
悔之何及！」

 rm#r00702@華 曏在 rm#r01157@李寶臣 幕府，
以直道已爲同列所忌，
至是爲副使，
同列尤疾之，
言於 rm#r02656@武俊 曰：
「 rm#r00702@華 以軍中陰事奏天子，
請爲内應，
故得超遷；
是將覆大夫之軍，
大夫宜備之。」

 rm#r02656@武俊 以其舊人，
不忍殺，
奪職，
使歸私第。上問以河朔利害
# p 

 rm#r02819@田悦 恃援兵將至，
遣其將 rm#xjts00456@康愔 將萬餘人出城西，
與 rm#r04181@馬燧 等戰於 dm#dm02968@御河 上，
大敗而還。

# p 

時 dm#dm00688@兩河 用兵，
月費百餘萬緡，
府庫不支數月。

太常博士 rm#xjts19014@韋都賓 、 rm#r03909@陳京 建議，
以爲：
「貨利所聚，
皆在富商，
請括富商錢，
出萬緡者，
借其餘以供軍計。

天下不過借一二千商，
則數年之用足矣。」

上從之。

甲子，
詔借商人錢，
令度支條上。

判度支 rm#r02023@杜佑 大索 dm#dm08170@長安 中商賈所有貨，
意其不實，
輒加搒捶，
人不勝苦，
有縊死者，
 dm#dm08170@長安 囂然如被寇盜。

計所得纔八十餘萬緡。

又括僦櫃質錢，
凡蓄積錢帛粟麥者，
皆借四分之一，
封其櫃窖；
百姓爲之罷市，
相帥遮宰相馬自訴，
以千萬數。

 rm#r02881@盧𣏌 始慰諭之，
勢不可遏，
乃疾驅自他道歸。

計幷借商所得，
纔二百萬緡，
人已竭矣。

 rm#r03909@京 ，
 rm#xjts26373@叔明 之五世孫也。

# p 

甲戌，
以 dm#dm03524@昭義 節度副使、 dm#dm06177@磁州 刺史 rm#xjts07065@盧玄卿 爲 dm#dm04839@洺州 刺史兼 dm#dm08946@魏博 招討副使。


# p 

初，
 rm#r01783@李抱眞 爲 dm#dm05401@澤潞 節度使，
 rm#r04181@馬燧 領 dm#dm04709@河陽 三城；
 rm#r01783@抱眞 欲殺 dm#dm03102@懷州 刺史 rm#xjts23015@楊鉥 ，
 rm#xjts23015@鉥 奔 rm#r04181@燧 ，
 rm#r04181@燧 納之，
且奏其無罪，
 rm#r01783@抱眞 怒。

及同討 rm#r02819@田悦 ，
數以事相恨望，
二人怨隙遂深，
不復相見。

由是諸軍逗橈，
久無成功，
上數遣中使和解之。

及 rm#r02656@王武俊 逼 dm#dm07623@趙州 ，
 rm@抱眞 分麾下二千人戍 dm#dm07817@邢州 ，
 rm@燧 大怒曰：
「餘賊未除，
宜相與戮力，
乃分兵自守其地！」

欲引兵歸。

 rm@李晟 説 rm#r04181@燧 曰：
「 rm@李尚書 以 dm#dm07814@邢 、 dm#dm07617@趙 連壤，
分兵守之，
誠未有害。

今公遽自引去，
衆謂公何！」

 rm#r04181@燧 悦，
乃單騎造 rm#r01783@抱眞 壘，
相與釋憾結歡。

會 dm#dm04839@洺州 刺史 rm#xjts24370@田昂 請入朝，
 rm#r04181@燧 奏以 dm#dm04839@洺州 隸 rm#r01783@抱眞 ，
請 rm#r01644@玄卿 爲刺史，
兼充招討之副。

 rm@李晟 軍先隸 rm#r01783@抱眞 ，
又請兼隸 rm#r04181@燧 ，
以示協和。

上皆從之。
我甯得獨戰邪
# p 

 dm#dm06013@盧龍 節度行軍司馬 rm#r03204@蔡廷玉 惡判官 rm#r03827@鄭雲逵 ，
奏貶 dm#dm06918@莫州 參軍。

 rm#r03827@雲逵 妻，
 rm#r01579@朱滔 之女也，
 rm#r01579@滔 復奏爲掌書記。

 rm#r03827@雲逵 深構 rm#r03204@廷玉 於 rm#r01579@滔 ，
 rm#r03204@廷玉 又與檢校大理少卿 rm#xjts09933@朱體微 言於 rm#r01577@泚 曰：
「 rm#r01579@滔 在 dm#dm02688@幽 鎭，
事多專，
其性非長者，
不可以兵權付之。」

 rm#r01579@滔 知之，
大怒，
數與 rm#r01577@泚 書，
請殺二人者，
 rm#r01577@泚 不從；
由是兄弟頗有隙。

及 rm#r01579@滔 拒命，
上欲歸罪於 rm#r03204@廷玉 等以悦 rm#r01579@滔 ，
甲子，
貶 rm#r03204@廷玉  dm#dm03978@柳州 司戸，
 rm#xjts09933@體微  dm#dm06975@萬州  dm#dm01019@南浦 尉。
言於朱泚
# p 

 dm#dm02225@宣武 節度使 rm#r00292@劉洽 攻 rm@李納 之 dm#dm05459@濮陽 ，
降其守將 rm#xjts00116@高彦昭 。

# p 

 rm#r01579@朱滔 遣人以蝋書置髻中遺 rm#r01577@朱泚 ，
欲與同反；
 rm#r04181@馬燧 獲之，
幷使者送 dm#dm08170@長安 ，
 rm#xr01577@泚 不之知。

上驛召 rm#r01577@泚 於 dm#dm09004@鳳翔 ，
至，
以蝋書幷使者示之，
 rm#r01577@泚 惶恐頓首請罪。

上曰：
「相去千里，
初不同謀，
非卿之罪也。

」
因留之 dm#dm08170@長安 私第，
賜名園、腴田、錦綵、金銀甚厚，
以安其意；
其 dm#dm02689@幽州 ‧ dm#dm06013@盧龍 節度、太尉、中書令竝如故。

# p 

上以 dm#dm02689@幽州 兵在 dm#dm09004@鳳翔 ，
思得重臣代之。

 rm#r02881@盧𣏌 忌 rm#r01266@張鎰 忠直，
爲上所重，
欲出之於外，
己得專總朝政，
乃對曰：
「 rm#r01577@朱泚 名位素崇，
 dm#dm09004@鳳翔 將校班秩已高，
非宰相信臣，
無以鎭撫，
臣請自行。」

上俛首未言，
 rm#r02881@𣏌 又曰：
「陛下必以臣貌寢，
不爲三軍所伏，
固惟陛下神算。」

上乃顧 rm#r01266@鎰 曰：
「才兼文武，
望重内外，
無以易卿。」

 rm#r01266@鎰 知爲 rm#r02881@𣏌 所排而無辭以免，
因再拜受命。

戊寅，
以 rm#r01266@鎰 兼 dm#dm09004@鳳翔 尹、 dm#dm08458@隴右 節度等使。

# p 

初，
 rm#r02881@盧𣏌 與御史大夫 rm#r00575@嚴郢 共搆 rm#r02224@楊炎 、 rm#xjts23770@趙惠伯 之獄，
 rm#r02224@炎 死，
 rm#r02881@𣏌 復忌 rm#r00575@郢 。

會 rm#r03204@蔡廷玉 等貶官，
殿中侍御史 rm#xjts27825@鄭詹 誤遞文符至 dm#dm03519@昭應 送之，
 rm#r03204@廷玉 等行已至 dm#dm07121@藍田 ，
召還而東，
 rm#r03204@廷玉 等以爲執己送 rm#r01579@朱滔 ，
至 dm#dm08614@靈寶 西，
赴 dm#dm04650@河 死。

上聞之，
駭異，
 rm#r02881@盧𣏌 因奏：
「 rm#r01577@朱泚 必疑以爲詔旨，
請遣三司使案 rm#xjts27825@詹 。」

又言：
「御史所爲，
必稟大夫，
請幷 rm#r00575@郢 案之。」

獄未具，
壬午，
 rm#r02881@𣏌 奏杖殺 rm#xjts27825@詹 於 dm#dm00427@京兆 府；
貶 rm#r00575@郢  dm#dm07530@費州 刺史，
卒於貶所。

# p 

上初即位，
 rm#r00975@崔祐甫 爲相，
務崇寛大，
故當時政聲藹然，
以爲有 y@貞觀 之風；
及 rm#r02881@盧𣏌 爲相，
知上性多忌，
因以疑似離間羣臣，
始勸上以嚴刻御下，
中外失望。
# p 

 dm#dm04984@淮南 節度使 rm#r03921@陳少遊 奏，
本道税錢毎千請増二百。

五月，
丙戌，
詔増他道税錢皆如 dm#dm04984@淮南 ；
又鹽毎斗價皆増百錢。

# p 

 rm#r01579@朱滔 、 rm#r02656@王武俊 自 dm#dm02294@寧晉 南救 dm#dm08950@魏州 ，
辛卯，
詔 dm#dm03677@朔方 節度使 rm#r01775@李懷光 將 dm#dm03677@朔方 及神策歩騎萬五千人東討 rm#r02819@田悦 ，
且拒 rm#r01579@滔 等。

 rm#r01579@滔 行至 dm#dm02113@宗城 ，
掌書記 rm#r03827@鄭雲逵 、參謀 rm#xjts24372@田景仙 棄 rm#r01579@滔 來降。

# p 

丁酉，
加 dm#dm04672@河東 節度使 rm#r04181@馬燧 同平章事。
# p 

辛亥，
置 dm#dm06550@義武軍 節度於 dm#dm02124@定州 ，
以 dm#dm03494@易 、 dm#dm02116@定 、 dm#dm05208@滄 三州隸之。

# p 

 rm#r01110@張光晟 之殺 rm@突董 也，
上欲遂絶囘紇，
召册可汗使 rm#r02468@源休 還 dm#dm01774@太原 。

久之，
乃復遣 rm#r02468@休 送 rm@突董 及翳密施、大‧小梅録等四喪還其國，
可汗遣其宰相 rm@頡子斯迦 等迎之。

 rm@頡子斯迦 坐大帳，
立 rm#r02468@休 等於帳前雪中，
詰以殺 rm@突董 之状，
欲殺者數四，
供待甚薄；
留五十餘日，
乃得歸。

可汗使人謂之曰：
「國人皆欲殺汝以償怨，
我意則不然。

汝國已殺 rm@突董 等，
我又殺汝，
如以血洗血，
汚益甚耳！

今吾以水洗血，
不亦善乎！

 dyn#ch100@唐 負我馬直百八十萬匹，
當速歸之。」

遣其散支將軍 rm#xjts00433@康赤心 隨 rm#r02468@休 入見，
 rm#r02468@休 竟不得見可汗而還。

己卯，
至 dm#dm08170@長安 ，
詔以帛十萬匹、金銀十萬兩償其馬直。

 rm#r02468@休 有口辯，
 rm#r02881@盧𣏌 恐其見上得幸，
乘其未至，
先除光祿卿。
絹六月
# p 

 rm#r01579@朱滔 、 rm#r02656@王武俊 軍至 dm#dm08950@魏州 ，
 rm#r02819@田悦 具牛酒出迎，
 dm#dm08945@魏 人懽呼動地。

 rm#r01579@滔 營於 dm#dm03058@愜山 ，
是日，
 rm#r01775@李懷光 軍亦至，
 rm#r04181@馬燧 等盛軍容迎之。

 rm#r01579@滔 以爲襲己，
遽出陳；
 rm#r01775@懷光 勇而無謀，
欲乘其營壘未就撃之。

 rm#r04181@燧 請且休將士，
觀釁而動，
 rm#r01775@懷光 曰：
「彼營壘既立，
將爲後患，
此時不可失也。」

遂撃 rm#r01579@滔 於 dm#dm03058@愜山 之西，
殺歩卒千餘人，
 rm#r01579@滔 軍崩沮；
 rm#r01775@懷光 按轡觀之，
有喜色。

士卒爭入 rm#r01579@滔 營取寶貨，
 rm#r02656@王武俊 引二千騎横衝 rm#r01775@懷光 軍，
軍分爲二；
 rm#r01579@滔 引兵繼之，
官軍大敗，
蹙入 dm#dm04439@永濟渠 溺死者不可勝數，
人相蹈藉，
其積如山，
水爲之不流，
 rm#r04181@馬燧 等各收軍保壘。

是夕，
 rm#r01579@滔 等堰 dm#dm04439@永濟渠 入 dm#dm05732@王莽故河 ，
絶官軍糧道及歸路，
明日，
水深三尺餘。

 rm#r04181@馬燧 懼，
遣使卑辭謝 rm#r01579@滔 ，
求與諸節度歸本道，
奏天子，
請以 dm#dm04656@河北 事委 rm#r01579@五郎 處之。

 rm#r01579@滔 欲許之，
 rm#r02656@王武俊 以爲不可；
 rm#r01579@滔 不從。

秋七月，
 rm#r04181@燧 與諸軍渉水而西，
退保 dm#dm08955@魏縣 以拒 rm#r01579@滔 ，
 rm#r01579@滔 乃謝 rm#r02656@武俊 ，
 rm#r02656@武俊 由是恨 rm#r01579@滔 。

後數日，
 rm#r01579@滔 等亦引兵營 dm#dm08955@魏縣 東南，
與官軍隔水相拒。
愜山連篋山
# p 

 rm@李納 求救於 rm#r01579@滔 等，
 rm#r01579@滔 遣 dm#dm08946@魏博 兵馬使 rm@信都承慶 將兵助之。

 rm@納 攻 dm#dm02098@宋州 ，
不克，
遣兵馬使 rm#xjts16283@李克信 、 rm@李欽遙 戍 dm#dm05459@濮陽 、 dm#dm01042@南華 以拒 rm#r00292@劉洽 。

# p 

甲辰，
以 dm#dm04995@淮寧 節度使 rm#r01719@李希烈 兼 dm#dm02660@平盧 、 dm#dm04964@淄青 、 dm#dm00665@兗鄆 、 dm#dm05864@登莱 、 dm#dm09208@齊州 節度使，
討 rm@李納 ；
又以 dm#dm04672@河東 節度使 rm#r04181@馬燧 兼 dm#dm08946@魏博 、 dm#dm05418@澶相 節度使；
加 dm#dm03677@朔方 、 dm#dm07810@邠寧 節度使 rm#r01775@李懷光 同平章事。

# p 

 dm#dm06232@神策 行營招討使 rm@李晟 請以所將兵北解 dm#dm07623@趙州 之圍，
與 rm#r01268@張孝忠 分勢圖 dm#dm06863@范陽 ，
上許之。

 rm@晟 自 dm#dm08950@魏州 引兵北趨 dm#dm07623@趙州 ，
 rm#r02613@王士眞 解圍去。

 rm@晟 留 dm#dm07623@趙州 三日，
與 rm#r01268@孝忠 合兵北略 dm#dm03023@恆州 。

# p 

 dm#dm05262@演州 司馬 rm#xjts14027@李孟秋 舉兵反，
自稱 dm#dm01981@安南 節度使；
 dm#dm01981@安南 都護 rm@輔良交 討斬之。

# p 

八月，
丁未，
置 dm#dm04650@河 東、西水陸運、兩税、鹽鐵使二人，
度支總其大要而已。
河汴
# p 

辛酉，
以 dm#dm04920@涇原 留後 rm#r00621@姚令言 爲節度使。
# p 

 rm@盧𣏌 惡太子太師 rm#r04147@顏眞卿 ，
欲出之於外。

 rm#r04147@眞卿 謂 rm@𣏌 曰：
「先中丞傳首至 dm#dm02609@平原 ，
 rm#r04147@眞卿 以舌舐面血。

今相公忍不相容乎！」

 rm@𣏌 矍然起拜，
然恨之益甚。
# p 

九月癸卯，
殿中少監 rm#r00952@崔漢衡 自吐蕃歸，
贊普遣其臣 rm#xjts25061@區頬贊 隨 rm#r00952@漢衡 入見。

# p 

冬，
十月，
辛亥，
以 dm#dm05139@湖南 觀察使 rm@曹王皋 爲 dm#dm04480@江南西道 節度使。

 rm@皋 至 dm#dm04806@洪州 ，
悉集將佐，
簡閲其才，
得牙將 rm#r00096@伊愼 、 rm#r02713@王鍔 等，
擢爲大將，
引 dm#dm06893@荊襄 判官 rm#r03505@許孟容 置幕府。

 rm@愼 ，
 dm#dm00663@兗州 人；
 rm#r03505@孟容 ，
 dm#dm08170@長安 人也。
# p 

 rm@愼 常從 rm#r01719@李希烈 討 rm#r02124@梁崇義 ，
 rm@希烈 愛其才，
欲留之，
 rm@愼 逃歸。

 rm@希烈 聞 rm@皋 用 rm@愼 ，
恐爲己患，
遺愼七屬甲，
詐爲復書，
墜之境上。

上聞之，
遣中使即軍中斬 rm@愼 ，
 rm@皋 爲之論雪；
未報。

會江賊三千餘衆入寇，
 rm@皋 遣 rm@愼 撃賊自贖；
 rm@愼 撃破之，
斬首數百級而還，
由是得免。
# p 

 rm@盧𣏌 秉政，
知上必更立相，
恐其分己權，
乘間薦吏部侍郎 rm#r03890@關播 儒厚，
可以鎭風俗；
丙辰，
以 rm@播 爲中書侍郎、同平章事。

政事皆決於 rm@𣏌 ，
 rm@播 但斂袵無所可否。

上嘗從容與宰相論事，
 rm@播 意有所不可，
起立欲言，
 rm@𣏌 目之而止。

還至中書，
 rm@𣏌 謂 rm@播 曰：
「以足下端慤少言，
故相引至此，
曏者奈何發口欲言邪！」

 rm@播 自是不復敢言。

# p 

戊辰，
遣都官員外郎 rm#r02269@樊澤 使于吐蕃，
告以結盟之期。河中
# p 

丙子，
 rm@肅王詳 薨。

# p 

十一月，
己卯朔，
加 dm#dm04984@淮南 節度使 rm#r03921@陳少遊 同平章事。
# p 

 rm#r02819@田悦 徳 rm#r01579@朱滔 之救，
與 rm#r02656@王武俊 議奉 rm@滔 爲主，
稱臣事之，
 rm#r01579@滔 不可，
曰：
「 dm#dm03058@愜山 之捷，
皆大夫、二兄之力，
 rm#r01579@滔 何敢獨居尊位！」

於是 dm#dm02689@幽州 判官 rm#xjts13999@李子千 、 dm#dm03018@恆冀 判官 rm@鄭濡 等共議：
「請與 dm#dm07905@鄆州  rm#r05361@李大夫 爲四國，
倶稱王而不改年號，
如昔諸侯奉 dyn#ch103@周 家正朔。

築壇同盟，
有不如約者，
衆共伐之。

不然，
豈得常爲叛臣，
茫然無主，
用兵既無名，
有功無官爵爲賞，
使將吏何所依歸乎！」

 rm#r01579@滔 等皆以爲然。

 rm#r01579@滔 乃自稱 rm#r01579@冀王 ，
 rm#r02819@田悦 稱 rm#r02819@魏王 ，
 rm#r02656@王武俊 稱 rm#r02656@趙王 ，
仍請 rm@李納 稱 rm@齊王 。

是日，
 rm#r01579@滔 等築壇於軍中，
告天而受之。

 rm#r01579@滔 爲盟主，
稱孤；
 rm#r02656@武俊 、 rm#r02819@悦 、 rm@納 稱寡人。

所居堂曰殿，
處分曰令，
羣下上書曰牋。

妻曰𡚱，
長子曰世子。

各以其所治州爲府，
置留守兼元帥，
以軍政委之；
又置東西曹，
視中書、門下省；
左右内史，
視侍中、中書令；
餘官皆倣天朝而易其名。
# p 

 rm#r02656@武俊 以 rm#r00702@孟華 爲司禮尚書，
華竟不受，
嘔血死；
以兵馬使 rm@衞常寧 爲内史監，
委以軍事。

 rm@常寧 謀殺 rm#r02656@武俊 ，
 rm#r02656@武俊 腰斬之。

 rm#r02656@武俊 遣其將 rm@張終葵 寇 dm#dm07623@趙州 ，
 rm#r01052@康日知 撃斬之。

# p 

 rm#r01719@李希烈 帥所部三萬徙鎭 dm#dm07433@許州 ，
遣所親詣 rm@李納 ，
與謀共襲 dm#dm04541@汴州 ；
遣使告 rm@李勉 ，
云已兼領 dm#dm04964@淄青 ，
欲假道之官。

 rm@勉 爲之治橋、具饌以待之，
而嚴爲之備。

 rm#r01719@希烈 竟不至，
又密與 rm#r01579@朱滔 等交通，
 rm@納 亦數遣遊兵渡 dm#dm04537@汴 以迎 rm#r01719@希烈 。

由是東南轉輸者皆不敢由 dm#dm04545@汴渠 ，
自 dm#dm07087@蔡水 而上。

# p 

十二月，
丁丑，
 rm#r01719@李希烈 自稱天下都元帥、太尉、 rm#r01719@建興王 。

時 rm#r01579@朱滔 等與官軍相拒累月，
官軍有度支饋糧，
諸道益兵，
而 rm#r01579@滔 與 rm#r02656@王武俊 孤軍深入，
專仰給於 rm#r02819@田悦 ，
客主日益困弊。

聞 rm#r01719@李希烈 軍勢甚盛，
頗怨望，
乃相與謀遣使詣 dm#dm07433@許州 ，
勸 rm#r01719@希烈 稱帝，
 rm#r01719@希烈 由是自稱天下都元帥。

# p 

司天少監 rm#r01314@徐承嗣 請更造建中正元暦；
從之。

*** 建中四年
# year 0783
# p 

春，
正月，
丁亥，
 dm#dm08458@隴右 節度使 rm#r01266@張鎰 與吐蕃 rm#xjts28773@尚結贊 盟于 dm#dm05042@清水 。

# p 

庚寅，
 rm#r01719@李希烈 遣其將 rm#xjts16254@李克誠 襲陷 dm#dm04465@汝州 ，
執別駕 rm#r01622@李元平 。

 rm#r01622@元平 ，
本 dm#dm05139@湖南 判官，
薄有才藝，
性疏傲，
敢大言，
好論兵；
 rm#r03890@關播 奇之，
薦於上，
以爲將相之器，
以 dm#dm04465@汝州 距 dm#dm07433@許州 最近，
擢 rm#r01622@元平 爲 dm#dm04465@汝州 別駕，
知州事。

 rm#r01622@元平 至 dm#dm04465@汝州 ，
即募工徒治城；
 rm#r01719@希烈 陰使壯士應募執役，
入數百人，
 rm#r01622@元平 不之覺。

 rm#r01719@希烈 遣 rm@克誠 將數百騎突至城下，
應募者應之於内，
縛 rm#r01622@元平 馳去。

 rm#r01622@元平 爲人眇小，
無須，
見 rm#r01719@希烈 恐懼，
便液汚地。

 rm#r01719@希烈 罵之曰：
「盲宰相以汝當我，
何相輕也！」

以判官 rm#xjts26667@周晃 爲 dm#dm04465@汝州 刺史，
又遣別將 rm#xjts19799@董待名 等四出抄掠，
取 dm#dm02347@尉氏 ，
圍 dm#dm07949@鄭州 ，
官軍數爲所敗。

邏騎西至 dm#dm02931@彭婆 ，
 dm#dm03880@東都 士民震駭，
竄匿山谷；
留守 rm#r03783@鄭叔則 入保西苑。
中書侍郎
# p 

上問計於 rm#r02881@盧𣏌 ，
對曰：
「 rm#r01719@希烈 年少驍將，
恃功驕慢，
將佐莫敢諫止；
誠得儒雅重臣，
奉宣聖澤，
爲陳逆順禍福，
 rm#r01719@希烈 必革心悔過，
可不勞軍旅而服。

 rm#r04147@顏眞卿 三朝舊臣，
忠直剛決，
名重海内，
人所信服，
眞其人也！」

上以爲然。

甲午，
命 rm#r04147@眞卿 詣 dm#dm07433@許州 宣慰 rm#r01719@希烈 。

詔下，
舉朝失色。

# p 

 rm#r04147@眞卿 乘驛至 dm#dm03880@東都 ，
 rm#r03783@鄭叔則 曰：
「往必不免，
宜少留，
須後命。」

 rm#r04147@眞卿 曰：
「君命也，
將焉避之！

」
遂行。

 rm@李勉 表言：
「失一元老，
爲國家羞，
請留之。」

又使人邀 rm#r04147@眞卿 ，
不及。

 rm#r04147@眞卿 與其子書，
但敕以「奉家廟、撫諸孤」
而已。

至 dm#dm07433@許州 ，
欲宣詔旨，
 rm@希烈 使其養子千餘人環繞慢罵，
拔刃擬之，
爲將剸啗之勢；
 rm#r04147@眞卿 足不移，
色不變。

 rm#r01719@希烈 遽以身蔽之，
麾衆令退，
館 rm#r04147@眞卿 而禮之。

 rm#r01719@希烈 欲遣 rm#r04147@眞卿 還，
會 rm#r01622@李元平 在座，
 rm#r04147@眞卿 責之，
 rm#r01622@元平 慚而起，
以密啓白 rm#r01719@希烈 ；
 rm#r01719@希烈 意遂變，
留 rm#r04147@眞卿 不遣。於道
# p 

 rm#r01579@朱滔 、 rm#r02656@王武俊 、 rm#r02819@田悦 、 rm@李納 各遣使詣 rm@希烈 ，
上表稱臣，
勸進，
使者拜舞於 rm#r01719@希烈 前，
説 rm#r01719@希烈 曰：
「朝廷誅滅功臣，
失信天下；
都統英武自天，
功烈蓋世，
已爲朝廷所猜忌，
將有 rm#r06274@韓 、 rm#r06288@白 之禍，
願亟稱尊號，
使四海臣民知有所歸。」

 rm#r01719@希烈 召 rm#r04147@顏眞卿 示之曰：
「今四王遣使見推，
不謀而同，
太師觀此事勢，
豈吾獨爲朝廷所忌無所自容邪！」

眞卿曰：
「此乃四凶，
何謂四王！

相公不自保功業，
爲 dyn#ch100@唐 忠臣，
乃與亂臣賊子相從，
求與之同覆滅邪！」

 rm#r01719@希烈 不悦，
扶 rm#r04147@眞卿 出。

他日，
又與四使同宴，
四使曰：
「久聞太師重望，
今都統將稱大號而太師適至，
是天以宰相賜都統也。」

 rm#r04147@眞卿 叱之曰：
「何謂宰相！

汝知有罵 rm#r00793@安祿山 而死者 rm#r04143@顏杲卿 乎？
乃吾兄也。

吾年八十，
知守節而死耳，
豈受汝輩誘脅乎！」

四使不敢復言。

 rm#r01719@希烈 乃使甲士十人守 rm#r04147@眞卿 於館舍，
掘坎於庭，
云欲阬之，
 rm#r04147@眞卿 怡然，
見 rm#r01719@希烈 曰：
「死生已定，
何必多端！

亟以一劍相與，
豈不快公心事邪！」

 rm#r01719@希烈 乃謝之。

# p 

戊戌，
以左龍武大將軍 rm#r00486@哥舒曜 爲 dm#dm03880@東都 、 dm#dm04465@汝州 節度使，
將 dm#dm09004@鳳翔 、 dm#dm07810@邠寧 、 dm#dm04920@涇原 、 dm#dm01853@奉天 、 dm#dm01876@好畤 行營兵萬餘人討 rm@希烈 ，
又詔諸道共討之。

 rm#r00486@曜 行至 dm#dm07851@郟城 ，
遇 rm#r01719@希烈 前鋒將 rm#r03914@陳利貞 ，
撃破之；
 rm#r01719@希烈 勢小沮。

 rm#r00486@曜 ，
 rm#r00487@翰 之子也。

# p 

 rm#r01719@希烈 使其將 rm@封有麟 據 dm#dm07942@鄧州 ，
南路遂絶貢獻，
商旅皆不通。

壬寅，
詔治 dm#dm00179@上津 山路，
置郵驛。

# p 

二月，
戊申朔，
命鴻臚卿 rm#r00952@崔漢衡 送 rm#xjts25061@區頬贊 還吐蕃。


# p 

丙寅，
以 dm#dm04709@河陽 三城、 dm#dm03102@懷 、 dm#dm00029@衞州 爲 dm#dm04713@河陽軍 。
# p 

丁卯，
 rm#r00486@哥舒曜 克 dm#dm04465@汝州 ，
擒 rm#xjts26667@周晃 。
# p 

三月，
戊寅，
 dm#dm04509@江西 節度使 rm#r00535@曹王皋 敗 rm#r01719@李希烈 將 rm#xjts20531@韓霜露 於 dm#dm09118@黄梅 ，
斬之；
辛卯，
拔 dm#dm09115@黄州 。

時 rm#r01719@希烈 兵柵 dm#dm07085@蔡山 ，
險不可攻。

 rm#r00535@皋 聲言西取 dm#dm07136@蘄州 ，
引舟師泝 dm#dm04475@江 而上，
 rm@希烈 之將引兵循 dm#dm04475@江 隨戰。

去 dm#dm07085@蔡山 三百餘里，
 rm@皋 乃復放舟順流而下，
急攻 dm#dm07085@蔡山 ，
拔之。

 rm@希烈 兵還救之，
不及而敗。

 rm@皋 遂進拔 dm#dm07136@蘄州 ，
表 rm#r00096@伊愼 爲 dm#dm07136@蘄州 刺史，
 rm#r02713@王鍔 爲 dm#dm04490@江州 刺史。
# p 

 dm#dm04995@淮寧 都虞候 rm#r00465@周曾 、鎭遏兵馬使 rm@王玢 、押牙 rm#xjts19653@姚憺 、 rm@韋清 密輸款於 rm@李勉 。

 rm#r01719@李希烈 遣 rm#r00465@曾 與十將 rm#xjts00408@康秀琳 將兵三萬攻 rm#r00486@哥舒曜 ，
至 dm#dm07267@襄城 ，
 rm#r00465@曾 等密謀還軍襲 rm#r01719@希烈 ，
奉 rm#r04147@顏眞卿 爲節度使，
使 rm@玢 、 rm#xjts19653@憺 、 rm@清 爲内應。

 rm#r01719@希烈 知之，
遣別將 rm#xjts16254@李克誠 將騾軍三千人襲 rm#r00465@曾 等，
殺之，
幷殺 rm@玢 、 rm#xjts19653@憺 及其黨。

甲午，
詔贈 rm#r00465@曾 等官。

始，
 rm@韋清 與曾等約，
事泄不相引，
故獨得免。

 rm@清 恐終及禍，
説 rm#r01719@希烈 請詣 rm#r01579@朱滔 乞師，
 rm#r01719@希烈 遣之，
行至 dm#dm07281@襄邑 ，
逃奔 rm#r00292@劉洽 。

 rm#r01719@希烈 聞 rm#r00465@周曾 等有變，
閉壁數日；
其黨寇 dm#dm02347@尉氏 、 dm#dm07949@鄭州 者聞之，
亦遁歸。

 rm#r01719@希烈 乃上表歸咎於 rm#r00465@周曾 等，
引兵還 dm#dm07086@蔡州 ，
外示悔過從順，
實待 rm#r01579@朱滔 等之援也。

置 rm#r04147@顏眞卿 於 dm#dm09260@龍興寺 。

# p 

丁酉，
 dm#dm06881@荊南 節度使 rm#r01102@張伯儀 與 dm#dm04995@淮寧 兵戰於 dm#dm02008@安州 ，
官軍大敗，
 rm#r01102@伯儀 僅以身免，
亡其所持節。

 rm#r01719@希烈 使人以其節及俘馘示 rm#r04147@顏眞卿 ；
 rm#r04147@眞卿 號慟投地，
絶而復蘇，
自是不復與人言。

# p 

夏，
四月，
上以神策軍使 rm#r02849@白志貞 爲 dm#dm08170@京城 召募使，
募禁兵以討 rm#r01719@李希烈 。

 rm#r02849@志貞 請諸嘗爲節度、觀察、都團練使者，
不問存沒，
竝勒其子弟帥奴馬自備資裝從軍，
授以五品官；
貧者甚苦之，
人心始搖。

# p 

上命宰相、尚書與吐蕃 rm#xjts25061@區頬贊 盟於 dm#dm07485@豐邑里 ，
 rm#xjts25061@區頬贊 以 dm#dm05042@清水 之盟，
疆埸未定，
不果盟。

己未，
命 rm#r00952@崔漢衡 入吐蕃，
決於贊普。

# p 

庚申，
加 dm#dm04412@永平 、 dm#dm02225@宣武 、 dm#dm04709@河陽 都統 rm@李勉  dm#dm05005@淮西 招討使，
 dm#dm03880@東都 、 dm#dm04465@汝州 節度使 rm#r00486@哥舒曜 爲之副，
以 dm#dm06881@荊南 節度使 rm#r01102@張伯儀 爲 dm#dm05005@淮西 應援招討使，
 dm#dm02400@山南東道 節度使 rm#r03583@賈耽 、 dm#dm04509@江西 節度使 rm#r00535@曹王皋 爲之副。

上督 rm#r00486@哥舒曜 進兵，
 rm#r00486@曜 至 dm#dm05336@潁橋 ，
遇大雨，
還保 dm#dm07267@襄城 。

 rm#r01719@李希烈 遣其將 rm@李光輝 攻 dm#dm07267@襄城 ；
 rm#r00486@曜 撃卻之。
# p 

五月，
乙酉，
 rm@潁王璬 薨。

# p 

乙未，
以 dm#dm02225@宣武 節度使 rm#r00292@劉洽 兼 dm#dm04964@淄青 招討使。
# p 

 rm@李晟 謀取 dm#dm04955@涿 、 dm#dm06918@莫 二州，
以絶 dm#dm02688@幽 、 dm#dm08945@魏 往來之路，
與 rm#r01268@張孝忠 之子 rm@升雲 圍 rm#r01579@朱滔 所署 dm#dm03494@易州 刺史 rm#xjts28406@鄭景濟 於 dm#dm05074@清苑 ，
累月不下。

 rm#r01579@滔 以其司武尚書 rm#xjts24968@馬寔 爲留守，
將歩騎萬餘守 dm#dm08945@魏 營，
自將歩騎萬五千救 dm#dm05074@清苑 。

 rm@李晟 軍大敗，
退保 dm#dm03494@易州 。

 rm#r01579@滔 還軍 dm#dm05480@瀛州 ，
 rm@張升雲 奔 dm#dm05249@滿城 。

會 rm@晟 病甚，
引軍還保 dm#dm02124@定州 。

# p 

 rm#r02656@王武俊 以 rm#r01579@滔 既破 rm@李晟 ，
留屯 dm#dm05480@瀛州 ，
未還 dm#dm08954@魏橋 ，
遣其給事中 rm#xjts11879@宋端 趣之。

 rm#xjts11879@端 見 rm#r01579@滔 ，
言頗不遜，
 rm#r01579@滔 怒，
使謂 rm#r02656@武俊 曰：
「 rm#r01579@滔 以熱疾，
暫未南還，
大王二兄遽有云云。

 rm#r01579@滔 以救 dm#dm08946@魏博 之故，
叛君棄兄，
如脱屣耳。

二兄必相疑，
惟二兄所爲！」

 rm#xjts11879@端 還報，
 rm#r02656@武俊 自辨於 rm#xjts24968@馬寔 ，
 rm#xjts24968@寔 以状白 rm#r01579@滔 ，
言：
「 rm@趙王 知 rm#xjts11879@宋端 無禮於大王，
深加責讓，
實無他志。」

 rm#r02656@武俊 亦遣承令官 rm@鄭和 隨 rm#xjts24968@寔 使者見 rm#r01579@滔 ，
謝之。

 rm#r01579@滔 乃悦，
相待如初。

然 rm#r02656@武俊 以是益恨 rm#r01579@滔 矣。

# p 

六月，
 rm#r01783@李抱眞 使參謀 rm#xjts03852@賈林 詣 rm#r02656@武俊 壁詐降。

 rm#r02656@武俊 見之。

 rm#xjts03852@林 曰：
「 rm#xjts03852@林 來奉詔，
非降也。」

 rm#r02656@武俊 色動，
問其故，
 rm#xjts03852@林 曰：
「天子知大夫宿著誠效，
及登壇之日，
撫膺顧左右曰：
『我本徇忠義，
天子不察。』

諸將亦嘗共表大夫之志。

天子語使者曰，
『朕前事誠誤，
悔之無及。

朋友失意，
尚可謝，
況朕爲四海之主乎！』」

 rm#r02656@武俊 曰：
「僕胡人也，
爲將尚知愛百姓；
況天子，
豈專以殺人爲事乎！

今 dm#dm02403@山東 連兵，
暴骨如莽，
就使克捷，
與誰守之！

僕不憚歸國，
但已與諸鎭結盟。

胡人性直，
不欲使曲在己，
天子誠能下詔赦諸鎭之罪，
僕當首唱從化；
諸鎭有不從者，
請奉辭伐之。

如此，
則上不負天子，
下不負同列，
不過五旬，
 dm#dm04671@河朔 定矣。」

使 rm#xjts03852@林 還報 rm#r01783@抱眞 ，
陰相約結。

# p 

庚戌，
初行税間架、除陌錢法。

時 dm#dm04672@河東 、 dm#dm05401@澤潞 、 dm#dm04709@河陽 、 dm#dm03677@朔方 四軍屯 dm#dm08955@魏縣 ，
神策、 dm#dm04412@永平 、 dm#dm02225@宣武 、 dm#dm04984@淮南 、 dm#dm04858@浙西 、 dm#dm06881@荊南 、 dm#dm04499@江泗 、 dm#dm04608@沔鄂 、 dm#dm05139@湖南 、 dm#dm09182@黔中 、 dm#dm00785@劍南 、 dm#dm02527@嶺南 諸軍環 dm#dm04995@淮寧 之境。

舊制，
諸道軍出境，
皆仰給度支；
上優恤士卒，
毎出境，
加給酒肉，
本道糧仍給其家，
一人兼三人之給，
故將士利之。

各出軍纔逾境而止，
月費錢百三十餘萬緡，
常賦不能供。

判度支 rm#r03635@趙贊 乃奏行二法：
所謂税間架者，
毎屋兩架爲間，
上屋税錢二千，
中税千，
下税五百，
吏執筆握算，
入人室廬計其數。

或有宅屋多而無他資者，
出錢動數百緡。

敢匿一間，
杖六十，
賞告者錢五十緡。

所謂除陌錢者，
公私給與及賣買，
毎緡官留五十錢，
給他物及相貿易者，
約錢爲率。

敢隱錢百，
杖六十，
罰錢二千，
賞告者錢十緡，
其賞錢皆出坐事之家。

於是愁怨之聲，
盈於遠近。
# p 

丁卯，
徙 rm#r00037@郴王逾 爲 rm#r00037@丹王 ，
 rm#r03067@鄜王遘 爲 rm#r03067@簡王 。


# p 

庚午，
答蕃判官監察御史 rm#r00042@于頔 與吐蕃使者 rm@論剌沒藏 至自 dm#dm08673@青海 ，
言疆埸已定，
請遣 rm#xjts25061@區頬贊 歸國。

秋，
七月，
甲申，
以禮部尚書 rm#r01787@李揆 爲入蕃會盟使。

壬辰，
詔諸將相與 rm#xjts25061@區頬贊 盟於城西。

 rm#r01787@李揆 有才望，
 rm@盧𣏌 惡之，
故使之入吐蕃。

 rm#r01787@揆 言於上曰：
「臣不憚遠行，
恐死於道路，
不能達詔命！

」
上爲之惻然，
謂 rm@𣏌 曰：
「 rm#r01787@揆 無乃太老！」

 rm#r02881@𣏌 曰：
「使遠夷，
非諳練朝廷故事者不可。

且 rm#r01787@揆 行，
則自 y@今年 少於 rm#r01787@揆 者不敢辭遠使矣。」


# p 

八月，
丁未，
 rm#r01719@李希烈 將兵三萬圍 rm#r00486@哥舒曜 於 dm#dm07267@襄城 ，
詔 rm@李勉 及 dm#dm06232@神策 將 rm#xjts25436@劉徳信 將兵救之。

乙卯，
 rm#r01719@希烈 將 rm#xjts24163@曹季昌 以 dm#dm08448@隨州 降，
尋復爲其將 rm@康叔夜 所殺。

# p 

初，
上在東宮，
聞監察御史 dm#dm01421@嘉興  rm#r03959@陸贄 名，
即位，
召爲翰林學士，
數問以得失。

時 dm#dm00688@兩河 用兵久不決，
賦役日滋，
 rm#r03959@贄 以兵窮民困，
恐別生内變，
乃上奏，
其略曰：
「克敵之要，
在乎將得其人；
馭將之方，
在乎操得其柄。

將非其人者，
兵雖衆不足恃；
操失其柄者，
將雖材不爲用。」

又曰：
「將不能使兵，
國不能馭將，
非止費財翫寇之弊，
亦有不戢自焚之災。」

又曰：
「今 dm#dm00688@兩河 、 dm#dm05005@淮西 爲叛亂之帥者，
獨四五凶人而已。

尚恐其中或遭詿誤，
内蓄危疑；
蒼黄失圖，
勢不得止。

況其餘衆，
蓋竝脅從，
苟知全生，
豈願爲惡！」

又曰：
「無紓目前之虞，
或興意外之變。

人者，
邦之本也。

財者，
人之心也。

其心傷則其本傷，
其本傷則枝幹顛瘁矣。」

又曰：
「人搖不寧，
事變難測，
是以兵貴拙速，
不貴巧遲。

若不靖於本而務救於末，
則救之所爲，
乃禍之所起也。」

又論 dm#dm08281@關中 形勢，
以爲：
「王者蓄威以昭徳，
偏廢則危；
居重以馭輕，
倒持則悖。

王畿者，
四方之本也。

 rm#r01602@太宗 列置府兵，
分隸禁衞，
大凡諸府八百餘所，
而在 dm#dm08281@關中 者殆五百焉。

舉天下不敵 dm#dm08281@關中 ，
則居重馭輕之意明矣。

承平漸久，
武備浸微，
雖府衞具存而卒乘罕習。

故 rm#r00793@祿山 竊倒持之柄，
乘外重之資，
一舉滔天，
 dm#dm00683@兩京 不守。

尚頼西邊有兵，
諸牧有馬，
毎州有糧，
故 rm#r01661@肅宗 得以中興。

 y@乾元 之後，
繼有外虞，
悉師東討，
邊備既弛，
禁戎亦空，
吐蕃乘虚，
深入爲寇，
故先皇帝莫與爲禦，
避之東遊。

是皆失居重馭輕之權，
忘深根固柢之慮。

内寇則 dm#dm04362@殽 、 dm#dm00738@函 失險，
外侵則 dm#dm00067@汧 、 dm#dm05102@渭 爲戎。

于斯之時，
雖有四方之師，
寧救一朝之患，
陛下追想及此，
豈不爲之寒心哉！

今 dm#dm03677@朔方 、 dm#dm01774@太原 之衆，
遠在 dm#dm02403@山東 ；
神策六軍之兵，
繼出 dm#dm08280@關 外。

儻有賊臣啗寇，
黠虜覷邊，
伺隙乘虚，
微犯亭障，
此愚臣所竊憂也。

未審陛下其何以禦之！

側聞伐叛之初，
議者多易其事，
僉謂有征無戰，
役不踰時，
計兵未甚多，
度費未甚廣，
於事爲無擾，
於人爲不勞；
曾不料兵連禍拏，
變故難測，
日引月長，
漸乖始圖。

往歳爲天下所患，
咸謂除之則可致升平者，
 rm#xjts13396@李正己 、 rm#r01157@李寶臣 、 rm#r02124@梁崇義 、 rm#r02819@田悦 是也。

往歳爲國家所信，
咸謂任之則可除禍亂者，
 rm#r01579@朱滔 、 rm#r01719@李希烈 是也。

既而 rm#xjts13396@正己 死，
 rm@李納 繼之；
 rm#r01157@寶臣 死，
 rm@惟嶽 繼之；
 rm#r02124@崇義 平，
 rm#r01719@希烈 叛；
 rm@惟嶽 戮，
 rm#r01579@朱滔 攜。

然則往歳之所患者，
四去其三矣，
而患竟不衰；
往歳之所信，
今則自叛矣，
而餘又難保。

是知立國之安危在勢，
任事之濟否在人。

勢苟安，
則異類同心也；
勢苟危，
則舟中敵國也。

陛下豈可不追鑒往事，
惟新令圖，
脩偏廢之柄以靖人，
復倒持之權以固國！

而乃孜孜汲汲，
極思勞神，
徇無已之求，
望難必之效乎！

今 dm#dm08290@關輔 之間，
徵發已甚，
宮苑之内，
備衞不全。

萬一將帥之中，
又如 rm#r01579@朱滔 、 rm#r01719@希烈 ，
或負固邊壘，
誘致豺狼，
或竊發郊畿，
驚犯城闕，
此亦愚臣所竊爲憂者也，
未審陛下復何以備之！

陛下儻過聽愚計，
所遣神策六軍 rm@李晟 等及節將子弟，
悉可追還；
明敕 dm#dm04919@涇 、 dm#dm08457@隴 、 dm#dm07808@邠 、 dm#dm02291@寧 ，
但令嚴備封守，
仍云更不徵發，
使知各保安居。

又降徳音，
罷 dm#dm08170@京城 及畿縣間架等雜税，
則冀已輸者弭怨，
見處者獲寧，
人心不搖，
邦本自固。」

上不能用。之半
# p 

壬戌，
以 dm#dm04547@汴西 運使 rm#r00980@崔縱 兼 dm#dm08950@魏州 四節度都糧料使。

 rm#r00980@縱 ，
 rm@渙 之子也。

# p 

九月，
丙戌，
神策將 rm#xjts25436@劉徳信 、 dm#dm02225@宣武 將 rm#xjts00756@唐漢臣 與 dm#dm04995@淮寧 將 rm#xjts16254@李克誠 戰，
敗於 dm#dm05239@滬澗 。

時 rm#r01644@李勉 遣 rm#xjts00756@漢臣 將兵萬人救 dm#dm07267@襄城 ，
上遣 rm#xjts25436@徳信 帥諸將家應募者三千人助之。

 rm#r01644@勉 奏：
「 rm#r01719@李希烈 精兵皆在 dm#dm07267@襄城 ，
 dm#dm07433@許州 空虚，
若襲 dm#dm07433@許州 ，
則 dm#dm07267@襄城 圍自解。」

遣二將趣 dm#dm07433@許州 ，
未至數十里，
上遣中使責其違詔，
二將狼狽而返，
無復斥候。

 rm#xjts16254@克誠 伏兵邀之，
殺傷太半。

 rm#xjts00756@漢臣 奔 dm#dm01638@大梁 ，
 rm#xjts25436@徳信 奔 dm#dm04465@汝州 ；
 rm#r01719@希烈 遊兵剽掠至 dm#dm00518@伊闕 。

 rm#r01644@勉 復遣其將 rm@李堅 帥四千人助守 dm#dm03880@東都 ，
 rm#r01719@希烈 以兵絶其後，
 rm@堅 軍不得還。

 dm#dm04537@汴 軍由是不振，
 dm#dm07267@襄城 益危。

# p 

上以諸軍討 dm#dm04995@淮寧 者不相統壹，
庚子，
以 rm#r03137@舒王謨 爲 dm#dm06893@荊襄 等道行營都元帥，
更名 rm#r03137@誼 ；
以戸部尚書 rm#r03243@蕭復 爲長史，
右庶子 rm#r00666@孔巣父 爲左司馬，
諫議大夫 rm#r02269@樊澤 爲右司馬，
自餘將佐皆選中外之望。

未行，
會 dm#dm04919@涇 師作亂而止。

 rm#r03243@復 ，
 rm#xjts20022@嵩 之孫也；
 rm#xjts06127@巣父 ，
 rm#r06150@孔子 三十七世孫也。
# p 

上發 dm#dm04920@涇原 諸道兵救 dm#dm07267@襄城 。

冬，
十月，
丙午，
 dm#dm04920@涇原 節度使 rm#r00621@姚令言 將兵五千至 dm#dm08170@京師 。

軍士冒雨，
寒甚，
多攜子弟而來，
冀得厚賜遺其家，
既至，
一無所賜。

丁未，
發至 dm#dm05248@滻水 ，
詔 dm#dm00427@京兆 尹 rm#r02690@王翃 犒師，
惟糲食菜餤；
衆怒，
蹴而覆之，
因揚言曰：
「吾輩將死於敵，
而食且不飽，
安能以微命拒白刃邪！

聞 dm#dm05766@瓊林 、 dm#dm01663@大盈 二庫，
金帛盈溢，
不如相與取之。」

乃擐甲張旗鼓譟，
還趣 dm#dm08170@京城 。

 rm#r00621@令言 入辭，
尚在禁中，
聞之，
馳至 dm#dm08204@長樂阪 ，
遇之。

軍士射 rm#r00621@令言 ，
 rm#r00621@令言 抱馬鬣突入亂兵，
呼曰：
「諸君失計！

東征立功，
何患不富貴，
乃爲族滅之計乎！」

軍士不聽，
以兵擁 rm#r00621@令言 而西。

上遽命賜帛，
人二匹；
衆益怒，
射中使。

又命中使宣慰，
賊已至 dm#dm07686@通化門 外，
中使出門，
賊殺之。

又命出金帛二十車賜之；
賊已入城，
喧聲浩浩，
不復可遏。

百姓狼狽駭走，
賊大呼告之曰：
「汝曹勿恐，
不奪汝商貨僦質矣！

不税汝間架陌錢矣！」

上遣 rm@普王誼 、翰林學士 rm#r00640@姜公輔 出慰諭之；
賊已陳於 dm#dm00308@丹鳳門 外，
小民聚觀者以萬計。
# p 

初，
 dm#dm06233@神策軍 使 rm#r02849@白志貞 掌召募禁兵，
東征死亡者 rm#r02849@志貞 皆隱不以聞，
但受市井富兒賂而補之，
名在軍籍受給賜，
而身居市廛爲販鬻。

司農卿 rm#r02349@段秀實 上言：
「禁兵不精，
其數全少，
卒有患難，
將何待之！」

不聽。

至是，
上召禁兵以禦賊，
竟無一人至者。

賊已斬關而入，
上乃與 rm#xjts23962@王貴𡚱 、 rm@韋淑𡚱 、太子、諸王、 rm#xjts20761@唐安公主 自苑北門出，
 rm#xjts23962@王貴𡚱 以傳國寶繋衣中以從；
後宮諸王、公主不及從者什七八。
# p 

初，
 rm#r04309@魚朝恩 既誅，
宦官不復典兵，
有 rm#r03034@竇文場 、 rm@霍仙嗚 者，
嘗事上於東宮，
至是，
帥宦官左右僅百人以從，
使 rm@普王誼 前驅，
太子執兵以殿。

司農卿 rm#r03728@郭曙 以部曲數十人獵苑中，
聞蹕，
謁道左，
遂以其衆從。

 rm#r03728@曙 ，
 rm#r03727@曖 之弟也。

右龍武軍使 rm#r00070@令狐建 方教射於軍中，
聞之，
帥麾下四百人從，
乃使 rm#r00070@建 居後爲殿。
# p 

 rm#r00640@姜公輔 叩馬言曰：
「 rm#r01577@朱泚 嘗爲 dm#dm04919@涇 帥，
坐弟 rm#r01579@滔 之故，
廢處 dm#dm08170@京師 ，
心嘗怏怏。

臣謂陛下既不能推心待之，
則不如殺之，
毋貽後患。

今亂兵若奉以爲主，
則難制矣。

請召使從行。」

上倉猝不暇用其言，
曰：
「無及矣！」

遂行。

夜至 dm#dm01345@咸陽 ，
飯數匕而過。

時事出非意，
羣臣皆不知乘輿所之。

 rm@盧𣏌 、 rm#r03890@關播 踰中書垣而出。

 rm#r02849@白志貞 、 rm#r02690@王翃 及御史大夫 rm#r00058@于頎 、中丞 rm#r00249@劉從一 、戸部侍郎 rm#r03635@趙贊 、翰林學士 rm#r03959@陸贄 、 rm#r00420@呉通微 等追及上於 dm#dm01345@咸陽 。

 rm#r00058@頎 ，
 rm@頔 之從父兄弟；
 rm@從一 ，
 rm@齊賢 之從孫也。

# p 

賊入宮，
登 dm#dm01259@含元殿 ，
大呼曰：
「天子已出，
宜人自求富！」

遂讙譟，
爭入府庫，
運金帛，
極力而止。

小民因之，
亦入宮盜庫物，
通夕不已。

其不能入者，
剽奪於路。

諸坊居民各相帥自守。

 rm#r00621@姚令言 與亂兵謀曰：
「今衆無主，
不能持久，
 rm#xjts09813@朱太尉 閒居私第，
請相與奉之。」

衆許諾。

乃遣數百騎迎 rm#r01577@泚 於 dm#dm03551@晉昌里 第。

夜半，
 rm#r01577@泚 按轡列炬，
傳呼入宮，
居 dm#dm01259@含元殿 ，
設警嚴，
自稱權知六軍。出而復入
# p 

戊申旦，
 rm#r01577@泚 徙居 dm#dm05921@白華殿 ，
出榜於外，
稱：
「 dm#dm04920@涇原 將士久處邊陲，
不閑朝禮，
輒入宮闕，
致驚乘輿，
西出巡幸。

太尉已權臨六軍，
應神策軍士及文武百官凡有祿食者，
悉詣行在；
不能往者，
即詣本司。

若出三日，
檢勘彼此無名者，
皆斬！」

於是百官出見泚，
或勸迎乘輿；
泚不悦，
百官稍稍遁去。
# p 

 rm#r02468@源休 以使囘紇還，
賞薄，
怨朝廷，
入見 rm#r01577@泚 ，
屏人密語移時，
爲 rm#r01577@泚 陳成敗，
引符命，
勸之僭逆。

 rm#r01577@泚 喜，
然猶未決。

宿衞諸軍舉白幡降者，
列於闕前甚衆。

 rm#r01577@泚 夜於苑門出兵，
旦自 dm#dm07686@通化門 入，
駱驛不絶，
張弓露刃，
欲以威衆。

# p 

上思 rm#r02118@桑道茂 之言，
自 dm#dm01345@咸陽 幸 dm#dm01853@奉天 。

縣僚聞車駕猝至，
欲逃匿山谷；
主簿 rm#r03333@蘇辨 止之。

 rm#r03333@辨 ，
 rm#r03343@良嗣 之兄孫也。

文武之臣稍稍繼至；
己酉，
左金吾大將軍 rm#r02462@渾瑊 至 dm#dm01853@奉天 。

 rm#r02462@瑊 素有威望，
衆心恃之稍安。

# p 

庚戌，
 rm#r02468@源休 勸 rm#r01577@朱泚 禁十城門，
毋得出朝士，
朝士往往易服爲傭僕潛出。

 rm#r02468@休 又爲 rm#r01577@泚 説誘文武之士，
使之附 rm#r01577@泚 。

檢校司空、同平章事 rm#r03193@李忠臣 久失兵柄，
太僕卿 rm#r01110@張光晟 自負其才，
皆鬱鬱不得志，
 rm#r01577@泚 悉起而用之。

工部侍郎 rm#r03223@蒋鎭 出亡，
墜馬傷足，
爲 rm#r01577@泚 所得。

先是 rm#r02468@休 以才能，
 rm#r01110@光晟 以節義，
 dm#dm08120@鎭 以清素，
都官員外郎 rm#r01285@彭偃 以文學，
太常卿 rm#xjts23556@敬釭 以勇略，
皆爲時人所重，
至是皆爲泚用。
# p 

 dm#dm09004@鳳翔 、 dm#dm04920@涇原 將 rm#xjts03968@張廷芝 、 rm#xjts26779@段誠諫 將數千人救 dm#dm07267@襄城 ，
未出 dm#dm05384@潼關 ，
聞 rm#r01577@朱泚 據 dm#dm08170@長安 ，
殺其大將 dm#dm08458@隴右 兵馬使 rm@戴蘭 ，
潰歸於 rm#r01577@泚 。

 rm#r01577@泚 於是自謂衆心所歸，
謀反遂定。

以 rm#r02468@源休 爲 dm#dm00427@京兆 尹、判度支，
 rm#r03193@李忠臣 爲皇城使。

百司供億，
六軍宿衞，
咸擬乘輿。

# p 

辛亥，
以 rm#r02462@渾瑊 爲 dm#dm00444@京畿 、 dm#dm05105@渭北 節度使，
行在都虞候 rm#r02849@白志貞 爲都知兵馬使，
 rm#r00070@令狐建 爲中軍鼓角使，
以神策都虞候 rm#r00122@侯仲莊 爲左衞將軍兼 dm#dm01853@奉天 防城使。

# p 

 rm#r01577@朱泚 以司農卿 rm#r02349@段秀實 久失兵柄，
意其必怏怏，
遣數十騎召之。

 rm#r02349@秀實 閉門拒之，
騎士踰垣入，
劫之以兵。

 rm#r02349@秀實 自度不免，
乃謂子弟曰：
「國家有患，
吾於何避之，
當以死徇社稷；
汝曹宜人自求生。」

乃往見 rm#r01577@泚 。

 rm#r01577@泚 喜曰：
「 rm#r02349@段公 來，
吾事濟矣。」

延坐問計。

 rm#r02349@秀實 説之曰：
「公本以忠義著聞天下，
今 dm#dm04919@涇 軍以犒賜不豐，
遽有披猖，
使乘輿播越。

夫犒賜不豐，
有司之過也，
天子安得知之！

公宜以此開諭將士，
示以禍福，
奉迎乘輿，
復歸宮闕，
此莫大之功也！」

 rm#r01577@泚 默然不悦，
然以 rm#r02349@秀實 與己皆爲朝廷所廢，
遂推心委之。

左驍衞將軍 rm#r00285@劉海賓 、 dm#dm04920@涇原 都虞候 rm#xjts07932@何明禮 、孔目官 rm#xjts09559@岐靈嶽 ，
皆 rm#r02349@秀實 素所厚也，
 rm#r02349@秀實 密與之謀誅 rm#r01577@泚 ，
迎乘輿。
# p 

上初至 dm#dm01853@奉天 ，
詔徵近道兵入援。

有上言：
「 rm#r01577@朱泚 爲亂兵所立，
且來攻城，
宜早脩守備。」

 rm#r02881@盧𣏌 切齒言曰：
「 rm#r01577@朱泚 忠貞，
羣臣莫及，
奈何言其從亂，
傷大臣心！

臣請以百口保其不反。」

上亦以爲然。

又聞羣臣勸 rm#r01577@泚 奉迎，
乃詔諸道援兵至者皆營於三十里外。

 rm#r00640@姜公輔 諫曰：
「今宿衞單寡，
防慮不可不深，
若 rm#r01577@泚 竭忠奉迎，
何憚於兵多；
如其不然，
有備無患。」

上乃悉召援兵入城。

 rm#r02881@盧𣏌 及 rm#r02849@白志貞 言於上曰：
「臣觀 rm#r01577@朱泚 心迹，
必不至爲逆，
願擇大臣入 dm#dm08170@京城 宣慰以察之。」

上以諸從臣皆畏憚，
莫敢行；
金吾將軍 rm@呉溆 獨請行，
上悦。

 rm@溆 退而告人曰：
「食其祿而違其難，
何以爲臣！

吾幸託肺附，
非不知往必死，
但舉朝無蹈難之臣，
使聖情慊慊耳！」

遂奉詔詣 rm#r01577@泚 。

 rm#r01577@泚 反謀已決，
雖陽爲受命，
館 rm@溆 於客省，
尋殺之。

 rm@溆 ，
 rm#r00413@湊 之兄也。諸問
# p 

 rm#r01577@泚 遣 dm#dm04920@涇原 兵馬使 rm#r06275@韓旻 將鋭兵三千，
聲言迎大駕，
實襲 dm#dm01853@奉天 。

時 dm#dm01853@奉天 守備單弱，
 rm#r02349@段秀實 謂 rm#xjts09559@岐靈嶽 曰：
「事急矣！」

使 rm#xjts09559@靈嶽 詐爲 rm#r00621@姚令言 符，
令 rm#r06275@旻 且還，
當與大軍倶發。

竊 rm#r00621@令言 印未至，
 rm#r02349@秀實 倒用司農印印符，
募善走者追之。

 rm#r06275@旻 至 dm#dm08865@駱驛 ，
得符而還。

 rm#r02349@秀實 謂同謀曰：
「 rm#r06275@旻 來，
吾屬無類矣！

我當直搏 rm#r01577@泚 殺之，
不克則死，
終不能爲之臣也！」

乃令 rm#r00285@劉海賓 、 rm#xjts07932@何明禮 陰結軍中之士，
欲使應之於外。

 rm#r06275@旻 兵至，
 rm#r01577@泚 、 rm#r00621@令言 大驚；
 rm#xjts09559@岐靈嶽 獨承其罪而死，
不以及 rm#r02349@秀實 等。
# p 

是日，
 rm#r01577@泚 召 rm#r03193@李忠臣 、 rm#r02468@源休 、 rm#r00621@姚令言 及 rm#r02349@秀實 等議稱帝事。

 rm#r02349@秀實 勃然起，
奪 rm#r02468@休 象笏，
前唾 rm#r01577@泚 面，
大罵曰：
「狂賊！

吾恨不斬汝萬段，
豈從汝反邪！」

因以笏撃 rm#r01577@泚 ，
 rm#r01577@泚 舉手扞之，
纔中其額，
濺血灑地。

 rm#r01577@泚 與 rm#r02349@秀實 相搏忷忷，
左右猝愕，
不知所爲。

 rm#r00285@海賓 不敢進，
乘亂而逸。

 rm#r03193@忠臣 前助 rm#r01577@泚 ，
 rm#r01577@泚 得匍匐脱走。

 rm#r02349@秀實 知事不成，
謂 rm#r01577@泚 黨曰：
「我不同汝反，
何不殺我！」

衆爭前殺之。

 rm#r01577@泚 一手承血，
一手止其衆曰：
「義士也！

勿殺。」

 rm#r02349@秀實 既死，
 rm#r01577@泚 哭之甚哀，
以三品禮葬之。

 rm#r00285@海賓 縗服而逃，
後二日，
捕得，
殺之；
亦不引 rm#xjts07932@何明禮 。

 rm#xjts07932@明禮 從 rm#r01577@泚 攻 dm#dm01853@奉天 ，
復謀殺 rm#r01577@泚 ，
亦死。

上聞 rm#r02349@秀實 死，
恨委用不至，
涕泗久之。
# p 

壬子，
以少府監 rm@李昌巎 爲 dm#dm00444@京畿 、 dm#dm05106@渭南 節度使。

# p 

 dm#dm09004@鳳翔 節度使、同平章事 rm#r01266@張鎰 ，
性儒緩，
好修飾邊幅，
不習軍事，
聞上在 dm#dm01853@奉天 ，
欲迎大駕，
具服用貨財，
獻于行在。

後營將 rm#xjts16619@李楚琳 ，
爲人剽悍，
軍中畏之，
嘗事 rm#r01577@朱泚 ，
爲 rm#r01577@泚 所厚。

行軍司馬 rm#r04345@齊映 與同幕 rm#r04344@齊抗 言於 rm#r01266@鎰 曰：
「不去 rm#xjts16619@楚琳 ，
必爲亂首。」

 rm#r01266@鎰 命 rm#xjts16619@楚琳 出戍 dm#dm08464@隴州 。

 rm#xjts16619@楚琳 託事不時發。

 rm#r01266@鎰 方以迎駕爲憂，
謂 rm#xjts16619@楚琳 已去矣。

 rm#xjts16619@楚琳 夜與其黨作亂，
 rm#r01266@鎰 縋城而走，
賊追及，
殺之，
判官 rm@王沼 等皆死。

 rm#r04345@映 自水竇出，
 rm#r04344@抗 爲傭保負荷而逃，
皆免。

# p 

始，
上以 dm#dm01853@奉天 迫隘，
欲幸 dm#dm09004@鳳翔 ，
戸部尚書 rm#r03243@蕭復 聞之，
遽請見曰：
「陛下大誤，
 dm#dm09004@鳳翔 將卒皆 rm#r01577@朱泚 故部曲，
其中必有與之同惡者。

臣尚憂 rm#r01266@張鎰 不能久，
豈得以鑾輿蹈不測之淵乎！」

上曰：
「吾行計已決，
試爲卿留一日。」

明日，
聞 dm#dm09004@鳳翔 亂，
乃止。
# p 

 rm#r04345@齊映 、 rm#r04344@齊抗 皆詣 dm#dm01853@奉天 ，
以 rm#r04345@映 爲御史中丞，
 rm#r04344@抗 爲侍御史。

 rm#xjts16619@楚琳 自爲節度使，
降于 rm#r01577@朱泚 ；
 dm#dm08464@隴州 刺史 rm#xjts23112@郝通 奔于 rm#xjts16619@楚琳 。

# p 

 dm#dm01379@商州 團練兵殺其刺史 rm#r03537@謝良輔 。
# p 

 rm#r01577@朱泚 自 dm#dm05921@白華殿 入 dm#dm02221@宣政殿 ，
自稱 rm#r01577@大秦皇帝 ，
改元 y@應天 。

癸丑，
泚以 rm#r00621@姚令言 爲侍中、 dm#dm08283@關内 元帥，
 rm#r03193@李忠臣 爲司空兼侍中，
 rm#r02468@源休 爲中書侍郎、同平章事、判度支，
 rm#r03223@蒋鎭 爲吏部侍郎，
 rm#r02270@樊系 爲禮部侍郎，
 rm#r01285@彭偃 爲中書舍人，
自餘 rm#r01110@張光晟 等各拜官有差。

立弟 rm#r01579@滔 爲皇太弟。

 rm#r00621@姚令言 與 rm#r02468@源休 共掌朝政，
凡 rm#r01577@泚 之謀畫、遷除、軍旅、資糧，
皆稟於 rm#r02468@休 。

 rm#r02468@休 勸 rm#r01577@泚 誅翦宗室在 dm#dm08170@京城 者以絶人望，
殺郡王、王子、王孫凡七十七人。

尋又以 rm#r03223@蒋鎭 爲門下侍郎，
 rm#xjts13985@李子平 爲諫議大夫，
竝同平章事。

 rm#r03223@鎭 憂懼，
毎懷刀欲自殺，
又欲亡竄，
然性怯，
竟不果。

 rm#r02468@源休 勸 rm#r01577@泚 誅朝士之竄匿者以脅其餘，
鎭力救之，
頼以全者甚衆。

 rm#r02270@樊系 爲 rm#r01577@泚 譔册文，
既成，
仰藥而死。

大理卿 dm#dm06642@膠水  rm#r03219@蒋沇 詣行在，
爲賊所得，
 rm#r03219@沇 絶食稱病，
潛竄得免。
逼以官
# p 

 rm#r00486@哥舒曜 食盡，
棄 dm#dm07267@襄城 奔 dm#dm04788@洛陽 ；
 rm#r01719@李希烈 陷 dm#dm07267@襄城 。
# p 

右龍武將軍 rm@李觀 將衞兵千餘人從上於 dm#dm01853@奉天 ，
上委之召募，
數日，
得五千餘人，
列之通衢，
旗鼓嚴整，
城人爲之増氣。

# p 

 rm#r00621@姚令言 之東出也，
以兵馬使 dm#dm00427@京兆  rm#r04197@馮河清 爲 dm#dm04920@涇原 留後，
判官 dm#dm04651@河中  rm#r00631@姚況 知 dm#dm04924@涇州 事。

 rm#r04197@河清 、 rm#r00631@況 聞上幸 dm#dm01853@奉天 ，
集將士大哭，
激以忠義，
發甲兵、器械百餘車，
通夕輸行在。

城中方苦無甲兵，
得之，
士氣大振。

詔以 rm#r04197@河清 爲 dm#dm01437@四鎭 、 dm#dm00860@北庭 行營、 dm#dm04920@涇原 節度使，
 rm#r00631@況 爲行軍司馬。
# p 

上至 dm#dm01853@奉天 數日，
右僕射、同平章事 rm#r00914@崔寧 始至，
上喜甚，
撫勞有加。

 rm#r00914@寧 退，
謂所親曰：
「主上聰明英武，
從善如流，
但爲 rm#r02881@盧𣏌 所惑，
以至於此！」

因潸然出涕。

 rm#r02881@𣏌 聞之，
與 rm#r02690@王翃 謀陷之。

 rm@翃 言於上曰：
「臣與 rm#r00914@寧 倶出 dm#dm08170@京城 ，
 rm#r00914@寧 數下馬便液，
久之不至，
有顧望意。」

會 rm#r01577@朱泚 下詔，
以左丞 rm#xjts23350@柳渾 同平章事，
 rm#r00914@寧 爲中書令。

 rm#xjts23350@渾 ，
 dm#dm07284@襄陽 人也，
時亡在山谷。

 rm@翃 使 dm#dm06019@盩厔 尉 rm#xjts00430@康湛 詐爲 rm#r00914@寧 遺 rm#r01577@朱泚 書，
獻之。

 rm#r02881@𣏌 因譖寧與 rm#r01577@朱泚 結盟，
約爲内應，
故獨後至。

乙卯，
上遣中使引 rm#r00914@寧 就幕下，
云宣密旨，
二力士自後縊殺之，
中外皆稱其冤；
上聞之，
乃赦其家。
# p 

 rm#r01577@朱泚 遣使遺 rm#r01579@朱滔 書，
稱：
「 dm#dm00142@三秦 之地，
指日克平；
 dm#dm01648@大河 之北，
委卿除殄，
當與卿會于 dm#dm04788@洛陽 。」

 rm#r01579@滔 得書，
宣示軍府，
移牒諸道，
以自誇大。西向舞蹈
# p 

上遣中使告難於 dm#dm08955@魏縣 行營，
諸將相與慟哭。

 rm#r01775@李懷光 帥衆赴 dm#dm08170@長安 ，
 rm#r04181@馬燧 、 rm@李艽 各引兵歸鎭，
 rm#r01783@李抱眞 退屯 dm#dm06692@臨洺 。
# p 

丁巳，
以戸部尚書 rm#r03243@蕭復 爲吏部尚書，
吏部郎中 rm#r00249@劉從一 爲刑部侍郎，
翰林學士 rm#r00640@姜公輔 爲諫議大夫，
竝同平章事。
# p 

 rm#r01577@朱泚 自將逼 dm#dm01853@奉天 ，
軍勢甚盛。

以 rm#r00621@姚令言 爲元帥，
 rm#r01110@張光晟 副之，
以 rm#r03193@李忠臣 爲 dm#dm00427@京兆 尹、皇城留守，
 rm#xjts09549@仇敬忠 爲 dm#dm01227@同 、 dm#dm06927@華 等州節度、 rm@拓東王 ，
以扞 dm#dm08286@關東 之師，
 rm#xjts17340@李日月 爲西道先鋒經略使。

# p 

 dm#dm07810@邠寧 留後 rm#r04133@韓遊瓌 ，
 dm#dm03083@慶州 刺史 rm#xjts01683@論惟明 ，
監軍 rm#xjts06714@翟文秀 ，
受詔將兵三千拒 rm#r01577@泚 於 dm#dm00545@便橋 ，
與 rm#r01577@泚 遇於 dm#dm07988@醴泉 。

 rm#r04133@遊瓌 欲還趣 dm#dm01853@奉天 ，
 rm#xjts06714@文秀 曰：
「我向 dm#dm01853@奉天 ，
賊亦隨至，
是引賊以迫天子也。

不若留壁於此，
賊必不敢越我向 dm#dm01853@奉天 ；
若不顧而過，
則與 dm#dm01853@奉天 夾攻之。」

 rm#r04133@遊瓌 曰：
「賊強我弱，
若賊分軍以綴我，
直趣 dm#dm01853@奉天 ，
 dm#dm01853@奉天 兵亦弱，
何夾攻之有！

我今急趣 dm#dm01853@奉天 ，
所以衞天子也。

且吾士卒飢寒而賊多財，
彼以利誘吾卒，
吾不能禁也。」

遂引兵入 dm#dm01853@奉天 ；
 rm#r01577@泚 亦隨至。

官軍出戰，
不利，
 rm#r01577@泚 兵爭門，
欲入；
 rm#r02462@渾瑊 與 rm#r04133@遊瓌 血戰竟日。

門内有草車數乘，
 rm#r02462@瑊 使虞候 rm#r04223@高固 帥甲士以長刀斫賊，
皆一當百，
曳車塞門，
縱火焚之，
衆軍乘火撃賊，
賊乃退。

會夜，
 rm#r01577@泚 營於城東三里，
撃柝張火，
布滿原野，
使 dm#dm07333@西明寺 僧 rm#xjts12400@法堅 造攻具，
毀佛寺以爲梯衝。

 rm#r04133@韓遊瓌 曰：
「寺材皆乾薪，
但具火以待之。」

 rm#r04223@固 ，
 rm#r06278@侃 之玄孫也。

 rm#r01577@泚 自是日來攻城，
 rm#r02462@瑊 、 rm#r04133@遊瓌 等晝夜力戰。

 dm#dm02689@幽州 兵救 dm#dm07267@襄城 者聞 rm#r01577@泚 反，
突入 dm#dm05384@潼關 ，
歸 rm#r01577@泚 於 dm#dm01853@奉天 ，
 dm#dm03584@普潤 戍卒亦歸之，
有衆數萬。
# p 

上與 rm#r03959@陸贄 語及亂故，
深自克責。

 rm#r03959@贄 曰：
「致今日之患，
皆羣臣之罪也。」

上曰：
「此亦天命，
非由人事。」

 rm#r03959@贄 退，
上疏，
以爲：
「陛下志壹區宇，
四征不庭，
兇渠稽誅，
逆將繼亂，
兵連禍結，
行及三年。

徵師日滋，
賦斂日重，
内自京邑，
外洎邊陲，
行者有鋒刃之憂，
居者有誅求之困。

是以叛亂繼起，
怨讟竝興，
非常之虞，
億兆同慮。

唯陛下穆然凝邃，
獨不得聞，
至使兇卒鼓行，
白晝犯闕，
豈不以乘我間隙，
因人攜離哉！

陛下有股肱之臣，
有耳目之任，
有諫諍之列，
有備衞之司，
見危不能竭其誠，
臨難不能效其死；
臣所謂致今日之患，
羣臣之罪者，
豈徒言歟！

聖旨又以國家興衰，
皆有天命。

臣聞天所視聽，
皆因於人。

故 rm@祖伊 責 rm#rt0056@紂 之辭曰：
『我生不有命在天！』

 rm#rt0064@武王 數 rm#rt0056@紂 之罪曰：
『乃曰吾有命，
罔懲其侮。』

此又捨人事而推天命必不可之理也！易曰：『視履考祥。』

又曰：『吉凶者，失得之象。』此乃天命由人，
其義明矣。

然則聖哲之意，
六經會通，
皆謂禍福由人，
不言盛衰有命。

蓋人事理而天命降亂者，
未之有也；
人事亂而天命降康者，
亦未之有也。

自頃征討頗頻，
刑網稍密，
物力耗竭，
人心驚疑，
如居風濤，
洶洶靡定。

上自朝列，
下達蒸黎，
日夕族黨聚謀，
咸憂必有變故，
旋屬 dm#dm04920@涇原 叛卒，
果如衆庶所虞。

 dm#dm08170@京師 之人，
動逾億計，
固非悉知算術，
皆曉占書，
則明致寇之由，
未必盡關天命。

臣聞理或生亂，
亂或資理，
有以無難而失守，
有以多難而興邦。

今生亂失守之事，
則既往而不可復追矣；
其資理興邦之業，
在陛下克勵而謹脩之。

何憂乎亂人，
何畏於厄運！

勤勵不息，
足致升平，
豈止盪滌妖氛，
旋復宮闕而已！」

# p 

 rm#r02819@田悦 説 rm#r02656@王武俊 ，
使與 rm#xjts24968@馬寔 共撃 rm#r01783@李抱眞 於 dm#dm06692@臨洺 。

 rm#r01783@抱眞 復遣 rm#xjts03852@賈林 説 rm#r02656@武俊 曰：
「 dm#dm06692@臨洺 兵精而有備，
未易輕也。

今戰勝得地，
則利歸 dm#dm08946@魏博 ；
不勝，
則 dm#dm03018@恆冀 大傷。

 dm#dm03494@易 、 dm#dm02116@定 、 dm#dm05208@滄 、 dm#dm07617@趙 ，
皆大夫之故地也，
不如先取之。」

 rm#r02656@武俊 乃辭 rm#r02819@悦 ，
與 rm#xjts24968@馬寔 北歸。

壬戌，
 rm#r02819@悦 送 rm#r02656@武俊 於 dm#dm08796@館陶 ，
執手泣別，
下至將士，
贈遺甚厚。
# p 

先是，
 rm#r02656@武俊 召囘紇兵，
使絶 rm#r01775@李懷光 等糧道，
 rm#r01775@懷光 等已西去，
而囘紇達干將囘紇千人、雜虜二千人適至 dm#dm02689@幽州 北境。

 rm#r01579@朱滔 因説之，
欲與倶詣 dm#dm04660@河南 取東都，
應接 rm#r01577@朱泚 ，
許以 dm#dm04660@河南 子女賂之。

 rm#r01579@滔 娶囘紇女爲側室，
囘紇謂之 rm@朱郎 ，
且利其俘掠，
許之。金帛
# p 

 rm#xjts03852@賈林 復説 rm#r02656@武俊 曰：
「自古國家有患，
未必不因之更興；
況主上九葉天子，
聰明英武，
天下誰肯捨之共事 rm#r01577@朱泚 乎！

 rm#r01579@滔 自爲盟主以來，
輕蔑同列。

 dm#dm04671@河朔 古無 dm#dm00710@冀國 ，
 dm#dm00712@冀 乃大夫之封域也。

今 rm#r01579@滔 稱 rm#r01579@冀王 ，
又西倚其兄，
北引囘紇，
其志欲盡呑 dm#dm04671@河朔 而王之，
大夫雖欲爲之臣，
不可得矣。

且大夫雄勇善戰，
非 rm#r01579@滔 之比；
又本以忠義手誅叛臣，
當時宰相處置失宜，
爲 rm@滔 所誑誘，
故蹉跌至此。

不若與 dm#dm03524@昭義 併力取 rm#r01579@滔 ，
其勢必獲。

 rm#r01579@滔 既亡，
則 rm#r01577@泚 自破矣。

此不世之功，
轉禍爲福之道也。

今諸道輻湊攻 rm#r01577@泚 ，
不日當平。

天下已定，
大夫乃悔過而歸國，
則已晩矣！」

時 rm#r02656@武俊 已與 rm#r01579@滔 有隙，
因攘袂作色曰：
「二百年天子吾不能臣，
豈能臣此田舍兒乎！」

遂與 rm#r01783@抱眞 及 rm#r04181@馬燧 相結，
約爲兄弟；
然猶外事 rm#r01579@滔 ，
禮甚謹，
與 rm#r02819@田悦 各遣使見 rm#r01579@滔 於 dm#dm04700@河間 ，
賀 rm#r01577@朱泚 稱尊號，
且請 rm#xjts24968@馬寔 之兵共攻 rm#r01052@康日知 於 dm#dm07623@趙州 。
# p 

 dm#dm04460@汝 、 dm#dm07947@鄭 應援使 rm#xjts25436@劉徳信 將子弟軍在 dm#dm04465@汝州 ，
聞難，
引兵入援，
與 rm#r01577@泚 衆戰于 dm#dm07406@見子陵 ，
破之；
以 dm#dm03850@東渭橋 有轉輸積粟，
癸亥，
進屯 dm#dm03850@東渭橋 。

# p 

 rm#r01577@朱泚 夜攻 dm#dm01853@奉天 東、西、南三面。

甲子，
 rm#r02462@渾瑊 力戰卻之；
左龍武大將軍 rm#xjts24492@呂希倩 戰死。

乙丑，
 rm#r01577@泚 復攻城，
將軍 rm@高重捷 與 rm#r01577@泚 將 rm#xjts17340@李日月 戰於 dm#dm04042@梁山 之隅，
破之；
乘勝逐北，
身先士卒，
賊伏兵擒之。

其麾下十餘人奮不顧死，
追奪之；
賊不能拒，
乃斬其首，
棄其身而去。

麾下收之入城，
上親撫而哭之盡哀，
結蒲爲首而葬之，
贈司空。

 rm#r01577@朱泚 見其首，
亦哭之曰：
「忠臣也！」

束蒲爲身而葬之。

 rm#xjts17340@李日月 ，
 rm#r01577@泚 之驍將也，
戰死於 dm#dm01853@奉天 城下；
 rm#r01577@泚 歸其尸於 dm#dm08170@長安 ，
厚葬之。

其母竟不哭，
罵曰：
「奚奴！

國家何負於汝而反？
死已晩矣！」

及 rm#r01577@泚 敗，
賊黨皆族誅，
獨 rm#xjts17340@日月 之母不坐。
# p 

己巳，
加 rm#r02462@渾瑊  dm#dm00444@京畿 、 dm#dm05106@渭南 ‧ dm#dm00829@北 、 dm#dm08010@金商 節度使。
# p 

壬申，
 rm#r02656@王武俊 與 rm#xjts24968@馬寔 至 dm#dm07623@趙州 城下。
# p 

初，
 rm#r01577@朱泚 鎭 dm#dm09004@鳳翔 ，
遣其將 rm#xjts09573@牛雲光 將 dm#dm02689@幽州 兵五百人戍 dm#dm08464@隴州 ，
以 dm#dm08458@隴右 營田判官 rm#r04056@韋皋 領 dm#dm08458@隴右 留後。

及 rm#xjts23112@郝通 奔 dm#dm09004@鳳翔 ，
 rm#xjts09573@牛雲光 詐疾，
欲俟 rm#r04056@皋 至，
伏兵執之以應 rm#r01577@泚 ，
事泄，
帥其衆奔 rm#r01577@泚 。

至 dm#dm00073@汧陽 ，
遇 rm#r01577@泚 遣中使 rm#xjts20299@蘇玉 齎詔書加 rm#r04056@皋 中丞，
 rm#xjts20299@玉 説 rm#xjts09573@雲光 曰：
「 rm#r04056@韋皋 ，
書生也。

君不如與我倶之 dm#dm08464@隴州 ，
 rm#r04056@皋 幸而受命，
乃吾人也；
不受命，
君以兵誅之，
如取孤㹠耳！」

 rm#xjts09573@雲光 從之。

 rm#r04056@皋 從城上問 rm#xjts09573@雲光 曰：
「曏者不告而行，
今而復來，
何也？」
 rm#xjts09573@雲光 曰：
「曏者未知公心，
今公有新命，
故復來，
願託腹心。

」
 rm#r04056@皋 乃先納 rm#xjts20299@蘇玉 ，
受其詔書；
謂 rm#xjts09573@雲光 曰：
「大使苟無異心，
請悉納甲兵，
使城中無疑，
衆乃可入。」

 rm#xjts09573@雲光 以 rm#r04056@皋 書生，
易之，
乃悉以甲兵輸之而入。

明日，
 rm#r04056@皋 宴 rm#xjts20299@玉 、 rm#xjts09573@雲光 及其卒於郡舍，
伏甲誅之。

築壇，
盟將士曰：
「 rm#xjts16619@李楚琳 賊虐本使，
既不事上，
安能恤下，
宜相與討之！」

遣兄 rm@平 、 rm@弇 詣 dm#dm01853@奉天 ，
復遣使求援於吐蕃。

# p 

十一月，
乙亥，
以 dm#dm08464@隴州 爲 dm#dm01864@奉義軍 ，
擢 rm#r04056@皋 爲節度使。

 rm#r01577@泚 又使中使 rm#xjts25604@劉海廣 許 rm#r04056@皋  dm#dm09004@鳳翔 節度使；
 rm#r04056@皋 斬之。

# p 

 dm#dm08626@靈武 留後 rm#r02040@杜希全 、 dm#dm09056@鹽州 刺史 rm#r01372@戴休顏 、 dm#dm01538@夏州 刺史 rm#xjts24630@時常春 會 dm#dm05105@渭北 節度使 rm#xjts13847@李建徽 合兵萬人入援，
將至 dm#dm01853@奉天 ，
上召將相議道所從出。

 rm#r03890@關播 、 rm#r02462@渾瑊 曰：
「 dm#dm05268@漠谷 道險狹，
恐爲賊所邀。

不若自 dm#dm00360@乾陵 北過，
附柏城而行，
營於城東北 dm#dm08520@雞子堆 ，
與城中掎角相應，
且分賊勢。」

 rm#r02881@盧𣏌 曰：
「 dm#dm05268@漠谷 道近，
若爲賊所邀，
則城中出兵應接可也。

儻出 dm#dm00360@乾陵 ，
恐驚陵寢。」

 rm#r02462@瑊 曰：
「自 rm#r01577@泚 攻城，
斬 dm#dm00360@乾陵 松柏，
以夜繼晝，
其驚多矣。

今城中危急，
諸道救兵未至，
惟 rm#r02040@希全 等來，
所繋非輕，
若得營據要地，
則 rm#r01577@泚 可破也。」

 rm#r02881@𣏌 曰：
「陛下行師，
豈比逆賊！

若令 rm#r02040@希全 等過之，
是自驚陵寢。」

上乃命 rm#r02040@希全 等自 dm#dm05268@漠谷 進。

丙子，
 rm#r02040@希全 等軍至 dm#dm05268@漠谷 ，
果爲賊所邀，
乘高以大弩、巨石撃之，
死傷甚衆；
城中出兵應接，
爲賊所敗。

是夕，
四軍潰，
退保 dm#dm07812@邠州 。

 rm#r01577@泚 閲其輜重於城下，
從官相視失色。

 rm#r01372@休顏 ，
 dm#dm01538@夏州 人也。

# p 

 rm#r01577@泚 攻城益急，
穿塹環之。

 rm#r01577@泚 移帳於 dm#dm00360@乾陵 ，
下視城中，
動靜皆見之，
時遣使環城招誘士民，
笑其不識天命。

# p 

神策、 dm#dm04656@河北 行營節度使 rm@李晟 疾愈，
聞上幸 dm#dm01853@奉天 ，
帥衆將奔命。

 rm#r01268@張孝忠 迫於 rm#r01579@朱滔 、 rm#r02656@王武俊 ，
倚 rm@晟 爲援，
不欲 rm@晟 行，
數沮止之。

 rm@晟 乃留其子憑，
使娶 rm#r01268@孝忠 女爲婦，
又解玉帶賂 rm#r01268@孝忠 親信，
使説之，
 rm#r01268@孝忠 乃聽 rm@晟 西歸，
遣大將 rm#xjts23074@楊榮國 將鋭兵六百與 rm@晟 倶。

 rm@晟 引兵出 dm#dm08784@飛狐道 ，
晝夜兼行，
至 dm#dm00485@代州 。

丁丑，
加 rm@晟 神策行營節度使。

# p 

 rm#r02656@王武俊 、 rm#xjts24968@馬寔 攻 dm#dm07623@趙州 不克。

辛巳，
 rm#xjts24968@寔 歸 dm#dm05480@瀛州 ，
 rm#r02656@武俊 送之五里，
犒贈甚厚；
 rm#r02656@武俊 亦歸 dm#dm03023@恆州 。

# p 

上之出幸 dm#dm01853@奉天 也，
 dm#dm08327@陝虢 觀察使 rm#xjts19611@姚明敭 以軍事委都防禦副使 rm@張勸 ，
去詣行在。

 rm@勸 募兵得數萬人。

甲申，
以 rm@勸 爲 dm#dm08327@陝虢 節度使。
# p 

 rm#r01577@朱泚 攻圍 dm#dm01853@奉天 經月，
城中資糧倶盡。

上嘗遣健歩出城覘賊，
其人懇以苦寒爲辭，
跪奏乞一襦袴。

上爲之尋求不獲，
竟憫默而遣之。

時供御纔有糲米二斛，
毎伺賊之休息，
夜，
縋人於城外，
采蕪菁根而進之。

上召公卿將吏謂曰：
「朕以不徳，
自陷危亡，
固其宜也。

公輩無罪，
宜早降以救室家。」

羣臣皆頓首流涕，
期盡死力，
故將士雖困急而鋭氣不衰。
# p 

上之幸 dm#dm01853@奉天 也，
糧料使 rm#r00980@崔縱 勸 rm#r01775@李懷光 令入援，
 rm#r01775@懷光 從之。

 rm#r00980@縱 悉斂軍資與 rm#r01775@懷光 皆來。

 rm#r01775@懷光 晝夜倍道，
至 dm#dm04651@河中 ，
力疲，
休兵三日。

 dm#dm04651@河中 尹 rm#r02018@李齊運 傾力犒宴，
軍尚欲遷延。

 rm#r00980@崔縱 先輦貨財渡 dm#dm04650@河 ，
謂衆曰：
「至 dm#dm04695@河西 ，
悉以分賜。」

衆利之，
西屯 dm#dm07024@蒲城 ，
有衆五萬。

 rm@齊運 ，
 rm@惲 之孫也。
士
# p 

 rm@李晟 行且收兵，
亦自 dm#dm07031@蒲津 濟軍於 dm#dm03850@東渭橋 ；
其始有卒四千，
 rm@晟 善於撫御，
與士卒同甘苦，
人樂從之，
旬月間至萬餘人。
# p 

神策兵馬使 rm#r00863@尚可孤 討 rm#r01719@李希烈 ，
將三千人在 dm#dm07284@襄陽 ，
自 dm#dm04315@武關 入援，
軍于 dm#dm00104@七盤 ，
敗 rm#r01577@泚 將 rm#xjts09549@仇敬 ，
遂取 dm#dm07121@藍田 。

可孤，
宇文部之別種也。

# p 

 dm#dm08128@鎭國軍 副使 rm#r00774@駱元光 ，
其先安息人，
 rm#r04209@駱奉先 養以爲子，
將兵守 dm#dm05384@潼關 近十年，
爲衆所服。

 rm#r01577@朱泚 遣其將 rm#xjts07877@何望之 襲 dm#dm06938@華州 ，
刺史 rm#r03191@董晉 棄州走行在。

 rm#xjts07877@望之 據其城，
將聚兵以絶東道；
 rm#r00774@元光 引關下兵襲 rm#xjts07877@望之 ，
走還 dm#dm08170@長安 。

 rm#r00774@元光 遂軍 dm#dm06938@華州 ，
召募士卒，
數日，
得萬餘人。

 rm#r01577@泚 數遣兵攻 rm#r00774@元光 ，
 rm#r00774@元光 皆撃卻之，
賊由是不能東出。

上即以 rm#r00774@元光 爲 dm#dm08128@鎭國軍 節度使，
 rm#r00774@元光 乃將兵二千西屯 dm#dm03519@昭應 。
# p 

 rm#r04181@馬燧 遣其行軍司馬 rm@王權 及其子 rm@彙 將兵五千人入援，
屯 dm#dm00275@中渭橋 。

# p 

於是 rm#r01577@泚 黨所據惟 dm#dm08170@長安 而已，
援軍遊騎時至 dm#dm03700@望春樓 下。

 rm#r03193@李忠臣 等屡出兵皆敗，
求援於 rm#r01577@泚 ，
 rm#r01577@泚 恐民間乘弊抄之，
所遣兵皆晝伏夜行。
# p 

 rm#r01577@泚 内以 dm#dm08170@長安 爲憂，
乃急攻 dm#dm01853@奉天 ，
使僧 rm#xjts12400@法堅 造雲梯，
高廣各數丈，
裹以兕革，
下施巨輪，
上容壯士五百人；
城中望之忷懼。

上以問羣臣，
 rm#r02462@渾瑊 、 rm#r00122@侯仲莊 對曰：
「臣觀雲梯勢甚重，
重則易陷，
臣請迎其所來鑿地道，
積薪蓄火以待之。」

神武軍使 rm@韓澄 曰：
「雲梯小伎，
不足上勞聖慮，
臣請禦之。」

乃度梯之所傃，
廣城東北隅三十歩，
多儲膏油松脂薪葦於其上。

丁亥，
泚盛兵鼓譟攻南城，
 rm#r04133@韓遊瓌 曰：
「此欲分吾力也。」

乃引兵嚴備東北。

戊子，
北風甚迅，
 rm#r01577@泚 推雲梯，
上施濕氈，
懸水嚢，
載壯士攻城，
翼以轒轀，
置人其下，
抱薪負土填塹而前，
矢石火炬所不能傷。

賊併兵攻城東北隅，
矢石如雨，
城中死傷者不可勝數。

賊已有登城者，
上與 rm#r02462@渾瑊 對泣，
羣臣惟仰首祝天。

上以無名告身自御史大夫、實食五百戸以下千餘通授 rm#r02462@瑊 ，
使募敢死士禦之，
仍賜御筆，
使視其功之大小書名給之，
告身不足則書其身，
且曰：
「今便與卿別。」

 rm#r02462@瑊 俯伏流涕，
上拊其背，
歔欷不自勝。

時士卒凍餒，
又乏甲冑，
 rm#r02462@瑊 撫諭，
激以忠義，
皆鼓譟力戰。

 rm#r02462@瑊 中流矢，
進戰不輟，
初不言痛。

會雲梯輾地道，
一輪偏陷，
不能前卻，
火從地中出，
風勢亦囘，
城上人投葦炬，
散松脂，
沃以膏油，
讙呼震地。

須臾，
雲梯及梯上人皆爲灰燼，
臭聞數里，
賊乃引退。

於是三門皆出兵，
太子親督戰，
賊徒大敗，
死者數千人。

將士傷者，
太子親爲裹瘡。

入夜，
 rm#r01577@泚 復來攻城，
矢及御前三歩而墜；
上大驚。梯橋
# p 

 rm#r01775@李懷光 自 dm#dm07024@蒲城 引兵趣 dm#dm04928@涇陽 ，
竝北山而西，
先遣兵馬使 rm@張韶 微服間行詣行在，
藏表於蝋丸。

 rm@韶 至 dm#dm01853@奉天 ，
値賊方攻城，
見 rm@韶 ，
以爲賤人，
驅之使與民倶填塹；
 rm@韶 得間，
踰塹抵城下呼曰：
「我 dm#dm03680@朔方軍 使者也。」

城上人下繩引之，
比登，
身中數十矢，
得表於衣中而進之。

上大喜，
舁 rm@韶 以徇城，
四隅歡聲如雷。

癸巳，
 rm#r01775@懷光 敗 rm#r01577@泚 兵於 dm#dm05406@澧泉 。

 rm#r01577@泚 聞之懼，
引兵遁歸 dm#dm08170@長安 。

衆以爲 rm#r01775@懷光 復三日不至，
則城不守矣。

# p 

 rm#r01577@泚 既退，
從臣皆賀。

 dm#dm04546@汴滑 行營兵馬使 rm#r03588@賈隱林 進言：
「陛下性太急，
不能容物，
若此性未改，
雖 rm#r01577@朱泚 敗亡，
憂未艾也！」

上不以爲忤，
甚稱之。

侍御史 rm#xjts03460@萬俟著 開 dm#dm08005@金 、 dm#dm01376@商 運路，
重圍既解，
諸道貢賦繼至，
用度始振。
# p 

 rm#r01577@朱泚 至 dm#dm08170@長安 ，
但爲城守之計，
時遣人自城外來，
周走呼曰：
「 dm#dm01853@奉天 破矣！」

欲以惑衆。

 rm#r01577@泚 既據府庫之富，
不愛金帛以悦將士，
公卿家屬在城者皆給月俸。

神策及六軍從車駕及 rm#r00486@哥舒曜 、 rm@李晟 者，
 rm#r01577@泚 皆給其家糧；
加以繕完器械，
日費甚廣。

及 dm#dm08170@長安 平，
府庫尚有餘蓄，
見者皆追怨有司之暴斂焉。

# p 

或謂 rm#r01577@泚 曰：
「陛下既受命，
 dyn#ch100@唐 之陵廟不宜復存。」

 rm#r01577@泚 曰：
「朕嘗北面事 dyn#ch100@唐 ，
豈忍爲此！」

又曰：
「百官多缺，
請以兵脅士人補之。」

 rm#r01577@泚 曰：
「強授之則人懼。

但欲仕者則與之，
何必叩戸拜官邪！」

 rm#r01577@泚 所用者惟 dm#dm06863@范陽 、神策團練兵；
 dm#dm04920@涇原 卒驕，
皆不爲用，
但守其所掠資貨，
不肯出戰；
又密謀殺 rm#r01577@泚 ，
不果而止。

# p 

 rm#r01775@李懷光 性粗疏，
自 dm#dm02403@山東 來赴難，
數與人言 rm#r02881@盧𣏌 、 rm#r03635@趙贊 、 rm#r02849@白志貞 之姦佞，
且曰：
「天下之亂，
皆此曹所爲也！

吾見上，
當請誅之。」

既解 dm#dm01853@奉天 之圍，
自矜其功，
謂上必接以殊禮。

或説 rm#r02690@王翃 、 rm#r03635@趙贊 曰：
「 rm#r01775@懷光 縁道憤歎，
以爲宰相謀議乖方，
度支賦斂煩重，
 dm#dm00426@京 尹犒賜刻薄；
致乘輿播遷者，
三臣之罪也。

今 rm#r01775@懷光 新立大功，
上必披襟布誠，
詢得失，
使其言入，
豈不殆哉！」

 rm@翃 、 rm@贊 以告 rm#r02881@盧𣏌 ，
 rm#r02881@𣏌 懼，
從容言於上曰：
「 rm#r01775@懷光 勳業，
社稷是頼，
賊徒破膽，
皆無守心，
若使之乘勝取 dm#dm08170@長安 ，
則一舉可以滅賊，
此破竹之勢也。

今聽其入朝，
必當賜宴，
留連累日，
使賊入 dm#dm08170@京城 ，
得從容成備，
恐難圖矣！」

上以爲然。

詔 rm#r01775@懷光 直引軍屯 dm#dm00545@便橋 ，
與 rm#xjts13847@李建徽 、 rm@李晟 及 dm#dm06232@神策 兵馬使 rm#xjts26526@楊惠元 刻期共取 dm#dm08170@長安 。

 rm#r01775@懷光 自以數千里竭誠赴難，
破 rm#r01577@朱泚 ，
解重圍，
而咫尺不得見天子，
意殊怏怏，
曰：
「吾今已爲姦臣所排，
事可知矣！」

遂引兵去，
至 dm#dm08977@魯店 ，
留二日乃行。
訪
# p 

 dm#dm00785@劍南  dm#dm07314@西山 兵馬使 rm#xjts05027@張朏 以所部兵作亂，
入 dm#dm03147@成都 ，
 dm#dm07316@西川 節度使 rm#r01145@張延賞 棄城奔 dm#dm05287@漢州 ；
 dm#dm09078@鹿頭 戍將 rm#xjts24611@叱干遂 等討之，
斬 rm#xjts05027@朏 及其黨，
 rm#r01145@延賞 復歸 dm#dm03147@成都 。
# p 

 dm#dm04984@淮南 節度使 rm#r03921@陳少遊 將兵討 rm#r01719@李希烈 ，
屯 dm#dm06022@盱眙 ，
聞 rm#r01577@朱泚 作亂，
歸 dm#dm02772@廣陵 ，
修塹壘，
繕甲兵。

 dm#dm04855@浙江東 、 dm#dm07286@西 節度使 rm#r04122@韓滉 閉關梁，
禁馬牛出境，
築 dm#dm06142@石頭城 ，
穿井近百所，
繕館第數十，
修塢壁，
起 dm#dm02862@建業 ，
抵 dm#dm00439@京峴 ，
樓堞相屬，
以備車駕渡 dm#dm04475@江 ，
且自固也。

 rm#r03921@少遊 發兵三千大閲於 dm#dm04475@江 北；
 rm#r04122@滉 亦發舟師三千曜武於 dm#dm00443@京江 以應之。

# p 

鹽鐵使 rm#r00342@包佶 有錢帛八百萬，
將輸 dm#dm08170@京師 。

 rm#r03921@陳少遊 以爲賊據 dm#dm08170@長安 ，
未期收復，
欲強取之。

 rm#r00342@佶 不可，
 rm#r03921@少遊 欲殺之；
 rm#r00342@佶 懼，
匿妻子於案牘中，
急濟 dm#dm04475@江 。

 rm#r03921@少遊 悉收其錢帛；
 rm#r00342@佶 有守財卒三千，
 rm#r03921@少遊 亦奪之。

 rm#r00342@佶 纔與數十人倶至 dm#dm00156@上元 ，
復爲 rm#r04122@韓滉 所奪。

# p 

時南方藩鎭各閉境自守，
惟 rm#r00535@曹王皋 數遣使間道貢獻。

 rm#r01719@李希烈 攻逼 dm#dm04537@汴 、 dm#dm07947@鄭 ，
 dm#dm04475@江 、 dm#dm04981@淮 路絶，
朝貢皆自 dm#dm02203@宣 、 dm#dm08799@饒 、 dm#dm06880@荊 、 dm#dm07261@襄 趣 dm#dm04315@武關 。

 rm#r00535@皋 治郵驛，
平道路，
由是往來之使，
通行無阻。

# p 

上問 rm#r03959@陸贄 以當今切務。

 rm#r03959@贄 以曏日致亂，
由上下之情不通，
勸上接下從諫，
乃上疏，
其略曰：
「臣謂當今急務，
在於審察羣情，
若羣情之所甚欲者，
陛下先行之，
所甚惡者，
陛下先去之。

欲惡與天下同而天下不歸者，
自古及今，
未之有也。

夫理亂之本，
繋於人心，
況乎當變故動搖之時，
在危疑向背之際，
人之所歸則植，
人之所去則傾，
陛下安可不審察羣情，
同其欲惡，
使億兆歸趣，
以靖邦家乎！

此誠當今之所急也。」

又曰：
「頃者竊聞輿議，
頗究羣情，
四方則患於中外意乖，
百辟又患於君臣道隔。

郡國之志不達於朝廷，
朝廷之誠不升於軒陛。

上澤闕於下布，
下情壅於上聞，
實事不必知，
知事不必實，
上下否隔於其際，
眞僞雜糅於其間，
聚怨囂囂，
騰謗籍籍，
欲無疑阻，
其可得乎！」

又曰：
「總天下之智以助聰明，
順天下之心以施教令，
則君臣同志，
何有不從！

遠邇歸心，
孰與爲亂！」

又曰：
「慮有愚而近道，
事有要而似迂。」

# p 

疏奏旬日，
上無所施行，
亦不詰問。

 rm#r03959@贄 又上疏，
其略曰：
「臣聞立國之本，
在乎得衆，
得衆之要，
在乎見情。

故 rm#r06150@仲尼 以謂人情者聖王之田，
言理道所生也。」

又曰：
「易，乾下坤上曰泰，坤下乾上曰否，損上益下曰益，損下益上曰損。夫天在下而地處上，
於位乖矣，
而反謂之泰者，
上下交故也。

君在上而臣處下，
於義順矣，
而反謂之否者，
上下不交故也。

上約己而裕於人，
人必説而奉上矣，
豈不謂之益乎！

上蔑人而肆諸己，
人必怨而叛上矣，
豈不謂之損乎！」

又曰：
「舟即君道，
水即人情。

舟順水之道乃浮，
違則沒；
君得人之情乃固，
失則危。

是以古先聖王之居人上也，
必以其欲從天下之心，
而不敢以天下之人從其欲。」

又曰：
「陛下憤習俗以妨理，
任削平而在躬，
以明威照臨，
以嚴法制斷，
流弊自久，
浚恆太深。

遠者驚疑而阻命逃死之禍作，
近者畏懾而偸容避罪之態生。

君臣意乖，
上下情隔，
君務致理，
而下防誅夷，
臣將納忠，
又上慮欺誕，
故睿誠不布於羣物，
物情不達於睿聰。

臣於往年曾任御史，
獲奉朝謁，
僅欲半年，
陛下嚴邃高居，
未嘗降旨臨問，
羣臣跼蹐趨退，
亦不列事奏陳。

軒陛之間，
且未相諭，
宇宙之廣，
何由自通！

雖復例對使臣，
別延宰輔，
既殊師錫，
且異公言。

未行者則戒以樞密勿論，
已行者又謂之遂事不諫，
漸生拘礙，
動渉猜嫌，
由是人各隱情，
以言爲諱。

至於變亂將起，
億兆同憂，
獨陛下恬然不知，
方謂太平可致。

陛下以今日之所覩驗往時之所聞，
孰眞孰虚，
何得何失，
則事之通塞備詳之矣！

人之情僞盡知之矣！」

# p 

上乃遣中使諭之曰：
「朕本性甚好推誠，
亦能納諫。

將謂君臣一體，
全不隄防，
縁推誠不疑，
多被姦人賣弄。

今所致患害，
朕思亦無他，
其失反在推誠。

又，
諫官論事，
少能愼密，
例自矜衒，
歸過於朕以自取名。

朕從即位以來，
見奏對論事者甚多，
大抵皆是雷同，
道聽塗説，
試加質問，
遽即辭窮。

若有奇才異能，
在朕豈惜拔擢。

朕見從前已來，
事祗如此，
所以近來不多取次對人，
亦非倦於接納。

卿宜深悉此意。」

 rm#r03959@贄 以人君臨下，
當以誠信爲本。

諫者雖辭情鄙拙，
亦當優容以開言路，
若震之以威，
折之以辯，
則臣下何敢盡言，
乃復上疏，
其略曰：
「天子之道，
與天同方，
天不以地有惡木而廢發生，
天子不以時有小人而廢聽納。」

又曰：
「唯信與誠，
有失無補。

一不誠則心莫之保，
一不信則言莫之行。

陛下所謂失於誠信以致患害者，
臣竊以斯言爲過矣。」

又曰：
「馭之以智則人詐，
示之以疑則人偸。

上行之則下從之，
上施之則下報之。

若誠不盡於己而望盡於人，
衆必怠而不從矣。

不誠於前而曰誠於後，
衆必疑而不信矣。

是知誠信之道，
不可斯須而去身。

願陛下愼守而行之有加，
恐非所以爲悔者也！」

又曰：
「臣聞 rm@仲虺 贊揚 rm#rt0027@成湯 ，
不稱其無過而稱其改過；
 rm@吉甫 歌誦 rm#rt0074@周宣 ，
不美其無闕而美其補闕。

是則聖賢之意較然著明，
惟以改過爲能，
不以無過爲貴。

蓋爲人之行己，
必有過差，
上智下愚，
倶所不免。

智者改過而遷善，
愚者恥過而遂非；
遷善則其徳日新，
遂非則其惡彌積。」

又曰：
「諫官不密自矜，
信非忠厚，
其於聖徳固亦無虧。

陛下若納諫不違，
則傳之適足増美；
陛下若違諫不納，
又安能禁之勿傳！」

又曰：
「侈言無驗不必用，
質言當理不必違。

辭拙而效速者不必愚，
言甘而利重者不必智。

是皆考之以實，
慮之以終，
其用無他，
唯善所在。」

又曰：
「陛下所謂『比見奏對論事皆是雷同道聽塗説者。』

臣竊以衆多之議，
足見人情，
必有可行，
亦有可畏，
恐不宜一概輕侮而莫之省納也。

陛下又謂『試加質問，
即便辭窮。』

臣但以陛下雖窮其辭而未窮其理，
能服其口而未服其心。」

又曰：
「爲下者莫不願忠，
爲上者莫不求理。

然而下毎苦上之不理，
上毎苦下之不忠。

若是者何？
兩情不通故也。

下之情莫不願達於上，
上之情莫不求知於下，
然而下恆苦上之難達，
上恆苦下之難知。

若是者何？
九弊不去故也。

所謂九弊者，
上有其六而下有其三：
好勝人，
恥聞過，
騁辯給，
眩聰明，
厲威嚴，
恣強愎，
此六者，
君上之弊也；
諂諛，
顧望，
畏愞，
此三者，
臣下之弊也。

上好勝必甘於佞辭，
上恥過必忌於直諫，
如是則下之諂諛者順指而忠實之語不聞矣。

上騁辯必勦説而折人以言，
上眩明必臆度而虞人以詐，
如是則下之顧望者自便而切磨之辭不盡矣。

上厲威必不能降情以接物，
上恣愎必不能引咎以受規，
如是則下之畏愞者避辜而情理之説不申矣。

夫以區域之廣大，
生靈之衆多，
宮闕之重深，
高卑之限隔，
自黎獻而上，
獲覩至尊之光景者，
踰億兆而無一焉；
就獲覩之中得接言議者，
又千萬不一；
幸而得接者，
猶有九弊居其間，
則上下之情所通鮮矣。

上情不通於下則人惑，
下情不通於上則君疑；
疑則不納其誠，
惑則不從其令；
誠而不見納則應之以悖，
令而不見從則加之以刑；
下悖上刑，
不敗何待！

是使亂多理少，
從古以然。」

又曰：
「昔 rm@趙武 吶吶而爲 dyn#ch110@晉 賢臣，
 rm#r06163@絳侯 木訥而爲 dyn#ch129@漢 元輔，
然則口給者事或非信，
辭屈者理或未窮。

人之難知，
 rm#rt0006@堯 、 rm#rt0007@舜 所病，
胡可以一詶一詰而謂盡其能哉！

以此察天下之情，
固多失實，
以此輕天下之士，
必有遺才。」

又曰：
「諫者多，
表我之能好；
諫者直，
示我之能容；
諫者之狂誣，
明我之能恕；
諫者之漏泄，
彰我之能從；
是則人君與諫者交相益之道也。

諫者有爵賞之利，
君亦有理安之利；
諫者得獻替之名，
君亦得采納之名。

然猶諫者有失中而君無不美，
唯恐讜言之有不切，
天下之不聞，
如此則納諫之徳光矣。」

上頗采用其言。有一于斯，皆爲盛徳
# p 

 rm#r01775@李懷光 頓兵不進，
數上表暴揚 rm#r02881@盧𣏌 等罪惡；
衆論諠騰，
亦咎 rm#r02881@𣏌 等。

上不得已，
十二月，
壬戌，
貶 rm#r02881@𣏌 爲 dm#dm03342@新州 司馬，
 rm#r02849@白志貞 爲 dm#dm03033@恩州 司馬，
 rm#r03635@趙贊 爲 dm#dm03267@播州 司馬。

宦者 rm#xjts06714@翟文秀 ，
上所信任也，
 rm#r01775@懷光 又言其罪，
上亦爲殺之。

# p 

乙丑，
以翰林學士、祠部員外郎 rm#r03959@陸贄 爲考功郎中，
金部員外郎 rm#r00420@呉通微 爲職方郎中。

 rm#r03959@贄 上奏，
辭以「初到 dm#dm01853@奉天 ，
扈從將吏例加兩階，
今翰林獨遷官。

 dyn#ch100@唐 自 y@至徳 以後，
勳階輕而職事官重，
故云然。

夫行罰先貴近而後卑遠，
則令不犯；
行賞先卑遠而後貴近，
則功不遺。

望先録大勞，
次徧羣品，
則臣亦不敢獨辭。」

上不許。
# p 

上在 dm#dm01853@奉天 ，
使人説 rm#r02819@田悦 、 rm#r02656@王武俊 、 rm@李納 ，
赦其罪，
厚賂以官爵；
 rm#r02819@悦 等皆密歸款，
而猶未敢絶 rm#r01579@朱滔 ，
各稱王如故。

 rm#r01579@滔 使其虎牙將軍 rm#xjts02018@王郅 説 rm#r02819@悦 曰：
「日者 rm#xjts13867@八郎 有急，
 rm#r01579@滔 與 rm@趙王 不敢愛其死，
竭力赴救，
幸而解圍。

今太尉三兄受命 dm#dm08281@關中 ，
 rm#r01579@滔 欲與囘紇共往助之，
願 rm#xjts13867@八郎 治兵，
與 rm#r01579@滔 渡 dm#dm04650@河 共取 dm#dm01638@大梁 。」

 rm#r02819@悦 心不欲行而未忍絶 rm#r01579@滔 ，
乃許之。

 rm#r01579@滔 復遣其内史舍人 rm@李琯 見 rm#r02819@悦 ，
審其可否，
 rm#r02819@悦 猶豫不決，
密召 rm@扈崿 議之。

司武侍郎 rm#xjts01766@許士則 曰：
「 rm#r01579@朱滔 昔事 rm#r01773@李懷仙 爲牙將，
與兄 rm#r01577@泚 及 rm#xjts09851@朱希彩 共殺 rm#r01773@懷仙 而立 rm#xjts09851@希彩 。

 rm#xjts09851@希彩 所以寵信其兄弟至矣，
 rm#r01579@滔 又與判官 rm@李子瑗 謀殺 rm#xjts09851@希彩 而立 rm#r01577@泚 。

 rm#r01577@泚 既爲帥，
 rm#r01579@滔 乃勸 rm#r01577@泚 入朝而自爲留後，
雖勸以忠義，
實奪之權也。

平生與之同謀共功如 rm@李子瑗 之徒，
負而殺之者二十餘人。

今又與 rm#r01577@泚 東西相應，
使 rm#r01579@滔 得志，
 rm#r01577@泚 亦不爲所容，
況同盟乎！

 rm#r01579@滔 爲人如此，
大王何從得其肺腑而信之邪！

彼引 dm#dm02693@幽陵 、囘紇十萬之兵屯於郊坰，
大王出迎，
則成擒矣。

彼囚大王，
兼 dm#dm08947@魏國 之兵，
南向渡 dm#dm04650@河 ，
與 dm#dm08281@關中 相應，
天下其孰能當之！

大王於時悔之無及。

爲大王計，
不若陽許偕行而陰爲之備，
厚加迎勞，
至則託以他故，
遣將分兵而隨之。

如此，
大王外不失報徳之名而内無倉猝之憂矣。」

 rm@扈崿 等皆以爲然。

 rm#r02656@王武俊 聞 rm@李琯 適 dm#dm08945@魏 ，
遣其司刑員外郎 rm#xjts24296@田秀 馳見 rm#r02819@悦 曰：
「 rm#r02656@武俊 曏以宰相處事失宜，
恐禍及身，
又 rm#xjts13867@八郎 困於重圍，
故與 rm#r01579@滔 合兵救之。

今天子方在隱憂，
以徳綏我，
我曹何得不悔過而歸之邪！

捨九葉天子不事而事 rm#r01579@滔 乎！

且 rm#r01577@泚 未稱帝之時，
 rm#r01579@滔 與我曹比肩爲王，
固已輕我曹矣。

況使之南平 dm#dm04537@汴 、 dm#dm04761@洛 ，
與 rm#r01577@泚 連衡，
吾屬皆爲虜矣！

 rm#xjts13867@八郎 愼勿與之倶南，
但閉城拒守；
 rm#r02656@武俊 請伺其隙，
連 dm#dm03524@昭義 之兵，
撃而滅之，
與 rm#xjts13867@八郎 再清 dm#dm04671@河朔 ，
復爲節度使，
共事天子，
不亦善乎！」

 rm@悦 意遂決，
紿 rm@滔 云：
「從行，
必如前約。」

泚及
# p 

丁卯，
 rm#r01579@滔 將 dm#dm06863@范陽 歩騎五萬人，
私從者復萬餘人，
囘紇三千人，
發 dm#dm04700@河間 而南，
輜重首尾四十里。

# p 

 rm#r01719@李希烈 攻 rm@李勉 於 dm#dm04541@汴州 ，
驅民運土木，
築壘道，
以攻城；
忿其未就，
幷人填之，
謂之濕薪。

 rm@勉 城守累月，
外救不至，
將其衆萬餘人奔 dm#dm02098@宋州 。

庚午，
 rm#r01719@希烈 陷 dm#dm01638@大梁 。

 dm#dm05229@滑州 刺史 rm@李澄 以城降 rm#r01719@希烈 ，
 rm#r01719@希烈 以 rm@澄 爲尚書令兼 dm#dm04412@永平 節度使。

 rm@勉 上表請罪，
上謂其使者曰：
「朕猶失守宗廟，
勉宜自安。」

待之如初。
# p 

 rm#r00292@劉洽 遣其將 rm#xjts00155@高翼 將精兵五千保 dm#dm07281@襄邑 ，
 rm#r01719@希烈 攻拔之，
 rm#xjts00155@翼 赴水死。

 rm#r01719@希烈 乘勝攻 dm#dm02309@寧陵 ，
 dm#dm04475@江 、 dm#dm04981@淮 大震。

 rm#r03921@陳少遊 遣參謀 rm#xjts12542@温述 送款於 rm#r01719@希烈 曰：
「 dm#dm05450@濠 、 dm#dm01516@壽 、 dm#dm06799@舒 、 dm#dm02792@廬 ，
已令弛備，
韜戈卷甲，
伏俟指麾。」

又遣巡官 rm#xjts23611@趙詵 結 rm@李納 於 dm#dm07905@鄆州 。

# p 

中書侍郎、同平章事 rm#r03890@關播 罷爲刑部尚書。
# p 

以給事中 rm#r00666@孔巣父 爲 dm#dm04964@淄青 宣慰使，
國子祭酒 rm#r03191@董晉 爲 dm#dm04656@河北 宣慰使。

# p 

 rm#r03959@陸贄 言於上曰：
「今盜遍天下，
輿駕播遷，
陛下宜痛自引過以感人心。

昔 rm#rt0027@成湯 以罪己勃興，
 rm@楚昭 以善言復國。

陛下誠能不吝改過，
以言謝天下，
使書詔無所避忌，
臣雖愚陋，
可以仰副聖情，
庶令反側之徒革心向化。」

上然之，
故 dm#dm01853@奉天 所下書詔，
雖驕將悍卒聞之，
無不感激揮涕。

# p 

術者上言：
「國家厄運，
宜有變更以應時數。」

羣臣請更加尊號一二字。

上以問 rm#r03959@贄 ，
 rm#r03959@贄 上奏，
以爲不可，
其略曰：
「尊號之興，
本非古制。

行於安泰之日，
已累謙沖，
襲乎喪亂之時，
尤傷事體。」

又曰：
「嬴秦徳衰，
兼皇與帝，
始總稱之；
流及後代，
昏僻之君，
乃有聖劉、天元之號。

是知人主輕重，
不在名稱。

損之有謙光稽古之善，
崇之獲矜能納諂之譏。」

又曰：
「必也俯稽術數，
須有變更，
與其増美稱而失人心，
不若黜舊號以祗天戒。」

上納其言，
但改年號而已。


# p 

上又以中書所撰赦文示 rm#r03959@贄 ，
 rm#r03959@贄 上言，
以爲：
「動人以言，
所感已淺，
言又不切，
人誰肯懷！

今茲徳音，
悔過之意不得不深，
引咎之辭不得不盡，
洗刷疵垢，
宣暢鬱堙，
使人人各得所欲，
則何有不從者乎！

應須改革事條，
謹具別状同進。

捨此之外，
尚有所虞。

竊以知過非難，
改過爲難；
言善非難，
行善爲難。

假使赦文至精，
止於知過言善，
猶願聖慮更思所難。」

上然之。
** 興元
*** 興元元年
# year 0784
# p 

春，
正月，
癸酉朔，
赦天下，
改元，
制曰：
「致理興化，
必在推誠；
忘己濟人，
不吝改過。

朕嗣服丕構，
君臨萬邦，
失守宗祧，
越在草莽。

不念率徳，
誠莫追於既往；
永言思咎，
期有復於將來。

明徵其義，
以示天下。

小子懼徳弗嗣，
罔敢怠荒，
然以長于深宮之中，
暗於經國之務，
積習易溺，
居安忘危，
不知稼穡之艱難，
不恤征戍之勞苦，
澤靡下究，
情未上通，
事既擁隔，
人懷疑阻。

猶昧省己，
遂用興戎，
徵師四方，
轉餉千里，
賦車籍馬，
遠近騷然，
行齎居送，
衆庶勞止，
或一日屡交鋒刃，
或連年不解甲冑。

祀奠乏主，
室家靡依，
死生流離，
怨氣凝結，
力役不息，
田莱多荒。

暴令峻於誅求，
疲甿空於杼軸，
轉死溝壑，
離去郷閭，
邑里丘墟，
人煙斷絶。

天譴於上而朕不寤，
人怨於下而朕不知，
馴致亂階，
變興都邑，
萬品失序，
九廟震驚，
上累于祖宗，
下負于蒸庶，
痛心靦貌，
罪實在豫，
永言愧悼，
若墜泉谷。

自今中外所上書奏，
不得更言『聖神文武』
之號。

 rm#r01719@李希烈 、 rm#r02819@田悦 、 rm#r02656@王武俊 、 rm@李納 等，
咸以勳舊，
各守藩維，
朕撫御乖方，
致其疑懼；
皆由上失其道而下罹其災，
朕實不君，
人則何罪！

宜幷所管將吏等一切待之如初。

 rm#r01579@朱滔 雖縁 rm#r01577@朱泚 連坐，
路遠必不同謀，
念其舊勳，
務在弘貸，
如能效順，
亦與惟新。

 rm#r01577@朱泚 反易天常，
盜竊名器，
暴犯陵寢，
所不忍言，
獲罪祖宗，
朕不敢赦。

其脅從將吏百姓等，
但官軍未到 dm#dm08170@京城 以前，
去逆效順幷散歸本道、本軍者，
竝從赦例。

諸軍、諸道應赴 dm#dm01853@奉天 及進收 dm#dm08170@京城 將士，
竝賜名 dm#dm01853@奉天 定難功臣。

其所加墊陌錢、税間架、竹、木、茶、漆、榷鐵之類，
悉宜停罷。

」

# p 

赦下，
四方人心大悦。

及上還 dm#dm08170@長安  y@明年 ，
 rm#r01783@李抱眞 入朝爲上言：
「 dm#dm02403@山東 宣布赦書，
士卒皆感泣，
臣見人情如此，
知賊不足平也！」


# p 

命兵部員外郎 rm@李充 爲 dm#dm03018@恆冀 宣慰使。

# p 

 rm#r01577@朱泚 更國號曰 dm#dm05271@漢 ，
自號 rm@漢元天皇 ，
改元 y@天皇 。
# p 

 rm#r02656@王武俊 、 rm#r02819@田悦 、 rm@李納 見赦令，
皆去王號，
上表謝罪。

惟 rm#r01719@李希烈 自恃兵強財富，
遂謀稱帝，
遣人問儀於 rm#r04147@顏眞卿 ，
 rm#r04147@眞卿 曰：
「老夫嘗爲禮官，
所記惟諸侯朝天子禮耳！」

 rm#r01719@希烈 遂即皇帝位，
國號 dm#dm01641@大楚 ，
改元 y@武成 。

置百官，
以其黨 rm@鄭賁 爲侍中，
 rm#r00720@孫廣 爲中書令，
 rm#xjts14638@李緩 、 rm#r01622@李元平 同平章事。

以 dm#dm04541@汴州 爲 dm#dm01640@大梁府 ，
分其境内爲四節度。

 rm#r01719@希烈 遣其將 rm#xjts01102@辛景臻 謂 rm#r04147@顏眞卿 曰：
「不能屈節，
當自焚！

」
積薪灌油於其庭。

 rm#r04147@眞卿 趨赴火，
 rm#xjts01102@景臻 遽止之。
# p 

 rm#r01719@希烈 又遣其將 rm@楊峯 齎赦賜 rm#r03921@陳少遊 及 dm#dm01521@壽州 刺史 rm#r01148@張建封 。

 rm#r01148@建封 執 rm@峯 徇於軍，
腰斬於市，
 rm#r03921@少遊 聞之駭懼。

 rm#r01148@建封 具以 rm#r03921@少遊 與 rm#r01719@希烈 交通之状聞，
上悦，
以 rm#r01148@建封 爲 dm#dm05450@濠 、 dm#dm01516@壽 、 dm#dm02792@廬 三州都團練使。

 rm#r01719@希烈 乃以其將 rm#xjts22125@杜少誠 爲 dm#dm04984@淮南 節度使，
使將歩騎萬餘人先取 dm#dm01521@壽州 ，
後之 dm#dm04510@江都 ，
 rm#r01148@建封 遣其將 rm#xjts22331@賀蘭元均 、邵怡守 dm#dm08589@霍丘 秋柵。

 rm#xjts22125@少誠 竟不能過，
遂南寇 dm#dm07134@蘄 、 dm#dm09115@黄 ，
欲斷 dm#dm04475@江 路。

時上命 rm#r00342@包佶 自督 dm#dm04475@江 、 dm#dm04981@淮 財賦，
泝 dm#dm04475@江 詣行在；
至 dm#dm07135@蘄口 ，
遇 rm#xjts22125@少誠 入寇。

 rm#r00535@曹王皋 遣 dm#dm07136@蘄州 刺史 rm#r00096@伊愼 將兵七千拒之，
戰於 dm#dm04401@永安戍 ，
大破之，
 rm#xjts22125@少誠 脱身走，
斬首萬級，
 rm#r00342@包佶 乃得前。

後 rm#r00342@佶 入朝，
具奏 rm#r03921@陳少遊 奪財賦事；
 rm#r03921@少遊 懼，
厚斂所部以償之。

 rm#r01719@李希烈 以 dm#dm01535@夏口 上流要地，
使其驍將 rm@董侍 募死士七千襲 dm#dm07895@鄂州 ，
刺史 rm@李兼 偃旗臥鼓閉門以待之。

 rm@侍 撤屋材以焚門，
 rm@兼 帥士卒出戰，
大破之。

上以 rm@兼 爲 dm#dm07893@鄂 、 dm#dm02432@嶽 、 dm#dm04606@沔 都團練使。

於是 rm#r01719@希烈 東畏 rm#r00535@曹王皋 ，
西畏 rm@李兼 ，
不敢復有窺 dm#dm04475@江 、 dm#dm04981@淮 之志矣。

# p 

 rm#r01579@朱滔 引兵入 dm#dm07617@趙 境，
 rm#r02656@王武俊 大具犒享；
入 dm#dm08945@魏 境，
 rm#r02819@田悦 供承倍豐，
使者迎候，
相望於道。

丁丑，
 rm#r01579@滔 至 dm#dm04435@永濟 ，
遣 rm#xjts02018@王郅 見 rm#r02819@悦 ，
約會 dm#dm08796@館陶 ，
偕行渡 dm#dm04650@河 。

 rm#r02819@悦 見 rm#xjts02018@郅 曰：
「 rm#r02819@悦 固願從五兄南行，
昨日將出軍，
將士勒兵不聽 rm#r02819@悦 出，
曰：
『國兵新破，
戰守踰年，
資儲竭矣。

今將士不免凍餒，
何以全軍遠征！

大王日自撫循，
猶不能安；
若捨城邑而去，
朝出，
暮必有變！』

 rm#r02819@悦 之志非敢有貳也，
如將士何！

已令 rm#xjts06642@孟祐 備歩騎五千，
從五兄供芻牧之役。」

因遣其司禮侍郎 rm@裴抗 等往謝 rm#r01579@滔 。

 rm#r01579@滔 聞之，
大怒曰：
「 rm#r02819@田悦 逆賊，
曏在重圍，
命如絲髮，
使我叛君棄兄，
發兵晝夜赴之，
幸而得存。

許我 dm#dm07514@貝州 ，
我辭不取；
尊我爲天子，
我辭不受。

今乃負恩，
誤我遠來，
飾辭不出！」

即日，
遣 rm#xjts24968@馬寔 攻 dm#dm02113@宗城 、 dm#dm06446@經城 ，
 rm#xjts23074@楊榮國 攻 dm#dm00719@冠氏 ，
皆拔之；
又縱囘紇掠 dm#dm08796@館陶 頓幄帟、器皿、車、牛以去。

 rm#r02819@悦 閉城自守。

壬午，
 rm#r01579@滔 遣 rm@裴抗 等還，
分兵置吏守 dm#dm02631@平恩 、 dm#dm04435@永濟 。

# p 

丙戌，
以吏部侍郎 rm#xjts07612@盧翰 爲兵部侍郎、同平章事。

 rm#xjts07612@翰 ，
 rm#xjts07798@義僖 之七世孫也。

# p 

 rm#r01579@朱滔 引兵北圍 dm#dm07514@貝州 ，
引水環之，
刺史 rm#xjts06764@邢曹俊 嬰城拒守；
縱 dm#dm06863@范陽 及囘紇兵大掠諸縣，
又拔 dm#dm04238@武城 ，
通 dm#dm02976@徳 、 dm#dm04071@棣 二州，
使給軍食；
遣 rm#xjts24968@馬寔 將歩騎五千屯 dm#dm00719@冠氏 以逼 dm#dm08950@魏州 。
# p 

以給事中 rm#r02068@杜黄裳 爲 dm#dm04501@江淮 宣慰副使。

# p 

上於行宮廡下貯諸道貢獻之物，
牓曰 dm#dm05767@瓊林大盈庫 。

 rm#r03959@陸贄 以爲戰守之功，
賞賚未行而遽私別庫，
則士卒怨望，
無復鬬志，
上疏諫，
其略曰：
「天子與天同徳，
以四海爲家，
何必橈廢公方，
崇聚私貨！

降至尊而代有司之守，
辱萬乘以效匹夫之藏，
虧法失人，
誘姦聚慝，
以斯制事，
豈不過哉！」

又曰：
「頃者六師初降，
百物無儲，
外扞兇徒，
内防危堞，
晝夜不息，
殆將五旬，
凍餒交侵，
死傷相枕，
畢命同力，
竟夷大艱。

良以陛下不厚其身，
不私其欲，
絶甘以同卒伍，
輟食以啗功勞。

無猛制而人不攜，
懷所感也；
無厚賞而人不怨，
悉所無也。

今者攻圍已解，
衣食已豐，
而謠讟方興，
軍情稍阻，
豈不以勇夫恆性，
嗜利矜功，
其患難既與之同憂而好樂不與之同利，
苟異恬默，
能無怨咨！」

又曰：
「陛下誠能近想重圍之殷憂，
追戒平居之專欲，
凡在二庫貨賄，
盡令出賜有功，
毎獲珍華，
先給軍賞，
如此，
則亂必靖，
賊必平，
徐駕六龍，
旋復都邑，
天子之貴，
豈當憂貧！

是乃散其小儲而成其大儲，
損其小寶而固其大寶也。」

上即命去其牓。

# p 

 rm#r03243@蕭復 嘗言於上曰：
「宦官自艱難以來，
多爲監軍，
恃恩縱横。

此屬但應掌宮掖之事，
不宜委以兵權國政。

」
上不悦。

又嘗言：
「陛下踐阼之初，
聖徳光被，
自 rm#r02224@楊炎 、 rm#r02881@盧𣏌 黷亂朝政，
以致今日。

陛下誠能變更睿志，
臣敢不竭力。

儻使臣依阿苟免，
臣實不能！」

又嘗與 rm#r02881@盧𣏌 同奏事，
 rm#r02881@𣏌 順上旨，
 rm#r03243@復 正色曰：
「 rm#r02881@盧𣏌 言不正！」

上愕然，
退，
謂左右曰：
「 rm#r03243@蕭復 輕朕！」

戊子，
命 rm#r03243@復 充 dm#dm02400@山南東 ‧ dm#dm07286@西 、 dm#dm06890@荊湖 、 dm#dm04984@淮南 、 dm#dm04509@江西 、 dm#dm07894@鄂嶽 、 dm#dm04855@浙江東 ‧ dm#dm07286@西 、 dm#dm06249@福建 、 dm#dm02527@嶺南 等道宣慰、安撫使，
實疏之也。

既而 rm#r00249@劉從一 及朝士往往奏留 rm#r03243@復 ，
上謂 rm#r03959@陸贄 曰：
「朕思遷幸以來，
 dm#dm04475@江 、 dm#dm04981@淮 遠方，
或傳聞過實，
欲遣重臣宣慰，
謀於宰相及朝士，
僉謂宜然。

今乃反覆如是，
朕爲之悵恨累日。

意 rm#r03243@復 悔行，
使之論奏邪？
卿知 rm#r03243@蕭復 何如人？
其不欲行，
意趣安在？」
 rm#r03959@贄 上奏，
以爲：
「 rm#r03243@復 痛自脩勵，
慕爲清貞，
用雖不周，
行則可保。

至於輕詐如此，
 rm#r03243@復 必不爲。

借使 rm#r03243@復 欲逗留，
 rm#r00249@從一 安肯附會！

今所言矛楯，
願陛下明加辯詰。

若 rm#r03243@蕭復 有所請求，
則 rm#r00249@從一 何容爲隱！

若 rm#r00249@從一 自有囘互，
則 rm#r03243@蕭復 不當受疑。

陛下何憚而不辯明，
乃直爲此悵恨也！

夫明則罔惑，
辯則罔冤；
惑莫甚於逆詐而不與明，
冤莫痛於見疑而不與辯。

是使情僞相糅，
忠邪靡分。

茲實居上御下之要樞，
惟陛下留意。」

上亦竟不復辯也。

# p 

辛卯，
以 rm#r02656@王武俊 爲 dm#dm03017@恆 、 dm#dm00712@冀 、 dm#dm05013@深 、 dm#dm07617@趙 節度使。

壬辰，
加 rm#r01783@李抱眞 、 rm#r01268@張孝忠 竝同平章事。

丙申，
加 rm#r02819@田悦 檢校左僕射。

以 dm#dm02400@山南東道 行軍司馬 rm#r02269@樊澤 爲本道節度使，
前 dm#dm05013@深 、 dm#dm07617@趙 觀察使 rm#r01052@康日知 爲 dm#dm01227@同州 刺史、奉誠軍節度使，
 dm#dm03641@曹州 刺史 rm@李納 爲 dm#dm07905@鄆州 刺史、 dm#dm02660@平盧 節度使。


# p 

戊戌，
加 rm#r00292@劉洽  dm#dm04537@汴 、 dm#dm05225@滑 、 dm#dm02093@宋 、 dm#dm00454@亳 都統副使，
知都統事，
 rm@李勉 悉以其衆授之。

# p 

辛丑，
六軍各置統軍，
秩從三品，
以寵勳臣。

# p 

吐蕃 rm#xjts28773@尚結贊 請出兵助 dyn#ch100@唐 收 dm#dm08170@京城 。

庚子，
遣祕書監 rm#r00952@崔漢衡 使吐蕃，
發其兵。

# p 

二月，
戊申，
詔贈 rm#r02349@段秀實 太尉，
諡曰 rm#r02349@忠烈 ，
厚恤其家。

時 rm#r03588@賈隱林 已卒，
贈左僕射，
賞其能直言也。

# p 

 rm#r01719@李希烈 將兵五萬圍 dm#dm02309@寧陵 ，
引水灌之；
 dm#dm05457@濮州 刺史 rm#r00271@劉昌 以三千人守之。

# p 

 dm#dm05229@滑州 刺史 rm@李澄 密遣使請降，
上許以 rm@澄 爲 dm#dm04546@汴滑 節度使。

 rm@澄 猶外事 rm#r01719@希烈 ；
 rm#r01719@希烈 疑之，
遣養子六百人戍 dm#dm05929@白馬 。

召 rm@澄 共攻 dm#dm02309@寧陵 。

 rm@澄 至 dm#dm06102@石柱 ，
使其衆陽驚，
燒營而遁。

又諷養子令剽掠，
 rm@澄 悉收斬之，
以白 rm#r01719@希烈 ，
 rm#r01719@希烈 無以罪也。
# p 

 rm#r00271@劉昌 守 dm#dm02309@寧陵 ，
凡四十五日不釋甲。

 rm#r04122@韓滉 遣其將 rm#r02654@王栖曜 將兵助 rm#r00292@劉洽 拒 rm#r01719@希烈 ，
 rm#r02654@栖曜 以強弩數千游 dm#dm04543@汴水 ，
夜，
入 dm#dm02310@寧陵城 。

明日，
從城上射 rm#r01719@希烈 ，
及其坐幄，
 rm#r01719@希烈 驚曰：
「 dm#dm02203@宣 、 dm#dm05366@潤 弩手至矣！」

遂解圍去。
# p 

 rm#r01577@朱泚 自 dm#dm01853@奉天 敗歸，
 rm@李晟 謀取 dm#dm08170@長安 。

 rm#xjts25436@劉徳信 與 rm@晟 倶屯 dm#dm03850@東渭橋 ，
不受 rm@晟 節制；
 rm@晟 因 rm#xjts25436@徳信 至營中，
數以 dm#dm05239@滬澗 之敗及所過剽掠之罪，
斬之；
因以數騎馳入 rm#xjts25436@徳信 軍，
勞其衆，
無敢動者，
遂幷將之，
軍勢益振。
既
# p 

 rm#r01775@李懷光 既脅朝廷逐 rm#r02881@盧𣏌 等，
内不自安，
遂有異志。

又惡 rm@李晟 獨當一面，
恐其成功，
奏請與 rm@晟 合軍；
詔許之。

 rm@晟 與 rm#r01775@懷光 會于 dm#dm01345@咸陽 西 dm#dm08353@陳濤斜 ，
築壘未畢，
 rm#r01577@泚 衆大至。

 rm@晟 謂 rm#r01775@懷光 曰：
「賊若固守宮苑，
或曠日持久，
未易攻取；
今去其巣穴，
敢出求戰，
此天以賊賜明公，
不可失也！」

 rm#r01775@懷光 曰：
「軍適至，
馬未秣，
士未飯，
豈可遽戰邪！」

 rm@晟 不得已乃就壁。

 rm@晟 毎與 rm#r01775@懷光 同出軍，
 rm#r01775@懷光 軍士多掠人牛馬，
 rm@晟 軍秋豪不犯。

 rm#r01775@懷光 軍士惡其異己，
分所獲與之，
 rm@晟 軍終不敢受。
# p 

 rm@懷光 屯 dm#dm01345@咸陽 累月，
逗留不進；
上屡遣中使趣之，
辭以士卒疲弊，
且當休息觀釁。

諸將數勸之攻 dm#dm08170@長安 ，
 rm#r01775@懷光 不從，
密與 rm#r01577@朱泚 通謀。

 rm@李晟 屡奏，
恐其有變，
爲所併，
請移軍 dm#dm03850@東渭橋 ；
上猶冀 rm#r01775@懷光 革心，
收其力用，
寢 rm@晟 奏不下。
事跡頗露
# p 

 rm#r01775@懷光 欲緩戰期，
且激怒諸軍，
奏言：
「諸軍糧賜薄，
神策獨厚。

厚薄不均，
難以進戰。」

上以財用方窘，
若糧賜皆比神策，
則無以給之，
不然，
又逆 rm#r01775@懷光 意，
恐諸軍觖望；
乃遣 rm#r03959@陸贄 詣 rm#r01775@懷光 營宣慰，
因召 rm@李晟 參議其事。

 rm#r01775@懷光 意欲 rm@晟 自乞減損，
使失士心，
沮敗其功，
乃曰：
「將士戰鬬同而糧賜異，
何以使之協力！」

 rm#r03959@贄 未有言，
數顧 rm@晟 。

 rm@晟 曰：
「公爲元帥，
得專號令；
 rm@晟 將一軍，
受指蹤而已。

至於増減衣食，
公當裁之。」

 rm#r01775@懷光 默然，
又不欲自減之，
遂止。

# p 

時上遣 rm#r00952@崔漢衡 詣吐蕃發兵，
吐蕃相 rm#xjts28773@尚結贊 言：
「蕃法發兵，
以主兵大臣爲信；
今制書無 rm#r01775@懷光 署名，
故不敢進。」

上命 rm#r03959@陸贄 諭 rm#r01775@懷光 ，
 rm#r01775@懷光 固執以爲不可，
曰：
「若克 dm#dm08170@京城 ，
吐蕃必縱兵焚掠，
誰能遏之！

此一害也。

前有敕旨，
募士卒克城者人賞百緡，
彼發兵五萬，
若援敕求賞，
五百萬緡何從可得！

此二害也。

虜騎雖來，
必不先進，
勒兵自固，
觀我兵勢，
勝則從而分功，
敗則從而圖變，
譎詐多端，
不可親信，
此三害也。」

竟不肯署敕；
 rm#xjts28773@尚結贊 亦不進軍。
# p 

 rm#r03959@陸贄 自 dm#dm01345@咸陽 還，
上言：
「賊 rm#r01577@泚 稽誅，
保聚宮苑，
勢窮援絶，
引日偸生。

 rm#r01775@懷光 總仗順之師，
乘制勝之氣，
鼓行芟翦，
易若摧枯，
而乃寇奔不追，
師老不用，
諸帥毎欲進取，
 rm#r01775@懷光 輒沮其謀。

據茲事情，
殊不可解。

陛下意在全護，
委曲聽從，
觀其所爲，
亦未知感。

若不別務規略，
漸思制持，
惟以姑息求安，
終恐變故難測。

此誠事機危迫之秋也，
固不可以尋常容易處之。

今 rm@李晟 奏請移軍，
適遇臣銜命宣慰，
 rm#r01775@懷光 偶論此事，
臣遂汎問所宜。

 rm#r01775@懷光 乃云：
『 rm@李晟 既欲別行，
某亦都不要藉。』

臣猶慮有翻覆，
因美其軍盛強。

 rm#r01775@懷光 大自矜誇，
轉有輕 rm@晟 之意。

臣又從容問云：
『囘日，
或聖旨顧問事之可否，
決定何如？』
 rm#r01775@懷光 已肆輕言，
不可中變，
遂云：
『恩命許去，
事亦無妨。』

要約再三，
非不詳審，
雖欲追悔，
固難爲辭。

伏望即以 rm@李晟 表出付中書，
敕下依奏，
別賜 rm#r01775@懷光 手詔，
示以移軍事由。

其手詔大意云：
『昨得 rm@李晟 奏，
請移軍城東以分賊勢。

朕本欲委卿商量，
適會 rm#r03959@陸贄 囘奏云，
見卿語及於此，
仍言許去事亦無妨，
遂敕本軍允其所請。』

如此，
則詞婉而直，
理順而明，
雖蓄異端，
何由起怨！」

上從之。

# p 

 rm@晟 自 dm#dm01345@咸陽 結陳而行，
歸 dm#dm03850@東渭橋 。

時 dm#dm07921@鄜坊 節度使 rm#xjts13847@李建徽 、 dm#dm06232@神策 行營節度使 rm#xjts26526@楊惠元 猶與 rm#r01775@懷光 聯營，
 rm#r03959@陸贄 復上奏曰：
「 rm#r01775@懷光 當管師徒，
足以獨制兇寇，
逗留未進，
抑有他由。

所患太強，
不資傍助。

比者又遣 rm@李晟 、 rm#xjts13847@李建徽 、 rm#xjts26526@楊惠元 三節度之衆附麗其營，
無益成功，
祗足生事。

何則？
四軍接壘，
羣帥異心，
論勢力則懸絶高卑，
據職名則不相統屬。

 rm#r01775@懷光 輕 rm@晟 等兵微位下而忿其制不從心，
 rm@晟 等疑 rm#r01775@懷光 養寇蓄姦而怨其事多陵己；
端居則互防飛謗，
欲戰則遞恐分功，
齟齬不和，
嫌釁遂構，
俾之同處，
必不兩全。

強者惡積而後亡，
弱者勢危而先覆，
覆亡之禍，
翹足可期！

舊寇未平，
新患方起，
憂歎所切，
實堪疚心！

太上消慝於未萌，
其次救失於始兆，
況乎事情已露，
禍難垂成，
委而不謀，
何以寧亂！

 rm@李晟 見機慮變，
先請移軍，
 rm#xjts13847@建徽 、 rm#xjts26526@惠元 勢轉孤弱，
爲其呑噬，
理在必然，
他日雖有良圖，
亦恐不能自拔；
拯其危急，
唯在此時。

今因 rm@李晟 願行，
便遣合軍同往，
託言 rm@晟 兵素少，
慮爲賊 rm#r01577@泚 所邀，
藉此兩軍迭爲掎角，
仍先諭旨，
密使促裝，
詔書至營，
即日進路，
 rm#r01775@懷光 意雖不欲，
然亦計無所施。

是謂先人有奪人之心，
疾雷不及掩耳者也。

解鬬不可以不離，
救焚不可以不疾，
理盡於此，
惟陛下圖之。」

上曰：
「卿所料極善。

然 rm@李晟 移軍，
 rm#r01775@懷光 不免悵望，
若更遣 rm#xjts13847@建徽 、 rm#xjts26526@惠元 就東，
恐因此生辭，
轉難調息，
且更俟旬時。」

就東
# p 

辛酉，
加 rm#r02656@王武俊 同平章事兼 dm#dm02689@幽州 、 dm#dm06013@盧龍 節度使。

# p 

 rm@李晟 以爲：
「 rm#r01775@懷光 反状已明，
緩急宜有備，
 dm#dm07197@蜀 、 dm#dm05271@漢 之路不可壅，
請以裨將 rm#xjts23858@趙光銑 等爲 dm#dm04757@洋 、 dm#dm00759@利 、 dm#dm00789@劍 三州刺史，
各將兵五百以防未然。

」
上疑未決，
欲親總禁兵幸 dm#dm01345@咸陽 ，
以慰撫爲名，
趣諸將進討。

或謂 rm#r01775@懷光 曰：
「此 rm#rt0511@漢祖 遊 dm#dm08559@雲夢 之策也！」

 rm#r01775@懷光 大懼，
反謀益甚。
# p 

上垂欲行，
 rm#r01775@懷光 辭益不遜，
上猶疑讒人間之，
甲子，
加 rm#r01775@懷光 太尉，
増實食，
賜鐵券，
遣 dm#dm06232@神策 右兵馬使 rm#xjts12873@李卞 等往諭旨。

 rm#r01775@懷光 對使者投鐵券於地曰：
「聖人疑 rm#r01775@懷光 邪？
人臣反，
賜鐵券；
 rm#r01775@懷光 不反，
今賜鐵券，
是使之反也！」

辭氣甚悖。

 dm#dm03677@朔方 左兵馬使 rm#r01118@張名振 當軍門大呼曰：
「太尉視賊不許撃，
待天使不敬，
果欲反邪！

功高 dm#dm01789@太山 ，
一旦棄之，
自取族滅，
富貴他人，
何益哉！

我今日必以死爭之。」

 rm#r01775@懷光 聞之，
謂曰：
「我不反，
以賊方強，
故須蓄鋭俟時耳。」

 rm#r01775@懷光 又言：
「天子所居必有城隍。」

乃發卒城 dm#dm01345@咸陽 ，
未幾，
移軍據之。

 rm#r01118@張名振 曰：
「乃者言不反，
今日拔軍此來，
何也？
何不攻 dm#dm08170@長安 ，
殺 rm#r01577@朱泚 ，
取富貴，
引軍還 dm#dm07808@邠 邪！」

 rm#r01775@懷光 曰：
「 rm#r01118@名振 病心矣！

」
命左右引去，
拉殺之。

# p 

右武鋒兵馬使 rm#r02960@石演芬 ，
本 dm#dm07304@西域 胡人，
 rm#r01775@懷光 養以爲子。

 rm#r01775@懷光 潛與 rm#r01577@朱泚 通謀，
 rm#r02960@演芬 遣其客 rm#xjts10646@郜成義 詣行在告之，
請罷其都統之權。

 rm#xjts10646@成義 至 dm#dm01853@奉天 ，
告 rm#r01775@懷光 子璀：
 rm@璀 密白其父。

 rm#r01775@懷光 召 rm#r02960@演芬 責之曰：
「我以爾爲子，
奈何欲破我家！

今日負我，
死甘心乎？」
 rm#r02960@演芬 曰：
「天子以太尉爲股肱，
太尉以 rm#r02960@演芬 爲心腹；
太尉既負天子，
 rm#r02960@演芬 安得不負太尉乎！

 rm#r02960@演芬 胡人，
不能異心，
惟知事一人。

苟免賊名而死，
死甘心矣！」

 rm#r01775@懷光 使左右臠食之，
皆曰：
「義士也！

可令快死。」

以刀斷其喉而去。
璀
# p 

 rm#xjts12873@李卞 等還，
言 rm#r01775@懷光 驕慢之状，
於是行在始嚴門禁，
從臣皆密裝以待。

# p 

乙丑，
加 rm@李晟  dm#dm04651@河中 、 dm#dm01233@同絳 節度使；
上猶以爲薄，
丙寅，
又加同平章事。
# p 

上將幸 dm#dm04043@梁州 ，
 dm#dm02398@山南 節度使 dm#dm09043@鹽亭  rm#r00576@嚴震 聞之，
遣使詣 dm#dm01853@奉天 奉迎，
又遣大將 rm#xjts05074@張用誠 將兵五千至 dm#dm06019@盩厔 以來迎衞。

 rm#xjts05074@用誠 爲 rm#r01775@懷光 所誘，
陰與之通謀，
上聞而患之。

會 rm#r00576@震 繼遣牙將 rm#xjts25026@馬勛 奉表，
上語之故；
 rm#xjts25026@勛 請「亟詣 dm#dm04043@梁州 取 rm#r00576@嚴震 符召 rm#xjts05074@用誠 還府；
若不受召，
臣請殺之。」

上喜曰：
「卿何時復至此？」
 rm#xjts25026@勛 刻日時而去。

既得 rm#r00576@震 符，
請壯士五人與之倶出 dm#dm08857@駱谷 。

 rm#xjts05074@用誠 不知事泄，
以數百騎迎之，
 rm#xjts25026@勛 與之倶入驛。

時天寒，
 rm#xjts25026@勛 多然藁火於驛外，
軍士皆往附火。

 rm#xjts25026@勛 乃從容出懷中符，
以示 rm#xjts05074@用誠 曰：
「大夫召君。」

 rm#xjts05074@用誠 錯愕起走，
壯士自後執其手擒之。

 rm#xjts05074@用誠 子在 rm#xjts25026@勛 後，
斫傷 rm#xjts25026@勛 首。

壯士格殺其子，
仆 rm#xjts05074@用誠 於地，
跨其腹，
以刀擬其喉曰：
「出聲則死！」

 rm#xjts25026@勛 入其營，
士卒已擐甲執兵矣。

 rm#xjts25026@勛 大言曰：
「汝曹父母妻子皆在 dm#dm05272@漢中 ，
一朝棄之，
與 rm#xjts05074@張用誠 同反，
於汝曹何利乎！

大夫令我取 rm#xjts05074@用誠 ，
不問汝曹，
無自取族滅！」

衆皆讋服。

 rm#xjts25026@勛 送 rm#xjts05074@用誠 詣 dm#dm04043@梁州 ，
 rm#r00576@震 杖殺之，
命副將領其衆。

 rm#xjts25026@勛 裹其首，
復命於行在，
愆期半日。

# p 

 rm#r01775@李懷光 夜遣人襲奪 rm#xjts13847@李建徽 、 rm#xjts26526@楊惠元 軍，
 rm#xjts13847@建徽 走免，
 rm#xjts26526@惠元 將奔 dm#dm01853@奉天 ，
 rm#r01775@懷光 遣兵追殺之。

 rm#r01775@懷光 又宣言曰：
「吾今與 rm#r01577@朱泚 連和，
車駕且當遠避！」


# p 

 rm#r01775@懷光 以 rm#r04133@韓遊瓌  dm#dm03677@朔方 將也，
掌兵在 dm#dm01853@奉天 ，
與 rm#r04133@遊瓌 書，
約使爲變，
 rm#r04133@遊瓌 密奏之；
明日，
又以書趣之，
上稱其忠義，
因問：
「策安出？」
對曰：
「 rm#r01775@懷光 總諸道兵，
故敢恃衆爲亂。

今 dm#dm07810@邠寧 有 rm#xjts04995@張昕 ，
 dm#dm08626@靈武 有 rm#xjts11086@甯景璿 ，
 dm#dm04651@河中 有 rm#xjts24507@呂鳴嶽 ，
 dm#dm03228@振武 有 rm#xjts21952@杜從政 ，
 dm#dm05384@潼關 有 rm#xjts00838@唐朝臣 ，
 dm#dm05105@渭北 有 rm#r03045@竇覦 ，
皆守將也。

陛下各以其地及其衆授之，
尊 rm#r01775@懷光 之官，
罷其權，
則行營諸將各受本府指麾矣。

 rm#r01775@懷光 獨立，
安能爲亂！」

上曰：
「罷 rm#r01775@懷光 兵權，
若 rm#r01577@朱泚 何？」
對曰：
「陛下既許將士以克城殊賞，
將士奉天子之命以討賊取富貴，
誰不願之！

 dm#dm07813@邠府 兵以萬數，
借使臣得而將之，
足以誅 rm#r01577@泚 ；
況諸道必有杖義之臣，
 rm#r01577@泚 不足憂也！」

上然之。遊⿰王褱又奏之
# p 

丁卯，
 rm#r01775@懷光 遣其將 rm@趙昇鸞 入 dm#dm01853@奉天 ，
約其夕使別將 rm#xjts12478@達奚小俊 燒 dm#dm00360@乾陵 ，
令 rm@昇鸞 爲内應以驚脅乘輿。

 rm@昇鸞 詣 rm#r02462@渾瑊 自言，
 rm#r02462@瑊 遽以聞，
且請決幸 dm#dm04043@梁州 。

上命 rm#r02462@瑊 戒嚴，
 rm#r02462@瑊 出，
部勒未畢，
上已出城西，
命 rm#r01372@戴休顏 守 dm#dm01853@奉天 ，
朝臣將士狼狽扈從。

 rm#r01372@戴休顏 徇於軍中曰：
「 rm#r01775@懷光 已反！」

遂乘城拒守。
# p 

 rm#r01577@朱泚 之稱帝也，
兵部侍郎 rm#r00327@劉迺 臥病在家，
 rm#r01577@泚 召之，
不起；
使 rm#r03223@蒋鎭 自往説之，
凡再往，
知不可誘脅，
乃歎曰：
「 rm#r03223@鎭 亦忝列曹，
不能捨生，
以至於此，
豈可復以己之腥臊汚漫賢者乎！」

歔欷而返。

 rm#r00327@迺 聞帝幸 dm#dm02398@山南 ，
搏膺大呼，
自投于牀，
不食數日而卒。

# p 

太子少師 rm#r00521@喬琳 從上至 dm#dm06019@盩厔 ，
稱老疾不堪山險，
削髮爲僧，
匿於 dm#dm00477@仙遊寺 ；
 rm#r01577@泚 聞之，
召至 dm#dm08170@長安 ，
以爲吏部尚書。

於是朝士之竄匿者多出仕 rm#r01577@泚 矣！

# p 

 rm#r01775@懷光 遣其將 rm#xjts06609@孟保 、 rm#xjts23966@惠靜壽 、 rm@孫福達 將精騎趣 dm#dm00975@南山 邀車駕，
遇諸軍糧料使 rm#r01128@張増 於 dm#dm06019@盩厔 。

三將曰：
「彼使我爲不臣，
我以追不及報之，
不過不使我將耳。」

因目 rm#r01128@増 曰：
「軍士未朝食，
如何？」
 rm#r01128@増 紿其衆曰：
「此東數里有佛祠，
吾貯糧焉。」

三將帥衆而東，
縱之剽掠，
由是百官從行者皆得入 dm#dm08857@駱谷 ，
以追不及還報，
 rm#r01775@懷光 皆黜之。
# p 

 dm#dm04672@河東 將 rm@王權 、 rm#xjts24962@馬彙 引兵歸 dm#dm01774@太原 。

# p 

 rm@李晟 得除官制，
拜哭受命，
謂將佐曰：
「 dm#dm08170@長安 ，
宗廟所在，
天下根本，
若諸將皆從行，
誰當滅賊者！」

乃治城隍，
繕甲兵，
爲復 dm#dm08170@京城 之計。

先是 dm#dm03850@東渭橋 有積粟十餘萬斛，
度支給 rm#r01775@李懷光 軍，
幾盡。

是時 rm#r01775@懷光 、 rm#r01577@朱泚 連兵，
聲勢甚盛，
車駕南幸，
人情擾擾；
 rm@晟 以孤軍處二強寇之間，
内無資糧，
外無救援，
徒以忠義感激將士，
故其衆雖單弱而鋭氣不衰。

又以書遺 rm#r01775@懷光 ，
辭禮卑遜，
雖示尊崇而諭以禍福，
勸之立功補過，
故 rm#r01775@懷光 慚恧，
未忍撃之。

 rm@晟 曰：
「畿内雖兵荒之餘，
猶可賦斂。

宿兵養寇，
患莫大焉！」

乃以判官 rm#r01152@張彧 假 dm#dm00427@京兆 尹，
擇四十餘人，
假官以督 dm#dm05105@渭北 芻粟，
不旬日，
皆充羨；
乃流涕誓衆，
決志平賊。
諸縣
# p 

 rm#r02819@田悦 用兵數敗，
士卒死者什六七，
其下皆厭苦之。

上以給事中 rm#r00666@孔巣父 爲 dm#dm08946@魏博 宣慰使。

 rm#xjts06127@巣父 性辯博，
至 dm#dm08950@魏州 ，
對其衆爲陳逆順禍福；
 rm#r02819@悦 及將士皆喜。

兵馬使 rm#r02829@田緒 ，
 rm#r02821@承嗣 之子也，
凶險，
多過失，
 rm#r02819@悦 不忍殺，
杖而拘之。

 rm#r02819@悦 既歸國，
内外撤警備。

三月，
壬申朔，
 rm#r02819@悦 與 rm#xjts06127@巣父 宴飮，
 rm#r02829@緒 對弟姪有怨言，
其姪止之，
 rm#r02829@緒 怒，
殺姪，
既而悔之，
曰：
「僕射必殺我！」

既夕，
 rm#r02819@悦 醉，
歸寢，
 rm#r02829@緒 與左右密穿後垣入，
殺 rm#r02819@悦 及其母、妻等十餘人，
即帥左右執刀立於中門之内夾道。

將旦，
以 rm#r02819@悦 命召行軍司馬 rm@扈崿 、判官 rm#xjts01766@許士則 、都虞候 rm#xjts20208@蒋濟 議事；
府署深邃，
外不知有變，
 rm#xjts01766@士則 、 rm#xjts20208@濟 先至，
召入，
亂斫殺之。

 rm#r02829@緒 恐既明事泄，
乃出門，
遇 rm#r02819@悦 親將 rm#xjts25736@劉忠信 方排牙，
 rm#r02829@緒 疾呼謂衆曰：
「 rm#xjts25736@劉忠信 與 rm@扈崿 謀反，
昨夜刺殺僕射。」

衆大驚，
諠譁。

 rm#xjts25736@忠信 未及自辯，
衆分裂殺之。

 rm@扈崿 來，
及戟門遇亂，
招諭將士，
將士從之者三分之一。

 rm#r02829@緒 懼，
登城而立，
大呼謂衆曰：
「 rm#r02829@緒 ，
先相公之子，
諸君受先相公恩，
若能立 rm#r02829@緒 ，
兵馬使賞緡錢二千，
大將半之，
下至士卒，
人賞百緡，
竭公私之貨，
五日取辦。」

於是將士囘首殺 rm@扈崿 ，
皆歸 rm#r02829@緒 ，
軍府乃安。

因請命於 rm#r00666@孔巣父 ，
 rm#xjts06127@巣父 命 rm#r02829@緒 權知軍府。

後數日，
衆乃知 rm#r02829@緒 殺其兄，
雖悔怒，
而 rm#r02829@緒 已立，
無如之何。

 rm#r02829@緒 又殺 rm#r02819@悦 親將 rm#xjts21404@薛有倫 等二十餘人。
# p 

 rm#r01783@李抱眞 、 rm#r02656@王武俊 引兵將救 dm#dm07514@貝州 ，
聞亂，
不敢進。

 rm#r01579@朱滔 聞 rm#r02819@悦 死，
喜曰：
「 rm#r02819@悦 負恩，
天假手於 rm#r02829@緒 也！」

即遣其執憲大夫 rm#xjts28406@鄭景濟 等將歩騎五千助 rm#xjts24968@馬寔 ，
合兵萬二千人攻 dm#dm08950@魏州 。

 rm#xjts24968@寔 軍 dm#dm05732@王莽河 ，
縱騎兵及囘紇四出剽掠。

 rm#r01579@滔 別遣人説 rm#r02829@緒 ，
許以本道節度使。

 rm#r02829@緒 方危急，
遣隨軍 rm#xjts10452@侯臧 詣 dm#dm07514@貝州 送款於 rm#r01579@滔 ，
 rm#r01579@滔 喜，
遣 rm#xjts10452@臧 還報，
使亟定盟約。

時 rm#r02829@緒 部署城内已定，
 rm#r01783@李抱眞 、 rm#r02656@王武俊 又遣使詣 rm#r02829@緒 ，
許以赴援，
如 rm#r02819@悦 存日之約。

 rm#r02829@緒 召將佐議之，
幕僚 rm#xjts27204@曾穆 、 rm#r02889@盧南史 曰：
「用兵雖尚威武，
亦本仁義，
然後有功。

今 dm#dm02693@幽陵 之兵恣行殺掠，
白骨蔽野，
雖先僕射背徳，
其民何罪！

今雖盛強，
其亡可跂立而待也。

況 dm#dm03524@昭義 、 dm#dm03018@恆冀 方相與攻之，
奈何以目前之急欲從人爲反逆乎！

不若歸命朝廷，
天子方蒙塵於外，
聞 dm#dm08946@魏博 使至必喜，
官爵旋踵而至矣。」

 rm#r02829@緒 從之，
遣使奉表詣行在，
城守以俟命。入城
# p 

上之發 dm#dm01853@奉天 也，
 rm#r04133@韓遊瓌 帥其麾下八百餘人還 dm#dm07812@邠州 。

 rm#r01775@李懷光 以 rm@李晟 軍浸盛，
惡之，
欲引軍自 dm#dm01345@咸陽 襲 dm#dm03850@東渭橋 ；
三令其衆，
衆不應，
竊相謂曰：
「若與我曹撃 rm#r01577@朱泚 ，
惟力是視；
若欲反，
我曹有死，
不能從也！」

 rm#r01775@懷光 知衆不可強，
問計於賓佐，
節度巡官 dm#dm06810@良郷  rm#r01816@李景略 曰：
「取 dm#dm08170@長安 ，
殺 rm#r01577@朱泚 ，
散軍還諸道，
單騎詣行在，
如此，
臣節亦未虧，
功名猶可保也。」

頓首懇請，
至於流涕，
 rm#r01775@懷光 許之。

都虞候 rm#xjts26901@閻晏 等勸 rm#r01775@懷光 東保 dm#dm04651@河中 ，
徐圖去就，
 rm#r01775@懷光 乃説其衆曰：
「今且屯 dm#dm04928@涇陽 ，
召妻孥於 dm#dm07808@邠 ，
俟至，
與之倶往 dm#dm04651@河中 。

春裝既辦，
還攻 dm#dm08170@長安 ，
未晩也。

東方諸縣皆富實，
軍發之日，
聽爾俘掠。」

衆許之。

 rm#r01775@懷光 乃謂 rm#r01816@景略 曰：
「曏者之議，
軍衆不從，
子宜速去，
不且見害！」

遣數騎送之。

 rm#r01816@景略 出軍門，
慟哭曰：
「不意此軍陷於不義！」

一旦
# p 

 rm#r01775@懷光 遣使詣 dm#dm07812@邠州 ，
令留後 rm#xjts04995@張昕 悉發所留兵萬餘人及行營將士家屬會 dm#dm04928@涇陽 ，
仍遣其將 rm@劉禮 等將三千餘騎脅遷之。

 rm#r04133@韓遊瓌 説 rm#xjts04995@昕 曰：
「 rm#xjts14889@李太尉 功高，
自蹈禍機；
中丞今日可以自求富貴，
 rm#r04133@遊瓌 請帥麾下以從。」

 rm#xjts04995@昕 曰：
「 rm#xjts04995@昕 微賤，
頼 rm#xjts14889@李太尉 得至此，
不忍負也！」

 rm#r04133@遊瓌 乃謝病不出，
陰與諸將 rm#r04223@高固 、 rm#xjts23054@楊懷賓 等相結。

時 rm#r00952@崔漢衡 以吐蕃兵營于 dm#dm07808@邠 南，
 rm#r04223@高固 曰：
「 rm#xjts04995@昕 以衆去，
則 dm#dm07809@邠城 空矣。」

乃詐爲 rm#r02462@渾瑊 書，
召吐蕃使稍逼 dm#dm07809@邠城 。

 rm#xjts04995@昕 等懼，
竟不敢出。

 rm#xjts04995@昕 等謀殺諸將之不從者，
 rm#r04133@遊瓌 知之，
先與 rm#r04223@高固 等舉兵殺 rm#xjts04995@昕 ，
遣 rm#xjts23054@楊懷賓 奉表以聞，
且遣人告 rm#r00952@崔漢衡 。

 rm#r00952@漢衡 矯詔以 rm#r04133@遊瓌 知軍府事，
軍中大喜。

 rm#r01775@懷光 子 rm@旻 在 dm#dm07808@邠 ，
 rm#r04133@遊瓌 遣之，
或曰：
「不殺 rm@旻 ，
何以自明？」
 rm#r04133@遊瓌 曰：
「殺 rm@旻 ，
 rm#r01775@懷光 怒，
其衆必至，
不如釋 rm@旻 以走之。」

時 rm#xjts23054@楊懷賓 子 rm#r02213@朝晟 在 rm#r01775@懷光 軍中爲右廂兵馬使，
聞之，
泣白 rm#r01775@懷光 曰：
「父立功於國，
子當誅夷，
不可典兵。」

 rm#r01775@懷光 囚之。

於是 rm#r04133@遊瓌 屯 dm#dm07810@邠寧 ，
 rm#r01372@戴休顏 屯 dm#dm01853@奉天 ，
 rm#r00774@駱元光 屯 dm#dm03519@昭應 ，
 rm#r00863@尚可孤 屯 dm#dm07121@藍田 ，
皆受 rm@李晟 節度，
 rm@晟 軍聲大振。棄己
# p 

始，
 rm#r01775@懷光 方強，
 rm#r01577@朱泚 畏之，
與 rm#r01775@懷光 書，
以兄事之，
約分帝 dm#dm08281@關中 ，
永爲鄰國。

及 rm#r01775@懷光 決反，
逼乘輿南幸，
其下多叛之，
勢益弱。

 rm#r01577@泚 乃賜 rm#r01775@懷光 詔書，
以臣禮待之，
且徵其兵。

 rm#r01775@懷光 慚怒，
内憂麾下爲變，
外怒 rm@李晟 襲之，
遂燒營東走，
掠 dm#dm04928@涇陽 等十二縣，
雞犬無遺。

及 dm#dm02268@富平 ，
大將 rm#xjts06627@孟渉 、 rm#xjts26822@段威勇 將數千人奔于 rm@李晟 ，
將士在道散亡相繼。

至 dm#dm04651@河中 ，
或勸 dm#dm04651@河中 守將 rm#xjts24507@呂鳴嶽 焚橋拒之，
 rm#xjts24507@鳴嶽 以兵少恐不能支，
遂納之，
 dm#dm04651@河中 尹 rm#r02018@李齊運 棄城走。

 rm#r01775@懷光 遣其將 rm#xjts23769@趙貴先 築壘於 dm#dm01227@同州 ，
刺史 rm@李紓 懼，
奔行在；
幕僚 rm#r03413@裴向 攝州事，
詣 rm#xjts23769@貴先 ，
責以逆順之理，
 rm#xjts23769@貴先 感寤，
遂請降，
 dm#dm01227@同州 由是獲全。

 rm#r03413@向 ，
 rm#r03470@遵慶 之子也。

 rm#r01775@懷光 使其將 rm@符嶠 襲 dm#dm01476@坊州 ，
據之，
 dm#dm05105@渭北 守將 rm#r03045@竇覦 帥獵團七百圍之；
 rm@嶠 請降。

詔以 rm#r03045@覦 爲 dm#dm05105@渭北 行軍司馬。
# p 

丁亥，
以 rm@李晟 兼 dm#dm00444@京畿 、 dm#dm05105@渭北 、 dm#dm07920@鄜 、 dm#dm01476@坊 、 dm#dm00293@丹 、 dm#dm02812@延 節度使。

# p 

庚寅，
車駕至 dm#dm01482@城固 。

 rm#xjts20761@唐安公主 薨，
上長女也。
# p 

上在道，
民有獻瓜果者，
上欲以散試官授之，
訪於 rm#r03959@陸贄 ，
 rm#r03959@贄 上奏，
以爲：
「爵位恆宜愼惜，
不可輕用。

起端雖微，
流弊必大。

獻瓜果者，
止可賜以錢帛，
不當酬以官。」

上曰：
「試官虚名，
無損於事。」

 rm#r03959@贄 又上奏，
其略曰：
「自兵興以來，
財賦不足以供賜，
而職官之賞興焉；
青朱雜沓於胥徒，
金紫普施於輿皁。

當今所病，
方在爵輕，
設法貴之，
猶恐不重，
若又自棄，
將何勸人！

夫誘人之方，
惟名與利，
名近虚而於教爲重，
利近實而於徳爲輕。

專實利而不濟之以虚，
則耗匱而物力不給；
專虚名而不副之以實，
則誕謾而人情不趨。

故國家命秩之制，
有職事官，
有散官，
有勳官，
有爵號，
然掌務而授俸者，
唯繋職事之一官也，
此所謂施實利而寓虚名者也。

其勳、散、爵號三者所繋，
大抵止於服色、資蔭而已，
此所謂假虚名而佐實利者也。

今之員外、試官，
頗同勳、散、爵號，
雖則授無費祿，
受不占員，
然而突銛鋒、排患難者則以是賞之，
竭筋力、展勞效者又以是酬之。

若獻瓜果者亦授試官，
則彼必相謂曰，
『吾以忘躯命而獲官，
此以進瓜果而獲官，
是乃國家以吾之躯命同於瓜果矣。』

視人如草木，
誰復爲用哉！

今陛下既未有實利以敦勸，
又不重虚名而濫施，
人無藉焉。

則後之立功者，
將曷用爲賞哉！」

# p 

 rm#r03959@贄 在翰林，
爲上所親信，
居艱難中，
雖有宰相，
大小之事，
上必與 rm#r03959@贄 謀之，
故當時謂之内相，
上行止必與之倶。

 dm#dm04038@梁 、 dm#dm04757@洋 道險，
嘗與 rm@贄 相失，
經夕不至，
上驚憂涕泣，
募得 rm#r03959@贄 者賞千金。

久之，
乃至，
上喜甚，
太子以下皆賀。

然 rm#r03959@贄 數直諫，
迕上意，
 rm#r02881@盧𣏌 雖貶官，
上心庇之。

 rm#r03959@贄 極言 rm#r02881@𣏌 姦邪致亂，
上雖貌從，
心頗不悦，
故 rm#r00249@劉從一 、 rm#r00640@姜公輔 皆自下陳登用，
 rm#r03959@贄 恩遇雖隆，
未得爲相。

# p 

壬辰，
車駕至 dm#dm04043@梁州 。

 dm#dm02398@山南 地薄民貧，
自 rm#r00793@安 、 rm#xjts23917@史 以來，
盜賊攻剽，
戸口減耗太半，
雖節制十五州，
租賦不及中原數縣。

及大駕駐蹕，
糧用頗窘。

上欲西幸 dm#dm03147@成都 ，
 rm#r00576@嚴震 言於上曰：
「 dm#dm02398@山南 地接 dm#dm00444@京畿 ，
 rm@李晟 方圖收復，
藉六軍以爲聲援。

若幸 dm#dm07316@西川 ，
則 rm@晟 未有收復之期也。」

衆議未決，
會 rm@李晟 表至，
言：
「陛下駐蹕 dm#dm05272@漢中 ，
所以繋億兆之心，
成滅賊之勢；
若規小捨大，
遷都 dm#dm02437@岷 、 dm#dm02438@峨 ，
則士庶失望，
雖有猛將謀臣，
無所施矣！」

上乃止。

 rm#r00576@嚴震 百方以聚財賦，
民不至困窮而供億無乏。

牙將 rm#r00570@嚴礪 ，
 rm#r00576@震 之從祖弟也，
 rm#r00576@震 使掌轉餉，
事甚脩辨。


# p 

初，
 dm#dm01853@奉天 圍既解，
 rm#xjts16619@李楚琳 遣使入貢，
上不得已除 dm#dm09004@鳳翔 節度使，
而心惡之。

議者言 rm#xjts16619@楚琳 凶逆反覆，
若不隄防，
恐生窺伺；
由是 rm#xjts16619@楚琳 使者數輩至，
上皆不引見，
留之不遣。

甫至 dm#dm05272@漢中 ，
欲以 rm#r02462@渾瑊 代 rm#xjts16619@楚琳 鎭 dm#dm09004@鳳翔 ，
 rm#r03959@陸贄 上奏，
以爲：
「 rm#xjts16619@楚琳 殺帥助賊，
其罪固大，
但以乘輿未復，
大憝猶存，
勤王之師悉在畿内，
急宣速告，
晷刻是爭。

 dm#dm01378@商嶺 則道迂且遙，
 dm#dm08857@駱谷 復爲盜所扼，
僅通王命，
唯在 dm#dm07258@褒斜 ，
此路若又阻艱，
南北遂將夐絶。

以諸鎭危疑之勢，
居二逆誘脅之中，
洶洶羣情，
各懷向背。

儻或 rm#xjts16619@楚琳 發憾，
公肆猖狂，
南塞要衝，
東延巨猾，
則我咽喉梗而心膂分矣。

今 rm#xjts16619@楚琳 能兩端顧望，
乃是天誘其衷，
故通歸塗，
將濟大業。

陛下誠宜深以爲念，
厚加撫循，
得其遲疑，
便足集事。

必欲精求素行，
追抉宿疵，
則是改過不足以補愆，
自新不足以贖罪。

凡今將吏，
豈得盡無疵瑕，
人皆省思，
孰免疑畏！

又況阻命之輩，
脅從之流，
自知負恩，
安敢歸化！

斯釁非小，
所宜速圖。

伏願陛下思英主大略，
勿以小不忍虧撓興復之業也。」

上釋然開悟，
善待 rm#xjts16619@楚琳 使者，
優詔存慰之。
# p 

丁酉，
加 dm#dm02225@宣武 節度使 rm#r00292@劉洽 同平章事。


# p 

己亥，
以行在都知兵馬使 rm#r02462@渾瑊 同平章事兼 dm#dm03677@朔方 節度使，
 dm#dm03677@朔方 、 dm#dm07810@邠寧 、 dm#dm03228@振武 、 dm#dm04412@永平 、 dm#dm01853@奉天 行營兵馬副元帥。

# p 

庚子，
詔數 rm#r01775@李懷光 罪惡，
敍 dm#dm03677@朔方 將士忠順功名，
猶以 rm#r01775@懷光 舊勳，
曲加容貸，
其副元帥、太尉、中書令、 dm#dm04651@河中 尹幷 dm#dm03677@朔方 諸道節度、觀察等使，
宜竝罷免，
授太子太保；
其所管兵馬，
委本軍自舉一人功高望重者便宜統領，
速具奏聞，
當授旌旄，
以從人欲。

# p 

夏，
四月，
壬寅，
以 dm#dm07810@邠寧 兵馬使 rm#r04133@韓遊瓌 爲 dm#dm07810@邠寧 節度使。

癸卯，
以 dm#dm01853@奉天 行營兵馬使 rm#r01372@戴休顏 爲 dm#dm01853@奉天 行營節度使。

# p 

 dm#dm08626@靈武 守將 rm#xjts11086@甯景璿 爲 rm#r01775@李懷光 治第，
別將 rm#xjts16777@李如暹 曰：
「 rm#xjts14889@李太尉 逐天子，
而 rm#xjts11086@景璿 爲之治第，
是亦反也！」

攻而殺之。


# p 

甲辰，
加 rm@李晟  dm#dm07921@鄜坊 、 dm#dm00444@京畿 、 dm#dm05105@渭北 、 dm#dm01385@商華 副元帥。

 rm@晟 家百口及 dm#dm06232@神策 軍士家屬皆在 dm#dm08170@長安 ，
 rm#r01577@朱泚 善遇之。

軍中有言及家者，
 rm@晟 泣曰：
「天子何在，
敢言家乎！」

 rm#r01577@泚 使 rm@晟 親近以家書遺 rm@晟 曰：
「公家無恙。」

 rm@晟 怒曰：
「爾敢爲賊爲間！」

立斬之。

軍士未授春衣，
盛夏猶衣裘褐，
終無叛志。

# p 

乙巳，
以 dm#dm08327@陝虢 防遏使 rm#xjts00838@唐朝臣 爲 dm#dm04651@河中 、 dm#dm01233@同絳 節度使。

前 dm#dm04651@河中 尹 rm#r02018@李齊運 爲 dm#dm00427@京兆 尹，
供 rm@晟 軍糧役。


# p 

庚戌，
以 dm#dm08946@魏博 兵馬使 rm#r02829@田緒 爲 dm#dm08946@魏博 節度使。
# p 

 rm#r02462@渾瑊 帥諸軍出 dm#dm03320@斜谷 ，
 rm#r00952@崔漢衡 勸吐蕃出兵助之，
 rm#xjts28773@尚結贊 曰：
「 dm#dm07808@邠 軍不出，
將襲我後。」

 rm#r04133@韓遊瓌 聞之，
遣其將 rm@曹子達 將兵三千往會瑊軍，
吐蕃遣其將 rm@論莽羅依 將兵二萬從之。

 rm#xjts16619@李楚琳 遣其將 rm@石鍠 將卒七百從 rm#r02462@瑊 拔 dm#dm04228@武功 ，
庚戌，
 rm#r01577@朱泚 遣其將 rm#r06275@韓旻 攻 dm#dm04228@武功 ，
 rm@鍠 以其衆迎降。

 rm#r02462@瑊 戰不利，
收兵登 dm#dm07296@西原 。

會 rm@曹子達 以吐蕃至，
撃 rm@旻 ，
大破之於 dm#dm04225@武亭川 ，
斬首萬餘級，
 rm@旻 僅以身免。

 rm#r02462@瑊 遂引兵屯 dm#dm01853@奉天 ，
與 rm@李晟 東西相應，
以逼 dm#dm08170@長安 。
# p 

上欲爲 rm#xjts20761@唐安公主 造塔，
厚葬之，
諫議大夫、同平章事 rm#r00640@姜公輔 表諫，
以爲「 dm#dm02398@山南 非久安之地，
公主之葬，
會歸 dm#dm00196@上都 ，
此宜儉薄，
以副軍須之急。」

上使謂 rm#r03959@陸贄 曰：
「 dm#dm01360@唐安 造塔，
其費甚微，
非宰相所宜論。

 rm#r00640@公輔 正欲指朕過失，
自求名耳。

相負如此，
當如何處之？」
 rm#r03959@贄 上奏，
以爲 rm#r00640@公輔 任居宰相，
遇事論諫，
不當罪之，
其略曰：
「 rm#r00640@公輔 頃與臣同在翰林，
臣今據理辯直則渉於私黨之嫌，
希旨順成則違於匡輔之義；
渉嫌止貽於身患，
違義實玷於君恩。

徇身忘君，
臣之恥也！」

又曰：
「唯闇惑之主，
則怨讟溢於下國而耳不欲聞，
腥徳達於上天而心不求寤，
迨乎顛覆，
猶未知非。」

又曰：
「當問理之是非，
豈論事之大小！虞書曰：『兢兢業業，一日二日萬幾。』

 rm@唐 、 rm@虞 之際，
主聖臣賢，
慮事之微，
日至萬數。

然則微之不可不重也如此，
陛下又安可忽而不念乎！」

又曰：
「若以諫爭爲指過，
則剖心之主不宜見罪於哲王；
以諫爭爲取名，
則匪躬之臣不應垂訓於聖典。」

又曰：
「假有意將指過，
諫以取名，
但能聞善而遷，
見諫不逆，
則所指者適足以彰陛下莫大之善，
所取者適足以資陛下無疆之休。

因而利焉，
所獲多矣。

儻或怒其指過而不改，
則陛下招惡直之譏；
黜其取名而不容，
則陛下被違諫之謗；
是乃掩己過而過彌著，
損彼名而名益彰。

果而行之，
所失大矣。」

上意猶怒，
甲寅，
罷 rm#r00640@公輔 爲左庶子。
# p 

加 dm#dm07316@西川 節度使 rm#r01145@張延賞 同平章事，
賞其供億無乏故也。

# p 

 rm#r01577@朱泚 、 rm#r00621@姚令言 數遣人誘 dm#dm04920@涇原 節度使 rm#r04197@馮河清 ，
 rm#r04197@河清 皆斬其使者。

大將 rm#xjts24355@田希鑒 密與 rm#r01577@泚 通，
殺 rm#r04197@河清 ，
以軍府附於 rm#r01577@泚 ；
 rm#r01577@泚 以 rm#xjts24355@希鑒 爲 dm#dm04920@涇原 節度使。

# p 

上問 rm#r03959@陸贄 ：
「近有卑官自山北來者，
率非良士。

有 rm@邢建 者，
論説賊勢，
語最張皇，
察其事情，
頗似窺覘，
今已於一所安置。

如此之類，
更有數人，
若不追尋，
恐成姦計。

卿試思之，
如何爲便？」
 rm#r03959@贄 上奏，
以爲今盜據宮闕，
有冒渉險遠來赴行在者，
當量加恩賞，
豈得復猜慮拘囚！

其略曰：
「以一人之聽覽而欲窮宇宙之變態，
以一人之防慮而求勝億兆之姦欺，
役智彌精，
失道彌遠。

 rm@項籍 納 dyn#ch128@秦 降卒二十萬，
慮其懷詐復叛，
一舉而盡阬之，
其於防虞，
亦已甚矣。

 rm#rt0511@漢高 豁達大度，
天下之士至者，
納用不疑，
其於備慮，
可謂疏矣。

然而 rm@項氏 以滅，
 rm@劉氏 以昌，
蓄疑之與推誠，
其效固不同也。

 rm#xjts09813@秦皇 嚴肅雄猜，
而 rm@荊軻 奮其陰計；
 rm#rt0529@光武 寛容博厚，
而 rm#r06858@馬援 輸其款誠。

豈不以虚懷待人，
人亦思附；
任數御物，
物終不親！

情思附則感而悦之，
雖寇讎化爲心膂矣；
意不親則懼而阻之，
雖骨肉結爲仇慝矣。」

又曰：
「陛下智出庶物，
有輕待人臣之心；
思周萬機，
有獨馭區㝢之意；
謀呑衆略，
有過愼之防；
明照羣情，
有先事之察；
嚴束百辟，
有任刑致理之規；
威制四方，
有以力勝殘之志。

由是才能者怨於不任，
忠藎者憂於見疑，
著勳業者懼於不容，
懷反側者迫於及討，
馴致離叛，
構成禍災。

天子所作，
天下式瞻，
小猶愼之，
矧又非小！

願陛下以覆車之轍爲戒，
實宗社無疆之休。」

# p 

丁巳，
以前 dm#dm02400@山南東道 節度使 dm#dm01033@南皮  rm#r03583@賈耽 爲工部尚書。

先是，
 rm#r03583@耽 使行軍司馬 rm#r02269@樊澤 奏事行在，
 rm#r02269@澤 既復命，
方大宴，
有急牒至，
以 rm#r02269@澤 代 rm#r03583@耽 爲節度使。

 rm#r03583@耽 内牒懷中，
宴飮如故，
顏色不改；
宴罷，
召 rm#r03583@澤 告之，
且命將吏謁 rm#r02269@澤 。

牙將 rm#r01212@張獻甫 怒曰：
「行軍爲尚書問天子起居，
乃敢自圖節鉞，
奪尚書土地，
事人不忠，
請殺之。」

 rm#r03583@耽 曰：
「是何言也！

天子所命，
即爲節度使矣！」

即日離鎭，
以 rm#r01212@獻甫 自隨，
軍府遂安。
衆心不服
# p 

左僕射 rm#r01787@李揆 自吐蕃還，
甲子，
薨於 dm#dm08995@鳳州 。

# p 

 rm#r04133@韓游瓌 引兵會 rm#r02462@渾瑊 於 dm#dm01853@奉天 。
# p 

丙寅，
加 dm#dm02660@平盧 節度使 rm@李納 同平章事。
# p 

丁卯，
 rm#r03094@義王玼 薨。

# p 

 rm#r01579@朱滔 攻 dm#dm07514@貝州 百餘日，
 rm#xjts24968@馬寔 攻 dm#dm08950@魏州 亦踰四旬，
皆不能下。

 rm#xjts03852@賈林 復爲 rm#r01783@李抱眞 説 rm#r02656@王武俊 曰：
「 rm#r01579@朱滔 志呑 dm#dm07512@貝 、 dm#dm08945@魏 ，
復値 rm#r02819@田悦 被害，
儻旬日不救，
則 dm#dm08946@魏博 皆爲 rm#r01579@滔 有矣。

 dm#dm08946@魏博 既下，
則 rm#r01268@張孝忠 必爲之臣。

 rm#r01579@滔 連三道之兵，
益以囘紇，
進臨 dm#dm02597@常山 ，
明公欲保其宗族，
得乎！

常山不守，
則 dm#dm03524@昭義 退保 dm#dm07314@西山 ，
 dm#dm04671@河朔 盡入於 rm#r01579@滔 矣。

不若乘 dm#dm07512@貝 、 dm#dm08945@魏 未下，
與 dm#dm03524@昭義 合兵救之；
 rm#r01579@滔 既破亡，
則 dm#dm08281@關中 喪氣，
 rm#r01577@朱泚 不日梟夷，
鑾輿反正，
諸將之功，
孰有居明公之右者哉！」

 rm#r02656@武俊 悦，
從之。
# p 

戊辰，
 rm#r02656@武俊 軍于 dm#dm00968@南宮 東南，
 rm#r01783@抱眞 自 dm#dm06692@臨洺 引兵會之，
與 rm#r02656@武俊 營相距十里。

兩軍尚相疑，
明日，
 rm#r01783@抱眞 以數騎詣 rm#r02656@武俊 營；
賓客共諫止之，
 rm#r01783@抱眞 命行軍司馬 rm#xjts07065@盧玄卿 勒兵以俟，
曰：
「吾之此舉，
繋天下安危，
若其不還，
領軍事以聽朝命亦惟子，
勵將士以雪讎恥亦惟子。」

言終，
遂行。

 rm#r02656@武俊 嚴備以待之，
 rm#r01783@抱眞 見 rm#r02656@武俊 ，
敍國家禍難，
天子播遷，
持 rm#r02656@武俊 哭，
流涕縱横。

 rm#r02656@武俊 亦悲不自勝，
左右莫能仰視，
遂與 rm#r02656@武俊 約爲兄弟，
誓同滅賊。

 rm#r02656@武俊 曰：
「相公十兄名高四海，
曏蒙開諭，
得棄逆從順，
免葅醢之罪，
享王公之榮。

今又不間胡虜，
辱爲兄弟，
 rm#r02656@武俊 當何以爲報乎！

 rm#r01579@滔 所恃者囘紇耳，
不足畏也。

戰日，
願十兄按轡臨視，
 rm#r02656@武俊 決爲十兄破之。」

 rm#r01783@抱眞 退入 rm#r02656@武俊 帳中，
酣寢久之；
 rm#r02656@武俊 感激，
待之益恭，
指心仰天曰：
「此身已許十兄死矣！」

遂連營而進。
# p 

 dm#dm02398@山南 地熱，
上以軍士未有春服，
亦自御裌衣。

# p 

五月，
鹽鐵判官 dm#dm06979@萬年  rm@王紹 以 dm#dm04475@江 、 dm#dm04981@淮 繒帛來至，
上命先給將士，
然後御衫。

 rm#r04122@韓滉 欲遣使獻綾羅四十擔詣行在，
幕僚 rm#r00106@何士幹 請行；
 rm#r04122@滉 喜曰：
「君能相爲行，
請今日過 dm#dm04475@江 。

」
士幹許諾，
歸別家，
則家之薪米儲偫已羅門庭矣；
登舟，
則資裝器用已充舟中矣；
下至廚籌，
 rm#r04122@滉 皆手筆記列，
無不周備。

毎擔夫，
與白金一版置腰間。

又運米百艘以餉 rm@李晟 ，
自負嚢米置舟中，
將佐爭舉之，
須臾而畢。

艘置五弩手以爲防援，
有寇則叩舷相警，
五百弩已彀矣。

比至 dm#dm05115@渭橋 ，
盜不敢近。

時 dm#dm08281@關中 兵荒，
米斗直錢五百；
及 rm#r04122@滉 米至，
減五之四。

 rm#r04122@滉 爲人強力嚴毅，
自奉儉素，
夫人常衣絹裙，
破，
然後易。廚廁
# p 

吐蕃既破 rm#r06275@韓旻 等，
大掠而去。

 rm#r01577@朱泚 使 rm#xjts24355@田希鑒 厚以金帛賂之，
吐蕃受之；
 rm#r04133@韓遊瓌 以聞。

 rm#r02462@渾瑊 又奏：
「 rm#xjts28773@尚結贊 屡遣人約刻日共取 dm#dm08170@長安 ，
既而不至；
聞其衆今春大疫，
近已引兵去。」

上以 rm@李晟 、 rm#r02462@渾瑊 兵少，
欲倚吐蕃以復 dm#dm08170@京城 ，
聞其去，
甚憂之，
以問 rm#r03959@陸贄 。

 rm@贄 以爲吐蕃貪狡，
有害無益，
得其引去，
實可欣賀；
乃上奏，
其略曰：
「吐蕃遷延顧望，
反覆多端，
深入郊畿，
陰受賊使，
致令羣帥進退憂虞；
欲捨之獨前，
則慮其懷怨乘躡；
欲待之合勢，
則苦其失信稽延。

戎若未歸，
寇終不滅。」

又曰：
「將帥意陛下不見信任，
且患蕃戎之奪其功；
士卒恐陛下不恤舊勞，
而畏蕃戎之專其利；
賊黨懼蕃戎之勝，
不死則悉遺人禽；
百姓畏蕃戎之來，
有財必盡爲所掠。

是以順於王化者其心不得不怠，
陷於寇境者其勢不得不堅。」

又曰：
「今 rm#r01775@懷光 別保 dm#dm07017@蒲 、 dm#dm06430@絳 ，
吐蕃遠避封疆，
形勢既分，
腹背無患，
 rm#r02462@瑊 、 rm@晟 諸帥，
才力得伸。」

又曰：
「但願陛下愼於撫接，
勤於砥礪，
中興大業，
旬月可期，
不宜尚眷眷於犬羊之羣，
以失將士之情也。」

# p 

上復使謂 rm#r03959@贄 曰：
「卿言吐蕃形勢甚善，
然 rm#r02462@瑊 、 rm@晟 諸軍當議規畫，
令其進取。

朕欲遣使宣慰，
卿宜審細條流以聞。」

 rm#r03959@贄 以爲：
「賢君選將，
委任責成，
故能有功。

況今 dm#dm06273@秦 、 dm#dm04038@梁 千里，
兵勢無常，
遙爲規畫，
未必合宜。

彼違命則失君威，
從命則害軍事，
進退羈礙，
難以成功；
不若假以便宜之權，
待以殊常之賞，
則將帥感悦，
智勇得伸。」

乃上奏，
其略曰：
「鋒鏑交於原野而決策於九重之中，
機會變於斯須而定計於千里之外，
用捨相礙，
否臧皆凶。

上有掣肘之譏，
下無死綏之志。」

又曰：
「傳聞與指實不同，
懸算與臨事有異。」

又曰：
「設使其中有肆情干命者，
陛下能於此時戮其違詔之罪乎？
是則違命者既不果行罰，
從命者又未必合宜，
徒費空言，
祗勞睿慮，
匪惟無益，
其損實多。」

又曰：
「君上之權，
特異臣下，
惟不自用，
乃能用人。」
流疏
# p 

癸酉，
 rm#r02440@涇王侹 薨。

# p 

 dm#dm02948@徐 、 dm#dm04887@海 、 dm#dm04580@沂 、 dm#dm02259@密 觀察使 rm#xjts00162@高承宗 卒，
甲戌，
使其子 rm#xjts00339@明應 知軍事。
# p 

乙亥，
 rm#r01783@李抱眞 、 rm#r02656@王武俊 距 dm#dm07514@貝州 三十里而軍。

 rm#r01579@朱滔 聞兩軍將至，
急召 rm#xjts24968@馬寔 ，
 rm@寔 晝夜兼行赴之。

或謂 rm#r01579@滔 曰：
「 rm#r02656@武俊 善野戰，
不可當其鋒，
宜徙營稍前逼之，
使囘紇絶其糧道。

我坐食 dm#dm02976@徳 、 dm#dm04071@棣 之餫，
依營而陳，
利則進攻，
否則入保，
待其飢疲，
然後可制也。」

 rm#r01579@滔 疑未決。

會 rm#xjts24968@馬寔 軍至，
 rm#r01579@滔 命明日出戰。

 rm#xjts24968@寔 言：
「軍士冒暑困憊，
請休息數日乃戰。」

# p 

常侍 rm#xjts22756@楊布 、將軍 rm#xjts21780@蔡雄 引囘紇達干見 rm#r01579@滔 ，
達干曰：
「囘紇在國與鄰國戰，
常以五百騎破鄰國數千騎，
如掃葉耳。

今受大王金帛、牛酒前後無算，
思爲大王立效，
此其時矣。

明日，
願大王駐馬高丘，
觀囘紇爲大王翦 rm#r02656@武俊 之騎，
使匹馬不返。」

 rm#xjts22756@布 、 rm#xjts21780@雄 曰：
「大王英略蓋世，
舉 dm#dm05594@燕 、 dm#dm07104@薊 全軍，
將掃 dm#dm04660@河南 ，
清 dm#dm08281@關中 ，
今見小敵冘豫不撃，
失遠近之望，
將何以成霸業乎！

達干請戰是也。」

 rm#r05646@滔 喜，
遂決意出戰。
# p 

丙子旦，
 rm#r02656@武俊 遣其兵馬使 rm#xjts23648@趙琳 將五百騎伏於 dm#dm04033@桑林 ，
 rm#r01783@抱眞 列方陳於後，
 rm#r02656@武俊 引騎兵居前，
自當囘紇。

囘紇縱兵衝之，
 rm#r02656@武俊 使其騎控馬避之。

囘紇突出其後，
將還，
 rm#r02656@武俊 乃縱兵撃之，
 rm#xjts23648@趙琳 自林中出横撃之，
囘紇敗走。

 rm#r02656@武俊 急追之，
 rm#r01579@滔 騎兵亦走，
自踐其歩陳，
歩騎皆東奔，
 rm#r01579@滔 不能制，
遂走趣其營，
 rm#r01783@抱眞 、 rm#r02656@武俊 合兵追撃之。

時 rm#r01579@滔 引三萬人出戰，
死者萬餘人，
逃潰者亦萬餘人，
滔纔與數千人入營堅守。

會日暮，
昏霧，
兩軍不能進，
 rm#r01783@抱眞 軍其營之西北，
 rm#r02656@武俊 軍其東北。

 rm#r01579@滔 夜焚營，
引兵出南門，
趣 dm#dm02976@徳州 遁去，
委棄所掠資財山積；
兩軍以霧，
不能追也。
# p 

 rm#r01579@滔 殺 rm#xjts22756@楊布 、 rm#xjts21780@蔡雄 而歸 dm#dm02689@幽州 ，
心既内慙，
又恐 dm#dm06863@范陽 留守 rm#r00256@劉怦 因敗圖己。

怦悉發留守兵夾道二十里，
具儀仗，
迎之入府，
相對悲喜，
時人多之。


# p 

初，
 rm#r01268@張孝忠 以 dm#dm03494@易州 歸國，
詔以 rm#r01268@孝忠 爲 dm#dm06549@義武 節度使，
以 dm#dm03494@易 、 dm#dm02116@定 、 dm#dm05208@滄 三州隸之。

 dm#dm05209@滄州 刺史 rm#xjts17251@李固烈 ，
 rm@李惟嶽 之妻兄也，
請歸 dm#dm03023@恆州 ，
 rm#r01268@孝忠 遣押牙 dm#dm01990@安喜  rm#r02996@程華 交其州事。

 rm#xjts17251@固烈 悉取軍府綾、縑、珍貨數十車，
將行，
軍士大譟曰：
「刺史掃府庫之實以行，
將士於後飢寒，
奈何！」

遂殺 rm#xjts17251@固烈 ，
屠其家。

 rm#r02996@程華 聞亂，
自竇逃出，
亂兵求得之，
請知州事；
 rm#r02996@華 不得已，
從之。

 rm#r01268@孝忠 聞之，
即版 rm#r02996@華 攝 dm#dm05209@滄州 刺史。

 rm#r02996@華 素寛厚，
推心以待將士，
將士安之。
# p 

會 rm#r01579@朱滔 、 rm#r02656@王武俊 叛，
更遣人招 rm#r02996@華 ，
 rm#r02996@華 皆不從。

時 rm#r01268@孝忠 在 dm#dm02124@定州 ，
自 dm#dm05208@滄 如 dm#dm02116@定 ，
必過 dm#dm05480@瀛州 ，
 dm#dm05480@瀛 隸 rm#r01579@朱滔 ，
道路阻澀。

 dm#dm05209@滄州 録事參軍 rm@李宇 説 rm#r02996@華 ，
表陳利害，
請別爲一軍，
 rm#r02996@華 從之，
遣 rm@宇 奉表詣行在。

上即以 rm#r02996@華 爲 dm#dm05209@滄州 刺史、 dm#dm04190@横海軍 副大使、知節度事，
賜名 rm#r02996@日華 ，
令 rm#r02996@日華 歳供 dm#dm06549@義武 租錢十二萬緡。
# p 

 rm#r02656@王武俊 又使人説誘之；
時軍中乏馬，
 rm#r02996@日華 紿使者曰：
「 rm@王大夫 必欲相屬，
當以二百騎相助。」

 rm#r02656@武俊 給之，
 rm#r02996@日華 悉留其馬，
遣其士歸。

 rm#r02656@武俊 怒，
而方與 rm#r04181@馬燧 等相拒，
不能攻取，
 rm#r02996@日華 由是獲全。

及 rm#r02656@武俊 歸國，
 rm#r02996@日華 乃遣人謝過，
償其馬價，
且賂之。

 rm#r02656@武俊 喜，
復與交好。

# p 

庚寅，
 rm@李晟 大陳兵，
諭以收復 dm#dm08170@京城 。

先是，
 rm#r00621@姚令言 等屡遣諜人覘 rm@晟 進軍之期，
皆爲邏騎所獲。

 rm@晟 引示以所陳兵，
謂曰：
「歸語諸賊：
努力固守，
勿不忠於賊也！」

皆飮之酒，
給錢而縱之。

遂引兵至 dm#dm07686@通化門 外，
曜武而還，
賊不敢出。

 rm@晟 召諸將，
問兵所從入，
皆請「先取外城，
據坊市，
然後北攻宮闕。」

 rm@晟 曰：
「坊市狹隘，
賊若伏兵格鬬，
居人驚亂，
非官軍之利也。

今賊重兵皆聚苑中，
不若自苑北攻之，
潰其腹心，
賊必奔亡。

如此，
則宮闕不殘，
坊市無擾，
策之上者也！」

諸將皆曰：
「善！」

乃牒 rm#r02462@渾瑊 及 dm#dm08127@鎭國 節度使 rm#r00774@駱元光 、 dm#dm01379@商州 節度使 rm#r00863@尚可孤 ，
刻期集於城下。

# p 

壬辰，
 rm#r00863@尚可孤 敗 rm#r01577@泚 將 rm#xjts09549@仇敬忠 於 dm#dm07121@藍田 西，
斬之。

乙未，
 rm@李晟 移軍於 dm#dm00651@光泰門 外 dm#dm06383@米倉村 。

丙申，
 rm@晟 方自臨築壘，
 rm#r01577@泚 驍將 rm#xjts03968@張庭芝 、 rm#xjts16304@李希倩 引兵大至，
 rm@晟 謂諸將曰：
「始吾憂賊潛匿不出，
今來送死，
此天贊我，
不可失也！」

命副元帥兵馬使 rm#xjts10239@呉詵 等縱兵撃之。

時 dm#dm06938@華州 營在北，
兵少，
賊併力攻之，
 rm@晟 命牙前將 rm@李演 等帥精兵救之。

 rm@演 等力戰，
賊敗走；
 rm@演 等追之，
乘勝入 dm#dm00651@光泰門 ；
再戰，
又破之。

會夜，
 rm@晟 斂兵還。

賊餘衆走入 dm#dm05922@白華門 ，
夜，
聞慟哭。

 rm#xjts16304@希倩 ，
 rm#r01719@希烈 之弟也。
# p 

丁酉，
 rm#r01807@晟 復出兵，
諸將請待西師至夾攻之。

 rm#r01807@晟 曰：
「賊數敗，
已破膽，
不乘勝取之，
使其成備，
非計也。」

賊又出戰，
官軍屡捷；
 rm#r00774@駱元光 敗 rm#r01577@泚 衆於 dm#dm05248@滻 西。

戊戌，
 rm#r01807@晟 陳兵於 dm#dm00651@光泰門 外，
使 rm#xjts15788@李演 及牙前兵馬使 rm#r02596@王佖 將騎兵，
牙前將 rm#xjts23899@史萬頃 將歩兵，
直抵苑牆 dm#dm06214@神䴥村 。

 rm#r01807@晟 先使人夜開苑牆二百餘歩，
比 rm#xjts15788@演 等至，
賊已樹柵塞之，
自柵中刺射官軍，
官軍不得進。

 rm#r01807@晟 怒，
叱諸將曰：
「縱賊如此，
吾先斬公輩矣！」

 rm#xjts23899@萬頃 懼，
帥衆先進，
拔柵而入，
 rm#r02596@佖 、 rm#xjts15788@演 引騎兵繼之，
賊衆大潰，
諸軍分道竝入。

 rm#r00621@姚令言 等猶力戰，
 rm#r01807@晟 命決勝軍使 rm#xjts00743@唐良臣 等歩騎蹙之，
且戰且前，
凡十餘合，
賊不能支。

至 dm#dm05922@白華門 ，
有賊數千騎出官軍之背，
 rm#r01807@晟 帥百餘騎囘禦之，
左右呼曰：
「相公來！」

賊皆驚潰。

# p 

先是，
 rm#r01577@泚 遣 rm#r01110@張光晟 將兵五千屯 dm#dm00326@九曲 ，
去 dm#dm03850@東渭橋 十餘里，
 rm#r01110@光晟 密輸款於 rm@晟 。

及 rm#r01577@泚 敗，
 rm#r01110@光晟 勸 rm#r01577@泚 出亡，
 rm#r01577@泚 乃與 rm#r00621@姚令言 帥餘衆西走，
猶近萬人。

 rm#r01110@光晟 送 rm#r01577@泚 出城，
還，
降於 rm@晟 。

 rm@晟 遣兵馬使 rm#xjts24292@田子奇 以騎兵追 rm#r01577@泚 。

 rm@晟 屯 dm#dm01259@含元殿 前，
舍於右金吾仗，
令諸軍曰：
「 rm@晟 頼將士之力，
克清宮禁。

 dm#dm08170@長安 士庶，
久陷賊庭，
若小有震驚，
非弔民伐罪之意。

 rm@晟 與公等室家相見非晩，
五日内無得通家信。」

命 dm#dm00427@京兆 尹 rm#r02018@李齊運 等安慰居人。

 rm@晟 大將 rm@高明曜 取賊妓，
 rm#r00863@尚可孤 軍士取賊馬，
 rm@晟 皆斬之，
軍中股栗。

公私安堵，
秋毫無犯，
遠坊有經宿乃知官軍入城者。

# p 

是日，
 rm#r02462@渾瑊 、 rm#r01372@戴休顏 、 rm#r04133@韓遊瓌 亦克 dm#dm01345@咸陽 ，
敗賊三千餘衆，
聞 rm#r01577@泚 西走，
分兵邀之。
# p 

己亥，
 rm@晟 使 dm#dm00446@京西 兵馬使 rm#xjts06627@孟渉 屯 dm#dm05922@白華門 ，
 rm#r00863@尚可孤 屯 dm#dm03696@望仙門 ，
 rm#r00774@駱元光 屯 dm#dm06344@章敬寺 ，
 rm@晟 以牙前三千人屯 dm#dm01996@安國寺 ，
以鎭 dm#dm08170@京城 ；
斬 rm#r01577@泚 黨 rm@李希倩 、 rm@敬釭 、 rm#r01285@彭偃 等八人於市。
# p 

 rm#r02656@王武俊 既破 rm#r01579@朱滔 ，
還 dm#dm03023@恆州 ，
表讓 dm#dm02689@幽州 、 dm#dm06013@盧龍 節度使，
上許之。

# p 

六月，
癸卯，
 rm@李晟 遣掌書記呉人 rm#r00045@于公異 作露布上行在曰：
「臣已肅清宮禁，
祗謁寢園，
鍾簴不移，
廟貌如故。」

上泣下曰：
「天生 rm@李晟 ，
以爲社稷，
非爲朕也。」


# p 

 rm@晟 在 dm#dm05115@渭橋 ，
熒惑守歳，
久之乃退，
賓佐皆賀，
曰：
「熒惑退舍，
皇家之福也！

宜速進兵。」

 rm@晟 曰：
「天子野次，
臣下知死敵而已；
天象高遠，
誰得知之！」

既克 dm#dm08170@長安 ，
乃謂之曰：
「曏非相拒也，
吾聞五星贏、縮無常，
萬一復來守歳，
吾軍不戰自潰矣！」

皆謝曰：
「非所及也！」

# p 

 rm#r01577@朱泚 將奔吐蕃，
其衆隨道散亡，
比至 dm#dm04924@涇州 ，
纔百餘騎。

 rm#xjts24355@田希鑒 閉城拒之，
 rm#r01577@泚 謂之曰：
「汝之節，
吾所授也。

奈何臨危相負！」

使焚其門；
 rm#xjts24355@希鑒 取節投火中曰：
「還汝節！」

 rm#r01577@泚 衆皆哭。

 rm@涇 卒遂殺 rm#r00621@姚令言 ，
詣 rm#xjts24355@希鑒 降。

 rm#r01577@泚 獨與 dm#dm06863@范陽 親兵及宗族、賓客北趣 dm#dm08870@驛馬關 ；
 dm#dm02291@寧州 刺史 rm#xjts03489@夏侯英 拒之。

至 dm#dm02922@彭原  dm#dm07301@西城屯 ，
其將 rm#xjts12238@梁庭芬 射 rm#r01577@泚 墜阬中，
 rm#r06275@韓旻 等斬之，
詣 dm#dm04924@涇州 降。

 rm#r02468@源休 、 rm#xjts13985@李子平 奔 dm#dm09004@鳳翔 ，
 rm#xjts16619@李楚琳 斬之，
皆傳首行在。
# p 

上命 rm#r03959@陸贄 草詔賜 rm#r02462@渾瑊 ，
使訪求 dm#dm01853@奉天 所失裹頭内人。

 rm#r03959@贄 上奏，
以爲：
「巨盜始平，
疲瘵之民，
瘡痍之卒，
尚未循拊，
而首訪婦人，
非所以副惟新之望也。

謀始盡善，
克終已稀；
始而不謀，
終則何有！

所賜 rm#r02462@瑊 詔，
未敢承旨。」

上遂不降詔，
竟遣中使求之。
# p 

乙巳，
詔吏部侍郎 rm#r02803@班宏 充宣慰使，
勞問將士，
撫慰蒸黎。

# p 

丙午，
 rm@李晟 斬文武官受 rm#r01577@朱泚 寵任者 rm#xjts08745@崔宣 、 rm#r02439@洪經綸 等十餘人；
又表守節不屈者 rm#r00327@劉迺 、 rm#r03219@蒋沇 等。

# p 

己酉，
以 rm@李晟 爲司徒、中書令，
 rm#r00774@駱元光 、 rm#r00863@尚可孤 各遷官有差。

以檢校御史中丞 rm#xjts24355@田希鑒 爲 dm#dm04920@涇原 節度使。
# p 

詔改 dm#dm04043@梁州 爲 dm#dm06755@興元府 。

# p 

甲寅，
以 rm#r02462@渾瑊 爲侍中，
 rm#r04133@韓遊瓌 、 rm#r01372@戴休顏 各遷官有差。

# p 

 rm#r01577@朱泚 之敗也，
 rm#r03193@李忠臣 奔 dm#dm04160@樊川 ，
擒獲，
丙辰，
斬之。
# p 

上問 rm#r03959@陸贄 ：
「今至 dm#dm09004@鳳翔 有迎駕諸軍，
形勢甚盛，
欲因此遣人代 rm#xjts16619@李楚琳 ，
何如？」
 rm#r03959@贄 上奏，
以爲：
「如此則事同脅執，
以言乎除亂則不武，
以言乎務理則不誠，
用是時巡，
後將安入！

議者或謂之權，
臣竊未諭其理。

夫權之爲義，
取類權衡，
今輦路所經，
首行脅奪，
易一帥而虧萬乘之義，
得一方而結四海之疑，
乃是重其所輕而輕其所重，
謂之權也，
不亦反乎！

以反道爲權，
以任數爲智，
君上行之必失衆，
臣下用之必陷身，
歴代之所以多喪亂而長姦邪，
由此誤也。

不如奠枕 dm#dm00449@京邑 ，
徵授一官，
彼喜於恩宥，
將奔走不暇，
安敢輒有旅拒，
復勞誅鉏哉！」

俟
# p 

戊午，
車駕發 dm#dm05272@漢中 。
# p 

 rm@李晟 綜理 dm#dm08170@長安 以備百司，
自請至 dm#dm09004@鳳翔 迎扈，
上不許。

内常侍 rm#xjts06774@尹元貞 奉使 dm#dm01236@同華 ，
輒詣 dm#dm04651@河中 招諭 rm#r01775@李懷光 。

 rm@晟 奏：
「 rm#xjts06774@元貞 矯制赦元惡，
請理其罪！

」

# p 

秋，
七月，
丙子，
車駕至 dm#dm09004@鳳翔 ，
斬 rm#r00521@喬琳 、 rm#r03223@蒋鎭 、 rm#r01110@張光晟 等。

 rm@李晟 以 rm#r01110@光晟 雖臣賊，
而滅賊亦頗有力，
欲全之；
上不許。
# p 

副元帥判官 rm#xjts00338@高郢 數勸 rm#r01775@李懷光 歸款，
 rm#r01775@懷光 遣其子 rm@璀 詣行在謝罪，
請束身歸朝。

庚辰，
詔遣給事中 rm#r00666@孔巣父 齎先除 rm#r01775@懷光 太子太保敕詣 dm#dm04651@河中 宣慰，
 dm#dm03677@朔方 將士悉復官爵如故。

# p 

壬午，
車駕至 dm#dm08170@長安 ，
 rm#r02462@渾瑊 、 rm#r04133@韓遊瓌 、 rm#r01372@戴休顏 以其衆扈從，
 rm@李晟 、 rm#r00774@駱元光 、 rm#r00863@尚可孤 以其衆奉迎，
歩騎十餘萬，
旌旗數十里。

 rm@晟 謁見上於 dm#dm00127@三橋 ，
先賀平賊，
後謝收復之晩，
伏路左請罪。

上駐馬慰撫，
爲之掩涕，
命左右扶上馬。

至宮，
毎閒日，
輒宴勳臣，
賞賜豐渥，
 rm@李晟 爲之首，
 rm#r02462@渾瑊 次之，
諸將相又次之。
# p 

 rm#r00535@曹王皋 遣其將 rm#r00096@伊愼 、 rm#r02713@王鍔 圍 dm#dm02008@安州 ，
 rm#r01719@李希烈 遣其甥 rm#xjts25757@劉戒虚 將歩騎八千救之；
 rm#r00535@皋 遣其別將 rm@李伯潛 逆之於 dm#dm03091@應山 ，
斬首千餘級。

生擒 rm#xjts25757@戒虚 ，
徇於城下，
 dm#dm02008@安州 遂降，
以 rm#r00096@伊愼 爲 dm#dm02008@安州 刺史。

又撃 rm#r01719@希烈 將 rm@康叔夜 於 dm#dm01128@厲郷 ，
走之。
撃
# p 

丁亥，
 rm#r00666@孔巣父 至 dm#dm04651@河中 ，
 rm#r01775@李懷光 素服待罪，
 rm#xjts06127@巣父 不之止。

 rm#r01775@懷光 左右多胡人，
皆歎曰：
「太尉無官矣！」

 rm#xjts06127@巣父 又宣言於衆曰：
「軍中誰可代太尉領軍者？」
於是 rm#r01775@懷光 左右發怒諠譟；
宣詔未畢，
衆殺 rm#xjts06127@巣父 及中使 rm#xjts24806@啖守盈 ，
 rm#r01775@懷光 亦不之止，
復治兵爲拒守之備。

# p 

辛卯，
赦天下。
# p 

初，
 rm#r01661@肅宗 在 dm#dm08626@靈武 ，
上爲 rm#r01333@奉節王 ，
學文於 rm#r01838@李泌 。

 rm#xjts00683@代宗 之世，
 rm#r01838@泌 居 dm#dm07068@蓬莱書院 ，
上爲太子，
亦與之遊。

及上在 dm#dm06753@興元 ，
 rm#r01838@泌 爲 dm#dm03781@杭州 刺史，
上急詔徵之，
與 dm#dm06059@睦州 刺史 rm#r02021@杜亞 倶詣行在。

乙未，
以 rm#r01838@泌 爲左散騎常侍，
 rm#r02021@亞 爲刑部侍郎；
命 rm#r01838@泌 日直西省以候對，
朝野皆屬目附之。

上問 rm#r01838@泌 ：
「 dm#dm04651@河中 密邇 dm#dm08170@京城 ，
 dm#dm03677@朔方 兵素稱精鋭，
如 rm#xjts12478@達奚小俊 等皆萬人敵，
朕晝夕憂之，
奈何？」
對曰：
「天下事甚有可憂者；
若惟 dm#dm04651@河中 ，
不足憂也。

夫料敵者，
料將不料兵。

今 rm#r01775@懷光 ，
將也；
 rm#xjts12478@小俊 之徒乃兵耳，
何足爲意！

 rm#r01775@懷光 既解 dm#dm01853@奉天 之圍，
視 rm#r01577@朱泚 垂亡之虜不能取，
乃與之連和，
使 rm@李晟 得取以爲功。

今陛下已還宮闕，
 rm#r01775@懷光 不束身歸罪，
乃虐殺使臣，
鼠伏 dm#dm04651@河中 ，
如夢魘之人耳！

但恐不日爲帳下所梟，
使諸將無以藉手也。」
小俊承俊
# p 

初，
上發吐蕃以討 rm#r01577@朱泚 ，
許成功以 dm#dm00516@伊西 、 dm#dm00860@北庭 之地與之；
及 rm@泚 誅，
吐蕃來求地，
上欲召兩鎭節度使 rm#r03725@郭昕 、 rm#xjts13483@李元忠 還朝，
以其地與之。

 rm@李泌 曰：
「 dm#dm02061@安西 、 dm#dm00860@北庭 ，
人性驍悍，
控制 dm#dm07304@西域 五十七國及十姓突厥，
又分吐蕃之勢，
使不能併兵東侵，
奈何拱手與之！

且兩鎭之人，
勢孤地遠，
盡忠竭力，
爲國家固守近二十年，
誠可哀憐。

一旦棄之以與戎狄，
彼其心必深怨 dm#dm00255@中國 ，
他日從吐蕃入寇，
如報私讎矣。

況日者吐蕃觀望不進，
陰持兩端，
大掠 dm#dm04228@武功 ，
受賂而去，
何功之有！」

衆議亦以爲然，
上遂不與。


# p 

 rm#r01719@李希烈 聞 rm@李希倩 伏誅，
忿怒，
八月，
壬寅，
遣中使至 dm#dm07086@蔡州 殺 rm#r04147@顏眞卿 。

中使曰：
「有敕。」

 rm#r04147@眞卿 再拜。

中使曰：
「今賜卿死。」

 rm#r04147@眞卿 曰：
「老臣無状，
罪當死。

不知使者幾日發 dm#dm08170@長安 ？」
使者曰：
「自 dm#dm01638@大梁 來，
非 dm#dm08170@長安 也。」

 rm#r04147@眞卿 曰：
「然則賊耳，
何謂敕邪！」

遂縊殺之。
# p 

 rm@李晟 以 dm#dm04924@涇州 倚邊，
屡害軍帥，
常爲亂根，
奏請往理不用命者，
力田積粟以攘吐蕃。

癸卯，
以 rm@晟 兼 dm#dm09004@鳳翔 、 dm#dm08458@隴右 節度等使及 dm#dm01437@四鎭 、 dm#dm00860@北庭 、 dm#dm04920@涇原 行營副元帥，
進爵 rm@西平王 。

時 rm#xjts16619@李楚琳 入朝，
 rm@晟 請與倶至 dm#dm09004@鳳翔 而斬之，
以懲逆亂。

上以新復 dm#dm08170@京師 ，
務安反仄，
不許。
# p 

先是，
上命 rm#r02462@渾瑊 、 rm#r00774@駱元光 討 rm@李懷光 軍于 dm#dm01227@同州 ，
 rm@懷光 遣其將 rm#xjts10714@徐庭光 以精卒六千軍于 dm#dm08188@長春宮 以拒之，
 rm@瑊 等數爲所敗，
不能進。

時度支用度不給，
議者多請赦 rm@懷光 ，
上不許。

 rm@李懷光 遣其妹壻 rm#xjts03661@要廷珍 守 dm#dm03544@晉州 ，
牙將 rm#xjts06976@毛朝敭 守 dm#dm08454@隰州 ，
 rm#xjts28301@鄭抗 守 dm#dm03068@慈州 ，
 rm#r04181@馬燧 皆遣人説下之。

上乃加 rm#r02462@渾瑊  dm#dm04651@河中 、 dm#dm06431@絳州 節度使，
充 dm#dm04651@河中 、 dm#dm01236@同華 、 dm#dm08327@陝虢 行營副元帥，
加 rm#r04181@馬燧  dm#dm01866@奉誠軍 、 dm#dm03533@晉 ‧ dm#dm03068@慈 ‧ dm#dm08451@隰 節度使，
充管内諸軍行營副元帥，
與 dm#dm08127@鎭國 節度使 rm#r00774@駱元光 、 dm#dm07921@鄜坊 節度使 rm#xjts00838@唐朝臣 合兵討 rm#r01775@懷光 。

# p 

初，
 rm#r02656@王武俊 急攻 rm#r01052@康日知 於 dm#dm07623@趙州 ，
 rm#r04181@馬燧 奏請詔 rm#r02656@武俊 與 rm#r01783@李抱眞 同撃 rm#r01579@朱滔 ，
以 dm#dm05013@深 、 dm#dm07617@趙 隸 rm#r02656@武俊 ，
改 rm#r01052@日知 爲 dm#dm03533@晉 、 dm#dm03068@慈 、 dm#dm08451@隰 節度使，
上從之。

 rm#r01052@日知 未至而三州降 rm#r04181@燧 ，
故上使 rm#r04181@燧 兼領之。

 rm#r04181@燧 表讓三州於 rm#r01052@日知 ，
且言因降而授，
恐後有功者，
踵以爲常，
上嘉而許之。

 rm#r04181@燧 遣使迎 rm#r01052@日知 ，
既至，
籍府庫而歸之。
# p 

甲辰，
以 dm#dm09004@鳳翔 節度使 rm#xjts16619@李楚琳 爲左金吾大將軍。
# p 

丙午，
加 rm#r02462@渾瑊  dm#dm03677@朔方 行營元帥。
# p 

 rm@李晟 至 dm#dm09004@鳳翔 ，
治殺 rm#r01266@張鎰 之罪，
斬裨將 rm#xjts01892@王斌 等十餘人。

# p 

 rm#r01579@朱滔 爲 rm#r02656@王武俊 所攻，
殆不能軍，
上表待罪。


# p 

癸未，
 rm#r04181@馬燧 將歩騎三萬攻 dm#dm06431@絳州 。

# p 

度支以 rm#r01775@李懷光 所部將士數萬與 rm#r01775@懷光 同反，
不給冬衣，
上曰：
「 dm#dm03677@朔方 軍累代忠義，
今爲 rm@懷光 所制耳，
將士何罪！」

冬，
十月，
詔：
「 dm#dm03677@朔方 及諸軍在 rm#r01775@懷光 所者，
冬衣及賞錢皆當別貯，
俟道路稍通，
即時給之。」
己亥
# p 

 rm@李勉 累表乞自貶，
辛丑，
罷 rm@勉 都統、節度使，
其檢校司徒、同平章事如故。
# p 

丙辰，
 rm#r01775@李懷光 將 rm#xjts26901@閻晏 寇 dm#dm01227@同州 ，
官軍敗于 dm#dm04627@沙苑 。

詔徵 dm#dm07812@邠州 之軍，
 rm#r04133@韓遊瓌 將甲士六千赴之。
# p 

乙丑，
 rm#r04181@馬燧 拔 dm#dm06431@絳州 ，
分兵取 dm#dm06601@聞喜 、 dm#dm06986@萬泉 、 dm#dm07185@虞郷 、 dm#dm04427@永樂 、 dm#dm05659@猗氏 。

# p 

初，
 rm#r04309@魚朝恩 既誅，
 rm#xjts00683@代宗 不復使宦官典兵。

上即位，
悉以禁兵委 rm#r02849@白志貞 ，
 rm#r02849@志貞 得罪，
上復以宦官 rm#r03034@竇文場 代之，
從幸 dm#dm02398@山南 ，
兩軍稍集。

上還 dm#dm08170@長安 ，
頗忌宿將握兵多者，
稍稍罷之。

戊辰，
以 rm#r03034@文場 監神策軍左廂兵馬使，
 rm#xjts02686@王希遷 監右廂兵馬使，
始令宦官分典禁旅。

# p 

閏月，
丙子，
以 dm#dm04920@涇原 節度使 rm#xjts24355@田希鑒 爲衞尉卿。
# p 

 rm@李晟 初至 dm#dm09004@鳳翔 ，
 rm#xjts24355@希鑒 遣使參候，
 rm@晟 謂使者曰：
「 dm#dm04924@涇州 逼近吐蕃，
萬一入寇，
州兵能獨禦之乎？
欲遣兵防援，
又未知 rm@田尚書 意。」

使者歸，
以告 rm#xjts24355@希鑒 ，
 rm#xjts24355@希鑒 果請援兵，
 rm@晟 遣腹心將 rm@彭令英 等戍 dm#dm04924@涇州 。

 rm@晟 尋託巡邊詣 dm#dm04924@涇州 ，
 rm#xjts24355@希鑒 出迎，
 rm@晟 與之竝轡而入，
道舊結歡。

 rm#xjts24355@希鑒 妻 rm@李氏 ，
以叔父事 rm@晟 ，
 rm@晟 謂之 rm#xjts24355@田郎 。

 rm@晟 命具三日食，
曰：
「巡撫畢，
即還 dm#dm09004@鳳翔 。」

 rm#xjts24355@希鑒 不復疑。

 rm@晟 置宴，
 rm#xjts24355@希鑒 與將佐倶至 rm@晟 營。

晟伏甲於外廡，
既食而飮，
 rm@彭令英 引 dm#dm04924@涇州 諸將下堂，
 rm@晟 曰：
「我與汝曹久別，
各宜自言姓名。」

於是得爲亂者 rm#xjts03699@石奇 等三十餘人，
讓之曰：
「汝曹屡爲逆亂，
殘害忠良，
固天地所不容！

」
悉引出，
斬之。

 rm#xjts24355@希鑒 尚在座，
 rm@晟 顧曰：
「 rm#xjts24355@田郎 亦不得無過，
以親知之故，
當使身首得完。」

 rm#xjts24355@希鑒 曰：
「唯。」

遂引出，
縊殺之，
幷其子 rm@萼 。

 rm@晟 入其營，
諭以誅 rm#xjts24355@希鑒 之意，
衆股栗，
無敢動者。
# p 

 rm#r01719@李希烈 遣其將 rm#xjts06719@翟崇暉 悉衆圍 dm#dm08351@陳州 ，
久之，
不克。

 rm@李澄 知 dm#dm01638@大梁 兵少，
不能制 dm#dm05229@滑州 ，
遂焚 rm#r01719@希烈 所授旌節，
誓衆歸國。

甲午，
以 rm@澄 爲 dm#dm04546@汴滑 節度使。

# p 

 dm#dm02094@宋亳 節度使 rm#r00292@劉洽 遣馬歩都虞候 rm#r00271@劉昌 與 dm#dm08458@隴右 、 dm#dm02689@幽州 行營節度使 rm#r01490@曲環 等將兵三萬救 dm#dm08351@陳州 ，
十一月，
癸卯，
敗 rm#xjts06719@翟崇暉 於州西，
斬首三萬五千級，
擒 rm#xjts06719@崇暉 以獻。

乘勝進攻 dm#dm04541@汴州 ，
 rm#r01719@李希烈 懼，
奔歸 dm#dm07086@蔡州 。

 rm#r01861@李澄 引兵趣 dm#dm04541@汴州 ，
至城北，
恇怯不敢進；
 rm#r00292@劉洽 兵至城東。

戊午，
 rm#r01719@李希烈 守將 rm#xjts24390@田懷珍 開門納之。

明日，
 rm#r01861@澄 入，
舍於 dm#dm04861@浚儀 ；
兩軍之士，
日有忿鬩。

會 rm#r01719@希烈  dm#dm07949@鄭州 守將 rm#xjts06324@孫液 降於 rm#r01861@澄 ，
 rm#r01861@澄 引兵屯 dm#dm07949@鄭州 。

詔以都統司馬 dm#dm02325@寶鼎  rm#r03265@薛 爲 dm#dm04541@汴州 刺史。

# p 

 rm@李勉 至 dm#dm08170@長安 ，
素服待罪；
議者多以「 rm@勉 失守 dm#dm01638@大梁 ，
不應尚爲相。」

 rm@李泌 言於上曰：
「 rm@李勉 公忠雅正，
而用兵非其所長。

及 dm#dm01638@大梁 不守，
將士棄妻子而從之者殆二萬人，
足以見其得衆心矣。

且 rm#r00292@劉洽 出 rm@勉 麾下，
 rm@勉 至 dm#dm06055@睢陽 ，
悉舉其衆以授之，
卒平 dm#dm01638@大梁 ，
亦 rm@勉 之功也。」

上乃命 rm@勉 復其位。

議者又言：
「 rm#r04122@韓滉 聞鑾輿在外，
聚兵脩 dm#dm06142@石頭城 ，
陰蓄異志。」

上疑之，
以問 rm@李泌 ，
對曰：
「 rm#r04122@滉 公忠清儉，
自車駕在外，
 rm#r04122@滉 貢獻不絶。

且鎭 dm#dm04494@江東 十五州，
盜賊不起，
皆 rm#r04122@滉 之力也。

所以脩 dm#dm06142@石頭城 者，
 rm#r04122@滉 見中原板蕩，
謂陛下將有 dm#dm04386@永嘉 之行，
爲迎扈之備耳。

此乃人臣忠篤之慮，
奈何更以爲罪乎！

 rm#r04122@滉 性剛嚴，
不附權貴，
故多謗毀，
願陛下察之，
臣敢保其無他。」

上曰：
「外議洶洶，
章奏如麻，
卿弗聞乎？」
對曰：
「臣固聞之。

其子 rm#r04122@皋 爲考功員外郎，
今不敢歸省其親，
正以謗語沸騰故也。」

上曰：
「其子猶懼如此，
卿奈何保之？」
對曰：
「 rm#r04122@滉 之用心，
臣知之至熟。

願上章明其無他，
乞宣示中書，
使朝衆皆知之。」

上曰：
「朕方欲用卿，
人亦何易可保！

愼勿違衆，
恐幷爲卿累也。」

 rm@泌 退，
遂上章，
請以百口保滉。

他日，
上謂 rm@泌 曰：
「卿竟上章，
已爲卿留中。

雖知卿與 rm#r04122@滉 親舊，
豈得不自愛其身乎！」

對曰：
「臣豈肯私於親舊以負陛下！

顧 rm#r04122@滉 實無異心，
臣之上章，
以爲朝廷，
非爲身也。」

上曰：
「如何其爲朝廷？」
對曰：
「今天下旱、蝗，
 dm#dm08281@關中 米斗千錢，
倉廩耗竭，
而 dm#dm04494@江東 豐稔。

願陛下早下臣章以解朝衆之惑，
面諭 rm#r04126@韓皋 使之歸覲，
令 rm#r04122@滉 感激無自疑之心，
速運糧儲，
豈非爲朝廷邪！」

上曰：
「善！

朕深諭之矣。」

即下 rm@泌 章，
令 rm#r04126@韓皋 謁告歸覲，
面賜緋衣，
諭以「卿父比有謗言，
朕今知其所以，
釋然不復信矣。」

因言：
「 dm#dm08281@關中 乏糧，
歸語卿父，
宜速致之。」

 rm#r04126@皋 至 dm#dm05367@潤州 ，
 rm#r04122@滉 感悦流涕，
即日，
自臨水濱發米百萬斛，
聽 rm#r04126@皋 留五日即還朝。

 rm#r04126@皋 別其母，
啼聲聞於外；
 rm#r04122@滉 怒，
召出，
撻之，
自送至 dm#dm04475@江 上，
冒風濤而遣之。

既而 rm#r03921@陳少遊 聞 rm#r04122@滉 貢米，
亦貢二十萬斛。

上謂 rm@李泌 曰：
「 rm#r04122@韓滉 乃能化 rm#r03921@陳少遊 貢米矣！」

對曰：
「豈惟 rm#r03921@少遊 ，
諸道將爭入貢矣！」

# p 

吏部尚書、同平章事 rm#r03243@蕭復 奉使自 dm#dm04475@江 、 dm#dm04981@淮 還，
與 rm@李勉 、 rm#xjts07612@盧翰 、 rm#r00249@劉從一 倶見上。

 rm@勉 等退，
 rm@復 獨留，
言於上曰：
「 rm#r03921@陳少遊 任兼將相，
首敗臣節，
 rm#r04056@韋皋 幕府下僚，
獨建忠義，
請以 rm#r04056@皋 代 rm#r03921@少遊 鎭 dm#dm04984@淮南 。」

上然之。

尋遣中使 rm@馬欽緒 揖 rm#r00249@劉從一 ，
附耳語而去。

諸相還閤。

 rm#r00249@從一 詣 rm#r03243@復 曰：
「 rm@欽緒 宣旨，
令 rm#r00249@從一 與公議朝來所言事，
即奏行之，
勿令 rm@李 、 rm@盧 知。

敢問何事也？」
 rm@復 曰：
「 rm@唐 、 rm@虞 黜陟，
嶽牧僉諧。

爵人於朝，
與士共之。

使 rm@李 、 rm@盧 不堪爲相，
則罷之。

既在相位，
朝廷政事，
安得不與之同議而獨隱此事乎！

此最當今之大弊，
朝來主上已有斯言，
 rm#r03243@復 已面陳其不可，
不謂聖意尚爾。

 rm#r03243@復 不惜與公奏行之，
但恐浸以成俗，
未敢以告。」

竟不以語 rm#r03243@從一 。

 rm#r03243@從一 奏之，
上愈不悦，
 rm@復 乃上表辭位，
乙丑，
罷爲左庶子。

使善惡著明
# p 

 rm#r00292@劉洽 克 dm#dm04541@汴州 ，
得李希烈起居注，云某月日， rm#r03921@陳少遊 上表歸順。 rm#r03921@少遊 聞之慙懼，
發疾，
十二月，
乙亥，
薨，
贈太尉，
賻祭如常儀。

# p 

 dm#dm04984@淮南 大將 rm#xjts01902@王韶 欲自爲留後，
令將士推己知軍事，
且欲大掠，
 rm#r04122@韓滉 遣使謂之曰：
「汝敢爲亂，
吾即日全軍渡 dm#dm04475@江 誅汝矣！」

 rm#xjts01902@韶 等懼而止。

上聞之喜，
謂 rm@李泌 曰：
「 rm#r04122@滉 不惟安 dm#dm04494@江東 ，
又能安 dm#dm04984@淮南 ，
眞大臣之器，
卿可謂知人！」

庚辰，
加 rm#r04122@滉 平章事、 dm#dm04475@江  dm#dm04981@淮 轉運使。

 rm#r04122@滉 運 dm#dm04475@江 、 dm#dm04981@淮 粟帛入貢府，
無虚月，
朝廷頼之，
使者勞問相繼，
恩遇始深矣。
# p 

 y@是歳 蝗徧遠近，
草木無遺，
惟不食稻，
大饑，
道殣相望。
