
** 麟徳
*** 麟徳元年
# year 0664
# p 

春，
正月，
甲子，
改 dm#dm08550@雲中都護府 爲 dm#dm01396@單于大都護府 ，
以 rm#r01797@殷王旭輪  dm#dm01394@單于 大都護。

# p 

初，
 rm#r02009@李靖 破突厥，
遷三百帳于 dm#dm08543@雲中城 ，
 rm#?@阿史徳氏 爲之長。

至是，
部落漸衆，
 rm@阿史徳氏 詣闕，
請如胡法立親王爲可汗以統之。

上召見，
謂曰：
「今之可汗，
古之單于也。」

故更爲 dm#dm01400@單于都護府 ，
而使 rm#?@殷王 遙領之。
# p 

二月，
戊子，
上行幸 dm#dm06978@萬年宮 。

# p 

夏，
四月，
壬子，
 dm#dm00029@衞州 刺史 rm#r03674@道孝王元慶 薨。
# p 

丙午，
 dm#dm08950@魏州 刺史 rm#r03163@郇公孝協 坐贓，
賜死。

司宗卿 rm#r03975@隴西王博乂 奏 rm#r03163@孝協 父 rm#r03868@叔良 死王事，
 rm#r03163@孝協 無兄弟，
恐絶嗣。

上曰：
「畫一之法，
不以親疏異制，
苟害百姓，
雖皇太子亦所不赦。

 rm#r03163@孝協 有一子，
何憂乏祀乎！」

 rm#r03163@孝協 竟自盡於第。


# p 

五月，
戊申朔，
 dm#dm07730@遂州 刺史 rm#r00363@許悼王孝 薨。

# p 

乙卯，
於 dm#dm03448@昆明 之 dm#dm02870@弄棟川 置 dm#dm01900@姚州都督府 。

# p 

秋，
七月，
丁未朔，
詔以 y@三年正月 有事於 dm#dm02430@岱宗 。
# p 

八月，
丙子，
車駕還 dm#dm08170@京師 ，
幸舊宅，
留七日；
壬午，
還 dm#dm07066@蓬莱宮 。
# p 

丁亥，
以司列太常伯 rm#r00300@劉祥道 兼右相，
大司憲 rm#r03030@竇徳玄 爲司元太常伯、檢校左相。

# p 

冬，
十月，
庚辰，
檢校 dm#dm05582@熊津 都督 rm#r00192@劉仁軌 上言：
「臣伏覩所存戍兵，
疲羸者多，
勇健者少，
衣服貧敝，
唯思西歸，
無心展效。

臣問以『往在海西，
見百姓人人應募，
爭欲從軍，
或請自辦衣糧，
謂之義征，
何爲今日士卒如此？』
咸言：
『今日官府與曩時不同，
人心亦殊。

曩時東西征役，
身沒王事，
竝蒙敕使弔祭，
追贈官爵，
或以死者官爵囘授子弟，
凡渡 dm#dm07776@遼海 者，
皆賜勳一轉。

自 y@顯慶五年 以來，
征人屡經渡海，
官不記録，
其死者亦無人誰何。

州縣毎發百姓爲兵，
其壯而富者，
行錢參逐，
皆亡匿得免；
貧者身雖老弱，
被發即行。

頃者破 dm#dm05948@百濟 及 dm#dm02614@平壤 苦戰，
當時將帥號令，
許以勳賞，
無所不至；
及達西岸，
惟聞枷鎖推禁，
奪賜破勳，
州縣追呼，
無以自存，
公私困弊，
不可悉言。

以是昨發海西之日已有逃亡自殘者，
非獨至海外而然也。

又，
本因征役勳級以爲榮寵；
而比年出征，
皆使勳官挽引，
勞苦與白丁無殊，
百姓不願從軍，
率皆由此。』

臣又問：
『曩日士卒留鎭五年，
尚得支濟，
今爾等始經一年，
何爲如此單露？』
咸言：
『初發家日，
惟令備一年資裝；
今已二年，
未有還期。』

臣檢校軍士所留衣，
今冬僅可充事，
來秋以往，
全無準擬。

陛下留其海外，
欲殄滅 dm#dm08934@高麗 、 dm#dm05948@百濟 ，
 dm#dm08934@高麗 舊相黨援，
 dm#dm00605@倭 人雖遠，
亦共爲影響，
若無鎭兵，
還成一國。

今既資戍守，
又置屯田，
所藉士卒同心同徳，
而衆有此議，
何望成功！

自非有所更張，
厚加慰勞，
明賞重罰以起士心，
若止如今日以前處置，
恐師衆疲老，
立效無日。

逆耳之事，
或無人爲陛下盡言，
故臣披露肝膽，
昧死奏陳。

」
# p 

上深納其言，
遣右威衞將軍 rm#r06156@劉仁願 將兵渡海以代舊鎭之兵，
仍敕 rm#r00192@仁軌 倶還。

 rm#r00192@仁軌 謂 rm#r06156@仁願 曰：
「國家懸軍海外，
欲以經略 dm#dm08934@高麗 ，
其事非易。

今收穫未畢，
而軍吏與士卒一時代去，
軍將又歸。

夷人新服，
衆心未安，
必將生變。

不如且留舊兵，
漸令收穫，
辦具資糧，
節級遣還；
軍將且留鎭撫，
未可還也。」

 rm#r06156@仁願 曰：
「吾前還海西，
大遭讒謗，
云吾多留兵衆，
謀據海東，
幾不免禍。

今日唯知准敕，
豈敢有所爲！」

 rm#r00192@仁軌 曰：
「人臣苟利於國，
知無不爲，
豈恤其私！

」
乃上表陳便宜，
自請留鎭海東，
上從之。

仍以 rm@扶餘隆 爲 dm#dm05582@熊津 都尉，
使招輯其餘衆。
# p 

初，
 rm#r02293@武后 能屈身忍辱，
奉順上意，
故上排羣議而立之；
及得志，
專作威福，
上欲有所爲，
動爲后所制，
上不勝其忿。

有道士 rm#r05946@郭行眞 ，
出入禁中，
嘗爲厭勝之術，
宦者 rm#r05601@王伏勝 發之。

上大怒，
密召西臺侍郎、同東西臺三品 rm#r00022@上官儀 議之。

 rm#r00022@儀 因言：
「皇后專恣，
海内所不與，
請廢之。」

上意亦以爲然，
即命 rm#r00022@儀 草詔。
# p 

左右奔告于后，
后遽詣上自訴。

詔草猶在上所，
上羞縮不忍，
復待之如初；
猶恐后怨怒，
因紿之曰：
「我初無此心，
皆 rm#r00022@上官儀 教我。」

 rm#r00022@儀 先爲 rm#r02551@陳王 諮議，
與 rm#r05601@王伏勝 倶事故太子 rm#r02551@忠 ，
后於是使 rm#r03511@許敬宗 誣奏 rm#r00022@儀 、 rm#r05601@伏勝 與 rm#r02551@忠 謀大逆。

十二月，
丙戌，
 rm#r00022@儀 下獄，
與其子 rm#r00025@庭芝 、 rm#r05601@王伏勝 皆死，
籍沒其家。

戊子，
賜 rm#r02551@忠 死于流所。

右相 rm#r00300@劉祥道 坐與 rm#r00022@儀 善，
罷政事，
爲司禮太常伯，
左肅機 rm#r03800@鄭欽泰 等朝士流貶者甚衆，
皆坐與 rm#r00022@儀 交通故也。

# p 

自是上毎視事，
則后垂簾於後，
政無大小，
皆與聞之。

天下大權，
悉歸中宮，
黜陟、殺生，
決於其口，
天子拱手而已，
中外謂之二聖。

# p 

太子右中護‧檢校西臺侍郎 rm#r02262@樂彦瑋 、西臺侍郎 rm#r00736@孫處約 竝同東西臺三品。
*** 二年
# year 0665
# p 

春，
正月，
丁卯，
吐蕃遣使入見，
請復與吐谷渾和親，
仍求 dm#dm07587@赤水 地畜牧，
上不許。
# p 

二月，
壬午，
車駕發 dm#dm08170@京師 ；
丁酉，
至 dm#dm01202@合璧宮 。
# p 

上語及 rm#rt0779@隋煬帝 ，
謂侍臣曰：
「 rm#rt0779@煬帝 拒諫而亡，
朕常以爲戒，
虚心求諫；
而竟無諫者，
何也？」
 rm#r01299@李勣 對曰：
「陛下所爲盡善，
羣臣無得而諫。」


# p 

三月，
甲寅，
以兼司戎太常伯 rm#r06166@姜恪 同東西臺三品。

 rm#r06166@恪 ，
 rm#r00642@寶誼 之子也。

# p 

辛未，
 dm#dm03880@東都  dm#dm00347@乾元殿 成。

閏月，
壬申朔，
車駕至 dm#dm03880@東都 。
# p 

疏勒弓月引吐蕃侵于闐，
敕 dm#dm07317@西州 都督 rm#r05227@崔知辯 、左武衞將軍 rm#r05340@曹繼叔 將兵救之。

# p 

夏，
四月，
戊辰，
左侍極 rm#r03951@陸敦信 檢校右相；
西臺侍郎 rm#r00736@孫處約 、太子右中護‧檢校西臺侍郎 rm#r02262@樂彦瑋 竝罷政事。

# p 

祕閣郎中 rm#r01847@李淳風 以 rm#r00139@傅仁均 戊寅暦推歩浸疏，
乃増損 rm#r05082@劉焯 皇極暦，
更撰麟徳暦；
五月，
辛卯，
行之。

# p 

秋，
七月，
己丑，
 dm#dm00663@兗州 都督 rm#r03764@鄧康王元裕 薨。
# p 

上命 dm#dm05582@熊津 都尉 rm@扶餘隆 與 rm@新羅王法敏 釋去舊怨；
八月，
壬子，
同盟于 dm#dm05583@熊津城 。

 rm#r00192@劉仁軌 以 dm#dm03383@新羅 、 dm#dm05948@百濟 、 dm#dm06593@耽羅 、 dm#dm00605@倭國 使者浮海西還，
會祠 dm#dm04750@泰山 ，
 dm#dm08934@高麗 亦遣太子 rm@福男 來侍祠。
# p 

冬，
十月，
癸丑，
皇后表稱：
「封禪舊儀，
祭皇地祇，
太后昭配，
而令公卿行事，
禮有未安，
至日，
妾請帥内外命婦奠獻。」

詔：
「禪社首以皇后爲亞獻，
 rm@越國太𡚱燕氏 爲終獻。」

壬戌，
詔：
「封禪壇所設上帝、后土位，
先用藁秸、陶匏等，
竝宜改用茵褥、罍爵，
其諸郊祀亦宜準此。」

又詔：
「自今郊廟享宴，
文舞用功成慶善之樂，
武舞用神功破陳之樂。」


# p 

丙寅，
上發 dm#dm03880@東都 ，
從駕文武儀仗，
數百里不絶。

列營置幕，
彌亙原野。

東自 dm#dm08934@高麗 ，
西至 dm#dm04736@波斯 、 dm#dm05549@烏長 諸國，
朝會者，
各帥其屬扈從，
穹廬毳幕，
牛羊駝馬，
填咽道路。

時比歳豐稔，
米斗至五錢，
麥、豆不列于市。
# p 

十一月，
戊子，
上至 dm#dm05459@濮陽 ，
 rm#r03030@竇徳玄 騎從。

上問：
「 dm#dm05459@濮陽 謂之 dm#dm02589@帝丘 ，
何也？」
 rm#r03030@徳玄 不能對。

 rm#r03511@許敬宗 自後躍馬而前曰：
「昔 rm#rt0003@顓頊 居此，
故謂之 dm#dm02589@帝丘 。」

上稱善。

 rm#r03511@敬宗 退，
謂人曰：
「大臣不可以無學；
吾見 rm#r03030@徳玄 不能對，
心實羞之。」

 rm#r03030@徳玄 聞之曰：
「人各有能有不能，
吾不強對以所不知，
此吾所能也。」

 rm#r01299@李勣 曰：
「 rm#r03511@敬宗 多聞，
信美矣；
 rm#r03030@徳玄 之言亦善也。」

# p 

 dm#dm01523@壽張 人 rm#r01114@張公藝 九世同居，
 dyn#ch171@齊 、 dyn#ch174@隋 、 dyn#ch100@唐 皆旌表其門。

上過 dm#dm01523@壽張 ，
幸其宅，
問所以能共居之故，
 rm#r01114@公藝 書「忍」
字百餘以進。

上善之，
賜以縑帛。
# p 

十二月，
丙午，
車駕至 dm#dm09208@齊州 ，
留十日。

丙辰，
發 dm#dm08617@靈巖頓 ，
至 dm#dm04750@泰山 下，
有司於山南爲圓壇，
山上爲登封壇，
 dm#dm06194@社首山 上爲降禪方壇。
** 乾封
*** 乾封元年
# year 0666
# p 

春，
正月，
戊辰朔，
上祀昊天上帝于 dm#dm04750@泰山 南。

己巳，
登 dm#dm04750@泰山 ，
封玉牒，
上帝册藏以玉匱，
配帝册藏以金匱，
皆纏以金繩，
封以金泥，
印以玉璽，
藏以石䃭。

庚午，
降禪于 dm#dm06193@社首 ，
祭皇地祇。

上初獻畢，
執事者皆趨下。

宦者執帷，
皇后升壇亞獻，
帷帟皆以錦繡爲之；
酌酒，
實俎豆，
登歌，
皆用宮人。

壬申，
上御朝覲壇，
受朝賀；
赦天下，
改元。

文武官三品已上賜爵一等，
四品已下加一階。

先是階無泛加，
皆以勞考敍，
進至五品三品，
仍奏取進止，
至是始有泛階；
比及末年，
服緋者滿朝矣。


# p 

時大赦，
惟長流人不聽還，
 rm#r01922@李義府 憂憤發病卒。

自 rm#r01922@義府 流竄，
朝士日憂其復入，
及聞其卒，
衆心乃安。

# p 

丙戌，
車駕發 dm#dm04750@泰山 ；
辛卯，
至 dm#dm03627@曲阜 ，
贈 rm#r06150@孔子 太師，
以少牢致祭。

癸未，
至 dm#dm00454@亳州 ，
謁 dm#dm06585@老君廟 ，
上尊號曰 rm#ry0032@太上玄元皇帝 。

丁丑，
至 dm#dm03880@東都 ，
留六日；
甲申，
幸 dm#dm01202@合璧宮 ；
夏，
四月，
甲辰，
至 dm#dm08170@京師 ，
謁太廟。
# p 

庚戌，
左侍極兼檢校右相 rm#r03951@陸敦信 以老疾辭職，
拜大司成，
兼左侍極，
罷政事。

# p 

五月，
庚寅，
鑄 y@乾封 泉寶錢，
一當十，
俟期年盡廢舊錢。

# p 

 dm#dm08934@高麗  rm#r05565@泉蓋蘇文 卒，
長子 rm#r02435@男生 代爲莫離支，
初知國政，
出巡諸城，
使其弟 rm#r05563@男建 、 rm#r05564@男産 知留後事。

或謂二弟曰：
「 rm#r02435@男生 惡二弟之逼，
意欲除之，
不如先爲計。」

二弟初未之信。

又有告 rm#r02435@男生 者曰：
「二弟恐兄還奪其權，
欲拒兄不納。」

 rm#r02435@男生 潛遣所親往 dm#dm02614@平壤 伺之，
二弟收掩，
得之，
乃以王命召 rm#r02435@男生 。

 rm#r02435@男生 懼，
不敢歸；
 rm#r05563@男建 自爲莫離支，
發兵討之。

 rm#r02435@男生 走保別城，
使其子 rm#r02434@獻誠 詣闕求救。

六月，
壬寅，
以右驍衞大將軍 rm#r00611@契苾何力 爲 rm@遼東道 安撫大使，
將兵救之；
以 rm#r02434@獻誠 爲右武衞將軍，
使爲郷導。

又以右金吾衞將軍 rm#r04350@龐同善 、 dm#dm05611@營州 都督 rm#r06278@高侃 爲行軍總管，
同討 dm#dm08934@高麗 。
# p 

秋，
七月，
乙丑朔，
徙 rm#r01797@殷王旭輪 爲 rm#r01797@豫王 。
# p 

以大司憲兼檢校太子左中護 rm#r00192@劉仁軌 爲右相。
# p 

初，
 rm#r00192@仁軌 爲給事中，
按 rm#r05681@畢正義 事，
 rm#r01922@李義府 怨之，
出爲 dm#dm08665@青州 刺史。

會討 dm#dm05948@百濟 ，
 rm#r00192@仁軌 當浮海運糧，
時未可行，
 rm#r01922@義府 督之，
遭風失船，
丁夫溺死甚衆，
命監察御史 rm#r06250@袁異式 往鞫之。

 rm#r01922@義府 謂 rm#r06250@異式 曰：
「君能辦事，
不憂無官。」

 rm#r06250@異式 至，
謂仁軌曰：
「君與朝廷何人爲讎，
宜早自爲計。」

 rm#r00192@仁軌 曰：
「 rm#r00192@仁軌 當官不職，
國有常刑，
公以法斃之，
無所逃命。

若使遽自引決以快讎人，
竊所未甘！」

乃具獄以聞。

 rm#r06250@異式 將行，
仍自掣其鎖。

獄上，
 rm#r01922@義府 言於上曰：
「不斬 rm#r00192@仁軌 ，
無以謝百姓。」

舍人 rm#r02471@源直心 曰：
「海風暴起，
非人力所及。」

上乃命除名，
以白衣從軍自效。

 rm#r01922@義府 又諷 rm#r06156@劉仁願 使害之，
 rm#r06156@仁願 不忍殺。

及爲大司憲，
 rm#r06250@異式 懼，
不自安，
 rm#r00192@仁軌 瀝觴告之曰：
「 rm#r00192@仁軌 若念疇昔之事，
有如此觴！」

 rm#r00192@仁軌 既知政事，
 rm#r06250@異式 尋遷詹事丞；
時論紛然；
 rm#r00192@仁軌 聞之，
遽薦爲司元大夫。

監察御史 rm#r02048@杜易簡 謂人曰：
「斯所謂矯枉過正矣！」


# p 

八月，
辛丑，
司元太常伯兼檢校左相 rm#r03030@竇徳玄 薨。
# p 

初，
 rm#r02300@武士彠 娶 rm#xjts22367@相里氏 ，
生 rm#ry0002@元慶 、 rm#r05538@元爽 ；
又娶 rm#xjts22959@楊氏 ，
生三女，
長適 dm#dm07614@越王府 法曹 rm#r05879@賀蘭越石 ，
次皇后，
次適 rm#r05938@郭孝愼 。

 rm#r02300@士彠 卒，
 rm#ry0002@元慶 、 rm#r05538@元爽 及 rm#r02300@士彠 兄子 rm#xjts06541@惟良 、 rm#xjts06496@懷運 皆不禮於 rm#xjts22959@楊氏 ，
 rm#xjts22959@楊氏 深銜之。

 rm#r05879@越石 、 rm#r05938@孝愼 及 rm#r05938@孝愼 妻竝早卒，
 rm#r05879@越石 妻生 rm#r03566@敏之 及一女而寡。

后既立，
 rm#xjts22959@楊氏 號 rm#xjts22959@榮國夫人 ，
 rm#r05879@越石 妻號 rm#xjts06575@韓國夫人 ，
 rm#xjts06541@惟良 自 dm#dm01884@始州 長史超遷司衞少卿，
 rm#xjts06496@懷運 自 dm#dm05480@瀛州 長史遷 dm#dm04961@淄州 刺史，
 rm#ry0002@元慶 自右衞郎將爲宗正少卿，
 rm#r05538@元爽 自 dm#dm02008@安州 戸曹累遷少府少監。

 rm#xjts22959@榮國夫人 嘗置酒，
謂 rm#xjts06541@惟良 等曰：
「頗憶疇昔之事乎？
今日之榮貴復何如？」
對曰：
「 rm#xjts06541@惟良 等幸以功臣子弟，
早登宦籍，
揣分量才，
不求貴達，
豈意以皇后之故，
曲荷朝恩，
夙夜憂懼，
不爲榮也。」

 rm#xjts22959@榮國 不悦。

皇后乃上疏，
請出 rm#xjts06541@惟良 等爲遠州刺史，
外示謙抑，
實惡之也。

於是以 rm#xjts06541@惟良 檢校 dm#dm01884@始州 刺史，
 rm#ry0002@元慶 爲 dm#dm09241@龍州 刺史，
 rm#r05538@元爽 爲 dm#dm05450@濠州 刺史。

 rm#ry0002@元慶 至州，
以憂卒。

 rm#r05538@元爽 坐事流 dm#dm03227@振州 而死。

# p 

 rm#xjts06575@韓國夫人 及其女以后故出入禁中，
皆得幸於上。

 rm#xjts06575@韓國 尋卒，
其女賜號 rm#xjts22339@魏國夫人 。

上欲以 rm#xjts22339@魏國 爲内職，
心難后未決，
后惡之。

會 rm#xjts06541@惟良 、 rm#xjts06496@懷運 與諸州刺史詣 dm#dm04750@泰山 朝覲，
從至 dm#dm08170@京師 ，
 rm#xjts06541@惟良 等獻食。

后密置毒醢中，
使 rm#xjts22339@魏國 食之，
暴卒，
因歸罪於 rm#xjts06541@惟良 、 rm#xjts06496@懷運 ，
丁未，
誅之，
改其姓爲 rm#no@蝮氏 。

 rm#xjts06496@懷運 兄 rm#xjts06586@懷亮 早卒，
其妻 rm@善氏 尤不禮於 rm#xjts22959@榮國 ，
坐 rm#xjts06541@惟良 等沒入掖庭，
 rm#xjts22959@榮國 令后以他事朿棘鞭之，
肉盡見骨而死。
# p 

九月，
 rm#r04350@龐同善 大破 dm#dm08934@高麗 兵，
 rm#r02435@泉男生 帥衆與 rm#r04350@同善 合。

詔以 rm#r02435@男生 爲特進、 dm#dm07770@遼東 大都督，
兼 dm#dm02616@平壤道 安撫大使，
封 rm#r02435@玄菟郡公 。

# p 

戊子，
金紫光祿大夫致仕 rm#r00300@廣平宣公劉祥道 薨，
子 rm#r00339@齊賢 嗣。

 rm#r00339@齊賢 爲人方正，
上甚重之，
爲 dm#dm03544@晉州 司馬。

將軍 rm#xjts23921@史興宗 嘗從上獵苑中，
因言 dm#dm03544@晉州 産佳鷂，
 rm#r00339@劉齊賢 今爲司馬，
請使捕之。

上曰：
「 rm#r00339@劉齊賢 豈捕鷂者邪！

卿何以此待之！」

# p 

冬，
十二月，
己酉，
以 rm#r01299@李勣 爲 dm#dm07773@遼東道 行軍大總管，
以司列少常伯 dm#dm02081@安陸  rm#r03702@郝處俊 副之，
以撃 dm#dm08934@高麗 。

 rm#r04350@龐同善 、 rm#r00611@契苾何力 竝爲 dm#dm07773@遼東道 行軍副大總管兼安撫大使如故；
其水陸諸軍總管幷運糧使 rm#r05733@竇義積 、 rm#r05589@獨孤卿雲 、 rm#r03720@郭待封 等，
竝受 rm#r01299@勣 處分。

 dm#dm04656@河北 諸州租賦悉詣 dm#dm07770@遼東 給軍用。

 rm#r03720@待封 ，
 rm#r03716@孝恪 之子也。
兼安撫大使
# p 

 rm#r01299@勣 欲與其壻 dm#dm00427@京兆  rm#r05448@杜懷恭 偕行，
以求勳效。

 rm#r05448@懷恭 辭以貧，
 rm#r01299@勣 贍之；
復辭以無奴馬，
又贍之。

 rm#r05448@懷恭 辭窮，
乃亡匿 dm#dm02422@岐陽 山中，
謂人曰：
「公欲以我立法耳。」

 rm#r01299@勣 聞之，
流涕曰：
「 rm#r05455@杜郎 疏放，
此或有之。」

乃止。

*** 二年
# year 0667
# p 

春，
正月，
上耕藉田，
有司進耒耜，
加以彫飾。

上曰：
「耒耜農夫所執，
豈宜如此之麗！」

命易之。

既而耕之，
九推乃止。

# p 

自行 y@乾封 泉寶錢，
穀帛踊貴，
商賈不行；
癸未，
詔罷之。
# p 

二月，
丁酉，
 rm#r03361@涪陵悼王愔 薨。

# p 

辛丑，
復以 dm#dm06978@萬年宮 爲 dm#dm00325@九成宮 。

# p 

生羌十二州爲吐蕃所破，
三月，
戊寅，
悉罷之。
# p 

上屡責侍臣不進賢，
衆莫敢對。

司列少常伯 rm#r01696@李安期 對曰：
「天下未嘗無賢，
亦非羣臣敢蔽賢也。

比來公卿有所薦引，
爲讒者已指爲朋黨，
滯淹者未獲伸而在位者先獲罪，
是以各務杜口耳！

陛下果推至誠以待之，
其誰不願舉所知！

此在陛下，
非在羣臣也。」

上深以爲然。

 rm#r01696@安期 ，
 rm#r01886@百藥 之子也。

# p 

夏，
四月，
乙卯，
西臺侍郎 rm#r02177@楊弘武 、 rm#r01375@戴至徳 、正諫大夫兼東臺侍郎 rm#r01696@李安期 、東臺舍人 dm#dm03470@昌樂  rm#r01169@張文瓘 、司列少常伯兼正諫大夫 dm#dm04656@河北  rm#r03601@趙仁本 竝同東西臺三品。

 rm#r02177@弘武 ，
 rm#r03595@素 之弟子；
 rm#r01375@至徳 ，
 rm#r01373@冑 之兄子也。

時造 dm#dm07065@蓬莱 、 dm#dm00199@上陽 、 dm#dm01202@合璧 等宮，
頻征伐四夷，

                     廐馬萬匹，
倉庫漸虚，
 rm#r01169@張文瓘 諫曰：
「 dyn#ch174@隋 鑒不遠，
願勿使百姓生怨。」

上納其言，
減廐馬數千匹。
# p 

秋，
八月，
己丑朔，
日有食之。
# p 

辛亥，
東臺侍郎同東西臺三品 rm#r01696@李安期 出爲 dm#dm06884@荊州 長史。

# p 

九月，
庚申，
上以久疾，
命太子 rm#r00688@弘 監國。

# p 

辛未，
 rm#r01299@李勣 拔 dm#dm08934@高麗 之 dm#dm03332@新城 ，
使 rm#r00611@契苾何力 守之。

 rm#r01299@勣 初度 dm#dm07763@遼 ，
謂諸將曰：
「 dm#dm03332@新城 ，
 dm#dm08934@高麗 西邊要害，
不先得之，
餘城未易取也。」

遂攻之，
城人 rm#r05234@師夫仇 等縛城主開門降。

 rm#r01299@勣 引兵進撃，
一十六城皆下之。
# p 

 rm#r04350@龐同善 、 rm#r06278@高侃 尚在 dm#dm03332@新城 ，
 rm#r05563@泉男建 遣兵襲其營，
左武衞將軍 rm#r03268@薛仁貴 撃破之。

 rm#r06278@侃 進至 dm#dm08022@金山 ，
與 dm#dm08934@高麗 戰，
不利，
高麗乘勝逐北，
 rm#r03268@仁貴 引兵横撃，
大破之，
斬首五萬餘級，
拔 dm#dm01043@南蘇 、 dm#dm03729@木底 、 dm#dm07047@蒼巖 三城，
與 rm#r02435@泉男生 軍合。
# p 

 rm#r03720@郭待封 以水軍自別道趣 dm#dm02614@平壤 ，
 rm#r01299@勣 遣別將 rm#r06084@馮師本 載糧仗以資之。

 rm#r06084@師本 船破，
失期，
 rm#r03720@待封 軍中飢窘，
欲作書與 rm#r01299@勣 ，
恐爲虜所得，
知其虚實，
乃作離合詩以與 rm#r01299@勣 。

 rm#r01299@勣 怒曰：
「軍事方急，
何以詩爲？
必斬之！」

行軍管記通事舍人 rm#r00162@元萬頃 爲釋其義，
 rm#r01299@勣 乃更遣糧仗赴之。河南
# p 

 rm#r00162@萬頃 作檄高麗文曰，不知守 dm#dm09021@鴨緑 之險。 rm#r05563@泉男建 報曰：
「謹聞命矣！」

即移兵據 dm#dm09023@鴨緑津  dyn#ch100@唐 兵不得渡。

上聞之，
流 rm#r00162@萬頃 於 dm#dm02527@嶺南 。
# p 

 rm#r03702@郝處俊 在 dm#dm08934@高麗 城下，
未及成列，
 dm#dm08934@高麗 奄至，
軍中大駭，
 rm#r03702@處俊 據胡床，
方食乾糒，
潛簡精鋭，
撃敗之，
將士服其膽略。
# p 

冬，
十二月，
甲午，
詔：
「自今祀昊天上帝、五帝、皇地祇、神州地祇，
竝以 rm#r04258@高祖 、 rm#r01602@太宗 配，
仍合祀昊天上帝、五帝於明堂。」


# p 

是歳，
 dm#dm04888@海南  dm#dm05666@獠 陷 dm#dm05765@瓊州 。

*** 三年
# year 0668
# p 

春，
正月，
壬子，
以右相 rm#r00192@劉仁軌 爲 rm#?@遼東道 副大總管。
# p 

二月，
壬午，
 rm#r01299@李勣 等拔 dm#dm08934@高麗  dm#dm03181@扶餘城 。

 rm#r03268@薛仁貴 既破 dm#dm08934@高麗 於 dm#dm08022@金山 ，
乘勝將三千人將攻 dm#dm03181@扶餘城 ，
諸將以其兵少，
止之。

 rm#r03268@仁貴 曰：
「兵不在多，
顧用之何如耳。」

遂爲前鋒以進，
與 dm#dm08934@高麗 戰，
大破之，
殺獲萬餘人，
遂拔 dm#dm03181@扶餘城 。

 dm#dm03182@扶餘川 中四十餘城皆望風請服。
# p 

侍御史 dm#dm04788@洛陽  rm#r05889@賈言忠 奉使自 dm#dm07770@遼東 還，
上問以軍事，
 rm#r05889@言忠 對曰：
「 dm#dm08934@高麗 必平。」

上曰：
「卿何以知之？」
對曰：
「 dyn#ch174@隋  rm#r02546@煬帝 東征而不克者，
人心離怨故也；
先帝東征而不克者，
 dm#dm08934@高麗 未有釁也。

今 rm#r06114@高藏 微弱，
權臣命，
 rm#r05780@蓋蘇文 死，
 rm@男建 兄弟内相攻奪，
 rm#r02435@男生 傾心内附，
爲我郷導，
彼之情僞，
靡不知之。

以陛下明聖，
國家富強，
將士盡力，
以乘 dm#dm08934@高麗 之亂，
其勢必克，
不俟再舉矣。

且 dm#dm08934@高麗 連年饑饉，
妖異屡降，
人心危駭，
其亡可翹足待也。」

上又問：
「 dm#dm07770@遼東 諸將孰賢？」
對曰：
「 rm#r03268@薛仁貴 勇冠三軍；
 rm@龐同善 雖不善鬬，
而持軍嚴整；
 rm#r06278@高侃 勤儉自處，
忠果有謀；
 rm#r00611@契苾何力 沈毅能斷，
雖頗忌前，
而有統御之才；
然夙夜小心，
忘身憂國，
皆莫及 rm#r01299@李勣 也。」

上深然其言。
# p 

 rm#r05563@泉男建 復遣兵五萬人救 dm#dm03181@扶餘城 ，
與 rm#r01299@李勣 等遇於 dm#dm07113@薛賀水 ，
合戰，
大破之，
斬獲三萬餘人，
進攻 dm#dm01681@大行城 ，
拔之。


** 總章
*** 總章元年
# year 0668
# p 

朝廷議明堂制度略定，
三月，
庚寅，
赦天下，
改元。
# p 

戊寅，
上幸 dm#dm00325@九成宮 。
# p 

夏，
四月，
丙辰，
彗星見于五車。

上避正殿，
減常膳，
撤樂。

 rm#r03511@許敬宗 等奏請復常，
曰：
「彗見東北，
 dm#dm08934@高麗 將滅之兆也。」

上曰：
「朕之不徳，
謫見于天，
豈可歸咎小夷！

且 dm#dm08934@高麗 百姓，
亦朕之百姓也。」

不許。

戊辰，
彗星滅。
# p 

辛巳，
西臺侍郎、同東西臺三品 rm#r02177@楊弘武 薨。
# p 

八月，
辛酉，
 dm#dm00927@卑列道 行軍總管、右威衞將軍 rm#r06156@劉仁願 坐征 dm#dm08934@高麗 逗留，
流 dm#dm01898@姚州 。
# p 

癸酉，
車駕還 dm#dm08170@京師 。
# p 

九月，
癸巳，
 rm#r01299@李勣 拔 dm#dm02614@平壤 。

 rm#r01299@勣 既克 dm#dm01681@大行城 ，
諸軍出他道者皆與 rm#r01299@勣 會，
進至 dm#dm09021@鴨緑 柵，
 dm#dm08934@高麗 發兵拒戰，
 rm#r01299@勣 等奮撃，
大破之，
追奔二百餘里，
拔 dm#dm07666@辱夷城 ，
諸城遁逃及降者相繼。

 rm#r00611@契苾何力 先引兵至 dm#dm02614@平壤 城下，
 rm#r01299@勣 軍繼之，
圍 dm#dm02614@平壤 月餘，
 rm@高麗王藏 遣 rm#r05564@泉男産 帥首領九十八人，
持白幡詣 rm#r01299@勣 降，
 rm#r01299@勣 以禮接之。

 rm#r05563@泉男建 猶閉門拒守，
頻遣兵出戰，
皆敗。

 rm#r05563@男建 以軍事委僧 rm#xjts06916@信誠 ，
 rm#xjts06916@信誠 密遣人詣 rm#r01299@勣 ，
請爲内應。

後五日，
 rm#xjts06916@信誠 開門，
 rm#r01299@勣 縱兵登城鼓譟，
焚城四月，
 rm#r05563@男建 自刺，
不死，
遂擒之。

 dm#dm08934@高麗 悉平。
# p 

冬，
十月，
戊午，
以 dm#dm05542@烏荼國 婆羅門 rm#r05713@盧迦逸多 爲懷化大將軍。

 rm#r05713@逸多 自言能合不死藥，
上將餌之。

東臺侍郎 rm#r03702@郝處俊 諫曰：
「脩短有命，
非藥可延。

 y@貞觀 之末，
先帝服 rm@那羅邇娑婆寐 藥，
竟無效；
大漸之際，
名醫不知所爲，
議者歸罪 rm@娑婆寐 ，
將加顯戮，
恐取笑戎狄而止。

前鑒不遠，
願陛下深察。」

上乃止。
# p 

 rm#r01299@李勣 將至，
上命先以 rm#r06114@高藏 等獻于 dm#dm03528@昭陵 ，
具軍容，
奏凱歌，
入 dm#dm08170@京師 ，
獻于太廟。

十二月，
丁巳，
上受俘于 dm#dm01259@含元殿 。

以 rm#r06114@高藏 政非己出，
赦以爲司平太常伯，
員外，
同正。

以 rm#r05564@泉男産 爲司宰少卿，
僧 rm#xjts06916@信誠 爲銀青光祿大夫，
 rm#r02435@泉男生 爲右衞大將軍。

 rm#r01299@李勣 以下，
封賞有差。

 rm#r05563@泉男建 流 dm#dm09182@黔中 ，
 dm#dm03183@扶餘豐 流 dm#dm02525@嶺  dm#dm00933@南 。

分 dm#dm08934@高麗 五部、百七十六城、六十九萬餘戸，
爲九都督府，
四十二州，
百縣，
置 dm#dm02035@安東都護府 於 dm#dm02614@平壤 以統之，
擢其酋帥有功者爲都督、刺史、縣令，
與 dm#dm06927@華 人參理。

以右威衞大將軍 rm#r03268@薛仁貴 檢校 dm#dm02032@安東 都護，
總兵二萬人以鎭撫之。
# p 

丁卯，
上祀南郊，
告平 dm#dm08934@高麗 ，
以 rm#r01299@李勣 爲亞獻。

己巳，
謁太廟。
# p 

 dm#dm05106@渭南 尉 rm#r00244@劉延祐 ，
弱冠登進士第，
政事爲畿縣最。

 rm#r01299@李勣 謂之曰：
「足下春秋甫爾，
遽大名，
宜稍自貶抑，
無爲獨出人右也。」


# p 

時有敕，
征 dm#dm07763@遼 軍士逃亡，
限内不首及首而更逃者，
身斬，
妻子籍沒。

太子上表，
以爲：
「如此之比，
其數至多：
或遇病不及隊伍，
怖懼而逃；
或因樵採爲賊所掠；
或渡海漂沒；
或深入賊庭，
爲所傷殺。

軍法嚴重，
同隊恐幷獲罪，
即舉以爲逃，
軍旅之中，
不暇勘當，
直據隊司通状關移所屬，
妻子沒官，
情實可哀。

書曰：
『與其殺不辜，
寧失不經。』

伏願逃亡之家，
免其配沒。」

從之。
# p 

甲戌，
司戎太常伯 rm#r06166@姜恪 兼檢校左相，
司平太常伯 rm#r03889@閻立本 守右相。
# p 

是歳，
 dm#dm08170@京師 及 dm#dm02403@山東 、 dm#dm04475@江 、 dm#dm04981@淮 旱，
饑。


*** 二年
# year 0669
# p 

春，
二月，
辛酉，
以 rm#r01169@張文瓘 爲東臺侍郎，
以右肅機、檢校太子中護 dm#dm07450@譙 人 rm#r01789@李敬玄 爲西臺侍郎，
竝同東西臺三品。

先是同三品不入銜，
至是始入銜。

# p 

癸亥，
以 dm#dm08502@雍州 長史 rm#r02907@盧承慶 爲司刑太常伯。

 rm#r02907@承慶 常考内外官，
有一官督運，
遭風失米，
 rm#r02907@承慶 考之曰：
「監運損糧，
考中下。」

其人容色自若，
無言而退。

 rm#r02907@承慶 重其雅量，
改註曰：
「非力所及，
考中中。」

既無喜容，
亦無愧詞。

又改曰：
「寵辱不驚，
考中上。」

# p 

三月，
丙戌，
東臺侍郎 rm#r03702@郝處俊 同東、西臺三品。
# p 

丁亥，
詔定明堂制度：
其基八觚，
其宇上圓，
覆以清陽玉葉，
其門牆階級，
窗櫺楣柱，
枊楶枅栱，
皆法天地陰陽律暦之數。

詔下之後，
衆議猶未決，
又會饑饉，
竟不果立。
# p 

夏，
四月，
己酉朔，
上幸 dm#dm00325@九成宮 。


# p 

 dm#dm08934@高麗 之民多離叛者，
敕徙 dm#dm08934@高麗 戸三萬八千二百於 dm#dm04475@江 、 dm#dm04981@淮 之南，
及 dm#dm02398@山南 、 dm#dm00446@京西 諸州空曠之地，
留其貧弱者，
使守 dm#dm02032@安東 。
# p 

六月，
戊申朔，
日有食之。
# p 

秋，
八月，
丁未朔，
詔以十月幸 dm#dm04947@涼州 。

時 dm#dm08458@隴右 虚耗，
議者多以爲未宜遊幸。

上聞之，
辛亥，
御 dm#dm02824@延福殿 ，
召五品已上謂曰：
「自古帝王，
莫不巡守，
故朕欲巡視遠俗。

若果爲不可，
何不面陳，
而退有後言，
何也？」
自宰相以下莫敢對。

詳刑大夫 rm#r05032@來公敏 獨進曰：
「巡守雖帝王常事，
然 dm#dm08934@高麗 新平，
餘寇尚多，
西邊經略，
亦未息兵。

 dm#dm08458@隴右 戸口彫弊，
鑾輿所至，
供億百端，
誠爲未易。

外間實有竊議，
但明制已行，
故羣臣不敢陳論耳。」

上善其言，
爲之罷西巡。

未幾，
擢 rm#r05032@公敏 爲黄門侍郎。

# p 

甲戌，
改 dm#dm05478@瀚海都護府 爲 dm#dm01980@安北都護府 。

# p 

九月，
丁丑朔，
詔徙吐谷渾部落就 dm#dm04947@涼州 南山。

議者恐吐蕃侵暴，
使不能自存，
欲先發兵撃吐蕃。

右相 rm#r03889@閻立本 以爲去歳饑歉，
未可興師。

議久不決，
竟不果徙。
# p 

庚寅，
大風，
海溢，
漂 dm#dm04386@永嘉 、 dm#dm01993@安固 六千餘家。

# p 

冬，
十月，
丁巳，
車駕還 dm#dm08170@京師 。

# p 

十一月，
丁亥，
徙 rm#r01797@豫王旭輪 爲 rm#r01797@冀王 ，
更名 rm#r01797@輪 。

# p 

司空、太子太師、 rm#r01299@英貞武公李勣 寢疾，
上悉召其子弟在外者，
使歸侍疾。

上及太子所賜藥，
 rm#r01299@勣 則餌之；
子弟爲之迎醫，
皆不聽進，
曰：
「吾本 dm#dm02403@山東 田夫，
遭値聖明，
致位三公，
年將八十，
豈非命邪！

脩短有期，
豈能復就醫工求活！」

一旦，
忽謂其弟司衞少卿 rm#r05382@弼 曰：
「吾今日少愈，
可共置酒爲樂。」

於是子孫悉集，
酒闌，
謂弼曰：
「吾自度必不起，
故欲與汝曹爲別耳。

汝曹勿悲泣，
聽我約束。

我見 rm#r01383@房 、 rm#r06215@杜 平生勤苦，
僅能立門戸，
遭不肖子蕩覆無餘。

吾有此子孫，
今悉付汝。

葬畢，
汝即遷入我堂，
撫養孤幼，
謹察視之。

其有志氣不倫，
交遊非類者，
皆先撾殺，
然後以聞。」

自是不復更言。

十二月，
戊申，
薨。

上聞之悲泣，
葬日，
幸 dm#dm03737@未央宮 ，
登樓望轜車慟哭。

起冢象 dm#dm08339@陰山 、 dm#dm08147@鐵山 、 dm#dm05523@烏徳鞬山 ，
以旌其破突厥，
薛延陀之功。

# p 

 rm#r01299@勣 爲將，
有謀善斷；
與人議事，
從善如流。

戰勝則歸功於下，
所得金帛，
悉散之將士，
故人思致死，
所向克捷。

臨事選將，
必訾相其状貌豐厚者遣之。

或問其故，
 rm#r01299@勣 曰：
「薄命之人，
不足與成功名。」

# p 

閨門雍睦而嚴。

其姉嘗病，
 rm#r01299@勣 已爲僕射，
親爲之煮粥，
風囘，
爇其須鬢。

姉曰：
「僕妾幸多，
何自苦如是！」

 rm#r01299@勣 曰：
「非爲無人使令也，
顧姉老，
 rm#r01299@勣 亦老，
雖欲久爲姉煮粥，
其可得乎！」

# p 

 rm#r01299@勣 常謂人：
「我年十二三時爲亡頼賊，
逢人則殺。

十四五爲難當賊，
有所不愜則殺人。

十七八爲佳賊，
臨陳乃殺之。

二十爲大將，
用兵以救人死。」

# p 

 rm#r01299@勣 長子 rm#r02007@震 早卒，
 rm#r02007@震 子 rm#r01788@敬業 襲爵。

# p 

時承平既久，
選人益多，
是歳，
司列少常伯 rm#r03460@裴行儉 始與員外郎 rm#r05245@張仁禕 設長名姓歴牓，
引銓注之法。

又定州縣升降、官資高下。

其後遂爲永制，
無能革之者。
# p 

大略 dyn#ch100@唐 之選法，
取人以身、言、書、判，
計資量勞而擬官。

始集而試，
觀其書、判；
已試而銓，
察其身、言；
已銓而注，
詢其便利；
已注而唱，
集衆告之。

然後類以爲甲，
先簡僕射，
乃上門下，
給事中讀，
侍郎省，
侍中審之，
不當者駮下。

既審，
然後上聞，
主者受旨奉行，
各給以符，
謂之告身。

兵部武選亦然。

課試之法，
以騎射及翹關、負米。

人有格限未至，
而能試文三篇，
謂之宏詞，
試判三條，
謂之拔萃，
入等者得不限而授。

其 dm#dm09182@黔中 、 dm#dm02527@嶺南 、 dm#dm08258@閩中 州縣官，
不由吏部，
委都督選擇土人補授。

凡居官以年爲考，
六品以下，
四考爲滿。
*** 三年
# year 0670
# p 

春，
正月，
丁丑，
右相 rm#r00192@劉仁軌 請致仕；
許之。
** 咸亨
*** 咸亨元年
# year 0670
# p 

三月，
甲戌朔，
以旱，
赦天下，
改元。
# p 

丁丑，
改 dm#dm07066@蓬莱宮 爲 dm#dm01258@含元宮 。

# p 

壬辰，
太子少師 rm#r03511@許敬宗 請致仕；
許之。
# p 

敕突厥酋長子弟事東宮。

西臺舍人 rm#r01297@徐齊耼 上疏，
以爲：
「皇太子當引文學端良之士置左右，
豈可使戎狄醜類入侍軒闥。」

又奏：
「 rm#r05979@齊獻公 即陛下外祖，
雖子孫有犯，
豈應上延祖禰！

今 rm#r02300@周忠孝公 廟甚修，
而 rm#r05959@齊獻公 廟毀廢，
不審陛下何以垂示海内，
彰孝理之風！」

上皆從之。

 rm#r01297@齊耼 ，
充容之弟也。

# p 

夏，
四月，
吐蕃陷 dm#dm07304@西域 十八州，
又與于闐襲龜茲 dm#dm03259@撥換城 ，
陷之。

罷龜茲、于闐、焉耆、疏勒四鎭。

辛亥，
以右衞大將軍 rm#r03268@薛仁貴 爲 dm#dm07789@邏娑道 行軍大總管，
左衞員外大將軍 rm#r03903@阿史那道眞 、左衞將軍 rm#r03720@郭待封 副之，
以討吐蕃，
且援送 dm#dm01253@吐谷渾 還故地。
# p 

庚午，
上幸 dm#dm00325@九成宮 。
# p 

 dm#dm08934@高麗 酋長 rm@劍牟岑 反，
立 rm#r06114@高藏 外孫 rm#r06561@安舜 爲主。

以左監門大將軍 rm#r06278@高侃 爲 dm#dm03819@東州道 行軍總管，
發兵討之。

 rm#r06561@安舜 殺 rm@劍牟岑 ，
奔 dm#dm03383@新羅 。
# p 

六月，
壬寅朔，
日有食之。
# p 

秋，
八月，
丁巳，
車駕還 dm#dm08170@京師 。
# p 

 rm#r03720@郭待封 先與 rm#r03268@薛仁貴 竝列，
及征吐蕃，
恥居其下，
 rm#r03268@仁貴 所言，
 rm#r03720@待封 多違之。

軍至 dm#dm01703@大非川 ，
將趣 dm#dm05532@烏海 ，
 rm#r03268@仁貴 曰：
「 dm#dm05532@烏海 險遠，
軍行甚難，
輜重自隨，
難以趨利；
宜留二萬人，
爲兩柵於 dm#dm01702@大非嶺 上，
輜重悉置柵内，
吾屬帥輕鋭，
倍道兼行，
掩其未備，
破之必矣。」

 rm#r03268@仁貴 帥所部前行，
撃吐蕃於 dm#dm04665@河口 ，
大破之，
斬獲甚衆，
進屯 dm#dm05532@烏海 以俟 rm#r03720@待封 。

 rm#r03720@待封 不用 rm#r03268@仁貴 策，
將輜重徐進。

未至 dm#dm05532@烏海 ，
遇吐蕃二十餘萬，
 rm#r03720@待封 軍大敗，
還走，
悉棄輜重。

 rm#r03268@仁貴 退屯 dm#dm01703@大非川 ，
吐蕃相 rm#xjts01678@論欽陵 將兵四十餘萬就撃之，
 dyn#ch100@唐 兵大敗，
死傷略盡。

 rm#r03268@仁貴 、 rm#r03720@待封 與 rm#r03903@阿史那道眞 竝脱身免，
與 rm#xjts01678@欽陵 約和而還。

敕大司憲樂彦瑋即軍按其敗状，
械送京師，
三人皆免死除名。
# p 

 rm#xjts01678@欽陵 ，
 rm#xjts12685@祿東贊 之子也，
與弟 rm#r05866@贊婆 、 rm#xjts06946@悉多于  rm#xjts20440@勃論 皆有才略。

 rm#xjts12685@祿東贊 卒，
 rm#xjts01678@欽陵 代之，
三弟將兵居外，
鄰國畏之。于干秉政
# p 

 dm#dm08281@關中 旱，
饑，
九月，
丁丑，
詔以 y@明年正月 幸 dm#dm03880@東都 。
# p 

甲申，
皇后母 rm#?@魯國忠烈夫人楊氏 卒，
敕文武九品以上及外命婦竝詣宅弔哭。
# p 

閏月，
癸卯，
皇后以久旱，
請避位，
不許。
# p 

壬子，
加贈司徒 rm#r02300@周忠孝公武士彠 爲太尉、 rm#r02300@太原王 ，
夫人爲王𡚱。
# p 

甲寅，
以左相 rm#r06166@姜恪 爲 dm#dm04949@涼州道 行軍大總管，
以禦吐蕃。
# p 

冬，
十月，
乙未，
太子右中護、同東西臺三品 rm#r03601@趙仁本 爲左肅機，
罷政事。

# p 

庚寅，
詔官名皆復舊。

*** 咸亨二年
# year 0671
# p 

春，
正月，
甲子，
上幸 dm#dm03880@東都 。

# p 

夏，
四月，
甲申，
以西突厥 rm#r06001@阿史那都支 爲左驍衞大將軍兼 dm#dm00824@匐延 都督，
以安集五咄陸之衆。

# p 

初，
 rm#ry0002@武元慶 等既死，
皇后奏以其姉子 rm#r03566@賀蘭敏之 爲 rm#r02300@士彠 之嗣，
襲爵 rm#*rt0104@周公 ，
改姓 rm#no@武氏 ，
累遷弘文館學士、左散騎常侍。

 rm#xjts22339@魏國夫人 之死也，
上見 rm#r03566@敏之 ，
悲泣曰：
「曏吾出視朝猶無恙，
退朝已不救，
何蒼猝如此！」

 rm#r03566@敏之 號哭不對。

后聞之，
曰：
「此兒疑我。」

由是惡之。

 rm#r03566@敏之 貌美，
蒸於 rm#r02300@太原王 𡚱；
及居𡚱喪，
釋衰絰，
奏妓。

司衞少卿 rm#r02186@楊思儉 女，
有殊色，
上及后自選以爲太子𡚱，
婚有日矣，
 rm#r03566@敏之 逼而淫之。

后於是表言 rm#r03566@敏之 前後罪惡，
請加竄逐。

六月，
丙子，
敕流 dm#dm08584@雷州 ，
復其本姓。

至 dm#dm08732@韶州 ，
以馬韁絞死。

朝士坐與 rm#r03566@敏之 交遊，
流 dm#dm02527@嶺南 者甚衆。

# p 

秋，
七月，
乙未朔，
 rm#r06278@高侃 破高麗餘衆於 dm#dm02010@安市城 。

# p 

九月，
丙申，
 dm#dm05357@潞州 刺史 rm#r01321@徐王元禮 薨。
# p 

冬，
十一月，
甲午朔，
日有食之。
# p 

車駕自 dm#dm03880@東都 幸 dm#dm07433@許 、 dm#dm04460@汝 ；
十二月，
癸酉，
校獵於 dm#dm06996@葉縣 ；
丙戌，
還 dm#dm03880@東都 。
*** 三年
# year 0672
# p 

春，
正月，
辛丑，
以太子左衞副率 rm#r05477@梁積壽 爲 dm#dm01899@姚州道 行軍總管，
將兵討叛 dm#dm07217@蠻 。

# p 

庚戌，
 dm#dm03452@昆明蠻 十四姓二萬三千戸内附，
置 dm#dm04359@殷 、 dm#dm03285@敦 、 dm#dm06476@總 三州。

# p 

二月，
庚午，
徙吐谷渾於 dm#dm07964@鄯州  dm#dm04870@浩亹水 南。

吐谷渾畏吐蕃之強，
不安其居，
又 dm#dm07964@鄯州 地狹，
尋徙 dm#dm08619@靈州 ，
以其部落置 dm#dm02043@安樂州 ，
以可汗 rm@諾曷鉢 爲刺史。

吐谷渾故地皆入於吐蕃。
# p 

己卯，
侍中 rm#r06166@永安郡公姜恪 薨。
# p 

夏，
四月，
庚午，
上幸 dm#dm01202@合璧宮 。
# p 

吐蕃遣其大臣 rm#r05864@仲琮 入貢，
上問以吐蕃風俗，
對曰：
「吐蕃地薄氣寒，
風俗朴魯；
然法令嚴整，
上下一心，
議事常自下而起，
因人所利而行之，
斯所以能持久也。」

上詰以呑滅吐谷渾、敗 rm#r03268@薛仁貴 、寇逼 dm#dm04947@涼州 事，
對曰：
「臣受命貢獻而已，
軍旅之事，
非所聞也。」

上厚賜而遣之。

癸未，
遣都水使者 rm#r06135@黄仁素 使于吐蕃。

# p 

秋，
八月，
壬午，
特進 rm#r03511@高陽郡公許敬宗 卒。

太常博士 rm#r03380@袁思古 議：
「 rm#r03511@敬宗 棄長子於荒徼，
嫁少女於 dm#dm01836@夷貊 。

按諡法，
『名與實爽曰繆，』
請諡爲繆。」

 rm#r03511@敬宗 孫太子舍人 rm#r03509@彦伯 訟 rm#r03380@思古 與 rm#no@許氏 有怨，
請改諡。

太常博士議，
以爲：
「得失一朝，
榮辱千載。

若嫌隙有實，
當據法推繩；
如其不然，
義不可奪。」

戸部尚書 rm#r01375@戴至徳 謂 rm#r02779@福畤 曰：
「 rm#r03511@高陽公 任遇如是，
何以諡之爲繆？」
對曰：
「昔 dyn#ch537@晉 司空 rm#r05025@何曾 既忠且孝，
徒以日食萬錢，
 rm#r05718@秦秀 諡之爲『繆』。

 rm#r03511@許敬宗 忠孝不逮於 rm#r05025@曾 ，
而飮食男女之累過之，
諡之曰『繆』，
無負 rm@許氏 矣。」

詔集五品已上更議，
禮部尚書 rm#r06030@陽思敬 議：
「按諡法，
既過能改曰恭，
請諡曰恭。」

詔從之。

 rm#r03511@敬宗 嘗奏流其子 rm#xjts01780@昂 于 dm#dm02527@嶺南 ，
又以女嫁蠻酋 rm#r04199@馮盎 之子，
多納其貨，
故 rm#r03380@思古 議及之。

 rm#r02779@福畤 ，
 rm#r02601@勃 之父也。
諡者
# p 

九月，
癸卯，
徙 rm#r03054@沛王賢 爲雍王。

# p 

冬，
十月，
己未，
詔太子監國。

# p 

壬戌，
車駕發 dm#dm03880@東都 。


# p 

十一月，
戊子朔，
日有食之。
# p 

甲辰，
車駕至 dm#dm08170@京師 。
# p 

十二月，
 rm#r06278@高侃 與 dm#dm08934@高麗 餘衆戰于 dm#dm05888@白水山 ，
破之。

 dm#dm03383@新羅 遣兵救 dm#dm08934@高麗 ，
 rm#r06278@侃 撃破之。
# p 

癸卯，
以左庶子 rm#r00192@劉仁軌 同中書門下三品。
# p 

太子罕接宮臣，
典膳丞 dm#dm00676@全椒  rm#r03683@邢文偉 輒減所供膳，
幷上書諫太子。

太子復書，
謝以多疾及入侍少暇，
嘉納其意。

頃之，
右史缺，
上曰：
「 rm#r03683@邢文偉 事吾子，
能撤膳進諫，
此直士也。」

擢爲右史。

# p 

太子因宴集，
命宮臣擲倒，
次至左奉裕率 rm@王及善 ，
 rm@及善 曰：
「擲倒自有伶官，
臣若奉令，
恐非所以羽翼殿下也。」

太子謝之。

上聞之，
賜 rm@及善 縑百匹，
尋遷左千牛衞將軍。

*** 四年
# year 0673
# p 

春，
正月，
丙辰，
 dm#dm06431@絳州 刺史 rm#r03809@鄭惠王元懿 薨。


# p 

三月，
丙申，
詔 rm#r00192@劉仁軌 等改脩國史，
以 rm#r03511@許敬宗 等所記多不實故也。
# p 

夏，
四月，
丙子，
車駕幸 dm#dm00325@九成宮 。
# p 

閏五月，
 dm#dm05598@燕山道 總管、右領軍大將軍 rm#r01967@李謹行 大破 dm#dm08934@高麗 叛者於 dm#dm05778@瓠蘆河 之西，
俘獲數千人，
餘衆皆奔 dm#dm03383@新羅 。

時 rm#r01967@謹行 妻 rm#?@劉氏 留 dm#dm00528@伐奴城 ，
 dm#dm08934@高麗 引靺鞨攻之，
 rm#?@劉氏 擐甲帥衆守城，
久之，
虜退。

上嘉其功，
封 rm#?@燕國夫人 。

 rm#r01967@謹行 ，
靺鞨人 rm#?@突地稽 之子也，
武力絶人，
爲衆夷所憚。
# p 

秋，
七月，
 dm#dm01926@婺州 大水，
溺死者五千人。
辛巳
# p 

八月，
辛丑，
上以瘧疾，
令太子於 dm#dm02824@延福殿 受諸司啓事。

# p 

冬，
十月，
壬午，
中書令 rm#r03889@閻立本 薨。
# p 

乙巳，
車駕還 dm#dm08170@京師 。
# p 

十二月，
丙午，
弓月、疏勒二王來降。

西突厥 rm@興昔亡可汗 之世，
諸部離散，
弓月及 rm@阿悉吉 皆叛。

 rm#r03341@蘇定方 之西討也，
擒 rm@阿悉吉 以歸。

弓月南結吐蕃，
北招咽麪
                     ，
共攻疏勒，
降之。

上遣鴻臚卿 rm#r03235@蕭嗣業 發兵討之。

 rm#r03235@嗣業 兵未至，
弓月懼，
與疏勒皆入朝；
上赦其罪，
遣歸國。

*** 五年
# year 0674
# p 

春，
正月，
壬午，
以左庶子、同中書門下三品 rm#r00192@劉仁軌 爲 dm#dm08524@雞林道 大總管，
衞尉卿 rm#r05383@李弼 、右領軍大將軍 rm#r01967@李謹行 副之，
發兵討 dm#dm03383@新羅 。

時 rm#?@新羅王  rm@法敏 既納 dm#dm08934@高麗 叛衆，
又據 dm#dm05948@百濟 故地，
使人守之。

上大怒，
詔削 rm@法敏 官爵；
其弟右驍衞員外大將軍、 rm#?@臨海郡公仁問 在 dm#dm08170@京師 ，
立以爲 rm#?@新羅王 ，
使歸國。
# p 

三月，
辛亥朔，
日有食之。
# p 

 rm#r03566@賀蘭敏之 既得罪，
皇后奏召 rm#r05538@武元爽 之子 rm#r02314@承嗣 於 dm#dm02527@嶺南 ，
襲爵 rm#*rt0104@周公 ，
拜尚衣奉御；
夏，
四月，
辛卯，
遷宗正卿。
** 上元
*** 上元元年
# year 0674
# p 

秋，
八月，
壬辰，
追尊 rm#ry1003@宣簡公 爲 rm#ry1003@宣皇帝 ，
妣 rm#xjts05033@張氏 爲 rm#xjts05033@宣莊皇后 ；
 rm#ry1004@懿王 爲 rm#ry1004@光皇帝 ，
妣 rm#xjts03866@賈氏 爲 rm#xjts03866@光懿皇后 ；
 rm#r04258@太武皇帝 爲 rm#r04258@神堯皇帝 ，
 rm#r03010@太穆皇后 爲 rm#r03010@太穆神皇后 ；
 rm#r01602@文皇帝 爲 rm#r01602@太宗文武聖皇帝 ，
 rm#r03855@文徳皇后 爲 rm#r03855@文徳聖皇后 。

皇帝稱天皇，
皇后稱天后，
以避先帝、先后之稱。

改元，
赦天下。
# p 

戊戌，
敕：
「文武官三品以上服紫，
金玉帶；
四品服深緋，
金帶；
五品服淺緋，
金帶；
六品服深緑，
七品服淺緑，
竝銀帶；
八品服深青，
九品服淺青，
竝鍮石帶；
庶人服黄，
銅鐵帶。

自非庶人，
不聽服黄。」


# p 

九月，
癸丑，
詔追復 rm#r05979@長孫晟 、 rm#r03856@長孫無忌 官爵，
以 rm#r03856@無忌 曾孫 rm@翼 襲爵 rm@趙公 ，
聽 rm#r03856@無忌 喪歸，
陪葬 dm#dm03528@昭陵 。

# p 

甲寅，
上御 dm#dm06568@翔鸞閣 ，
觀大酺。

分音樂爲東西朋，
使 rm#r03054@雍王賢 主東朋，
 rm#r01656@周王顯 主西朋，
角勝爲樂，
 rm#r03702@郝處俊 諫曰：
「二王春秋尚少，
志趣未定，
當推梨讓棗，
相親如一。

今分二朋，
遞相誇競，
俳優小人，
言辭無度，
恐其交爭勝負，
譏誚失禮，
非所以崇禮義，
勸敦睦也。」

上瞿然曰：
「卿遠識，
非衆人所及也。」

遽止之。
# p 

是日，
衞尉卿 rm#r05383@李弼 暴卒于宴所，
爲之廢酺一日。

# p 

冬，
十一月，
丙午朔，
車駕發 dm#dm08170@京師 ；
己酉，
校獵 dm#dm06933@華山 之 dm#dm03614@曲武原 ；
戊辰，
至 dm#dm03880@東都 。


# p 

 dm#dm06366@箕州 録事參軍 rm#r05255@張君澈 等誣告刺史 rm#r03207@蒋王惲 及其子 rm#r03208@汝南郡王煒 謀反，
敕通事舍人 rm#r05813@薛思貞 馳傳往按之。

十二月，
癸未，
 rm#r03207@惲 惶懼，
自縊死，
上知其非罪，
深痛惜之，
斬 rm#r05255@君澈 等四人。
# p 

戊子，
 rm#r05197@于闐王伏闍雄 來朝。

# p 

辛卯，
 rm#?@波斯王卑路斯 來朝。
# p 

壬寅，
天后上表，
以爲：
「國家聖緒，
出自 rm#ry0032@玄元皇帝 ，
請令王公以下皆習老子，
毎歳明經，
準孝經、論語策試。」

又請「自今父在，
爲母服齊衰三年。

又，
京官八品以上，
宜量加俸祿。」

及其餘便宜，
合十二條。

詔書褒美，
皆行之。
# p 

是歳，
有 rm#r05076@劉曉 者，
上疏論選，
以爲：
「今選曹以檢勘爲公道，
書判爲得人，
殊不知考其徳行才能。

況書判借人者衆矣。

又，
禮部取士，
專用文章爲甲乙，
故天下之士，
皆捨徳行而趨文藝，
有朝登甲科而夕陷刑辟者，
雖日誦萬言，
何關理體！

文成七歩，
未足化人。

況盡心卉木之間，
極筆煙霞之際，
以斯成俗，
豈非大謬！

夫人之慕名，
如水趨下，
上有所好，
下必甚焉。

陛下若取士以徳行爲先，
文藝爲末，
則多士雷奔，
四方風動矣！」


*** 二年
# year 0675
# p 

春，
正月，
丙寅，
以 dm#dm00369@于闐國 爲 dm#dm04372@毘沙都督府 ，
分其境内爲十州，
以 rm#r05197@于闐王尉遲伏闍雄 爲 dm#dm04372@毘沙 都督。

# p 

辛未，
吐蕃遣其大臣 rm@論吐渾彌 來請和，
且請與吐谷渾復脩鄰好；
上不許。

# p 

二月，
 rm#r00192@劉仁軌 大破 dm#dm03383@新羅 之衆於 dm#dm00110@七重城 ；
又使靺鞨浮海，
略 dm#dm03383@新羅 之南境，
斬獲甚衆。

 rm#r00192@仁軌 引兵還。

詔以 rm#r01967@李謹行 爲 dm#dm02032@安東 鎭撫大使，
屯 dm#dm03383@新羅 之 dm#dm07528@買肖城 以經略之，
三戰皆捷，
 dm#dm03383@新羅 乃遣使入貢，
且謝罪；
上赦之，
復 rm@新羅王法敏 官爵。

 rm#r05968@金仁問 中道而還，
改封 rm#?@臨海郡公 。
# p 

三月，
丁巳，
天后祀先蠶於 dm#dm07795@邙山 之陽；
百官及朝集使皆陪位。

# p 

上苦風眩甚，
議使天后攝知國政。

中書侍郎同三品 rm#r03702@郝處俊 曰：
「天子理外，
后理内，
天之道也。

昔 rm#rt0550@魏文 著令，
雖有幼主，
不許皇后臨朝，
所以杜禍亂之萌也。

陛下奈何以 rm#r04258@高祖 、 rm#r01602@太宗 之天下，
不傳之子孫而委之天后乎！」

中書侍郎 dm#dm03470@昌樂  rm#r01924@李義琰 曰：
「 rm#r03702@處俊 之言至忠，
陛下宜聽之！」

上乃止。
# p 

天后多引文學之士著作郎 rm#r00162@元萬頃 、左史 rm#r00301@劉禕之 等，
使之撰列女傳、臣軌、百僚新戒、樂書，
凡千餘卷。

朝廷奏議及百司表疏，
時密令參決，
以分宰相之權，
時人謂之北門學士。

 rm#r00301@禕之 ，
 rm#r05062@子翼 之子也。

# p 

夏，
四月，
庚辰，
以司農少卿 rm#r04028@韋弘機 爲司農卿。

 rm#r04028@弘機 兼知 dm#dm03880@東都 營田，
受詔完葺宮苑。

有宦者於苑中犯法，
 rm#r04028@弘機 杖之，
然後奏聞。

上以爲能，
賜絹數十匹，
曰：
「更有犯者，
卿即杖之，
不必奏也。」

# p 

初，
左千牛將軍 dm#dm08170@長安  rm#ry0005@趙瓌 尚 rm#r04258@高祖 女 rm#r01028@常樂公主 ，
生女爲 rm#r01656@周王顯 𡚱。

公主頗爲上所厚，
天后惡之。

辛巳，
𡚱坐廢，
幽閉於内侍省，
食料給生者，
防人候其突煙，
而已數日煙不出，
開視，
死腐矣。

 rm#ry0005@瓌 自 dm#dm02124@定州 刺史貶 dm#dm03988@栝州 刺史，
令公主隨之官，
仍絶其朝謁。


# p 

 rm#r00688@太子弘 仁孝謙謹，
上甚愛之；
禮接士大夫，
中外屬心。

天后方逞其志，
太子奏請，
數迕旨，
由是失愛於天后。

 rm#r03103@義陽 、 rm#r00838@宣城 二公主，
 rm@蕭淑𡚱 之女也，
坐母得罪，
幽于掖庭，
年踰三十不嫁。

太子見之驚惻，
遽奏請出降，
上許之。

天后怒，
即日以公主配當上翊衞 rm#r05533@權毅 、 rm#r05657@王遂古 。

己亥，
太子薨于 dm#dm01202@合璧宮 ，
時人以爲天后酖之也。

# p 

壬寅，
車駕還 dm#dm04789@洛陽宮 。

五月，
戊申，
下詔：
「朕方欲禪位皇太子，
而疾遽不起，
宜申往命，
加以尊名，
可諡爲 rm#r00688@孝敬皇帝 。」


# p 

六月，
戊寅，
立 rm#r03054@雍王賢 爲皇太子，
赦天下。

# p 

天后惡 dm#dm03068@慈州 刺史 rm#r02521@𣏌王上金 ，
有司希旨奏其罪；
秋，
七月，
 rm#r02521@上金 坐解官，
 dm#dm05403@澧州 安置。


# p 

八月，
庚寅，
葬 rm#r00688@孝敬皇帝 于 dm#dm03039@恭陵 。

# p 

戊戌，
以 rm#r01375@戴至徳 爲右僕射，
庚子，
以 rm#r00192@劉仁軌 爲左僕射，
竝同中書門下三品如故。

 rm#r01169@張文瓘 爲侍中，
 rm#r03702@郝處俊 爲中書令；
 rm#r01789@李敬玄 爲吏部尚書兼左庶子，
同中書門下三品如故。
# p 

 rm#r00192@劉仁軌 、 rm#r01375@戴至徳 更日受牒訴，
 rm#r00192@仁軌 常以美言許之，
 rm#r01375@至徳 必據理難詰，
未嘗與奪，
實有冤結者，
密爲奏辯。

由是時譽皆歸 rm#r00192@仁軌 。

或問其故，
 rm#r01375@至徳 曰：
「威福者人主之柄，
人臣安得盜取之！」

上聞，
深重之。

有老嫗欲詣 rm#r00192@仁軌 陳牒，
誤詣 rm#r01375@至徳 ，
 rm#r01375@至徳 覽之未終，
嫗曰：
「本謂是解事僕射，
乃不解事僕射邪！

歸我牒！」

 rm#r01375@至徳 笑而授之。

時人稱其長者。

 rm#r01169@文瓘 時兼大理卿，
囚聞改官，
皆慟哭。

 rm#r01169@文瓘 性嚴正，
諸司奏議，
多所糾駮，
上甚委之。

*** 三年
# year 0676
# p 

春，
正月，
壬戌，
徙 rm#r01797@冀王輪 爲 rm#r01797@相王 。
# p 

 dm#dm06394@納州 獠反，
敕 dm#dm09188@黔州 都督發兵討之。


# p 

二月，
甲戌，
徙 dm#dm02035@安東都護府 於 dm#dm07770@遼東 故城；
先是有 dm#dm06927@華 人任東官者，
悉罷之。

徙 dm#dm05582@熊津 都督府於 dm#dm02843@建安 故城；
其 dm#dm05948@百濟 戸口先徙於 dm#dm02948@徐 、 dm#dm00663@兗 等州者，
皆置於 dm#dm02843@建安 。安
# p 

天后勸上封中嶽；
癸未，
詔以今冬有事于 dm#dm02514@嵩山 。

# p 

丁亥，
上幸 dm#dm04465@汝州 之温湯。

# p 

三月，
癸卯，
黄門侍郎 rm#r00118@來恆 、中書侍郎 rm#r03274@薛元超 竝同中書門下三品。

 rm#r00118@恆 ，
 rm#r00119@濟 之兄；
 rm#r03274@元超 ，
 rm#r03296@收 之子也。

# p 

甲辰，
上還 dm#dm03880@東都 。

# p 

閏月，
吐蕃寇 dm#dm07957@鄯 、 dm#dm02715@廓 、 dm#dm04650@河 、 dm#dm06832@芳 等州，
敕左監門衞中郎將 rm#r05016@令狐智通 發 dm#dm06771@興 、 dm#dm08992@鳳 等州兵以禦之。

己卯，
詔以吐蕃犯塞，
停封中嶽。

乙酉，
以 dm#dm04778@洛州 牧 rm#r01656@周王顯 爲 dm#dm04824@洮州道 行軍元帥，
將工部尚書 rm#r00226@劉審禮 等十二總管，
 dm#dm00059@幷州 大都督 rm#r01797@相王輪 爲 dm#dm04949@涼州道 行軍元帥，
將左衞大將軍 rm#r00611@契苾何力 等，
以討吐蕃。

二王皆不行。
# p 

庚寅，
車駕西還。

# p 

甲寅，
中書侍郎 rm#r01924@李義琰 同中書門下三品。
# p 

戊午，
車駕至 dm#dm00325@九成宮 。
# p 

六月，
癸亥，
黄門侍郎 dm#dm03564@晉陵  rm#r04246@高智周 同中書門下三品。
# p 

秋，
八月，
乙未，
吐蕃寇 dm#dm05855@疊州 。
# p 

壬寅，
敕：
「 dm#dm03996@桂 、 dm#dm02717@廣 、 dm#dm00412@交 、 dm#dm09181@黔 等都督府，
比來注擬土人，
簡擇未精，
自今毎四年遣五品已上清正官充使，
仍令御史同往注擬。」

時人謂之南選。

# p 

九月，
壬申，
大理奏左威衞大將軍 rm#r05529@權善才 、左監門中郎將 rm#r05759@范懷義 誤斫 dm#dm03528@昭陵 柏，
罪當除名；
上特命殺之。

大理丞 dm#dm01774@太原  rm#r02567@狄仁傑 奏：
「二人罪不當死。」

上曰：
「 rm#r05529@善才 等斫陵柏，
我不殺則爲不孝。」

 rm#r02567@仁傑 固執不已，
上作色，
令出，
 rm#r02567@仁傑 曰：
「犯顏直諫，
自古以爲難。

臣以爲遇 rm#rt0026@桀 、 rm#rt0056@紂 則難，
遇 rm#rt0006@堯 、 rm#rt0007@舜 則易。

今法不至死而陛下特殺之，
是法不信於人也，
人何所措其手足！

且 rm#r05307@張釋之 有言：
『設有盜 dm#dm08239@長陵 一抔土，
陛下何以處之？』
今以一株柏殺二將軍，
後代謂陛下爲何如矣！

臣不敢奉詔者，
恐陷陛下於不道，
且羞見 rm#r05307@釋之 於地下故也。」

上怒稍解，
二人除名，
流 dm#dm02527@嶺南 。

後數日，
擢 rm#r02567@仁傑 爲侍御史。

# p 

初，
 rm#r02567@仁傑 爲 dm#dm00059@幷州 法曹，
同僚 rm#r05959@鄭崇質 當使絶域。

 rm#r05959@崇質 母老且病，
 rm#r02567@仁傑 曰：
「彼母如此，
豈可使之有萬里之憂！」

詣長史 rm#xjts20160@藺仁基 ，
請代之行。

 rm#xjts20160@仁基 素與司馬 rm#r05369@李孝廉 不叶，
因相謂曰：
「吾輩豈可不自愧乎！」

遂相與輯睦。
# p 

冬，
十月，
車駕還 dm#dm08170@京師 。

# p 

丁酉，
祫享太廟，
用太學博士 rm#r05099@史璨 議，
禘後三年而祫，
祫後二年而禘。

# p 

 rm#r03522@郇王素節 ，
 rm#?@蕭淑𡚱 之子也，
警敏好學。

天后惡之，
 dm#dm06743@自岐州 刺史左遷 dm#dm05829@申州 刺史。

 y@乾封初 ，
敕曰：
「 rm#r03522@素節 既有舊疾，
不須入朝。」

而 rm#r03522@素節 實無疾，
自以久不得入覲，
乃著忠孝論。

王府倉曹參軍 rm#r01188@張柬之 因使潛封其論以進。

后見之，
誣以贓賄，
丙午，
降封 rm#r03522@鄱陽王 ，
 dm#dm07243@袁州 安置。

** 儀鳳
*** 儀鳳元年
# year 0676
# p 

十一月，
壬申，
改元，
赦天下。
# p 

庚寅，
以 rm#r01789@李敬玄 爲中書令。
# p 

十二月，
戊午，
以 rm#r00118@來恆 爲 dm#dm04663@河南道 大使，
 rm#r03274@薛元超 爲 dm#dm04658@河北道 大使，
尚書左丞 dm#dm07935@鄢陵  rm#r00971@崔知悌 、國子司業 rm#r05963@鄭祖玄 爲 dm#dm04481@江南道 大使，
分道巡撫。
*** 二年
# year 0677
# p 

春，
正月，
乙亥，
上耕藉田。
# p 

初，
 rm#r00192@劉仁軌 引兵自 dm#dm05582@熊津 還，
 rm#xjts24128@扶餘隆 畏 dm#dm03383@新羅 之逼，
不敢留，
尋亦還朝。

二月，
丁巳，
以工部尚書 rm#r06114@高藏 爲 dm#dm07772@遼東州 都督，
封 rm#r06114@朝鮮王 ，
遣歸 dm#dm07770@遼東 ，
安輯 dm#dm08934@高麗 餘衆；
 dm#dm08934@高麗 先在諸州者，
皆遣與 rm#r06114@藏 倶歸。

又以司農卿 rm#xjts24128@扶餘隆 爲 dm#dm05582@熊津 都督，
封 rm#xjts24128@帶方王 ，
亦遣歸安輯 dm#dm05948@百濟 餘衆，
仍移 dm#dm02035@安東都護府 於 dm#dm03332@新城 以統之。

時 dm#dm05948@百濟 荒殘，
命 rm#xjts24128@隆 寓居 dm#dm08934@高麗 之境。

 rm#r06114@藏 至 dm#dm07770@遼東 ，
謀叛，
潛與靺鞨通；
召還，
徙 dm#dm07804@邛州 而死，
散徙其人於 dm#dm04660@河南 、 dm#dm08458@隴右 諸州，
貧者留 dm#dm02032@安東 城傍。

 dm#dm08934@高麗 舊城沒於 dm#dm03383@新羅 ，
餘衆散入靺鞨及突厥，
 rm#xjts24128@隆 亦竟不敢還故地，
 rm#no@高氏 、 rm#no@扶餘氏 遂亡。
# p 

三月，
癸亥朔，
以 rm#r03702@郝處俊 、 rm#r04246@高智周 竝爲左庶子，
 rm#r01924@李義琰 爲右庶子。

# p 

夏，
四月，
左庶子 rm#r01130@張大安 同中書門下三品。

 rm#r01130@大安 ，
 rm#r01115@公謹 之子也。

# p 

詔以 dm#dm04660@河南 、 dm#dm00829@北 旱，
遣御史中丞 rm#r05232@崔謐 等分道存問賑給。

侍御史 dm#dm02309@寧陵  rm#r00255@劉思立 上疏：
以爲：
「今麥秀蠶老，
農事方殷，
敕使撫巡，
人皆竦抃，
忘其家業，
冀此天恩，
聚集參迎，
妨廢不少。

既縁賑給，
須立簿書，
本欲安存，
更成煩擾。

望且委州縣賑給，
待秋務閒，
出使褒貶。」

疏奏，
 rm#r05232@謐 等遂不行。

# p 

五月，
吐蕃寇 dm#dm03171@扶州 之 dm#dm06687@臨河鎭 ，
擒鎭將 rm#r05446@杜孝昇 ，
令齎書説 dm#dm03903@松州 都督 rm#r05539@武居寂 使降，
 rm#r05446@孝昇 固執不從。

吐蕃軍還，
捨 rm#r05446@孝昇 而去，
 rm#r05446@孝昇 復帥餘衆拒守。

詔以 rm#r05446@孝昇 爲游撃將軍。

# p 

秋，
八月，
徙 rm#r01656@周王顯 爲 rm#r01656@英王 ，
更名 rm#r01656@哲 。

# p 

命 rm#r00192@劉仁軌 鎭 dm#dm04827@洮河軍 。

冬，
十二月，
乙卯，
詔大發兵討吐蕃。
# p 

詔以 y@顯慶 新禮，
多不師古，
其五禮竝依周禮行事。

自是禮官益無憑守，
毎有大禮，
臨時撰定。

*** 三年
# year 0678
# p 

春，
正月，
辛酉，
百官及蠻夷酋長朝天后于 dm#dm00660@光順門 。

# p 

 rm#r00192@劉仁軌 鎭 dm#dm04826@洮河 ，
毎有奏請，
多爲 rm#r01789@李敬玄 所抑，
由是怨之。

 rm#r00192@仁軌 知 rm#r01789@敬玄 非將帥才，
欲中傷之，
奏言：
「西邊鎭守，
非 rm#r01789@敬玄 不可。」

 rm#r01789@敬玄 固辭。

上曰：
「 rm#r00192@仁軌 須朕，
朕亦自往，
卿安得辭！」

丙子，
以 rm#r01789@敬玄 代 rm#r00192@仁軌 爲 dm#dm04828@洮河道 大總管兼安撫大使，
仍檢校 dm#dm07964@鄯州 都督。

又命 dm#dm05982@益州 大都督府長史 rm#r02121@李孝逸 等發 dm#dm00785@劍南 、 dm#dm02398@山南 兵以赴之。

 rm#r02121@孝逸 ，
 rm#r02450@神通 之子也。

# p 

癸未，
遣金吾將軍 rm#r06198@曹懷舜 等分往 dm#dm04660@河南 、 dm#dm00829@北 募猛士，
不問布衣及仕宦。
# p 

夏，
四月，
戊申，
赦天下，
改來年元爲 y@通乾 。


# p 

五月，
壬戌，
上幸 dm#dm00325@九成宮 。

丙寅，
山中雨，
大寒，
從兵有凍死者。

# p 

秋，
七月，
 rm#r01789@李敬玄 奏破吐蕃於 dm#dm09244@龍支 。

# p 

上初即位，
不忍觀破陳樂，
命撤之。

辛酉，
太常少卿 rm#r04067@韋萬石 奏：
「久寢不作，
懼成廢缺。

請自今大宴會復奏之。」

上從之。

# p 

九月，
辛酉，
車駕還 dm#dm08170@京師 。
# p 

上將發兵討 dm#dm03383@新羅 ，
侍中 rm#r01169@張文瓘 臥疾在家，
自輿入見，
諫曰：
「今吐蕃爲寇，
方發兵西討；
 dm#dm03383@新羅 雖云不順，
未嘗犯邊，
若又東征，
臣恐公私不勝其弊。」

上乃止。

癸亥，
 rm#r01169@文瓘 薨。
# p 

丙寅，
 rm#r01789@李敬玄 將兵十八萬與吐蕃將 rm#xjts01678@論欽陵 戰於 dm#dm08673@青海 之上，
兵敗，
工部尚書、右衞大將軍 rm#r00226@彭城僖公  rm#r00226@劉審禮 爲吐蕃所虜。

時 rm#r00226@審禮 將前軍深入，
頓于 dm#dm05451@濠所 ，
爲虜所攻，
 rm#r01789@敬玄 懦怯，
按兵不救。

聞 rm#r00226@審禮 戰沒，
狼狽還走，
頓于 dm#dm03198@承風嶺 ，
阻泥溝以自固，
虜屯兵高岡以壓之。

左領軍員外將軍 rm#r04339@黒齒常之 ，
夜帥敢死之士五百人襲撃虜營，
虜衆潰亂，
其將 rm#xjts24607@跋地設 引兵遁去，
 rm#r01789@敬玄 乃收餘衆還 dm#dm07964@鄯州 。

# p 

 rm#r00226@審禮 諸子自縛詣闕，
請入吐蕃贖其父，
敕聽次子 rm#r00274@易從 詣吐蕃省之。

比至，
 rm#r00226@審禮 已病卒，
 rm#r00274@易從 晝夜號哭不絶聲；
吐蕃哀之，
還其尸，
 rm#r00274@易從 徒跣負之以歸。
# p 

上嘉 rm#r04339@黒齒常之 之功，
擢拜左武衞將軍，
充 dm#dm04691@河源軍 副使。

# p 

 rm#r01789@李敬玄 之西征也，
監察御史 dm#dm01115@原武  rm#r00657@婁師徳 應猛士詔從軍，
及敗，
敕 rm#r00657@師徳 收集散亡，
軍乃復振。

因命使于吐蕃，
吐蕃將 rm#r05866@論贊婆 迎之 dm#dm07582@赤嶺 。

 rm#r00657@師徳 宣導上意，
諭以禍福，
 rm#r05866@贊婆 甚悦，
爲之數年不犯邊。

 rm#r00657@師徳 遷殿中侍御史，
充 dm#dm04691@河源軍 司馬，
兼知營田事。
# p 

上以吐蕃爲憂，
悉召侍臣謀之，
或欲和親以息民；
或欲嚴設守備，
俟公私富實而討之；
或欲亟發兵撃之。

議竟不決，
賜食而遣之。
# p 

太學生 dm#dm02096@宋城  rm#r04302@魏元忠 上封事，
言禦吐蕃之策，
以爲：
「理國之要，
在文與武。

今言文者則以辭華爲首而不及經綸，
言武者則以騎射爲先而不及方略，
是皆何益於理亂哉！

故 rm#r06026@陸機 著辨亡之論，
無救 dm#dm04678@河橋 之敗，
 rm@養由基 射穿七札，
不濟 dm#dm07935@鄢陵 之師，
此已然之明效也。

古語有之：
『人無常俗，
政有理亂；
兵無強弱，
將有巧拙。』

故選將當以智略爲本，
勇力爲末。

今朝廷用人，
類取將門子弟及死事之家，
彼皆庸人，
豈足當閫外之任！

 rm#r05377@李左車 、 rm#r06014@陳湯 、 rm#r05118@呂蒙 、 rm#r05155@孟觀 ，
皆出貧賤而立殊功，
未聞其家代爲將也。

夫賞罰者，
軍國之切務，
苟有功不賞，
有罪不誅，
雖 rm#rt0006@堯 、 rm#rt0007@舜 不能以致理。

議者皆云：
『近日征伐，
虚有賞格而無事實。』

蓋由小才之吏，
不知大體，
徒惜勳庸，
恐虚倉庫。

不知士不用命，
所損幾何！

黔首雖微，
不可欺罔。

豈得懸不信之令，
設虚賞之科，
而望其立功乎！

自 rm#r03341@蘇定方 征 dm#dm07770@遼東 ，
 rm#r01299@李勣 破 dm#dm02614@平壤 ，
賞絶不行，
勳仍淹滯，
不聞斬一臺郎，
戮一令史，
以謝勳人。

 dm#dm01703@大非川 之敗，
 rm#r03268@薛仁貴 、 rm#r03720@郭待封 等不即重誅，
曏使早誅 rm#r03268@仁貴 等，
則自餘諸將豈敢失利於後哉！

臣恐吐蕃之平，
非旦夕可冀也。

又，
出師之要，
全資馬力。

臣請開畜馬之禁，
使百姓皆得畜馬；
若官軍大舉，
委州縣長吏以官錢増價市之，
則皆爲官有。

彼胡虜恃馬力以爲強，
若聽人間市而畜之，
乃是損彼之強爲 dm#dm00255@中國 之利也。

」
先是禁百姓畜馬，
故 rm#r04302@元忠 言之。

上善其言，
召見，
令直中書省，
仗内供奉。

# p 

冬，
十月，
丙午，
 dm#dm02952@徐州 刺史 rm#r00845@密貞王元曉 薨。
# p 

十一月，
壬子，
黄門侍郎、同中書門下三品 rm#r00118@來恆 薨。

# p 

十二月，
詔停來年 y@通乾 之號，
以反語不善故也。

*** 四年
# year 0679
# p 

春，
正月，
己酉，
上幸 dm#dm03880@東都 。

# p 

司農卿 rm#r04028@韋弘機 作 dm#dm02251@宿羽 、 dm#dm08891@高山 、 dm#dm00199@上陽 等宮，
制度壯麗。

 dm#dm00199@上陽宮 臨 dm#dm04780@洛水 ，
爲長廊亙一里。

宮成，
上徙御之。

侍御史 rm#r02567@狄仁傑 劾奏 rm#r04028@弘機 導上爲奢泰，
 rm#r04028@弘機 坐免官。

左司郎中 rm#r01148@王本立 恃恩用事，
朝廷畏之。

 rm#r02567@仁傑 奏其姦，
請付法司，
上特原之，
 rm#r02567@仁傑 曰：
「國家雖乏英才，
豈少 rm#r01148@本立 輦！

陛下何惜罪人，
以虧王法。

必欲曲赦 rm#r01148@本立 ，
請棄臣於無人之境，
爲忠貞將來之戒！」

 rm#r01148@本立 竟得罪。

由是朝廷肅然。
# p 

庚戌，
右僕射、太子賓客 rm#r01375@道恭公戴至徳 薨。

# p 

二月，
壬戌，
吐蕃贊普卒，
子 rm@器弩悉弄 立，
生八年矣。

時 rm@器弩悉弄 與其舅 rm#?@麹薩若 詣羊同發兵，
有弟生六年，
在 rm#xjts01678@論欽陵 軍中。

國人畏 rm#xjts01678@欽陵 之強，
欲立之，
 rm#xjts01678@欽陵 不可，
與 rm@薩若 共立 rm@器弩悉弄 。
# p 

上聞贊普卒，
命 rm#r03460@裴行儉 乘間圖之，
 rm#r03460@行儉 曰：
「 rm#xjts01678@欽陵 爲政，
大臣輯睦，
未可圖也。」

乃止。

嗣主未定
# p 

夏，
四月，
辛酉，
 rm#r03702@郝處俊 爲侍中。
# p 

 dm#dm00606@偃師 人 rm#r01443@明崇儼 ，
以符呪幻術爲上及天后所重，
官至正諫大夫。

五月，
壬午，
 rm#r01443@崇儼 爲盜所殺，
求賊，
竟不得。

贈 rm#r01443@崇儼 侍中。
# p 

丙戌，
命太子監國。

太子處事明審，
時人稱之。
# p 

戊戌，
作 dm#dm06414@紫桂宮 於 dm#dm05396@澠池 之西。

** 調露
*** 調露元年
# year 0679
# p 

六月，
辛亥，
赦天下，
改元。
# p 

初，
西突厥十姓可汗 rm#r06001@阿史那都支 及其別帥 rm#r05436@李遮匐 與吐蕃連和，
侵逼 dm#dm02061@安西 ，
朝議欲發兵討之。

吏部侍郎 rm#r03460@裴行儉 曰：
「吐蕃爲寇，
 rm#r00226@審禮 覆沒，
干戈未息，
豈可復出師西方！

今 rm#?@波斯王 卒，
其子 rm@泥洹師 爲質在 dm#dm08170@京師 ，
宜遣使者送歸國，
道過二虜，
以便宜取之，
可不血刃而擒也。」

上從之，
命 rm#r03460@行儉 册立 rm@波斯王 ，
仍爲安撫大食使。

 rm#r03460@行儉 奏 dm#dm06603@肅州 刺史 rm#r02644@王方翼 以爲己副，
仍令檢校 dm#dm02061@安西 都護。

# p 

秋，
七月，
己卯朔，
詔以 y@今年冬 至有事于 dm#dm02514@嵩山 。
# p 

初，
 rm#r03460@裴行儉 嘗爲 dm#dm07317@西州 長史，
及奉使過 dm#dm07317@西州 ，
吏人郊迎，
 rm#r03460@行儉 悉召其豪傑子弟千餘人自隨，
且揚言天時方熱，
未可渉遠，
須稍涼乃西上。

 rm#r06001@阿史那都支 覘知之，
遂不設備。

 rm#r03460@行儉 徐召四鎭諸 rm#*rt0073@胡 酋長謂曰：
「昔在 dm#dm07317@西州 ，
縱獵甚樂，
今欲尋舊賞，
誰能從吾獵者？」
諸胡子弟爭請從行，
近得萬人。

 rm#r03460@行儉 陽爲畋獵，
校勒部伍，
數日，
遂倍道西進。

去 rm#r06001@都支 部落十餘里，
先遣 rm#r06001@都支 所親問其安否，
外示閒暇，
似非討襲，
續使促召相見。

 rm#r06001@都支 先與 rm#r05436@李遮匐 約，
秋中拒 dyn#ch129@漢 使，
猝聞軍至，
計無所出，
帥其子弟迎謁，
遂擒之。

因傳其契箭，
悉召諸部酋長，
執送 dm#dm06163@碎葉城 。

簡其精騎，
輕齎，
晝夜進掩 rm#r05436@遮匐 ，
途中，
獲 rm#r06001@都支 還使與 rm#r05436@遮匐 使者同來；
 rm#r03460@行儉 釋 rm#r05436@遮匐 使者，
使先往諭 rm#r05436@遮匐 以 rm#r06001@都支 已就擒，
 rm#r05436@遮匐 亦降。

於是囚 rm#r06001@都支 、 rm#r05436@遮匐 以歸，
遣 rm@波斯王 自還其國，
留 rm#r02644@王方翼 於 dm#dm02061@安西 ，
使築 dm#dm06163@碎葉城 。

# p 

冬，
十月，
 dm#dm01396@單于大都護府 突厥 rm#r05571@阿史徳温傅 、奉職二部倶反，
立 rm#r05998@阿史那泥熟匐 爲可汗，
二十四州酋長皆叛應之，
衆數十萬，
遣鴻臚卿 dm#dm01396@單于大都護府 長史 rm#r03235@蕭嗣業 、右領軍衞將軍 rm#xjts19953@花大智 、右千牛衞將軍 rm#r05402@李景嘉 等將兵討之。

 rm#r03235@嗣業 等先戰屡捷，
因不設備；
會大雪，
突厥夜襲其營，
 rm#r03235@嗣業 狼狽拔營走，
衆遂大亂，
爲虜所敗，
死者不可勝數。

 rm#xjts19953@大智 、 rm#r05402@景嘉 引歩兵且行且戰，
得入 dm#dm01400@單于都護府 。

 rm#r03235@嗣業 減死，
流 dm#dm04001@桂州 ，
 rm#xjts19953@大智 、 rm#r05402@景嘉 竝免官。
# p 

突厥寇 dm#dm02124@定州 ，
刺史 rm#r03988@霍王元軌 命開門偃旗，
虜疑有伏，
懼而宵遁。

州人 rm#ry0006@李嘉運 與虜通謀，
事洩，
上令 rm#r03988@元軌 窮其黨與，
 rm#r03988@元軌 曰：
「強寇在境，
人心不安，
若多所逮繋，
是驅之使叛也。」

乃獨殺 rm#ry0006@嘉運 ，
餘無所問，
因自劾違制。

上覽表大喜，
謂使者曰：
「朕亦悔之，
向無王，
失 dm#dm02124@定州 矣。」

自是朝廷有大事，
上多密敕問之。

# p 

壬子，
遣左金吾衞將軍 rm#r06198@曹懷舜 屯 dm#dm00409@井陘 ，
右武衞將軍 rm#r05224@崔獻 屯 dm#dm09269@龍門 ，
以備突厥。

突厥扇誘奚、契丹侵掠 dm#dm05611@營州 ，
都督 rm#r00473@周道務 遣戸曹 dm#dm01885@始平  rm#r00488@唐休璟 將兵撃破之。

# p 

庚申，
詔以突厥背誕，
罷封 dm#dm02514@嵩山 。

# p 

癸亥，
吐蕃 rm@文成公主 遣其大臣 rm#?@論塞調傍 來告喪，
幷請和親，
上遣郎將 rm#r05183@宋令文 詣吐蕃會贊普之葬。

# p 

十一月，
戊寅朔，
以太子左庶子、同中書門下三品 rm#r04246@高智周 爲御史大夫，
罷知政事。
# p 

癸未，
上宴 rm#r03460@裴行儉 ，
謂之曰：
「卿有文武兼資，
今授卿二職。」

乃除禮部尚書兼檢校右衞大將軍。

甲辰，
以 rm#r03460@行儉 爲 dm#dm02145@定襄道 行軍大總管，
將兵十八萬，
幷西軍檢校 dm#dm07478@豐州 都督 rm#r02987@程務挺 、東軍 dm#dm02689@幽州 都督 rm#r01790@李文暕 總三十餘萬以討突厥，
竝受 rm#r03460@行儉 節度。

 rm#r02987@務挺 ，
 rm#r01118@名振 之子也。

*** 二年
# year 0680
# p 

春，
二月，
癸丑，
上幸 dm#dm04465@汝州 之温湯；
戊午，
幸 dm#dm02514@嵩山 處士 dm#dm00119@三原  rm#r02834@田遊巖 所居；
己未，
幸道士 dm#dm02113@宗城  rm#r02519@潘師正 所居，
上及天后、太子皆拜之。

乙丑，
還 dm#dm03880@東都 。

# p 

三月，
 rm#r03460@裴行儉 大破突厥於 dm#dm09170@黒山 ，
擒其酋長 rm@奉職 ；
可汗 rm#r05998@泥熟匐 爲其下所殺，
以其首來降。

# p 

初，
 rm#r03460@行儉 行至 dm#dm03673@朔川 ，
謂其下曰：
「用兵之道，
撫士貴誠，
制敵貴詐。

前日 rm#r03235@蕭嗣業 糧運爲突厥所掠，
士卒凍餒，
故敗。

今突厥必復爲此謀，
宜有以詐之。」

乃詐爲糧車三百乘，
毎車伏壯士五人，
各持陌刀、勁弩，
以羸兵數百爲之援，
且伏精兵於險要以待之。

虜果至，
羸兵棄車散走。

虜驅車就水草，
解鞍牧馬，
欲取糧，
壯士自車中躍出，
撃之，
虜驚走，
復爲伏兵所邀，
殺獲殆盡，
自是糧運行者，
虜莫敢近。

# p 

軍至 dm#dm01397@單于府 北，
抵暮，
下營，
掘塹已周，
 rm#r03460@行儉 遽命移就高岡；
諸將皆言士卒已安堵，
不可復動，
 rm#r03460@行儉 不從，
趣使移。

是夜，
風雨暴至，
前所營地，
水深丈餘，
諸將驚服，
問其故，
 rm#r03460@行儉 笑曰：
「自今但從我命，
不必問其所由知也。」

# p 

 rm@奉職 既就擒，
餘黨走保 dm#dm05654@狼山 。

詔戸部尚書 rm#r00971@崔知悌 馳傳詣 dm#dm02141@定襄 宣慰將士，
且區處餘寇，
 rm#r03460@行儉 引軍還。


# p 

夏，
四月，
乙丑，
上幸 dm#dm06414@紫桂宮 。
# p 

戊辰，
黄門侍郎 dm#dm06601@聞喜  rm#r03449@裴炎 、 rm#r00972@崔知温 、中書侍郎 dm#dm00427@京兆  rm#r05626@王徳眞 竝同中書門下三品。

 rm#r00972@知温 ，
 rm#r00971@知悌 之弟也。
# p 

秋，
七月，
吐蕃寇 dm#dm04690@河源 ，
左武衞將軍 rm#r04339@黒齒常之 撃卻之。

擢 rm#r04339@常之 爲 dm#dm04691@河源軍 經略大使。

 rm#r04339@常之 以 dm#dm04690@河源 衝要，
欲加兵戍之，
而轉輸險遠，
乃廣置烽戍七十餘所，
開屯田五千餘頃，
歳收五百餘萬石，
由是戰守有備焉。


# p 

先是，
 dm#dm00785@劍南 募兵於 dm#dm06857@茂州 ，
西南築 dm#dm02025@安戎城 ，
以斷吐蕃通蠻之路。

吐蕃以生羌爲郷導，
攻陷其城，
以兵據之，
由是西洱諸蠻皆降於吐蕃。

吐蕃盡據羊同、黨項及諸羌之地，
東接 dm#*dm04947@涼 、 dm#dm03903@松 、 dm#dm06857@茂 、 dm#dm02536@巂 等州，
南鄰 dm#dm01752@天竺 ，
西陷 dm#dm09290@龜茲 、 dm#dm05857@疏勒 等四鎭，
北抵 dm#*dm06325@突厥 ，
地方萬餘里，
諸胡之盛，
莫與爲比。
# p 

丙申，
 dm#dm07949@鄭州 刺史 rm#r02400@江王元祥 薨。

# p 

突厥餘衆圍 dm#dm08566@雲州 ，
 dm#dm00485@代州 都督 rm#r05730@竇懷悊 ，
右領軍中郎將 rm#r02987@程務挺 將兵撃破之。

# p 

八月，
丁未，
上還 dm#dm03880@東都 。
# p 

中書令、檢校 dm#dm07964@鄯州 都督 rm#r01789@李敬玄 ，
軍既敗，
屡稱疾請還；
上許之。

既至，
無疾，
詣中書視事；
上怒，
丁巳，
貶 dm#dm07230@衡州 刺史。


** 永隆
*** 永隆元年
# year 0680
# p 

 rm#r03054@太子賢 聞宮中竊議，
以 rm#r03054@賢 爲天后姉 rm#ry0003@韓國夫人 所生，
内自疑懼。

 rm#r01443@明崇儼 以厭勝之術爲天后所信，
常密稱「太子不堪承繼，
 rm#r01656@英王 貌類 rm#r01602@太宗 」，
又言「 rm#r01797@相王 相最貴」。

天后嘗命北門學士撰少陽正範及孝子傳以賜太子，
又數作書誚讓之，
太子愈不自安。
# p 

及 rm#r01443@崇儼 死，
賊不得，
天后疑太子所爲。

太子頗好聲色，
與戸奴 rm#r05916@趙道生 等狎昵，
多賜之金帛，
司議郎 rm#r04034@韋承慶 上書諫，
不聽。

天后使人告其事。

詔 rm#r03274@薛元超 、 rm#r03449@裴炎 與御史大夫 rm#r04246@高智周 等雜鞫之，
於東宮馬坊搜得皂甲數百領，
以爲反具；
 rm#r05916@道生 又款稱太子使 rm#r05916@道生 殺 rm#r01443@崇儼 。

上素愛太子，
遲囘欲宥之，
天后曰：
「爲人子懷逆謀，
天地所不容；
大義滅親，
何可赦也！」

甲子，
廢 rm#r03054@太子賢 爲庶人，
遣右監門中郎將 rm#r05016@令狐智通 等送 rm#r03054@賢 詣 dm#dm08170@京師 ，
幽於別所，
黨與皆伏誅，
仍焚其甲於 dm#dm01750@天津橋 南以示士民。

 rm#r04034@承慶 ，
 rm#r04002@思謙 之子也。

# p 

乙丑，
立左衞大將軍、 dm#dm08502@雍州 牧 rm#r01656@英王哲 爲皇太子，
改元，
赦天下。
# p 

太子洗馬 rm#r00319@劉訥言 常撰俳諧集以獻 rm#r03054@賢 ，
 rm#r03054@賢 敗，
搜得之，
上怒曰：
「以六經教人，
猶恐不化，
乃進俳諧鄙説，
豈輔導之義邪！」

流 rm#r00319@訥言 於 dm#dm03227@振州 。

# p 

左衞將軍 rm#r04257@高眞行 之子 rm@政 爲太子典膳丞，
事與 rm#r03054@賢 連，
上以付其父，
使自訓責。

 rm@政 入門，
 rm#r04257@眞行 以佩刀刺其喉，
 rm#r04257@眞行 兄戸部侍郎 rm#r04234@審行 又刺其腹，
 rm#r04257@眞行 兄子 rm@琁 斷其首，
棄之道中。

上聞之，
不悦，
貶 rm#r04257@眞行 爲 dm#dm06059@睦州 刺史，
 rm#r04234@審行 爲 dm#dm05090@渝州 刺史。

 rm#r04257@眞行 ，
 rm#r04217@士廉 之子也。

# p 

左庶子、中書門下三品 rm#r01130@張大安 坐阿附太子，
左遷 dm#dm03579@普州 刺史。

其餘宮僚，
上皆釋其罪，
使復位，
左庶子 rm#r03274@薛元超 等皆舞蹈拜恩；
右庶子 rm#r01924@李義琰 獨引咎涕泣，
時論美之。同
# p 

九月，
甲申，
以中書侍郎、同中書門下三品 rm#r05626@王徳眞 爲 rm@相王 府長史，
罷政事。

# p 

冬，
十月，
壬寅，
 dm#dm07147@蘇州 刺史 rm#r01527@曹王明 ，
 dm#dm04581@沂州 刺史 rm#r03208@嗣蒋王煒 ，
皆坐故太子 rm#r03054@賢 之黨，
 rm#r01527@明 降封 rm#r01527@零陵郡王 ，
 dm#dm09188@黔州 安置；
 rm#r03208@煒 除名，
 dm#dm07742@道州 安置。

# p 

丙午，
 rm@文成公主 薨于吐蕃。
# p 

己酉，
車駕西還。
# p 

十一月，
壬申朔，
日有食之。
*** 二年
# year 0681
# p 

春，
正月，
突厥寇 dm#dm01114@原 、 dm#dm03083@慶 等州。

乙亥，
遣右衞將軍 rm#r05421@李知十 等屯 dm#dm04919@涇 、 dm#dm03083@慶 二州以備突厥。

# p 

庚辰，
以初立太子，
敕宴百官及命婦於 dm#dm02221@宣政殿 ，
引九部伎及散樂自 dm#dm02222@宣政門 入。

太常博士 rm#r03373@袁利貞 上疏，
以爲：
「正寢非命婦宴會之地，
路門非倡優進御之所，
請命婦會於別殿，
九部伎自東西門入，
其散樂伏望停省。」

上乃更命置宴於 dm#dm09095@麟徳殿 ；
宴日，
賜 rm#r03373@利貞 帛百段。

 rm#r03373@利貞 ，
 rm#r06767@昂 之曾孫也。
# p 

 rm#r03373@利貞 族孫 rm#r03393@誼 爲 dm#dm07147@蘇州 刺史，
自以其先自 dyn#ch164@宋 太尉 rm#r06768@淑 以來，
盡忠帝室，
謂 dm#dm05740@琅邪  rm#no@王氏 雖奕世臺鼎，
而爲歴代佐命，
恥與爲比，
嘗曰：
「所貴於名家者，
爲其世篤忠貞，
才行相繼故也。

彼鬻婚姻求祿利者，
又烏足貴乎！」

時人是其言。

# p 

 rm#r03460@裴行儉 軍既還，
突厥 rm#r06268@阿史那伏念 復自立爲可汗，
與 rm#r05571@阿史徳温傅 連兵爲寇。

癸巳，
以 rm#r03460@行儉 爲 dm#dm02145@定襄道 大總管，
以右武衞將軍 rm#r06198@曹懷舜 、 dm#dm02689@幽州 都督 rm#r01790@李文暕 爲副，
將兵討之。

# p 

二月，
天后表請赦 rm#r02521@𣏌王上金 、 rm#r03522@鄱陽王素節 之罪；
以 rm#r02521@上金 爲 dm#dm04607@沔州 刺史，
 dyn#r03522@素節 爲 dm#dm02432@嶽州 刺史，
仍不聽朝集。

# p 

三月，
辛卯，
以 rm#r00192@劉仁軌 兼太子少傅，
餘如故。

以侍中 rm#r03702@郝處俊 爲太子少保，
罷政事。
# p 

少府監 rm#r05841@裴匪舒 ，
善營利，
奏賣苑中馬糞，
歳得錢二十萬緡。

上以問 rm#r00192@劉仁軌 ，
對曰：
「利則厚矣，
恐後代稱 dyn#ch100@唐家 賣馬糞，
非嘉名也。」

乃止。

 rm#r05841@匪舒 又爲上造 dm#dm08138@鏡殿 ，
成，
上與 rm#r00192@仁軌 觀之，
 rm#r00192@仁軌 驚趨下殿。

上問其故，
對曰：
「天無二日，
土無二王，
適視四壁有數天子，
不祥孰甚焉！」

上遽令剔去。

# p 

 rm#r06198@曹懷舜 與裨將 rm#r05732@竇義昭 將前軍撃突厥。

或告「 rm#r06268@阿史那伏念 與 rm#r05571@阿史徳温傅 在 dm#dm09178@黒沙 ，
左右纔二十騎以下，
可徑往取也。」

 rm#r06198@懷舜 等信之，
留老弱於 dm#dm05779@瓠蘆泊 ，
帥輕鋭倍道進，
至 dm#dm09178@黒沙 ，
無所見，
人馬疲頓，
乃引兵還。北
# p 

會 dm#dm07112@薛延陀 部落欲西詣 rm#r06268@伏念 ，
遇 rm#r06198@懷舜 軍，
因請降。

 rm#r06198@懷舜 等引兵徐還，
至長城北，
遇 rm#r05571@温傅 ，
小戰，
各引去。

至 dm#dm04186@横水 ，
遇 rm#r06268@伏念 ，
 rm#r06198@懷舜 、 rm#?@義昭 與 rm#r01790@李文暕 及裨將 rm#r05071@劉敬同 四軍合爲方陳，
且戰且行；
經一日，
 rm#r06268@伏念 乘便風撃之，
軍中擾亂，
 rm#r06198@懷舜 等棄軍走，
軍遂大敗，
死者不可勝數。

 rm#r06198@懷舜 等收散卒，
斂金帛以賂 rm#r06268@伏念 ，
與之約和，
殺牛爲盟。

 rm#r06268@伏念 北去，
 rm#r06198@懷舜 等乃得還。

# p 

夏，
五月，
丙戌，
 rm#r06198@懷舜 免死，
流 dm#dm02527@嶺南 。
# p 

己丑，
 dm#dm04692@河源道 經略大使 rm#r04339@黒齒常之 將兵撃吐蕃 rm#r05866@論贊婆 於 dm#dm06811@良非川 ，
破之，
收其糧畜而還。

 rm#r04339@常之 在軍七年，
吐蕃深畏之，
不敢犯邊。


# p 

初，
 rm#r02300@太原王 𡚱之薨也，
天后請以 rm#r00603@太平公主 爲女官以追福。

及吐蕃求和親，
請尚 rm#r00603@太平公主 ，
上乃爲立 dm#dm01797@太平觀 ，
以公主爲觀主以拒之。

至是，
始選光祿卿 dm#dm04568@汾陰  rm#r03301@薛曜 之子 rm#r05819@紹 尚焉。

 rm#r05819@紹 母，
 rm#r01602@太宗 女 rm#r00581@城陽公主 也。

# p 

秋，
七月，
公主適，
自 dm#dm06767@興安門 南至 dm#dm02233@宣陽坊 西，
燎炬相屬，
夾路槐木多死。

 rm#r05819@紹 兄 rm#r03320@顗 以公主寵盛，
深憂之，
以問族祖戸部郎中 rm#r03275@克構 ，
 rm#r03275@克構 曰：
「帝甥尚主，
國家故事，
苟以恭愼行之，
亦何傷！

然諺曰：
『娶婦得公主，
無事取官府。』

不得不爲之懼也。」

# p 

天后以 rm#r03320@顗 妻 rm#?@蕭氏 及 rm#r03320@顗 弟 rm#?@緒 妻 rm#?@成氏 非貴族，
欲出之，
曰：
「我女豈可使與田舍女爲妯娌邪！」

或曰：
「 rm#?@蕭氏 ，
 rm#r03249@瑀 之姪孫，
國家舊姻。」

乃止。
# p 

 dm#dm01538@夏州 羣牧使 rm#r05172@安元壽 奏：
「自 y@調露元年九月 以來，
喪馬一十八萬餘匹，
監牧吏卒爲虜所殺掠者八百餘人。」


# p 

薛延陀 dm#dm07750@達渾 等五州四萬餘帳來降。


# p 

甲午，
左僕射兼太子少傅、同中書門下三品 rm#r00192@劉仁軌 固請解僕射，
許之。
# p 

閏七月，
丁未，
 rm#r03449@裴炎 爲侍中，
 rm#r00972@崔知温 、 rm#r03274@薛元超 竝守中書令。
# p 

上徵 rm#r02834@田遊巖 爲太子洗馬，
在東宮無所規益。

右衞副率 rm#r03214@蒋儼 以書責之曰：
「足下負 rm#?@巣 、 rm#?@由 之俊節，
傲 rm#rt0006@唐 、 rm#rt0007@虞 之聖主，
聲出區宇，
名流海内。

主上屈萬乘之重，
申三顧之榮，
遇子以 dm#dm01377@商山 之客，
待子以不臣之禮，
將以輔導儲貳，
漸染芝蘭耳。

皇太子春秋鼎盛，
聖道未周，
僕以不才，
猶參庭諍，
足下受調護之寄，
是可言之秋，
唯唯而無一談，
悠悠以卒年歳。

向使不餐 dyn#ch103@周 粟，
僕何敢言！

祿及親矣，
以何酬塞？
想爲不達，
謹書起豫。」

 rm#r02834@遊巖 竟不能答。
# p 

庚申，
上以服餌，
令太子監國。

# p 

 rm#r03460@裴行儉 軍于 dm#dm00485@代州 之 dm#dm08312@陘口 ，
多縱反間，
由是 rm#r06268@阿史那伏念 與 rm#r05571@阿史徳温傅 浸相猜貳。

 rm#r06268@伏念 留妻子輜重於 dm#dm08046@金牙山 ，
以輕騎襲 rm#r06198@曹懷舜 。

 rm#r03460@行儉 遣裨將 rm#r05029@何迦密 自 dm#dm07696@通漠道 ，
 rm#r02987@程務挺 自 dm#dm06076@石地道 掩取之。

 rm#r06268@伏念 與 rm#r06198@曹懷舜 約和而還，
比至 dm#dm08046@金牙山 ，
失其妻子輜重，
士卒多疾疫，
乃引兵北走 dm#dm06421@細沙 ，
 rm#r03460@行儉 又使副總管 rm#r05071@劉敬同 、 rm#r02987@程務挺 等將 dm#dm01397@單于府 兵追躡之。

 rm#r06268@伏念 請執 rm#r05571@温傅 以自效，
然尚猶豫，
又自恃道遠，
 dyn#ch100@唐 兵必不能至，
不復設備。

 rm#r05071@敬同 等軍到，
 rm#r06268@伏念 狼狽，
不能整其衆，
遂執 rm#r05571@温傅 ，
從間道詣 rm#r03460@行儉 降。

候騎告以塵埃漲天而至，
將士皆震恐，
 rm#r03460@行儉 曰：
「此乃 rm#r06268@伏念 執 rm#r05571@温傅 來降，
非他盜也。

然受降如受敵，
不可無備。」

乃命嚴備，
遣單使迎前勞之。

少選，
 rm#r06268@伏念 果帥酋長縛 rm#r05571@温傅 詣軍門請罪。

 rm#r03460@行儉 盡平突厥餘黨，
以 rm#r06268@伏念 、 rm#r05571@温傅 歸 dm#dm08170@京師 。

# p 

冬，
十月，
丙寅朔，
日有食之。
** 開耀
*** 開耀元年
# year 0681
# p 

壬戌，
 rm#r03460@裴行儉 等獻 dm#dm02141@定襄 之俘。

乙丑，
改元。

丙寅，
斬 rm#r06268@阿史那伏念 、 rm#r05571@阿史徳温傅 等五十四人於都市。

# p 

初，
 rm#r03460@行儉 許 rm#r06268@伏念 以不死，
故降。

 rm#r03449@裴炎 疾 rm#r03460@行儉 之功，
奏言：
「 rm#r06268@伏念 爲副將 rm#r06190@張虔勗 、 rm#r02987@程務挺 所逼，
又囘紇等自磧北南向逼之，
窮窘而降耳。」

遂誅之。

 rm#r03460@行儉 歎曰：
「 rm#?@渾 、 rm#?@濬 爭功，
古今所恥。

但恐殺降，
無復來者。」

因稱疾不出。
# p 

丁亥，
 rm@新羅王  rm@法敏 卒，
遣使立其子 rm#?@政明 。
# p 

十一月，
癸卯，
徙故太子 rm#r03054@賢 於 dm#dm02572@巴州 。


*** 開耀二年
# year 0682
# p 

春，
二月，
作 dm#dm06985@萬泉宮 於 dm#dm07121@藍田 。

** 永淳
*** 永淳元年
# year 0682
# p 

癸未，
改元，
赦天下。
# p 

戊午，
立皇孫 rm#r03834@重照 爲皇太孫。

上欲令開府置官屬，
問吏部郎中 rm#r02684@王方慶 ，
對曰：
「 dyn#ch537@晉 及 dyn#ch165@齊 皆嘗立太孫，
其太子官屬即爲太孫官屬，
未聞太子在東宮而更立太孫者也。」

上曰：
「自我作古，
可乎？」
對曰：
「三王不相襲禮，
何爲不可！」

乃奏置師傅等官。

既而上疑其非法，
竟不補授。

 rm#r02684@方慶 ，
 rm#r06710@裒 之曾孫也。

名 rm#r02684@綝 ，
以字行。


# p 

 dm#dm07372@西突厥  rm#r06000@阿史那車薄 帥十姓反。

# p 

夏，
四月，
甲子朔，
日有食之。
# p 

上以 dm#dm08281@關中 饑饉，
米斗三百，
將幸東都；
丙寅，
發 dm#dm08170@京師 ，
留太子監國，
使 rm#r00192@劉仁軌 、 rm#r03449@裴炎 、 rm#r03274@薛元超 輔之。

時出幸倉猝，
扈從之士有餓死於中道者。

上慮道路多草竊，
命監察御史 rm#r04302@魏元忠 檢校車駕前後。

 rm#r04302@元忠 受詔，
即閲視赤縣獄，
得盜一人，
神采語言異於衆；
命釋桎梏，
襲冠帶，
乘驛以從，
與之共食宿，
託以詰盜，
其人笑許諾。

比及 dm#dm03880@東都 ，
士馬萬數，
不亡一錢。
# p 

辛未，
以禮部尚書 rm#r03460@聞喜憲公裴行儉 爲 dm#dm08047@金牙道 行軍大總管，
帥右金吾將軍 rm#r05982@閻懷旦 等三總管分道討西突厥。

師未行，
 rm#r03460@行儉 薨。
# p 

 rm#r03460@行儉 有知人之鑒，
初爲吏部侍郎，
前進士 rm#r02725@王勮 、 dm#dm01345@咸陽 尉 dm#dm04202@欒城  rm#r03329@蘇味道 皆未知名，
 rm#r03460@行儉 一見謂之曰：
「二君後當相次掌銓衡，
僕有弱息，
願以爲託。」

是時 rm#r02725@勮 弟 rm#r02601@勃 與 dm#dm06943@華陰  rm#r02142@楊烱 、 dm#dm06863@范陽  rm#r02917@盧照鄰 、 dm#dm06553@義烏  rm#r04206@駱賓王 皆以文章有盛名，
司列少常伯 rm#r01789@李敬玄 尤重之，
以爲必顯達。

 rm#r03460@行儉 曰：
「士之致遠，
當先器識而後才藝。

 rm#r02601@勃 等雖有文華，
而浮躁淺露，
豈享爵祿之器邪！

 rm#r02142@楊子 稍沈靜，
應至令長；
餘得令終幸矣。」

既而 rm#r02601@勃 度海墮水，
 rm#r02142@烱 終於 dm#dm05978@盈川 令，
 rm#r02917@照鄰 惡疾不愈，
赴水死，
 rm#r04206@賓王 反誅，
 rm#r02725@勮 、 rm#r03329@味道 皆典選，
如 rm#r03460@行儉 言。

 rm#r03460@行儉 爲將帥，
所引偏裨如 rm#r02987@程務挺 、 rm#r06190@張虔勗 、 rm#r02644@王方翼 、 rm#r05071@劉敬同 、 rm#r01671@李多祚 、 rm#r04339@黒齒常之 ，
後多爲名將。

# p 

 rm#r03460@行儉 常命左右取犀角、麝香而失之。

又敕賜馬及鞍，
令史輒馳驟，
馬倒，
鞍破。

二人皆逃去，
 rm#r03460@行儉 使人召還，
謂曰：
「爾曹皆誤耳，
何相輕之甚邪！」

待之如故。

破 rm#r06001@阿史那都支 ，
得馬腦盤，
廣二尺餘，
以示將士，
軍吏 rm#r05603@王休烈 捧盤升階，
跌而碎之，
惶恐，
叩頭流血。

 rm#r03460@行儉 笑曰：
「爾非故爲，
何至於是！」

不復有追惜之色。

詔賜 rm#r06001@都支 等資産金器三千餘物，
雜畜稱是，
竝分給親故及偏裨，
數日而盡。


# p 

 rm#r06000@阿史那車薄 圍 dm#dm02876@弓月城 ，
 dm#dm02061@安西 都護 rm#r02644@王方翼 引軍救之，
破虜衆於 dm#dm00521@伊麗水 ，
斬首千餘級。

俄而三姓 rm#?@咽麪 與 rm#r06000@車薄 合兵拒 rm#r02644@方翼 ，
 rm#r02644@方翼 與戰於 dm#dm05593@熱海 ，
流矢貫 rm#r02644@方翼 臂，
 rm#r02644@方翼 以佩刀截之，
左右不知。

所將胡兵謀執 rm#r02644@方翼 以應 rm#r06000@車薄 ，
 rm#r02644@方翼 知之，
悉召會議，
陽出軍資賜之，
以次引出斬之，
會大風，
 rm#r02644@方翼 振金鼓以亂其聲，
誅七十餘人，
其徒莫之覺。

既而分遣裨將襲 rm#r06000@車薄 、 rm#?@咽麪 ，
大破之，
擒其酋長三百人，
西突厥遂平。

 rm#r05982@閻懷旦 竟不行。

 rm#r02644@方翼 尋遷 dm#dm01538@夏州 都督，
徵入，
議邊事。

上見 rm#r02644@方翼 衣有血漬，
問之，
 rm#r02644@方翼 具對 dm#dm05593@熱海 苦戰之状，
上視瘡歎息；
竟以廢后近屬，
不得用而歸。

# p 

乙酉，
車駕至 dm#dm03880@東都 。
# p 

丁亥，
以黄門侍郎 dm#dm05331@潁川  rm#r05940@郭待舉 、兵部侍郎 rm#r00882@岑長倩 、祕書員外少監‧檢校中書侍郎 dm#dm09202@鼓城  rm#r03730@郭正一 、吏部侍郎 dm#dm09202@鼓城  rm#r04301@魏玄同 竝與中書門下同承受進止平章事。

上欲用 rm#r05940@待舉 等，
謂 rm#ry0008@韋知温 曰：
「 rm#r05940@待舉 等資任尚淺，
且令預聞政事，
未可與卿等同名。」

自是外司四品已下知政事者，
始以平章事爲名。

 rm#r00882@長倩 ，
 rm#r00879@文本 之兄子也。

韋崔
# p 

先是，
 rm#r04301@玄同 爲吏部侍郎，
上言銓選之弊，
以爲：
「人君之體，
當委任而責成功，
所委者當，
則所用者自精矣。

故 rm#rt0068@周穆王 命 rm#?@伯冏 爲太僕正，
曰：
『愼簡乃僚。』

是使羣司各求其小者，
而天子命其大者也。

乃至 rm@漢氏 ，
得人皆自州縣補署，
五府辟召，
然後升於天朝，
自 dyn#ch134@魏 、 dyn#ch537@晉 以來，
始專委選部。

夫以天下之大，
士人之衆，
而委之數人之手，
用刀筆以量才，
按簿書而察行，
借使平如權衡，
明如水鏡，
猶力有所極，
照有所窮，
況所委非人而有愚闇阿私之弊乎！

願略依 dyn#ch103@周 、 dyn#ch130@漢 之規以救 dyn#ch134@魏 、 dyn#ch537@晉 之失。」

疏奏，
不納。
# p 

五月，
 dm#dm03880@東都 霖雨。

乙卯，
 dm#dm04780@洛水 溢，
溺民居千餘家。

 dm#dm08281@關中 先水後旱、蝗，
繼以疾疫，
米斗四百，
 dm#dm00683@兩京 間死者相枕於路，
人相食。丙午
# p 

上既封 dm#dm04750@泰山 ，
欲遍封 dm#dm00097@□□ ，
秋，
七月，
作 dm#dm01855@奉天宮 於 dm#dm02515@嵩山南 。

監察御史裏行 rm#r05344@李善感 諫曰：
「陛下封 dm#dm04750@泰山 ，
告太平，
致羣瑞，
與 rm#gr@三皇 、 rm#gr@五帝 比隆矣。

數年以來，
菽粟不稔，
餓殍相望，
四夷交侵，
兵車歳駕；
陛下宜恭默思道以禳災譴，
乃更廣營宮室，
勞役不休，
天下莫不失望。

臣忝備國家耳目，
竊以此爲憂！」

上雖不納，
亦優容之。

自 rm#r03475@褚遂良 、 rm#r04125@韓瑗 之死，
中外以言爲諱，
無敢逆意直諫，
幾二十年；
及 rm#r05344@善感 始諫，
天下皆喜，
謂之「鳳鳴朝陽」。
□□五嶽
# p 

上遣宦者縁 dm#dm04475@江 徙異竹，
欲植苑中。

宦者科舟載竹，
所在縱暴；
過 dm#dm06884@荊州 ，
 dm#dm06884@荊州 長史 rm#r03343@蘇良嗣 囚之，
上疏切諫，
以爲：
「致遠方異物，
煩擾道路，
恐非聖人愛人之意。

又，
小人竊弄威福，
虧損皇明。」

上謂天后曰：
「吾約束不嚴，
果爲 rm#r03343@良嗣 所怪。」

手詔慰諭 rm#r03343@良嗣 ，
令棄竹 dm#dm04475@江 中。

 rm#r03343@良嗣 ，
 rm#r03326@世長 之子也。

# p 

 dm#dm09188@黔州 都督 rm#r03536@謝祐 希天后意，
逼 rm#r01527@零陵王明 令自殺，
上深惜之，
 dm#dm09190@黔府 官屬皆坐免官。

 rm#r03536@祐 後寢於平閣，
與婢妾十餘人共處，
夜，
失其首。

 y@垂拱中 ，
 rm#r01527@明 子 rm#r03982@零陵王俊 、 rm#r04336@黎國公  rm#r04336@傑 爲天后所殺，
有司籍其家，
得祐首，
漆爲穢器，
題云 rm#r03536@謝祐 ，
乃知 rm#r01527@明 子使刺客取之也。
# p 

太子留守 dm#dm08170@京師 ，
頗事遊畋，
 rm#r03274@薛元超 上疏規諫；
上聞之，
遣使者慰勞 rm#r03274@元超 ，
仍召赴 dm#dm03880@東都 。
# p 

吐蕃將 rm#xjts01678@論欽陵 寇 dm#dm03960@柘 、 dm#dm03903@松 、 dm#dm06576@翼 等州。

詔左驍衞郎將 rm#r02121@李孝逸 、右衞郎將 rm#r05002@衞蒲山 發 dm#dm06273@秦 、 dm#dm05102@渭 等州兵分道禦之。

# p 

冬，
十月，
丙寅，
黄門侍郎 rm#r03514@劉景先 同中書門下平章事。
# p 

是歳，
突厥餘黨 rm#r06002@阿史那骨篤祿 、 rm#r05048@阿史徳元珍 等招集亡散，
據 dm#dm09178@黒沙城 反，
入寇 dm#dm00059@幷州 及 dm#dm01397@單于府 之北境，
殺 dm#dm02511@嵐州 刺史 rm#r05627@王徳茂 。

右領軍衞將軍、檢校 dm#dm00485@代州 都督 rm#r03268@薛仁貴 將兵撃 rm#r05048@元珍 於 dm#dm08566@雲州 ，
虜問 dyn#ch100@唐 大將爲誰，
應之曰：
「 rm#r03268@薛仁貴 」。

虜曰：
「吾聞 rm#r03268@仁貴 流 dm#dm07496@象州 ，
死久矣，
何以紿我！」

 rm#r03268@仁貴 免冑示之面，
虜相顧失色，
下馬列拜，
稍稍引去。

 rm#r03268@仁貴 因奪撃，
大破之，
斬首萬餘級，
捕虜二萬餘人。
# p 

吐蕃入寇 dm#dm04691@河源軍 ，
軍使 rm#r00657@婁師徳 將兵撃之於 dm#dm05889@白水澗 ，
八戰八捷。

上以師徳爲比部員外郎、左驍衞郎將、 dm#dm04691@河源軍 經略副使，
曰：
「卿有文武材，
勿辭也！」


*** 二年
# year 0683
# p 

春，
正月，
甲午朔，
上行幸 dm#dm01855@奉天宮 。
# p 

二月，
庚午，
突厥寇 dm#dm02124@定州 ，
刺史 rm#r03988@霍王元軌 撃卻之。

乙亥，
復寇 dm#dm01931@媯州 。

三月，
庚寅，
 rm#r06002@阿史那骨篤祿 、 rm#r05048@阿史徳元珍 圍 dm#dm01400@單于都護府 ，
執司馬 rm#r05298@張行師 ，
殺之。

遣 dm#dm00812@勝州 都督 rm#r01148@王本立 、 dm#dm01538@夏州 都督 rm#r05376@李崇義 將兵分道救之。
# p 

太子右庶子、同中書門下三品 rm#r01924@李義琰 改葬父母，
使其舅氏遷舊墓；
上聞之，
怒曰：
「 rm#r01924@義琰 倚勢，
乃陵其舅家，
不可復知政事！

」
 rm#r01924@義琰 聞之，
不自安，
以足疾乞骸骨，
庚子，
以 rm#r01924@義琰 爲銀青光祿大夫，
致仕。
# p 

癸丑，
守中書令 rm#r00972@崔知温 薨。

# p 

夏，
四月，
己未，
車駕還 dm#dm03880@東都 。
# p 

 dm#dm06439@綏州 歩落稽 rm#r05690@白鐵餘 ，
埋銅佛於地中，
久之，
草生其上，
紿其郷人曰：
「吾於此數見佛光。

」
擇日集衆掘地，
果得之，
因曰：
「得見聖佛者，
百疾皆愈。」

遠近赴之。

 rm#r05690@鐵餘 以雜色嚢盛之數十重，
得厚施，
乃去一嚢。

數年間，
歸信者衆，
遂謀作亂。

據 dm#dm01484@城平縣 ，
自稱 rm#r05690@光明聖皇帝 ，
置百官，
進攻 dm#dm06442@綏徳 、 dm#dm01626@大斌 二縣，
殺官吏，
焚民居。

遣右武衞將軍 rm#r02987@程務挺 與 dm#dm01538@夏州 都督 rm#r02644@王方翼 討之，
甲申，
攻拔其城，
擒 rm#r05690@鐵餘 ，
餘黨悉平。

# p 

五月，
庚寅，
上幸 dm#dm06838@芳桂宮 ，
至 dm#dm01202@合璧宮 ，
遇大雨而還。
# p 

乙巳，
突厥 rm#r06002@阿史那骨篤祿 等寇 dm#dm07077@蔚州 ，
殺刺史 rm#r05386@李思儉 ，
 dm#dm07478@豐州 都督 rm#r05220@崔智辯 將兵邀之於 dm#dm03718@朝那山 北，
兵敗，
爲虜所擒。

朝議欲廢 dm#dm07478@豐州 ，
遷其百姓於 dm#dm08619@靈 、 dm#dm01532@夏 。

 dm#dm07478@豐州 司馬 rm#r00488@唐休璟 上言，
以爲：
「 dm#dm07478@豐州 阻河爲固，
居賊衝要，
自 dyn#ch128@秦 、 dyn#ch129@漢 已來，
列爲郡縣；
土宜耕牧。

 dyn#ch174@隋 季喪亂，
遷百姓於 dm#dm02291@寧 、 dm#dm03083@慶 二州，
致胡虜深侵，
以 dm#dm08619@靈 、 dm#dm01532@夏 爲邊境；
 y@貞觀 之末，
募人實之，
西北始安。

今廢之則 dm#dm04650@河 濱之地復爲賊有，
 dm#dm08619@靈 、 dm#dm01532@夏 等州人不安業，
非國家之利也！」

乃止。


# p 

六月，
突厥別部寇掠 dm#dm02511@嵐州 ，
偏將 rm#r05508@楊玄基 撃走之。

# p 

秋，
七月，
己丑，
立皇孫 rm#r00502@重福 爲 rm#r00502@唐昌王 。

# p 

庚辰，
詔以 y@今年十月 有事於 dm#dm02514@嵩山 ；
尋以上不豫，
改用 y@來年正月 。庚壬
# p 

甲辰，
徙 rm#r01797@相王輪 爲 rm#r01797@豫王 ，
更名 rm#r01797@旦 。

# p 

中書令兼太子左庶子 rm#r03274@薛元超 病瘖，
乞骸骨，
許之。

# p 

八月，
己丑，
以將封 dm#dm02514@嵩山 ，
召太子赴 dm#dm03880@東都 ；
留 rm#r00502@唐昌王重福 守 dm#dm08170@京師 ，
以 rm#r00192@劉仁軌 爲之副。

冬，
十月，
己卯，
太子至 dm#dm03880@東都 。
# p 

癸亥，
車駕幸 dm#dm01855@奉天宮 。
# p 

十一月，
丙戌，
詔罷 y@來年 封 dm#dm02514@嵩山 ，
上疾甚故也。

上苦頭重，
不能視，
召侍醫 rm#r05720@秦鳴鶴 診之，
 rm#r05720@鳴鶴 請刺頭出血，
可愈。

天后在簾中，
不欲上疾愈，
怒曰：
「此可斬也，
乃欲於天子頭刺血！」

 rm#r05720@鳴鶴 叩頭請命。

上曰：
「但刺之，
未必不佳。」

乃刺百會、腦戸二穴。

上曰：
「吾目似明矣。」

后舉手加額曰：
「天賜也！」

自負綵百匹以賜 rm#r05720@鳴鶴 。
# p 

戊戌，
以右武衞將軍 rm#r02987@程務挺 爲 dm#dm01399@單于道 安撫大使，
招討 rm#r06002@阿史那骨篤祿 等。


# p 

詔太子監國，
以 rm#r03449@裴炎 、 rm#r03514@劉景先 、 rm#r03730@郭正一 同東宮平章事。
# p 

上自 dm#dm01855@奉天宮 疾甚，
宰相皆不得見。

丁未，
還 dm#dm03880@東都 ，
百官見於 dm#dm01750@天津橋 南。

** 弘道
# p 

十二月，
丁巳，
改元，
赦天下。

上欲御 dm#dm00765@則天門 樓宣赦，
氣逆不能乘馬，
乃召百姓入殿前宣之。

是夜，
召 rm#r03449@裴炎 入，
受遺詔輔政，
上崩於 dm#dm07516@貞觀殿 。

遺詔太子柩前即位，
軍國大事有不決者，
兼取天后進止。

廢 dm#dm06986@萬泉 、 dm#dm06838@芳桂 、 dm#dm01853@奉天 等宮。
# p 

庚申，
 rm#r03449@裴炎 奏太子未即位，
未應宣敕，
有要速處分，
望宣天后令於中書、門下施行。

甲子，
 rm#r01656@中宗 即位，
尊天后爲皇太后，
政事咸取決焉。

太后以 dm#dm05400@澤州 刺史 rm#r04123@韓王元嘉 等，
地尊望重，
恐其爲變，
竝加三公等官以慰其心。
# p 

甲戌，
以 rm#r00192@劉仁軌 爲左僕射，
 rm#r03449@裴炎 爲中書令；
戊寅，
以 rm#r03514@劉景先 爲侍中。
# p 

故事，
宰相於門下省議事，
謂之政事堂，
故 rm#r03856@長孫無忌 爲司空，
 rm#r01377@房玄齡 爲僕射，
 rm#r04294@魏徵 爲太子太師，
皆知門下省事。

及 rm#r03449@裴炎 遷中書令，
始遷政事堂於中書省。
# p 

壬午，
遣左威衞將軍 rm#r05643@王果 、左監門將軍 rm#r05016@令狐智通 、右金吾將軍 rm#r05507@楊玄儉 、右千牛將軍 rm@郭齊宗 分往 dm#dm00058@幷 ‧ dm#dm05982@益 ‧ dm#dm06880@荊 ‧ dm#dm03240@揚 四大都督府，
與府司相知鎭守。

# p 

中書侍郎同平章事 rm#r03730@郭正一 爲國子祭酒，
罷政事。
** 嗣聖
*** 嗣聖元年
# year 0684
# p 

春，
正月，
甲申朔，
改元 y@嗣聖 ，
赦天下。
# p 

立太子𡚱 rm#r00840@韋氏 爲皇后；
擢后父 rm#r03832@玄貞 自 dm#dm03579@普州 參軍爲 dm#dm07502@豫州 刺史。

# p 

癸巳，
以左散騎常侍 dm#dm03772@杜陵  rm#r06044@韋弘敏 爲太府卿、同中書門下三品。

# p 

 rm#r01656@中宗 欲以 rm#r03832@韋玄貞 爲侍中，
又欲授乳母之子五品官；
 rm#r03449@裴炎 固爭，
 rm#r01656@中宗 怒曰：
「我以天下與 rm#r03832@韋玄貞 何不可！

而惜侍中邪！」

 rm#r03449@炎 懼，
白太后，
密謀廢立。

二月，
戊午，
太后集百官於 dm#dm00347@乾元殿 ，
 rm#r03449@裴炎 與中書侍郎 rm#r00301@劉禕之 、羽林將軍 rm#r02987@程務挺 、 rm#r06190@張虔勗 勒兵入宮，
宣太后令，
廢 rm#r01656@中宗 爲 rm#r01656@廬陵王 ，
扶下殿。

 rm#r01656@中宗 曰：
「我何罪？」
太后曰：
「汝欲以天下與 rm#r03832@韋玄貞 ，
何得無罪！」

乃幽于別所。
# p 

己未，
立 dm#dm08502@雍州 牧 rm#r01797@豫王旦 爲皇帝。

政事決於太后，
居 rm#r01797@睿宗 於別殿，
不得有所預。

立 rm#r01797@豫王 𡚱 rm@劉氏 爲皇后。

后，
 rm#r00252@徳威 之孫也。

# p 

有飛騎十餘人飮於坊曲，
一人言：
「曏知別無勳賞，
不若奉 dm#dm02796@廬陵 。」

一人起，
出詣北門告之。

座未散，
皆捕得，
繋羽林獄。

言者斬，
餘以知反不告皆絞；
告者除五品官。

告密之端自此興矣。
** 文明
*** 文明元年
# year 0684
# p 

壬子，
以 rm#r02384@永平郡王成器 爲皇太子，
 rm#r01797@睿宗 之長子也。

赦天下，
改元 y@文明 。

# p 

庚申，
廢皇太孫 rm#r03834@重照 爲庶人，
命 rm#r00192@劉仁軌 專知 dm#dm07290@西京 留守事。

流 rm#r03832@韋玄貞 於 dm#dm04208@欽州 。

# p 

太后與 rm#r00192@劉仁軌 書曰：
「昔 dyn#ch129@漢 以 dm#dm08281@關中 事委 rm#r06244@蕭何 ，
今託公亦猶是矣。」

 rm#r00192@仁軌 上疏，
辭以衰老不堪居守，
因陳 rm@呂后 禍敗事以申規戒。

太后使祕書監 rm#r02314@武承嗣 齎璽書慰諭之曰：
「今以皇帝諒闇不言，
眇身且代親政；
遠勞勸戒，
復辭衰疾。

又云『 rm@呂氏 見嗤於後代，
 rm#ry0026@祿 、 rm#ry0025@産 貽禍於 dyn#ch129@漢朝 』，
引喩良深，
愧慰交集。

公忠貞之操，
終始不渝，
勁直之風，
古今罕比。

初聞此語，
能不罔然；
靜而思之，
是爲龜鏡。

況公先朝舊徳，
遐邇具瞻，
願以匡救爲懷，
無以暮年致請。」

# p 

辛酉，
太后命左金吾將軍 rm#r00031@丘神勣 詣 dm#dm02572@巴州 ，
檢校故 rm#r03054@太子賢 宅以備外虞，
其實風使殺之。

 rm#r00031@神勣 ，
 rm#r00032@行恭 之子也。

# p 

甲子，
太后御 dm#dm04268@武成殿 ，
皇帝帥王公以下上尊號。

丁卯，
太后臨軒，
遣禮部尚書 rm#r02314@武承嗣 册嗣皇帝。

自是太后常御 dm#dm06405@紫宸殿 ，
施慘紫帳以視朝。

# p 

丁丑，
以太常卿、檢校 rm#r01797@豫王 府長史 rm#r05626@王徳眞 爲侍中；
中書侍郎、檢校 rm#r01797@豫王 府司馬 rm#r00301@劉禕之 同中書門下三品。
# p 

三月，
丁亥，
徙 rm#r02521@𣏌王上金 爲 rm#r025211@畢王 ，
 rm#r03522@鄱陽王素節 爲 rm#r03522@葛王 。
# p 

 rm#r00031@丘神勣 至 dm#dm02572@巴州 ，
幽故 rm#r03054@太子賢 於別室，
逼令自殺。

太后乃歸罪於 rm#r00031@神勣 ，
戊戌，
舉哀於 dm#dm08770@顯福門 ，
貶 rm#r00031@神勣 爲 dm#dm05855@疊州 刺史。

己亥，
追封 rm#r03054@賢 爲 rm@雍王 。

 rm#r00031@神勣 尋復入爲左金吾將軍。


# p 

夏，
四月，
開府儀同三司、 dm#dm04043@梁州 都督 rm#r02496@滕王元嬰 薨。
# p 

辛酉，
徙 rm#r02521@畢王上金 爲 rm#r02521@澤王 ，
拜 dm#dm07147@蘇州 刺史；
 rm#r03522@葛王素節 爲 rm#r03522@許王 ，
拜 dm#dm06431@絳州 刺史。
# p 

癸酉，
遷 rm#r01656@廬陵王 于 dm#dm03162@房州 ；
丁丑，
又遷于 dm#dm01472@均州 故 rm@濮王 宅。

# p 

五月，
丙申，
 rm#r01837@高宗 靈駕西還。
# p 

閏月，
以禮部尚書 rm#r02314@武承嗣 爲太常卿、同中書門下三品。
# p 

秋，
七月，
戊午，
 dm#dm02733@廣州 都督 rm#r05919@路元叡 爲 dm#dm02492@崑崙 所殺。

 rm#r05919@元叡 闇懦，
僚屬恣横。

有商舶至，
僚屬侵漁不已，
商 rm#*rt0073@胡 訴於 rm#r05919@元叡 ；
 rm#r05919@元叡 索枷，
欲繋治之。

羣胡怒，
有 dm#dm02492@崑崙 袖劍直登聽事，
殺 rm#r05919@元叡 及左右十餘人而去，
無敢近者，
登舟入海，
追之不及。
# p 

 dm#dm05194@温州 大水，
流四千餘家。
# p 

突厥 rm#r06002@阿史那骨篤祿 等寇 dm#dm03674@朔州 。
# p 

八月，
庚寅，
葬 rm#r01837@天皇大帝 于 dm#dm00360@乾陵 ，
廟號 rm#r01837@高宗 。
# p 

初，
尚書左丞 rm#r04187@馮元常 爲 rm#r01837@高宗 所委，
 rm#r01837@高宗 晩年多疾，
毎曰：
「朕體中不佳，
可與 rm#r04187@元常 平章以聞。」

 rm#r04187@元常 嘗密言「中宮威權太重，
宜稍抑損」。

 rm#r01837@高宗 雖不能用，
深以其言爲然。

及太后稱制，
四方爭言符瑞；
 dm#dm02517@嵩陽 令 rm#r05527@樊文 獻瑞石，
太后命於朝堂示百官，
 rm#r04187@元常 奏：
「状渉諂詐，
不可誣罔天下。」

太后不悦，
出爲 dm#dm08464@隴州 刺史。

 rm#r04187@元常 ，
 rm#r06860@子琮 之曾孫也。
百司奏事
# p 

丙午，
太常卿、同中書門下三品 rm#r02314@武承嗣 罷爲禮部尚書。
# p 

 dm#dm03988@栝州 大水，
流二千餘家。
** 光宅
*** 光宅元年
# year 0684
# p 

九月，
甲寅，
赦天下，
改元。

旗幟皆從金色。

八品以下，
舊服青者更服碧。

改 dm#dm03880@東都 爲 dm#dm06235@神都 ，
宮名 dm#dm01773@太初 。

又改尚書省爲 dm#dm03307@文昌臺 ，
左、右僕射爲左、右相，
六曹爲天、地、四時六官；
門下省爲鸞臺，
中書省爲鳳閣，
侍中爲納言，
中書令爲内史；
御史臺爲左肅政臺，
増置右肅政臺；
其餘省、寺、監、率之名，
悉以義類改之。
# p 

以左武衞大將軍 rm#r02987@程務挺 爲 dm#dm01399@單于道 安撫大使，
以備突厥。


# p 

 rm#r02314@武承嗣 請太后追王其祖，
立 rm#r02293@武氏 七廟，
太后從之。

 rm#r03449@裴炎 諫曰：
「太后母臨天下，
當示至公，
不可私於所親。

獨不見 rm@呂氏 之敗乎！」

太后曰：
「 rm@呂后 以權委生者，
故及於敗。

今吾追尊亡者，
何傷乎！」

對曰：
「事當防微杜漸，
不可長耳！」

太后不從。

己巳，
追尊太后五代祖 rm#xjts06550@克己 爲 rm#xjts06550@魯靖公 ，
妣爲夫人；
高祖 rm#xjts06579@居常 爲太尉、 rm#xjts06579@北平恭肅王 ，
曾祖 rm#xjts06533@儉 爲太尉、 rm#xjts06533@金城義康王 ，
祖 rm#xjts06555@華 爲太尉、 rm#xjts06555@太原安成王 ，
考 rm#r02300@士彠 爲太師、 rm#r02300@魏定王 ；
祖妣皆爲𡚱。

 rm#r03449@裴炎 由是得罪。

又作五代祠堂於 dm#dm03309@文水 。

# p 

時諸 rm#no@武 用事，
 dyn#ch100@唐 宗室人人自危，
衆心憤惋。

會 dm#dm06035@眉州 刺史 rm#r01299@英公  rm#r01788@李敬業 及弟 dm#dm06019@盩厔 令 rm#xjts16916@敬猷 、給事中 rm#r00491@唐之奇 、 dm#dm08170@長安 主簿 rm#r04206@駱賓王 、詹事司直 rm#r02054@杜求仁 皆坐事，
 rm#r01788@敬業 貶 dm#dm03978@柳州 司馬，
 rm#xjts16916@敬猷 免官，
 rm#r00491@之奇 貶 dm#dm03991@栝蒼 令，
 rm#r04206@賓王 貶 dm#dm06696@臨海 丞，
 rm#r02054@求仁 貶 dm#dm09194@黟 令。

 rm#r02054@求仁 ，
 rm#r02053@正倫 之姪也。

 dm#dm06019@盩厔 尉 rm#r06120@魏思温 嘗爲御史，
復被黜。

皆會於 dm#dm03246@揚州 ，
各自以失職怨望，
乃謀作亂，
以匡復 rm#r01656@廬陵王 爲辭。


# p 

 rm#r06120@思温 爲之謀主，
使其黨監察御史 rm#r05797@薛仲璋 求奉使 dm#dm04510@江都 ，
令 dm#dm08502@雍州 人 rm#r06059@韋超 詣 rm#r05797@仲璋 告變，
云「 dm#dm03246@揚州 長史 rm#ry0009@陳敬之 謀反」。

 rm#r05797@仲璋 收 rm#ry0009@敬之 繋獄。

居數日，
 rm#r01788@敬業 乘傳而至，
矯稱 dm#dm03246@揚州 司馬來之官，
云「奉密旨，
以 dm#dm08893@高州 酋長 rm#r04190@馮子猷 謀反，
發兵討之。」

於是開府庫，
令士曹參軍 rm#r05371@李宗臣 就錢坊，
驅囚徒、工匠授以甲。

斬 rm#ry0009@敬之 於繋所；
録事參軍 rm#r05166@孫處行 拒之，
亦斬以徇，
僚吏無敢動者。

遂起一州之兵，
復稱 y@嗣聖元年 。

開三府：
一曰匡復府，
二曰 dm#dm06848@英公 府，
三曰 dm#dm03246@揚州 大都督府。

 rm#r01788@敬業 自稱匡復府上將，
領 dm#dm03246@揚州 大都督。

以 rm#r00491@之奇 、 rm#r02054@求仁 爲左、右長史，
 rm#r05371@宗臣 、 rm#r05797@仲璋 爲左、右司馬，
 rm#r06120@思温 爲軍師，
 rm#r04206@賓王 爲記室，
旬日間得勝兵十餘萬。
數百
# p 

移檄州縣，
略曰：
「僞臨朝 rm#r02293@武氏 者，
人非温順，
地實寒微。

昔充 rm#r01602@太宗 下陳，
嘗以更衣入侍，
洎乎晩節，
穢亂春宮。

密隱先帝之私，
陰圖後庭之嬖，
踐元后於翬翟，
陷吾君於聚麀。」

又曰：
「殺姉屠兄，
弑君鴆母，
人神之所同嫉，
天地之所不容。」

又曰：
「包藏禍心，
竊窺神器。

君之愛子，
幽之於別宮；
賊之宗盟，
委之以重任。」

又曰：
「一抔之土未乾，
六尺之孤安在！」

又曰：
「試觀今日之域中，
竟是誰家之天下！」

太后見檄，
問曰：
「誰所爲？」
或對曰：
「 rm#r04206@駱賓王 。」

太后曰：
「宰相之過也。

人有如此才，
而使之流落不偶乎！」

# p 

 rm#r01788@敬業 求得人貌類故 rm#r03054@太子賢 者，
紿衆云：
「 rm#r03054@賢 不死，
亡在此城中，
令吾屬舉兵。」

因奉以號令。
# p 

 dm#dm04089@楚州 司馬 rm#r05375@李崇福 帥所部三縣應 rm#r01788@敬業 。

 dm#dm06022@盱眙 人 rm#r05087@劉行舉 獨據縣不從，
 rm#r01788@敬業 遣其將 rm#r05198@尉遲昭 攻 dm#dm06022@盱眙 。

詔以 rm#r05087@行舉 爲遊撃將軍，
以其弟 rm@行實 爲 dm#dm04089@楚州 刺史。行舉拒卻之
# p 

甲申，
以左玉鈐衞大將軍 rm#r02121@李孝逸 爲 dm#dm03247@揚州道 大總管，
將兵三十萬，
以將軍 rm#r05421@李知十 、 rm#r06074@馬敬臣 爲之副，
以討 rm#r01788@李敬業 。


# p 

 rm#r02314@武承嗣 與其從父弟右衞將軍 rm#r02294@三思 以 rm#r04123@韓王元嘉 、 rm#r04316@魯王靈夔 屬尊位重，
屡勸太后因事誅之。

太后謀於執政，
 rm#r00301@劉禕之 、 rm#r04002@韋思謙 皆無言；
内史 rm#r03449@裴炎 獨固爭，
太后愈不悦。

 rm#r02294@三思 ，
 rm#ry0002@元慶 之子也。
# p 

及 rm#r01788@李敬業 舉兵，
 rm#r05797@薛仲璋 ，
 rm#r03449@炎 之甥也，
 rm#r03449@炎 欲示閒暇，
不汲汲議誅討。

太后問計於 rm#r03449@炎 ，
對曰：
「皇帝年長，
不親政事，
故豎子得以爲辭。

若太后返政，
則不討自平矣。」

監察御史 dm#dm07121@藍田  rm#r05203@崔詧 聞之，
上言：
「 rm#r03449@炎 受顧託，
大權在己，
若無異圖，
何故請太后歸政？」
太后命左肅政大夫 dm#dm08011@金城  rm@騫味道 、侍御史 dm#dm04199@櫟陽  rm#r06129@魚承曄 鞫之，
收 rm#r03449@炎 下獄。

 rm#r03449@炎 被收，
辭氣不屈。

或勸 rm#r03449@炎 遜辭以免，
 rm#r03449@炎 曰：
「宰相下獄，
安有全理！」


# p 

鳳閣舍人 rm#r05403@李景諶 證 rm#r03449@炎 必反。

 rm#r03514@劉景先 及鳳閣侍郎 dm#dm06561@義陽  rm#r05748@胡元範 皆曰：
「 rm#r03449@炎 社稷元臣，
有功於國，
悉心奉上，
天下所知，
臣敢明其不反。」

太后曰：
「 rm#r03449@炎 反有端，
顧卿不知耳。

」
對曰：
「若 rm#r03449@裴炎 爲反，
則臣等亦反也。」

太后曰：
「朕知 rm#r03449@裴炎 反，
知卿等不反。」

文武間證 rm#r03449@炎 不反者甚衆，
太后皆不聽。

俄幷 rm#r03514@景先 、 rm#r05748@元範 下獄。

丁亥，
以 rm#xjts11117@騫味道 檢校内史同鳳閣鸞臺三品，
 rm#r05403@李景諶 同鳳閣鸞臺平章事。
# p 

 rm#r06120@魏思温 説 rm#r01788@李敬業 曰：
「明公以匡復爲辭，
宜帥大衆鼓行而進，
直指 dm#dm04788@洛陽 ，
則天下知公志在勤王，
四面響應矣。」

 rm#r05797@薛仲璋 曰：
「 dm#dm08062@金陵 有王氣，
且 dm#dm01647@大江 天險，
足以爲固，
不如先取 dm#dm02596@常 、 dm#dm05366@潤 ，
爲定霸之基，
然後北向以圖中原，
進無不利，
退有所歸，
此良策也！」

 rm#r06120@思温 曰：
「 dm#dm02403@山東 豪傑以 rm#r02293@武氏 專制，
憤惋不平，
聞公舉事，
皆自蒸麥飯爲糧，
伸鋤爲兵，
以俟南軍之至。

不乘此勢以立大功，
乃更蓄縮自謀巣穴，
遠近聞之，
其誰不解體！」

 rm#r01788@敬業 不從，
使 rm#r00491@唐之奇 守 dm#dm04510@江都 ，
將兵渡 dm#dm04475@江 攻 dm#dm05367@潤州 。

 rm#r06120@思温 謂 rm#r02054@杜求仁 曰：
「兵勢合則強，
分則弱，
 rm#r01788@敬業 不幷力渡 dm#dm04981@淮 ，
收 dm#dm02403@山東 之衆以取 dm#dm04788@洛陽 ，
敗在眼中矣！」

# p 

壬辰，
 rm#r01788@敬業 陷 dm#dm05367@潤州 ，
執刺史 rm#r01755@李思文 ，
以 rm#r05371@李宗臣 代之。

 rm#r01755@思文 ，
 rm#r01788@敬業 之叔父也，
知 rm#r01788@敬業 之謀，
先遣使間道上變，
爲 rm#r01788@敬業 所攻，
拒守久之，
力屈而陷。

 rm#r06120@思温 請斬以徇，
 rm#r01788@敬業 不許，
謂 rm#r01755@思文 曰：
「叔黨於 rm#r02293@武氏 ，
宜改姓 rm#no@武 。」

 dm#dm05367@潤州 司馬 rm#r00242@劉延嗣 不降，
 rm#r01788@敬業 將斬之，
 rm#r06120@思温 救之，
得免，
與 rm#r01755@思文 皆囚於獄。

 rm#r00242@劉延嗣 ，
 rm#r00226@審禮 從父弟也。

 dm#dm03629@曲阿 令 dm#dm04700@河間  rm#r00870@尹元貞 引兵救 dm#dm05367@潤州 ，
戰敗，
爲 rm#r01788@敬業 所擒，
臨以白刃，
不屈而死。
# p 

丙申，
斬 rm#r03449@裴炎 于 dm#dm07871@都亭 。

 rm#r03449@炎 將死，
顧兄弟曰：
「兄弟官皆自致，
 rm#r03449@炎 無分毫之力，
今坐 rm#r03449@炎 流竄，
不亦悲乎！」

籍沒其家，
無甔石之儲。

 rm#r03514@劉景先 貶 dm#dm03579@普州 刺史，
 rm#r05748@胡元範 流 dm#dm05765@瓊州 而死。

 rm#r03449@裴炎 弟子太僕寺丞 rm#r03401@伷先 ，
年十七，
上封事請見言事。

太后召見，
詰之曰：
「汝伯父謀反，
尚何言？」
 rm#r03401@伷先 曰：
「臣爲陛下畫計耳，
安敢訴冤！

陛下爲 rm@李氏 婦，
先帝棄天下，
遽攬朝政，
變易嗣子，
疏斥 rm@李氏 ，
封崇諸 rm#no@武 。

臣伯父忠於社稷，
反誣以罪，
戮及子孫。

陛下所爲如是，
臣實惜之！

陛下早宜復子明辟，
高枕深居，
則宗族可全；
不然，
天下一變，
不可復救矣！」

太后怒曰：
「胡白，
小子敢發此言！

」
命引出，
 rm#r03401@伷先 反顧曰：
「今用臣言，
猶未晩。」

如是者三。

太后命於朝堂杖之一百，
長流 dm#dm05492@瀼州 。
又貶辰州刺史
# p 

 rm#r03449@炎 之下獄也，
郎將 rm#ry0010@姜嗣宗 使至 dm#dm08170@長安 ，
 rm#r00192@劉仁軌 問以 dm#dm03880@東都 事，
 rm#ry0010@嗣宗 曰：
「 rm#ry0010@嗣宗 覺 rm#r03449@裴炎 有異於常久矣。」

 rm#r00192@仁軌 曰：
「使人覺之邪？」
 rm#ry0010@嗣宗 曰：
「然。」

 rm#r00192@仁軌 曰：
「 rm#r00192@仁軌 有奏事，
願附使人以聞。」

 rm#ry0010@嗣宗 曰：
「諾。」

明日，
受 rm#r00192@仁軌 表而還，
表言「 rm#ry0010@嗣宗 知 rm#r03449@裴炎 反不言」。

太后覽之，
命拉 rm#ry0010@嗣宗 於殿庭，
絞於 dm#dm07871@都亭 。

# p 

丁酉，
追削 rm#r01788@李敬業 祖考官爵，
發冢斲棺，
復姓 rm@徐氏 。


# p 

 rm@李景諶 罷爲司賓少卿，
以右史 dm#dm04259@武康  rm#r05558@沈君諒 、著作郎 rm#r05203@崔詧 爲正諫大夫、同平章事。
# p 

 rm#r01788@徐敬業 聞 rm#r02121@李孝逸 將至，
自 dm#dm05367@潤州 囘軍拒之，
屯 dm#dm08919@高郵 之 dm#dm00229@下阿溪 ；
使 rm#r05319@徐敬猷 逼 dm#dm05006@淮陰 ，
別將 rm#r06059@韋超 、 rm#r05198@尉遲昭 屯 dm#dm07881@都梁山 。

# p 

 rm#r02121@李孝逸 軍至 dm#dm06704@臨淮 ，
偏將 rm#r06031@雷仁智 與 rm#r01788@敬業 戰不利，
 rm#r02121@孝逸 懼，
按兵不進。

殿中侍御史 rm#r04302@魏元忠 謂 rm#r02121@孝逸 曰：
「天下安危，
在茲一舉。

四方承平日久，
忽聞狂狡，
注心傾耳以俟其誅。

今大軍久留不進，
遠近失望，
萬一朝廷更命他將以代將軍，
將軍何辭以逃逗撓之罪乎！」

 rm#r02121@孝逸 乃引軍而前。

壬寅，
 rm#r06074@馬敬臣 撃斬 rm#r05198@尉遲昭 於 dm#dm07881@都梁山 。監軍
# p 

十一月，
辛亥，
以左鷹揚大將軍 rm#r04339@黒齒常之 爲 dm#dm04481@江南道 大總管，
討 rm#r01788@敬業 。

# p 

 rm#r06059@韋超 擁衆據 dm#dm07881@都梁山 ，
諸將皆曰：
「 rm#r06059@超 憑險自固，
士無所施其勇，
騎無所展其足；
且窮寇死戰，
攻之多殺士卒，
不如分兵守之，
大軍直趣 dm#dm04510@江都 ，
覆其巣穴。」

支度使 rm#r05799@薛克楊 曰：
「 rm#r06059@超 雖據險，
其衆非多。

今多留兵則前軍勢分，
少留兵則終爲後患，
不如先撃之，
其勢必舉，
舉 dm#dm07879@都梁 ，
則 dm#dm05006@淮陰 、 dm#dm08919@高郵 望風瓦解矣！」

 rm#r04302@魏元忠 請先撃 rm#r05319@徐敬猷 ，
諸將曰：
「不如先攻 rm#r01788@敬業 ，
 rm#r01788@敬業 敗，
則 rm#r05319@敬猷 不戰自擒矣。

若撃 rm#r05319@敬猷 ，
則 rm#r01788@敬業 引兵救之，
是腹背受敵也。」

 rm#r04302@元忠 曰：
「不然。

賊之精兵，
盡在 dm#dm00229@下阿 ，
烏合而來，
利在一決，
萬一失利，
大事去矣！

 rm#r05319@敬猷 出於博徒，
不習軍事，
其衆單弱，
人情易搖，
大軍臨之，
駐馬可克。

 rm#r01788@敬業 雖欲救之，
計程必不能及。

我克 rm#r05319@敬猷 ，
乘勝而進，
雖有 rm#r06274@韓 、 rm#r06288@白 不能當其鋒矣！

今不先取弱者而遽攻其強，
非計也。」

 rm#r02121@孝逸 從之，
引兵撃 rm#r06059@超 ，
 rm#r06059@超 夜遁，
進撃 rm#r05319@敬猷 ，
 rm#r05319@敬猷 脱身走。楊構
# p 

庚申，
 rm#r01788@敬業 勒兵阻溪拒守，
後軍總管 rm#r05826@蘇孝祥 夜將五千人，
以小舟渡溪先撃之，
兵敗，
 rm#r05826@孝祥 死，
士卒赴溪溺死者過半。

左豹韜衞果毅 dm#dm05254@漁陽  rm#r01369@成三朗 爲 rm#r01788@敬業 所擒，
 rm#r00491@唐之奇 紿其衆曰：
「此 rm#r02121@李孝逸 也！」

將斬之，
 rm#r01369@三朗 大呼曰：
「我果毅 rm#r01369@成三朗 ，
非 rm#r02121@李將軍 也。

官軍今大至矣，
爾曹破在朝夕。

我死，
妻子受榮，
爾死，
妻子籍沒，
爾終不及我也！」

遂斬之。
# p 

 rm#r02121@孝逸 等諸軍繼至，
戰數不利。

 rm#r02121@孝逸 懼，
欲引退，
 rm#r04302@魏元忠 與行軍管記 rm#r00298@劉知柔 言於 rm#r02121@孝逸 曰：
「風順荻乾，
此火攻之利。」

固請決戰。

 rm#r01788@敬業 置陳既久，
士卒多疲倦顧望，
陳不能整；
 rm#r02121@孝逸 進撃之，
因風縱火，
 rm#r01788@敬業 大敗，
斬首七千級，
溺死者不可勝紀。

 rm#r01788@敬業 等輕騎走入 dm#dm04510@江都 ，
挈妻子奔 dm#dm05367@潤州 ，
將入海奔 dm#dm08934@高麗 ；
 rm#r02121@孝逸 進屯 dm#dm04510@江都 ，
分遣諸將追之。

乙丑，
 rm#r01788@敬業 至 dm#dm04908@海陵 界，
阻風，
其將 rm#r05658@王那相 斬 rm#r01788@敬業 、 rm@敬猷 及 rm#r04206@駱賓王 首來降。

餘黨 rm#r00491@唐之奇 、 rm#r06120@魏思温 皆捕得，
傳首 dm#dm06235@神都 ，
 dm#dm03240@揚 、 dm#dm05366@潤 、 dm#dm04085@楚 三州平。
# p 

 rm#r06007@陳嶽 論曰：
「 rm#r01788@敬業 苟能用 rm#r06120@魏思温 之策，
直指 dm#dm04650@河 、 dm#dm04761@洛 ，
專以匡復爲事，
縱軍敗身戮，
亦忠義在焉。

而妄希 dm#dm08062@金陵 王氣，
是眞爲叛逆，
不敗何待！

 rm#r01788@敬業 之起也，
使 rm@敬猷 將兵五千，
循 dm#dm04475@江 西上，
略地 dm#dm01327@和州 。

前弘文館學士 dm#dm04339@歴陽  rm#r04225@高子貢 帥郷里數百人拒之，
 rm@敬猷 不能西。

以功拜朝散大夫、成均助教。」


# p 

丁卯，
 rm#r05940@郭待舉 罷爲左庶子；
以鸞臺侍郎 rm#r04039@韋方質 爲鳳閣侍郎、同平章事。

 rm#r04039@方質 ，
 rm#r04084@雲起 之孫也。

# p 

十二月，
 rm#r03514@劉景先 又貶 dm#dm01211@吉州 員外長史，
 rm#r05940@郭待舉 貶 dm#dm02432@嶽州 刺史。

# p 

初，
 rm#r03449@裴炎 下獄，
 dm#dm01399@單于道 安撫大使、左武衞大將軍 rm#r02987@程務挺 密表申理，
由是忤旨。

 rm#r02987@務挺 素與 rm#r00491@唐之奇 、 rm#r02054@杜求仁 善，
或譖之曰，
「 rm#r02987@務挺 與 rm#r03449@裴炎 、 rm#r01788@徐敬業 通謀。」

癸卯，
遣左鷹揚將軍 rm#r05848@裴紹業 即軍中斬之，
籍沒其家。

突厥聞 rm#r02987@務挺 死，
所在宴飮相慶；
又爲 rm#r02987@務挺 立祠，
毎出師，
必祷之。
# p 

太后以 dm#dm01538@夏州 都督 rm#r02644@王方翼 與 rm#r02987@務挺 連職，
素相親善，
且廢后近屬，
徵下獄，
流 dm#dm02498@崖州 而死。

** 垂拱
*** 垂拱元年
# year 0685
# p 

春，
正月，
丁未朔，
赦天下，
改元。
# p 

太后以 rm#r01755@徐思文 爲忠，
特免縁坐，
拜司僕少卿。

謂曰：
「 rm#r01788@敬業 改卿姓 rm#no@武 ，
朕今不復奪也。」


# p 

庚戌，
以 rm@騫味道 守内史。

# p 

戊辰，
文昌左相、同鳳閣鸞臺三品 rm@樂城文獻公  rm#r00192@劉仁軌 薨。

# p 

二月，
癸未，
制：
「朝堂所置登聞鼓及肺石，
不須防守，
有撾鼓立石者，
令御史受状以聞。」


# p 

乙巳，
以春官尚書 rm#r02314@武承嗣 、秋官尚書 rm#r03427@裴居道 、右肅政大夫 rm#r04002@韋思謙 竝同鳳閣鸞臺三品。
# p 

突厥 rm#r06002@阿史那骨篤祿 等數寇邊，
以左玉鈐衞中郎將 rm#r05566@淳于處平 爲 dm#dm08408@陽曲道 行軍總管，
撃之。


# p 

正諫大夫、同平章事 rm#r05558@沈君諒 罷。
# p 

三月，
正諫大夫、同平章事 rm#r05203@崔詧 罷。
# p 

丙辰，
遷 rm#r01656@廬陵王 于 dm#dm03162@房州 。

# p 

辛酉，
 rm#r02314@武承嗣 罷。
# p 

辛未，
頒垂拱格。
# p 

朝士有左遷詣宰相自訴者，
内史 rm@騫味道 曰：
「此太后處分。」

同中書門下三品 rm#r00301@劉禕之 曰：
「縁坐改官，
由臣下奏請。」

太后聞之，
夏，
四月，
丙子，
貶 rm#r03329 ?@味道 爲 dm#dm08665@青州 刺史，
加 rm#r00301@禕之 太中大夫。

謂侍臣曰：
「君臣同體，
豈得歸惡於君，
引善自取乎！」

# p 

癸未，
突厥寇 dm#dm00485@代州 ；
 rm#r05566@淳于處平 引兵救之；
至 dm#dm03000@忻州 ，
爲突厥所敗，
死者五千餘人。
# p 

丙午，
以 rm#r03427@裴居道 爲内史。

納言 rm#r05626@王徳眞 流 dm#dm07496@象州 。

五月
# p 

己酉，
以冬官尚書 rm#r03343@蘇良嗣 爲納言。

# p 

壬戌，
制内外九品以上及百姓，
咸令自舉。

# p 

壬申，
 rm#r04039@韋方質 同鳳閣鸞臺三品。
# p 

六月，
天官尚書 rm#r04030@韋待價 同鳳閣鸞臺三品。

 rm#r04030@待價 ，
 rm#r04067@萬石 之兄也。
# p 

同羅、僕固等諸部叛，
遣左豹韜衞將軍 rm#r05071@劉敬同 發 dm#dm04695@河西 騎士出 dm#dm02389@居延海 以討之，
同羅、僕固等皆敗散。

敕僑置 dm#dm01980@安北都護府 於 dm#dm01219@同城 以納降者。


# p 

秋，
七月，
己酉，
以文昌左丞 rm#r04301@魏玄同 爲鸞臺侍郎、同鳳閣鸞臺三品。

# p 

詔自今祀天地，
 rm#r04258@高祖 、 rm#r01602@太宗 、 rm#r01837@高宗 皆配坐；
用鳳閣舍人 rm#r00162@元萬頃 等之議也。
# p 

九月，
丁卯，
 dm#dm02733@廣州 都督 rm#r05643@王果 討反獠，
平之。

# p 

冬，
十一月，
癸卯，
命天官尚書 rm#r04030@韋待價 爲 dm#dm05605@燕然道 行軍大總管以討吐蕃。

初，
西突厥 rm@興昔亡 、 rm@繼往絶可汗 既死，
十姓無主，
部落多散亡，
太后乃擢 rm@興昔亡 之子左豹韜衞翊府中郎將 rm#rw0003@元慶 爲左玉鈐衞將軍，
兼 dm#dm00007@崐陵 都護，
襲 rm#?@興昔亡可汗 押五咄陸部落。


# p 

麟臺正字 dm#dm02340@射洪  rm#r03920@陳子昂 上疏，
以爲：
「朝廷遣使巡察四方，
不可任非其人，
及刺史、縣令，
不可不擇。

比年百姓疲於軍旅，
不可不安。」

其略曰：
「夫使不擇人，
則黜陟不明，
刑罰不中，
朋黨者進，
貞直者退；
徒使百姓脩飾道路，
送往迎來，
無所益也。

諺曰：
『欲知其人，
觀其所使。』

不可不愼也。」

又曰：
「宰相，
陛下之腹心；
刺史、縣令，
陛下之手足；
未有無腹心手足而能獨理者也！」

又曰：
「天下有危機，
禍福因之而生，
機靜則有福，
機動則有禍，
百姓是也。

百姓安則樂其生，
不安則輕其死，
輕其死則無所不至，
祅逆乘釁，
天下亂矣！」

又曰：
「 rm#r02546@隋煬帝 不知天下有危機，
而信貪佞之臣，
冀收夷狄之利，
卒以滅亡，
其爲殷鑒，
豈不大哉！」

# p 

太后修故 dm#dm05931@白馬寺 ，
以僧 rm#r03283@懷義 爲寺主。

 rm#r03283@懷義 ，
 dm#dm07933@鄠 人，
本姓 rm#r03283@馮 ，
名 rm#r03283@小寶 ，
賣藥 dm#dm04788@洛陽 市，
因 rm@千金公主 以進，
得幸於太后；
太后欲令出入禁中，
乃度爲僧，
名 rm#r03283@懷義 。

又以其家寒微，
令與駙馬都尉 rm#r05819@薛紹 合族，
命 rm#r05819@紹 以季父事之。

出入乘御馬，
宦者十餘人侍從；
士民遇之者皆奔避，
有近之者，
輒撾其首流血，
委之而去，
任其生死。

見道士則極意毆之，
仍髡其髮而去。

朝貴皆匍匐禮謁，
 rm#r02314@武承嗣 、 rm#r02294@武三思 皆執僮僕之禮以事之，
爲之執轡，
 rm#r03283@懷義 視之若無人。

多聚無頼少年，
度爲僧，
縱横犯法，
人莫敢言。

右臺御史 rm#r06086@馮思勗 屡以法繩之，
 rm#r03283@懷義 遇 rm#r06086@思勗 於途，
令從者毆之，
幾死。

*** 二年
# year 0686
# p 

春，
正月，
太后下詔復政於皇帝。

 rm#r01797@睿宗 知太后非誠心，
奉表固讓；
太后復臨朝稱制。

辛酉，
赦天下。
# p 

二月，
辛未朔，
日有食之。
# p 

右衞大將軍 rm#r02121@李孝逸 既克 rm#r01788@徐敬業 ，
聲望甚重；
 rm#r02314@武承嗣 等惡之，
數譖於太后，
左遷 dm#dm03428@施州 刺史。


# p 

三月，
戊申，
太后命鑄銅爲匭：
其東曰「延恩」，
獻賦頌、求仕進者投之；
南曰「招諫」，
言朝政得失者投之；
西曰「伸冤」，
有冤抑者投之；
北曰「通玄」，
言天象災變及軍機祕計者投之。

命正諫、補闕、拾遺一人掌之，
先責識官，
乃聽投表疏。
置之朝堂以受天下表疏銘
# p 

 rm#r01788@徐敬業 之反也，
侍御史 rm#r06129@魚承曄 之子 rm@保家 教 rm#r01788@敬業 作刀車及弩，
 rm#r01788@敬業 敗，
僅得免。

太后欲周知人間事，
 rm@保家 上書，
請鑄銅爲匭以受天下密奏。

其器共爲一室，
中有四隔，
上各有竅，
以受表疏，
可入不可出。

太后善之。

未幾，
其怨家投匭告 rm@保家 爲 rm#r01788@敬業 作兵器，
殺傷官軍甚衆，
遂伏誅。

# p 

太后自 rm#r01788@徐敬業 之反，
疑天下人多圖己，
又自以久專國事，
且内行不正，
知宗室大臣怨望，
心不服，
欲大誅殺以威之。

乃盛開告密之門，
有告密者，
臣下不得問，
皆給驛馬，
供五品食，
使詣行在。

雖農夫樵人，
皆得召見，
廩於客館，
所言或稱旨，
則不次除官，
無實者不問。

於是四方告密者蜂起，
人皆重足屏息。

# p 

有胡人 rm#r03074@索元禮 ，
知太后意，
因告密召見，
擢爲游撃將軍，
令案制獄。

 rm#r03074@元禮 性殘忍，
推一人必令引數十百人，
太后數召見賞賜以張其權。

於是尚書都事 dm#dm08170@長安  rm#r00116@周興 、 dm#dm06979@萬年 人 rm#r00115@來俊臣 之徒效之，
紛紛繼起。

 rm#r00116@興 累遷至秋官侍郎，
 rm#r00115@俊臣 累遷至御史中丞，
相與私畜無頼數百人，
專以告密爲事；
欲陷一人，
輒令數處倶告，
事状如一。

 rm#r00115@俊臣 與司刑評事 dm#dm04788@洛陽  rm#r03177@萬國俊 共撰羅織經數千言，
教其徒網羅無辜，
織成反状，
構造布置，
皆有支節。

太后得告密者，
輒令 rm#r03074@元禮 等推之，
競爲訊囚酷法，
有「定百脈」
、「突地吼」
、「死豬愁」
、「求破家」
、「反是實」
等名號。

或以椽關手足而轉之，
謂之「鳳皇曬翅」；
或以物絆其腰，
引枷向前，
謂之「驢駒拔撅」；
或使跪捧枷，
累甓其上，
謂之「仙人獻果」；
或使立高木，
引枷尾向後，
謂之「玉女登梯」；
或倒懸石縋其首，
或以醋灌鼻，
或以鐵圈𩌊其首而加楔，
至有腦裂髓出者。

毎得囚，
輒先陳其械具以示之，
皆戰栗流汗，
望風自誣。

毎有赦令，
 rm#r00115@俊臣 輒令獄卒先殺重囚，
然後宣示。

 rm@太后 以爲忠，
益寵任之。

中外畏此數人，
甚於虎狼。作大枷之上
# p 

麟臺正字 rm#r03920@陳子昂 上疏：
以爲：
「執事者疾 rm#r01788@徐敬業 首亂唱禍，
將息姦源，
窮其黨與，
遂使陛下大開詔獄，
重設嚴刑，
有迹渉嫌疑，
辭相逮引，
莫不窮捕考按。

至有姦人熒惑，
乘險相誣，
糾告疑似，
冀圖爵賞，
恐非伐罪弔人之意也。

臣竊觀當今天下，
百姓思安久矣，
故 dm#dm03246@揚州 構逆，
殆有五旬，
而海内晏然，
纖塵不動。

陛下不務玄默以救疲人，
而反任威刑以失其望，
臣愚暗昧，
竊有大惑。

伏見諸方告密，
囚累百千輩，
及其窮竟，
百無一實。

陛下仁恕，
又屈法容之，
遂使姦惡之黨快意相讎，
睚眦之嫌即稱有密，
一人被訟，
百人滿獄，
使者推捕，
冠蓋如市。

或謂陛下愛一人而害百人，
天下喁喁，
莫知寧所。

臣聞 dyn#ch174@隋 之末代，
天下猶平，
 rm#r05509@楊玄感 作亂，
不踰月而敗。

天下之弊，
未至土崩，
蒸人之心，
猶望樂業。

 rm#r02546@煬帝 不悟，
遂使兵部尚書 rm#r05525@樊子蓋 專行屠戮，
大窮黨與，
海内豪士，
無不罹殃；
遂至殺人如麻，
流血成澤，
天下靡然，
始思爲亂，
於是雄傑竝起而 rm#no@隋族 亡矣。

夫大獄一起，
不能無濫，
冤人吁嗟，
感傷和氣，
羣生癘疫，
水旱隨之，
人既失業，
則禍亂之心怵然而生矣。

古者明王重愼刑法，
蓋懼此也。

昔 rm@漢武帝 時巫蠱獄起，
使太子奔走，
兵交宮闕，
無辜被害者以千萬數，
宗廟幾覆；
頼 rm@武帝 得 dm#dm01513@壺關 三老書，
廓然感悟，
夷 rm#rx0059@江充 三族，
餘獄不論，
天下以安爾。

古人云：
『前事之不忘，
後事之師。』

伏願陛下念之！

」
太后不聽。
# p 

夏，
四月，
太后鑄大儀，
置北闕。

# p 

以 rm#r00882@岑長倩 爲内史。

六月，
辛未，
以 rm#r03343@蘇良嗣 爲左相，
同鳳閣鸞臺三品 rm#r04030@韋待價 爲右相。

己卯，
以 rm#r04002@韋思謙 爲納言。
# p 

 rm#r03343@蘇良嗣 遇僧 rm#r03283@懷義 於朝堂，
 rm#r03283@懷義 偃蹇不爲禮；
 rm#r03343@良嗣 大怒，
命左右捽曳，
批其頬數十。

 rm#r03283@懷義 訴於太后，
太后曰：
「阿師當於北門出入，
南牙宰相所往來，
勿犯也。」

# p 

太后託言 rm#r03283@懷義 有巧思，
故使入禁中營造。

補闕 dm#dm08230@長社  rm#r02659@王求禮 上表，
以爲：
「 rm#r01602@太宗 時，
有 rm#r05747@羅黒黒 善彈琵琶，
 rm#r01602@太宗 閹爲給使，
使教宮人。

陛下若以 rm#r03283@懷義 有巧性，
欲宮中驅使者，
臣請閹之，
庶不亂宮闈。」

表寢不出。
# p 

秋，
九月，
丁未，
以西突厥 rm@繼往絶可汗 之子 rm@斛瑟羅 爲右玉鈐衞將軍，
襲 rm@繼往絶可汗 押五弩失畢部落。


# p 

己巳，
 dm#dm08502@雍州 言 dm#dm03395@新豐縣 東南有山踊出，
改 dm#dm03393@新豐 爲 dm#dm03082@慶山縣 。

四方畢賀。

 dm#dm04516@江陵 人 rm#r00130@兪文俊 上書：
「天氣不和而寒暑併，
人氣不和而疣贅生，
地氣不和而塠阜出。

今陛下以女主處陽位，
反易剛柔，
故地氣塞隔而山變爲災。

陛下謂之『 dm#dm03082@慶山 』，
臣以爲非慶也。

臣愚以爲宜側身脩徳以答天譴；
不然，
殃禍至矣！」

太后怒，
流於 dm#dm02532@嶺外 ，
後爲六道使所殺。

# p 

突厥入寇，
左鷹揚衞大將軍 rm#r04339@黒齒常之 拒之；
至 dm#dm00682@兩井 ，
遇突厥三千餘人，
見 dyn#ch100@唐 兵，
皆下馬擐甲，
 rm#r04339@常之 以二百餘騎衝之，
皆棄甲走。

日暮，
突厥大至，
 rm#r04339@常之 令營中然火，
東南又有火起，
虜疑有兵相應，
遂夜遁。
# p 

 rm#r02567@狄仁傑 爲 dm#dm02291@寧州 刺史。

右臺監察御史 dm#dm03564@晉陵  rm#r03735@郭翰 巡察 dm#dm08458@隴右 ，
所至多所按劾。

入 dm#dm02291@寧州 境，
耆老歌刺史徳美者盈路；
 rm#r03735@翰 薦之於朝，
徵爲冬官侍郎。
*** 垂拱三年
# year 0687
# p 

春，
閏正月，
丁卯，
封皇子 rm#r03931@成美 爲 rm@恆王 ，
 rm#r02004@隆基 爲 rm@楚王 ，
 rm#r03770@隆範 爲 rm#r03770@衞王 ，
 rm#r03598@隆業 爲 rm@趙王 。
# p 

二月，
丙辰，
突厥 rm#r06002@骨篤祿 等寇 dm#dm03464@昌平 ，
命左鷹揚大將軍 rm#r04339@黒齒常之 帥諸軍討之。

# p 

三月，
乙丑，
納言 rm#r04002@韋思謙 以太中大夫致仕。
# p 

夏，
四月，
命 rm#r03343@蘇良嗣 留守 dm#dm07290@西京 。

時尚方監 rm#r06253@裴匪躬 檢校 dm#dm00426@京 苑，
將鬻苑中蔬果以收其利。

 rm#r03343@良嗣 曰：
「昔 rm@公儀休 相 dm#dm08968@魯 ，
猶能拔葵、去織婦，
未聞萬乘之主鬻蔬果也。

」
乃止。
# p 

壬戌，
 rm#r03427@裴居道 爲納言。

五月，
丙寅，
夏官侍郎 dm#dm00427@京兆  rm#r01111@張光輔 爲鳳閣侍郎、同平章事。

# p 

鳳閣侍郎、同鳳閣鸞臺三品 rm#r00301@劉禕之 竊謂鳳閣舍人 dm#dm04417@永年  rm#r03571@賈大隱 曰：
「太后既廢昏立明，
安用臨朝稱制！

不如返正以安天下之心。」

 rm#r03571@大隱 密奏之，
太后不悦，
謂左右曰：
「 rm#r00301@禕之 我所引，
乃復叛我！

」
或誣 rm#r00301@禕之 受 dm#dm04352@歸誠州 都督 rm#r01945@孫萬榮 金，
又與 rm#r03511@許敬宗 妾有私，
太后命 dm#dm06603@肅州 刺史 rm#r01148@王本立 推之。

 rm#r01148@本立 宣敕示之，
 rm#r00301@禕之 曰：
「不經鳳閣鸞臺，
何名爲敕！」

太后大怒，
以爲拒捍制使；
庚午，
賜死于家。正政
# p 

 rm#r00301@禕之 初下獄，
 rm#r01797@睿宗 爲之上疏申理，
親友皆賀之，
 rm#r00301@禕之 曰：
「此乃所以速吾死也。」

臨刑，
沐浴，
神色自若，
自草謝表，
立成數紙。

麟臺郎 rm#r03735@郭翰 、太子文學 rm#r05123@周思鈞 稱歎其文。

太后聞之，
左遷 rm#r03735@翰  dm#dm02562@巫州 司法，
 rm#r05123@思鈞  dm#dm03267@播州 司倉。

# p 

秋，
七月，
壬辰，
 rm#r04301@魏玄同 檢校納言。
# p 

 dm#dm02527@嶺南  dm#dm00547@俚 戸舊輸半課，
 dm#dm00422@交趾 都護 rm#r00244@劉延祐 使之全輸，
 dm#dm00547@俚 戸不從，
 rm#r00244@延祐 誅其魁首。

其黨 rm#r05387@李思愼 等作亂，
攻破 dm#dm01981@安南 府城，
殺 rm#r00244@延祐 。

 dm#dm04001@桂州 司馬 rm#r06201@曹玄靜 將兵討 rm#r05387@思愼 等，
斬之。

# p 

突厥 rm#r06002@骨篤祿 、 rm#r05048@元珍 寇 dm#dm03674@朔州 ，
遣 dm#dm05605@燕然道 大總管 rm#r04339@黒齒常之 撃之，
以左鷹揚大將軍 rm#r01671@李多祚 爲之副，
大破突厥於 dm#dm09144@黄花堆 ，
追奔四十餘里，
突厥皆散走磧北。

 rm#r01671@多祚 世爲靺鞨酋長，
以軍功得入宿衞。

 rm#r04339@黒齒常之 毎得賞賜，
皆分將士；
有善馬爲軍士所損，
官屬請笞之，
 rm#r04339@常之 曰：
「奈何以私馬笞官兵乎！」

卒不問。

# p 

九月，
己卯，
 dm#dm07188@虢州 人 rm#r05484@楊初成 詐稱郎將，
矯制於都市募人迎 rm#r01656@廬陵王 於 dm#dm03162@房州 ；
事覺，
伏誅。


# p 

冬，
十月，
庚子，
右監門衞中郎將 rm@爨寶璧 與突厥 rm#r06002@骨篤祿 、 rm#r05048@元珍 戰，
全軍皆沒，
 rm@寶璧 輕騎遁歸。

# p 

 rm@寶璧 見 rm#r04339@黒齒常之 有功，
表請窮追餘寇。

詔與 rm#r04339@常之 計議，
遙爲聲援。

 rm@寶璧 欲專其功，
不待 rm#r04339@常之 ，
引精卒萬三千人先行，
出塞二千餘里，
掩撃其部落；
既至，
又先遣人告之，
使得嚴備，
與戰，
遂敗。

太后誅 rm@寶璧 ；
改 rm#r06002@骨篤祿 曰 rm#r06002@不卒祿 。

# p 

命 rm@魏玄同 留守 dm#dm07290@西京 。

# p 

 rm#r02314@武承嗣 又使人誣 rm#r02121@李孝逸 自云「名中有兔，
兔，
月中物，
當有天分。」

太后以 rm#r02121@孝逸 有功，
十一月，
戊寅，
減死除名，
流 dm#dm00623@儋州 而卒。

# p 

太后欲遣 rm#r04030@韋待價 將兵撃吐蕃，
鳳閣侍郎 rm#r04039@韋方質 奏，
請如舊制遣御史監軍，
太后曰：
「古者明君遣將，
閫外之事悉以委之。

比聞御史監軍，
軍中事無大小皆須承稟。

以下制上，
非令典也；
且何以責其有功！」

遂罷之。
# p 

是歳，
天下大饑，
 dm#dm02403@山東 、 dm#dm08283@關内 尤甚。
*** 四年
# year 0688
# p 

春，
正月，
甲子，
於 dm#dm06235@神都 立 rm#r04258@高祖 、 rm#r01602@太宗 、 rm#r01837@高宗 三廟，
四時享祀如西廟之儀。

又立 dm#dm02458@崇先廟 以享 rm#r02293@武氏 祖考。

太后命有司議 dm#dm02458@崇先廟 室數，
司禮博士 rm#r05124@周悰 請爲七室，
又減 dyn#ch100@唐 太廟爲五室。

春官侍郎 rm#r03571@賈大隱 奏：
「禮，
天子七廟，
諸侯五廟，
百王不易之義。

今 rm#r05124@周悰 別引浮議，
廣述異聞，
直崇臨朝權儀，
不依國家常度。

皇太后親承顧託，
光顯大猷，
其 dm#dm02458@崇先廟 室應如諸侯之數，
國家宗廟不應輒有變移。」

太后乃止。
# p 

 rm#r01602@太宗 、 rm#r01837@高宗 之世，
屡欲立明堂，
諸儒議其制度，
不決而止。

及太后稱制，
獨與北門學士議其制，
不問諸儒。

諸儒以爲明堂當在國陽丙巳之地，
三里之外，
七里之内。

太后以爲去宮太遠。

二月，
庚午，
毀 dm#dm00347@乾元殿 ，
於其地作明堂，
以僧 rm#r03283@懷義 爲之使，
凡役數萬人。
# p 

夏，
四月，
戊戌，
殺太子通事舍人 rm#r03703@郝象賢 。

 rm#r03703@象賢 ，
 rm#r03702@處俊 之孫也。


# p 

初，
太后有憾於 rm#r03702@處俊 ，
會奴誣告 rm#r03703@象賢 反，
太后命 rm#r00116@周興 鞫之，
致 rm#r03703@象賢 族罪。

 rm#r03703@象賢 家人詣朝堂，
訟冤於監察御史 dm#dm04132@樂安  rm#ry0013@任玄殖 。

 rm#ry0013@玄殖 奏 rm#r03703@象賢 無反状，
 rm#ry0013@玄殖 坐免官。

 rm#r03703@象賢 臨刑，
極口罵太后，
發揚宮中隱慝，
奪市人柴以撃刑者；
金吾兵共格殺之。

太后命支解其尸，
發其父祖墳，
毀棺焚尸。

自是終太后之世，
法官毎刑人，
先以木丸塞其口。

# p 

 rm#r02314@武承嗣 使鑿白石爲文曰：
「聖母臨人，
永昌帝業。

」
末紫石雜藥物填之。

庚午，
使 dm#dm08502@雍州 人 rm#r05137@唐同泰 奉表獻之，
稱獲之於 dm#dm04780@洛水 。

太后喜，
命其石曰「寶圖」。

擢 rm#r05137@同泰 爲遊撃將軍。

五月，
戊辰，
詔當親拜 dm#dm04761@洛 ，
受「寶圖」；
有事南郊，
告謝昊天；
禮畢，
御明堂，
朝羣臣。

命諸州都督、刺史及宗室、外戚以拜 dm#dm04761@洛 前十日集 dm#dm06235@神都 。

乙亥，
太后加尊號爲 rm#r02293@聖母神皇 。
# p 

六月，
丁亥朔，
日有食之。
# p 

壬寅，
作神皇三璽。

# p 

 rm#r02072@東陽大長公主 削封邑，
幷二子徙 dm#dm02562@巫州 。

公主適 rm#r04236@高履行 ，
太后以 rm#r01294@高氏  rm#r03856@長孫無忌 之舅族，
故惡之。

# p 

 dm#dm04481@江南道 巡撫大使、冬官侍郎 rm#r02567@狄仁傑 以 dyn#ch109@呉 、 dyn#ch117@楚 多淫祠，
奏焚其一千七百餘所，
獨留 rm#rt0008@夏禹 、 rm#rt0210@呉太伯 、 rm@季札 、 rm@伍員 四祠。

# p 

秋，
七月，
丁巳，
赦天下。

更命「寶圖」
爲「天授聖圖」；
 dm#dm04780@洛水 爲 dm#dm04421@永昌洛水 ，
封其神爲 rm#no@顯聖侯 ，
加特進，
禁漁釣，
祭祀比四涜。

名圖所出曰「聖圖泉」，
泉側置 dm#dm04422@永昌縣 。

又改 dm#dm02514@嵩山 爲 dm#dm06221@神嶽 ，
封其神爲 rm#no@天中王 ，
拜太師、使持節、 dm#dm06221@神嶽 大都督，
禁芻牧。

又以先於 dm#dm04455@汜水 得瑞石，
改 dm#dm04455@汜水 爲 dm#dm02751@廣武 。

# p 

太后潛謀革命，
稍除宗室。

 dm#dm06431@絳州 刺史 rm#r04123@韓王元嘉 、 dm#dm08665@青州 刺史 rm#r03988@霍王元軌 、 dm#dm07817@邢州 刺史 rm#r04316@魯王靈夔 、 dm#dm07502@豫州 刺史 rm#r03593@越王貞 及 rm#r04123@元嘉 子 dm#dm07693@通州 刺史 rm#r04328@黄公譔 、 rm#r03988@元軌 子 dm#dm08028@金州 刺史 rm#r02402@江都王緒 、 rm#r03356@虢王鳳 子 dm#dm05829@申州 刺史 rm@東莞公融 、 rm#r04316@靈夔 子 rm#r03164@范陽王藹 、 rm#r03593@貞 子 dm#dm01088@博州 刺史 rm#r02804@琅邪王沖 ，
在宗室中皆以才行有美名，
太后尤忌之。

 rm#r04123@元嘉 等内不自安，
密有匡復之志。

# p 

 rm#r04328@譔 謬爲書與 rm#r03593@貞 云：
「内人病浸重，
當速療之，
若至今冬，
恐成痼疾。」

及太后召宗室朝明堂，
諸王因遞相驚曰：
「神皇欲於大饗之際，
使人告密，
盡收宗室，
誅之無遺。」

 rm#r04328@譔 詐爲皇帝璽書與 rm#r02804@沖 云：
「朕遭幽縶，
諸王宜各發兵救我。」

 rm#r02804@沖 又詐爲皇帝璽書云：
「神皇欲移 rm@李氏 社稷以授 rm#r02293@武氏 。」

八月，
壬寅，
 rm#r02804@沖 召長史 rm#r05788@蕭徳琮 等令募兵，
分告 dm#dm08726@韓 、 dm#dm08588@霍 、 dm#dm08968@魯 、 dm#dm07606@越 及 dm#dm07514@貝州 刺史 rm#r03068@紀王愼 ，
令各起兵共趣 dm#dm06235@神都 。

太后聞之，
以左金吾將軍 rm#r00031@丘神勣 爲 dm#dm05037@清平道 行軍大總管以討之。

# p 

 rm#r02804@沖 募兵得五千餘人，
欲渡 dm#dm04650@河 取 dm#dm05438@濟州 ；
先撃 dm#dm04279@武水 ，
 dm#dm04279@武水 令 rm#r05932@郭務悌 詣 dm#dm08950@魏州 求救。

 dm#dm06914@莘 令 rm#r06076@馬玄素 將兵千七百人中道邀 rm#r02804@沖 ，
恐力不敵，
入 dm#dm04279@武水 ，
閉門拒守。

 rm#r02804@沖 推草車塞其南門，
因風縱火焚之，
欲乘火突入；
火作而風囘，
 rm#r02804@沖 軍不得進，
由是氣沮。

 dm#dm01489@堂邑  rm#r05775@董玄寂 爲 rm#r02804@沖 將兵撃 dm#dm04279@武水 ，
謂人曰：
「 rm#r02804@琅邪王 與國家交戰，
此乃反也。」

 rm#r02804@沖 聞之，
斬 rm#r05775@玄寂 以徇，
衆懼而散入草澤，
不可禁止，
惟家僮左右數十人在。

 rm#r02804@沖 還走 dm#dm01088@博州 ，
戊申，
至城門，
爲守門者所殺，
凡起兵七日而敗。

 rm#r00031@丘神勣 至 dm#dm01088@博州 ，
官吏素服出迎，
 rm#r00031@神勣 盡殺之，
凡破千餘家。
盡揮刃盡盡揮刀
# p 

 rm#r03593@越王貞 聞 rm#r02804@沖 起，
亦舉兵於 dm#dm07502@豫州 ，
遣兵陷 dm#dm00187@上蔡 。

九月，
丙辰，
命左豹韜大將軍 rm#xjts23088@麹崇裕 爲中軍大總管，
 rm#r00882@岑長倩 爲後軍大總管，
將兵十萬以討之，
又命 rm#r01111@張光輔 爲諸軍節度。

削 rm#r02804@沖 屬籍，
更姓 rm#no@虺氏 。

 rm#r03593@貞 聞 rm#r02804@沖 敗，
欲自鎖詣闕謝罪，
會所署 dm#dm03390@新蔡 令 rm#r05038@傅延慶 募得勇士二千餘人，
 rm#r03593@貞 乃宣言於衆曰：
「 rm#r02804@琅邪 已破 dm#dm08945@魏 、 dm#dm06025@相 數州，
有兵二十萬，
朝夕至矣。」

發屬縣兵共得五千，
分爲五營，
使 dm#dm04462@汝南 縣丞 rm#r01701@裴守徳 等將之，
署九品以上官五百餘人。

所署官皆受迫脅，
莫有鬬志，
惟 rm#r01701@守徳 與之同謀，
 rm#r03593@貞 以其女妻之，
署大將軍，
委以腹心。

 rm#r03593@貞 使道士及僧誦經以求事成，
左右及戰士皆帶辟兵符。

 rm#xjts23088@麹崇裕 等軍至 dm#dm07502@豫州 城東四十里，
 rm#r03593@貞 遣少子 rm@規 及 rm#r01701@裴守徳 拒戰，
兵潰而歸。

 rm#r03593@貞 大懼，
閉閤自守。

 rm#xjts23088@崇裕 等至城下，
左右謂 rm#r03593@貞 曰：
「王豈可坐待戮辱！」

 rm#r03593@貞 、 rm@規 、 rm#r01701@守徳 及其妻皆自殺。

與 rm#r02804@沖 皆梟首 dm#dm03880@東都 闕下。
貞
# p 

初，
 rm#r03164@范陽王藹 遣使語 rm#r03593@貞 及 rm#r02804@沖 曰：
「若四方諸王一時竝起，
事無不濟。」

諸王往來相約結，
未定而 rm#r02804@沖 先發，
惟 rm#r03593@貞 狼狽應之，
諸王皆不敢發，
故敗。
# p 

 rm#r03593@貞 之將起兵也，
遣使告 dm#dm01521@壽州 刺史 rm#ry0005@趙瓌 ，
 rm#ry0005@瓌 妻 rm#r01028@常樂長公主 謂使者曰：
「爲我語 rm@越王 ：
昔 rm#rt0778@隋文帝 將簒 dyn#ch173@周 室，
 rm#r05200@尉遲迥  dyn#ch173@周 之甥也，
猶能舉兵匡救社稷，
功雖不成，
威震海内，
足爲忠烈。

況汝諸王，
先帝之子，
豈得不以社稷爲心！

今 rm@李氏 危若朝露，
汝諸王不捨生取義，
尚猶豫不發，
欲何須邪！

禍且至矣，
大丈夫當爲忠義鬼，
無爲徒死也。」

# p 

及 rm#r03593@貞 敗，
太后欲悉誅 dm#dm08726@韓 、 dm#dm08968@魯 等諸王，
命監察御史 dm#dm07121@藍田  rm#r03323@蘇珦 按其密状。

 rm#r03323@珦 訊問，
皆無明驗，
或告 rm#r03323@珦 與 dm#dm08726@韓 、 dm#dm08968@魯 通謀，
太后召 rm#r03323@珦 詰之，
 rm#r03323@珦 抗論不囘。

太后曰：
「卿大雅之士，
朕當別有任使，
此獄不必卿也。」

乃命 rm#r03323@珦 於 dm#dm04695@河西 監軍，
更使 rm#r00116@周興 等按之，
於是收 rm#r04123@韓王元嘉 、 rm#r04316@魯王靈夔 、 rm#r04328@黄公譔 、 rm#r01028@常樂公主 於 dm#dm03880@東都 ，
迫脅皆自殺，
更其姓曰「虺」，
親黨皆誅。
# p 

以文昌左丞 rm#r02567@狄仁傑 爲 dm#dm07502@豫州 刺史。

時治 rm#r03593@越王貞 黨與，
當坐者六七百家，
籍沒者五千口，
司刑趣使行刑。

 rm#r02567@仁傑 密奏：
「彼皆詿誤，
臣欲顯奏，
似爲逆人申理；
知而不言，
恐乖陛下仁恤之旨。」

太后特原之，
皆流 dm#dm07478@豐州 。

道過 dm#dm02291@寧州 ，
 dm#dm02291@寧州 父老迎勞之曰：
「我 rm#r02567@狄使君 活汝邪？」
相攜哭於徳政碑下，
設齋三日而後行。


# p 

時 rm#r01111@張光輔 尚在 dm#dm07502@豫州 ，
將士恃功，
多所求取，
 rm#r02567@仁傑 不之應。

 rm#r01111@光輔 怒曰：
「州將輕元帥邪？」
 rm#r02567@仁傑 曰：
「亂 dm#dm04660@河南 者一 rm#r03593@越王貞 耳，
今一 rm#r03593@貞 死，
萬 rm#r03593@貞 生！」

 rm#r01111@光輔 詰其語，
 rm#r02567@仁傑 曰：
「明公總兵三十萬，
所誅者止於 rm#r03593@越王貞 。

城中聞官軍至，
踰城出降者四面成蹊，
明公縱將士暴掠，
殺已降以爲功，
流血丹野，
非萬 rm#r03593@貞 而何！

恨不得尚方斬馬劍，
加於明公之頸，
雖死如歸耳！」

 rm#r01111@光輔 不能詰，
歸，
奏 rm#r02567@仁傑 不遜，
左遷 dm#dm02970@復州 刺史。

# p 

丁卯，
左肅政大夫 rm@騫味道 、夏官侍郎 rm#r01148@王本立 竝同平章事。
# p 

太后之召宗室朝明堂也，
 rm#r01953@東莞公融 密遣使問成均助教 rm#r04225@高子貢 ，
 rm#r04225@子貢 曰：
「來必死。」

 rm#r01953@融 乃稱疾不赴。

 rm#r03593@越王貞 起兵，
遣使約 rm#r01953@融 ，
 rm#r01953@融 蒼猝不能應，
爲官屬所逼，
執使者以聞，
擢拜右贊善大夫。

未幾，
爲支黨所引，
冬，
十月，
己亥，
戮於市，
籍沒其家。

 rm#r04225@高子貢 亦坐誅。
# p 

 dm#dm05438@濟州 刺史 rm#r03320@薛顗 、 rm#r03320@顗 弟 rm#?@緒 、 rm#?@緒 弟駙馬都尉 rm#?@紹 ，
皆與 rm#r02804@琅邪王沖 通謀。

 rm#r03320@顗 聞 rm#r02804@沖 起兵，
作兵器，
募人；
 rm#r02804@沖 敗，
殺録事參軍 rm#r06113@高纂 以滅口。

十一月，
辛酉，
 rm#r03320@顗 、 rm#?@緒 伏誅，
 rm#?@紹 以 rm#r00603@太平公主 故，
杖一百，
餓死於獄。


# p 

十二月，
乙酉，
司徒、 dm#dm08665@青州 刺史 rm#r03988@霍王元軌 坐與 rm@越王 連謀，
廢徙 dm#dm09188@黔州 ，
載以檻車，
行至 dm#dm08349@陳倉 而死。

 rm#r02402@江都王緒 、殿中監 rm#r03437@郕公裴承先 皆戮於市。

 rm#r03437@承先 ，
 rm#r03424@寂 之孫也。

# p 

命 rm#r03427@裴居道 留守 dm#dm07290@西京 。

# p 

左肅政大夫、同平章事 rm@騫味道 素不禮於殿中侍御史 rm#r00469@周矩 ，
屡言其不能了事。

會有羅告 rm#r03329@味道 者，
敕 rm#r00469@矩 按之。

 rm#r00469@矩 謂 rm#r03329@味道 曰：
「公常責 rm#r00469@矩 不了事，
今日爲公了之。」

乙亥，
 rm#r03329@味道 及其子 rm@辭玉 皆伏誅。

# p 

己酉，
太后拜 dm#dm04761@洛 受圖，
皇帝、皇太子皆從，
内外文武百官、蠻夷各依方敍立，
珍禽、奇獸、雜寶列於壇前，
文物鹵簿之盛，
 dyn#ch100@唐 興以來未之有也。酋長
# p 

辛亥，
明堂成，
高二百九十四尺，
方三百尺。

凡三層：
下層法四時，
各隨方色。

中層法十二辰；
上爲圓蓋，
九龍捧之。

上施鐵鳳，
高一丈，
飾以黄金；
中有巨木十圍，
上下通貫，
栭櫨橕𣗽藉以爲本；
下施鐵渠，
爲辟雍之象。

號曰 dm#dm06987@萬象神宮 。

宴賜羣臣，
赦天下，
縱民入觀。

改 dm#dm04660@河南 爲 dm#dm01185@合宮縣 。

又於明堂北起天堂五級以貯大像；
至三級，
則俯視明堂矣。

僧 rm#r03283@懷義 以功拜左威衞大將軍、 rm@梁國公 。
上層法二十四氣，亦爲圓蓋
# p 

侍御史 rm#r02659@王求禮 上書曰：
「古之明堂，
茅茨不翦，
采椽不斲。

今者飾以珠玉，
塗以丹青，
鐵鷟入雲，
金龍隱霧，
昔 rm#rt0056@殷辛 瓊臺，
 rm#rt0026@夏癸 瑤室，
無以加也。」

太后不報。
# p 

太后欲發梁、鳳、巴蜑，
自 dm#dm08477@雅州 開山通道，
出撃生羌，
因襲吐蕃。

正字 rm#r03920@陳子昂 上書，
以爲：
「 dm#dm08477@雅州 邊羌，
自國初以來未嘗爲盜。

今一旦無罪戮之，
其怨必甚；
且懼誅滅，
必蜂起爲盜。

 dm#dm07314@西山 盜起，
則 dm#dm07197@蜀 之邊邑不得不連兵備守，
兵久不解，
臣愚以爲 dm#dm07381@西蜀 之禍，
自此結矣。

臣聞吐蕃愛 dm#dm07197@蜀 富饒，
欲盜之久矣，
徒以山川阻絶，
障隘不通，
勢不能動。

今國家乃亂邊羌，
開隘道，
使其收奔亡之種，
爲郷導以攻邊，
是借寇兵爲賊除道，
舉全 dm#dm07197@蜀 以遺之也。

 dm#dm07197@蜀 者國家之寶庫，
可以兼濟 dm#dm00255@中國 。

今執事者乃圖僥幸之利以事 dm#dm07374@西羌 ，
得其地不足以稼穡，
財不足以富國，
徒爲糜費，
無益聖徳，
況其成敗未可知哉！

夫 dm#dm07197@蜀 之所恃者險也，
人之所以安者無役也；
今國家乃開其險，
役其人，
險開則便寇，
人役則傷財，
臣恐未見羌戎，
已有姦盜在其中矣。

且 dm#dm07197@蜀 人尫劣，
不習兵戰，
山川阻曠，
去 dm#dm00257@中夏 遠，
今無故生西羌、吐蕃之患，
臣見其不及百年，
 dm#dm07197@蜀 爲戎矣。

國家近廢 dm#dm01976@安北 ，
拔 dm#dm01394@單于 ，
棄 dm#dm09290@龜茲 ，
放 dm#dm05857@疏勒 ，
天下翕然謂之盛徳者，
蓋以陛下務在養人，
不在廣地也。

今 dm#dm02403@山東 饑，
 dm#dm08280@關 、 dm#dm08457@隴 弊，
而徇貪夫之議，
謀動甲兵，
興大役，
自古國亡家敗，
未嘗不由黷兵，
願陛下熟計之。」

既而役不果興。
** 永昌
*** 永昌元年
# year 0689
# p 

春，
正月，
乙卯朔，
大饗 dm#dm06987@萬象神宮 ，
太后服袞冕，
搢大圭，
執鎭圭爲初獻，
皇帝爲亞獻，
太子爲終獻。

先詣昊天上帝座，
次 rm#r04258@高祖 、 rm#r01602@太宗 、 rm#r01837@高宗 ，
次 rm#r02300@魏國先王 ，
次五方帝座。

太后御 dm#dm00765@則天門 ，
赦天下，
改元。

丁巳，
太后御明堂，
受朝賀。

戊午，
布政于明堂，
頒九條以訓百官。

己未，
御明堂，
饗羣臣。


# p 

二月，
丁酉，
尊 rm#r02300@魏忠孝王 曰 rm#r02300@周忠孝太皇 ，
妣曰 rm#xjts22959@忠孝太后 ，
 dm#dm03309@文水 陵曰 dm#dm06343@章徳陵 ，
 dm#dm01345@咸陽 陵曰 dm#dm03485@明義陵 。

置崇先府官。

戊戌，
尊 rm#xjts06550@魯公 曰 rm#xjts06550@太原靖王 ，
 rm#xjts06579@北平王 曰 rm#xjts06579@趙肅恭王 ，
 rm#xjts06533@金城王 曰 rm#xjts06533@魏義康王 ，
 rm#xjts06555@太原王 曰 rm#xjts06555@周安成王 。
# p 

三月，
甲子，
 rm#r01111@張光輔 守納言。
# p 

壬申，
太后問正字 rm#r03920@陳子昂 ，
當今爲政之要。

 rm#r03920@子昂 退，
上疏，
以爲「宜緩刑崇徳，
息兵革，
省賦役，
撫慰宗室，
各使自安。」

辭婉意切，
其論甚美，
凡三千言。
# p 

癸酉，
以天官尚書 rm#r02314@武承嗣 爲納言，
 rm#r01111@張光輔 守内史。
# p 

夏，
四月，
甲辰，
殺 dm#dm07659@辰州 別駕 rm#r03208@汝南王煒 、 dm#dm07711@連州 別駕 rm@鄱陽公  rm#r00067@諲 等宗室十二人，
徙其家於 dm#dm02536@巂州 。

 rm#r03208@煒 ，
 rm#r03207@惲 之子；
諲，
 rm#r03674@元慶 之子也。

# p 

己酉，
殺天官侍郎 dm#dm07121@藍田  rm#r03763@鄧玄挺 。

 rm#r03763@玄挺 女爲 rm@諲 妻，
又與 rm#r03208@煒 善。

 rm@諲 謀迎 rm#r01656@中宗 於 dm#dm02796@廬陵 ，
以問 rm#r03763@玄挺 ；
 rm#r03208@煒 又嘗謂 rm#r03763@玄挺 曰：
「欲爲急計，
何如？」
 rm#r03763@玄挺 皆不應。

故坐知反不告，
同誅。
# p 

五月，
丙辰，
命文昌右相 rm#r04030@韋待價 爲 dm#dm02022@安息道 行軍大總管，
撃吐蕃。

# p 

 dm#dm04873@浪穹州 蠻酋 rm@傍時昔 等二十五部，
先附吐蕃，
至是來降；
以 rm@傍時昔 爲 dm#dm04873@浪穹州 刺史，
令統其衆。


# p 

己巳，
以僧 rm#r03283@懷義 爲 dm#dm03349@新平軍 大總管，
北討突厥。

行至 dm#dm06416@紫河 ，
不見虜，
於 dm#dm01398@單于臺 刻石紀功而還。

# p 

諸王之起兵也，
 dm#dm07514@貝州 刺史 rm#r03068@紀王愼 獨不預謀，
亦坐繋獄；
秋七月，
丁巳，
檻車徙 dm#dm02572@巴州 ，
更姓 rm@虺氏 ，
行及 dm#dm07029@蒲州 而卒。

八男 dm#dm02952@徐州 刺史 rm#r02070@東平王續 等，
相繼被誅，
家徙 dm#dm02527@嶺南 。
# p 

女 rm#r02069@東光縣主  rm#r02069@楚媛 ，
幼以孝謹稱，
適司議郎 rm#r05840@裴仲將 ，
相敬如賓；
姑有疾，
親嘗藥膳；
接遇娣姒，
皆得歡心。

時宗室諸女皆以驕奢相尚，
誚 rm#r02069@楚媛 獨儉素，
曰：
「所貴於富貴者，
得適志也；
今獨守勤苦，
將以何求？」
 rm#r02069@楚媛 曰：
「幼而好禮，
今而行之，
非適志歟！

觀自古女子，
皆以恭儉爲美，
縱侈爲惡。

辱親是懼，
何所求乎；
富貴儻來之物，
何足驕人！」

衆皆慙服。

及 rm#r03068@愼 凶問至，
 rm#r02069@楚媛 號慟，
嘔血數升；
免喪，
不御膏沐者垂二十年。


# p 

 rm#r04030@韋待價 軍至 dm#dm02258@寅識迦河 ，
與吐蕃戰，
大敗。

 rm#r04030@待價 既無將領之才，
狼狽失據，
士卒凍餒，
死亡甚衆，
乃引軍還。

太后大怒，
丙子，
 rm#r04030@待價 除名，
流 dm#dm06487@繡州 ，
斬副大總管 dm#dm02061@安西 大都護 rm#r05986@閻温古 。

 dm#dm02061@安西 副都護 rm#r00488@唐休璟 收其餘衆，
撫安西土，
太后以 rm#r00488@休璟 爲 dm#dm07317@西州 都督。會大雪，糧運不繼
# p 

戊寅，
以 rm#r01148@王本立 同鳳閣鸞臺三品。
# p 

 rm#r01788@徐敬業 之敗也，
弟 rm#r05320@敬眞 流 dm#dm06487@繡州 ，
逃歸，
將奔突厥。

過 dm#dm04788@洛陽 ，
 dm#dm04778@洛州 司馬 rm#ry0014@弓嗣業 、 dm#dm04788@洛陽 令 rm#r05256@張嗣明 資遣之；
至 dm#dm02124@定州 ，
爲吏所獲，
 rm#ry0014@嗣業 縊死。

 rm#r05256@嗣明 、 rm#r05320@敬眞 多引海内知識，
云有異圖，
冀以免死；
於是朝野之士爲所連引坐死者甚衆。

 rm#r05256@嗣明 誣内史 rm#r01111@張光輔 ，
云「征 dm#dm07502@豫州 日，
私論圖讖、天文，
陰懷兩端。」

八月，
甲申，
 rm#r01111@光輔 與 rm#r05320@敬眞 、 rm#r05256@嗣明 等同誅，
籍沒其家。
# p 

乙未，
秋官尚書 dm#dm01774@太原  rm#r01190@張楚金 、 dm#dm08320@陝州 刺史 rm#r03730@郭正一 、鳳閣侍郎 rm#r00162@元萬頃 、 dm#dm04788@洛陽 令 rm#r04302@魏元忠 ，
竝免死流 dm#dm02527@嶺南 。

 rm#r01190@楚金 等皆爲 rm#r05320@敬眞 所引，
云與 rm#r01788@敬業 通謀。

臨刑，
太后使鳳閣舍人 rm#r02800@王隱客 馳騎傳聲赦之。

聲達於市，
當刑者皆喜躍讙呼，
宛轉不已；
 rm#r04302@元忠 獨安坐自如，
或使之起，
 rm#r04302@元忠 曰：
「虚實未知。」

 rm#r02800@隱客 至，
又使起，
 rm#r04302@元忠 曰：
「俟宣敕已。」

既宣敕，
乃徐起，
舞蹈再拜，
竟無憂喜之色。

是日，
陰雲四塞，
既釋 rm#r01190@楚金 等，
天氣晴霽。

# p 

九月，
壬子，
以僧 rm#r03283@懷義 爲 dm#dm03350@新平道 行軍大總管，
將兵二十萬討突厥 rm#r06002@骨篤祿 。

# p 

初，
 rm#r01837@高宗 之世，
 rm#r00116@周興 以 dm#dm04709@河陽 令召見，
上欲加擢用，
或奏以爲非清流，
罷之。

 rm#r00116@興 不知，
數於朝堂俟命。

諸相皆無言，
地官尚書、檢校納言 rm#r04301@魏玄同 ，
時同平章事，
謂之曰：
「 dm#dm01308@周明府 可去矣。」

 rm#r00116@興 以爲 rm#r04301@玄同 沮己，
銜之。

 rm#r04301@玄同 素與 rm#r03449@裴炎 善，
時人以其終始不渝，
謂之耐久朋。

 rm#r00116@周興 奏誣 rm#r04301@玄同 言：
「太后老矣，
不若奉嗣君爲耐久。」

太后怒，
閏月，
甲午，
賜死于家。

監刑御史 rm#r05330@房濟 謂 rm#r04301@玄同 曰：
「丈人何不告密，
冀得召見，
可以自直！」

 rm#r04301@玄同 歎曰：
「人殺鬼殺，
亦復何殊，
豈能作告密人邪！」

乃就死。

又殺夏官侍郎 rm#r05203@崔詧 於隱處。

自餘内外大臣坐死及流貶者甚衆。
# p 

 dm#dm02932@彭州 長史 rm#r00274@劉易從 亦爲 rm#r05320@徐敬眞 所引；
戊申，
就州誅之。

 rm#r00274@易從 爲人，
仁孝忠謹，
將刑於市，
吏民憐其無辜，
遠近奔赴，
競解衣投地曰：
「爲長史求冥福。」

有司平準，
直十餘萬。
# p 

 rm#r00116@周興 等誣右武衞大將軍 rm@燕公  rm#r04339@黒齒常之 謀反，
徵下獄。

冬，
十月，
戊午，
 rm#r04339@常之 縊死。

# p 

己未，
殺宗室 dm#dm07895@鄂州 刺史嗣 rm#r00559@鄭王璥 等六人。

庚申，
嗣 rm@滕王  rm#r03875@脩琦 等六人免死，
流 dm#dm02527@嶺南 。

# p 

丁卯，
春官尚書 rm#r03156@范履冰 、鳳閣侍郎 rm#r03683@邢文偉 竝同平章事。
# p 

己卯，
詔 rm#r03010@太穆神皇后 、 rm#r03854@文徳聖皇后 宜配皇地祇，
 rm@忠孝太后 從配。


# p 

右衞冑曹參軍 rm#r03920@陳子昂 上疏，
以爲：
「 dyn#ch103@周 頌 rm#rt0065@成 、 rm#rt0066@康 ，
 dyn#ch129@漢 稱 rm#rt0515@文 、 rm#rt0516@景 ，
皆以能措刑故也。

今陛下之政，
雖盡善矣，
然太平之朝，
上下樂化，
不宜有亂臣賊子，
日犯天誅。

比者大獄増多，
逆徒滋廣，
愚臣頑昧，
初謂皆實，
乃去月十五日，
陛下特察繋囚 rm#r05417@李珍 等無罪，
百僚慶悦，
皆賀聖明，
臣乃知亦有無罪之人挂於疏網者。

陛下務在寛典，
獄官務在急刑，
以傷陛下之仁，
以誣太平之政，
臣竊恨之。

又，
九月二十一日敕免 rm#r01190@楚金 等死，
初有風雨，
變爲景雲。

臣聞陰慘者刑也，
陽舒者徳也；
聖人法天，
天亦助聖，
天意如此，
陛下豈可不承順之哉！

今又陰雨，
臣恐過在獄官。

凡繋獄之囚，
多在極法，
道路之議，
或是或非，
陛下何不悉召見之，
自詰其罪！

罪有實者顯示明刑，
濫者嚴懲獄吏，
使天下咸服，
人知政刑，
豈非至徳克明哉！」

** 載初
*** 載初元年
# year 0690
# p 

十一月，
庚辰朔，
日南至。

太后享 dm#dm06987@萬象神宮 ，
赦天下。

始用 dyn#ch176@周 正，
改 y@永昌元年十一月 爲 y@載初元年正月 ，
以十二月爲臘月，
夏正月爲一月。

以 dyn#ch103@周 、 dyn#ch129@漢 之後爲二王後，
 rm#rt0007@舜 、 rm#rt0008@禹 、 rm#rt0027@成湯 之後爲三恪，
 dyn#ch173@周 、 dyn#ch174@隋 之嗣同列國。

# p 

鳳閣侍郎 dm#dm04672@河東  rm#r05191@宗秦客 ，
改造「天」
「地」
等十二字以獻，
丁亥，
行之。

太后自名「曌」，
改詔曰制。

 rm#r05191@秦客 ，
太后從父姉之子也。

# p 

乙未，
司刑少卿 rm#r00116@周興 奏除唐親屬籍。
# p 

臘月，
辛未，
以僧 rm#r03283@懷義 爲右衞大將軍，
賜爵 rm@鄂國公 。
# p 

春，
一月，
戊子，
 rm#r02314@武承嗣 遷文昌左相，
 rm#r00882@岑長倩 遷文昌右相、同鳳閣鸞臺三品，
鳳閣侍郎 rm#r06225@武攸寧 爲納言，
 rm#r03683@邢文偉 守内史，
左肅政大夫、同鳳閣鸞臺三品 rm#r01148@王本立 罷爲地官尚書。

 rm#r06225@攸寧 ，
 rm#r02300@士彠 之兄孫也。

# p 

時 rm#r02314@武承嗣 、 rm#r02294@三思 用事，
宰相皆下之。

地官尚書、同鳳閣鸞臺三品 rm#r04039@韋方質 有疾，
 rm#r02314@承嗣 、 rm#r02294@三思 往問之，
 rm#r04039@方質 據牀不爲禮。

或諫之，
 rm#r04039@方質 曰：
「死生有命，
大丈夫安能曲事近戚以求苟免乎！」

尋爲 rm#r00116@周興 等所搆，
甲午，
流 dm#dm00623@儋州 ，
籍沒其家。

# p 

二月，
辛酉，
太后策貢士於 dm#dm04775@洛城殿 。

貢士殿試自此始。
# p 

丁卯，
地官尚書 rm#r01148@王本立 薨。

# p 

三月，
丁亥，
特進、同鳳閣鸞臺三品 rm#r03343@蘇良嗣 薨。


# p 

夏，
四月，
丁巳，
春官尚書、同平章事 rm#r03156@范履冰 坐嘗舉犯逆者下獄死。

# p 

 dm#dm07988@醴泉 人 rm#r00126@侯思止 ，
始以賣餅爲業，
後事游撃將軍 rm#r06096@高元禮 爲僕，
素詭譎無頼。

 dm#dm03023@恆州 刺史 rm#r05855@裴貞 杖一判司，
判司使 rm#r00126@思止 告 rm#r05855@貞 與 rm#r03143@舒王元名 謀反，
秋，
七月，
辛巳，
 rm#r03143@元名 坐廢，
徙 dm#dm01327@和州 ，
壬午，
殺其子 rm#r03556@豫章王亶 ；
 rm#r05855@貞 亦族滅。

擢 rm#r00126@思止 爲游撃將軍。

時，
告密者往往得五品，
 rm#r00126@思止 求爲御史，
太后曰：
「卿不識字，
豈堪御史！」

對曰：
「獬豸何嘗識字，
但能觸邪耳。」

太后悦，
即以爲朝散大夫、侍御史。

他日，
太后以先所籍沒宅賜之，
 rm#r00126@思止 不受，
曰：
「臣惡反逆之人，
不願居其宅。」

太后益賞之。
# p 

 dm#dm07232@衡水 人 rm#r02627@王弘義 ，
素無行，
嘗從鄰舍乞瓜，
不與，
乃告縣官，
瓜田中有白兔；
縣官使人搜捕，
蹂踐瓜田立盡。

又遊 dm#dm07617@趙 、 dm#dm07512@貝 ，
見閭里耆老作邑齋，
遂告以謀反，
殺二百餘人。

擢授游撃將軍，
俄遷殿中侍御史。

或告 dm#dm00812@勝州 都督 rm#r02738@王安仁 謀反，
敕 rm#r02627@弘義 按之。

 rm#r02738@安仁 不服，
 rm#r02627@弘義 即於枷上刎其首；
又捕其子，
適至，
亦刎其首，
函之以歸。

道過 dm#dm04561@汾州 ，
司馬 rm@毛公 與之對食，
須臾，
叱 rm@毛公 下階，
斬之，
槍掲其首入 dm#dm04761@洛 ，
見者無不震栗。

# p 

時置制獄於 dm#dm09086@麗景門 内，
入是獄者，
非死不出，
 rm#r02627@弘義 戲呼曰「例竟門」。

朝士人人自危，
相見莫敢交言，
道路以目。

或因入朝密遭掩捕，
毎朝，
輒與家人訣曰：
「未知復相見否？」

# p 

時法官競爲深酷，
唯司刑丞 rm#r01311@徐有功 、 rm#r02049@杜景儉 獨存平恕，
被告者皆曰：
「遇 rm#r00115@來 、 rm#r00126@侯 必死，
遇 rm#r01311@徐 、 rm#r02049@杜 必生。」

# p 

 rm#r01311@有功 ，
 rm#r01316@文遠 之孫也，
名 rm#r01311@弘敏 ，
以字行。

初爲 dm#dm07029@蒲州 司法，
以寛爲治，
不施敲朴。

吏相約有犯 rm#r01311@徐 司法杖者，
衆共斥之。

迨官滿，
不杖一人，
職事亦脩。

累遷司刑丞，
酷吏所誣構者，
 rm#r01311@有功 皆爲直之，
前後所活數十百家。

嘗廷爭獄事，
太后厲色詰之，
左右爲戰栗，
 rm#r01311@有功 神色不撓，
爭之彌切。

太后雖好殺，
知 rm#r01311@有功 正直，
甚敬憚之。

 rm#r02049@景儉 ，
 dm#dm04306@武邑 人也。

# p 

司刑丞 dm#dm05216@滎陽  rm#r01795@李日知 亦尚平恕。

少卿 rm#ry0015@胡元禮 欲殺一囚，
 rm#r01795@日知 以爲不可，
往復數四，
 rm#ry0015@元禮 怒曰：
「 rm#ry0015@元禮 不離刑曹，
此囚終無生理！」

 rm#r01795@日知 曰：
「 rm#r01795@日知 不離刑曹，
此囚終無死法！」

竟以兩状列上，
 rm#r01795@日知 果直。
# p 

 dm#dm03898@東魏國寺 僧 rm@法明 等撰大雲經四卷，
表上之，
言太后乃彌勒佛下生，
當代 dyn#ch100@唐 爲閻浮提主，
制頒於天下。
# p 

 rm#r02314@武承嗣 使 rm#r00116@周興 羅告 dm#dm08439@隋州 刺史 rm#r02521@澤王上金 、 dm#dm06799@舒州 刺史 rm#r03522@許王素節 謀反，
徵詣行在。

 rm#r03522@素節 發 dm#dm06799@舒州 ，
聞遭喪哭者，
歎曰：
「病死何可得，
乃更哭邪！」

丁亥，
至 dm#dm09269@龍門 ，
縊殺之。

 rm#r02521@上金 自殺。

悉誅其諸子及支黨。
# p 

太后欲以 rm#r00603@太平公主 妻其伯父 rm#r05685@士讓 之孫 rm#r02317@攸曁 ，
 rm#r02317@攸曁 時爲右衞中郎將，
太后潛使人殺其妻而妻之。

公主方額廣頤，
多權略，
太后以爲類己，
寵愛特厚，
常與密議天下事。

舊制，
食邑，
諸王不過千戸，
公主不過三百五十戸；
 rm#r00603@太平 食邑獨累加至三千戸。


# p 

八月，
甲寅，
殺太子少保、納言 rm#r03427@裴居道 ；
癸亥，
殺尚書左丞 rm#r05299@張行廉 。

辛未，
殺 rm#r00351@南安王潁 等宗室十二人，
又鞭殺故太子 rm#r03054@賢 二子，
 dyn#ch100@唐 之宗室於是殆盡矣，
其幼弱存者亦流 dm#dm02527@嶺南 ，
又誅其親黨數百家。

惟 rm#r00783@千金長公主 以巧媚得全，
自請爲太后女，
仍改姓 rm#r02293@武氏 ；
太后愛之，
更號 rm#r00783@延安大長公主 。

** 天授
*** 天授元年
# year 0690
# p 

九月，
丙子，
侍御史 dm#dm04534@汲 人 rm#r00142@傅遊藝 帥 dm#dm08281@關中 百姓九百餘人詣闕上表，
請改國號曰 dyn#ch103@周 ，
賜皇帝姓 rm#r02293@武氏 。

太后不許；
擢 rm#r00142@遊藝 爲給事中。

於是百官及帝室宗戚、遠近百姓、四夷酋長、沙門、道士合六萬餘人，
倶上表如 rm#r00142@遊藝 所請，
皇帝亦上表自請賜姓 rm#r02293@武氏 。

戊寅，
羣臣上言：
有鳳皇自明堂飛入 dm#dm00199@上陽宮 ，
還集左臺梧桐之上，
久之，
飛東南去；
及赤雀數萬集朝堂。

# p 

庚辰，
太后可皇帝及羣臣之請。

壬午，
御 dm#dm00764@則天樓 ，
赦天下，
以 dyn#ch100@唐 爲 dyn#ch103@周 ，
改元。

乙酉，
上尊號曰 rm#r02293@聖神皇帝 ，
以皇帝爲皇嗣，
賜姓 rm#r02293@武氏 ；
以皇太子爲皇孫。
# p 

丙戌，
立 rm#r02293@武氏 七廟于 dm#dm06235@神都 ，
追尊 rm#rt0063@周文王 曰 rm#rt0063@始祖文皇帝 ，
妣 rm@姒氏 曰 rm@文定皇后 ；
 rm#*ry0017@平王 少子 rm@武 曰 rm@睿祖康皇帝 ，
妣 rm@姜氏 曰 rm@康睿皇后 ；
 rm#xjts06550@太原靖王 曰 rm#xjts06550@嚴祖成皇帝 ，
妣曰 rm@成莊皇后 ；
 rm#xjts06579@趙肅恭王 曰 rm#xjts06579@肅祖章敬皇帝 ，
 rm#xjts06533@魏義康王 曰 rm#xjts06533@烈祖昭安皇帝 ，
 rm#xjts06555@周安成王 曰 rm#xjts06555@顯祖文穆皇帝 ，
 rm#r02300@忠孝太皇 曰 rm#r02300@太祖孝明高皇帝 ，
妣皆如考諡，
稱皇后。

立 rm#r02314@武承嗣 爲 rm#r02314@魏王 ，
 rm#r02294@三思 爲 rm#r02294@梁王 ，
 rm#r06225@攸寧 爲 rm#r06225@建昌王 ，
 rm#r02300@士彠 兄孫 rm#r05440@攸歸 、 rm#r05542@重規 、 rm#xjts06554@載徳 、 rm#r02317@攸曁 、 rm#r02313@懿宗 、 rm#xjts06571@嗣宗 、 rm#r06224@攸宜 、 rm#xjts06534@攸望 、 rm#r02318@攸緒 、 rm#r06672@攸止 皆爲郡王，
諸姑姉皆爲長公主。
睿惠
# p 

又以司賓卿 dm#dm05186@溧陽  rm#r00375@史務滋 爲納言，
鳳閣侍郎 rm#r05191@宗秦客 檢校内史，
給事中 rm#r00142@傅遊藝 爲鸞臺侍郎、平章事。

 rm#r00142@遊藝 與 rm#r00882@岑長倩 、右玉鈐衞大將軍 rm#r06190@張虔勗 、左金吾大將軍 rm#r00031@丘神勣 、侍御史 rm#r00117@來子珣 等竝賜姓 rm#no@武 。

 rm#r05191@秦客 潛勸太后革命，
故首爲内史。

 rm#r00142@遊藝 朞年之中歴衣青、緑、朱、紫，
時人謂之四時仕宦。

# p 

敕改州爲郡；
或謂太后曰：
「陛下始革命而廢州，
不祥。」

太后遽追止之。
# p 

命 rm#r00375@史務滋 等十人巡撫諸道。

太后立兄孫 rm#r02308@延基 等六人爲郡王。巡存癸卯
# p 

冬，
十月，
甲子，
檢校内史 rm#r05191@宗秦客 坐贓貶 dm#dm07760@遵化 尉，
弟 rm#r00825@楚客 亦以姦贓流嶺外。晉卿
# p 

丁卯，
殺流人 rm#r04039@韋方質 。


# p 

辛未，
内史 rm#r03683@邢文偉 坐附會 rm#r05191@宗秦客 貶 dm#dm05735@珍州 刺史。

頃之，
有制使至州，
 rm#r03683@文偉 以爲誅己，
遽自縊死。

# p 

壬申，
敕 dm#dm00683@兩京 諸州各置 dm#dm01699@大雲寺 一區，
藏大雲經，
使僧升高座講解，
其撰疏僧 rm@雲宣 等九人皆賜爵縣公，
仍賜紫袈裟、銀龜袋。

# p 

制天下 rm#r02293@武氏 咸蠲課役。
# p 

西突厥十姓，
自 y@垂拱 以來爲東突厥所侵掠，
散亡略盡。

 dm#dm05429@濛池 都護 rm@繼往絶可汗  rm@斛瑟羅 收其餘衆六七萬人入居内地，
拜右衞大將軍，
改號 rm@竭忠事主可汗 。

# p 

 dm#dm07742@道州 刺史 rm#r05431@李行褒 兄弟爲酷吏所陷，
當族，
秋官郎中 rm#r01311@徐有功 固爭不能得。

秋官侍郎 rm#r00116@周興 奏 rm#r01311@有功 出反囚，
當斬，
太后雖不許，
亦免 rm#r01311@有功 官；
然太后雅重 rm#r01311@有功 ，
久之，
復起爲侍御史。

 rm#r01311@有功 伏地流涕固辭曰：
「臣聞鹿走山林而命懸庖廚，
勢使之然也。

陛下以臣爲法官，
臣不敢枉陛下法，
必死是官矣。」

太后固授之，
遠近聞者相賀。故
# p 

是歳，
以右衞大將軍 rm#r02434@泉獻誠 爲左衞大將軍。

太后出金寶，
命選南北牙善射者五人賭之，
 rm#r02434@獻誠 第一，
以讓右玉鈐衞大將軍 rm#r05800@薛咄摩 ，
 rm#r05800@咄摩 復讓 rm#r02434@獻誠 。

 rm#r02434@獻誠 乃奏言：
「陛下令選善射者，
今多非 dm#dm05271@漢 官，
竊恐四夷輕 dm#dm05271@漢 ，
請停此射。」

太后善而從之。
*** 二年
# year 0691
# p 

正月，
癸酉朔，
太后始受尊號於 dm#dm06987@萬象神宮 ，
旗幟尚赤。

甲戌，
改置社稷於 dm#dm06235@神都 。

辛巳，
納 rm#r02293@武氏 神主于太廟；
 dyn#ch100@唐 太廟之在 dm#dm08170@長安 者，
更命曰 dm#dm00425@享徳廟 。

四時唯享 rm#r04258@高祖 已下，
餘四室皆閉不享。

又改 dm#dm08170@長安  dm#dm02458@崇先廟 爲 dm#dm02460@崇尊廟 。

乙酉，
日南至，
大享明堂，
祀昊天上帝，
百神從祀，
 rm#r02293@武氏 祖宗配饗，
 dyn#ch100@唐 三帝亦同配。餘三廟餘四廟四廟餘
# p 

御史中丞知大夫事 rm#r01666@李嗣眞 以酷吏縱横，
上疏，
以爲：
「今告事紛紜，
虚多實少，
恐有凶慝陰謀離間陛下君臣。

古者獄成，
公卿參聽，
王必三宥，
然後行刑。

比日獄官單車奉使，
推鞫既定，
法家依斷，
不令重推；
或臨時專決，
不復聞奏。

如此，
則權由臣下，
非審愼之法，
儻有冤濫，
何由可知！

況以九品之官專命推覆，
操殺生之柄，
竊人主之威，
按覆既不在秋官，
省審復不由門下，
國之利器，
輕以假人，
恐爲社稷之禍。」

太后不聽。
# p 

 dm#dm08803@饒陽 尉 rm#r05144@姚貞亮 等數百人表請上尊號曰上聖大神皇帝，
不許。
# p 

侍御史 rm#r00117@來子珣 誣尚衣奉御 rm#r05086@劉行感 兄弟謀反，
皆坐誅。
# p 

春，
一月，
地官尚書 rm#r01755@武思文 及朝集使二千八百人，
表請封中嶽。

# p 

己亥，
廢 dyn#ch100@唐  dm#dm06768@興寧 、 dm#dm04418@永康 、 dm#dm08456@隱陵 署官，
唯量置守戸。


# p 

左金吾大將軍 rm#r00031@丘神勣 以罪誅。
# p 

納言 rm#r00375@史務滋 與 rm#r00115@來俊臣 同鞫 rm#r05086@劉行感 獄，
 rm#r00115@俊臣 奏 rm#r00375@務滋 與 rm#r05086@行感 親密，
意欲寢其反状。

太后命 rm#r00115@俊臣 幷推之。

 rm#r00375@務滋 恐懼自殺。庚子
# p 

或告文昌右丞 rm#r00116@周興 與 rm#r00031@丘神勣 通謀，
太后命 rm#r00115@來俊臣 鞫之，
 rm#r00115@俊臣 與 rm#r00116@興 方推事對食，
謂 rm#r00116@興 曰：
「囚多不承，
當爲何法？」
 rm#r00116@興 曰：
「此甚易耳！

取大甕，
以炭四周炙之，
令囚入中，
何事不承！」

 rm#r00115@俊臣 乃索大甕，
火圍如 rm#r00116@興 法，
因起謂 rm#r00116@興 曰：
「有内状推兄，
請兄入此甕！」

 rm#r00116@興 惶恐叩頭伏罪。

法當死，
太后原之，
二月，
流 rm#r00116@興  dm#dm02527@嶺南 ，
在道，
爲仇家所殺。
# p 

 rm#r00116@興 與 rm#r03074@索元禮 、 rm#r00115@來俊臣 競爲暴刻，
 rm#r00116@興 、 rm#r03074@元禮 所殺各數千人，
 rm#r00115@俊臣 所破千餘家。

 rm#r03074@元禮 殘酷尤甚，
太后亦殺之以慰人望。
# p 

徙左衞大將軍 rm#r02317@千乘王武攸曁 爲 rm#r02317@定王 。

# p 

立故太子 rm#r03054@賢 之子 rm#r02259@光順 爲 rm#r02259@義豐王 。

# p 

甲子，
太后命 rm#*rt0063@始祖 墓曰 dm#dm02981@徳陵 ，
 rm@睿祖 墓曰 dm#dm01392@喬陵 ，
 rm@嚴祖 墓曰 dm#dm06372@節陵 ，
 rm@肅祖 墓曰 dm#dm06376@簡陵 ，
 rm@烈祖 墓曰 dm#dm08695@靖陵 ，
 rm@顯祖 墓曰 dm#dm04450@永陵 ，
改 dm#dm06343@章徳陵 爲 dm#dm03459@昊陵 ，
 dm#dm08771@顯義陵 爲 dm#dm08748@順陵 。

# p 

追復 rm#r01653@李君羨 官爵。


# p 

夏，
四月，
壬寅朔，
日有食之。
# p 

癸卯，
制以釋教開革命之階，
升於道教之上。
# p 

命 rm#r01703@建安王  rm#r06224@攸宜 留守 dm#dm08170@長安 。

# p 

丙辰，
鑄大鍾，
置北闕。
# p 

五月，
以 rm#r00882@岑長倩 爲 dm#dm04242@武威道 行軍大總管，
撃 dm#*dm01250@吐蕃 ，
中道召還，
軍竟不出。
# p 

六月，
以左肅政大夫 rm#r02114@格輔元 爲地官尚書，
與鸞臺侍郎 rm#r02265@樂思晦 、鳳閣侍郎 rm#r00093@任知古 竝同平章事。

 rm#r02265@思晦 ，
 rm#r02262@彦暐 之子也。

# p 

秋，
七月，
徙 dm#dm08283@關内 戸數十萬以實 dm#dm04788@洛陽 。
# p 

八月，
戊申，
納言 rm#r06225@武攸寧 罷爲左羽林大將軍；
夏官尚書 rm#r02290@歐陽通 爲司禮卿兼判納言事。

# p 

庚申，
殺玉鈐衞大將軍 rm#r06190@張虔勗 。

 rm#r00115@來俊臣 鞫 rm#r06190@虔勗 獄，
 rm#r06190@虔勗 自訟於 rm#r01311@徐有功 ；
 rm#r00115@俊臣 怒，
命衞士以刀亂斫殺之，
梟首于市。


# p 

 rm#r02259@義豐王光順 、 rm#r03679@嗣雍王守禮 、 rm#r02381@永安王守義 、 rm@長信縣主 等皆賜姓 rm#no@武氏 ，
與 rm#r01797@睿宗 諸子皆幽閉宮中，
不出門庭者十餘年。

 rm#r03679@守禮 、 rm#r02381@守義 ，
 rm#r02259@光順 之弟也。
# p 

或告地官尚書 rm#r01755@武思文 初與 rm#r01788@徐敬業 通謀；
甲子，
流 rm#r01755@思文 於 dm#dm02527@嶺南 ，
復姓 rm#no@徐氏 。

# p 

九月，
乙亥，
殺 dm#dm02420@岐州 刺史 rm@雲弘嗣 。

 rm#r00115@來俊臣 鞫之，
不問一款，
先斷其首，
乃僞立案奏之，
其殺 rm#r06190@張虔勗 亦然。

敕旨皆依，
海内鉗口。

# p 

鸞臺侍郎、同平章事 rm#r00142@傅遊藝 夢登 dm#dm05164@湛露殿 ，
以語所親，
所親告之；
壬辰，
下獄，
自殺。

# p 

癸巳，
以左羽林衞大將軍 rm#r06225@建昌王武攸寧 爲納言，
 dm#dm04778@洛州 司馬 rm#r02567@狄仁傑 爲地官侍郎，
與冬官侍郎 rm#ry0016@裴行本 竝同平章事。

太后謂 rm#r02567@仁傑 曰：
「卿在 dm#dm04462@汝南 ，
甚有善政，
卿欲知譖卿者名乎？」
 rm#r02567@仁傑 謝曰：
「陛下以臣爲過，
臣請改之；
知臣無過，
臣之幸也，
不願知譖者名。」

太后深歎美之。
# p 

先是，
鳳閣舍人 dm#dm06632@脩武  rm#r06184@張嘉福 使 dm#dm04788@洛陽 人 rm#r05630@王慶之 等數百人上表，
請立 rm#r02314@武承嗣 爲皇太子。

文昌右相、同鳳閣鸞臺三品 rm#r00882@岑長倩 以皇嗣在東宮，
不宜有此議，
奏請切責上書者，
告示令散。

太后又問地官尚書、同平章事 rm#r02114@格輔元 ，
 rm#r02114@輔元 固稱不可。

由是大忤諸 rm#no@武 意，
故斥 rm#r00882@長倩 令西征吐蕃，
未至，
徵還，
下制獄。

 rm#r02314@承嗣 又譖 rm#r02114@輔元 。

 rm#r00115@來俊臣 又脅 rm#r00882@長倩 子 rm@靈原 ，
令引司禮卿兼判納言事 rm#r02290@歐陽通 等數十人，
皆云同反。

 rm#r02290@通 爲 rm#r00115@俊臣 所訊，
五毒備至，
終無異詞，
 rm#r00115@俊臣 乃詐爲 rm#r02290@通 款。

冬，
十月，
己酉，
 rm#r00882@長倩 、 rm#r02114@輔元 、 rm#r02290@通 等皆坐誅。
# p 

 rm#r05630@王慶之 見太后，
太后曰：
「皇嗣我子，
奈何廢之？」
 rm#r05630@慶之 對曰：
「『神不歆非類，
民不祀非族。』

今誰有天下，
而以 rm@李氏 爲嗣乎！」

太后諭遣之。

 rm#r05630@慶之 伏地，
以死泣請，
不去，
太后乃以印紙遺之曰：
「欲見我，
以此示門者。

」
自是 rm#r05630@慶之 屡求見，
太后頗怒之，
命鳳閣侍郎 rm#r01805@李昭徳 賜 rm#r05630@慶之 杖。

 rm#r01805@昭徳 引出 dm#dm00650@光政門 外，
以示朝士曰：
「此賊欲廢我皇嗣，
立 rm#r02314@武承嗣 ，」
命撲之，
耳目皆血出，
然後杖殺之，
其黨乃散。


# p 

 rm#r01805@昭徳 因言於太后曰：
「天皇，
陛下之夫；
皇嗣，
陛下之子。

陛下身有天下，
當傳之子孫爲萬代業，
豈得以姪爲嗣乎！

自古未聞姪爲天子而爲姑立廟者也！

且陛下受天皇顧託，
若以天下與 rm#r02314@承嗣 ，
則天皇不血食矣。」

太后亦以爲然。

 rm#r01805@昭徳 ，
 rm#r01606@乾祐 之子也。

# p 

壬辰，
殺鸞臺侍郎‧同平章事 rm#r02265@樂思晦 、右衞將軍 rm#r01698@李安靜 。

 rm#r01698@安靜 ，
 rm#r01876@綱 之孫也。

太后將革命，
王公百官皆上表勸進，
 rm#r01698@安靜 獨正色拒之。

及下制獄，
 rm#r00115@來俊臣 詰其反状，
 rm#r01698@安靜 曰：
「以我 dyn#ch100@唐家 老臣，
須殺即殺！

若問謀反，
實無可對。」

 rm#r00115@俊臣 竟殺之。
# p 

太學生 rm#r05623@王循之 上表，
乞假還郷；
太后許之。

 rm#r02567@狄仁傑 曰：
「臣聞君人者唯殺生之柄不假人，
自餘皆歸之有司。

故左、右丞，
徒以下不句；
左、右相，
流以上乃判，
爲其漸貴故也。

彼學生求假，
丞、簿事耳，
若天子爲之發敕，
則天下之事幾敕可盡乎！

必欲不違其願，
請普爲立制而已。」

太后善之。
*** 天授三年
# year 0692
# p 

正月，
戊辰朔，
太后享 dm#dm06987@萬象神宮 。
# p 

臘月，
立故于闐王尉遲伏闍雄之子 rm@瑕 爲 rm@于闐王 。

# p 

春，
一月，
丁卯，
太后引見存撫使所舉人，
無問賢愚，
悉加擢用，
高者試鳳閣舍人、給事中，
次試員外郎、侍御史、補闕、拾遺、校書郎。

試官自此始。

時人爲之語曰：
「補闕連車載，
拾遺平斗量；
欋推侍御史，
盌脱校書郎。」

有舉人 rm#r02413@沈全交 續之曰：
「𪍒心存撫使，
眯目聖神皇。」

爲御史 rm#r05740@紀先知 所擒，
劾其誹謗朝政，
請杖之朝堂，
然後付法，
太后笑曰：
「但使卿輩不濫，
何恤人言！

宜釋其罪。」

 rm#r05740@先知 大慚。

太后雖濫以祿位收天下人心，
然不稱職者，
尋亦黜之，
或加刑誅。

挾刑賞之柄以駕御天下，
政由己出，
明察善斷，
故當時英賢亦競爲之用。

# p 

 dm#dm02309@寧陵 丞 dm#dm02793@廬江  rm#r03719@郭霸 以諂諛干太后，
拜監察御史。

中丞 rm#r04302@魏元忠 病，
 rm#r03719@霸 往問之，
因嘗其糞，
喜曰：
「大夫糞甘則可憂；
今苦，
無傷也。」

 rm#r04302@元忠 大惡之，
遇人輒告之。
# p 

戊辰，
以夏官尚書 rm#r02161@楊執柔 同平章事。

 rm#r02161@執柔 ，
 rm#r02189@恭仁 弟之孫也，
太后以外族用之。

# p 

初，
 rm#r02546@隋煬帝 作 dm#dm03880@東都 ，
無外城，
僅有短垣而已，
至是，
鳳閣侍郎 rm#r01805@李昭徳 始築之。
# p 

左臺中丞 rm#r00115@來俊臣 羅告同平章事 rm#r00093@任知古 、 rm#r02567@狄仁傑 、 rm#ry0016@裴行本 、司禮卿 rm#r05212@崔宣禮 、前文昌左丞 rm#r05708@盧獻 、御史中丞 rm#r04302@魏元忠 、 dm#dm05357@潞州 刺史 rm#r01666@李嗣眞 謀反。

先是，
 rm#r00115@來俊臣 奏請降敕，
一問即承反者得減死。

及 rm#r00093@知古 等下獄，
 rm#r00115@俊臣 以此誘之，
 rm#r02567@仁傑 對曰：
「 dyn#ch176@大周 革命，
萬物惟新，
 dyn#ch100@唐室 舊臣，
甘從誅戮。

反是實！」

 rm#r00115@俊臣 乃少寛之。

判官 rm#r05625@王徳壽 謂 rm#r02567@仁傑 曰：
「尚書定減死矣。

 rm#r05625@徳壽 業受驅策，
欲求少階級，
煩尚書引 rm#r02161@楊執柔 ，
可乎？」
 rm#r02567@仁傑 曰：
「皇天后土遣 rm#r02567@狄仁傑 爲如此事！

」
以頭觸柱，
血流被面；
 rm#r05625@徳壽 懼而謝之。
禮農崔裴
# p 

 rm#r00126@侯思止 鞫 rm#r04302@魏元忠 ，
 rm#r04302@元忠 辭氣不屈；
 rm#r00126@思止 怒，
命倒曳之。

 rm#r04302@元忠 曰：
「我薄命，
譬如墜驢，
足絓於鐙，
爲所曳耳。」

 rm#r00126@思止 愈怒，
更曳之，
 rm#r04302@元忠 曰：
「 rm#r00126@侯思止 ，
汝若須 rm#r04302@魏元忠 頭則截取，
何必使承反也！」


# p 

 rm#r02567@狄仁傑 既承反，
有司待報行刑，
不復嚴備。

 rm#r02567@仁傑 裂衾帛書冤状，
置綿衣中，
謂 rm#r05625@王徳壽 曰：
「天時方熱，
請授家人去其綿。」

 rm#r05625@徳壽 許之。

 rm#r02567@仁傑 子 rm#ry0019@光遠 得書，
持之告變，
得召見。

 rm#r02293@則天 覽之，
以問 rm#r00115@俊臣 ，
對曰：
「 rm#r02567@仁傑 等下獄，
臣未嘗褫其巾帶，
寢處甚安，
苟無事實，
安肯承反！」

太后使通事舍人 rm#r05130@周綝 往視之，
 rm#r00115@俊臣 暫假 rm#r02567@仁傑 等巾帶，
羅立於西，
使 rm#r05130@綝 視之；
 rm#r05130@綝 不敢視，
惟東顧唯諾而已。

 rm#r00115@俊臣 又詐爲 rm#r02567@仁傑 等謝死表，
使 rm#r05130@綝 奏之。
# p 

 rm#r02265@樂思晦 男未十歳，
沒入司農，
上變，
得召見，
太后問状，
對曰：
「臣父已死，
臣家已破，
但惜陛下法爲 rm#r00115@俊臣 等所弄，
陛下不信臣言，
乞擇朝臣之忠清、陛下素所信任者，
爲反状以付 rm#r00115@俊臣 ，
無不承反矣。」

太后意稍寤，
召見 rm#r02567@仁傑 等，
問曰：
「卿承反何也？」
對曰：
「不承，
則已死於拷掠矣。」

太后曰：
「何爲作謝死表？」
對曰：
「無之。

」
出表示之，
乃知其詐，
於是出此七族。

庚午，
貶 rm#r00093@知古  dm#dm04483@江夏 令，
 rm#r02567@仁傑  dm#dm02935@彭澤 令，
 rm#r05212@宣禮  dm#dm01839@夷陵 令，
 rm#r04302@元忠  dm#dm04940@涪陵 令，
 rm#r05708@獻  dm#dm07386@西郷 令；
流 rm#ry0016@行本 、 rm#r01666@嗣眞 于 dm#dm02527@嶺南 。


# p 

 rm#r00115@俊臣 與 rm#r02314@武承嗣 等固請誅之，
太后不許。

 rm#r00115@俊臣 乃獨稱 rm#ry0016@行本 罪尤重，
請誅之；
秋官郎中 rm#r01311@徐有功 駮之，
以爲「明主有更生之恩，
 rm#r00115@俊臣 不能將順，
虧損恩信。」

# p 

殿中侍御史 dm#dm07525@貴郷  rm#r06037@霍獻可 ，
 rm#r05212@宣禮 之甥也，
言於太后曰：
「陛下不殺 rm#r05212@崔宣禮 ，
臣請隕命於前。」

以頭觸殿階，
血流霑地，
以示爲人臣者不私其親。

太后皆不聽。

 rm#r06037@獻可 常以緑帛裹其傷，
微露之於幞頭下，
冀太后見之以爲忠。
# p 

甲戌，
補闕 rm#r03304@薛謙光 上疏，
以爲：
「選舉之法，
宜得實才，
取捨之間，
風化所繋。

今之選人，
咸稱覓舉，
奔競相尚，
諠訴無慚。

至於才應經邦，
惟令試策；
武能制敵，
止驗彎弧。

昔 rm@漢武帝 見 rm#r05103@司馬相如 賦，
恨不同時，
及置之朝廷，
終 dm#dm03296@文園 令，
知其不堪公卿之任故也。

 rm#r05109@呉起 將戰，
左右進劍，
 rm#r05109@起 曰：
『將者提鼓揮桴，
臨敵決疑，
一劍之任，
非將事也。』

然則虚文豈足以佐時，
善射豈足以克敵！

要在文吏察其行能，
武吏觀其勇略，
考居官之臧否，
行舉者賞罰而已。」

# p 

 rm#r00115@來俊臣 求金於左衞大將軍 rm#r02434@泉獻誠 ，
不得，
誣以謀反，
下獄，
乙亥，
縊殺之。

# p 

庚辰，
司刑卿、檢校 dm#dm08320@陝州 刺史 rm#r01987@李游道 爲冬官尚書、同平章事。

# p 

二月，
己亥，
吐蕃黨項部落萬餘人内附，
分置十州。
# p 

戊午，
以秋官尚書 rm#r05838@袁智弘 同平章事。

** 如意
*** 如意元年
# year 0692
# p 

夏，
四月，
丙申，
赦天下，
改元 y@如意 。

# p 

五月，
丙寅，
禁天下屠殺及捕魚蝦。

 dm#dm04475@江  dm#dm04981@淮 旱，
饑，
民不得采魚蝦，
餓死者甚衆。

# p 

右拾遺 rm@張徳 ，
生男三日，
私殺羊會同僚，
補闕 rm#r05452@杜肅 懷一餤，
上表告之。

明日，
太后對仗，
謂 rm@徳 曰：
「聞卿生男，
甚喜。」

 rm@徳 拜謝。

太后曰：
「何從得肉？」
 rm@徳 叩頭服罪。

 rm@太后 曰：
「朕禁屠宰，
吉凶不預。

然卿自今召客，
亦須擇人。」

出 rm#r05452@肅 表示之。

 rm#r05452@肅 大慚，
舉朝欲唾其面。

# p 

吐蕃酋長 rm@曷蘇 帥部落請内附，
以右玉鈴衞將軍 rm#r06186@張玄遇 爲安撫使，
將精卒二萬迎之。

六月，
軍至 dm#dm01651@大渡水 西，
 rm@曷蘇 事洩，
爲國人所擒。

別部酋長 rm@昝捶 帥羌蠻八千餘人内附，
 rm#r06186@玄遇 以其部落置 dm#dm06952@莱川州 而還。

# p 

辛亥，
 dm#dm06979@萬年 主簿 rm#r01306@徐堅 上疏，
以爲：
「書有五聽之道，
令著三覆之奏。

竊見比有敕推按反者，
令使者得實，
即行斬決。

人命至重，
死不再生，
萬一懷枉，
呑聲赤族，
豈不痛哉！

此不足肅姦逆而明典刑，
適所以長威福而生疑懼。

臣望絶此處分，
依法覆奏。

又，
法官之任，
宜加簡擇，
有用法寛平，
爲百姓所稱者，
願親而任之；
有處事深酷，
不允人望者，
願疏而退之。」

 rm#r01306@堅 ，
 rm#r01297@齊耼 之子也。

# p 

夏官侍郎 rm#r01805@李昭徳 密言於太后曰：
「 rm#r02314@魏王承嗣 權太重。」

太后曰：
「吾姪也，
故委以腹心。」

 rm#r01805@昭徳 曰：
「姪之於姑，
其親何如子之於父？
子猶有簒弑其父者，
況姪乎！

今 rm#r02314@承嗣 既陛下之姪，
爲親王，
又爲宰相，
權侔人主，
臣恐陛下不得久安天位也！」

太后矍然曰：
「朕未之思。」

秋，
七月，
戊寅，
以文昌左相、同鳳閣鸞臺三品 rm#r02314@武承嗣 爲特進，
納言 rm#r06225@武攸寧 爲冬官尚書，
夏官尚書、同平章事 rm#r02161@楊執柔 爲地官尚書，
竝罷政事；
以秋官侍郎 dm#dm03402@新鄭  rm#r00898@崔元綜 爲鸞臺侍郎，
夏官侍郎 rm#r01805@李昭徳 爲鳳閣侍郎，
檢校天官侍郎 rm#r00620@姚璹 爲文昌左丞，
檢校地官侍郎 rm#r01627@李元素 爲文昌右丞，
與司賓卿 rm#r00976@崔神基 竝同平章事。

 rm#r00620@璹 ，
 rm#r00630@思廉 之孫；
 rm#r01627@元素 ，
 rm#r01789@敬玄 之弟也。

辛巳，
以營繕大匠 rm#r02774@王璿 爲夏官尚書、同平章事。

 rm#r02314@承嗣 亦毀 rm#r01805@昭徳 於太后，
太后曰：
「吾任 rm#r01805@昭徳 ，
始得安眠，
此代吾勞，
汝勿言也。」

# p 

是時，
酷吏恣横，
百官畏之側足，
 rm#r01805@昭徳 獨廷奏其姦。

太后好祥瑞，
有獻白石赤文者，
執政詰其異，
對曰：
「以其赤心。」

 rm#r01805@昭徳 怒曰：
「此石赤心，
他石盡反邪？」
左右皆笑。

 dm#dm07274@襄州 人 rm#r05750@胡慶 以丹漆書龜腹曰：
「天子萬萬年。」

詣闕獻之。

 rm#r01805@昭徳 以刀刮盡，
奏請付法。

太后曰：
「此心亦無惡。」

命釋之。
# p 

太后習貓，
使與鸚鵡共處。

出示百官，
傳觀未遍，
貓飢，
搏鸚鵡食之，
太后甚慚。


# p 

太后自 y@垂拱 以來，
任用酷吏，
先誅 dyn#ch100@唐 宗室貴戚數百人，
次及大臣數百家，
其刺史、郎將以下，
不可勝數。

毎除一官，
戸婢竊相謂曰：
「鬼朴又來矣。」

不旬月，
輒遭掩捕、族誅。

監察御史 dm#dm03715@朝邑  rm#r00566@嚴善思 ，
公直敢言。

時告密者不可勝數，
太后亦厭其煩，
命 rm#r00566@善思 按問，
引虚伏罪者八百五十餘人。

羅織之黨爲之不振，
乃相與搆陷 rm#r00566@善思 ，
坐流 dm#dm08873@驩州 。

太后知其枉，
尋復召爲渾儀監丞。

 rm#r00566@善思 名 rm@譔 ，
以字行。

# p 

右補闕 dm#dm03402@新鄭  rm#r01572@朱敬則 以太后本任威刑以禁異議，
今既革命，
衆心已定，
宜省刑尚寛，
乃上疏，
以爲：
「 rm#r05400@李斯 相 dyn#ch128@秦 ，
用刻薄變詐以屠諸侯，
不知易之以寛和，
卒至土崩，
此不知變之禍也。

 rm#rt0511@漢高祖 定天下，
 rm#r06028@陸賈 、 rm#rx0049@叔孫通 説之以禮義，
傳世十二，
此知變之善也。

自 y@文明 草昧，
天地屯蒙，
三叔流言，
四凶構難，
不設鉤距，
無以應天順人，
不切刑名，
不可摧姦息暴。

故置神器，
開告端，
曲直之影必呈，
包藏之心盡露，
神道助直，
無罪不除，
蒼生晏然，
紫宸易主。

然而急趨無善迹，
促柱少和聲，
向時之妙策，
乃當今之芻狗也。

伏願覽 dyn#ch128@秦 、 dyn#ch129@漢 之得失，
考時事之合宜，
審糟粕之可遺，
覺蘧廬之須毀，
去萋菲之牙角，
頓姦險之鋒芒，
窒羅織之源，
掃朋黨之迹，
使天下蒼生坦然大悦，
豈不樂哉！」

太后善之，
賜帛三百段。

# p 

侍御史 rm#r00469@周矩 上疏曰：
「推劾之吏皆相矜以虐，
泥耳籠頭，
枷研楔𩌊，
摺膺籤爪，
懸髮薫耳，
號曰『獄持』。

或累日節食，
連宵緩問，
晝夜搖撼，
使不得眠，
號曰『宿囚』。

此等既非木石，
且救目前，
苟求賖死。

臣竊聽輿議，
皆稱天下太平，
何苦須反！

豈被告者盡是英雄，
欲求帝王邪？
但不勝楚毒自誣耳。

願陛下察之。

今滿朝側息不安，
皆以爲陛下朝與之密，
夕與之讎，
不可保也。

 dyn#ch103@周 用仁而昌，
 dyn#ch128@秦 用刑而亡。

願陛下緩刑用仁，
天下幸甚！」

太后頗采其言，
制獄稍衰。

** 長壽
*** 長壽元年
# year 0692
# p 

太后春秋雖高，
善自塗澤，
雖左右不覺其衰。

丙戌，
敕以齒落更生，
九月，
庚子，
御 dm#dm00765@則天門 ，
赦天下，
改元。

更以九月爲社。

# p 

制於 dm#dm00059@幷州 置 dm#dm00895@北都 。
# p 

癸丑，
同平章事 rm#r01987@李遊道 、 rm#r02774@王璿 、 rm#r05838@袁智弘 、 rm#r00976@崔神基 、 rm#r01627@李元素 、春官侍郎 rm#r05148@孔思元 、 dm#dm05982@益州 長史 rm#r05018@任令輝 ，
皆爲 rm#r02627@王弘義 所陷，
流 dm#dm02527@嶺南 。

# p 

左羽林中郎將 rm#r00117@來子珣 坐事流 dm#dm03057@愛州 ，
尋卒。

# p 

初，
 dm#dm03393@新豐  rm#r02615@王孝傑 從 rm#r00226@劉審禮 撃吐蕃爲副總管，
與 rm#r00226@審禮 皆沒於吐蕃。

贊普見 rm#r02615@孝傑 泣曰：
「貌類吾父。」

厚禮之，
後竟得歸，
累遷右鷹揚衞將軍。

 rm#r02615@孝傑 久在吐蕃，
知其虚實。

會 dm#dm07317@西州 都督 rm#r00488@唐休璟 請復取龜茲、于闐、疏勒、碎葉四鎭，
敕以 rm#r02615@孝傑 爲 dm#dm04241@武威 軍總管，
與武衞大將軍 rm#r05991@阿史那忠節 將兵撃吐蕃。

冬，
十月，
丙戌，
大破吐蕃，
復取四鎭。

置 dm#dm02061@安西 都護府於龜茲，
發兵戍之。
*** 二年
# year 0693
# p 

正月，
壬辰朔，
太后享 dm#dm06987@萬象神宮 ，
以 rm#r02314@魏王承嗣 爲亞獻，
 rm#r02294@梁王三思 爲終獻。

太后自制神宮樂，
用舞者九百人。
# p 

戸婢 rm#r06838@團兒 爲太后所寵信，
有憾於皇嗣，
乃譖皇嗣𡚱 rm@劉氏 、 rm#?@徳𡚱竇氏 爲厭呪。

癸巳，
𡚱與 rm#?@徳𡚱 朝太后於 dm#dm01424@嘉豫殿 ，
既退，
同時殺之，
瘞於宮中，
莫知所在。

 rm#?@徳𡚱 ，
 rm#r03033@抗 之曾孫也。

皇嗣畏忤旨，
不敢言，
居太后前，
容止自如。

 rm#r06838@團兒 復欲害皇嗣，
有言其情於太后者，
太后乃殺 rm#r06838@團兒 。

# p 

是時，
告密者皆誘人奴婢告其主，
以求功賞。

 rm#?@徳𡚱 父 rm#r03021@孝諶 爲 dm#dm05367@潤州 刺史，
有奴妄爲妖異以恐 rm#?@徳𡚱 母 rm#xjts00022@龐氏 ，
 rm#xjts00022@龐氏 懼，
奴請夜祠祷解，
因發其事。

下監察御史 dm#dm09269@龍門  rm#r03280@薛季昶 按之，
 rm#r03280@季昶 誣奏，
以爲與 rm#?@徳𡚱 同祝詛，
先涕泣不自勝，
乃言曰：
「 rm#xjts00022@龐氏 所爲，
臣子所不忍道。」

太后擢 rm#r03280@季昶 爲給事中。

 rm#xjts00022@龐氏 當斬，
其子 rm#r03024@希瑊 詣侍御史 rm#r01311@徐有功 訟冤，
 rm#r01311@有功 牒所司停刑，
上奏論之，
以爲無罪；
 rm#r03280@季昶 奏 rm#r01311@有功 阿黨惡逆，
請付法，
法司處 rm#r01311@有功 罪當絞。

令史以白 rm#r01311@有功 ，
 rm#r01311@有功 嘆曰：
「豈我獨死，
諸人永不死邪！」

既食，
掩扇而寢。

人以爲 rm#r01311@有功 苟自強，
必内憂懼，
密伺之，
方熟寢。

太后召 rm#r01311@有功 ，
迎謂曰：
「卿比按獄，
失出何多？」
對曰：
「失出，
人臣之小過；
好生，
聖人之大徳。」

太后默然。

由是 rm#xjts00022@龐氏 得減死，
與其三子皆流 dm#dm02527@嶺南 ，
 rm#r03021@孝諶 貶 dm#dm06504@羅州 司馬，
 rm#r01311@有功 亦除名。

# p 

戊申，
 rm#r00620@姚璹 奏請令宰相撰時政記，
月送史館。

從之。

時政記自此始。
# p 

臘月，
丁卯，
降皇孫 rm#r02384@成器 爲 rm#r02384@壽春王 ，
 rm#r01346@恆王成義 爲 rm#r01346@衡陽王 ，
 rm#r02004@楚王隆基 爲 rm#r02004@臨淄王 ，
 rm#r03770@衞王隆範 爲 rm#r03770@巴陵王 ，
 rm#r03598@趙王隆業 爲 rm#r03598@彭城王 ，
皆 rm#r01797@睿宗 之子也。
# p 

春，
一月，
庚子，
以夏官侍郎 rm#r00657@婁師徳 同平章事。

 rm#r00657@師徳 寛厚清愼，
犯而不校。

與 rm#r01805@李昭徳 倶入朝，
 rm#r00657@師徳 體肥行緩，
 rm#r01805@昭徳 屡待之不至，
怒罵曰：
「田舍夫！」

 rm#r00657@師徳 徐笑曰：
「 rm#r00657@師徳 不爲田舍夫，
誰當爲之！」

其弟除 dm#dm00485@代州 刺史，
將行，
 rm#r00657@師徳 謂曰：
「吾備位宰相，
汝復爲州牧，
榮寵過盛，
人所疾也，
將何以自免？」
弟長跪曰：
「自今雖有人唾某面，
某拭之而已，
庶不爲兄憂。」

 rm#r00657@師徳 愀然曰：
「此所以爲吾憂也！

人唾汝面，
怒汝也；
汝拭之，
乃逆其意，
所以重其怒。

夫唾，
不拭自乾，
當笑而受之。

」
# p 

甲寅，
前尚方監 rm#r06253@裴匪躬 、内常侍 rm#r05762@范雲仙 坐私謁皇嗣腰斬於市。

自是公卿以下皆不得見。

又有告皇嗣潛有異謀者，
太后命 rm#r00115@來俊臣 鞫其左右，
左右不勝楚毒，
皆欲自誣。

太常工人 dm#dm00427@京兆  rm#r00796@安金藏 大呼謂 rm#r00115@俊臣 曰：
「公既不信 rm#r00796@金藏 之言，
請剖心以明皇嗣不反。」

即引佩刀自剖其胸，
五藏皆出，
流血被地。

太后聞之，
令轝入宮中，
使醫内五藏，
以桑皮線縫之，
傅以藥，
經宿始蘇。

太后親臨視之，
歎曰：
「吾有子不能自明，
使汝至此。」

即命 rm#r00115@俊臣 停推。

 rm#r01797@睿宗 由是得免。

# p 

罷舉人習老子，
更習太后所造臣軌。

# p 

二月，
丙子，
 rm@新羅王政明 卒，
遣使立其子 rm@理洪 爲王。


# p 

乙亥，
禁人間錦。

侍御史 rm#r00126@侯思止 私畜錦，
 rm#r01805@李昭徳 按之，
杖殺於朝堂。

# p 

或告 dm#dm02527@嶺南 流人謀反，
太后遣司刑評事 rm#r03177@萬國俊 攝監察御史就按之。

 rm#r03177@國俊 至 dm#dm02733@廣州 ，
悉召流人，
矯制賜自盡。

流人號呼不服，
 rm#r03177@國俊 驅就水曲，
盡斬之，
一朝殺三百餘人。

然後詐爲反状，
還奏，
因言諸道流人，
亦必有怨望謀反者，
不可不早誅。

太后喜，
擢 rm#r03177@國俊 爲朝散大夫、行侍御史。

更遣右翊衞兵曹參軍 rm#r05056@劉光業 、司刑評事 rm#r05625@王徳壽 、苑南面監丞 rm#r06132@鮑思恭 、尚輦直長 rm#r05612@王大貞 、右武威衞兵曹參軍 rm#xjts26741@屈貞筠 皆攝監察御史，
詣諸道按流人。

 rm#r05056@光業 等以 rm#r03177@國俊 多殺蒙賞，
爭效之，
 rm#r05056@光業 殺七百人，
 rm#r05625@徳壽 殺五百人，
自餘少者不減百人，
其遠年雜犯流人亦與之倶斃。

太后頗知其濫，
制：
「六道流人未死者幷家屬皆聽還郷里。」

 rm#r03177@國俊 等亦相繼死，
或得罪流竄。

# p 

 rm#r00115@來俊臣 誣冬官尚書 rm#r03332@蘇幹 ，
云在 dm#dm08950@魏州 與 rm#r02804@琅邪王沖 通謀，
夏，
四月，
乙未，
殺之。
# p 

五月，
癸丑，
 dm#dm04071@棣州 河溢。

流二千餘家
# p 

秋，
九月，
丁亥朔，
日有食之。
# p 

 rm#r02314@魏王承嗣 等五千人表請加尊號曰 rm#r02293@金輪聖神皇帝 。

乙未，
太后御 dm#dm06987@萬象神宮 ，
受尊號，
赦天下。

作金輪等七寶，
毎朝會，
陳之殿庭。

# p 

庚子，
追尊 rm#xjts06533@昭安皇帝 曰 rm#xjts06533@渾元昭安皇帝 ，
 rm#xjts06555@文穆皇帝 曰 rm#xjts06555@立極文穆皇帝 ，
 rm#r02300@孝明高皇帝 曰 rm#r02300@無上孝明高皇帝 ；
皇后從帝號。


# p 

辛丑，
以文昌左丞、同平章事 rm#r00620@姚璹 爲司賓卿，
罷政事；
以司賓卿 dm#dm06979@萬年  rm#r03546@豆盧欽望 爲内史，
文昌左丞 rm#r04023@韋巨源 同平章事，
秋官侍郎 dm#dm01275@呉 人 rm#r03943@陸元方 爲鸞臺侍郎、同平章事。

 rm#r04023@巨源 ，
 rm#r06839@孝寛 之玄孫也。

*** 三年
# year 0694
# p 

正月，
丙戌，
太后享 dm#dm06987@萬象神宮 。
# p 

突厥可汗 rm#r06002@骨篤祿 卒，
其子幼，
弟 rm@默啜 自立爲可汗。

臘月，
甲戌，
 rm@默啜 寇 dm#dm08619@靈州 。
# p 

室韋反，
遣右鷹揚衞大將軍 rm#r01671@李多祚 撃破之。
# p 

春，
一月，
以 rm#r00657@婁師徳 爲 dm#dm04690@河源 等軍檢校營田大使。


# p 

二月，
 dm#dm04242@武威道 總管 rm#r02615@王孝傑 破吐蕃 rm@㪍論贊刃 、突厥可汗 rm#xjts24859@俀子 等於 dm#dm00730@冷泉 及 dm#dm01610@大嶺 ，
各三萬餘人，
 dm#dm06162@碎葉 鎭守使 rm#r06065@韓思忠 破泥熟俟斤等萬餘人。

刃興
# p 

庚午，
以僧 rm#r03283@懷義 爲 dm#dm00483@代北道 行軍大總管，
以討 dm#dm09191@默啜 。
# p 

三月甲申，
以鳳閣舍人 rm#r03329@蘇味道 爲鳳閣侍郎、同平章事，
 rm#r01805@李昭徳 檢校内史。

更以僧 rm#r03283@懷義 爲 dm#dm03681@朔方道 行軍大總管，
以 rm#r01805@李昭徳 爲長史，
 rm#r03329@蘇味道 爲司馬，
帥 rm#r00613@契苾明 、 rm#ry0020@曹仁師 、 rm@沙吒忠義 等十八將軍以討 rm@默啜 ，
未行，
虜退而止。

 rm#r01805@昭徳 嘗與 rm#r03283@懷義 議事，
失其旨，
 rm#r03283@懷義 撻之，
 rm#r01805@昭徳 惶懼請罪。
# p 

夏，
四月，
壬戌，
以夏官尚書、 dm#dm04242@武威道 大總管 rm#r02615@王孝傑 同鳳閣鸞臺三品。
** 延載
*** 延載元年
# year 0694
# p 

五月，
 rm#r02314@魏王承嗣 等二萬六千餘人上尊號曰 rm#r02293@越古金輪聖神皇帝 。

甲午，
御 dm#dm00765@則天門 樓受尊號，
赦天下，
改元。
# p 

 y@天授中 ，
遣監察御史 dm#dm01525@壽春  rm#r03436@裴懷古 安集西南蠻。

六月，
癸丑，
 dm#dm04420@永昌 蠻酋 rm@薫期 帥部落二十餘萬戸内附。

# p 

 dm#dm04653@河内 有老尼居 dm#dm06235@神都  dm#dm09096@麟趾寺 ，
與 dm#dm02514@嵩山 人 rm#r06039@韋什方 等以妖妄惑衆。

尼自號 rm@淨光如來 ，
云能知未然；
 rm#r05537@什方 自云 dyn#ch136@呉  y@赤烏 年生。

又有老胡亦自言五百歳，
云見 rm#r03283@薛師 已二百年矣，
容貌愈少。

太后甚信重之，
賜 rm#r05537@什方 姓 rm#no@武氏 。

秋，
七月，
癸未，
以 rm#r05537@什方 爲正諫大夫、同平章事，
制云：
「邁 dyn#*ch上古@軒代 之 rm#rt0001@廣成 ，
逾 dyn#ch130@漢朝 之 rm@河上 。」

八月，
 rm#r05537@什方 乞還山，
制罷遣之。元
# p 

戊辰，
以 rm#r02615@王孝傑 爲 dm#dm05475@瀚海道 行軍總管，
仍受 dm#dm03681@朔方道 行軍大總管 rm#r03283@薛懷義 節度。
# p 

己巳，
以司賓少卿 rm#r00620@姚璹 爲納言；
左肅政中丞 dm#dm01115@原武  rm#r02155@楊再思 爲鸞臺侍郎，
 dm#dm04778@洛州 司馬 rm#r02049@杜景儉 爲鳳閣侍郎，
竝同平章事。
# p 

 rm#r03546@豆盧欽望 請京官九品已上輸兩月俸以贍軍，
轉帖百官，
令拜表。

百官但赴拜，
不知何事。

拾遺 rm#r02659@王求禮 謂 rm#r03546@欽望 曰：
「明公祿厚，
輸之無傷；
卑官貧迫，
奈何不使其知而欺奪之乎？」
 rm#r03546@欽望 正色拒之。

既上表，
 rm#r02659@求禮 進言曰：
「陛下富有四海，
軍國有儲，
何藉貧官九品之俸而欺奪之！」

 rm#r00620@姚璹 曰：
「 rm#r02659@求禮 不識大體。」

 rm#r02659@求禮 曰：
「如 rm#r00620@姚璹 ，
爲識大體者邪！」

事遂寢。


# p 

戊寅，
鸞臺侍郎、同平章事 rm#r00898@崔元綜 坐事流 dm#dm03227@振州 。
# p 

 rm#r02294@武三思 帥四夷酋長請鑄銅鐵爲天樞，
立於 dm#dm06352@端門 之外，
銘紀功徳，
黜 dyn#ch100@唐 頌 dyn#ch103@周 ；
以 rm#r00620@姚璹 爲督作使。

諸胡聚錢百萬億，
買銅鐵不能足，
賦民間農器以足之。
# p 

九月，
壬午朔，
日有食之。
# p 

殿中丞 rm#r00115@來俊臣 坐贓貶 dm#dm01227@同州 參軍。

 rm#r02627@王弘義 流 dm#dm05765@瓊州 ，
詐稱敕追還，
至 dm#dm05271@漢 北，
侍御史 rm#ry0015@胡元禮 遇之，
按驗，
得其姦状，
杖殺之。
# p 

内史 rm#r01805@李昭徳 恃太后委遇，
頗專權使氣，
人多疾之，
前 rm@魯王 府功曹參軍 rm#r05008@丘愔 上疏攻之，
其略曰：
「陛下 y@天授 以前，
萬機獨斷。

自 y@長壽 以來，
委任 rm#r01805@昭徳 ，
參奉機密，
獻可替否；
事有便利，
不預諮謀，
要待畫日將行，
方乃別生駁異。

揚露專，
顯示於人，
歸美引愆，
義不如此。」

又曰：
「臣觀其膽，
乃大於身，
鼻息所衝，
上拂雲漢。」

又曰：
「蟻穴壞隄，
針芒寫氣，
權重一去，
收之極難。」

長上果毅 rm#r05953@鄧注 ，
又著石論數千言，
述 rm#r01805@昭徳 專權之状。

鳳閣舍人 rm@逄弘敏 取奏之，
太后由是惡 rm#r01805@昭徳 。

壬寅，
貶 rm#r01805@昭徳 爲 dm#dm01056@南賓 尉，
尋又免死流竄。

# p 

太后出黎花一枝以示宰相，
宰相皆以爲瑞。

 rm#r02049@杜景儉 獨曰：
「今草木黄落，
而此更發榮，
陰陽不時，
咎在臣等。」

因拜謝。

太后曰：
「卿眞宰相也！」


# p 

冬，
十月，
壬申，
以文昌右丞 rm#r01627@李元素 爲鳳閣侍郎，
左肅政中丞 rm#r00450@周允元 檢校鳳閣侍郎，
竝同平章事。

 rm#r00450@允元 ，
 dm#dm07502@豫州 人也。
# p 

 dm#dm02527@嶺南 獠反，
以 dm#dm02240@容州 都督 rm#r06186@張玄遇 爲 dm#dm03996@桂 、 dm#dm04410@永 等州經略大使以討之。

** 證聖
*** 證聖元年
# year 0694
# p 

正月，
辛巳朔，
太后加號 rm#r02293@慈氏越古金輪聖神皇帝 ，
赦天下，
改元 y@證聖 。
# p 

 rm#r00450@周允元 與司刑少卿 rm#r05696@皇甫文備 奏内史 rm#r03546@豆盧欽望 、同平章事 rm#r04023@韋巨源 、 rm#r02049@杜景儉 、 rm#r03329@蘇味道 、 rm#r03943@陸元方 附會 rm#r01805@李昭徳 ，
不能匡正，
 rm#r03546@欽望 貶 dm#dm07623@趙州 ，
 rm#r04023@巨源 貶 dm#dm09094@麟州 ，
 rm#r02049@景儉 貶 dm#dm05205@溱州 ，
 rm#r03329@味道 貶 dm#dm08483@集州 ，
 rm#r03943@元方 貶 dm#dm06439@綏州 刺史。

# p 

初，
明堂既成，
太后命僧 rm#r03283@懷義 作夾紵大像，
其小指中猶容數十人，
於明堂北構天堂以貯之。

堂始構，
爲風所摧，
更構之，
日役萬人，
采木江嶺，
數年之間，
所費以萬億計，
府藏爲之耗竭。

 rm#r03283@懷義 用財如糞土，
太后一聽之，
無所問。

毎作無遮會，
用錢萬緡；
士女雲集，
又散錢十車，
使之爭拾，
相蹈踐有死者。

所在公私田宅，
多爲僧有。

 rm#r03283@懷義 頗厭入宮，
多居 dm#dm05931@白馬寺 ，
所度力士爲僧者滿千人。

侍御史 rm#r00469@周矩 疑有姦謀，
固請按之。

太后曰：
「卿姑退，
朕即令往。」

 rm#r00469@矩 至臺，
懷義亦至，
乘馬就階而下，
坦腹於牀。

 rm#r00469@矩 召吏將按之，
遽躍馬而去。

 rm#r00469@矩 具奏其状，
太后曰：
「此道人病風，
不足詰，
所度僧，
惟卿所處。」

悉流遠州。

遷 rm#r00469@矩 天官員外郎。
# p 

乙未，
作無遮會於明堂，
鑿地爲阬，
深五丈，
結綵爲宮殿，
佛像皆於阬中引出之，
云自地涌出。

又殺牛取血，
畫大像首，
高二百尺，
云 rm#r03283@懷義 刺膝血爲之。

丙申，
張像於 dm#dm01750@天津橋 南，
設齋。

時御醫 rm#r05557@沈南璆 亦得幸於太后，
 rm#r03283@懷義 心慍，
是夕，
密燒天堂，
延及明堂，
火照城中如晝，
比明皆盡，
暴風裂血像爲數百段。

太后恥而諱之，
但云内作工徒誤燒麻主，
遂渉明堂。

時方酺宴，
左拾遺 rm#r00261@劉承慶 請輟朝停酺以答天譴，
太后將從之。

 rm#r00620@姚璹 曰：
「昔 dm#dm03127@成周  dm#dm02223@宣榭 ，
卜代愈隆；
 rm#rt0517@漢武  dm#dm02864@建章 ，
盛徳彌永。

今明堂布政之所，
非宗廟也，
不應自貶損。」

太后乃御端門，
觀酺如平日。

命更造明堂、天堂，
仍以 rm#r03283@懷義 充使。

又鑄銅爲九州鼎及十二神，
皆高一丈，
各置其方。明朝
# p 

先是，
 dm#dm04653@河内 老尼晝食一麻一米，
夜則烹宰宴樂，
畜弟子百餘人，
淫穢靡所不爲。

 rm#r05537@武什方 自言能合長年藥，
太后遣乘驛於 dm#dm02527@嶺南 采藥。

及明堂火，
尼入唁太后，
太后怒叱之，
曰：
「汝常言能前知，
何以不言明堂火？」
因斥還 dm#dm04653@河内 ，
弟子及老胡等皆逃散。

又有發其姦者，
太后乃復召尼還 dm#dm09096@麟趾寺 ，
弟子畢集，
敕給使掩捕，
盡獲之，
皆沒爲官婢。

 rm#r05537@什方 還，
至 dm#dm00606@偃師 ，
聞事露，
自絞死。
# p 

庚子，
以明堂火告廟，
下制求直言。

 rm#r00261@劉承慶 上疏，
以爲：
「火發既從麻主，
後及 y@總章 所營佛舍，
恐勞無益，
請罷之。

又，
明堂所以統和天人，
一旦焚毀，
臣下何心猶爲酺宴！

憂喜相爭，
傷於情性。

又，
陛下垂制博訪，
許陳至理，
而左史 rm#r01274@張鼎 以爲今既火流王屋，
彌顯 dyn#ch176@大周 之祥，
通事舍人 rm@逄敏 奏稱，
 rm@彌勒 成道時有天魔燒宮，
七寶臺須臾散壞，
斯實諂妄之邪言，
非君臣之正論。

伏願陛下乾乾翼翼，
無戾天人之心而興不急之役，
則兆人蒙頼，
福祿無窮。」

# p 

 dm#dm05675@獲嘉 主簿 dm#dm02926@彭城  rm#r00216@劉知幾 表陳四事：
其一，
以爲：
「皇業權輿，
天地開闢，
嗣君即位，
黎元更始，
時則藉非常之慶以申再造之恩。

今六合清晏而赦令不息，
近則一年再降，
遠則毎歳無遺，
至於違法悖禮之徒，
無頼不仁之輩，
編戸則寇攘爲業，
當官則贓賄是求。

而元日之朝，
指期天澤，
重陽之節，
佇降皇恩，
如其忖度，
咸果釋免。

或有名垂結正，
罪將斷決，
竊行貨賄，
方便規求，
故致稽延，
畢霑寛宥。

用使俗多頑悖，
時罕廉隅，
爲善者不預恩光，
作惡者獨承徼幸。

古語曰：
『小人之幸，
君子之不幸。』

斯之謂也。

望陛下而今而後，
頗節於赦，
使黎氓知禁，
姦宄肅清。」

其二，
以爲：
「海内具僚九品以上，
毎歳逢赦，
必賜階勳，
至於朝野宴集，
公私聚會，
緋服衆於青衣，
象板多於木笏；
皆榮非徳舉，
位罕才升，
不知何者爲妍蚩，
何者爲美惡。

臣望自今以後，
稍息私恩，
使有善者逾效忠勤，
無才者咸知勉勵。」

其三，
以爲：
「陛下臨朝踐極，
取士太廣，
六品以下職事清官，
遂乃方之土芥，
比之沙礫，
若遂不加沙汰，
臣恐有穢皇風。」

其四，
以爲：
「今之牧伯遷代太速，
倏來忽往，
蓬轉萍流，
既懷苟且之謀，
何暇循良之政！

望自今刺史非三歳以上不可遷官，
仍明察功過，
尤甄賞罰。」

疏奏，
太后頗嘉之。

是時官爵易得而法網嚴峻，
故人競爲趨進而多陷刑戮，
 rm#r00216@知幾 乃著思愼賦以刺時見志焉。
# p 

丙午，
以 rm#r02615@王孝傑 爲 dm#dm03681@朔方道 行軍總管，
撃突厥。


# p 

春，
二月，
己酉朔，
日有食之。
# p 

僧 rm#r03283@懷義 益驕恣，
太后惡之。

既焚明堂，
心不自安，
言多不順；
太后密選宮人有力者百餘人以防之。

壬子，
執之於 dm#dm05755@瑤光殿 前樹下，
使 rm@建昌王  rm#r06225@武攸寧 帥壯士毆殺之，
送尸 dm#dm05931@白馬寺 ，
焚之以造塔。
# p 

甲子，
太后去「慈氏越古」
之號。

# p 

三月，
丙辰，
鳳閣侍郎、同平章事 rm#r00450@周允元 薨。
# p 

夏，
四月，
天樞成，
高一百五尺，
徑十二尺，
八面，
各徑五尺。

下爲鐵山，
周百七十尺，
以銅爲蟠龍麒麟縈繞之；
上爲騰雲承露盤，
徑三丈，
四龍人立捧火珠，
高一丈。

工人 rm#r05555@毛婆羅 造模，
 rm#r02294@武三思 爲文，
刻百官及四夷酋長名，
太后自書其榜曰「 dyn#ch176@大周 萬國頌徳天樞」。
# p 

秋，
七月，
辛酉，
吐蕃寇 dm#dm06688@臨洮 ，
以 rm#r02615@王孝傑 爲 dm#dm06609@肅邊道 行軍大總管以討之。
** 天册萬歳
*** 天册萬歳元年
# year 0695
# p 

九月，
甲寅，
太后合祭天地於南郊，
加號 rm#r02293@天册金輪大聖皇帝 ，
赦天下，
改元。

# p 

冬，
十月，
突厥 rm@默啜 遣使請降，
太后喜，
册授左衞大將軍 rm@歸國公 。
** 萬歳登封
*** 萬歳登封元年
# year 0696
# p 

臘月，
甲戌，
太后發 dm#dm06235@神都 ；
甲申，
封神嶽；
赦天下，
改元 y@萬歳登封 ，
天下百姓無出今年租税；
大酺九日。

丁亥，
禪于 dm#dm02371@少室 ；
己丑，
御朝覲壇受賀；
癸巳，
還宮；
甲午，
謁太廟。
# p 

右千牛衞將軍 rm#r02318@安平王  rm#r02318@武攸緒 ，
少有志行，
恬澹寡欲，
扈從封中嶽還，
即求棄官，
隱於 dm#dm02514@嵩山 之陽。

太后疑其詐，
許之，
以觀其所爲。

 rm#r02318@攸緒 遂優游巖壑，
冬居茅椒，
夏居石室，
一如山林之士。

太后所賜及王公所遺野服器玩，
 rm#r02318@攸緒 一皆置之不用，
塵埃凝積。

買田使奴耕種，
與民無異。

*** 二年
# year 0696
# p 

春，
一月，
甲寅，
以 rm#r00657@婁師徳 爲 dm#dm06609@肅邊道 行軍副總管，
撃吐蕃。

己巳，
以 rm#r00657@師徳 爲左肅政大夫，
知政事如故。

# p 

改 dm#dm08170@長安  dm#dm02460@崇尊廟 爲太廟。

# p 

二月，
辛巳，
尊 rm#no@神嶽天中王 爲 rm#no@神嶽天中黄帝 ，
 rm#no@靈𡚱 爲 rm#no@天中黄后 ；
 rm#*rt0009@啓 爲 rm@齊聖皇帝 ；
封 rm@啓母神 爲 rm@玉京太后 。

# p 

三月，
壬寅，
 rm#r02615@王孝傑 、 rm#r00657@婁師徳 與吐蕃將 rm@論欽陵贊婆 戰於 dm#dm06399@素羅汗山 ，
 dyn#ch100@唐 兵大敗；
 rm#r02615@孝傑 坐免爲庶人，
 rm#r00657@師徳 貶 dm#dm01114@原州 員外司馬。

 rm#r00657@師徳 因署移牒，
驚曰：
「官爵盡無邪！」

既而曰：
「亦善，
亦善。」

不復介意。

** 萬歳通天
*** 萬歳通天元年
# year 0696
# p 

丁巳，
新明堂成，
高二百九十四尺，
方三百尺，
規模率小於舊。

上施金塗鐵鳳，
高二丈，
後爲大風所損；
更爲銅火珠，
羣龍捧之，
號曰 dm#dm07688@通天宮 。

赦天下，
改元 y@萬歳通天 。
# p 

 dm#dm01706@大食 請獻師子。

 rm#r00620@姚璹 上疏，
以爲：
「師子專食肉，
遠道傳致，
肉既難得，
極爲勞費。

陛下鷹犬不蓄，
漁獵悉停，
豈容菲薄於身而厚給於獸！」

乃卻之。
# p 

以檢校夏官侍郎 rm#r05158@孫元亨 同平章事。
# p 

夏，
五月，
壬子，
 dm#dm05611@營州 契丹 dm#dm03908@松漠 都督 rm#r05419@李盡忠 、 dm#dm04352@歸誠州 刺史 rm#r01945@孫萬榮 舉兵反，
攻陷 dm#dm05611@營州 ，
殺都督 rm#r05911@趙文翽 。

 rm#r05419@盡忠 ，
 rm#r01945@萬榮 之妹夫也，
皆居於 dm#dm05611@營州 城側。

 rm#r05911@文翽 剛愎，
契丹饑不加賑給，
視酋長如奴僕，
故二人怨而反。

乙丑，
遣左鷹揚衞將軍 rm@曹仁師 、右金吾衞大將軍 rm#r06186@張玄遇 、左威衞大將軍 rm#r01671@李多祚 、司農少卿 rm#r06133@麻仁節 等二十八將討之。

秋，
七月，
辛亥，
以春官尚書 rm@梁王  rm#r02294@武三思 爲 dm#dm04114@楡關道 安撫大使，
 rm#r00620@姚璹 副之，
以備契丹。

改 rm#r05419@李盡忠 爲 rm#r05420@李盡滅 ，
 rm#r01945@孫萬榮 爲 rm#r01945@孫萬斬 。

# p 

 rm@盡忠 尋自稱 rm@無上可汗 ，
據 dm#dm05611@營州 ，
以 rm#r01945@萬榮 爲前鋒，
略地，
所向皆下，
旬日，
兵至數萬，
進圍 dm#dm00056@檀州 ，
清邊前軍副總管 rm#r05244@張九節 撃卻之。
# p 

八月，
丁酉，
 rm#ry0020@曹仁師 、 rm#r06186@張玄遇 、 rm#r06133@麻仁節 與契丹戰于 dm#dm06161@硤石谷 ，
 dyn#ch100@唐 兵大敗。

先是，
契丹破 dm#dm05611@營州 ，
獲 dyn#ch100@唐 俘數百，
囚之地牢，
聞 dyn#ch100@唐 兵將至，
使守牢霫紿之曰：
「吾輩家屬，
飢寒不能自存，
唯俟官軍至即降耳。」

既而契丹引出其俘，
飼以糠粥，
慰勞之曰：
「吾養汝則無食，
殺汝又不忍，
今縱汝去。」

遂釋之。

俘至 dm#dm02689@幽州 ，
具言其状，
諸軍聞之，
爭欲先入。

至 dm#dm09109@黄麞谷 ，
虜又遣老弱迎降，
故遺老牛痩馬於道側。

 rm#ry0020@仁師 等三軍棄歩卒，
將騎兵先進。

契丹設伏横撃之，
飛索以䁥䌈 rm#r06186@玄遇 、 rm#r06133@仁節 ，
生獲之，
將卒死者填山谷，
鮮有脱者。

契丹得軍印，
詐爲牒，
令 rm#r06186@玄遇 等署之，
牒總管 rm#r05577@燕匪石 、 rm#r05190@宗懷昌 等云：
「官軍已破賊，
若至 dm#dm05611@營州 ，
軍將皆斬，
兵不敍勳。」

 rm#r05577@匪石 等得牒，
晝夜兼行，
不遑寢食以赴之，
士馬疲弊；
契丹伏兵於中道邀之，
全軍皆沒。
# p 

九月，
制：
「天下繋囚及庶士家奴驍勇者，
官償其直，
發以撃契丹。」

初令 dm#dm02403@山東 近邊諸州置武騎團兵，
以 dm#dm01227@同州 刺史 rm#r01703@建安王  rm#r06224@武攸宜 爲右武威衞大將軍，
充 dm#dm05083@清邊道 行軍大總管，
以討契丹。
# p 

右拾遺 rm#r03920@陳子昂 爲 rm#r06224@攸宜 府參謀，
上疏曰：
「恩制免天下罪人及募諸色奴充兵討撃契丹，
此乃捷急之計，
非天子之兵。

且比來刑獄久清，
罪人全少，
奴多怯弱，
不慣征行，
縱其募集，
未足可用。

況今天下忠臣義士，
萬分未用其一，
契丹小孼，
假命待誅，
何勞免罪贖奴，
損國大體！

臣恐此策不可威示天下。」

# p 

丁巳，
突厥寇 dm#dm04947@涼州 ，
執都督 rm#r03518@許欽明 。

 rm#r03518@欽明 ，
 rm#r03523@紹 之曾孫也；
時出按部，
突厥數萬奄至城下，
 rm#r03518@欽明 拒戰，
爲所虜。


# p 

 rm#r03518@欽明 兄 rm#r03517@欽寂 ，
時爲 dm#dm09235@龍山軍 討撃副使，
與契丹戰於 dm#dm02463@崇州 ，
軍敗，
被擒。

虜將圍 dm#dm02032@安東 ，
令 rm#r03517@欽寂 説其屬城未下者。

 dm#dm02032@安東 都護 rm#r05846@裴玄珪 在城中，
 rm#r03517@欽寂 謂曰：
「狂賊天殃，
滅在朝夕，
公但勵兵謹守以全忠節。」

虜殺之。
# p 

吐蕃復遣使請和親，
太后遣右武衞冑曹參軍 dm#dm07525@貴郷  rm#r03747@郭元振 往察其宜。

吐蕃將 rm#xjts01678@論欽陵 請罷 dm#dm02061@安西 四鎭戍兵，
幷求分十姓突厥之地。

 rm#r03747@元振 曰：
「四鎭、十姓與吐蕃種類本殊，
今請罷 dyn#ch100@唐 兵，
豈非有兼幷之志乎？」
 rm#xjts01678@欽陵 曰：
「吐蕃苟貪土地，
欲爲邊患，
則東侵 dm#dm05794@甘 、 dm#*dm04947@涼 ，
豈肯規利於萬里之外邪！」

乃遣使者隨 rm#r03747@元振 入請之。
# p 

朝廷疑未決，
 rm#r03747@元振 上疏，
以爲：
「 rm#xjts01678@欽陵 求罷兵割地，
此乃利害之機，
誠不可輕舉措也。

今若直拒其善意，
則爲邊患必深。

四鎭之利遠，
 dm#dm05794@甘 、 dm#*dm04947@涼 之害近，
不可不深圖也。

宜以計緩之，
使其和望未絶則善矣。

彼四鎭、十姓，
吐蕃之所甚欲也，
而 dm#dm08673@青海 、 dm#dm01253@吐谷渾 ，
亦國家之要地也，
今報之宜曰：
『四鎭、十姓之地，
本無用於 dm#dm00255@中國 ，
所以遣兵戍之，
欲以鎭撫 dm#dm07304@西域 ，
分吐蕃之勢，
使不得併力東侵也。

今若果無東侵之志，
當歸我吐谷渾諸部及 dm#dm08673@青海 故地，
則五俟斤部亦當以歸吐蕃。』

如此則足以塞 rm#xjts01678@欽陵 之口，
而亦未與之絶也。

若 rm#xjts01678@欽陵 小有乖違，
則曲在彼矣。

且四鎭、十姓款附日久，
今未察其情之向背，
事之利害，
遙割而棄之，
恐傷諸國之心，
非所以御四夷也。」

太后從之。

# p 

 rm#r03747@元振 又上言：
「 dm#*dm01250@吐蕃 百姓疲於傜戍，
早願和親；
 rm#xjts01678@欽陵 利於統兵專制，
獨不欲歸款。

若國家歳發和親使，
而 rm#xjts01678@欽陵 常不從命，
則彼國之人怨 rm#xjts01678@欽陵 日深，
望國恩日甚，
設欲大舉其徒，
固亦難矣。

斯亦離間之漸，
可使其上下猜阻，
禍亂内興矣。」

太后深然之。

 rm#r03747@元振 名 rm#r03747@震 ，
以字行。
# p 

庚申，
以 dm#dm00059@幷州 長史 rm#r02684@王方慶 爲鸞臺侍郎，
與殿中監 dm#dm06979@萬年  rm#r05434@李道廣 竝同平章事。
# p 

突厥 rm#xjts24882@默啜 請爲太后子，
幷爲其女求昏，
悉歸 dm#dm04695@河西 降戸，
帥其部衆爲國討契丹。

太后遣豹韜衞大將軍 rm#r03888@閻知微 、左衞郎將攝司賓卿 rm#r02822@田歸道 册授 rm#xjts24882@默啜 左衞大將軍、 rm#xjts24882@遷善可汗 。

 rm#r03888@知微 ，
 rm#r03882@立徳 之孫；
 rm#r02822@歸道 ，
 rm#r02815@仁會 之子也。

# p 

冬，
十月，
辛卯，
契丹 rm#r05419@李盡忠 卒，
 rm#r01945@孫萬榮 代領其衆。

突厥 rm@默啜 乘間襲 dm#dm03908@松漠 ，
虜 rm#r05419@盡忠 、 rm#r01945@萬榮 妻子而去。

太后進拜 rm@默啜 爲 rm@頡跌利施大單于 、 rm@立功報國可汗 。

# p 

 rm#r01945@孫萬榮 收合餘衆，
軍勢復振，
遣別帥 rm#r06092@駱務整 、 rm#r05031@何阿小 爲前鋒，
攻陷 dm#dm00712@冀州 ，
殺刺史 rm#r06024@陸寶積 ，
屠吏民數千人；
又攻 dm#dm05480@瀛州 ，
 dm#dm04656@河北 震動。

制起 dm#dm02935@彭澤 令 rm#r02567@狄仁傑 爲 dm#dm08950@魏州 刺史。

前刺史 rm#r05590@獨孤思莊 畏 dm#*dm01868@契丹 猝至，
悉驅百姓入城，
繕脩守備。

 rm#r02567@仁傑 至，
悉遣還農，
曰：
「賊猶在遠，
何煩如是！

萬一賊來，
吾自當之。」

百姓大悦。
# p 

時契丹入寇，
軍書填委，
夏官郎中 dm#dm06157@硤石  rm#r00627@姚元崇 剖析如流，
皆有條理，
太后奇之，
擢爲夏官侍郎。
# p 

太后思 rm#r01311@徐有功 用法平，
擢拜左臺殿中侍御史，
聞者無不相賀。

 dm#dm09065@鹿城 主簿 dm#dm02113@宗城  rm#r02517@潘好禮 ，
著論，
稱 rm#r01311@有功 蹈道依仁，
固守誠節，
不以貴賤死生易其操履。

設客問曰：
「 rm#r01311@徐公 於今誰與爲比？」
主人曰：
「四海至廣，
人物至多，
或匿迹韜光，
僕不敢誣，
若所聞見，
則一人而已，
當於古人中求之。」

客曰：
「何如 rm#r05307@張釋之 ？」
主人曰：
「 rm#r05307@釋之 所行者甚易，
 rm#r01311@徐公 所行者甚難，
難易之間，
優劣見矣。

 rm@張公 逢 rm#rt0515@漢文 之時，
天下無事，
至如盜 dm#dm08897@高廟 玉環及 dm#dm05115@渭橋 驚馬，
守法而已，
豈不易哉！

 rm#r01311@徐公 逢革命之秋，
屬惟新之運，
 dyn#ch100@唐朝 遺老，
或包藏禍心，
使人主有疑。

如 rm#r00116@周興 、 rm#r00115@來俊臣 ，
乃 rm#rt0006@堯 年之四凶也，
崇飾惡言以誣盛徳；
而 rm#r01311@徐公 守死善道，
深相明白，
幾陷囹圄，
數挂綱維，
此吾子所聞，
豈不難哉！」

客曰：
「使爲司刑卿，
乃得展其才矣。」

主人曰：
「吾子徒見 rm#r01311@徐公 用法平允，
謂可置司刑；
僕覩其人，
方寸之地，
何所不容，
若其用之，
何事不可，
豈直司刑而已哉！」
遠近綱維網羅
*** 二年
# year 0697
# p 

正月，
己亥朔，
太后享 dm#dm07688@通天宮 。
# p 

突厥 rm@默啜 寇 dm#dm08619@靈州 ，
以 rm#r03518@許欽明 自隨。

 rm#r03518@欽明 至城下大呼，
求美醤、梁米及墨，
意欲城中選良將、引精兵、夜襲虜營，
而城中無諭其意者。
# p 

 dm#dm06366@箕州 刺史 rm#r00254@劉思禮 學相人於術士 rm#r01161@張憬藏 ，
 rm#r01161@憬藏 謂 rm#r00254@思禮 當歴 dm#dm06366@箕州 ，
位至太師。

 rm#r00254@思禮 念太師人臣極貴，
非佐命無以致之，
乃與 dm#dm04778@洛州 録事參軍 rm@綦連耀 謀反，
陰結朝士，
託相術，
許人富貴，
俟其意悦，
因説以「 rm@綦連耀 有天命，
公必因之以得富貴。」

鳳閣舍人 rm#r02725@王勮 兼天官侍郎事，
用 rm#r00254@思禮 爲 dm#dm06366@箕州 刺史。
# p 

 dm#*dm03477@明堂 尉 rm#r00398@吉頊 聞其謀，
以告 dm#dm01184@合宮 尉 rm#r00115@來俊臣 ，
使上變告之。

太后使 rm#r02313@河内王  rm#r02313@武懿宗 推之。

 rm#r01367@懿宗 令 rm#r00254@思禮 廣引朝士，
許免其死，
凡小忤意皆引之。

於是 rm#r00254@思禮 引鳳閣侍郎同平章事 rm#r01627@李元素 、夏官侍郎同平章事 rm#r05158@孫元亨 、知天官侍郎事 rm#r02959@石抱忠 、 rm#r00213@劉奇 、給事中 rm#r05131@周譒 及 rm#r02725@王勮 兄 dm#dm04924@涇州 刺史 rm#r02721@勔 、弟監察御史 rm#r02600@助 等，
凡三十六家，
皆海内名士，
窮楚毒以成其獄，
壬戌，
皆族誅之，
親黨連坐流竄者千餘人。河南
# p 

初，
 rm#r01367@懿宗 寛 rm#r00254@思禮 於外，
使誣引諸人。

諸人既誅，
然後收 rm#r00254@思禮 ，
 rm#r00254@思禮 悔之。

 rm#r01367@懿宗 自 y@天授 以來，
太后數使之鞫獄，
喜誣陷人，
時人以爲 rm#r00116@周 、 rm#r00115@來 之亞。
# p 

 rm#r00115@來俊臣 欲其功，
復羅告 rm#r00398@吉頊 ；
 rm#r00398@頊 上變，
得召見，
僅免。

 rm#r00115@俊臣 由是復用，
而 rm#r00398@頊 亦以此得進。
# p 

 rm#r00115@俊臣 黨人羅告司刑府史 rm#r05526@樊惎 謀反，
誅之。

 rm#r05526@惎 子訟冤於朝堂，
無敢理者，
乃援刀自刳其腹。

秋官侍郎 dm#dm00192@上邽  rm#r00214@劉如璿 見之，
竊嘆而泣。

 rm#r00115@俊臣 奏 rm#r00214@如璿 黨惡逆，
下獄，
處以絞刑；
制流 dm#dm05492@瀼州 。
# p 

尚乘奉御 rm#r01178@張易之 ，
 rm#r01250@行成 之族孫也，
年少，
美姿容，
善音律。

 rm#r00603@太平公主 薦 rm#r01178@易之 弟 rm#r01176@昌宗 入侍禁中，
 rm#r01176@昌宗 復薦 rm#r01178@易之 ，
兄弟皆得幸於太后，
常傅朱粉，
衣錦繡。

 rm#r01176@昌宗 累遷散騎常侍，
 rm#r01178@易之 爲司衞少卿；
拜其母 rm#xjts19129@臧氏 、 rm#xjts19129@韋氏 爲太夫人，
賞賜不可勝紀，
仍敕鳳閣侍郎 rm#r01983@李迥秀 爲臧氏私夫。

 rm#r01983@迥秀 ，
 rm#r01672@大亮 之族孫也。

 rm#r02314@武承嗣 、 rm#r02294@三思 、 rm#r01367@懿宗 、 rm#r00825@宗楚客 、 rm#r00824@晉卿 皆候 rm#r01178@易之 門庭，
爭執鞭轡，
謂 rm#r01178@易之 爲 rm#r01178@五郎 ，
 rm#r01176@昌宗 爲 rm#r01176@六郎 。
# p 

癸亥，
突厥 rm@默啜 寇 dm#dm00812@勝州 ，
 dm#dm02658@平狄軍 副使 rm#r05179@安道買 撃破之。

# p 

甲子，
以 dm#dm01114@原州 司馬 rm#r00657@婁師徳 守鳳閣侍郎、同平章事。
# p 

春，
三月，
戊申，
 dm#dm05083@清邊道 總管 rm#r02615@王孝傑 、 rm#r05828@蘇宏暉 等將兵十七萬與 rm#r01945@孫萬榮 戰于 dm#dm03860@東硤石谷 ，
 dyn#ch100@唐 兵大敗，
 rm#r02615@孝傑 死之。

# p 

 rm#r02615@孝傑 遇契丹，
帥精兵爲前鋒，
力戰。

契丹引退，
 rm#r02615@孝傑 追之，
行背懸崖；
契丹囘兵薄之，
 rm@宏暉 先遁，
 rm#r02615@孝傑 墜崖死，
將士死亡殆盡。

管記 dm#dm04788@洛陽  rm#r01253@張説 馳奏其事。

太后贈 rm#r02615@孝傑 官爵，
遣使斬 rm@宏暉 以徇；
使者未至，
 rm@宏暉 以立功得免。

# p 

 rm#r06224@武攸宜 軍 dm#dm05254@漁陽 ，
聞 rm#r02615@孝傑 等敗沒，
軍中震恐，
不敢進。

契丹乘勝寇 dm#dm02689@幽州 ，
攻陷城邑，
剽掠吏民，
 rm#r06224@攸宜 遣將撃之，
不克。

# p 

 rm#r03888@閻知微 、 rm#r02822@田歸道 同使突厥，
册 rm@默啜 爲可汗。

 rm#r03888@知微 中道遇突厥使者，
輒與之緋袍、銀帶，
且上言：
「虜使至都，
宜大爲供張。」

 rm#r02822@歸道 上言：
「突厥背誕積年，
方今悔過，
宜待聖恩寛宥。

今 rm#r03888@知微 與之袍帶，
使朝廷無以復加；
宜令反初服以俟朝恩。

又，
小虜使臣，
不足大爲供張。」

太后然之。

 rm#r03888@知微 見 rm@默啜 ，
舞蹈，
吮其靴鼻；
 rm#r02822@歸道 長揖不拜。

 rm@默啜 囚 rm#r02822@歸道 ，
將殺之，
 rm#r02822@歸道 辭色不撓，
責其無厭，
爲陳禍福。

 rm@阿波達干  rm#r05048@元珍 曰：
「大國使者，
不可殺也。

」
 rm@默啜 怒稍解，
但拘留不遣。


# p 

初，
 y@咸亨中 ，
突厥有降者，
皆處之 dm#dm07470@豐 、 dm#dm00812@勝 、 dm#dm08619@靈 、 dm#dm01532@夏 、 dm#dm03671@朔 、 dm#dm00485@代 六州，
至是，
 rm@默啜 求六州降戸及 dm#dm01394@單于  dm#dm07884@都護府 之地，
幷穀種、繒帛、農器、鐵，
太后不許。

 rm@默啜 怒，
言辭悖慢。

 rm#r00620@姚璹 、 rm#r02155@楊再思 以契丹未平，
請依 rm@默啜 所求給之。

麟臺少監、知鳳閣侍郎 dm#dm07566@贊皇  rm#r01714@李嶠 曰：
「戎狄貪而無信，
此所謂『借寇兵資盜糧』
也，
不如治兵以備之。」

 rm#r00620@璹 、 rm#r02155@再思 固請與之，
乃悉驅六州降戸數千帳以與 rm@默啜 ，
幷給穀種四萬斛，
雜綵五萬段，
農器三千事，
鐵四萬斤，
幷許其昏。

 rm@默啜 由是益強。
# p 

 rm#r02822@田歸道 始得還，
與 rm#r03888@閻知微 爭論於太后前。

 rm#r02822@歸道 以爲 rm@默啜 必負約，
不可恃和親，
宜爲之備。

 rm#r03888@知微 以爲和親必可保。


# p 

夏，
四月，
鑄九鼎成，
徙置 dm#dm07688@通天宮 。

 dm#dm07502@豫州 鼎高丈八尺，
受千八百石；
 dm#dm08790@餘州 高丈四尺，
受千二百石；
各圖山川物産於其上，
共用銅五十六萬七百餘斤。

太后欲以黄金千兩塗之，
 rm#r00620@姚璹 曰：
「九鼎神器，
貴於天質自然。

且臣觀其五采煥炳相雜，
不待金色以爲炫燿。」

太后從之。

自 dm#dm05694@玄武門 曳入，
令宰相、諸王帥南北牙宿衞兵十餘萬人幷仗内大牛、白象共曳之。

# p 

前 dm#dm05982@益州 長史 rm@王及善 已致仕，
會契丹作亂，
 dm#dm02403@山東 不安，
起爲 dm#dm05229@滑州 刺史。

太后召見，
問以朝廷得失，
 rm@及善 陳治亂之要十餘條。

太后曰：
「外州末事，
此爲根本，
卿不可出。」

癸酉，
留爲内史。

# p 

癸未，
以右金吾衞大將軍 rm#r02313@武懿宗 爲 dm#dm06216@神兵道 行軍大總管，
與右豹韜衞將軍 rm#r05029@何迦密 將兵撃契丹。

五月，
癸卯，
又以 rm#r00657@婁師徳 爲 dm#dm05083@清邊道 副大總管，
右武威衞將軍 rm@沙吒忠義 爲前軍總管，
將兵二十萬撃契丹。
# p 

先是，
有 rm#r05342@朱前疑 者上書云：
「臣夢陛下壽滿八百。」

即拜拾遺。

又自言「夢陛下髮白再玄，
齒落更生」。

遷駕部郎中。

出使還，
上書曰：
「聞 dm#dm02514@嵩山 呼萬歳。」

賜以緋算袋，
時未五品，
於緑衫上佩之。

會發兵討契丹，
敕 dm#dm00426@京 官出馬一匹供軍，
酬以五品。

 rm#r05342@前疑 買馬輸之，
屡抗表求進階；
太后惡其貪鄙，
六月，
乙丑，
敕還其馬，
斥歸田里。
# p 

右司郎中 dm#dm08850@馮翊  rm#r00522@喬知之 有美妾曰 rm@碧玉 ，
 rm#r00522@知之 爲之不昏。

 rm#r02314@武承嗣 借以教諸姬，
遂留不還。

 rm#r00522@知之 作緑珠怨以寄之，
 rm@碧玉 赴井死。

 rm#r02314@承嗣 得詩於裙帶，
大怒，
諷酷吏羅告，
族之。

# p 

司僕少卿 rm#r00115@來俊臣 倚勢貪淫，
士民妻妾有美者，
百方取之；
或使人羅告其罪，
矯稱敕以取其妻，
前後羅織誅人，
不可勝計。

自宰相以下，
籍其姓名而取之。

自言才比 rm#rx0021@石勒 。

監察御史 rm#r01805@李昭徳 素惡 rm#r00115@俊臣 ，
又嘗庭辱秋官侍郎 rm@皇甫丈備 ，
二人共誣昭徳謀反，
下獄。
丈文
# p 

 rm#r00115@俊臣 欲羅告 rm#r02293@武氏 諸王及 rm#r00603@太平公主 ，
又欲誣皇嗣及 rm#r01656@廬陵王 與南北牙同反，
冀因此盜國權，
 dm#dm04672@河東 人 rm#r05003@衞遂忠 告之。

諸 rm#no@武 及 rm#r00603@太平公主 恐懼，
共發其罪，
繋獄，
有司處以極刑。

太后欲赦之，
奏上三日，
不出。

 rm#r02603@王及善 曰：
「 rm#r00115@俊臣 凶狡貪暴，
國之元惡，
不去之，
必動搖朝廷。」

太后遊苑中，
 rm#r00398@吉頊 執轡，
太后問以外事，
對曰：
「外人唯怪 rm#r00115@來俊臣 奏不下。」

太后曰：
「 rm#r00115@俊臣 有功於國，
朕方思之。」

 rm#r00398@頊 曰：
「 rm#r05011@于安遠 告 rm#r03593@虺貞 反，
既而果反，
今止爲 dm#dm03135@成州 司馬。

 rm#r00115@俊臣 聚結不逞，
誣構良善，
贓賄如山，
冤魂塞路，
國之賊也，
何足惜哉！」

太后乃下其奏。
# p 

丁卯，
 rm#r01805@昭徳 、 rm#r00115@俊臣 同棄市，
時人無不痛 rm#r01805@昭徳 而快 rm#r00115@俊臣 。

仇家爭噉 rm#r00115@俊臣 之肉，
斯須而盡，
抉眼剥面，
披腹出心，
騰蹋成泥。

太后知天下惡之，
乃下制數其罪惡，
且曰：
「宜加赤族之誅，
以雪蒼生之憤，
可準法籍沒其家。」

士民皆相賀於路曰：
「自今眠者背始帖席矣。」

# p 

 rm#r00115@俊臣 以告 rm@綦連耀 功，
賞奴婢十人。

 rm#r00115@俊臣 閲司農婢，
無可者，
以西突厥可汗 rm@斛瑟羅 家有細婢，
善歌舞，
欲得以爲賞口，
乃使人誣告 rm@斛瑟羅 反。

諸酋長詣闕割耳剺面訟冤者數千人。

會 rm#r00115@俊臣 誅，
乃得免。
# p 

 rm#r00115@俊臣 方用事，
選司受其屬請不次除官者，
毎銓數百人。

 rm#r00115@俊臣 敗，
侍郎皆自首。

太后責之，
對曰：
「臣負陛下，
死罪！

臣亂國家法，
罪止一身；
違 rm#r00115@俊臣 語，
立見滅族。」

太后乃赦之。
# p 

上林令 rm#r05035@侯敏 素諂事 rm#r00115@俊臣 ，
其妻 rm@董氏 諫之曰：
「 rm#r00115@俊臣 國賊，
指日將敗，
君宜遠之。」

 rm#r05035@敏 從之。

 rm#r00115@俊臣 怒，
出爲 dm#dm04329@武龍 令。

 rm#r05035@敏 欲不往，
妻曰：
「速去勿留！」

 rm#r00115@俊臣 敗，
其黨皆流 dm#dm02527@嶺南 ，
 rm#r05035@敏 獨得免。
# p 

太后徵 rm#r05011@于安遠 爲尚食奉御，
擢 rm#r00398@吉頊 爲右肅政中丞。
# p 

以檢校夏官侍郎 rm#r00825@宗楚客 同平章事。
# p 

 rm#r02313@武懿宗 軍至 dm#dm07623@趙州 ，
聞契丹將 rm#r06092@駱務整 數千騎將至 dm#dm00712@冀州 ，
 rm#r01367@懿宗 懼，
欲南遁。

或曰：
「虜無輜重，
以抄掠爲資，
若按兵拒守，
勢必離散，
從而撃之，
可有大功。」

 rm#r01367@懿宗 不從，
退據 dm#dm06029@相州 ，
委棄軍資器仗甚衆。

契丹遂屠 dm#dm07623@趙州 。


# p 

甲午，
 rm#r01945@孫萬榮 爲奴所殺。午申
# p 

 rm#r01945@萬榮 之破 rm#r02615@王孝傑 也，
於 dm#dm03970@柳城 西北四百里依險築城，
留其老弱婦女，
所獲器仗資財，
使妹夫 rm@乙冤羽 守之，
引精兵寇 dm#dm02689@幽州 。

恐突厥 rm@默啜 襲其後，
遣五人至黒沙，
語 rm@默啜 曰：
「我已破 rm#r02615@王孝傑 百萬之衆，
 dyn#ch100@唐 人破膽，
請與可汗乘勝共取 dm#dm02689@幽州 。」

三人先至，
 rm@默啜 喜，
賜以緋袍。

二人後至，
 rm@默啜 怒其稽緩，
將殺之，
二人曰：
「請一言而死。」

 rm@默啜 問其故，
二人以契丹之情告。

 rm@默啜 乃殺前三人而賜二人緋，
使爲郷導，
發兵取契丹 dm#dm03332@新城 ，
殺所獲 dm#dm04947@涼州 都督 rm#r03518@許欽明 以祭天；
圍 dm#dm03332@新城 三日，
克之，
盡俘以歸。

使 rm@乙冤羽 馳報 rm#r01945@萬榮 。
# p 

時 rm#r01945@萬榮 方與 dyn#ch100@唐 兵相持，
軍中聞之，
忷懼。

奚人叛 rm#r01945@萬榮 ，
 dm#dm06216@神兵道 總管 rm#r05508@楊玄基 撃其前，
奚兵撃其後，
獲其將 rm#r05031@何阿小 。

 rm#r01945@萬榮 軍大潰，
帥輕騎數千東走。

前軍總管 rm#r05244@張九節 遣兵邀之於道，
 rm#r01945@萬榮 窮蹙，
與其奴逃至 dm#dm05360@潞水 東，
息於林下，
嘆曰：
「今欲歸 dyn#ch100@唐 ，
罪已大。

歸突厥亦死，
歸 dm#dm03383@新羅 亦死。

將安之乎！」

奴斬其首以降，
梟之四方館門。

其餘衆及奚、霫皆降於突厥。

# p 

戊子，
特進 rm#r02314@武承嗣 、春官尚書 rm#r02294@武三思 竝同鳳閣鸞臺三品。
# p 

辛卯，
制以契丹初平，
命 rm#r02313@河内王武懿宗 、 rm#r00657@婁師徳 及 dm#dm08950@魏州 刺史 rm#r02567@狄仁傑 分道安撫 dm#dm04656@河北 。

 rm#r02313@懿宗 所至殘酷，
民有爲契丹所脅從復來歸者，
 rm#r02313@懿宗 皆以爲反，
生刳取其膽。

先是，
 rm#r05031@何阿小 嗜殺人，
 dm#dm04656@河北 人爲之語曰：
「唯此兩 rm#gr@何 ，
殺人最多。」


# p 

秋，
七月，
丁酉，
 dm#dm03448@昆明 内附，
置 dm#dm06328@竇州 。
# p 

 rm#r02314@武承嗣 、 rm#r02294@武三思 竝罷政事。
# p 

庚午，
 rm#r06224@武攸宜 自 dm#dm02689@幽州 凱旋。

 rm#r02313@武懿宗 奏 dm#dm04656@河北 百姓從賊者請盡族之，
左拾遺 rm#r02659@王求禮 庭折之曰：
「此屬素無武備，
力不勝賊，
苟從之以求生，
豈有叛國之心！

 rm#r01367@懿宗 擁強兵數十萬，
望風退走，
賊徒滋蔓，
又欲委罪於草野詿誤之人，
爲臣不忠，
請先斬 rm#r01367@懿宗 以謝 dm#dm04656@河北 ！」

 rm#r01367@懿宗 不能對。

司刑卿 rm#r02049@杜景儉 亦奏：
「此皆脅從之人，
請悉原之。」

太后從之。
# p 

八月，
丙戌，
納言 rm#r00620@姚璹 坐事左遷 dm#dm05982@益州 長史，
以太子宮尹 rm#r03546@豆盧欽望 爲文昌右相、鳳閣鸞臺三品。

** 神功
*** 神功元年
# year 0697
# p 

九月，
壬辰，
大享 dm#dm07688@通天宮 ，
大赦，
改元。
大赦赦天下
# p 

庚戌，
 rm#r00657@婁師徳 守納言。
# p 

甲寅，
太后謂侍臣曰：
「頃者 rm#r00116@周興 、 rm#r00115@來俊臣 按獄，
多連引朝臣，
云其謀反；
國有常法，
朕安敢違！

中間疑其不實，
使近臣就獄引問，
得其手状，
皆自承服，
朕不以爲疑。

自 rm#r00116@興 、 rm#r00115@俊臣 死，
不復聞有反者，
然則前死者不有冤邪？」
夏官侍郎 rm#r00627@姚元崇 對曰：
「自 y@垂拱 以來坐謀反死者，
率皆 rm#r00116@興 等羅織，
自以爲功。

陛下使近臣問之，
近臣亦不自保，
何敢動搖！

所問者若有翻覆，
懼遭慘毒，
不若速死。

頼天啓聖心，
 rm#r00116@興 等伏誅，
臣以百口爲陛下保，
自今内外之臣無復反者；
若微有實状，
臣請受知而不告之罪。」

太后悦曰：
「曏時宰相皆順成其事，
陷朕爲淫刑之主；
聞卿所言，
深合朕心。」

賜 rm#r00627@元崇 錢千緡。
# p 

時人多爲 rm#r04302@魏元忠 訟冤者，
太后復召爲肅政中丞。

 rm#r04302@元忠 前後坐棄市流竄者四。

嘗侍宴，
太后問曰：
「卿往者數負謗，
何也？」
對曰：
「臣猶鹿耳，
羅織之徒欲得臣肉爲羹，
臣安所避之！」

# p 

冬，
閏十月，
甲寅，
以 dm#dm02689@幽州 都督 rm#r02567@狄仁傑 爲鸞臺侍郎，
司刑卿 rm#r02049@杜景儉 爲鳳閣侍郎，
竝同平章事。
# p 

 rm#r02567@仁傑 上疏以爲：
「天生四夷，
皆在先王封略之外，
故東拒滄海，
西阻流沙，
北横大漠，
南阻五嶺，
此天所以限夷狄而隔中外也。

自典籍所紀，
聲教所及，
 dyn#ch902@三代 不能至者，
國家盡兼之矣。

詩人矜薄伐於 dm#dm01774@太原 ，
美化行於 dm#dm04475@江 、 dm#dm05271@漢 ，
則 dyn#ch902@三代 之遠裔，
皆國家之域中也。

若乃用武方外，
邀功絶域，
竭府庫之實以爭不毛之地，
得其人不足増賦，
獲其土不可耕織，
苟求冠帶遠夷之稱，
不務固本安人之術，
此 rm#rt0506@秦皇 、 rm#rt0517@漢武 之所行，
非 rm#gr@五帝 、 rm#gr@三王 之事業也。

 rm#rt0506@始皇 窮兵極武，
務求廣地，
死者如麻，
致天下潰叛。

 rm@漢武 征伐四夷，
百姓困窮，
盜賊蜂起；
末年悔悟，
息兵罷役，
故能爲天所祐。

近者國家頻歳出師，
所費滋廣，
西戍四鎭，
東戍 dm#dm02032@安東 ，
調發日加，
百姓虚弊。

今 dm#dm08286@關東 饑饉，
 dm#dm07197@蜀 、 dm#dm05271@漢 逃亡，
 dm#dm04475@江 、 dm#dm04981@淮 已南，
徵求不息，
人不復業，
相率爲盜，
本根一搖，
憂患不淺。

其所以然者，
皆以爭蠻貊不毛之地，
乖子養蒼生之道也。

昔 rm#rt0521@漢元 納 rm#r05886@賈捐之 之謀而罷 dm#dm03742@朱崖郡 ，
 rm@宣帝 用 rm#r06124@魏相 之策而棄 dm#dm07632@車師 之田，
豈不欲慕尚虚名，
蓋憚勞人力也。

近 y@貞觀中 克平九姓，
立 rm#r05388@李思摩 爲可汗，
使統諸部者，
蓋以夷狄叛則伐之，
降則撫之，
得推亡固存之義，
無遠戍勞人之役，
此近日之令典，
經邊之故事也。

竊謂宜立 rm#r05994@阿史那斛瑟羅 爲可汗，
委之四鎭，
繼 rm#r01294@高氏 絶國，
使守 dm#dm02032@安東 。

省軍費於遠方，
幷甲兵於塞上，
使夷狄無侵侮之患則可矣，
何必窮其窟穴，
與螻蟻校長短哉！

但當敕邊兵，
謹守備，
遠斥候，
聚資糧，
待其自致，
然後撃之。

以逸待勞則戰士力倍，
以主禦客則我得其便，
堅壁清野則寇無所得；
自然二賊深入則有顛躓之慮，
淺入必無寇獲之益。

如此數年，
可使二虜不撃而服矣。」

事雖不行，
識者是之。
# p 

鳳閣舍人 rm#r01714@李嶠 知天官選事，
始置員外官數千人。
# p 

先是暦官以是月爲正月，
以臘月爲閏。

太后欲正月甲子朔冬至，
乃下制以爲「去晦仍見月，
有爽天經。

可以今月爲閏月，
來月爲正月。」

** 聖暦
*** 聖暦元年
# year 0698
# p 

正月，
甲子朔，
冬至，
太后享 dm#dm07688@通天宮 ；
赦天下，
改元。


# p 

夏官侍郎 rm#r00825@宗楚客 罷政事。
# p 

春，
二月，
乙未，
文昌右相、同鳳閣鸞臺三品 rm#r03546@豆盧欽望 罷爲太子賓客。
# p 

 rm#r02314@武承嗣 、 rm#r02294@三思 營求爲太子，
數使人説太后曰：
「自古天子未有以異姓爲嗣者。

」
太后意未決。

 rm#r02567@狄仁傑 毎從容言於太后曰：
「 rm#r01602@文皇帝 櫛風沐雨，
親冒鋒𨮹，
以定天下，
傳之子孫。

 rm#r01837@大帝 以二子託陛下。

陛下今乃欲移之他族，
無乃非天意乎！

且姑姪之與母子孰親？
陛下立子，
則千秋萬歳後，
配食太廟，
承繼無窮；
立姪，
則未聞姪爲天子而祔姑於廟者也。」

太后曰：
「此朕家事，
卿勿預知。」

 rm#r02567@仁傑 曰：
「王者以四海爲家，
四海之内，
孰非臣妾，
何者不爲陛下家事！

君爲元首，
臣爲股肱，
義同一體，
況臣備位宰相，
豈得不預知乎！」

又勸太后召還 rm#r01656@廬陵王 。

 rm#r02684@王方慶 、 rm@王及善 亦勸之。

太后意稍寤。

他日，
又謂 rm#r02567@仁傑 曰：
「朕夢大鸚鵡兩翼皆折，
何也？」
對曰：
「 rm#no@武 者，
陛下之姓，
兩翼，
二子也。

陛下起二子，
則兩翼振矣。」

太后由是無立 rm#r02314@承嗣 、 rm#r02294@三思 之意。
# p 

 rm#r01945@孫萬榮 之圍 dm#dm02689@幽州 也，
移檄朝廷曰：
「何不歸我 rm#r01656@廬陵王 ？」
 rm#r00398@吉頊 與 rm#r01178@張易之 、 rm#r01176@昌宗 皆爲控鶴監供奉，
 rm#r01178@易之 兄弟親狎之。

 rm#r00398@頊 從容説二人曰：
「公兄弟貴寵如此，
非以徳業取之也，
天下側目切齒多矣。

不有大功於天下，
何以自全？
竊爲公憂之！」

二人懼，
流涕問計。

 rm#r00398@頊 曰：
「天下士庶未忘 dyn#ch100@唐 徳，
咸復思 rm#r01656@廬陵王 。

主上春秋高，
大業須有所付；
 rm#r02293@武氏 諸王非所屬意。

公何不從容勸上立 rm#r01656@廬陵王 以繋蒼生之望！

如此，
非徒免禍，
亦可以長保富貴矣。」

二人以爲然，
承間屡爲太后言之。

太后知謀出於 rm#r00398@頊 ，
乃召問之，
 rm#r00398@頊 復爲太后具陳利害，
太后意乃定。


# p 

三月，
己巳，
託言 rm#r01656@廬陵王 有疾，
遣職方員外郎 dm#dm05752@瑕丘  rm#r01318@徐彦伯 召 rm#r01656@廬陵王 及其𡚱、諸子詣行在療疾。

戊子，
 rm#r01656@廬陵王 至 dm#dm06235@神都 。

# p 

夏，
四月，
庚寅朔，
太后祀太廟。

# p 

辛丑，
以 rm#r00657@婁師徳 充 dm#dm08458@隴右 諸軍大使，
仍檢校營田事。

# p 

六月，
甲午，
命 rm#r02309@淮陽王  rm#r02309@武延秀 入突厥，
納 rm@默啜 女爲𡚱；
豹韜衞大將軍 rm#r03888@閻知微 攝春官尚書，
右武衞郎將 rm#r05520@楊齊莊 攝司賓卿，
齎金帛巨億以送之。

 rm#r02309@延秀 ，
 rm#r02314@承嗣 之子也。
# p 

鳳閣舍人 dm#dm07284@襄陽  rm#r01188@張柬之 諫曰：
「自古未有 dm#dm00255@中國 親王娶夷狄女者。」

由是忤旨，
出爲 dm#dm01190@合州 刺史。

# p 

秋，
七月，
鳳閣侍郎、同平章事 rm#r02049@杜景儉 罷爲秋官尚書。
# p 

八月，
戊子，
 rm#r02309@武延秀 至黒沙南庭。

突厥 rm#xjts24882@默啜 謂 rm#r03888@閻知微 等曰：
「我欲以女嫁 rm#no@李氏 ，
安用 rm#no@武氏 兒邪！

此豈天子之子乎！

我突厥世受 rm#no@李氏 恩，
聞 rm#no@李氏 盡滅，
唯兩兒在，
我今將兵輔立之。」

乃拘 rm#r02309@延秀 於別所，
以 rm#r03888@知微 爲 rm#r03888@南面可汗 ，
言欲使之主 dyn#ch100@唐 民也。

遂發兵襲 dm#dm08711@靜難 、 dm#dm02658@平狄 、 dm#dm05034@清夷 等軍，
 dm#dm08712@靜難軍 使 rm#xjts20258@慕容玄崱 以兵五千降之。

虜勢大振，
進寇 dm#dm01931@媯 、 dm#dm00056@檀 等州。

前從 rm#r03888@閻知微 入突厥者，
 rm#xjts24882@默啜 皆賜之五品、三品之服，
太后悉奪之。
# p 

 rm@默啜 移書數朝廷曰：
「與我蒸穀種，
種之不生，
一也。

金銀器皆行濫，
非眞物，
二也。

我與使者緋紫皆奪之，
三也。

繒帛皆疏惡，
四也。

我可汗女當嫁天子兒，
 rm#r02293@武氏 小姓，
門戸不敵，
罔冒爲昏，
五也。

我爲此起兵，
欲取 dm#dm04656@河北 耳。」


# p 

監察御史 rm#r03436@裴懷古 從 rm#r03888@閻知微 入突厥，
 rm@默啜 欲官之，
不受。

囚，
將殺之，
逃歸；
抵 dm#dm03567@晉陽 ，
形容羸悴。

突騎譟聚，
以爲間諜，
欲取其首以求功。

有果毅嘗爲人所枉，
 rm#r03436@懷古 按直之，
大呼曰：
「 rm#r03436@裴御史 也。」

救之，
得全。

至都，
引見，
遷祠部員外郎。

# p 

時諸州聞突厥入寇，
方秋，
爭發民脩城。

 dm#dm00029@衞州 刺史 dm#dm01792@太平  rm#r01407@敬暉 謂僚屬曰：
「吾聞金湯非粟不守，
奈何捨收穫而事城郭乎？」
悉罷之，
使歸田，
百姓大悦。
# p 

甲午，
鸞臺侍郎、同平章事 rm#r02684@王方慶 罷爲麟臺監。
# p 

太子太保 rm@魏宣王  rm#r02314@武承嗣 ，
恨不得爲太子，
意怏怏，
戊戌，
病薨。

# p 

庚子，
以春官尚書 rm#r02294@武三思 檢校内史，
 rm#r02567@狄仁傑 兼納言。
# p 

太后命宰相各舉尚書郎一人，
 rm#r02567@仁傑 舉其子司府丞 rm#r02568@光嗣 ，
拜地官員外郎，
已而稱職。

太后喜曰：
「卿足繼 rm@祁奚 矣。」


# p 

通事舍人 dm#dm04660@河南  rm#r00163@元行沖 ，
博學多通，
 rm#r02567@仁傑 重之。

 rm#r00163@行沖 數規諫 rm#r02567@仁傑 ，
且曰：
「凡爲家者必有儲蓄脯醢以適口，
參朮以攻疾。

僕竊計明公之門，
珍味多矣，
 rm#r00163@行沖 請備藥物之末。」

 rm#r02567@仁傑 笑曰：
「吾藥籠中物，
何可一日無也！」

 rm#r00163@行沖 名 rm#r00163@澹 ，
以字行。


# p 

以司屬卿 rm#r05542@武重規 爲 dm#dm01715@天兵中道 大總管，
右武衞將軍 rm@沙吒忠義 爲 dm#dm01717@天兵西道 總管，
 dm#dm02689@幽州 都督 dm#dm00227@下邽  rm#r01095@張仁愿 爲 dm#dm01716@天兵東道 總管，
將兵三十萬以討突厥 rm@默啜 ；
又以左羽林衞大將軍 rm#r05984@閻敬容 爲 dm#dm01717@天兵西道 後軍總管，
將兵十五萬爲後援。
# p 

癸丑，
 rm@默啜 寇 dm#dm08780@飛狐 ，
乙卯，
陷 dm#dm02124@定州 ，
殺刺史 rm#r05161@孫彦高 及吏民數千人。

# p 

九月，
甲子，
以夏官尚書 rm#r06225@武攸寧 同鳳閣鸞臺三品。
# p 

改 rm@默啜 爲 rm@斬啜 。
突厥
# p 

 rm@默啜 使 rm#r03888@閻知微 招諭 dm#dm07623@趙州 ，
 rm#r03888@知微 與虜連手蹋萬歳樂於城下。

將軍 rm#r06004@陳令英 在城上謂曰：
「尚書位任非輕，
乃爲虜蹋歌，
獨無慙乎！」

 rm#r03888@知微 微吟曰：
「不得已，
萬歳樂。」

歌
# p 

戊辰，
 rm@默啜 圍 dm#dm07623@趙州 ，
長史 rm@唐般若 翻城應之。

刺史 rm#r04222@高叡 與妻 rm#r02971@秦氏 仰藥詐死，
虜輿之詣 rm@默啜 ，
 rm@默啜 以金獅子帶、紫袍示之曰：
「降則拜官，
不降則死！」

 rm#r04222@叡 顧其妻，
妻曰：
「酬報國恩，
正在今日！」

遂倶閉目不言。

經再宿，
虜知不可屈，
乃殺之。

虜退，
 rm@唐般若 族誅；
贈 rm#r04222@叡 冬官尚書，
諡曰 rm#r04222@節 。

 rm#r04222@叡 ，
 rm#r06109@熲 之孫也。

# p 

皇嗣固請遜位於 rm#r01656@廬陵王 ，
太后許之。

壬申，
立 rm#r01656@廬陵王哲 爲皇太子，
復名 rm#r01656@顯 。

赦天下。
# p 

甲戌，
命太子爲 dm#dm04658@河北道 元帥以討突厥。

先是，
募人月餘不滿千人，
及聞太子爲元帥，
應募者雲集，
未幾，
數盈五萬。

# p 

戊寅，
以 rm#r02567@狄仁傑 爲 dm#dm04658@河北道 行軍副元帥，
右丞 rm#r05184@宋元爽 爲長史，
右臺中丞 rm#r05224@崔獻 爲司馬，
左臺中丞 rm#r00398@吉頊 爲監軍使。

時太子不行，
命 rm#r02567@仁傑 知元帥事，
太后親送之。
# p 

 dm#dm07121@藍田 令 rm#r03313@薛訥 ，
 rm#r03268@仁貴 之子也，
太后擢爲左威衞將軍、 dm#dm02034@安東道 經略。

將行，
言於太后曰：
「太子雖立，
外議猶疑未定；
苟此命不易，
醜虜不足平也。」

太后深然之。

 rm@王及善 請太子赴外朝以慰人心，
從之。

# p 

以天官侍郎 rm#r03329@蘇味道 爲鳳閣侍郎、同平章事。

 rm#r03329@味道 前後在相位數歳，
依阿取容，
嘗謂人曰：
「處事不宜明白，
但摸稜持兩端可矣。」

時人謂之「 rm#r05829@蘇摸稜 」。

# p 

癸未，
突厥 rm@默啜 盡殺所掠 dm#dm07617@趙 、 dm#dm02116@定 等州男女萬餘人，
自 dm#dm00377@五囘 道去，
所過，
殺掠不可勝紀。

 rm#xjts12733@沙吒忠義 等但引兵躡之，
不敢逼。

 rm#r02567@狄仁傑 將兵十萬追之，
無所及。

 rm@默啜 還漠北，
擁兵四十萬，
據地萬里，
西北諸夷皆附之，
甚有輕 dm#dm00255@中國 之心。
# p 

冬，
十月，
制：
都下屯兵，
命河内王武懿宗、九江王武攸歸領之。
# p 

癸卯，
以 rm#r02567@狄仁傑 爲 dm#dm04658@河北道 安撫大使。

時 dm#dm00829@北 人爲突厥所驅逼者，
虜退，
懼誅，
往往亡匿。

 rm#r02567@仁傑 上疏，
以爲：
「朝廷議者皆罪契丹、突厥所脅從之人，
言其迹雖不同，
心則無別。

誠以 dm#dm02403@山東 近縁軍機調發傷重，
家道悉破，
或至逃亡。

重以官典侵漁，
因事而起，
枷杖之下，
痛切肌膚，
事迫情危，
不循禮義。

愁苦之地，
不樂其生，
有利則歸，
且圖賖死，
此乃君子之愧辱，
小人之常行也。

又，
諸城入僞，
或待天兵，
將士求功，
皆云攻得，
臣憂濫賞，
亦恐非辜。

以經與賊同，
是爲惡地，
至於污辱妻子，
劫掠貨財，
兵士信知不仁，
簪笏未能以免，
乃是賊平之後，
爲惡更深。

且賊務招攜，
秋毫不犯，
今之歸正，
即是平人，
翻被破傷，
豈不悲痛！

夫人猶水也，
壅之則爲泉，
疏之則爲川，
通塞隨流，
豈有常性！

今負罪之伍，
必不在家，
露宿草行，
潛竄山澤，
赦之則出，
不赦則狂，
 dm#dm02403@山東 羣盜，
縁茲聚結。

臣以邊塵蹔起，
不足爲憂，
中土不安，
此爲大事。

罪之則衆情恐懼，
恕之則反側自安，
伏願曲赦 dm#dm04656@河北 諸州，
一無所問。」

制從之。

 rm#r02567@仁傑 於是撫慰百姓，
得突厥所驅掠者，
悉遞還本貫。

散糧運以賑貧乏，
修郵驛以濟旋師。

恐諸將及使者妄求供頓，
乃自食疏糲，
禁其下無得侵擾百姓，
犯者必斬。

 dm#dm04656@河北 遂安。

河
# p 

以夏官侍郎 rm#r00627@姚元崇 、祕書少監 rm#r01714@李嶠 竝同平章事。
# p 

突厥 rm@默啜 離 dm#dm07623@趙州 ，
乃縱 rm#r03888@閻知微 使還。

太后命磔於 dm#dm01750@天津橋 南，
使百官共射之，
既乃其肉，
剉其骨，
夷其三族，
疏親有先未相識而同死者。

# p 

 rm@褒公  rm#r02348@段瓚 ，
 rm#r02342@志玄 之子也，
先沒於突厥。

突厥在 dm#dm07623@趙州 ，
 rm#r02348@瓚 邀 rm#r05520@楊齊莊 與之倶逃，
 rm#r05520@齊莊 畏懦，
不敢發。

 rm#r02348@瓚 先歸，
太后賞之。

 rm#r05520@齊莊 尋至，
敕 rm#r02313@河内王  rm#r02313@武懿宗 鞫之；
 rm#r02313@懿宗 以爲 rm#r05520@齊莊 意懷猶豫，
遂與 rm#r03888@閻知微 同誅。

既射之如蝟，
氣殜殜未死，
乃決其腹，
割心，
投於地，
猶趌趌然躍不止。

# p 

擢 rm#r02822@田歸道 爲夏官侍郎，
甚見親委。
# p 

 dm#dm07202@蜀州 毎歳遣兵五百人戍 dm#dm01898@姚州 ，
路險遠，
死亡者多。

 dm#dm07202@蜀州 刺史 rm#r01188@張柬之 上言，
以爲：
「 dm#dm01898@姚州 本哀牢之國，
荒外絶域，
山高水深。

國家開以爲州，
未嘗得其鹽布之税，
甲兵之用，
而空竭府庫，
驅率平人，
受役蠻夷，
肝腦塗地，
臣竊爲國家惜之。

請廢 dm#dm01898@姚州 以隸 dm#dm02536@巂州 ，
歳時朝覲，
同之蕃國。

 dm#dm05469@瀘 南諸鎭亦皆廢省，
於 dm#dm05469@瀘 北置關，
百姓非奉使，
無得交通往來。」

疏奏，
不納。
*** 二年
# year 0699
# p 

正月，
丁卯朔，
告朔於 dm#dm07688@通天宮 。

# p 

壬戌，
以皇嗣爲 rm@相王 ，
領太子右衞率。

# p 

甲子，
置控鶴監丞、主簿等官，
率皆嬖寵之人，
頗用才能文學之士以參之。

以司衞卿 rm#r01178@張易之 爲控鶴監，
銀青光祿大夫 rm#r01176@張昌宗 、左臺中丞 rm#r00398@吉頊 、殿中監 rm#r02822@田歸道 、夏官侍郎 rm#r01983@李迥秀 、鳳閣舍人 rm#r03305@薛稷 、正諫大夫 dm#dm06678@臨汾  rm#rx0071@員半千 皆爲控鶴監内供奉。

 rm#r03305@稷 ，
 rm#r03274@元超 之從子也。

 rm#rx0071@半千 以古無此官，
且所聚多輕薄之士，
上疏請罷之；
由是忤旨，
左遷水部郎中。
# p 

臘月，
戊子，
以左臺中丞 rm#r00398@吉頊 爲天官侍郎，
右臺中丞 rm#r04302@魏元忠 爲鳳閣侍郎，
竝同平章事。
# p 

文昌左丞 rm#r00825@宗楚客 與弟司農卿 rm#r00824@晉卿 ，
坐贓賄滿萬餘緡及第舍過度，
 rm#r00825@楚客 貶 dm#dm03267@播州 司馬，
 rm#r00824@晉卿 流 dm#dm00006@峯州 。

 rm#r00603@太平公主 觀其第，
歎曰：
「見其居處，
吾輩乃虚生耳。」

# p 

辛亥，
賜太子姓 rm#r02293@武氏 ；
赦天下。
# p 

太后生重眉，
成八字，
百官皆賀。
# p 

 dm#dm04660@河南 、 dm#dm00829@北 置武騎團以備突厥。

# p 

春，
一月，
庚申，
夏官尚書、同鳳閣鸞臺三品 rm#r06225@武攸寧 罷爲冬官尚書。
# p 

二月，
己丑，
太后幸 dm#dm02514@嵩山 ，
過 dm#dm06469@緱氏 ，
謁 dm#dm00923@升仙太子廟 。

壬辰，
太后不豫，
遣給事中 dm#dm04202@欒城  rm#r03884@閻朝隱 祷 dm#dm02372@少室山 。

 rm#r03884@朝隱 自爲犧牲，
沐浴伏俎上，
請代太后命。

太后疾小愈，
厚賞之。

丁酉，
自 dm#dm06469@緱氏 還。
# p 

初，
吐蕃贊普 rm#xjts24697@器弩悉弄 尚幼，
 rm#xjts01678@論欽陵 兄弟用事，
皆有勇略，
諸胡畏之。

 rm#xjts01678@欽陵 居中秉政，
諸弟握兵分據方面，
 rm#r05866@贊婆 常居東邊，
爲 dm#dm00255@中國 患者三十餘年。

 rm#xjts24697@器弩悉弄 浸長，
陰與大臣 rm#r05865@論巖 謀誅之。

會 rm#xjts01678@欽陵 出外，
贊普詐云出畋，
集兵執 rm#xjts01678@欽陵 親黨二千餘人，
殺之，
遣使召 rm#xjts01678@欽陵 兄弟，
 rm#xjts01678@欽陵 等舉兵不受命。

贊普將兵討之，
 rm#xjts01678@欽陵 兵潰，
自殺。

夏四月，
 rm#r05866@贊婆 帥所部千餘人來降，
太后命左武衞鎧曹參軍 rm#r03747@郭元振 與 dm#dm04691@河源軍 大使 rm#xjts23952@夫蒙令卿 將騎迎之，
以 rm#r05866@贊婆 爲特進、 rm#r05866@歸徳王 。

 rm#xjts01678@欽陵 子 rm#r03529@弓仁 ，
以所統吐谷渾七千帳來降，
拜左玉鈐衞將軍、酒泉郡公。
# p 

壬辰，
以 rm#r04302@魏元忠 檢校 dm#dm00059@幷州 長史，
充 dm#dm01718@天兵軍 大總管，
以備突厥。
# p 

 rm#r00657@婁師徳 爲 dm#dm01718@天兵軍 副大總管，
仍充 dm#dm08458@隴右 諸軍大使，
專掌懷撫吐蕃降者。
# p 

太后春秋高，
慮身後太子與諸 rm#no@武 不相容。

壬寅，
命太子、 rm@相王 、 rm#r00603@太平公主 與 rm#r02317@武攸曁 等爲誓文，
告天地於明堂，
銘之鐵券，
藏于史館。
# p 

秋，
七月，
命 rm#r06224@建安王武攸宜 留守 dm#dm07290@西京 ，
代 rm#xjts06534@會稽王武攸望 。

# p 

丙辰，
吐谷渾部落一千四百帳内附。


# p 

八月，
癸巳，
突騎施烏質勒遣其子 rm@遮弩 入見。

遣侍御史 dm#dm00634@元城  rm#r03492@解琬 安撫烏質勒及十姓部落。

# p 

制：
「州縣長吏，
非奉有敕旨，
毋得立碑。」


# p 

内史 rm@王及善 雖無學術，
然清正難奪，
有大臣之節。

 rm#r01178@張易之 兄弟毎侍内宴，
無復人臣禮；
 rm@及善 屡奏以爲不可。

太后不悦，
謂 rm@及善 曰：
「卿既年高，
不宜更侍遊宴，
但檢校閤中可也。」

 rm@及善 因稱病，
謁假月餘；
太后不問。

 rm@及善 歎曰：
「豈有中書令而天子可一日不見乎！

事可知矣！」

乃上疏乞骸骨，
太后不許。

庚子，
以 rm@及善 爲文昌左相，
太子宮尹 rm#r03546@豆盧欽望 爲文昌右相，
仍竝同鳳閣鸞臺三品。

鸞臺侍郎、同平章事 rm#r02155@楊再思 罷爲左臺大夫。

丁未，
 rm@相王 兼檢校 dm#dm01976@安北 大都護。

以天官侍郎 rm#r03943@陸元方 爲鸞臺侍郎、同平章事。
# p 

納言、 dm#dm08458@隴右 諸軍大使 rm#r00657@婁師徳 薨。

# p 

 rm#r00657@師徳 在 dm#dm04716@河隴 ，
前後四十餘年，
恭勤不怠，
民夷安之。

性沈厚寛恕，
 rm#r02567@狄仁傑 之入相也，
 rm#r00657@師徳 實薦之；
而 rm#r02567@仁傑 不知，
意頗輕 rm#r00657@師徳 ，
數擠之於外。

太后覺之，
嘗問 rm#r02567@仁傑 曰：
「 rm#r00657@師徳 賢乎？」
對曰：
「爲將能謹守邊陲，
賢則臣不知。」

又曰：
「 rm#r00657@師徳 知人乎？」
對曰：
「臣嘗同僚，
未聞其知人也。」

太后曰：
「朕之知卿，
乃 rm#r00657@師徳 所薦也，
亦可謂知人矣。」

 rm#r02567@仁傑 既出，
歎曰：
「 rm#r00657@婁公 盛徳，
我爲其所包容久矣，
吾不得窺其際也。」

是時羅織紛紜，
師徳久爲將相，
獨能以功名終，
人以是重之。
# p 

戊申，
以 rm#r02294@武三思 爲内史。
# p 

九月，
乙亥，
太后幸 dm#dm06252@福昌 ；
戊寅，
還 dm#dm06235@神都 。
# p 

庚子，
 rm@邢貞公王及善 薨。
# p 

 dm#dm04650@河 溢，
漂 dm#dm05442@濟源 百姓廬舍千餘家。

# p 

冬，
十月，
丁亥，
 rm#r05866@論贊婆 至都，
太后寵待賞賜甚厚，
以爲右衞大將軍，
使將其衆守 dm#dm04810@洪源谷 。

# p 

太子、 rm@相王 諸子復出閤。

# p 

太后自稱制以來，
多以 rm#r02293@武氏 諸王及駙馬都尉爲成均祭酒，
博士、助教亦多非儒士。

又因郊丘，
明堂，
拜 dm#dm04761@洛 ，
封 dm#dm02513@嵩 ，
取 dm#dm02885@弘文 國子生爲齋郎，
因得選補。

由是學生不復習業，
二十年間，
學校殆廢。

而曏時酷吏所誣陷者，
其親友流離，
未獲原宥。

鳳閣舍人 rm#r04015@韋嗣立 上疏，
以爲：
「時俗浸輕儒學，
先王之道，
弛廢不講。

宜令王公以下子弟，
皆入國學，
不聽以他岐仕進。

又，
自 dm#dm03240@揚 、 dm#dm07502@豫 以來，
制獄漸繁，
酷吏乘間，
專欲殺人以求進。

頼陛下聖明，
 rm#r00116@周 、 rm#r00031@丘 、 rm#r02627@王 、 rm#r00115@來 相繼誅殛，
朝野慶泰，
若再覩陽和。

至如 rm#r02567@仁傑 、 rm#r04302@元忠 ，
往遭按鞫，
亦皆自誣，
非陛下明察，
則以爲葅醢矣；
今陛下升而用之，
皆爲良輔。

何乃前非而後是哉？
誠由枉陷與甄明耳。

臣恐曏之負冤得罪者甚衆，
亦皆如是。

伏望陛下弘天地之仁，
廣雷雨之施，
自 y@垂拱 以來，
罪無輕重，
一皆昭洗，
死者追復官爵，
生者聽還郷里。

如此，
則天下知昔之枉濫，
非陛下之意，
皆獄吏之辜，
幽明歡欣，
感通和氣。」

太后不能從。
# p 

 rm#r04015@嗣立 ，
 rm#r04034@承慶 之異母弟也。

母 rm#r02658@王氏 ，
遇 rm#r04034@承慶 甚酷，
毎杖 rm#r04034@承慶 ，
 rm#r04015@嗣立 必解衣請代；
母不許，
輒私自杖，
母乃爲之漸寛。

 rm#r04034@承慶 爲鳳閣舍人，
以疾去職。

 rm#r04015@嗣立 時爲 dm#dm06955@莱蕪 令，
太后召謂曰：
「卿父嘗言，
『臣有兩兒，
堪事陛下。』

卿兄弟在官，
誠如父言。

朕今以卿代兄，
更不用他人。」

即日拜鳳閣舍人。
# p 

是歳，
突厥 rm#xjts24609@默啜 立其弟 rm#xjts24602@咄悉匐 爲左廂察，
 rm#r06002@骨篤祿 子 rm#xjts24610@默矩 爲右廂察，
各主兵二萬餘人；
其子 rm#xjts10645@匐倶 爲小可汗，
位在兩察上，
主處木昆等十姓，
兵四萬餘人，
又號爲 rm#xjts10645@拓西可汗 。

*** 三年
# year 0700
# p 

正月，
戊寅，
内史 rm#r02294@武三思 罷爲特進、太子少保。

天官侍郎、同平章事 rm#r00398@吉頊 貶 dm#dm01993@安固 尉。


# p 

太后以 rm#r00398@頊 有幹略，
故委以腹心。

 rm#r00398@頊 與 rm#r02313@武懿宗 爭 dm#dm07623@趙州 之功於太后前。

 rm#r00398@頊 魁岸辯口，
 rm#r01367@懿宗 短小傴僂，
 rm#r00398@頊 視 rm#r01367@懿宗 ，
聲氣陵厲。

太后由是不悦，
曰：
「 rm#r00398@頊 在朕前，
猶卑我諸 rm#no@武 ，
況異時詎可倚邪！」

他日，
 rm#r00398@頊 奏事，
方援古引今，
太后怒曰：
「卿所言，
朕飫聞之，
無多言！

 rm#r01602@太宗 有馬名師子驄，
肥逸無能調馭者。

朕爲宮女侍側，
言於太宗曰：
『妾能制之，
然須三物，
一鐵鞭，
二鐵檛，
三匕首。

鐵鞭撃之不服，
則以檛檛其首，
又不服，
則以匕首斷其喉。』

太宗壯朕之志。

今日卿豈足汚朕匕首邪！」

頊惶懼流汗，
拜伏求生，
乃止。

諸 rm#no@武 怨其附太子，
共發其弟冒官事，
由是坐貶。
# p 

辭日，
得召見，
涕泣言曰：
「臣今遠離闕庭，
永無再見之期，
願陳一言。」

太后命之坐，
問之，
 rm#r00398@頊 曰：
「合水土爲泥，
有爭乎？」
太后曰：
「無之。」

又曰：
「分半爲佛，
半爲天尊，
有爭乎？」
曰：
「有爭矣。」

 rm#r00398@頊 頓首曰：
「宗室、外戚各當其分，
則天下安。

今太子已立而外戚猶爲王，
此陛下驅之使他日必爭，
兩不得安也。」

太后曰：
「朕亦知之。

然業已如是，
不可何如。」


# p 

臘月，
辛巳，
立故太孫 rm#r03834@重潤 爲 rm#r03834@邵王 ，
其弟 rm#r03836@重茂 爲 rm#r03836@北海王 。
# p 

太后問鸞臺侍郎 rm#r03943@陸元方 以外事，
對曰：
「臣備位宰相，
有大事不敢以不聞；
人間細事，
不足煩聖聽。」

由是忤旨。

庚寅，
罷爲司禮卿。
同平章事
# p 

 rm#r03943@元方 爲人清謹，
再爲宰相，
太后毎有遷除，
多訪之，
 rm#r03943@元方 密封以進，
未嘗漏露。

臨終，
悉取奏藁焚之，
曰：
「吾於人多陰徳，
子孫其未衰乎！」

# p 

以西突厥 rm@竭忠事主可汗  rm@斛瑟羅 爲 dm#dm02666@平西軍 大總管，
鎭 dm#dm06162@碎葉 。
# p 

丁酉，
以 rm#r02567@狄仁傑 爲内史。
# p 

庚子，
以文昌左丞 rm#r04023@韋巨源 爲納言。

# p 

乙巳，
太后幸 dm#dm02514@嵩山 ；
春，
一月，
丁卯，
幸 dm#dm04465@汝州 之温湯；
戊寅，
還 dm#dm06235@神都 。

作 dm#dm00151@三陽宮 於 dm#dm01300@告成 之 dm#dm06110@石淙 。

# p 

二月，
乙未，
同鳳閣鸞臺三品 rm#r03546@豆盧欽望 罷爲太子賓客。


# p 

三月，
以吐谷渾 rm#?@青海王宣超 爲 rm@烏地也拔勤忠可汗 。

# p 

夏，
四月，
戊申，
太后幸 dm#dm00151@三陽宮 避暑，
有胡僧邀車駕觀葬舍利，
太后許之。

 rm#r02567@狄仁傑 跪於馬前曰：
「佛者夷狄之神，
不足以屈天下之主。

彼胡僧詭譎，
直欲邀致萬乘以惑遠近之人耳。

山路險狹，
不容侍衞，
非萬乘所宜臨也。」

太后中道而還曰：
「以成吾直臣之氣。」

** 久視
*** 久視元年
# year 0700
# p 

五月，
己酉朔，
日有食之。
# p 

太后使 dm#dm04806@洪州 僧 rm#r05752@胡超 合長生藥，
三年而成，
所費巨萬。

太后服之，
疾小瘳。

癸丑，
赦天下，
改元 y@久視 ；
去 rm#r02293@天册金輪大聖 之號。

# p 

六月，
改控鶴爲奉宸府，
以 rm#r01178@張易之 爲奉宸令。

太后毎内殿曲宴，
輒引諸 rm#no@武 、 rm#r01178@易之 及弟祕書監 rm#r01176@昌宗 飮博嘲謔。

太后欲掩其迹，
乃命 rm#r01178@易之 、 rm#r01176@昌宗 與文學之士 rm#r01714@李嶠 等修三教珠英於内殿。

 rm#r02294@武三思 奏 rm#r01176@昌宗 乃 rm#r05614@王子晉 後身。

太后命 rm#r01176@昌宗 衣羽衣，
吹笙，
乘木鶴於庭中；
文士皆賦詩以美之。

# p 

太后又多選美少年爲奉宸内供奉，
右補闕 rm#r01572@朱敬則 諫曰：
「陛下内寵有 rm#r01178@易之 、 rm#r01176@昌宗 ，
足矣。

近聞右監門衞長史 rm#r05036@侯祥 等，
明自媒衒，
醜慢不恥，
求爲奉宸内供奉，
無禮無儀，
溢于朝聽。

臣職在諫諍，
不敢不奏。」

太后勞之曰：
「非卿直言，
朕不知此。

」
賜綵百段。
# p 

 rm#r01178@易之 、 rm#r01176@昌宗 競以豪侈相勝。

弟 rm@昌儀 爲 dm#dm04788@洛陽 令，
請屬無不從。

嘗早朝，
有選人姓 rm@薛 ，
以金五十兩幷状邀其馬而賂之。

 rm@昌儀 受金，
至朝堂，
以状授天官侍郎 rm#r01263@張錫 。

數日，
 rm#r01263@錫 失其状，
以問 rm@昌儀 ，
 rm@昌儀 罵曰：
「不了事人！

我亦不記，
但姓 rm#no@薛 者即與之。」

 rm#r01263@錫 懼，
退，
索在銓姓 rm#no@薛 者六十餘人，
悉留注官。

 rm#r01263@錫 ，
 rm#r01169@文瓘 之兄子也。

# p 

初，
契丹將 rm#r05408@李楷固 ，
善用䌈索及騎射、舞槊，
毎陷陳，
如鶻入烏羣，
所向披靡。

 dm#dm09108@黄麞 之戰，
 rm#r06186@張玄遇 、 rm#r06133@麻仁節 皆爲所䌈。

又有 rm#r06092@駱務整 者，
亦爲契丹將，
屡敗 dyn#ch100@唐 兵。

及 rm#r01945@孫萬榮 死，
二人皆來降。

有司責其後至，
奏請族之。

 rm#r02567@狄仁傑 曰：
「 rm#r05408@楷固 等竝驍勇絶倫，
能盡力於所事，
必能盡力於我，
若撫之以徳，
皆爲我用矣。」

奏請赦之。

所親皆止之，
 rm#r02567@仁傑 曰：
「苟利於國，
豈爲身謀！」

太后用其言，
赦之。

又請與之官，
太后以 rm#r05408@楷固 爲左玉鈐衞將軍，
 rm#r06092@務整 爲右武威衞將軍，
使將兵撃契丹餘黨，
悉平之。
# p 

秋，
七月，
獻俘於 dm#dm01272@含樞殿 。

太后以 rm#r05408@楷固 爲左玉鈐衞大將軍、 rm@燕國公 ，
賜姓 rm#r02293@武氏 。

召公卿合宴，
舉觴屬 rm#r02567@仁傑 曰：
「公之功也。」

將賞之，
對曰：
「此乃陛下威靈，
將帥盡力，
臣何功之有！」

固辭不受。
# p 

閏月，
戊寅，
車駕還宮。

# p 

己丑，
以天官侍郎 rm#r01263@張錫 爲鳳閣侍郎、同平章事。

鸞臺侍郎、同平章事 rm#r01714@李嶠 罷爲成均祭酒。

 rm#r01263@錫 ，
 rm#r01714@嶠 之舅也，
故罷 rm#r01714@嶠 政事。


# p 

丁酉，
吐蕃將 rm@麹莽布支 寇 dm#dm04947@涼州 ，
圍 dm#dm03468@昌松 ，
 dm#dm08458@隴右 諸軍大使 rm#r00488@唐休璟 與戰於 dm#dm05126@港源谷 。

 rm@麹莽布支 兵甲鮮華，
 rm#r00488@休璟 謂諸將曰：
「諸論既死，
 rm@麹莽布支 新爲將，
不習軍事，
望之雖如精鋭，
實易與耳，
請爲諸君破之。」

乃被甲先陷陳，
六戰皆捷，
吐蕃大奔，
斬首二千五百級，
獲二裨將而還。
港洪諸貴臣子弟皆從之
# p 

司府少卿 rm#r02149@楊元亨 ，
尚食奉御 rm#r02152@楊元禧 ，
皆 rm#r02177@弘武 之子也。

 rm#r02152@元禧 嘗忤 rm#r01178@張易之 ，
 rm#r01178@易之 言於太后：
「 rm#r02152@元禧 ，
 rm#r03595@楊素 之族；
 rm#r03595@素 父子，
 dyn#ch174@隋 之逆臣，
子孫不應供奉。」

太后從之，
壬寅，
制：
「 rm#r03595@楊素 及其兄弟子孫皆不得任京官。」

左遷 rm#r02149@元亨  dm#dm06059@睦州 刺史，
 rm#r02152@元禧  dm#dm07514@貝州 刺史。
貝資
# p 

庚戌，
以 rm#r04302@魏元忠 爲 dm#dm08458@隴右 諸軍大使，
撃吐蕃。
# p 

庚申，
太后欲造大像，
使天下僧尼日出一錢以助其功。

 rm#r02567@狄仁傑 上疏諫，
其略曰：
「今之伽藍，
制過宮闕。

功不使鬼，
止在役人，
物不天來，
終須地出，
不損百姓，
將何以求！」

又曰：
「游僧皆託佛法，
詿誤生人；
里陌動有經坊，
闤闠亦立精舍。

化誘所急，
切於官徵；
法事所須，
嚴於制敕。」

又曰：
「 rm#rt0704@梁武 、 rm#rt0705@簡文 捨施無限，
及 dm#dm00138@三淮 沸浪，
 dm#dm00381@五嶺 騰煙，
列刹盈衢，
無救危亡之禍，
緇衣蔽路，
豈有勤王之師！」

又曰：
「雖斂僧錢，
百未支一。

尊容既廣，
不可露居，
覆以百層，
尚憂未遍，
自餘廊宇，
不得全無。

如來設教，
以慈悲爲主，
豈欲勞人，
以存虚飾！」

又曰：
「比來水旱不節，
當今邊境未寧，
若費官財，
又盡人力，
一隅有難，
將何以救之！」

太后曰：
「公教朕爲善，
何得相違！」

遂罷其役。
# p 

 rm@阿悉吉薄露 叛，
遣左金吾將軍 rm#r05675@田揚名 、殿中侍御史 rm#r05195@封思業 討之。

軍至 dm#dm06162@碎葉 ，
 rm@薄露 夜於城傍剽掠而去，
 rm#r05195@思業 將騎追之，
反爲所敗。

 rm#r05675@揚名 引西突厥 rm@斛瑟羅 之衆攻其城，
旬餘，
不克。

九月，
 rm@薄露 詐降，
 rm#r05195@思業 誘而斬之，
遂俘其衆。
# p 

太后信重内史 rm@梁文惠公  rm#r02567@狄仁傑 ，
羣臣莫及，
常謂之國老而不名。

 rm#r02567@仁傑 好面引廷爭，
太后毎屈意從之。

嘗從太后遊幸，
遇風吹 rm#r02567@仁傑 巾墜，
而馬驚不能止，
太后命太子追執其鞚而繋之。

 rm#r02567@仁傑 屡以老疾乞骸骨，
太后不許。

入見，
常止其拜，
曰：
「毎見公拜，
朕亦身痛。」

仍免其宿直，
戒其同僚曰：
「自非軍國大事，
勿以煩公。」

辛丑，
薨，
太后泣曰：
「朝堂空矣！」

自是朝廷有大事，
衆或不能決，
太后輒歎曰：
「天奪吾國老何太早邪！」

# p 

太后嘗問 rm#r02567@仁傑 ：
「朕欲得一佳士用之，
誰可者？」
 rm#r02567@仁傑 曰：
「未審陛下欲何所用之？」
太后曰：
「欲用爲將相。」

 rm#r02567@仁傑 對曰：
「文學縕藉，
則 rm#r03329@蘇味道 、 rm#r01714@李嶠 固其選矣。

必欲取卓犖奇才，
則有 dm#dm06884@荊州 長史 rm#r01188@張柬之 ，
其人雖老，
宰相才也。」

太后擢 rm#r01188@柬之 爲 dm#dm04778@洛州 司馬。

數日，
又問 rm#r02567@仁傑 ，
對曰：
「前薦 rm#r01188@柬之 ，
尚未用也。」

太后曰：
「已遷矣。」

對曰：
「臣所薦者可爲宰相，
非司馬也。」

乃遷秋官侍郎；
久之，
卒用爲相。

 rm#r02567@仁傑 又嘗薦夏官侍郎 rm#r00627@姚元崇 、監察御史 dm#dm03629@曲阿  rm#r02120@桓彦範 、 dm#dm01791@太州 刺史 rm#r01407@敬暉 等數十人，
率爲名臣。

或謂 rm#r02567@仁傑 曰：
「天下桃李，
悉在公門矣。」

 rm#r02567@仁傑 曰：
「薦賢爲國，
非爲私也。」


# p 

初，
 rm#r02567@仁傑 爲 dm#dm08950@魏州 刺史，
有惠政，
百姓爲之立生祠。

後其子 rm@景暉 爲 dm#dm08950@魏州 司功參軍，
貪暴爲人患，
人遂毀其像焉。

# p 

冬，
十月，
辛亥，
以 rm#r04302@魏元忠 爲 dm#dm07100@蕭關道 大總管，
以備突厥。

# p 

甲寅，
制復以正月爲十一月，
一月爲正月。

赦天下。
# p 

丁巳，
納言 rm#r04023@韋巨源 罷，
以文昌右丞 rm#r04019@韋安石 爲鸞臺侍郎、同平章事。

 rm#r04019@安石 ，
 rm#r06841@津 之孫也。

# p 

時 rm#r02294@武三思 、 rm#r01178@張易之 兄弟用事，
 rm#r04019@安石 數面折之。

嘗侍宴禁中，
 rm#r01178@易之 引 dm#dm07197@蜀 商 rm#xjts11886@宋霸子 等數人在座同博。

 rm#r04019@安石 跪奏曰：
「商賈賤類，
不應得預此會。」

顧左右逐出之，
座中皆失色；
太后以其言直，
勞勉之，
同列皆歎服。

# p 

丁卯，
太后幸 dm#dm03337@新安 ；
壬申，
還宮。

# p 

十二月，
甲寅，
突厥掠 dm#dm08458@隴右 諸監馬萬餘匹而去。

# p 

時屠禁尚未解，
鳳閣舍人 dm#dm00679@全節  rm#r00990@崔融 上言，
以爲「割烹犧牲，
弋獵禽獸，
聖人著之典禮，
不可廢闕。

又，
 dm#dm04476@江南 食魚，
 dm#dm04695@河西 食肉，
一日不可無；
富者未革，
貧者難堪。

況貧賤之人，
仰屠爲生，
日戮一人，
終不能絶，
但資恐喝，
徒長姦欺。

爲政者苟順月令，
合禮經，
自然物遂其生，
人得其性矣。」

戊午，
復開屠禁，
祠祭用牲牢如故。
** 大足
*** 大足元年
# year 0701
# p 

春，
正月，
丁丑，
以 dm#dm03135@成州 言佛迹見，
改元 y@大足 。

# p 

二月，
己酉，
以鸞臺侍郎 dm#dm03944@柏人  rm#r01777@李懷遠 同平章事。

# p 

三月，
鳳閣侍郎、同平章事 rm#r01263@張錫 坐知選漏泄禁中語、贓滿數萬，
當斬，
臨刑釋之，
流 dm#dm02972@循州 。

時 rm#r03329@蘇味道 亦坐事與 rm#r01263@錫 倶下司刑獄，
 rm#r01263@錫 乘馬，
意氣自若，
舍于三品院，
帷屏食飮，
無異平居。

 rm#r03329@味道 歩至繋所，
席地而臥，
蔬食而已。

太后聞之，
赦 rm#r03329@味道 ，
復其位。
# p 

是月，
大雪，
 rm#r03329@蘇味道 以爲瑞，
帥百官入賀。

殿中侍御史 rm#r02659@王求禮 止之曰：
「三月雪爲瑞雪，
臘月雷爲瑞雷乎？」
 rm#r03329@味道 不從。

既入，
 rm#r02659@求禮 獨不賀，
進言曰：
「今陽和布氣，
草木發榮，
而寒雪爲災，
豈得誣以爲瑞！

賀者皆諂諛之士也。

」
太后爲之罷朝。

# p 

時又有獻三足牛者，
宰相復賀。

 rm#r02659@求禮 颺言曰：
「凡物反常皆爲妖。

此鼎足非其人，
政教不行之象也。」

太后爲之愀然。

# p 

夏，
五月，
乙亥，
太后幸 dm#dm00151@三陽宮 。
# p 

以 rm#r04302@魏元忠 爲 dm#dm08629@靈武道 行軍大總管，
以備突厥。
# p 

天官侍郎 dm#dm09050@鹽官  rm#r04156@顧琮 同平章事。

# p 

六月，
庚申，
以夏官尚書 rm#r01983@李迥秀 同平章事。
# p 

 rm#r01983@迥秀 性至孝，
其母本微賤，
妻 rm#r00885@崔氏 常叱媵婢，
母聞之不悦，
 rm#r01983@迥秀 即時出之。

或曰：
「賢室雖不避嫌疑，
然過非七出，
何遽如是？」
 rm#r01983@迥秀 曰：
「娶妻本以養親；
今乃違忤顏色，
安敢留也！」

竟出之。


# p 

秋，
七月，
甲戌，
太后還宮。
# p 

甲申，
 rm#r01777@李懷遠 罷爲秋官尚書。
# p 

八月，
突厥 rm@默啜 寇邊，
命 dm#dm01976@安北 大都護 rm@相王 爲 dm#dm01719@天兵道 元帥，
統諸軍撃之，
未行而虜退。

# p 

丙寅，
 dm#dm04306@武邑 人 rm#r03331@蘇安恆 上疏曰：
「陛下欽先聖之顧託，
受嗣子之推讓，
敬天順人，
二十年矣。

豈不聞 rm#rt0007@帝舜 褰裳，
 rm#rt0104@周公 復辟！

 rm#rt0007@舜 之於 rm#rt0008@禹 ，
事祗族親；
 rm#rt0104@旦 與 rm#rt0065@成王 ，
不離叔父。

族親何如子之愛，
叔父何如母之恩？
今太子孝敬是崇，
春秋既壯，
若使統臨宸極，
何異陛下之身！

陛下年徳既尊，
寶位將倦，
機務煩重，
浩蕩心神，
何不禪位東宮，
自怡聖體！

自昔理天下者，
不見二姓而倶王也。

當今 rm#r02294@梁 、 rm#r02317@定 、 rm#r02313@河内 、 rm#r06225@建昌 諸王，
承陛下之蔭覆，
竝得封王；
臣謂千秋萬歳之後，
於事非便，
臣請黜爲公侯，
任以閒簡。

臣又聞陛下有二十餘孫，
今無尺寸之封，
此非長久之計也；
臣請分土而王之，
擇立師傅，
教其孝敬之道，
以夾輔周室，
屏藩皇家，
斯爲美矣。」

疏奏，
太后召見，
賜食，
慰諭而遣之。
# p 

太后春秋高，
政事多委 rm#r01178@張易之 兄弟；
 rm#r03834@邵王重潤 與其妹 rm#r02386@永泰郡主 、主壻 rm#r02308@魏王武延基 竊議其事。

 rm#r01178@易之 訴於太后，
九月，
壬申，
太后皆逼令自殺。

 rm#r02308@延基 ，
 rm#r02314@承嗣 之子也。

# p 

丙申，
以 rm@相王 知左、右羽林衞大將軍事。
** 長安
*** 長安元年
# year 0701
# p 

冬，
十月，
壬寅，
太后西入 dm#dm08280@關 ，
辛酉，
至 dm#dm08170@京師 ；
赦天下，
改元。

# p 

十一月，
戊寅，
改 dm#dm01258@含元宮 爲 dm#dm01633@大明宮 。

# p 

天官侍郎 dm#dm02011@安平  rm#r00958@崔玄暐 ，
性介直，
未嘗請謁。

執政惡之，
改文昌左丞。

月餘，
太后謂 rm#r00958@玄暐 曰：
「自卿改官以來，
聞令史設齋自慶。

此欲盛爲姦貪耳；
今還卿舊任。」

乃復拜天官侍郎，
仍賜綵七十段。

# p 

以主客郎中 rm#r03747@郭元振 爲 dm#dm04947@涼州 都督、 dm#dm08458@隴右 諸軍大使。

# p 

先是，
 dm#dm04947@涼州 南北境不過四百餘里，
突厥、吐蕃頻歳奄至城下，
百姓苦之。

 rm#r03747@元振 始於南境 dm#dm06155@硤口 置 dm#dm01329@和戎城 ，
北境磧中置 dm#dm05872@白亭軍 ，
控其衝要，
拓州境千五百里，
自是寇不復至城下。

 rm#r03747@元振 又令 dm#dm05794@甘州 刺史 rm#r05414@李漢通 開置屯田，
盡水陸之利。

舊 dm#dm04947@涼州 粟麥斛至數千，
及 rm#r05414@漢通 收率之後，
一縑糴數十斛，
積軍糧支數十年。

 rm#r03747@元振 善於撫御，
在 dm#dm04947@涼州 五年，
夷、夏畏慕，
令行禁止，
牛羊被野，
路不拾遺。
*** 二年
# year 0702
# p 

春，
正月，
乙酉，
初設武舉。

# p 

突厥寇 dm#dm09056@鹽 、 dm#dm01532@夏 二州。

三月，
庚寅，
突厥破 dm#dm06091@石嶺 ，
寇 dm#dm00059@幷州 。

以 dm#dm08502@雍州 長史 rm#r03280@薛季昶 攝右臺大夫，
充 dm#dm02403@山東 防禦軍大使，
 dm#dm05208@滄 、 dm#dm05480@瀛 、 dm#dm02688@幽 、 dm#dm03494@易 、 dm#dm03017@恆 、 dm#dm02116@定 等州諸軍皆受 rm#r03280@季昶 節度。

夏，
四月，
以 dm#dm02689@幽州 刺史 rm#r01095@張仁愿 專知 dm#dm02688@幽 、 dm#dm02607@平 、 dm#dm01931@媯 、 dm#dm00056@檀 防禦，
仍與 rm#r03280@季昶 相知，
以拒突厥。


# p 

五月，
壬申，
 rm#r03331@蘇安恆 復上疏曰：
「臣聞天下者，
 rm#r04258@神堯 、 rm#r01602@文武 之天下也，
陛下雖居正統，
實因 rm@唐氏 舊基。

當今太子追迴，
年徳倶盛，
陛下貪其寶位而忘母子深恩，
將何聖顏以見 dyn#ch100@唐家 宗廟，
將何誥命以謁 rm#r01837@大帝 墳陵？
陛下何故日夜積憂，
不知鍾鳴漏盡！

臣愚以爲天意人事，
還歸 dyn#ch100@李家 。

陛下雖安天位，
殊不知物極則反，
器滿則傾。

臣何惜一朝之命而不安萬乘之國哉！」

太后亦不之罪。
# p 

乙未，
以 rm@相王 爲 dm#dm00059@幷州 牧，
充 dm#dm01979@安北道 行軍元帥，
以 rm#r04302@魏元忠 爲之副。
# p 

六月，
壬戌，
召 dm#dm06235@神都 留守 rm#r04023@韋巨源 詣 dm#dm08170@京師 ，
以副留守 rm#r01714@李嶠 代之。

# p 

秋，
七月，
甲午，
突厥寇 dm#dm00485@代州 。
# p 

司僕卿 rm#r01176@張昌宗 兄弟貴盛，
勢傾朝野。

八月，
戊午，
太子、 rm@相王 、 rm#r00603@太平公主 上表請封 rm#r01176@昌宗 爲王，
制不許；
壬戌，
又請，
乃賜爵 rm@鄴國公 。
# p 

敕：
「自今有告言 dm#dm03246@揚州 及 dm#dm07502@豫 、 dm#dm01088@博 餘黨，
一無所問，
内外官司無得爲理。」


# p 

九月，
乙丑朔，
日有食之，
不盡如鉤，
 dm#dm06235@神都 見其既。
# p 

壬申，
突厥寇 dm#dm03000@忻州 。


# p 

己卯，
吐蕃遣其臣 rm@論彌薩 來求和。

# p 

庚辰，
以太子賓客 rm#r02294@武三思 爲 dm#dm01684@大谷道 大總管，
 dm#dm04778@洛州 長史敬暉爲副；
辛巳，
又以 rm#r01797@相王旦 爲 dm#dm00060@幷州道 元帥，
 rm#r02294@三思 與 rm#r06224@武攸宜 、 rm#r04302@魏元忠 爲之副；
 rm#r00627@姚元崇 爲長史，
司禮少卿 rm#r03798@鄭杲 爲司馬；
然竟不行。
# p 

癸未，
宴 rm#xjts01635@論彌薩 於 dm#dm09095@麟徳殿 。

時 dm#dm04947@涼州 都督 rm#r00488@唐休璟 入朝，
亦預宴。

 rm#xjts01635@彌薩 屡窺之。

太后問其故，
對曰：
「 dm#dm04809@洪源 之戰，
此將軍猛厲無敵，
故欲識之。」

太后擢 rm#r00488@休璟 爲右武威、金吾二衞大將軍。

 rm#r00488@休璟 練習邊事，
自 dm#dm06169@碣石 以西踰 dm#dm01437@四鎭 ，
緜亙萬里，
山川要害，
皆能記之。

# p 

冬，
十月，
甲辰，
天官侍郎、同平章事 rm#r04156@顧琮 薨。
# p 

戊申，
吐蕃贊普將萬餘人寇 dm#dm06857@茂州 ，
都督 rm#r06006@陳大慈 與之四戰，
皆破之，
斬首千餘級。
# p 

十一月，
辛未，
監察御史 rm#r04308@魏靖 上疏，
以爲：
「陛下既知 rm#r00115@來俊臣 之姦，
處以極法，
乞詳覆 rm#r00115@俊臣 等所推大獄，
伸其枉濫。」

太后乃命監察御史 rm#r03348@蘇頲 按覆 rm#r00115@俊臣 等舊獄，
由是雪免者甚衆。

 rm#r03348@頲 ，
 rm#r06763@夔 之曾孫也。

# p 

戊子，
太后祀南郊，
赦天下。
# p 

十二月，
甲午，
以 rm#r04302@魏元忠 爲 dm#dm02034@安東道 安撫大使，
羽林衞大將軍 rm#r01671@李多祚 檢校 dm#dm02689@幽州 都督，
右羽林衞將軍 rm#r03313@薛訥 、左武衞將軍 rm#r06092@駱務整 爲之副。
# p 

戊申，
置 dm#dm00862@北庭都護府 於 dm#dm02702@庭州 。

# p 

侍御史 rm#r05271@張循憲 爲 dm#dm04672@河東 采訪使，
有疑事不能決，
病之，
問侍吏曰：
「此有佳客，
可與議事者乎？」
吏言前 dm#dm02673@平郷 尉 dm#dm05659@猗氏  rm#r01126@張嘉貞 有異才，
 rm#r05271@循憲 召見，
詢以事；
 rm#r01126@嘉貞 爲條析理分，
莫不洗然；
 rm#r05271@循憲 因請爲奏，
皆意所未及。

 rm#r05271@循憲 還，
見太后，
太后善其奏，
 rm#r05271@循憲 具言 rm#r01126@嘉貞 所爲，
且請以己之官授之。

太后曰：
「朕寧無一官自進賢邪！」

因召 rm#r01126@嘉貞 ，
入見内殿，
與語，
大悦，
即拜監察御史；
擢 rm#r05271@循憲 司勳郎中，
賞其得人也。
*** 三年(癸卯、七０三)
# year 0703
# p 

春，
三月，
壬戌朔，
日有食之。
# p 

夏，
四月，
吐蕃遣使獻馬千匹、金二千兩以求婚。

# p 

閏月，
丁丑，
命 rm#r04019@韋安石 留守 dm#dm06235@神都 。
# p 

己卯，
改文昌臺爲中臺。

以中臺左丞 rm#r01714@李嶠 知納言事。
# p 

新羅王金理洪卒，
遣使立其弟 rm@崇基 爲王。
# p 

六月，
辛酉，
突厥 rm@默啜 遣其臣 rm@莫賀干 來，
請以女妻皇太子之子。

# p 

 dm#dm02291@寧州 大水，
溺殺二千餘人。

# p 

秋，
七月，
癸卯，
以正諫大夫 rm#r01572@朱敬則 同平章事。

# p 

戊申，
以 rm#r01797@相王  rm#r01797@旦 爲 dm#dm08502@雍州 牧。
幷州牧
# p 

庚戌，
以夏官尚書、檢校 dm#dm04947@涼州 都督 rm#r00488@唐休璟 同鳳閣鸞臺三品。

時突騎施酋長烏質勒與西突厥諸部相攻，
 dm#dm02064@安西道 絶。

太后命 rm#r00488@休璟 與諸宰相議其事，
頃之，
奏上，
太后即依其議施行。

後十餘日，
 dm#dm02061@安西 諸州請兵應接，
程期一如 rm#r00488@休璟 所畫，
太后謂 rm#r00488@休璟 曰：
「恨用卿晩。」

謂諸宰相曰：
「 rm#r00488@休璟 練習邊事，
卿曹十不當一。」

# p 

時西突厥可汗 rm@斛瑟羅 用刑殘酷，
諸部不服。

烏質勒本隸 rm@斛瑟羅 ，
號 rm@莫賀達干 ，
能撫其衆，
諸部歸之，
 rm@斛瑟羅 不能制。

烏質勒置都督二十員，
各將兵七千人，
屯 dm#dm06162@碎葉 西北；
後攻陷碎葉，
徙其牙帳居之。

 rm@斛瑟羅 部衆離散，
因入朝，
不敢復還，
烏質勒悉倂其地。
# p 

九月，
庚寅朔，
日有食之，
既。
# p 

初，
 dm#dm02556@左臺 大夫、同鳳閣鸞臺三品 rm#r04302@魏元忠 爲 dm#dm04778@洛州 長史，
 dm#dm04788@洛陽 令張昌儀恃諸兄之勢，
毎牙，
直上長史聽事；
 rm#r04302@元忠 到官，
叱下之。

 rm#r01178@張易之 奴暴亂都市，
 rm#r04302@元忠 杖殺之。

及爲相，
太后召 rm#r01178@易之 弟 dm#dm02420@岐州 刺史 rm#r05281@昌期 ，
欲以爲 dm#dm08502@雍州 長史，
對仗，
問宰相曰：
「誰堪 dm#dm08502@雍州 者？」
 rm#r04302@元忠 對曰：
「今之朝臣無以易 rm#r03280@薛季昶 。」

太后曰：
「 rm#r03280@季昶 久任 dm#dm00441@京府 ，
朕欲別除一官；
 rm#r05281@昌期 何如？」
諸相皆曰：
「陛下得人矣。」

 rm#r04302@元忠 獨曰：
「 rm#r05281@昌期 不堪！」

太后問其故，
 rm#r04302@元忠 曰：
「 rm#r05281@昌期 少年，
不閑吏事，
曏在 dm#dm02420@岐州 ，
戸口逃亡且盡。

 dm#dm08502@雍州 帝京，
事任繁劇，
不若 rm#r03280@季昶 強幹習事。」

太后默然而止。

 rm#r04302@元忠 又嘗面奏：
「臣自先帝以來，
蒙被恩渥，
今承乏宰相，
不能盡忠死節，
使小人在側，
臣之罪也！」

太后不悦。

由是諸 rm#no@張 深怨之。
# p 

司禮丞 rm#r06104@高戩 ，
 rm#r00603@太平公主 之所愛也。

會太后不豫，
 rm#r01176@張昌宗 恐太后一日晏駕，
爲 rm#r04302@元忠 所誅，
乃譖 rm#r04302@元忠 與 rm#r06104@戩 私議云：
「太后老矣，
不若挾太子爲久長。」

太后怒，
下 rm#r04302@元忠 、 rm#r06104@戩 獄，
將使與 rm#r01176@昌宗 廷辨之。

 rm#r01176@昌宗 密引鳳閣舍人 rm#r01253@張説 ，
賂以美官，
使證 rm#r04302@元忠 ；
 rm#r01253@説 許之。

明日，
太后召太子、 rm@相王 及諸宰相，
使 rm#r04302@元忠 與 rm#r01176@昌宗 參對，
往復不決。

 rm#r01176@昌宗 曰：
「 rm#r01253@張説 聞 rm#r04302@元忠 言，
請召問之。」

# p 

太后召 rm#r01253@説 。

 rm#r01253@説 將入，
鳳閣舍人 dm#dm00950@南和  rm#r00813@宋璟 謂 rm#r01253@説 曰：
「名義至重，
鬼神難欺，
不可黨邪陷正以求苟免！

若獲罪流竄，
其榮多矣。

若事有不測，
 rm#r00813@璟 當叩閤力爭，
與子同死。

努力爲之，
萬代瞻仰，
在此舉也！」

殿中侍御史 dm#dm05442@濟源  rm#r01146@張廷珪 曰：
「朝聞道，
夕死可矣！」

左史 rm#r00216@劉知幾 曰：
「無汚青史，
爲子孫累！」


# p 

及入，
太后問之，
説未對。

 rm#r04302@元忠 懼，
謂 rm#r01253@説 曰：
「 rm#r01253@張説 欲與 rm#r01176@昌宗 共羅織 rm#r04302@魏元忠 邪！」

 rm#r01253@説 叱之曰：
「 rm#r04302@元忠 爲宰相，
何乃效委巷小人之言！」

 rm#r01176@昌宗 從旁迫趣 rm#r01253@説 ，
使速言。

 rm#r01253@説 曰：
「陛下視之，
在陛下前，
猶逼臣如是，
況在外乎！

臣今對廣朝，
不敢不以實對。

臣實不聞 rm#r04302@元忠 有是言，
但 rm#r01176@昌宗 逼臣使誣證之耳！」

 rm#r01178@易之 、 rm#r01176@昌宗 遽呼曰：
「 rm#r01253@張説 與 rm#r04302@魏元忠 同反！」

太后問其状。

對曰：
「 rm#r01253@説 嘗謂 rm#r04302@元忠 爲 rm#r06152@伊 、 rm#rt0104@周 ；
 rm#r06152@伊尹 放 rm#rt0030@太甲 ，
 rm#rt0104@周公 攝王位，
非欲反而何？」
 rm#r01253@説 曰：
「 rm#r01178@易之 兄弟小人，
徒聞 rm#r06152@伊 、 rm#rt0104@周 之語，
安知 rm#r06152@伊 、 rm#rt0104@周 之道！

日者 rm#r04302@元忠 初衣紫，
臣以郎官往賀，
 rm#r04302@元忠 語客曰：
『無功受寵，
不勝慙懼。』

臣實言曰：
『明公居 rm#r06152@伊 、 rm#rt0104@周 之任，
何愧三品！』

彼 rm#r06152@伊尹 、 rm#rt0104@周公 皆爲臣至忠，
古今慕仰。

陛下用宰相，
不使學 rm#r06152@伊 、 rm#rt0104@周 ，
當使學誰邪？
且臣豈不知今日附 rm#r01176@昌宗 立取臺衡，
附 rm#r04302@元忠 立致族滅！

但臣畏 rm#r04302@元忠 冤魂，
不敢誣之耳。」

太后曰：
「 rm#r01253@張説 反覆小人，
宜幷繋治之。」

他日，
更引問 rm#r01253@説 ，
對如前。

太后怒，
命宰相與 rm#r02313@河内王  rm#r02313@武懿宗 共鞫之，
 rm#r01253@説 所執如初。
# p 

 rm#r01572@朱敬則 抗疏理之曰：
「 rm#r04302@元忠 素稱忠正，
 rm#r01253@張説 所坐無名，
若令抵罪，
失天下望。」

 rm#r03331@蘇安恆 亦上疏，
以爲：
「陛下革命之初，
人以爲納諫之主；
暮年以來，
人以爲受佞之主。

自 rm#r04302@元忠 下獄，
里巷恟恟。

皆以爲陛下委信姦宄，
斥逐賢良，
忠臣烈士，
皆撫髀於私室而箝口於公朝，
畏迕 rm#r01178@易之 等意，
徒取死而無益。

方今賦役煩重，
百姓凋弊，
重以讒慝專恣，
刑賞失中，
竊恐人心不安，
別生他變，
爭鋒於 dm#dm03754@朱雀門 内，
問鼎於 dm#dm01635@大明殿 前，
陛下將何以謝之，
何以禦之？」
 rm#r01178@易之 等見其疏，
大怒，
欲殺之，
頼 rm#r01572@朱敬則 及鳳閣舍人 rm#r02120@桓彦範 、著作郎 dm#dm08384@陸澤  rm#r04303@魏知古 保救得免。

# p 

丁酉，
貶 rm#r04302@魏元忠 爲 dm#dm08913@高要 尉；
 rm@戩 、 rm#r01253@説 皆流 dm#dm02533@嶺表 。

 rm#r04302@元忠 辭日，
言於太后曰：
「臣老矣，
今向 dm#dm02527@嶺南 ，
十死一生。

陛下他日必有思臣之時。」

太后問其故，
時 rm#r01178@易之 、 rm#r01176@昌宗 皆侍側，
 rm#r04302@元忠 指之曰：
「此二小兒，
終爲亂階。」

 rm#r01178@易之 等下殿，
叩膺自擲稱冤。

太后曰：
「 rm#r04302@元忠 去矣！」

# p 

殿中侍御史 dm#dm03589@景城  rm#r02651@王晙 復奏申理 rm#r04302@元忠 ，
 rm#r00813@宋璟 謂之曰：
「 rm@魏公 幸已得全，
今子復冒威怒，
得無狼狽乎！」

 rm#r02651@晙 曰：
「 rm@魏公 以忠獲罪，
 rm#r02651@晙 爲義所激，
顛沛無恨。」

 rm#r00813@璟 歎曰：
「 rm#r00813@璟 不能申 rm@魏公 之枉，
深負朝廷矣。」

# p 

太子僕 rm#r00997@崔貞愼 等八人餞 rm#r04302@元忠 於郊外，
 rm#r01178@易之 詐爲告密人 rm@柴明 状，
稱 rm#r00997@貞愼 等與 rm#r04302@元忠 謀反。

太后使監察御史 dm#dm00295@丹徒  rm#r04176@馬懷素 鞫之，
謂 rm#r04176@懷素 曰：
「茲事皆實，
略問，
速以聞。」

頃之，
中使督趣者數四，
曰：
「反状昭然，
何稽留如此？」
 rm#r04176@懷素 請 rm@柴明 對質，
太后曰：
「我自不知 rm@柴明 處，
但據状鞫之，
安用告者？」
 rm#r04176@懷素 據實以聞，
太后怒曰：
「卿欲縱反者邪？」
對曰：
「臣不敢縱反者！

 rm#r04302@元忠 以宰相謫官，
 rm#r00997@貞愼 等以親故追送，
若誣以爲反，
臣實不敢。

昔 rm@欒布 奏事 rm#r06194@彭越 頭下，
 rm#rt0511@漢祖 不以爲罪，
況 rm#r04302@元忠 之刑未如 rm#r06194@彭越 ，
而陛下欲誅其送者乎！

且陛下操生殺之柄，
欲加之罪，
取決聖衷可矣；
若命臣推鞫，
臣不敢不以實聞。」

太后曰：
「汝欲全不罪邪？」
對曰：
「臣智識愚淺，
實不見其罪。」

太后意解。

 rm#r00997@貞愼 等由是獲免。
# p 

太后嘗命朝貴宴集，
 rm#r01178@易之 兄弟皆位在 rm#r00813@宋璟 上。

 rm#r01178@易之 素憚 rm#r00813@璟 ，
欲悦其意，
虚位揖之曰：
「公方今第一人，
何乃下坐？」
 rm#r00813@璟 曰：
「才劣位卑，
 rm#r01178@張卿 以爲第一，
何也？」
天官侍郎 rm#r03798@鄭杲 謂 rm#r00813@璟 曰：
「中丞奈何卿 rm#r01178@五郎 ？」
 rm#r00813@璟 曰：
「以官言之，
正當爲卿。

足下非 rm#r01178@張卿 家奴，
何郎之有！」

舉坐悚惕。

時自 rm#r02294@武三思 以下，
皆謹事 rm#r01178@易之 兄弟，
 rm#r00813@璟 獨不爲之禮。

諸 rm@張 積怒，
常欲中傷之；
太后知之，
故得免。
# p 

丁未，
以左武衞大將軍 rm#r06224@武攸宜 充 dm#dm07290@西京 留守。

# p 

冬，
十月，
丙寅，
車駕發 dm#dm07290@西京 ；
乙酉，
至 dm#dm06235@神都 。


# p 

十一月，
突厥遣使謝許婚。

丙寅，
宴於 dm#dm02252@宿羽臺 ，
太子預焉。

宮尹 rm#r00977@崔神慶 上疏：
以爲：
「今五品以上所以佩龜者，
爲別敕徵召，
恐有詐妄，
内出龜合，
然後應命。

況太子國本，
古來徵召皆用玉契。

此誠重愼之極也。

昨縁突厥使見，
太子應預朝參，
直有文符下宮，
曾不降敕處分，
臣愚謂太子非朔望朝參、應別召者，
望降墨敕及玉契。」

太后甚然之。己丑寅申
# p 

 dm#dm01881@始安 獠 rm#r05535@歐陽倩 擁衆數萬，
攻陷州縣，
朝廷思得良吏以鎭之。

 rm#r01572@朱敬則 稱司封郎中 rm#r03436@裴懷古 有文武才，
制以 rm#r03436@懷古 爲 dm#dm04001@桂州 都督，
仍充招慰討撃使。

 rm#r03436@懷古 纔及 dm#dm02525@嶺 上，
飛書示以禍福，
 rm#r05535@倩 等迎降，
且言「爲吏所侵逼，
故舉兵自救耳。」

 rm#r03436@懷古 輕騎赴之。

左右曰：
「 dm#dm01835@夷獠 無信，
不可忽也。」

 rm#r03436@懷古 曰：
「吾仗忠信，
可通神明，
而況人乎！」

遂詣其營，
賊衆大喜，
悉歸所掠貨財；
諸洞酋長素持兩端者，
皆來款附，
 dm#dm02532@嶺外 悉定。
# p 

是歳，
分命使者以六條察州縣。

# p 

吐蕃南境諸部皆叛，
贊普 rm@器弩悉弄 自將撃之，
卒於軍中。

卒，
子恤翻。

諸子爭立，
久之，
國人立其子 rm@棄隸蹜贊 爲贊普，
生七年矣。

*** 四年
# year 0704
# p 

春，
正月，
丙申，
册拜右武衞將軍 rm#rw0006@阿史那懷道 爲西突厥十姓可汗。

 rm#rw0006@懷道 ，
 rm@斛瑟羅 之子也。

# p 

丁未，
毀 dm#dm00151@三陽宮 ，
以其材作 dm#dm06787@興泰宮 於 dm#dm06972@萬安山 。

二宮皆 rm#r02294@武三思 建議爲之，
請太后毎歳臨幸，
功費甚廣，
百姓苦之。

左拾遺 rm#r02929@盧藏用 上疏，
以爲：
「左右近臣多以順意爲忠，
朝廷具僚皆以犯忤爲戒，
致陛下不知百姓失業，
傷陛下之仁。

陛下誠能以勞人爲辭，
發制罷之，
則天下皆知陛下苦己而愛人也。」

不從。

 rm#r02929@藏用 ，
 rm#r02907@承慶 之弟孫也。

# p 

壬子，
以天官侍郎 rm#r04015@韋嗣立 爲鳳閣侍郎、同平章事。


# p 

夏官侍郎、同鳳閣鸞臺三品 rm#r01983@李迥秀 頗受賄賂，
監察御史 rm#r04176@馬懷素 劾奏之。

二月，
癸亥，
 rm#r01983@迥秀 貶 dm#dm02792@廬州 刺史。

# p 

壬申，
正諫大夫，
同平章事 rm#r01572@朱敬則 以老疾致仕。

 rm#r01572@敬則 爲相，
以用人爲先，
自餘細務不之視。
# p 

太后嘗與宰相議及刺史、縣令。

三月，
己丑，
 rm#r01714@李嶠 、 rm#r00488@唐休璟 等奏：
「竊見朝廷物議，
遠近人情，
莫不重内官，
輕外職，
毎除授牧伯，
皆再三披訴。

比來所遣外任，
多是貶累之人；
風俗不澄，
寔由於此。

望於臺、閣、寺、監妙簡賢良，
分典大州，
共康庶績。

臣等請輟近侍，
率先具僚。」

太后命書名探之，
得 rm#r04015@韋嗣立 及御史大夫 rm#r02155@楊再思 等二十人。

癸巳，
制各以本官檢校刺史。

 rm#r04015@嗣立 爲 dm#dm04541@汴州 刺史。

其後政績可稱者，
唯 dm#dm02599@常州 刺史 rm#r03304@薛謙光 、 dm#dm02952@徐州 刺史 rm#r00393@司馬鍠 而已。

# p 

丁丑，
徙 rm#r00502@平恩王重福 爲 rm#r00502@譙王 。

# p 

以夏官侍郎 rm#r00825@宗楚客 同平章事。
# p 

鳳閣侍郎、同鳳閣鸞臺三品 rm#r03329@蘇味道 謁歸葬其父，
制州縣供葬事。

 rm#r03329@味道 因之侵毀郷人墓田，
役使過度，
監察御史 rm#r03254@蕭至忠 劾奏之，
左遷 dm#dm01476@坊州 刺史。

 rm#r03254@至忠 ，
 rm#r06752@引 之玄孫也。

# p 

夏，
四月，
壬戌，
同鳳閣鸞臺三品 rm#r04019@韋安石 知納言，
 rm#r01714@李嶠 知内史事。
# p 

太后幸 dm#dm06787@興泰宮 。
# p 

太后復税天下僧尼，
作大像於 dm#dm05873@白司馬阪 ，
令春官尚書 rm#r06225@武攸寧 檢校，
糜費巨億。

 rm#r01714@李嶠 上疏，
以爲：
「天下編戸，
貧弱者衆。

造像錢見有一十七萬餘緡，
若將散施，
人與一千，
濟得一十七萬餘戸。

拯飢寒之弊，
省勞役之勤，
順諸佛慈悲之心，
霑聖君亭育之意，
人神胥悦，
功徳無窮。

方作過後因縁，
豈如見在果報！」

監察御史 rm#r01146@張廷珪 上疏諫曰：
「臣以時政論之，
則宜先邊境，
蓄府庫，
養人力；
以釋教論之，
則宜救苦厄，
滅諸相，
崇無爲。

伏願陛下察臣之愚，
行佛之意，
務以理爲上，
不以人廢言。」

太后爲之罷役，
仍召見 rm#r01146@廷珪 ，
深賞慰之。
# p 

鳳閣侍郎、同鳳閣鸞臺三品 rm#r00627@姚元崇 以母老固請歸侍，
六月，
辛酉，
以 rm#r00627@元崇 行 rm@相王 府長史，
秩位竝同三品。
# p 

乙丑，
以天官侍郎 rm#r00958@崔玄暐 同平章事。
# p 

召鳳閣侍郎、同平章事、檢校 dm#dm04541@汴州 刺史 rm#r04015@韋嗣立 赴 dm#dm06787@興泰宮 。


# p 

丁丑，
以 rm#r01714@李嶠 同鳳閣鸞臺三品。

 rm#r01714@嶠 自請解内史。
# p 

壬午，
以 rm@相王 府長史 rm#r00627@姚元崇 兼知夏官尚書、同鳳閣鸞臺三品。
# p 

秋，
七月，
丙戌，
以 dm#dm06235@神都 副留守 rm#r02155@楊再思 爲内史。

# p 

 rm#r02155@再思 爲相，
專以諂媚取容。

司禮少卿 rm#r05254@張同休 ，
 rm#r01178@易之 之兄也，
嘗召公卿宴集，
酒酣，
戲 rm#r02155@再思 曰：
「 rm#r02155@楊内史 面似 dm#dm08934@高麗 。」

 rm#r02155@再思 欣然，
即翦紙帖巾，
反披紫袍，
爲 dm#dm08934@高麗 舞，
舉坐大笑。

時人或譽 rm#r01176@張昌宗 之美曰：
「六郎面似蓮花。」

 rm#r02155@再思 獨曰：
「不然。」

 rm#r01176@昌宗 問其故，
 rm#r02155@再思 曰：
「乃蓮花似六郎耳。」

# p 

甲午，
太后還宮。
# p 

乙未，
司禮少卿 rm#r05254@張同休 、 dm#dm04541@汴州 刺史 rm#r05281@張昌期 、尚方少監 rm#r05280@張昌儀 皆坐贓下獄，
命左右臺共鞫之；
丙申，
敕，
 rm#r01178@張易之 ，
 rm#r01176@張昌宗 作威作福，
亦命同鞫。

辛丑，
司刑正 rm#r05887@賈敬言 奏：
「 rm#r01176@張昌宗 強市人田，
應徵銅二十斤。」

制「可」。

乙巳，
御史大夫 rm#r03479@李承嘉 、中丞 rm#r02120@桓彦範 奏：
「 rm#r05254@張同休 兄弟贓共四千餘緡，
 rm#r01176@張昌宗 法應免官。

」
 rm#r01176@昌宗 奏：
「臣有功於國，
所犯不至免官。」

太后問諸宰相：
「 rm#r01176@昌宗 有功乎？」
 rm#r02155@楊再思 曰：
「 rm#r01176@昌宗 合神丹，
聖躬服之有驗，
此莫大之功。」

太后悦，
赦 rm#r01176@昌宗 罪，
復其官。

左補闕 rm#r05327@戴令言 作兩脚狐賦以譏 rm#r02155@再思 ，
 rm#r02155@再思 出 rm#r05327@令言 爲 dm#dm08230@長社 令。


# p 

丙午，
夏官侍郎、同平章事 rm#r00825@宗楚客 有罪，
左遷 dm#dm01114@原州 都督，
充 dm#dm08629@靈武道 行軍大總管。
# p 

癸丑，
 rm#r05254@張同休 貶 dm#dm02417@岐山 丞，
 rm#r05280@張昌儀 貶 dm#dm01095@博望 丞。
# p 

鸞臺侍郎、知納言事、同鳳閣鸞臺三品 rm#r04019@韋安石 舉奏 rm#r01178@張易之 等罪，
敕付 rm#r04019@安石 及右庶子、同鳳閤鸞臺三品 rm#r00488@唐休璟 鞫之，
未竟而事變。

八月，
甲寅，
以 rm#r04019@安石 兼檢校 dm#dm03246@揚州 刺史，
庚申，
以 rm#r00488@休璟 兼 dm#dm02692@幽營 都督、 dm#dm02032@安東 都護。

 rm#r00488@休璟 將行，
密言於太子曰：
「 rm#no@二張 恃寵不臣，
必將爲亂。」

殿下宜備之。刺長刺
# p 

 rm@相王 府長史兼知夏官尚書事、同鳳閣鸞臺三品 rm#r00627@姚元崇 上言：
「臣事 rm@相王 ，
不宜典兵馬。

臣不敢愛死，
恐不益於王。」

辛酉，
改春官尚書，
餘如故。

 rm#r00627@元崇 字 rm#r00627@元之 ，
時突厥 rm#xjts24612@叱列元崇 反，
太后命 rm#r00627@元崇 以字行。
# p 

突厥 rm@默啜 既和親，
戊寅，
始遣 rm#r02309@淮陽王  rm#r02309@武延秀 還。


# p 

九月，
壬子，
以 rm#r00627@姚元之 充 dm#dm08629@靈武道 行軍大總管；
辛酉，
以 rm#r00627@元之 爲 dm#dm08629@靈武道 安撫大使。

# p 

 rm#r00627@元之 將行，
太后令舉外司堪爲宰相者。

對曰：
「 rm#r01188@張柬之 沈厚有謀，
能斷大事，
且其人已老，
惟陛下急用之。」

冬，
十月，
甲戌，
以秋官侍郎 rm#r01188@張柬之 同平章事，
時年且八十矣。
# p 

乙亥，
以 rm#r04015@韋嗣立 檢校 dm#dm08950@魏州 刺史，
餘如故。

# p 

壬午，
以 dm#dm03102@懷州 長史 dm#dm04660@河南  rm#ry0022@房融 同平章事。
# p 

太后命宰相各舉堪爲員外郎者，
 rm#r04015@韋嗣立 薦 rm#r00881@廣武公  rm#r00881@岑羲 曰：
「但恨其伯父 rm#r00882@長倩 爲累。」

太后曰：
「苟或有才，
此何所累！」

遂拜天官員外郎。

由是諸縁坐者始得進用。公令
# p 

十一月，
丁亥，
以天官侍郎 rm#r04034@韋承慶 爲鳳閣侍郎、同平章事。
# p 

癸卯，
成均祭酒、同鳳閣鸞臺三品 rm#r01714@李嶠 罷爲地官尚書。
# p 

十二月，
甲寅，
敕 y@大足 已來新置官竝停。
# p 

丙辰，
鳳閣侍郎、同平章事 rm#r04015@韋嗣立 罷爲成均祭酒，
檢校 dm#dm08950@魏州 刺史如故；
以兄 rm#r04034@承慶 入相故也。


# p 

太后寢疾，
居 dm#dm08228@長生院 ，
宰相不得見者累月，
惟 rm#r01178@張易之 、 rm#r01176@昌宗 侍側。

疾少閒，
 rm#r00958@崔玄暐 奏言：
「皇太子、 rm@相王 ，
仁明孝友，
足侍湯藥。

宮禁事重，
伏願不令異姓出入。」

 rm@太后 曰：
「徳卿厚意。」

 rm#r01178@易之 、 rm#r01176@昌宗 見太后疾篤，
恐禍及己，
引用黨援，
陰爲之備。

屡有人爲飛書及牓其書於通衢，
云「 rm#r01178@易之 兄弟謀反」，
太后皆不問。
# p 

辛未，
 dm#dm07433@許州 人 rm#r05482@楊元嗣 ，
告「 rm#r01176@昌宗 嘗召術士 rm@李弘泰 占相，
 rm@弘泰 言 rm#r01176@昌宗 有天子相，
勸於 dm#dm02124@定州 造佛寺，
則天下歸心。」

太后命 rm#r04034@韋承慶 及司刑卿 rm#r00977@崔神慶 、御史中丞 rm#r00813@宋璟 鞫之。

 rm#r00977@神慶 ，
 rm#r00976@神基 之弟也。

 rm#r04034@承慶 、 rm#r00977@神慶 奏言：
「 rm#r01176@昌宗 款稱『 rm@弘泰 之語，
尋已奏聞』，
準法首原；
 rm@弘泰 妖言，
請收行法。」

 rm#r00813@璟 與大理丞 rm#r05193@封全禎 奏：
「 rm#r01176@昌宗 寵榮如是，
復召術士占相，
志欲何求！

 rm@弘泰 稱筮得純乾，
天子之卦。

 rm#r01176@昌宗 儻以 rm@弘泰 爲妖妄，
何不執送有司！

雖云奏聞，
終是包藏禍心，
法當處斬破家。

請收付獄，
窮理其罪！」

太后久之不應，
 rm#r00813@璟 又曰：
「儻不即收繋，
恐其搖動衆心。」

太后曰：
「卿且停推，
俟更檢詳文状。」

 rm#r00813@璟 退，
左拾遺 dm#dm04510@江都  rm#r01995@李邕 進曰：
「向觀 rm#r00813@宋璟 所奏，
志安社稷，
非爲身謀，
願陛下可其奏！」

太后不聽。

尋敕 rm#r00813@璟  dm#dm03246@揚州 推按，
又敕 rm#r00813@璟 按 dm#dm02689@幽州 都督 rm#r00875@屈突仲翔 贓汚，
又敕 rm#r00813@璟 副 rm#r01714@李嶠 安撫 dm#dm08457@隴 、 dm#dm07197@蜀 ；
 rm#r00813@璟 皆不肯行，
奏曰：
「故事，
州縣官有罪，
品高則侍御史、卑則監察御史按之，
中丞非軍國大事，
不當出使。

今 dm#dm08457@隴 、 dm#dm07197@蜀 無變，
不識陛下遣臣出外何也？
臣皆不敢奉制。」


# p 

司刑少卿 rm#r02120@桓彦範 上疏，
以爲：
「 rm#r01176@昌宗 無功荷寵，
而包藏禍心，
自招其咎，
此乃皇天降怒；
陛下不忍加誅，
則違天不祥。

且 rm#r01176@昌宗 既云奏訖，
則不當更與 rm@弘泰 往還，
使之求福禳災，
是則初無悔心；
所以奏者，
擬事發則云先已奏陳，
不發則俟時爲逆。

此乃奸臣詭計，
若云可捨，
誰爲可刑！

況事已再發，
陛下皆釋不問，
使 rm#r01176@昌宗 益自負得計，
天下亦以爲天命不死，
此乃陛下養成其亂也。

苟逆臣不誅，
社稷亡矣。

請付鸞臺鳳閣三司，
考竟其罪！」

疏奏，
不報。
# p 

 rm#r00958@崔玄暐 亦屡以爲言，
太后令法司議其罪。

 rm#r00958@玄暐 弟司刑少卿 rm#r01597@昪 ，
處以大辟。

 rm#r00813@宋璟 復奏收 rm#r01176@昌宗 下獄。

太后曰：
「 rm#r01176@昌宗 已自奏聞。」

對曰：
「 rm#r01176@昌宗 爲飛書所逼，
窮而自陳，
勢非得已。

且謀反大逆，
無容首免。

若 rm#r01176@昌宗 不伏大刑，
安用國法！」

太后温言解之。

 rm#r00813@璟 聲色逾厲曰：
「 rm#r01176@昌宗 分外承恩，
臣知言出禍從，
然義激於心，
雖死不恨！」

 rm#r02155@楊再思 恐其忤旨，
遽宣敕令出，
 rm#r00813@璟 曰：
「聖主在此，
不煩宰相宣敕命！」

太后乃可其奏，
遣 rm#r01176@昌宗 詣臺。

 rm#r00813@璟 庭立而按之；
事未畢，
太后遣中使召 rm#r01176@昌宗 特敕赦之。

 rm#r00813@璟 歎曰：
「不先撃小子腦裂，
負此恨矣。」

太后乃使 rm#r01176@昌宗 詣 rm#r00813@璟 謝，
 rm#r00813@璟 拒不見。
太后不悦
# p 

左臺中丞 rm#r02120@桓彦範 、右臺中丞 dm#dm03792@東光  rm#r03381@袁恕己 共薦詹事司直 rm#r03964@陽嶠 爲御史。

 rm#r02155@楊再思 曰：
「 rm#r03964@嶠 不樂搏撃之任如何？」
 rm#r02120@彦範 曰：
「爲官擇人，
豈必待其所欲！

所不欲者，
尤須與之，
所以長難進之風，
抑躁求之路。」

乃擢爲右臺侍御史。

 rm#r03964@嶠 ，
 rm#r06833@休之 之玄孫也。

# p 

先是 rm#r01714@李嶠 、 rm#r00958@崔玄暐 奏：
「往屬革命之時，
人多逆節，
遂致刻薄之吏，
恣行酷法，
其 rm#r00116@周興 等所劾破家者，
竝請雪免。」

司刑少卿 rm#r02120@桓彦範 又奏陳之，
表疏前後十上。

太后乃從之。
# p 

中宗大和大聖大昭孝皇帝上
** 神龍
*** 神龍元年
# year 0705
# p 

春，
正月，
壬午朔，
赦天下，
改元。

自 y@文明 以來，
得罪者非 dm#dm03240@揚 、 dm#dm07502@豫 、 dm#dm01088@博 三州及諸反逆魁首，
咸赦除之。
# p 

太后疾甚，
麟臺監 rm#r01178@張易之 、春官侍郎 rm#r01176@張昌宗 居中用事，
 rm#r01188@張柬之 、 rm#r00958@崔玄暐 與中臺右丞 rm#r01407@敬暉 、司刑少卿 rm#r02120@桓彦範 、 rm@相王 府司馬 rm#r03381@袁恕己 謀誅之。

 rm#r01188@柬之 謂右羽林衞大將軍 rm#r01671@李多祚 曰：
「將軍今日富貴，
誰所致也？」
 rm#r01671@多祚 泣曰：
「 rm#r01837@大帝 也。」

 rm#r01188@柬之 曰：
「今 rm#r01837@大帝 之子爲二豎所危，
將軍不思報 rm#r01837@大帝 之徳乎！」

 rm#r01671@多祚 曰：
「苟利國家，
惟相公處分，
不敢顧身及妻子。」

因指天地以自誓。

遂與定謀。
# p 

初，
 rm#r01188@柬之 與 dm#dm06885@荊府 長史 dm#dm08271@閺郷  rm#r02151@楊元琰 相代，
同泛 dm#dm04475@江 ，
至中流，
語及太后革命事，
 rm#r02151@元琰 慨然有匡復之志。

及 rm#r01188@柬之 爲相，
引 rm#r02151@元琰 爲右羽林將軍，
謂曰：
「君頗記 dm#dm04475@江 中之言乎？
今日非輕授也。」

 rm#r01188@柬之 又用 rm#r02120@彦範 、 rm#r01407@暉 及右散騎侍郎 rm#r01852@李湛 皆爲左、右羽林將軍，
委以禁兵。

 rm#r01178@易之 等疑懼，
乃更以其黨 rm#r06224@武攸宜 爲右羽林大將軍，
 rm#r01178@易之 等乃安。

# p 

俄而 rm#r00627@姚元之 自 dm#dm08626@靈武 至，
 rm#r01188@柬之 、 rm#r02120@彦範 相謂曰：
「事濟矣！」

遂以其謀告之。

 rm#r02120@彦範 以事白其母，
母曰：
「忠孝不兩全，
先國後家可也。」

時太子於北門起居，
 rm#r02120@彦範 、 rm#r01407@暉 謁見，
密陳其策，
太子許之。
# p 

癸卯，
 rm#r01188@柬之 、 rm#r00958@玄暐 、 rm#r02120@彦範 與左威衞將軍 rm#r05812@薛思行 等帥左右羽林兵五百餘人至 dm#dm05694@玄武門 ，
遣 rm#r01671@多祚 、 rm#r01852@湛 及内直郎、駙馬都尉 dm#dm02084@安陽  rm#r02606@王同皎 詣東宮迎太子。

太子疑不出，
 rm#r02606@同皎 曰：
「先帝以神器付殿下，
横遭幽廢，
人神同憤，
二十三年矣。

今天誘其衷，
北門、南牙，
同心協力，
以誅凶豎，
復 rm@李氏 社稷，
願殿下蹔至 dm#dm05694@玄武門 以副衆望。」

太子曰：
「凶豎誠當夷滅，
然上體不安，
得無驚怛！

諸公更爲後圖。

」
 rm#r01852@李湛 曰：
「諸將相不顧家族以徇社稷，
殿下奈何欲納之鼎鑊乎！

請殿下自出止之。」

太子乃出。今日
# p 

 rm#r02606@同皎 扶抱太子上馬，
從至 dm#dm05694@玄武門 ，
斬關而入。

太后在 dm#dm07667@迎仙宮 ，
 rm#r01188@柬之 等斬 rm#r01178@易之 、 rm#r01176@昌宗 於廡下，
進至太后所寢 dm#dm08227@長生殿 ，
環繞侍衞。

太后驚起，
問曰：
「亂者誰邪？」
對曰：
「 rm#r01178@張易之 、 rm#r01176@昌宗 謀反，
臣等奉太子令誅之，
恐有漏洩，
故不敢以聞。

稱兵宮禁，
罪當萬死！」

太后見太子曰：
「乃汝邪？
小子既誅，
可還東宮。」

 rm#r02120@彦範 進曰：
「太子安得更歸！

昔 rm#r02293@天皇 以愛子託陛下，
 y@今年 齒已長，
久居東宮，
天意人心，
久思 rm@李氏 。

羣臣不忘 rm#r01602@太宗 、 rm#r02293@天皇 之徳，
故奉太子誅賊臣。

願陛下傳位太子，
以順天人之望！」

 rm#r01852@李湛 ，
 rm#r01922@義府 之子也。

太后見之，
謂曰：
「汝亦爲誅 rm#r01178@易之 將軍邪？
我於汝父子不薄，
乃有今日！」

 rm#r01852@湛 慙不能對。

又謂 rm#r00958@崔玄暐 曰：
「他人皆因人以進，
惟卿朕所自擢，
亦在此邪？」
對曰：
「此乃所以報陛下之大徳。」

# p 

於是收 rm#r05281@張昌期 、 rm#r05254@同休 、 rm#r05280@昌儀 ，
皆斬之，
與 rm#r01178@易之 、 rm#r01176@昌宗 梟首 dm#dm01749@天津 南。

是日，
 rm#r03381@袁恕己 從 rm@相王 統南牙兵以備非常，
收 rm#r04034@韋承慶 、 rm#ry0022@房融 及司禮卿 rm#r00977@崔神慶 繋獄，
皆 rm#r01178@易之 之黨也。

初，
 rm#r05280@昌儀 新作第，
甚美，
逾於王主，
或夜書其門曰：
「一日絲能作幾日絡？」
滅去，
復書之，
如是六七，
 rm#r05280@昌儀 取筆註其下曰：
「一日亦足。」

乃止。
# p 

甲辰，
制太子監國，
赦天下。

以 rm#r03381@袁恕己 爲鳳閣侍郎、同平章事，
分遣十使齎璽書宣慰諸州。

乙巳，
太后傳位於太子。
# p 

丙午，
 rm#r01656@中宗 即位。

赦天下，
惟 rm#r01178@張易之 黨不原；
其爲 rm#r00116@周興 等所枉者，
咸令清雪，
子女配沒者皆免之。

 rm@相王 加號 rm#r01797@安國相王 ，
拜太尉、同鳳閣鸞臺三品，
 rm#r00603@太平公主 加號 rm#r00603@鎭國太平公主 。

皇族先配沒者，
子孫皆復屬籍，
仍量敍官爵。


# p 

丁未，
太后徙居 dm#dm00199@上陽宮 ，
 rm#r01852@李湛 留宿衞。

戊申，
帝帥百官詣 dm#dm00199@上陽宮 ，
上太后尊號曰 rm#r02293@則天大聖皇帝 。

# p 

庚戌，
以 rm#r01188@張柬之 爲夏官尚書、同鳳閣鸞臺三品，
 rm#r00958@崔玄暐 爲内史，
 rm#r03381@袁恕己 同鳳閣鸞臺三品，
 rm#r01407@敬暉 、 rm#r02120@桓彦範 皆爲納言；
竝賜爵郡公。

 rm#r01671@李多祚 賜爵 rm@遼陽郡王 ，
 rm#r02606@王同皎 爲右千牛將軍、 rm@琅邪郡公 ，
 rm#r01852@李湛 爲右羽林大將軍、 rm@趙國公 ；
自餘官賞有差。

# p 

 rm#r01188@張柬之 等之討 rm#r01178@張易之 也，
殿中監 rm#r02822@田歸道 將千騎宿 dm#dm05694@玄武門 ，
 rm#r01407@敬暉 遣使就索千騎，
 rm#r02822@歸道 先不預謀，
拒而不與。

事寧，
 rm#r01407@暉 欲誅之，
 rm#r02822@歸道 以理自陳，
乃免歸私第；
帝嘉其忠壯，
召拜太僕少卿。
# p 

二月，
辛亥，
帝帥百官詣 dm#dm00199@上陽宮 問太后起居；
自是毎十日一往。
# p 

甲寅，
復國號曰 dyn#ch100@唐 。

郊廟、社稷、陵寢、百官、旗幟、服色、文字皆如 y@永淳 以前故事。

復以 dm#dm06235@神都 爲 dm#dm03880@東都 ，
 dm#dm00895@北都 爲 dm#dm00059@幷州 ，
 rm#ry0032@老君 爲 rm#ry0032@玄元皇帝 
# p 

乙卯，
鳳閣侍郎、同平章事 rm#r04034@韋承慶 貶 dm#dm08913@高要 尉；
正諫大夫、同平章事 rm#ry0022@房融 除名，
流 dm#dm08893@高州 ；
司禮卿 rm#r00977@崔神慶 流 dm#dm04208@欽州 。

 rm#r02155@楊再思 爲戸部尚書、同中書門下三品、 dm#dm07290@西京 留守。

# p 

太后之遷 dm#dm00199@上陽宮 也，
太僕卿、同中書門下三品 rm#r00627@姚元之 獨嗚咽流涕。

 rm#ry0023@桓彦範 、 rm#r01188@張柬之 謂曰：
「今日豈公涕泣時邪！

恐公禍由此始。」

 rm#r00627@元之 曰：
「 rm#r00627@元之 事 rm#r02293@則天皇帝 久，
乍此辭違，
悲不能忍。

且 rm#r00627@元之 前日從公誅姦逆，
人臣之義也；
今日別舊君，
亦人臣之義也，
雖獲罪，
實所甘心。」

是日，
出爲 dm#dm00454@亳州 刺史。

# p 

甲子，
立𡚱 rm#r00840@韋氏 爲皇后，
赦天下。

追贈后父 rm#xjts18378@玄貞 爲 rm#xjts18378@上洛王 、母 rm#r00885@崔氏 爲𡚱。
# p 

左拾遺 rm#ry0024@賈虚己 上疏，
以爲「異姓不王，
古今通制。

今中興之始，
萬姓喁喁以觀陛下之政；
而先王后族，
非所以廣徳美於天下也。

且先朝贈后父 rm#r02300@太原王 ，
 dyn#ch102@殷 鑒不遠，
須防其漸。

若以恩制已行，
宜令皇后固讓，
則益増謙沖之徳矣。」

不聽。
# p 

初，
 rm#xjts18722@韋后 生 rm#r03834@邵王重潤 、 rm#r03867@長寧 ‧ rm#r00790@安樂 二公主，
上之遷 dm#dm03164@房陵 也，
 rm#r00790@安樂公主 生於道中，
上特愛之。

上在 dm#dm03164@房陵 與后同幽閉，
備嘗艱危，
情愛甚篤。

上毎聞敕使至，
輒惶恐欲自殺，
后止之曰：
「禍福無常，
寧失一死，
何遽如是！」

上嘗與后私誓曰：
「異時幸復見天日，
當惟卿所欲，
不相禁制。」

及再爲皇后，
遂干預朝政，
如 rm#r04193@武后 在 rm#r01837@高宗 之世。

 rm#ry0023@桓彦範 上表，
以爲：
「易稱『無攸遂，在中饋，貞吉』，
書稱『牝雞之辰，惟家之索』。伏見陛下毎臨朝，
皇后必施帷幔坐殿上，
預聞政事。

臣竊觀自古帝王，
未有與婦人共政而不破國亡身者也。

且以陰乘陽，
違天也；
以婦陵夫，
違人也。

伏願陛下覽古今之戒，
以社稷蒼生爲念，
令皇后專居中宮，
治陰教，
勿出外朝干國政。」


# p 

先是，
胡僧 rm#xjts24139@慧範 以妖妄遊權貴之門，
與 rm#r01178@張易之 兄弟善，
 rm#xjts18722@韋后 亦重之。

及 rm#r01178@易之 誅，
復稱 rm#xjts24139@慧範 預其謀，
以功加銀青光祿大夫，
賜爵 rm#xjts24139@上庸縣公 ，
出入宮掖，
上數微行幸其舍。

 rm#r02120@彦範 復表言 rm#xjts24139@慧範 執左道以亂政，
請誅之。

上皆不聽。
# p 

初，
 rm#r02293@武后 誅 dyn#ch100@唐 宗室，
有才徳者先死，
惟 rm#r00416@呉王恪 之子 rm#r01370@鬱林侯  rm#r01370@千里 ，
褊躁無才，
又數獻符瑞，
故獨得免。

上即位，
立爲 rm#r01370@成王 ，
拜左金吾大將軍。

 rm#r02293@武后 所誅唐諸王、𡚱、主、駙馬等皆無人葬埋，
子孫或流竄 dm#dm02533@嶺表 ，
或拘囚歴年，
或逃匿民間，
爲人傭保。

至是，
制州縣求訪其柩，
以禮改葬，
追復官爵，
召其子孫，
使之承襲，
無子孫者爲擇後置之。

既而宗室子孫相繼而至，
皆召見，
涕泣舞蹈，
各以親疏襲爵拜官有差。
# p 

 rm#no@二張 之誅也，
 dm#dm04778@洛州 長史 rm#r03280@薛季昶 謂 rm#r01188@張柬之 、 rm#r01407@敬暉 曰：
「二凶雖除，
 rm#ry0025@産 、 rm#ry0026@祿 猶在，
去草不去根，
終當復生。」

二人曰：
「大事已定，
彼猶机上肉耳，
夫何能爲！

所誅已多，
不可復益也。」

 rm#r03280@季昶 歎曰：
「吾不知死所矣。」

 dm#dm03715@朝邑 尉 dm#dm04263@武強  rm#r00239@劉幽求 亦謂 rm#ry0023@桓彦範 、 rm#r01407@敬暉 曰：
「 rm#r02294@武三思 尚存，
公輩終無葬地；
若不早圖，
噬臍無及。

」
不從。

# p 

上女 rm#r00790@安樂公主 適 rm#r02294@三思 子 rm#r02306@崇訓 。

 rm#r00023@上官婉兒 ，
 rm#r00022@儀 之女孫也，
 rm#r00022@儀 死，
沒入掖庭，
辯慧善屬文，
明習吏事。

 rm#r02293@則天 愛之，
自 y@聖暦 以後，
百司表奏多令參決；
及上即位，
又使專掌制命，
益委任之，
拜爲婕妤，
用事於中。

 rm#r02294@三思 通焉，
故黨於 rm#r02293@武氏 ，
又薦 rm#r02294@三思 於 rm#xjts18722@韋后 ，
引入禁中，
上遂與 rm#r02294@三思 圖議政事，
 rm#r01188@張柬之 等皆受制於 rm#r02294@三思 矣。

上使 rm#xjts18722@韋后 與 rm#r02294@三思 雙陸，
而自居旁爲之點籌；
 rm#r02294@三思 遂與后通，
由是 rm#r02293@武氏 之勢復振。
# p 

 rm#r01188@張柬之 等數勸上誅諸 rm#no@武 ，
上不聽。

 rm#r01188@柬之 等曰：
「革命之際，
宗室諸 rm#no@李 ，
誅夷略盡；
今頼天地之靈，
陛下返正，
而 rm@武氏 濫官僭爵，
按堵如故，
豈遠近所望邪！

願頗抑損其祿位以慰天下！」

又不聽。

 rm#r01188@柬之 等或撫牀歎憤，
或彈指出血，
曰：
「主上昔爲 rm#r01656@英王 ，
時稱勇烈，
吾所以不誅諸 rm#no@武 者，
欲使上自誅之以張天子之威耳。

今反如此，
事勢已去，
知復奈何！」


# p 

上數微服幸 rm#r02294@武三思 第，
監察御史 dm#dm05053@清河  rm#r05226@崔皎 密疏諫曰：
「國命初復，
 rm#r02293@則天皇帝 在 dm#dm07310@西宮 ，
人心猶有附會；
 dyn#ch103@周 之舊臣，
列居朝廷，
陛下奈何輕有外遊，
不察豫且之禍！」

上洩之，
 rm#r02294@三思 之黨切齒。


# p 

丙寅，
以太子賓客 rm#r02294@武三思 爲司空、同中書門下三品。
# p 

左散騎常侍 rm#r03540@譙王重福 ，
上之庶子也；
其𡚱，
 rm#r01178@張易之 之甥。

 rm#xjts18722@韋后 惡之，
譖於上曰：
「 rm#r03834@重潤 之死，
 rm#r03540@重福 爲之也。」

由是貶 dm#dm05457@濮州 員外刺史，
又改 dm#dm01472@均州 刺史，
常令州司防守之。
# p 

丁卯，
以右散騎常侍 rm#r02317@安定王  rm#r02317@武攸曁 爲司徒、 rm#r02317@定王 。
# p 

辛未，
 rm@相王 固讓太尉及知政事，
許之；
又立爲皇太弟，
 rm@相王 固辭而止。

# p 

甲戌，
以國子祭酒 dm#dm01885@始平  rm#r02966@祝欽明 同中書門下三品，
黄門侍郎、知侍中事 rm#r04019@韋安石 爲刑部尚書，
罷知政事。
# p 

丁丑，
 rm#r02294@武三思 、 rm#r02317@武攸曁 固辭新官爵及政事，
許之，
竝加開府儀同三司。
# p 

立皇子 rm#r03066@義興王重俊 爲 rm#r03066@衞王 ，
 rm#r03836@北海王重茂 爲 rm#r03836@温王 ；
仍以 rm#r03066@重俊 爲 dm#dm04778@洛州 牧。

# p 

三月，
甲申，
制：
「 y@文明 已來破家子孫皆復舊資廕，
唯 rm#r01788@徐敬業 、 rm#r03449@裴炎 不在免限。」


# p 

丁亥，
制：
「酷吏 rm#r00116@周興 、 rm#r00115@來俊臣 等，
已死者追奪官爵，
存者皆流 dm#dm02527@嶺南 惡地。」


# p 

己丑，
以 rm#r03381@袁恕己 爲中書令。
# p 

以安車徵 rm#r02318@安平王武攸緒 於 dm#dm02514@嵩山 ，
既至，
除太子賓客；
固請還山，
許之。
# p 

制：
「 rm#no@梟氏 、 rm#no@蟒氏 皆復舊姓。」


# p 

術士 rm#r05962@鄭普思 、尚衣奉御 rm#r05766@葉靜能 皆以妖妄爲上所信重，
夏，
四月，
墨敕以 rm#r05962@普思 爲祕書監，
 rm#r05766@靜能 爲國子祭酒。

 rm#r02120@桓彦範 、 rm#r00958@崔玄暐 固執不可，
上曰：
「已用之，
無容遽改。」

 rm#r02120@彦範 曰：
「陛下初即位，
下制云：
『政令皆依 y@貞觀 故事。』

 y@貞觀中 ，
 rm#r04294@魏徵 、 rm#r03353@虞世南 、 rm#r04140@顏師古 爲祕書監，
 rm#r00680@孔穎達 爲國子祭酒，
豈 rm#r05962@普思 、 rm#r05766@靜能 之比乎！」

庚戌，
左拾遺 rm#r01995@李邕 上疏，
以爲「詩三百，
一言以蔽之，
曰『思無邪』。

若有神仙能令人不死，
則 rm#rt0506@秦始皇 、 rm#rt0517@漢武帝 得之矣；
佛能爲人福利，
則 rm#rt0704@梁武帝 得之矣。

 rm#rt0006@堯 、 rm#rt0007@舜 所以爲帝王首者，
亦脩人事而已。

尊寵此屬，
何補於國！」

上皆不聽。
# p 

上即位之日，
驛召 rm#r04302@魏元忠 於 dm#dm08913@高要 ；
丁卯，
至都，
拜衞尉卿、同平章事。
# p 

甲戌，
以 rm#r04302@魏元忠 爲兵部尚書，
 rm#r04019@韋安石 爲吏部尚書，
 rm#r01777@李懷遠 爲右散騎常侍，
 rm#r00488@唐休璟 爲輔國大將軍，
 rm#r00958@崔玄暐 檢校 dm#dm05985@益府 長史，
 rm#r02155@楊再思 檢校 dm#dm04080@楊府 長史，
 rm#r02966@祝欽明 爲刑部尚書，
竝同中書門下三品。

 rm#r04302@元忠 等皆以東宮舊僚褒之也。

# p 

乙亥，
以 rm#r01188@張柬之 爲中書令。
# p 

戊寅，
追贈故 rm#r03834@邵王重潤 爲 rm#r03834@懿徳太子 。
# p 

五月，
壬午，
遷 dyn#ch176@周 廟七主於 dm#dm07290@西京  dm#dm02460@崇尊廟 。

制：
「 rm#no@武氏 三代諱，
奏事者皆不得犯。」

# p 

乙酉，
立太廟、社稷於 dm#dm03880@東都 。
# p 

以 rm#r01188@張柬之 等及 rm#r02317@武攸曁 、 rm#r02294@武三思 、 rm#r05962@鄭普思 等十六人皆爲立功之人，
賜以鐵券，
自非反逆，
各恕十死。
# p 

癸巳，
 rm#r01407@敬暉 等帥百官上表，
以爲：
「五運迭興，
事不兩大。

 y@天授 革命之際，
宗室誅竄殆盡，
豈得與諸 rm#no@武 竝封！

今天命惟新，
而諸 rm#no@武 封建如舊，
竝居 dm#dm08170@京師 ，
開闢以來未有斯理。

願陛下爲社稷計，
順遐邇心，
降其王爵以安内外。」

上不許。
# p 

 rm#r01407@敬暉 等畏 rm#r02294@武三思 之讒，
以考功員外郎 rm#r00950@崔湜 爲耳目，
伺其動靜。

 rm#r00950@湜 見上親 rm#r02294@三思 而忌 rm#r01407@暉 等，
乃悉以 rm#r01407@暉 等謀告 rm#r02294@三思 ，
反爲 rm#r02294@三思 用；
 rm#r02294@三思 引爲中書舍人。

 rm#r00950@湜 ，
 rm#r00890@仁師 之孫也。


# p 

先是，
殿中侍御史 dm#dm01033@南皮  rm#r06265@鄭愔 諂事 rm#no@二張 ，
 rm#no@二張 敗，
貶 dm#dm02214@宣州 司士參軍，
坐贓，
亡入 dm#dm03880@東都 ，
私謁 rm#r02294@武三思 。

初見 rm#r02294@三思 ，
哭甚哀，
既而大笑。

 rm#r02294@三思 素貴重，
甚怪之，
 rm#r06265@愔 曰：
「始見大王而哭，
哀大王將戮死而滅族也。

後乃大笑，
喜大王之得 rm#r06265@愔 也。

大王雖得天子之意，
彼五人皆據將相之權，
膽略過人，
廢太后如反掌。

大王自視勢位與太后孰重？
彼五人日夜切齒欲噬大王之肉，
非盡大王之族不足以快其志。

大王不去此五人，
危如朝露，
而晏然尚自以爲 dm#dm04750@泰山 之安，
此 rm#r06265@愔 所以爲大王寒心也。」

 rm#r02294@三思 大悦，
與之登樓，
問自安之策，
引爲中書舍人，
與 rm#r00950@崔湜 皆爲 rm#r02294@三思 謀主。
# p 

 rm#r02294@三思 與 rm#xjts18722@韋后 日夜譖 rm#r01407@暉 等，
云「恃功專權，
將不利於社稷。」

上信之。

 rm#r02294@三思 等因爲上畫策，
「不若封 rm#r01407@暉 等爲王，
罷其政事，
外不失尊寵功臣，
内實奪之權。」

上以爲然，
甲午，
以侍中 rm#r01407@齊公敬暉 爲 rm#r01407@平陽王 ，
 rm#r02120@桓彦範 爲 rm#r02120@扶陽王 ，
中書令 rm#r01188@漢陽公  rm#r01188@張柬之 爲 rm#r01188@漢陽王 ，
 rm#r03381@南陽公  rm#r03381@袁恕己 爲 rm#r03381@南陽王 ，
特進、同中書門下三品 rm#r00958@博陵公  rm#r00958@崔玄暐 爲 rm#r00958@博陵王 ，
罷知政事，
賜金帛鞍馬，
令朝朔望；
仍賜 rm#r02120@彦範 姓 rm#no@韋氏 ，
與皇后同籍。

尋又以 rm#r00958@玄暐 檢校 dm#dm05982@益州 長史、知都督事，
又改 dm#dm04043@梁州 刺史。

 rm#r02294@三思 令百官復脩 rm#r02293@則天 之政，
不附 rm@武氏 者斥之，
爲五王所逐者復之，
大權盡歸 rm#r02294@三思 矣。譙公
# p 

五王之請削 rm@武氏 諸王也，
求人爲表，
衆莫肯爲。

中書舍人 rm#r00881@岑羲 爲之，
語甚激切；
中書舍人 dm#dm00606@偃師  rm#r02838@畢構 次當讀表，
辭色明厲。

 rm#r02294@三思 既得志，
 rm#r00881@羲 改祕書少監，
出 rm#r02838@構 爲 dm#dm05367@潤州 刺史。

# p 

 dm#dm03494@易州 刺史 rm#r05903@趙履温 ，
 rm#r02120@桓彦範 之妻兄也。

 rm#r02120@彦範 之誅 rm#no@二張 ，
稱 rm#r05903@履温 預其謀，
召爲司農少卿，
 rm#r05903@履温 以二婢遺 rm#r02120@彦範 ；
及 rm#r02120@彦範 罷政事，
 rm#r05903@履温 復奪其婢。
# p 

上嘉 rm#r00813@宋璟 忠直，
屡遷黄門侍郎。

 rm#r02294@武三思 嘗以事屬 rm#r00813@璟 ，
 rm#r00813@璟 正色拒之曰：
「今太后既復子明辟，
王當以侯就第，
何得尚干朝政！

獨不見 rm#ry0025@産 、 rm#ry0026@祿 之事乎！」

# p 

以 rm#r04019@韋安石 兼檢校中書令，
 rm#r04302@魏元忠 兼檢校侍中，
又以 rm#r01852@李湛 爲右散騎常侍，
 rm#r05909@趙承恩 爲光祿卿，
 rm#r02151@楊元琰 爲衞尉卿。

# p 

先是，
 rm#r02151@元琰 知 rm#r02294@三思 浸用事，
請棄官爲僧，
上不許。

 rm#r01407@敬暉 聞之，
笑曰：
「使我早知，
勸上許之，
髡去胡頭，
豈不妙哉！

」
 rm#r02151@元琰 多鬚類胡，
故 rm#r01407@暉 戲之。

 rm#r02151@元琰 曰：
「功成名遂，
不退將危。

此乃由衷之請，
非徒然也。」

 rm#r01407@暉 知其意，
瞿然不悦。

及 rm#r01407@暉 等得罪，
 rm#r02151@元琰 獨免。
# p 

 rm#r00023@上官婕妤 勸 rm#xjts18722@韋后 襲 rm#r02293@則天 故事，
上表請天下士庶爲出母服喪三年，
又請百姓年二十三爲丁，
五十九免役，
改易制度以收時望。

制皆許之。
# p 

癸卯，
制，
降諸 rm#no@武 ，
 rm#r02294@梁王三思 爲 rm#r02294@徳靜王 ，
 rm#r02317@定王攸曁 爲 rm#r02317@樂壽王 ，
 rm#r02313@河内王懿宗 等十二人皆降爲公，
以厭人心。

# p 

甲辰，
以 rm#r00488@唐休璟 爲左僕射，
同中書門下三品如故；
 rm#r03546@豆盧欽望 爲右僕射。


# p 

六月，
壬子，
以左驍衞大將軍 rm#r05844@裴思説 充 dm#dm08628@靈武軍 大總管，
以備突厥。

# p 

癸亥，
命右僕射 rm#r03546@豆盧欽望 ，
有軍國重事，
中書門下可共平章。
# p 

先是，
僕射爲正宰相，
其後多兼中書門下之職，
午前決朝政，
午後決省事。

至是，
 rm#r03546@欽望 專爲僕射，
不敢預政事，
故有是命。

是後專拜僕射者，
不復爲宰相矣。

# p 

又以 rm#r04019@韋安石 爲中書令，
 rm#r04302@魏元忠 爲侍中，
 rm#r02155@楊再思 檢校中書令。
# p 

丁卯，
祔 rm#r00688@孝敬皇帝 於太廟，
號 rm#r00688@義宗 。

# p 

戊辰，
 dm#dm04780@洛水 溢，
流二千餘家。
# p 

秋，
七月，
辛巳，
以太子賓客 rm#r04023@韋巨源 同中書門下三品，
 dm#dm07290@西京 留守如故。

# p 

特進 rm#r02510@漢陽王  rm#r01188@張柬之 表請歸 dm#dm07274@襄州 養疾；
乙未，
以 rm#r01188@柬之 爲 dm#dm07274@襄州 刺史，
不知州事，
給全俸。

# p 

 dm#dm04650@河 南、北十七州大水。

八月，
戊申，
以水災求直言。

右衞騎曹參軍 dm#dm07346@西河  rm#r00804@宋務光 上疏，
以爲：
「水陰類，
臣妾之象，
恐後庭有干外朝之政者，
宜杜絶其萌。

今霖雨不止，
乃閉坊門以禳之，
至使里巷謂坊門爲宰相，
言朝廷使之燮理陰陽也。

又，
太子國本，
宜早擇賢能而立之。

又，
外戚太盛，
如 rm#r02294@武三思 等，
宜解其機要，
厚以祿賜。

又，
 rm#r05962@鄭普思 、 rm#r05766@葉靜能 以小技竊大位，
亦朝政之蠹也。」

疏奏，
不省。

# p 

壬戌，
追立𡚱 rm#r03596@趙氏 爲 rm#r03596@恭皇后 ，
 rm#r00688@孝敬皇帝 𡚱 rm@裴氏 爲 rm@哀皇后 。
# p 

九月，
壬午，
上祀昊天上帝、皇地祇于明堂，
以 rm#r01837@高宗 配。
# p 

初，
上在 dm#dm03164@房陵 ，
州司制約甚急；
刺史 dm#dm04672@河東  rm#r01223@張知謇 、 dm#dm08623@靈昌  rm#r05218@崔敬嗣 獨待遇以禮，
供給豐贍。

上徳之，
擢 rm#r01223@知謇 自 dm#dm07514@貝州 刺史爲左衞將軍，
賜爵 rm#r01223@范陽公 。

 rm#r05218@敬嗣 已卒，
求得其子 rm@汪 ，
嗜酒，
不堪釐職，
除五品散官。

# p 

改葬上洛王韋玄貞，
其儀皆如 rm#r02300@太原王 故事。

# p 

癸巳，
太子賓客、同中書門下三品 rm#r04023@韋巨源 罷爲禮部尚書，
以其從父 rm#r04019@安石 爲中書令故也。


# p 

以左衞將軍 dm#dm00192@上邽  rm#r03072@紀處訥 兼檢校太府卿，
 rm#r03072@處訥 娶 rm#r02294@武三思 之妻姉故也。

# p 

冬，
十月，
命 rm#r00488@唐休璟 留守 dm#dm08170@京師 。

# p 

癸亥，
上幸 dm#dm09269@龍門 ；
乙丑，
獵於 dm#dm03337@新安 而還。

# p 

辛未，
以 rm#r04302@魏元忠 爲中書令，
 rm#r02155@楊再思 爲侍中。
# p 

十一月，
戊寅，
羣臣上皇帝尊號曰 rm#r01656@應天皇帝 ，
皇后曰 rm@順天皇后 。

壬午，
上與后
# p 

謁謝太廟，
赦天下；
 rm#r01797@相王 、 rm#r00603@太平公主 加實封，
皆滿萬戸。

# p 

己丑，
上御洛城南樓，
觀溌寒胡戲。

 dm#dm05067@清源 尉 rm#r00424@呂元泰 上疏，
以爲「謀時寒若，
何必裸身揮水，
鼓舞衢路以索之！

」
疏奏，
不納。
# p 

壬寅，
 rm#r02293@則天 崩於 dm#dm00199@上陽宮 ，
年八十二。

遺制：
「去帝號，
稱 rm#r02293@則天大聖皇后 。

 rm@王 、 rm@蕭 二族及 rm#r03475@褚遂良 、 rm#r04125@韓瑗 、 rm#r02088@柳奭 親屬皆赦之。」


# p 

上居諒陰，
以 rm#r04302@魏元忠 攝冢宰三日。

 rm#r04302@元忠 素負忠直之望，
中外頼之；
 rm#r02294@武三思 憚之，
矯太后遺制，
慰諭 rm#r04302@元忠 ，
賜實封百戸。

 rm#r04302@元忠 捧制，
感咽涕泗，
見者曰：
「事去矣！」


# p 

十二月，
丁卯，
上始御 dm#dm01232@同明殿 見羣臣。

# p 

太后將合葬 dm#dm00360@乾陵 ，
給事中 rm#r00566@嚴善思 上疏，
以爲：
「 dm#dm00360@乾陵 玄宮以石爲門，
鐵錮其縫，
今啓其門，
必須鐫鑿。

神明之道，
體尚幽玄，
動衆加功，
恐多驚黷。

況合葬非古，
 dyn#ch129@漢 時諸陵，
皇后多不合葬，
 dyn#ch134@魏 、 dyn#ch537@晉 已降，
始有合者。

望於 dm#dm00360@乾陵 之傍更擇吉地爲陵，
若神道有知，
幽塗自當通會；
若其無知，
合之何益！」

不從。
# p 

是歳，
戸部奏天下戸六百一十五萬，
口三千七百一十四萬有畸。

*** 二年
# year 0706
# p 

春，
正月，
戊戌，
以吏部尚書 rm#r01714@李嶠 同中書門下三品，
中書侍郎 rm#r05012@于惟謙 同平章事。
# p 

閏月，
丙午，
制：
「 rm#r00603@太平 、 rm#r03867@長寧 、 rm#r00790@安樂 、 rm#r03096@宜城 、 rm#r01434@新都 、 rm#r00830@定安 、 rm#r03839@金城公主 竝開府，
置官屬。」


# p 

 rm#r02294@武三思 以 rm#r01407@敬暉 、 rm#r02120@桓彦範 、 rm#r03381@袁恕己 尚在 dm#dm08170@京師 ，
忌之，
乙卯，
出爲 dm#dm05225@滑 、 dm#dm04838@洺 、 dm#dm07502@豫 三州刺史。

# p 

賜 dm#dm08271@閺郷 僧 rm#ry0028@萬囘 ，
號 rm#ry0028@法雲公 。

# p 

甲戌，
以突騎施酋長 rm#ry0029@烏質勒 爲 rm#ry0029@懷徳郡王 。

# p 

二月，
乙未，
以刑部尚書 rm#r04023@韋巨源 同中書門下三品，
仍與皇后敍宗族。
# p 

丙申，
僧 rm@慧範 等九人竝加五品階，
賜爵郡、縣公；
道士 rm#r05096@史崇恩 等加五品階，
除國子祭酒，
同正；
 rm#r05766@葉靜能 加金紫光祿大夫。三人
# p 

選左、右臺及内外五品以上官二十人爲十道巡察使，
委之察吏撫人，
薦賢直獄，
二年一代，
考其功罪而進退之。

 dm#dm03494@易州 刺史 dm#dm08945@魏 人 rm#r00643@姜師度 、禮部員外郎 rm#r04176@馬懷素 、殿中侍御史 dm#dm06718@臨漳  rm#r02467@源乾曜 、監察御史 dm#dm08623@靈昌  rm#r02906@盧懷愼 、衞尉少卿 dm#dm05222@滏陽  rm#r01645@李傑 皆預焉。

# p 

三月，
甲辰，
中書令 rm#r04019@韋安石 罷爲戸部尚書；
戸部尚書 rm#r03324@蘇瓌 爲侍中、 dm#dm07290@西京 留守。

 rm#r03324@瓌 ，
 rm#r03348@頲 之父也。

 rm#r00488@唐休璟 致仕。
# p 

初，
少府監丞 dm#dm02888@弘農  rm#r00799@宋之問 及弟 dm#dm00663@兗州 司倉 rm#r05182@之遜 皆坐附會 rm#r01178@張易之 貶 dm#dm02527@嶺南 ，
逃歸 dm#dm03880@東都 ，
匿於友人光祿卿、駙馬都尉 rm#r02606@王同皎 家。

 rm#r02606@同皎 疾 rm#r02294@武三思 及 rm#xjts18722@韋后 所爲，
毎與所親言之，
輒切齒。

 rm#r05182@之遜 於簾下聞之，
密遣其子 rm#r06568@曇 及甥校書郎 rm#r05389@李悛 告 rm#r02294@三思 ，
欲以自贖。

 rm#r02294@三思 使 rm#r06568@曇 、 rm#r05389@悛 及 dm#dm03261@撫州 司倉 rm#r06239@冉祖雍 上書告 rm#r02606@同皎 與 dm#dm04788@洛陽 人 rm#r05246@張仲之 、 rm#rw0001@祖延慶 、 rm@武當 丞 dm#dm01525@壽春  rm#r00460@周憬 等潛結壯士，
謀殺 rm#r02294@三思 ，
因勒兵詣闕，
廢皇后。

上命御史大夫 rm#r03479@李承嘉 、監察御史 rm#r00634@姚紹之 按其事，
又命 rm#r02155@楊再思 、 rm#r01714@李嶠 、 rm#r04023@韋巨源 參驗。

 rm#r05246@仲之 言 rm#r02294@三思 罪状，
事連宮壼。

 rm#r02155@再思 、 rm#r04023@巨源 陽寐不聽；
 rm#r01714@嶠 與 rm#r00634@紹之 命反接送獄。

 rm#r05246@仲之 還顧，
言不已，
 rm#r00634@紹之 命檛之，
折其臂。

 rm#r05246@仲之 大呼曰：
「吾已負汝死，
當訟汝於天！」

庚戌，
 rm#r02606@同皎 等皆坐斬，
籍沒其家。

 rm#r00460@周憬 亡入 dm#dm04366@比干廟 中，
大言曰：
「 rm@比干 古之忠臣，
知吾此心。

 rm#r02294@三思 與皇后淫亂，
傾危國家，
行當梟首都市，
恨不及見耳！」

遂自剄。

 rm#r00799@之問 、 rm#r05182@之遜 、 rm#r06568@曇 、 rm#r05389@悛 、 rm#r06239@祖雍 竝除京官，
加朝散大夫。

# p 

 rm#r02294@武三思 與 rm#xjts18722@韋后 日夜譖 rm#r01407@敬暉 等不已，
復左遷 rm#r01407@暉 爲 dm#dm03687@朗州 刺史，
 rm#r00958@崔玄暐 爲 dm#dm01472@均州 刺史，
 rm#r02120@桓彦範 爲 dm#dm00454@亳州 刺史，
 rm#r03381@袁恕己 爲 dm#dm07856@郢州 刺史；
與 rm#r01407@暉 等同立功者皆以爲黨與坐貶。薛思行等
# p 

大置員外官，
自京司及諸州凡二千餘人，
宦官超遷七品以上員外官者又將千人。
# p 

 rm#r04302@魏元忠 自 dm#dm06349@端州 還，
爲相，
不復強諫，
惟與時俯仰；
中外失望。

 dm#dm07987@酸棗 尉 rm#r03386@袁楚客 致書 rm#r04302@元忠 ，
以爲：
「主上新服厥命，
惟新厥徳，
當進君子，
退小人，
以興大化，
豈可安其榮寵，
循默而已！

今不早建太子，
擇師傅而輔之，
一失也。

公主開府置僚屬，
二失也。

崇長緇衣，
使遊走權門，
借勢納賂，
三失也。

俳優小人，
盜竊品秩，
四失也。

有司選進賢才，
皆以貨取勢求，
五失也。

寵進宦者，
殆滿千人，
爲長亂之階，
六失也。

王公貴戚，
賞賜無度，
競爲侈靡，
七失也。

廣置員外官，
傷財害民，
八失也。

先朝宮女，
得自便居外，
出入無禁，
交通請謁，
九失也。

左道之人，
熒惑主聽，
盜竊祿位，
十失也。

凡此十失，
君侯不正，
誰與正之哉！」

 rm#r04302@元忠 得書，
愧謝而已。
# p 

夏，
四月，
改贈后父 rm#r03832@韋玄貞 爲 rm#r03832@酆王 ，
后四弟皆贈郡王。

# p 

己丑，
左散騎常侍、同中書門下三品 rm#r01777@李懷遠 致仕。
# p 

處士 rm#r06049@韋月將 上書告 rm#r02294@武三思 潛通宮掖，
必爲逆亂；
上大怒，
命斬之。

黄門侍郎 rm#r00813@宋璟 奏請推按，
上益怒，
不及整巾，
屣履出側門，
謂 rm#r00813@璟 曰：
「朕謂已斬，
乃猶未邪！」

命趨斬之。

 rm#r00813@璟 曰：
「人言宮中私於 rm#r02294@三思 ，
陛下不問而誅之，
臣恐天下必有竊議。」

固請按之，
上不許，
 rm#r00813@璟 曰：
「必欲斬 rm#r06049@月將 ，
請先斬臣！

不然，
臣終不敢奉詔。」

上怒少解。

左御史大夫 rm#r03323@蘇珦 、給事中 rm#r01306@徐堅 、大理卿 dm#dm08170@長安  rm#r00872@尹思貞 皆以爲方夏行戮，
有違時令。

上乃命與杖，
流 dm#dm02527@嶺南 。

過秋分一日，
平曉，
 dm#dm02733@廣州 都督 rm#rw0002@周仁軌 斬之。
京兆
# p 

御史大夫 rm#r03479@李承嘉 附 rm#r02294@武三思 ，
詆 rm#r00872@尹思貞 於朝，
 rm#r00872@思貞 曰：
「公附會姦臣，
將圖不軌，
先除忠臣邪！」

 rm#r03479@承嘉 怒，
劾奏 rm#r00872@思貞 ，
出爲 dm#dm08665@青州 刺史。

或謂 rm#r00872@思貞 曰：
「公平日訥於言，
及廷折 rm#r03479@承嘉 ，
何其敏邪？」
 rm#r00872@思貞 曰：
「物不能鳴者，
激之則鳴。

 rm#r03479@承嘉 恃威權相陵，
僕義不受屈，
亦不知言之從何而至也。」

# p 

 rm#r02294@武三思 惡 rm#r00813@宋璟 ，
出之檢校 dm#dm07514@貝州 刺史。

# p 

五月，
庚申，
葬 rm#r02293@則天大聖皇后 於 dm#dm00360@乾陵 。
# p 

 rm#r02294@武三思 使 rm#r06265@鄭愔 告 dm#dm03687@朗州 刺史 rm#r01407@敬暉 、 dm#dm00454@亳州 刺史 rm#r02120@韋彦範 、 dm#dm07274@襄州 刺史 rm#r01188@張柬之 、 dm#dm07856@郢州 刺史 rm#r03381@袁恕己 、 dm#dm01472@均州 刺史 rm#r00958@崔玄暐 與 rm#r02606@王同皎 通謀，
六月，
戊寅，
貶 dm#dm03599@暉崖州 司馬，
 rm#r02120@彦範  dm#dm05487@瀧州 司馬，
 rm#r01188@柬之  dm#dm03342@新州 司馬，
 rm#r03381@恕己  dm#dm06328@竇州 司馬，
 rm#r00958@玄暐  dm#dm05883@白州 司馬，
竝員外置，
仍長任，
削其勳封；
復 rm#r02120@彦範 姓 rm#no@桓氏 。
# p 

初，
 rm#r03832@韋玄貞 流 dm#dm04208@欽州 而卒，
蠻酋 rm#r05668@甯承基 兄弟逼取其女，
妻 rm#r00885@崔氏 不與，
 rm#r05668@承基 等殺之，
及其四男 rm@洵 、 rm@浩 、 rm@洞 、 rm@泚 ，
上命 dm#dm02733@廣州 都督 rm#rw0002@周仁軌 使將兵二萬討之。

 rm#r05668@承基 等亡入海，
 rm#rw0002@仁軌 追斬之，
以其首祭 rm#r00885@崔氏 墓，
殺掠其部衆殆盡。

上喜，
加 rm#rw0002@仁軌 鎭國大將軍，
充五府大使，
賜爵 rm#rw0002@汝南郡公 。

 rm#xjts18722@韋后 隔簾拜 rm#rw0002@仁軌 ，
以父事之。

及 rm#xjts18722@韋后 敗，
 rm#rw0002@仁軌 以黨與誅。

# p 

秋，
七月，
戊申，
立 rm#r03066@衞王重俊 爲太子。

太子性明果，
而官屬率貴遊子弟，
所爲多不法；
左庶子 rm#r00633@姚珽 屡諫，
不聽，
 rm#r00633@珽 ，
 rm#r00620@璹 之弟也。

# p 

丙寅，
以 rm#r01714@李嶠 爲中書令。
# p 

上將還 dm#dm07290@西京 ，
辛未，
左散騎常侍 rm#r01777@李懷遠 同中書門下三品，
充 dm#dm03880@東都 留守。


# p 

 rm#r02294@武三思 陰令人疏皇后穢行，
牓於 dm#dm01750@天津橋 ，
請加廢黜。

上大怒，
命御史大夫 rm#r03479@李承嘉 窮覈其事。

 rm#r03479@承嘉 奏言：
「 rm#r01407@敬暉 、 rm#r02120@桓彦範 、 rm#r01188@張柬之 、 rm#r03381@袁恕己 、 rm#r00958@崔玄暐 使人爲之，
雖云廢后，
實謀大逆，
請族誅之。」

 rm#r02294@三思 又使 rm#r00790@安樂公主 譖之於内，
侍御史 rm#r06265@鄭愔 言之於外，
上命法司結竟。

大理丞 dm#dm00119@三原  rm#r01823@李朝隱 奏稱：
「 rm#r01407@暉 等未經推鞫，
不可遽就誅夷。」

大理丞 rm#r05854@裴談 奏稱：
「 rm#r01407@暉 等宜據制書處斬籍沒，
不應更加推鞫。」

上以 rm#r01407@暉 等嘗賜鐵券，
許以不死，
乃長流 rm#r01407@暉 於 dm#dm05765@瓊州 ，
 rm#r02120@彦範 於 dm#dm05492@瀼州 ，
 rm#r01188@柬之 於 dm#dm05487@瀧州 ，
 rm#r03381@恕己 於 dm#dm05759@環州 ，
 rm#r00958@玄暐 於 dm#dm01142@古州 ，
子弟年十六以上，
皆流嶺外。

擢 rm#r03479@承嘉 爲金紫光祿大夫，
進爵 rm#r03479@襄武郡公 ，
 rm#r05854@談 爲刑部尚書；
出 rm#r01823@李朝隱 爲聞喜令。
# p 

 rm#r02294@三思 又諷太子上表，
請夷 rm#r01407@暉 等三族；
上不許。
# p 

中書舍人 rm#r00950@崔湜 説 rm#r02294@三思 曰：
「 rm#r01407@暉 等異日北歸，
終爲後患，
不如遣使矯制殺之。」

 rm#r02294@三思 問誰可使者，
 rm#r00950@湜 薦大理正 rm#r05120@周利用 。

 rm#r05120@利用 先爲五王所惡，
貶 dm#dm01417@嘉州 司馬，
乃以 rm#r05120@利用 攝右臺侍御史，
奉使 dm#dm02532@嶺外 。

比至，
 rm#r01188@柬之 、 rm#r00958@玄暐 已死，
遇 rm#r02120@彦範 於 dm#dm07521@貴州 ，
令左右縛之，
曳於竹槎之上，
肉盡至骨，
然後杖殺。

得 rm#r01407@暉 ，
咼而殺之。

 rm#r03381@恕己 素服黄金，
 rm#r05120@利用 逼之使飮野葛汁，
盡數升不死，
不勝毒憤，
掊地，
爪甲殆盡，
仍捶殺之。

 rm#r05120@利用 還，
擢拜御史中丞。

 rm#r03280@薛季昶 累貶 dm#dm00623@儋州 司馬，
飮藥死。
用貞用貞用貞用貞用貞
# p 

 rm#r02294@三思 既殺五王，
權傾人主，
常言：
「我不知代間何者謂之善人，
何者謂之惡人；
但於我善者則爲善人，
於我惡者則爲惡人耳。」

# p 

時兵部尚書 rm#r00825@宗楚客 、將作大匠 rm#r00824@宗晉卿 、大府卿 rm#r03072@紀處訥 、鴻臚卿 rm@甘元柬 皆爲 rm#r02294@三思 羽翼。

御史中丞 rm#r05120@周利用 、侍御史 rm#r06239@冉祖雍 、太僕丞 rm#r05351@李俊 、光祿丞 rm#r05182@宋之遜 、監察御史 rm#r00634@姚紹之 皆爲 rm#r02294@三思 耳目，
時人謂之五狗。用貞
# p 

九月，
戊午，
左散騎常侍、同中書門下三品 rm#r01777@李懷遠 薨。
# p 

初，
 rm#r01714@李嶠 爲吏部侍郎，
欲樹私恩，
再求入相，
奏大置員外官，
廣引貴勢親識。

既而爲相，
銓衡失序，
府庫減耗，
乃更表言濫官之弊，
且請遜位；
上慰諭不許。
# p 

冬，
十月，
己卯，
車駕發 dm#dm03880@東都 ，
以前檢校 dm#dm00059@幷州 長史 rm#r01095@張仁愿 檢校左屯衞大將軍兼 dm#dm04778@洛州 長史。

戊戌，
車駕至 dm#dm07290@西京 。

十一月，
乙巳，
赦天下。
# p 

丙辰，
以 dm#dm07029@蒲州 刺史 rm#r03032@竇從一 爲 dm#dm08502@雍州 刺史。

 rm#r03032@從一 ，
 rm#r03030@徳玄 之子也，
初名 rm#r03032@懷貞 ，
避皇后父諱，
更名 rm#r03032@從一 ，
多諂附權貴。

 rm#r00603@太平公主 與僧寺爭碾磑，
 dm#dm08502@雍州 司戸 rm#r01625@李元紘 判歸僧寺。

 rm#r03032@從一 大懼，
亟命 rm#r01625@元紘 改判。

 rm#r01625@元紘 大署判後曰：
「南山可移，
此判無動！」

 rm#r03032@從一 不能奪。

 rm#r01625@元紘 ，
 rm#r05434@道廣 之子也。

# p 

初，
祕書監 rm#r05962@鄭普思 納其女於後宮，
監察御史 dm#dm08623@靈昌  rm#r00930@崔日用 劾奏之，
上不聽。

 rm#r05962@普思 聚黨於 dm#dm08502@雍 、 dm#dm02420@岐 二州，
謀作亂。

事覺，
 dm#dm07290@西京 留守 rm#r03324@蘇瓌 收繋，
窮治之。

 rm#r05962@普思 妻 rm#ry0030@第五氏 以鬼道得幸於皇后，
上敕 rm#r03324@瓌 勿治。

及車駕還 dm#dm07290@西京 ，
 rm#r03324@瓌 廷爭之，
上抑瓌而佑普思；
侍御史范獻忠進曰：
「請斬蘇瓌！」

上曰：
「何故？」
對曰：
「 rm#r03324@瓌 爲留守大臣，
不能先斬 rm#r05962@普思 ，
然後奏聞，
使之熒惑聖聽，
其罪大矣。

且 rm#r05962@普思 反状明白，
而陛下曲爲申理。

臣聞王者不死，
殆謂是乎！

臣願先賜死，
不能北面事 rm#r05962@普思 。」

 rm#r04302@魏元忠 曰：
「 rm#r03324@蘇瓌 長者，
用刑不枉。

 rm#r05962@普思 法當死。」

上不得已，
戊午，
流 rm#r05962@普思 於 dm#dm00623@儋州 ，
餘黨皆伏誅。
# p 

十二月，
己卯，
突厥 rm@默啜 寇 dm#dm09011@鳴沙 ，
 dm#dm08628@靈武軍 大總管 rm@沙吒忠義 與戰，
軍敗，
死者六千餘人。

丁巳，
突厥進寇 dm#dm01114@原 、 dm#dm03655@會 等州，
掠 dm#dm08458@隴右 牧馬萬餘匹而去。

免 rm@忠義 官。丁辛
# p 

 dm#dm02061@安西 大都護 rm#r03747@郭元振 詣突騎施烏質勒牙帳議軍事，
天大風雪，
 rm#r03747@元振 立於帳前，
與烏質勒語。

久之，
雪深，
 rm#r03747@元振 不移足；
烏質勒老，
不勝寒，
會罷而卒。

其子 rm@娑葛 勒兵將攻 rm#r03747@元振 ，
副使御史中丞 rm#r03492@解琬 知之，
勸 rm#r03747@元振 夜逃去，
 rm#r03747@元振 曰：
「吾以誠心待人，
何所疑懼！

且深在寇庭，
逃將安適！」

安臥不動。

明旦，
入哭，
甚哀，
 rm@娑葛 感其義，
待 rm#r03747@元振 如初。

戊戌，
以 rm@娑葛 襲 dm#dm01410@嗢鹿州 都督、 rm@懷徳王 。

# p 

 rm#r00790@安樂公主 恃寵驕恣，
賣官鬻獄，
勢傾朝野。

或自爲制敕，
掩其文，
令上署之；
上笑而從之，
竟不視也。

自請爲皇太女，
上雖不從，
亦不譴責。

*** 三年
# year 0707
# p 

春，
正月，
庚戌，
制以突厥 rm@默啜 寇邊，
命内外官各進平突厥之策。

右補闕 rm#r02880@盧俌 上疏，
以爲：
「 rm@郤縠 悦禮樂，
敦詩書，
爲 dyn#ch110@晉 元帥；
 rm#r06216@杜預 射不穿札，
建平 dyn#ch136@呉 之勳。

是知中權制謀，
不取一夫之勇。

如 rm@沙吒忠義 ，
驍將之材，
本不足以當大任。

又，
 dm#dm09011@鳴沙 之役，
主將先逃，
宜正邦憲；
賞罰既明，
敵無不服。

又，
邊州刺史，
宜精擇其人，
使之蒐卒乘，
積資糧，
來則禦之，
去則備之。

去歳四方旱災，
未易興師。

當理内以及外，
綏近以來遠，
俟倉廩實，
士卒練，
然後大舉以討之。」

上善之。
# p 

二月，
丙戌，
上遣 rm#r02317@武攸曁 、 rm#r02294@武三思 詣 dm#dm00360@乾陵 祈雨。

既而雨降，
上喜，
制復 rm@武氏  dm#dm02465@崇恩廟 及 dm#dm03459@昊陵 、 dm#dm08748@順陵 ，
因名 dm#dm07980@酆王廟 曰 dm#dm07257@褒徳 ，
 dm#*dm08361@陵 曰 dm#dm04117@榮先 ；
又詔 dm#dm02465@崇恩廟 齋郎取五品子充。

太常博士 rm#r05492@楊孚 曰：
「太廟皆取七品已下子爲齋郎，
今 dm#dm02465@崇恩廟 取五品子，
未知太廟當如何？」
上命太廟亦準 dm#dm02465@崇恩廟 。

 rm#r05492@孚 曰：
「以臣準君，
猶爲僭逆，
況以君準臣乎！」

上乃止。
# p 

庚寅，
敕改諸州 dm#dm00282@中興寺 、 dm#dm07411@觀 爲 dm#dm09259@龍興 ，
自今奏事不得言中興。

右補闕 rm#r02281@權若訥 上疏，
以爲「天、地、日、月等字皆 rm#r02293@則天 能事，
賊臣 rm#r01407@敬暉 等輕紊前規；
今削之無益於淳化，
存之有光於孝理。

又，
 y@神龍元年 制書，
一事以上，
竝依 y@貞觀 故事，
豈可近捨母儀，
遠尊祖徳！」

疏奏，
手制褒美。

# p 

三月，
庚子，
吐蕃遣其大臣 rm@悉薫熱 入貢。

# p 

夏，
四月，
辛巳，
以上所養 rm#r03679@雍王守禮 女 rm#r03839@金城公主 妻 dm#*dm01250@吐蕃 贊普。

# p 

五月，
戊戌，
以左屯衞大將軍 rm#r01095@張仁愿 爲 dm#dm03681@朔方道 大總管，
以備突厥。
# p 

上以歳旱穀貴，
召太府卿 rm#r03072@紀處訥 謀之。

明日，
 rm#r02294@武三思 使知太史事 rm#r03667@迦葉志忠 奏：
「是夜，
攝提入太微宮，
至帝座，
主大臣宴見納忠於天子。」

上以爲然。

敕稱 rm#r03072@處訥 忠誠，
徹於玄象，
賜衣一襲，
帛六十段。
# p 

六月，
丁卯朔，
日有食之。
# p 

姚巂道討撃使、監察御史 dm#dm03549@晉昌  rm#r05136@唐九徵 撃 dm#dm01898@姚州 叛蠻，
破之，
斬獲三千餘人。
# p 

皇后以 rm#r03066@太子重俊 非其所生，
惡之；
特進 rm#r02294@徳靜王武三思 尤忌太子。

 rm#r00023@上官婕妤 以 rm#r02294@三思 故，
毎下制敕，
推尊 rm#r02293@武氏 。

 rm#r00790@安樂公主 與駙馬左衞將軍 rm#r02306@武崇訓 常陵侮太子，
或呼爲奴。

 rm#r02306@崇訓 又教公主言於上，
請廢太子，
立己爲皇太女。

太子積不能平。
# p 

秋，
七月，
辛丑，
太子與左羽林大將軍 rm#r01671@李多祚 、將軍 rm#r01756@李思沖 、 rm#r01782@李承況 、 rm#r05594@獨孤禕 、 rm@沙吒忠義 等，
矯制發羽林千騎兵三百餘人，
殺 rm#r02294@三思 、 rm#r02306@崇訓 于其第，
幷親黨十餘人。

又使左金吾大將軍 rm#r01370@成王千里 及其子 rm@天水王  rm@禧 分兵守宮城諸門，
太子與 rm#r01671@多祚 引兵自 dm#dm06607@肅章門 斬關而入，
叩閤索 rm#r00023@上官婕妤 。

 rm#r00023@婕妤 大言曰：
「觀其意欲先索 rm#r00023@婉兒 ，
次索皇后，
次及大家。」

上乃與 rm#xjts18722@韋后 、 rm#r00790@安樂公主 、 rm#r00023@上官婕妤 登 dm#dm05694@玄武門 樓以避兵鋒，
使右羽林大將軍 rm#r05075@劉景仁 帥飛騎百餘人屯於樓下以自衞。

 rm#r02155@楊再思 、 rm#r03324@蘇瓌 、 rm#r01714@李嶠 與兵部尚書 rm#r00825@宗楚客 、左衞將軍 rm#r03072@紀處訥 擁兵二千餘人屯 dm#dm01809@太極殿 前，
閉門自守。

 rm#r01671@多祚 先至 dm#dm05691@玄武樓 下，
欲升樓，
宿衞拒之。

 rm#r01671@多祚 與太子狐疑，
按兵不戰，
冀上問之。

宮闈令 dm#dm06077@石城  rm#r03335@楊思勗 在上側，
請撃之。

 rm#r01671@多祚 壻羽林中郎將 rm@野呼利 爲前鋒總管，
 rm#r03335@思勗 挺刃斬之，
 rm#r01671@多祚 軍奪氣。

上據檻俯謂 rm#r01671@多祚 所將千騎曰：
「汝輩皆朕宿衞之士，
何爲從 rm#r01671@多祚 反！

苟能斬反者，
勿患不富貴。」

於是千騎斬 rm#r01671@多祚 、 rm#r01782@承況 、 rm#r00301@禕之 、 rm#d02677@忠義 ，
餘衆皆潰。

 rm#r01370@成王千里 、 rm@天水王  rm@禧 攻 dm#dm01168@右延明門 ，
將殺 rm#r00825@宗楚客 、 rm#r03072@紀處訥 ，
不克而死。

太子以百騎走 dm#dm06424@終南山 、至 dm#dm07933@鄠 西，
能屬者纔數人，
憩於林下，
爲左右所殺。

上以其首獻太廟及祭 rm#r02294@三思 、 rm#r02306@崇訓 之柩，
然後梟之朝堂。

更 rm#r01370@成王千里 姓曰 rm#no@蝮氏 ，
同黨皆伏誅。
之
# p 

東宮僚屬無敢近太子尸者，
唯 dm#dm04385@永和縣 丞 rm#r05666@甯嘉勗 解衣裹太子首號哭，
貶 dm#dm06772@興平 丞。

# p 

太子兵所經諸門守者皆坐流；
 rm#r00840@韋氏 之黨奏請悉誅之，
上更命法司推斷。

大理卿 dm#dm02096@宋城  rm#r03791@鄭惟忠 曰：
「大獄始決，
人心未安，
若復有改推，
則反仄者衆矣。」

上乃止。


# p 

以 rm#r03335@楊思勗 爲銀青光祿大夫，
行内常侍。

癸卯，
赦天下。
# p 

贈 rm#r02294@武三思 太尉、 rm@梁宣王 ，
 rm#r02306@武崇訓 開府儀同三司、 rm@魯忠王 。

 rm#r00790@安樂公主 請用 rm#r02386@永泰公主 故事，
以 rm#r02306@崇訓 墓爲陵，
給事中 rm#r02925@盧粲 駮之，
以爲「 rm#r02386@永泰 事出特恩，
今 rm@魯王 主壻，
不可爲比。」

上手敕曰：
「 y@安樂 與 rm#r02386@永泰 無異，
同穴之義，
今古不殊。」

 rm#r02925@粲 又奏：
「陛下以膝下之愛施及其夫，
豈可使上下無辨，
君臣一貫哉！」

上乃從之。

公主怒，
出 rm#r02925@粲 爲 dm#dm08351@陳州 刺史。

# p 

 dm#dm07281@襄邑 尉 dm#dm07284@襄陽  rm#r01021@席豫 聞 rm#r00790@安樂公主 求爲太女，
歎曰：
「 rm#xjts23567@梅福 譏切 rm#r02658@王氏 ，
獨何人哉！」

乃上書請立太子，
言甚深切。

 rm#r00603@太平公主 欲表爲諫官，
 rm#r01021@豫 恥之，
逃去。
# p 

八月，
戊寅，
皇后及王公已下表上尊號曰 rm#r01656@應天神龍皇帝 ，
改 dm#dm05694@玄武門 爲 dm#dm06228@神武門 ，
樓爲 dm#dm00763@制勝樓 。

 rm#r00825@宗楚客 又帥百官表請加皇后尊號曰 rm@順天翊聖皇后 。

上竝許之。
# p 

初，
右臺大夫 rm#r03323@蘇珦 治 rm#r03066@太子重俊 之黨，
囚有引 rm@相王 者，
 rm#r03323@珦 密爲之申理，
上乃不問。

自是 rm#r00790@安樂公主 及兵部尚書 rm#r00825@宗楚客 日夜謀譖 rm@相王 ，
使侍御史 rm#r06239@冉祖雍 誣奏 rm@相王 及 rm#r00603@太平公主 ，
云「與 rm#r03066@重俊 通謀，
請收付制獄。」

上召吏部侍郎兼御史中丞 rm#r03254@蕭至忠 ，
使鞫之，
 rm#r03254@至忠 泣曰：
「陛下富有四海，
不能容一弟一妹，
而使人羅織害之乎！

 rm@相王 昔爲皇嗣，
固請於 rm#r02293@則天 ，
以天下讓陛下，
累日不食，
此海内所知。

奈何以 rm#r06239@祖雍 一言而疑之！」

上素友愛，
遂寢其事。
# p 

右補闕 dm#dm04861@浚儀  rm#r00406@呉兢 聞 rm#r06239@祖雍 之謀，
上疏，
以爲：
「自 y@文明 以來，
國之祚胤，
不絶如綫，
陛下龍興，
恩及九族，
求之瘴海，
升之闕庭。

況 rm@相王 同氣至親，
六合無貳，
而賊臣日夜連謀，
乃欲陷之極法；
禍亂之根，
將由此始。

夫任以權則雖疏必重，
奪其勢則雖親必輕。

自古委信異姓，
猜忌骨肉，
以覆國亡家者，
幾何人矣。

況國家枝葉無幾，
陛下登極未久，
而一子以弄兵受誅，
一子以愆違遠竄，
惟餘一弟朝夕左右，
尺布斗粟之譏，
不可不愼，
青蠅之詩，
良可畏也。」


# p 

 rm@相王 寛厚恭謹，
安恬好讓，
故經 rm#r02293@武 、 rm#r03995@韋 之世，
竟免於難。


# p 

初，
右僕射、中書令 rm#r04302@魏元忠 以 rm#r02294@武三思 權，
意常憤鬱。

及 rm#r03066@太子重俊 起兵，
遇 rm#r04302@元忠 子太僕少卿 rm@升 於 dm#dm04403@永安門 ，
脅以自隨；
太子死，
 rm@幷 爲亂兵所殺。

 rm#r04302@元忠 揚言曰：
「元惡已死，
雖鼎鑊何傷！

但惜太子隕沒耳。」

上以其有功，
且爲 rm#r01837@高宗 、 rm#r02293@武后 所重，
故釋不問。

兵部尚書 rm#r00825@宗楚客 、太府卿 rm#r03072@紀處訥 等共證 rm#r04302@元忠 ，
云「與太子通謀，
請夷其三族。」

制不許。

 rm#r04302@元忠 懼，
表請解官爵，
以散秩還第。

丙戌，
上手敕聽解僕射，
以特進、 rm@齊公 致仕，
仍朝朔望。
幷升
# p 

九月，
丁卯，
以吏部侍郎 rm#r03254@蕭至忠 爲黄門侍郎，
兵部尚書 rm#r00825@宗楚客 爲左衞將軍，
兼太府卿 rm#r03072@紀處訥 爲太府卿，
竝同中書門下三品；
中書侍郎、同中書門下三品 rm#r05012@于惟謙 罷爲國子祭酒。