
* 　唐紀一
** 武徳
*** 武徳元年
# year 0618
# p 

春，
正月，
丁未朔，
 rm#rt0782@隋恭帝 詔 rm#r04258@唐王 劍履上殿，
贊拜不名。

# p 

 rm#r04258@唐王 既克 dm#dm08170@長安 ，
以書諭諸郡縣，
於是東自 dm#dm01383@商洛 ，
南盡 dm#dm02566@巴 、 dm#dm07197@蜀 ，
郡縣長吏及盜賊渠帥、氐、羌酋長，
爭遣子弟入見請降，
有司復書，
日以百數。

# p 

 rm#r02590@王世充 既得 dm#dm03880@東都 兵，
進撃 rm#r01704@李密 於 dm#dm04761@洛 北，
敗之，
遂屯 dm#dm08719@鞏 北。

辛酉，
 rm#r02590@世充 命諸軍各造浮橋渡 dm#dm04761@洛 撃 rm#r01704@密 ，
橋先成者先進，
前後不一。

虎賁郎將 rm#r06711@王辯 破 rm#r01704@密 外柵，
 rm#r01704@密 營中驚擾，
將潰；
 rm#r02590@世充 不知，
鳴角收衆，
 rm#r01704@密 因帥敢死士乘之，
 rm#r02590@世充 大敗，
爭橋溺死者萬餘人。

 rm#r06711@王辯 死，
 rm#r02590@世充 僅自免，
 dm#dm04761@洛 北諸軍皆潰。

 rm#r02590@世充 不敢入 dm#dm03880@東都 ，
北趣 dm#dm04709@河陽 ，
是夜，
疾風寒雨，
軍士渉水沾濕，
道路凍死者又以萬數。

 rm#r02590@世充 獨與數千人至 dm#dm04709@河陽 ，
自繋獄請罪，
 rm#rt0783@越王侗 遣使赦之，
召還 dm#dm03880@東都 ，
賜金帛、美女以安其意。

 rm#r02590@世充 收合亡散，
得萬餘人，
屯 dm#dm01267@含嘉城 ，
不敢復出。

# p 

 rm#r01704@密 乘勝進據 dm#dm08018@金墉城 ，
脩其門堞、廬舍而居之，
鉦鼓之聲，
聞於 dm#dm03880@東都 ；
未幾，
擁兵三十萬，
陳於 dm#dm00893@北邙 ，
南逼 dm#dm00167a@上春門 。

乙丑，
金紫光祿大夫 rm#r05551@段達 、民部尚書 rm#r06841@韋津 出兵拒之；
 rm#r05551@達 望見 rm#r01704@密 兵盛，
懼而先還，
 rm#r01704@密 縱兵乘之，
軍遂潰，
 rm#r06841@韋津 死。

於是 dm#dm00606@偃師 、 dm#dm03953@柏谷 及 dm#dm04709@河陽 都尉 rm#r05592@獨孤武都 、檢校 dm#dm04655@河内郡 丞 rm#r05462@柳燮 、職方郎 rm#r05463@柳續 等各舉所部降於 rm#r01704@密 。

 rm#r03028@竇建徳 、 rm#r01583@朱粲 、 rm#rz0003@孟海公 、 rm#r01305@徐圓朗 等竝遣使奉表勸進，
 rm#r01704@密 官屬 rm#r06251@裴仁基 等亦上表請正位號，
 rm#r01704@密 曰：
「 dm#dm03880@東都 未平，
不可議此。」

# p 

戊辰，
 rm#r04258@唐王 以世子 rm#r01078@建成 爲左元帥，
 rm#r01602@秦公世民 爲右元帥，
督諸軍十餘萬人救 dm#dm03880@東都 。
# p 

 dm#dm03880@東都 乏食，
太府卿 rm#r05044@元文都 等募守城不食公糧者進散官二品；
於是商賈執象而朝者，
不可勝數。

# p 

二月，
己卯，
 rm#r04258@唐王 遣太常卿 rm#r03778@鄭元璹 將兵出 dm#dm01383@商洛 ，
徇 dm#dm01077@南陽 ，
左領軍府司馬 dm#dm02081@安陸  rm#r04168@馬元規 徇 dm#dm02081@安陸 及 dm#dm06880@荊 、 dm#dm07261@襄 。

# p 

 rm#r01704@李密 遣 rm#r01380@房彦藻 、 rm#rz0004@鄭頲 等東出 dm#dm09166@黎陽 ，
分道招慰州縣。

以 dm#dm04048@梁郡 太守 rm#r06219@楊汪 爲上柱國、 dm#dm02098@宋州 總管，
又以手書與之曰：
「昔在 dm#dm08496@雍丘 ，
曾相追捕，
射鉤斬袂，
不敢庶幾。」

 rm#r06219@汪 遣使往來通意，
 rm#r01704@密 亦羈縻待之。

 rm#r01380@彦藻 以書招 rm#r03028@竇建徳 ，
使來見 rm#r01704@密 。

 rm#r03028@建徳 復書，
卑辭厚禮，
託以 rm#r03089@羅藝 南侵，
請捍禦北垂。

 rm#r01380@彦藻 還，
至 dm#dm00029@衞州 ，
賊帥 rm#r06232@王徳仁 邀殺之。

 rm#r06232@徳仁 有衆數萬，
據 dm#dm03924@林慮山 ，
四出抄掠，
爲數州之患。

# p 

三月，
己酉，
以 rm#r01016@齊公元吉 爲鎭北將軍、 dm#dm01779@太原道 行軍元帥、都督十五郡諸軍事，
聽以便宜從事。
# p 

 rm#rt0779@隋煬帝 至 dm#dm04510@江都 ，
荒淫益甚，
宮中爲百餘房，
各盛供張，
實以美人，
日令一房爲主人。

 dm#dm04514@江都郡 丞 rm#r05896@趙元楷 掌供酒饌，
帝與 rm#rz0007@蕭后 及幸姬歴就宴飮，
酒卮不離口，
從姬千餘人亦常醉。

然帝見天下危亂，
意亦擾擾不自安，
退朝則幅巾短衣，
策杖歩遊，
徧歴臺館，
非夜不止，
汲汲顧景，
唯恐不足。
# p 

帝自曉占候卜相，
好爲 dm#dm01275@呉 語；
常夜置酒，
仰視天文，
謂 rm#rz0007@蕭后 曰：
「外間大有人圖儂，
然儂不失爲 rm#rt0720@長城公 ，
卿不失爲 rm#rz0008@沈后 ，
且共樂飮耳！」

因引滿沈醉。

又嘗引鏡自照，
顧謂 rm#rz0007@蕭后 曰：
「好頭頸，
誰當斫之！」

后驚問故，
帝笑曰：
「貴賤苦樂，
更迭爲之，
亦復何傷！」


# p 

帝見中原已亂，
無心北歸，
欲都 dm#dm00299@丹陽 ，
保據 dm#dm04494@江東 ，
命羣臣廷議之，
内史侍郎 rm#r06248@虞世基 等皆以爲善；
右候衞大將軍 rm#r05392@李才 極陳不可，
請車駕還 dm#dm08170@長安 ，
與 rm#r06248@世基 忿爭而出。

門下録事 dm#dm07232@衡水  rm#r01827@李桐客 曰：
「 dm#dm04494@江東 卑濕，
土地險狹，
内奉萬乘，
外給三軍，
民不堪命，
亦恐終散亂耳。」

御史劾 rm#r01827@桐客 謗毀朝政。

於是公卿皆阿意言：
「 dm#dm04494@江東 之民望幸已久，
陛下過 dm#dm04475@江 ，
撫而臨之，
此 rm#rt0008@大禹 之事也。」

乃命治 dm#dm00301@丹陽宮 ，
將徙都之。

# p 

時 dm#dm04510@江都 糧盡，
從駕驍果多 dm#dm08281@關中 人，
久客思郷里，
見帝無西意，
多謀叛歸，
郎將 rm#r05736@竇賢 遂帥所部西走，
帝遣騎追斬之，
而亡者猶不止，
帝患之。

虎賁郎將 dm#dm03177@扶風  rm#r06160@司馬徳戡 素有寵於帝，
帝使領驍果屯於東城，
 rm@徳戡 與所善虎賁郎將 rm#r06148@元禮 、直閤 rm#r06258@裴虔通 謀曰：
「今驍果人人欲亡，
我欲言之，
恐先事受誅；
不言，
於後事發，
亦不免族滅，
奈何？
又聞 dm#dm08283@關内 淪沒，
 rm#r05368@李孝常 以 dm#dm06943@華陰 叛，
上囚其二弟，
欲殺之。

我輩家屬皆在西，
能無此慮乎！」

二人皆懼，
曰：
「然則計將安出？」
 rm#r06160@徳戡 曰：
「驍果若亡，
不若與之倶去。」

二人皆曰：
「善！」

因轉相招引，
内史舍人 rm#r05043@元敏 、虎牙郎將 rm#r05914@趙行樞 、鷹揚郎將 rm#r05154@孟秉 、符璽郎 rm#r05585@牛方裕 、直長 rm#r05860@許弘仁 、 rm#r05796@薛世良 、城門郎 rm#r05139@唐奉義 、醫正 rm#r06185@張愷 、勳侍 rm#r05491@楊士覽 等皆與之同謀，
日夜相結約，
於廣座明論叛計，
無所畏避。

有宮人白 rm#rz0007@蕭后 曰：
「外間人人欲反。」

后曰：
「任汝奏之。」

宮人言於帝，
帝大怒，
以爲非所宜言，
斬之。

其後宮人復白后，
后曰：
「天下事一朝至此，
無可救者，
何用言之，
徒令帝憂耳！」

自是無復言者。李覆
# p 

 rm#r05914@趙行樞 與將作少監 rm#r05169@宇文智及 素厚，
 rm#r05491@楊士覽 ，
 rm#r05169@智及 之甥也，
二人以謀告 rm#r05169@智及 ；
 rm#r05169@智及 大喜。

 rm#r06160@徳戡 等期以三月望日結黨西遁，
 rm#r05169@智及 曰：
「主上雖無道，
威令尚行，
卿等亡去，
正如 rm#r05736@竇賢 取死耳。

今天實喪 dyn#ch174@隋 ，
英雄竝起，
同心叛者已數萬人，
因行大事，
此帝王之業也。」

 rm#r06160@徳戡 等然之。

 rm#r05914@行樞 、 rm#r05796@薛世良 請以 rm#r05169@智及 兄右屯衞將軍 rm#r00748@許公化及 爲主，
結約既定，
乃告 rm#r00748@化及 。

 rm#r00748@化及 性駑怯，
聞之，
變色流汗，
既而從之。

# p 

 rm#r06160@徳戡 使 rm#r05860@許弘仁 、 rm#r06185@張愷 入備身府，
告所識者云：
「陛下聞驍果欲叛，
多醞毒酒，
欲因享會，
盡鴆殺之，
獨與南人留此。」

驍果皆懼，
轉相告語，
反謀益急。

乙卯，
 rm#r06160@徳戡 悉召驍果軍吏，
諭以所爲，
皆曰：
「唯將軍命！」

是日，
風霾晝昏。

晡後，
 rm#r06160@徳戡 盜御廐馬，
潛厲兵刃。

是夕，
 rm#r06148@元禮 、 rm#r06258@裴虔通 直閤下，
專主殿内；
 rm#r05139@唐奉義 主閉城門，
與 rm#r06258@虔通 相知，
諸門皆不下鍵。

至三更，
 rm#r06160@徳戡 於東城集兵得數萬人，
舉火與城外相應。

帝望見火，
且聞外諠囂，
問何事。

 rm#r06258@虔通 對曰：
「草坊失火，
外人共救之耳。」

時内外隔絶，
帝以爲然。

 rm#r05169@智及 與 rm#r05154@孟秉 於城外集千餘人，
劫候衞虎賁 rm#r06088@馮普樂 布兵分守衢巷。

 rm#rz0011@燕王倓 覺有變，
夜，
穿 dm#dm06836@芳林門 側水竇而入，
至 dm#dm05694@玄武門 ，
詭奏曰：
「臣猝中風，
命懸俄頃，
請得面辭。」

 rm#r06258@裴虔通 等不以聞，
執囚之。

丙辰，
天未明，
 rm#r06160@徳戡 授 rm#r06258@虔通 兵，
以代諸門衞士。

 rm#r06258@虔通 自門將數百騎至 dm#dm03146@成象殿 ，
宿衞者傳呼有賊，
 rm#r06258@虔通 乃還，
閉諸門，
獨開東門，
驅殿内宿衞者令出，
皆投仗而走。

右屯衞將軍 rm#r05593@獨孤盛 謂 rm#r06258@虔通 曰：
「何物兵勢太異！」

 rm#r06258@虔通 曰：
「事勢已然，
不預將軍事；
將軍愼毋動！」

 rm#r05593@盛 大罵曰：
「老賊，
是何物語！」

不及被甲，
與左右十餘人拒戰，
爲亂兵所殺。

 rm#r05593@盛 ，
 rm#r06694@楷 之弟也。

千牛 rm#r05595@獨孤開遠 帥殿内兵數百人詣 dm#dm05697@玄覽門 ，
叩閤請曰：
「兵仗尚全，
猶堪破賊。

陛下若出臨戰，
人情自定；
不然，
禍今至矣。」

竟無應者，
軍士稍散。

賊執 rm#r05595@開遠 ，
義而釋之。

先是，
帝選驍健官奴數百人置 dm#dm05694@玄武門 ，
謂之給使，
以備非常，
待遇優厚，
至以宮人賜之。

司宮 rm#rz0013@魏氏 爲帝所信，
 rm#r00748@化及 等結之使爲内應。

是日，
 rm#rz0013@魏氏 矯詔悉聽給使出外，
倉猝際制無一人在者。
# p 

 rm#r06160@徳戡 等引兵自 dm#dm05694@玄武門 入，
帝聞亂，
易服逃於西閤。

 rm#r06258@虔通 與 rm#r06148@元禮 進兵排左閤，
 rm#rz0013@魏氏 啓之，
遂入 dm#dm04411@永巷 ，
問：
「陛下安在？」
有美人出，
指之。

校尉 rm#r05017@令狐行達 拔刀直進，
帝映窗扉謂 rm#r05017@行達 曰：
「汝欲殺我邪？」
對曰：
「臣不敢，
但欲奉陛下西還耳。」

因扶帝下閤。

 rm#r06258@虔通 ，
本帝爲 rm#rt0779@晉王 時親信左右也，
帝見之，
謂曰：
「卿非我故人乎！

何恨而反？」
對曰：
「臣不敢反，
但將士思歸，
欲奉陛下還 dm#dm08170@京師 耳。」

帝曰：
「朕方欲歸，
正爲 dm#dm00174@上江 米船未至，
今與汝歸耳！」

 rm#r06258@虔通 因勒兵守之。
# p 

至旦，
 rm#r05154@孟秉 以甲騎迎 rm#r00748@化及 ，
 rm#r00748@化及 戰栗不能言，
人有來謁之者，
但俛首據鞍稱罪過。

 rm#r00748@化及 至城門，
 rm#r06160@徳戡 迎謁，
引入朝堂，
號爲丞相。

 rm#r06258@裴虔通 謂帝曰：
「百官悉在朝堂，
陛下須親出慰勞。」

進其從騎，
逼帝乘之；
帝嫌其鞍勒弊，
更易新者，
乃乘之。

 rm#r06258@虔通 執轡挾刀出宮門，
賊徒喜譟動地。

 rm#r00748@化及 揚言曰：
「何用持此物出，
亟還與手。」

帝問：
「 rm#r06248@世基 何在？」
賊黨 rm#r06075@馬文舉 曰：
「已梟首矣！」

於是引帝還至寢殿，
 rm#r06258@虔通 、 rm#r06160@徳戡 等拔白刃侍立。

帝歎曰：
「我何罪至此？」
 rm#r06075@文舉 曰：
「陛下違棄宗廟，
巡遊不息，
外勤征討，
内極奢淫，
使丁壯盡於矢刃，
女弱填於溝壑，
四民喪業，
盜賊𧔧起；
專任佞諛，
飾非拒諫：
何謂無罪！」

帝曰：
「我實負百姓；
至於爾輩，
榮祿兼極，
何乃如是！

今日之事，
孰爲首邪？」
 rm#r06160@徳戡 曰：
「溥天同怨，
何止一人！」

 rm#r00748@化及 又使 rm#r00851@封徳彞 數帝罪，
帝曰：
「卿乃士人，
何爲亦爾？」
 rm#r00851@徳彞 赧然而退。

帝愛子 rm#rz0015@趙王杲 ，
年十二，
在帝側，
號慟不已，
 rm#r06258@虔通 斬之，
血濺御服。

賊欲弑帝，
帝曰：
「天子死自有法，
何得加以鋒刃！

取鴆酒來！」

 rm#r06075@文舉 等不許，
使 rm#r05017@令狐行達 頓帝令坐。

帝自解練巾授 rm#r05017@行達 ，
縊殺之。

初，
帝自知必及於難，
常以甖貯毒藥自隨，
謂所幸諸姬曰：
「若賊至，
汝曹當先飮之，
然後我飮。」

及亂，
顧索藥，
左右皆逃散，
竟不能得。

 rm#rz0007@蕭后 與宮人撤漆牀板爲小棺，
與 rm#rz0015@趙王杲 同殯於西院 dm#dm04848@流珠堂 。
# p 

帝毎巡幸，
常以 rm#rz0016@蜀王秀 自隨，
囚於驍果營。

 rm#r00748@化及 弑帝，
欲奉立之，
衆議不可，
乃殺 rm#rz0016@秀 及其七男。

又殺 rm#rz0017@齊王暕 及其二子幷 rm#rz0011@燕王倓 ，
 dyn#ch174@隋氏 宗室、外戚，
無少長皆死。

唯 rm#rt0780@秦王浩 素與 rm#r05169@智及 往來，
且以計全之。

 rm#rz0017@齊王暕 素失愛於帝，
恆相猜忌，
帝聞亂，
顧 rm#rz0007@蕭后 曰：
「得非 rm#rz0017@阿孩 邪？」
 rm#r00748@化及 使人就第誅 rm#rz0017@暕 ，
 rm#rz0017@暕 謂帝使收之，
曰：
「詔使且緩兒，
兒不負國家！」

賊曳至街中，
斬之，
 rm#rz0017@暕 竟不知殺者爲誰，
父子至死不相明。

又殺内史侍郎 rm#r06248@虞世基 、御史大夫 rm#r05851@裴蘊 、左翊衞大將軍 rm#r05033@來護兒 、祕書監 rm#r05833@袁充 、右翊衞將軍 rm#r06171@宇文協 、千牛 rm#r06175@宇文皛 、 rm#r06754@梁公蕭鉅 等及其子。

 rm#r06754@鉅 ，
 rm#rt0714@琮 之弟子也。

# p 

難將作，
 dm#dm04522@江陽 長 rm#r05277@張惠紹 馳告 rm#r05851@裴蘊 ，
與 rm#r05277@惠紹 謀矯詔發郭下兵收 rm#r00748@化及 等，
扣門援帝。

議定，
遣報 rm#r06248@虞世基 ；
 rm#r06248@世基 疑告反者不實，
抑而不許。

須臾，
難作，
 rm#r05851@蘊 歎曰：
「謀及 rm#r06248@播郎 ，
竟誤人事！」

 rm#r06248@虞世基 宗人 rm#rz0019@伋 謂 rm#r06248@世基 子符璽郎 rm#rz0020@熙 曰：
「事勢已然，
吾將濟卿南渡，
同死何益！」

 rm#rz0020@熙 曰：
「棄父背君，
求生何地！

感尊之懷，
自此決矣！」

 rm#r06248@世基 弟 rm#r03353@世南 抱 rm#r06248@世基 號泣請代，
 rm#r00748@化及 不許。

黄門侍郎 rm#r03452@裴矩 知必將有亂，
雖廝役皆厚遇之，
又建策爲驍果娶婦；
及亂作，
賊皆曰：
「非 rm#r03452@裴黄門 之罪。」

既而 rm#r00748@化及 至，
 rm#r03452@矩 迎拜馬首，
故得免。

 rm#r00748@化及 以 rm#r06246@蘇威 不預朝政，
亦免之。

 rm#r06246@威 名位素重，
往參 rm#r00748@化及 ；
 rm#r00748@化及 集衆而見之，
曲加殊禮。

百官悉詣朝堂賀，
給事郎 rm#r05858@許善心 獨不至。

 rm#r05860@許弘仁 馳告之曰：
「天子已崩，
 rm#r00748@宇文將軍 攝政，
闔朝文武咸集，
天道人事自有代終，
何預於叔而低囘若此！」

 rm#r05858@善心 怒，
不肯行。

 rm#r05860@弘仁 反走上馬，
泣而去。

 rm#r00748@化及 遣人就家擒至朝堂，
既而釋之。

 rm#r05858@善心 不舞蹈而出，
 rm#r00748@化及 怒曰：
「此人大負氣！

」
復命擒還，
殺之。

其母 rm#rz0021@范氏 ，
年九十二，
撫柩不哭，
曰：
「能死國難，
吾有子矣！」

因臥不食，
十餘日而卒。

 rm#r04258@唐王 之入關也，
 rm#r05263@張季珣 之弟 rm#rz0022@仲琰 爲 dm#dm00175@上洛 令，
帥吏民拒守，
部下殺之以降。

 rm#r00748@宇文化及 之亂，
 rm#rz0022@仲琰 弟 rm#rz0023@琮 爲千牛左右，
 rm#r00748@化及 殺之，
兄弟三人皆死國難，
時人愧之。以身
# p 

 rm#r00748@化及 自稱大丞相，
總百揆。

以皇后令立 rm#rt0780@秦王浩 爲帝，
居別宮，
令發詔畫敕書而已，
仍以兵監守之。

 rm#r00748@化及 以弟 rm#r05169@智及 爲左僕射，
 rm#r00750@士及 爲内史令，
 rm#r03452@裴矩 爲右僕射。

# p 

乙卯，
徙 rm#r01602@秦公世民 爲 rm#r01602@趙公 。


# p 

戊辰，
 dyn#ch174@隋  rm#rt0782@恭帝 詔以十郡益 dm#dm01358@唐國 ，
仍以 rm#r04258@唐王 爲相國，
總百揆，
 dm#dm01358@唐國 置丞相以下官，
又加九錫。

王謂僚屬曰：
「此諂諛者所爲耳。

孤秉大政而自加寵錫，
可乎！

必若循 dyn#ch134@魏 、 dyn#ch537@晉 之迹，
彼皆繁文僞飾，
欺天罔人；
考其實不及五霸，
而求名欲過三王，
此孤常所非笑，
竊亦恥之。」

或曰：
「歴代所行，
亦何可廢！」

王曰：
「 rm#rt0006@堯 、 rm#rt0007@舜 、 rm#rt0027@湯 、 rm#rt0064@武 ，
各因其時，
取與異道，
皆推其至誠以應天順人，
未聞 dyn#ch101@夏 、 dyn#ch102@商 之末必效 rm#rt0006@唐 、 rm#rt0007@虞 之禪也。

若使少帝有知，
必不肯爲；
若其無知，
孤自尊而飾讓，
平生素心所不爲也。」

但改丞相爲相國府，
其九錫殊禮，
皆歸之有司。
# p 

 rm#r00748@宇文化及 以左武衞將軍 rm#r06021@陳稜 爲 dm#dm04510@江都 太守，
綜領留事。

壬申，
令内外戒嚴，
云欲還 dm#dm08170@長安 。

皇后六宮皆依舊式爲御營，
營前別立帳，
 rm#r00748@化及 視事其中，
仗衞部伍，
皆擬乘輿。

奪 dm#dm04510@江都 人舟檝，
取 dm#dm02926@彭城 水路西歸。

以折衝郎將 rm#rz0025@沈光 驍勇，
使將給使營於禁内。

行至 dm#dm08769@顯福宮 ，
虎賁郎將 rm#rz0026@麥孟才 、虎牙郎 rm#r05976@錢傑 與 rm#rz0025@光 謀曰：
「吾儕受先帝厚恩，
今俛首事讎，
受其驅帥，
何面目視息世間哉！

吾必欲殺之，
死無所恨！」

 rm#rz0025@光 泣曰：
「是所望於將軍也。」

 rm#rz0026@孟才 乃糾合恩舊，
帥所將數千人，
期以晨起將發時襲 rm#r00748@化及 。

語洩，
 rm#r00748@化及 夜與腹心走出營外，
留人告 rm#r06160@司馬徳戡 等，
使討之。

 rm#rz0025@光 聞營内諠，
知事覺，
即襲 rm#r00748@化及 營，
空無所獲，
値内史侍郎 rm#r05043@元敏 ，
數而斬之。

 rm#r06160@徳戡 引兵入圍之，
殺 rm#rz0025@光 ，
其麾下數百人皆鬬死，
一無降者，
 rm#rz0026@孟才 亦死。

 rm#rz0026@孟才 ，
 rm#rz0027@鐵杖 之子也。

# p 

 dm#dm04259@武康  rm#r02419@沈法興 ，
世爲郡著姓，
宗族數千家。

 rm#r02419@法興 爲 dm#dm01289@呉興 太守，
聞 rm#r00748@宇文化及 弑逆，
舉兵以討 rm#r00748@化及 爲名，
比至 dm#dm05537@烏程 ，
得精卒六萬，
遂攻 dm#dm08791@餘杭 、 dm#dm04374@毘陵 、 dm#dm00299@丹陽 ，
皆下之；
據 dm#dm04475@江 表十餘郡，
自稱 dm#dm04481@江南道 大總管，
承制置百官。
# p 

 rm#r03033@陳國公竇抗 ，
 rm#r04258@唐王 之𡚱兄也，
 rm#rt0779@煬帝 使行長城於 dm#dm08626@靈武 ；
聞 rm#r04258@唐王 定 dm#dm08281@關中 ，
癸酉，
帥 dm#dm08626@靈武 、 dm#dm09053@鹽川 等數郡來降。

# p 

夏，
四月，
稽胡寇 dm#dm02268@富平 ，
將軍 rm#r05619@王師仁 撃破之。

又五萬餘人寇 dm#dm02178@宜春 ，
相國府諮議參軍 rm#r03047@竇軌 將兵討之，
戰於 dm#dm09120@黄欽山 。

稽胡乘高縱火，
官軍小卻；
 rm#r03047@軌 斬其部將十四人，
拔隊中小校代之，
勒兵復戰。

 rm#r03047@軌 自將數百騎居軍後，
令之曰：
「聞鼓聲有不進者，
自後斬之！」

既而鼓之，
將士爭先赴敵，
稽胡射之不能止，
遂大破之，
虜男女二萬口。
# p 

世子 rm#r01078@建成 等至 dm#dm03880@東都 ，
軍於 dm#dm06841@芳華苑 ；
 dm#dm03880@東都 閉門不出，
遣人招諭，
不應。

 rm#r01704@李密 出軍爭之，
小戰，
各引去。

城中多欲爲内應者，
 rm#r01602@趙公世民 曰：
「吾新定 dm#dm08281@關中 ，
根本未固，
雖得 dm#dm03880@東都 ，
不能守也。」

遂不受。

戊寅，
引軍還。

 rm#r01602@世民 曰：
「城中見吾退，
必來追躡。」

乃設三伏於 dm#dm00141@三王陵 以待之；
 rm#r05551@段達 果將萬餘人追之，
遇伏而敗。

 rm#r01602@世民 逐北，
抵其城下，
斬四千餘級。

遂置 dm#dm03337@新安 、 dm#dm02199@宜陽 二郡，
使行軍總管 rm#r05100@史萬寶 、 rm#r02874@盛彦師 鎭 dm#dm02199@宜陽 ，
 rm#rz0032@呂紹宗 、 rm#r00090@任瓌 將兵鎭 dm#dm03337@新安 而還。
懸軍遠來將兵
# p 

初，
 dm#dm00372@五原 通守 dm#dm04199@櫟陽  rm#r01267@張長遜 以中原大亂，
舉郡附突厥，
突厥以爲 rm#r01267@割利特勒 。

 rm#r05927@郝瑗 説 rm#r03307@薛舉 ，
與 rm#r02125@梁師都 及突厥連兵以取 dm#dm08170@長安 ，
 rm#r03307@舉 從之。

時 rm#rz0033@啓民可汗 之子 rm#rz0034@咄苾 號 rm#rz0034@莫賀咄設 ，
建牙直 dm#dm00372@五原 之北，
 rm#r03307@舉 遣使與 rm#rz0034@莫賀咄設 謀入寇；
 rm#rz0034@莫賀咄設 許之。

 rm#r04258@唐王 使都水監 rm#r00758@宇文歆 賂 rm#rz0034@莫賀咄設 ，
且爲陳利害，
止其出兵，
又説 rm#rz0034@莫賀咄設 遣 rm#r01267@張長遜 入朝，
以 dm#dm00372@五原 之地歸之 dm#dm00255@中國 ，
 rm#rz0034@莫賀咄設 竝從之。

己卯，
 dm#dm04309@武都 、 dm#dm02108@宕渠 、 dm#dm00372@五原 等郡皆降，
王即以 rm#r01267@長遜 爲 dm#dm00372@五原 太守。

 rm#r01267@長遜 又詐爲詔書與 rm#rz0034@莫賀咄設 ，
示知其謀。

 rm#rz0034@莫賀咄設 乃拒 rm#r03307@舉 、 rm#r02125@師都 等，
不納其使。

# p 

戊戌，
世子 rm#r01078@建成 等還 dm#dm08170@長安 。

# p 

 dm#dm03880@東都 號令不出四門，
人無固志，
朝議郎 rm#r05543@段世弘 等謀應西師。

會西師已還，
乃遣人招 rm#r01704@李密 ，
期以己亥夜納之。

事覺，
 rm#rt0783@越王 命 rm#r02590@王世充 討誅之。

 rm#r01704@密 聞城中已定，
乃還。
# p 

 rm#r00748@宇文化及 擁衆十餘萬，
據有六宮，
自奉養一如 rm#rt0779@煬帝 。

毎於帳中南面坐，
人有白事者，
嘿然不對；
下牙，
方取啓状與 rm#r05139@唐奉義 、 rm#r05585@牛方裕 、 rm#r05796@薛世良 、 rm#r06185@張愷 等參決之。

以少主 rm#rt0780@浩 付尚書省，
令衞士十餘人守之，
遣令史取其畫敕，
百官不復朝參。

至 dm#dm02926@彭城 ，
水路不通，
復奪民車牛得二千兩，
竝載宮人珍寶；
其戈甲戎器，
悉令軍士負之，
道遠疲劇，
軍士始怨。

 rm#r06160@司馬徳戡 竊謂 rm#r05914@趙行樞 曰：
「君大謬誤我！

當今撥亂，
必藉英賢；
 rm#r00748@化及 庸暗，
羣小在側，
事將必敗，
若之何？」
 rm#r05914@行樞 曰：
「在我等耳，
廢之何難！」

初，
 rm#r00748@化及 既得政，
賜 rm#r06160@司馬徳戡 爵 rm#r06160@温國公 ，
加光祿大夫；
以其專統驍果，
心忌之。

後數日，
 rm#r00748@化及 署諸將分部士卒，
以 rm#r06160@徳戡 爲禮部尚書，
外示美遷，
實奪其兵柄。

 rm#r06160@徳戡 由是憤怨，
所獲賞賜，
皆以賂 rm#r05169@智及 ；
 rm#r05169@智及 爲之言，
乃使之將後軍萬餘人以從。

於是 rm#r06160@徳戡 、 rm#r05914@行樞 與諸將 rm#r05404@李本 、 rm#r05201@尹正卿 、 rm#rz0012@宇文導師 等謀，
以後軍襲殺 rm#r00748@化及 ，
更立 rm#r06160@徳戡 爲主；
遣人詣 rm#rz0003@孟海公 ，
結爲外助，
遷延未發，
待 rm#rz0003@海公 報。

 rm#r05860@許弘仁 、 rm#r06185@張愷 知之，
以告 rm#r00748@化及 ，
 rm#r00748@化及 遣 rm#r00750@宇文士及 陽爲遊獵，
至後軍，
 rm#r06160@徳戡 不知事露，
出營迎謁，
因執之。

 rm#r00748@化及 讓之曰：
「與公戮力共定海内，
出於萬死。

今始事成，
方願共守富貴，
公又何反也？」
 rm#r06160@徳戡 曰：
「本殺昏主，
苦其淫虐；
推立足下，
而又甚之；
逼於物情，
不得已也。」

 rm#r00748@化及 縊殺之，
幷殺其支黨十餘人。

 rm#rz0003@孟海公 畏 rm#r00748@化及 之強，
帥衆具牛酒迎之。

 rm#r01704@李密 據 dm#dm08717@鞏洛 以拒 rm#r00748@化及 ，
 rm#r00748@化及 不得西，
引兵向 dm#dm03879@東郡 ，
 dm#dm03879@東郡 通守 rm#r06236@王軌 以城降之。

# p 

辛丑，
 rm#r01704@李密 將 dm#dm00409@井陘  rm#r02607@王君廓 帥衆來降。

 rm#r02607@君廓 本羣盜，
有衆數千人，
與賊帥 rm#r06043@韋寶 、 rm#r05955@鄧豹 合軍 dm#dm07185@虞郷 ，
 rm#r04258@唐王 與 rm#r01704@李密 倶遣使招之。

 rm#r06043@寶 、 rm#r05955@豹 欲從 rm#r04258@唐王 ，
 rm#r02607@君廓 僞與之同，
乘其無備，
襲撃，
破之，
奪其輜重，
奔 rm#r01704@李密 ；
 rm#r01704@密 不禮之，
復來降，
拜上柱國，
假 dm#dm04653@河内 太守。
# p 

 rm#r03260@蕭銑 即皇帝位，
置百官，
準 dyn#ch166@梁 故事。

諡其從父 rm#rt0714@琮 爲 rm#rt0714@孝靖皇帝 ，
祖 rm#rz0035@巖 爲 rm#rz0035@河間忠烈王 ，
父 rm#rz0036@璿 爲 rm#rz0036@文憲王 ，
封 rm#r05772@董景珍 等功臣七人皆爲王。

遣 rm#r05516@宋王楊道生 撃 dm#dm01060@南郡 ，
下之，
徙都 dm#dm04516@江陵 ，
脩復園廟。

引 rm#r00879@岑文本 爲中書侍郎，
使典文翰，
委以機密。

又使 rm#r05292@魯王張繡 徇 dm#dm02527@嶺南 ，
 dyn#ch174@隋 將 rm#r06193@張鎭周 、 rm#r05596@王仁壽 等拒之；
既而聞 rm#rt0779@煬帝 遇弑，
皆降於 rm#r03260@銑 。

 dm#dm04208@欽州 刺史 rm#r05671@甯長眞 亦以 dm#dm08939@鬱林 、 dm#dm01881@始安 之地附於 rm#r03260@銑 。

 dm#dm05302@漢陽 太守 rm#r04199@馮盎 以 dm#dm07050@蒼梧 、 dm#dm08909@高涼 、 dm#dm05737@珠崖 、 dm#dm05842@番禺 之地附於 rm#r02073@林士弘 。

 rm#r03260@銑 、 rm#r02073@士弘 各遣人招 dm#dm00422@交趾 太守 rm#r00029@丘和 ，
 rm#r00029@和 不從。

 rm#r03260@銑 遣 rm#r05671@甯長眞 帥 dm#dm02527@嶺南 之兵自海道攻 rm#r00029@和 ，
 rm#r00029@和 欲出迎之，
司法書佐 rm#r04217@高士廉 説 rm#r00029@和 曰：
「 rm#r05671@長眞 兵數雖多，
懸軍遠至，
不能持久，
城中勝兵足以當之，
奈何望風受制於人！」

 rm#r00029@和 從之，
以 rm#r04217@士廉 爲軍司馬，
將水陸諸軍逆撃，
破之，
 rm#r05671@長眞 僅以身免，
盡俘其衆。

既而有驍果自 dm#dm04510@江都 至，
得 rm#rt0779@煬帝 凶問，
亦以郡附於 rm#r03260@銑 。

 rm#r04217@士廉 ，
 rm#r06865@勱 之子也。

# p 

 dm#dm01881@始安郡 丞 rm#r01958@李襲志 ，
 rm#r06644@遷哲 之孫也，
 dyn#ch174@隋 末，
散家財，
募士得三千人，
以保郡城；
 rm#r03260@蕭銑 、 rm#r02073@林士弘 、 rm#r06200@曹武徹 迭來攻之，
皆不克。

聞 rm#rt0779@煬帝 遇弑，
帥吏民臨三日。

或説 rm#r01958@襲志 曰：
「公 dm#dm00266@中州 貴族，
久臨鄙郡，
 dm#dm06927@華 、夷悦服。

今 dyn#ch174@隋室 無主，
海内鼎沸，
以公威惠，
號令 dm#dm02533@嶺表 ，
 rm#r05893@尉佗 之業可坐致也。」

 rm#r01958@襲志 怒曰：
「吾世繼忠貞，
今 dm#dm04510@江都 雖覆，
宗社尚存，
 rm#r05893@尉佗 狂僭，
何足慕也！」

欲斬説者，
衆乃不敢言。

堅守二年，
外無聲援，
城陷，
爲 rm#r03260@銑 所虜，
 rm#r03260@銑 以爲工部尚書，
檢校 dm#dm04001@桂州 總管。

於是東自 dm#dm00329@九江 ，
西抵 dm#dm00123@三峽 ，
南盡 dm#dm00422@交趾 ，
北距 dm#dm05285@漢川 ，
 rm#r03260@銑 皆有之，
勝兵四十餘萬。

# p 

 rm#rt0779@煬帝 凶問至 dm#dm08170@長安 ，
 rm#r04258@唐王 哭之慟，
曰：
「吾北面事人，
失道不能救，
敢忘哀乎！」

# p 

五月，
 dm#dm02398@山南 撫慰使 rm#r04168@馬元規 撃 rm#r01583@朱粲 於 dm#dm00722@冠軍 ，
破之。

# p 

 rm#r06232@王徳仁 既殺 rm#r01380@房彦藻 ，
 rm#r01704@李密 遣 rm#r01299@徐世勣 討之。

 rm#r06232@徳仁 兵敗，
甲寅，
與 dm#dm04244@武安 通守 rm#r05835@袁子幹 皆來降，
詔以 rm#r06232@徳仁 爲 dm#dm07975@鄴郡 太守。

# p 

戊午，
 rm#rt0782@隋恭帝 禪位于 dyn#ch100@唐 ，
遜居 dm#dm00487@代邸 。

甲子，
 rm#r04258@唐王 即皇帝位于 dm#dm01809@太極殿 ，
遣刑部尚書 rm#r05791@蕭造 告天於南郊，
大赦，
改元。

罷郡，
置州，
以太守爲刺史。

推五運爲土徳，
色尚黄。
# p 

 dyn#ch174@隋  rm#rt0779@煬帝 凶問至 dm#dm03880@東都 ，
戊辰，
留守官奉 rm#rt0783@越王 即皇帝位，
大赦，
改元 y@皇泰 。

是時於朝堂宣旨，
以時鍾金革，
公私皆即日大祥。

追諡大行曰 rm#rt0779@明皇帝 ，
廟號 rm#rt0779@世祖 ；
追尊 rm#rt0781@元徳太子 曰 rm#rt0781@成皇帝 ，
廟號 rm#rt0781@世宗 。

尊母 rm#r05085@劉良娣 爲皇太后。

以 rm#r05551@段達 爲納言、 rm#r05551@陳國公 ，
 rm#r02590@王世充 爲納言、 rm#r02590@鄭國公 ，
 rm#r05044@元文都 爲内史令、 rm#r05044@魯國公 ，
 rm#r02861@皇甫無逸 爲兵部尚書、 rm#r02861@𣏌國公 ；
又以 rm#r05706@盧楚 爲内史令，
 rm#r05942@郭文懿 爲内史侍郎，
 rm#r05917@趙長文 爲黄門侍郎，
共掌朝政。

時人號七貴。

 rm#rt0783@皇泰主 眉目如畫，
温厚仁愛，
風格儼然。
# p 

辛未，
突厥 rm#rz0041@始畢可汗 遣 rm#rz0042@骨咄祿特勒 來，
宴之於 dm#dm01809@太極殿 ，
奏九部樂。

時 dm#dm00255@中國 人避亂者多入突厥，
突厥強盛，
東自契丹、室韋，
西盡吐谷渾、 dm#dm08900@高昌 諸國，
皆臣之，
控弦百餘萬。

帝以初起資其兵馬，
前後餉遺，
不可勝紀。

突厥恃功驕倨，
毎遣使者至 dm#dm08170@長安 ，
多暴横，
帝優容之。
# p 

壬申，
命 rm#r03424@裴寂 、 rm#r00267@劉文靜 等修定律令。

置國子、太學、四門生，
合三百餘員，
郡縣學亦各置生員。


# p 

六月，
甲戌朔，
以 rm#r01602@趙公世民 爲尚書令，
 rm#r01070@黄臺公瑗 爲刑部侍郎，
相國府長史 rm#r03424@裴寂 爲右僕射、知政事，
司馬 rm#r00267@劉文靜 爲納言，
司録 rm#r03019@竇威 爲内史令，
 rm#r01876@李綱 爲禮部尚書、參掌選事，
掾 rm#r02357@殷開山 爲吏部侍郎，
屬 rm#r05907@趙慈景 爲兵部侍郎，
 rm#r06055@韋義節 爲禮部侍郎，
主簿 rm#r03915@陳叔達 、 dm#dm01107@博陵  rm#r06182@崔民幹 竝爲黄門侍郎，
 rm#ry9001@唐儉 爲内史侍郎，
録事參軍 rm#r06256@裴晞 爲尚書左丞；
以 dyn#ch174@隋 民部尚書 rm#r03249@蕭瑀 爲内史令，
禮部尚書 rm#r03040@竇璡 爲戸部尚書，
 rm#r00876@蒋公屈突通 爲兵部尚書，
 dm#dm08170@長安 令 rm#r02574@獨孤懷恩 爲工部尚書。

 rm#r01070@瑗 ，
上之從子；
 rm#r02574@懷恩 ，
舅子也。

# p 

上待 rm#r03424@裴寂 特厚，
羣臣無與爲比，
賞賜服玩，
不可勝紀；
命尚書奉御日以御膳賜 rm#r03424@寂 ，
視朝必引與同坐，
入閤則延之臥内；
言無不從，
稱爲 rm#r03424@裴監 而不名。

委 rm#r03249@蕭瑀 以庶政，
事無大小，
無不關掌。

 rm#r03249@瑀 亦孜孜盡力，
繩違舉過，
人皆憚之，
毀之者衆，
終不自理。

上嘗有敕而内史不時宣行，
上責其遲，
 rm#r03249@瑀 對曰：
「 y@大業 之世，
内史宣敕，
或前後相違，
有司不知所從，
其易在前，
其難在後；
臣在省日久，
備見其事。

今王業經始，
事繋安危，
遠方有疑，
恐失機會，
故臣毎受一敕必勘審，
使與前敕不違，
始敢宣行，
稽緩之愆，
實由於此。」

上曰：
「卿用心如是，
吾復何憂！」


# p 

初，
帝遣 rm#r04168@馬元規 慰撫 dm#dm02398@山南 ，
 dm#dm01079@南陽郡 丞 dm#dm04672@河東  rm#r00428@呂子臧 獨據郡不從；
 rm#r04168@元規 遣使數輩諭之，
皆爲 rm#r00428@子臧 所殺。

及 rm#rt0779@煬帝 遇弑，
 rm#r00428@子臧 發喪成禮，
然後請降；
拜 dm#dm07942@鄧州 刺史，
封 rm#r00428@南郡公 。
# p 

廢 y@大業 律令，
頒新格。
# p 

上毎視事，
自稱名，
引貴臣同榻而坐。

 rm#r00267@劉文靜 諫曰：
「昔 rm#r05616@王導 有言：
『若太陽俯同萬物，
使羣生何以仰照！』

今貴賤失位，
非常久之道。」

上曰：
「昔 rm#rt0529@漢光武 與 rm#rz0043@嚴子陵 共寢，
 rm#rz0043@子陵 加足於帝腹。

今諸公皆名徳舊齒，
平生親友，
宿昔之歡，
何可忘也。

公勿以爲嫌！」

# p 

戊寅，
 dyn#ch174@隋  dm#dm02084@安陽 令 rm#r05111@呂珉 以 dm#dm06029@相州 來降，
以爲 dm#dm06029@相州 刺史。
# p 

己卯，
祔四親廟主。

追尊皇高祖 rm#ry1003@瀛州府君 曰 rm#ry1003@宣簡公 ；
皇曾祖司空曰 rm#ry1004@懿王 ；
皇祖 rm#ry1001@景王 曰 rm#ry1001@景皇帝 ，
廟號 rm#ry1001@太祖 ，
祖妣曰 rm#rz0044@景烈皇后 ；
皇考 rm#rz0001@元王 曰 rm#rz0001@元皇帝 ，
廟號 rm#rz0001@世祖 ，
妣 rm#rz0045@獨孤氏 曰 rm#rz0045@元貞皇后 ；
追諡𡚱 rm#r03010@竇氏 曰 rm#r03010@穆皇后 。

毎歳祀昊天上帝、皇地祇、神州地祇，
以 rm#ry1001@景帝 配，
感生帝、明堂，
以 rm#rz0001@元帝 配。

庚辰，
立世子 rm#r01078@建成 爲皇太子，
 rm#r01602@趙公世民 爲 rm#r01602@秦王 ，
 rm#r01016@齊公元吉 爲 rm#r01016@齊王 ，
宗室 rm#rz0048@黄瓜公白駒 爲 rm#rz0048@平原王 ，
 rm#r02380@蜀公孝基 爲 rm#r02380@永安王 ，
柱國 rm#r02454@道玄 爲 rm#r02454@淮陽王 ，
 rm#r03868@長平公叔良 爲 rm#r03868@長平王 ，
 rm#r02450@鄭公神通 爲 rm#r02450@永康王 ，
 rm#r03482@安吉公神符 爲 rm#r03482@襄邑王 ，
柱國 rm#r01430@徳良 爲 rm#r01430@新興王 ，
上柱國 rm#r03975@博义 爲 rm#r03975@隴西王 ，
上柱國 rm#r02459@奉慈 爲 rm#r02459@勃海王 。

 rm#r02380@孝基 、 rm#r03868@叔良 、 rm#r03482@神符 、 rm#r01430@徳良 ，
帝之從父弟；
 rm#r03975@博义 、 rm#r02459@奉慈 ，
弟子；
 rm#r02454@道玄 ，
從父兄子也。

# p 

癸未，
 rm#r03307@薛舉 寇 dm#dm04924@涇州 ，
以 rm#r01602@秦王世民 爲元帥，
將八總管兵以拒之。

# p 

遣太僕卿 rm#r05168@宇文明達 招慰 dm#dm02403@山東 ，
以 rm#r02380@永安王孝基 爲 dm#dm08320@陝州 總管。

時天下未定，
凡邊要之州，
皆置總管府，
以統數州之兵。

# p 

乙酉，
奉 dyn#ch174@隋 帝爲 rm#rt0782@酅國公 。

詔曰：
「近世以來，
時運遷革，
前代親族，
莫不誅夷。

興亡之效，
豈伊人力！

其 dyn#ch174@隋  rm#rz0049@蔡王智積 等子孫，
竝付所司，
量才選用。」


# p 

 dm#dm03880@東都 聞 rm#r00748@宇文化及 西來，
上下震懼。

有 rm#r05779@蓋琮 者，
上疏請説 rm#r01704@李密 與之合勢拒 rm#r00748@化及 。

 rm#r05044@元文都 謂 rm#r05706@盧楚 等曰：
「今讎恥未雪而兵力不足，
若赦 rm#r01704@密 罪使撃 rm#r00748@化及 ，
兩賊自鬬，
吾徐承其弊。

 rm#r00748@化及 既破，
 rm#r01704@密 兵亦疲；
又其將士利吾官賞，
易可離間，
幷 rm#r01704@密 亦可擒也。」

 rm#r05706@楚 等皆以爲然，
即以 rm#r05779@琮 爲通直散騎常侍，
齎敕書賜 rm#r01704@密 。
# p 

丙申，
 dyn#ch174@隋  dm#dm00585@信都郡 丞 dm#dm03869@東莱  rm#rz0050@麹稜 來降，
拜 dm#dm00712@冀州 刺史。

# p 

 dm#dm06979@萬年縣 法曹 dm#dm04238@武城  rm#r00709@孫伏伽 上表，
以爲：
「 dyn#ch174@隋 以惡聞其過亡天下。

陛下龍飛 dm#dm03567@晉陽 ，
遠近響應，
未期年而登帝位；
徒知得之之易，
不知 dyn#ch174@隋 失之之不難也。

臣謂宜易其覆轍，
務盡下情。

凡人君言動，
不可不愼。

竊見陛下今日即位而明日有獻鷂雛者，
此乃少年之事，
豈聖主所須哉！

又，
百戲散樂，
亡國淫聲。

近太常於民間借婦女裙襦五百餘襲以充妓衣，
擬五月五日 dm#dm05694@玄武門 遊戲，
此亦非所以爲子孫法也。

凡如此類，
悉宜廢罷。

善惡之習，
朝夕漸染，
易以移人。

皇太子、諸王參僚左右，
宜謹擇其人；
其有門風不能雍睦，
爲人素無行義，
專好奢靡，
以聲色遊獵爲事者，
皆不可使之親近也。

自古及今，
骨肉乖離，
以至敗國亡家，
未有不因左右離間而然也。

願陛下愼之。」

上省表大悦，
下詔褒稱，
擢爲治書侍御史，
賜帛三百匹，
仍頒示遠近。丁酉
# p 

辛丑，
内史令 rm#r03019@延安靖公竇威 薨。

以將作大匠 rm#r03033@竇抗 兼納言，
黄門侍郎 rm#r03915@陳叔達 判納言。

# p 

 rm#r00748@宇文化及 留輜重於 dm#dm05233@滑臺 ，
以 rm#r06236@王軌 爲刑部尚書，
使守之，
引兵北趣 dm#dm09166@黎陽 。

 rm#r01704@李密 將 rm#r01299@徐世勣 據 dm#dm09166@黎陽 ，
畏其軍鋒，
以兵西保 dm#dm00597@倉城 。

 rm#r00748@化及 渡 dm#dm04650@河 ，
保 dm#dm09166@黎陽 ，
分兵圍 rm#r01299@世勣 。

 rm#r01704@密 帥歩騎二萬，
壁於 dm#dm05064@清淇 ，
與 rm#r01299@世勣 以烽火相應，
深溝高壘，
不與 rm#r00748@化及 戰。

 rm#r00748@化及 毎攻 dm#dm00597@倉城 ，
 rm#r01704@密 輒引兵以掎其後。

 rm#r01704@密 與 rm#r00748@化及 隔水而語，
 rm#r01704@密 數之曰：
「卿本匈奴皁隸 rm#no@破野頭 耳；
父兄子弟，
竝受 dyn#ch174@隋 恩，
富貴累世，
舉朝莫二。

主上失徳，
不能死諫，
反行弑逆，
欲規簒奪。

不追 rm#r05868@諸葛瞻 之忠誠，
乃爲 rm#r06038@霍禹 之惡逆，
天地所不容，
將欲何之！

若速來歸我，
尚可得全後嗣。」

 rm#r00748@化及 默然，
俯視良久，
瞋目大言曰：
「與爾論相殺事，
何須作書語邪！」

 rm#r01704@密 謂從者曰：
「 rm#r00748@化及 庸愚如此，
忽欲圖爲帝王，
吾當折杖驅之耳！」

 rm#r00748@化及 盛脩攻具以逼 dm#dm00597@倉城 ，
 rm#r01299@世勣 於城外掘深溝以固守，
 rm#r00748@化及 阻塹，
不得至城下。

 rm#r01299@世勣 於塹中爲地道，
出兵撃之，
 rm#r00748@化及 大敗，
焚其攻具。
# p 

時 rm#r01704@密 與 dm#dm03880@東都 相持日久，
又東拒 rm#r00748@化及 ，
常畏 dm#dm03880@東都 議其後，
見 rm#r05779@蓋琮 至，
大喜，
遂上表乞降，
請討滅 rm#r00748@化及 以贖罪，
送所獲雄武郎將 rm#r05014@于洪建 ，
遣元帥府記室參軍 rm#r01620@李儉 、上開府 rm#r05318@徐師譽 等入見。

 rm#rt0783@皇泰主 命戮 rm#r05014@洪建 於 dm#dm02552@左掖門 外，
如 rm#rz0054@斛斯政 之法。

 rm#r05044@元文都 等以 rm#r01704@密 降爲誠實，
盛飾賓館於 dm#dm02204@宣仁門 東。

 rm#rt0783@皇泰主 引見 rm#r01620@儉 等，
以 rm#r01620@儉 爲司農卿，
 rm#r05318@師譽 爲尚書右丞，
使具導從，
列鐃吹，
還館，
玉帛酒饌，
中使相望。

册拜 rm#r01704@密 太尉、尚書令、東南道大行臺行軍元帥、 rm#r01704@魏國公 ，
令先平 rm#r00748@化及 ，
然後入朝輔政。

以 rm#r01299@徐世勣 爲右武候大將軍。

仍下詔稱 rm#r01704@密 忠款，
且曰：
「其用兵機略，
一稟 rm#r01704@魏公 節度。」
凶黨
# p 

 rm#r05044@元文都 喜於和解，
謂天下可定，
於 dm#dm00171@上東門 置酒作樂，
自 rm#r05551@段達 已下皆起舞。

 rm#r02590@王世充 作色謂起居侍郎 rm#r05233@崔長文 曰：
「朝廷官爵，
乃以與賊，
其志欲何爲邪！」

 rm#r05044@文都 等亦疑 rm#r02590@世充 欲以城應 rm#r00748@化及 ，
由是有隙，
然猶外相彌縫，
陽爲親善。
# p 

秋，
七月，
 rm#rt0783@皇泰主 遣大理卿 rm#rz0055@張權 、鴻臚卿 rm#r05204@崔善福 賜 rm#r01704@李密 書曰：
「今日以前，
咸共刷蕩，
使至以後，
彼此通懷。

七政之重，
佇公匡弼，
九伐之利，
委公指揮。」

 rm#r01191@權 等既至，
 rm#r01704@密 北面拜受詔書。

既無西慮，
悉以精兵東撃 rm#r00748@化及 。

 rm#r01704@密 知 rm#r00748@化及 軍糧且盡，
因僞與和；
 rm#r00748@化及 大喜，
恣其兵食，
冀 rm#r01704@密 饋之。

會 rm#r01704@密 下有人獲罪，
亡抵 rm#r00748@化及 ，
具言其情，
 rm#r00748@化及 大怒，
其食又盡，
乃渡 dm#dm04439@永濟渠 ，
與 rm#r01704@密 戰于 dm#dm06347@童山 之下，
自辰達酉；
 rm#r01704@密 爲流矢所中，
墮馬悶絶，
左右奔散，
追兵且至，
唯 rm#r02977@秦叔寶 獨捍衞之，
 rm#r01704@密 由是獲免。

 rm#r02977@叔寶 復收兵與之力戰，
 rm#r00748@化及 乃退。

 rm#r00748@化及 入 dm#dm04536@汲郡 求軍糧，
又遣使拷掠 dm#dm03879@東郡 吏民以責米粟。

 rm#r06236@王軌 等不堪其弊，
遣通事舍人 rm#r03511@許敬宗 詣 rm#r01704@密 請降；
以 rm#r06236@軌 爲 dm#dm05229@滑州 總管，
以 rm#r03511@敬宗 爲元帥府記室，
與 rm#r04294@魏徵 共掌文翰。

 rm#r03511@敬宗 ，
 rm#r05858@善心 之子也。

 rm#r06246@房公蘇威 在 dm#dm03879@東郡 ，
隨衆降 rm#r01704@密 ，
 rm#r01704@密 以其 dyn#ch174@隋氏 大臣，
虚心禮之。

 rm#r06246@威 見 rm#r01704@密 ，
初不言帝室艱危，
唯再三舞蹈，
稱「不圖今日復覩聖明！」

時人鄙之。

 rm#r00748@化及 聞 rm#r06236@王軌 叛，
大懼，
自 dm#dm04536@汲郡 引兵欲取以北諸郡，
其將 rm#r06273@陳智略 帥 dm#dm02527@嶺南 驍果萬餘人，
 rm#r05528@樊文超 帥 dm#dm04501@江淮 排䂎，
 rm#r05289@張童兒 帥 dm#dm04494@江東 驍果數千人，
皆降於 rm#r01704@密 。

 rm#r05528@文超 ，
 rm#r05525@子蓋 之子也。

 rm#r00748@化及 猶有衆二萬，
北趣 dm#dm08955@魏縣 ；
 rm#r01704@密 知其無能爲，
西還 dm#dm08717@鞏洛 ，
留 rm#r01299@徐世勣 以備之。密
# p 

乙巳，
 dm#dm02214@宣州 刺史 rm#r05132@周超 撃 rm#r01583@朱粲 ，
敗之。

# p 

丁未，
 rm#r02125@梁師都 寇 dm#dm08619@靈州 ，
驃騎將軍 rm#rz0056@藺興粲 撃破之。

# p 

突厥 rm#rz0057@闕可汗 遣使内附。

初，
 rm#rz0057@闕可汗 附於 rm#r01980@李軌 ；
 dyn#ch174@隋 西戎使者 rm#r06202@曹瓊 據 dm#dm05794@甘州 誘之，
乃更附 rm#r06202@瓊 ，
與之拒 rm#r01980@軌 ；
爲 rm#r01980@軌 所敗，
竄於 dm#dm07749@達斗拔谷 ，
與吐谷渾相表裏，
至是内附。

尋爲 rm#r01980@李軌 所滅。上厚加撫慰
# p 

 rm#r03307@薛舉 進逼 dm#dm08877@高墌 ，
遊兵至于 dm#dm07508@豳 ，
 dm#dm02420@岐 ，
 rm#r01602@秦王世民 深溝高壘不與戰。

會 rm#r01602@世民 得瘧疾，
委軍事於長史‧納言 rm#r00267@劉文靜 、司馬 rm#r02357@殷開山 ，
且戒之曰：
「 rm#r03307@薛舉 懸軍深入，
食少兵疲，
若來挑戰，
愼勿應也。

俟吾疾愈，
爲君等破之。」

 rm#r02357@開山 退，
謂 rm#r00267@文靜 曰：
「王慮公不能辦，
故有此言耳。

且賊聞王有疾，
必輕我，
宜曜武以威之。」

乃陳於 dm#dm08877@高墌 西南，
恃衆而不設備。

 rm#r03307@舉 潛師掩其後，
壬子，
戰於 dm#dm05027@淺水原 ，
八總管皆敗，
士卒死者什五六，
大將軍 rm#rz0058@慕容羅㬋 、 rm#r01697@李安遠 、 rm#r00246@劉弘基 皆沒。

 rm#r01602@世民 引兵還 dm#dm08170@長安 ，
 rm#r03307@舉 遂拔 rm#r06094@高墌 ，
收 dyn#ch100@唐 兵死者爲京觀；
 rm#r00267@文靜 等皆坐除名。
# p 

乙卯，
 dm#dm04101@楡林 賊帥 rm#r03714@郭子和 遣使來降，
以爲 dm#dm08619@靈州 總管。
# p 

 rm#r01704@李密 毎戰勝，
必遣使告捷於 rm#rt0783@皇泰主 ，
 dyn#ch174@隋 人皆喜，
 rm#r02590@王世充 獨謂其麾下曰：
「 rm#r05044@元文都 輩，
刀筆吏耳，
吾觀其勢，
必爲 rm#r01704@李密 所擒。

且吾軍士屡與 rm#r01704@密 戰，
沒其父兄子弟，
前後已多，
一旦爲之下，
吾屬無類矣！」

欲以激怒其衆。

 rm#r05044@文都 聞之，
大懼，
與 rm#r05706@盧楚 等謀因 rm#r02590@世充 入朝，
伏甲誅之。

 rm#r05551@段達 性庸懦，
恐其事不就，
遣其壻 rm#rz0059@張志 以 rm#r05706@楚 等謀告 rm#r02590@世充 。

戊午夜三鼓，
 rm#r02590@世充 勒兵襲 dm#dm01268@含嘉門 。

 rm#r05044@元文都 聞變，
入奉 rm#rt0783@皇泰主 御 dm#dm00362@乾陽殿 ，
陳兵自衞，
命諸將閉門拒守。

將軍 rm#rz0062@跋野綱 將兵出，
遇 rm#r02590@世充 ，
下馬降之。

將軍 rm#rz0063@費曜 、 rm#r05679@田闍 戰於門外，
不利。

 rm#r05044@文都 自將宿衞兵欲出 dm#dm05694@玄武門 以襲其後，
長秋監 rm#r05548@段瑜 稱求門鑰不獲，
稽留遂久。

天且曙，
 rm#r05044@文都 復欲引兵出 dm#dm01826@太陽門 逆戰，
還至 dm#dm00362@乾陽殿 ，
 rm#r02590@世充 已攻 dm#dm01826@太陽門 得入。

 rm#r02861@皇甫無逸 棄母及妻子，
斫 dm#dm01171@右掖門 ，
西奔 dm#dm08170@長安 。

 rm#r05706@盧楚 匿於太官署，
 rm#r02590@世充 之黨擒之，
至 dm#dm06782@興教門 ，
見 rm#r02590@世充 ，
 rm#r02590@世充 令亂斬殺之；
進攻 dm#dm06410@紫微宮 門。

 rm#rt0783@皇泰主 使人登 dm#dm06412@紫微觀 ，
問：
「稱兵欲何爲？」
 rm#r02590@世充 下馬謝曰：
「 rm#r05044@元文都 、 rm#r05706@盧楚 等横見規圖；
請殺 rm#r05044@文都 ，
甘從刑典。」

 rm#r05551@段達 乃令將軍 rm#r06138@黄桃樹 執送 rm#r05044@文都 。

 rm#r05044@文都 顧謂 rm#rt0783@皇泰主 曰：
「臣今朝死，
陛下夕及矣！」

 rm#rt0783@皇泰主 慟哭遣之，
出 dm#dm06782@興教門 ，
亂斬如 rm#r05706@盧楚 ，
幷殺 rm#r05706@盧 、 rm#r05044@元 諸子。

 rm#r05551@段達 又以 rm#rt0783@皇泰主 命開門納 rm#r02590@世充 ，
 rm#r02590@世充 悉遣人代宿衞者，
然後入見 rm#rt0783@皇泰主 於 dm#dm00362@乾陽殿 。

 rm#rt0783@皇泰主 謂 rm#r02590@世充 曰：
「相誅殺，
曾不聞奏，
豈爲臣之道乎？
公欲肆其強力，
敢及我邪！」

 rm#r02590@世充 拜伏流涕謝曰：
「臣蒙先皇采拔，
粉骨非報。

 rm#r05044@文都 等苞藏禍心，
欲召 rm#r01704@李密 以危社稷，
疾臣違異，
深積猜嫌；
臣迫於救死，
不暇聞奏。

若内懷不臧，
違負陛下，
天地日月，
實所照臨，
使臣闔門殄滅，
無復遺類。」

詞涙倶發。

 rm#rt0783@皇泰主 以爲誠，
引令升殿，
與語久之，
因與倶入見皇太后；
 rm#r02590@世充 被髮爲誓，
稱不敢有貳心。

乃以 rm#r02590@世充 爲左僕射、總督内外諸軍事。

比及日中，
捕獲 rm#r05917@趙長文 、 rm#r05942@郭文懿 ，
殺之。

然後巡城，
告諭以誅 rm#r05044@元 、 rm#r05706@盧 之意。

 rm#r02590@世充 自 dm#dm01267@含嘉城 移居尚書省，
漸結黨援，
恣行威福。

用兄 rm#rz0024@世惲 爲内史令，
入居禁中，
子弟咸典兵馬，
分政事爲十頭，
悉以其黨主之，
勢震内外，
莫不趨附，
 rm#rt0783@皇泰主 拱手而已。
# p 

 rm#r01704@李密 將入朝，
至 dm#dm05190@温 ，
聞 rm#r05044@元文都 等死，
乃還 dm#dm08017@金墉 。

 dm#dm03880@東都 大饑，
私錢濫惡，
太半雜以錫鐶，
其細如線，
米斛直錢八九萬。
# p 

初，
 rm#r01704@李密 嘗受業於儒生 rm#r01316@徐文遠 。

 rm#r01316@文遠 爲 rm#rt0783@皇泰主 國子祭酒，
自出樵采，
爲 rm#r01704@密 軍所執；
 rm#r01704@密 令 rm#r01316@文遠 南面坐，
備弟子禮，
北面拜之。

 rm#r01316@文遠 曰：
「老夫既荷厚禮，
敢不盡言！

未審將軍之志欲爲 rm#r06152@伊 、 rm#rz0053@霍 以繼絶扶傾乎？
則老夫雖遲暮，
猶願盡力；
若爲 rm#rt0526@莽 、 rm#r06742@卓 ，
乘危邀利，
則無所用老夫矣！」

 rm#r01704@密 頓首曰：
「昨奉朝命，
備位上公，
冀竭庸虚，
匡濟國難，
此 rm#r01704@密 之本志也。」

 rm#r01316@文遠 曰：
「將軍名臣之子，
失塗至此，
若能不遠而復，
猶不失爲忠義之臣！」

及 rm#r02590@王世充 殺 rm#r05044@元文都 等，
 rm#r01704@密 復問計於 rm#r01316@文遠 。

 rm#r01316@文遠 曰：
「 rm#r02590@世充 亦門人也，
其爲人殘忍褊隘，
既乘此勢，
必有異圖，
將軍前計爲不諧矣。

非破 rm#r02590@世充 ，
不可入朝也。」

 rm#r01704@密 曰：
「始謂先生儒者，
不達時事，
今乃坐決大計，
何其明也！

」
 rm#r01316@文遠 ，
 rm#r06604@孝嗣 之玄孫也。

# p 

庚申，
詔 dyn#ch174@隋氏 離宮遊幸之所竝廢之。
# p 

戊辰，
遣 rm#r01070@黄臺公瑗 安撫 dm#dm02398@山南 。

# p 

己巳，
以 dyn#ch174@隋 右武衞將軍 rm#r02861@皇甫無逸 爲刑部尚書。
# p 

 dyn#ch174@隋  dm#dm04704@河間郡 丞 rm#r05651@王琮 守郡城以拒羣盜，
 rm#r03028@竇建徳 攻之，
歳餘不下；
聞 rm#rt0779@煬帝 凶問，
帥吏士發喪，
乘城者皆哭。

 rm#r03028@建徳 遣使弔之，
 rm#r05651@琮 因使者請降，
 rm#r03028@建徳 退舍具饌以待之。

 rm#r05651@琮 言及 dyn#ch174@隋 亡，
俯伏流涕，
 rm#r03028@建徳 亦爲之泣。

諸將曰：
「 rm#r05651@琮 久拒我軍，
殺傷甚衆，
力盡乃降，
請烹之。」

 rm#r03028@建徳 曰：
「 rm#r05651@琮 ，
忠臣也，
吾方賞之以勸事君，
奈何殺之！

往在 dm#dm08930@高雞泊 爲盜，
容可妄殺人；
今欲安百姓，
定天下，
豈得害忠良乎！」

乃徇軍中曰：
「先與 rm#r05651@王琮 有怨敢妄動者，
夷三族！」

以 rm#r05651@琮 爲 dm#dm05480@瀛州 刺史。

於是 dm#dm04656@河北 郡縣聞之，
爭附於 rm#r03028@建徳 。

# p 

先是，
 rm#r03028@建徳 陷 dm#dm03589@景城 ，
執戸曹 dm#dm04672@河東  rm#r01214@張玄素 ，
將殺之，
縣民千餘人號泣，
請代其死，
曰：
「戸曹清愼無比，
大王殺之，
何以勸善！

」
 rm#r03028@建徳 乃釋之，
以爲治書侍御史，
固辭；
及 dm#dm04510@江都 敗，
復以爲黄門侍郎，
 rm#r01214@玄素 乃起。

 dm#dm08803@饒陽 令 rm#r05187@宋正本 ，
博學有才氣，
説 rm#r03028@建徳 以定 dm#dm04656@河北 之策，
 rm#r03028@建徳 引爲謀主。

 rm#r03028@建徳 定都 dm#dm04130@樂壽 ，
命所居曰 dm#dm08013@金城宮 ，
備置百官。
# p 

八月，
 rm#r03307@薛舉 遣其子 rm#r03266@仁果 進圍 dm#dm02291@寧州 ，
刺史 rm#r05751@胡演 撃卻之。

 rm#r05927@郝瑗 言於 rm#r03307@舉 曰：
「今 dyn#ch100@唐 兵新破，
 dm#dm08281@關中 騷動，
宜乘勝直取 dm#dm08170@長安 。」

 rm#r03307@舉 然之，
會有疾而止。

辛巳，
 rm#r03307@舉 卒。

 rm#r03266@太子仁果 立，
居於 dm#dm03200@折墌城 ，
諡 rm#r03307@舉 曰 rm#r03307@武帝 。
# p 

上欲與 rm#r01980@李軌 共圖 dm#dm06273@秦 、 dm#dm08457@隴 ，
遣使潛詣 dm#dm04947@涼州 ，
招撫之，
與之書，
謂之從弟。

 rm#r01980@軌 大喜，
遣其弟 rm#rz0065@懋 入貢。

上以 rm#rz0065@懋 爲大將軍，
命鴻臚少卿 rm#r05247@張俟徳 册拜 rm#r01980@軌 爲 dm#dm04947@涼州 總管，
封 rm#r01980@涼王 。


# p 

初，
朝廷以 dm#dm02084@安陽 令 rm#r05111@呂珉 爲 dm#dm06029@相州 刺史，
更以 dm#dm06029@相州 刺史 rm#r06232@王徳仁 爲 dm#dm02542@巖州 刺史。

 rm#r06232@徳仁 由是怨憤，
甲申，
誘 dm#dm02403@山東 大使 rm#r05168@宇文明達 入 dm#dm03924@林慮山 而殺之，
叛歸 rm#r02590@王世充 。
# p 

己丑，
以 rm#r01602@秦王世民 爲元帥，
撃 rm#r03266@薛仁果 。
# p 

丁酉，
 dm#dm06688@臨洮 等四郡來降。

# p 

 dyn#ch174@隋  dm#dm04510@江都 太守 rm#r06021@陳稜 求得 rm#rt0779@煬帝 之柩，
取 rm#r00748@宇文化及 所留輦輅鼓吹，
粗備天子儀衞，
改葬於 dm#dm04512@江都宮 西 dm#dm01277@呉公臺 下，
其王公以下，
皆列瘞於帝塋之側。

# p 

 rm#r00748@宇文化及 之發 dm#dm04510@江都 也，
以 rm#r02022@杜伏威 爲 dm#dm04339@歴陽 太守；
 rm#r02022@伏威 不受，
仍上表於 dyn#ch174@隋 ，
 rm#rt0783@皇泰主 拜 rm#r02022@伏威 爲東道大總管，
封 rm#r02022@楚王 。
# p 

 rm#r02419@沈法興 亦上表於 rm#rt0783@皇泰主 ，
自稱大司馬、録尚書事、 rm#r02419@天門公 ，
承制置百官，
以 rm#r06012@陳杲仁 爲司徒，
 rm#r05159@孫士漢 爲司空，
 rm#r05783@蒋元超 爲左僕射，
 rm#r05554@殷芊 爲左丞，
 rm#r05316@徐令言 爲右丞，
 rm#r05062@劉子翼 爲選部侍郎，
 rm#r01886@李百藥 爲府掾。

 rm#r01886@百藥 ，
 rm#r06628@徳林 之子也。

# p 

九月，
 dyn#ch174@隋  dm#dm07262@襄國 通守 rm#r03917@陳君賓 來降，
拜 dm#dm07817@邢州 刺史。

 rm#r03917@君賓 ，
 rm#rz0051@伯山 之子也。

# p 

 dm#dm07183@虞州 刺史 rm#r06055@韋義節 攻 dyn#ch174@隋  dm#dm04672@河東 通守 rm#rz0066@堯君素 ，
久不下，
軍數不利；
壬子，
以工部尚書 rm#r02574@獨孤懷恩 代之。
# p 

初，
 rm#r01704@李密 既殺 rm#rz0067@翟讓 ，
頗自驕矜，
不恤士衆；
倉粟雖多，
無府庫錢帛，
戰士有功，
無以爲賞；
又厚撫初附之人，
衆心頗怨。

 rm#r01299@徐世勣 嘗因宴會刺譏其短；
 rm#r01704@密 不懌，
使 rm#r01299@世勣 出鎭 dm#dm09166@黎陽 ，
雖名委任，
實亦疏之。

# p 

 rm#r01704@密 開 dm#dm04771@洛口倉 散米，
無防守典當者，
又無文券，
取之者隨意多少；
或離倉之後，
力不能致，
委棄衢路，
自 dm#dm00597@倉城 至郭門，
米厚數寸，
爲車馬所轥踐；
羣盜來就食者幷家屬近百萬口，
無甕盎，
織荊筐淘米，
 dm#dm04780@洛水 兩岸十里之間，
望之皆如白沙。

 rm#r01704@密 喜，
謂 rm#r05892@賈閏甫 曰：
「此可謂足食矣！」

 rm#r05892@閏甫 對曰：
「國以民爲本，
民以食爲天。

今民所以襁負如流而至者，
以所天在此故也。

而有司曾無愛吝，
屑越如此，
竊恐一旦米盡民散，
明公孰與成大業哉！」

 rm#r01704@密 謝之，
即以 rm#r05892@閏甫 判司倉參軍事。
# p 

 rm#r01704@密 以 dm#dm03880@東都 兵數敗微弱，
而將相自相屠滅，
謂旦夕可平；
 rm#r02590@王世充 既專大權，
厚賞將士，
繕治器械，
亦陰圖取 rm#r01704@密 。

時 dyn#ch174@隋 軍乏食，
而 rm#r01704@密 軍少衣，
 rm#r02590@世充 請交易，
 rm#r01704@密 難之；
長史 rm#rz0069@邴元眞 等各求私利，
勸 rm#r01704@密 許之。

先是，
 dm#dm03880@東都 人歸 rm#r01704@密 者，
日以百數；
既得食，
降者益少，
 rm#r01704@密 悔而止。
# p 

 rm#r01704@密 破 rm#r00748@宇文化及 還，
其勁卒良馬多死，
士卒疲病。

 rm#r02590@世充 欲乘其弊撃之，
恐人心不壹，
乃詐稱左軍衞士 rm#r05284@張永通 三夢 rm#rt0104@周公 ，
令宣意於 rm#r02590@世充 ，
當勒兵相助撃賊；
乃爲 rm#rt0104@周公 立廟，
毎出兵，
輒先祈祷。

 rm#r02590@世充 令巫宣言 rm#rt0104@周公 欲令僕射急討 rm#r01704@李密 ，
當有大功，
不即兵皆疫死。

 rm#r02590@世充 兵多 dm#dm04085@楚 人，
信妖言，
皆請戰。

 rm#r02590@世充 簡練精鋭得二萬餘人，
馬二千餘匹。

壬子，
出師撃 rm#r01704@密 ，
旗幡之上皆書 rm#r05284@永通 字，
軍容甚盛。

癸丑，
至 dm#dm00606@偃師 ，
營於 dm#dm07698@通濟渠 南，
作三橋於渠上。

 rm#r01704@密 留 rm#r06230@王伯當 守 dm#dm08017@金墉 ，
自引精兵出 dm#dm00606@偃師 ，
阻 dm#dm07795@邙山 以待之。
# p 

 rm#r01704@密 召諸將會議，
 rm#r06251@裴仁基 曰：
「 rm#r02590@世充 悉衆而至，
 dm#dm04761@洛 下必虚，
可分兵守其要路，
令不得東，
簡精兵三萬，
傍 dm#dm04650@河 西出以逼 dm#dm03880@東都 。

 rm#r02590@世充 還，
我且按甲；
 rm#r02590@世充 再出，
我又逼之。

如此，
則我有餘力，
彼勞奔命，
破之必矣。」

 rm#r01704@密 曰：
「公言大善。

今 dm#dm03880@東都 兵有三不可當：
兵仗精鋭，
一也；
決計深入，
二也；
食盡求戰，
三也。

我但乘城固守，
蓄力以待之；
彼欲鬬不得，
求走無路，
不過十日，
 rm#r02590@世充 之頭可致麾下。」

 rm#r06273@陳智略 、 rm#r05528@樊文超 、 rm#r00523@單雄信 皆曰：
「計 rm#r02590@世充 戰卒甚少，
屡經摧破，
悉已喪膽。

兵法曰，
『倍則戰』，
況不啻倍哉！

且 dm#dm04475@江 、 dm#dm04981@淮 新附之士，
望因此機展其勳效，
及其鋒而用之，
可以得志。」

於是諸將諠然，
欲戰者什七八，
 rm#r01704@密 惑於衆議而從之。

 rm#r06251@仁基 苦爭不能得，
撃地歎曰：
「公後必悔之。」

 rm#r04294@魏徵 言於長史 rm#rz0004@鄭頲 曰：
「 rm#r01704@魏公 雖驟勝，
而驍將鋭卒多死，
戰士心怠，
此二者難以應敵。

且 rm#r02590@世充 乏食，
志在死戰，
難與爭鋒，
未若深溝高壘以拒之，
不過旬月，
 rm#r02590@世充 糧盡，
必自退，
追而撃之，
蔑不勝矣。」

 rm#rz0004@頲 曰：
「此老生之常談耳。」

 rm#r04294@徵 曰：
「此乃奇策，
何謂常談！

」
拂衣而起。
# p 

 rm#r02983@程知節 將内馬軍與 rm#r01704@密 同營在 dm#dm00894@北邙山 上，
 rm#r00523@單雄信 將外馬軍營於 dm#dm00607@偃師城 北。

 rm#r02590@世充 遣數百騎渡 dm#dm07698@通濟渠 攻 rm#r00523@雄信 營，
 rm#r01704@密 遣 rm#r06259@裴行儼 與 rm#r02983@知節 助之。

 rm#r06259@行儼 先馳赴敵，
中流矢，
墜於地；
 rm#r02983@知節 救之，
殺數人，
 rm#r02590@世充 軍披靡，
乃抱 rm#r06259@行儼 重騎而還；
爲 rm#r02590@世充 騎所逐，
刺槊洞過，
 rm#r02983@知節 迴身捩折其槊，
兼斬追者，
與 rm#r06259@行儼 倶免。

會日暮，
各斂兵還營。

 rm#r01704@密 驍將 rm#r06169@孫長樂 等十餘人皆被重創。

# p 

 rm#r01704@密 新破 rm#r00748@宇文化及 ，
有輕 rm#r02590@世充 之心，
不設壁壘。

 rm#r02590@世充 夜遣二百餘騎潛入 dm#dm00852@北山 ，
伏谿谷中，
命軍士皆秣馬蓐食。

甲寅旦，
將戰，
 rm#r02590@世充 誓衆曰：
「今日之戰，
非直爭勝負；
死生之分，
在此一舉。

若其捷也，
富貴固所不論；
若其不捷，
必無一人獲免。

所爭者死，
非獨爲國，
各宜勉之！」

遲明，
引兵薄 rm#r01704@密 。

 rm#r01704@密 出兵應之，
未及成列，
 rm#r02590@世充 縱兵撃之。

 rm#r02590@世充 士卒皆 dm#dm04475@江 、 dm#dm04981@淮 剽勇，
出入如飛。

 rm#r02590@世充 先索得一人貌類 rm#r01704@密 者，
縛而匿之，
戰方酣，
使牽以過陳前，
譟曰：
「已獲 rm#r01704@李密 矣！」

士卒皆呼萬歳。

其伏兵發，
乘高而下，
馳壓 rm#r01704@密 營，
縱火焚其廬舍。

 rm#r01704@密 衆大潰，
其將 rm#r05288@張童仁 、 rm#r06273@陳智略 皆降，
 rm#r01704@密 與萬餘人馳向 dm#dm04770@洛口 。
# p 

 rm#r02590@世充 夜圍 dm#dm00606@偃師 ；
 rm#rz0004@鄭頲 守 dm#dm00606@偃師 ，
其部下翻城納 rm#r02590@世充 。

初，
 rm#r02590@世充 家屬在 dm#dm04510@江都 ，
隨 rm#r00748@宇文化及 至 dm#dm05233@滑臺 ，
又隨 rm#r06236@王軌 入 rm#r01704@李密 ，
 rm#r01704@密 留於 dm#dm00606@偃師 ，
欲以招 rm#r02590@世充 。

及 dm#dm00606@偃師 破，
 rm#r02590@世充 得其兄 rm#xjts02782@世偉 、子 rm#xjts01833@玄應 、 rm#xjts01871@虔恕 、 rm#xjts02019@瓊 等，
又獲 rm#r01704@密 將佐 rm#r06251@裴仁基 、 rm#rz0004@鄭頲 、 rm#r02964@祖君彦 等數十人。

 rm#r02590@世充 於是整兵向 dm#dm04770@洛口 ，
得 rm#rz0069@邴元眞 妻子、 rm#r05965@鄭虔象 母及 rm#r01704@密 諸將子弟，
皆撫慰之，
令潛呼其父兄。
虔玄
# p 

初，
 rm#rz0069@邴元眞 爲縣吏，
坐贓亡命，
從 rm#rz0067@翟讓 於 dm#dm05785@瓦岡 ；
 rm#rz0067@讓 以其嘗爲吏，
使掌書記。

及 rm#r01704@密 開幕府，
妙選時英，
 rm#rz0067@讓 薦 rm#rz0069@元眞 爲長史；
 rm#r01704@密 不得已用之，
行軍謀畫，
未嘗參預。

 rm#r01704@密 西拒 rm#r02590@世充 ，
留 rm#rz0069@元眞 守 dm#dm04771@洛口倉 。

 rm#rz0069@元眞 性貪鄙，
 rm#r06174@宇文温 謂 rm#r01704@密 曰：
「不殺 rm#rz0069@元眞 ，
必爲公患。」

 rm#r01704@密 不應。

 rm#rz0069@元眞 知之，
陰謀叛 rm#r01704@密 ；
 rm#?@楊慶 聞之，
以告 rm#r01704@密 ，
 rm#r01704@密 固疑焉。

至是，
 rm#r01704@密 將入 dm#dm04772@洛口城 ，
 rm#rz0069@元眞 已遣人潛引 rm#r02590@世充 矣。

 rm#r01704@密 知而不發，
因與衆謀，
待 rm#r02590@世充 兵半濟 dm#dm04780@洛水 ，
然後撃之。

 rm#r02590@世充 軍至，
 rm#r01704@密 候騎不時覺，
比將出戰，
 rm#r02590@世充 軍悉已濟矣。

 rm#r00523@單雄信 等又勒兵自據；
 rm#r01704@密 自度不能支，
帥麾下輕騎奔 dm#dm07165@虎牢 ，
 rm#rz0069@元眞 遂以城降。

# p 

初，
 rm#r00523@雄信 驍捷，
善用馬槊，
名冠諸軍，
軍中號曰 rm#r00523@飛將 。

 rm#r01380@彦藻 以 rm#r00523@雄信 輕於去就，
勸 rm#r01704@密 除之；
 rm#r01704@密 愛其才，
不忍也。

及 rm#r01704@密 失利，
 rm#r00523@雄信 遂以所部降 rm#r02590@世充 。

# p 

 rm#r01704@密 將如 dm#dm09166@黎陽 ，
或曰：
「殺 rm#rz0067@翟讓 之際，
 rm#r01299@徐世勣 幾死，
今失利而就之，
安可保乎！」

時 rm#r06230@王伯當 棄 dm#dm08017@金墉 保 dm#dm04709@河陽 ，
 rm#r01704@密 自 dm#dm07165@虎牢 歸之，
引諸將共議。

 rm#r01704@密 欲南阻 dm#dm04650@河 ，
北守 dm#dm01820@太行 ，
東連 dm#dm09166@黎陽 ，
以圖進取。

諸將皆曰：
「今兵新失利，
衆心危懼，
若更停留，
恐叛亡不日而盡。

又人情不願，
難以成功。」

 rm#r01704@密 曰：
「孤所恃者衆也，
衆既不願，
孤道窮矣。」

欲自刎以謝衆。

 rm#r06230@伯當 抱 rm#r01704@密 號絶，
衆皆悲泣，
 rm#r01704@密 復曰：
「諸君幸不相棄，
當共歸 dm#dm08281@關中 ；
 rm#r01704@密 身雖無功，
諸君必保富貴。

」
府掾 rm#r05462@柳燮 曰：
「明公與 rm#r04258@唐公 同族，
兼有疇昔之好；
雖不陪起兵，
然阻 dm#dm03880@東都 ，
斷隋歸路，
使 rm#r04258@唐公 不戰而據 dm#dm08170@長安 ，
此亦公之功也。」

衆咸曰：
「然。」

 rm#r01704@密 又謂 rm#r06230@王伯當 曰：
「將軍室家重大，
豈復與孤倶行哉！」

 rm#r06230@伯當 曰：
「昔 rm#r06244@蕭何 盡帥子弟以從 rm#rt0511@漢王 ，
 rm#r06230@伯當 恨不兄弟倶從，
豈以公今日失利遂輕去就乎！

縱身分原野，
亦所甘心！」

左右莫不感激，
從 rm#r01704@密 入 dm#dm08280@關 者凡二萬人。

於是 rm#r01704@密 之將帥、州縣多降於 dyn#ch174@隋 。

 rm#r01583@朱粲 亦遣使降 dyn#ch174@隋 ，
 rm#rt0783@皇泰主 以 rm#r01583@粲 爲 rm#r01583@楚王 。二三
# p 

甲寅，
 dm#dm06279@秦州 總管 rm#r03047@竇軌 撃 rm#r03266@薛仁果 ，
不利；
驃騎將軍 rm#r00258@劉感 鎭 dm#dm04924@涇州 ，
 rm#r03266@仁果 圍之。

城中糧盡，
 rm#r00258@感 殺所乘馬以分將士，
 rm#r00258@感 一無所噉，
唯煑馬骨取汁和木屑食之。

城垂陷者數矣；
會 rm#r03868@長平王叔良 將士至 dm#dm04924@涇州 ，
 rm#r03266@仁果 乃揚言食盡，
引兵南去；
乙卯，
又遣 dm#dm08877@高墌 人僞以城降。

 rm#r03868@叔良 遣 rm#r00258@感 帥衆赴之；
己未，
至城下，
扣城中人曰：
「賊已去，
可踰城入。」

 rm#r00258@感 命燒其門，
城上下水灌之。

 rm#r00258@感 知其詐，
遣歩兵先還，
自帥精兵爲殿。

俄而城上舉三烽，
 rm#r03266@仁果 兵自南原大下，
戰於 dm#dm05959@百里細川 ，
 dyn#ch100@唐 軍大敗，
 rm#r00258@感 爲 rm#r03266@仁果 所擒。

 rm#r03266@仁果 復圍 dm#dm04924@涇州 ，
令 rm#r00258@感 語城中云：
「援軍已敗，
不如早降。」

 rm#r00258@感 許之，
至城下，
大呼曰：
「逆賊飢餒，
亡在旦夕，
 rm#r01602@秦王 帥數十萬衆，
四面倶集，
城中勿憂，
勉之！」

 rm#r03266@仁果 怒，
執 rm#r00258@感 ，
於城旁埋之至膝，
馳騎射之；
至死，
聲色逾厲。

 rm#r03868@叔良 嬰城固守，
僅能自全。

 rm#r00258@感 ，
 rm#r06523@豐生 之孫也。
門
# p 

庚申，
 dm#dm08464@隴州 刺史 dm#dm08318@陝 人 rm#r01031@常達 撃 rm#r03266@薛仁果 於 dm#dm02187@宜祿川 ，
斬首千餘級。
# p 

上遣從子 rm#r03479@襄武公琛 ，
太常卿 rm#r03778@鄭元璹 以女妓遺 rm#rz0041@始畢可汗 。

壬戌，
 rm#rz0041@始畢 復遣 rm#rz0042@骨咄祿特勒 來。
突厥
# p 

癸亥，
 dm#dm05929@白馬 道士 rm#r00139@傅仁均 造戊寅暦成，
奏上，
行之。


# p 

 rm#r03266@薛仁果 屡攻 rm#r01031@常達 ，
不能克，
乃遣其將 rm#xjts10688@仵士政 以數百人詐降，
 rm#r01031@達 厚撫之。

乙丑，
 rm#xjts10688@士政 伺隙以其徒劫 rm#r01031@達 ，
擁城中二千人降於 rm#r03266@仁果 。

 rm#r01031@達 見 rm#r03266@仁果 ，
詞色不屈，
 rm#r03266@仁果 壯而釋之。

奴賊帥 rm#r05304@張貴 謂 rm#r01031@達 曰：
「汝識我乎？」
 rm#r01031@達 曰：
「汝逃死奴賊耳！」

 rm#r05304@貴 怒，
欲殺之；
人救之，
得免。
# p 

辛未，
追諡 dyn#ch174@隋 太上皇爲 rm#rt0779@煬帝 。

# p 

 rm#r00748@宇文化及 至 dm#dm08955@魏縣 ，
 rm#r06185@張愷 等謀去之；
事覺，
 rm#r00748@化及 殺之。

腹心稍盡，
兵勢日蹙，
兄弟更無他計，
但相聚酣宴，
奏女樂。

 rm#r00748@化及 醉，
尤 rm#r05169@智及 曰：
「我初不知，
由汝爲計，
強來立我。

今所向無成，
士馬日散，
負弑君之名，
天下所不容。

今者滅族，
豈不由汝乎！」

持其兩子而泣。

 rm#r05169@智及 怒曰：
「事捷之日，
初不賜尤，
及其將敗，
乃欲歸罪，
何不殺我以降 rm#r03028@竇建徳 ！」

數相鬬䦧，
言無長幼；
醒而復飮，
以此爲恆。

其衆多亡，
 rm#r00748@化及 自知必敗，
嘆曰：
「人生固當死，
豈不一日爲帝乎！

」
於是鴆殺 rm#rt0780@秦王浩 ，
即皇帝位於 dm#dm08955@魏縣 ，
國號 dyn#?@許 ，
改元 y@天壽 ，
署置百官。


# p 

冬，
十月，
壬申朔，
日有食之。
# p 

戊寅，
宴突厥 rm#rz0042@骨咄祿 ，
引 rm#rz0042@骨咄祿 升御坐以寵之。

# p 

 rm#r01704@李密 將至，
上遣使迎勞，
相望於道。

 rm#r01704@密 大喜，
謂其徒曰：
「我擁衆百萬，
一朝解甲歸 dyn#ch100@唐 ，
 dm#dm02403@山東 連城數百，
知我在此，
遣使招之，
亦當盡至；
比於 rm#r05735@竇融 ，
功亦不細，
豈不以一臺司見處乎！」

己卯，
至 dm#dm08170@長安 ，
有司供待稍薄，
所部兵累日不得食，
衆心頗怨。

既而以 rm#r01704@密 爲光祿卿、上柱國，
賜爵 rm#r01704@邢國公 。

 rm#r01704@密 既不滿望，
朝臣又多輕之，
執政者或來求賄，
意甚不平；
獨上親禮之，
常呼爲弟，
以舅子 rm#?@獨孤氏 妻之。


# p 

庚辰，
詔右翊衞大將軍 rm#r02450@淮安王神通 爲 dm#dm02404@山東道 安撫大使，
 dm#dm02403@山東 諸軍竝受節度；
以黄門侍郎 rm#r06182@崔民幹 爲副。


# p 

 dm#dm07942@鄧州 刺史 rm#r00428@呂子臧 與撫慰使 rm#r04168@馬元規 撃 rm#r01583@朱粲 ，
破之。

 rm#r00428@子臧 言於 rm#r04168@元規 曰：
「 rm#r01583@粲 新敗，
上下危懼，
請倂力撃之，
一舉可滅。

若復遷延，
其徒稍集，
力強食盡，
致死於我，
爲患方深。」

 rm#r04168@元規 不從。

 rm#r00428@子臧 請獨以所部兵撃之，
 rm#r04168@元規 不許。

既而 rm#r01583@粲 收集餘衆，
兵復大振，
自稱 rm#r01583@楚帝 於 dm#dm00722@冠軍 ，
改元 y@昌達 ，
進攻 dm#dm07942@鄧州 。

 rm#r00428@子臧 撫膺謂 rm#r04168@元規 曰：
「老夫今坐公死矣！」

 rm#r01583@粲 圍 dm#dm01077@南陽 ，
會霖雨城壞，
所親勸 rm#r00428@子臧 降。

 rm#r00428@子臧 曰：
「安有天子方伯降賊者乎！

」
帥麾下赴敵而死。

俄而城陷，
 rm#r04168@元規 亦死。

# p 

癸未，
 rm#r02590@王世充 收 rm#r01704@李密 美人珍寶及將卒十餘萬人還 dm#dm03880@東都 ，
陳於闕下。

乙酉，
 rm#rt0783@皇泰主 大赦。

丙戌，
以 rm#r02590@世充 爲太尉、尚書令、内外諸軍事，
仍使之開太尉府，
備置官屬，
妙選人物。

 rm#r02590@世充 以 rm#r06251@裴仁基 父子驍勇，
深禮之。

 rm#r01316@徐文遠 復入 dm#dm03880@東都 ，
見 rm#r02590@世充 ，
必先拜。

或問曰：
「君倨見 rm#r01704@李密 而敬 rm#r02590@王公 ，
何也？」
 rm#r01316@文遠 曰：
「 rm#r01704@魏公 ，
君子也，
能容賢士；
 rm#r02590@王公 ，
小人也，
能殺故人，
吾何敢不拜！」
總督
# p 

 rm#r01704@李密 總管 rm#r01929@李育徳 以 dm#dm04316@武陟 來降，
拜 dm#dm08330@陟州 刺史。

 rm#r01929@育徳 ，
 rm#r06641@諤 之孫也。

其餘將佐 rm#r00252@劉徳威 、 rm#r05892@賈閏甫 、 rm#r04227@高季輔 等，
或以城邑，
或帥衆，
相繼來降。


# p 

初，
 dm#dm00875@北海 賊帥 rm#?@綦公順 帥其徒三萬攻郡城，
已克其外郭，
進攻子城；
城中食盡，
 rm#?@公順 自謂克在旦夕，
不爲備。

明經 rm#r06159@劉蘭成 糾合城中驍健百餘人襲撃之，
城中見兵繼之，
 rm#?@公順 大敗，
棄營走，
郡城獲全。

於是郡官及望族分城中民爲六軍，
各將之，
 rm#r00314@蘭成 亦將一軍。

有 rm#?@宋書佐 者，
離間諸軍曰：
「 rm#r00314@蘭成 得衆心，
必爲諸人不利，
不如殺之。」

衆不忍殺，
但奪其兵以授 rm#?@宋書佐 。

 rm#r00314@蘭成 恐終及禍，
亡奔 rm#?@公順 ；
 rm#?@公順 軍中喜譟，
欲奉以爲主，
固辭，
乃以爲長史，
軍事咸聽焉。

居五十餘日，
 rm#r00314@蘭成 簡軍中驍健者百五十人，
往抄 dm#dm00875@北海 。

距城四十里，
留十人，
使多芟草，
分爲百餘積；
二十里，
又留二十人，
各執大旗；
五六里，
又留三十人，
伏險要；
 rm#r00314@蘭成 自將十人，
夜，
距城一里許潛伏；
餘八十人分置便處，
約聞鼓聲即抄取人畜亟去，
仍一時焚積草。

明晨，
城中遠望無煙塵，
皆出樵牧。

日向中，
 rm#r00314@蘭成 以十人直抵城門，
城上鉦鼓亂發；
伏兵四出，
抄掠雜畜十餘頭及樵牧者而去。

 rm#r00314@蘭成 度抄者已遠，
徐歩而還。

城中雖出兵，
恐有伏兵，
不敢急追；
又見前有旌旗、煙火，
遂不敢進而還。

既而城中知 rm#r00314@蘭成 前者衆少，
悔不窮追。

居月餘，
 rm#r00314@蘭成 謀取郡城，
更以二十人直抵城門。

城中人競出逐之，
行未十里，
 rm#?@公順 將大兵總至。

郡兵奔馳還城，
 rm#?@公順 進兵圍之；
 rm#r00314@蘭成 一言招諭，
城中人爭出降。

 rm#r00314@蘭成 撫存老幼，
禮遇郡官，
見 rm#?@宋書佐 ，
亦禮之如舊，
仍資送出境，
内外安堵。十千
# p 

時 dm#dm04908@海陵 賊帥 rm#xjts09516@臧君相 聞 rm#xjts21806@公順 據 dm#dm00875@北海 ，
帥其衆五萬來爭之；
 rm#xjts21806@公順 衆少，
聞之大懼。

 rm#r00314@蘭成 爲 rm#xjts21806@公順 畫策曰：
「 rm#xjts09516@君相 今去此尚遠，
必不爲備，
請將軍倍道襲撃其營。」

 rm#xjts21806@公順 從之，
自將驍勇五千人，
齎熟食，
倍道襲之。

將至，
 rm#r00314@蘭成 與敢死士二十人前行，
距 rm#xjts09516@君相 營五十里，
見其抄者負擔向營，
 rm#r00314@蘭成 亦與其徒負擔蔬米、燒器，
詐爲抄者，
擇空而行聽察，
得其號及主將姓名；
至暮，
與賊比肩而入，
負擔巡營，
知其虚實，
得其更號。

乃於空地燃火營食，
至三鼓，
忽於主將幕前交刀亂下，
殺百餘人，
賊衆驚擾；
 rm#xjts21806@公順 兵亦至，
急攻之，
 rm#xjts09516@君相 僅以身免，
俘斬數千，
收其資糧甲仗以還。

由是 rm#xjts21806@公順 黨衆大盛。

及 rm#r01704@李密 據 dm#dm04770@洛口 ，
 rm#xjts21806@公順 以衆附之，
 rm#r01704@密 敗，
亦來降。

# p 

 dyn#ch174@隋 末羣盜起，
冠軍司兵 rm#r01959@李襲譽 説 dm#dm07290@西京 留守 rm#?@陰世師 ，
遣兵據 dm#dm04447@永豐倉 ，
發粟以賑貧乏，
出庫物賞戰士，
移檄郡縣，
同心討賊。

 rm#?@世師 不能用，
乃求募兵 dm#dm02398@山南 ，
 rm#?@世師 許之。

上克 dm#dm08170@長安 ，
自 dm#dm05272@漢中 召還，
爲太府少卿；
乙未，
附 rm#r01959@襲譽 籍於宗正。

 rm#r01959@襲譽 ，
 rm#r01958@襲志 之弟也。

# p 

丙申，
 rm#r01583@朱粲 寇 dm#dm04966@淅州 ，
遣太常卿 rm#r03778@鄭元璹 帥歩騎一萬撃之。

# p 

是月，
納言 rm#r03033@竇抗 罷爲左武候大將軍。
# p 

十一月，
乙巳，
 rm#r01980@涼王李軌 即皇帝位，
改元 y@安樂 。

# p 

戊申，
 rm#r06236@王軌 以 dm#dm05229@滑州 來降。

# p 

 rm#r03266@薛仁果 之爲太子也，
與諸將多有隙；
及即位，
衆心猜懼。

 rm#r05927@郝瑗 哭 rm#r03307@舉 得疾，
遂不起，
由是國勢浸弱。

 rm#r01602@秦王世民 至 dm#dm08877@高墌 ，
 rm#r03266@仁果 使 rm#r05192@宗羅㬋 將兵拒之；
 rm#r05192@羅㬋 數挑戰，
 rm#r01602@世民 堅壁不出。

諸將咸請戰，
 rm#r01602@世民 曰：
「我軍新敗，
士氣沮喪，
賊恃勝而驕，
有輕我心，
宜閉壘以待之。

彼驕我奮，
可一戰而克也。」

乃令軍中曰：
「敢言戰者斬！」

相持六十餘日，
 rm#r03266@仁果 糧盡，
其將 rm#r05478@梁胡郎 等帥所部來降。

 rm#r01602@世民 知 rm#r03266@仁果 將士離心，
命行軍總管 rm@梁實 營於 dm#dm05027@淺水原 以誘之。

 rm#r05192@羅㬋 大喜，
盡鋭攻之，
 rm@梁實 守險不出；
營中無水，
人馬不飮者數日。

 rm#r05192@羅㬋 攻之甚急；
 rm#r01602@世民 度賊已疲，
謂諸將曰：
「可以戰矣！」

遲明，
使右武候大將軍 rm#r06284@龐玉 陳於 dm#dm05027@淺水原 。

 rm#r05192@羅㬋 倂兵撃之，
 rm#r06284@玉 戰，
幾不能支，
 rm#r01602@世民 引大軍自原北出其不意，
 rm#r05192@羅㬋 引兵還戰。

 rm#r01602@世民 帥驍騎數十先陷陳，
 dyn#ch100@唐 兵表裏奮撃，
呼聲動地，
 rm#r05192@羅㬋 士卒大潰，
斬首數千級。

 rm#r01602@世民 帥二千餘騎追之，
 rm#r03047@竇軌 叩馬苦諫曰：
「 rm#r03266@仁果 猶據堅城，
雖破 rm#r05192@羅㬋 ，
未可輕進，
請且按兵以觀之。」

 rm#r01602@世民 曰：
「吾慮之久矣，
破竹之勢，
不可失也，
舅勿復言！」

遂進。

 rm#r03266@仁果 陳於城下，
 rm#r01602@世民 據 dm#dm04926@涇水 臨之，
 rm#r03266@仁果 驍將 rm#r05567@渾幹 等數人臨陳來降。

 rm#r03266@仁果 懼，
引兵入城拒守。

日向暮，
大軍繼至，
遂圍之。

夜半，
守城者爭自投下。

 rm#r03266@仁果 計窮，
己酉，
出降；
得其精兵萬餘人，
男女五萬口。
# p 

諸將皆賀，
因問曰：
「大王一戰而勝，
遽捨歩兵，
又無攻具，
輕騎直造城下，
衆皆以爲不克，
而卒取之，
何也？」
 rm#r01602@世民 曰：
「 rm#r05192@羅㬋 所將皆 dm#dm08457@隴 外之人，
將驍卒悍；
吾特出其不意而破之，
斬獲不多。

若緩之，
則皆入城，
 rm#r03266@仁果 撫而用之，
未易克也；
急之，
則散歸 dm#dm08457@隴 外，
 dm#dm03199@折墌 虚弱，
 rm#r03266@仁果 破膽，
不暇爲謀，
此吾所以克也。」

衆皆悦服。

 rm#r01602@世民 所得降卒，
悉使 rm#r03266@仁果 兄弟及 rm#r05192@宗羅㬋 、 rm#?@翟長孫 等將之，
與之射獵，
無所疑間。

賊畏威銜恩，
皆願效死。

 rm#r01602@世民 聞 rm#r03473@褚亮 名，
求訪，
獲之，
禮遇甚厚，
引爲王府文學。

# p 

上遣使謂 rm#r01602@世民 曰：
「 rm#r03307@薛舉 父子多殺我士卒，
必盡誅其黨以謝冤魂。」

 rm#r01704@李密 諫曰：
「 rm#r03307@薛舉 虐殺無辜，
此其所以亡也，
陛下何怨焉！

懷服之民，
不可不撫！」

乃命戮其謀首，
餘皆赦之。
# p 

上使 rm#r01704@李密 迎 rm#r01602@秦王世民 於 dm#dm07510@豳州 ，
 rm#r01704@密 自恃智略功名，
見上猶有傲色；
及見 rm#r01602@世民 ，
不覺驚服，
私謂 rm#r02357@殷開山 曰：
「眞英主也，
不如是，
何以定禍亂乎！」

# p 

詔以員外散騎常侍 rm#r00639@姜謩 爲 dm#dm06279@秦州 刺史，
 rm#r00639@謩 撫以恩信，
盜賊悉歸首，
士民安之。


# p 

 rm#r01299@徐世勣 據 rm#r01704@李密 舊境，
未有所屬。

 rm#r04294@魏徵 隨 rm#r01704@密 至 dm#dm08170@長安 ，
乃自請安集 dm#dm02403@山東 ，
上以爲祕書丞，
乘傳至 dm#dm09166@黎陽 ，
遺 rm#r01299@徐世勣 書，
勸之早降。

 rm#r01299@世勣 遂決計西向，
謂長史 dm#dm08423@陽翟  rm#r03716@郭孝恪 曰：
「此民衆土地，
皆 rm#r01704@魏公 有也；
吾若上表獻之，
是利主之敗，
自爲功以邀富貴也，
吾實恥之。

今宜籍郡縣戸口士馬之數以啓 rm#r01704@魏公 ，
使自獻之。」

乃遣 rm#r03716@孝恪 詣 dm#dm08170@長安 ，
又運糧以餉 rm#r02450@淮安王神通 。

上聞 rm#r01299@世勣 使者至，
無表，
止有啓與 rm#r01704@密 ，
甚怪之。

 rm#r03716@孝恪 具言 rm#r01299@世勣 意，
上乃嘆曰：
「 rm#r01299@徐世勣 不背徳，
不邀功，
眞純臣也！」

賜姓 rm#no@李 。

以 rm#r03716@孝恪 爲 dm#dm02098@宋州 刺史，
使與 rm#r01299@世勣 經略 dm#dm07165@虎牢 以東，
所得州縣，
委之選補。
久不爲朝廷所知
# p 

癸丑，
 rm#r02574@獨孤懷恩 攻 rm#rz0066@堯君素 於 dm#dm07021@蒲反 。

行軍總管 rm#r05907@趙慈景 尚帝女 rm#rz0070@桂陽公主 ，
爲 rm#rz0066@君素 所擒，
梟首城外，
以示無降意。

# p 

癸亥，
 rm#r01602@秦王世民 至 dm#dm08170@長安 ，
斬 rm#r03266@薛仁果 於市，
賜 rm#r01031@常達 帛三百段。

贈 rm#r00258@劉感  rm#r00258@平原郡公 ，
諡 rm#r00258@忠壯 。

撲殺 rm#xjts10688@仵士政 於殿庭。

以 rm#r05304@張貴 尤淫暴，
腰斬之。

上享勞將士，
因謂羣臣曰：
「諸公共相翊戴以成帝業，
若天下承平，
可共保富貴。

使 rm#r02590@王世充 得志，
公等豈有種乎！

如 rm#r03266@薛仁果 君臣，
豈可不以爲前鑑也！」

己巳，
以 rm#r00267@劉文靜 爲戸部尚書，
領 dm#dm08324@陝東道 行臺左僕射；
復 rm#r02357@殷開山 爵位。

# p 

 rm#r01704@李密 驕貴日久，
又自負歸國之功，
朝廷待之不副本望，
鬱鬱不樂。

嘗遇大朝會，
 rm#r01704@密 爲光祿卿，
當進食，
深以爲恥；
退，
以告左武衞大將軍 rm#r06230@王伯當 。

 rm#r06230@伯當 心亦怏怏，
因謂 rm#r01704@密 曰：
「天下事在公度内耳。

今 rm#r01299@東海公 在 dm#dm09166@黎陽 ，
 rm#r01122@襄陽公 在 dm#dm06499@羅口 ，
 dm#dm04660@河南 兵馬，
屈指可計，
豈得久如此也！

」
 rm#r01704@密 大喜，
乃獻策於上曰：
「臣虚蒙榮寵，
安坐 dm#dm08170@京師 ，
曾無報效；
 dm#dm02403@山東 之衆皆臣故時麾下，
請往收而撫之。

憑藉國威，
取 rm#r02590@王世充 如拾地芥耳！」

上聞 rm#r01704@密 故將士多不附 rm#r02590@世充 ，
亦欲遣 rm#r01704@密 往收之，
羣臣多諫曰：
「 rm#r01704@李密 狡猾好反，
今遣之，
如投魚於泉，
放虎於山，
必不反矣！」

上曰：
「帝王自有天命，
非小子所能取。

借使叛去，
如以蒿箭射蒿中耳！

今使二賊交鬬，
吾可以坐收其弊。」

辛未，
遣 rm#r01704@密 詣 dm#dm02403@山東 ，
收其餘衆之未下者。

 rm#r01704@密 請與 rm#r05892@賈閏甫 偕行，
上許之，
命 rm#r01704@密 及 rm#r05892@閏甫 同升御榻，
賜食，
傳飮巵酒曰：
「吾三人同飮是酒以明同心，
善建功名，
以副朕意。

丈夫一言許人，
千金不易。

有人確執不欲弟行，
朕推赤心於弟，
非他人所能間也。」

 rm#r01704@密 、 rm#r05892@閏甫 再拜受命。

上又以 rm#r06230@王伯當 爲 rm#r01704@密 副而遣之。


# p 

有大鳥五集于 dm#dm04130@樂壽 ，
羣鳥數萬從之，
經日乃去。

 rm#r03028@竇建徳 以爲己瑞，
改元 y@五鳳 。

 dm#dm02113@宗城 人有得玄圭獻於 rm#r03028@建徳 者，
 rm#r05187@宋正本 及 dm#dm03589@景城 丞 dm#dm03660@會稽  rm#r00667@孔徳紹 皆曰：
「此天所以賜 rm#rt0008@大禹 也，
請改國號曰 dyn#?@夏 。」

 rm#r03028@建徳 從之。

以 rm#r05187@正本 爲納言，
 rm#r00667@徳紹 爲内史侍郎。
# p 

初，
 rm#r05663@王須拔 掠 dm#dm02689@幽州 ，
中流矢死，
其將 rm#r06119@魏刀兒 代領其衆，
據 dm#dm05018@深澤 ，
掠 dm#dm00712@冀 、 dm#dm02116@定 之間，
衆至十萬，
自稱 rm#r06119@魏帝 。

 rm#r03028@建徳 僞與連和，
 rm#r06119@刀兒 弛備，
 rm#r03028@建徳 襲撃破之，
遂圍 dm#dm05018@深澤 ；
其徒執 rm#r06119@刀兒 降，
 rm#r03028@建徳 斬之，
盡幷其衆。


# p 

 dm#dm03494@易 、 dm#dm02116@定 等州皆降，
唯 dm#dm00712@冀州 刺史 rm#rz0050@麹稜 不下。

 rm#rz0050@稜 壻 rm#r05214@崔履行 ，
 rm#r06584@暹 之孫也，
自言有奇術，
可使攻者自敗，
 rm#rz0050@稜 信之。

 rm#r05214@履行 命守城者皆坐，
毋得妄鬬，
曰：
「賊雖登城，
汝曹勿怖，
吾將使賊自縛。」

於是爲壇，
夜，
設章醮，
然後自衣衰絰，
杖竹登北樓慟哭；
又令婦女升屋四面振裙。

 rm#r03028@建徳 攻之急，
 rm#rz0050@稜 將戰，
 rm#r05214@履行 固止之。

俄而城陷，
 rm#r05214@履行 哭猶未已。

 rm#r03028@建徳 見 rm#rz0050@稜 曰：
「卿忠臣也！」

厚禮之，
以爲内史令。
# p 

十二月，
壬申，
詔以 rm#r01602@秦王世民 爲太尉、使持節、 dm#dm08324@陝東道 大行臺，
其 dm#dm07029@蒲州 、 dm#dm04656@河北 諸府兵馬竝受節度。

# p 

癸酉，
西突厥 rm#?@曷娑那可汗 自 rm#r00748@宇文化及 所來降。

# p 

 dyn#ch174@隋 將 rm#rz0066@堯君素 守 dm#dm04672@河東 ，
上遣 rm#rz0032@呂紹宗 、 rm#r06055@韋義節 、 rm#r02574@獨孤懷恩 相繼攻之，
倶不下。

時外圍嚴急，
 rm#rz0066@君素 爲木鵝，
置表於頸，
具論事勢，
浮之於 dm#dm04650@河 ；
 dm#dm04709@河陽 守者得之，
達於 dm#dm03880@東都 。

 rm#rt0783@皇泰主 見而歎息，
拜 rm#rz0066@君素 金紫光祿大夫。

 rm#r06284@龐玉 、 rm#r02861@皇甫無逸 自 dm#dm03880@東都 來降，
上悉遣詣城下，
爲陳利害，
 rm#rz0066@君素 不從。

又賜金券，
許以不死。

其妻又至城下，
謂之曰：
「 dyn#ch174@隋室 已亡，
君何自苦！」

 rm#rz0066@君素 曰：
「天下名義，
非婦人所知！」

引弓射之，
應弦而倒。

 rm#rz0066@君素 亦自知不濟，
然志在守死，
毎言及國家，
未嘗不歔欷。

謂將士曰：
「吾昔事主上於藩邸，
大義不得不死。

必若 dyn#ch174@隋 祚永終，
天命有屬，
自當斷頭以付諸君，
聽君等持取富貴。

今城池甚固，
倉儲豐備，
大事猶未可知，
不可横生心也！」

 rm#rz0066@君素 性嚴明，
善御衆，
下莫敢叛。

久之，
倉粟盡，
人相食；
又獲外人，
微知 dm#dm04510@江都 傾覆。

丙子，
 rm#rz0066@君素 左右 rm#?@薛宗 、 rm#r05406@李楚客 殺 rm#rz0066@君素 以降，
傳首 dm#dm08170@長安 。

 rm#rz0066@君素 遣朝散大夫 dm#dm07425@解 人 rm#r06235@王行本 將精兵七百在他所，
聞之，
赴救不及，
因捕殺 rm#rz0066@君素 者黨與數百人，
悉誅之，
復乘城拒守，
 rm#r02574@獨孤懷恩 引兵圍之。
# p 

丁酉，
 dyn#ch174@隋  dm#dm07276@襄平 太守 rm#r05951@鄧暠 以 dm#dm03970@柳城 、 dm#dm00855@北平 二郡來降，
以 rm#r05951@暠 爲 dm#dm05611@營州 總管。

酉丑
# p 

辛巳，
太常卿 rm#r03778@鄭元璹 撃 rm#r01583@朱粲 於 dm#dm01379@商州 ，
破之。

# p 

初，
 rm#r00748@宇文化及 遣使招 rm#r03089@羅藝 ，
 rm#r03089@藝 曰：
「我 dyn#ch174@隋 臣也。」

斬其使者，
爲 rm#rt0779@煬帝 發喪，
臨三日。

 rm#r03028@竇建徳 、 rm#r04273@高開道 各遣使招之，
 rm#r03089@藝 曰：
「 rm#r03028@建徳 、 rm#r04273@開道 ，
皆劇賊耳！

吾聞 rm#r04258@唐公 已定 dm#dm08281@關中 ，
人望歸之。

此眞吾主也，
吾將從之，
敢沮議者斬！」

會 rm#r01199@張道源 慰撫 dm#dm02403@山東 ，
 rm#r03089@藝 遂奉表，
與 dm#dm05254@漁陽 、 dm#dm00190@上谷 等諸郡皆來降。

癸未，
詔以 rm#r03089@藝 爲 dm#dm02689@幽州 總管。

 rm#r03310@薛萬均 ，
 rm#r06756@世雄 之子也，
與弟 rm#r03311@萬徹 倶以勇略爲 rm#r03089@藝 所親待，
詔以 rm#r03310@萬均 爲上柱國、 rm#r03310@永安郡公 ，
 rm#r03311@萬徹 爲車騎將軍、 rm#r03311@武安縣公 。

# p 

 rm#r03028@竇建徳 既克 dm#dm00712@冀州 ，
兵威益盛，
帥衆十萬寇 dm#dm02689@幽州 。

 rm#r03089@藝 將逆戰，
 rm#r03310@萬均 曰：
「彼衆我寡，
出戰必敗，
不若使羸兵背城阻水爲陳，
彼必渡水撃我。

 rm#r03310@萬均 請以精騎百人伏於城旁，
俟其半渡撃之，
蔑不勝矣。」

 rm#r03089@藝 從之。

 rm#r03028@建徳 果引兵渡水，
 rm#r03310@萬均 邀撃，
大破之。

 rm#r03028@建徳 竟不能至其城下，
乃分兵掠 dm#dm08592@霍堡 及 dm#dm08500@雍奴 等縣，
 rm#r03089@藝 復邀撃，
敗之。

凡相拒百餘日，
 rm#r03028@建徳 不能克，
乃還 dm#dm04130@樂壽 。


# p 

 rm#r03089@藝 得 dyn#ch174@隋 通直謁者 rm#r02480@温彦博 ，
以爲司馬。

 rm#r03089@藝 以 dm#dm02689@幽州 歸國，
 rm#r02480@彦博 贊成之；
詔以 rm#r02480@彦博 爲 dm#dm02689@幽州 總管府長史，
未幾，
徵爲中書侍郎。

兄 rm#r02475@大雅 ，
時爲黄門侍郎，
與 rm#r02480@彦博 對居近密，
時人榮之。
# p 

以西突厥 rm#?@曷娑那可汗 爲 rm#?@歸義王 ，
 rm#?@曷娑那 獻大珠，
上曰：
「珠誠至寶；
然朕寶王赤心，
珠無所用。」

竟還之。
# p 

乙酉，
車駕幸 dm#dm01312@周氏陂 ，
過 dm#dm03270@故墅 。

丁亥還宮
# p 

初，
羌豪 rm#xjts11077@旁企地 以所部附 rm#r03307@薛舉 ，
及 rm#r03266@薛仁果 敗，
 rm#xjts11077@企地 來降，
留 dm#dm08170@長安 。

 rm#xjts11077@企地 不樂，
帥其衆數千叛，
入 dm#dm00975@南山 ，
出 dm#dm05285@漢川 ，
所過殺掠。

武候大將軍 rm#r06284@龐玉 撃之，
爲 rm#xjts11077@企地 所敗。

 rm#xjts11077@企地 行至 dm#dm01884@始州 ，
掠女子 rm#r04306@王氏 ，
與倶醉臥野外；
 rm#r04306@王氏 拔其佩刀，
斬首送 dm#dm04043@梁州 ，
其衆遂潰。

詔賜 rm#r04306@王氏 號爲 rm#r04306@崇義夫人 。據
# p 

壬辰，
 rm#r02590@王世充 帥衆三萬圍 dm#dm06302@穀州 ，
刺史 rm#r00090@任瓌 拒卻之。

# p 

上使 rm#r01704@李密 分其麾下之半留 dm#dm06938@華州 ，
將其半出 dm#dm08280@關 。

長史 rm#r05267@張寶徳 預在行中，
恐 rm#r01704@密 亡去，
罪相及；
上封事，
言其必叛。

上意乃中變，
又恐 rm#r01704@密 驚駭，
乃降敕書勞來，
令 rm#r01704@密 留所部徐行，
單騎入朝，
更受節度。

# p 

 rm#r01704@密 至 dm#dm06291@稠桑 ，
得敕，
謂 rm#r05892@賈閏甫 曰：
「敕遣我去，
無故復召我還，
天子曏云，
『有人確執不許』，
此譖行矣。

吾今若還，
無復生理，
不若破 dm#dm04014@桃林縣 ，
收其兵糧，
北走渡 dm#dm04650@河 。

比信達 dm#dm05581@熊州 ，
吾已遠矣。

苟得至 dm#dm09166@黎陽 ，
大事必成。

公意如何？」
 rm#r05892@閏甫 曰：
「主上待明公甚厚；
況國家姓名，
著在圖讖，
天下終當一統。

明公既已委質，
復生異圖；
 rm#r00090@任瓌 、 rm#r05100@史萬寶 據 dm#dm05579@熊 、 dm#dm06298@穀 二州，
此事朝舉，
彼兵夕至，
雖克 dm#dm04012@桃林 ，
兵豈暇集，
一稱叛逆，
誰復容人！

爲明公計，
不若且應朝命，
以明元無異心，
自然浸潤不行；
更欲出就 dm#dm02403@山東 ，
徐思其便可也。」

 rm#r01704@密 怒曰：
「 dyn#ch100@唐 使吾與 rm#r06163@絳 、 rm#r06287@灌 同列，
何以堪之！

且讖文之應，
彼我所共。

今不殺我，
聽使東行，
足明王者不死；
縱使 dyn#ch100@唐 遂定 dm#dm08281@關中 ，
 dm#dm02403@山東 終爲我有。

天與不取，
乃欲束手投人！

公，
吾之心腹，
何意如是！

若不同心，
當斬而後行！」

 rm#r05892@閏甫 泣曰：
「明公雖云應讖，
近察天人，
稍已相違。

今海内分崩，
人思自，
強者爲雄；
明公奔亡甫爾，
誰相聽受！

且自 rm#rz0067@翟讓 受戮之後，
人皆謂明公棄恩忘本，
今日誰肯復以所有之兵束手委公乎！

彼必慮公見奪，
逆相拒抗，
一朝失勢，
豈有容足之地哉！

自非荷恩殊厚者，
詎肯深言不諱乎！

願明公熟思之，
但恐大福不再。

苟明公有所措身，
 rm#r05892@閏甫 亦何辭就戮！」

 rm#r01704@密 大怒，
揮刃欲撃之；
 rm#r06230@王伯當 等固請，
乃釋之。

 rm#r05892@閏甫 奔 dm#dm05581@熊州 。

 rm#r06230@伯當 亦止 rm#r01704@密 ，
以爲未可；
 rm#r01704@密 不從。

 rm#r06230@伯當 乃曰：
「義士之志，
不以存亡易心。

公必不聽，
 rm#r06230@伯當 與公同死耳，
然恐終無益也。」

# p 

 rm#r01704@密 因執使者，
斬之。

庚子旦，
 rm#r01704@密 紿 dm#dm04012@桃林 縣官曰：
「奉詔蹔還 dm#dm08170@京師 ，
家人請寄縣舍。」

乃簡驍勇數十人，
著婦人衣，
戴羃䍦，
藏刀裙下，
詐爲妻妾，
自帥之入縣舍，
須臾，
變服突出，
因據縣城。

驅掠徒衆，
直趣 dm#dm00975@南山 ，
乘險而東，
遣人馳告故將 dm#dm00514@伊州 刺史 dm#dm07267@襄城  rm#r01122@張善相 ，
令以兵應接。

# p 

右翊衞將軍 rm#r05100@史萬寶 鎭 dm#dm05581@熊州 ，
謂行軍總管 rm#r02874@盛彦師 曰：
「 rm#r01704@李密 ，
驍賊也，
又輔以 rm#r06230@王伯當 ，
今決策而叛，
殆不可當也。」

 rm#r02874@彦師 笑曰：
「請以數千之衆邀之，
必梟其首。」

 rm#r05100@萬寶 曰：
「公以何策能爾？」
 rm#r02874@彦師 曰：
「兵法尚詐，
不可爲公言之。」

即帥衆踰 dm#dm05587@熊耳山 南，
據要道，
令弓弩夾路乘高，
刀楯伏於溪谷，
令之曰：
「俟賊半渡，
一時倶發。」

或問曰：
「聞 rm#r01704@李密 欲向 dm#dm04778@洛州 ，
而公入山，
何也？」
 rm#r02874@彦師 曰：
「 rm#r01704@密 聲言向 dm#dm04761@洛 ，
實欲出人不意，
走 dm#dm07267@襄城 ，
就 rm#r01122@張善相 耳。

若賊入谷口，
我自後追之，
山路險隘，
無所施力，
一夫殿後，
必不能制。

今吾先得入谷，
擒之必矣。」

# p 

 rm#r01704@李密 既渡 dm#dm08318@陝 ，
以爲餘不足慮，
遂擁衆徐行，
果踰山南出。

 rm#r02874@彦師 撃之，
 rm#r01704@密 衆首尾斷絶，
不得相救，
遂斬 rm#r01704@密 及 rm#r06230@伯當 ，
倶傳首 dm#dm08170@長安 。

 rm#r02874@彦師 以功賜爵 rm#r02874@葛國公 ，
仍領 dm#dm05581@熊州 。
拜武衞將軍
# p 

 rm#r01299@李世勣 在 dm#dm09166@黎陽 ，
上遣使以 rm#r01704@密 首示之，
告以反状。

 rm#r01299@世勣 北面拜伏號慟，
表請收葬；
詔歸其尸。

 rm#r01299@世勣 爲之行服，
備君臣之禮。

大具儀衞，
舉軍縞素，
葬 rm#r01704@密 于 dm#dm09167@黎陽山 南。

 rm#r01704@密 素得士心，
哭者多歐血。
# p 

 dyn#ch174@隋 右武衞大將軍 rm#?@李景 守 dm#dm00855@北平 ，
 rm#r04273@高開道 圍之，
歳餘不能克。

 dm#dm07779@遼西 太守 rm#r05951@鄧暠 將兵救之，
 rm#?@景 帥其衆遷于 dm#dm03970@柳城 ；
後將還 dm#dm02689@幽州 ，
於道爲盜所殺。

 rm#r04273@開道 遂取 dm#dm00855@北平 ，
進陷 dm#dm05257@漁陽郡 ，
有馬數千匹，
衆且萬，
自稱 rm#r04273@燕王 ，
改元 y@始興 ，
都 dm#dm05254@漁陽 。
# p 

 dm#dm03107@懷戎 沙門 rm#r06105@高曇晟 因縣令設齋，
士民大集，
 rm#r06105@曇晟 與僧五千人擁齋衆而反，
殺縣令及鎭將，
自稱 rm#r06105@大乘皇帝 ，
立尼 rm#xjts24066@靜宣 爲 rm#xjts24066@邪輸皇后 ，
改元 y@法輪 。

遣使招 rm#r04273@開道 ，
立爲 rm#r04273@齊王 。

 rm#r04273@開道 帥衆五千人歸之，
居數月，
襲殺 rm#r06105@曇晟 ，
悉幷其衆。
# p 

有犯法不至死者，
上特命殺之。

監察御史 rm#r01908@李素立 諫曰：
「三尺法，
王者所與天下共也；
法一動搖，
人無所措手足。

陛下甫創洪業，
奈何棄法！

臣忝法司，
不敢奉詔。」

上從之。

自是特承恩遇，
命所司授以七品清要官；
所司擬 dm#dm08502@雍州 司戸，
上曰：
「此官要而不清。」

又擬祕書郎，
上曰：
「此官清而不要。」

遂擢授侍御史。

 rm#r01908@素立 ，
 rm#r06637@義深 之曾孫也。

# p 

上以舞胡 rm#xjts11247@安比奴 爲散騎侍郎。

禮部尚書 rm#r01876@李綱 諫曰：
「古者樂工不與士齒，
雖賢如 rm#?@子野 、 rm#?@師襄 ，
皆世不易其業。

唯 dyn#ch171@齊 末封 rm#r06197@曹妙達 爲王，
 rm#r05181@安馬駒 爲開府，
有國家者以爲 dyn#ch102@殷 鑑。

今天下新定，
建義功臣，
行賞未遍，
高才碩學，
猶滯草莱；
而先擢舞胡爲五品，
使鳴玉曳組，
趨翔廊廟，
非所以規模後世也。」

上不從，
曰：
「吾業已授之，
不可追也。」

比叱終身繼
# p 

 rm#r06007@陳嶽 論曰：
「受命之主，
發號出令，
爲子孫法；
一不中理，
則爲厲階。

今 rm#r04258@高祖 曰業已授之，
不可追，
苟授之而是，
則已；
授之而非，
胡不可追歟！

君人之道，
不得不以業已授之爲誡哉！」

# p 

 rm#r01980@李軌 吏部尚書 rm#r05475@梁碩 ，
有智略，
 rm#r01980@軌 常倚之以爲謀主。

 rm#r05475@碩 見諸胡浸盛，
陰勸 rm#r01980@軌 宜加防察，
由是與戸部尚書 rm#r05177@安脩仁 有隙。

 rm#r01980@軌 子 rm#xjts14972@仲琰 嘗詣 rm#r05475@碩 ，
 rm#r05475@碩 不爲禮，
乃與 rm#r05177@脩仁 共譖 rm#r05475@碩 於 rm#r01980@軌 ，
誣以謀反，
 rm#r01980@軌 酖 rm#r05475@碩 ，
殺之。

有胡巫謂 rm#r01980@軌 曰：
「上帝當遣玉女自天而降。」

 rm#r01980@軌 信之，
發民築臺以候玉女，
勞費甚廣。

 dm#dm04667@河右 饑，
人相食，
 rm#r01980@軌 傾家財以賑之；
不足，
欲發倉粟，
召羣臣議之，
 rm#r05339@曹珍 等皆曰：
「國以民爲本，
豈可愛倉粟而坐視其死乎！」

 rm#r05875@謝統師 等皆故 dyn#ch174@隋 官，
心終不服，
密與羣胡爲黨，
排 rm#r01980@軌 故人，
乃詬 rm#r05339@珍 曰：
「百姓餓者自是羸弱，
勇壯之士終不至此。

國家倉粟以備不虞，
豈可散之以飼羸弱！

僕射苟悦人情，
不爲國計，
非忠臣也。」

 rm#r01980@軌 以爲然，
由是士民離怨。


*** 武徳二年
# year 0619
# p 

春，
正月，
壬寅，
 rm#r02590@王世充 悉取 dyn#ch174@隋朝 顯官、名士爲太尉府官屬，
 rm#r02056@杜淹 、 rm#r01373@戴冑 皆預焉。

 rm#r01373@冑 ，
 dm#dm02084@安陽 人也。

 dyn#ch174@隋 將軍 rm#?@王隆 帥屯衞將軍 rm#r06193@張鎭周 、都水少監 rm#r03326@蘇世長 等以 dm#dm02398@山南 兵始至 dm#dm03880@東都 。

 rm#r02590@王世充 專總朝政，
事無大小，
悉關太尉府；
臺省監署，
莫不闃然。

 rm#r02590@世充 立三牌於府門外：
一求文學才識，
堪濟時務者；
一求武勇智略，
能摧鋒陷敵者；
一求身有冤滯，
擁抑不申者。

於是上書陳事日有數百，
 rm#r02590@世充 悉引見，
躬自省覽，
殷勤慰諭，
人人自喜，
以爲言聽計從，
然終無所施行。

下至士卒廝養，
 rm#r02590@世充 皆以甘言悦之，
而實無恩施。
者
# p 

 dyn#ch174@隋 馬軍總管 rm#r05592@獨孤武都 爲 rm#r02590@世充 所親任，
其從弟司隸大夫 rm#r05591@機 與虞部郎 rm#r05497@楊恭愼 、前 dm#dm00806@勃海郡 主簿 rm#r05160@孫師孝 、歩兵總管 rm#r05063@劉孝元 、 rm#r01620@李儉 、 rm#r05211@崔孝仁 謀召 dyn#ch100@唐 兵，
使 rm#r05211@孝仁 説 rm#r05592@武都 曰：
「 rm#r02590@王公 徒爲兒女之態以悦下愚，
而鄙隘貪忍，
不顧親舊，
豈能成大業哉！

圖讖之文，
應歸 rm#no@李氏 ，
人皆知之。

 dyn#ch100@唐 起 dm#dm03567@晉陽 ，
奄有 dm#dm08283@關内 ，
兵不留行，
英雄景附。

且坦懷待物，
舉善責功，
不念舊惡，
據勝勢以爭天下，
誰能敵之！

吾屬託身非所，
坐待夷滅。

今 rm#r00090@任管公 兵近在 dm#dm03337@新安 ，
又吾之故人也，
若遣間使召之，
使夜造城下，
吾曹共爲内應，
開門納之，
事無不集矣。」

 rm#r05592@武都 從之。

事泄，
 rm#r02590@世充 皆殺之。

 rm#r05497@恭愼 ，
 rm#r06658@達 之子也。

# p 

癸卯，
命 rm#r01602@秦王世民 出鎭 dm#dm08188@長春宮 。

# p 

 rm#r00748@宇文化及 攻 dm#dm08950@魏州 總管 rm#r05040@元寶藏 ，
四旬不克。

 rm#r04294@魏徵 往説之，
丁未，
 rm#r05040@寶藏 舉州來降。


# p 

戊午，
 rm#r02450@淮安王神通 撃 rm#r00748@宇文化及 於 dm#dm08955@魏縣 ，
 rm#r00748@化及 不能抗，
東走 dm#dm06596@聊城 。

 rm#r02450@神通 拔 dm#dm08955@魏縣 ，
斬獲二千餘人，
引兵追 rm#r00748@化及 至 dm#dm06596@聊城 ，
圍之。
# p 

甲子，
以 rm#r03915@陳叔達 爲納言。
# p 

丙寅，
 rm#r01704@李密 所置 dm#dm00514@伊州 刺史 rm#r01122@張善相 來降。

# p 

 rm#r01583@朱粲 有衆二十萬，
剽掠 dm#dm05271@漢 、 dm#dm04981@淮 之間，
遷徙無常，
毎破州縣，
食其積粟未盡，
復他適，
將去，
悉焚其餘資；
又不務稼穡，
民餒死者如積。

 rm#r01583@粲 無可復掠，
軍中乏食，
乃教士卒烹婦人、嬰兒噉之，
曰：
「肉之美者無過於人，
但使他國有人，
何憂於餒！」

 dyn#ch174@隋 著作佐郎 rm#r06025@陸從典 、通事舍人 rm#r06069@顏愍楚 謫官在 dm#dm01077@南陽 ，
 rm#r01583@粲 初引爲賓客，
其後無食，
闔家皆爲所噉。

 rm#r06069@愍楚 ，
 rm#r06845@之推 之子也。

又税諸城堡細弱以供軍食，
諸城堡相帥叛之。

# p 

 dm#dm04992@淮安 土豪 rm#r05490@楊士林 、 rm#r06238@田瓚 起兵攻 rm#r01583@粲 ，
諸州皆應之。

 rm#r01583@粲 與戰于 dm#dm05002@淮源 ，
大敗，
帥餘衆數千奔 dm#dm06924@菊潭 。

 rm#r05490@士林 家世蠻酋，
 dyn#ch174@隋 末，
 rm#r05490@士林 爲鷹揚府校尉，
殺郡官而據其郡。

既逐 rm#r01583@朱粲 ，
己巳，
帥 dm#dm05291@漢東 四郡遣使詣 dm#dm00576@信州 總管 rm#r01070@廬江王瑗 請降，
詔以爲 dm#dm08765@顯州道 行臺。

 rm#r05490@士林 以 rm#r06238@瓚 爲長史。
# p 

初，
 rm#r02590@王世充 既殺 rm#r05044@元 、 rm#r05706@盧 ，
慮人情未服，
猶媚事 rm#rt0783@皇泰主 ，
禮甚謙敬。

又請爲 rm#xjts25644@劉太后 假子，
尊號曰 rm#xjts25644@聖感皇太后 。

既而漸驕横，
嘗賜食於禁中，
還家大吐，
疑遇毒，
自是不復朝謁。

 rm#rt0783@皇泰主 知其終不爲臣，
而力不能制，
唯取内庫綵物大造幡花；
又出諸服玩，
令僧散施貧乏以求福。

 rm#r02590@世充 使其黨 rm#r05291@張績 、 rm#r05773@董濬 守 dm#dm06336@章善 、 dm#dm08770@顯福 二門，
宮内雜物，
毫釐不得出。

是月，
 rm#r02590@世充 使人獻印及劍。

又言 dm#dm04679@河水 清，
欲以耀衆，
爲己符瑞云。


# p 

上遣金紫光祿大夫 dm#dm04228@武功  rm#?@靳孝謨 安集邊郡，
爲 rm#r02125@梁師都 所獲。

 rm#?@孝謨 罵之極口，
 rm#r02125@師都 殺之。

二月，
詔追賜爵 rm#?@武昌縣公 ，
諡曰 rm#?@忠 。
# p 

初定租、庸、調法，
毎丁租二石，
絹二匹，
綿三兩；
自茲以外，
不得横有調斂。

# p 

丙戌，
詔：
「諸宗姓居官者在同列之上，
未仕者免其傜役；
毎州置宗師一人以攝總，
別爲團伍。」

# p 

 rm#r05247@張俟徳 至 dm#*dm04947@涼 ，
 rm#r01980@李軌 召其羣臣廷議曰：
「 dyn#ch100@唐 天子，
吾之從兄，
今已正位 dm#dm00449@京邑 。

一姓不可自爭天下，
吾欲去帝號，
受其封爵，
可乎？」
 rm#r05339@曹珍 曰：
「 dyn#ch174@隋 失其鹿，
天下共逐之，
稱王稱帝者，
奚啻一人！

 dyn#ch100@唐 帝 dm#dm08281@關中 ，
 dm#*dm04947@涼 帝 dm#dm04667@河右 ，
固不相妨。

且已爲天子，
奈何復自貶黜！

必欲以小事大，
請依 rm#rt0712@蕭詧 事 dyn#ch169@魏 故事。」

 rm#r01980@軌 從之。

戊戌，
 rm#r01980@軌 遣其尚書左丞 rm#r05952@鄧曉 入見，
奉書稱「皇從弟 rm#r01980@大涼皇帝 臣 rm#r01980@軌 」
而不受官爵。

帝怒，
拘 rm#r05952@曉 不遣，
始議興師討之。


# p 

初，
 rm#rt0779@隋煬帝 自征吐谷渾，
吐谷渾可汗 rm#xjts20264@伏允 以數千騎奔黨項，
 rm#rt0779@煬帝 立其質子 rm#xjts22519@順 爲主，
使統餘衆，
不果入而還。

會 dm#dm00255@中國 喪亂，
 rm#xjts20264@伏允 復還收其故地。

上受禪，
 rm#xjts22519@順 自 dm#dm04510@江都 還 dm#dm08170@長安 ，
上遣使與 rm#xjts20264@伏允 連和，
使撃 rm#r01980@李軌 ，
許以 rm#xjts22519@順 還之。

 rm#xjts20264@伏允 喜，
起兵撃 rm#r01980@軌 ，
數遣使入貢請 rm#xjts22519@順 ，
上遣之。

# p 

閏月，
 rm#r01583@朱粲 遣使請降，
詔以 rm#r01583@粲 爲 rm#r01583@楚王 ，
聽自置官屬，
以便宜從事。
# p 

 rm#r00748@宇文化及 以珍貨誘海曲諸賊，
賊帥 rm#r06234@王薄 帥衆從之，
與共守 dm#dm06596@聊城 。
# p 

 rm#r03028@竇建徳 謂其羣下曰：
「吾爲 dyn#ch174@隋 民，
 dyn#ch174@隋 爲吾君；
今 rm#r00748@宇文化及 弑逆，
乃吾讎也，
吾不可以不討！」

乃引兵趣 dm#dm06596@聊城 。

# p 

 rm#r02450@淮安王神通 攻 dm#dm06596@聊城 ，
 rm#r00748@化及 糧盡，
請降，
 rm#r02450@神通 不許。

安撫副使 rm#r06182@崔世幹 勸 rm#r02450@神通 許之，
 rm#r02450@神通 曰：
「軍士暴露日久，
賊食盡計窮，
克在旦暮，
吾當攻取以示國威，
且散其玉帛以勞將士，
若受其降，
將何以爲軍賞乎！」

 rm#r06182@世幹 曰：
「今 rm#r03028@建徳 方至，
若 rm#r00748@化及 未平，
内外受敵，
吾軍必敗。

夫不攻而下之，
爲功甚易，
奈何貪其玉帛而不受乎！」

 rm#r02450@神通 怒，
囚 rm#r06182@世幹 於軍中。

既而 rm#r00750@宇文士及 自 dm#dm05434@濟北 餽之，
 rm#r00748@化及 軍稍振，
遂復拒戰。

 rm#r02450@神通 督兵攻之，
 dm#dm07514@貝州 刺史 rm#r05897@趙君徳 攀堞先登，
 rm#r02450@神通 心害其功，
收兵不戰，
 rm#r05897@君徳 大詬而下，
遂不克。

 rm#r03028@建徳 軍且至，
 rm#r02450@神通 引兵退。
# p 

 rm#r03028@建徳 與 rm#r00748@化及 連戰，
大破之，
 rm#r00748@化及 復保聊城。

 rm#r03028@建徳 縱兵四面急攻，
 rm#r06234@王薄 開門納之。

 rm#r03028@建徳 入城，
生擒 rm#r00748@化及 ，
先謁 dyn#ch174@隋  rm#rz0007@蕭皇后 ，
語皆稱臣，
素服哭 rm#rt0779@煬帝 盡哀；
收傳國璽及鹵簿儀仗，
撫存 dyn#ch174@隋 之百官，
然後執逆黨 rm#r05169@宇文智及 、 rm#r05491@楊士覽 、 rm#r05046@元武達 、 rm#r05860@許弘仁 、 rm#r05152@孟景 ，
集 dyn#ch174@隋 官而斬之，
梟首軍門之外。

以檻車載 rm#r00748@化及 幷二子 rm#?@承基 、 rm#?@承趾 至 dm#dm07262@襄國 ，
斬之。

 rm#r00748@化及 且死，
更無餘言，
但云：
「不負 rm#r03028@夏王 ！」


# p 

 rm#r03028@建徳 毎戰勝克城，
所得資財，
悉以分將士，
身無所取。

又不噉肉，
常食蔬，
茹粟飯；
妻 rm#xjts24204@曹氏 ，
不衣紈綺，
所役婢妾，
纔十許人。

及破 rm#r00748@化及 ，
得 dyn#ch174@隋 宮人千數，
即時散遣之。

以 dyn#ch174@隋 黄門侍郎 rm#r03452@裴矩 爲左僕射、掌選事，
兵部侍郎 rm#r05210@崔君肅 爲侍中，
少府令 rm#r05028@何稠 爲工部尚書，
右司郎中 rm#r05464@柳調 爲左丞，
 rm#r03353@虞世南 爲黄門侍郎，
 rm#r02288@歐陽詢 爲太常卿。

 rm#r02288@詢 ，
 rm#r06670@紇 之子也。

自餘隨才授職，
委以政事。

其不願留，
欲詣 dm#dm08281@關中 及 dm#dm03880@東都 者亦聽之，
仍給資糧，
以兵援之出境。

 dyn#ch174@隋 驍果尚近萬人，
亦各縱遣，
任其所之。

又與 rm#r02590@王世充 結好，
遣使奉表於 dyn#ch174@隋  rm#rt0783@皇泰主 ，
 rm#rt0783@皇泰主 封爲 rm#r03028@夏王 。

 rm#r03028@建徳 起於羣盜，
雖建國，
未有文物法度，
 rm#r03452@裴矩 爲之定朝儀，
制律令，
 rm#r03028@建徳 甚悦，
毎從之諮訪典禮。
# p 

甲辰，
上考第羣臣，
以 rm#r01876@李綱 、 rm#r00709@孫伏伽 爲第一，
因置酒高會，
謂 rm#r03424@裴寂 等曰：
「 dyn#ch174@隋氏 以主驕臣諂亡天下，
朕即位以來，
毎虚心求諫，
然惟 rm#r01876@李綱 差盡忠款，
 rm#r00709@孫伏伽 可謂誠直，
餘人猶踵敝風，
俛眉而已，
豈朕所望哉！

朕視卿如愛子，
卿當視朕如慈父，
有懷必盡，
勿自隱也！」

因命捨君臣之敬，
極歡而罷。


# p 

遣前御史大夫 rm#r05549@段確 使於 rm#r01583@朱粲 。

# p 

初，
上爲 dyn#ch174@隋 殿内少監，
 rm#r00750@宇文士及 爲尚輦奉御，
上與之善。

 rm#r00750@士及 從 rm#r00748@化及 至 dm#dm09166@黎陽 ，
上手詔召之，
 rm#r00750@士及 潛遣家僮間道詣 dm#dm08170@長安 ，
又因使者獻金環。

 rm#r00748@化及 至 dm#dm08955@魏縣 ，
兵勢日蹙，
 rm#r00750@士及 勸之歸 dyn#ch100@唐 ，
 rm#r00748@化及 不從，
内史令 rm#r00851@封徳彞 説 rm#r00750@士及 於 dm#dm05434@濟北 徵督軍糧以觀其變。

 rm#r00748@化及 稱帝，
立 rm#r00750@士及 爲 rm#r00750@蜀王 。

 rm#r00748@化及 死，
 rm#r00750@士及 與 rm#r00851@徳彞 自 dm#dm05434@濟北 來降。

時 rm#r00750@士及 妹爲昭儀，
由是授上儀同。

上以 rm#r00851@封徳彞  dyn#ch174@隋 室舊臣，
而諂巧不忠，
深誚責之，
罷遣就舍。

 rm#r00851@徳彞 以祕策干上，
上悦，
尋拜内史舍人，
俄遷侍郎。

# p 

甲寅，
 dyn#ch174@隋  dm#dm01841@夷陵郡 丞 dm#dm02081@安陸  rm#r03523@許紹 帥 dm#dm09187@黔安 、 dm#dm04319@武陵 、 dm#dm05408@澧陽 等諸郡來降。

 rm#r03523@紹 幼與帝同學；
詔以 rm#r03523@紹 爲 dm#dm02449@峽州 刺史，
賜爵 rm#r03523@安陸公 。
# p 

丙辰，
以 rm#r01299@徐世勣 爲 dm#dm09164@黎州 總管。


# p 

丁巳，
驃騎將軍 rm#r05261@張孝珉 以勁卒百人襲 rm#r02590@王世充  dm#dm04456@汜水城 ，
入其郛，
沈米船百五十艘。

# p 

己未，
 rm#r02590@世充 寇 dm#dm06302@穀州 。

 rm#r02590@世充 以 rm#r02977@秦叔寶 爲龍驤大將軍，
 rm#r02983@程知節 爲將軍，
待之皆厚。

然二人疾 rm#r02590@世充 多詐，
 rm#r02983@知節 謂 rm#r02977@叔寶 曰：
「 rm#r02590@王公 器度淺狹而多妄語，
好爲呪誓，
此乃老巫嫗耳，
豈撥亂之主乎！」

 rm#r02590@世充 與 dyn#ch100@唐 兵戰於 dm#dm00326@九曲 ，
 rm#r02977@叔寶 、 rm#r02983@知節 皆將兵在陳，
與其徒數十騎，
西馳百許歩，
下馬拜 rm#r02590@世充 曰：
「僕荷公殊禮，
深思報效；
公性猜忌，
喜信讒言，
非僕託身之所，
今不能仰事，
請從此辭。」

遂躍馬來降。

 rm#r02590@世充 不敢逼。

上使事 rm#r01602@秦王世民 ，
 rm#r01602@世民 素聞其名，
厚禮之，
以 rm#r02977@叔寶 爲馬軍總管，
 rm#r02983@知節 爲左三統軍。

時 rm#r02590@世充 驍將又有驃騎 dm#dm04244@武安  rm#r01653@李君羨 、征南將軍 dm#dm06738@臨邑  rm#r05677@田留安 ，
亦惡 rm#r02590@世充 之爲人，
帥衆來降。

 rm#r01602@世民 引 rm#r01653@君羨 置左右，
以 rm#r05677@留安 爲右四統軍。
# p 

 rm#r02590@王世充 囚 rm#r01929@李育徳 之兄 rm#r05354@厚徳 於 dm#dm05675@獲嘉 ，
 rm#r05354@厚徳 與其守將 rm#r05898@趙君穎 逐 dm#dm04359@殷州 刺史 rm#r05544@段大師 ，
以城來降。

以 rm#r05354@厚徳 爲 dm#dm04359@殷州 刺史。

# p 

 rm#r03028@竇建徳 陷 dm#dm07817@邢州 ，
執總管 rm#r03917@陳君賓 。
# p 

上遣殿内監 rm#r03046@竇誕 、右衞將軍 rm#r00758@宇文歆 助 dm#dm00059@幷州 總管 rm#r01016@齊王元吉 守 dm#dm03567@晉陽 。

 rm#r03046@誕 ，
 rm#r03033@抗 之子也，
尚帝女 rm#r03483@襄陽公主 。

 rm#r01016@元吉 性驕侈，
奴客婢妾數百人，
好使之被甲，
戲爲攻戰，
前後死傷甚衆，
 rm#r01016@元吉 亦嘗被傷。

其乳母 rm#r06003@陳善意 苦諫，
 rm#r01016@元吉 醉，
怒，
命壯士毆殺之。

性好田獵，
載罔罟三十車，
嘗言：
「我寧三日不食，
不能一日不獵。」

常與 rm#r03046@誕 遊獵，
蹂踐人禾稼。

又縱左右奪民物，
當衢射人，
觀其避箭。

夜，
開府門，
宣淫他室。

百姓憤怨，
歆屡諫不納，
乃表言其状。

壬戌，
 rm#r01016@元吉 坐免官。

# p 

癸亥，
 dm#dm08330@陟州 刺史 rm#r01929@李育徳 攻下 rm#r02590@王世充  dm#dm04653@河内 堡聚三十一所。

乙丑，
 rm#r02590@世充 遣其兄子 rm#r02607@君廓 侵 dm#dm08330@陟州 ，
 rm#r01929@李育徳 撃走之，
斬首千餘級。

 rm#r05354@李厚徳 歸省親疾，
使 rm#r01929@李育徳 守 dm#dm05675@獲嘉 ，
 rm#r02590@世充 倂兵攻之；
丁卯，
城陷，
 rm#r01929@育徳 及弟三人皆戰死。
# p 

己巳，
 rm#r01641@李公逸 以 dm#dm08496@雍丘 來降，
拜 dm#dm00063@𣏌州 總管，
以其族弟 rm#r05345@善行 爲 dm#dm00063@𣏌州 刺史。

# p 

 dyn#ch174@隋 吏部侍郎 rm#r02189@楊恭仁 ，
從 rm#r00748@宇文化及 至 dm#dm04656@河北 ；
 rm#r00748@化及 敗，
 dm#dm08950@魏州 總管 rm#r05040@元寶藏 獲之，
己巳，
送 dm#dm08170@長安 。

上與之有舊，
拜黄門侍郎，
尋以爲 dm#dm04947@涼州 總管。

 rm#r02189@恭仁 素習邊事，
曉羌、胡情僞，
民夷悦服，
自 dm#dm00020@葱嶺 已東，
竝入朝貢。

# p 

突厥 rm#rz0041@始畢可汗 將其衆渡 dm#dm04650@河 至 dm#dm01538@夏州 ，
 rm#r02125@梁師都 發兵會之，
以五百騎授 rm#r00280@劉武周 ，
欲自 dm#dm01149@句注 入寇 dm#dm01774@太原 。

會 rm#rz0041@始畢 卒，
子 rm#xjts11264@什鉢苾 幼，
未可立，
立其弟 rm#xjts08013@俟利弗設 爲 rm#xjts08013@處羅可汗 。

 rm#xjts08013@處羅 以 rm#xjts11264@什鉢苾 爲尼歩設，
使居東偏，
直 dm#dm02689@幽州 之北。

先是，
上遣右武候將軍 rm#r06117@高靜 奉幣使於突厥，
至 dm#dm07478@豐州 ，
聞 rm#rz0041@始畢 卒，
敕納於所在之庫。

突厥聞之，
怒，
欲入寇；
 dm#dm07478@豐州 總管 rm#r01267@張長遜 遣 rm#r06117@高靜 以幣出塞爲朝廷致賻，
突厥乃還。

# p 

三月，
庚午，
 rm#r02125@梁師都 寇 dm#dm08619@靈州 ，
長史 rm#r05485@楊則 撃走之。

# p 

壬申，
 rm#r02590@王世充 寇 dm#dm06302@穀州 ，
刺史 rm#r05100@史萬寶 戰不利。
# p 

庚辰，
 dyn#ch174@隋  dm#dm00875@北海 通守 rm#r05964@鄭虔符 、 dm#dm05863@登 令 rm#r05333@方惠整 及 dm#dm03844@東海 、 dm#dm09215@齊郡 、 dm#dm03822@東平 、 dm#dm00495@任城 、 dm#dm02680@平陸 、 dm#dm01523@壽張 、 dm#dm08754@須昌 賊帥 rm#r06234@王薄 等竝以其地來降。

# p 

 rm#r02590@王世充 之寇 dm#dm03337@新安 也，
外示攻取，
實召文武之附己者議受禪。

 rm#r05347@李世英 深以爲不可，
曰：
「四方所以奔馳歸附 dm#dm03880@東都 者，
以公能中興 dyn#ch174@隋室 故也。

今九州之地，
未清其一，
遽正位號，
恐遠人皆思叛去矣！」

 rm#r02590@世充 曰：
「公言是也！」

長史 rm#r06054@韋節 、 rm#r02241@楊續 等曰：
「 dyn#ch174@隋氏 數窮，
在理昭然。

夫非常之事，
固不可與常人議之。」

太史令 rm#r05523@樂徳融 曰：
「昔歳長星出，
乃除舊布新之徵；
 y@今歳 星在角、亢，
亢，
 dm#dm07947@鄭 之分野。

若不亟順天道，
恐王氣衰息。」

 rm#r02590@世充 從之。

外兵曹參軍 rm#r01373@戴冑 言於 rm#r02590@世充 曰：
「君臣猶父子也，
休戚同之。

明公莫若竭忠徇國，
則家國倶安矣。」

 rm#r02590@世充 詭辭稱善而遣之。

 rm#r02590@世充 議受九錫，
 rm#r01373@冑 復固諫，
 rm#r02590@世充 怒，
出爲 dm#dm07949@鄭州 長史，
使與兄子 rm#?@行本 鎭 dm#dm07165@虎牢 。

乃使 rm#r05551@段達 等言於 rm#rt0783@皇泰主 ，
請加 rm#r02590@世充 九錫。

 rm#rt0783@皇泰主 曰：
「 rm#r02590@鄭公 近平 rm#r01704@李密 ，
已拜太尉，
自是以來，
未有殊績，
俟天下稍平，
議之未晩。」

 rm#r05551@段達 曰：
「太尉欲之。

」
 rm#rt0783@皇泰主 熟視 rm#r05551@達 曰：
「任公！」

辛巳，
 rm#r05551@達 等以 rm#rt0783@皇泰主 之詔命 rm#r02590@世充 爲相國，
假黄鉞，
總百揆，
進爵 rm#r02590@鄭王 ，
加九錫，
 dm#dm07948@鄭國 置丞相以下官。
# p 

初，
 rm#r00748@宇文化及 以 dyn#ch174@隋 大理卿 rm#r03785@鄭善果 爲民部尚書，
從至 dm#dm06596@聊城 ，
爲 rm#r00748@化及 督戰，
中流矢。

 rm#r03028@竇建徳 克 dm#dm06596@聊城 ，
 rm#r05651@王琮 獲 rm#r03785@善果 ，
責之曰：
「公名臣之家，
 dyn#ch174@隋室 大臣，
奈何爲弑君之賊效命，
苦戰傷痍至此乎！」

 rm#r03785@善果 大慙，
欲自殺，
 rm#r05187@宋正本 馳往救止之；
 rm#r03028@建徳 復不爲禮，
乃奔 dm#dm06029@相州 ，
 rm#r02450@淮安王神通 送之 dm#dm08170@長安 。

庚午，
 rm#r03785@善果 至，
上優禮之，
拜左庶子、檢校内史侍郎。
庚壬
# p 

 rm#r01016@齊王元吉 諷 dm#dm00059@幷州 父老詣闕留己；
甲申，
復以 rm#r01016@元吉 爲 dm#dm00059@幷州 總管。

# p 

戊子，
 dm#dm04984@淮南 五州皆遣使來降。


# p 

辛卯，
 rm#r00280@劉武周 寇 dm#dm00059@幷州 。
# p 

壬辰，
 dm#dm05611@營州 總管 rm#r05951@鄧暠 撃 rm#r04273@高開道 ，
敗之。

# p 

甲午，
 rm#r02590@王世充 遣其將 rm#r06107@高毘 寇 dm#dm06542@義州 。

# p 

 dm#dm03880@東都 道士 rm#r05467@桓法嗣 獻孔子閉房記於 rm#r02590@王世充 ，
言相國當代 dyn#ch174@隋 爲天子。

 rm#r02590@世充 大悦，
以 rm#r05467@法嗣 爲諫議大夫。

 rm#r02590@世充 又羅取雜鳥，
書帛繋頸，
自言符命而縱之。

有得鳥來獻者，
亦拜官爵。

於是 rm#r05551@段達 以 rm#rt0783@皇泰主 命，
加 rm#r02590@世充 殊禮，
 rm#r02590@世充 奉表三讓。

百官勸進，
設位於都堂。

納言 rm#r06246@蘇威 年老，
不任朝謁，
 rm#r02590@世充 以 rm#r06246@威  dyn#ch174@隋氏 重臣，
欲以眩耀士民，
毎勸進，
必冠 rm#r06246@威 名。

及受殊禮之日，
扶 rm#r06246@威 置百官之上，
然後南面正坐受之。
# p 

夏，
四月，
 rm#r00280@劉武周 引突厥之衆，
軍於 dm#dm09150@黄蛇嶺 ，
兵鋒甚盛。

 rm#r01016@齊王元吉 使車騎將軍 rm#r05306@張達 以歩卒嘗寇；
 rm#r05306@達 辭以兵少不可往，
 rm#r01016@元吉 強遣之，
至則倶沒。

 rm#r05306@達 忿恨，
庚子，
引 rm#r00280@武周 襲 dm#dm04106@楡次 ，
陷之。
百人
# p 

散騎常侍 rm#r05549@段確 ，
性嗜酒，
奉詔慰勞 rm#r01583@朱粲 於 dm#dm06924@菊潭 。

辛丑，
乘醉侮 rm#r01583@粲 曰：
「聞卿好噉人，
人作何味？」
 rm#r01583@粲 曰：
「噉醉人正如糟藏彘肉。」

 rm#r05549@確 怒，
罵曰：
「狂賊入朝，
爲一頭奴耳，
復得噉人乎！」

 rm#r01583@粲 於座收 rm#r05549@確 及從者數十人，
悉烹之以噉左右。

遂屠 dm#dm06924@菊潭 ，
奔 rm#r02590@王世充 ，
 rm#r02590@世充 以爲龍驤大將軍。

# p 

 rm#r02590@王世充 令長史 rm#r06054@韋節 、 rm#r02241@楊續 等及太常博士 dm#dm07232@衡水  rm#r00680@孔穎達 ，
造禪代儀，
遣 rm#r05551@段達 、 rm@雲定興 等十餘人入奏 rm#rt0783@皇泰主 曰：
「天命不常，
 rm#r02590@鄭王 功徳甚盛，
願陛下遵 rm#rt0006@唐  rm#rt0007@虞 之迹！」

 rm#rt0783@皇泰主 斂膝據案，
怒曰：
「天下，
 rm#r04258@高祖 之天下，
若 dyn#ch174@隋 祚未亡，
此言不應輒發；
必天命已改，
何煩禪讓！

公等或祖禰舊臣，
或臺鼎高位，
既有斯言，
朕復何望！」

顏色凜冽，
在廷者皆流汗。

退朝，
泣對太后。

 rm#r02590@世充 更使人謂之曰：
「今海内未寧，
須立長君，
俟四方安集，
當復子明辟，
必如前誓。」

癸卯，
 rm#r02590@世充 稱 rm#rt0783@皇泰主 命，
禪位于 dyn#?@鄭 ，
遣其兄 rm#rz0024@世惲 幽 rm#rt0783@皇泰主 於 dm#dm01273@含涼殿 ，
雖有三表陳讓及敕書敦勸，
 rm#rt0783@皇泰主 皆不知也。

遣諸將引兵入清宮城，
又遣術人以桃湯葦火祓除禁省。

# p 

 dyn#ch174@隋 將帥、郡縣及賊帥前後繼有降者，
詔以 rm#r06234@王薄 爲 dm#dm09208@齊州 總管，
 rm@伏徳 爲 dm#dm05438@濟州 總管，
 rm#r05964@鄭虔符 爲 dm#dm08665@青州 總管，
 rm#xjts21806@綦公順 爲 dm#dm04997@淮州 總管，
 rm#r05615@王孝師 爲 dm#dm05209@滄州 總管。

# p 

甲辰，
遣大理卿 dm#dm03363@新樂  rm#?@郎楚之 安撫 dm#dm02403@山東 ，
祕書監 rm#r00593@夏侯端 安撫 dm#dm04998@淮左 。
# p 

乙巳，
 rm#r02590@王世充 備法駕入宮，
即皇帝位；
丙午，
大赦，
改元 y@開明 。

# p 

丁未，
 dyn#ch174@隋 禦衞將軍 rm#r06021@陳稜 以 dm#dm04510@江都 來降；
以 rm#r06021@稜 爲 dm#dm03246@揚州 總管。

# p 

戊申，
 rm#r02590@王世充 立子 rm#?@玄應 爲太子，
 rm#xjts01871@玄恕 爲 rm#xjts01871@漢王 ，
餘兄弟宗族十九人皆爲王。

奉 rm#rt0783@皇泰主 爲 rm#rt0783@潞國公 。

以 rm#r06246@蘇威 爲太師，
 rm#r05551@段達 爲司徒，
 rm@雲定興 爲太尉，
 rm#r05249@張僅 爲司空，
 rm#r02241@楊續 爲納言，
 rm#r06054@韋節 爲内史，
 rm@王隆 爲左僕射，
 rm#r06061@韋霽 爲右僕射，
 rm#rz0024@齊王世惲 爲尚書令，
 rm#r06219@楊汪 爲吏部尚書，
 rm#r02056@杜淹 爲少吏部，
 rm#rz0004@鄭頲 爲御史大夫。

 rm#rz0024@世惲 ，
 rm#r02590@世充 之兄也。

又以國子助教 dm#dm01275@呉 人 rm#r03948@陸徳明 爲 rm@漢王 師，
令 rm@玄恕 就其家行束脩禮。

 rm#r03948@徳明 恥之，
服巴豆散，
臥稱病，
 rm@玄恕 入跪牀下，
對之遺利，
竟不與語。

 rm#r03948@徳明 名 rm#r03948@朗 ，
以字行。

# p 

世充於闕下及玄武門等數處皆設榻，
坐無常所，
親受章表；
或輕騎歴衢市，
亦不清道，
民但避路而已。

世充按轡徐行，
語之曰：
「昔時天子深居九重，
在下事情無由聞徹。

今世充非貪天位，
但欲救恤時危，
正如一州刺史，
親覽庶務，
當與士庶共評朝政，
尚恐門有禁限，
今於門外設坐聽朝，
宜各盡情。」

又令西朝堂納冤抑，
東朝堂納直諫。

於是獻策上書者日有數百，
條流既煩，
省覽難遍，
數日後，
不復更出。

# p 

 rm#r03028@竇建徳 聞 rm#r02590@王世充 自立，
乃絶之，
始建天子旌旗，
出警入蹕，
下書稱詔，
追諡 rm#rt0779@隋煬帝 爲 rm#rt0779@閔帝 。

 rm#rz0017@齊王暕 之死也，
有遺腹子 rm@政道 ，
 rm#r03028@建徳 立以爲 rm@鄖公 ，
然猶依倚突厥以壯其兵勢。

 rm@隋義成公主 遣使迎 rm#rz0007@蕭皇后 及 rm#rz0009@南陽公主 ，
 rm#r03028@建徳 遣千餘騎送之，
又傳 rm#r00748@宇文化及 首以獻 rm@義成公主 。廢皇泰主
# p 

丙辰，
 rm#r00280@劉武周 圍 dm#dm00059@幷州 ，
 rm#r01016@齊王元吉 拒卻之。

戊午，
詔太常卿 rm#r01611@李仲文 將兵救 dm#dm00059@幷州 。


# p 

 rm#r02590@王世充 將軍 rm#r05009@丘懷義 居門下内省，
召 rm#xjts02037@越王君度 、 rm#xjts01871@漢王玄恕 、將軍 rm#xjts01484@郭士衡 雜妓妾飮博，
侍御史 rm#r01246@張蘊古 彈之。

 rm#r02590@世充 大怒，
令散手執 rm#xjts02037@君度 、 rm#xjts01871@玄恕 ，
批其耳數十；
又命引入 dm#dm03785@東上閤 ，
杖之各數十。

 rm#r05009@懷義 、 rm#xjts01484@士衡 不問。

賞 rm#r01246@蘊古 帛百段，
遷太子舍人。

 rm#xjts02037@君度 ，
 rm#r02590@世充 之兄子也。
# p 

 rm#r02590@世充 毎聽朝，
殷勤誨諭，
言詞重複，
千端萬緒，
侍衞之人不勝倦弊，
百司奏事，
疲於聽受。

御史大夫 rm@蘇良 諫曰：
「陛下語太多而無領要，
計云爾即可，
何煩許辭也！」

 rm#r02590@世充 默然良久，
亦不罪 rm@良 ，
然性如是，
終不能改也。
# p 

 rm#r02590@王世充 數攻 dm#dm00514@伊州 ，
總管 rm#r01122@張善相 拒之；
糧盡，
援兵不至，
癸亥，
城陷，
 rm#r01122@善相 罵 rm#r02590@世充 極口而死。

帝聞，
歎曰：
「吾負 rm#r01122@善相 ，
 rm#r01122@善相 不負吾也！」

賜其子 rm@襄城郡公 。

爵
# p 

五月，
 rm#r02590@王世充 陷 dm#dm06542@義州 ，
復寇 dm#dm07361@西濟州 。

遣右驍衞大將軍 rm#r00246@劉弘基 將兵救之。


# p 

 rm#r01980@李軌 將 rm#r05177@安脩仁 兄 rm#r05178@興貴 ，
仕 dm#dm08170@長安 ，
表請説 rm#r01980@軌 ，
諭以禍福。

上曰：
「 rm#r01980@軌 阻兵恃險，
連結吐谷渾、突厥，
吾興兵撃之，
尚恐不克，
豈口舌所能下乎！」

 rm#r05178@興貴 曰：
「臣家在 dm#dm04947@涼州 ，
奕世豪望，
爲民夷所附；
弟 rm#r05177@脩仁 爲 rm#r01980@軌 所信任，
子弟在機近者以十數。

臣往説之，
 rm#r01980@軌 聽臣固善，
若其不聽，
圖之肘腋，
易矣！」

上乃遣之。
# p 

 rm#r05178@興貴 至 dm#dm04241@武威 ，
 rm#r01980@軌 以爲左右衞大將軍。

 rm#r05178@興貴 乘間説 rm#r01980@軌 曰：
「 dm#*dm04947@涼 地不過千里，
土薄民貧。

今 dyn#ch100@唐 起 dm#dm01774@太原 ，
取 dm#dm00740@函秦 ，
宰制中原，
戰必勝，
攻必取，
此殆天啓，
非人力也。

不若舉 dm#dm04695@河西 歸之，
則 rm#r05735@竇融 之功復見於今日矣！」

 rm#r01980@軌 曰：
「吾據山河之固，
彼雖強大，
若我何！

汝自 dyn#ch100@唐 來，
爲 dyn#ch100@唐 遊説耳。」

 rm#r05178@興貴 謝曰：
「臣聞富貴不歸故郷，
如衣繡夜行，
臣闔門受陛下榮祿，
安肯附 dyn#ch100@唐 ！

但欲效其愚慮，
可否在陛下耳。」

於是退與 rm#r05177@脩仁 陰結諸胡起兵撃 rm#r01980@軌 ，
 rm#r01980@軌 出戰而敗，
嬰城自守。

 rm#r05178@興貴 徇曰：
「 dyn#ch100@大唐 遣我來誅 rm#r01980@李軌 ，
敢助之者夷三族！」

城中人爭出就 rm#r05178@興貴 。

 rm#r01980@軌 計窮，
與妻子登 dm#dm05703@玉女臺 ，
置酒爲別。

庚辰，
 rm#r05178@興貴 執之以聞，
 dm#dm04695@河西 悉平。
# p 

 rm#r05952@鄧曉 在 dm#dm08170@長安 ，
舞蹈稱慶，
上曰：
「汝爲人使臣，
聞國亡，
不慼而喜，
以求媚於朕，
不忠於 rm#r01980@李軌 ，
肯爲朕用乎！」

遂廢之終身。


# p 

 rm#r01980@軌 至 dm#dm08170@長安 ，
幷其子弟皆伏誅。

以 rm#r05178@安興貴 爲右武候大將軍、上柱國、 rm#r05178@涼國公 ，
賜帛萬段，
 rm#r05177@安脩仁 爲左武候大將軍、 rm#r05177@申國公 。
# p 

 dyn#ch174@隋 末，
 dm#dm08532@離石 胡 rm#r05092@劉龍兒 擁兵數萬，
自號 rm#r05092@劉王 ，
以其子 rm#r00219@季眞 爲太子；
虎賁郎將 rm#r05472@梁徳 撃斬 rm#r05092@龍兒 。

至是，
 rm#r00219@季眞 與弟 rm#r05057@六兒 復舉兵爲亂，
引 rm#r00280@劉武周 之衆攻陷 dm#dm06095@石州 ，
殺刺史 rm@王儉 。

 rm#r00219@季眞 自稱 rm#r00219@突利可汗 ，
以 rm#r05057@六兒 爲 rm#r05057@拓定王 。

 rm#r05057@六兒 遣使請降，
詔以爲 dm#dm02511@嵐州 總管。

# p 

壬午，
以 rm#r01602@秦王世民 爲左武候大將軍、使持節、 dm#*dm04947@涼 ‧ dm#dm05794@甘 等九州諸軍事、 dm#dm04947@涼州 總管，
其太尉、尚書令、 dm#dm08502@雍州 牧、 dm#dm08324@陝東道 行臺竝如故。

遣黄門侍郎 rm#r02189@楊恭仁 安撫 dm#dm04695@河西 。
# p 

丙戌，
 rm#r00280@劉武周 陷 dm#dm02668@平遙 。

# p 

癸巳，
 dm#dm04043@梁州 總管、 dm#dm02404@山東道 安撫副使 rm#r06009@陳政 爲麾下所殺，
攜其首奔 rm#r02590@王世充 。

 rm#r06009@政 ，
 rm#r06829@茂 之子也。

# p 

 rm#r02590@王世充 以禮部尚書 rm#r06251@裴仁基 、左輔大將軍 rm#r06259@裴行儼 有威名，
忌之。

 rm#r06251@仁基 父子知之，
亦不自安，
乃與尚書左丞 rm#r06170@宇文儒童 、 rm#r06170@儒童 弟尚食直長 rm#r06174@温 、散騎常侍 rm#r05215@崔徳本 謀殺 rm#r02590@世充 及其黨，
復尊立 rm#rt0783@皇泰主 ；
事泄，
皆夷三族。

 rm#rz0024@齊王世惲 言於 rm#r02590@世充 曰：
「 rm#r06170@儒童 等謀反，
正爲 rm#rt0783@皇泰主 尚在故也，
不如早除之。」

 rm#r02590@世充 從之，
遣兄子 rm#xjts02168@唐王仁則 及家奴 rm#r05474@梁百年 酖 rm#rt0783@皇泰主 。

 rm#r01351@皇泰主 曰：
「更爲請太尉，
以往者之言，
未應至此。」

 rm#r05474@百年 欲爲啓陳，
 rm#rz0024@世惲 不許；
又請與皇太后辭訣，
亦不許。

乃布席焚香禮佛：
「願自今已往，
不復生帝王家！」

飮藥，
不能絶，
以帛縊殺之，
諡曰 rm#rt0783@恭皇帝 。

 rm#r02590@世充 以其兄 rm#xjts02782@楚王世偉 爲太保，
 rm#rz0024@齊王世惲 爲太傅，
領尚書令。
# p 

六月，
庚子，
 rm#r03028@竇建徳 陷 dm#dm05209@滄州 。

# p 

初，
 dm#dm03494@易州 賊帥 rm#r06179@宋金剛 ，
有衆萬餘，
與 rm#r06119@魏刀兒 連結。

 rm#r06119@刀兒 爲 rm#r03028@竇建徳 所滅，
 rm#r06179@金剛 救之，
戰敗，
帥衆四千西奔 rm#r00280@劉武周 。

 rm#r00280@武周 聞其善用兵，
得之，
甚喜，
號曰 rm#r06179@宋王 ，
委以軍事，
中分家貲以遺之。

 rm#r06179@金剛 亦深自結，
出其故妻，
納 rm#r00280@武周 之妹。

因説 rm#r00280@武周 圖 dm#dm03567@晉陽 ，
南向爭天下。

 rm#r00280@武周 以 rm#r06179@金剛 爲西南道大行臺，
使將兵三萬寇 dm#dm00059@幷州 。

丁未，
 rm#r00280@武周 進逼 dm#dm00467@介州 ，
沙門 rm@道澄 以佛幡縋之入城，
遂陷 dm#dm00467@介州 ；
詔左武衞大將軍 rm#r00642@姜寶誼 、行軍總管 rm#r01611@李仲文 撃之。

 rm#r00280@武周 將 rm#r06137@黄子英 往來 dm#dm08471@雀鼠谷 ，
數以輕兵挑戰，
兵纔接，
 rm#r06137@子英 陽不勝而走，
如是再三，
 rm#r00642@寶誼 、 rm#r01611@仲文 悉衆逐之，
伏兵發，
 dyn#ch100@唐 兵大敗，
 rm#r00642@寶誼 、 rm#r01611@仲文 皆爲所虜。

既而倶逃歸，
上復使二人將兵撃 rm#r00280@武周 。

# p 

己酉，
突厥使來告 rm#rz0041@始畢可汗 之喪，
上舉哀于 dm#dm08203@長樂門 ，
廢朝三日，
詔百官就館弔其使者。

又遣内史舍人 rm#r05960@鄭徳挺 弔 rm@處羅可汗 ，
賻帛三萬段。

# p 

上以 rm#r00280@劉武周 入寇爲憂，
右僕射 rm#r03424@裴寂 請自行。

癸亥，
以 rm#r03424@寂 爲 dm#dm03544@晉州 道行軍總管，
討 rm#r00280@武周 ，
聽以便宜從事。
# p 

秋，
七月，
初置十二軍，
分關内諸府以隸焉，
皆取天星爲名，
以車騎府統之。

毎軍將、副各一人，
取威名素重者爲之，
督以耕戰之務。

由是士馬精強，
所向無敵。
# p 

 dm#dm04892@海岱 賊帥 rm#r01305@徐圓朗 以數州之地請降，
拜 dm#dm00663@兗州 總管，
封 rm#r01305@魯國公 。
# p 

 rm#r02590@王世充 遣其將 rm#r03081@羅士信 寇 dm#dm06302@穀州 ，
 rm#r03081@士信 帥其衆千餘人來降。

先是，
 rm#r03081@士信 從 rm#r01704@李密 撃 rm#r02590@世充 ，
兵敗，
爲 rm#r02590@世充 所得，
 rm#r02590@世充 厚禮之，
與同寢食。

既而得 rm@邴元眞 等，
待之如 rm#r03081@士信 ，
 rm#r03081@士信 恥之。

 rm#r03081@士信 有駿馬，
 rm#r02590@世充 兄子 rm@趙王道詢 欲之，
不與，
 rm#r02590@世充 奪之以賜 rm@道詢 ；
 rm#r03081@士信 怒，
故來降。

上聞其來，
甚喜，
遣使迎勞，
廩食其所部，
以 rm#r03081@士信 爲 dm#dm08321@陝州道 行軍總管。

 rm#r02590@世充 左龍驤將軍 dm#dm06701@臨涇  rm#r05236@席辯 與同列 rm#r05514@楊虔安 、 rm#r05358@李君義 皆帥所部來降。
賜帛五千段
# p 

丙子，
 rm#r02590@王世充 遣其將 rm#?@郭士衡 寇 dm#dm06302@穀州 ，
刺史 rm#r00090@任瓌 大破之，
俘斬且盡。

# p 

甲申，
行軍總管 rm#r00246@劉弘基 遣其將 rm@種如願 襲 rm#r02590@王世充  dm#dm04710@河陽城 ，
毀其 dm#dm04650@河 橋而還。

# p 

乙酉，
西突厥 rm@統葉護可汗 、 rm@高昌王麹伯雅 各遣使入貢。


# p 

初，
西突厥 rm@曷娑那可汗 入朝于 dyn#ch174@隋 ，
 dyn#ch174@隋 人留之，
國人立其叔父，
號 rm@射匱可汗 。

 rm@射匱 者，
 rm@達頭可汗 之孫也，
既立，
拓地東至 dm#dm08022@金山 ，
西至海，
遂與北突厥爲敵，
建庭於 dm#dm09290@龜茲 北 dm#dm00126@三彌山 。

 rm@射匱 卒，
子 rm@統葉護 立。

 rm@統葉護 勇而有謀，
北幷鐵勒，
控弦數十萬，
據烏孫故地，
又移庭於 dm#dm06074@石國 北 dm#dm00913@千泉 ；
 dm#dm07304@西域 諸國皆臣之，
 rm@葉護 各遣吐屯監之，
督其征賦。
可汗
# p 

辛卯，
 rm#r06179@宋金剛 寇 dm#dm04872@浩州 ，
浹旬而退。

# p 

八月，
丁酉，
 rm#rt0782@酅公 薨，
諡曰 rm#rt0782@隋恭帝 ；
無後，
以族子 rm@行基 嗣。

# p 

 rm#r03028@竇建徳 將兵十餘萬趣 dm#dm04839@洺州 ，
 rm#r02450@淮安王神通 帥諸軍退保 dm#dm06029@相州 。

己亥，
 rm#r03028@建徳 兵至 dm#dm04839@洺州 城下。

# p 

丙午，
將軍 rm#r05717@秦武通 軍至 dm#dm04788@洛陽 ，
敗 rm#r02590@王世充 將 rm@葛彦璋 。


# p 

丁未，
 rm#r03028@竇建徳 陷 dm#dm04839@洺州 ，
總管 rm#r05835@袁子幹 降之。

乙卯，
引兵趣 dm#dm06029@相州 ，
 rm#r02450@淮安王神通 聞之，
帥諸軍就 rm#r01299@李世勣 於 dm#dm09166@黎陽 。
# p 

 rm#r02125@梁師都 與突厥合數千騎寇 dm#dm02812@延州 ，
行軍總管 rm#r06227@段徳操 兵少不敵，
閉壁不戰，
伺 rm#r02125@師都 稍怠，
九月，
丙寅，
遣副總管 rm#r05476@梁禮 將兵撃之。

 rm#r02125@師都 與 rm#r05476@禮 戰方酣，
 rm#r06227@徳操 以輕騎多張旗幟，
掩撃其後，
 rm#r02125@師都 軍潰，
逐北二百里，
破其 dm#dm08950@魏州 ，
虜男女二千餘口。

 rm#r06227@徳操 ，
 rm#r06674@孝先 之子也。

# p 

 rm#r03260@蕭銑 遣其將 rm#r05516@楊道生 寇 dm#dm02449@峽州 ，
刺史 rm#r03523@許紹 撃破之。

 rm#r03260@銑 又遣其將 rm#r06011@陳普環 帥舟師上 dm#dm02447@峽 ，
規取 dm#dm02566@巴 、 dm#dm07197@蜀 。

 rm#r03523@紹 遣其子 rm#r03515@智仁 及録事參軍 rm#r06209@李弘節 等追至 dm#dm07393@西陵 ，
大破之，
擒 rm#r06011@普環 。

 rm#r03260@銑 遣兵戍 dm#dm02060@安蜀城 及 dm#dm06897@荊門城 。

# p 

先是，
上遣開府 rm#r02009@李靖 詣 dm#dm01550@夔州 經略 rm#r03260@蕭銑 。

 rm#r02009@靖 至 dm#dm02449@峽州 ，
阻 rm#r03260@銑 兵，
久不得進。

上怒其遲留，
陰敕 rm#r03523@許紹 斬之；
紹惜其才，
爲之奏請，
獲免。

# p 

己巳，
 rm#r03028@竇建徳 陷 dm#dm06029@相州 ，
殺刺史 rm#r05111@呂珉 。

# p 

民部尚書 rm#r00267@魯公劉文靜 ，
自以才略功勳在 rm#r03424@裴寂 之右而位居其下，
意甚不平。

毎廷議，
 rm#r03424@寂 有所是，
 rm#r00267@文靜 必非之，
數侵侮 rm#r03424@寂 ，
由是有隙。

 rm#r00267@文靜 與弟通直散騎常侍 rm@文起 飮，
酒酣怨望，
拔刀撃柱曰：
「會當斬 rm#r03424@裴寂 首！」

家數有妖，
 rm@文起 召巫於星下被髮銜刀爲厭勝。

 rm#r00267@文靜 有妾無寵，
使其兄上變告之。

上以 rm#r00267@文靜 屬吏，
遣 rm#r03424@裴寂 、 rm#r03249@蕭瑀 問状，
 rm#r00267@文靜 曰：
「建義之初，
忝爲司馬，
計與長史位望略同。

今 rm#r03424@寂 爲僕射，
據甲第；
臣官賞不異衆人，
東西征討，
老母留 dm#dm08170@京師 ，
風雨無所庇，
實有觖望之心，
因醉怨言，
不能自保。」

上謂羣臣曰：
「觀 rm#r00267@文靜 此言，
反明白矣。」

 rm#r01876@李綱 、 rm#r03249@蕭瑀 皆明其不反，
 rm#r01602@秦王世民 爲之固請曰：
「昔在 dm#dm03567@晉陽 ，
 rm#r00267@文靜 先定非常之策，
始告 rm#r03424@寂 知，
及克 dm#dm08170@京城 ，
任遇懸隔，
令 rm#r00267@文靜 觖望則有之，
非敢謀反。

」
 rm#r03424@裴寂 言於上曰：
「 rm#r00267@文靜 才略實冠時人，
性復粗險，
今天下未定，
留之必貽後患。」

上素親 rm#r03424@寂 ，
低囘久之，
卒用 rm#r03424@寂 言。

辛未，
 rm#r00267@文靜 及 rm@文起 坐死，
籍沒其家。

# p 

 rm#r02419@沈法興 既克 dm#dm04374@毘陵 ，
謂 dm#dm04475@江 、 dm#dm04981@淮 之南指撝可定，
自稱 rm#r02419@梁王 ，
都 dm#dm04374@毘陵 ，
改元 y@延康 ，
置百官。

性殘忍，
專尚威刑，
將士小有過，
即斬之，
由是其下離怨。
# p 

時 rm#r02022@杜伏威 據 dm#dm04339@歴陽 ，
 rm#r06021@陳稜 據 dm#dm04510@江都 ，
 rm#r01680@李子通 據 dm#dm04908@海陵 ，
倶有窺 dm#dm04475@江 表之心。

 rm#r02419@法興 軍數敗；
會 rm#r01680@子通 圍 rm#r06021@稜 於 dm#dm04510@江都 ，
 rm#r06021@稜 送質求救於 rm#r02419@法興 及 rm#r02022@伏威 ，
 rm#r02419@法興 使其子 rm@綸 將兵數萬與 rm#r02022@伏威 共救之。

 rm#r02022@伏威 軍 dm#dm05055@清流 ，
 rm@綸 軍 dm#dm03241@揚子 ，
相去數十里。

 rm#r01680@子通 納言 rm#r05556@毛文深 獻策，
募 dm#dm04476@江南 人詐爲 rm@綸 兵，
夜襲 rm#r02022@伏威 營，
 rm#r02022@伏威 怒，
復遣兵襲 rm@綸 。

由是二人相疑，
莫敢先進。

 rm#r01680@子通 得盡鋭攻 dm#dm04510@江都 ，
克之，
 rm#r06021@稜 奔 rm#r02022@伏威 。

 rm#r01680@子通 入 dm#dm04510@江都 ，
因縱撃 rm@綸 ，
大破之，
 rm#r02022@伏威 亦引去。

 rm#r01680@子通 即皇帝位，
國號 dyn#?@呉 ，
改元 y@明政 。

 dm#dm00299@丹陽 賊帥 rm#r05522@樂伯通 帥衆萬餘降之，
 rm#r01680@子通 以爲左僕射。
# p 

 rm#r02022@杜伏威 請降；
丁丑，
以 rm#r02022@伏威 爲 dm#dm04984@淮南 安撫大使、 dm#dm01327@和州 總管。

# p 

 rm#r03424@裴寂 至 dm#dm00463@介休 ，
 rm#r06179@宋金剛 據城拒之。

 rm#r03424@寂 軍于 dm#dm02697@度索原 ，
營中飮澗水，
 rm#r06179@金剛 絶之，
士卒渇乏。

 rm#r03424@寂 欲移營就水，
 rm#r06179@金剛 縱兵撃之，
 rm#r03424@寂 軍遂潰，
失亡略盡；
 rm#r03424@寂 一日一夜馳至 dm#dm03544@晉州 。

先是，
 rm#r00280@劉武周 屡遣兵攻 dm#dm07346@西河 ，
 dm#dm04872@浩州 刺史 rm#r05089@劉贍 拒之，
 rm#r01611@李仲文 引兵就之，
與共守 dm#dm07346@西河 。

及 rm#r03424@裴寂 敗，
自 dm#dm03544@晉州 以北城鎭倶沒，
唯 dm#dm07346@西河 獨存。

 rm#r00642@姜寶誼 復爲 rm#r06179@金剛 所虜，
謀逃歸，
 rm#r06179@金剛 殺之。

 rm#r03424@裴寂 上表謝罪，
上慰諭之，
復使鎭撫 dm#dm04672@河東 。

# p 

 rm#r00280@劉武周 進逼 dm#dm00059@幷州 ，
 rm#r01016@齊王元吉 紿其司馬 rm#r00252@劉徳威 曰：
「卿以老弱守城，
吾以強兵出戰。」

辛巳，
 rm#r01016@元吉 夜出兵，
攜其妻妾棄州奔還 dm#dm08170@長安 。

 rm#r01016@元吉 始去，
 rm#r00280@武周 兵已至城下，
 dm#dm03567@晉陽 土豪 rm#r05817@薛深 以城納 rm#r00280@武周 。

上聞之，
大怒，
謂禮部尚書 rm#r01876@李綱 曰：
「 rm#r01016@元吉 幼弱，
未習時事，
故遣 rm#r03046@竇誕 、 rm#r00758@宇文歆 輔之。

 dm#dm03567@晉陽 強兵數萬，
食支十年，
興王之基，
一旦棄之。

聞 rm#r00758@宇文歆 首畫此策，
我當斬之！」

 rm#r01876@綱 曰：
「王年少驕逸，
 rm#r03046@竇誕 曾無規諫，
又掩覆之，
使士民憤怨，
今日之敗，
 rm#r03046@誕 之罪也。

 rm#r00758@歆 諫，
王不悛，
尋皆聞奏，
乃忠臣也，
豈可殺哉！」

明日，
上召 rm#r01876@綱 入，
升御座曰：
「我得公，
遂無濫刑。

 rm#r01016@元吉 自爲不善，
非二人所能禁也。」

幷 rm#r03046@誕 赦之。

衞尉少卿 rm#r00264@劉政會 在 dm#dm01774@太原 ，
爲 rm#r00280@武周 所虜，
 rm#r00264@政會 密表論武周形勢。遣人奉
# p 

 rm#r00280@武周 據 dm#dm01774@太原 ，
遣 rm#r06179@宋金剛 攻 dm#dm03544@晉州 ，
拔之，
虜右驍衞大將軍 rm#r00246@劉弘基 ，
 rm#r00246@弘基 逃歸。

 rm#r06179@金剛 進逼 dm#dm06431@絳州 ，
陷 dm#dm09269@龍門 。

# p 

西突厥 rm@曷娑那可汗 與北突厥有怨；
 rm@曷娑那 在 dm#dm08170@長安 ，
北突厥遣使請殺之，
上不許。

羣臣皆曰：
「保一人而失一國，
後必爲患！」

 rm#r01602@秦王世民 曰：
「人窮來歸，
我殺之不義。」

上遲迴久之，
不得已，
丙戌，
引 rm@曷娑那 於内殿宴飮，
既而送中書省，
縱北突厥使者使殺之。
# p 

禮部尚書 rm#r01876@李綱 領太子詹事，
 rm#r01078@太子建成 始甚禮之。

久之，
太子漸昵近小人，
疾 rm#r01602@秦王世民 功高，
頗相猜忌；
 rm#r01876@綱 屡諫不聽，
乃乞骸骨。

上罵之曰：
「卿爲 rm#r05027@何潘仁 長史，
乃恥爲朕尚書邪！

且方使卿輔導 rm#r01078@建成 ，
而固求去，
何也？」
 rm#r01876@綱 頓首曰：
「 rm#r05027@潘仁 ，
賊也，
毎欲妄殺人，
臣諫之即止，
爲其長史，
可以無愧。

陛下創業明主，
臣不才，
所言如水投石，
言於太子亦然，
臣何敢久汚天臺、辱東朝乎！」

上曰：
「知公直士，
勉留輔吾兒。」

戊子，
以 rm#r01876@綱 爲太子少保，
尚書、詹事如故。

 rm#r01876@綱 復上書諫太子飮酒無節，
及信讒慝，
疏骨肉；
太子不懌，
而所爲如故。

 rm#r01876@綱 鬱鬱不得志，
 y@是歳 ，
固稱老病辭職，
詔解尚書，
仍爲少保。
# p 

 rm#r02450@淮安王神通 使慰撫使 rm#r01199@張道源 鎭 dm#dm07623@趙州 。

庚寅，
 rm#r03028@竇建徳 陷 dm#dm07623@趙州 ，
執總管 rm#r05273@張志昂 及 rm#r01199@道源 。

 rm#r03028@建徳 以二人及 dm#dm07817@邢州 刺史 rm#r03917@陳君賓 不早下，
欲殺之，
國子祭酒 rm#r05052@凌敬 諫曰：
「人臣各爲其主用，
彼堅守不下，
乃忠臣也。

今大王殺之，
何以勵羣下乎！」

 rm#r03028@建徳 怒曰：
「吾至城下，
彼猶不降，
力屈就擒，
何可捨也！」

 rm#r05052@敬 曰：
「今大王使大將 rm#r06098@高士興 拒 rm#r03089@羅藝 於 dm#dm03495@易水 ，
 rm#r03089@藝 纔至，
 rm#r06098@興 即降，
大王之意以爲何如？」
 rm#r03028@建徳 乃悟，
即命釋之。
# p 

乙未，
 rm#r02125@梁師都 復寇 dm#dm02812@延州 ，
 rm#r06227@段徳操 撃破之，
斬首二千餘級，
 rm#r02125@師都 以百餘騎遁去。

 rm#r06227@徳操 以功拜柱國，
賜爵 rm#r06227@平原郡公 。

 dm#dm07926@鄜州 刺史 rm#r05476@鄜城壯公梁禮 戰沒。

# p 

冬，
十月，
己亥，
就加 dm#dm04947@涼州 總管 rm#r02189@楊恭仁 納言；
賜 dm#dm02689@幽州 總管 rm#r03089@燕公羅藝 姓 rm#no@李氏 ，
封 rm#r03089@燕郡王 。

# p 

辛丑，
 rm#r03089@李藝 破 rm#r03028@竇建徳 於 dm#dm07232@衡水 。


# p 

癸卯，
以左武候大將軍 rm#r06284@龐玉 爲 dm#dm04043@梁州 總管。

時 dm#dm08483@集州 獠反，
 rm#r06284@玉 討之，
獠據險自守，
軍不得進，
糧且盡。

熟獠與反者皆鄰里親黨，
爭言賊不可撃，
請 rm#r06284@玉 還。

 rm#r06284@玉 揚言：
「秋穀將熟，
百姓毋得收刈，
一切供軍，
非平賊吾不返。」

聞者大懼曰：
「大軍不去，
吾曹皆將餒死。」

其中壯士乃入賊營，
與所親潛謀，
斬其渠帥而降，
餘黨皆散，
 rm#r06284@玉 追討，
悉平之。
# p 

 rm#r00280@劉武周 將 rm#r06179@宋金剛 進攻 dm#dm05411@澮州 ，
陷之，
軍勢甚鋭。

 rm#r03424@裴寂 性怯，
無將帥之略，
唯發使駱驛，
趣 dm#dm07179@虞 、 dm#dm04746@泰 二州居民入城堡，
焚其積聚。

民驚擾愁怨，
皆思爲盜，
 dm#dm01545@夏縣 民 rm#r06161@呂崇茂 聚衆自稱 rm#r06161@魏王 ，
以應 rm#r00280@武周 ，
 rm#r03424@寂 討之，
爲所敗。

詔 rm#r02380@永安王孝基 、 rm#r02574@獨孤懷恩 、 dm#dm08320@陝州 總管 rm#r05015@于筠 、内史侍郎 rm#ry9001@唐儉 等將兵討之。

工部尚書
# p 

時 rm#r06235@王行本 猶據 dm#dm07021@蒲反 ，
未下，
亦與 rm#r00280@武周 相應，
 dm#dm08281@關中 震駭。

上出手敕曰：
「賊勢如此，
難與爭鋒，
宜棄 dm#dm01648@大河 以東，
謹守 dm#dm08288@關西 而已。」

 rm#r01602@秦王世民 上表曰：
「 dm#dm01774@太原 ，
王業所基，
國之根本；
 dm#dm04672@河東 富實，
 dm#dm00449@京邑 所資，
若舉而棄之，
臣竊憤恨。

願假臣精兵三萬，
必冀平殄 rm#r00280@武周 ，
克復 dm#dm04559@汾 、 dm#dm03533@晉 。」

上於是悉發 dm#dm08281@關中 兵以益 rm#r01602@世民 所統，
使撃 rm#r00280@武周 。

乙卯，
幸 dm#dm06943@華陰 ，
至 dm#dm08188@長春宮 以送之。

# p 

 rm#r03028@竇建徳 引兵趣 dm#dm00029@衞州 。

 rm#r03028@建徳 毎行軍，
常爲三道，
輜重、細弱居中央，
歩騎夾左右，
相去三里許。

 rm#r03028@建徳 以千騎前行，
過 dm#dm09166@黎陽 三十里，
 rm#r01299@李世勣 遣騎將 rm#r05006@丘孝剛 將三百騎偵之。

 rm#r05006@孝剛 驍勇，
善馬槊，
與 rm#r03028@建徳 遇，
遂撃之，
 rm#r03028@建徳 敗走；
右方兵救之，
撃斬 rm#r05006@孝剛 。

 rm#r03028@建徳 怒，
還攻 dm#dm09166@黎陽 ，
克之，
虜 rm#r02450@淮安王神通 ，
 rm#r01299@李世勣 父 rm@蓋 、 rm#r04294@魏徵 及帝妹 rm#r00399@同安公主 。

唯 rm#r01299@李世勣 以數百騎走渡 dm#dm04650@河 ，
數日，
以其父故，
還詣 rm#r03028@建徳 降；
 dm#dm00029@衞州 聞 dm#dm09166@黎陽 陷，
亦降。

 rm#r03028@建徳 以 rm#r01299@李世勣 爲左驍衞將軍，
使守 dm#dm09166@黎陽 ，
常以其父 rm@蓋 自隨爲質。

以 rm#r04294@魏徵 爲起居舍人。

 dm#dm05229@滑州 刺史 rm#r06236@王軌 奴殺 rm#r06236@軌 ，
攜其首詣 rm#r03028@建徳 降。

 rm#r03028@建徳 曰：
「奴殺主大逆，
吾何爲受之！」

立命斬奴，
返其首於 dm#dm05229@滑州 。

吏民感悦，
即日請降。

於是其旁州縣及 rm#r01305@徐圓朗 等皆望風歸附。

己未，
 rm#r03028@建徳 還 dm#dm04839@洺州 ，
築 dm#dm06982@萬春宮 ，
徙都之。

置 rm#r02450@淮安王神通 於 dm#dm00208@下博 ，
待以客禮。
# p 

行軍總管 rm#r03081@羅士信 帥勇士夜入 dm#dm04788@洛陽 外郭，
縱火焚 dm#dm05030@清化里 而還。

壬戌，
 rm#r03081@士信 拔 dm#dm08651@青城堡 。

# p 

 rm#r02590@王世充 自將兵徇地至 dm#dm05233@滑臺 ，
臨 dm#dm09166@黎陽 ；
 dm#dm02347@尉氏 城主 rm#r05336@時徳叡 、 dm#dm04541@汴州 刺史 rm#r05656@王要漢 、 dm#dm00454@亳州 刺史 rm#r05004@丁叔則 遣使降之。

以 rm#r05336@徳叡 爲 dm#dm02345@尉州 刺史。

 rm#r05656@要漢 ，
 rm#r06230@伯當 之兄也。
# p 

 rm#r00593@夏侯端 至 dm#dm09166@黎陽 ，
 rm#r01299@李世勣 發兵送之，
自 dm#dm05417@澶淵 濟 dm#dm04650@河 ，
傳檄州縣，
東至于海，
南至于 dm#dm04981@淮 ，
二十餘州，
皆遣使來降。

行至 dm#dm07451@譙州 ，
會 dm#dm04537@汴 、 dm#dm00454@亳 降於 rm#r02590@王世充 ，
還路遂絶。

 rm#r00593@端 素得衆心，
所從二千人，
雖糧盡不忍委去，
 rm#r00593@端 坐澤中，
殺馬以饗士，
因歔欷謂曰：
「卿等郷里皆已從賊，
特以共事之情，
未能見委。

我奉王命，
不可從卿；
卿有妻子，
無宜效我。

可斬吾首歸賊，
必獲富貴。」

衆皆流涕曰：
「公於 dyn#ch100@唐室 非有親屬，
直以忠義，
志不圖存。

某等雖賤，
心亦人也，
寧肯害公以求利乎！」

 rm#r00593@端 曰：
「卿不忍見殺，
吾當自刎。」

衆抱持之，
乃復同進，
潛行五日，
餒死及爲賊所撃奔潰相失者太半，
唯餘五十二人同走，
采䝁豆生食之。

 rm#r00593@端 持節未嘗離身，
屡遣從者散，
自求生，
衆又不可。

時 dm#dm04660@河南 之地皆入 rm#r02590@世充 ，
唯 dm#dm00063@𣏌州 刺史 rm#r01641@李公逸 爲 dyn#ch100@唐 堅守，
遣兵迎 rm#r00593@端 ，
館給之。

 rm#r02590@世充 遣使召 rm#r00593@端 ，
解衣遺之，
仍送除書，
以 rm#r00593@端 爲 rm#r00593@淮南郡公 、尚書少吏部；
 rm#r00593@端 對使者焚書毀衣，
曰：
「 rm#r00593@夏侯端 天子大使，
豈受 rm#r02590@王世充 官乎！

汝欲吾往，
唯可取吾首耳。」

因解節旄懷之，
置刃於竿，
自山中西走，
無復蹊徑，
冒踐荊棘，
晝夜兼行，
得達 dm#dm02199@宜陽 ，
從者墜崖溺水，
爲虎狼所食，
又喪其半；
其存者鬢髮禿落，
無復人状。

 rm#r00593@端 詣闕見上，
但謝無功，
初不自言艱苦，
上復以爲祕書監。
# p 

 rm#?@郎楚之 至 dm#dm02403@山東 ，
亦爲 rm#r03028@竇建徳 所獲，
 rm#?@楚之 不屈，
竟得還。

# p 

 rm#r02590@王世充 遣其從弟 rm#r06695@世辯 以 dm#dm02948@徐 、 dm#dm00454@亳 之兵攻 dm#dm08496@雍丘 ，
 rm#r01641@李公逸 遣使求救，
上以隔賊境，
不能救。

 rm#r01641@公逸 乃留其屬 rm#r05345@李善行 守 dm#dm08496@雍丘 ，
身帥輕騎入朝，
至 dm#dm07267@襄城 ，
爲 rm#r02590@世充  dm#dm00514@伊州 刺史 rm#r05283@張殷 所獲，
 rm#r02590@世充 謂曰：
「卿越 dyn#?@鄭 臣 dyn#ch100@唐 ，
其説安在？」
 rm#r01641@公逸 曰：
「我於天下，
唯知有 dyn#ch100@唐 ，
不知有 dyn#?@鄭 。」

 rm#r02590@世充 怒，
斬之。

 rm#r05345@善行 亦沒。

上以 rm#r01641@公逸 子爲 rm#r01641@襄邑公 。
# p 

甲子，
上祠 dm#dm06933@華山 。

# p 

十一月，
己卯，
 rm#r00280@劉武周 寇 dm#dm04872@浩州 。

# p 

 rm#r01602@秦王世民 引兵自 dm#dm09269@龍門 乘冰堅渡 dm#dm04650@河 ，
屯 dm#dm03946@柏壁 ，
與 rm#r06179@宋金剛 相持。

時 dm#dm04650@河 東州縣，
俘掠之餘，
未有倉廩，
人情恇擾，
聚入城堡，
徵斂無所得，
軍中乏食。

 rm#r01602@世民 發教諭民，
民聞 rm#r01602@世民 爲帥而來，
莫不歸附，
自近及遠，
至者日多，
然後漸收其糧食，
軍食以充。

乃休兵秣馬，
唯令偏裨乘間抄掠，
大軍堅壁不戰，
由是賊勢日衰。


# p 

 rm#r01602@世民 嘗自帥輕騎覘敵，
騎皆四散，
 rm#r01602@世民 獨與一甲士登丘而寢。

俄而賊兵四合，
初不之覺，
會有蛇逐鼠，
觸甲士之面，
甲士驚寤，
遂白 rm#r01602@世民 倶上馬，
馳百餘歩，
爲賊所及，
 rm#r01602@世民 以大羽箭射殪其驍將，
賊騎乃退。
# p 

 rm#r01299@李世勣 欲歸 dyn#ch100@唐 ，
恐禍及其父，
謀於 rm#r03716@郭孝恪 。

 rm#r03716@孝恪 曰：
「吾新事 rm#no@竇氏 ，
動則見疑，
宜先立效以取信，
然後可圖也。」

 rm#r01299@世勣 從之。

襲 rm#r02590@王世充  dm#dm05675@獲嘉 ，
破之，
多所俘獲，
以獻 rm#r03028@建徳 ，
 rm#r03028@建徳 由是親之。
# p 

初，
 dm#dm05318@漳南 人 rm#r00337@劉黒闥 ，
少驍勇狡獪，
與 rm#r03028@竇建徳 善，
後爲羣盜，
轉事 rm#r05926@郝孝徳 、 rm#r01704@李密 、 rm#r02590@王世充 。

 rm#r02590@世充 以爲騎將，
毎見 rm#r02590@世充 所爲，
竊笑之。

 rm#r02590@世充 使 rm#r00337@黒闥 守 dm#dm03400@新郷 ，
 rm#r01299@李世勣 撃虜之，
獻於 rm#r03028@建徳 。

 rm#r03028@建徳 署爲將軍，
賜爵 rm#r00337@漢東公 ，
常使將奇兵東西掩襲，
或潛入敵境覘視虚實，
 rm#r00337@黒闥 往往乘間奮撃，
克獲而還。

# p 

十二月，
庚申，
上獵于 dm#dm06933@華山 。


# p 

 rm#r05015@于筠 説 rm#r02380@永安王孝基 急攻 rm#r06161@呂崇茂 ，
 rm#r02574@獨孤懷恩 請先成攻具，
然後進，
 rm#r02380@孝基 從之。

 rm#r06161@崇茂 求救於 rm#r06179@宋金剛 ，
 rm#r06179@金剛 遣其將 dm#dm00096@善陽  rm#r00862@尉遲敬徳 、 rm@尋相 將兵奄至 dm#dm01545@夏縣 。

 rm#r02380@孝基 表裏受敵，
軍遂大敗，
 rm#r02380@孝基 、 rm#r02574@懷恩 、 rm#r05015@筠 、 rm#ry9001@唐儉 及行軍總管 rm#r00187@劉世讓 皆爲所虜。

 rm#r00862@敬徳 名 rm#r00862@恭 ，
以字行。
# p 

上徵 rm#r03424@裴寂 入朝，
責其敗軍，
下吏，
既而釋之，
寵待彌厚。
# p 

 rm#r00862@尉遲敬徳 、 rm@尋相 將還 dm#dm05411@澮州 ，
 rm#r01602@秦王世民 遣兵部尚書 rm#r02357@殷開山 、總管 rm#r02977@秦叔寶 等邀之於 dm#dm06523@美良川 ，
大破之，
斬首二千餘級。

頃之，
 rm#r00862@敬徳 、 rm@尋相 潛引精騎援 rm#r06235@王行本 於 dm#dm07021@蒲反 ，
 rm#r01602@世民 自將歩騎三千從間道夜趨 dm#dm02072@安邑 ，
邀撃，
大破之。

 rm#r00862@敬徳 、 rm@相 僅以身免，
悉俘其衆，
復歸 dm#dm03946@柏壁 。
# p 

諸將咸請與 rm#r06179@宋金剛 戰，
 rm#r01602@世民 曰：
「 rm#r06179@金剛 懸軍深入，
精兵猛將，
咸聚於是，
 rm#r00280@武周 據 dm#dm01774@太原 ，
倚 rm#r06179@金剛 爲扞蔽。

 dm#*dm07639@軍 無蓄積，
以虜掠爲資，
利在速戰。

我閉營養鋭以挫其鋒，
分兵 dm#dm04559@汾 、 dm#dm08451@隰 ，
衝其心腹，
彼糧盡計窮，
自當遁走。

當待此機，
未宜速戰。」
金剛
# p 

 rm#r02380@永安壯王孝基 謀逃歸，
 rm#r00280@劉武周 殺之。
# p 

 rm#r01299@李世勣 復遣人説 rm#r03028@竇建徳 曰：
「 dm#dm03636@曹 、 dm#dm03154@戴 二州，
戸口完實，
 rm#rz0003@孟海公 竊有其地，
與 dyn#?@鄭 人外合内離；
若以大軍臨之，
指期可取。

既得 rm#rz0003@海公 ，
以臨 dm#dm02948@徐 、 dm#dm00663@兗 ，
 dm#dm04660@河南 可不戰而定也。」

 rm#r03028@建徳 以爲然，
欲自將徇 dm#dm04660@河南 ，
先遣其行臺 rm#r06199@曹旦 等將兵五萬濟 dm#dm04650@河 ，
 rm#r01299@世勣 引兵三千會之。
*** 三年
# year 0620
# p 

春，
正月，
將軍 rm#r05717@秦武通 攻 rm#r06235@王行本 於 dm#dm07021@蒲反 。

 rm#r06235@行本 出戰而敗，
糧盡援絶，
欲突圍走，
無隨之者，
戊寅，
開門出降。

辛巳，
上幸 dm#dm07029@蒲州 ，
斬 rm#r06235@行本 。

 rm#r01602@秦王世民 輕騎謁上於 dm#dm07029@蒲州 。

 rm#r06179@宋金剛 圍 dm#dm06431@絳州 。

癸巳，
上還 dm#dm08170@長安 。
# p 

 rm#r01299@李世勣 謀俟 rm#r03028@竇建徳 至 dm#dm04660@河南 ，
掩襲其營，
殺之，
冀得其父幷 rm#r03028@建徳 土地以歸 dyn#ch100@唐 。

會 rm#r03028@建徳 妻産，
久之不至。


# p 

 rm#r06199@曹旦 ，
 rm#r03028@建徳 之妻兄也，
在 dm#dm04660@河南 ，
多所侵擾，
諸賊羈屬者皆怨之。

賊帥 dm#dm08957@魏郡  rm#r05399@李文相 ，
號 rm#r05359@李商胡 ，
聚五千餘人，
據 dm#dm01950@孟津  dm#dm00278@中潬 ；
母 rm#?@霍氏 ，
亦善騎射，
自稱 rm#?@霍總管 。

 rm#r01299@世勣 結 rm#r05359@商胡 爲昆弟，
入拜 rm#r05359@商胡 之母。

母泣謂 rm#r01299@世勣 曰：
「 rm#?@竇氏 無道，
如何事之！」

 rm#r01299@世勣 曰：
「母無憂，
不過一月，
當殺之，
相與歸 dyn#ch100@唐 耳！」

 rm#r01299@世勣 辭去，
母謂 rm#r05359@商胡 曰：
「 rm#r01299@東海公 許我共圖此賊，
事久變生，
何必待其來，
不如速決。」

是夜，
 rm#r05359@商胡 召 rm#r06199@曹旦 偏裨二十三人，
飮之酒，
盡殺之。

 rm#r06199@旦 別將 rm#r06282@高雅賢 、 rm@阮君明 尚在 dm#dm04650@河 北未濟，
 rm#r05359@商胡 以巨舟四艘濟 dm#dm04650@河 北之兵三百人，
至中流，
悉殺之。

有獸醫游水得免，
至南岸，
告 rm#r06199@曹旦 ，
 rm#r06199@旦 嚴警爲備。

 rm#r05359@商胡 既舉事，
始遣人告 rm#r01299@李世勣 。

 rm#r01299@世勣 與 rm#r06199@曹旦 連營，
 rm#r03716@郭孝恪 勸 rm#r01299@世勣 襲 rm#r06199@旦 ，
 rm#r01299@世勣 未決，
聞 rm#r06199@旦 已有備，
遂與 rm#r03716@孝恪 帥數十騎來奔。

 rm#r05359@商胡 復引精兵二千北襲 rm@阮君明 ，
破之。

 rm#r06282@高雅賢 收衆去，
 rm#r05359@商胡 追之，
不及而還。

# p 

 rm#r03028@建徳 羣臣請誅 rm#r05430@李蓋 ，
 rm#r03028@建徳 曰：
「 rm#r01299@世勣 ，
 dyn#ch100@唐 臣，
爲我所虜，
不忘本朝，
乃忠臣也，
其父何罪！」

遂赦之。
# p 

甲午，
 rm#r01299@世勣 、 rm#r03716@孝恪 至 dm#dm08170@長安 。

 rm#r06199@曹旦 遂取 dm#dm05438@濟州 ，
復還 dm#dm04839@洺州 。


# p 

二月，
庚子，
上幸華陰。

# p 

 rm#r00280@劉武周 遣兵寇 dm#dm05357@潞州 ，
陷 dm#dm08168@長子 、 dm#dm01513@壺關 。

 dm#dm05357@潞州 刺史 rm#r05937@郭子武 不能禦，
上以將軍 dm#dm04672@河東  rm#r02696@王行敏 助之。

 rm#r02696@行敏 與 rm#r05937@子武 不叶，
或言 rm#r05937@子武 將叛，
 rm#r02696@行敏 斬 rm#r05937@子武 以徇。

乙巳，
 rm#r00280@武周 復遣兵寇 dm#dm05357@潞州 ，
 rm#r02696@行敏 撃破之。
# p 

壬子，
開州蠻 rm@冉肇則 陷 dm#dm07693@通州 。

# p 

甲寅，
遣將軍 rm#r05466@桑顯和 等攻 rm#r06161@呂崇茂 於 dm#dm01545@夏縣 。


# p 

初，
工部尚書 rm#r02574@獨孤懷恩 攻 dm#dm07021@蒲反 ，
久不下，
失亡多，
上數以敕書誚讓之，
 rm#r02574@懷恩 由是怨望。

上嘗戲謂 rm#r02574@懷恩 曰：
「姑之子皆已爲天子，
次應至舅之子乎？」
 rm#r02574@懷恩 亦頗以此自負，
或時扼腕曰：
「我家豈女獨貴乎？」
遂與麾下 rm#r05039@元君寶 謀反。

會 rm#r02574@懷恩 、 rm#r05039@君寶 與 rm#ry9001@唐儉 皆沒於 rm#r00862@尉遲敬徳 ，
 rm#r05039@君寶 謂 rm#ry9001@儉 曰：
「 rm#r02574@獨孤尚書 近謀大事，
若能早決，
豈有此辱哉！」

及 rm#r01602@秦王世民 敗 rm#r00862@敬徳 於 dm#dm06523@美良川 ，
 rm#r02574@懷恩 逃歸，
上復使之將兵攻 dm#dm07021@蒲反 。

 rm#r05039@君寶 又謂 rm#ry9001@儉 曰：
「 rm#r02574@獨孤尚書 遂拔難得還，
復在 dm#dm07021@蒲反 ，
可謂王者不死！」

 rm#ry9001@儉 恐 rm#r02574@懷恩 遂成其謀，
乃説 rm#r00862@尉遲敬徳 ，
請使 rm#r00187@劉世讓 還與 dyn#ch100@唐 連和，
 rm#r00862@敬徳 從之，
遂以 rm#r02574@懷恩 反状聞。

時 rm#r06235@王行本 已降，
 rm#r02574@懷恩 入據其城，
上方濟 dm#dm04650@河 幸 rm#r02574@懷恩 營，
已登舟矣，
 rm#r00187@世讓 適至。

上大驚曰：
「吾得免，
豈非天也！」

乃使召 rm#r02574@懷恩 ，
 rm#r02574@懷恩 未知事露，
輕舟來至，
即執以屬吏，
分捕黨與。

甲寅，
誅 rm#r02574@懷恩 及其黨。
# p 

 rm#r03028@竇建徳 攻 rm#r05359@李商胡 ，
殺之。

 rm#r03028@建徳  dm#dm04839@洺州 勸課農桑，
境内無盜，
商旅野宿。至
# p 

突厥 rm@處羅可汗 迎 rm#r06218@楊政道 ，
立爲 rm#r06218@隋王 。

 dm#dm00255@中國 士民在北者，
 rm@處羅 悉以配之，
有衆萬人。

置百官，
皆依 dyn#ch174@隋 制，
居于 dm#dm02141@定襄 。

# p 

三月，
乙丑，
 rm#r00280@劉武周 遣其將 rm#r05295@張萬歳 寇 dm#dm04872@浩州 ，
 rm#r01611@李仲文 撃走之，
俘斬數千人。
# p 

改納言爲侍中，
内史令爲中書令，
給事郎爲給事中。


# p 

甲戌，
以内史侍郎 rm#r00851@封徳彞 爲中書令。
# p 

 rm#r02590@王世充 將帥、州縣來降者，
時月相繼。

 rm#r02590@世充 乃峻其法，
一人亡叛，
舉家無少長就戮，
父子、兄弟、夫婦許相告而免之。

又使五家爲保，
有舉家亡者，
四鄰不覺，
皆坐誅。

殺人益多而亡者益甚，
至於樵采之人，
出入皆有限數；
公私愁窘，
人不聊生。

又以宮城爲大獄，
意所忌者，
幷其家屬收繋宮中；
諸將出討，
亦質其家屬於宮中，
禁止者常不減萬口，
餒死者日有數十。

 rm#r02590@世充 又以臺省官爲 dm#dm01176@司 、 dm#dm07947@鄭 、 dm#dm06371@管 、 dm#dm01114@原 、 dm#dm00514@伊 、 dm#dm04359@殷 、 dm#dm04038@梁 、 dm#dm05133@湊州 、 dm#dm02513@嵩 、 dm#dm07463@谷 、 dm#dm03102@懷 、 dm#dm02976@徳 等十二州營田使，
丞、郎得爲此行者，
喜若登仙。

# p 

甲申，
行軍副總管 rm#r05290@張綸 敗 rm#r00280@劉武周 於 dm#dm04872@浩州 ，
俘斬千餘人。
# p 

 rm#r05290@西河公張綸 、 rm#r01611@眞郷公李仲文 引兵臨 dm#dm06095@石州 ，
 rm#r00219@劉季眞 懼而詐降。

乙酉，
以 rm#r00219@季眞 爲 dm#dm06095@石州 總管，
賜姓 rm#no@李氏 ，
封 rm#r00219@彭山郡王 。
# p 

蠻酋 rm@冉肇則 寇 dm#dm00576@信州 ，
 rm#r02432@趙郡公孝恭 與戰，
不利。

 rm#r02009@李靖 將兵八百，
襲撃，
斬之，
俘五千餘人；
己丑，
復 dm#dm08247@開 、 dm#dm07693@通 二州。

 rm#r02432@孝恭 又撃 rm#r03260@蕭銑  rm#r06755@東平王闍提 ，
斬之。


# p 

夏，
四月，
丙申，
上祠 dm#dm06933@華山 ；
壬寅，
還 dm#dm08170@長安 。


# p 

置 dm#dm05983@益州道 行臺，
以 dm#dm05982@益 、 dm#dm00759@利 、 dm#dm03655@會 、 dm#dm07920@鄜 ，
 dm#dm04919@涇 、 dm#dm07730@遂 六總管隸焉。

# p 

 rm#r00280@劉武周 數攻 dm#dm04872@浩州 ，
爲 rm#r01611@李仲文 所敗。

 rm#r06179@宋金剛 軍中食盡；
丁未，
 rm#r06179@金剛 北走，
 rm#r01602@秦王世民 追之。
# p 

 rm#r03081@羅士信 圍 dm#dm03074@慈澗 ，
 rm#r02590@王世充 使 rm@太子玄應 救之，
 rm#r03081@士信 刺 rm@玄應 墜馬，
人救之，
得免。救拒
# p 

壬子，
以 dm#dm08765@顯州道 行臺 rm#r05490@楊士林 爲行臺尚書令。


# p 

甲寅，
加 rm#r01602@秦王世民  dm#dm05983@益州道 行臺尚書令。
# p 

 rm#r01602@秦王世民 追及 rm@尋相 於 dm#dm01297@呂州 ，
大破之，
乘勝逐北，
一晝夜行二百餘里，
戰數十合。

至 dm#dm08885@高壁嶺 ，
總管 rm#r00246@劉弘基 執轡諫曰：
「大王破賊，
逐北至此，
功亦足矣，
深入不已，
不愛身乎！

且士卒飢疲，
宜留壁於此，
俟兵糧畢集，
然後復進，
未晩也。」

 rm#r01602@世民 曰：
「 rm#r06179@金剛 計窮而走，
衆心離沮；
功難成而易敗，
機難得而易失，
必乘此勢取之。

若更淹留，
使之計立備成，
不可復攻矣。

吾竭忠徇國，
豈顧身乎！」

遂策馬而進，
將士不敢復言飢。

追及 rm#r06179@金剛 於 dm#dm08471@雀鼠谷 ，
一日八戰，
皆破之，
俘斬數萬人。

夜，
宿於 dm#dm08471@雀鼠谷 西原，
 rm#r01602@世民 不食二日，
不解甲三日矣，
軍中止有一羊，
 rm#r01602@世民 與將士分而食之。

丙辰，
 dm#dm08320@陝州 總管 rm#r05015@于筠 自 rm#r06179@金剛 所逃來。

 rm#r01602@世民 引兵趣 dm#dm00463@介休 ，
 rm#r06179@金剛 尚有衆二萬，
出西門，
背城布陳，
南北七里。

 rm#r01602@世民 遣總管 rm#r01299@李世勣 與戰，
小卻，
爲賊所乘，
 rm#r01602@世民 帥精騎撃之，
出其陳後，
 rm#r06179@金剛 大敗，
斬首三千級。

 rm#r06179@金剛 輕騎走，
 rm#r01602@世民 追之數十里，
至 dm#dm02914@張難堡 。

 dm#dm04872@浩州 行軍總管 rm#r05524@樊伯通 、 rm#r05272@張徳政 據堡自守，
 rm#r01602@世民 免冑示之，
堡中喜譟且泣，
左右告以王不食，
獻濁酒、脱粟飯。

戊午
# p 

 rm#r00862@尉遲敬徳 收餘衆守 dm#dm00463@介休 ，
 rm#r01602@世民 遣 rm#r02398@任城王道宗 、 rm#r00750@宇文士及 往諭之，
 rm#r00862@敬徳 與 rm@尋相 舉 dm#dm00463@介休 及 dm#dm04395@永安 降。

 rm#r01602@世民 得 rm#r00862@敬徳 ，
甚喜，
以爲右一府統軍，
使將其舊衆八千，
與諸營相參。

 rm#r00876@屈突通 慮其變，
驟以爲言，
 rm#r01602@世民 不聽。
# p 

 rm#r00280@劉武周 聞 rm#r06179@金剛 敗，
大懼，
棄 dm#dm00059@幷州 走突厥。

 rm#r06179@金剛 收其餘衆，
欲復戰，
衆莫肯從，
亦與百餘騎走突厥。

# p 

 rm#r01602@世民 至 dm#dm03567@晉陽 ，
 rm#r00280@武周 所署僕射 rm#r05481@楊伏念 以城降。

 rm#ry9001@唐儉 封府庫以待 rm#r01602@世民 ，
 rm#r00280@武周 所得州縣皆入于 dyn#ch100@唐 。
# p 

未幾，
 rm#r06179@金剛 謀走 dm#dm00190@上谷 ，
突厥追獲，
腰斬之。

 dm#dm02511@嵐州 總管 rm#r05057@劉六兒 從 rm#r06179@宋金剛 在 dm#dm00463@介休 ，
 rm#r01602@秦王世民 擒斬之。

其兄 rm#r00219@季眞 ，
棄 dm#dm06095@石州 ，
奔 rm#r00280@劉武周 將 dm#dm08829@馬邑  rm#r06279@高滿政 ，
 rm#r06279@滿政 殺之。

# p 

 rm#r00280@武周 之南寇也，
其内史令 rm#r03146@苑君璋 諫曰：
「 dyn#ch100@唐 主舉一州之衆，
直取 dm#dm08170@長安 ，
所向無敵，
此乃天授，
非人力也。

 dm#dm03567@晉陽 以南，
道路險隘，
縣軍深入，
無繼於後，
若進戰不利，
何以自還！

不如北連突厥，
南結 dyn#ch100@唐朝 ，
南面稱孤，
足爲長策。」

 rm#r00280@武周 不聽，
留 rm#r03146@君璋 守 dm#dm03674@朔州 。

及敗，
泣謂 rm#r03146@君璋 曰：
「不用君言，
以至於此。」

久之，
 rm#r00280@武周 謀亡歸 dm#dm08829@馬邑 ，
事泄，
突厥殺之。

突厥又以 rm#r03146@君璋 爲大行臺，
統其餘衆，
仍令 rm@郁射設 督兵助鎭。
# p 

庚申，
 dm#dm03102@懷州 總管 rm#r06136@黄君漢 撃 rm#r02590@王世充 太子 rm@玄應 於 dm#dm07361@西濟州 ，
大破之；
 dm#dm05581@熊州 行軍總管 rm#r05100@史萬寶 邀之於 dm#dm00326@九曲 ，
又破之。
# p 

辛酉，
 rm#r02590@王世充 陷 dm#dm07942@鄧州 。
# p 

上聞 dm#dm00059@幷州 平，
大悦。

壬戌，
宴羣臣，
賜繒帛，
使自入御府，
盡力取之。

復 rm#ry9001@唐儉 官爵，
仍以爲 dm#dm00060@幷州道 安撫大使；
所籍 rm#r02574@獨孤懷恩 田宅資財，
悉以賜之。

# p 

 rm#r01602@世民 留 rm#r01611@李仲文 鎭 dm#dm00059@幷州 ，
 rm#r00280@劉武周 數遣兵入寇，
 rm#r01611@仲文 輒撃破之，
下城堡百餘所。

詔 rm#r01611@仲文 檢校 dm#dm00059@幷州 總管。

# p 

五月，
 rm#r03028@竇建徳 遣 rm#r06098@高士興 撃 rm#r03089@李藝 於 dm#dm02689@幽州 ，
不克，
退軍 dm#dm06380@籠火城 。

 rm#r03089@藝 襲撃，
大破之，
斬首五千級。

 rm#r03028@建徳 大將軍 rm#r05602@王伏寶 ，
勇略冠軍中，
諸將疾之，
言其謀反，
 rm#r03028@建徳 殺之，
 rm#r05602@伏寶 曰：
「大王奈何聽讒言，
自斬左右手乎！」

# p 

初，
 rm#r00862@尉遲敬徳 將兵助 rm#r06161@呂崇茂 守 dm#dm01545@夏縣 ，
上潛遣使赦 rm#r06161@崇茂 罪，
拜 dm#dm01538@夏州 刺史，
使圖 rm#r00862@敬徳 ，
事泄，
 rm#r00862@敬徳 殺之。

 rm#r00862@敬徳 去，
 rm#r06161@崇茂 餘黨復據 dm#dm01545@夏縣 拒守。

 rm#r01602@秦王世民 引軍自 dm#dm03544@晉州 還攻 dm#dm01545@夏縣 ，
壬午，
屠之。

# p 

辛卯，
 rm#r01602@秦王世民 至 dm#dm08170@長安 。
# p 

是月，
突厥遣 rm#r05993@阿史那掲多 獻馬千匹於 rm#r02590@王世充 ，
且求婚，
 rm#r02590@世充 以宗女妻之，
幷與之互市。
# p 

六月，
壬辰，
詔以 dm#dm01327@和州 總管、東南道行臺尚書令 rm#r02022@楚王杜伏威 爲使持節、總管 dm#dm04475@江 ‧ dm#dm04981@淮 以南諸軍事、 dm#dm03246@揚州 刺史、東南道行臺尚書令、 dm#dm04988@淮南道 安撫使，
進封 rm#r02022@呉王 ，
賜姓 rm#no@李氏 。

以 rm#r03657@輔公祏 爲行臺左僕射，
封 rm#r03657@舒國公 。

# p 

丙午，
立皇子 rm#r03168@元景 爲 rm#r03168@趙王 ，
 rm#r02507@元昌 爲 rm#r02507@魯王 ，
 rm#r03832@元亨 爲 rm#r03832@酆王 。
# p 

 dm#dm08764@顯州 行臺尚書令 rm#r05490@楚公楊士林 ，
雖受 dyn#ch100@唐 官爵，
而北結 rm#r02590@王世充 ，
南通 rm#r03260@蕭銑 ，
詔 rm#r01070@廬江王瑗 與安撫使 rm#r05381@李弘敏 討之。

兵未行，
長史 rm#r06238@田瓚 爲 rm#r05490@士林 所忌，
甲寅，
 rm#r06238@瓚 殺 rm#r05490@士林 ，
降於 rm#r02590@世充 ，
 rm#r02590@世充 以 rm#r06238@瓚 爲 dm#dm08764@顯州 總管。

# p 

 rm#r01602@秦王世民 之討 rm#r00280@劉武周 也，
突厥 rm@處羅可汗 遣其弟 rm@歩利設 帥二千騎助 dyn#ch100@唐 。

 rm#r00280@武周 既敗，
是月，
 rm@處羅 至 dm#dm03567@晉陽 ，
總管 rm#r01611@李仲文 不能制；
又留 rm@倫特勒 ，
使將數百人，
云助 rm#r01611@仲文 鎭守，
自 dm#dm06091@石嶺 以北，
皆留兵戍之而去。

# p 

上議撃 rm#r02590@王世充 ，
 rm#r02590@世充 聞之，
選諸州鎭驍勇皆集 dm#dm04788@洛陽 ，
置四鎭將軍，
募人分守四城。

秋，
七月，
壬戌，
詔 rm#r01602@秦王世民 督諸軍撃 rm#r02590@世充 。

 dm#dm08324@陝東道 行臺 rm#r00876@屈突通 二子在 dm#dm04788@洛陽 ，
上謂 rm#r00876@通 曰：
「今欲使卿東征，
如卿二子何？」
 rm#r00876@通 曰：
「臣昔爲俘囚，
分當就死，
陛下釋縛，
加以恩禮。

當是之時，
臣心口相誓，
期以更生餘年爲陛下盡節，
但恐不獲死所耳。

今得備先驅，
二兒何足顧乎！」

上歎曰：
「徇義之士，
一至此乎！」

# p 

癸亥，
突厥遣使潛詣 rm#r02590@王世充 ，
 dm#dm05357@潞州 總管 rm#r01959@李襲譽 邀撃，
敗之，
虜牛羊萬計。
# p 

驃騎大將軍 rm@可朱渾定遠 告「 dm#dm00059@幷州 總管 rm@李仲文 與突厥通謀，
欲俟 dm#dm04788@洛陽 兵交，
引胡騎直入 dm#dm08170@長安 。」

甲戌，
命皇太子鎭 dm#dm07021@蒲反 以備之，
又遣禮部尚書 rm#ry9001@唐儉 安撫 dm#dm00059@幷州 ，
蹔廢 dm#dm00059@幷州 總管府，
徵 rm#r01611@仲文 入朝。

# p 

壬午，
 rm#r01602@秦王世民 至 dm#dm03337@新安 ；
 rm#r02590@王世充 遣 rm#r05622@魏王弘烈 鎭 dm#dm07284@襄陽 ，
 rm#r06235@荊王行本 鎭 dm#dm07165@虎牢 ，
 rm@宋王泰 鎭 dm#dm03102@懷州 ，
 rm#rz0024@齊王世惲 檢校南城，
 rm#xjts02782@楚王世偉 守寶城，
 rm#xjts01833@太子玄應 守東城，
 rm#xjts01871@漢王玄恕 守 dm#dm01267@含嘉城 ，
 rm@魯王道徇 守 dm#dm03604@曜儀城 ，
 rm#r02590@世充 自將戰兵，
左輔大將軍 rm#r05483@楊公卿 帥左龍驤二十八府騎兵，
右游撃大將軍 rm#r05929@郭善才 帥内軍二十八府歩兵，
左游撃大將軍 rm#rz0062@跋野綱 帥外軍二十八府歩兵，
總三萬人，
以備 dyn#ch100@唐 。

 rm#r05622@弘烈 、 rm#r06235@行本 ，
 rm#xjts02782@世偉 之子；
 rm@泰 ，
 rm#r02590@世充 之兄子也。
# p 

 rm#r02125@梁師都 引突厥、稽胡兵入寇，
行軍總管 rm#r06227@段徳操 撃破之，
斬首千餘級。
# p 

 rm#r03081@羅士信 將前軍圍 dm#dm03074@慈澗 ，
 rm#r02590@世充 自將兵三萬救之。

己丑，
 rm#r01602@秦王 將輕騎前覘 rm#r02590@世充 ，
猝與之遇，
衆寡不敵，
道路險阨，
爲 rm#r02590@世充 所圍。

 rm#r01602@世民 左右馳射，
獲其左建威將軍 rm#r05580@燕琪 ，
 rm#r02590@世充 乃退。

 rm#r01602@世民 還營，
塵埃覆面，
軍不復識，
欲拒之，
 rm#r01602@世民 免冑自言，
乃得入。

旦日，
帥歩騎五萬進軍 dm#dm03074@慈澗 ；
 rm#r02590@世充 拔 dm#dm03074@慈澗 之戍，
歸于洛陽。

 rm#r01602@世民 遣行軍總管 rm#r05100@史萬寶 自 dm#dm02199@宜陽 南據 dm#dm09269@龍門 ，
將軍 rm#r00252@劉徳威 自 dm#dm01820@太行 東圍 dm#dm04653@河内 ，
 rm#r02607@上谷公王君廓 自 dm#dm04770@洛口 斷其餉道，
 dm#dm03102@懷州 總管 rm#r06136@黄君漢 自 dm#dm04705@河陰 攻 dm#dm07677@迴洛城 ；
大軍屯于 dm#dm00893@北邙 ，
連營以逼之。

 rm#r02590@世充  dm#dm04801@洧州 長史 dm#dm06479@繁水  rm#r01115@張公謹 與刺史 rm#r05221@崔樞 以州城來降。
世民皆應弦而斃
# p 

八月，
丁酉，
 dm#dm00971@南寧 西爨蠻遣使入貢。

初，
 dyn#ch174@隋 末蠻酋 rm@爨翫 反，
誅，
諸子沒爲官奴，
棄其地。

帝即位，
以 rm@翫 子 rm#xjts26974@弘達 爲 dm#dm03446@昆州 刺史，
令持其父尸歸葬；
 dm#dm05982@益州 刺史 rm#r05550@段綸 因遣使招諭其部落，
皆來降。


# p 

己亥，
 rm#r03028@竇建徳  dm#dm00708@共州 縣令 rm#r05140@唐綱 殺刺史，
以州來降。

# p 

 dm#dm07942@鄧州 土豪執 rm#r02590@王世充 所署刺史來降。

# p 

癸卯，
 rm#r02125@梁師都  dm#dm06083@石堡 留守 rm#r05293@張舉 帥千餘人來降。

# p 

甲辰，
 rm#r06136@黄君漢 遣校尉 rm#r05257@張夜叉 以舟師襲 dm#dm07677@迴洛城 ，
克之，
獲其將 rm@達奚善定 ，
斷 dm#dm04709@河陽  dm#dm01010@南橋 而還，
降其堡聚二十餘。

 rm#r02590@世充 使 rm@太子玄應 帥 rm#r05483@楊公卿 等攻 dm#dm07676@迴洛 ，
不克，
乃築月城於其西，
留兵戍之。
# p 

 rm#r02590@世充 陳於 dm#dm08651@青城宮 ，
 rm#r01602@秦王世民 亦置陳當之。

 rm#r02590@世充 隔水謂 rm#r01602@世民 曰：
「 dyn#ch174@隋室 傾覆，
 dyn#ch100@唐 帝 dm#dm08281@關中 ，
 dyn#?@鄭 帝 dm#dm04660@河南 ，
 rm#r02590@世充 未嘗西侵，
王忽舉兵東來，
何也？」
 rm#r01602@世民 使 rm#r00750@宇文士及 應之曰：
「四海皆仰皇風，
唯公獨阻聲教，
爲此而來！」

 rm#r02590@世充 曰：
「相與息兵講好，
不亦善乎！」

又應之曰：
「奉詔取 dm#dm03880@東都 ，
不令講好也。」

至暮，
各引兵還。


# p 

上遣使與 rm#r03028@竇建徳 連和，
 rm#r03028@建徳 遣 rm#r00399@同安長公主 隨使者倶還。

# p 

乙卯，
 rm#r00252@劉徳威 襲 dm#dm03102@懷州 ，
入其外郭，
下其堡聚。
# p 

九月，
庚午，
 rm#r02125@梁師都 將 rm#?@劉旻 以 dm#dm06941@華池 來降，
以爲 dm#dm03922@林州 總管。

# p 

癸酉，
 rm#r02590@王世充  dm#dm08764@顯州 總管 rm#r06238@田瓚 以所部二十五州來降；
自是 dm#dm07284@襄陽 聲問與 rm#r02590@世充 絶。

# p 

 rm#r05100@史萬寶 進軍 dm#dm05802@甘泉宮 。

丁丑，
 rm#r01602@秦王世民 遣右武衞將軍 rm#r02607@王君廓 攻 dm#dm07655@轘轅 ，
拔之。

 rm#r02590@王世充 遣其將 rm#r06127@魏隱 等撃 rm#r02607@君廓 ，
 rm#r02607@君廓 僞遁，
設伏，
大破之，
遂東徇地，
至 dm#dm06370@管城 而還。

先是，
 rm#r02590@王世充 將 rm#?@郭士衡 、 rm#r05862@許羅漢 掠 dyn#ch100@唐 境，
 rm#r02607@君廓 以策撃卻之，
詔勞之曰：
「卿以十三人破賊一萬，
自古以少制衆，
未之有也。」


# p 

 rm#r02590@世充  dm#dm02345@尉州 刺史 rm#r05336@時徳叡 帥所部 dm#dm00063@𣏌 、 dm#dm01532@夏 、 dm#dm08348@陳 、 dm#dm08446@隨 、 dm#dm07433@許 、 dm#dm05327@潁 、 dm#dm02345@尉 七州來降。

 rm#r01602@秦王世民 以便宜命州縣官竝依 rm#r02590@世充 所署，
無所變易，
改 dm#dm02345@尉州 爲 dm#dm01013@南汴州 ，
於是 dm#dm04660@河南 郡縣相繼來降。
# p 

 rm#r00280@劉武周 降將 rm@尋相 等多叛去。

諸將疑 rm#r00862@尉遲敬徳 ，
囚之軍中，
行臺左僕射 rm#r00876@屈突通 、尚書 rm#r02357@殷開山 言於 rm#r01602@世民 曰：
「 rm#r00862@敬徳 驍勇絶倫，
今既囚之，
心必怨望，
留之恐爲後患，
不如遂殺之。」

 rm#r01602@世民 曰：
「不然，
 rm#r00862@敬徳 若叛，
豈在 rm@尋相 之後邪！」

遽命釋之，
引入臥内，
賜之金，
曰：
「丈夫意氣相期，
勿以小嫌介意，
吾終不信讒言以害忠良，
公宜體之。

必欲去者，
以此金相資，
表一時共事之情也。」

辛巳，
 rm#r01602@世民 以五百騎行戰地，
登 dm#dm08949@魏宣武陵 。

 rm#r02590@王世充 帥歩騎萬餘猝至，
圍之，
 rm#r00523@單雄信 引槊直趨 rm#r01602@世民 ，
 rm#r00862@敬徳 躍馬大呼，
横刺 rm#r00523@雄信 墜馬，
 rm#r02590@世充 兵稍卻，
 rm#r00862@敬徳 翼 rm#r01602@世民 出圍。

 rm#r01602@世民 、 rm#r00862@敬徳 更帥騎兵還戰，
出入 rm#r02590@世充 陳，
往反無所礙。

 rm#r00876@屈突通 引大兵繼至，
 rm#r02590@世充 兵大敗，
僅以身免；
擒其冠軍大將軍 rm#r06273@陳智略 ，
斬首千餘級，
獲排矟兵六千。

 rm#r01602@世民 謂 rm#r00862@敬徳 曰：
「公何相報之速也！」

賜 rm#r00862@敬徳 金銀一篋，
自是寵遇日隆。
# p 

 rm#r00862@敬徳 善避矟，
毎單騎入敵陳中，
敵叢矟刺之，
終莫能傷，
又能奪敵矟返刺之。

 rm#r01016@齊王元吉 以善馬矟自負，
聞 rm#r00862@敬徳 之能，
請各去刃相與校勝負，
 rm#r00862@敬徳 曰：
「 rm#r00862@敬徳 謹當去之，
王勿去也。」

既而 rm#r01016@元吉 刺之，
終不能中。

 rm#r01602@秦王世民 問 rm#r00862@敬徳 曰：
「奪矟與避矟，
孰難？」
 rm#r00862@敬徳 曰：
「奪矟難。」

乃命 rm#r00862@敬徳 奪 rm#r01016@元吉 矟。

 rm#r01016@元吉 操矟躍馬，
志在刺之，
 rm#r00862@敬徳 須臾三奪其矟；
 rm#r01016@元吉 雖面相歎異，
内甚恥之。
# p 

叛胡陷 dm#dm02511@嵐州 。

# p 

初，
 rm#r02590@王世充 以 rm@邴元眞 爲 dm#dm05229@滑州 行臺僕射。

 dm#dm05457@濮州 刺史 rm#r05449@杜才幹 ，
 rm#r01704@李密 故將也，
恨 rm@元眞 叛 rm#r01704@密 ，
詐以其衆降之。

 rm@元眞 恃其官勢，
自往招慰，
 rm#r05449@才幹 出迎，
延入就坐，
執而數之曰：
「汝本庸才，
 rm#r01704@魏公 置汝元僚，
不建毫髮之功，
乃構滔天之禍，
今來送死，
是汝之分！」

遂斬之，
遣人齎其首至 dm#dm09166@黎陽 祭 rm#r01704@密 墓。

壬午，
以 dm#dm05457@濮州 來降。


# p 

突厥 rm#rz0034@莫賀咄設 寇 dm#dm04947@涼州 ，
總管 rm#r02189@楊恭仁 撃之，
爲所敗，
掠男女數千人而去。
# p 

丙戌，
以 rm#r06238@田瓚 爲 dm#dm08764@顯州 總管，
賜爵 rm#r06238@蔡國公 。

# p 

冬，
十月，
甲午，
 rm#r02590@王世充 大將軍 rm#r06193@張鎭周 來降。
# p 

甲辰，
行軍總管 rm#r03081@羅士信 襲 rm#r02590@王世充  dm#dm06158@硤石堡 ，
拔之。

 rm#r03081@士信 又圍 dm#dm00920@千金堡 ，
堡中人駡之。

 rm#r03081@士信 夜遣百餘人抱嬰兒數十至堡下，
使兒啼呼，
詐云「從 dm#dm03880@東都 來歸 rm#r0381@羅總管 」。

既而相謂曰：
「此 dm#dm00920@千金堡 也，
吾屬誤矣。」

即去。

堡中以爲 rm#r03081@士信 已去，
來者 dm#dm04788@洛陽 亡人，
出兵追之。

 rm#r03081@士信 伏兵於道，
伺其門開，
突入，
屠之。

# p 

 rm#r03028@竇建徳 之圍 dm#dm02689@幽州 也，
 rm#r03089@李藝 告急于 rm#r04273@高開道 ，
 rm#r04273@開道 帥二千騎救之，
 rm#r03028@建徳 兵引去，
 rm#r04273@開道 因 rm#r03089@藝 遣使來降。

戊申，
以 rm#r04273@開道 爲 dm#dm07077@蔚州 總管，
賜姓 rm#no@李氏 ，
封 rm#r04273@北平郡王 。

 rm#r04273@開道 有矢鏃在頬，
召醫出之，
醫曰：
「鏃深，
不可出。」

 rm#r04273@開道 怒，
斬之。

別召一醫，
曰：
「出之恐痛。」

又斬之。

更召一醫，
醫曰：
「可出。」

乃鑿骨，
置楔其間，
骨裂寸餘，
竟出其鏃；
 rm#r04273@開道 奏妓進膳不輟。


# p 

 rm#r03028@竇建徳 帥衆二十萬復攻 dm#dm02689@幽州 ，
 rm#r03028@建徳 兵已攀堞，
 rm#r03310@薛萬均 、 rm#r03311@萬徹 帥敢死士百人從地道出其背，
掩撃之，
 rm#r03028@建徳 兵潰走，
斬首千餘級。

 rm#r03089@李藝 兵乘勝薄其營，
 rm#r03028@建徳 陳於營中，
填塹而出，
奮撃，
大破之，
 rm#r03028@建徳 逐北，
至其城下，
攻之不克而還。

# p 

 rm#r01704@李密 之敗也，
 rm@楊慶 歸 dm#dm04788@洛陽 ，
復姓 rm#no@楊氏 。

及 rm#r02590@王世充 稱帝，
 rm#?@慶 復姓 rm#no@郭氏 ，
 rm#r02590@世充 以爲 dm#dm06371@管州 總管，
妻以兄女。

 rm#r01602@秦王世民 逼 dm#dm04788@洛陽 ，
 rm#?@慶 潛遣人請降，
 rm#r01602@世民 遣總管 rm#r01299@李世勣 將兵往據其城。

 rm#?@慶 欲與其妻偕來，
妻曰：
「主上使妾侍巾櫛者，
欲結君之心也。

今君既辜付託，
徇利求全，
妾將如君何！

若至 dm#dm08170@長安 ，
則君家一婢耳，
君何用爲！

願送至 dm#dm04788@洛陽 ，
君之惠也。」

 rm#?@慶 不許。

 rm#?@慶 出，
妻謂侍者曰：
「若 dyn#ch100@唐 遂勝 dyn#?@鄭 ，
則吾家必滅；
 dyn#?@鄭 若勝 dyn#ch100@唐 ，
則吾夫必死。

人生至此，
何用生爲！」

遂自殺。

庚戌，
 rm#?@慶 來降，
復姓 rm#no@楊氏 ，
拜上柱國、 rm#?@郇國公 。

# p 

時 rm#r02590@世充 太子 rm#?@玄應 鎭 dm#dm07165@虎牢 ，
軍于 dm#dm04118@榮 、 dm#dm04537@汴 之間，
聞之，
引兵趣 dm#dm06370@管城 ，
 rm#r01299@李世勣 撃卻之。

使 rm#r03716@郭孝恪 爲書説 dm#dm04118@榮州 刺史 rm#r06126@魏陸 ，
 rm#r06126@陸 密請降。

 rm#?@玄應 遣大將軍 rm#rz0059@張志 就 rm#r06126@陸 徵兵，
丙辰，
 rm#r06126@陸 擒 rm#rz0059@志 等四將，
舉州來降。

 dm#dm08390@陽城 令 rm@王雄 帥諸堡來降，
 rm#r01602@秦王世民 使 rm#r01299@李世勣 引兵應之，
以 rm@雄 爲 dm#dm02516@嵩州 刺史，
 dm#dm02513@嵩 南之路始通。

 rm#r06126@魏陸 使 rm#rz0059@張志 詐爲 rm#?@玄應 書，
停其東道之兵，
令其將 rm#r05278@張慈寶 且還 dm#dm04541@汴州 ，
又密告 dm#dm04541@汴州 刺史 rm#r05656@王要漢 使圖 rm#r05278@慈寶 ，
 rm#r05656@要漢 斬 rm#r05278@慈寶 以降。

 rm#?@玄應 聞諸州皆叛，
大懼，
奔還 dm#dm04788@洛陽 。

詔以 rm#r05656@要漢 爲 dm#dm04541@汴州 總管，
賜爵 rm#r05656@郳國公 。
榮滎榮滎
# p 

 rm#r05622@王弘烈 據 dm#dm07284@襄陽 ，
上令 dm#dm08028@金州 總管府司馬 dm#dm04928@涇陽  rm#r01672@李大亮 安撫 dm#dm04155@樊 、 dm#dm07938@鄧 以圖之。

十一月，
庚申，
 rm#r01672@大亮 攻 dm#dm04158@樊城鎭 ，
拔之，
斬其將 rm@國大安 ，
下其城柵十四。

# p 

 rm#r03260@蕭銑 性褊狹，
多猜忌。

諸將恃功恣横，
好專誅殺，
 rm#r03260@銑 患之，
乃宣言罷兵營農，
實欲奪諸將之權。

大司馬 rm#r05772@董景珍 弟爲將軍，
怨望，
謀作亂；
事泄，
伏誅。

 rm#r05772@景珍 時鎭 dm#dm08214@長沙 ，
 rm#r03260@銑 下詔赦之，
召還 dm#dm04516@江陵 。

 rm#r05772@景珍 懼，
甲子，
以 dm#dm08214@長沙 來降，
詔 dm#dm02449@峽州 刺史 rm#r03523@許紹 出兵應之。
# p 

 dm#dm08566@雲州 總管 rm#r03714@郭子和 ，
先與突厥、 rm#r02125@梁師都 相連結，
既而襲 rm#r02125@師都  dm#dm02296@寧朔城 ，
克之。

又詗得突厥釁隙，
遣使以聞，
爲突厥候騎所獲。

 rm#xjts08013@處羅可汗 大怒，
囚其弟 rm#xjts14017@子升 。

 rm#r03714@子和 自以孤危，
請帥其民南徙，
詔以 dm#dm02812@延州 故城處之。

# p 

 rm#r05293@張舉 、 rm#xjts25775@劉旻 之降也，
 rm#r02125@梁師都 大懼，
遣其尚書 rm#r06023@陸季覽 説突厥 rm@處羅可汗 曰：
「比者中原喪亂，
分爲數國，
勢均力弱，
故皆北面歸附突厥。

今 rm#r00280@定楊可汗 既亡，
天下將悉爲 dyn#ch100@唐 有。

 rm#r02125@師都 不辭灰滅，
亦恐次及可汗，
不若及其未定，
南取中原，
如 rm#rt0735@魏道武 所爲，
 rm#r02125@師都 請爲郷導。」

 rm@處羅 從之，
謀使 rm#rz0034@莫賀咄設 入自 dm#dm01114@原州 ，
 rm@泥歩設 與 rm#r02125@師都 入自 dm#dm02812@延州 ，
 rm@突利可汗 與奚、霫、契丹、靺鞨入自 dm#dm02689@幽州 ，
會 rm#r03028@竇建徳 之師自 dm#dm05220@滏口 西入，
會于 dm#dm03533@晉 、 dm#dm06430@絳 。

 rm#rz0034@莫賀咄 者，
 rm@處羅 之弟 rm#rz0034@咄苾 也；
 rm@突利 者，
 rm#rz0041@始畢 之子 rm#xjts11264@什鉢苾 也。
處羅入自幷州
# p 

 rm#xjts08013@處羅 又欲取 dm#dm00059@幷州 以居 rm#r06218@楊政道 ，
其羣臣多諫，
 rm#xjts08013@處羅 曰：
「我父失國，
頼 dyn#ch174@隋 得立，
此恩不可忘。」

將出師而卒。

 rm#xjts27179@義成公主 以其子 rm#xjts10627@奧射設 醜弱，
廢之，
更立 rm#rz0034@莫賀咄設 ，
號 rm#rz0034@頡利可汗 。

乙酉，
 rm#rz0034@頡利 遣使告 rm#xjts08013@處羅 之喪，
上禮之如 rm#rz0041@始畢 之喪。

# p 

戊子，
安撫大使 rm#r01672@李大亮 取 rm#r02590@王世充  dm#dm04644@沮 、 dm#dm06927@華 二州。


# p 

是月，
 rm#r03028@竇建徳 濟 dm#dm04650@河 撃 rm#rz0003@孟海公 。

# p 

初，
 rm#r02590@王世充 侵 rm#r03028@建徳  dm#dm09166@黎陽 ，
 rm#r03028@建徳 襲破 dm#dm04359@殷州 以報之。

自是二國交惡，
信使不通。

及唐兵逼 dm#dm04788@洛陽 ，
 rm#r02590@世充 遣使求救於 rm#r03028@建徳 。

 rm#r03028@建徳 中書侍郎 rm#r05067@劉彬 説 rm#r03028@建徳 曰：
「天下大亂，
 dyn#ch100@唐 得 dm#dm08288@關西 ，
 dyn#?@鄭 得 dm#dm04660@河南 ，
 dyn#?@夏 得 dm#dm04656@河北 ，
共成鼎足之勢。

今 dyn#ch100@唐 舉兵臨 dyn#?@鄭 ，
自秋渉冬，
 dyn#ch100@唐 兵日増，
 dyn#?@鄭 地日蹙，
 dyn#ch100@唐 強 dyn#?@鄭 弱，
勢必不支，
 dyn#?@鄭 亡，
則 dyn#?@夏 不能獨立矣。

不如解仇除忿，
發兵救之，
 dyn#?@夏 撃其外，
鄭攻其内，
破 dyn#ch100@唐 必矣。

 dyn#ch100@唐 師既退，
徐觀其變，
若 dyn#?@鄭 可取則取之，
幷二國之兵，
乘 dyn#ch100@唐 師之老，
天下可取也！」

 rm#r03028@建徳 從之，
遣使詣 rm#r02590@世充 ，
許以赴援。

又遣其禮部侍郎 rm#r05362@李大師 等詣 dyn#ch100@唐 ，
請罷 dm#dm04788@洛陽 之兵，
 rm#r01602@秦王世民 留之，
不答。
# p 

十二月，
辛卯，
 rm#r02590@王世充  dm#dm07433@許 、 dm#dm00454@亳 等十一州皆請降。

# p 

壬辰，
 rm#r03089@燕郡王李藝 又撃 rm#r03028@竇建徳 軍於 dm#dm06380@籠火城 ，
破之。

# p 

辛丑，
 rm#r02590@王世充  dm#dm08448@隨州 總管 rm#r05322@徐毅 舉州降。

# p 

癸卯，
 dm#dm02449@峽州 刺史 rm#r03523@許紹 攻 rm#r03260@蕭銑  dm#dm06899@荊門鎭 ，
拔之。

 rm#r03523@紹 所部與 dyn#?@梁 、 dyn#?@鄭 鄰接，
二境得 rm#r03523@紹 士卒，
皆殺之，
 rm#r03523@紹 得二境士卒，
皆資給遣之。

敵人愧感，
不復侵掠，
境内以安。

# p 

 rm#r03260@蕭銑 遣其 rm#r05292@齊王張繡 攻 dm#dm08214@長沙 ，
 rm#r05772@董景珍 謂 rm#r05292@繡 曰：
「『前年醢 rm#r06194@彭越 ，
往年殺 rm#r06274@韓信 』，
卿不見之乎，
何爲相攻！」

 rm#r05292@繡 不應，
進兵圍之，
 rm#r05772@景珍 欲潰圍走，
爲麾下所殺；
 rm#r03260@銑 以 rm#r05292@繡 爲尚書令。

 rm#r05292@繡 恃功驕横，
 rm#r03260@銑 又殺之。

由是功臣諸將皆有離心，
兵勢益弱。

# p 

 rm#r02590@王世充 遣其兄子 rm#xjts01980@代王琬 、 rm#r03858@長孫安世 詣 rm#r03028@竇建徳 報聘，
且乞師。

# p 

突厥 rm@倫特勒 在 dm#dm00059@幷州 ，
大爲民患，
 dm#dm00059@幷州 總管 rm#r00187@劉世讓 設策擒之。

上聞之，
甚喜。

 rm#r01199@張道源 從 rm#r03028@竇建徳 在 dm#dm04660@河南 ，
密遣人詣 dm#dm08170@長安 ，
請出兵攻 dm#dm04839@洺州 以震 dm#dm02403@山東 。

丙午，
詔 rm#r00187@世讓 爲行軍總管，
使將兵出 dm#dm01466@土門 ，
趣 dm#dm04839@洺州 。

# p 

己酉，
 dm#dm05769@瓜州 刺史 rm#r05882@賀拔行威 執驃騎將軍 rm@達奚暠 ，
舉兵反。
# p 

 y@是歳 ，
 rm#r01680@李子通 渡 dm#dm04475@江 攻 rm#r02419@沈法興 ，
取 dm#dm00432@京口 。

 rm#r02419@法興 遣其僕射 rm#r05783@蒋元超 拒之，
戰於 dm#dm02703@庱亭 ，
 rm#r05783@元超 敗死，
 rm#r02419@法興 棄 dm#dm04374@毘陵 ，
奔 dm#dm01292@呉郡 。

於是 dm#dm00299@丹陽 、 dm#dm04374@毘陵 等郡皆降於 rm#r01680@子通 。

 rm#r01680@子通 以 rm#r02419@法興 府掾 rm#r01886@李百藥 爲内史侍郎、國子祭酒。

# p 

 rm#r02022@杜伏威 遣行臺左僕射 rm#r03657@輔公祏 將卒數千攻 rm#r01680@子通 ，
以將軍 rm#r03891@闞稜 、 rm#r02717@王雄誕 爲之副。

 rm#r03657@公祏 渡 dm#dm04475@江 攻 dm#dm00299@丹陽 ，
克之，
進屯 dm#dm05184@溧水 ，
 rm#r01680@子通 帥衆數萬拒之。

 rm#r03657@公祏 簡精甲千人，
執長刀爲前鋒，
又使千人踵其後，
曰：
「有退者即斬之。」

自帥餘衆，
復居其後。

 rm#r01680@子通 爲方陳而前，
 rm#r03657@公祏 前鋒千人殊死戰，
 rm#r03657@公祏 復張左右翼以撃之，
 rm#r01680@子通 敗走，
公祏逐之，
反爲所敗，
還，
閉壁不出。

 rm#r02717@王雄誕 曰：
「 rm#r01680@子通 無壁壘，
又狃於初勝，
乘其無備，
撃之可破也。」

 rm#r03657@公祏 不從。

 rm#r02717@雄誕 以其私屬數百人夜出撃之，
因風縱火，
 rm#r01680@子通 大敗，
降其卒數千人。

 rm#r01680@子通 食盡，
棄 dm#dm04510@江都 ，
保 dm#dm00432@京口 ，
 dm#dm04509@江西 之地盡入於 rm#r02022@伏威 ，
 rm#r02022@伏威 徙居 dm#dm00299@丹陽 。
# p 

 rm#r01680@子通 復東走 dm#dm01815@太湖 ，
收合亡散，
得二萬人，
襲 rm#r02419@沈法興 於 dm#dm01292@呉郡 ，
大破之。

 rm#r02419@法興 帥左右數百人棄城走，
 dm#dm01292@呉郡 賊帥 rm@聞人遂安 遣其將 rm#r05764@葉孝辯 迎之，
 rm#r02419@法興 中塗而悔，
欲殺 rm#r05764@孝辯 ，
更向 dm#dm03660@會稽 。

 rm#r05764@孝辯 覺之，
 rm#r02419@法興 窘迫，
赴 dm#dm04475@江 溺死。

 rm#r01680@子通 軍勢復振，
徙都 dm#dm08791@餘杭 ，
盡收 rm#r02419@法興 之地，
北自 dm#dm01815@太湖 ，
南至 dm#dm02525@嶺 ，
東包 dm#dm03660@會稽 ，
西距 dm#dm02209@宣城 ，
皆有之。帥其羣臣
# p 

 dm#dm02717@廣 、 dm#dm03342@新 二州賊帥 rm#r06108@高法澄 、 rm#r05559@沈寶徹 殺 dyn#ch174@隋 官，
據州，
附於 rm#r02073@林士弘 ，
 dm#dm05302@漢陽 太守 rm#r04199@馮盎 撃破之。

既而 rm#r05559@寶徹 兄子 rm@智臣 復聚兵於 dm#dm03342@新州 ，
 rm#r04199@盎 引兵撃之。

賊始合，
 rm#r04199@盎 免冑大呼曰：
「爾識我乎？」
賊多棄仗肉袒而拜，
遂潰，
擒 rm#r05559@寶徹 、 rm@智臣 等，
 dm#dm02525@嶺 外遂定。
# p 

 rm#r03028@竇建徳 行臺尚書令 dm#dm03021@恆山  rm#r05749@胡大恩 請降。

*** 四年
# year 0621
# p 

春，
正月，
癸酉，
以 rm#r05749@大恩 爲 dm#dm00485@代州 總管，
封 rm#r05749@定襄郡王 ，
賜姓 rm#no@李氏 。

 dm#dm00485@代州  dm#dm06091@石嶺 之北，
自 rm#r00280@劉武周 之亂，
寇盜充斥，
 rm#r05749@大恩 徙鎭 dm#dm09017@鴈門 ，
討撃，
悉平之。
# p 

稽胡酋帥 rm#r06157@劉仚成 部落數萬，
爲邊寇；
辛巳，
詔 rm#r01078@太子建成 統諸軍討之。
# p 

 rm#r02590@王世充  dm#dm04043@梁州 總管 rm#r05722@程嘉會 以所部來降。

# p 

 rm#r02022@杜伏威 遣其將 rm#r06013@陳正通 、 rm@徐紹宗 帥精兵二千來，
會 rm#r01602@秦王世民 撃 rm#r02590@王世充 ，
甲申，
攻 dyn#ch166@梁 ，
克之。

# p 

丙戌，
 dm#dm09188@黔州 刺史 rm#r05672@田世康 攻 rm#r03260@蕭銑 五州、四鎭，
皆克之。
# p 

 rm#r01602@秦王世民 選精鋭千餘騎，
皆皂衣玄甲，
分爲左右隊，
使 rm#r02977@秦叔寶 、 rm#r02983@程知節 、 rm#r00862@尉遲敬徳 、 rm@翟長孫 分將之。

毎戰，
 rm#r01602@世民 親被玄甲帥之爲前鋒，
乘機進撃，
所向無不摧破，
敵人畏之。

行臺僕射 rm#r00876@屈突通 、 rm#r03047@贊皇公竇軌 引兵按行營屯，
猝與 rm#r02590@王世充 遇，
戰不利。

 rm#r01602@秦王世民 帥玄甲救之，
 rm#r02590@世充 大敗，
獲其騎將 rm@葛彦璋 ，
俘斬六千餘人。

 rm#r02590@世充 遁歸。
# p 

 rm#r02009@李靖 説 rm#r02432@趙郡王孝恭 以取 rm#r03260@蕭銑 十策，
 rm#r02432@孝恭 上之。

二月，
辛卯，
改 dm#dm00576@信州 爲 dm#dm01550@夔州 ，
以 rm#r02432@孝恭 爲總管，
使大造舟艦，
習水戰。

以 rm#r02432@孝恭 未更軍旅，
以 rm#r02009@靖 爲行軍總管，
兼 rm#r02432@孝恭 長史，
委以軍事。

 rm#r02009@靖 説 rm#r02432@孝恭 悉召 dm#dm02566@巴 、 dm#dm07197@蜀 酋長子弟，
量才授任，
置之左右，
外示引擢，
實以爲質。

# p 

 rm#r02590@王世充 太子 rm#r04210@玄應 將兵數千人，
自 dm#dm07165@虎牢 運糧入 dm#dm04788@洛陽 ，
 rm#r01602@秦王世民 遣將軍 rm#r01653@李君羨 邀撃，
大破之，
 rm#?@玄應 僅以身免。
# p 

 rm#r01602@世民 使 rm#r00750@宇文士及 奏請進圍 dm#dm03880@東都 ，
上謂 rm#r00750@士及 曰：
「歸語爾王：
今取 dm#dm04788@洛陽 ，
止於息兵，
克城之日，
乘輿法物，
圖籍器械，
非私家所須者，
委汝收之；
其餘子女玉帛，
竝以分賜將士。」


# p 

辛丑，
 rm#r01602@世民 移軍 dm#dm08651@青城宮 ，
壁壘未立，
 rm#r02590@王世充 帥衆二萬自 dm#dm03423@方諸門 出，
憑故馬坊垣塹，
臨 dm#dm06303@穀水 以拒 dyn#ch100@唐 兵，
諸將皆懼。

 rm#r01602@世民 以精騎陳於 dm#dm00893@北邙 ，
登 dm#dm08949@魏宣武陵 以望之，
謂左右曰：
「賊勢窘矣，
悉衆而出，
徼幸一戰，
今日破之，
後不敢復出矣！」

命 rm#r00876@屈突通 帥歩卒五千渡水撃之，
戒 rm#r00876@通 曰：
「兵交則縱煙。」

煙作，
 rm#r01602@世民 引騎南下，
身先士卒，
與 rm#r00876@通 合勢力戰。

 rm#r01602@世民 欲知 rm#r02590@世充 陳厚薄，
與精騎數十衝之，
直出其背，
衆皆披靡，
殺傷甚衆。

既而限以長堤，
與諸騎相失，
將軍 rm#r00032@丘行恭 獨從 rm#r01602@世民 ，
 rm#r02590@世充 數騎追及之，
 rm#r01602@世民 馬中流矢而斃。

 rm#r00032@行恭 囘騎射追者，
發無不中，
追者不敢前。

乃下馬以授 rm#r01602@世民 ，
 rm#r00032@行恭 於馬前歩執長刀，
距躍大呼，
斬數人，
突陳而出，
得入大軍。

 rm#r02590@世充 亦帥衆殊死戰，
散而復合者數四，
自辰至午，
 rm#r02590@世充 兵始退。

 rm#r01602@世民 縱兵乘之，
直抵城下，
俘斬七千人，
遂圍之。

驃騎將軍 rm#r02342@段志玄 與 rm#r02590@世充 兵力戰，
深入，
馬倒，
爲 rm#r02590@世充 兵所擒，
兩騎夾持其髻，
將渡 dm#dm04780@洛水 ，
 rm#r02342@志玄 踴身而奮，
二人倶墜馬，
 rm#r02342@志玄 馳歸，
追者數百騎，
不敢逼。
# p 

初，
驃騎將軍 rm#r05632@王懷文 爲 dyn#ch100@唐 軍斥候，
爲 rm#r02590@世充 所獲，
 rm#r02590@世充 欲慰悦之，
引置左右。

壬寅，
 rm#r02590@世充 出 dm#dm01171@右掖門 ，
臨 dm#dm04780@洛水 爲陳，
 rm#r05632@懷文 忽引槊刺 rm#r02590@世充 ，
 rm#r02590@世充 衷甲，
槊折不能入，
左右猝出不意，
皆愕眙不知所爲。

 rm#r05632@懷文 走趣 dyn#ch100@唐 軍，
至 dm#dm02312@寫口 ，
追獲，
殺之。

 rm#r02590@世充 歸，
解去衷甲，
袒示羣臣曰：
「 rm#r05632@懷文 以槊刺我，
卒不能傷，
豈非天所命乎！」

# p 

先是御史大夫 rm#rz0004@鄭頲 不樂仕 rm#r02590@世充 ，
多稱疾不預事，
至是謂 rm#r02590@世充 曰：
「臣聞佛有金剛不壞身，
陛下眞是也。

臣實多幸，
得生佛世，
願棄官削髮爲沙門，
服勤精進，
以資陛下之神武。」

 rm#r02590@世充 曰：
「國之大臣，
聲望素重，
一旦入道，
將駭物聽。

俟兵革休息，
當從公志。」

 rm#rz0004@頲 固請，
不許。

退謂其妻曰：
「吾束髮從官，
志慕名節，
不幸遭遇亂世，
流離至此，
側身猜忌之朝，
累足危亡之地，
智力淺薄，
無以自全，
人生會有死，
早晩何殊，
姑從吾所好，
死亦無憾。」

遂削髮被僧服。

 rm#r02590@世充 聞之，
大怒曰：
「爾以我爲必敗，
欲苟免邪？
不誅之，
何以制衆！」

遂斬 rm#rz0004@頲 於市。

 rm#rz0004@頲 言笑自若，
觀者壯之。
# p 

詔贈 rm#r05632@王懷文 上柱國、 dm#dm03674@朔州 刺史。

# p 

 dm#dm00059@幷州 安撫使 rm#ry9001@唐儉 密奏：
「 rm#r01611@眞郷公李仲文 與妖僧 rm#xjts12833@志覺 有謀反語，
又娶 rm#no@陶氏 之女以應桃李之謠。

諂事可汗，
甚得其意，
可汗許立爲 rm#xjts26914@南面可汗 ；
及在 dm#dm00059@幷州 ，
贓賄狼籍。」

上命 rm#r03424@裴寂 、 rm#r03915@陳叔達 、 rm#r03249@蕭瑀 雜鞫之。

乙巳，
 rm#r01611@仲文 伏誅。
# p 

庚戌，
 rm@王泰 棄 dm#dm04709@河陽 走，
其將 rm#r05910@趙夐 等以城來降。

別將 rm#r00523@單雄信 、 rm#r05842@裴孝達 與總管 rm#r02607@王君廓 相持於 dm#dm04770@洛口 ，
 rm#r01602@秦王世民 帥歩騎五千援之，
至 dm#dm07655@轘轅 ，
 rm#r00523@雄信 等遁去，
 rm#r02607@君廓 追敗之。

# p 

壬子，
 dm#dm02812@延州 總管 rm#r06227@段徳操 撃 rm#r06157@劉仚成 ，
破之，
斬首千餘級。


# p 

乙卯，
 rm#r02590@王世充  dm#dm03102@懷州 刺史 rm@陸善宗 以城降。
# p 

 rm#r01602@秦王世民 圍 dm#dm04788@洛陽 宮城，
城中守禦甚嚴，
大礮飛石重五十斤，
擲二百歩，
八弓弩箭如車輻，
鏃如巨斧，
射五百歩。

 rm#r01602@世民 四面攻之，
晝夜不息，
旬餘不克。

城中欲翻城者凡十三輩，
皆不果發而死。

 dyn#ch100@唐 將士皆疲弊思歸，
總管 rm#r00246@劉弘基 等請班師，
 rm#r01602@世民 曰：
「今大舉而來，
當一勞永逸。

東方諸州已望風款服，
唯 dm#dm04788@洛陽 孤城，
勢不能久，
功在垂成，
奈何棄之而去！」

乃下令軍中曰：
「 dm#dm04788@洛陽 未破，
師必不還，
敢言班師者斬！」

衆乃不敢復言。

上聞之，
亦密敕 rm#r01602@世民 使還，
 rm#r01602@世民 表稱 dm#dm04788@洛陽 必可克，
又遣參謀軍事 rm#r00851@封徳彞 入朝面論形勢。

 rm#r00851@徳彞 言於上曰：
「 rm#r02590@世充 得地雖多，
率皆羈屬，
號令所行，
唯 dm#dm04788@洛陽 一城而已，
智盡力窮，
克在朝夕。

今若旋師，
賊勢復振，
更相連結，
後必難圖！」

上乃從之。

 rm#r01602@世民 遺 rm#r02590@世充 書，
諭以禍福；
 rm#r02590@世充 不報。
# p 

戊午，
 rm#r02590@王世充  dm#dm07949@鄭州 司兵 rm#r05560@沈悦 遣使詣左武候大將軍 rm#r01299@李世勣 請降。

左衞將軍 rm#r02607@王君廓 夜引兵襲 dm#dm07165@虎牢 ，
 rm#r05560@悦 爲内應，
遂拔之，
獲其 rm@荊王行本 及長史 rm#r01373@戴冑 。

 rm#r05560@悦 ，
 rm#r06679@君理 之孫也。

# p 

 rm#r03028@竇建徳 克 dm#dm01309@周橋 ，
虜 rm#rz0003@孟海公 。
# p 

三月，
庚申，
以靺鞨渠帥 rm@突地稽 爲 dm#dm05599@燕州 總管。

# p 

太子 rm#r01078@建成 獲稽胡千餘人，
釋其酋帥數十人，
授以官爵，
使還，
招其餘黨，
 rm#r06157@劉仚成 亦降。

 rm#r01078@建成 詐稱増置州縣，
築城邑，
命降胡年二十以上皆集，
以兵圍而殺之，
死者六千餘人，
 rm#r06157@仚成 覺變，
亡奔 rm#r02125@梁師都 。


# p 

行軍總管 rm#r00187@劉世讓 攻 rm#r03028@竇建徳  dm#dm09115@黄州 ，
拔之。

 dm#dm04839@洺州 嚴備，
 rm#r00187@世讓 不得進。

會突厥將入寇，
上召 rm#r00187@世讓 還。
# p 

 rm#r03028@竇建徳 所署 dm#dm03582@普樂 令 dm#dm02631@平恩  rm#?@程名振 來降，
上遙除 rm#?@名振  dm#dm04405@永寧 令，
使將兵徇 dm#dm04656@河北 。

 rm#?@名振 夜襲 dm#dm07971@鄴 ，
俘其男女千餘人。

去 dm#dm07971@鄴 八十里，
閲婦人乳有湩者，
九十餘人，
悉縱遣之，
 dm#dm07971@鄴 人感其仁，
爲之飯僧。

# p 

突厥 rm#rz0034@頡利可汗 承父兄之資，
士馬雄盛，
有憑陵 dm#dm00255@中國 之志。

妻 dyn#ch174@隋  rm#xjts27179@義成公主 ，
公主從弟 rm#xjts22998@善經 ，
避亂在突厥，
與 rm#r02590@王世充 使者 rm#r05638@王文素 共説 rm#rz0034@頡利 曰：
「昔 rm#rz0033@啓民 爲兄弟所逼，
脱身奔 dyn#ch174@隋 ，
頼 rm#rt0778@文皇帝 之力，
有此土宇，
子孫享之。

今 dyn#ch100@唐 天子非 rm#rt0778@文皇帝 子孫，
可汗宜奉 rm#r06218@楊政道 以伐之，
以報 rm#rt0778@文皇帝 之徳。」

 rm#rz0034@頡利 然之。

上以 dm#dm00255@中國 未寧，
待突厥甚厚，
而 rm#rz0034@頡利 求請無厭，
言辭驕慢。

甲戌，
突厥寇 dm#dm04568@汾陰 。


# p 

 dyn#ch100@唐 兵圍 dm#dm04788@洛陽 ，
掘塹築壘而守之。

城中乏食，
絹一匹直粟三升，
布十匹直鹽一升，
服飾珍玩，
賤如土芥。

民食草根木葉皆盡，
相與澄取浮泥，
投米屑作餅食之，
皆病，
身腫脚弱，
死者相枕倚於道。

 rm#rt0783@皇泰主 之遷民入宮城也，
凡三萬家，
至是無三千家。

雖貴爲公卿，
糠覈不充，
尚書郎以下，
親自負戴，
往往餒死。
# p 

 rm#r03028@竇建徳 使其將 rm#r06240@范願 守 dm#dm03641@曹州 ，
悉發 rm#rz0003@孟海公 、 rm#r01305@徐圓朗 之衆，
西救 dm#dm04788@洛陽 。

至 dm#dm05229@滑州 ，
 rm#r02590@王世充 行臺僕射 rm#rz0071@韓洪 開門納之。

己卯，
軍于 dm#dm07987@酸棗 。

# p 

壬午，
突厥寇 dm#dm06095@石州 ，
刺史 rm#r05662@王集 撃卻之。
# p 

 rm#r03028@竇建徳 陷 dm#dm06371@管州 ，
殺刺史 rm#r05935@郭士安 ；
又陷 dm#dm05216@滎陽 、 dm#dm08423@陽翟 等縣，
水陸竝進，
汎舟運糧，
泝 dm#dm04650@河 西上。

 rm#r02590@王世充 之弟 dm#dm02952@徐州 行臺 rm#r06695@世辯 遣其將 rm#?@郭士衡 將兵數千會之，
合十餘萬，
號三十萬，
軍於 dm#dm03143@成皋 之東原，
築宮 dm#dm03918@板渚 ，
遣使與 rm#r02590@王世充 相聞。
# p 

先是，
 rm#r03028@建徳 遺 rm#r01602@秦王世民 書，
請退軍 dm#dm05384@潼關 ，
返 dyn#?@鄭 侵地，
復脩前好。

 rm#r01602@世民 集將佐議之，
皆請避其鋒，
 rm#r03716@郭孝恪 曰：
「 rm#r02590@世充 窮蹙，
垂將面縛，
 rm#r03028@建徳 遠來助之，
此天意欲兩亡之也。

宜據 dm#dm04285@武牢 之險以拒之，
伺間而動，
破之必矣！」

記室 rm#r03296@薛收 曰：
「 rm#r02590@世充 保據 dm#dm03880@東都 ，
府庫充實，
所將之兵，
皆 dm#dm04475@江 、 dm#dm04981@淮 精鋭，
即日之患，
但乏糧食耳。

以是之故，
爲我所持，
求戰不得，
守則難久。

 rm#r03028@建徳 親帥大衆，
遠來赴援，
亦當極其精鋭。

若縱之至此，
兩寇合從，
轉 dm#dm04656@河北 之粟以饋 dm#dm04788@洛陽 ，
則戰爭方始，
偃兵無日，
混一之期，
殊未有涯也。

今宜分兵守 dm#dm04788@洛陽 ，
深溝高壘，
 rm#r02590@世充 出兵，
愼勿與戰，
大王親帥驍鋭，
先據 dm#dm03143@成皋 ，
厲兵訓士，
以待其至，
以逸待勞，
決可克也。

 rm#r03028@建徳 既破，
 rm#r02590@世充 自下，
不過二旬，
兩主就縛矣！」

 rm#r01602@世民 善之。

 rm#r03296@收 ，
 rm#r06761@道衡 之子也。

 rm#r03249@蕭瑀 、 rm#r00876@屈突通 、 rm#r00851@封徳彞 皆曰：
「吾兵疲老，
 rm#r02590@世充 憑守堅城，
未易猝拔，
 rm#r03028@建徳 席勝而來，
鋒鋭氣盛，
吾腹背受敵，
非完策也，
不若退保 dm#dm03337@新安 ，
以承其弊。」

 rm#r01602@世民 曰：
「 rm#r02590@世充 兵摧食盡，
上下離心，
不煩力攻，
可以坐克。

 rm#r03028@建徳 新破 rm#rz0003@海公 ，
將驕卒惰，
吾據 dm#dm04285@武牢 ，
扼其咽喉。

彼若冒險爭鋒，
吾取之甚易。

若狐疑不戰，
旬月之間，
 rm#r02590@世充 自潰。

城破兵強，
氣勢自倍，
一舉兩克，
在此行矣。

若不速進，
賊入 dm#dm04285@武牢 ，
諸城新附，
必不能守；
兩賊倂力，
其勢必強，
何弊之承！

吾計決矣！」

 rm#r00876@通 等又請解圍據險以觀其變，
 rm#r01602@世民 不許。

中分麾下，
使 rm#r00876@通 等副 rm#r01016@齊王元吉 圍守 dm#dm03880@東都 ，
 rm#r01602@世民 將驍勇三千五百人東趣 dm#dm04285@武牢 。

時正晝出兵，
歴 dm#dm00893@北邙 ，
抵 dm#dm04709@河陽 ，
趨 dm#dm08719@鞏 而去。

 rm#r02590@王世充 登城望見，
莫之測也，
竟不敢出。致死於我
# p 

癸未，
 rm#r01602@世民 入 dm#dm04285@武牢 ；
甲申，
將驍騎五百，
出 dm#dm04285@武牢 東二十餘里，
覘 rm#r03028@建徳 之營。

縁道分留從騎，
使 rm#r01299@李世勣 、 rm#r02983@程知節 、 rm#r02977@秦叔寶 分將之，
伏於道旁，
纔餘四騎，
與之偕進。

 rm#r01602@世民 謂 rm#r00862@尉遲敬徳 曰。

「吾執弓矢，
公執槊相隨，
雖百萬衆若我何！」

又曰：
「賊見我而還，
上策也。」

去 rm#r03028@建徳 營三里所，
 rm#r03028@建徳 遊兵遇之，
以爲斥候也。

 rm#r01602@世民 大呼曰：
「我 rm#r01602@秦王 也。」

引弓射之，
斃其一將。

 rm#r03028@建徳 軍中大驚，
出五六千騎逐之，
從者咸失色。

 rm#r01602@世民 曰：
「汝弟前行，
吾自與 rm#r00862@敬徳 爲殿。」

於是按轡徐行，
追騎將至，
則引弓射之，
輒斃一人。

追者懼而止，
止而復來，
如是再三，
毎來必有斃者，
 rm#r01602@世民 前後射殺數人，
 rm#r00862@敬徳 殺十許人，
追者不敢復逼。

 rm#r01602@世民 逡巡稍卻以誘之，
入於伏内，
 rm#r01299@世勣 等奮撃，
大破之，
斬首三百餘級，
獲其驍將 rm#r05553@殷秋 、 rm#r05715@石瓚 以歸。

乃爲書報 rm#r03028@建徳 ，
諭以「 dm#dm07617@趙 、 dm#dm08945@魏 之地，
久爲我有，
爲足下所侵奪。

但以 rm#r02450@淮安 見禮，
公主得歸，
故相與坦懷釋怨。

 rm#r02590@世充 頃與足下修好，
已嘗反覆，
今亡在朝夕，
更飾辭相誘，
足下乃以三軍之衆，
仰哺他人，
千金之資，
坐供外費，
良非上策。

今前茅相遇，
彼遽崩摧，
郊勞未通，
能無懷愧。

故抑止鋒鋭，
冀聞擇善，
若不獲命，
恐雖悔難追。」

# p 

立 rm#r01602@秦王世民 之子 rm#r02535@泰 爲 rm#r02535@衞王 。
# p 

夏，
四月，
己丑，
 dm#dm07478@豐州 總管 rm#r01267@張長遜 入朝。

時言事者多云，
 rm#r01267@長遜 久居 dm#dm07478@豐州 ，
爲突厥所厚，
非國家之利。

 rm#r01267@長遜 聞之，
請入朝，
上許之。

會太子 rm#r01078@建成 北伐稽胡，
 rm#r01267@長遜 帥所部會之，
因入朝，
拜右武候將軍。

 dm#dm05982@益州 行臺左僕射 rm#r03047@竇軌 帥 dm#dm02566@巴 、 dm#dm07197@蜀 兵來會 rm#r01602@秦王 ，
撃 rm#r02590@王世充 ；
以 rm#r01267@長遜 檢校 dm#dm05982@益州 行臺右僕射。
# p 

己亥，
突厥 rm#rz0034@頡利可汗 寇 dm#dm09017@鴈門 ，
 rm#r05749@李大恩 撃走之。

# p 

壬寅，
 rm#r02590@王世充 騎將 rm#r05483@楊公卿 、 rm#r00523@單雄信 引兵出戰，
 rm#r01016@齊王元吉 撃之，
不利，
行軍總管 rm#r05701@盧君諤 戰死。


# p 

太子還 dm#dm08170@長安 。
# p 

 rm#r02590@王世充  dm#dm02627@平州 刺史 rm#r05119@周仲隱 以城來降。

# p 

戊申，
突厥寇 dm#dm00059@幷州 。

初，
 rm@處羅可汗 與 rm#r00280@劉武周 相表裏，
寇 dm#dm00059@幷州 ；
上遣太常卿 rm#r03778@鄭元璹 往諭以禍福，
 rm@處羅 不從。

未幾，
 rm@處羅 遇疾卒，
國人疑元璹毒之，
留不遣。

上又遣 rm#r02510@漢陽公瓌 賂 rm#rz0034@頡利可汗 以金帛，
 rm#rz0034@頡利 欲令 rm#r02510@瓌 拜，
 rm#r02510@瓌 不從，
亦留之。

又留左驍衞大將軍 rm#r03866@長孫順徳 。

上怒，
亦留其使者。

 rm#r02510@瓌 ，
 rm#r02432@孝恭 之弟也。

# p 

甲寅，
封皇子 rm#r00468@元方 爲 rm#r00468@周王 ，
 rm#r01321@元禮 爲 rm#r01321@鄭王 ，
 rm#r04123@元嘉 爲 rm#r04123@宋王 ，
 rm#r01289@元則 爲 rm#r01289@荊王 ，
 rm#xjts13471@元茂 爲 rm#xjts13471@越王 。
# p 

 rm#r03028@竇建徳 迫於 dm#dm04285@武牢 不得進，
留屯累月，
戰數不利，
將士思歸。

丁巳，
 rm#r01602@秦王世民 遣 rm#r02607@王君廓 將輕騎千餘抄其糧運，
又破之，
獲其大將軍 rm#r05310@張青特 。
# p 

 rm#r05052@凌敬 言於 rm#r03028@建徳 曰：
「大王悉兵濟 dm#dm04650@河 ，
攻取 dm#dm03102@懷州 、 dm#dm04709@河陽 ，
使重將守之，
更鳴鼓建旗，
踰 dm#dm01820@太行 ，
入 dm#dm00204@上黨 ，
徇 dm#dm04559@汾 、 dm#dm03533@晉 ，
趣 dm#dm07031@蒲津 ，
如此有三利：
一則蹈無人之境，
取勝可以萬全；
二則拓地收衆，
形勢益強；
三則 dm#dm08281@關中 震駭，
 dyn#?@鄭 圍自解。

爲今之策，
無以易此。」

 rm#r03028@建徳 將從之，
而 rm#r02590@王世充 遣使告急相繼於道，
 rm@王琬 、 rm#r03858@長孫安世 朝夕涕泣，
請救 dm#dm04788@洛陽 ，
又陰以金玉啗 rm#r03028@建徳 諸將，
以撓其謀。

諸將皆曰：
「 rm#r05052@凌敬 書生，
安知戰事，
其言豈可用也！」

 rm#r03028@建徳 乃謝 rm#r05052@敬 曰：
「今衆心甚鋭，
天贊我也，
因之決戰，
必將大捷，
不得從公言。」

 rm#r05052@敬 固爭之，
 rm#r03028@建徳 怒，
令扶出。

其妻 rm@曹氏 謂 rm#r03028@建徳 曰：
「祭酒之言不可違也。

今大王自 dm#dm05220@滏口 乘 dyn#ch100@唐國 之虚，
連營漸進以取山北，
又因突厥西抄 dm#dm08281@關中 ，
 dyn#ch100@唐 必還師自救，
 dyn#?@鄭 圍何憂不解！

若頓兵於此，
老師費財，
欲求成功，
在於何日？」
 rm#r03028@建徳 曰：
「此非女子所知！

吾來救 dyn#?@鄭 ，
 dyn#?@鄭 今倒懸，
亡在朝夕，
吾乃捨之而去，
是畏敵而棄信也，
不可。」

# p 

諜者告曰：
「 rm#r03028@建徳 伺 dyn#ch100@唐 軍芻盡，
牧馬於 dm#dm04650@河 北，
將襲 dm#dm04285@武牢 。」

五月，
戊午，
 rm#r01602@秦王世民 北濟 dm#dm04650@河 ，
南臨 dm#dm02751@廣武 ，
察敵形勢，
因留馬千餘匹，
牧於河渚以誘之，
夕還 dm#dm04285@武牢 。

己未，
 rm#r03028@建徳 果悉衆而至，
自 dm#dm03918@板渚 出 dm#dm05622@牛口 置陳，
北距 dm#dm01648@大河 ，
西薄 dm#dm04455@汜水 ，
南屬 dm#dm09028@鵲山 ，
亙二十里，
鼓行而進。

諸將皆懼，
 rm#r01602@世民 將數騎升高丘而望之，
謂諸將曰：
「賊起 dm#dm02403@山東 ，
未嘗見大敵，
今度險而囂，
是無紀律，
逼城而陳，
有輕我心；
我按甲不出，
彼勇氣自衰，
陳久卒飢，
勢將自退，
追而撃之，
無不克者。

與公等約，
甫過日中，
必破之矣！」

 rm#r03028@建徳 意輕 dyn#ch100@唐 軍，
遣三百騎渉 dm#dm04455@汜水 ，
距 dyn#ch100@唐 營一里所止。

遣使與 rm#r01602@世民 相聞曰：
「請選鋭士數百與之劇。」

 rm#r01602@世民 遣 rm#r02607@王君廓 將長槊二百以應之，
相與交戰，
乍進乍退，
兩無勝負，
各引還。

 rm#r03754@王琬 乘 rm#rt0779@隋煬帝 驄馬，
鎧仗甚鮮，
迥出陳前以誇衆。

 rm#r01602@世民 曰：
「彼所乘眞良馬也！」

 rm#r00862@尉遲敬徳 請往取之，
 rm#r01602@世民 止之曰：
「豈可以一馬喪猛士。」

 rm#r00862@敬徳 不從，
與 rm#r06110@高甑生 、 rm#r05471@梁建方 三騎直入其陳，
擒 rm#?@琬 ，
引其馬馳歸，
衆無敢當者。

 rm#r01602@世民 使召 dm#dm04650@河 北馬，
待其至乃出戰。
# p 

 rm#r03028@建徳 列陳，
自辰至午，
士卒飢倦，
皆坐列，
又爭飮水，
逡巡欲退。

 rm#r01602@世民 命 rm#r00750@宇文士及 將三百騎經 rm#r03028@建徳 陳西，
馳而南上，
戒之曰：
「賊若不動，
爾宜引歸，
動則引兵東出。」

 rm#r00750@士及 至陳前，
陳果動，
 rm#r01602@世民 曰：
「可撃矣！」

時 dm#dm04650@河 渚馬亦至，
乃命出戰。

 rm#r01602@世民 帥輕騎先進，
大軍繼之，
東渉 dm#dm04455@汜水 ，
直薄其陳。

 rm#r03028@建徳 羣臣方朝謁，
 dyn#ch100@唐 騎猝來，
朝臣趨就 rm#r03028@建徳 ，
 rm#r03028@建徳 召騎兵使拒 dyn#ch100@唐 兵，
騎兵阻朝臣不得過，
 rm#r03028@建徳 揮朝臣令卻，
進退之間，
 dyn#ch100@唐 兵已至，
 rm#r03028@建徳 窘迫，
退依東陂。

 rm#r03033@竇抗 引兵撃之，
戰小不利。

 rm#r01602@世民 帥騎赴之，
所向皆靡。

 rm#r02454@淮陽王道玄 挺身陷陳，
直出其後，
復突陳而歸，
再入再出，
飛矢集其身如蝟毛，
勇氣不衰，
射人，
皆應弦而仆。

 rm#r01602@世民 給以副馬，
使從己。

於是諸軍大戰，
塵埃漲天。

 rm#r01602@世民 帥 rm#r00376@史大奈 、 rm#r02983@程知節 、 rm#r02977@秦叔寶 、 rm#r00758@宇文歆 等卷旆而入，
出其陳後，
張 dyn#ch100@唐 旗幟，
 rm#r03028@建徳 將士顧見之，
大潰，
追奔三十里，
斬首三千餘級。

 rm#r03028@建徳 中槊，
竄匿於 dm#dm05623@牛口渚 。

車騎將軍 rm#r05685@白士讓 、 rm#r05504@楊武威 逐之，
 rm#r03028@建徳 墜馬，
 rm#r05685@士讓 援槊欲刺之，
 rm#r03028@建徳 曰：
「勿殺我，
我 rm#r03028@夏王 也，
能富貴汝。」

 rm#r05504@武威 下擒之，
載以從馬，
來見 rm#r01602@世民 。

 rm#r01602@世民 讓之曰：
「我自討 rm#r02590@王世充 ，
何預汝事，
而來越境，
犯我兵鋒！」

 rm#r03028@建徳 曰：
「今不自來，
恐煩遠取。」

 rm#r03028@建徳 將士皆潰去，
所俘獲五萬人，
 rm#r01602@世民 即日散遣之，
使還郷里。
# p 

 rm#r00851@封徳彞 入賀，
 rm#r01602@世民 笑曰：
「不用公言，
得有今日。

智者千慮，
不免一失乎！」

 rm#r00851@徳彞 甚慚。
# p 

 rm#r03028@建徳 妻 rm@曹氏 與左僕射 rm#r06140@齊善行 將數百騎遁歸 dm#dm04839@洺州 。

# p 

甲子，
 rm#r02590@世充  dm#dm00606@偃師 ，
 dm#dm08719@鞏縣 皆降。


# p 

乙丑，
以太子左庶子 rm#r03785@鄭善果 爲 dm#dm02404@山東道 撫慰大使。

# p 

 rm#r02590@世充 將 rm#r06232@王徳仁 棄故 dm#dm04788@洛陽 城而遁，
亞將 rm#r05902@趙季卿 以城降。

 rm#r01602@秦王世民 囚 rm#r03028@竇建徳 、 rm#r03754@王琬 、 rm#r03858@長孫安世 、 rm#xjts01484@郭士衡 等至 dm#dm04788@洛陽 城下，
以示 rm#r02590@世充 。

 rm#r02590@世充 與 rm#r03028@建徳 語而泣，
仍遣 rm#r03858@安世 等入城言敗状。

 rm#r02590@世充 召諸將議突圍，
南走 dm#dm07284@襄陽 ，
諸將皆曰：
「吾所恃者 rm#r03028@夏王 ，
 rm#r03028@夏王 今已爲擒，
雖得出，
終必無成。」

丙寅，
 rm#r02590@世充 素服帥其太子、羣臣、二千餘人詣軍門降。

 rm#r01602@世民 禮接之，
 rm#r02590@世充 俯伏流汗。

 rm#r01602@世民 曰：
「卿常以童子見處，
今見童子，
何恭之甚邪？」
 rm#r02590@世充 頓首謝罪。

於是部分諸軍，
先入 dm#dm04788@洛陽 ，
分守市肆，
禁止侵掠，
無敢犯者。
# p 

丁卯，
 rm#r01602@世民 入宮城，
命記室 rm#r01377@房玄齡 先入中書、門下省，
收 dyn#ch174@隋 圖籍制詔，
已爲 rm#r02590@世充 所毀，
無所獲。

命 rm#r03249@蕭瑀 、 rm#r03047@竇軌 等封府庫，
收其金帛，
頒賜將士。

收 rm#r02590@世充 之黨罪尤大者 rm#r05551@段達 、 rm@王隆 、 rm#r05222@崔洪丹 、 rm#r05809@薛徳音 、 rm#r06219@楊汪 、 rm#r05151@孟孝義 、 rm#r00523@單雄信 、 rm#r05483@楊公卿 、 rm#r05930@郭什柱 、 rm#?@郭士衡 、 rm#r05768@董叡 、 rm#r05289@張童兒 、 rm#r06232@王徳仁 、 rm#r01583@朱粲 、 rm#r05929@郭善才 等十餘人斬於 dm#dm04780@洛水 之上。

初，
 rm#r01299@李世勣 與 rm#r00523@單雄信 友善，
誓同生死。

及 dm#dm04788@洛陽 平，
 rm#r01299@世勣 言 rm#r00523@雄信 驍健絶倫，
請盡輸己之官爵以贖之，
 rm#r01602@世民 不許。

 rm#r01299@世勣 固請不能得，
涕泣而退。

 rm#r00523@雄信 曰：
「我固知汝不辦事。」

 rm#r01299@世勣 曰：
「吾不惜餘生，
與兄倶死；
但既以此身許國，
事無兩遂。

且吾死之後，
誰復視兄之妻子乎？」
乃割股肉以啗 rm#r00523@雄信 ，
曰：
「使此肉隨兄爲土，
庶幾不負昔誓也！」

士民疾 rm#r01583@朱粲 殘忍，
競投瓦礫撃其尸，
須臾如冢。

囚 rm#r06054@韋節 、 rm#r02241@楊續 、 rm#r03858@長孫安世 等十餘人送 dm#dm08170@長安 。

士民無罪爲 rm#r02590@世充 所囚者，
皆釋之，
所殺者祭而誄之。

# p 

初，
 rm#r01602@秦王 府屬 rm#r02033@杜如晦 叔父 rm#r02056@淹 事 rm#r02590@王世充 。

 rm#r02056@淹 素與 rm#r02033@如晦 兄弟不協，
譖 rm#r02033@如晦 兄殺之，
又囚其弟 rm#r02052@楚客 ，
餓幾死，
 rm#r00825@楚客 終無怨色。

及 dm#dm04788@洛陽 平，
 rm#r02056@淹 當死，
 rm#r00825@楚客 涕泣請 rm#r02033@如晦 救之，
 rm#r02033@如晦 不從。

 rm#r00825@楚客 曰：
「曩者叔已殺兄，
今兄又殺叔，
一門之内，
自相殘而盡，
豈不痛哉！」

欲自剄，
 rm#r02033@如晦 乃爲之請於 rm#r01602@世民 ，
 rm#r02056@淹 得免死。

# p 

 rm#r01602@秦王世民 坐 dm#dm08270@閶闔門 ，
 rm#r06246@蘇威 請見，
稱老病不能拜。

 rm#r01602@世民 遣人數之曰：
「公 dyn#ch174@隋室 宰相，
危不能扶，
使君弑國亡。

見 rm#r01704@李密 、 rm#r02590@王世充 皆拜伏舞蹈。

今既老病，
無勞相見。」

及至 dm#dm08170@長安 ，
又請見，
不許。

既老且貧，
無復官爵，
卒於家，
年八十二。

# p 

 rm#r01602@秦王世民 觀 dyn#ch174@隋 宮殿，
歎曰：
「逞侈心，
窮人欲，
無亡得乎！」

命撤 dm#dm06353@端門樓 ，
焚 dm#dm00362@乾陽殿 ，
毀 dm#dm00765@則天門 及闕；
廢諸道場，
城中僧尼，
留有名徳者各三十人，
餘皆返初。

# p 

前 dm#dm06038@眞定 令 rm#r06164@周法明 ，
 rm#r06540@法尚 之弟也，
 dyn#ch174@隋 末結客，
襲據 dm#dm09118@黄梅 ，
遣族子 rm#xjts26654@孝節 攻 dm#dm07137@蘄春 ，
兄子 rm@紹則 攻 dm#dm02081@安陸 ，
子 rm@紹徳 攻 dm#dm04610@沔陽 ，
皆拔之。

庚午，
以四郡來降。

# p 

壬申，
 rm#r06140@齊善行 以 dm#dm04838@洺 、 dm#dm06025@相 、 dm#dm08945@魏 等州來降。

時 rm#r03028@建徳 餘衆走至 dm#dm04839@洺州 ，
欲立 rm#r03028@建徳 養子爲主，
徵兵以拒 dyn#ch100@唐 ；
又欲剽掠居民，
還向海隅爲盜。

 rm#r06140@善行 獨以爲不可，
曰：
「 dyn#ch174@隋 末喪亂，
故吾屬相聚草野，
苟求生耳。

以 rm#r03028@夏王 之英武，
平定 dm#dm04671@河朔 ，
士馬精強，
一朝爲擒，
易如反掌，
豈非天命有所屬，
非人力所能爭邪！

今喪敗如此，
守亦無成，
逃亦不免，
等爲亡國，
豈可復遺毒於民！

不若委心請命於唐，
必欲得繒帛者，
當盡散府庫之物，
勿復殘民也！」

於是運府庫之帛數十萬段，
置 dm#dm06982@萬春宮 東街，
以散將卒，
凡三晝夜乃畢。

仍布兵守坊巷，
得物者即出，
無得更入人家。

士卒散盡，
然後與僕射 rm#r03452@裴矩 、行臺 rm#r06199@曹旦 、帥其百官，
奉 rm#r03028@建徳 妻 rm@曹氏 及傳國八璽幷破 rm#r00748@宇文化及 所得珍寶請降于 dyn#ch100@唐 。

上以 rm#r06140@善行 爲 rm#r01602@秦王 左二護軍，
仍厚賜之。
# p 

初，
 rm#r03028@竇建徳 之誅 rm#r00748@宇文化及 也，
 dyn#ch174@隋  rm#rz0009@南陽公主 有子曰 rm@禪師 ，
 rm#r03028@建徳 虎賁郎將 rm@於士澄 問之曰：
「 rm#r00748@化及 大逆，
兄弟之子皆當從坐，
若不能捨 rm@禪師 ，
當相爲留之。

」
公主泣曰：
「虎賁既 dyn#ch174@隋室 貴臣，
茲事何須見問。」

 rm#r03028@建徳 竟殺之。

公主尋請爲尼。

及 rm#r03028@建徳 敗，
公主將歸 dm#dm08170@長安 ，
與 rm#r00750@宇文士及 遇於 dm#dm04788@洛陽 ，
 rm#r00750@士及 請與相見，
公主不可。

 rm#r00750@士及 立於戸外，
請復爲夫婦。

公主曰：
「我與君仇家，
今所以不手刃君者，
但謀逆之日，
察君不預知耳。」

訶令速去。

 rm#r00750@士及 固請，
公主怒曰：
「必欲就死，
可相見也。」

 rm#r00750@士及 知不可屈，
乃拜辭而去。
# p 

乙亥，
以 rm#r06164@周法明 爲 dm#dm09115@黄州 總管。

# p 

戊寅，
 rm#r02590@王世充  dm#dm02952@徐州 行臺 rm#r06695@𣏌王世辯 以 dm#dm02948@徐 、 dm#dm02093@宋 等三十八州詣 dm#dm04663@河南道 安撫大使 rm#r00090@任瓌 請降；
 rm#r02590@世充 故地悉平。
# p 

 rm#r03028@竇建徳  dm#dm01088@博州 刺史 rm#r06082@馮士羨 復推 rm#r02450@淮安王神通 爲慰撫 dm#dm02403@山東 使，
徇下三十餘州；
 rm#r03028@建徳 之地悉平。
# p 

己卯，
 dm#dm00485@代州 總管 rm#r05749@李大恩 撃 rm#r03146@苑君璋 ，
破之。
# p 

突厥寇邊，
 rm#r03868@長平靖王叔良 督五將撃之，
 rm#r03868@叔良 中流矢；
師旋，
六月，
戊子，
卒於道。

# p 

戊戌，
 rm#rz0003@孟海公 餘黨 rm#r05782@蒋善合 以 dm#dm07905@鄆州 ，
 rm#r05150@孟噉鬼 以 dm#dm03641@曹州 來降。

 rm#r05150@噉鬼 ，
 rm#rz0003@海公 之從兄也。

# p 

庚子，
 dm#dm05611@營州 人 rm#r05714@石世則 執總管 rm@晉文衍 ，
舉州叛，
奉靺鞨 rm@突地稽 爲主。

# p 

 dm#dm09115@黄州 總管 rm#r06164@周法明 攻 rm#r03260@蕭銑  dm#dm02008@安州 ，
拔之，
獲其總管 rm#r06078@馬貴遷 。


# p 

乙巳，
以右驍衞將軍 rm#r02874@盛彦師 爲 dm#dm02098@宋州 總管，
安撫 dm#dm04660@河南 。

# p 

乙卯，
 dm#dm04893@海州 賊帥 rm@臧君相 以五州來降，
拜 dm#dm04893@海州 總管。

# p 

秋，
七月，
庚申，
 rm#r02590@王世充 行臺 rm#r05622@王弘烈 、 rm#?@王泰 、左僕射 rm#r05878@豆盧行褒 、右僕射 rm#r03326@蘇世長 以 dm#dm07274@襄州 來降。

上與 rm#r05878@行褒 、 rm#r03326@世長 皆有舊，
先是，
屡以書招之，
 rm#r05878@行褒 輒殺使者；
既至 dm#dm08170@長安 ，
上誅 rm#r05878@行褒 而責 rm#r03326@世長 。

 rm#r03326@世長 曰：
「 dyn#ch174@隋 失其鹿，
天下共逐之。

陛下既得之矣，
豈可復忿同獵之徒，
問爭肉之罪乎！」

上笑而釋之，
以爲諫議大夫。

嘗從校獵 dm#dm08924@高陵 ，
大獲禽獸，
上顧羣臣曰：
「今日畋，
樂乎？」
 rm#r03326@世長 對曰：
「陛下遊獵，
薄廢萬機，
不滿十旬，
未足爲樂！」

上變色，
既而笑曰：
「狂態復發邪？」
對曰：
「於臣則狂，
於陛下甚忠。」

嘗侍宴 dm#dm03202@披香殿 ，
酒酣，
謂上曰：
「此殿 rm#rt0779@煬帝 之所爲邪？」
上曰：
「卿諫似直而實多詐，
豈不知此殿朕所爲，
而謂之 rm#rt0779@煬帝 乎？」
對曰：
「臣實不知，
但見其華侈如 dm#dm00612@傾宮 、 dm#dm09074@鹿臺 ，
非興王之所爲故也。

若陛下爲之，
誠非所宜。

臣昔侍陛下於 dm#dm04228@武功 ，
見所居宅僅庇風雨，
當時亦以爲足。

今因隋之宮室，
已極侈矣，
而又増之，
將何以矯其失乎？」
上深然之。
# p 

甲子，
 rm#r01602@秦王世民 至 dm#dm08170@長安 。

 rm#r01602@世民 被黄金甲，
 rm#r01016@齊王元吉 、 rm#r01299@李世勣 等二十五將從其後，
鐵騎萬匹，
前後部鼓吹，
俘 rm#r02590@王世充 、 rm#r03028@竇建徳 及 dyn#ch174@隋 乘輿、御物獻于太廟，
行飮至之禮以饗之。

甲士三萬人
# p 

乙丑，
 rm#xjts00152@高句麗王建武 遣使入貢。

 rm#xjts00152@建武 ，
 rm#xjts00126@元 之弟也。

# p 

上見 rm#r02590@王世充 而數之，
 rm#r02590@世充 曰：
「臣罪固當誅，
然 rm#r01602@秦王 許臣不死。」

丙寅，
詔赦 rm#r02590@世充 爲庶人，
與兄弟子姪處 dm#dm07197@蜀 ；
斬 rm#r03028@竇建徳 於市。徙
# p 

丁卯，
以天下略定，
大赦百姓，
給復一年。

 dm#dm08318@陝 、 dm#dm09198@鼎 、 dm#dm00738@函 、 dm#dm07186@虢 、 dm#dm07179@虞 、 dm#dm06823@芮 六州，
轉輸勞費，
 dm#dm02689@幽州 管内，
久隔寇戎，
竝給復二年。

律、令、格、式，
且用 y@開皇 舊制。

赦令既下，
而 rm#r02588@王 、 rm#r03028@竇 餘黨尚有遠徙者，
治書侍御史 rm#r00709@孫伏伽 上言：
「兵、食可去，
信不可去，
陛下已赦而復徙之，
是自違本心，
使臣民何所憑依。

且 rm#r02590@世充 尚蒙寛宥，
況於餘黨，
所宜縱釋。」

上從之。
# p 

 rm#r02590@王世充 以防夫未備，
置 dm#dm08502@雍州 廨舍。

 rm#r05591@獨孤機 之子 dm#dm02124@定州 刺史 rm@修徳 帥兄弟至其所，
矯稱敕呼 rm#r02590@鄭王 ；
 rm#r02590@世充 與兄 rm#rz0024@世惲 趨出，
 rm@修徳 等殺之。

詔免 rm@修徳 官。

其餘兄弟子姪等於道，
亦以謀反誅。
# p 

 dyn#ch174@隋 末錢弊濫薄，
至裁皮糊紙爲之，
民間不勝其弊。

至是，
初行開元通寶錢，
重二銖四參，
積十錢重一兩，
輕重大小最爲折衷，
遠近便之。

命給事中 rm#r02288@歐陽詢 撰其文幷書，
迴環可讀。
徑八分
# p 

以 rm#r00876@屈突通 爲 dm#dm08324@陝東道 大行臺右僕射，
鎭 dm#dm04788@洛陽 ；
以 rm#r02454@淮陽王道玄 爲 dm#dm04778@洛州 總管。

 rm#r01299@李世勣 父 rm#r05430@蓋 竟無恙而還，
詔復其官爵。

 rm#r03047@竇軌 還 dm#dm05982@益州 。

 rm#r03047@軌 將兵征討，
或經旬月不解甲。

性嚴酷，
將佐有犯，
無貴賤立斬之，
鞭撻吏民，
常流血滿庭，
所部重足屏息。


# p 

癸酉，
置錢監於 dm#dm04761@洛 、 dm#dm00058@幷 、 dm#dm02688@幽 、 dm#dm05982@益 等諸州，
 rm#r01602@秦王世民 、 rm#r01016@齊王元吉 賜三鑪，
 rm#r03424@裴寂 賜一鑪，
聽鑄錢。

自餘敢盜鑄者，
身死，
家口配沒。
# p 

 dm#dm04656@河北 既平，
上以 rm#r03917@陳君賓 爲 dm#dm04839@洺州 刺史。

將軍 rm#r05717@秦武通 等將兵屯 dm#dm04839@洺州 ，
欲使分鎭東方諸州；
又以 rm#r03785@鄭善果 等爲慰撫大使，
就 dm#dm04839@洺州 選補 dm#dm02403@山東 州縣官。
# p 

 rm#r03028@竇建徳 之敗也，
其諸將多盜匿庫物，
及居閭里，
暴横爲民患，
 dyn#ch100@唐 官吏以法繩之，
或加捶撻，
 rm#r03028@建徳 故將皆驚懼不安。

 rm#r06282@高雅賢 、 rm#r05617@王小胡 家在 dm#dm04839@洺州 ，
欲竊其家以逃，
官吏捕之，
 rm#r06282@雅賢 等亡命至 dm#dm07514@貝州 。

會上徵 rm#r03028@建徳 故將 rm#r06240@范願 、 rm#r05770@董康買 、 rm#r05338@曹湛 及 rm#r06282@雅賢 等，
於是 rm#r06240@願 等相謂曰：
「 rm#r02590@王世充 以 dm#dm04788@洛陽 降 dyn#ch100@唐 ，
其將相大臣 rm#r05551@段達 、 rm#r00523@單雄信 等皆夷滅；
吾屬至 dm#dm08170@長安 ，
必不免矣。

吾屬自十年以來，
身經百戰，
當死久矣，
今何惜餘生，
不以之立事。

且 rm#r03028@夏王 得 rm#r02450@淮安王 ，
遇以客禮，
 dyn#ch100@唐 得 rm#r03028@夏王 即殺之。

吾屬皆爲 rm#r03028@夏王 所厚，
今不爲之報仇，
將無以見天下之士！」

乃謀作亂，
卜之，
以 rm#no@劉氏 爲主吉，
因相與之 dm#dm05318@漳南 ，
見 rm#r03028@建徳 故將 rm#r05091@劉雅 ，
以其謀告之。

 rm#r05091@雅 曰：
「天下適安定，
吾將老於耕桑，
不願復起兵！」

衆怒，
且恐泄其謀，
遂殺之。

故 rm#r00337@漢東公劉黒闥 ，
時屏居 dm#dm05318@漳南 ，
諸將往詣之，
告以其謀，
 rm#r00337@黒闥 欣然從之。

 rm#r00337@黒闥 方種蔬，
即殺耕牛與之共飮食定計，
聚衆得百人。

甲戌，
襲 dm#dm05318@漳南縣 據之。

是時，
諸道有事則置行臺尚書省，
無事則罷之。

朝廷聞 rm#r00337@黒闥 作亂，
乃置 dm#dm02404@山東道 行臺於 dm#dm04839@洺州 ，
 dm#dm08945@魏 、 dm#dm00712@冀 、 dm#dm02116@定 、 dm#dm05208@滄 竝置總管府。

丁丑，
以 rm#r02450@淮安王神通 爲 dm#dm02404@山東道 行臺右僕射。
# p 

辛巳，
 dm#dm00032@襃州 道安撫使 rm#r05945@郭行方 攻 rm#r03260@蕭銑  dm#dm07892@鄀州 ，
拔之。

# p 

 rm#rz0003@孟海公 與 rm#r03028@竇建徳 同伏誅，
 dm#dm03154@戴州 刺史 rm#r05150@孟噉鬼 不自安，
挾 rm#rz0003@海公 之子 rm#?@義 以 dm#dm03636@曹 、 dm#dm03154@戴 二州反，
以 dm#dm06257@禹城 令 rm#r05782@蒋善合 爲腹心；
 rm#r05782@善合 與其左右同謀斬之。
# p 

八月，
丙戌朔，
日有食之。
# p 

丁亥，
命太子安撫北邊。
# p 

丁酉，
 rm#r00337@劉黒闥 陷 dm#dm07899@鄃縣 ，
 dm#dm08950@魏州 刺史 rm#r05531@權威 、 dm#dm07514@貝州 刺史 rm#r05328@戴元祥 與戰，
皆敗死，
 rm#r00337@黒闥 悉取其餘衆及器械。

 rm#r03028@竇建徳 舊黨稍稍出歸之，
衆至二千人，
爲壇於 dm#dm05318@漳南 ，
祭 rm#r03028@建徳 ，
告以舉兵之意，
自稱大將軍。

詔發 dm#dm08281@關中 歩騎三千，
使將軍 rm#r05717@秦通 、 dm#dm02124@定州 總管 dm#dm07121@藍田  rm#r01868@李玄通 撃之；
又詔 dm#dm02689@幽州 總管 rm#r03089@李藝 引兵會撃 rm#r00337@黒闥 。
# p 

癸卯，
突厥寇 dm#dm00485@代州 ，
總管 rm#r05749@李大恩 遣行軍總管 rm@王孝基 拒之，
舉軍皆沒。

甲辰，
進圍 dm#dm02502@崞縣 。

乙巳，
 rm@王孝基 自突厥逃歸，
 rm#r05749@李大恩 衆少，
據城自守，
突厥不敢逼，
月餘引去。
# p 

上以南方寇盜尚多，
丙午，
以左武候將軍 rm#r06193@張鎭周 爲 dm#dm04988@淮南道 行軍總管，
大將軍 rm#r06273@陳智略 爲 dm#dm02531@嶺南道 行軍總管，
鎭撫之。
# p 

丁未，
 rm#r00337@劉黒闥 陷 dm#dm04332@歴亭 ，
執屯衞將軍 rm#r02696@王行敏 ，
使之拜，
不可，
遂殺之。
# p 

初，
 dm#dm04788@洛陽 既平，
 rm#r01305@徐圓朗 請降，
拜 dm#dm00663@兗州 總管，
封 rm#r01305@魯郡公 。

 rm#r00337@劉黒闥 作亂，
陰與 rm#r01305@圓朗 通謀。

上使 rm#r02874@葛公盛彦師 安集 dm#dm04660@河南 ，
行至 dm#dm00495@任城 ；
辛亥，
 rm#r01305@圓朗 執 rm#r02874@彦師 ，
舉兵反。

 rm#r00337@黒闥 以 rm#r01305@圓朗 爲大行臺元帥，
 dm#dm00663@兗 、 dm#dm07903@鄆 、 dm#dm08348@陳 、 dm#dm00063@𣏌 、 dm#dm00514@伊 、 dm#dm04761@洛 、 dm#dm03636@曹 、 dm#dm03154@戴 等八州豪右皆應之。

 rm#r01305@圓朗 厚禮 rm#r02874@彦師 ，
使作書與其弟，
令舉 dm#dm07182@虞城 降。

 rm#r02874@彦師 爲書曰：
「吾奉使無状，
爲賊所擒，
爲臣不忠，
誓之以死；
汝善侍老母，
勿以吾爲念。」

 rm#r01305@圓朗 初色動，
而 rm#r02874@彦師 自若。

 rm#r01305@圓朗 乃笑曰：
「 rm#r02874@盛將軍 有壯節，
不可殺也。」

待之如舊。

# p 

 dm#dm04663@河南道 安撫大使 rm#r00090@任瓌 行至 dm#dm02098@宋州 ，
屬 rm#r01305@圓朗 反，
副使 rm#r05461@柳濬 勸 rm#r00090@瓌 退保 dm#dm04541@汴州 ，
 rm#r00090@瓌 笑曰：
「 rm#r05461@柳公 何怯也！」

 rm#r01305@圓朗 又攻陷 dm#dm04087@楚丘 ，
引兵將圍 dm#dm07182@虞城 ，
 rm#r00090@瓌 遣部將 rm#r05221@崔樞 、 rm#r01115@張公謹 自 dm#dm07935@鄢陵 帥諸豪右質子百餘人守 dm#dm07182@虞城 。

 rm#r05461@濬 曰：
「 rm#r05221@樞 與 rm#r01115@公謹 皆 rm#r02590@王世充 將，
諸州質子父兄皆反，
恐必爲變。」

 rm#r00090@瓌 不應。

 rm#r05221@樞 至 dm#dm07182@虞城 ，
分質子使與土人合隊共守城。

賊稍近，
質子有叛者，
 rm#r05221@樞 斬其隊帥。

於是諸隊帥皆懼，
各殺其質子，
 rm#r05221@樞 不禁，
梟其首於門外，
遣使白 rm#r00090@瓌 。

 rm#r00090@瓌 陽怒曰：
「吾所以使與質子倶者，
欲招其父兄耳，
何罪而殺之！」

退謂 rm#r05461@濬 曰：
「吾固知 rm#r05221@崔樞 能辦此也。

縣人既殺質子，
與賊深仇，
吾何患乎！

」
賊攻 dm#dm07182@虞城 ，
果不克而去。
# p 

初，
 rm#r03028@竇建徳 以 dm#dm07967@鄱陽  rm#r05208@崔元遜 爲 dm#dm05016@深州 刺史，
及 rm#r00337@劉黒闥 反，
 rm#r05208@元遜 與其黨數十人謀於野，
伏甲士於車中，
以禾覆其上，
直入聽事，
自禾中呼譟而出，
執刺史 rm#r06256@裴晞 殺之，
傳首 rm#r00337@黒闥 。詐爲農人
# p 

九月，
乙卯，
 dm#dm03312@文登 賊帥 rm@淳于難 請降，
置 dm#dm05863@登州 ，
以 rm@難 爲刺史。

# p 

突厥寇 dm#dm00059@幷州 ，
遣左屯衞大將軍 rm#r03039@竇琮 等撃之。

戊午，
突厥寇 dm#dm01114@原州 ，
遣行軍總管 rm#r00862@尉遲敬徳 等撃之。

# p 

辛酉，
 rm#r01305@徐圓朗 自稱 rm#r01305@魯王 。
# p 

 dyn#ch174@隋 末，
 dm#dm04211@歙州 賊 rm@汪華 據 dm#dm09194@黟 、 dm#dm04210@歙 等五州，
有衆一萬，
自稱 rm@呉王 。

甲子，
遣使來降；
拜 dm#dm04211@歙州 總管。
# p 

 dyn#ch174@隋 末，
 dm#dm02873@弋陽  rm#r02920@盧祖尚 糾合壯士以衞郷里，
部分嚴整，
羣盜畏之。

及 rm#rt0779@煬帝 遇弑，
郷人奉之爲 dm#dm00646@光州 刺史；
時年十九，
奉表於 rm#rt0783@皇泰主 。

及 rm#r02590@王世充 自立，
 rm#r02920@祖尚 來降，
丙子，
以 rm#r02920@祖尚 爲 dm#dm00646@光州 總管。

# p 

己卯，
詔括天下戸口。


# p 

 rm#r01305@徐圓朗 寇 dm#dm05438@濟州 ，
治中 rm#r05107@呉伋論 撃走之。

# p 

癸未，
詔以太常樂工皆前代因罪配沒，
子孫相承，
多歴年所，
良可哀愍；
宜竝蠲除爲民，
且令執事若仕宦入流，
勿更追集。
# p 

甲申，
 dm#dm08619@靈州 總管 rm#r02174@楊師道 撃突厥，
破之。

 rm#r02174@師道 ，
 rm#r02189@恭仁 之弟也。

# p 

詔發 dm#dm02566@巴 、 dm#dm07197@蜀 兵，
以 rm#r02432@趙郡王孝恭 爲 dm#dm06891@荊湘道 行軍總管，
 rm#r02009@李靖 攝行軍長史，
統十二總管，
自 dm#dm01550@夔州 順流東下；
以 rm#r01070@廬江王瑗 爲 dm#dm06895@荊郢道 行軍元帥，
 dm#dm09188@黔州 刺史 rm#r05672@田世康 出 dm#dm07660@辰州道 ，
 dm#dm09115@黄州 總管 rm#r06164@周法明 出 dm#dm01536@夏口道 ，
以撃 rm#r03260@蕭銑 。

是月，
 rm#r02432@孝恭 發 dm#dm01550@夔州 。

時 dm#dm02450@峽江 方漲，
諸將請俟水落進軍，
 rm#r02009@李靖 曰：
「兵貴神速。

今吾兵始集，
 rm#r03260@銑 尚未知，
若乘 dm#dm04475@江 漲，
倐忽抵其城下，
掩其不備，
此必成擒；
不可失也！」

 rm#r02432@孝恭 從之。出襄州道
# p 

 rm#r02450@淮安王神通 將 dm#dm08283@關内 兵至 dm#dm00712@冀州 ，
與 rm#r03089@李藝 兵合。

又發 dm#dm07814@邢 、 dm#dm04838@洺 、 dm#dm06025@相 、 dm#dm08945@魏 、 dm#dm03017@恆 、 dm#dm07617@趙 等兵合五萬餘人，
與 rm#r00337@劉黒闥 戰於 dm#dm08803@饒陽 城南，
布陳十餘里；
 rm#r00337@黒闥 衆少，
依隄單行而陳以當之。

會風雪，
 rm#r02450@神通 乘風撃之，
既而風返，
 rm#r02450@神通 大敗，
士馬軍資失亡三分之二。

 rm#r03089@李藝 居西偏，
撃 rm#r06282@高雅賢 ，
破之，
逐奔數里，
聞大軍不利，
退保 dm#dm00022@藁城 ；
 rm#r00337@黒闥 就撃之，
 rm#r03089@藝 亦敗，
 rm#r03310@薛萬均 、 rm#r03311@萬徹 皆爲所虜，
截髮驅之。

 rm#r03310@萬均 兄弟亡歸，
 rm#r03089@藝 引兵歸 dm#dm02689@幽州 。

 rm#r00337@黒闥 兵勢大振。
# p 

上以 rm#r01602@秦王 功大，
前代官皆不足以稱之，
特置天策上將，
位在王公上。

冬，
十月，
以 rm#r01602@世民 爲天策上將，
領司徒、 dm#dm08324@陝東道 大行臺尚書令，
増邑二萬戸，
仍開天策府，
置官屬。

以 rm#r01016@齊王元吉 爲司空。

 rm#r01602@世民 以海内浸平，
乃開館於宮西，
延四方文學之士，
出教以王府屬 rm#r02033@杜如晦 、記室 rm#r01377@房玄齡 、 rm#r03353@虞世南 、文學 rm#r03473@褚亮 、 rm#r00630@姚思廉 、主簿 rm#r01869@李玄道 、參軍 rm#r03201@蔡允恭 、 rm#r03272@薛元敬 、 rm#r04146@顏相時 、諮議典籤 rm#r05824@蘇勗 、天策府從事中郎 rm#r00047@于志寧 、軍諮祭酒 rm#r03326@蘇世長 、記室 rm#r03296@薛收 、倉曹 rm#r01692@李守素 、國子助教 rm#r03948@陸徳明 ，
 rm#r00680@孔穎達 ，
 dm#dm00581@信都  rm#r03197@蓋文達 、 dm#dm02098@宋州 總管府戸曹 rm#r03511@許敬宗 ，
竝以本官兼文學館學士，
分爲三番，
更日直宿，
供給珍膳，
恩禮優厚。

 rm#r01602@世民 朝謁公事之暇，
輒至館中，
引諸學士討論文籍，
或夜分乃寢。

又使庫直 rm#r03889@閻立本 圖像，
 rm#r03473@褚亮 爲贊，
號十八學士。

士大夫得預其選者，
時人謂之「登 dm#dm05480@瀛州 」。

 rm#r03201@允恭 ，
 rm#r06745@大寶 之弟子；
 rm#r03272@元敬 ，
 rm#r03296@收 之從子；
 rm#r04146@相時 ，
 rm#r04140@師古 之弟；
 rm#r03889@立本 ，
 rm#r06816@毘 之子也。
世民
# p 

初，
 rm#r02033@杜如晦 爲 rm#r01602@秦王 府兵曹參軍，
俄遷 dm#dm08320@陝州 長史。

時府僚多補外官，
 rm#r01602@世民 患之。

 rm#r01377@房玄齡 曰：
「餘人不足惜，
至於 rm#r02033@杜如晦 ，
王佐之才，
大王欲經營四方，
非 rm#r02033@如晦 不可。」

 rm#r01602@世民 驚曰：
「微公言，
幾失之。」

即奏爲府屬。

與 rm#r01377@玄齡 常從 rm#r01602@世民 征伐，
參謀帷幄，
軍中多事，
 rm#r02033@如晦 剖決如流。

 rm#r01602@世民 毎破軍克城，
諸將佐爭取寶貨，
 rm#r01377@玄齡 獨收采人物，
致之幕府。

又將佐有勇略者，
 rm#r01377@玄齡 必與之深相結，
使爲 rm#r01602@世民 盡死力。

 rm#r01602@世民 毎令 rm#r01377@玄齡 入奏事，
上歎曰：
「 rm#r01377@玄齡 爲吾兒陳事，
雖隔千里，
皆如面談。」

# p 

 rm#r01869@李玄道 嘗事 rm#r01704@李密 爲記室，
 rm#r01704@密 敗，
官屬爲 rm#r02590@王世充 所虜，
懼死，
皆達曙不寐。

獨 rm#r01869@玄道 起居自若，
曰：
「死生有命，
非憂可免！」

衆服其識量。


# p 

庚寅，
 rm#r00337@劉黒闥 陷 dm#dm05480@瀛州 ，
殺刺史 rm#r02894@盧士叡 。

 dm#dm07415@觀州 人執刺史 rm#r06032@雷徳備 ，
以城降之。

# p 

辛卯，
 rm#r03260@蕭銑  dm#dm07895@鄂州 刺史 rm#r06035@雷長穎 以 dm#dm08973@魯山 來降。

# p 

 rm#r02432@趙郡王孝恭 帥戰艦二千餘艘東下，
 rm#r03260@蕭銑 以 dm#dm04475@江 水方漲，
殊不爲備；
 rm#r02432@孝恭 等拔其 dm#dm06896@荊門 、 dm#dm02197@宜都 二鎭，
進至 dm#dm01839@夷陵 。

 rm#r03260@銑 將 rm@文士弘 將精兵數萬屯 dm#dm05045@清江 ，
癸巳，
 rm#r02432@孝恭 撃走之，
獲戰艦三百餘艘，
殺溺死者萬計，
追奔至 dm#dm05958@百里洲 。

 rm@士弘 收兵復戰，
又敗之，
進入 dm#dm00871@北江 。

 rm#r03260@銑  dm#dm04490@江州 總管 rm#r05778@蓋彦舉 以 dm#dm00384@五州 來降。

# p 

 dm#dm04376@毛州 刺史 rm#r05895@趙元愷 性嚴急，
下不堪命。

丁卯，
州民 rm#r05774@董燈明 等作亂，
殺 rm#r05895@元愷 以應 rm#r00337@劉黒闥 。


# p 

 rm#r02874@盛彦師 自 rm#r01305@徐圓朗 所逃歸。

 rm#r06234@王薄 因説 dm#dm08642@青 、 dm#dm06953@莱 、 rm#r01704@密 諸州，
皆下之。

# p 

 rm#r03260@蕭銑 之罷兵營農也，
纔留宿衞數千人，
聞唐兵至，
 rm@文士弘 敗，
大懼，
倉猝徵兵，
皆在 dm#dm04475@江 、 dm#dm02525@嶺 之外，
道塗阻遠，
不能遽集，
乃悉見兵出拒戰。

 rm#r02432@孝恭 將撃之，
 rm#r02009@李靖 止之曰：
「彼救敗之師，
策非素立，
勢不能久，
不若且泊南岸，
緩之一日，
彼必分其兵，
或留拒我，
或歸自守，
兵分勢弱，
我乘其懈而撃之，
蔑不勝矣。

今若急之，
彼則倂力死戰，
 dm#dm04085@楚 兵剽鋭，
未易當也。」

 rm#r02432@孝恭 不從，
留 rm#r02009@靖 守營，
自帥鋭師出戰，
果敗走，
趣南岸。

 rm#r03260@銑 衆委舟收掠軍資，
人皆負重，
 rm#r02009@靖 見其衆亂，
縱兵奮撃，
大破之，
乘勝直抵 dm#dm04516@江陵 ，
入其外郭。

又攻水城，
拔之，
大獲舟艦，
 rm#r02009@李靖 使 rm#r02432@孝恭 盡散之 dm#dm04475@江 中。

諸將皆曰：
「破敵所獲，
當藉其用，
奈何棄以資敵？」
 rm#r02009@靖 曰：
「 rm#r03260@蕭銑 之地，
南出 dm#dm02533@嶺表 ，
東距 dm#dm04795@洞庭 。

吾懸軍深入，
若攻城未拔，
援軍四集，
吾表裏受敵，
進退不獲，
雖有舟楫，
將安用之？
今棄舟艦，
使塞 dm#dm04475@江 而下，
援兵見之，
必謂 dm#dm04516@江陵 已破，
未敢輕進，
往來覘伺，
動淹旬月，
吾取之必矣。」

 rm#r03260@銑 援兵見舟艦，
果疑不進。

其 dm#dm00415@交州 刺史 rm#r00029@丘和 、長史 rm#r04217@高士廉 、司馬 rm#r02020@杜之松 將朝 dm#dm04516@江陵 ，
聞 rm#r03260@銑 敗，
悉詣 rm#r02432@孝恭 降。

刺史總管
# p 

 rm#r02432@孝恭 勒兵圍 dm#dm04516@江陵 ，
 rm#r03260@銑 内外阻絶，
問策於中書侍郎 rm#r00879@岑文本 ，
 rm#r00879@文本 勸銑降。

 rm#r03260@銑 乃謂羣下曰：
「天不祚 dyn#ch166@梁 ，
不可復支矣。

若必待力屈，
則百姓蒙患，
奈何以我一人之故陷百姓於塗炭乎！」

乙巳，
 rm#r03260@銑 以太牢告于太廟，
下令開門出降，
守城者皆哭。

 rm#r03260@銑 帥羣臣緦縗布幘詣軍門，
曰：
「當死者唯 rm#r03260@銑 耳，
百姓無罪，
願不殺掠。」

 rm#r02432@孝恭 入據其城，
諸將欲大掠，
 rm#r00879@岑文本 説 rm#r02432@孝恭 曰：
「 dm#dm04475@江 南之民，
自 dyn#ch174@隋 末以來，
困於虐政，
重以羣雄虎爭，
今之存者，
皆鋒鏑之餘，
跂踵延頸以望眞主，
是以 rm#no@蕭氏 君臣、 dm#dm04516@江陵 父老決計歸命，
庶幾有所息肩。

今若縱兵俘掠，
恐自此以南，
無復向化之心矣！」

 rm#r02432@孝恭 稱善，
遽禁止之。

諸將又言：
「 dyn#ch166@梁 之將帥與官軍拒鬬死者，
其罪既深，
請籍沒其家，
以賞將士。」

 rm#r02009@李靖 曰：
「王者之師，
宜使義聲先路。

彼爲其主鬬死，
乃忠臣也，
豈可同叛逆之科籍其家乎！」

於是城中安堵，
秋毫無犯。

南方州縣聞之，
皆望風款附。

 rm#r03260@銑 降數日，
援兵至者十餘萬，
聞 dm#dm04516@江陵 不守，
皆釋甲而降。使士民失望
# p 

 rm#r02432@孝恭 送 rm#r03260@銑 於 dm#dm08170@長安 ，
上數之，
 rm#r03260@銑 曰：
「 dyn#ch174@隋 失其鹿，
天下共逐之。

 rm#r03260@銑 無天命，
故至此；
若以爲罪，
無所逃死！」

竟斬於都市。

詔以 rm#r02432@孝恭 爲 dm#dm06884@荊州 總管；
 rm#r02009@李靖 爲上柱國，
賜爵 rm#r02009@永康縣公 ，
仍使之安撫 dm#dm02527@嶺南 ，
得承制拜授。
# p 

先是，
 rm#r03260@銑 遣黄門侍郎 dm#dm04516@江陵  rm#r00283@劉洎 略地 dm#dm02533@嶺表 ，
得五十餘城，
未還而 rm#r03260@銑 敗，
 rm#r00283@洎 以所得城來降，
除 dm#dm00985@南康州 都督府長史。

# p 

戊申，
 rm#r01305@徐圓朗  dm#dm03463@昌州 治中 rm#r05053@劉善行 以 dm#dm08754@須昌 來降。

# p 

庚戌，
詔 dm#dm08324@陝東道 大行臺尚書省自令、僕至郎中、主事，
品秩皆與京師同，
而員數差少，
 dm#dm02403@山東 行臺及總管府、諸州竝隸焉。

其 dm#dm05982@益州 、 dm#dm07274@襄州 、 dm#dm02403@山東 、 dm#dm04984@淮南 、 dm#dm04656@河北 等道令、僕以下，
各降京師一等，
員數又減焉。

行臺尚書令得承制補署。

其 rm#r01602@秦王 、 rm#r01016@齊王 府官之外，
各置左右六護軍府，
及左右親事帳内府。

# p 

閏月，
乙卯，
上幸 dm#dm06293@稷州 ；
己未，
幸 dm#dm04228@武功 舊墅；
壬戌，
獵于 dm#dm01876@好畤 ，
乙丑，
獵于 dm#dm00323@九嵕 ；
丁卯，
獵于 dm#dm00492@仲山 ；
戊辰，
獵于 dm#dm05044@清水谷 ，
遂幸 dm#dm00119@三原 ；
辛未，
幸 dm#dm01312@周氏陂 ；
壬申，
還 dm#dm08170@長安 。
# p 

十一月，
甲申，
上祀圜丘。

# p 

 rm#r02022@杜伏威 使其將 rm#r02717@王雄誕 撃 rm#r01680@李子通 ，
 rm#r01680@子通 以精兵守 dm#dm05668@獨松嶺 。

 rm#r02717@雄誕 遣其將 rm#r06018@陳當 將千餘人，
乘高據險以逼之，
多張旗幟，
夜則縛炬火於樹，
布滿山澤。

 rm#r01680@子通 懼，
燒營走保 dm#dm03781@杭州 ；
 rm#r02717@雄誕 追撃之，
又敗之於城下。

庚寅，
 rm#r01680@子通 窮蹙請降。

 rm#r02022@伏威 執 rm#r01680@子通 幷其左僕射 rm#r05522@樂伯通 送 dm#dm08170@長安 ；
上釋之。
# p 

先是，
 rm@汪華 據 dm#dm09194@黟 、 dm#dm04210@歙 ，
稱王十餘年，
 rm#r02717@雄誕 還軍撃之，
 rm@華 拒之於 dm#dm03338@新安洞 口，
甲兵甚鋭。

 rm#r02717@雄誕 伏精兵於山谷，
帥羸弱數千犯其陳，
戰纔合，
陽不勝，
走還營，
 rm@華 進攻之，
不能克，
會日暮，
引還，
伏兵已據其 dm#dm04792@洞口 ，
 rm@華 不得入，
窘迫請降。
# p 

 rm@聞人遂安 據 dm#dm02488@崑山 ，
無所屬，
 rm#r02022@伏威 使 rm#r02717@雄誕 撃之，
 rm#r02717@雄誕 以 dm#dm02488@崑山 險隘，
難以力勝，
乃單騎造其城下，
陳國威靈，
示以禍福，
 rm@遂安 感悦，
帥諸將出降。
# p 

於是 rm#r02022@伏威 盡有 dm#dm04984@淮南 、 dm#dm04494@江東 之地，
南至嶺，
東距海。

 rm#r02717@雄誕 以功除 dm#dm04211@歙州 總管，
賜爵 rm#r02717@宜春郡公 。

# p 

壬辰，
 dm#dm03922@林州 總管 rm@劉旻 撃 rm#r06157@劉仚成 ，
大破之。

 rm#r06157@仚成 僅以身免，
部落皆降。

# p 

 rm#r02009@李靖 度嶺，
遣使分道招撫諸州，
所至皆下。

 rm#r03260@蕭銑  dm#dm04001@桂州 總管 rm#r01958@李襲志 帥所部來降，
 rm#r02432@趙郡王孝恭 即以 rm#r01958@襲志 爲 dm#dm04001@桂州 總管，
明年入朝。

以 rm#r02009@李靖 爲 dm#dm02527@嶺南 撫慰大使，
檢校 dm#dm04001@桂州 總管，
引兵下九十六州，
得戸六十餘萬。諸州
# p 

壬寅，
 rm#r00337@劉黒闥 陷 dm#dm02124@定州 ，
執總管 rm#r01868@李玄通 ，
 rm#r00337@黒闥 愛其才，
欲以爲大將，
 rm#r01868@玄通 不可。

故吏有以酒肉饋之者，
 rm#r01868@玄通 曰：
「諸君哀吾幽辱，
幸以酒肉來相開慰，
當爲諸君一醉。」

酒酣，
謂守者曰：
「吾能劍舞，
願假吾刀。」

守者與之，
 rm#r01868@玄通 舞竟太息曰：
「大丈夫受國厚恩，
鎭撫方面，
不能保全所守，
亦何面目視息世間哉！」

即引刀自刺，
潰腹而死。

上聞，
爲之流涕，
拜其子 rm#xjts14765@伏護 爲大將。
# p 

庚戌，
 dm#dm00063@𣏌州 人 rm#r05125@周文舉 殺刺史 rm#r05637@王文矩 ，
以城應 rm#r01305@徐圓朗 。
# p 

 dm#dm02689@幽州 大饑，
 rm#r04273@高開道 許以粟賑之。

 rm#r03089@李藝 遣老弱詣 rm#r04273@開道 就食，
 rm#r04273@開道 皆厚遇之。

 rm#r03089@藝 喜，
於是發民三千人，
車數百乘，
驢馬千餘匹往受粟，
 rm#r04273@開道 悉留之，
告絶於 rm#r03089@藝 ，
復稱 rm#r03089@燕王 ，
北連突厥，
南與 rm#r00337@劉黒闥 相結，
引兵攻 dm#dm03494@易州 不克，
大掠而去。

又遣其將 rm#r05874@謝稜 詐降於 rm#r03089@藝 ，
請兵援接，
 rm#r03089@藝 出兵應之。

將至 dm#dm03107@懷戎 ，
 rm#r05874@稜 襲撃破之。

 rm#r04273@開道 與突厥連兵數入爲寇，
 dm#dm03017@恆 、 dm#dm02116@定 、 dm#dm02688@幽 、 dm#dm03494@易 咸被其患。

# p 

十二月，
乙卯，
 rm#r00337@劉黒闥 陷 dm#dm00712@冀州 ，
殺刺史 rm#rz0050@麹稜 。

 rm#r00337@黒闥 既破 rm#r02450@淮安王神通 ，
移書 dm#dm07617@趙 、 dm#dm08945@魏 ，
故 rm#r03028@竇建徳 將卒爭殺 dyn#ch100@唐 官吏以應 rm#r00337@黒闥 。

庚申，
遣右屯衞大將軍 rm#r05368@義安王孝常 將兵討 rm#r00337@黒闥 。

 rm#r00337@黒闥 將兵數萬進逼 dm#dm02113@宗城 ，
 dm#dm09164@黎州 總管 rm#r01299@李世勣 先屯 dm#dm02113@宗城 ，
棄城走保 dm#dm04839@洺州 。

甲子，
 rm#r00337@黒闥 追撃 rm#r01299@世勣 等，
破之，
殺歩卒五千人，
 rm#r01299@世勣 僅以身免。

丙寅，
 dm#dm04839@洺州 土豪翻城應 rm#r00337@黒闥 。

 rm#r00337@黒闥 於城東南告天及祭 rm#r03028@竇建徳 而後入；
後旬日，
引兵攻拔 dm#dm06029@相州 ，
執刺史 rm#r05329@房晃 ，
右武衞將軍 rm#r01158@張士貴 潰圍走。

 rm#r00337@黒闥 南取 dm#dm09164@黎 、 dm#dm00026@衞 二州，
半歳之間，
盡復 rm#r03028@建徳 舊境。

又遣使北連突厥，
 rm#rz0034@頡利可汗 遣俟斤 rm#xjts11901@宋邪那 帥胡騎從之。

右武衞將軍 rm#r05717@秦武通 ，
 dm#dm04839@洺州 刺史 rm#r03917@陳君賓 、 dm#dm04405@永寧 令 rm#xjts10358@程名振 皆自 dm#dm04656@河北 遁歸 dm#dm08170@長安 。築壇宋末
# p 

丁卯，
命 rm#r01602@秦王世民 、 rm#r01016@齊王元吉 討 rm#r00337@黒闥 。
# p 

昆彌遣使内附。

昆彌，
即 dyn#ch129@漢 之昆明也。

 dm#dm02536@巂州 治中 rm#r05105@吉弘緯 通 dm#dm00971@南寧 ，
至其國説之，
遂來降。

# p 

己巳，
 rm#r00337@劉黒闥 陷 dm#dm07817@邢州 、 dm#dm07623@趙州 ；
庚午，
陷 dm#dm08950@魏州 ，
殺總管 rm#r05572@潘道毅 ；
辛未，
陷 dm#dm06915@莘州 。

# p 

壬申，
徙 rm#r04123@宋王元嘉 爲 rm#r04123@徐王 。
*** 武徳五年
# year 0622
# p 

春，
正月，
 rm#r00337@劉黒闥 自稱 rm#r00337@漢東王 ，
改元 y@天造 ，
定都 dm#dm04839@洺州 。

以 rm#r06240@范願 爲左僕射，
 rm#r05770@董康買 爲兵部尚書 rm#r06282@高雅賢 爲右領軍；
徵 rm#r05651@王琮 爲中書令，
 rm#r05073@劉斌 爲中書侍郎；
 rm#r03028@竇建徳 時文武悉復本位。

其設法行政，
悉師 rm#r03028@建徳 ，
而攻戰勇決過之。
# p 

丙戌，
 dm#dm01220@同安 賊帥 rm#r05552@殷恭邃 以 dm#dm06799@舒州 來降。

# p 

丁亥，
 dm#dm05438@濟州 別駕 rm#r05055@劉伯通 執刺史 rm#r05726@竇務本 ，
以州附 rm#r01305@徐圓朗 。


# p 

庚寅，
 dm#dm03899@東鹽州 治中 rm#r05634@王才藝 殺刺史 rm#r05678@田華 ，
以城應 rm#r00337@劉黒闥 。

# p 

 rm#r01602@秦王世民 軍至 dm#dm05675@獲嘉 ，
 rm#r00337@劉黒闥 棄 dm#dm06029@相州 ，
退保 dm#dm04839@洺州 。

丙申，
 rm#r01602@世民 復取 dm#dm06029@相州 ，
進軍 dm#dm06615@肥郷 ，
列營 dm#dm04841@洺水 之上以逼之。

# p 

 rm#r03260@蕭銑 既敗，
散兵多歸 rm#r02073@林士弘 ，
軍勢復振。

# p 

己酉，
 dm#dm02527@嶺南 俚帥 rm#r05479@楊世略 以 dm#dm02972@循 、 dm#dm05376@潮 二州來降。

# p 

 dyn#ch100@唐 使者 rm#r05655@王義童 下 dm#dm04721@泉 、 dm#dm06059@睦 、 dm#dm02850@建 三州。

# p 

 dm#dm02689@幽州 總管 rm#r03089@李藝 將所部兵數萬會 rm#r01602@秦王世民 討 rm#r00337@劉黒闥 ，
 rm#r00337@黒闥 聞之，
留兵萬人，
使 rm#r06240@范願 守 dm#dm04839@洺州 ，
自將兵拒 rm#r03089@藝 。

夜，
宿 dm#dm04619@沙河 ，
 rm#?@程名振 載鼓六十具，
於城西二里隄上急撃之，
城中地皆震動。

 rm#r06240@范願 驚懼，
馳告 rm#r00337@黒闥 ；
 rm#r00337@黒闥 遽還，
遣其弟 rm#r05058@十善 與行臺 rm#r06183@張君立 將兵一萬撃 rm#r03089@藝 於 dm#dm09202@鼓城 。

壬子，
戰於 dm#dm02955@徐河 ，
 rm#r05058@十善 、 rm#r06183@君立 大敗，
所失亡八千人。
# p 

 dm#dm04841@洺水 人 rm#r05355@李去惑 據城來降，
 rm#r01602@秦王世民 遣 rm#r02607@彭公王君廓 將千五百騎赴之，
入城共守。

二月，
 rm#r00337@劉黒闥 引兵還攻 dm#dm04841@洺水 ，
癸亥，
行至 dm#dm00753@列人 ；
 rm#r01602@秦王世民 使 rm#r02977@秦叔寶 邀撃，
破之。

# p 

 dm#dm07504@豫章 賊帥 rm#r01121@張善安 以 dm#dm07172@虔 、 dm#dm01211@吉 等五州來降，
拜 dm#dm04806@洪州 總管。

# p 

戊辰，
 dm#dm08057@金郷 人 rm#r06029@陽孝誠 叛 rm#r01305@徐圓朗 ，
以城來降。

# p 

己巳，
 rm#r01602@秦王世民 復取 dm#dm07817@邢州 。

辛未，
 dm#dm00405@井州 人 rm#r06080@馮伯讓 以城來降。


# p 

丙子，
 rm#r03089@李藝 取 rm#r00337@劉黒闥  dm#dm02116@定 、 dm#dm04200@欒 、 dm#dm02713@廉 、 dm#dm07617@趙 四州，
獲 rm#r00337@黒闥 尚書 rm@劉希道 ，
引兵與 rm#r01602@秦王世民 會 dm#dm04839@洺州 。

# p 

 rm#r00337@劉黒闥 攻 dm#dm04841@洺水 甚急。

城四旁皆有水，
廣五十餘歩，
 rm#r00337@黒闥 於城東北築二甬道以攻之；
 rm#r01602@世民 三引兵救之，
 rm#r00337@黒闥 拒之，
不得進。

 rm#r01602@世民 恐 rm#r02607@王君廓 不能守，
召諸將謀之，
 rm#r01299@李世勣 曰：
「若甬道達城下，
城必不守。」

行軍總管 rm#r03081@郯勇公羅士信 請代 rm#r02607@君廓 守之。

 rm#r01602@世民 乃登城南高冢，
以旗招 rm#r02607@君廓 ，
 rm#r02607@君廓 帥其徒力戰，
潰圍而出；
 rm#r03081@士信 帥左右二百人乘之入城，
代 rm#r02607@君廓 固守。

 rm#r00337@黒闥 晝夜急攻，
會大雪，
救兵不得往，
凡八日，
丁丑，
城陷。

 rm#r00337@黒闥 素聞其勇，
欲生之，
 rm#r03081@士信 詞色不屈，
乃殺之，
時年二十。


# p 

戊寅，
 dm#dm04541@汴州 總管 rm#r05656@王要漢 攻 rm#r01305@徐圓朗  dm#dm00063@𣏌州 ，
拔之，
獲其將 rm#r05125@周文舉 。

# p 

庚辰，
 dm#dm02813@延州道 行軍總管 rm#r06227@段徳操 撃 rm#r02125@梁師都  dm#dm06083@石堡 城，
 rm#r02125@師都 自將救之；
 rm#r06227@徳操 與戰，
大破之，
 rm#r02125@師都 以十六騎遁去。

上益其兵，
使乘勝進攻 dm#dm01538@夏州 ，
克其東城，
 rm#r02125@師都 以數百人保西城。

會突厥救至，
詔 rm#r06227@徳操 引還。

# p 

辛巳，
 rm#r01602@秦王世民 拔 dm#dm04841@洺水 。

三月，
 rm#r01602@世民 與 rm#r03089@李藝 營於 dm#dm04841@洺水 之南，
分兵屯水北。

 rm#r00337@黒闥 數挑戰，
 rm#r01602@世民 堅壁不應，
別遣奇兵絶其糧道。

壬辰，
 rm#r00337@黒闥 以 rm#r06282@高雅賢 爲左僕射，
軍中高會。

 rm#r01299@李世勣 引兵逼其營，
 rm#r06282@雅賢 乘醉，
單騎逐之，
 rm#r01299@世勣 部將 rm@潘毛 刺之墜馬，
左右繼至，
扶歸，
未至營而卒。

甲午，
諸將復往逼其營，
 rm@潘毛 爲 rm#r05617@王小胡 所擒。

 rm#r00337@黒闥 運糧於 dm#dm00712@冀 、 dm#dm07512@貝 、 dm#dm05208@滄 、 dm#dm05480@瀛 諸州，
水陸倶進，
 rm#?@程名振 以千餘人邀之，
沈其舟，
焚其車。

# p 

 dm#dm02098@宋州 總管 rm#r02874@盛彦師 帥 dm#dm09208@齊州 總管 rm#r06234@王薄 攻 dm#dm08754@須昌 ，
徵軍糧於 dm#dm05373@潭州 ；
刺史 rm#r05428@李義滿 與 rm#r06234@薄 有隙，
閉倉不與。

及 dm#dm08754@須昌 降，
 rm#r02874@彦師 收 rm#r05428@義滿 ，
繋 dm#dm09208@齊州 獄，
詔釋之。

使者未至，
 rm#r05428@義滿 憂憤，
死獄中。

 rm#r06234@薄 還，
過 dm#dm05373@潭州 ，
戊戌夜，
 rm#r05428@義滿 兄子 rm@武意 執 rm#r06234@薄 ，
殺之；
 rm#r02874@彦師 亦坐死。

# p 

上遣使賂突厥 rm#rz0034@頡利可汗 ，
且許結婚。

 rm#rz0034@頡利 乃遣 rm#r02510@漢陽公瓌 、 rm#r03778@鄭元璹 、 rm#r03866@長孫順徳 等還，
庚子，
復遣使來修好，
上亦遣其使者特勒 rm@熱寒 、 rm#r05990@阿史那徳 等還。

 dm#dm00059@幷州 總管 rm#r00187@劉世讓 屯 dm#dm09017@鴈門 ，
 rm#rz0034@頡利 與 rm#r04273@高開道 、 rm#r03146@苑君璋 合衆攻之，
月餘，
乃退。
不克
# p 

甲辰，
以 dyn#ch174@隋  dm#dm00422@交趾 太守 rm#r00029@丘和 爲 dm#dm00415@交州 總管，
 rm#r00029@和 遣司馬 rm#r04217@高士廉 奉表請入朝，
詔許之，
遣其子 rm#r06503@師利 迎之。

# p 

 rm#r01602@秦王世民 與 rm#r00337@劉黒闥 相持六十餘日。

 rm#r00337@黒闥 潛師襲 rm#r01299@李世勣 營，
 rm#r01602@世民 引兵掩其後以救之，
爲 rm#r00337@黒闥 所圍，
 rm#r00862@尉遲敬徳 帥壯士犯圍而入，
 rm#r01602@世民 與 rm#r02398@略陽公道宗 乘之得出。

 rm#r02398@道宗 ，
帝之從子也。

 rm#r01602@世民 度 rm#r00337@黒闥 糧盡，
必來決戰，
乃使人堰 dm#dm04841@洺水 上流，
謂守吏曰：
「待我與賊戰，
乃決之。」

丁未，
 rm#r00337@黒闥 帥歩騎二萬南渡 dm#dm04841@洺水 ，
壓 dyn#ch100@唐 營而陳，
 rm#r01602@世民 自將精騎撃其騎兵，
破之，
乘勝蹂其歩兵。

 rm#r00337@黒闥 帥衆殊死戰，
自午至昏，
戰數合，
 rm#r00337@黒闥 勢不能支。

 rm#r05617@王小胡 謂 rm#r00337@黒闥 曰：
「智力盡矣，
宜早亡去。」

遂與 rm#r00337@黒闥 先遁，
餘衆不知，
猶格戰。

守吏決堰，
 dm#dm04841@洺水 大至，
深丈餘，
 rm#r00337@黒闥 衆大潰，
斬首萬餘級，
溺死數千人，
 rm#r00337@黒闥 與 rm#r06240@范願 等二百騎奔突厥，
 dm#dm02403@山東 悉平。

# p 

 rm#r04273@高開道 寇 dm#dm03494@易州 ，
殺刺史 rm@慕容孝幹 。
# p 

夏，
四月，
己未，
 dyn#ch174@隋 鴻臚卿 rm#r05671@甯長眞 以 dm#dm02305@寧越 、 dm#dm08939@鬱林 之地請降於 rm#r02009@李靖 ，
 dm#dm00412@交 、 dm#dm03057@愛 之道始通；
以 rm#r05671@長眞 爲 dm#dm04208@欽州 總管。

# p 

以 dm#dm01550@夔州 總管 rm#r02432@趙郡王孝恭 爲 dm#dm06884@荊州 總管。
# p 

 rm#r01305@徐圓朗 聞 rm#r00337@劉黒闥 敗，
大懼，
不知所出。

 dm#dm04700@河間 人 rm#r05068@劉復禮 説 rm#r01305@圓朗 曰：
「有 rm#r05054@劉世徹 者，
其才不世出，
名高 dm#dm03804@東夏 ，
且有非常之相，
眞帝王之器。

將軍若自立，
恐終無成；
若迎 rm#r05054@世徹 而奉之，
天下指揮可定。」

 rm#r01305@圓朗 然之，
使 rm#r05068@復禮 迎 rm#r05054@世徹 於 dm#dm04861@浚儀 。

或説 rm#r01305@圓朗 曰：
「將軍爲人所惑，
欲迎 rm#r05054@劉世徹 而奉之，
 rm#r05054@世徹 若得志，
將軍豈有全地乎！

僕不敢遠引前古，
將軍獨不見 rm#rz0067@翟讓 之於 rm#r01704@李密 乎？」
 rm#r01305@圓朗 復以爲然。

 rm#r05054@世徹 至，
已有衆數千人，
頓於城外，
以待 rm#r01305@圓朗 出迎，
 rm#r01305@圓朗 不出，
使人召之。

 rm#r05054@世徹 知事變，
欲亡走，
恐不免，
乃入謁；
 rm#r01305@圓朗 悉奪其兵，
以爲司馬，
使徇 dm#dm07450@譙 、 dm#dm00063@𣏌 二州，
東人素聞其名，
所向皆下，
 rm#r01305@圓朗 遂殺之。
# p 

 rm#r01602@秦王世民 自 dm#dm04656@河北 引兵將撃 rm#r01305@圓朗 ，
會上召之，
使馳傳入朝，
乃以兵屬 rm#r01016@齊王元吉 。

庚申，
 rm#r01602@世民 至 dm#dm08170@長安 ，
上迎之於 dm#dm08193@長樂 。

 rm#r01602@世民 具陳取 rm#r01305@圓朗 形勢，
上復遣之詣 dm#dm09166@黎陽 ，
會大軍趨 dm#dm05443@濟陰 。

# p 

丁卯，
廢 dm#dm02403@山東 行臺。

# p 

壬申，
 dm#dm00485@代州 總管 rm#r05749@定襄王李大恩 爲突厥所殺。

先是，
 rm#r05749@大恩 奏稱突厥饑饉，
 dm#dm08829@馬邑 可取，
詔殿内少監 rm@獨孤晟 將兵與 rm#r05749@大恩 共撃 rm#r03146@苑君璋 ，
期以二月會 dm#dm08829@馬邑 ；
失期不至，
 rm#r05749@大恩 不能獨進，
頓兵 dm#dm03332@新城 。

 rm#rz0034@頡利可汗 遣數萬騎與 rm#r00337@劉黒闥 共圍 rm#r05749@大恩 ，
上遣右驍衞大將軍 rm#r02014@李高遷 救之。

未至，
 rm#r05749@大恩 糧盡，
夜遁，
突厥邀之，
衆潰而死，
上惜之。

 rm@獨孤晟 坐減死徙邊。
# p 

丙子，
行臺民部尚書 rm#r05100@史萬寶 攻 rm#r01305@徐圓朗  dm#dm08351@陳州 ，
拔之。

# p 

戊寅，
 dm#dm02733@廣州 賊帥 rm#r05950@鄧文進 、 dyn#ch174@隋  dm#dm01198@合浦 太守 rm#r05667@甯宣 、 dm#dm03432@日南 太守 rm#r05401@李晙 竝來降。

# p 

五月，
庚寅，
 dm#dm05769@瓜州 土豪 rm#r05621@王幹 斬 rm#r05882@賀拔行威 以降，
 dm#dm05769@瓜州 平。

# p 

突厥寇 dm#dm03000@忻州 ，
 rm#r02014@李高遷 撃破之。
# p 

六月，
辛亥，
 rm#r00337@劉黒闥 引突厥寇 dm#dm02403@山東 ，
詔 rm#r03089@燕郡王李藝 撃之。

# p 

癸丑，
吐谷渾寇 dm#dm04823@洮 、 dm#dm03439@旭 、 dm#dm05855@疊 三州，
 dm#dm02437@岷州 總管 rm#r05439@李長卿 撃破之。

# p 

乙卯，
遣 rm#r02450@淮安王神通 撃 rm#r01305@徐圓朗 。
# p 

丁卯，
 rm#r00337@劉黒闥 引突厥寇 dm#dm02124@定州 。
# p 

秋，
七月，
甲申，
爲 rm#r01602@秦王世民 營 dm#dm02887@弘義宮 ，
使居之。

 rm#r01602@世民 撃 rm#r01305@徐圓朗 ，
下十餘城，
聲震 dm#dm04981@淮 、 dm#dm04727@泗 ，
 rm#r02022@杜伏威 懼，
請入朝。

 rm#r01602@世民 以 dm#dm04981@淮 、 dm#dm05433@濟 之間略定，
使 rm#r02450@淮安王神通 、行軍總管 rm#r00090@任瓌 、 rm#r01299@李世勣 攻 rm#r01305@圓朗 ；
乙酉，
班師。
# p 

丁亥，
 rm#r02022@杜伏威 入朝，
延升御榻，
拜太子太保，
仍兼行臺尚書令，
留 dm#dm08170@長安 ，
位在 rm#r01016@齊王元吉 上，
以寵異之。

以 rm#r03891@闞稜 爲左領軍將軍。

# p 

 rm#r01680@李子通 謂 rm#r05522@樂伯通 曰：
「 rm#r02022@伏威 既來，
 dm#dm04494@江東 未定，
我往收舊兵，
可以立大功。」

遂相與亡至 dm#dm07126@藍田關 ，
爲吏所獲，
倶伏誅。
# p 

 rm#r00337@劉黒闥 至 dm#dm02124@定州 ，
其故將 rm#r05338@曹湛 、 rm#r05770@董康買 亡命在 dm#dm08988@鮮虞 ，
復聚兵應之。

甲午，
以 rm#r02454@淮陽王道玄 爲 dm#dm04658@河北道 行軍總管以討之。
# p 

丙申，
 dm#dm07762@遷州 人 rm#r05949@鄧士政 執刺史 rm#r05398@李敬昂 以反。


# p 

丁酉，
 dyn#ch174@隋  dm#dm05302@漢陽 太守 rm#r04199@馮盎 承 rm#r02009@李靖 檄，
帥所部來降，
以其地爲 dm#dm08893@高 、 dm#dm06496@羅 、 dm#dm03504@春 、 dm#dm05867@白 、 dm#dm02498@崖 、 dm#dm00623@儋 、 dm#dm03922@林 、 dm#dm03227@振 八州，
以 rm#r04199@盎 爲 dm#dm08893@高州 總管，
封 rm#r04199@耿國公 。

先是，
或説 rm#r04199@盎 曰：
「 dyn#ch100@唐 始定中原，
未能及遠，
公所領二十州地已廣於 rm#r05893@趙佗 ，
宜自稱 rm#no@南越王 。」

 rm#r04199@盎 曰：
「吾家居此五世矣，
爲牧伯者不出吾門，
富貴極矣，
常懼不克負荷，
爲先人羞，
敢效趙佗自王一方乎！」

遂來降。

於是 dm#dm02527@嶺南 悉平。
# p 

八月，
辛亥，
以 dm#dm04838@洺 、 dm#dm06880@荊 、 dm#dm00412@交 、 dm#dm00058@幷 、 dm#dm02688@幽 五州爲大總管府。

# p 

改葬 rm#rt0779@隋煬帝 於 dm#dm03246@揚州  dm#dm08583@雷塘 。

# p 

甲戌，
吐谷渾寇 dm#dm02437@岷州 ，
敗總管 rm#r05439@李長卿 。

詔 dm#dm05982@益州 行臺右僕射 rm#r03047@竇軌 、 dm#dm05113@渭州 刺史 rm@且洛生 救之。


# p 

乙卯，
突厥 rm#rz0034@頡利可汗 寇邊，
遣左武衞將軍 rm#r06227@段徳操 、 dm#dm08566@雲州 總管 rm#r03714@李子和 將兵拒之。

 rm#r03714@子和 本姓 rm#r03714@郭 ，
以討 rm#r00337@劉黒闥 有功，
賜姓。

丙辰，
 rm#rz0034@頡利 十五萬騎入 dm#dm09017@鴈門 ，
己未，
寇 dm#dm00059@幷州 ，
別遣兵寇 dm#dm01114@原州 ；
庚子，
命太子出 dm#dm02690@幽州道 ，
 rm#r01602@秦王世民 出 dm#dm06280@秦州道 以禦之。

 rm#r03714@李子和 趨 dm#dm08542@雲中 ，
掩撃可汗，
 rm#r06227@段徳操 趨 dm#dm01538@夏州 ，
邀其歸路。
子申
# p 

辛酉，
上謂羣臣曰：
「突厥入寇而復求和，
和與戰孰利？」
太常卿 rm#r03778@鄭元璹 曰：
「戰則怨深，
不如和利。」

中書令 rm#r00851@封徳彞 曰：
「突厥恃犬羊之衆，
有輕 dm#dm00255@中國 之意，
若不戰而和，
示之以弱，
明年將復來。

臣愚以爲不如撃之，
既勝而後與和，
則恩威兼著矣！」

上從之。
# p 

己巳，
 dm#dm00059@幷州 大總管 rm#r03482@襄邑王神符 破突厥於 dm#dm04562@汾東 ；
 dm#dm04561@汾州 刺史 rm#r05793@蕭顗 破突厥，
斬首五千餘級。
# p 

吐谷渾寇 dm#dm04823@洮州 ，
遣 dm#dm04255@武州 刺史 rm@賀亮 禦之。
寇陷拔
# p 

丙子，
突厥寇 dm#dm02713@廉州 ；
戊寅，
陷 dm#dm01701@大震關 。

上遣 rm#r03778@鄭元璹 詣 rm#rz0034@頡利 。

是時，
突厥精騎數十萬，
自 dm#dm00463@介休 至 dm#dm03544@晉州 ，
數百里間，
填溢山谷。

 rm#r03778@元璹 見 rm#rz0034@頡利 ，
責以負約，
與相辨詰，
 rm#rz0034@頡利 頗慚。

 rm#r03778@元璹 因説 rm#rz0034@頡利 曰：
「 dyn#ch100@唐 與突厥，
風俗不同，
突厥雖得 dyn#ch100@唐 地，
不能居也。

今虜掠所得，
皆入國人，
於可汗何有？
不如旋師，
復脩和親，
可無跋渉之勞，
坐受金幣，
又皆入可汗府庫，
孰與棄昆弟積年之歡，
而結子孫無窮之怨乎！」

 rm#rz0034@頡利 悦，
引兵還。

 rm#r03778@元璹 自 y@義寧 以來，
五使突厥，
幾死者數焉。


# p 

九月，
癸巳，
 dm#dm00415@交州 刺史 rm#r05530@權士通 、 dm#dm02882@弘州 總管 rm#r00758@宇文歆 、 dm#dm08619@靈州 總管 rm#r02174@楊師道 撃突厥於 dm#dm00146@三觀山 ，
破之。

乙未，
太子班師。

丙申，
 rm#r00758@宇文歆 邀突厥於 dm#dm02462@崇崗鎭 ，
大破之，
斬首千餘級。

壬寅，
 dm#dm02124@定州 總管 rm@雙士洛 撃突厥於 dm#dm03021@恆山 之南，
丙午，
領軍將軍 rm#r05178@安興貴 撃突厥於 dm#dm05794@甘州 ，
皆破之。

# p 

 rm#r00337@劉黒闥 陷 dm#dm05480@瀛州 ，
殺刺史 rm#r06071@馬匡武 。

 dm#dm09056@鹽州 人 rm#r06072@馬君徳 以城叛附 rm#r00337@黒闥 。

 rm#r04273@高開道 寇 dm#dm07211@蠡州 。

# p 

冬，
十月，
己酉，
詔 rm#r01016@齊王元吉 討 rm#r00337@劉黒闥 於 dm#dm02403@山東 。

壬子，
以 rm#r01016@元吉 爲領軍大將軍、 dm#dm00059@幷州 大總管。

癸丑，
 dm#dm07514@貝州 刺史 rm#r05859@許善護 與 rm#r00337@黒闥 弟 rm#r05058@十善 戰於 dm#dm07899@鄃縣 ，
 rm#r05859@善護 全軍皆沒。

甲寅，
右武候將軍 rm#r05466@桑顯和 撃 rm#r00337@黒闥 於 dm#dm03572@晏城 ，
破之。

 dm#dm07415@觀州 刺史 rm#r05077@劉會 以城叛附 rm#r00337@黒闥 。

# p 

 dm#*dm01868@契丹 寇 dm#dm00855@北平 。

# p 

甲子，
以 rm#r01602@秦王世民 領左、右十二衞大將軍。

# p 

乙丑，
行軍總管 rm#r02454@淮陽壯王道玄 與 rm#r00337@劉黒闥 戰于 dm#dm00208@下博 ，
軍敗，
爲 rm#r00337@黒闥 所殺。

時 rm#r02454@道玄 將兵三萬，
與副將 rm#r05100@史萬寶 不協；
 rm#r02454@道玄 帥輕騎先出犯陳，
使 rm#r05100@萬寶 將大軍繼之。

 rm#r05100@萬寶 擁兵不進，
謂所親曰：
「我奉手敕云，
 rm#r02454@淮陽 小兒，
軍事皆委老夫。

今王輕脱妄進，
若與之倶，
必同敗沒，
不如以王餌賊，
王敗，
賊必爭進，
我堅陳以待之，
破之必矣。」

由是 rm#r02454@道玄 獨進敗沒。

 rm#r05100@萬寶 勒兵將戰，
士卒皆無鬬志，
軍遂大潰，
 rm#r05100@萬寶 逃歸。

 rm#r02454@道玄 數從 rm#r01602@秦王世民 征伐，
死時年十九，
 rm#r01602@世民 深惜之，
謂人曰：
「 rm#r02454@道玄 常從吾征伐，
見吾深入賊陳，
心慕效之，
以至於此。」

爲之流涕。

 rm#r01602@世民 自起兵以來，
前後數十戰，
常身先士卒，
輕騎深入，
雖屡危殆而未嘗爲矢刃所傷。

# p 

 rm#r02073@林士弘 遣其弟 rm#?@鄱陽王藥師 攻 dm#dm02972@循州 ，
刺史 rm#r05510@楊略 與戰，
斬之，
其將 rm#r05633@王戎 以 dm#dm00999@南昌州 降。

 rm#r02073@士弘 懼，
己巳，
請降。

尋復走保 dm#dm02027@安成 山洞，
 dm#dm07243@袁州 人相聚應之；
 dm#dm04806@洪州 總管 rm@若干則 遣兵撃破之。

會 rm#r02073@士弘 死，
其衆遂散。

# p 

 rm#r02454@淮陽王道玄 之敗也，
 dm#dm02403@山東 震駭，
 dm#dm04839@洺州 總管 rm#r01070@廬江王瑗 棄城西走，
州縣皆叛附於 rm#r00337@黒闥 ，
旬日間，
 rm#r00337@黒闥 盡復故地，
乙亥，
進據 dm#dm04839@洺州 。

十一月，
庚辰，
 dm#dm05209@滄州 刺史 rm#r05723@程大買 爲 rm#r00337@黒闥 所迫，
棄城走。

 rm#r01016@齊王元吉 畏 rm#r00337@黒闥 兵強，
不敢進。
# p 

上之起兵 dm#dm03567@晉陽 也，
皆 rm#r01602@秦王世民 之謀，
上謂 rm#r01602@世民 曰：
「若事成，
則天下皆汝所致，
當以汝爲太子。」

 rm#r01602@世民 拜且辭。

及爲 rm#r04258@唐王 ，
將佐亦請以 rm#r01602@世民 爲世子，
上將立之，
世民固辭而止。

 rm#r01078@太子建成 ，
性寛簡，
喜酒色遊畋；
 rm#r01016@齊王元吉 ，
多過失；
皆無寵於上。

 rm#r01602@世民 功名日盛，
上常有意以代 rm#r01078@建成 ，
 rm#r01078@建成 内不自安，
乃與 rm#r01016@元吉 協謀，
共傾 rm#r01602@世民 ，
各引樹黨友。
# p 

上晩年多内寵，
小王且二十人，
其母競交結諸長子以自固。

 rm#r01078@建成 與 rm#r01016@元吉 曲意事諸𡚱嬪，
諂諛賂遺，
無所不至，
以求媚於上。

或言蒸於 rm#r05260@張婕妤 、 rm@尹徳𡚱 ，
宮禁深祕，
莫能明也。

是時，
東宮、諸王公、𡚱主之家及後宮親戚横 dm#dm08170@長安 中，
恣爲非法，
有司不敢詰。

 rm#r01602@世民 居 dm#dm03185@承乾殿 ，
 rm#r01016@元吉 居 dm#dm04266@武徳殿 後院，
與上臺、東宮晝夜通行，
無復禁限。

太子、二王出入上臺，
皆乘馬、攜弓刀雜物，
相遇如家人禮。

太子令、 rm#r01602@秦 ‧ rm#r01016@齊王 教與詔敕竝行，
有司莫知所從，
唯據得之先後爲定。

 rm#r01602@世民 獨不奉事諸𡚱嬪，
諸𡚱嬪爭譽 rm#r01078@建成 、 rm#r01016@元吉 而短 rm#r01602@世民 。
奪人田宅
# p 

 rm#r01602@世民 平 dm#dm04788@洛陽 ，
上使貴𡚱等數人詣 dm#dm04788@洛陽 選閲 dyn#ch174@隋 宮人及收府庫珍物。

貴𡚱等私從 rm#r01602@世民 求寶貨及爲親屬求官，
 rm#r01602@世民 曰：
「寶貨皆已籍奏，
官當授賢才有功者。」

皆不許，
由是益怨。

 rm#r01602@世民 以 rm#r02450@淮安王神通 有功，
給田數十頃。

 rm#r05260@張婕妤 之父因婕妤求之於上，
上手敕賜之，
 rm#r02450@神通 以教給在先，
不與。

婕妤訴於上曰：
「敕賜妾父田，
 rm#r01602@秦王 奪之以與 rm#r02450@神通 。」

上遂發怒，
責 rm#r01602@世民 曰：
「我手敕不如汝教邪！」

他日，
謂左僕射 rm#r03424@裴寂 曰：
「此兒久典兵在外，
爲書生所教，
非復昔日子也。」

 rm@尹徳𡚱 父 rm@阿鼠 驕横，
 rm#r01602@秦王 府屬 rm#r02033@杜如晦 過其門，
 rm@阿鼠 家童數人曳 rm#r02033@如晦 墜馬，
敺之，
折一指，
曰：
「汝何人，
敢過我門而不下馬！」

 rm@阿鼠 恐 rm#r01602@世民 訴於上，
先使 rm@徳𡚱 奏云：
「 rm#r01602@秦王 左右陵暴妾家。」

上復怒責 rm#r01602@世民 曰：
「我𡚱嬪家猶爲汝左右所陵，
況小民乎！」

 rm#r01602@世民 深自辯析，
上終不信。
# p 

 rm#r01602@世民 毎侍宴宮中，
對諸𡚱嬪，
思 rm#r03010@太穆皇后 早終，
不得見上有天下，
或歔欷流涕，
上顧之不樂。

諸𡚱嬪因密共譖 rm#r01602@世民 曰：
「海内幸無事，
陛下春秋高，
唯宜相娯樂，
而 rm#r01602@秦王 毎獨涕泣，
正是憎疾妾等，
陛下萬歳後，
妾母子必不爲 rm#r01602@秦王 所容，
無孑遺矣！」

因相與泣，
且曰：
「皇太子仁孝，
陛下以妾母子屬之，
必能保全。」

上爲之愴然。

由是無易太子意，
待 rm#r01602@世民 浸疏，
而 rm#r01078@建成 、 rm#r01016@元吉 日親矣。

# p 

太子中允 rm#r02672@王珪 、洗馬 rm#r04294@魏徵 説太子曰：
「 rm#r01602@秦王 功蓋天下，
中外歸心；
殿下但以年長位居東宮，
無大功以鎭服海内。

今 rm#r00337@劉黒闥 散亡之餘，
衆不滿萬，
資糧匱乏，
以大軍臨之，
勢如拉朽，
殿下宜自撃之以取功名，
因結納 dm#dm02403@山東 豪傑，
庶可自安。」

太子乃請行於上，
上許之。

 rm#r02672@珪 ，
 rm#r06713@頍 之兄子也。

甲申，
詔 rm#r01078@太子建成 將兵討 rm#r00337@黒闥 ，
其 dm#dm08324@陝東道 大行臺及 dm#dm02404@山東道 行軍元帥、 dm#dm04660@河南 ‧ dm#dm04656@河北 諸州竝受 rm#r01078@建成 處分，
得以便宜從事。


# p 

乙酉，
封宗室 rm#r02398@略陽公道宗 等十八人爲郡王。

 rm#r02398@道宗 ，
 rm#r02454@道玄 從父弟也，
爲 dm#dm08619@靈州 總管，
 rm#r02125@梁師都 遣弟 rm@洛兒 引突厥數萬圍之，
 rm#r02398@道宗 乘間出撃，
大破之。

突厥與 rm#r02125@師都 相結，
遣其 rm#xjts24877@郁射設 入居故 dm#dm00372@五原 ，
 rm#r02398@道宗 逐出之，
斥地千餘里。

上以 rm#r02398@道宗 武幹如 dyn#ch134@魏  rm@任城王彰 ，
乃立爲 rm#r02398@任城郡王 。
# p 

丙申，
上幸 dm#dm02174@宜州 。

# p 

己亥，
 rm#r01016@齊王元吉 遣兵撃 rm#r05058@劉十善 於 dm#dm08950@魏州 ，
破之。
# p 

癸卯，
上校獵於 dm#dm02268@富平 。

# p 

 rm#r00337@劉黒闥 擁兵而南，
自 dm#dm06029@相州 以北州縣皆附之，
唯 dm#dm08950@魏州 總管 rm#r05677@田留安 勒兵拒守。

 rm#r00337@黒闥 攻之，
不下，
引兵南拔 dm#dm00634@元城 ，
復還攻之。

# p 

十二月，
庚戌，
立宗室 rm@孝友 等八人爲郡王。

 rm@孝友 ，
 rm#r02450@神通 之子也。
# p 

丙辰，
上校獵於 dm#dm06941@華池 。


# p 

戊午，
 rm#r00337@劉黒闥 陷 dm#dm03023@恆州 ，
殺刺史 rm#r05606@王公政 。

# p 

庚申，
車駕至 dm#dm08170@長安 。
# p 

癸亥，
 dm#dm02689@幽州 大總管 rm#r03089@李藝 復 dm#dm02713@廉 、 dm#dm02116@定 二州。
# p 

甲子，
 rm#r05677@田留安 撃 rm#r00337@劉黒闥 ，
破之，
獲其 dm#dm06915@莘州 刺史 rm#r05153@孟柱 ，
降將卒六千人。

是時，
 dm#dm02403@山東 豪傑多殺長吏以應 rm#r00337@黒闥 ，
上下相猜，
人益離怨；
 rm#r05677@留安 待吏民獨坦然無疑，
白事者無問親疏，
皆聽直入臥内，
毎謂吏民曰：
「吾與爾曹倶爲國禦賊，
固宜同心協力，
必欲棄順從逆者，
但自斬吾首去。」

吏民皆相戒曰：
「 rm#r05677@田公 推至誠以待人，
當共竭死力報之，
必不可負。」

有 rm#r05754@苑竹林 者，
本 rm#r00337@黒闥 之黨，
潛有異志。

 rm#r05677@留安 知之，
不發其事，
引置左右，
委以管鑰；
 rm#r05754@竹林 感激，
遂更歸心，
卒收其用。

以功進封 rm#r05677@道國公 。
# p 

乙丑，
 dm#dm00059@幷州 刺史 rm#r05324@成仁重 撃 rm#r06240@范願 ，
破之。

# p 

 rm#r00337@劉黒闥 攻 dm#dm08950@魏州 未下，
太子 rm#r01078@建成 、 rm#r01016@齊王元吉 大軍至 dm#dm03470@昌樂 ，
 rm#r00337@黒闥 引兵拒之，
再陳，
皆不戰而罷。

 rm#r04294@魏徵 言於太子曰：
「前破 rm#r00337@黒闥 ，
其將帥皆懸名處死，
妻子係虜；
故 rm#r01016@齊王 之來，
雖有詔書赦其黨與之罪，
皆莫之信。

今宜悉解其囚俘，
慰諭遣之，
則可坐視離散矣！」

太子從之。

 rm#r00337@黒闥 食盡，
衆多亡，
或縛其渠帥以降。

 rm#r00337@黒闥 恐城中兵出，
與大軍表裏撃之，
遂夜遁。

至 dm#dm08796@館陶 ，
 dm#dm04437@永濟橋 未成，
不得度。

壬申，
太子、 rm#r01016@齊王 以大軍至，
 rm#r00337@黒闥 使 rm#r05617@王小胡 背水而陳，
自視作橋成，
即過橋西，
衆遂大潰，
捨仗來降。

大軍度橋追 rm#r00337@黒闥 ，
度者纔千餘騎，
橋壞，
由是 rm#r00337@黒闥 得與數百騎亡去。

# p 

上以 dyn#ch174@隋 末戰士多沒於 dm#dm08934@高麗 ，
 y@是歳 賜，
 rm@高麗王建武 書，
使悉遣還；
亦使州縣索 dm#dm08934@高麗 人在中土者，
遣歸其國。

 rm@建武 奉詔，
遣還 dm#dm00255@中國 民前後以萬數。
*** 六年
# year 0623
# p 

春，
正月，
己卯，
 rm#r00337@劉黒闥 所署 dm#dm08799@饒州 刺史 rm#r05867@諸葛徳威 執 rm#r00337@黒闥 ，
舉城降。

時太子遣騎將 rm#r00246@劉弘基 追 rm#r00337@黒闥 ，
 rm#r00337@黒闥 爲官軍所迫，
奔走不得休息，
至 dm#dm08803@饒陽 ，
從者纔百餘人，
餒甚。

 rm#r05867@徳威 出迎，
延 rm#r00337@黒闥 入城，
 rm#r00337@黒闥 不可；
 rm#r05867@徳威 涕泣固請，
 rm#r00337@黒闥 乃從之。

至城旁市中憩止，
 rm#r05867@徳威 饋之食；
食未畢，
 rm#r05867@徳威 勒兵執之，
送詣太子，
幷其弟 rm#r05058@十善 斬於 dm#dm04839@洺州 。

 rm#r00337@黒闥 臨刑歎曰：
「我幸在家鉏菜，
爲 rm#r06282@高雅賢 輩所誤至此！」

# p 

壬午，
 dm#dm02536@巂州 人 rm#r05635@王摩沙 舉兵，
自稱元帥，
改元 y@進通 ，
遣驃騎將軍 rm#r05001@衞彦 討之。

# p 

庚子，
以 rm#r02022@呉王杜伏威 爲太保。

# p 

二月，
庚戌，
上幸 dm#dm08874@驪山 温湯；
甲寅，
還宮。
# p 

 rm#r01038@平陽昭公主 薨。

戊午，
葬公主，
詔加前後部鼓吹、班劍四十人，
武賁甲卒。

太常奏：
「禮，
婦人無鼓吹。」

上曰：
「鼓吹，
軍樂也。

公主親執金鼓，
興義兵以輔成大業，
豈與常婦人比乎！」

# p 

丙寅，
 rm#r01305@徐圓朗 窮蹙，
與數騎棄城走，
爲野人所殺，
其地悉平。
# p 

 rm@林邑王梵志 遣使入貢。

初，
 dyn#ch174@隋 人破 dm#dm03927@林邑 ，
分其地爲三郡。

及中原喪亂，
 dm#dm03927@林邑 復國，
至是始入貢。
# p 

 dm#dm02689@幽州 總管 rm#r03089@李藝 請入朝；
庚午，
以 rm#r03089@藝 爲左翊衞大將軍。


# p 

廢參旗等十二軍。

# p 

三月，
癸未，
 rm#r04273@高開道 掠 dm#dm03301@文安 、 dm#dm08971@魯城 ，
驃騎將軍 rm@平善政 邀撃，
破之。

# p 

庚子，
 rm#r02125@梁師都 將 rm#r05880@賀遂 、 rm#r05741@索同 以所部十二州來降。

# p 

乙巳，
前 dm#dm04806@洪州 總管 rm#r01121@張善安 反，
遣 dm#dm06799@舒州 總管 rm#r06193@張鎭周 等撃之。


# p 

夏，
四月，
吐谷渾寇 dm#dm06832@芳州 ，
刺史 rm#r05331@房當樹 奔 dm#dm03903@松州 。

# p 

 rm#r01121@張善安 陷 dm#dm01954@孫州 ，
執總管 rm#r05633@王戎 而去。
# p 

乙丑，
 dm#dm07927@鄜州道 行軍總管 rm#r06227@段徳操 撃 rm#r02125@梁師都 ，
至 dm#dm01538@夏州 ，
俘其民畜而還。


# p 

丙寅，
吐谷渾寇 dm#dm04823@洮 、 dm#dm02437@岷 二州。

# p 

丁卯，
 dm#dm00979@南州 刺史 rm#r06144@龐孝恭 、 dm#dm01059@南越州 民 rm#r05670@甯道明 、 dm#dm08893@高州 首領 rm#r06089@馮暄 倶反，
陷 dm#dm01059@南越州 ，
進攻 dm#dm01901@姜州 ；
 dm#dm01190@合州 刺史 rm#r05669@甯純 引兵救之。

# p 

壬申，
立皇子 rm#r03988@元軌 爲 rm#r03988@蜀王 、 rm#r03356@鳳 爲 rm#r03356@豳王 、 rm#r03674@元慶 爲 rm#r03674@漢王 。

# p 

癸酉，
以 rm#r03424@裴寂 爲左僕射，
 rm#r03249@蕭瑀 爲右僕射，
 rm#r02189@楊恭仁 爲吏部尚書兼中書令，
 rm#r00851@封徳彞 爲中書令。
# p 

五月，
庚辰，
遣 dm#dm02420@岐州 刺史 rm#r02112@柴紹 救 dm#dm02437@岷州 。

# p 

庚寅，
吐谷渾及黨項寇 dm#dm04668@河州 ，
刺史 rm#r05702@盧士良 撃破之。
# p 

丙申，
 rm#r02125@梁師都 將 rm#r05922@辛獠兒 引突厥寇 dm#dm03922@林州 。

# p 

戊戌，
 rm#r05753@苑君彰 將 rm#r06279@高滿政 寇 dm#dm00485@代州 ，
驃騎將軍 rm@林寶言 撃走之。
林李
# p 

癸卯，
 rm#r04273@高開道 引奚騎寇 dm#dm02689@幽州 ，
長史 rm#?@王詵 撃破之。

 rm#r00337@劉黒闥 之叛也，
 rm@突地稽 引兵助 dyn#ch100@唐 ，
徙其部落於 dm#dm02689@幽州 之 dm#dm03465@昌平城 ；
 rm#r04273@高開道 引突厥寇 dm#dm02689@幽州 ，
 rm@突地稽 將兵邀撃，
破之。
# p 

六月，
戊午，
 rm#r06279@高滿政 以 dm#dm08829@馬邑 來降。

先是，
前 dm#dm00059@幷州 總管 rm#r00187@劉世讓 除 dm#dm02733@廣州 總管，
將之官，
上問以備邊之策，
 rm#r00187@世讓 對曰：
「突厥比數爲寇，
良以 dm#dm08829@馬邑 爲之中頓故也。

請以勇將戍 dm#dm02501@崞城 ，
多貯金帛，
募有降者厚賞之，
數出騎兵掠其城下，
蹂其禾稼，
敗其生業，
不出歳餘，
彼無所食，
必降矣。」

上然其計，
曰：
「非公，
誰爲勇將！」

即命 rm#r00187@世讓 戍 dm#dm02501@崞城 ，
 dm#dm08829@馬邑 病之。

是時，
 dm#dm08829@馬邑 人多不願屬突厥，
上復遣人招諭 rm#r03146@苑君璋 。

 rm#r06279@高滿政 説 rm#r03146@苑君璋 盡殺突厥戍兵降 dyn#ch100@唐 ，
 rm#r03146@君璋 不從。

 rm@滿政 因衆心所欲，
夜襲 rm#r03146@君璋 ，
 rm#r03146@君璋 覺之，
亡奔突厥，
 rm@滿政 殺 rm#r03146@君璋 之子及突厥戍兵二百人而降。
# p 

壬戌，
 rm#r02125@梁師都 以突厥寇 dm#dm00907@匡州 。

# p 

丁卯，
 rm#r03146@苑君璋 與突厥 rm@吐屯設 寇 dm#dm08829@馬邑 ，
 rm#r06279@高滿政 與戰，
破之。

以 rm#r06279@滿政 爲 dm#dm03674@朔州 總管，
封 rm#r06279@榮國公 。


# p 

 dm#dm05769@瓜州 總管 rm@賀若懷廣 按部至 dm#dm04617@沙州 ，
値州人 rm#r05303@張護 、 rm#r01984@李通 反，
 rm@懷廣 以數百人保子城；
 dm#dm04947@涼州 總管 rm#r02189@楊恭仁 遣兵救之，
爲 rm#r05303@護 等所敗。

# p 

癸酉，
 rm#r02112@柴紹 與吐谷渾戰，
爲其所圍，
虜乘高射之，
矢下如雨。

 rm#r02112@紹 遣人彈胡琵琶，
二女子對舞。

虜怪之，
駐弓矢相與聚觀，
 rm#r02112@紹 察其無備，
潛遣精騎出虜陳後，
撃之，
虜衆大潰。

# p 

秋，
七月，
丙子，
 rm#r03146@苑君璋 以突厥寇 dm#dm08829@馬邑 ，
右武候大將軍 rm#r02014@李高遷 及 rm#r06279@高滿政 禦之，
戰于 dm#dm06645@臘河谷 ，
破之。
# p 

 rm#r05303@張護 、 rm#r01984@李通 殺 rm@賀拔懷廣 ，
立 dm#dm04465@汝州 別駕 rm#r05725@竇伏明 爲主，
進逼 dm#dm05769@瓜州 ；
長史 rm#r05901@趙孝倫 撃卻之。
拔若
# p 

 rm#r04273@高開道 掠 dm#dm07581@赤岸鎭 及 dm#dm08612@靈壽 、 dm#dm00335@九門 、 dm#dm07223@行唐 三縣而去。

# p 

丁丑，
 dm#dm02425@岡州 刺史 rm@馮士翽 據 dm#dm03360@新會 反，
 dm#dm02733@廣州 刺史 rm#r00258@劉感 討降之，
使復其位。
刺史總管
# p 

辛巳，
 rm#r04273@高開道 所部 dm#dm02892@弘陽 、 dm#dm06426@統漢 二鎭來降。
# p 

癸未，
突厥寇 dm#dm01114@原州 ；
乙酉，
寇 dm#dm03674@朔州 。

 rm#r02014@李高遷 爲虜所敗，
行軍總管 rm#r00862@尉遲敬徳 將兵救之。

己亥，
遣太子將兵屯北邊，
 rm#r01602@秦王世民 屯 dm#dm00059@幷州 ，
以備突厥。

八月，
丙辰，
突厥寇 dm#dm06043@眞州 ，
又寇 dm#dm08829@馬邑 。丙甲
# p 

壬子，
 dm#dm04988@淮南道 行臺僕射 rm#r03657@輔公祏 反。

初，
 rm#r02022@杜伏威 與 rm#r03657@公祏 相友善，
 rm#r03657@公祏 年長，
 rm#r02022@伏威 兄事之，
軍中謂之伯父，
畏敬與 rm#r02022@伏威 等。

 rm#r02022@伏威 浸忌之，
乃署其養子 rm#r03891@闞稜 爲左將軍，
 rm#r02717@王雄誕 爲右將軍，
潛奪其兵權。

 rm#r03657@公祏 知之，
怏怏不平，
與其故人 rm@左遊仙 陽爲學道、辟穀以自晦。

及 rm#r02022@伏威 入朝，
留 rm#r03657@公祏 守 dm#dm00296@丹楊 ，
令 rm#r02717@雄誕 典兵爲之副，
陰謂 rm#r02717@雄誕 曰：
「吾至 dm#dm08170@長安 ，
苟不失職，
勿令 rm#r03657@公祏 爲變。」

 rm#r02022@伏威 既行，
 rm@左遊仙 説 rm#r03657@公祏 謀反；
而 rm#r02717@雄誕 握兵，
 rm#r03657@公祏 不得發。

乃詐稱得 rm#r02022@伏威 書，
疑 rm#r02717@雄誕 有貳心，
 rm#r02717@雄誕 聞之不悦，
稱疾不視事；
 rm#r03657@公祏 因奪其兵，
使其黨 rm@西門君儀 諭以反計。

 rm#r02717@雄誕 始寤而悔之，
曰：
「今天下方平，
 rm#r02022@呉王 又在 dm#dm08170@京師 ，
 dyn#ch100@大唐 兵威，
所向無敵，
奈何無故自求族滅乎！

 rm#r02717@雄誕 有死而已，
不敢聞命。

今從公爲逆，
不過延百日之命耳，
大丈夫安能愛斯須之死而自陷於不義乎！」

 rm#r03657@公祏 知不可屈，
縊殺之。

 rm#r02717@雄誕 善撫士卒，
得其死力，
又約束嚴整，
毎破城邑，
秋毫無犯，
死之日，
 dm#dm04476@江南 軍中及民間皆爲之流涕。

 rm#r03657@公祏 又詐稱 rm#r02022@伏威 不得還 dm#dm04476@江南 ，
貽書令其起兵，
大修鎧仗，
運糧儲。

尋稱帝於 dm#dm00296@丹楊 ，
國號 dyn#?@宋 ，
修 dyn#ch167@陳 故宮室而居之，
署置百官，
以 rm@左遊仙 爲兵部尚書、東南道大使、 dm#dm07613@越州 總管，
與 rm#r01121@張善安 連兵，
以 rm#r01121@善安 爲西南道大行臺。
# p 

己未，
突厥寇 dm#dm01114@原州 。

# p 

乙丑，
詔 dm#dm07275@襄州道 行臺僕射 rm#r02432@趙郡王孝恭 以舟師趣 dm#dm04490@江州 ，
 dm#dm02531@嶺南道 大使 rm#r02009@李靖 以 dm#dm00412@交 、 dm#dm02717@廣 、 dm#dm04721@泉 、 dm#dm03996@桂 之衆趣 dm#dm02214@宣州 ，
 dm#dm03102@懷州 總管 rm#r06136@黄君漢 出 dm#dm07450@譙 、 dm#dm00454@亳 ，
 dm#dm09208@齊州 總管 rm#r01299@李世勣 出 dm#dm04981@淮 、 dm#dm04727@泗 以討 rm#r03657@輔公祏 。

 rm#r02432@孝恭 將發，
與諸將宴集，
命取水，
忽變爲血，
在坐者皆失色，
 rm#r02432@孝恭 舉止自若，
曰：
「此乃 rm#r03657@公祏 授首之徵也！」

飮而盡之，
衆皆悦服。
# p 

丙寅，
吐谷渾内附。

# p 

辛未，
突厥陷 dm#dm01114@原州 之 dm#dm00087@善和鎭 ；
癸酉，
又寇 dm#dm05113@渭州 。

# p 

 rm#r04273@高開道 以奚侵 dm#dm02689@幽州 ，
州兵撃卻之。


# p 

九月，
太子班師。
丙子
# p 

戊子，
 rm#r03657@輔公祏 遣其將 rm@徐紹宗 寇 dm#dm04893@海州 ，
 rm#r06010@陳政通 寇 dm#dm01530@壽陽 。

# p 

 dm#dm07804@邛州 獠反，
遣 rm#r03778@沛公鄭元璹 討之。

# p 

庚寅，
突厥寇 dm#dm02689@幽州 。

# p 

壬辰，
詔以 rm#r01602@秦王世民 爲 dm#dm04492@江州道 行軍元帥。

# p 

乙未，
 rm#r05725@竇伏明 以 dm#dm04617@沙州 降。

# p 

 rm@高昌王麹伯雅 卒，
子 rm#?@文泰 立。
# p 

丙申，
 dm#dm05090@渝州 人 rm#r05258@張大智 反，
刺史 rm#r05814@薛敬仁 棄城走。
# p 

壬寅，
 rm#r04273@高開道 引突厥二萬騎寇 dm#dm02689@幽州 。

# p 

突厥惡 rm#r00187@弘農公劉世讓 爲己患，
遣其臣 rm#r06203@曹般陁 來，
言 rm#r00187@世讓 與可汗通謀，
欲爲亂，
上信之。

冬，
十月，
丙午，
殺 rm#r00187@世讓 ，
籍其家。

# p 

 rm#r01602@秦王世民 猶在 dm#dm00059@幷州 ，
己未，
詔 rm#r01602@世民 引兵還。

# p 

上幸 dm#dm06943@華陰 。


# p 

 rm#r05258@張大智 侵 dm#dm04938@涪州 ，
刺史 rm#r05672@田世康 等討之，
 rm#r05258@大智 以衆降。
# p 

初，
上遣右武候大將軍 rm#r02014@李高遷 助 dm#dm03674@朔州 總管 rm#r06279@高滿政 守 dm#dm08829@馬邑 ，
 rm#r03146@苑君璋 引突厥萬餘騎至城下，
 rm#r06279@滿政 撃破之。

 rm#rz0034@頡利可汗 怒，
大發兵攻 dm#dm08829@馬邑 。

 rm#r02014@高遷 懼，
帥所部二千人斬關宵遁，
虜邀之，
失亡者半。

 rm#rz0034@頡利 自帥衆攻城，
 rm#r06279@滿政 出兵禦之，
或一日戰十餘合。

上命行軍總管 rm#r00187@劉世讓 救之，
至 dm#dm03902@松子嶺 ，
不敢進，
還保 dm#dm02501@崞城 。

會 rm#rz0034@頡利 遣使求婚，
上曰：
「釋 dm#dm08829@馬邑 之圍，
乃可議婚。」

 rm#rz0034@頡利 欲解兵，
 rm@義成公主 固請攻之。

 rm#rz0034@頡利 以 rm#r04273@高開道 善爲攻具，
召 rm#r04273@開道 ，
與之攻 dm#dm08829@馬邑 甚急。

 rm#rz0034@頡利 誘 rm#r06279@滿政 使降，
 rm#r06279@滿政 罵之。

糧且盡，
救兵未至，
 rm#r06279@滿政 欲潰圍走 dm#dm03674@朔州 ，
右虞候 rm#r05445@杜士遠 以虜兵盛，
恐不免，
壬戌，
殺 rm#r06279@滿政 降於突厥，
 rm#r03146@苑君璋 復殺城中豪傑與 rm#r06279@滿政 同謀者三十餘人。

上以 rm#r06279@滿政 子 rm@玄積 爲上柱國，
襲爵。

丁卯，
突厥復請和親，
以 dm#dm08829@馬邑 歸 dyn#ch100@唐 ；
上以將軍 rm#r05717@秦武通 爲 dm#dm03674@朔州 總管。


# p 

突厥數爲邊患，
 dm#dm00059@幷州 大總管府長史 rm#r03049@竇靜 表請於 dm#dm01774@太原 置屯田以省餽運；
議者以爲煩擾，
不許。

 rm#r03049@靜 切論不已，
敕徵 rm#r03049@靜 入朝，
使與 rm#r03424@裴寂 、 rm#r03249@蕭瑀 、 rm#r00851@封徳彞 相論難於上前，
 rm#r03424@寂 等不能屈，
乃從 rm#r03049@靜 議，
歳收穀數千斛，
上善之，
命檢校 dm#dm00059@幷州 大總管。

 rm#r03049@靜 ，
 rm#r03033@抗 之子也。

十一月，
辛巳，
 rm#r01602@秦王世民 復請増置屯田於 dm#dm00059@幷州 之境，
從之。
# p 

 dm#dm09115@黄州 總管 rm#r06164@周法明 將兵撃 rm#r03657@輔公祏 ，
 rm#r01121@張善安 據 dm#dm01535@夏口 ，
拒之。

 rm#r06164@法明 屯 dm#dm06882@荊口鎭 ，
壬午，
 rm#r06164@法明 登戰艦飮酒，
 rm#r01121@善安 遣刺客數人詐乘魚艓而至，
見者不以爲虞，
遂殺 rm#r06164@法明 而去。
# p 

甲申，
 dm#dm06799@舒州 總管 rm#r06193@張鎭周 等撃 rm#r03657@輔公祏 將 rm#r06018@陳當世 於 dm#dm05664@猷州 之 dm#dm09123@黄沙 ，
大破之。

# p 

丁亥，
上校獵於 dm#dm06943@華陰 。

己丑，
迎勞 rm#r01602@秦王世民 於 dm#dm02994@忠武頓 。

# p 

十二月，
癸卯，
安撫使 rm#r01672@李大亮 誘 rm#r01121@張善安 ，
執之。

 rm#r01672@大亮 撃 rm#r01121@善安 於 dm#dm04806@洪州 ，
與 rm#r01121@善安 隔水而陳，
遙相與語。

 rm#r01672@大亮 諭以禍福，
 rm#r01121@善安 曰：
「 rm#r01121@善安 初無反心，
正爲將士所誤；
欲降又恐不免。」

 rm#r01672@大亮 曰：
「 rm#r01121@張總管 有降心，
則與我一家耳。」

因單騎渡水入其陳，
與 rm#r01121@善安 執手共語，
示無猜間。

 rm#r01121@善安 大悦，
遂許之降。

既而 rm#r01121@善安 將數十騎詣 rm#r01672@大亮 營，
 rm#r01672@大亮 止其騎於門外，
引 rm#r01121@善安 入，
與語。

久之，
 rm#r01121@善安 辭去，
 rm#r01672@大亮 命武士執之，
從騎皆走。

 rm#r01121@善安 營中聞之，
大怒，
悉衆而來，
將攻 rm#r01672@大亮 。

 rm#r01672@大亮 使人諭之曰：
「吾不留總管。

總管赤心歸國，
謂我曰：
『若還營，
恐將士或有異同，
爲其所制。』

故自留不去耳，
卿輩何怒於我！」

其黨復大罵曰：
「 rm#r01121@張總管 賣我以自媚於人。」

遂皆潰去。

 rm#r01672@大亮 追撃，
多所虜獲。

送 rm#r01121@善安 於 dm#dm08170@長安 ，
 rm#r01121@善安 自稱不與 rm#r03657@輔公祏 交通，
上赦其罪，
善遇之；
及 rm#r03657@公祏 敗，
得所與往還書，
乃殺之。
# p 

甲寅，
車駕至 dm#dm08170@長安 。
# p 

己巳，
突厥寇 dm#dm02124@定州 ，
州兵撃走之。
# p 

庚申，
白簡、白狗羌竝遣使入貢。

*** 七年
# year 0624
# p 

春，
正月，
依 dyn#ch173@周 、 dyn#ch171@齊 舊制，
毎州置大中正一人，
掌知州内人物，
品量望第，
以本州門望高者領之，
無品秩。


# p 

壬午，
 rm#r02432@趙郡王孝恭 撃 rm#r03657@輔公祏 別將於 dm#dm04153@樅陽 ，
破之。

# p 

庚寅，
 dm#dm07909@鄒州 人 rm#r05948@鄧同穎 殺刺史 rm#r05360@李士衡 反。

# p 

丙申，
以白狗等羌地置 dm#dm06452@維 、 dm#dm03037@恭 二州。

# p 

二月，
 rm#r03657@輔公祏 遣兵圍 dm#dm05664@猷州 ，
刺史 rm#xjts12795@左難當 嬰城自守。

安撫使 rm#r01672@李大亮 引兵撃 rm#r03657@公祏 ，
破之。

 rm#r02432@趙郡王孝恭 攻 rm#r03657@公祏  dm#dm09029@鵲頭鎭 ，
拔之。
辛丑
# p 

丁未，
 rm@高麗王建武 遣使來請班暦。

遣使册 rm@建武 爲 rm@遼東郡王 、 rm@高麗王 ；
以 rm#xjts24117@百濟王扶餘璋 爲 rm#xjts24117@帶方郡王 ，
 rm#r05974@新羅王金眞平 爲 rm#r05974@樂浪郡王 。

# p 

 dm#dm01884@始州 獠反，
遣行臺僕射 rm#r03047@竇軌 討之。
# p 

己酉，
詔：
「諸州有明一經以上未仕者，
咸以名聞；
州縣及郷皆置學。」


# p 

壬子，
行軍副總管 rm#r05532@權文誕 破 rm#r03657@輔公祏 之黨於 dm#dm05664@猷州 ，
拔其 dm#dm03929@枚洄 等四鎭。
# p 

丁巳，
上幸國子監，
釋奠；
詔諸王公子弟各就學。
# p 

戊午，
改大總管爲大都督府。
# p 

己未，
 rm#r04273@高開道 將 rm#r05308@張金樹 殺 rm#r04273@開道 來降。

 rm#r04273@開道 見天下皆定，
欲降，
自以數反覆不敢；
且恃突厥之衆，
遂無降意。

其將卒皆 dm#dm02403@山東 人，
思郷里，
咸有離心。

 rm#r04273@開道 選勇敢士數百，
謂之假子，
常直閤内，
使 rm#r05308@金樹 領之。

故 rm#r00337@劉黒闥 將 rm#r06183@張君立 亡在 rm#r04273@開道 所，
與 rm#r05308@金樹 密謀取 rm#r04273@開道 。

 rm#r05308@金樹 遣其黨數人入閤内，
與假子遊戲，
向夕，
潛斷其弓弦，
藏刀槊於牀下，
合瞑，
抱之趨出，
 rm#r05308@金樹 帥其黨大譟，
攻 rm#r04273@開道 閤，
假子將禦之，
弓弦皆絶，
刀槊已失，
爭出降；
 rm#r06183@君立 亦舉火於外與相應，
内外惶擾。

 rm#r04273@開道 知不免，
乃擐甲持兵坐堂上，
與妻妾奏樂酣飮，
衆憚其勇，
不敢逼。

天且明，
 rm#r04273@開道 縊，
妻妾及諸子乃自殺。

 rm#r05308@金樹 陳兵，
悉收假子斬之，
幷殺 rm#r06183@君立 ，
死者五百餘人。

遣使來降，
詔以其地置 dm#dm01931@媯州 。

壬戌，
以 rm#r05308@金樹 爲 dm#dm00879@北燕州 都督。


# p 

戊辰，
 dm#dm04757@洋 、 dm#dm08483@集 二州獠反，
陷 dm#dm08432@隆州  dm#dm03536@晉城 。

# p 

是月，
太保 rm#r02022@呉王杜伏威 薨。

 rm#r03657@輔公祏 之反也，
詐稱 rm#r02022@伏威 之命以紿其衆。

及 rm#r03657@公祏 平，
 rm#r02432@趙郡王孝恭 不知其詐，
以状聞；
詔追除 rm#r02022@伏威 名，
籍沒其妻子。

及 rm#r01602@太宗 即位，
知其冤，
赦之，
復其官爵。
# p 

三月，
初定令，
以太尉、司徒、司空爲三公，
次尚書、門下、中書、祕書、殿中、内侍爲六省，
次御史臺，
次太常至太府爲九寺，
次將作監，
次國子學，
次天策上將府，
次左、右衞至左、右領衞爲十四衞；
東宮置三師、三少、詹事及兩坊、三寺、十率府；
王、公置府佐、國官，
公主置邑司，
竝爲京職事官。

州、縣、鎭、戍爲外職事官。

自開府儀同三司至將仕郎，
二十八階，
爲文散官；
驃騎大將軍至陪戎副尉三十一階，
爲武散官；
上柱國至武騎尉十二等，
爲勳官。

# p 

丙戌，
 rm#r02432@趙郡王孝恭 破 rm#r03657@輔公祏 於 dm#dm07092@蕪湖 ，
拔 dm#dm04042@梁山 等三鎭。

辛卯，
安撫使 rm#r00090@任瓌 拔 dm#dm03242@揚子城 ，
 dm#dm02774@廣陵城 主 rm@龍龕 降。

# p 

丁酉，
突厥寇 dm#dm01114@原州 。
# p 

戊戌，
 rm#r02432@趙郡王孝恭 克 dm#dm00296@丹楊 。
# p 

先是，
 rm#r03657@輔公祏 遣其將 rm#r06087@馮慧亮 、 rm#r06018@陳當世 將舟師三萬屯 dm#dm01096@博望山 ，
 rm#r06013@陳正通 、 rm#?@徐紹宗 將歩騎三萬屯 dm#dm08668@青林山 ，
仍於 dm#dm04042@梁山 連鐵鎖以斷江路，
築卻月城，
延袤十餘里，
又結壘 dm#dm04475@江 西以拒官軍。

 rm#r02432@孝恭 與 rm#r02009@李靖 帥舟師次 dm#dm06799@舒州 ，
 rm#r01299@李世勣 帥歩卒一萬渡 dm#dm04981@淮 ，
拔 dm#dm01530@壽陽 ，
次 dm#dm06157@硤石 。

 rm#r06087@慧亮 等堅壁不戰，
 rm#r02432@孝恭 遣奇兵絶其糧道，
 rm#r06087@慧亮 等軍乏食，
夜，
遣兵薄 rm#r02432@孝恭 營，
 rm#r02432@孝恭 堅臥不動。

 rm#r02432@孝恭 集諸將議軍事，
皆曰：
「 rm#r06087@慧亮 等擁強兵，
據水陸之險，
攻之不可猝拔，
不如直指 dm#dm00296@丹楊 ，
掩其巣穴，
 dm#dm00296@丹楊 既潰，
 rm#r06087@慧亮 等自降矣！」

 rm#r02432@孝恭 將從其議，
 rm#r02009@李靖 曰：
「 rm#r03657@公祏 精兵雖在此水陸二軍，
然所自將亦不爲少，
今 dm#dm01095@博望 諸柵尚不能拔，
 rm#r03657@公祏 保據 rm#r05745@石頭 ，
豈易取哉！

進攻 dm#dm00296@丹楊 ，
旬月不下，
 rm#r06087@慧亮 躡吾後，
腹背受敵，
此危道也。

 rm#r06087@慧亮 、 rm#r06013@正通 皆百戰餘賊，
其心非不欲戰，
正以 rm#r03657@公祏 立計使之持重，
欲以老我師耳。

我今攻其城以挑之，
一舉可破也！」

 rm#r02432@孝恭 然之，
使羸兵先攻賊營而勒精兵結陳以待之。

攻壘者不勝而走，
賊出兵追之，
行數里，
遇大軍，
與戰，
大破之。

 rm#r03891@闞稜 免冑謂賊衆曰：
「汝曹不識我邪？
何敢來與我戰！」

賊多 rm#r03891@稜 故部曲，
皆無鬬志，
或有拜者，
由是遂敗。

 rm#r02432@孝恭 、 rm#r02009@靖 乘勝逐北，
轉戰百餘里，
 dm#dm01087@博山 、 dm#dm08667@青林 兩戍皆潰，
 rm#r06087@慧亮 、 rm#r06013@正通 等遁歸，
殺傷及溺死者萬餘人。

 rm#r02009@李靖 兵先至 dm#dm00296@丹楊 ，
 rm#r03657@公祏 大懼，
擁兵數萬，
棄城東走，
欲就 rm@左遊仙 於 dm#dm03660@會稽 ，
 rm#r01299@李世勣 追之。

 rm#r03657@公祏 至 dm#dm01147@句容 ，
從兵能屬者纔五百人，
夜，
宿 dm#dm02599@常州 ，
其將 rm#r05110@呉騷 等謀執之。

 rm#r03657@公祏 覺之，
棄妻子，
獨將腹心數十人，
斬關走。

至 dm#dm04259@武康 ，
爲野人所攻，
 rm@西門君儀 戰死，
執 rm#r03657@公祏 ，
送 dm#dm00296@丹楊 梟首，
分捕餘黨，
悉誅之，
 dm#dm04476@江南 皆平。
# p 

己亥，
以 rm#r02432@孝恭 爲東南道行臺右僕射，
 rm#r02009@李靖 爲兵部尚書。

頃之，
廢行臺，
以 rm#r02432@孝恭 爲 dm#dm03246@揚州 大都督，
 rm#r02009@靖 爲府長史。

上深美 rm#r02009@靖 功，
曰：
「 rm#r02009@靖 ，
 rm#r03260@蕭 、 rm#r03657@輔 之膏肓也。」


# p 

 rm#r03891@闞稜 功多，
頗自矜伐。

 rm#r03657@公祏 誣 rm#r03891@稜 與己通謀。

會 rm#r02432@趙郡王孝恭 籍沒賊黨田宅，
 rm#r03891@稜 及 rm#r02022@杜伏威 、 rm#r02717@王雄誕 田宅在賊境者，
 rm#r02432@孝恭 幷籍沒之；
 rm#r03891@稜 自訴理，
忤 rm#r02432@孝恭 ，
 rm#r02432@孝恭 怒，
以謀反誅之。
# p 

夏，
四月，
庚子朔，
赦天下。

是日，
頒新律令，
比 y@開皇 舊制増新格五十三條。
# p 

初定均田租、庸、調法：
丁、中之民，
給田一頃，
篤疾減什之六，
寡妻妾減七，
皆以什之二爲世業，
八爲口分。

毎丁歳入租，
粟二石。

調隨土地所宜，
綾、絹、絁、布。

歳役二旬；
不役則收其傭，
日三尺；
有事而加役者，
旬有五日，
免其調；
三旬，
租、調倶免。

水旱蟲霜爲災，
什損四以上免租，
損六以上免調，
損七已上課役倶免。

凡民貲業分九等。

百戸爲里，
五里爲郷，
四家爲鄰，
四鄰爲保。

在城邑者爲坊，
田野者爲村。

食祿之家，
無得與民爭利；
工商雜類，
無預士伍。

男女始生爲黄，
四歳爲小，
十六爲中，
二十爲丁，
六十爲老。

歳造計帳，
三年造戸籍。


# p 

丁未，
黨項寇 dm#dm03903@松州 。
# p 

庚申，
通事舍人 rm#r05442@李鳳起 撃 dm#dm06975@萬州 反獠，
平之。

# p 

五月，
辛未，
突厥寇 dm#dm03674@朔州 。
# p 

甲戌，
羌與吐谷渾同寇 dm#dm03903@松州 ，
遣 dm#dm05982@益州 行臺左僕射竇軌自 dm#dm06577@翼州道 ，
 dm#dm03171@扶州 刺史 rm#r05782@蒋善合 自 dm#dm06833@芳州道 撃之。

# p 

丙戌，
作 dm#dm00458@仁智宮 於 dm#dm02166@宜君 。

# p 

丁亥，
 rm#r03047@竇軌 破反獠於 dm#dm03416@方山 ，
俘二萬餘口。
# p 

六月，
辛丑，
上幸 dm#dm00458@仁智宮 避暑。

# p 

辛亥，
 dm#dm05487@瀧州 、 dm#dm03171@扶州 獠作亂，
遣 dm#dm00974@南尹州 都督 rm#r05352@李光度 等撃平之。

# p 

丙辰，
吐谷渾寇 dm#dm03171@扶州 ，
刺史 rm#r05782@蒋善合 撃走之。
# p 

壬戌，
 dm#dm03083@慶州 都督 rm#r05501@楊文幹 反。

# p 

初，
 rm#r01016@齊王元吉 勸太子 rm#r01078@建成 除 rm#r01602@秦王世民 ，
曰：
「當爲兄手刃之！」

 rm#r01602@世民 從上幸 rm#r01016@元吉 第，
 rm#r01016@元吉 伏護軍 rm#r06172@宇文寶 於寢内，
欲刺 rm#r01602@世民 ；
 rm#r01078@建成 性頗仁厚，
遽止之。

 rm#r01016@元吉 慍曰：
「爲兄計耳，
於我何有！」

# p 

 rm#r01078@建成 募 dm#dm08170@長安 及四方驍勇二千餘人爲東宮衞士，
分屯左、右 dm#dm08190@長林 ，
號 dm#dm08190@長林 兵。

又密使右虞候率 rm#xjts03755@可達志 從 rm#r03089@燕王李藝 發 dm#dm02689@幽州 突騎三百，
置宮東諸坊，
欲以補東宮長上。

爲人所告，
上召 rm#r01078@建成 責之，
流 rm#xjts03755@可達志 於 dm#dm02536@巂州 。

# p 

 rm#r05501@楊文幹 嘗宿衞東宮，
 rm#r01078@建成 與之親厚，
私使募壯士送 dm#dm08170@長安 。

上將幸 dm#dm00458@仁智宮 ，
命 rm#r01078@建成 居守，
 rm#r01602@世民 、 rm#r01016@元吉 皆從。

 rm#r01078@建成 使 rm#r01016@元吉 就圖 rm#r01602@世民 ，
曰：
「安危之計，
決在今歳。」

又使郎將 rm@爾朱煥 、校尉 rm@橋公山 以甲遺 rm#r05501@文幹 。

二人至 dm#dm07510@豳州 ，
上變，
告太子使 rm#r05501@文幹 舉兵，
使表裏相應；
又有 dm#dm02291@寧州 人 rm#r05456@杜鳳舉 亦詣宮言状。

上怒，
託他事，
手詔召 rm#r01078@建成 ，
令詣行在。

建成懼，
不敢赴。

太子舍人 rm#r05317@徐師謩 勸之據城舉兵；
詹事主簿 rm#r03617@趙弘智 勸之貶損車服，
屏從者，
詣上謝罪，
 rm#r01078@建成 乃詣 dm#dm00458@仁智宮 。

未至六十里，
悉留其官屬於 dm#dm04377@毛鴻賓堡 ，
以十餘騎往見上，
叩頭謝罪，
奮身自擲，
幾至於絶。

上怒不解，
是夜，
置之幕下，
飼以麥飯，
使殿中監 rm#r06020@陳福 防守，
遣司農卿 rm#r00763@宇文穎 馳召 rm#r05501@文幹 。

 rm#r00763@穎 至 dm#dm03083@慶州 ，
以情告之，
 rm#r05501@文幹 遂舉兵反。

上遣左武衞將軍 rm#r03843@錢九隴 與 dm#dm08619@靈州 都督 rm#r02174@楊師道 撃之。使欲
# p 

甲子，
上召 rm#r01602@秦王世民 謀之，
 rm#r01602@世民 曰：
「 rm#r05501@文幹 豎子，
敢爲狂逆，
計府僚已應擒戮；
若不爾，
正應遣一將討之耳。」

上曰：
「不然。

 rm#r05501@文幹 事連 rm#r01078@建成 ，
恐應之者衆。

汝宜自行，
還，
立汝爲太子。

吾不能效 rm#rt0778@隋文帝 自誅其子，
當封 rm#r01078@建成 爲 rm#r01078@蜀王 。

 dm#dm07197@蜀 兵脆弱，
他日苟能事汝，
汝宜全之；
不能事汝，
汝取之易耳！」


# p 

上以 dm#dm00458@仁智宮 在山中，
恐盜兵猝發，
夜，
帥宿衞南出山外，
行數十里，
東宮官屬繼至，
皆令三十人爲隊，
分兵圍守之。

明日，
復還 dm#dm00458@仁智宮 。
將卒
# p 

 rm#r01602@世民 既行，
 rm#r01016@元吉 與𡚱嬪更迭爲 rm#r01078@建成 請，
 rm#r00851@封徳彞 復爲之營解於外，
上意遂變，
復遣 rm#r01078@建成 還 dm#dm08170@京師 居守。

惟責以兄弟不睦，
歸罪於太子中允 rm#r02672@王珪 、左衞率 rm#r04036@韋挺 、天策兵曹參軍 rm#r02056@杜淹 ，
竝流於 dm#dm02536@巂州 。

 rm#r04036@挺 ，
 rm#r06840@沖 之子也。

初，
 dm#dm04788@洛陽 既平，
 rm#r02056@杜淹 久不得調，
欲求事 rm#r01078@建成 。

 rm#r01377@房玄齡 以 rm#r02056@淹 多狡數，
恐其教導 rm#r01078@建成 ，
益爲 rm#r01602@世民 不利，
乃言於世民，
引入天策府。
# p 

突厥寇 dm#dm00485@代州 之 dm#dm04234@武周城 ，
州兵撃破之。
# p 

秋，
七月，
己巳，
 rm#r03146@苑君璋 以突厥寇 dm#dm03674@朔州 ，
總管 rm#r05717@秦武通 撃卻之。
# p 

 rm#r05501@楊文幹 襲陷 dm#dm02291@寧州 ，
驅掠吏民出據 dm#dm05943@百家堡 。

 rm#r01602@秦王世民 軍至 dm#dm02291@寧州 ，
其黨皆潰。

癸酉，
 rm#r05501@文幹 爲其麾下所殺，
傳首 dm#dm08170@京師 。

獲 rm#r00763@宇文穎 ，
誅之。
# p 

丁丑，
 rm#r02125@梁師都 行臺 rm#r05683@白伏願 來降。

# p 

戊寅，
突厥寇 dm#dm01114@原州 ；
遣 dm#dm02291@寧州 刺史 rm@鹿大師 救之，
又遣 rm#r02174@楊師道 趨 dm#dm01637@大木根山 。

庚辰，
突厥寇 dm#dm08464@隴州 ；
遣護軍 rm#r00862@尉遲敬徳 撃之。
邀其歸路
# p 

吐谷渾寇 dm#dm02437@岷州 。

辛巳，
吐谷渾、黨項寇 dm#dm03903@松州 。

# p 

癸未，
突厥寇 dm#dm08344@陰盤 。


# p 

甲申，
 dm#dm03171@扶州 刺史 rm#r05782@蒋善合 撃吐谷渾於 dm#dm03903@松州  dm#dm07600@赤磨鎭 ，
破之。
# p 

己丑，
突厥 rm@吐利設 與 rm#r03146@苑君璋 寇 dm#dm00059@幷州 。
# p 

甲子，
車駕還京師。
# p 

或説上曰：
「突厥所以屡寇 dm#dm08281@關中 者，
以子女玉帛皆在 dm#dm08170@長安 故也。

若焚 dm#dm08170@長安 而不都，
則胡寇自息矣。」

上以爲然，
遣中書侍郎 rm#r00750@宇文士及 踰 dm#dm00975@南山 至 dm#dm04155@樊 、 dm#dm07938@鄧 ，
行可居之地，
將徙都之。

太子 rm#r01078@建成 、 rm#r01016@齊王元吉 、 rm#r03424@裴寂 皆贊成其策，
 rm#r03249@蕭瑀 等雖知其不可而不敢諫。

 rm#r01602@秦王世民 諫曰：
「戎狄爲患，
自古有之。

陛下以聖武龍興，
光宅 dm#dm00257@中夏 ，
精兵百萬，
所征無敵，
奈何以胡寇擾邊，
遽遷都以避之，
貽四海之羞，
爲百世之笑乎！

彼 rm#r06036@霍去病  dyn#ch129@漢 廷一將，
猶志滅匈奴；
況臣忝備藩維，
願假數年之期，
請係 rm#rz0034@頡利 之頸，
致之闕下。

若其不效，
遷都未晩。」

上曰：
「善。

」
 rm#r01078@建成 曰：
「昔 rm#r06222@樊噲 欲以十萬衆横行匈奴中，
 rm#r01602@秦王 之言得無似之！」

 rm#r01602@世民 曰：
「形勢各異，
用兵不同，
 rm#r06222@樊噲 小豎，
何足道乎！

不出十年，
必定漠北，
非虚言也！」

上乃止。

 rm#r01078@建成 與𡚱嬪因共譖 rm#r01602@世民 曰：
「突厥雖屡爲邊患，
得賂即退。

 rm#r01602@秦王 外託禦寇之名，
内欲總兵權，
成其簒奪之謀耳！」

敢
# p 

上校獵城南，
太子、 rm#r03193@秦 、 rm#r01016@齊王 皆從，
上命三子馳射角勝。

 rm#r01078@建成 有胡馬，
肥壯而喜蹶，
以授 rm#r01602@世民 曰：
「此馬甚駿，
能超數丈澗，
弟善騎，
試乘之。」

 rm#r01602@世民 乘以逐鹿，
馬蹶，
 rm#r01602@世民 躍立於數歩之外，
馬起，
復乘之，
如是者三，
顧謂 rm#r00750@宇文士及 曰：
「彼欲以此見殺，
死生有命，
庸何傷乎！」

 rm#r01078@建成 聞之，
因令𡚱嬪譖之於上曰：
「 rm#r01602@秦王 自言，
我有天命，
方爲天下主，
豈有浪死！」

上大怒，
先召 rm#r01078@建成 、 rm#r01016@元吉 ，
然後召 rm#r01602@世民 入，
責之曰：
「天子自有天命，
非智力可求；
汝求之一何急邪！」

 rm#r01602@世民 免冠頓首，
請下法司案驗。

上怒不解，
會有司奏突厥入寇，
上乃改容勞勉 rm#r01602@世民 ，
命之冠帶，
與謀突厥。

閏月，
己未，
詔 rm#r01602@世民 、 rm#r01016@元吉 將兵出 dm#dm07510@豳州 以禦突厥，
上餞之於 dm#dm07156@蘭池 。

上毎有寇盜，
輒命 rm#r01602@世民 討之，
事平之後，
猜嫌益甚。
# p 

初，
 dyn#ch174@隋 末 dm#dm00427@京兆  rm#r04001@韋仁壽 爲 dm#dm07205@蜀郡 司法書佐，
所論囚至市，
猶西向爲 rm#r04001@仁壽 禮佛然後死。

 dyn#ch100@唐 興，
 rm#xjts26974@爨弘達 帥西南夷内附，
朝廷遣使撫之，
類皆貪縱，
遠民患之，
有叛者。

 rm#r04001@仁壽 時爲 dm#dm02536@巂州 都督長史，
上聞其名，
命檢校 dm#dm00971@南寧州 都督，
寄治 dm#dm07609@越巂 ，
使之歳一至其地慰撫之。

 rm#r04001@仁壽 性寛厚，
有識度，
既受命，
將兵五百人至 dm#dm07351@西洱河 ，
周歴數千里，
蠻、夷豪帥皆望風歸附，
來見 rm#r04001@仁壽 。

 rm#r04001@仁壽 承制置七州、十五縣，
各以其豪帥爲刺史、縣令，
法令清肅，
蠻、夷悦服。

將還，
豪帥皆曰：
「天子遣公都督 dm#dm00971@南寧 ，
何爲遽去？」
 rm#r04001@仁壽 以城池未立爲辭。

蠻、夷即相帥爲 rm#r04001@仁壽 築城，
立廨舍，
旬日而就。

 rm#r04001@仁壽 乃曰：
「吾受詔但令巡撫，
不敢留。」

蠻、夷號泣送之，
因各遣子弟入貢。

壬戌，
 rm#r04001@仁壽 還朝，
上大悦，
命 rm#r04001@仁壽 徙鎭 dm#dm00971@南寧 ，
以兵戍之。
# p 

 rm#r03146@苑君璋 引突厥寇 dm#dm03674@朔州 。

# p 

八月，
戊辰，
突厥寇 dm#dm01114@原州 。
# p 

己巳，
吐谷渾寇 dm#dm07964@鄯州 。

# p 

壬申，
突厥寇 dm#dm03000@忻州 ，
丙子，
寇 dm#dm00059@幷州 ；
 dm#dm08170@京師 戒嚴。

戊寅，
寇 dm#dm06439@綏州 ，
刺史 rm#r05061@劉大倶 撃卻之。
# p 

是時，
 rm#rz0034@頡利 、 rm@突利 二可汗舉國入寇，
連營南上，
 rm#r01602@秦王世民 引兵拒之。

會 dm#dm08281@關中 久雨，
糧運阻絶，
士卒疲於征役，
器械頓弊，
朝廷及軍中咸以爲憂。

 rm#r01602@世民 與虜遇於 dm#dm07510@豳州 ，
勒兵將戰，
己卯，
可汗帥萬餘騎奄至城西，
陳於 dm#dm00403@五隴阪 ，
將士震恐。

 rm#r01602@世民 謂 rm#r01016@元吉 曰：
「今虜騎憑陵，
不可示之以怯，
當與之一戰，
汝能與我倶乎？」
 rm#r01016@元吉 懼曰：
「虜形勢如此，
奈何輕出，
萬一失利，
悔可及乎！」

 rm#r01602@世民 曰：
「汝不敢出，
吾當獨往，
汝留此觀之。」

 rm#r01602@世民 乃帥騎馳詣虜陳，
告之曰：
「國家與可汗和親，
何爲負約，
深入我地！

我 rm#r01602@秦王 也，
可汗能鬬，
獨出與我鬬；
若以衆來，
我直以此百騎相當耳。」

 rm#rz0034@頡利 不之測，
笑而不應。

 rm#r01602@世民 又前，
遣騎告 rm@突利 曰：
「爾往與我盟，
有急相救；
今乃引兵相攻，
何無香火之情也！」

 rm@突利 亦不應。

 rm#r01602@世民 又前，
將渡溝水，
 rm#rz0034@頡利 見 rm#r01602@世民 輕出，
又聞香火之言，
疑 rm@突利 與 rm#r01602@世民 有謀，
乃遣止 rm#r01602@世民 曰：
「王不須渡，
我無他意，
更欲與王申固盟約耳。」

乃引兵稍卻。

是後霖雨益甚，
 rm#r01602@世民 謂諸將曰：
「虜所恃者弓矢耳，
今積雨彌時，
筋膠倶解，
弓不可用，
彼如飛鳥之折翼；
吾屋居火食，
刀槊犀利，
以逸制勞，
此而不乘，
將復何待！」

乃潛師夜出，
冒雨而進，
突厥大驚。

 rm#r01602@世民 又遣説 rm@突利 以利害，
 rm@突利 悦，
聽命。

 rm#rz0034@頡利 欲戰，
 rm@突利 不可，
乃遣 rm@突利 與其夾畢特勒 rm#r05992@阿史那思摩 來見 rm#r01602@世民 ，
請和親，
 rm#r01602@世民 許之。

 rm#r05992@思摩 ，
 rm#rz0034@頡利 之從叔也。

 rm@突利 因自託於 rm#r01602@世民 ，
請結爲兄弟；
 rm#r01602@世民 亦以恩意撫之，
與盟而去。

# p 

庚寅，
 dm#dm02420@岐州 刺史 rm#r02112@柴紹 破突厥於 dm#dm03777@杜陽谷 。

# p 

壬申，
突厥 rm#r05992@阿史那思摩 入見，
上引升御榻，
慰勞之。

 rm#r05992@思摩 貌類胡，
不類突厥，
故 rm@處羅 疑其非 rm#no@阿史那 種，
歴 rm@處羅 、 rm#rz0034@頡利 世，
常爲夾畢特勒，
終不得典兵爲設。

既入朝，
賜爵 rm#r05992@和順王 。
# p 

丁酉，
遣左僕射 rm#r03424@裴寂 使於突厥。

# p 

九月，
癸卯，
 dm#dm03432@日南 人 rm#r05145@姜子路 反，
 dm#dm00415@交州 都督 rm#r05628@王志遠 撃破之。
# p 

癸卯，
突厥寇 dm#dm06439@綏州 ，
都督 rm#r05061@劉大倶 撃破之，
獲特勒三人。
# p 

冬，
十月，
己巳，
突厥寇 dm#dm05794@甘州 。
# p 

辛未，
上校獵於 dm#dm07933@鄠 之 dm#dm00975@南山 ；
癸酉，
幸 dm#dm06423@終南 。

# p 

吐谷渾及羌人寇 dm#dm05855@疊州 ，
陷 dm#dm01186@合川 。

# p 

丙子，
上幸 dm#dm04170@樓觀 ，
謁 dm#dm06587@老子祠 ；
癸未，
以太牢祭 dm#dm08440@隋文帝陵 ；
十一月，
丁卯，
上幸 dm#dm09265@龍躍宮 ；
庚午，
還宮。
# p 

太子詹事 rm#r03452@裴矩 權檢校侍中。

*** 八年
# year 0625
# p 

春，
正月，
丙辰，
以 dm#dm01521@壽州 都督 rm#r06193@張鎭周 爲 dm#dm06799@舒州 都督。

 rm#r06193@鎭周 以 dm#dm06799@舒州 本其郷里，
到州，
就故宅多市酒肴，
召親戚故人，
與之酣宴，
散髮箕踞，
如爲布衣時，
凡十日。

既而分贈金帛，
泣，
與之別，
曰：
「今日 rm#r06193@張鎭周 猶得與故人歡飮，
明日之後，
則 dm#dm06799@舒州 都督治百姓耳，
君民禮隔，
不得復爲交遊。」

自是親戚故人犯法，
一無所縱，
境内肅然。
# p 

丁巳，
遣右武衞將軍 rm#r06227@段徳操 徇 dm#dm01538@夏州 地。

# p 

吐谷渾寇 dm#dm05855@疊州 。

# p 

是月，
突厥、吐谷渾各請互市，
詔皆許之。

先是，
 dm#dm00255@中國 喪亂，
民乏耕牛，
至是資於戎狄，
雜畜被野。


# p 

夏，
四月，
乙亥，
黨項寇 dm#dm05113@渭州 。

# p 

甲申，
上幸 dm#dm07934@鄠縣 ，
校獵于 dm#dm05803@甘谷 ，
營 dm#dm01782@太和宮 於 dm#dm06424@終南山 ；
丙戌，
還宮。
# p 

西突厥 rm@統葉護可汗 遣使請婚，
上謂 rm#r03452@裴矩 曰：
「西突厥道遠，
緩急不能相助，
今求婚，
何如？」
對曰：
「今北狄方強，
爲國家今日計，
且當遠交而近攻，
臣謂宜許其婚以威 rm#rz0034@頡利 ；
俟數年之後，
 dm#dm00255@中國 完實，
足抗北夷，
然後徐思其宜。」

上從之。

遣 rm#r04239@高平王道立 至其國，
 rm@統葉護 大喜。

 rm#r04239@道立 ，
上之從子也。

# p 

初，
上以天下大定，
罷十二軍。

既而突厥爲寇不已，
辛亥，
復置十二軍，
以太常卿 rm#r03046@竇誕 等爲將軍，
簡練士馬，
議大舉撃突厥。
# p 

甲寅，
 dm#dm04947@涼州 胡 rm@睦伽陀 引突厥襲都督府，
入子城；
長史 rm#r05060@劉君傑 撃破之。

# p 

六月，
甲子，
上幸 dm#dm01782@太和宮 。
# p 

丙子，
遣 rm#r03089@燕郡王李藝 屯 dm#dm06929@華亭縣 及 dm#dm02916@彈箏峽 ，
水部郎中 rm#r00653@姜行本 斷 dm#dm06093@石嶺道 以備突厥。

# p 

丙戌，
 rm#rz0034@頡利可汗 寇 dm#dm08619@靈州 。

丁亥，
以右衞大將軍 rm#r05287@張瑾 爲行軍總管以禦之，
以中書侍郎 rm#r02480@温彦博 爲長史。

先是，
上與突厥書用敵國禮，
秋，
七月，
甲辰，
上謂侍臣曰：
「突厥貪婪無厭，
朕將征之，
自今勿復爲書，
皆用詔敕。」

# p 

丙午，
車駕還宮。
# p 

己酉，
突厥 rm#rz0034@頡利可汗 寇 dm#dm06029@相州 。

# p 

 rm@睦伽陀 攻 dm#dm04292@武興 。

# p 

丙辰，
 dm#dm00485@代州 都督 rm@藺謩 與突厥戰於 dm#dm03332@新城 ，
不利；
復命行軍總管 rm#r05287@張瑾 屯 dm#dm06091@石嶺 ，
 rm#r02014@李高遷 趨 dm#dm01683@大谷 以禦之。

丁巳，
命 rm#r01602@秦王 出屯 dm#dm07029@蒲州 以備突厥。

# p 

八月，
壬戌，
突厥踰 dm#dm06091@石嶺 ，
寇 dm#dm00059@幷州 ；
癸亥，
寇 dm#dm08619@靈州 ；
丁卯，
寇 dm#dm05352@潞 、 dm#dm04574@沁 、 dm#dm08726@韓 三州。

# p 

左武候大將軍 rm#r05171@安修仁 撃 rm@睦伽陀 於 dm#dm00239@且渠川 ，
破之。

# p 

詔 dm#dm02008@安州 大都督 rm#r02009@李靖 出 dm#dm05358@潞州道 ，
行軍總管 rm#r00090@任瓌 屯 dm#dm01820@太行 ，
以禦突厥。

 rm#rz0034@頡利可汗 將兵十餘萬大掠 dm#dm03674@朔州 。

壬申，
 dm#dm00060@幷州道 行軍總管 rm#r05287@張瑾 與突厥戰于 dm#dm01824@太谷 ，
全軍皆沒，
 rm#r05287@瑾 脱身奔 rm#r02009@李靖 。

行軍長史 rm#r02480@温彦博 爲虜所執，
虜以 rm#r02480@彦博 職在機近，
問以國家兵糧虚實，
 rm#r02480@彦博 不對，
虜遷之 dm#dm08339@陰山 。

庚辰，
突厥寇 dm#dm08626@靈武 ，
甲申，
 dm#dm08619@靈州 都督 rm#r02398@任城王道宗 撃破之。

丙戌，
突厥寇 dm#dm06439@綏州 。

丁亥，
 rm#rz0034@頡利可汗 遣使請和而退。


# p 

九月，
癸巳，
突厥 rm@沒賀咄設 陷 dm#dm00059@幷州 一縣，
丙申，
 dm#dm00485@代州 都督 rm#?@藺謩 撃破之。
# p 

癸卯，
初令太府檢校諸州權量。

# p 

丙午，
右領軍將軍 rm#r02607@王君廓 破突厥於 dm#dm02689@幽州 ，
俘斬二千餘人。
# p 

突厥寇 dm#dm07132@藺州 。

# p 

冬，
十月，
壬申，
吐谷渾寇 dm#dm05855@疊州 ，
遣 dm#dm03171@扶州 刺史 rm#r05782@蒋善合 救之。

# p 

戊寅，
突厥寇 dm#dm07964@鄯州 ，
遣 rm#r02112@霍公柴紹 救之。

# p 

十一月，
辛卯朔，
上幸 dm#dm02174@宜州 。
# p 

權檢校侍中 rm#r03452@裴矩 罷判黄門侍郎。
# p 

戊戌，
突厥寇 dm#dm02932@彭州 。

# p 

庚子，
以天策司馬 rm#r00750@宇文士及 權檢校侍中。


# p 

辛丑，
徙 rm#r03988@蜀王元軌 爲 rm#r03988@呉王 ，
 rm#r03674@漢王元慶 爲 rm#r03674@陳王 。
# p 

癸卯，
加 rm#r01602@秦王世民 中書令，
 rm#r01016@齊王元吉 侍中。
# p 

丙午，
吐谷渾寇 dm#dm02437@岷州 。
# p 

戊申，
 dm#dm06035@眉州 山獠反。

# p 

十二月，
辛酉，
上還至 dm#dm08170@京師 。
# p 

庚辰，
上校獵於 dm#dm09015@鳴犢泉 ；
辛巳，
還宮。
# p 

以 rm#r03482@襄邑王神符 檢校 dm#dm03246@揚州 大都督。

始自 dm#dm00296@丹楊 徙州府及居民於 dm#dm04475@江 北。

*** 九年
# year 0626
# p 

春，
正月，
己亥，
詔太常少卿 rm#r02965@祖孝孫 等更定雅樂。

# p 

甲寅，
以左僕射 rm#r03424@裴寂 爲司空，
日遣員外郎一人更直其第。
# p 

二月，
庚申，
以 rm#r01016@齊王元吉 爲司徒。
# p 

丙子，
初令州縣祀社稷，
又令士民里閈相從立社。

各申祈報，
用洽郷黨之歡。

戊寅，
上祀社稷。
# p 

丁亥，
突厥寇 dm#dm01114@原州 ，
遣折威將軍 rm#r05505@楊毛 撃之。

毛屯
# p 

三月，
庚寅，
上幸 dm#dm03450@昆明池 ；
壬辰，
還宮。
# p 

癸巳，
吐谷渾、黨項寇 dm#dm02437@岷州 。
# p 

戊戌，
 dm#dm05983@益州道 行臺尚書 rm#r05945@郭行方 撃 dm#dm06035@眉州 叛獠，
破之。

# p 

壬寅，
 rm#r02125@梁師都 寇邊，
陷 dm#dm08713@靜難鎭 。

# p 

丙午，
上幸 dm#dm01312@周氏陂 。
# p 

辛亥，
突厥寇 dm#dm08619@靈州 。

# p 

乙卯，
車駕還宮。
# p 

癸丑，
 rm#r05536@南海公歐陽胤 奉使在突厥，
帥其徒五十人謀掩襲可汗牙帳；
事泄，
突厥囚之。
# p 

丁巳，
突厥寇 dm#dm04947@涼州 ，
都督 rm#r03873@長樂王幼良 撃走之。

# p 

戊午，
 rm#r05945@郭行方 撃叛獠於 dm#dm04804@洪 、 dm#dm08476@雅 二州，
大破之，
俘男女五千口。
# p 

夏，
四月，
丁卯，
突厥寇 dm#dm03674@朔州 ；
庚午，
寇 dm#dm01114@原州 ；
癸酉，
寇 dm#dm04924@涇州 。

戊寅，
 dm#dm02008@安州 大都督 rm#r02009@李靖 與突厥 rm#rz0034@頡利可汗 戰於 dm#dm08619@靈州 之硤石，
自旦至申，
突厥乃退。


# p 

太史令 rm#r00140@傅奕 上疏請除佛法曰：
「佛在 dm#dm07304@西域 ，
言妖路遠，
 dyn#ch129@漢 譯胡書，
恣其假託。

使不忠不孝削髮而揖君親，
遊手遊食易服以逃租賦。

僞啓三塗，
謬張六道，
恐愒愚夫，
詐欺庸品。

乃追懺既往之罪，
虚規將來之福；
布施萬錢，
希萬倍之報，
持齋一日，
冀百日之糧。

遂使愚迷，
妄求功徳，
不憚科禁，
輕犯憲章；
有造爲惡逆，
身墜刑網，
方乃獄中禮佛，
規免其罪。

且生死壽夭，
由於自然，
刑徳威福，
關之人主，
貧富貴賤，
功業所招，
而愚僧矯詐，
皆云由佛。

竊人主之權，
造化之力，
其爲害政，
良可悲矣！

降自、 rm#?@羲  rm#?@農 ，
至于 dyn#ch129@有漢 ，
皆無佛法，
君明臣忠，
祚長年久。

 rm#rt0530@漢明帝 始立胡神，
 dm#dm07304@西域 桑門自傳其法。

 dyn#ch137@西晉 以上，
國有嚴科，
不許 dm#dm00255@中國 之人輒行髡髮之事。

洎于 rm#rt0613@苻 、 rm#rt0601@石 ，
羌、胡亂 dm#dm06927@華 ，
主庸臣佞，
政虐祚短，
 rm#rt0704@梁武 、 rm#rt0760@齊襄 ，
足爲明鏡。

今天下僧尼，
數盈十萬，
翦刻繒綵，
裝束泥人，
競爲厭魅，
迷惑萬姓。

請令匹配，
即成十萬餘戸，
産育男女，
十年長養，
一紀教訓，
可以足兵。

四海免蠶食之殃，
百姓知威福所在，
則妖惑之風自革，
淳朴之化還興。

竊見 dyn#ch171@齊朝  rm#r05738@章仇子佗 表言：
『僧尼徒衆，
糜損國家，
寺塔奢侈，
虚費金帛。』

爲諸僧附會宰相，
對朝讒毀，
諸尼依託𡚱、主，
潛行謗讟，
 rm#r05738@子佗 竟被囚縶，
刑於都市。

 rm#rt0771@周武 平 dyn#ch171@齊 ，
制封其墓。

臣雖不敏，
竊慕其蹤。」

# p 

上詔百官議其事，
唯太僕卿 rm#r01199@張道源 稱 rm#r00140@奕 言合理。

 rm#r03249@蕭瑀 曰：
「佛，
聖人也，
而 rm#r00140@奕 非之；
非聖人者無法，
當治其罪。」

 rm#r00140@奕 曰：
「人之大倫，
莫如君父。

佛以世嫡而叛其父，
以匹夫而抗天子。

 rm#r03249@蕭瑀 不生於空桑，
乃遵無父之教。

非孝者無親，
 rm#r03249@瑀 之謂矣！」

 rm#r03249@瑀 不能對，
但合手曰：
「地獄之設，
正爲是人！」


# p 

上亦惡沙門、道士苟避征傜，
不守戒律，
皆如 rm#r00140@奕 言。

又寺觀鄰接廛邸，
溷雜屠沽，
辛巳，
下詔：
「命有司沙汰天下僧、尼、道士、女冠，
其精勤練行者，
遷居大寺觀，
給其衣食，
毋令闕乏。

庸猥粗穢者，
悉令罷道，
勒還郷里。

 dm#dm08170@京師 留寺三所，
觀二所，
諸州各留一所，
餘皆罷之。」
道遣
# p 

 rm#r00140@傅奕 性謹密，
既職在占候，
杜絶交遊，
所奏災異，
悉焚其藁，
人無知者。
# p 

癸未，
突厥寇 dm#dm07336@西會州 。

# p 

五月，
戊子，
 dm#dm07172@虔州  rm#r05326@胡成郎 等殺長史，
叛歸 rm#r02125@梁師都 ；
都督 rm#?@劉旻 追斬之。
# p 

壬辰，
黨項寇 dm#dm02715@廓州 。

# p 

戊戌，
突厥寇 dm#dm06279@秦州 。
# p 

壬寅，
 dm#dm07613@越州 人 rm#r05700@盧南 反，
殺刺史 rm#r05670@甯道明 。

# p 

丙午，
吐谷渾、黨項寇 dm#dm04668@河州 。

# p 

突厥寇 dm#dm07155@蘭州 。

# p 

丙辰，
遣平道將軍 rm#r02112@柴紹 將兵撃胡。

# p 

六月，
丁巳，
太白經天。


# p 

 rm#r01602@秦王世民 既與太子 rm#r01078@建成 、 rm#r01016@齊王元吉 有隙，
以 dm#dm04788@洛陽 形勝之地，
恐一朝有變，
欲出保之，
乃以行臺工部尚書 rm#r02475@温大雅 鎭 dm#dm04788@洛陽 ，
遣 rm#r01602@秦 府車騎將軍 dm#dm05216@滎陽  rm#r01094@張亮 將左右 rm#xjts02291@王保 等千餘人之 dm#dm04788@洛陽 ，
陰結納 dm#dm02403@山東 豪傑以俟變，
多出金帛，
恣其所用。

 rm#r01016@元吉 告 rm#r01094@亮 謀不軌，
下吏考驗；
 rm#r01094@亮 終無言，
乃釋之，
使還 dm#dm04788@洛陽 。
# p 

 rm#r01078@建成 夜召 rm#r01602@世民 ，
飮酒而酖之，
 rm#r01602@世民 暴心痛，
吐血數升，
 rm#r02450@淮安王神通 扶之還 dm#dm07310@西宮 。

上幸 dm#dm07310@西宮 ，
問 rm#r01602@世民 疾，
敕 rm#r01078@建成 曰：
「 rm#r01602@秦王 素不能飮，
自今無得復夜飮。」

因謂 rm#r01602@世民 曰：
「首建大謀，
削平海内，
皆汝之功。

吾欲立汝爲嗣，
汝固辭；
且 rm#r01078@建成 年長，
爲嗣日久，
吾不忍奪也。

觀汝兄弟似不相容，
同處 dm#dm00449@京邑 ，
必有紛競，
當遣汝還行臺，
居 dm#dm04788@洛陽 ，
自 dm#dm08318@陝 以東皆主之。

仍命汝建天子旌旗，
如 dyn#ch129@漢  rm@梁孝王 故事。」

 rm#r01602@世民 涕泣，
辭以不欲遠離膝下，
上曰：
「天下一家，
東、西兩都，
道路甚邇，
吾思汝即往，
毋煩悲也。」

將行，
 rm#r01078@建成 、 rm#r01016@元吉 相與謀曰：
「 rm#r01602@秦王 若至 dm#dm04788@洛陽 ，
有土地甲兵，
不可復制；
不如留之 dm#dm08170@長安 ，
則一匹夫耳，
取之易矣。」

乃密令數人上封事，
言「 rm#r01602@秦王 左右聞往 dm#dm04788@洛陽 ，
無不喜躍，
觀其志趣，
恐不復來。」

又遣近幸之臣以利害説上，
上意遂移，
事復中止。


# p 

 rm#r01078@建成 、 rm#r01016@元吉 與後宮日夜譖訴 rm#r01602@世民 於上，
上信之，
將罪 rm#r01602@世民 。

 rm#r03915@陳叔達 諫曰：
「 rm#r01602@秦王 有大功於天下，
不可黜也。

且性剛烈，
若加挫抑，
恐不勝憂憤，
或有不測之疾，
陛下悔之何及！」

上乃止。

 rm#r01016@元吉 密請殺 rm#r01602@秦王 ，
上曰：
「彼有定天下之功，
罪状未著，
何以爲辭？」
 rm#r01016@元吉 曰：
「 rm#r01602@秦王 初平 dm#dm03880@東都 ，
顧望不還，
散錢帛以樹私恩，
又違敕命，
非反而何！

但應速殺，
何患無辭！」

上不應。

# p 

 rm#r01602@秦 府僚屬皆憂懼不知所出。

行臺考功郎中 rm#r01377@房玄齡 謂比部郎中 rm#r03856@長孫無忌 曰：
「今嫌隙已成，
一旦禍機竊發，
豈惟府朝塗地，
乃實社稷之憂；
莫若勸王行 rm#rt0104@周公 之事以安家國。

存亡之機，
間不容髮，
正在今日！」

 rm#r03856@無忌 曰：
「吾懷此久矣，
不敢發口；
今吾子所言，
正合吾心，
謹當白之。」

乃入言 rm#r01602@世民 。

 rm#r01602@世民 召 rm#r01377@玄齡 謀之，
 rm#r01377@玄齡 曰：
「大王功蓋天地，
當承大業；
今日憂危，
乃天贊也，
願大王勿疑。」

乃與府屬 rm#r02033@杜如晦 共勸 rm#r01602@世民 誅 rm#r01078@建成 、 rm#r01016@元吉 。
# p 

 rm#r01078@建成 、 rm#r01016@元吉 以 rm#r01602@秦 府多驍將，
欲誘之使爲己用，
密以金銀器一車贈左二副護軍 rm#r00862@尉遲敬徳 ，
幷以書招之曰：
「願迂長者之眷，
以敦布衣之交。」

 rm#r00862@敬徳 辭曰：
「 rm#r00862@敬徳 ，
蓬戸甕牖之人，
遭 dyn#ch174@隋 末亂離，
久淪逆地，
罪不容誅。

 rm#r01602@秦王 賜以更生之恩，
今又策名藩邸，
唯當殺身以爲報；
於殿下無功，
不敢謬當重賜。

若私交殿下，
乃是貳心，
徇利忘忠，
殿下亦何所用！」

 rm#r01078@建成 怒，
遂與之絶。

 rm#r00862@敬徳 以告 rm#r01602@世民 ，
 rm#r01602@世民 曰：
「公心如山嶽，
雖積金至斗，
知公不移。

相遺但受，
何所嫌也！

且得以知其陰計，
豈非良策！

不然，
禍將及公。」

既而 rm#r01016@元吉 使壯士夜刺 rm#r00862@敬徳 ，
 rm#r00862@敬徳 知之，
洞開重門，
安臥不動，
刺客屡至其庭，
終不敢入。

 rm#r01016@元吉 乃譖 rm#r00862@敬徳 於上，
下詔獄訊治，
將殺之，
 rm#r01602@世民 固請，
得免。

又譖左一馬軍總管 rm#r02983@程知節 ，
出爲 dm#dm02708@康州 刺史。

 rm#r02983@知節 謂 rm#r01602@世民 曰：
「大王股肱羽翼盡矣，
身何能久！

 rm#r02983@知節 以死不去，
願早決計。」

又以金帛誘右二護軍 rm#r02342@段志玄 ，
 rm#r02342@志玄 不從。

 rm#r01078@建成 謂 rm#r01016@元吉 曰：
「 rm#r01602@秦 府智略之士，
可憚者獨 rm#r01377@房玄齡 、 rm#r02033@杜如晦 耳。」

皆譖之於上而逐之。
# p 

 rm#r01602@世民 腹心唯 rm#r03856@長孫無忌 尚在府中，
與其舅 dm#dm08502@雍州 治中 rm#r04217@高士廉 、右候車騎將軍 dm#dm00129@三水  rm#r00124@侯君集 及 rm#r00862@尉遲敬徳 等，
日夜勸 rm#r01602@世民 誅 rm#r01078@建成 、 rm#r01016@元吉 。

 rm#r01602@世民 猶豫未決，
問於 dm#dm08619@靈州 大都督 rm#r02009@李靖 ，
 rm#r02009@靖 辭；
問於行軍總管 rm#r01299@李世勣 ，
 rm#r01299@世勣 辭；
 rm#r01602@世民 由是重二人。

# p 

會突厥 rm@郁射設 將數萬騎屯 dm#dm04650@河 南，
入塞，
圍 dm#dm05515@烏城 ，
 rm#r01078@建成 薦 rm#r01016@元吉 代 rm#r01602@世民 督諸軍北征，
上從之，
命 rm#r01016@元吉 督右武衞大將軍 rm#r03089@李藝 、天紀將軍 rm#r05287@張瑾 等救 dm#dm05515@烏城 。

 rm#r01016@元吉 請 rm#r00862@尉遲敬徳 、 rm#r02983@程知節 、 rm#r02342@段志玄 及 rm#r01602@秦 府右三統軍 rm#r02977@秦叔寶 等與之偕行，
簡閲 rm#r01602@秦王 帳下精鋭之士以益 rm#r01016@元吉 軍。

率更丞 rm#r05640@王晊 密告 rm#r01602@世民 曰：
「太子語 rm#r01016@齊王 ：
『今汝得 rm#r01602@秦王 驍將精兵，
擁數萬之衆，
吾與 rm#r01602@秦王 餞汝於 dm#dm03450@昆明池 ，
使壯士拉殺之於幕下，
奏云暴卒，
主上宜無不信。

吾當使人進説，
令授吾國事。

 rm#r00862@敬徳 等既入汝手，
宜悉坑之，
孰敢不服！』」

 rm#r01602@世民 以 rm#r05640@晊 言告 rm#r03856@長孫無忌 等，
 rm#r03856@無忌 等勸 rm#r01602@世民 先事圖之。

 rm#r01602@世民 歎曰：
「骨肉相殘，
古今大惡。

吾誠知禍在朝夕，
欲俟其發，
然後以義討之，
不亦可乎！」

 rm#r00862@敬徳 曰：
「人情誰不愛其死！

今衆人以死奉王，
乃天授也。

禍機垂發，
而王猶晏然不以爲憂，
大王縱自輕，
如宗廟社稷何！

大王不用 rm#r00862@敬徳 之言，
 rm#r00862@敬徳 將竄身草澤，
不能留居大王左右，
交手受戮也！」

 rm#r03856@無忌 曰：
「不從 rm#r00862@敬徳 之言，
事今敗矣。

 rm#r00862@敬徳 等必不爲王有，
 rm#r03856@無忌 亦當相隨而去，
不能復事大王矣！」

 rm#r01602@世民 曰：
「吾所言亦未可全棄，
公更圖之。」

 rm#r00862@敬徳 曰：
「王今處事有疑，
非智也；
臨難不決，
非勇也。

且大王素所畜養勇士八百餘人，
在外者今已入宮，
擐甲執兵，
事勢已成，
大王安得已乎！」

# p 

 rm#r01602@世民 訪之府僚，
皆曰：
「 rm#r01016@齊王 凶戾，
終不肯事其兄。

比聞護軍 rm#r05804@薛實 嘗謂 rm#r01016@齊王 曰：
『大王之名，
合之成唐字，
大王終主 dyn#ch100@唐 祀。』

 rm#r01016@齊王 喜曰：
『但除 rm#r01602@秦王 ，
取東宮如反掌耳。』

彼與太子謀亂未成，
已有取太子之心。

亂心無厭，
何所不爲！

若使二人得志，
恐天下非復 dyn#ch100@唐 有。

以大王之賢，
取二人如拾地芥耳，
奈何徇匹夫之節，
忘社稷之計乎！」

 rm#r01602@世民 猶未決，
衆曰：
「大王以 rm#rt0007@舜 爲何如人？」
曰：
「聖人也。」

衆曰：
「使 rm#rt0007@舜 浚井不出，
則爲井中之泥，
塗廩不下，
則爲廩上之灰，
安能澤被天下，
法施後世乎！

是以小杖則受，
大杖則走，
蓋所存者大故也。」

 rm#r01602@世民 命卜之，
幕僚 rm#r01115@張公謹 自外來，
取龜投地，
曰：
「卜以決疑；
今事在不疑，
尚何卜乎！

卜而不吉，
庸得已乎！」

於是定計。
見之
# p 

 rm#r01602@世民 令 rm#r03856@無忌 密召 rm#r01377@房玄齡 等，
曰：
「敕旨不聽復事王；
今若私謁，
必坐死，
不敢奉教！」

 rm#r01602@世民 怒，
謂 rm#r00862@敬徳 曰：
「 rm#r01377@玄齡 、 rm#r02033@如晦 豈叛我邪！」

取所佩刀授 rm#r00862@敬徳 曰：
「公往觀之，
若無來心，
可斷其首以來。」

 rm#r00862@敬徳 往，
與 rm#r03856@無忌 共諭之曰：
「王已決計，
公宜速入共謀之。

吾屬四人，
不可羣行道中。」

乃令 rm#r01377@玄齡 、 rm#r02033@如晦 著道士服，
與 rm#r03856@無忌 倶入，
 rm#r00862@敬徳 自他道亦至。
# p 

己未，
太白復經天。

 rm#r00140@傅奕 密奏：
「太白見 dm#dm06273@秦 分，
 rm#r01602@秦王 當有天下。」

上以其状授 rm#r01602@世民 。

於是 rm#r01602@世民 密奏 rm#r01078@建成 、 rm#r01016@元吉 淫亂後宮，
且曰：
「臣於兄弟無絲毫負，
今欲殺臣，
似爲 rm#r02590@世充 、 rm#r03028@建徳 報讎。

臣今枉死，
永違君親，
魂歸地下，
實恥見諸賊！」

上省之，
愕然，
報曰：
「明當鞫問，
汝宜早參。」


# p 

庚申，
 rm#r01602@世民 帥 rm#r03856@長孫無忌 等入，
伏兵於 dm#dm05694@玄武門 。

 rm#r05260@張婕妤 竊知 rm#r01602@世民 表意，
馳語 rm#r01078@建成 。

 rm#r01078@建成 召 rm#r01016@元吉 謀之，
 rm#r01016@元吉 曰：
「宜勒宮府兵，
託疾不朝，
以觀形勢。」

 rm#r01078@建成 曰：
「兵備已嚴，
當與弟入參，
自問消息。」

乃倶入，
趣 dm#dm05694@玄武門 。

上時已召 rm#r03424@裴寂 、 rm#r03249@蕭瑀 、 rm#r03915@陳叔達 等，
欲按其事。

# p 

 rm#r01078@建成 、 rm#r01016@元吉 至 dm#dm06714@臨湖殿 ，
覺變，
即跋馬東歸宮府。

 rm#r01602@世民 從而呼之，
 rm#r01016@元吉 張弓射 rm#r01602@世民 ，
再三不彀，
 rm#r01602@世民 射 rm#r01078@建成 ，
殺之。

 rm#r00862@尉遲敬徳 將七十騎繼至，
左右射 rm#r01016@元吉 墜馬。

 rm#r01602@世民 馬逸入林下，
爲木枝所絓，
墜不能起。

 rm#r01016@元吉 遽至，
奪弓將扼之，
 rm#r00862@敬徳 躍馬叱之。

 rm#r01016@元吉 歩欲趣 dm#dm04266@武徳殿 ，
 rm#r00862@敬徳 追射，
殺之。

翊衞車騎將軍 dm#dm08850@馮翊  rm#r04200@馮立 聞 rm#r01078@建成 死，
歎曰：
「豈有生受其恩而死逃其難乎！

」
乃與副護軍 rm#r03311@薛萬徹 、屈咥直府左車騎 dm#dm06979@萬年  rm#r03535@謝叔方 帥東宮、 rm#r01016@齊 府精兵二千馳趣 dm#dm05694@玄武門 。

 rm#r01115@張公謹 多力，
獨閉關以拒之，
不得入。

雲麾將軍 rm#r01400@敬君弘 掌宿衞兵，
屯 dm#dm05694@玄武門 ，
挺身出戰，
所親止之曰：
「事未可知，
且徐觀變，
俟兵集，
成列而戰，
未晩也。」

 rm#r01400@君弘 不從，
與中郎將 rm#r05112@呂世衡 大呼而進，
皆死之。

 rm#r01400@君弘 ，
 rm#r06611@顯雋 之曾孫也。

守門兵與 rm#r03311@萬徹 等力戰良久，
 rm#r03311@萬徹 鼓譟欲攻 rm#r01602@秦 府，
將士大懼；
 rm#r00862@尉遲敬徳 持 rm#r01078@建成 、 rm#r01016@元吉 首示之，
宮府兵遂潰。

 rm#r03311@萬徹 與數十騎亡入 dm#dm06424@終南山 。

 rm#r04200@馮立 既殺 rm#r01400@敬君弘 ，
謂其徒曰：
「亦足以少報太子矣！」

遂解兵，
逃於野。
# p 

上方泛舟 dm#dm04898@海池 ，
 rm#r01602@世民 使 rm#r00862@尉遲敬徳 入宿衞，
 rm#r00862@敬徳 擐甲持矛，
直至上所。

上大驚，
問曰：
「今日亂者誰邪？
卿來此何爲？」
對曰：
「 rm#r01602@秦王 以太子、 rm#r01016@齊王 作亂，
舉兵誅之，
恐驚動陛下，
遣臣宿衞。」

上謂 rm#r03424@裴寂 等曰：
「不圖今日乃見此事，
當如之何？」
 rm#r03249@蕭瑀 、 rm#r03915@陳叔達 曰：
「 rm#r01078@建成 、 rm#r01016@元吉 本不預義謀，
又無功於天下，
疾 rm#r01602@秦王 功高望重，
共爲姦謀。

今 rm#r01602@秦王 已討而誅之，
 rm#r01602@秦王 功蓋宇宙，
率土歸心，
陛下若處以元良，
委之國事，
無復事矣！」

上曰：
「善！

此吾之夙心也。」

時宿衞及 rm#r01602@秦 府兵與二宮左右戰猶未已，
 rm#r00862@敬徳 請降手敕，
令諸軍竝受 rm#r01602@秦王 處分，
上從之。

天策府司馬 rm#r00750@宇文士及 自 dm#dm03786@東上閤門 出宣敕，
衆然後定。

上又使黄門侍郎 rm#r03452@裴矩 至東宮曉諭諸將卒，
皆罷散。

上乃召 rm#r01602@世民 ，
撫之曰：
「近日以來，
幾有投杼之惑。」

 rm#r01602@世民 跪而吮上乳，
號慟久之。

# p 

 rm#r01078@建成 子 rm#xjts14076@安陸王承道 、 rm#xjts14011@河東王承徳 、 rm#xjts13975@武安王承訓 、 rm#xjts14104@汝南王承明 、 rm#xjts14116@鉅鹿王承義 ，
 rm#r01016@元吉 子 rm#xjts14054@梁郡王承業 、 rm#xjts14009@漁陽王承鸞 、 rm#xjts14023@普安王承奬 、 rm#xjts14074@江夏王承裕 、 rm#xjts13966@義陽王承度 皆坐誅，
仍絶屬籍。
# p 

初，
 rm#r01078@建成 許 rm#r01016@元吉 以正位之後，
立爲太弟，
故 rm#r01016@元吉 爲之盡死。

諸將欲盡誅 rm#r01078@建成 、 rm#r01016@元吉 左右百餘人，
籍沒其家，
 rm#r00862@尉遲敬徳 固爭曰：
「罪在二凶，
既伏其誅；
若及支黨，
非所以求安也！」

乃止。

是日，
下詔：
「赦天下。

凶逆之罪，
止於 rm#r01078@建成 、 rm#r01016@元吉 ，
自餘黨與，
一無所問。

其僧、尼、道士、女冠竝宜依舊。

國家庶事，
皆取 rm#r01602@秦王 處分。」


# p 

辛酉，
 rm#r04200@馮立 、 rm#r03535@謝叔方 皆自出；
 rm#r03311@薛萬徹 亡匿，
 rm#r01602@世民 屡使踰之，
乃出。

 rm#r01602@世民 曰：
「此皆忠於所事，
義士也。」

釋之。
# p 

癸亥，
立 rm#r01602@世民 爲皇太子。

又詔：
「自今軍國庶事，
無大小悉委太子處決，
然後聞奏。」

# p 

臣 rm@光 曰：
「立嫡以長，
禮之正也。

然 rm#r04258@高祖 所以有天下，
皆 rm#r01602@太宗 之功；
 rm#r01078@隱太子 以庸劣居其右，
地嫌勢逼，
必不相容。

曏使 rm#r04258@高祖 有 rm#rt0063@文王 之明，
 rm#r01078@隱太子 有 rm@泰伯 之賢，
 rm#r01602@太宗 有 rm@子臧 之節，
則亂何自而生矣！

既不能然，
 rm#r01602@太宗 始欲俟其先發，
然後應之，
如此，
則事非獲已，
猶爲愈也。

既而爲羣下所迫，
遂至蹀血禁門，
推刃同氣，
貽譏千古，
惜哉！

夫創業垂統之君，
子孫之所儀刑也，
彼 rm#r01656@中 、 rm#r02004@明 、 rm#r01661@肅 、 rm#r01617@代 之傳繼，
得非有所指擬以爲口實乎！」


# p 

戊辰，
以 rm#r00750@宇文士及 爲太子詹事，
 rm#r03856@長孫無忌 、 rm#r02033@杜如晦 爲左庶子，
 rm#r04217@高士廉 、 rm#r01377@房玄齡 爲右庶子，
 rm#r00862@尉遲敬徳 爲左衞率，
 rm#r02983@程知節 爲右衞率，
 rm#r03353@虞世南 爲中舍人，
 rm#r03473@褚亮 爲舍人，
 rm#r00630@姚思廉 爲洗馬。

悉以 rm#r01016@齊王 國司金帛什器賜 rm#r00862@敬徳 。

初，
洗馬 rm#r04294@魏徵 常勸太子 rm#r01078@建成 早除 rm#r01602@秦王 ，
及 rm#r01078@建成 敗，
 rm#r01602@世民 召 rm#r04294@徵 謂曰：
「汝何爲離間我兄弟！」

衆爲之危懼，
 rm#r04294@徵 舉止自若，
對曰：
「先太子早從 rm#r04294@徵 言，
必無今日之禍。」

 rm#r01602@世民 素重其才，
改容禮之，
引爲詹事主簿。

亦召 rm#r02672@王珪 、 rm#r04036@韋挺 於 dm#dm02536@巂州 ，
皆以爲諫議大夫。
# p 

 rm#r01602@世民 命縱禁苑鷹犬，
罷四方貢獻，
聽百官各陳治道，
政令簡肅，
中外大悦。
# p 

以 rm#r00876@屈突通 爲 dm#dm08324@陝東道 行臺左僕射，
鎭 dm#dm04788@洛陽 。

# p 

 dm#dm05982@益州 行臺僕射 rm#r03047@竇軌 與行臺尚書 rm#r04084@韋雲起 、 rm#r05945@郭行方 不協。

 rm#r04084@雲起 弟 rm@慶儉 及宗族多事太子 rm#r01078@建成 ，
 rm#r01078@建成 死，
 rm#r03047@軌 誣 rm#r04084@雲起 與 rm#r01078@建成 同反，
收斬之。

 rm#r05945@行方 懼，
逃奔 dm#dm08170@京師 ，
 rm#r03047@軌 追之，
不及。
# p 

吐谷渾寇 dm#dm02437@岷州 。

# p 

突厥寇 dm#dm08464@隴州 ；
辛未，
寇 dm#dm05113@渭州 ；
遣右衞大將軍 rm#r02112@柴紹 撃之。

# p 

廢 dm#dm05982@益州 大行臺，
置大都督府。
# p 

壬申，
上以手詔賜 rm#r03424@裴寂 等曰：
「朕當加尊號爲太上皇。」

# p 

辛巳，
 dm#dm02689@幽州 大都督 rm#r01070@廬江王瑗 反，
右領軍將軍 rm#r02607@王君廓 殺之，
傳首。
# p 

初，
上以 rm#r01070@瑗 懦怯非將帥才，
使 rm#r02607@君廓 佐之。

 rm#r02607@君廓 故羣盜，
勇悍險詐，
 rm#r01070@瑗 推心倚仗之，
許爲婚姻。

太子 rm#r01078@建成 謀害 rm#r01602@秦王 ，
密與 rm#r01070@瑗 相結。

 rm#r01078@建成 死，
詔遣通事舍人 rm#r00929@崔敦禮 馳驛召 rm#r01070@瑗 。

 rm#r01070@瑗 心不自安，
謀於 rm#r02607@君廓 。

 rm#r02607@君廓 欲取 rm#r01070@瑗 以爲功，
乃説曰：
「大王若入，
必無全理。

今擁兵數萬，
奈何受單使之召，
自投罔罟乎！」

因相與泣。

 rm#r01070@瑗 曰：
「我今以命託公，
舉事決矣。

」
乃劫 rm#r00929@敦禮 ，
問以 dm#dm08170@京師 機事；
 rm#r00929@敦禮 不屈，
 rm#r01070@瑗 囚之。

發驛徵兵，
且召 dm#dm05599@燕州 刺史 rm#xjts01894@王詵 赴 dm#dm07104@薊 ，
與之計事。

兵曹參軍 rm#r05608@王利渉 説 rm#r01070@瑗 曰：
「 rm#r02607@王君廓 反覆，
不可委以機柄，
宜早除去，
以 rm#xjts01894@王詵 代之。」

 rm#r01070@瑗 不能決。

 rm#r02607@君廓 知之，
往見 rm#xjts01894@詵 ，
 rm#xjts01894@詵 方沐，
握髮而出，
 rm#r02607@君廓 手斬之，
持其首告衆曰：
「 rm#r01070@李瑗 與 rm#xjts01894@王詵 同反，
囚執敕使，
自徵兵。

今 rm#xjts01894@詵 已誅，
獨有 rm#r01070@李瑗 ，
無能爲也。

汝寧隨 rm#r01070@瑗 族滅乎，
欲從我以取富貴乎？」
衆皆曰：
「願從公討賊。」

 rm#r02607@君廓 乃帥其麾下千餘人，
踰西城而入，
 rm#r01070@瑗 不之覺；
 rm#r02607@君廓 入獄出 rm#r00929@敦禮 ，
 rm#r01070@瑗 始知之，
遽帥左右數百人被甲而出，
遇 rm#r02607@君廓 於門外。

 rm#r02607@君廓 謂 rm#r01070@瑗 衆曰：
「 rm#r01070@李瑗 爲逆，
汝何爲隨之入湯火乎！」

衆皆棄兵而潰。

唯 rm#r01070@瑗 獨存，
罵 rm#r02607@君廓 曰：
「小人賣我，
行自及矣！」

遂執 rm#r01070@瑗 ，
縊之。

壬午，
以 rm#r02607@王君廓 爲左領軍大將軍兼 dm#dm02689@幽州 都督，
以 rm#r01070@瑗 家口賜之。

 rm#r00929@敦禮 ，
 rm#r06578@仲方 之孫也。


# p 

乙酉，
罷天策府。

# p 

秋，
七月，
己丑，
 rm#r02112@柴紹 破突厥於 dm#dm06279@秦州 ，
斬特勒一人，
士卒首千餘級。

# p 

以 rm#r01602@秦 府護軍 rm#r02977@秦叔寶 爲左衞大將軍，
又以 rm#r02983@程知節 爲右武衞大將軍，
 rm#r00862@尉遲敬徳 爲右武候大將軍。

# p 

壬辰，
以 rm#r04217@高士廉 爲侍中，
 rm#r01377@房玄齡 爲中書令，
 rm#r03249@蕭瑀 爲左僕射，
 rm#r03856@長孫無忌 爲吏部尚書，
 rm#r02033@杜如晦 爲兵部尚書。

癸巳，
以 rm#r00750@宇文士及 爲中書令，
 rm#r00851@封徳彞 爲右僕射；
又以前天策府兵曹參軍 rm#r02056@杜淹 爲御史大夫，
中書舍人 rm#r04140@顏師古 、 rm#r05078@劉林甫 爲中書侍郎，
左衞副率 rm#r00124@侯君集 爲左衞將軍，
左虞候 rm#r02342@段志玄 爲驍衞將軍，
副護軍 rm#r03311@薛萬徹 爲右領軍將軍，
右内副率 rm#r01115@張公謹 爲右武候將軍，
右監門率 rm#r05977@長孫安業 爲右監門將軍，
右内副率 rm#r01702@李客師 爲領左右軍將軍。

 rm#r05977@安業 ，
 rm#r03856@無忌 之兄；
 rm#r01702@客師 ，
 rm#r02009@靖 之弟也。


# p 

太子 rm#r01078@建成 、 rm#r01016@齊王元吉 之黨散亡在民間，
雖更赦令，
猶不自安，
徼幸者爭告捕以邀賞。

諫議大夫 rm#r02672@王珪 以啓太子。

丙子，
太子下令：
「六月四日已前事連東宮及 rm#r01016@齊王 ，
十七日前連 rm#r01070@李瑗 者，
竝不得相告言，
違者反坐。」


# p 

丁酉，
遣諫議大夫 rm#r04294@魏徵 宣慰 dm#dm02403@山東 ，
聽以便宜從事。

 rm#r04294@徵 至 dm#dm06177@磁州 ，
遇州縣錮送前太子千牛 rm#r05384@李志安 、 rm#r01016@齊王 護軍 rm#r01757@李思行 詣京師，
 rm#r04294@徵 曰：
「吾受命之日，
前宮、 rm#r01016@齊 府左右皆赦不問；
今復送 rm#r01757@思行 等，
則誰不自疑！

雖遣使者，
人誰信之！

吾不可以顧身嫌，
不爲國慮。

且既蒙國士之遇，
敢不以國士報之乎！」

遂皆解縱之。

太子聞之，
甚喜。
# p 

右衞率府鎧曹參軍 rm#r00510@唐臨 出爲 dm#dm06986@萬泉 丞，
縣有繋囚十許人，
會春雨，
臨縱之，
使歸耕種，
皆如期而返。

 rm#r00510@臨 ，
 rm#r06542@令則 之弟子也。

# p 

八月，
丙辰，
突厥遣使請和。

# p 

壬戌，
吐谷渾遣使請和。

# p 

癸亥，
制傳位於太子；
太子固辭，
不許。

甲子，
 rm#r01602@太宗 即皇帝位於東宮 dm#dm08766@顯徳殿 ，
赦天下；
 dm#dm08280@關 内及 dm#dm07017@蒲 、 dm#dm06823@芮 、 dm#dm07179@虞 、 dm#dm04746@泰 、 dm#dm08318@陝 、 dm#dm09198@鼎 六州免二年租調，
自餘給復一年。

# p 

詔以「宮女衆多，
幽閟可愍，
宜簡出之，
各歸親戚，
任其適人。」
癸未
# p 

初，
稽胡酋長 rm#r06157@劉仚成 帥衆降 rm#r02125@梁師都 ，
 rm#r02125@師都 信讒，
殺之，
由是所部猜懼，
多來降者。

 rm#r02125@師都 浸衰弱，
乃朝于突厥，
爲之畫策，
勸令入寇。

於是 rm#rz0034@頡利 、 rm@突利 二可汗合兵十餘萬寇涇州，
進至 dm#dm04228@武功 ，
 dm#dm08170@京師 戒嚴。
# p 

丙子，
立𡚱 rm#r03854@長孫氏 爲皇后。

后少好讀書，
造次必循禮法，
上爲 rm#r01602@秦王 ，
與太子 rm#r01078@建成 、 rm#r01016@齊王元吉 有隙，
后奉事 rm#r04258@高祖 ，
承順𡚱嬪，
彌縫其闕，
甚有内助。

及正位中宮，
務存節儉，
服御取給而已。

上深重之，
嘗與之議賞罰，
后辭曰：
「『牝雞之晨，
唯家之索，』
妾婦人，
安敢豫聞政事！」

固問之，
終不對。
# p 

己卯，
突厥進寇 dm#dm08924@高陵 。

辛巳，
 dm#dm04925@涇州道 行軍總管 rm#r00862@尉遲敬徳 與突厥戰於 dm#dm04928@涇陽 ，
大破之。

獲其俟斤 rm@阿史徳烏沒啜 ，
斬首千餘級。
# p 

癸未，
 rm#rz0034@頡利可汗 進至 dm#dm05117@渭水  dm#dm00545@便橋 之北，
遣其腹心 rm#r00582@執失思力 入見，
以觀虚實。

 rm#r00582@思力 盛稱「 rm#rz0034@頡利 與 rm@突利 二可汗將兵百萬，
今至矣。」

上讓之曰：
「吾與汝可汗面結和親，
贈遺金帛，
前後無算。

汝可汗自負盟約，
引兵深入，
於我無愧！

汝雖戎狄，
亦有人心，
何得全忘大恩，
自誇強盛！

我今先斬汝矣！」

 rm#r00582@思力 懼而請命。

 rm#r03249@蕭瑀 、 rm#r00851@封徳彞 請禮遣之。

上曰：
「我今遣還，
虜謂我畏之，
愈肆憑陵。」

乃囚 rm#r00582@思力 於門下省。
# p 

上自出 dm#dm05694@玄武門 ，
與 rm#r04217@高士廉 、 rm#r01377@房玄齡 等六騎徑詣 dm#dm05117@渭水 上，
與 rm#rz0034@頡利 隔水而語，
責以負約。

突厥大驚，
皆下馬羅拜。

俄而諸軍繼至，
旌甲蔽野，
 rm#rz0034@頡利 見 rm#r00582@執失思力 不返，
而上挺身輕出，
軍容甚盛，
有懼色。

上麾諸軍使卻而布陳，
獨留與 rm#rz0034@頡利 語。

 rm#r03249@蕭瑀 以上輕敵，
叩馬固諫，
上曰：
「吾籌之已熟，
非卿所知。

突厥所以敢傾國而來，
直抵郊甸者，
以我國内有難，
朕新即位，
謂我不能抗禦故也。

我若示之以弱，
閉門拒守，
虜必放兵大掠，
不可復制。

故朕輕騎獨出，
示若輕之；
又震曜軍容，
使之必戰；
出虜不意，
使之失圖。

虜入我地既深，
必有懼心，
故與戰則克，
與和則固矣。

制服突厥，
在此一舉。

卿第觀之！」

是日，
 rm#rz0034@頡利 來請和，
詔許之。

上即日還宮。

乙酉，
又幸城西，
斬白馬，
與 rm#rz0034@頡利 盟于 dm#dm00545@便橋 之上。

突厥引兵退。
之知
# p 

 rm#r03249@蕭瑀 請於上曰：
「突厥未和之時，
諸將爭請戰，
陛下不許，
臣等亦以爲疑，
既而虜自退，
其策安在？」
上曰：
「吾觀突厥之衆雖多而不整，
君臣之志唯賄是求，
當其請和之時，
可汗獨在水西，
達官皆來謁我，
我若醉而縛之，
因襲撃其衆，
勢如拉朽。

又命 rm#r03856@長孫無忌 、 rm#r02009@李靖 伏兵於 dm#dm02689@幽州 以待之，
虜若奔歸，
伏兵邀其前，
大軍躡其後，
覆之如反掌耳。

所以不戰者，
吾即位日淺，
國家未安，
百姓未富，
且當靜以撫之。

一與虜戰，
所損甚多；
虜結怨既深，
懼而脩備，
則吾未可以得志矣。

故卷甲韜戈，
啗以金帛，
彼既得所欲，
理當自退，
志意驕惰，
不復設備，
然後養威伺釁，
一舉可滅也。

將欲取之，
必固與之，
此之謂矣。

卿知之乎？」
 rm#r03249@瑀 再拜曰：
「非所及也。」


# p 

九月，
突厥 rm#rz0034@頡利 獻馬三千匹，
羊萬口；
上不受，
但詔歸所掠 dm#dm00255@中國 戸口，
徵 rm#r02480@温彦博 還朝。


# p 

丁未，
上引諸衞將卒習射於 dm#dm08766@顯徳殿 庭，
諭之曰：
「戎狄侵盜，
自古有之，
患在邊境少安，
則人主逸遊忘戰，
是以寇來莫之能禦。

今朕不使汝曹穿池築苑，
專習弓矢，
居閒無事，
則爲汝師，
突厥入寇，
則爲汝將，
庶幾 dm#dm00255@中國 之民可以少安乎！」

於是日引數百人教射於殿庭，
上親臨試，
中多者賞以弓、刀、帛，
其將帥亦加上考。

羣臣多諫曰：
「於律，
以兵刃至御在所者絞。

今使卑碎之人張弓挾矢於軒陛之側，
陛下親在其間，
萬一有狂夫竊發，
出於不意，
非所以重社稷也。

」
 dm#dm08730@韓州 刺史 rm#r05194@封同人 詐乘驛馬入朝切諫。

上皆不聽，
曰：
「王者視四海如一家，
封域之内，
皆朕赤子，
朕一一推心置其腹中，
奈何宿衞之士亦加猜忌乎！」

由是人思自勵，
數年之間，
悉爲精鋭。
# p 

上嘗言：
「吾自少經略四方，
頗知用兵之要，
毎觀敵陳，
則知其強弱，
常以吾弱當其強，
強當其弱。

彼乘吾弱，
逐奔不過數十百歩，
吾乘其弱，
必出其陳後反撃之，
無不潰敗，
所以取勝，
多在此也！」

# p 

己酉，
上面定勳臣 rm#r03856@長孫無忌 等爵邑，
命 rm#r03915@陳叔達 於殿下唱名示之，
且曰：
「朕敍卿等勳賞或未當，
宜各自言。」

於是諸將爭功，
紛紜不已。

 rm#r02450@淮安王神通 曰：
「臣舉兵 dm#dm08288@關西 ，
首應義旗，
今 rm#r01377@房玄齡 、 rm#r02033@杜如晦 等專弄刀筆，
功居臣上，
臣竊不服。」

上曰：
「義旗初起，
叔父雖首唱舉兵，
蓋亦自營脱禍。

及 rm#r03028@竇建徳 呑噬 dm#dm02403@山東 ，
叔父全軍覆沒；
 rm#r00337@劉黒闥 再合餘燼，
叔父望風奔北。

 rm#r01377@玄齡 等運籌帷幄，
坐安社稷，
論功行賞，
固宜居叔父之先。

叔父，
國之至親，
朕誠無所愛，
但不可以私恩濫與勳臣同賞耳！

」
諸將乃相謂曰：
「陛下至公，
雖 rm#r02450@淮安王 尚無所私，
吾儕何敢不安其分。」

遂皆悦服。

 rm#r01377@房玄齡 嘗言：
「 rm#r01602@秦 府舊人未遷官者，
皆嗟怨曰：
『吾屬奉事左右，
幾何年矣，
今除官，
返出前宮、 rm#r01016@齊 府人之後。』」

上曰：
「王者至公無私，
故能服天下之心。

朕與卿輩日所衣食，
皆取諸民者也。

故設官分職，
以爲民也，
當擇賢才而用之，
豈以新舊爲先後哉！

必也新而賢，
舊而不肖，
安可捨新而取舊乎！

今不論其賢不肖而直言嗟怨，
豈爲政之體乎！」

# p 

詔：
「民間不得妄立妖祠。

自非卜筮正術，
其餘雜占，
悉從禁絶。」

# p 

上於 dm#dm02884@弘文殿 聚四部書二十餘萬卷，
置 dm#dm02885@弘文館 於殿側，
精選天下文學之士 rm#r03353@虞世南 、 rm#r03473@褚亮 、 rm#r00630@姚思廉 、 rm#r02288@歐陽詢 、 rm#r03201@蔡允恭 、 rm#r03244@蕭徳言 等，
以本官兼學士，
令更日宿直，
聽朝之隙，
引入内殿，
講論前言往行，
商榷政事，
或至夜分乃罷。

又取三品已上子孫充 dm#dm02885@弘文館 學士。

士生
# p 

冬，
十月，
丙辰朔，
日有食之。
# p 

詔追封故太子 rm#r01078@建成 爲 rm#r01078@息王 ，
諡曰 rm#r01078@隱 ；
 rm#r01016@齊王  rm#r01016@元吉 爲 rm#r01016@剌王 ，
以禮改葬。

葬日，
上哭之於 dm#dm02192@宜秋門 ，
甚哀。

 rm#r04294@魏徵 、 rm#r02672@王珪 表請陪送至墓所，
上許之，
命宮府舊僚皆送葬。諡曰剌剌海陵
# p 

癸亥，
立皇子 rm#r01026@中山王承乾 爲太子，
生八年矣。

# p 

庚辰，
初定功臣實封有差。

# p 

初，
 rm#r03249@蕭瑀 薦 rm#r00851@封徳彞 於上皇，
上皇以爲中書令。

及上即位，
 rm#r03249@瑀 爲左僕射，
 rm#r00851@徳彞 爲右僕射。

議事已定，
 rm#r00851@徳彞 數反於上前，
由是有隙。

時 rm#r01377@房玄齡 、 rm#r02033@杜如晦 新用事，
皆疏 rm#r03249@瑀 而親 rm#r00851@徳彞 ，
 rm#r03249@瑀 不能平，
遂上封事論之，
辭指寥落，
由是忤旨。

會 rm#r03249@瑀 與 rm#r03915@陳叔達 忿爭於上前，
庚辰，
 rm#r03249@瑀 、 rm#r03915@叔達 皆坐不敬，
免官。
之
# p 

甲申，
民部尚書 rm#r03452@裴矩 奏「民遭突厥暴踐者，
請戸給絹一匹。」

上曰：
「朕以誠信御下，
不欲虚有存恤之名而無其實，
戸有大小，
豈得雷同給賜乎！」

於是計口爲率。
# p 

初，
上皇欲強宗室以鎭天下，
故皇再從、三從弟及兄弟之子，
雖童孺皆爲王，
王者數十人。

上從容問羣臣：
「徧封宗子，
於天下利乎？」
 rm#r00851@封徳彞 對曰：
「前世唯皇子及兄弟乃爲王，
自餘非有大功，
無爲王者。

上皇敦睦九族，
大封宗室，
自 dyn#ch129@兩漢 以來未有如今之多者。

爵命既崇，
多給力役，
恐非示天下以至公也！」

上曰：
「然。

朕爲天子，
所以養百姓也，
豈可勞百姓以養己之宗族乎！」

十一月，
庚寅，
降宗室郡王皆爲縣公，
惟有功者數人不降。
# p 

丙午，
上與羣臣論止盜。

或請重法以禁之，
上哂之曰：
「民之所以爲盜者，
由賦繁役重，
官吏貪求，
飢寒切身，
故不暇顧廉恥耳。

朕當去奢省費，
輕傜薄賦，
選用廉吏，
使民衣食有餘，
則自不爲盜，
安用重法邪！」

自是數年之後，
海内升平，
路不拾遺，
外戸不閉，
商旅野宿焉。
# p 

上又嘗謂侍臣曰：
「君依於國，
國依於民。

刻民以奉君，
猶割肉以充腹，
腹飽而身斃，
君富而國亡。

故人君之患，
不自外來，
常由身出。

夫欲盛則費廣，
費廣則賦重，
賦重則民愁，
民愁則國危，
國危則君喪矣。

朕常以此思之，
故不敢縱欲也。」

# p 

十二月，
己巳，
 dm#dm05982@益州 大都督 rm#r03047@竇軌 奏稱獠反，
請發兵討之。

上曰：
「獠依阻山林，
時出鼠竊，
乃其常俗；
牧守苟能撫以恩信，
自然帥服，
安可輕動干戈，
漁獵其民，
比之禽獸，
豈爲民父母之意邪！」

竟不許。
# p 

上謂 rm#r03424@裴寂 曰：
「比多上書言事者，
朕皆粘之屋壁，
得出入省覽，
毎思治道，
或深夜方寢。

公輩亦當恪勤職業，
副朕此意。」

# p 

上厲精求治，
數引 rm#r04294@魏徵 入臥内，
訪以得失；
徵知無不言，
上皆欣然嘉納。

上遣使點兵，
 rm#r00851@封徳彞 奏：
「中男雖未十八，
其躯幹壯大者，
亦可幷點。」

上從之。

敕出，
 rm#r04294@魏徵 固執以爲不可，
不肯署敕，
至于數四。

上怒，
召而讓之曰：
「中男壯大者，
乃姦民詐妄以避征役，
取之何害，
而卿固執至此！」

對曰：
「夫兵在御之得其道，
不在衆多。

陛下取其壯健，
以道御之，
足以無敵於天下，
何必多取細弱以増虚數乎！

且陛下毎云：
『吾以誠信御天下，
欲使臣民皆無欺詐。』

今即位未幾，
失信者數矣！」

上愕然曰：
「朕何爲失信？」
對曰：
「陛下初即位，
下詔云：
『逋負官物，
悉令蠲免。』

有司以爲負 rm#r01602@秦 府國司者，
非官物，
徵督如故。

陛下以 rm#r01602@秦王 升爲天子，
國司之物，
非官物而何！

又曰：
『 dm#dm08280@關 中免二年租調，
 dm#dm08280@關 外給復一年。』

既而繼有敕云：
『已役已輸者，
以來年爲始。』

散還之後，
方復更徵，
百姓固已不能無怪。

今既徵得物，
復點爲兵，
何謂以來年爲始乎！

又陛下所與共治天下者在於守宰，
居常簡閲，
咸以委之；
至於點兵，
獨疑其詐，
豈所謂以誠信爲治乎！」

上悦曰：
「曏者朕以卿固執疑卿不達政事，
今卿論國家大體，
誠盡其精要。

夫號令不信，
則民不知所從，
天下何由而治乎！

朕過深矣！」

乃不點中男，
賜 rm#r04294@徵 金甕一。
# p 

上聞 dm#dm03590@景州 録事參軍 rm#r01214@張玄素 名，
召見，
問以政道，
對曰：
「 dyn#ch174@隋 主好自專庶務，
不任羣臣；
羣臣恐懼，
唯知稟受奉行而已，
莫之敢違。

以一人之智決天下之務，
借使得失相半，
乖謬已多，
下諛上蔽，
不亡何待！

陛下誠能謹擇羣臣而分任以事，
高拱穆清而考其成敗以施刑賞，
何憂不治！

又，
臣觀 dyn#ch174@隋 末亂離，
其欲爭天下者不過十餘人而已，
其餘皆保郷黨、全妻子，
以待有道而歸之耳。

乃知百姓好亂者亦鮮，
但人主不能安之耳。」

上善其言，
擢爲侍御史。
# p 

前 dm#dm02689@幽州 記室直中書省 rm#r01246@張蘊古 上大寶箴，
其略曰：
「聖人受命，
拯溺亨屯，
故以一人治天下，
不以天下奉一人。」

又曰：
「壯九重於内，
所居不過容膝；
彼昏不知，
瑤其臺而瓊其室。

羅八珍於前，
所食不過適口；
惟狂罔念，
丘其糟而池其酒。」

又曰：
「勿沒沒而闇，
勿察察而明，
雖冕旒蔽目而視於未形，
雖黈絋塞耳而聽於無聲。」

上嘉之，
賜以束帛，
除大理丞。

# p 

上召 rm#r00140@傅奕 ，
賜之食，
謂曰：
「汝前所奏，
幾爲吾禍。

然凡有天變，
卿宜盡言皆如此，
勿以前事爲懲也。」

上嘗謂 rm#r00140@奕 曰：
「佛之爲教，
玄妙可師，
卿何獨不悟其理？」
對曰：
「佛乃胡中桀黠，
誑耀彼土。

中國邪僻之人，
取 rm@莊 、 rm#ry0032@老 玄談，
飾以妖幻之語，
用欺愚俗，
無益於民，
有害於國，
臣非不悟，
鄙不學也。

」
上頗然之。
# p 

上患吏多受賕，
密使左右試賂之。

有司門令史受絹一匹，
上欲殺之，
民部尚書 rm#r03452@裴矩 諫曰：
「爲吏受賂，
罪誠當死；
但陛下使人遺之而受，
乃陷人於法也，
恐非所謂『道之以徳，
齊之以禮。』」

上悦，
召文武五品已上告之曰：
「 rm#r03452@裴矩 能當官力爭，
不爲面從，
儻毎事皆然，
何憂不治！」


# p 

臣 rm@光 曰：
「古人有言：
君明臣直 rm#r03452@裴矩 佞於 dyn#ch174@隋 而忠於 dyn#ch100@唐 ，
非其性之有變也；
君惡聞其過，
則忠化爲佞，
君樂聞直言，
則佞化爲忠。

是知君者表也，
臣者景也，
表動則景隨矣。」

# p 

 y@是歳 ，
進皇子 rm#r00416@長沙郡王恪 爲 rm#r00416@漢王 、 rm#r00837@宜陽郡王祐 爲 rm#r00837@楚王 。


# p 

 dm#dm03383@新羅 、 dm#dm05948@百濟 、 dm#dm08934@高麗 三國有宿仇，
迭相攻撃；
上遣國子助教 rm#r01565@朱子奢 往諭指，
三國皆上表謝罪。
