
** 天寶
*** 天寶元年
# year 0742
# p 

春，
正月，
丁未朔，
上御 dm#dm00820@勤政樓 受朝賀，
赦天下，
改元。
# p 

壬子，
分 dm#dm02660@平盧 別爲節度，
以 rm#r00793@安祿山 爲節度使。

# p 

是時，
天下聲教所被之州三百三十一，
羈縻之州八百，
置十節度、經略使以備邊。

 dm#dm02061@安西 節度撫寧 dm#dm07304@西域 ，
統 dm#dm09290@龜茲 、 dm#dm05556@焉耆 、 dm#dm00368@于闐 、 dm#dm05857@疏勒 四鎭，
治 dm#dm09291@龜茲城 ，
兵二萬四千。

 dm#dm00860@北庭 節度防制突騎施、 dm#dm01494@堅昆 ，
統 dm#dm05472@瀚海 、 dm#dm01731@天山 、 dm#dm00505@伊吾 三軍，
屯 dm#dm00514@伊 、 dm#dm07286@西 二州之境，
治 dm#dm00860@北庭 都護府，
兵二萬人。

 dm#dm04695@河西 節度斷隔吐蕃、突厥，
統 dm#dm07587@赤水 、 dm#dm01627@大斗 、 dm#dm02852@建康 、 dm#dm02290@寧寇 、 dm#dm05716@玉門 、 dm#dm01507@墨離 、 dm#dm07468@豆盧 、 dm#dm03367@新泉 八軍，
 dm#dm02903@張掖 、 dm#dm00413@交城 、 dm#dm05871@白亭 三守捉，
屯 dm#*dm04947@涼 、 dm#dm06603@肅 、 dm#dm05769@瓜 、 dm#dm04612@沙 、 dm#dm03655@會 五州之境，
治 dm#dm04947@涼州 ，
兵七萬三千人。

 dm#dm03677@朔方 節度捍禦突厥，
統 dm#dm06448@經略 、 dm#dm07472@豐安 、 dm#dm02148@定遠 三軍，
三 dm#dm01138@受降城 ，
 dm#dm01976@安北 、 dm#dm01394@單于 二都護府，
屯 dm#dm08619@靈 、 dm#dm01532@夏 、 dm#dm07470@豐 三州之境，
治 dm#dm08619@靈州 ，
兵六萬四千七百人。

 dm#dm04672@河東 節度與 dm#dm03677@朔方 掎角以禦突厥，
統 dm#dm01718@天兵 、 dm#dm01578@大同 、 dm#dm04193@横野 、 dm#dm02426@岢嵐 四軍，
 dm#dm08542@雲中 守捉，
屯 dm#dm01776@太原府  dm#dm03000@忻 、 dm#dm00485@代 、 dm#dm02511@嵐 三州之境，
治 dm#dm01776@太原府 ，
兵五萬五千人。

 dm#dm06863@范陽 節度臨制奚、契丹，
統 dm#dm06448@經略 、 dm#dm01909@威武 、 dm#dm05034@清夷 、 dm#dm08698@靜塞 、 dm#dm03029@恆陽 、 dm#dm00855@北平 、 dm#dm08926@高陽 、 dm#dm01370@唐興 、 dm#dm04189@横海 九軍，
屯 dm#dm02688@幽 、 dm#dm07104@薊 、 dm#dm01931@媯 、 dm#dm00056@檀 、 dm#dm03494@易 、 dm#dm03017@恆 、 dm#dm02116@定 、 dm#dm05267@漠 、 dm#dm05208@滄 九州之境，
治 dm#dm02689@幽州 ，
兵九萬一千四百人。

 dm#dm02660@平盧 節度鎭撫室韋、靺鞨，
統 dm#dm02660@平盧 、 dm#dm06013@盧龍 二軍，
 dm#dm04113@楡關 守捉，
 dm#dm02032@安東 都護府，
屯 dm#dm05609@營 、 dm#dm02607@平 二州之境，
治 dm#dm05611@營州 ，
兵三萬七千五百人。

 dm#dm08458@隴右 節度備禦吐蕃，
統 dm#dm06688@臨洮 、 dm#dm04690@河源 、 dm#dm05887@白水 、 dm#dm01964@安人 、 dm#dm03226@振威 、 dm#dm01907@威戎 、 dm#dm05270@漠門 、 dm#dm02285@寧塞 、 dm#dm06315@積石 、 dm#dm08135@鎭西 十軍，
 dm#dm06437@綏和 、 dm#dm01186@合川 、 dm#dm02619@平夷 三守捉，
屯 dm#dm07957@鄯 、 dm#dm02715@廓 、 dm#dm04823@洮 、 dm#dm04650@河 之境，
治 dm#dm07964@鄯州 ，
兵七萬五千人。

 dm#dm00785@劍南 節度西抗吐蕃，
南撫蠻獠，
統 dm#dm01729@天寶 、 dm#dm02632@平戎 、 dm#dm03448@昆明 、 dm#dm02306@寧遠 、 dm#dm05389@澄川 、 dm#dm01012@南江 六軍，
屯 dm#dm05982@益 、 dm#dm06576@翼 、 dm#dm06857@茂 、 dm#dm05845@當 、 dm#dm02536@巂 、 dm#dm03960@柘 、 dm#dm03903@松 、 dm#dm06452@維 、 dm#dm03037@恭 、 dm#dm08476@雅 、 dm#dm09164@黎 、 dm#dm01898@姚 、 dm#dm03045@悉 十三州之境，
治 dm#dm05982@益州 ，
兵三萬九百人。

 dm#dm02527@嶺南 五府經略綏靜夷、獠，
統 dm#dm06448@經略 、 dm#dm05058@清海 二軍，
 dm#dm03996@桂 、 dm#dm02238@容 、 dm#dm07790@邕 、 dm#dm00412@交 四管，
治 dm#dm02733@廣州 ，
兵萬五千四百人。

此外又有 dm#dm08200@長樂經略 ，
 dm#dm06248@福州 領之，
兵千五百人。

 dm#dm03869@東莱 守捉，
 dm#dm06953@莱州 領之；
 dm#dm03853@東牟 守捉，
 dm#dm05863@登州 領之；
兵各千人。

凡鎭兵四十九萬人，
馬八萬餘匹。

 y@開元 之前，
毎歳供邊兵衣糧，
費不過二百萬；
 y@天寶 之後，
邊將奏益兵浸多，
毎歳用衣千二十萬匹，
糧百九十萬斛，
公私勞費，
民始困苦矣。


# p 

甲寅，
 rm#r03908@陳王 府參軍 rm#r05674@田同秀 上言：
「見 rm#ry0032@玄元皇帝 於 dm#dm00308@丹鳳門 之空中，
告以『我藏靈符，
在 rm#?@尹喜 故宅。』」

上遣使於故 dm#dm00742@函谷關  dm#dm02382@尹喜臺 旁求得之。

# p 

 dm#dm08320@陝州 刺史 rm#r02017@李齊物 穿 dm#dm00150@三門運渠 ，
辛未，
渠成。

 rm#r02017@齊物 ，
 rm#r02450@神通 之曾孫也。

# p 

壬辰，
羣臣上表，
以「 dm#dm00741@函谷 靈符，
潛應年號；
先天不違，
請於尊號加『天寶』
字。」

從之。
# p 

二月，
辛卯，
上享 rm#ry0032@玄元皇帝 於新廟。

甲午，
享太廟。

丙申，
合祀天地於南郊，
赦天下。

改侍中爲左相，
中書令爲右相，
尚書左、右丞相復爲僕射；
 dm#dm03880@東都 、 dm#dm00895@北都 皆爲京，
州爲郡，
刺史爲太守；
改 dm#dm04014@桃林縣 曰 dm#dm08614@靈寶 。

 rm#r05674@田同秀 除朝散大夫。

# p 

時人皆疑寶符 rm#r05674@同秀 所爲。

間一歳，
 dm#dm05053@清河 人 rm#r05206@崔以清 復言：
「見 rm#ry0032@玄元皇帝 於 dm#dm01750@天津橋 北，
云藏符在 dm#dm04238@武城  dm#dm06411@紫微山 ，」
敕使往求，
亦得之。

 dm#dm03880@東都 留守 rm#xjts02178@王倕 知其詐，
按問，
果首服。

奏之。

上亦不深罪，
流之而已。
# p 

三月，
以 dm#dm08170@長安 令 rm#r04017@韋堅 爲 dm#dm08329@陝郡 太守，
領 dm#dm04475@江 、 dm#dm04981@淮 租庸轉運使。

# p 

初，
 rm#r00766@宇文融 既敗，
言利者稍息。

及 rm#r02191@楊愼矜 得幸，
於是 rm#r04017@韋堅 、 rm#r02724@王鉷 之徒競以利進，
百司有利權者，
稍稍別置使以領之，
舊官充位而已。

 rm#r04017@堅 ，
太子之𡚱兄也，
爲吏以幹敏稱。

上使之督 dm#dm04475@江 、 dm#dm04981@淮 租運，
歳増巨萬；
上以爲能，
故擢任之。

 rm#r02724@王鉷 ，
 rm#r02644@方翼 之曾孫也，
亦以善治租賦爲戸部員外郎兼侍御史。

# p 

 rm#r01824@李林甫 爲相，
凡才望功業出己右及爲上所厚、勢位將逼己者，
必百計去之；
尤忌文學之士，
或陽與之善，
啗以甘言而陰陷之。

世謂 rm#r01824@李林甫 「口有蜜，
腹有劍」。

# p 

上嘗陳樂於 dm#dm00820@勤政樓 ，
垂簾觀之。

兵部侍郎 rm#r05710@盧絢 謂上已起，
垂鞭按轡，
横過樓下；
 rm#r05710@絢 風標清粹，
上目送之，
深歎其蘊藉。

 rm#r01824@林甫 常厚以金帛賂上左右，
上舉動必知之，
乃召 rm#r05710@絢 子弟謂曰：
「尊君素望清崇，
今 dm#dm00412@交 、 dm#dm02717@廣 藉才，
聖上欲以尊君爲之，
可乎？
若憚遠行，
則當左遷；
不然，
則以賓、詹分務 dm#dm03843@東洛 ，
亦優賢之命也，
何如？」
 rm#r05710@絢 懼，
以賓、詹爲請。

 rm#r01824@林甫 恐乖衆望，
乃除 dm#dm06938@華州 刺史。

到官未幾，
誣其有疾，
州事不理，
除詹事、員外、同正。

# p 

上又嘗問 rm#r01824@林甫 以「 rm#r00568@嚴挺之 今安在？
是人亦可用。」

 rm#r00568@挺之 時爲 dm#dm06431@絳州 刺史。

 rm#r01824@林甫 退，
召 rm#r00568@挺之 弟 rm#r01699@損之 ，
諭以「上待尊兄意甚厚，
盍爲見上之策，
奏稱風疾，
求還 dm#dm08170@京師 就醫。」

 rm#r00568@挺之 從之。

 rm#r01824@林甫 以其奏白上云：
「 rm#r00568@挺之 衰老得風疾，
宜且授以散秩，
使便醫藥。」

上歎吒久之；
夏，
四月，
壬寅，
以爲詹事，
又以 dm#dm04541@汴州 刺史、 dm#dm04660@河南 采訪使 rm#r04346@齊澣 爲少詹事，
皆員外、同正，
於 dm#dm03788@東京 養疾。

 rm#r04346@澣 亦朝廷宿望，
故幷忌之。
# p 

上發兵納十姓可汗 rm#r05995@阿史那昕 於突騎施，
至 dm#dm00594@倶蘭城 ，
爲 rm@莫賀達干 所殺。

突騎施大纛官 rm#?@都摩度 來降，
六月，
乙未，
册 rm#?@都摩度 爲三姓葉護。
# p 

秋，
七月，
癸卯朔，
日有食之。
# p 

辛未，
左相 rm#r02557@牛仙客 薨。

八月，
丁丑，
以刑部尚書 rm#r01802@李適之 爲左相。
# p 

突厥拔悉密、囘紇、葛邏祿三部共攻 rm#?@骨咄葉護 ，
殺之，
推拔悉密酋長爲 rm#?@頡跌伊施可汗 ，
囘紇、葛邏祿自爲左、右葉護。

突厥餘衆共立 rm#?@判闕特勒 之子爲 rm#?@烏蘇米施可汗 ，
以其子 rm#?@葛臘哆 爲西殺。

# p 

上遣使諭烏蘇令内附，
烏蘇不從。

 dm#dm03677@朔方 節度使 rm#r02632@王忠嗣 盛兵 dm#dm06181@磧口 以威之，
烏蘇懼，
請降，
而遷延不至。

 rm#r02632@忠嗣 知其詐，
乃遣使説拔悉密、囘紇、葛邏祿使攻之，
烏蘇遁去。

 rm#r02632@忠嗣 因出兵撃之，
取其右廂以歸。

# p 

丁亥，
突厥西葉護 rm#?@阿布思 及西殺 rm#?@葛臘哆 、 rm#?@默啜發 之孫 rm#?@勃徳支 、 rm#rx0007@伊然 小妻、 rm#?@毘伽登利 之女帥部衆千餘帳，
相次來降，
突厥遂微。

九月，
辛亥，
上御 dm#dm06828@花萼樓 宴突厥降者，
賞賜甚厚。
# p 

 rm#?@護密 先附吐蕃，
戊午，
其王 rm#?@頡吉里匐 遣使請降。

# p 

冬，
十月，
丁酉，
上幸 dm#dm08874@驪山 温泉；
己巳，
還宮。十一月
# p 

十二月，
 dm#dm08458@隴右 節度使 rm#r02857@皇甫惟明 奏破吐蕃 dm#dm01610@大嶺 等軍；
戊戌，
又奏破 dm#dm08674@青海道 莽布支營三萬餘衆，
斬獲五千餘級。

庚子，
 dm#dm04695@河西 節度使 rm#?@王倕 奏破吐蕃漁海及遊弈等軍。

# p 

 y@是歳 ，
天下縣一千五百二十八，
郷一萬六千八百二十九，
戸八百五十二萬五千七百六十三，
口四千八百九十萬九千八百。
# p 

囘紇葉護 rm#?@骨力裴羅 遣使入貢，
賜爵 rm#?@奉義王 。

*** 二年
# year 0743
# p 

春，
正月，
 rm#r00793@安祿山 入朝；
上寵待甚厚，
謁見無時。

 rm#r00793@祿山 奏言：
「 y@去年  dm#dm05611@營州 蟲食苗，
臣焚香祝天云：
『臣若操心不正，
事君不忠，
願使蟲食臣心；
若不負神祇，
願使蟲散。』

即有羣鳥從北來，
食蟲立盡。

請宣付史官。」

從之。

# p 

 rm#r01824@李林甫 領吏部尚書，
日在政府，
選事悉委侍郎 rm#r05188@宋遙 、 rm#r03147@苗晉卿 。

御史中丞 rm#r01105@張倚 新得幸於上，
 rm#r05188@遙 、 rm#r03147@晉卿 欲附之。

時選人集者以萬計，
入等者六十四人，
 rm#r01105@倚 子 rm#xjts04679@奭 爲之首，
羣議沸騰。

前 dm#dm07104@薊 令 rm#r05827@蘇孝韞 以告 rm#r00793@安祿山 ，
 rm#r00793@祿山 入言於上，
上悉召入等人面試之，
 rm#xjts04679@奭 手持試紙，
終日不成一字，
時人謂之「曳白」。

癸亥，
 rm#r05188@遙 貶 dm#dm04288@武當 太守，
 rm#r03147@晉卿 貶 dm#dm02016@安康 太守，
 rm#r01105@倚 貶 dm#dm05009@淮陽 太守，
同考判官禮部郎中 rm#r03443@裴朏 等皆貶 dm#dm02527@嶺南 官。

 rm#r03147@晉卿 ，
 dm#dm01513@壺關 人也。

# p 

三月，
壬子，
追尊 rm#ry0032@玄元皇帝 父 dyn#ch103@周 上御大夫爲 rm#?@先天太皇 ；
又尊 rm#?@皋繇 爲 rm#?@徳明皇帝 ，
 rm#rt0673@涼武昭王 爲 rm#rt0673@興聖皇帝 。

# p 

 dm#dm04475@江 、 dm#dm04981@淮 南租庸等使 rm#r04017@韋堅 引 dm#dm05248@滻水 抵苑東 dm#dm03700@望春樓 下爲潭，
以聚 dm#dm04475@江 、 dm#dm04981@淮 運船，
役夫匠通漕渠，
發人丘壟，
自 dm#dm04475@江 、 dm#dm04981@淮 至 dm#dm08170@京城 ，
民間蕭然愁怨。

二年而成。

丙寅，
上幸 dm#dm03700@望春樓 觀新潭。

 rm#r04017@堅 以新船數百艘，
扁榜郡名，
各陳郡中珍貨於船背；
 dm#dm08318@陝 尉 rm#r05217@崔成甫 著錦半臂，
鈌胯緑衫以裼之，
紅袹首，
居前船唱得寶歌，
使美婦百人盛飾而和之，
連檣數里；
 rm#r04017@堅 跪進諸郡輕貨，
仍上百牙盤食。

上置宴，
竟日而罷，
觀者山積。

夏，
四月，
加 rm#r04017@堅 左散騎常侍，
其僚屬吏卒褒賞有差；
名其潭曰 dm#dm02765@廣運 。

時 dm#dm00427@京兆 尹 rm#r04115@韓朝宗 亦引 dm#dm05117@渭水 置潭於西街，
以貯材木。

# p 

丁亥，
 rm#r02857@皇甫惟明 引軍出 dm#dm07321@西平 ，
撃吐蕃，
行千餘里，
攻 dm#dm04814@洪濟城 ，
破之。

# p 

上以右贊善大夫 rm#r02191@楊愼矜 知御史中丞事。

時 rm#r01824@李林甫 專權，
公卿之進，
有不出其門者，
必以罪去之；
 rm#r02191@愼矜 由是固辭，
不敢受。

五月，
辛丑，
以 rm#r02191@愼矜 爲諫議大夫。
# p 

冬，
十月，
戊寅，
上幸 dm#dm08874@驪山 温泉；
乙卯，
還宮。

*** 三載
# year 0744
# p 

春，
正月，
丙申朔，
改年曰載。

# p 

辛丑，
上幸 dm#dm08874@驪山 温泉；
二月，
庚午，
還宮。

# p 

辛卯，
太子更名 rm#r01661@亨 。

# p 

海賊 rm#r05106@呉令光 等抄掠 dm#dm01160@臺 、 dm#dm03478@明 ，
命 dm#dm04660@河南 尹 rm#r06255@裴敦復 將兵討之。

# p 

三月，
己巳，
以 dm#dm02660@平盧 節度使 rm#r00793@安祿山 兼 dm#dm06863@范陽 節度使；
以 dm#dm06863@范陽 節度使 rm#r03426@裴寛 爲戸部尚書。

禮部尚書 rm#r01021@席建侯 爲 dm#dm04656@河北 黜陟使，
稱 rm#r00793@祿山 公直；
 rm#r01824@李林甫 、 rm#r03426@裴寛 皆順旨稱其美。

三人皆上所信任，
由是 rm#r00793@祿山 之寵益固不搖矣。
# p 

夏，
四月，
 rm#r06255@裴敦復 破 rm#r05106@呉令光 ，
擒之。
# p 

五月，
 dm#dm04695@河西 節度使 rm#r06079@夫蒙靈詧 討突騎施 rm@莫賀達干 ，
斬之，
更請立黒姓伊里底蜜施 rm#?@骨咄祿毘伽 ；
六月，
甲辰，
册拜 rm#?@骨咄祿毘伽 爲十姓可汗。

# p 

秋，
八月，
拔悉蜜攻斬突厥 rm#xjts10596@烏蘇可汗 ，
傳首 dm#dm08170@京師 。

國人立其弟 rm#xjts10030@鶻隴匐白眉特勒 ，
是爲 rm#xjts10030@白眉可汗 。

於是突厥大亂，
敕 dm#dm03677@朔方 節度使 rm#r02632@王忠嗣 出兵乘之。

至 dm#dm07117@薩河内山 ，
破其左廂阿波達干等十一部，
右廂未下。

會囘紇葛邏祿共攻 rm#xjts19476@拔悉蜜頡跌伊施可汗 ，
殺之。

 rm#r05849@囘紇骨力裴羅 自立爲 rm#r05849@骨咄祿毘伽闕可汗 ，
遣使言状；
上册拜 rm#r05849@裴羅 爲 rm#r05849@懷仁可汗 。

於是 rm#r05849@懷仁 南據突厥故地，
立牙帳於 dm#dm05522@烏徳犍山 ，
舊統藥邏葛等九姓，
其後又幷拔悉蜜、葛邏祿，
凡十一部，
各置都督，
毎戰則以二客部爲先。
# p 

 rm#r01824@李林甫 以 rm#r02191@楊愼矜 屈附於己，
九月，
甲戌，
復以 rm#r02191@愼矜 爲御史中丞，
充諸道鑄錢使。

# p 

冬，
十月，
癸巳，
上幸 dm#dm08874@驪山 温泉；
十一月，
丁卯，
還宮。


# p 

術士 rm#r05825@蘇嘉慶 上言：
遯甲術有九宮貴神，
典司水旱，
請立壇於東郊，
祀以四孟月；
從之。

禮在昊天上帝下，
 dm#dm01814@太清宮 、太廟上，
所用牲玉，
皆侔天地。

# p 

十二月，
癸巳，
置 dm#dm03659@會昌縣 於 dm#dm05200@温泉宮 下。


# p 

戸部尚書 rm#r03426@裴寛 素爲上所重，
 rm#r01824@李林甫 恐其入相，
忌之。

刑部尚書 rm#r06255@裴敦復 撃海賊還，
受請託，
廣序軍功，
 rm#r03426@寛 微奏其事。

 rm#r01824@林甫 以告 rm#r06255@敦復 ，
 rm#r06255@敦復 言 rm#r03426@寛 亦嘗以親故屬 rm#r06255@敦復 。

 rm#r01824@林甫 曰：
「君速奏之，
勿後於人。」

 rm#r06255@敦復 乃以五百金賂女官 rm#r02136@楊太眞 之姉，
使言於上。

甲午，
 rm#r03426@寛 坐貶 dm#dm06055@睢陽 太守。

# p 

初，
 rm@武惠𡚱 薨，
上悼念不已，
後宮數千，
無當意者。

或言 rm#?@壽王 𡚱 rm#r02141@楊氏 之美，
絶世無雙。

上見而悦之，
乃令𡚱自以其意乞爲女官，
號 rm#r02136@太眞 ；
更爲 rm#?@壽王 娶左衞郎將 rm#rx0015@韋昭訓 女。

潛内 rm#r02136@太眞 宮中。

 rm#r02136@太眞 肌態豐豔，
曉音律，
性警穎，
善承迎上意，
不期歳，
寵遇如 rm@惠𡚱 ，
宮中號曰「娘子」，
凡儀體皆如皇后。
# p 

癸卯，
以宗女爲 rm#xjts10331@和義公主 ，
嫁 dm#dm02306@寧遠  rm#xjts24835@奉化王阿悉爛達干 。


# p 

癸丑，
上祀九宮貴神，
赦天下。
# p 

初令百姓十八爲中，
二十三成丁。
# p 

初，
上自 dm#dm03880@東都 還，
 rm#r01824@李林甫 知上厭巡幸，
乃與 rm#r02557@牛仙客 謀増近道粟賦及和糴以實 dm#dm08281@關中 ；
數年，
蓄積稍豐。

上從容謂 rm#r04220@高力士 曰：
「 dm#dm08170@長安 近十年，
天下無事，
朕欲高居無爲，
悉以政事委 rm#r01824@林甫 ，
何如？」
對曰：
「天子巡狩，
古之制也。

且天下大柄，
不可假人；
彼威勢既成，
誰敢復議之者！」

上不悦。

 rm#r04220@力士 頓首自陳：
「臣狂疾，
發妄言，
罪當死。」

上乃爲 rm#r04220@力士 置酒，
左右皆呼萬歳。

 rm#r04220@力士 自是不敢深言天下事矣。

*** 四載
# year 0745
# p 

春，
正月，
庚午，
上謂宰相曰：
「朕比以甲子日，
於宮中爲壇，
爲百姓祈福，
朕自草黄素置案上，
俄飛升天，
聞空中語云：
『聖壽延長。』

又朕於 dm#dm02514@嵩山 鍊藥成，
亦置壇上，
及夜，
左右欲收之，
又聞空中語云：
『藥未須收，
此自守護。』

達曙乃收之。」

太子、諸王、宰相，
皆上表賀。

# p 

囘紇 rm#?@懷仁可汗 撃突厥 rm#?@白眉可汗 ，
殺之，
傳首 dm#dm08170@京師 。

突厥 rm#?@毘伽可敦 帥衆來降。

於是北邊晏然，
烽燧無警矣。
# p 

囘紇斥地愈廣，
東際室韋，
西抵 dm#dm08022@金山 ，
南跨大漠，
盡有突厥故地。

 rm#r05849@懷仁 卒，
子 rm#?@磨延啜 立，
號 rm#?@葛勒可汗 。
# p 

二月，
己酉，
以 dm#dm03677@朔方 節度使 rm#r02632@王忠嗣 兼 dm#dm04672@河東 節度使。

 rm#r02632@忠嗣 少以勇敢自負，
及鎭方面，
專以持重安邊爲務，
常曰：
「太平之將，
但當撫循訓練士卒而已，
不可疲 dm#dm00255@中國 之力以邀功名。」

有漆弓百五十斤，
常貯之櫜中，
以示不用。

軍中日夜思戰，
 rm#r02632@忠嗣 多遣諜人伺其間隙，
見可勝，
然後興師，
故出必有功。

既兼兩道節制，
自 dm#dm03677@朔方 至 dm#dm08542@雲中 ，
邊陲數千里，
要害之地，
悉列置城堡，
斥地各數百里。

邊人以爲自 rm#r01095@張仁亶 之後，
將帥皆不及。

# p 

三月，
壬申，
上以外孫 rm#r03992@獨孤氏 爲 rm#r03992@靜樂公主 ，
嫁 rm#r05391@契丹王李懷節 ；
甥 rm#rx0001@楊氏 爲 rm#rx0001@宜芳公主 ，
嫁 rm#r05380@奚王李延寵 。

# p 

乙巳，
以刑部尚書 rm#r06255@裴敦復 充 dm#dm02527@嶺南 五府經略等使。

五月，
壬申，
 rm#r06255@敦復 坐逗留不之官，
貶 dm#dm04960@淄川 太守，
以光祿少卿 rm#r05314@彭果 代之。

上嘉 rm#r06255@敦復 平海賊之功，
故 rm#r01824@李林甫 陷之。果杲
# p 

 rm#r01802@李適之 與 rm#r01824@李林甫 爭權有隙。

 rm#r01802@適之 領兵部尚書，
駙馬 rm#r01088@張垍 爲侍郎，
 rm#r01824@林甫 亦惡之，
使人發兵部銓曹姦利事，
收吏六十餘人付 dm#dm00427@京兆 與御史對鞫之，
數日，
竟不得其情。

 dm#dm00427@京兆 尹 rm#r04315@蕭炅 使法曹 rm#r00396@吉温 鞫之。

 rm#r00396@温 入院，
置兵部吏於外，
先於後廳取二重囚訊之，
或杖或壓，
號呼之聲，
所不忍聞；
皆曰：
「苟存餘生，
乞紙盡答。」

兵部吏素聞 rm#r00396@温 之慘酷，
引入，
皆自誣服，
無敢違 rm#r00396@温 意者。

頃刻而獄成，
驗囚無榜掠之迹。

六月，
辛亥，
敕誚責前後知銓侍郎及判南曹郎官而宥之。

 rm#r01088@垍 ，
 rm#r01127@均 之兄；
 rm#r00396@温 ，
 rm#r00398@頊 之弟子也。

# p 

 rm#r00396@温 始爲 dm#dm03393@新豐 丞，
太子文學 rm#r05808@薛嶷 薦 rm#r00396@温 才，
上召見，
顧 rm#r05808@嶷 曰：
「是一不良人，
朕不用也。」

# p 

 rm#r04315@蕭炅 爲 dm#dm04660@河南 尹，
嘗坐事，
西臺遣 rm#r00396@温 往按之，
 rm#r00396@温 治 rm#r04315@炅 甚急。

及 rm#r00396@温 爲 dm#dm06979@萬年 丞，
未幾，
 rm#r04315@炅 爲 dm#dm00427@京兆 尹。

 rm#r00396@温 素與 rm#r04220@高力士 相結，
 rm#r04220@力士 自禁中歸，
 rm#r00396@温 度 rm#r04315@炅 必往謝官，
乃先詣 rm#r04220@力士 ，
與之談謔，
握手甚歡，
 rm#r04315@炅 後至，
 rm#r00396@温 陽爲驚避；
 rm#r04220@力士 呼曰：
「 rm#r00396@吉七 不須避。」

謂 rm#r04315@炅 曰：
「此亦吾故人也。」

召還，
與 rm#r04315@炅 坐。

 rm#r04315@炅 接之甚恭，
不敢以前事爲怨。

他日，
 rm#r00396@温 謁 rm#r04315@炅 曰：
「曩者 rm#r00396@温 不敢隳國家法，
自今請洗心事公。」

 rm#r04315@炅 遂與盡歡，
引爲法曹。

# p 

及 rm#r01824@林甫 欲除不附己者，
求治獄吏，
 rm#r04315@炅 薦 rm#r00396@温 於 rm#r01824@林甫 ；
 rm#r01824@林甫 得之，
大喜。

 rm#r00396@温 常曰：
「若遇知己，
南山白額虎不足縛也。」

時又有 dm#dm03781@杭州 人 rm#r03083@羅希奭 ，
爲吏深刻，
 rm#r01824@林甫 引之，
自御史臺主簿再遷殿中侍御史。

二人皆隨 rm#r01824@林甫 所欲深淺，
鍛鍊成獄，
無能自脱者，
時人謂之「 rm#r03083@羅 鉗 rm#r00396@吉 網」。

# p 

秋，
七月，
壬午，
册 rm#rx0015@韋昭訓 女爲 rm#?@壽王 𡚱。
# p 

八月，
壬寅，
册 rm#r02136@楊太眞 爲貴𡚱；
贈其父 rm#rx0013@玄琰 兵部尚書，
以其叔父 rm#?@玄珪 爲光祿卿，
從兄 rm#r05518@銛 爲殿中少監，
 rm#r05519@錡 爲駙馬都尉。

癸卯，
册 rm@武惠𡚱 女爲 rm#r00607@太華公主 ，
命 rm#r05519@錡 尚之。

及貴𡚱三姉，
皆賜第 dm#dm08170@京師 ，
寵貴赫然。
# p 

 rm#r02248@楊釗 ，
貴𡚱之從祖兄也，
不學無行，
爲宗黨所鄙。

從軍於 dm#dm07197@蜀 ，
得 dm#dm03397@新都 尉；
考滿，
家貧不能自歸，
 dm#dm03354@新政 富民 rm@鮮于仲通 常資給之。

 rm#rx0013@楊玄琰 卒於 dm#dm07197@蜀 ，
 rm#r02248@釗 往來其家，
遂與其中女通。

# p 

 rm#xjts10937@鮮于仲通 名 rm#xjts10937@向 ，
以字行，
頗讀書，
有材智，
 dm#dm00785@劍南 節度使 rm#r03051@章仇兼瓊 引爲采訪支使，
委以心腹。

嘗從容謂 rm#xjts10937@仲通 曰：
「今吾獨爲上所厚，
苟無内援，
必爲 rm#r01824@李林甫 所危。

聞 rm#r02136@楊𡚱 新得幸，
人未敢附之。

子能爲我至 dm#dm08170@長安 與其家相結，
吾無患矣。」

 rm#xjts10937@仲通 曰：
「 rm#xjts10937@仲通  dm#dm07197@蜀 人，
未嘗遊上國，
恐敗公事。

今爲公更求得一人。」

因言 rm#r02248@釗 本末。

 rm#r03051@兼瓊 引見 rm#r02248@釗 ，
儀觀豐偉，
言辭敏給；
 rm#r03051@兼瓊 大喜，
即辟爲推官，
往來浸親密。

乃使人獻春綈於 dm#dm08170@京師 ，
將別，
謂曰：
「有少物在 dm#dm07859@郫 ，
以具一日之糧，
子過，
可取之。」

 rm#r02248@釗 至 dm#dm07859@郫 ，
 rm#r03051@兼瓊 使親信大齎 dm#dm07197@蜀 貨精美者遺之，
可直萬緡。

 rm#r02248@釗 大喜過望，
晝夜兼行，
至 dm#dm08170@長安 ，
歴抵諸妹，
以 dm#dm07197@蜀 貨遺之，
曰：
「此 rm#r03051@章仇公 所贈也。」

時中女新寡，
 rm#r02248@釗 遂館於其室，
中分 dm#dm07197@蜀 貨以與之。

於是諸 rm#no@楊 日夜譽 rm#r03051@兼瓊 ；
且言 rm#r02248@釗 善樗蒲，
引之見上，
得隨供奉官出入禁中，
改金吾兵曹參軍。
# p 

九月，
癸未，
以 dm#dm08329@陝郡 太守、 dm#dm04475@江  dm#dm04981@淮 租庸轉運使 rm#r04017@韋堅 爲刑部尚書，
罷其諸使，
以御史中丞 rm#r02191@楊愼矜 代之。

 rm#r04017@堅 妻 rm#xjts27159@姜氏 ，
 rm#r00650@皎 之女，
 rm#r01824@林甫 之舅子也，
故 rm#r01824@林甫 昵之。

及 rm#r04017@堅 以通漕有寵於上，
遂有入相之志，
又與 rm#r01802@李適之 善；
 rm#r01824@林甫 由是惡之，
故遷以美官，
實奪之權也。
# p 

 rm#r00793@安祿山 欲以邊功市寵，
數侵掠奚、契丹；
奚、契丹各殺公主以叛，
 rm#r00793@祿山 討破之。
# p 

 dm#dm08458@隴右 節度使 rm#r02857@皇甫惟明 與吐蕃戰于 dm#dm06084@石堡城 ，
爲虜所敗，
副將 rm#r05856@褚誗 戰死。

# p 

冬，
十月，
甲午，
 rm#r00793@安祿山 奏：
「臣討契丹至 dm#dm00859@北平郡 ，
夢先朝名將李靖、李勣從臣求食。

」
遂命立廟。

又奏薦奠之日，
廟梁産芝。

# p 

丁酉，
上幸 dm#dm08874@驪山 温泉。
# p 

上以戸部郎中 rm#r02724@王鉷 爲戸口色役使，
敕賜百姓復除。

 rm#r02724@鉷 奏徵其輦運之費，
廣張錢數，
又使市本郡輕貨，
百姓所輸乃甚於不復除。

舊制，
戍邊者免其租庸，
六歳而更。

時邊將恥敗，
士卒死者皆不申牒，
貫籍不除。

 rm#r02724@王鉷 志在聚斂，
以有籍無人者皆爲避課，
按籍戍邊六歳之外，
悉徵其租庸，
有併徵三十年者，
民無所訴。

上在位久，
用度日侈，
後宮賞賜無節，
不欲數於左、右藏取之。

 rm#r02724@鉷 探知上指，
歳貢額外錢百億萬，
貯於内庫，
以供宮中宴賜，
曰：
「此皆不出於租庸調，
無預經費。」

上以 rm#r02724@鉷 爲能富國，
益厚遇之。

 rm#r02724@鉷 務爲割剥以求媚，
中外嗟怨。

丙子，
以 rm#r02724@鉷 爲御史中丞、 dm#dm00444@京畿 采訪使。帛
# p 

 rm#r02248@楊釗 侍宴禁中，
專掌樗蒲文簿，
鉤校精密。

上賞其強明，
曰：
「好度支郎」。

諸 rm#no@楊 數徵此言於上，
又以屬 rm#r02724@王鉷 ，
 rm#r02724@鉷 因奏充判官。


# p 

十二月，
戊戌，
上還宮。

*** 五載
# year 0746
# p 

春，
正月，
乙丑，
以 dm#dm08458@隴右 節度使 rm#r02857@皇甫惟明 兼 dm#dm04695@河西 節度使。


# p 

 rm#r01802@李適之 性疏率，
 rm#r01824@李林甫 嘗謂 rm#r01802@適之 曰：
「 dm#dm06933@華山 有金礦，
采之可以富國，
主上未之知也。

」
他日，
 rm#r01802@適之 因奏事言。

之上以問 rm#r01824@林甫 ，
對曰：
「臣久知之，
但 dm#dm06933@華山 陛下本命，
王氣所在，
鑿之非宜，
故不敢言。」

上以 rm#r01824@林甫 爲愛己，
薄 rm#r01802@適之 慮事不熟，
謂曰：
「自今奏事，
宜先與 rm#r01824@林甫 議之，
無得輕脱。」

 rm#r01802@適之 由是束手矣。

 rm#r01802@適之 既失恩，
 rm#r04017@韋堅 失權，
益相親密，
 rm#r01824@林甫 愈惡之。

# p 

初，
太子之立，
非 rm#r01824@林甫 意。

 rm#r01824@林甫 恐異日爲己禍，
常有動搖東宮之志；
而 rm#r04017@堅 ，
又太子之𡚱兄也。

 rm#r02857@皇甫惟明 嘗爲 rm#r01661@忠王 友，
時破吐蕃，
入獻捷，
見 rm#r01824@林甫 專權，
意頗不平。

時因見上，
乘間微勸上去 rm#r01824@林甫 ，
 rm#r01824@林甫 知之，
使 rm#r02191@楊愼矜 密伺其所爲。

會正月望夜，
太子出遊，
與 rm#r04017@堅 相見，
 rm#r04017@堅 又與 rm#r02857@惟明 會於 dm#dm03598@景龍觀 道士之室。

 rm#r02191@愼矜 發其事，
以爲 rm#r04017@堅 戚里，
不應與邊將狎暱。

 rm#r01824@林甫 因奏 rm#r04017@堅 與 rm#r02857@惟明 結謀，
欲共立太子。

 rm#r04017@堅 、 rm#r02857@惟明 下獄，
 rm#r01824@林甫 使 rm#r02191@愼矜 與御史中丞 rm#r02724@王鉷 、 dm#dm00427@京兆 府法曹 rm#r00396@吉温 共鞫之。

上亦疑 rm#r04017@堅 與 rm#r02857@惟明 有謀而不顯其罪，
癸酉，
下制，
責 rm#r04017@堅 以干進不已，
貶 dm#dm06474@縉雲 太守；
 rm#r02857@惟明 以離間君臣，
貶 dm#dm03266@播川 太守；
仍別下制戒百官。
# p 

以 rm#r02632@王忠嗣 爲 dm#dm04695@河西 、 dm#dm08458@隴右 節度使，
兼知 dm#dm03677@朔方 、 dm#dm04672@河東 節度事。

 rm#r02632@忠嗣 始在 dm#dm03677@朔方 、 dm#dm04672@河東 ，
毎互市，
高估馬價，
諸胡聞之，
爭賣馬於 dyn#ch100@唐 ，
 rm#r02632@忠嗣 皆買之。

由是胡馬少，
 dyn#ch100@唐 兵益壯。

及徙 dm#dm08458@隴右 、 dm#dm04695@河西 ，
復請分 dm#dm03677@朔方 、 dm#dm04672@河東 馬九千匹以實之，
其軍亦壯。

 rm#r02632@忠嗣 杖四節，
控制萬里，
天下勁兵重鎭，
皆在掌握，
與吐蕃戰於 dm#dm08673@青海 、 dm#dm06315@積石 ，
皆大捷。

又討吐谷渾於 dm#dm01508@墨離軍 ，
虜其全部而歸。

# p 

夏，
四月，
癸未，
立奚酋 rm#r05366@娑固 爲 rm#r05366@昭信王 ，
契丹酋 rm#r05409@楷洛 爲 rm#r05409@恭仁王 。

# p 

己亥，
制：
「自今四孟月，
皆擇吉日祀天地、九宮。」

# p 

 rm#r04017@韋堅 等既貶，
左相 rm#r01802@李適之 懼，
自求散地。

庚寅，
以 rm#r01802@適之 爲太子少保，
罷政事。

其子衞尉少卿 rm#?@霅 嘗盛饌召客，
客畏 rm#r01824@李林甫 ，
竟日無一人敢往者。
# p 

以門下侍郎、 dm#dm02475@崇玄館 大學士 rm#r03924@陳希烈 同平章事。

 rm#r03924@希烈 ，
 dm#dm02098@宋州 人，
以講老、莊得進，
專用神仙符瑞取媚於上。

 rm#r01824@李林甫 以 rm#r03924@希烈 爲上所愛，
且柔佞易制，
故引以爲相；
凡政事一決於 rm#r01824@林甫 ，
 rm#r03924@希烈 但給唯諾。

故事，
宰相午後六刻乃出，
 rm#r01824@林甫 奏，
今太平無事，
巳時即還第，
軍國機務皆決於私家；
主書抱成案詣 rm#r03924@希烈 書名而已。
# p 

五月，
壬子朔，
日有食之。
# p 

乙亥，
以 dm#dm00785@劍南 節度使 rm#r03051@章仇兼瓊 爲戸部尚書；
諸 rm#no@楊 引之也。
# p 

秋，
七月，
丙辰，
敕：
「流貶人多在道逗留。

自今左降官日馳十驛以上。」

是後流貶者多不全矣。
# p 

 rm#r02136@楊貴𡚱 方有寵，
毎乘馬則 rm#r04220@高力士 執轡授鞭，
織繡之工專供貴𡚱院者七百人，
中外爭獻器服珍玩。

 dm#dm02527@嶺南 經略使 rm#r05243@張九章 ，
 dm#dm02772@廣陵 長史 rm#r02782@王翼 ，
以所獻精美，
 rm#r05243@九章 加三品，
 rm#r02782@翼 入爲戸部侍郎；
天下從風而靡。

民間歌之曰：
「生男勿喜女勿悲，
君今看女作門楣。」

𡚱欲得生茘支，
歳命 dm#dm02527@嶺南 馳驛致之，
比至 dm#dm08170@長安 ，
色味不變。

# p 

至是，
𡚱以妬悍不遜，
上怒，
命送歸兄 rm#r05518@銛 之第。

是日，
上不懌，
比日中，
猶未食，
左右動不稱旨，
横被棰撻。

 rm#r04220@高力士 欲嘗上意，
請悉載院中儲偫送 rm#r02136@貴𡚱 ，
凡百餘車；
上自分御膳以賜之。

及夜，
 rm#r04220@力士 伏奏請迎 rm#r02136@貴𡚱 歸院，
遂開禁門而入。

自是恩遇愈隆，
後宮莫得進矣。
# p 

將作少匠 rm#r06057@韋蘭 、兵部員外郎 rm#r06056@韋芝 爲其兄 rm#r04017@堅 訟冤，
且引太子爲言；
上益怒。

太子懼，
表請與𡚱離婚，
乞不以親廢法。

丙子，
再貶 rm#r04017@堅  dm#dm04483@江夏 別駕，
 rm#r06057@蘭 、 rm#r06056@芝 皆貶 dm#dm02527@嶺南 。

然上素知太子孝謹，
故譴怒不及。

 rm#r01824@李林甫 因言 rm#r04017@堅 與 rm#r01802@李適之 等爲朋黨，
後數日，
 rm#r04017@堅 長流 dm#dm06651@臨封 ，
 rm#r01802@適之 貶 dm#dm02178@宜春 太守，
太常少卿 rm#r04038@韋斌 貶 dm#dm02581@巴陵 太守，
嗣 rm#r00547@薛王琄 貶 dm#dm01839@夷陵 別駕，
 dm#dm06055@睢陽 太守 rm#r03426@裴寛 貶 dm#dm02081@安陸 別駕，
 dm#dm04660@河南 尹 rm#r02017@李齊物 貶 dm#dm06334@竟陵 太守，
凡 rm#r04017@堅 親黨坐流貶者數十人。

 rm#r04038@斌 ，
 rm#r04019@安石 之子。

 rm#r00547@琄 ，
 rm#?@業 之子，
 rm#r04017@堅 之甥也。

 rm#r00547@琄 母亦令隨 rm#r00547@琄 之官。

# p 

冬，
十月，
戊戌，
上幸 dm#dm08874@驪山 温泉；
十一月，
乙巳，
還宮。
# p 

贊善大夫 rm#r05450@杜有鄰 ，
女爲太子良娣，
良娣之姉爲左驍衞兵曹 rm#r05458@柳勣 妻。

 rm#r05458@勣 性狂疏，
好功名，
喜交結豪俊。

 dm#dm04960@淄川 太守 rm#r06255@裴敦復 薦於 dm#dm00875@北海 太守 rm#r01995@李邕 ，
 rm#r01995@邕 與之定交。

 rm#r05458@勣 至 dm#dm08170@京師 ，
與著作郎 rm#r05642@王曾 等爲友，
皆當時名士也。
# p 

 rm#r05458@勣 與妻族不協，
欲陷之，
爲飛語，
告 rm#r05450@有鄰 妄稱圖讖，
交構東宮，
指斥乘輿。

 rm#r01824@林甫 令 dm#dm00427@京兆 士曹 rm#r00396@吉温 與御史鞫之，
乃 rm#r05458@勣 首謀也。

 rm#r00396@温 令 rm#r05458@勣 連引曾等入臺。

十二月，
甲戌，
 rm#r05450@有鄰 、 rm#r05458@勣 及 rm#r05642@曾 等皆杖死，
積尸大理，
妻子流遠方；
中外震慄。

嗣 rm#r03358@虢王巨 貶 dm#dm06561@義陽 司馬，
 rm#r03358@巨 ，
 rm#r01995@邕 之子也。

別遣監察御史 rm#r03083@羅希奭 往按 rm#r01995@李邕 ，
太子亦出良娣爲庶人。
# p 

乙亥，
 dm#dm07975@鄴郡 太守 rm#r02673@王琚 坐贓貶 dm#dm04507@江華 司馬。

琚性豪侈，
與李邕皆自謂耆舊，
久在外，
意怏怏，
 rm#r01824@李林甫 惡其負材使氣，
故因事除之。

*** 六載
# year 0747
# p 

春，
正月，
辛巳。

 rm#r01995@李邕 、 rm#r06255@裴敦復 皆杖死。

 rm#r01995@邕 才藝出衆，
 rm#r02929@盧藏用 常語之曰：
「君如干將、莫邪，
難與爭鋒，
然終虞缺折耳。」

 rm#r01995@邕 不能用。
# p 

 rm#r01824@林甫 又奏分遣御史即貶所賜 rm#r02857@皇甫惟明 、 rm#r04017@韋堅 兄弟等死。

 rm#r03083@羅希奭 自 dm#dm08665@青州 如 dm#dm02527@嶺南 ，
所過殺遷謫者，
郡縣惶駭。

排馬牒至 dm#dm02178@宜春 ，
 rm#r01802@李適之 憂懼，
仰藥自殺。

至 dm#dm04507@江華 ，
 rm#r02673@王琚 仰藥不死，
聞 rm#r03083@希奭 已至，
即自縊。

 rm#r03083@希奭 又迂路過 dm#dm02081@安陸 ，
欲怖殺 rm#r03426@裴寛 ，
 rm#r03426@寛 向 rm#r03083@希奭 叩頭祈生，
 rm#r03083@希奭 不宿而過，
乃得免。

 rm#r01802@李適之 子 rm#?@霅 迎父喪至 dm#dm03788@東京 ，
 rm#r01824@李林甫 令人誣告 rm#?@霅 ，
杖死於 dm#dm04661@河南府 。

給事中 rm#r01381@房琯 坐與 rm#r01802@適之 善，
貶 dm#dm02178@宜春 太守。

 rm#r01381@琯 ，
 rm#ry0022@融 之子也。


# p 

 rm#r01824@林甫 恨 rm#r04017@韋堅 不已，
遣使於循 dm#dm04650@河 及 dm#dm04475@江 、 dm#dm04981@淮 州縣求 rm#r04017@堅 罪，
收繋綱典船夫，
溢於牢獄，
徵剥逋負，
延及鄰伍，
皆裸露死於公府，
至 rm#r01824@林甫 薨乃止。所在
# p 

丁亥，
上享太廟；
戊子，
合祭天地於南郊，
赦天下。

制免百姓 y@今載 田租。

又令削絞、斬條。

上慕好生之名，
故令應絞斬者皆重杖流 dm#dm02527@嶺南 ，
其實有司率杖殺之。

又令天下爲嫁母服三載。

# p 

上欲廣求天下之士，
命通一藝以上皆詣 dm#dm08170@京師 。

 rm#r01824@李林甫 恐草野之士對策斥言其姦惡，
建言：
「舉人多卑賤愚聵，
恐有俚言汚濁聖聽。」

乃令郡縣長官精加試練，
灼然超絶者，
具名送省，
委尚書覆試，
御史中丞監之，
取名實相副者聞奏。

既而至者皆試以詩、賦、論，
遂無一人及第者。

 rm#r01824@林甫 乃上表賀野無遺賢。
# p 

戊寅，
以 dm#dm06863@范陽 、 dm#dm02660@平盧 節度使 rm#r00793@安祿山 兼御史大夫。
# p 

 rm#r00793@祿山 體充肥，
腹垂過膝，
嘗自稱腹重三百斤。

外若癡直，
内實狡黠。

常令其將 rm#xjts25876@劉駱谷 留 dm#dm08170@京師 詗朝廷指趣，
動靜皆報之；
或應有牋表者，
 dm#dm08857@駱谷 即爲代作通之。

歳獻俘虜、雜畜、奇禽、異獸、珍玩之物，
不絶於路，
郡縣疲於遞運。

腹
# p 

 rm#r00793@祿山 在上前，
應對敏給，
雜以詼諧，
上嘗戲指其腹曰：
「此胡腹中何所有？
其大乃爾！」

對曰：
「更無餘物，
正有赤心耳！」

上悦。

又嘗命見太子，
 rm#r00793@祿山 不拜。

左右趣之拜，
 rm#r00793@祿山 拱立曰：
「臣胡人，
不習朝儀，
不知太子者何官？」
上曰：
「此儲君也，
朕千秋萬歳後，
代朕君汝者也。」

 rm#r00793@祿山 曰：
「臣愚，
曏者惟知有陛下一人，
不知乃更有儲君。」

不得已，
然後拜。

上以爲信然，
益愛之。

上嘗宴 dm#dm00820@勤政樓 ，
百官列坐樓下，
獨爲 rm#r00793@祿山 於御座東間設金雞障，
置榻使坐其前，
仍命卷簾以示榮寵。

命 rm#r05518@楊銛 、 rm#r05519@楊錡 、貴𡚱三姉皆與 rm#r00793@祿山 敍兄弟。

 rm#r00793@祿山 得出入禁中，
因請爲貴𡚱兒。

上與貴𡚱共坐，
 rm#r00793@祿山 先拜貴𡚱。

上問何故，
對曰：
「胡人先母而後父。」

上悦。
# p 

 rm#r01824@李林甫 以 rm#r02632@王忠嗣 功名日盛，
恐其入相，
忌之。

 rm#r00793@安祿山 潛蓄異志，
託以禦寇，
築 dm#dm08474@雄武城 ，
大貯兵器，
請 rm#r02632@忠嗣 助役，
因欲留其兵。

 rm#r02632@忠嗣 先期而往，
不見 rm#r00793@祿山 而還，
數上言 rm#r00793@祿山 必反；
 rm#r01824@林甫 益惡之。

夏，
四月，
 rm#r02632@忠嗣 固辭兼 dm#dm04672@河東 、 dm#dm03677@朔方 節度，
許之。
# p 

冬，
十月，
己酉，
上幸 dm#dm08874@驪山 温泉，
改 dm#dm05200@温泉宮 曰 dm#dm06942@華清宮 。
# p 

 dm#dm04695@河西 、 dm#dm08458@隴右 節度使 rm#r02632@王忠嗣 以部將 rm#r00487@哥舒翰 爲 dm#dm01630@大斗軍 副使，
 rm#r01630@李光弼 爲 dm#dm04695@河西 兵馬使、充 dm#dm07587@赤水 軍使。

 rm#r00487@翰 父祖本突騎施別部酋長，
 rm#r01630@光弼 ，
 rm#r05409@契丹王楷洛 之子也，
皆以勇略爲 rm#r02632@忠嗣 所重。

 rm#r02632@忠嗣 使 rm#r00487@翰 撃 dm#*dm01250@吐蕃 ，
有同列爲之副，
倨慢不爲用，
翰檛殺之，
軍中股慄，
累功至 dm#dm08458@隴右 節度副使。

毎歳 dm#dm06318@積石軍 麥熟，
吐蕃輒來穫之，
無能禦者，
邊人謂之「吐蕃麥莊」。

 rm#r00487@翰 先伏兵於其側，
虜至，
斷其後，
夾撃之，
無一人得返者，
自是不敢復來。

# p 

上欲使 rm#r02632@王忠嗣 攻吐蕃 dm#dm06084@石堡城 ，
 rm#r02632@忠嗣 上言：
「 dm#dm06083@石堡 險固，
吐蕃舉國守之，
今頓兵其下，
非殺數萬人不能克；
臣恐所得不如所亡，
不如且厲兵秣馬，
俟其有釁，
然後取之。」

上意不快。

將軍 rm#rx0002@董延光 自請將兵取 dm#dm06084@石堡城 ，
上命 rm#r02632@忠嗣 分兵助之。

 rm#r02632@忠嗣 不得已奉詔，
而不盡副 rm#rx0002@延光 所欲，
 rm#rx0002@延光 怨之。
# p 

 rm#r01630@李光弼 言於 rm#r02632@忠嗣 曰：
「大夫以愛士卒之故，
不欲成 rm#rx0002@延光 之功，
雖迫於制書，
實奪其謀也。

何以知之？
今以數萬衆授之而不立重賞，
士卒安肯爲之盡力乎！

然此天子意也，
彼無功，
必歸罪於大夫。

大夫軍府充牣，
何愛數萬段帛不以杜其讒口乎！」

 rm#r02632@忠嗣 曰：
「今以數萬之衆爭一城，
得之未足以制敵，
不得亦無害於國，
故 rm#r02632@忠嗣 不欲爲之。

 rm#r02632@忠嗣 今受責，
天子不過以金吾、羽林一將軍歸宿衞，
其次不過黔中上佐；
 rm#r02632@忠嗣 豈以數萬人之命易一官乎！

 rm#?@李將軍 ，
子誠愛我矣，
然吾志決矣，
子勿復言。」

 rm#r01630@光弼 曰：
「曏者恐爲大夫之累，
故不敢不言。

今大夫能行古人之事，
非 rm#r01630@光弼 所及也。」

遂趨出。
# p 

 rm#rx0002@延光 過期不克，
言 rm#r02632@忠嗣 沮撓軍計，
上怒。

 rm#r01824@李林甫 因使 dm#dm05448@濟陽 別駕 rm#r06123@魏林 告「 rm#r02632@忠嗣 嘗自言我幼養宮中，
與 rm#r01661@忠王 相愛狎」，
欲擁兵以尊奉太子。

敕徵 rm#r02632@忠嗣 入朝，
委三司鞫之。
# p 

上聞 rm#r00487@哥舒翰 名，
召見 dm#dm06942@華清宮 ，
與語，
悦之。

十一月，
辛卯，
以 rm#r00487@翰 判 dm#dm07321@西平 太守，
充 dm#dm08458@隴右 節度使；
以 dm#dm03677@朔方 節度使 rm#r06178@安思順 判 dm#dm04243@武威郡 事，
充 dm#dm04695@河西 節度使。

# p 

戸部侍郎兼御史中丞 rm#r02191@楊愼矜 爲上所厚，
 rm#r01824@李林甫 浸忌之。

 rm#r02191@愼矜 與 rm#r02724@王鉷 父 rm#?@晉 ，
中表兄弟也，
少與 rm#r02724@鉷 狎，
 rm#r02724@鉷 之入臺，
頗因 rm#r02191@愼矜 推引。

及 rm#r02724@鉷 遷中丞，
 rm#r02191@愼矜 與語，
猶名之；
 rm#r02724@鉷 自恃與 rm#r01824@林甫 善，
意稍不平。

 rm#r02191@愼矜 奪 rm#r02724@鉷 職田，
 rm#r02724@鉷 母本賤，
 rm#r02191@愼矜 嘗以語人；
 rm#r02724@鉷 深銜之。

 rm#r02191@愼矜 猶以故意待之，
嘗與之私語讖書。

# p 

 rm#r02191@愼矜 與術士 rm#r05097@史敬忠 善，
 rm#r05097@敬忠 言天下將亂，
勸 rm#r02191@愼矜 於 dm#dm06671@臨汝山 中買莊爲避亂之所。

會 rm#r02191@愼矜 父墓田中草木皆流血，
 rm#r02191@愼矜 惡之，
惡，
烏路翻。

以問 rm#r05097@敬忠 。

 rm#r05097@敬忠 請禳之，
設道場於後園，
 rm#r02191@愼矜 退朝，
輒躶貫桎梏坐其中。

旬日血止，
 rm#r02191@愼矜 徳之。

 rm#r02191@愼矜 有侍婢 rm#r06612@明珠 ，
色美，
 rm#r05097@敬忠 屡目之，
 rm#r02191@愼矜 即以遺 rm#r05097@敬忠 ，
車載過 rm#r02136@貴𡚱 姉 rm@柳氏 樓下，
姉邀 rm#r05097@敬忠 上樓，
求車中美人，
 rm#r05097@敬忠 不敢拒。

明日，
姉入宮，
以 rm#r06612@明珠 自隨。

上見而異之，
問所從來，
 rm#r06612@明珠 具以實對。

上以 rm#r02191@愼矜 與術士爲妖法，
惡之，
含怒未發。
# p 

 rm#r02248@楊釗 以告 rm#r02724@鉷 ，
 rm#r02724@鉷 心喜，
因侮慢 rm#r02191@愼矜 ；
 rm#r02191@愼矜 怒。

 rm#r01824@林甫 知 rm#r02724@鉷 與 rm#r02191@愼矜 有隙，
密誘使圖之。

 rm#r02724@鉷 乃遣人以飛語告「 rm#r02191@愼矜  rm#r02546@隋煬帝 孫，
與凶人往來，
家有讖書，
謀復祖業。」

上大怒，
收 rm#r02191@愼矜 繋獄，
命刑部、大理與侍御史 rm#r02248@楊釗 、殿中侍御史 rm#r02936@盧鉉 同鞫之。

太府少卿 rm#r01217@張瑄 ，
 rm#r02191@愼矜 所薦也，
 rm#r02936@盧鉉 誣 rm#r01217@瑄 嘗與 rm#r02191@愼矜 論讖，
拷掠百端，
 rm#r01217@瑄 不肯答辯。

乃以木綴其足，
使人引其枷柄，
向前挽之，
身加長數尺，
腰細欲絶，
眼鼻出血，
 rm#r01217@瑄 竟不答。
# p 

又使 rm#r00396@吉温 捕 rm#r05097@史敬忠 於 dm#dm04465@汝州 。

 rm#r05097@敬忠 與 rm#r00396@温 父素善，
 rm#r00396@温 之幼也，
 rm#r05097@敬忠 常抱撫之。

及捕獲，
温不與交言，
鎖其頸，
以布蒙首，
驅之馬前。

至 dm#dm03152@戲水 ，
 rm#r00396@温 使吏誘之曰：
「 rm#r02191@楊愼矜 已款服，
惟須子一辯，
若解人意則生，
不然必死，
前至温湯，
則求首不獲矣。」

 rm#r05097@敬忠 顧謂 rm#r00396@温 曰：
「 rm#r00396@七郎 ，
求一紙。」

 rm#r00396@温 陽不應。

去温湯十餘里，
 rm#r05097@敬忠 祈請哀切，
乃於桑下令答三紙，
辯皆如 rm#r00396@温 意。

 rm#r00396@温 徐謂曰：
「丈人且勿怪！」

因起拜之。
# p 

至 y@會昌 ，
始鞫 rm#r02191@愼矜 ，
以 rm#r01165@敬忠 爲證。

 rm#r02191@愼矜 皆引服，
惟搜讖書不獲。

 rm#r01824@林甫 危之，
使 rm#r02936@盧鉉 入 dm#dm08170@長安 搜 rm#r02191@愼矜 家，
 rm#r02936@鉉 袖讖書入闇中，
詬而出曰：
「逆賊深藏祕記。」

至 dm#dm03656@會昌 ，
以示 rm#r02191@愼矜 。

 rm#r02191@愼矜 歎曰：
「吾不蓄讖書，
此何從在吾家哉！

吾應死而已。」

丁酉，
賜 rm#r02191@愼矜 及兄少府少監 rm#?@愼餘 、 dm#dm04788@洛陽 令 rm#?@愼名 自盡；
 rm#r01165@敬忠 杖百，
妻子皆流 dm#dm02527@嶺南 ；
 rm#r01217@瑄 杖六十，
流 dm#dm06651@臨封 ，
死於 dm#dm03656@會昌 。

嗣 rm#r03358@虢王巨 雖不預謀，
坐與 rm#r01165@敬忠 相識，
解官，
 dm#dm01056@南賓 安置。

自餘連坐者數十人。

 rm#?@愼名 聞敕，
神色不變，
爲書別姉；
 rm#?@愼餘 合掌指天而縊。
# p 

三司按 rm#r02632@王忠嗣 ，
上曰：
「吾兒居深宮，
安得與外人通謀，
此必妄也。

但劾 rm#r02632@忠嗣 沮撓軍功。」

 rm#r00487@哥舒翰 之入朝也，
或勸多齎金帛以救 rm#r02632@忠嗣 。

 rm#r00487@翰 曰：
「若直道尚存，
 rm#r00271@王公 必不冤死；
如其將喪，
多賂何爲！」

遂單嚢而行。

三司奏 rm#r02632@忠嗣 罪當死。

 rm#r00487@翰 始遇知於上，
力陳 rm#r02632@忠嗣 之冤，
且請以己官爵贖 rm#r02632@忠嗣 罪；
上起，
入禁中，
 rm#r00487@翰 叩頭隨之，
言與涙倶。

上感寤，
己亥，
貶 rm#r02632@忠嗣  dm#dm05302@漢陽 太守。

# p 

 rm#r01824@李林甫 屡起大獄，
別置推事院於 dm#dm08170@長安 。

以 rm#r02248@楊釗 有掖庭之親，
出入禁闥，
所言多聽，
乃引以爲援，
擢爲御史。

事有微渉東宮者，
皆指擿使之奏劾，
付 rm#r03083@羅希奭 、 rm#r00396@吉温 鞫之。

 rm#r02248@釗 因得逞其私志，
所擠陷誅夷者數百家，
皆 rm#r02248@釗 發之。

幸太子仁孝謹靜，
 rm#r01088@張垍 、 rm#r04220@高力士 常保護於上前，
故 rm#r01824@林甫 終不能間也。


# p 

十二月，
壬戌，
發 dm#dm08850@馮翊 、 dm#dm06943@華陰 民夫築 dm#dm03657@會昌城 ，
置百司。

王公各置第舍，
土畝直千金。

癸亥，
上還宮。


# p 

丙寅，
命百官閲天下歳貢物於尚書省，
既而悉以車載賜 rm#r01824@李林甫 家。

上或時不視朝，
百司悉集 rm#r01824@林甫 第門，
臺省爲空。

 rm#r03924@陳希烈 雖坐府，
無一人入謁者。
# p 

 rm#r01824@林甫 子 rm#?@岫 爲將作監，
頗以滿盈爲懼，
嘗從 rm#r01824@林甫 遊後園，
指役夫言於 rm#r01824@林甫 曰：
「大人久處鈞軸，
怨仇滿天下，
一朝禍至，
欲爲此得乎！」

 rm#r01824@林甫 不樂曰：
「勢已如此，
將若之何！

」
# p 

先是，
宰相皆以徳度自處，
不事威勢，
騶從不過數人，
士民或不之避。

 rm#r01824@林甫 自以多結怨，
常虞刺客，
出則歩騎百餘人，
爲左右翼，
金吾靜街，
前驅在數百歩外，
公卿走避；
居則重關複壁，
以石甃地，
牆中置板，
如防大敵，
一夕屡徙牀，
雖家人莫知其處。

宰相騶從之盛，
自 rm#r01824@林甫 始。
# p 

初，
將軍 rm#r04214@高仙芝 ，
本 dm#dm08934@高麗 人，
從軍 dm#dm02061@安西 。

 rm#r04214@仙芝 驍勇，
善騎射，
節度使 rm#r06079@夫蒙靈詧 屡薦至 dm#dm02061@安西 副都護、都知兵馬使，
充四鎭節度副使。
# p 

吐蕃以女妻 rm#?@小勃律王 ，
及其旁二十餘國，
皆附吐蕃，
貢獻不入，
前後節度使討之，
皆不能克。

制以 rm#r04214@仙芝 爲行營節度使，
將萬騎討之。

自 dm#dm02061@安西 行百餘日，
乃至 dm#dm05639@特勒滿川 ，
分軍爲三道，
期以七月十三日會吐蕃 dm#dm07717@連雲堡 下。

有兵近萬人，
不意 dyn#ch100@唐 兵猝至，
大驚，
依山拒戰，
礮櫑如雨。

 rm#r04214@仙芝 以郎將 dm#dm08924@高陵  rm#r01663@李嗣業 爲陌刀將，
令之曰：
「不及日中，
決須破虜。」

嗣業執一旗，
引陌刀縁險先登力戰，
自辰至巳，
大破之，
斬首五千級，
捕虜千餘人，
餘皆逃潰。

中使 rm#?@邊令誠 以入虜境已深，
懼不敢進；
 rm#r04214@仙芝 乃使令誠以羸弱三千守其城，
復進。
# p 

三日，
至 dm#dm01477@坦駒嶺 ，
下峻阪四十餘里，
前有 dm#dm08297@阿弩越城 。

 rm#r04214@仙芝 恐士卒憚險，
不肯下，
先令人胡服詐爲阿弩越城守者迎降，
云：
「阿弩越赤心歸 dyn#ch100@唐 ，
 dm#dm01916@娑夷水 藤橋已斫斷矣。」

 dm#dm01916@娑夷水 ，
即 dm#dm02896@弱水 也，
其水不能勝草芥。

藤橋者，
通吐蕃之路也。

 rm#r04214@仙芝 陽喜，
士卒乃下。

又三日，
 dm#dm08297@阿弩越城 迎者果至。
# p 

明日，
 rm#r04214@仙芝 入 dm#dm08297@阿弩越城 ，
遣將軍 rm#rx0003@席元慶 將千騎前行，
謂曰：
「 dm#dm02359@小勃律 聞大軍至，
其君臣百姓必走山谷，
第呼出，
取繒帛稱敕賜之，
大臣至，
盡縛之以待我。」

 rm#rx0003@元慶 如其言，
悉縛諸大臣。

王及吐蕃公主逃入石窟，
取不可得。

 rm#r04214@仙芝 至，
斬其附吐蕃者大臣數人。


# p 

藤橋去城猶六十里，
 rm#r04214@仙芝 急遣 rm#rx0003@元慶 往斫之，
甫畢，
吐蕃兵大至，
已無及矣。

藤橋闊盡一矢，
力脩之，
期年乃成。
# p 

八月，
 rm#r04214@仙芝 虜 rm#?@小勃律王 及吐蕃公主而還。

九月，
至 dm#dm07717@連雲堡 ，
與 rm#?@邊令誠 倶。

月末，
至 dm#dm03264@播密川 ，
遣使奏状。

# p 

至河西，
 rm#r06079@夫蒙靈詧 怒 rm#r04214@仙芝 不先言己而遽發奏，
一不迎勞，
罵 rm#r04214@仙芝 曰：
「噉狗糞 dm#dm08934@高麗 奴！

汝官皆因誰得，
而不待我處分，
奏捷書！

 dm#dm08934@高麗 奴！

汝罪當斬，
但以汝新有功不忍耳！」

 rm#r04214@仙芝 但謝罪。

 rm#?@邊令誠 奏 rm#r04214@仙芝 深入萬里，
立奇功，
今旦夕憂死。
# p 

十二月，
己巳，
上以 rm#r04214@仙芝 爲 dm#dm02061@安西 四鎭節度使，
徵 rm#?@靈詧 入朝，
 rm#?@靈詧 大懼。

 rm#r04214@仙芝 見 rm#?@靈詧 ，
趨走如故，
 rm#?@靈詧 益懼。

副都護 dm#dm00427@京兆  rm#r02989@程千里 、押牙 rm#r05680@畢思琛 及行官 rm#r05646@王滔 等，
皆平日構 rm#r04214@仙芝 於 rm#?@靈詧 者也，
 rm#r04214@仙芝 面責 rm#r02989@千里 、 rm#r05680@思琛 曰：
「公面如男子，
心如婦人，
何也？」
又捽 rm#r05646@滔 等，
欲笞之，
既而皆釋之，
謂曰：
「吾素所恨於汝者，
欲不言，
恐汝懷憂；
今既言之，
則無事矣。」

軍中乃安。
# p 

初，
 rm#r04214@仙芝 爲都知兵馬使，
 dm#dm05659@猗氏 人 rm#r00852@封常清 ，
少孤貧，
細痩纇目，
一足偏短，
求爲 rm#r04214@仙芝 傔，
不納。

 rm#r00852@常清 日候 rm#r04214@仙芝 出入，
不離其門，
凡數十日，
 rm#r04214@仙芝 不得已留之。

會達奚部叛，
 rm#r06079@夫蒙靈詧 使 rm#r04214@仙芝 追之，
斬獲略盡。

 rm#r00852@常清 私作捷書以示 rm#r04214@仙芝 ，
皆 rm#r04214@仙芝 心所欲言者，
由是一府奇之。

 rm#r04214@仙芝 爲節度使，
即署 rm#r00852@常清 判官；
 rm#r04214@仙芝 出征，
常爲留後。

 rm#r04214@仙芝 乳母子 rm#r05961@鄭徳詮 爲郎將，
 rm#r04214@仙芝 遇之如兄弟，
使典家事，
威行軍中。

 rm#r00852@常清 嘗出，
 rm#r05961@徳詮 自後走馬突之而過。

 rm#r00852@常清 至使院，
使召 rm#r05961@徳詮 ，
毎過一門，
輒闔之，
既至，
 rm#r00852@常清 離席謂曰：
「 rm#r00852@常清 本出寒微，
郎將所知。

今日中丞命爲留後，
郎將何得於衆中相陵突！」

因叱之曰：
「郎將須蹔死以肅軍政。

」
遂杖之六十，
面仆地，
曳出。

 rm#r04214@仙芝 妻及乳母於門外號哭救之，
不及，
因以状白 rm#r04214@仙芝 ，
 rm#r04214@仙芝 覽之，
驚曰：
「已死邪？」
及見 rm#r00852@常清 ，
遂不復言，
 rm#r00852@常清 亦不之謝。

軍中畏之惕息。

# p 

自 dyn#ch100@唐 興以來，
邊帥皆用忠厚名臣，
不久任，
不遙領，
不兼統，
功名著者往往入爲宰相。

其四夷之將，
雖才略如 rm#r03900@阿史那社爾 、 rm#r00611@契苾何力 猶不專大將之任，
皆以大臣爲使以制之。

及 y@開元中 ，
天子有呑四夷之志，
爲邊將者十餘年不易，
始久任矣；
皇子則 rm#?@慶 、 rm#?@忠 諸王，
宰相則 rm#r03240@蕭嵩 、 rm#r02557@牛仙客 ，
始遙領矣；
 rm#r06242@蓋嘉運 、 rm#r02632@王忠嗣 專制數道，
始兼統矣。

 rm#r01824@李林甫 欲杜邊帥入相之路，
以胡人不知書，
乃奏言：
「文臣爲將，
怯當矢石，
不若用寒畯胡人；
胡人則勇決習戰，
寒族則孤立無黨，
陛下誠以恩洽其心，
彼必能爲朝廷盡死。」

上悦其言，
始用 rm#r00793@安祿山 。

至是，
諸道節度盡用胡人，
精兵咸戍北邊，
天下之勢偏重，
卒使 rm#r00793@祿山 傾覆天下，
皆出於 rm#r01824@林甫 專寵固位之謀也。

*** 七載
# year 0748
# p 

夏，
四月，
辛丑，
左監門大將軍、知内侍省事 rm#r04220@高力士 加驃騎大將軍。

 rm#r04220@力士 承恩歳久，
中外畏之，
太子亦呼之爲兄，
諸王公呼之爲翁，
駙馬輩直謂之爺。

自 rm#r01824@李林甫 、 rm#r00793@安祿山 輩皆因之以取將相。

其家富厚不貲。

於 dm#dm07290@西京 作 dm#dm02317@寶壽寺 ，
寺鐘成，
 rm#r04220@力士 作齋以慶之，
舉朝畢集。

撃鐘一杵，
施錢百緡，
有求媚者至二十杵，
少者不減十杵。

然性和謹少過，
善觀時俯仰，
不敢驕横，
故天子終親任之，
士大夫亦不疾惡也。

# p 

五月，
壬午，
羣臣上尊號曰 rm#r02004@開元天寶聖文神武應道皇帝 ；
赦天下，
免百姓來載租庸，
擇 dyn#ch169@後魏 子孫一人爲三恪。

# p 

六月，
庚子，
賜 rm#r00793@安祿山 鐵券。
# p 

度支郎中兼侍御史 rm#r02248@楊釗 善窺上意所愛惡而迎之，
以聚斂驟遷，
歳中領十五餘使。

甲辰，
遷給事中，
兼御史中丞，
專判度支事，
恩幸日隆。
# p 

 rm#r03327@蘇冕 論曰：
「設官分職，
各有司存。

政有恆而易守，
事歸本而難失，
經遠之理，
捨此奚據！

洎姦臣廣言利以邀恩，
多立使以示寵，
刻下民以厚斂，
張虚數以獻状；
上心蕩而益奢，
人望怨而成禍；
使天子有司守其位而無其事，
受厚祿而虚其用。

 rm#r00766@宇文融 首唱其端，
 rm#r02191@楊愼矜 、 rm#r02724@王鉷 繼遵其軌，
 rm#r02248@楊國忠 終成其亂。

 rm#r06150@仲尼 云：
寧有盜臣而無聚斂之臣。

誠哉是言！

前車既覆，
後轍未改，
求達化本，
不亦難乎！

」
# p 

冬，
十月，
庚戌，
上幸 dm#dm06942@華清宮 。
# p 

十一月，
癸未，
以 rm#r02136@貴𡚱 姉適 rm#?@崔氏 者爲 rm#xjts22963@韓國夫人 ，
適 rm#?@裴氏 者爲 rm#?@虢國夫人 ，
適 rm#?@柳氏 者爲 rm#?@秦國夫人 。

三人皆有才色，
上呼之爲姨，
出入宮掖，
竝承恩澤，
勢傾天下。

毎命婦入見，
 rm#r02586@玉眞公主 等皆讓不敢就位。

三姉與 rm#r05518@銛 、 rm#r05519@錡 五家，
凡有請託，
府縣承迎，
峻於制敕；
四方賂遺，
輻湊其門，
惟恐居後，
朝夕如市。

十宅諸王及百孫院婚嫁，
皆以錢千緡賂 rm#ry0003@韓 、 rm#?@虢 使請，
無不如志。

上所賜與及四方獻遺，
五家如一。

競開第舍，
極其壯麗，
一堂之費，
動踰千萬；
既成，
見他人有勝己者，
輒毀而改爲。

 rm#?@虢國 尤爲豪蕩，
一旦，
帥工徒突入 rm#r04015@韋嗣立 宅，
即撤去舊屋，
自爲新第，
但授 rm#r00840@韋氏 以隙地十畝而已。

中堂既成，
召工圬墁，
約錢二百萬；
復求賞技，
 rm#?@虢國 以絳羅五百段賞之，
嗤而不顧，
曰：
「請取螻蟻、蜥蜴，
記其數置堂中，
苟失一物，
不敢受直。」

# p 

十二月，
戊戌，
或言 rm#ry0032@玄元皇帝 降於 dm#dm03709@朝元閣 ，
制改 dm#dm03659@會昌縣 曰 dm#dm03519@昭應 ，
廢 dm#dm03393@新豐 入 dm#dm03519@昭應 。

辛酉，
上還宮。

# p 

 rm#r00487@哥舒翰 築 dm#dm06220@神威軍 於 dm#dm08673@青海 上，
吐蕃至，
 rm#r00487@翰 撃破之。

又築城於 dm#dm08673@青海 中 dm#dm09282@龍駒島 ，
謂之 dm#dm03093@應龍城 ，
吐蕃屏跡不敢近 dm#dm08673@青海 。

# p 

 y@是歳 ，
 rm#?@雲南王歸義 卒，
子 rm#?@閤羅鳳 嗣，
以其子 rm#?@鳳迦異 爲 dm#dm08415@陽瓜州 刺史。

*** 八載
# year 0749
# p 

春，
二月，
戊申，
引百官觀左藏，
賜帛有差。

是時州縣殷富，
倉庫積粟帛，
動以萬計。

 rm#r02248@楊釗 奏請所在糶變爲輕貨，
及徵丁租地税皆變布帛輸 dm#dm08170@京師 ；
屡奏帑藏充牣，
古今罕儔，
故上帥羣臣觀之，
賜 rm#r02248@釗 紫衣金魚以賞之。

上以國用豐衍，
故視金帛如糞壤，
賞賜貴寵之家，
無有限極。
# p 

三月，
 dm#dm03677@朔方 節度等使 rm#r01275@張齊丘 於 dm#dm00253@中受降城 西北五百餘里 dm#dm03726@木剌山 築 dm#dm04180@横塞軍 ，
以 dm#dm03231@振遠軍 使 dm#dm07947@鄭 人 rm#r03707@郭子儀 爲 dm#dm04180@横塞軍 使。

# p 

夏，
四月，
 dm#dm01339@咸寧 太守 rm#r05900@趙奉璋 告 rm#r01824@李林甫 罪二十餘條；
状未達，
 rm#r01824@林甫 知之，
諷御史逮捕，
以爲妖言，
杖殺之。

# p 

先是，
折衝府皆有木契、銅魚，
朝廷徵發，
下敕書、契、魚，
都督、郡府參驗皆合，
然後遣之。

自募置彍騎，
府兵日益墮壞，
死及逃亡者，
有司不復點補；
其六駄馬牛、器械、糗糧，
耗散略盡。

府兵入宿衞者，
謂之侍官，
言其爲天子侍衞也。

其後本衞多以假人，
役使如奴隸；
 dm#dm08170@長安 人羞之，
至以相詬病。

其戍邊者，
又多爲邊將苦使，
利其死而沒其財。

由是應爲府兵者皆逃匿，
至是無兵可交。

五月，
癸酉，
 rm#r01824@李林甫 奏停折衝府上下魚書；
是後府兵徒有官吏而已。

其折衝、果毅，
又歴年不遷，
士大夫亦恥爲之。

其彍騎之法，
 y@天寶 以後，
稍亦變廢，
應募者皆市井負販、無頼子弟，
未嘗習兵。

時承平日久，
議者多謂 dm#dm00255@中國 兵可銷，
於是民間挾兵器者有禁；
子弟爲武官，
父兄擯不齒。

猛將精兵，
皆聚於西北，
 dm#dm00255@中國 無武備矣。

# p 

 dm#dm01817@太白山 人 rm#r05413@李渾 等上言見神人，
言 dm#dm08035@金星洞 有玉板石記聖主福壽之符，
命御史中丞 rm#r02724@王鉷 入 dm#dm00478@仙遊谷 求而獲之。

上以符瑞相繼，
皆祖宗休烈，
六月，
戊申，
上 rm#ry0032@聖祖 號曰 rm#ry0032@大道玄元皇帝 ，
上 rm#r04258@高祖 諡曰 rm#r04258@神堯大聖皇帝 ，
 rm#r01602@太宗 諡曰 rm#r01602@文武大聖皇帝 ，
 rm#r01837@高宗 諡曰 rm#r01837@天皇大聖皇帝 ，
 rm#r01656@中宗 諡曰 rm#r01656@孝和大聖皇帝 ，
 rm#r01797@睿宗 諡曰 rm#r01797@玄眞大聖皇帝 ，
 rm#r03009@竇太后 以下皆加諡曰 rm#r03009@順聖皇后 。
# p 

辛亥，
刑部尚書、 dm#dm00427@京兆 尹 rm#r04315@蕭炅 坐贓左遷 dm#dm04469@汝陰 太守。

# p 

上命 dm#dm08458@隴右 節度使 rm#r00487@哥舒翰 帥 dm#dm08458@隴右 、 dm#dm04695@河西 及突厥 rm#?@阿布思 兵，
益以 dm#dm03677@朔方 、 dm#dm04672@河東 兵，
凡六萬三千，
攻吐蕃 dm#dm06084@石堡城 。

其城三面險絶，
惟一徑可上，
吐蕃但以數百人守之，
多貯糧食，
積檑木及石，
 dyn#ch100@唐 兵前後屡攻之，
不能克。

 rm#r00487@翰 進攻數日不拔，
召裨將 rm#r06280@高秀巖 、 rm#r05265@張守瑜 ，
欲斬之，
二人請三日期可克；
如期拔之，
獲吐蕃 rm#?@鐵刃悉諾羅 等四百人，
 dyn#ch100@唐 士卒死者數萬，
果如 rm#r02632@王忠嗣 之言。

頃之，
 rm#r00487@翰 又遣兵於 dm#dm07582@赤嶺 西開屯田，
以謫卒二千戍 dm#dm09282@龍駒島 ，
冬冰合，
吐蕃大集，
戍者盡沒。

# p 

閏月，
乙丑，
以 dm#dm06084@石堡城 爲 dm#dm06226@神武軍 ，
又於 dm#dm00783@劍南西山  dm#dm06402@索磨川 置 dm#dm00563@保寧都護府 。


# p 

丙寅，
上謁 dm#dm01814@太清宮 。

丁卯，
羣臣上尊號曰 rm#r02004@開元天地大寶聖文神武應道皇帝 ，
赦天下。

禘、祫自今於 dm#dm01814@太清宮  rm#ry0032@聖祖 前設位序正。
# p 

秋，
七月，
册突騎施 rm#?@移撥 爲十姓可汗。

# p 

八月，
乙亥，
 rm#r05744@護密王羅眞檀 入朝，
請留宿衞；
許之，
拜左武衞將軍。
# p 

冬，
十月，
乙丑，
上幸 dm#dm06942@華清宮 。
# p 

十一月，
乙未，
吐火羅葉護 rm#xjts09612@失里怛伽羅 遣使表稱：
「 rm#?@朅師王 親附吐蕃，
困苦 dm#dm02359@小勃律 鎭軍，
阻其糧道。

臣思破凶徒，
望發 dm#dm02061@安西 兵，
以 y@來歳正月 至 dm#dm02359@小勃律 ，
六月至 dm#dm01576@大勃律 。」

上許之。
*** 九載
# year 0750
# p 

春，
正月，
己亥，
上還宮。
# p 

羣臣屡表請封 dm#dm07315@西嶽 ，
許之。
# p 

二月，
 rm#r02136@楊貴𡚱 復忤旨，
送歸私第。

戸部郎中 rm#r00396@吉温 因宦官言於上曰：
「婦人識慮不遠，
違忤聖心，
陛下何愛宮中一席之地，
不使之就死，
豈忍辱之於外舍邪？」
上亦悔之，
遣中使賜以御膳。

𡚱對使者涕泣曰：
「妾罪當死，
陛下幸不殺而歸之。

今當永離掖庭，
金玉珍玩，
皆陛下所賜，
不足爲獻，
惟髮者父母所與，
敢以薦誠。」

乃翦髮一繚而獻之。

上遽使 rm#r04220@高力士 召還，
寵待益深。

# p 

時諸貴戚競以進食相尚，
上命宦官 rm#r05143@姚思藝 爲檢校進食使，
水陸珍羞數千盤，
一盤費中人十家之産。

中書舍人 rm#r05734@竇華 嘗退朝，
値公主進食，
列於中衢，
傳呼按轡出其間；
宮苑小兒數百奮梃於前，
 rm#r05734@華 僅以身免。
# p 

 dm#dm02061@安西 節度使 rm#r04214@高仙芝 破朅師，
虜其王 rm#?@勃特沒 。

三月，
庚子，
立 rm#?@勃特沒 之兄 rm#?@素迦 爲朅師王。

# p 

上命御史大夫 rm#r02724@王鉷 鑿 dm#dm06933@華山 路，
設壇場於其上。

是春，
 dm#dm08281@關中 旱；
辛亥，
 dm#dm02534@嶽祠 災；
制罷封 dm#dm07315@西嶽 。


# p 

夏，
四月，
己巳，
御史大夫 rm#r00811@宋渾 坐贓巨萬，
流 dm#dm05378@潮陽 。

初，
 rm#r00396@吉温 因 rm#r01824@李林甫 得進；
及兵部侍郎兼御史中丞 rm#r02248@楊釗 恩遇浸深，
 rm#r00396@温 遂去 rm#r01824@林甫 而附之，
爲 rm#r02248@釗 畫代 rm#r01824@林甫 執政之策。

 rm#r04315@蕭炅 及 rm#r00811@渾 ，
皆 rm#r01824@林甫 所厚也，
求得其罪，
使 rm#r02248@釗 奏而逐之，
以翦其心腹，
 rm#r01824@林甫 不能救也。
# p 

五月，
乙卯，
賜 rm#r00793@安祿山 爵 rm#r00793@東平郡王 。

 dyn#ch100@唐 將帥封王自此始。

# p 

秋，
七月，
乙亥，
置 dm#dm02745@廣文館 於國子監，
以教諸生習進士者。

# p 

八月，
丁巳，
以 rm#r00793@安祿山 兼 dm#dm04658@河北道 采訪處置使。
# p 

 dm#dm03677@朔方 節度使 rm#r01275@張齊丘 給糧失宜，
軍士怒，
毆其判官；
兵馬使 rm#r03707@郭子儀 以身捍 rm#r01275@齊丘 ，
乃得免。

癸亥，
 rm#r01275@齊丘 左遷 rm#r01275@濟陰太守 ，
以 dm#dm04695@河西 節度使 rm#r06178@安思順 權知 dm#dm03677@朔方 節度事。
# p 

辛卯，
處士 rm#r05219@崔昌 上言：
「國家宜承 dyn#ch103@周 、 dyn#ch129@漢 ，
以土代火；
 dyn#ch173@周 、 dyn#ch174@隋 皆閏位，
不當以其子孫爲二王後。」

事下公卿集議。

 dm#dm08489@集賢殿 學士 rm#r05000@衞包 上言：
「集議之夜，
四星聚於尾，
天意昭然。」

上乃命求 dyn#ch102@殷 、 dyn#ch103@周 、 dyn#ch129@漢 後爲三恪，
廢 rm#xjts03368@韓 、 rm#?@介 、 rm#?@酅公 ；
以 rm#r05219@昌 爲左贊善大夫，
 rm#r05000@包 爲虞部員外郎。
# p 

冬，
十月，
庚申，
上幸 dm#dm06942@華清宮 。
# p 

 dm#dm01817@太白山 人 rm#r05650@王玄翼 上言見 rm#ry0032@玄元皇帝 ，
言 dm#dm02315@寶仙洞 有妙寶眞符。

命刑部尚書 rm#r01127@張均 等往求，
得之。

時上尊道教，
慕長生，
故所在爭言符瑞，
羣臣表賀無虚月。

 rm#r01824@李林甫 等皆請捨宅爲觀以祝聖壽，
上悦。
# p 

 rm#r00793@安祿山 屡誘奚、契丹，
爲設會，
飮以莨菪酒，
醉而阬之，
動數千人，
函其酋長之首以獻，
前後數四。

至是請入朝，
上命有司先爲起第於 dm#dm03519@昭應 。

 rm#r00793@祿山 至 dm#dm03152@戲水 ，
 rm#r02248@楊釗 兄弟姉妹皆往迎之，
冠蓋蔽野；
上自幸 dm#dm03699@望春宮 以待之。

辛未，
 rm#r00793@祿山 獻奚俘八千人，
上命考課之日書上上考。

前此聽 rm#r00793@祿山 於 dm#dm00190@上谷 鑄錢五壚，
 rm#r00793@祿山 乃獻錢樣千緡。

# p 

 rm#r02248@楊釗 ，
 rm#r01178@張易之 之甥也，
奏乞昭雪 rm#r01178@易之 兄弟。

庚辰，
制引 rm#r01178@易之 兄弟迎 rm#r01656@中宗 於 dm#dm03164@房陵 之功，
復其官爵；
仍賜一子官。
# p 

釗以圖讖有「金刀」，
請更名；
上賜名 rm#r02248@國忠 。
# p 

十二月，
乙亥，
上還宮。
# p 

 dm#dm08288@關西 遊弈使 rm#r02718@王難得 撃吐蕃，
克 dm#dm00388@五橋 ，
拔 dm#dm04174@樹敦城 ；
以 rm#r02718@難得 爲 dm#dm05892@白水軍 使。


# p 

 dm#dm02061@安西 四鎭節度使 rm#r04214@高仙芝 僞與 dm#dm06074@石國 約和，
引兵襲之，
虜其王及部衆以歸，
悉殺其老弱。

 rm#r04214@仙芝 性貪，
掠得瑟瑟十餘斛，
黄金五六橐駝，
其餘口馬雜貨稱是，
皆入其家。

# p 

 rm#r02248@楊國忠 徳 rm#xjts10937@鮮于仲通 ，
薦爲 dm#dm00785@劍南 節度使。

 rm#xjts10937@仲通 性褊急，
失蠻夷心。

# p 

故事，
 dm#dm01049@南詔 常與妻子倶謁都督，
過 dm#dm08554@雲南 ，
 dm#dm08554@雲南 太守 rm#r05296@張虔陀 皆私之。

又多所徵求，
 rm#xjts26851@南詔王閤羅鳳 不應，
 rm#r05296@虔陀 遣人詈辱之，
仍密奏其罪。

 rm#xjts26851@閤羅鳳 忿怨，
是歳，
發兵反，
攻陷 dm#dm08554@雲南 ，
殺 rm#r05296@虔陀 ，
取夷州三十二。

*** 十載
# year 0751
# p 

春，
正月，
壬辰，
上朝獻 dm#dm01814@太清宮 ；
癸巳，
朝享太廟；
甲子，
合祭天地於南郊，
赦天下，
免天下 y@今載 地税。

# p 

丁酉，
命 rm#r01824@李林甫 遙領 dm#dm03677@朔方 節度使，
以戸部侍郎 rm#r01821@李暐 知留後事。
# p 

庚子，
 rm#no@楊氏 五宅夜遊，
與 rm#xjts01016@廣平公主 從者爭 dm#dm07320@西市門 ，
 rm#no@楊氏 奴揮鞭及公主衣，
公主墜馬，
駙馬程昌裔下扶之，
亦被數鞭。

公主泣訴於上，
上爲之杖殺 rm#no@楊氏 奴。

明日，
免 rm#r00272@昌裔 官，
不聽朝謁。
# p 

上命有司爲 rm#r00793@安祿山 治第於 dm#dm07407@親仁坊 ，
敕令但窮壯麗，
不限財力。

既成，
具幄帟器皿，
充牣其中，
有帖白檀牀二，
皆長丈，
闊六尺；
銀平脱屏風，
帳方丈六尺；
於廚廐之物皆飾以金銀，
金飯罌二，
銀淘盆二，
皆受五斗，
織銀絲筐及笊籬各一；
他物稱是。

雖禁中服御之物，
殆不及也。

上毎令中使爲 rm#r00793@祿山 護役，
築第及造儲偫賜物，
常戒之曰：
「胡眼大，
勿令笑我。」

方丈六一方一丈八方丈八
# p 

 rm#r00793@祿山 入新第，
置酒，
乞降墨敕請宰相至第。

是日，
上欲於樓下撃毬，
遽爲罷戲，
命宰相赴之。

日遣諸楊與之選勝遊宴，
侑以 dm#dm04062@梨園 教坊樂。

上毎食一物稍美，
或後苑校獵獲鮮禽，
輒遣中使走馬賜之，
絡繹於路。
# p 

甲辰，
 rm#r00793@祿山 生日，
上及 rm#r02136@貴𡚱 賜衣服、寶器、酒饌甚厚。

後三日，
召 rm#r00793@祿山 入禁中，
 rm#r02136@貴𡚱 以錦繡爲大襁褓，
裹 rm#r00793@祿山 ，
使宮人以綵輿舁之。

上聞後宮歡笑，
問其故，
左右以 rm#r02136@貴𡚱 三日洗 rm#?@祿兒 對。

上自往觀之，
喜，
賜 rm#r02136@貴𡚱 洗兒金銀錢，
復厚賜祿山，
盡歡而罷。

自是 rm#r00793@祿山 出入宮掖不禁，
或與 rm#r02136@貴𡚱 對食，
或通宵不出，
頗有醜聲聞於外，
上亦不疑也。

# p 

 dm#dm02061@安西 節度使 rm#r04214@高仙芝 入朝，
獻所擒突騎 rm#?@施可汗 、吐蕃酋長、 rm#?@石國王 、 rm#?@朅師王 。

加 rm#r04214@仙芝 開府儀同三司。

尋以 rm#r04214@仙芝 爲 dm#dm04695@河西 節度使，
代 rm#r06178@安思順 ；
 rm#r06178@思順 諷羣胡割耳剺面請留己，
制復留 rm#r06178@思順 於 dm#dm04695@河西 。

# p 

 rm#r00793@安祿山 求兼 dm#dm04672@河東 節度。

二月，
丙辰，
以 dm#dm04672@河東 節度使 rm#r06063@韓休珉 爲左羽林將軍，
以 rm#r00793@祿山 代之。
# p 

戸部郎中 rm#r00396@吉温 見 rm#r00793@祿山 有寵，
又附之，
約爲兄弟。

説 rm#r00793@祿山 曰：
「 rm#r01824@李右丞相 雖以時事親三兄，
不必肯以兄爲相；
温雖蒙驅使，
終不得超擢。

兄若薦 rm#r00396@温 於上，
 rm#r00396@温 即奏兄堪大任，
共排 rm#r01824@林甫 出之，
爲相必矣。」

 rm#r00793@祿山 悦其言，
數稱 rm#r00396@温 才於上，
上亦忘曩日之言。

會 rm#r00793@祿山 領 dm#dm04672@河東 ，
因奏温爲節度副使、知留後，
以大理司直 rm#r06191@張通儒 爲留後判官，
 dm#dm04672@河東 事悉以委之。
# p 

是時，
 rm#r02248@楊國忠 爲御史中丞，
方承恩用事。

 rm#r00793@祿山 登降殿階，
 rm#r02248@國忠 常扶掖之。

 rm#r00793@祿山 與 rm#r02724@王鉷 倶爲大夫，
 rm#r02724@鉷 權任亞於 rm#r01824@李林甫 。

 rm#r00793@祿山 見 rm#r01824@林甫 ，
禮貌頗倨。

 rm#r01824@林甫 陽以他事召 rm#r05611@王大夫 ，
 rm#r02724@鉷 至，
趨拜甚謹；
 rm#r00793@祿山 不覺自失，
容貌益恭。

 rm#r01824@林甫 與 rm#r00793@祿山 語，
毎揣知其情，
先言之，
 rm#r00793@祿山 驚服。

 rm#r00793@祿山 於公卿皆慢侮之，
獨憚 rm#r01824@林甫 ，
毎見，
雖盛冬，
常汗沾衣。

 rm#r01824@林甫 乃引與坐於中書廳，
撫以温言，
自解披袍以覆之。

 rm#r00793@祿山 忻荷，
言無不盡，
謂 rm#r01824@林甫 爲 rm#r01824@十郎 。

既歸 dm#dm06863@范陽 ，
 rm#xjts25876@劉駱谷 毎自 dm#dm08170@長安 來，
必問：
「 rm#r01824@十郎 何言？」
得美言則喜；
或但云「語 rm#r00793@安大夫 ，
須好檢校！」

輒反手據牀曰：
「噫嘻，
我死矣！」

# p 

 rm#r00793@祿山 既兼領三鎭，
賞刑己出，
日益驕恣。

自以曩時不拜太子，
見上春秋高，
頗内懼；
又見武備墮弛，
有輕 dm#dm00255@中國 之心。

孔目官 rm#r06165@嚴莊 、掌書記 rm#r04212@高尚 因爲之解圖讖，
勸之作亂。

# p 

 rm#r00793@祿山 養同羅、奚、契丹降者八千餘人，
謂之「曳落河」。

曳落河者，
胡言壯士也。

及家僮百餘人，
皆驍勇善戰，
一可當百。

又畜戰馬數萬匹，
多聚兵仗，
分遣商胡詣諸道販鬻，
歳輸珍貨數百萬。

私作緋紫袍、魚袋，
以百萬計。

以 rm#r04212@高尚 、 rm#r06165@嚴莊 、 rm#r06191@張通儒 及將軍 rm#r00716@孫孝哲 爲腹心，
 rm#r00380@史思明 、 rm#r06177@安守忠 、 rm#r06214@李歸仁 、 rm#r06243@蔡希徳 、 rm#r05584@牛廷玠 、 rm#?@向潤容 、 rm#r06208@李庭望 、 rm#r06181@崔乾祐 、 rm#r06180@尹子奇 、 rm#r06153@何千年 、 rm#r06223@武令珣 、 rm#?@能元皓 、 rm#r02821@田承嗣 、 rm#r06237@田乾眞 、 rm#r06270@阿史那承慶 爲爪牙。

 rm#r04212@尚 ，
雍奴人，
本名 rm#r04212@不危 ，
頗有辭學，
薄遊 dm#dm04671@河朔 ，
貧困不得志，
常歎曰：
「 rm#r04212@高不危 當舉大事而死，
豈能齧草根求活邪！

」
 rm#r00793@祿山 引置幕府，
出入臥内。

 rm#r04212@尚 典牋奏，
 rm#r06165@莊 治簿書。

 rm#r06191@通儒 ，
 rm#r05295@萬歳 之子；
 rm#r00716@孝哲 ，
契丹也。

 rm#r02821@承嗣 世爲 dm#dm06013@盧龍 小校，
 rm#r00793@祿山 以爲前鋒兵馬使。

嘗大雪，
 rm#r00793@祿山 按行諸營，
至承嗣營，
寂若無人，
入閲士卒，
無一人不在者，
 rm#r00793@祿山 以是重之。治軍嚴整
# p 

夏，
四月，
壬午，
 dm#dm00785@劍南 節度使 rm#xjts10937@鮮于仲通 討南詔蠻，
大敗於 dm#dm05468@瀘南 。

時 rm#xjts10937@仲通 將兵八萬分二道出戎、 dm#dm02524@嶲州 ，
至 dm#dm03609@曲州 、 dm#dm08694@靖州 。

 rm#xjts26851@南詔王閤羅鳳 謝罪，
請還所俘掠，
城 dm#dm08554@雲南 而去，
且曰：
「今吐蕃大兵壓境，
若不許我，
我將歸命吐蕃，
 dm#dm08554@雲南 非 dyn#ch100@唐 有也。

」
 rm#xjts10937@仲通 不許，
囚其使。

進軍至 dm#dm07351@西洱河 ，
與 rm#xjts26851@閤羅鳳 戰，
軍大敗，
士卒死者六萬人，
 rm#xjts10937@仲通 僅以身免。

 rm#r02248@楊國忠 掩其敗状，
仍敍其戰功。

 rm#xjts26851@閤羅鳳 斂戰尸，
築爲京觀，
遂北臣於吐蕃。

蠻語謂弟爲「鍾」，
吐蕃命 rm#xjts26851@閤羅鳳 爲「贊普鍾」，
號曰 rm#xjts26851@東帝 ，
給以金印。

 rm#xjts26851@閤羅鳳 刻碑於國門，
言己不得已而叛 dyn#ch100@唐 ，
且曰：
「我世世事 dyn#ch100@唐 ，
受其封爵，
後世容復歸唐，
當指碑以示 dyn#ch100@唐 使者，
知吾之叛非本心也。」

遣使
# p 

制大募 dm#dm00683@兩京 及 dm#dm04660@河南 、 dm#dm00829@北 兵以撃 dm#dm01049@南詔 ；
人聞 dm#dm08554@雲南 多瘴癘，
未戰士卒死者什八九，
莫肯應募。

 rm#r02248@楊國忠 遣御史分道捕人，
連枷送詣軍所。

舊制，
百姓有勳者免征役，
時調兵既多，
 rm#r02248@國忠 奏先取高勳。

於是行者愁怨，
父母妻子送之，
所在哭聲振野。
# p 

 rm#r04214@高仙芝 之虜 rm#?@石國王 也，
 dm#dm06074@石國 王子逃詣諸胡，
具告 rm#r04214@仙芝 欺誘貪暴之状。

諸胡皆怒，
潛引大食欲共攻四鎭。

 rm#r04214@仙芝 聞之，
將蕃、 dyn#ch129@漢 三萬衆撃大食，
深入七百餘里，
至 dm#dm03026@恆羅斯城 ，
與大食遇。

相持五日，
葛羅祿部衆叛，
與大食夾攻 dyn#ch100@唐 軍，
 rm#r04214@仙芝 大敗，
士卒死亡略盡，
所餘纔數千人。

右威衞將軍 rm#r01663@李嗣業 勸仙芝宵遁，
道路阻隘，
拔汗那部衆在前，
人畜塞路；
 rm#r01663@嗣業 前驅，
奮大梃撃之，
人馬倶斃，
 rm#r04214@仙芝 乃得過。
# p 

將士相失，
別將 dm#dm00073@汧陽  rm#r02349@段秀實 聞 rm#r01663@嗣業 之聲，
詬曰：
「避敵先奔，
無勇也；
全己棄衆，
不仁也。

幸而得達，
獨無愧乎！」

 rm#r01663@嗣業 執其手謝之，
留拒追兵，
收散卒，
得倶免。

還至 dm#dm02061@安西 ，
言於 rm#r04214@仙芝 ，
以 rm#r02349@秀實 兼都知兵馬使，
爲己判官。
# p 

八月，
丙辰，
武庫火，
燒兵器三十七萬。

# p 

 rm#r00793@安祿山 將三道兵六萬以討契丹，
以奚騎二千爲郷導。

過 dm#dm02660@平盧 千餘里，
至 dm#dm01464@土護眞水 ，
遇雨。

 rm#r00793@祿山 引兵晝夜兼行三百餘里，
至契丹牙帳，
契丹大駭。

時久雨，
弓弩筋膠皆弛，
大將 rm#r05024@何思徳 言於 rm#r00793@祿山 曰：
「吾兵雖多，
遠來疲弊，
實不可用，
不如按甲息兵以臨之，
不過三日，
虜必降。」

 rm#r00793@祿山 怒，
欲斬之，
 rm#r05024@思徳 請前驅效死。

 rm#r05024@思徳 貌類 rm#r00793@祿山 ，
虜爭撃，
殺之，
以爲已得 rm#r00793@祿山 ，
勇氣増倍。

奚復叛，
與契丹合，
夾撃 dyn#ch100@唐 兵，
殺傷殆盡。

射 rm#r00793@祿山 ，
中鞍，
折冠簪，
失履，
獨與麾下二十騎走；
會夜，
追騎解，
得入 dm#dm02593@師州 。

歸罪於 rm#xjts03759@左賢王哥解 、 dm#dm04672@河東 兵馬使 rm#r06128@魚承仙 而斬之。
# p 

 dm#dm02660@平盧 兵馬使 rm#r00380@史思明 懼，
逃入山谷近二旬，
收散卒，
得七百人。

 dm#dm02660@平盧 守將 rm#r05095@史定方 將精兵二千救 rm#r00793@祿山 ，
契丹引去，
 rm#r00793@祿山 乃得免。

至 dm#dm02660@平盧 ，
麾下皆亡，
不知所出。

 rm#r00380@史思明 出見 rm#r00793@祿山 ，
 rm#r00793@祿山 喜，
起，
執其手曰：
「吾得汝，
復何憂！」

 rm#r00380@思明 退，
謂人曰：
「曏使早出，
已與 rm#?@哥解 幷斬矣。」

契丹圍 dm#dm02593@師州 ，
 rm#r00793@祿山 使 rm#r00380@思明 撃卻之。
# p 

冬，
十月，
壬子，
上幸 dm#dm06942@華清宮 。
# p 

 rm#r02248@楊國忠 使 rm@鮮于仲通 表請己遙領 dm#dm00785@劍南 ；
十一月，
丙午，
以 rm#r02248@國忠 領 dm#dm00785@劍南 節度使。
*** 十一載
# year 0752
# p 

春，
正月，
丁亥，
上還宮。
# p 

二月，
庚午，
命有司出粟帛及庫錢數十萬緡於兩市易惡錢。

先是，
 dm#dm04475@江 、 dm#dm04981@淮 多惡錢，
貴戚大商往往以良錢一易惡錢五，
載入 dm#dm08170@長安 ，
市井不勝其弊，
故 rm#r01824@李林甫 奏請禁之，
官爲易取，
期一月，
不輸官者罪之。

於是商賈囂然，
不以爲便。

衆共遮 rm#r02248@楊國忠 馬自言，
國忠爲之言於上，
乃更命非鉛錫所鑄及穿穴者，
皆聽用之如故。

# p 

三月，
 rm#r00793@安祿山 發蕃、漢歩騎二十萬撃契丹，
欲以雪去秋之恥。

初，
突厥 rm#?@阿布思 來降，
上厚禮之，
賜姓名 rm#r05416@李獻忠 ，
累遷 dm#dm03677@朔方 節度副使，
賜爵 rm#r05416@奉信王 。

 rm#r05416@獻忠 有才略，
不爲 rm#r00793@安祿山 下，
 rm#r00793@祿山 恨之；
至是，
奏請 rm#r05416@獻忠 帥同羅數萬騎，
與倶撃契丹。

 rm#r05416@獻忠 恐爲 rm#r00793@祿山 所害，
白留後 rm#r01186@張暐 ，
請奏留不行，
 rm#r01186@暐 不許。

 rm#r05416@獻忠 乃帥所部大掠倉庫，
叛歸漠北，
 rm#r00793@祿山 遂頓兵不進。
# p 

乙巳，
改吏部爲文部，
兵部爲武部，
刑部爲憲部。
# p 

戸部侍郎、御史大夫、 dm#dm00427@京兆 尹 rm#r02724@王鉷 ，
權寵日盛，
領二十餘使。

宅旁爲使院，
文案盈積，
吏求署一字，
累日不得前；
中使賜賚不絶於門，
雖 rm#r01824@李林甫 亦畏避之。

 rm#r01824@林甫 子 rm#?@岫 爲將作監，
 rm#r02724@鉷 子 rm#?@準 爲衞尉少卿，
倶供奉禁中。

 rm#?@準 陵侮 rm#?@岫 ，
 rm#?@岫 常下之。

然 rm#r02724@鉷 事 rm#r01824@林甫 謹，
 rm#r01824@林甫 雖忌其寵，
不忍害也。
# p 

 rm#?@準 嘗帥其徒過駙馬都尉 rm#r05654@王繇 ，
 rm#r05654@繇 望塵拜伏；
 rm#?@準 挾彈命中於 rm#r05654@繇 冠，
折其玉簪，
以爲戲笑。

既而 rm#r05654@繇 延 rm#?@準 置酒；
 rm#r05654@繇 所尚 rm#r02389@永穆公主 ，
上之愛女也，
爲 rm#?@準 親執刀匕。

 rm#?@準 去，
或謂 rm#r05654@繇 曰：
「鼠雖挾其父勢，
君乃使公主爲之具食，
有如上聞，
無乃非宜？」
 rm#r05654@繇 曰：
「上雖怒無害，
至於 rm#r02724@七郎 ，
死生所繋，
不敢不爾。」

# p 

 rm#r02724@鉷 弟戸部郎中 rm#?@銲 ，
凶險不法，
召術士 rm#r05019@任海川 問「我有王者之相否？」
 rm#r05019@海川 懼，
亡匿。

 rm#r02724@鉷 恐事泄，
捕得，
託以他事杖殺之。

王府司馬 rm#?@韋會 ，
 rm#r00830@定安公主 之子，
 rm#r05654@王繇 之同産也，
話之私庭。

 rm#r02724@鉷 使 dm#dm08170@長安 尉 rm#r05884@賈季鄰 收 rm#?@會 繋獄，
縊殺之。

 rm#r05654@繇 不敢言。
# p 

 rm#?@銲 所善 rm#r05924@邢縡 ，
與龍武萬騎謀殺龍武將軍，
以其兵作亂，
殺 rm#r01824@李林甫 、 rm#r03924@陳希烈 、 rm#r02248@楊國忠 ；
前期二日，
有告之者。

夏，
四月，
乙酉，
上臨朝，
以告状面授 rm#r02724@鉷 ，
使捕之。

 rm#r02724@鉷 意 rm#?@銲 在 rm#r05924@縡 所，
先使人召之，
日晏，
乃命 rm#r05884@賈季鄰 等捕 rm#r05924@縡 。

 rm#r05924@縡 居 dm#dm08012@金城坊 ，
 rm#r05884@季鄰 等至門，
 rm#r05924@縡 帥其黨數十人持弓刀格鬬突出。

 rm#r02724@鉷 與 rm#r02248@楊國忠 引兵繼至，
 rm#r05924@縡 黨曰：
「勿傷大夫人。」

 rm#r02248@國忠 之傔密謂 rm#r02248@國忠 曰：
「賊有號，
不可戰也。」

 rm#r05924@縡 鬬且走，
至皇城西南隅。

會 rm#r04220@高力士 引飛龍禁軍四百至，
撃斬 rm#r05924@縡 ，
捕其黨，
皆擒之。


# p 

 rm#r02248@國忠 以状白上，
曰：
「 rm#r02724@鉷 必預謀。」

上以 rm#r02724@鉷 任遇深，
不應同逆；
 rm#r01824@李林甫 亦爲之辯解。

上乃特命原 rm#xjts03151@銲 不問，
然意欲 rm#r02724@鉷 表請罪之；
使 rm#r02248@國忠 諷之，
 rm#r02724@鉷 不忍，
上怒。

會 rm#r03924@陳希烈 極言 rm#r02724@鉷 大逆當誅，
戊子，
敕 rm#r03924@希烈 與 rm#r02248@國忠 鞫之，
仍以 rm#r02248@國忠 兼 dm#dm00427@京兆 尹。

於是 rm#r05019@任海川 、 rm#xjts19183@韋會 等事皆發，
獄具，
 rm#r02724@鉷 賜自盡，
 rm#xjts03151@銲 杖死於朝堂，
 rm#r02724@鉷 子 rm#xjts02421@準 、 rm#xjts02113@偁 流 dm#dm02527@嶺南 ，
尋殺之。

有司籍其第舍，
數日不能徧。

 rm#r02724@鉷 賓佐莫敢窺其門，
獨采訪判官 rm#r03411@裴冕 收其尸葬之。

# p 

初，
 rm#r01824@李林甫 以 rm#r03924@陳希烈 易制，
引爲相，
政事常隨 rm#r01824@林甫 左右，
晩節遂與 rm#r01824@林甫 爲敵，
 rm#r01824@林甫 懼。

會 rm#r05416@李獻忠 叛，
 rm#r01824@林甫 乃請解 dm#dm03677@朔方 節制，
且薦 dm#dm04695@河西 節度使 rm#r06178@安思順 自代；
庚子，
以 rm#r06178@思順 爲 dm#dm03677@朔方 節度使。

# p 

五月，
戊申，
 rm#r03513@慶王琮 薨，
贈 rm#r03513@靖徳太子 。

# p 

丙辰，
 dm#dm00427@京兆 尹 rm#r02248@楊國忠 加御史大夫、 dm#dm00444@京畿 ‧ dm#dm08283@關内 采訪等使，
凡 rm#r02724@王鉷 所綰使務，
悉歸 rm#r02248@國忠 。

# p 

初，
 rm#r01824@李林甫 以 rm#r02248@國忠 微才，
且貴𡚱之族，
故善遇之。

 rm#r02248@國忠 與 rm#r02724@王鉷 倶爲中丞，
 rm#r02724@鉷 用 rm#r01824@林甫 薦爲大夫，
故 rm#r02248@國忠 不悦，
遂深探 rm#r05924@邢縡 獄，
令引 rm#r01824@林甫 交私 rm#r02724@鉷 兄弟及 rm#?@阿布思 事状，
 rm#r03924@陳希烈 、 rm#r00487@哥舒翰 從而證之；
上由是疏 rm#r01824@林甫 。

 rm#r02248@國忠 貴震天下，
始與 rm#r01824@林甫 爲仇敵矣。
# p 

六月，
甲子，
 rm#r02248@楊國忠 奏吐蕃兵六十萬救南詔，
 dm#dm00785@劍南 兵撃破之於 dm#dm08554@雲南 ，
克故 dm#dm08454@隰州 等三城，
捕虜六千三百，
以道遠，
簡壯者千餘人及酋長降者獻之。


# p 

秋，
八月，
乙丑，
上復幸左藏，
賜羣臣帛。

癸巳，
 rm#r02248@楊國忠 奏有鳳皇見左藏庫屋，
出納判官 rm#r04287@魏仲犀 言鳳集庫西 dm#dm07701@通訓門 。
乙己
# p 

九月，
 rm#?@阿布思 入寇，
圍 dm#dm04434@永清柵 ，
柵使 rm#r05252@張元軌 拒卻之。

# p 

冬，
十月，
戊寅，
上幸 dm#dm06942@華清宮 。
# p 

己亥，
改 dm#dm07701@通訓門 曰 dm#dm09010@鳳集門 ；
 rm#r04287@魏仲犀 遷殿中侍御史，
 rm#r02248@楊國忠 屬吏率以鳳皇優得調。

# p 

南詔數寇邊，
 dm#dm07197@蜀 人請 rm#r02248@楊國忠 赴鎭；
左僕射兼右相 rm#r01824@李林甫 奏遣之。

 rm#r02248@國忠 將行，
泣辭，
上言必爲 rm#r01824@林甫 所害，
貴𡚱亦爲之請。

上謂 rm#r02248@國忠 曰：
「卿蹔到 dm#dm07197@蜀 區處軍事，
朕屈指待卿，
還當入相。」

 rm#r01824@林甫 時已有疾，
憂懣不知所爲，
巫言一見上可小愈；
上欲就視之，
左右固諫。

上乃令 rm#r01824@林甫 出庭中，
上登 dm#dm08308@降聖閣 遙望，
以紅巾招之。

 rm#r01824@林甫 不能拜，
使人代拜。

 rm#r02248@國忠 比至 dm#dm07197@蜀 ，
上遣中使召還，
至 dm#dm03519@昭應 ，
謁 rm#r01824@林甫 ，
拜於牀下。

 rm#r01824@林甫 流涕謂曰：
「 rm#r01824@林甫 死矣，
公必爲相，
以後事累公！」

 rm#r02248@國忠 謝不敢當，
汗出覆面。

十一月，
丁卯，
 rm#r01824@林甫 薨。
# p 

上晩年自恃承平，
以爲天下無復可憂，
遂深居禁中，
專以聲色自娯，
悉委政事於 rm#r01824@林甫 。

 rm#r01824@林甫 媚事左右，
迎合上意，
以固其寵；
杜絶言路，
掩蔽聰明，
以成其姦；
妬賢疾能，
排抑勝己，
以保其位；
屡起大獄，
誅逐貴臣，
以張其勢。

自皇太子以下，
畏之側足。

凡在相位十九年，
養成天下之亂，
而上不之寤也。
# p 

庚申，
以 rm#r02248@楊國忠 爲右相，
兼文部尚書，
其判使竝如故。

# p 

 rm#r02248@國忠 爲人強辯而輕躁，
無威儀。

既爲相，
以天下爲己任，
裁決機務，
果敢不疑；
居朝廷，
攘袂扼腕，
公卿以下，
頤指氣使，
莫不震慴。

自侍御史至爲相，
凡領四十餘使。

臺省官有才行時名，
不爲己用者，
皆出之。
# p 

或勸 dm#dm08329@陝郡 進士 rm#r05270@張彖 謁 rm#r02248@國忠 ，
曰：
「見之，
富貴立可圖。」

 rm#r05270@彖 曰：
「君輩倚 rm#r05488@楊右相 如 dm#dm04750@泰山 ，
吾以爲冰山耳！

若皎日既出，
君輩得無失所恃乎！」

遂隱居 dm#dm02514@嵩山 。
# p 

 rm#r02248@國忠 以司勳員外郎 rm#r00908@崔圓 爲 dm#dm00785@劍南 留後，
徵 dm#dm08957@魏郡 太守 rm#r00396@吉温 爲御史中丞，
充 dm#dm00444@京畿 、 dm#dm08283@關内 採訪等使。

 rm#r00396@温 詣 dm#dm06863@范陽 辭 rm#r00793@安祿山 ，
 rm#r00793@祿山 令其子 rm#r00789@慶緒 送至境，
爲 rm#r00396@温 控馬出驛數十歩。

 rm#r00396@温 至 dm#dm08170@長安 ，
凡朝廷動靜，
輒報 rm#r00793@祿山 ，
信宿而達。
# p 

十二月，
 rm#r02248@楊國忠 欲收人望，
建議：
「文部選人，
無問賢不肖，
選深者留之，
依資據闕注官。」

滯淹者翕然稱之。

 rm#r02248@國忠 凡所施置，
皆曲徇人所欲，
故頗得衆譽。
# p 

甲申，
以 dm#dm02660@平盧 兵馬使 rm#r00380@史思明 兼 dm#dm00855@北平 太守，
充 dm#dm06013@盧龍 軍使。

# p 

丁亥，
上還宮。

# p 

丁酉，
以 dm#dm02061@安西 行軍司馬 rm#r00852@封常清 爲 dm#dm02061@安西 四鎭節度使。

# p 

 rm#r00487@哥舒翰 素與 rm#r00793@安祿山 、 rm#r06178@安思順 不協，
上常和解之，
使爲兄弟。

是冬，
三人倶入朝，
上使 rm#r04220@高力士 宴之於城東。

 rm#r00793@祿山 謂 rm#r00487@翰 曰：
「我父胡，
母突厥，
公父突厥，
母胡，
族類頗同，
何得不相親？」
 rm#r00487@翰 曰：
「古人云，
狐向窟嘷不祥，
爲其忘本故也。

兄苟見親，
 rm#r00487@翰 敢不盡心！」

 rm#r00793@祿山 以爲譏其胡也，
大怒，
罵 rm#r00487@翰 曰：
「突厥敢爾！」

 rm#r00487@翰 欲應之，
 rm#r04220@力士 目 rm#r00487@翰 ，
 rm#r00487@翰 乃止，
陽醉而散，
自是爲怨愈深。
# p 

 rm#r02134@棣王琰 有二孺人，
爭寵，
其一使巫書符置 rm#r02134@琰 履中以求媚。

 rm#r02134@琰 與監院宦者有隙，
宦者知之，
密奏 rm#r02134@琰 祝詛上；
上使人掩其履而獲之，
大怒。

 rm#r02134@琰 頓首謝：
「臣實不知有符。」

上使鞫之，
果孺人所爲。

上猶疑 rm#r02134@琰 知之，
囚於鷹狗坊，
絶朝請，
憂憤而薨。
# p 

故事，
兵、吏部尚書知政事者，
選事悉委侍郎以下，
三注三唱，
仍過門下省審，
自春及夏，
其事乃畢。

及 rm#r02248@楊國忠 以宰相領文部尚書，
欲自示精敏，
乃遣令史先於私第密定名闕。
*** 十二載
# year 0753
# p 

春，
正月，
壬戌，
 rm#r02248@國忠 召左相 rm#r03924@陳希烈 及給事中、諸司長官皆集尚書都堂，
唱注選人，
一日而畢，
曰：
「今左相、給事中倶在座，
已過門下矣。」

其間資格差繆甚衆，
無敢言者。

於是門下不復過官，
侍郎但掌試判而已；
侍郎 rm#r04073@韋見素 、 rm#r01105@張倚 趨走門庭，
與主事無異。

 rm#r04073@見素 ，
 rm#r04048@湊 之子也。

# p 

 dm#dm00427@京兆 尹 rm@鮮于仲通 諷選人請爲 rm#r02248@國忠 刻頌，
立於省門，
制 rm#xjts10937@仲通 撰其辭；
上爲改定數字，
 rm#xjts10937@仲通 以金填之。
# p 

 rm#r02248@楊國忠 使人説 rm#r00793@安祿山 誣 rm#r01824@李林甫 與 rm#?@阿布思 謀反，
 rm#r00793@祿山 使 rm#?@阿布思 部落降者詣闕，
誣告 rm#r01824@林甫 與 rm#?@阿布思 約爲父子。

上信之，
下吏按問；
 rm#r01824@林甫 壻諫議大夫 rm#r02251@楊齊宣 懼爲所累，
附 rm#r02248@國忠 意證成之。

時 rm#r01824@林甫 尚未葬，
二月，
癸未，
制削 rm#r01824@林甫 官爵；
子孫有官者除名，
流嶺南及 dm#dm09182@黔中 ，
給隨身衣及糧食，
自餘貲産竝沒官；
近親及黨與坐貶者五十餘人。

剖 rm#r01824@林甫 棺，
抉取含珠，
褫金紫，
更以小棺如庶人禮葬之。

己亥，
賜 rm#r03924@陳希烈 爵 rm#r03924@許國公 ，
 rm#r02248@楊國忠 爵 rm#r02248@魏國公 ，
賞其成 rm#r01824@林甫 之獄也。
# p 

夏，
五月，
己酉，
復以 dyn#ch169@魏 、 dyn#ch173@周 、 dyn#ch174@隋 後爲三恪，
 rm#r02248@楊國忠 欲攻 rm#r01824@李林甫 之短也。

 rm#r05000@衞包 以助邪貶 dm#dm01562@夜郎 尉，
 rm#r05219@崔昌 貶 dm#dm05551@烏雷 尉。

# p 

 rm#?@阿布思 爲囘紇所破，
 rm#r00793@安祿山 誘其部落而降之，
由是 rm#r00793@祿山 精兵，
天下莫及。
# p 

壬辰，
以左武衞大將軍 rm#r05023@何復光 將 dm#dm02527@嶺南 五府兵撃南詔。
# p 

 rm#r00793@安祿山 以 rm#r01824@李林甫 狡猾踰己，
故畏服之。

及 rm#r02248@楊國忠 爲相，
 rm#r00793@祿山 視之蔑如也，
由是有隙。

 rm#r02248@國忠 屡言 rm#r00793@祿山 有反状；
上不聽。
# p 

 dm#dm08458@隴右 節度使 rm#r00487@哥舒翰 撃吐蕃，
拔 dm#dm04813@洪濟 、 dm#dm01655@大漠門 等城，
悉收九曲部落。

# p 

初，
 dm#dm08934@高麗 人 rm#r02633@王思禮 與 rm#r00487@翰 倶爲押牙，
事 rm#r02632@王忠嗣 。

 rm#r00487@翰 爲節度使，
 rm#r02633@思禮 爲兵馬使兼 dm#dm04691@河源軍 使。

 rm#r00487@翰 撃九曲，
 rm#r02633@思禮 後期；
 rm#r00487@翰 將斬之，
既而復召釋之。

 rm#r02633@思禮 徐曰：
「斬則遂斬，
復召何爲！」


# p 

 rm#r02248@楊國忠 欲厚結 rm#r00487@翰 共排 rm#r00793@安祿山 ，
奏以 rm#r00487@翰 兼 dm#dm04695@河西 節度使。

秋，
八月，
戊戌，
賜 rm#r00487@翰 爵 rm#r00487@西平郡王 。

 rm#r00487@翰 表侍御史 rm#r03411@裴冕 爲 dm#dm04695@河西 行軍司馬。
# p 

是時 dm#dm00255@中國 盛強，
自 dm#dm02069@安遠門 西盡 dyn#ch100@唐 境萬二千里，
閭閻相望，
桑麻翳野，
天下稱富庶者無如 dm#dm08458@隴右 。

 rm#r00487@翰 毎遣使入奏，
常乘白橐駝，
日馳五百里。

# p 

九月，
甲辰，
以突騎施 rm#?@黒姓可汗登里伊羅蜜施 爲 rm#?@突騎施可汗 。
# p 

 dm#dm00860@北庭 都護 rm#r02989@程千里 追 rm#?@阿布思 至 dm#dm06182@磧西 ，
以書諭 rm#?@葛邏祿 ，
使相應。

 rm#?@阿布思 窮迫，
歸 rm#?@葛邏祿 ，
 rm#?@葛邏祿 葉護執之，
幷其妻子、麾下數千人送之。

甲寅，
加 rm#?@葛邏祿 葉護 rm#?@頓毘伽 開府儀同三司，
賜爵 rm#?@金山王 。
# p 

冬，
十月，
戊寅，
上幸 dm#dm06942@華清宮 。

# p 

 rm#r02248@楊國忠 與 rm#?@虢國夫人 居第相鄰，
晝夜往來，
無復期度，
或竝轡走馬入朝，
不施障幕，
道路爲之掩目。


# p 

三夫人將從車駕幸 dm#dm06942@華清宮 ，
會於 rm#r02248@國忠 第；
車馬僕從，
充溢數坊，
錦繡珠玉，
鮮華奪目。

 rm#r02248@國忠 謂客曰：
「吾本寒家，
一旦縁椒房至此，
未知税駕之所，
然念終不能致令名，
不若且極樂耳。」

 rm#no@楊氏 五家，
隊各爲一色衣以相別，
五家合隊，
粲若雲錦；
 rm#r02248@國忠 仍以 dm#dm00785@劍南 旌節引於其前。
# p 

 rm#r02248@國忠 子 rm#?@暄 舉明經，
學業荒陋，
不及格。

禮部侍郎 rm#r03675@達奚珣 畏 rm#r02248@國忠 權勢，
遣其子 dm#dm03519@昭應 尉 rm#?@撫 先白之。

 rm#?@撫 伺 rm#r02248@國忠 入朝上馬，
趨至馬下；
 rm#r02248@國忠 意其子必中選，
有喜色。

 rm#?@撫 曰：
「大人白相公，
郎君所試，
不中程式，
然亦未敢落也。」

 rm#r02248@國忠 怒曰：
「我子何患不富貴，
乃令鼠輩相賣！」

策馬不顧而去。

 rm#?@撫 惶遽，
書白其父曰：
「彼恃挾貴勢，
令人慘嗟，
安可復與論曲直！」

遂置暄上第。

及 rm#?@暄 爲戸部侍郎，
 rm#r03675@珣 始自禮部遷吏部，
 rm#?@暄 與所親言，
猶歎己之淹囘，
 rm#r03675@珣 之迅疾。
# p 

 rm#r02248@國忠 既居要地，
中外餉遺輻湊，
積縑至三千萬匹。
# p 

上在 dm#dm06942@華清宮 ，
欲夜出遊，
龍武大將軍 rm#r03929@陳玄禮 諫曰：
「宮外即曠野，
安可不備不虞！

陛下必欲夜遊，
請歸城闕。」

上爲之引還。

# p 

 y@是歳 ，
 dm#dm02061@安西 節度使 rm#r00852@封常清 撃大勃律至 dm#dm06926@菩薩勞城 ，
前鋒屡捷，
 rm#r00852@常清 乘勝逐之。

斥候府果毅 rm#r02349@段秀實 諫曰：
「虜兵羸而屡北，
誘我也；
請搜左右山林。」

 rm#r00852@常清 從之。

果獲伏兵，
遂大破之，
受降而還。
# p 

中書舍人 rm#r00810@宋昱 知選事，
前進士 dm#dm02734@廣平  rm#r00327@劉迺 以選法未善，
上書於 rm#r00810@昱 ，
以爲：
「 rm#rt0008@禹 、 rm#rt0057@稷 、 rm@皋陶 同居 rm#rt0007@舜 朝，
猶曰載采有九徳，
考績以九載。

近代主司，
察言於一幅之判，
觀行於一揖之間，
何古今遲速不侔之甚哉！

借使 rm#rt0104@周公 、 rm#r06150@孔子 今處銓廷，
考其辭華，
則不及 rm#?@徐 、 rm#?@庾 ，
觀其利口，
則不若 rm#?@嗇夫 ，
何暇論聖賢之事業乎！」

*** 十三載
# year 0754
# p 

春，
正月，
己亥，
 rm#r00793@安祿山 入朝。

是時 rm#r02248@楊國忠 言 rm#r00793@祿山 必反，
且曰：
「陛下試召之，
必不來。」

上使召之，
 rm#r00793@祿山 聞命即至。

庚子，
見上於 dm#dm06942@華清宮 ，
泣曰：
「臣本胡人，
陛下寵擢至此，
爲 rm#r02248@國忠 所疾，
臣死無日矣！」

上憐之，
賞賜巨萬，
由是益親信 rm#r00793@祿山 ，
 rm#r02248@國忠 之言不能入矣。

太子亦知 rm#r00793@祿山 必反，
言於上，
上不聽。


# p 

甲辰，
 dm#dm01814@太清宮 奏：
「學士 rm#r01875@李琪 見 rm#ry0032@玄元皇帝 乘紫雲，
告以國祚延昌。」

# p 

 dyn#ch100@唐 初，
詔敕皆中書、門下官有文者爲之。

 y@乾封 以後，
始召文士 rm#r00162@元萬頃 、 rm#r03156@范履冰 等草諸文辭，
常於北門候進止，
時人謂之「北門學士」。

 rm#r01656@中宗 之世，
 rm#r00023@上官昭容 專其事。

上即位，
始置翰林院，
密邇禁廷，
延文章之士，
下至僧、道，
書、畫、琴、棋、數術之工皆處之，
謂之「待詔」。

刑部尚書 rm#r01127@張均 及弟太常卿 rm#r01088@垍 皆翰林院供奉。

上欲加 rm#r00793@安祿山 同平章事，
已令 rm#r01088@張垍 草制。

 rm#r02248@楊國忠 諫曰：
「 rm#r00793@祿山 雖有軍功，
目不知書，
豈可爲宰相！

制書若下，
恐四夷輕 dyn#ch100@唐 。」

上乃止。

乙巳，
加 rm#r00793@祿山 左僕射，
賜一子三品、一子四品官。
# p 

丙午，
上還宮。

# p 

 rm#r00793@安祿山 求兼領閑廐、羣牧；
庚申，
以 rm#r00793@祿山 爲閑廐、 dm#dm08458@隴右 羣牧等使。

 rm#r00793@祿山 又求兼總監；
壬戌，
兼知總監事。

 rm#r00793@祿山 奏以御史中丞 rm#r00396@吉温 爲武部侍郎，
充閑廐副使，
 rm#r02248@楊國忠 由是惡 rm#r00396@温 。

 rm#r00793@祿山 密遣親信選健馬堪戰者數千匹，
別飼之。

# p 

二月，
壬申，
上朝獻 dm#dm01814@太清宮 ，
上 rm#ry0032@聖祖 尊號曰 rm#ry0032@大聖祖高上大道金闕玄元大皇太帝 。

癸酉，
享太廟，
上 rm#r04258@高祖 諡曰 rm#r04258@神堯大聖光孝皇帝 ，
 rm#r01602@太宗 諡曰 rm#r01602@文武大聖大廣孝皇帝 ，
 rm#r01837@高宗 諡曰 rm#r01837@天皇大聖大弘孝皇帝 ，
 rm#r01656@中宗 諡曰 rm#r01656@孝和大聖大昭孝皇帝 ，
 rm#r01797@睿宗 諡曰 rm#r01797@玄眞大聖大興孝皇帝 ，
以 dm#*dm05284@漢家 諸帝皆諡孝故也。

甲戌，
羣臣上尊號曰 rm#r02004@開元天地大寶聖文神武證道孝徳皇帝 。

赦天下。

# p 

丁丑，
 rm#r02248@楊國忠 進位司空；
甲申，
臨軒册命。
# p 

己丑，
 rm#r00793@安祿山 奏：
「臣所部將士討奚、契丹、九姓、同羅等，
勳效甚多，
乞不拘常格，
超資加賞，
仍好寫告身付臣軍授之。」

於是除將軍者五百餘人，
中郎將者二千餘人。

 rm#r00793@祿山 欲反，
故先以此收衆心也。
# p 

三月，
丁酉朔，
 rm#r00793@祿山 辭歸 dm#dm06863@范陽 。

上解御衣以賜之，
 rm#r00793@祿山 受之驚喜。

恐 rm#r02248@楊國忠 奏留之，
疾驅出 dm#dm08280@關 。

乘船沿 dm#dm04650@河 而下，
令船夫執繩板立於岸側，
十五里一更，
晝夜兼行，
日數百里，
過郡縣不下船。

自是有言 rm#r00793@祿山 反者，
上皆縛送，
由是人皆知其將反，
無敢言者。之
# p 

 rm#r00793@祿山 之發 dm#dm08170@長安 也，
上令 rm#r04220@高力士 餞之 dm#dm08196@長樂坡 ，
及還，
上問：
「 rm#r00793@祿山 慰意乎？」
對曰：
「觀其意怏怏，
必知欲命爲相而中止故也。」

上以告 rm#r02248@國忠 ，
曰：
「此議他人不知，
必 rm#r01088@張垍 兄弟告之也。」

上怒，
貶 rm#r01127@張均 爲 dm#dm02843@建安 太守，
 rm#r01088@垍 爲 dm#dm06011@盧溪 司馬，
 rm#r01088@垍 弟給事中 rm#xjts04841@埱 爲 dm#dm02178@宜春 司馬。

# p 

 rm#r00487@哥舒翰 亦爲其部將論功，
敕以 dm#dm08458@隴右 十將、特進、 dm#dm05507@火拔州 都督、 rm#?@燕山郡王火拔歸仁 爲驃騎大將軍，
 dm#dm04691@河源軍 使 rm#r02633@王思禮 加特進，
 dm#dm06688@臨洮 太守 rm#r05325@成如璆 、討撃副使 dm#dm06863@范陽  rm#r04315@魯炅 、 dm#dm05971@皋蘭府 都督 rm#r05568@渾惟明 竝加雲麾將軍，
 dm#dm08458@隴右 討撃副使 rm#r03737@郭英乂 爲左羽林將軍。

 rm#r03737@英乂 ，
 rm#r03732@知運 之子也。

 rm#r00487@翰 又奏 rm#r00568@嚴挺之 之子 rm#r00569@武 爲節度判官，
 dm#dm04672@河東  rm#r00441@呂諲 爲支度判官，
前 dm#dm02328@封丘 尉 rm#r04263@高適 爲掌書記，
 dm#dm02072@安邑  rm#r01490@曲環 爲別將。

# p 

 rm#r02989@程千里 執 rm#?@阿布思 ，
獻於闕下，
斬之。

甲子，
以 rm#r02989@千里 爲金吾大將軍，
以 rm#r00852@封常清 權 dm#dm00860@北庭 都護、 dm#dm00516@伊西 節度使。
# p 

夏，
四月，
癸巳，
 rm#r00793@安祿山 奏撃奚破之，
虜其王 rm#r06212@李日越 。
# p 

六月，
乙丑朔，
日有食之，
不盡如鉤。
# p 

侍御史、 dm#dm00785@劍南 留後 rm#r05370@李宓 將兵七萬撃南詔。

 rm@閤羅鳳 誘之深入，
至 dm#dm01586@大和城 ，
閉壁不戰。

 rm#r05370@宓 糧盡，
士卒罹瘴疫及飢死什七八，
乃引還，
蠻追撃之，
 rm#r05370@宓 被擒，
全軍皆沒。

 rm#r02248@楊國忠 隱其敗，
更以捷聞，
益發 dm#dm00255@中國 兵討之，
前後死者幾二十萬人；
無敢言者。

上嘗謂 rm#r04220@高力士 曰：
「朕今老矣，
朝事付之宰相，
邊事付之諸將，
夫復何憂！」

 rm#r04220@力士 對曰：
「臣聞 dm#dm08554@雲南 數喪師，
又邊將擁兵太盛，
陛下將何以制之！

臣恐一旦禍發，
不可復救，
何得謂無憂也！」

上曰：
「卿勿言，
朕徐思之。」

大太
# p 

秋，
七月，
癸丑，
 rm#r00487@哥舒翰 奏：
於所開 dm#dm00326@九曲 之地置 dm#dm04831@洮陽 、 dm#dm05394@澆河 二郡及 dm#dm06233@神策軍 ，
以 dm#dm06688@臨洮 太守 rm#r05325@成如璆 兼 dm#dm04831@洮陽 太守，
充 dm#dm06233@神策軍 使。

# p 

 rm#r02248@楊國忠 忌 rm#r03924@陳希烈 ，
 rm#r03924@希烈 累表辭位；
上欲以武部侍郎 rm#r00396@吉温 代之，
 rm#r02248@國忠 以温附 rm#r00793@安祿山 ，
奏言不可；
以文部侍郎 rm#r04073@韋見素 和雅易制，
薦之。

八月，
丙戌，
以 rm#r03924@希烈 爲太子太師，
罷政事；
以 rm#r04073@見素 爲武部尚書、同平章事。

# p 

自 y@去歳 水旱相繼，
 dm#dm08281@關中 大饑。

 rm#r02248@楊國忠 惡 dm#dm00427@京兆 尹 rm#r01713@李峴 不附己，
以災沴歸咎於 rm#r01713@峴 ，
九月，
貶 dm#dm08214@長沙 太守。

 rm#r01713@峴 ，
 rm#r00132@禕 之子也。

上憂雨傷稼，
 rm#r02248@國忠 取禾之善者獻之，
曰：
「雨雖多，
不害稼也。」

上以爲然。

 dm#dm03177@扶風 太守 rm#r01381@房琯 言所部水災，
 rm#r02248@國忠 使御史推之。

 y@是歳 ，
天下無敢言災者。

 rm#r04220@高力士 侍側，
上曰：
「淫雨不已，
卿可盡言。」

對曰：
「自陛下以權假宰相，
賞罰無章，
陰陽失度，
臣何敢言！」

上默然。
# p 

冬，
十月，
乙酉，
上幸 dm#dm06942@華清宮 。
# p 

十一月，
己未，
置内侍監二員，
正三品。

# p 

 dm#dm04672@河東 太守兼本道采訪使 rm#r04081@韋陟 ，
 rm#r04038@斌 之兄也，
文雅有盛名，
 rm#r02248@楊國忠 恐其入相，
使人告 rm#r04081@陟 贓汚事，
下御史按問。

 rm#r04081@陟 賂中丞 rm#r00396@吉温 ，
使求救於 rm#r00793@安祿山 ，
復爲 rm#r02248@國忠 所發。

閏月，
壬寅，
貶 dm#dm08331@陟桂嶺 尉，
 rm#r00396@温  dm#dm05408@澧陽 長史。

 rm#r00793@安祿山 爲温訟冤，
且言 rm#r02248@國忠 讒疾。

上兩無所問。
# p 

戊午，
上還宮。
# p 

 y@是歳 ，
戸部奏天下郡三百二十一，
縣千五百三十八，
郷萬六千八百二十九，
戸九百六萬九千一百五十四，
口五千二百八十八萬四百八十八。

*** 十四載
# year 0755
# p 

春，
正月，
蘇毘王子 rm#?@悉諾邏 去吐蕃來降。

# p 

二月，
辛亥，
 rm#r00793@安祿山 使副將 rm#r06153@何千年 入奏，
請以蕃將三十二人代 dyn#ch129@漢 將，
上命立進畫，
給告身。

 rm#r04073@韋見素 謂 rm#r02248@楊國忠 曰：
「 rm#r00793@祿山 久有異志，
今又有此請，
其反明矣。

明日 rm#r04073@見素 當極言；
上未允，
公其繼之。」

 rm#r02248@國忠 許諾。

壬子，
 rm#r02248@國忠 、 rm#r04073@見素 入見，
上迎謂曰：
「卿等有疑 rm#r00793@祿山 之意邪？」
 rm#r04073@見素 因極言 rm#r00793@祿山 反已有迹，
所請不可許，
上不悦；
 rm#r02248@國忠 逡巡不敢言，
上竟從 rm#r00793@祿山 之請。

他日，
 rm#r02248@國忠 、 rm#r04073@見素 言於上曰：
「臣有策可坐消 rm#r00793@祿山 之謀。

今若除 rm#r00793@祿山 平章事，
召詣闕，
以 rm#r03574@賈循 爲 dm#dm06863@范陽 節度使，
 rm#r05117@呂知誨 爲 dm#dm02660@平盧 節度使，
 rm#r06217@楊光翽 爲 dm#dm04672@河東 節度使，
則勢自分矣。」

上從之。

已草制，
上留不發，
更遣中使 rm#r05920@輔璆琳 以珍果賜 rm#r00793@祿山 ，
潛察其變。

 rm#r05920@璆琳 受 rm#r00793@祿山 厚賂，
還，
盛言 rm#r00793@祿山 竭忠奉國，
無有二心。

上謂 rm#r02248@國忠 等曰：
「 rm#r00793@祿山 ，
朕推心待之，
必無異志。

東北二虜，
藉其鎭遏。

朕自保之，
卿等勿憂也！」

事遂寢。

 rm#r03574@循 ，
 dm#dm06930@華原 人也，
時爲節度副使。
# p 

 dm#dm08458@隴右 、 dm#dm04695@河西 節度使 rm#r00487@哥舒翰 入朝，
道得風疾，
遂留 dm#dm08170@京師 ，
家居不出。
# p 

三月，
辛巳，
命給事中 rm#r03417@裴士淹 宣慰 dm#dm04656@河北 。

# p 

夏，
四月，
 rm#r00793@安祿山 奏破奚、契丹。

# p 

癸巳，
以蘇毘王子 rm#r05385@悉諾邏 爲 rm#r05385@懷義王 ，
賜姓名 rm#r05385@李忠信 。
# p 

 rm#r00793@安祿山 歸至 dm#dm06863@范陽 ，
朝廷毎遣使者至，
皆稱疾不出迎，
盛陳武備，
然後見之。

 rm#r03417@裴士淹 至 dm#dm06863@范陽 ，
二十餘日乃得見，
無復人臣禮。

 rm#r02248@楊國忠 日夜求 rm#r00793@祿山 反状，
使 dm#dm00427@京兆 尹圍其第，
捕 rm#r00793@祿山 客 rm#r01978@李超 等，
送御使臺獄，
潛殺之。

 rm#r00793@祿山 子 rm#?@慶宗 尚宗女 rm#?@榮義郡主 ，
供奉在 dm#dm08170@京師 ，
密報 rm#r00793@祿山 ，
 rm#r00793@祿山 愈懼。

六月，
上以其子成婚，
手詔 rm#r00793@祿山 觀禮，
 rm#r00793@祿山 辭疾不至。

秋，
七月，
 rm#r00793@祿山 表獻馬三千匹，
毎匹執控夫二人，
遣蕃將二十二人部送。

 dm#dm04660@河南 尹 rm#r03675@達奚珣 疑有變，
奏請「諭 rm#r00793@祿山 以進車馬宜俟至冬，
官自給夫，
無煩本軍。」

於是上稍寤，
始有疑 rm#r00793@祿山 之意。

會 rm#r05920@輔璆琳 受賂事亦泄，
上託以他事撲殺之。

上遣中使 rm#r06091@馮神威 齎手詔諭 rm#r00793@祿山 ，
如 rm#r03675@珣 策；
且曰：
「朕新爲卿作一湯，
十月於 dm#dm06942@華清宮 待卿。」

 rm#r06091@神威 至 dm#dm06863@范陽 宣旨，
 rm#r00793@祿山 踞牀微起，
亦不拜，
曰：
「聖人安隱。」

又曰：
「馬不獻亦可，
十月灼然詣 dm#dm08170@京師 。」

即令左右引 rm#r06091@神威 置館舍，
不復見；
數日，
遣還，
亦無表。

 rm#r06091@神威 還，
見上泣曰：
「臣幾不得見大家！

」

# p 

八月，
辛卯，
免 y@今載 百姓租庸。
# p 

冬，
十月，
庚寅，
上幸 dm#dm06942@華清宮 。

# p 

 rm#r00793@安祿山 專制三道，
陰蓄異志，
殆將十年，
以上待之厚，
欲俟上晏駕然後作亂。

會 rm#r02248@楊國忠 與 rm#r00793@祿山 不相悦，
屡言 rm#r00793@祿山 且反，
上不聽；
 rm#r02248@國忠 數以事激之，
欲其速反以取信於上。

 rm#r00793@祿山 由是決意遽反，
獨與孔目官‧太僕丞 rm#r06165@嚴莊 、掌書記‧屯田員外郎 rm#r04212@高尚 、將軍 rm#r06270@阿史那承慶 密謀，
自餘將佐皆莫之知，
但怪其自八月以來，
屡饗士卒，
秣馬厲兵而已。

會有奏事官自 dm#dm08170@京師 還，
 rm#r00793@祿山 詐爲敕書，
悉召諸將示之曰：
「有密旨，
令 rm#r00793@祿山 將兵入朝討 rm#r02248@楊國忠 ，
諸君宜即從軍。」

衆愕然相顧，
莫敢異言。

十一月，
甲子，
 rm#r00793@祿山 發所部兵及同羅、奚、契丹、室韋凡十五萬衆，
號二十萬，
反於 dm#dm06863@范陽 。

命 dm#dm06863@范陽 節度副使 rm#r03574@賈循 守 dm#dm06863@范陽 ，
 dm#dm02660@平盧 節度副使 rm#r05117@呂知誨 守 dm#dm02660@平盧 ，
別將 rm#r06280@高秀巖 守 dm#dm01578@大同 ；
諸將皆引兵夜發。
# p 

詰朝，
 rm#r00793@祿山 出 dm#dm07106@薊城 南，
大閲誓衆，
以討 rm#r02248@楊國忠 爲名，
牓軍中曰：
「有異議扇動軍人者，
斬及三族！」

於是引兵而南。

 rm#r00793@祿山 乘鐵轝，
歩騎精鋭，
煙塵千里，
鼓譟震地。

時海内久承平，
百姓累世不識兵革，
猝聞 dm#dm06863@范陽 兵起，
遠近震駭。

 dm#dm04656@河北 皆 rm#r00793@祿山 統内，
所過州縣，
望風瓦解，
守令或開門出迎，
或棄城竄匿，
或爲所擒戮，
無敢拒之者。

 rm#r00793@祿山 先遣將軍 rm#r06153@何千年 、 rm#r06281@高邈 將奚騎二十，
聲言獻射生手，
乘驛詣 dm#dm01774@太原 。

乙丑，
 dm#dm00832@北京 副留守 rm#r06217@楊光翽 出迎，
因劫之以去。

 dm#dm01774@太原 具言其状。

 dm#dm03796@東受降城 亦奏 rm#r00793@祿山 反。

上猶以爲惡 rm#r00793@祿山 者詐爲之，
未之信也。
# p 

庚午，
上聞 rm#r00793@祿山 定反，
乃召宰相謀之。

 rm#r02248@楊國忠 揚揚有徳色，
曰：
「今反者獨 rm#r00793@祿山 耳，
將士皆不欲也。

不過旬日，
必傳首詣行在。」

上以爲然，
大臣相顧失色。

上遣特進 rm#r05680@畢思琛 詣 dm#dm03788@東京 ，
金吾將軍 rm#r02989@程千里 詣 dm#dm04672@河東 ，
各簡募數萬人，
隨便團結以拒之。

辛未，
 dm#dm02061@安西 節度使 rm#r00852@封常清 入朝，
上問以討賊方略，
 rm#r00852@常清 大言曰：
「今太平積久，
故人望風憚賊。

然事有逆順，
勢有奇變，
臣請走馬詣 dm#dm03788@東京 ，
開府庫，
募驍勇，
挑馬箠渡 dm#dm04650@河 ，
計日取逆胡之首獻闕下！」

上悦。

壬申，
以 rm#r00852@常清 爲 dm#dm06863@范陽 、 dm#dm02660@平盧 節度使。

 rm#r00852@常清 即日乘驛詣 dm#dm03788@東京 募兵，
旬日，
得六萬人；
乃斷 dm#dm04711@河陽橋 ，
爲守禦之備。

# p 

甲戌，
 rm#r00793@祿山 至 dm#dm01107@博陵 南，
 rm#r06153@何千年 等執 rm#r06217@楊光翽 見 rm#r00793@祿山 ，
責 rm#r06217@光翽 以附 rm#r02248@楊國忠 ，
斬之以徇。

 rm#r00793@祿山 使其將 rm#r01157@安忠志 將精兵軍 dm#dm01466@土門 ，
 rm#r01157@忠志 ，
奚人，
 rm#r00793@祿山 養爲假子；
又以 rm#r01213@張獻誠 攝 dm#dm01107@博陵 太守，
 rm#r01213@獻誠 ，
 rm#r01137@守珪 之子也。

# p 

 rm#r00793@祿山 至 dm#dm00022@藁城 ，
 dm#dm02597@常山 太守 rm#r04143@顏杲卿 力不能拒，
與長史 rm#r06249@袁履謙 往迎之。

 rm#r00793@祿山 輒賜 rm#r04143@杲卿 金紫，
質其子弟，
使仍守 dm#dm02597@常山 ；
又使其將 rm#r06213@李欽湊 將兵數千人守 dm#dm00407@井陘口 ，
以備西來諸軍。

 rm#r04143@杲卿 歸途中，
指其衣謂 rm#r06249@履謙 曰：
「何爲著此？」
 rm#r06249@履謙 悟其意，
乃陰與 rm#r04143@杲卿 謀起兵討 rm#r00793@祿山 。

 rm#r04143@杲卿 ，
 rm#r06849@思魯 之玄孫也。


# p 

丙子，
上還宮。

斬太僕卿 rm#?@安慶宗 ，
賜 rm#?@榮義郡主 自盡。

以朔方節度使 rm#r06178@安思順 爲戸部尚書，
 rm#r06178@思順 弟 rm#rx0004@元貞 爲太僕卿。

以 dm#dm03677@朔方 右廂兵馬使、 dm#dm00317@九原 太守 rm#r03707@郭子儀 爲 dm#dm03677@朔方 節度使，
右羽林大將軍 rm#r06233@王承業 爲 dm#dm01774@太原 尹。

置 dm#dm04660@河南 節度使，
領 dm#dm08355@陳留 等十三郡，
以衞尉卿 dm#dm05659@猗氏  rm#r01096@張介然 爲之。

以 rm#r02989@程千里 爲 dm#dm05357@潞州 長史。

諸郡當賊衝者，
始置防禦使。
# p 

丁丑，
以 rm#r03754@榮王琬 爲元帥，
右金吾大將軍 rm#r04214@高仙芝 副之，
統諸軍東征。

出内府錢帛，
於 dm#dm08170@京師 募兵十一萬，
號曰 dm#dm01745@天武軍 ，
旬日而集，
皆市井子弟也。
# p 

十二月，
丙戌，
 rm#r04214@高仙芝 將飛騎、彍騎及新募兵、邊兵在 dm#dm08170@京師 者合五萬人，
發 dm#dm08170@長安 。

上遣宦者監門將軍 rm#?@邊令誠 監其軍，
屯於 dm#dm08318@陝 。

# p 

丁亥，
 rm#r00793@安祿山 自 dm#dm08623@靈昌 渡 dm#dm04650@河 ，
以緪約敗船及草木横絶河流，
一夕，
冰合如浮梁，
遂陷 dm#dm08625@靈昌郡 。

 rm#r00793@祿山 歩騎散漫，
人莫知其數，
所過殘滅。

 rm#r01096@張介然 至 dm#dm08355@陳留 纔數日，
 rm#r00793@祿山 至，
授兵登城，
衆忷懼，
不能守。

庚寅，
太守 rm#r03734@郭納 以城降。

 rm#r00793@祿山 入北郭，
聞 rm#?@安慶宗 死，
慟哭曰：
「我何罪，
而殺我子！」

時 dm#dm08355@陳留 將士降者夾道近萬人，
 rm#r00793@祿山 皆殺之以快其忿；
斬 rm#r01096@張介然 於軍門。

以其將 rm#r06208@李庭望 爲節度使，
守 dm#dm08355@陳留 。

# p 

壬辰，
上下制欲親征，
其 dm#dm03677@朔方 、 dm#dm04695@河西 、 dm#dm08458@隴右 兵留守城堡之外，
皆赴行營，
令節度使自將之；
期二十日畢集。
# p 

初，
 dm#dm02609@平原 太守 rm#r04147@顏眞卿 知 rm#r00793@祿山 且反，
因霖雨，
完城浚壕，
料丁壯，
實倉廩；
 rm#r00793@祿山 以其書生，
易之。

及 rm#r00793@祿山 反，
牒 rm#r04147@眞卿 以 dm#dm02609@平原 、 dm#dm01090@博平 兵七千人防 dm#dm04650@河 津，
 rm#r04147@眞卿 遣 dm#dm02609@平原 司兵 rm#r05378@李平 間道奏之。

上始聞 rm#r00793@祿山 反，
 dm#dm04656@河北 郡縣皆風靡，
歎曰：
「二十四郡，
曾無一人義士邪！

」
及 rm#r05378@平 至，
大喜曰：
「朕不識 rm#r04147@顏眞卿 作何状，
乃能如是！」

 rm#r04147@眞卿 遣親客密懷購賊牒詣諸郡，
由是諸郡多應者。

 rm#r04147@眞卿 ，
 rm#r04143@杲卿 之從弟也。

# p 

 rm#r00793@安祿山 引兵向 dm#dm05216@滎陽 ，
太守 rm#r00956@崔無詖 拒之；
士卒乘城者，
聞鼓角聲，
自墜如雨。

癸巳，
 rm#r00793@祿山 陷 dm#dm05216@滎陽 ，
殺 rm#r00956@無詖 ，
以其將 rm#r06223@武令珣 守之。

 rm#r00793@祿山 聲勢益張，
以其將 rm#r02821@田承嗣 、 rm#r01157@安忠志 、 rm#r01268@張孝忠 爲前鋒。

 rm#r00852@封常清 所募兵皆白徒，
未更訓練，
屯 dm#dm04285@武牢 以拒賊；
賊以鐵騎蹂之，
官軍大敗。

 rm#r00852@常清 收餘衆，
戰於 dm#dm07011@葵園 ，
又敗；
戰 dm#dm00171@上東門 内，
又敗。

丁酉，
 rm#r00793@祿山 陷 dm#dm03788@東京 ，
賊鼓譟自四門入，
縱兵殺掠。

 rm#r00852@常清 戰於 dm#dm07872@都亭驛 ，
又敗；
退守 dm#dm02204@宣仁門 ，
又敗；
乃自苑西壞牆西走。

# p 

 dm#dm04660@河南 尹 rm#r03675@達奚珣 降於 rm#r00793@祿山 。

留守 rm#r01595@李憕 謂御史中丞 rm#r02897@盧奕 曰：
「吾曹荷國重任，
雖知力不敵，
必死之！」

 rm#r02897@奕 許諾。

 rm#r01595@憕 收殘兵數百，
欲戰，
皆棄 rm#r01595@憕 潰去；
 rm#r01595@憕 獨坐府中。

 rm#r02897@奕 先遣妻子懷印間道走 dm#dm08170@長安 ，
朝服坐臺中，
左右皆散。

 rm#r00793@祿山 屯於閑廐，
使人執 rm#r01595@憕 、 rm#r02897@奕 及采訪判官 rm#r03220@蒋清 ，
皆殺之。

 rm#r02897@奕 罵 rm#r00793@祿山 ，
數其罪，
顧賊黨曰：
「凡爲人當知逆順。

我死不失節，
夫復何恨！」

 rm#r01595@憕 ，
 dm#dm03309@文水 人；
 rm#r02897@奕 ，
 rm#r02906@懷愼 之子；
 rm#r03220@清 ，
 rm#r03218@欽緒 之子也。

 rm#r00793@祿山 以其黨 rm#r01244@張萬頃 爲 dm#dm04660@河南 尹。
# p 

 rm#r00852@封常清 帥餘衆至 dm#dm08318@陝 ，
 dm#dm08329@陝郡 太守 rm#r05728@竇廷芝 已奔 dm#dm04672@河東 ，
吏民皆散。

 rm#r00852@常清 謂 rm#r04214@高仙芝 曰：
「 rm#r00852@常清 連日血戰，
賊鋒不可當。

且 dm#dm05384@潼關 無兵，
若賊豕突入 dm#dm08280@關 ，
則 dm#dm08170@長安 危矣。

 dm#dm08318@陝 不可守，
不如引兵先據 dm#dm05384@潼關 以拒之。」

 rm#r04214@仙芝 乃帥見兵西趣 dm#dm05384@潼關 。

賊尋至，
官軍狼狽走，
無復部伍，
士馬相騰踐，
死者甚衆。

至 dm#dm05384@潼關 ，
脩完守備，
賊至，
不得入而去。

 rm#r00793@祿山 使其將 rm#r06181@崔乾祐 屯 dm#dm08318@陝 ，
 dm#dm06670@臨汝 、 dm#dm02888@弘農 、 dm#dm05443@濟陰 、 dm#dm05459@濮陽 、 dm#dm08547@雲中郡 皆降於 rm#r00793@祿山 。

是時，
朝廷徵兵諸道，
皆未至，
 dm#dm08281@關中 忷懼。

會 rm#r00793@祿山 方謀稱帝，
留 dm#dm03788@東京 不進，
故朝廷得爲之備，
兵亦稍集。

# p 

 rm#r00793@祿山 以 rm#r06191@張通儒 之弟 rm#r05305@通晤 爲 dm#dm06055@睢陽 太守，
與 dm#dm08355@陳留 長史 rm#?@楊朝宗 將胡騎千餘東略地，
守，
式又翻。

將，
即亮翻。

騎，
奇寄翻。

郡縣官多望風降走，
惟 dm#dm03822@東平 太守嗣 rm#r00527@呉王祗 、 dm#dm05436@濟南 太守 rm#r02005@李隨 起兵拒之。

 rm#?@祗 ，
 rm#r00132@禕 之弟也。

郡縣之不從賊者，
皆倚 rm#?@呉王 爲名。

 dm#dm01402@單父 尉 rm#r03587@賈賁 帥吏民南撃 dm#dm06055@睢陽 ，
斬 rm#r05305@張通晤 。

 rm#r06208@李庭望 引兵欲東徇地，
聞之，
不敢進而還。

# p 

庚子，
以 rm#r02372@永王璘 爲 dm#dm02398@山南 節度使，
 dm#dm04516@江陵 長史 rm#r02470@源洧 爲之副；
 rm#r02516@潁王璬 爲 dm#dm00785@劍南 節度使，
 dm#dm07205@蜀郡 長史 rm#r00908@崔圓 爲之副。

二王皆不出閤。

 rm#r02470@洧 ，
 rm#r02469@光裕 之子也。

# p 

上議親征，
辛丑，
制太子監國，
謂宰相曰：
「朕在位垂五十載，
倦于憂勤，
去秋已欲傳位太子；
値水旱相仍，
不欲以餘災遺子孫，
淹留俟稍豐。

不意逆胡横發，
朕當親征，
且使之監國。

事平之日，
朕將高枕無爲矣。」

 rm#r02248@楊國忠 大懼，
退謂 rm#ry0003@韓 、 rm#?@虢 、 rm#?@秦 三夫人曰：
「太子素惡吾家專横久矣，
若一旦得天下，
吾與姉妹併命在旦暮矣！」

相與聚哭。

使三夫人説 rm#r02136@貴𡚱 ，
銜土請命於上；
事遂寢。
# p 

 rm#r04147@顏眞卿 召募勇士，
旬日至萬餘人，
諭以舉兵討 rm#r00793@安祿山 ，
繼以涕泣，
士皆感憤。

 rm#r00793@祿山 使其黨 rm#r05545@段子光 齎 rm#r01595@李憕 、 rm#r02897@盧奕 、 rm#r03220@蒋清 首徇 dm#dm04656@河北 諸郡，
至 dm#dm02609@平原 ，
壬寅，
 rm#r04147@眞卿 執 rm#r05545@子光 ，
腰斬以徇；
取三人首，
續以蒲身，
棺斂葬之，
祭哭受弔。

 rm#r00793@祿山 以海運使 rm#r05090@劉道玄 攝 dm#dm03589@景城 太守，
 dm#dm05048@清池 尉 rm#r05890@賈載 、 dm#dm09051@鹽山 尉 dm#dm04653@河内  rm#r03003@穆寧 共斬 rm#r05090@道玄 ，
得其甲仗五十餘船；
攜 rm#r05090@道玄 首謁長史 rm#r01821@李暐 ，
 rm#r01821@暐 收 rm#r06165@嚴莊 宗族，
悉誅之。

是日，
送 rm#r05090@道玄 首至 dm#dm02609@平原 。

 rm#r04147@眞卿 召 rm#r05890@載 、 rm#r03003@寧 及 dm#dm05053@清河 尉 rm#r05285@張澹 詣 dm#dm02609@平原 計事。

 dm#dm08803@饒陽 太守 rm#r05698@盧全誠 據城不受代；
 dm#dm04700@河間 司法 rm#r06207@李奐 殺 rm#r00793@祿山 所署長史 rm#r05631@王懷忠 ；
 rm#r02005@李隨 遣遊弈將 rm#r05863@訾嗣賢 濟 dm#dm04650@河 ，
殺 rm#r00793@祿山 所署 dm#dm01090@博平 太守 rm#r06070@馬冀 ；
各有衆數千或萬人，
共推 rm#r04147@眞卿 爲盟主，
軍事皆稟焉。

 rm#r00793@祿山 使 rm#r01213@張獻誠 將 dm#dm00190@上谷 、 dm#dm01107@博陵 、 dm#dm02597@常山 、 dm#dm07625@趙郡 、 dm#dm03301@文安 五郡團結兵萬人圍 dm#dm08803@饒陽 。

# p 

 rm#r04214@高仙芝 之東征也，
監軍 rm#xjts12612@邊令誠 數以事干之，
 rm#r04214@仙芝 多不從。

 rm#xjts12612@令誠 入奏事，
具言 rm#r04214@仙芝 、 rm#r00852@常清 橈敗之状，
且云：
「 rm#r00852@常清 以賊搖衆，
而 rm#r04214@仙芝 棄 dm#dm08318@陝 地數百里，
又盜減軍士糧賜。」

上大怒，
癸卯，
遣 rm#xjts12612@令誠 齎敕即軍中斬 rm#r04214@仙芝 及 rm#r00852@常清 。

初，
 rm#r00852@常清 既敗，
三遣使奉表陳賊形勢，
上皆不之見。

 rm#r00852@常清 乃自馳詣闕，
至 dm#dm05106@渭南 ，
敕削其官爵，
令還 rm#r04214@仙芝 軍，
白衣自效。

 rm#r00852@常清 草遺表曰：
「臣死之後，
望陛下不輕此賊，
無忘臣言！」

時朝議皆以爲 rm#r00793@祿山 狂悖，
不日授首，
故 rm#r00852@常清 云然。

 rm#xjts12612@令誠 至 dm#dm05384@潼關 ，
先引 rm#r00852@常清 ，
宣敕示之；
 rm#r00852@常清 以表附 rm#xjts12612@令誠 上之。

 rm#r00852@常清 既死，
陳尸蘧蒢。

蘧蒢，
蘆䕠也。

 rm#r04214@仙芝 還，
至聽事，
 rm#xjts12612@令誠 索陌刀手百餘人自隨，
乃謂 rm#r04214@仙芝 曰：
「大夫亦有恩命。」

 rm#r04214@仙芝 遽下，
 rm#xjts12612@令誠 宣敕。

 rm#r04214@仙芝 曰：
「我遇敵而退，
死則宜矣。

今上戴天，
下履地，
謂我盜減糧賜則誣也。」

時士卒在前，
皆大呼稱枉，
其聲振地，
遂斬之。

以將軍 rm#r05393@李承光 攝領其衆。
# p 

 dm#dm04695@河西 、 dm#dm08458@隴右 節度使 rm#r00487@哥舒翰 病廢在家，
上藉其威名，
且素與 rm#r00793@祿山 不協，
召見，
拜兵馬副元帥，
將兵八萬以討 rm#r00793@祿山 ；
仍敕天下四面進兵，
會攻 dm#dm04788@洛陽 。

 rm#r00487@翰 以病固辭，
上不許，
以 rm#?@田良丘 爲御史中丞，
充行軍司馬，
起居郎 rm#r03245@蕭昕 爲判官，
蕃將 rm#?@火拔歸仁 等各將部落以從，
幷 rm#r04214@仙芝 舊卒，
號二十萬，
軍于 dm#dm05384@潼關 。

 rm#r00487@翰 病，
不能治事，
悉以軍政委 rm#?@田良丘 ；
 rm#?@良丘 復不敢專決，
使 rm#r02633@王思禮 主騎，
 rm#r05393@李承光 主歩，
二人爭長，
無所統壹。

 rm#r00487@翰 用法嚴而不恤，
士卒皆懈弛，
無鬬志。

# p 

 rm#r00793@安祿山  dm#dm01584@大同軍 使 rm#r06280@高秀巖 寇 dm#dm03230@振武軍 ，
 dm#dm03677@朔方 節度使 rm#r03707@郭子儀 撃敗之，
 rm#r03707@子儀 乘勝拔 dm#dm08709@靜邊軍 。

 dm#dm01578@大同 兵馬使 rm#r05810@薛忠義 寇 dm#dm08709@靜邊軍 ，
 rm#r03707@子儀 使左兵馬使 rm#r01630@李光弼 、右兵馬使 rm#?@高濬 、左武鋒使 rm#r00144@僕固懷恩 、右武鋒使 rm#r05569@渾釋之 等逆撃，
大破之，
坑其騎七千。

進圍 dm#dm08542@雲中 ，
使別將 rm#r05051@公孫瓊 巖將二千騎撃 dm#dm08829@馬邑 ，
拔之，
開 dm#dm03887@東陘關 。

甲辰，
加 rm#r03707@子儀 御史大夫。

 rm#r00144@懷恩 ，
 rm#?@哥濫拔延 之曾孫也，
世爲 dm#dm08029@金微 都督。

 rm#r05569@釋之 ，
渾部酋長，
世爲 dm#dm05968@皋蘭 都督。

# p 

 rm#r04143@顏杲卿 將起兵，
參軍 rm#r06277@馮虔 、前 dm#dm06038@眞定 令 rm#r06262@賈深 、 dm#dm00022@藁城 尉 rm#r04019@崔安石 、郡人 rm#r06149@翟萬徳 、 dm#dm00667@内丘 丞 rm#r06192@張通幽 皆預其謀；
又遣人語 dm#dm01774@太原 尹 rm#r06233@王承業 ，
密與相應。

會 rm#r04147@顏眞卿 自 dm#dm02609@平原 遣 rm#r04143@杲卿 甥 rm#r05712@盧逖 潛告 rm#r04143@杲卿 ，
欲連兵斷 rm#r00793@祿山 歸路，
以緩其西入之謀。

時 rm#r00793@祿山 遣其金吾將軍 rm#r06281@高邈 詣 dm#dm02689@幽州 徵兵，
未還，
杲卿以 rm#r00793@祿山 命召 rm#r06213@李欽湊 ，
使帥衆詣郡受犒賚；
丙午，
薄暮，
 rm#r06749@欽湊 至，
 rm#r04143@杲卿 使 rm#r05836@袁屡謙 、 rm#r06277@馮虔 等攜酒食妓樂往勞之，
幷其黨皆大醉，
乃斷 rm#r06749@欽湊 首，
收其甲兵，
盡縛其黨，
明日，
斬之，
悉散 dm#dm00409@井陘 之衆。

有頃，
 rm#r06281@高邈 自 dm#dm02689@幽州 還，
且至 dm#dm00022@藁城 ，
 rm#r04143@杲卿 使 rm#r06277@馮虔 往，
擒之。

南境又白 rm#r06153@何千年 自 dm#dm03788@東京 來，
 rm#r04019@崔安石 與 rm#r06149@翟萬徳 馳詣 dm#dm07991@醴泉驛 迎 rm#r06153@千年 ，
又擒之，
同日致於郡下。

 rm#r06153@千年 謂 rm#r04143@杲卿 曰：
「今太守欲輸力王室，
既善其始，
當愼其終。

此郡應募烏合，
難以臨敵，
宜深溝高壘，
勿與爭鋒。

俟 dm#dm03677@朔方 軍至，
併力齊進，
傳檄 dm#dm07617@趙 、 dm#dm08945@魏 ，
斷 dm#dm05594@燕 、 dm#dm07104@薊 要膂。

今且宜聲云，
『 rm#r01630@李光弼 引歩騎一萬出 dm#dm00409@井陘 ；』
因使人説 rm#r01213@張獻誠 云：
『足下所將多團練之人，
無堅甲利兵，
難以當 dm#dm02407@山西 勁兵，』
 dm#dm02597@常山 、 dm#dm08803@饒陽 以 dm#dm00058@幷 、 dm#dm00485@代 爲 dm#dm02407@山西 。

合天下言之，
則 dm#dm04660@河南 、 dm#dm04656@河北 通謂之 dm#dm02403@山東 ，
 dm#dm00743@函關 以西爲 dm#dm02407@山西 。

説，
式芮翻。

將，
即亮翻，
又音如字。

獻誠必解圍遁去。

此亦一奇也。」

 rm#r04143@杲卿 悦，
用其策，
 rm#r01213@獻誠 果遁去，
其團練兵皆潰。

 rm#r04143@杲卿 乃使人入 dm#dm08804@饒陽城 ，
慰勞將士。

命 rm#r04019@崔安石 等徇諸郡云：
「大軍已下 dm#dm00409@井陘 ，
朝夕當至，
先平 dm#dm04656@河北 諸郡。

先下者賞，
後至者誅！」

於是 dm#dm04656@河北 諸郡響應，
凡十七郡皆歸朝廷，
兵合二十餘萬；
其附 rm#r00793@祿山 者，
唯 dm#dm06863@范陽 、 dm#dm06013@盧龍 、 dm#dm02264@密雲 、 dm#dm05254@漁陽 、 dm#dm04534@汲 、 dm#dm07971@鄴 六郡而已。
彼則成擒矣
# p 

 rm#r04143@杲卿 又密使人入 dm#dm06863@范陽 招 rm#r03574@賈循 ，
 dm#dm07851@郟城 人 rm#r04181@馬燧 説 rm#r03574@循 曰：
「 rm#r00793@祿山 負恩悖逆，
雖得 dm#dm04788@洛陽 ，
終歸夷滅。

公若誅諸將之不從命者，
以 dm#dm06863@范陽 歸國，
傾其根柢，
此不世之功也。」

 rm#r03574@循 然之，
猶豫不時發。

別將 rm#r05586@牛潤容 知之，
以告 rm#r00793@祿山 ，
 rm#r00793@祿山 使其黨 rm#r06067@韓朝陽 召 rm#r03574@循 。

 rm#r06067@朝陽 至 dm#dm06863@范陽 ，
引 rm#r03574@循 屏語，
使壯士縊殺之，
滅其族；
以別將 rm#r05584@牛廷玠 知 dm#dm06863@范陽 軍事。

 rm#r00380@史思明 、 rm#r05425@李立節 將蕃、 dm#dm05271@漢 歩騎萬人撃 dm#dm01107@博陵 、 dm#dm02597@常山 。

 rm#r04181@馬燧 亡入 dm#dm07314@西山 ；
隱者 rm#r05323@徐遇 匿之，
得免。范漁
# p 

初，
 rm#r00793@祿山 欲自將攻 dm#dm05384@潼關 ，
至 dm#dm03337@新安 ，
聞 dm#dm04656@河北 有變而還。

 rm#r06243@蔡希徳 將兵萬人自 dm#dm04653@河内 北撃 dm#dm02597@常山 。

# p 

戊申，
 rm#r03754@榮王琬 薨，
贈諡 rm#r03754@靖恭太子 。
# p 

 y@是歳 ，
吐蕃贊普 rm#xjts27223@乞梨蘇籠獵贊 卒，
子 rm#xjts12488@娑悉籠獵贊 立。


# p 

肅宗文明武徳大聖大宣孝皇帝上之上
*** 十五年
# year 0756
*** 至徳元載
# year 0756
# p 

春，
正月，
乙卯朔，
 rm#r00793@祿山 自稱 rm#r00793@大燕皇帝 ，
改元 y@聖武 ，
以 rm#r03675@達奚珣 爲侍中，
 rm#r06191@張通儒 爲中書令。

 rm#r04212@高尚 、 rm#r06165@嚴莊 爲中書侍郎。
# p 

 rm#r02005@李隨 至 dm#dm06055@睢陽 ，
有衆數萬。

丙辰，
以 rm#r02005@隨 爲 dm#dm04660@河南 節度使，
以前高要尉 rm#r03525@許遠 爲 dm#dm06055@睢陽 太守兼防禦使。

 dm#dm05459@濮陽 客 rm#r00867@尚衡 起兵討 rm#r00793@祿山 ，
以郡人 rm#r02654@王栖曜 爲衙前總管，
攻拔 dm#dm05443@濟陰 ，
殺 rm#r00793@祿山 將 rm#r05925@邢超然 。

# p 

 rm#r04143@顏杲卿 使其子 rm#r04144@泉明 、 rm#r06262@賈深 、 rm#r06149@翟萬徳 獻 rm#r06213@李欽湊 首及 rm#r06153@何千年 、 rm#r06281@高邈 于 dm#dm08170@京師 。

 rm#r06192@張通幽 泣請曰：
「 rm#r06192@通幽 兄陷賊，
乞與 rm#r04144@泉明 偕行，
以救宗族。」

 rm#r04143@杲卿 哀而許之。

至 dm#dm01774@太原 ，
 rm#r06192@通幽 欲自託於 rm#r06233@王承業 ，
乃教之留 rm#r04144@泉明 等，
更其表，
多自爲功，
毀短 rm#r04143@杲卿 ，
別遣使獻之。

 rm#r04143@杲卿 起兵纔八日，
守備未完，
 rm#r00380@史思明 、 rm#r06243@蔡希徳 引兵皆至城下。

 rm#r04143@杲卿 告急於 rm#?@承業 ，
 rm#?@承業 既竊其功，
利於城陷，
遂擁兵不救。

 rm#r04143@杲卿 晝夜拒戰，
糧盡矢竭；
壬戌，
城陷。

賊縱兵殺萬餘人，
執 rm#r04143@杲卿 及 rm#r06249@袁履謙 等送 dm#dm04788@洛陽 。

 rm#r06233@王承業 使者至 dm#dm08170@京師 ，
 rm#r02004@玄宗 大喜，
拜 rm#?@承業 羽林大將軍，
麾下受官爵者以百數。

徵 rm#r04143@顏杲卿 爲衞尉卿。

朝命未至，
 dm#dm02597@常山 已陷。

# p 

 rm#r04143@杲卿 至 dm#dm04788@洛陽 ，
 rm#r00793@祿山 數之曰：
「汝自 dm#dm06863@范陽 戸曹，
我奏汝爲判官，
不數年超至太守，
何負於汝而反邪？」
 rm#r04143@杲卿 瞋目罵曰：
「汝本 dm#dm05611@營州 牧羊羯奴，
天子擢汝爲三道節度使，
恩幸無比，
何負於汝而反？
我世爲 dyn#ch100@唐 臣，
祿位皆 dyn#ch100@唐 有，
雖爲汝所奏，
豈從汝反邪！

我爲國討賊，
恨不斬汝，
何謂反也？
臊羯狗，
何不速殺我！」

 rm#r00793@祿山 大怒，
幷 rm#r06249@袁履謙 等縛於 dm#dm00272@中橋 之柱而冎之。

 rm#r04143@杲卿 、 rm#r06249@履謙 比死，
罵不虚口。

 rm#no@顏氏 一門死於刀鋸者三十餘人。
# p 

 rm#r00380@史思明 、 rm#r05425@李立節 、 rm#r06243@蔡希徳 既克 dm#dm02597@常山 ，
引兵撃諸郡之不從者，
所過殘滅，
於是 dm#dm07971@鄴 、 dm#dm02734@廣平 、 dm#dm08069@鉅鹿 、 dm#dm07617@趙 、 dm#dm00190@上谷 、 dm#dm01107@博陵 、 dm#dm03301@文安 、 dm#dm08945@魏 、 dm#dm00581@信都 等郡復爲賊守。

 dm#dm08803@饒陽 太守 rm#r05698@盧全誠 獨不從，
 rm#r00380@思明 等圍之。

 dm#dm04700@河間 司法 rm#r06207@李奐 將七千人、 dm#dm03589@景城 長史 rm#r01821@李暐 遣其子 rm#?@祀 將八千人救之，
皆爲 rm#r00380@思明 所敗。

# p 

上命 rm#r03707@郭子儀 罷圍 dm#dm08542@雲中 ，
還 dm#dm03677@朔方 ，
益發兵進取 dm#dm03788@東京 ；
選良將一人分兵先出 dm#dm00409@井陘 ，
定 dm#dm04656@河北 。

 rm#r03707@子儀 薦 rm#r01630@李光弼 ，
癸亥，
以 rm#r01630@光弼 爲 dm#dm04672@河東 節度使，
分 dm#dm03677@朔方 兵萬人與之。

# p 

甲子，
加 rm#r00487@哥舒翰 左僕射、同平章事，
餘如故。
# p 

置 dm#dm01077@南陽 節度使，
以 dm#dm01077@南陽 太守 rm#r04315@魯炅 爲之，
將 dm#dm02527@嶺南 、 dm#dm09182@黔中 、 dm#dm07284@襄陽 子弟五萬人屯 dm#dm06992@葉 北，
以備 rm#r00793@安祿山 。

 rm#r04315@炅 表 rm#r03292@薛愿 爲 dm#dm05331@潁川 太守兼防禦使，
 rm#r04352@龐堅 爲副使。

 rm#r03292@愿 ，
故太子瑛之𡚱兄；
 rm#r04352@堅 ，
 rm#r06284@玉 之曾孫也。

# p 

乙丑，
 rm#r00793@安祿山 遣其子 rm#r00789@慶緒 寇 dm#dm05384@潼關 ；
 rm#r00487@哥舒翰 撃卻之。

# p 

己巳，
加 rm#r04147@顏眞卿 戸部侍郎兼本郡防禦使；
 rm#r04147@眞卿 以 rm#r01821@李暐 爲副。


# p 

二月，
丙戌，
加 rm#r01630@李光弼  dm#dm08957@魏郡 太守、 dm#dm04658@河北道 采訪使。
# p 

 rm#r00380@史思明 等圍 dm#dm08803@饒陽 二十九日，
不下，
 rm#r01630@李光弼 將蕃、 dm#dm05271@漢 歩騎萬餘人、 dm#dm01774@太原 弩手三千人出 dm#dm00409@井陘 。

己亥，
至 dm#dm02597@常山 ，
 dm#dm02597@常山 團練兵三千人殺胡兵，
執 rm#r05174@安思義 出降。

 rm#r01630@光弼 謂 rm#r05174@思義 曰：
「汝自知當死否？」
 rm#r05174@思義 不應。

 rm#r01630@光弼 曰：
「汝久更陳行，
視吾此衆，
可敵 rm#r00380@思明 否？
今爲我計當如何？
汝策可取，
當不殺汝。」

 rm#r05174@思義 曰：
「大夫士馬遠來疲弊，
猝遇大敵，
恐未易當；
不如移軍入城，
早爲備禦，
先料勝負，
然後出兵。

胡騎雖鋭，
不能持重，
苟不獲利，
氣沮心離，
於時乃可圖矣。

 rm#r00380@思明 今在 dm#dm08803@饒陽 ，
去此不二百里。

昨暮羽書已去，
計其先鋒來晨必至，
而大軍繼之，
不可不留意也。」

 rm#r01630@光弼 悦，
釋其縛，
即移軍入城。

 rm#r00380@史思明 聞 dm#dm02597@常山 不守，
立解 dm#dm08803@饒陽 之圍；
明日未旦，
先鋒已至，
 rm#r00380@思明 等繼之，
合二萬餘騎，
直抵城下。

 rm#r01630@光弼 遣歩卒五千自東門出戰，
賊守門不退。

 rm#r01630@光弼 命五百弩於城上齊發射之，
賊稍卻；
乃出弩手千人分爲四隊，
使其矢發發相繼，
賊不能當，
斂軍道北。

 rm#r01630@光弼 出兵五千爲槍城於道南，
夾 dm#dm01322@呼沱水 而陳；
賊數以騎兵搏戰，
 rm#r01630@光弼 之兵射之，
人馬中矢者太半，
乃退，
小憩以俟歩兵。

有村民告賊歩兵五千自 dm#dm08803@饒陽 來，
晝夜行百七十里，
至 dm#dm00335@九門 南 dm#dm07705@逢壁 ，
度憩息。

 rm#r01630@光弼 遣歩騎各二千，
匿旗鼓，
竝水潛行，
至 dm#dm07705@逢壁 ，
賊方飯，
縱兵掩撃，
殺之無遺。

 rm#r00380@思明 聞之，
失勢，
退入 dm#dm00335@九門 。

時 dm#dm02597@常山 九縣，
七附官軍，
惟 dm#dm00335@九門 、 dm#dm00022@藁城 爲賊所據。

 rm#r01630@光弼 遣裨將 rm#r05259@張奉璋 以兵五百戍 dm#dm06124@石邑 ；
餘皆三百人戍之。
# p 

上以 rm#r00527@呉王祗 爲 dm#dm08623@靈昌 太守、 dm#dm04660@河南 都知兵馬使。

 rm#r03587@賈賁 前至 dm#dm08496@雍丘 ，
有衆二千。

先是 dm#dm07453@譙郡 太守 rm#r05513@楊萬石 以郡降 rm#r00793@安祿山 ，
逼 dm#dm06045@眞源 令 dm#dm04672@河東  rm#r01142@張巡 使爲長史，
西迎賊。

 rm#r01142@巡 至 dm#dm06045@眞源 ，
帥吏民哭於 dm#dm05684@玄元皇帝廟 ，
起兵討賊，
吏民樂從者數千人；
 rm#r01142@巡 選精兵千人西至 dm#dm08496@雍丘 ，
與 rm#r03587@賈賁 合。
# p 

初，
 dm#dm08496@雍丘 令 rm#r06151@令狐潮 以縣降賊，
賊以爲將，
使東撃 dm#dm05009@淮陽 救兵于 dm#dm07281@襄邑 ，
破之，
俘百餘人，
拘於 dm#dm08496@雍丘 ，
將殺之，
往見 rm#r06208@李庭望 ；
 dm#dm05009@淮陽 兵遂殺守者，
 rm#r06151@潮 棄妻子走，
故 rm#r03587@賈賁 得以其間入 dm#dm08496@雍丘 。

庚子，
 rm#r06151@潮 引賊精兵攻 dm#dm08496@雍丘 ；
 rm#r03587@賁 出戰，
敗死。

 rm#r01142@張巡 力戰卻賊，
因兼領 rm#r03587@賁 衆，
自稱 rm#r01142@呉王 先鋒使。
# p 

三月，
乙卯，
 rm#r06151@潮 復與賊將 rm#r01773@李懷仙 、 rm#?@楊朝宗 、 rm#r05869@謝元同 等四萬餘衆奄至城下；
衆懼，
莫有固志。

 rm#r01142@巡 曰：
「賊兵精鋭，
有輕我心。

今出其不意撃之，
彼必驚潰。

賊勢小折，
然後城可守也。」

乃使千人乘城；
自帥千人，
分數隊，
開門突出。

 rm#r01142@巡 身先士卒，
直衝賊陳，
人馬辟易，
賊遂退。

明日，
復進攻城，
設百礮環城，
樓堞皆盡；
 rm#r01142@巡 於城上立木柵以拒之。

賊蟻附而登，
 rm#r01142@巡 束蒿灌脂，
焚而投之，
賊不得上。

時伺賊隙，
出兵撃之，
或夜縋斫營，
積六十餘日，
大小三百餘戰，
帶甲而食，
裹瘡復戰，
賊遂敗走。

 rm#r01142@巡 乘勝追之，
獲胡兵二千人而還，
軍聲大振。


# p 

初，
戸部尚書 rm#r06178@安思順 知 rm#r00793@祿山 反謀，
因入朝奏之。

及 rm#r00793@祿山 反，
上以 rm#r06178@思順 先奏，
不之罪也。

 rm#r00487@哥舒翰 素與之有隙，
使人詐爲 rm#r00793@祿山 遺 rm#r06178@思順 書，
於 dm#dm08280@關 門擒之以獻，
且數 rm#r06178@思順 七罪，
請誅之。

丙辰，
 rm#r06178@思順 及弟太僕卿 rm#?@元貞 皆坐死，
家屬徙 dm#dm02532@嶺外 。

 rm#r02248@楊國忠 不能救，
由是始畏翰。

# p 

 rm#r03707@郭子儀 至 dm#dm03677@朔方 ，
益選精兵，
戊午，
進軍于 dm#dm00485@代 。

# p 

戊辰，
 rm#r00527@呉王祗 撃 rm#r05869@謝元同 ，
走之，
拜 dm#dm08355@陳留 太守、 dm#dm04660@河南 節度使。

# p 

壬午，
以 dm#dm04672@河東 節度使 rm#r01630@李光弼 爲 dm#dm06863@范陽 長史、 dm#dm04656@河北 節度使。

加 rm#r04147@顏眞卿  dm#dm04656@河北 采訪使。

 rm#r04147@眞卿 以 rm#r05285@張澹 爲支使。
# p 

先是 dm#dm05053@清河 客 rm#r05429@李萼 ，
年二十餘，
爲郡人乞師於 rm#r04147@眞卿 曰：
「公首唱大義，
 dm#dm04656@河北 諸郡恃公以爲長城。

今 dm#dm05053@清河 ，
公之西鄰，
國家平日聚 dm#dm04475@江 、 dm#dm04981@淮 、 dm#dm04660@河南 錢帛於彼以贍北軍，
謂之『天下北庫』；
今有布三百餘萬匹，
帛八十餘萬匹，
錢三十餘萬緡，
糧三十餘萬斛。

昔討默啜，
甲兵皆貯 dm#dm05053@清河 庫，
今有五十餘萬事。

戸七萬，
口十餘萬。

竊計財足以三 dm#dm02609@平原 之富，
兵足以倍 dm#dm02609@平原 之強。

公誠資以士卒，
撫而有之，
以二郡爲腹心，
則餘郡如四支，
無不隨所使矣。」

 rm#r04147@眞卿 曰：
「 dm#dm02609@平原 兵新集，
尚未訓練，
自保恐不足，
何暇及鄰！

雖然，
借若諾子之請，
則將何爲乎？」
 rm#r05429@萼 曰：
「 dm#dm05053@清河 遣僕銜命於公者，
非力不足而借公之師以嘗寇也，
亦欲觀大賢之明義耳。

今仰瞻高意，
未有決辭定色，
僕何敢遽言所爲哉！」

 rm#r04147@眞卿 奇之，
欲與之兵。

衆以爲 rm#r05429@萼 年少輕虜，
徒分兵力，
必無所成，
 rm#r04147@眞卿 不得已辭之。

 rm#r05429@萼 就館，
復爲書説 rm#r04147@眞卿 ，
以爲：
「 dm#dm05053@清河 去逆效順，
奉粟帛器械以資軍，
公乃不納而疑之。

僕囘轅之後，
 dm#dm05053@清河 不能孤立，
必有所繋託，
將爲公西面之強敵，
公能無悔乎？」
 rm#r04147@眞卿 大驚，
遽詣其館，
以兵六千借之；
送至境，
執手別。

 rm#r04147@眞卿 問曰：
「兵已行矣，
可以言子之所爲乎？」
 rm#r05429@萼 曰：
「聞朝廷遣 rm#r02989@程千里 將精兵十萬出 dm#dm02500@崞口 討賊，
賊據險拒之，
不得前。

今當引兵先撃 dm#dm08957@魏郡 ，
執 rm#r00793@祿山 所署太守 rm#r05839@袁知泰 ，
納舊太守 rm#r05102@司馬垂 ，
使爲西南主人；
分兵開 dm#dm02500@崞口 ，
出 rm#r02989@千里 之師，
因討 dm#dm04534@汲 、 dm#dm07971@鄴 以北至于 dm#dm02693@幽陵 郡縣之未下者；
 dm#dm02609@平原 、 dm#dm05053@清河 帥諸同盟，
合兵十萬，
南臨 dm#dm01950@孟津 ，
分兵循 dm#dm04650@河 ，
據守要害，
制其北走之路。

計官軍東討者不下二十萬，
 dm#dm04660@河南 義兵西向者亦不減十萬。

公但當表朝廷堅壁勿戰，
不過月餘，
賊必有内潰相圖之變矣。」

 rm#r04147@眞卿 曰：
「善！

」
命録事參軍 rm#r05397@李擇交 及 dm#dm02609@平原 令 rm#r05756@范冬馥 將其兵，
會 dm#dm05053@清河 兵四千及 dm#dm01090@博平 兵千人軍於 dm#dm01489@堂邑 西南。

 rm#r05839@袁知泰 遣其將 rm#r05684@白嗣恭 等將二萬餘人來逆戰，
三郡兵力戰盡日，
 dm#dm08945@魏 兵大敗，
斬首萬餘級，
捕虜千餘人，
得馬千匹，
軍資甚衆。

 rm#r05839@知泰 奔 dm#dm04536@汲郡 ，
遂克 dm#dm08957@魏郡 ，
軍聲大振。明名
# p 

時 dm#dm00875@北海 太守 rm#r03567@賀蘭進明 亦起兵，
 rm#r04147@眞卿 以書召之幷力，
 rm#r03567@進明 將歩騎五千渡 dm#dm04650@河 ，
 rm#r04147@眞卿 陳兵逆之，
相揖，
哭於馬上，
哀動行伍。

 rm#r03567@進明 屯 dm#dm02609@平原 城南，
休養士馬，
 rm#r04147@眞卿 毎事咨之，
由是軍權稍移於 rm#r03567@進明 矣，
 rm#r04147@眞卿 不以爲嫌。

 rm#r04147@眞卿 以 dm#dm01489@堂邑 之功讓 rm#r03567@進明 ，
 rm#r03567@進明 奏其状，
取捨任意。

敕加 rm#r03567@進明  dm#dm04656@河北 招討使，
 rm#r05397@擇交 、 rm#r05756@冬馥 微進資級，
 dm#dm05053@清河 、 dm#dm01090@博平 有功者皆不録。

 rm#r03567@進明 攻 dm#dm00585@信都郡 ，
久之，
不克；
録事參軍 dm#dm08170@長安  rm#r03064@第五琦 勸 rm#r03567@進明 厚以金帛募勇士，
遂克之。

# p 

 rm#r01630@李光弼 與 rm#r00380@史思明 相守四十餘日，
 rm#r00380@思明 絶 dm#dm02597@常山 糧道。

城中乏草，
馬食薦藉。

 rm#r01630@光弼 以車五百乘之 dm#dm06124@石邑 取草，
將車者皆衣甲，
弩手千人衞之，
爲方陳而行，
賊不能奪。

 rm#r06243@蔡希徳 引兵攻 dm#dm06124@石邑 ，
 rm#r05259@張奉璋 拒卻之。

 rm#r01630@光弼 遣使告急於 rm#r03707@郭子儀 ，
 rm#r03707@子儀 引兵自 dm#dm00409@井陘 出，
夏，
四月，
壬辰，
至 dm#dm02597@常山 ，
與 rm#r01630@光弼 合，
蕃、 dm#dm05271@漢 歩騎共十餘萬。

甲午，
 rm#r03707@子儀 、 rm#r01630@光弼 與 rm#r00380@史思明 等戰於 dm#dm00335@九門 城南，
 rm#r00380@思明 大敗。

中郎將 rm#r02462@渾瑊 射 rm#r05425@李立節 ，
殺之。

 rm#r02462@瑊 ，
 rm#r05569@釋之 之子也。

 rm#r00380@思明 收餘衆奔 dm#dm07625@趙郡 ，
 rm#r06243@蔡希徳 奔 dm#dm08069@鉅鹿 。

 rm#r00380@思明 自 dm#dm07625@趙郡 如 dm#dm01107@博陵 ，
時 dm#dm01107@博陵 已降官軍，
 rm#r00380@思明 盡殺郡官。

 dm#dm04671@河朔 之民苦賊殘暴，
所至屯結，
多至二萬人，
少者萬人，
各爲營以拒賊；
及 rm#r03707@郭 、 rm#r05425@李 軍至，
爭出自效。

庚子，
攻 dm#dm07625@趙郡 ；
一日，
城降。

士卒多虜掠，
 rm#r01630@光弼 坐城門，
收所獲，
悉歸之，
民大悦。

 rm#r03707@子儀 生擒四千人，
皆捨之，
斬 rm#r00793@祿山 太守 rm#r05944@郭獻璆 。

 rm#r01630@光弼 進圍 dm#dm01107@博陵 ，
十日，
不拔，
引兵還恆陽就食。

# p 

 rm#r02248@楊國忠 問士之可爲將者於左拾遺 dm#dm01090@博平  rm#r01264@張鎬 及 rm#r03245@蕭昕 ，
 rm#r01264@鎬 、 rm#r03245@昕 薦左贊善大夫 dm#dm04394@永壽  rm#r00120@來瑱 ，
丙午，
以 rm#r00120@瑱 爲 dm#dm05331@潁川 太守。

賊屡攻之，
 rm#r00120@瑱 前後破賊甚衆，
加本郡防禦使；
人謂之「來嚼鐵」。
# p 

 rm#r00793@安祿山 使 dm#dm02660@平盧 節度使 rm#r05117@呂知誨 誘 dm#dm02032@安東 副大都護 rm#r06079@馬靈詧 ，
殺之。

 dm#dm02660@平盧 遊弈使 dm#dm04316@武陟  rm#r05066@劉客奴 、先鋒使 rm#r03193@董秦 及 dm#dm02032@安東 將 rm#r05648@王玄志 同謀討誅 rm#r05117@知誨 ，
遣使踰海與 rm#r04147@顏眞卿 相聞，
請取 dm#dm06863@范陽 以自效。

 rm#r04147@眞卿 遣判官 rm#r05890@賈載 齎糧及戰士衣助之。

 rm#r04147@眞卿 時惟一子 rm#xjts01193@頗 ，
纔十餘歳，
使詣 rm#r05066@客奴 爲質。

朝廷聞之，
以客奴爲 dm#dm02660@平盧 節度使，
賜名 rm#r01943@正臣 ；
 rm#r05648@玄志 爲 dm#dm02032@安東 副大都護，
董 rm#r03193@秦 爲 dm#dm02660@平盧 兵馬使。
# p 

 dm#dm01077@南陽 節度使 rm#r04315@魯炅 立柵於 dm#dm05212@滍水 之南，
 rm#r00793@安祿山 將 rm#r06223@武令珣 、 rm#r05680@畢思琛 攻之。

# p 

五月，
丁巳，
 rm#r04315@炅 衆潰，
走保 dm#dm01077@南陽 ，
賊就圍之。

太常卿 rm#r01088@張垍 薦 dm#dm01839@夷陵 太守 rm#r03358@虢王巨 有勇略，
上徵 rm#r00527@呉王祗 爲太僕卿，
以 rm#r03358@巨 爲 dm#dm08355@陳留 ‧ dm#dm07453@譙郡 太守、 dm#dm04660@河南 節度使，
兼統 dm#dm02527@嶺南 節度使 rm#r05022@何履光 、 dm#dm09182@黔中 節度使 rm#r03613@趙國珍 、 dm#dm01077@南陽 節度使 rm#r04315@魯炅 。

 rm#r03613@國珍 ，
本牂柯夷也。

戊辰，
 rm#r03358@巨 引兵自 dm#dm07121@藍田 出，
趣 dm#dm01077@南陽 。

賊聞之，
解圍走。
# p 

 rm#r06151@令狐潮 復引兵攻 dm#dm08496@雍丘 。

 rm#r06151@潮 與 rm#r01142@張巡 有舊，
於城下相勞苦如平生，
 rm#r06151@潮 因説 rm#r01142@巡 曰：
「天下事去矣，
足下堅守危城，
欲誰爲乎？」
 rm#r01142@巡 曰：
「足下平生以忠義自許，
今日之舉，
忠義何在！

」
 rm#r06151@潮 慚而退。
# p 

 rm#r03707@郭子儀 、 rm#r01630@李光弼 還 dm#dm02597@常山 ，
 rm#r00380@史思明 收散卒數萬踵其後。

 rm#r03707@子儀 選驍騎更挑戰，
三日，
至 dm#dm07223@行唐 ，
賊疲，
乃退。

 rm#r03707@子儀 乘之，
又敗之於 dm#dm04619@沙河 。

 rm#r06243@蔡希徳 至 dm#dm04788@洛陽 ，
 rm#r00793@安祿山 復使將歩騎二萬人北就 rm#r00380@思明 ，
又使牛廷玠發范陽等郡兵萬餘人助思明，
合五萬餘人，
而同羅、曳落河居五分之一。

 rm#r03707@子儀 至 dm#dm03029@恆陽 ，
 rm#r00380@思明 隨至，
 rm#r03707@子儀 深溝高壘以待之；
賊來則守，
去則追之，
晝則耀兵，
夜斫其營，
賊不得休息。

數日，
 rm#r03707@子儀 、 rm#r01630@光弼 議曰：
「賊倦矣，
可以出戰。」

壬午，
戰于 dm#dm01416@嘉山 ，
大破之，
斬首四萬級，
捕虜千餘人。

 rm#r00380@思明 墜馬，
露髻跣足歩走，
至暮，
杖折槍歸營，
奔于 dm#dm01107@博陵 ；
 rm#r01630@光弼 就圍之，
軍聲大振。

於是 dm#dm04656@河北 十餘郡皆殺賊守將而降。

 dm#dm05254@漁陽 路再絶，
賊往來者皆輕騎竊過，
多爲官軍所獲，
將士家在 dm#dm05254@漁陽 者無不搖心。
# p 

 rm#r00793@祿山 大懼，
召 rm#r04212@高尚 、 rm#r06165@嚴莊 詬之曰：
「汝數年教我反，
以爲萬全。

今守 dm#dm05384@潼關 ，
數月不能進，
北路已絶，
諸軍四合，
吾所有者止 dm#dm04537@汴 、 dm#dm07947@鄭 數州而已，
萬全何在？
汝自今勿來見我！」

 rm#r04212@尚 、 rm#r06165@莊 懼，
數日不敢見。

 rm#r06237@田乾眞 自關下來，
爲 rm#r04212@尚 、 rm#r06165@莊 説 rm#r00793@祿山 曰：
「自古帝王經營大業，
皆有勝敗，
豈能一舉而成！

今四方軍壘雖多，
皆新募烏合之衆，
未更行陳，
豈能敵我 dm#dm07105@薊北 勁鋭之兵，
何足深憂！

 rm#r04212@尚 、 rm#r06165@莊 皆佐命元勳，
陛下一旦絶之，
使諸將聞之，
誰不内懼！

若上下離心，
臣竊爲陛下危之！」

 rm#r00793@祿山 喜曰：
「 rm#r06237@阿浩 ，
汝能豁我心事。」

即召 rm#r04212@尚 、 rm#r06165@莊 ，
置酒酣宴，
自爲之歌以侑酒，
待之如初。

 rm#r06237@阿浩 ，
 rm#r06237@乾眞 小字也。

 rm#r00793@祿山 議棄 dm#dm04788@洛陽 ，
走歸 dm#dm06863@范陽 ，
計未決。
# p 

是時，
天下以 rm#r02248@楊國忠 驕縱召亂，
莫不切齒。

又，
 rm#r00793@祿山 起兵以誅 rm#r02248@國忠 爲名，
 rm#r02633@王思禮 密説 rm#r00487@哥舒翰 ，
使抗表請誅 rm#r02248@國忠 ，
 rm#r00487@翰 不應。

 rm#r02633@思禮 又請以三十騎劫取以來，
至 dm#dm05384@潼關 殺之，
 rm#r00487@翰 曰：
「如此，
乃 rm#r00487@翰 反，
非 rm#r00793@祿山 也。」

或説 rm#r02248@國忠 ：
「今朝廷重兵盡在 rm#r00487@翰 手，
 rm#r00487@翰 若援旗西指，
於公豈不危哉！」

 rm#r02248@國忠 大懼，
乃奏：
「 dm#dm05384@潼關 大軍雖盛，
而後無繼，
萬一失利，
 dm#dm08170@京師 可憂，
請選監牧小兒三千於苑中訓練。」

上許之，
使 dm#dm00785@劍南 軍將 rm#r05423@李福徳 等領之。

又募萬人屯 dm#dm05501@灞上 ，
令所親 rm#r06647@杜乾運 將之，
名爲禦賊，
實備 rm#r00487@翰 也。

 rm#r00487@翰 聞之，
亦恐爲 rm#r02248@國忠 所圖，
乃表請 dm#dm05501@灞上 軍隸 dm#dm05384@潼關 ；
六月，
癸未，
召 rm#r06647@杜乾運 詣 dm#dm08280@關 ，
因事斬之；
 rm#r02248@國忠 益懼。
# p 

會有告 rm#r06181@崔乾祐 在陝，
兵不滿四千，
皆羸弱無備，
上遣使趣 rm#r00487@哥舒翰 進兵復 dm#dm08318@陝 、 dm#dm04761@洛 。

 rm#r00487@翰 奏曰：
「 rm#r00793@祿山 久習用兵，
今始爲逆，
豈肯無備！

是必羸師以誘我，
若往，
正墮其計中。

且賊遠來，
利在速戰；
官軍據險以扼之，
利在堅守。

況賊殘虐失衆，
兵勢日蹙，
將有内變；
因而乘之，
可不戰擒也。

要在成功，
何必務速！

今諸道徵兵尚多未集，
請且待之。」

 rm#r03707@郭子儀 、 rm#r01630@李光弼 亦上言：
「請引兵北取 dm#dm06863@范陽 ，
覆其巣穴，
質賊黨妻子以招之，
賊必内潰。

 dm#dm05384@潼關 大軍，
唯應固守以弊之，
不可輕出。」

 rm#r02248@國忠 疑 rm#r00487@翰 謀己，
言於上，
以賊方無備，
而 rm#r00487@翰 逗留，
將失機會。

上以爲然，
續遣中使趣之，
項背相望。

 rm#r00487@翰 不得已，
撫膺慟哭；
丙戌，
引兵出 dm#dm08280@關 。

# p 

己丑，
遇 rm#r06181@崔乾祐 之軍於 dm#dm08614@靈寶 西原。

 rm#r06181@乾祐 據險以待之，
南薄山，
北阻 dm#dm04650@河 ，
隘道七十里。

庚寅，
官軍與 rm#r06181@乾祐 會戰。

 rm#r06181@乾祐 伏兵於險，
 rm#r00487@翰 與 rm#?@田良丘 浮舟中流以觀軍勢，
見 rm#r06181@乾祐 兵少，
趣諸軍使進。

 rm#r02633@王思禮 等將精兵五萬居前，
 rm#r06146@龐忠 等將餘兵十萬繼之，
 rm#r00487@翰 以兵三萬登 dm#dm04650@河 北阜望之，
鳴鼓以助其勢。

 rm#r06181@乾祐 所出兵不過萬人，
什什伍伍，
散如列星，
或疏或密，
或前或卻，
官軍望而笑之。

 rm#r06181@乾祐 嚴精兵，
陳於其後。

兵既交，
賊偃旗如欲遁者，
官軍懈，
不爲備。

須臾，
伏兵發，
賊乘高下木石，
撃殺士卒甚衆。

道隘，
士卒如束，
槍槊不得用。

 rm#r00487@翰 以氈車駕馬爲前驅，
欲以衝賊。

日過中，
東風暴急，
 rm#r06181@乾祐 以草車數十乘塞氈車之前，
縱火焚之。

煙焔所被，
官軍不能開目，
妄自相殺，
謂賊在煙中，
聚弓弩而射之。

日暮，
矢盡，
乃知無賊。

 rm#r06181@乾祐 遣同羅精騎自南山過，
出官軍之後撃之，
官軍首尾駭亂，
不知所備，
於是大敗；
或棄甲竄匿山谷，
或相擠排入 dm#dm04650@河 溺死，
囂聲振天地，
賊乘勝蹙之。

後軍見前軍敗，
皆自潰，
 dm#dm04656@河北 軍望之亦潰。

 rm#r00487@翰 獨與麾下數百騎走，
自 dm#dm08809@首陽山 西渡 dm#dm04650@河 入 dm#dm08280@關 。

 dm#dm08280@關 外先爲三塹，
皆廣二丈，
深丈，
人馬墜其中，
須臾而滿；
餘衆踐之以度，
士卒得入 dm#dm08280@關 者纔八千餘人。

辛卯，
 rm#r06181@乾祐 進攻 dm#dm05384@潼關 ，
克之。瞬息間兩岸皆空
# p 

 rm#r00487@翰 至 dm#dm08289@關西驛 ，
掲牓收散卒，
欲復守 dm#dm05384@潼關 。

蕃將 rm#?@火拔歸仁 等以百餘騎圍驛，
入謂 rm#r00487@翰 曰：
「賊至矣，
請公上馬。」

 rm#r00487@翰 上馬出驛，
 rm#?@歸仁 帥衆叩頭曰：
「公以二十萬衆一戰棄之，
何面目復見天子！

且公不見 rm#r04214@高仙芝 、 rm#r00852@封常清 乎？
請公東行。」

 rm#r00487@翰 不可，
欲下馬。

 rm#?@歸仁 以毛縶其足於馬腹，
及諸將不從者，
皆執之以東。

會賊將 rm#r06237@田乾眞 已至，
遂降之，
倶送 dm#dm04788@洛陽 。

 rm#r00793@安祿山 問 rm#r00487@翰 曰：
「汝常輕我，
今定何如？」
 rm#r00487@翰 伏地對曰：
「臣肉眼不識聖人。

今天下未平，
 rm#r01630@李光弼 在 dm#dm02597@常山 ，
 rm#r05422@李祗 在 dm#dm03822@東平 ，
 rm#r04315@魯炅 在 dm#dm01077@南陽 ，
陛下留臣，
使以尺書招之，
不日皆下矣。

」
 rm#r00793@祿山 大喜，
以 rm#r00487@翰 爲司空、同平章事。

謂 rm#?@火拔歸仁 曰：
「汝叛主，
不忠不義。」

執而斬之。

 rm#r00487@翰 以書招諸將，
皆復書責之。

 rm#r00793@祿山 知不效，
乃囚諸苑中。

 dm#dm05384@潼關 既敗，
於是 dm#dm04672@河東 、 dm#dm06943@華陰 、 dm#dm08850@馮翊 、 dm#dm00175@上洛 防禦使皆棄郡走，
所在守兵皆散。
# p 

是日，
 rm#r00487@翰 麾下來告急，
上不時召見，
但遣 rm#r05423@李福徳 等將監牧兵赴 dm#dm05384@潼關 。

及暮，
平安火不至，
上始懼。

壬辰，
召宰相謀之。

 rm#r02248@楊國忠 自以身領 dm#dm00785@劍南 ，
聞 rm#r00793@安祿山 反，
即令副使 rm#r00908@崔圓 陰具儲偫，
以備有急投之，
至是首唱幸 dm#dm07197@蜀 之策。

上然之。

癸巳，
 rm#r02248@國忠 集百官於朝堂，
惶懅流涕；
問以策略，
皆唯唯不對。

 rm#r02248@國忠 曰：
「人告 rm#r00793@祿山 反状已十年，
上不之信。

今日之事，
非宰相之過。」

仗下，
士民驚擾奔走，
不知所之，
市里蕭條。

 rm#r02248@國忠 使 rm#ry0003@韓 、 rm#?@虢 入宮，
勸上入 dm#dm07197@蜀 。
# p 

甲午，
百官朝者什無一二。

上御 dm#dm00820@勤政樓 ，
下制，
云欲親征，
聞者皆莫之信。

以 dm#dm00427@京兆 尹 rm#r06122@魏方進 爲御史大夫兼置頓使；
 dm#dm00427@京兆 少尹 dm#dm08623@靈昌  rm#r00901@崔光遠 爲 dm#dm00427@京兆 尹，
充 dm#dm07290@西京 留守；
將軍 rm#xjts12612@邊令誠 掌宮闈管鑰。

託以 dm#dm00785@劍南 節度大使 rm#r02516@潁王璬 將赴鎭，
令本道設儲偫。

是日，
上移仗 dm#dm00834@北内 。

既夕，
命龍武大將軍 rm#r03929@陳玄禮 整比六軍，
厚賜錢帛，
選閑廐馬九百餘匹，
外人皆莫之知。

乙未，
黎明，
上獨與貴𡚱姉妹、皇子、𡚱、主、皇孫、 rm#r02248@楊國忠 、 rm#r04073@韋見素 、 rm#r06122@魏方進 、 rm#r03929@陳玄禮 及親近宦官、宮人出 dm#dm02827@延秋門 ，
𡚱、主、皇孫之在外者，
皆委之而去。

上過左藏，
 rm#r02248@楊國忠 請焚之，
曰：
「無爲賊守。」

上愀然曰：
「賊來不得，
必更斂於百姓；
不如與之，
無重困吾赤子。」

是日，
百官猶有入朝者，
至宮門，
猶聞漏聲，
三衞立仗儼然。

門既啓，
則宮人亂出，
中外擾攘，
不知上所之。

於是王公、士民四出逃竄，
山谷細民爭入宮禁及王公第舍，
盜取金寶，
或乘驢上殿。

又焚左藏 dm#dm01663@大盈庫 。

 rm#r00901@崔光遠 、 rm#xjts12612@邊令誠 帥人救火，
又募人攝府、縣官分守之，
殺十餘人，
乃稍定。

 rm#r00901@光遠 遣其子東見 rm#r00793@祿山 ，
 rm#xjts12612@令誠 亦以管鑰獻之。
# p 

上過便橋，
 rm#r02248@楊國忠 使人焚橋。

上曰：
「士庶各避賊求生，
奈何絶其路！」

留内侍監 rm#r04220@高力士 ，
使撲滅乃來。

上遣宦者 rm#r05645@王洛卿 前行，
告諭郡縣置頓。

食時，
至 dm#dm01345@咸陽  dm#dm03705@望賢宮 ，
 rm#r05645@洛卿 與縣令倶逃，
中使徵召，
吏民莫有應者。

日向中，
上猶未食，
 rm#r02248@楊國忠 自市胡餅以獻。

於是民爭獻糲飯，
雜以麥豆；
皇孫輩爭以手掬食之，
須臾而盡，
猶未能飽。

上皆酬其直，
慰勞之。

衆皆哭，
上亦掩泣。

有老父 rm#r05941@郭從謹 進言曰：
「 rm#r00793@祿山 包藏禍心，
固非一日；
亦有詣闕告其謀者，
陛下往往誅之，
使得逞其姦逆，
致陛下播越。

是以先王務延訪忠良以廣聰明，
蓋爲此也。

臣猶記 rm#r00813@宋璟 爲相，
數進直言，
天下頼以安平。

自頃以來，
在廷之臣以言爲諱，
惟阿諛取容，
是以闕門之外，
陛下皆不得而知。

草野之臣，
必知有今日久矣，
但九重嚴邃，
區區之心無路上達。

事不至此，
臣何由得睹陛下之面而訴之乎！」

上曰：
「此朕之不明，
悔無所及。」

慰諭而遣之。

俄而尚食舉御膳而至，
上命先賜從官，
然後食之。

令軍士散詣村落求食，
期未時皆集而行。

夜將半，
乃至 dm#dm08011@金城 。

縣令亦逃，
縣民皆脱身走，
飮食器皿具在，
士卒得以自給。

時從者多逃，
内侍監 rm#rx0011@袁思藝 亦亡去。

驛中無燈，
人相枕藉而寢，
貴賤無以復辨。

 rm#r02633@王思禮 自 dm#dm05384@潼關 至，
始知 rm#r00487@哥舒翰 被擒；
以 rm#r02633@思禮 爲 dm#dm04695@河西 、 dm#dm08458@隴右 節度使，
即令赴鎭，
收合散卒，
以俟東討。
# p 

丙申，
至 dm#dm08815@馬嵬驛 ，
將士飢疲，
皆憤怒。

 rm#r03929@陳玄禮 以禍由 rm#r02248@楊國忠 ，
欲誅之，
因東宮宦者 rm#r02010@李輔國 以告太子，
太子未決。

會吐蕃使者二十餘人遮 rm#r02248@國忠 馬，
訴以無食，
 rm#r02248@國忠 未及對，
軍士呼曰：
「 rm#r02248@國忠 與胡虜謀反！」

或射之，
中鞍。

 rm#r02248@國忠 走至西門内，
軍士追殺之，
屠割支體，
以槍掲其首於驛門外，
幷殺其子戸部侍郎 rm#r06089@暄 及 rm#xjts22963@韓國 、 rm#?@秦國夫人 。

御史大夫 rm#r06122@魏方進 曰：
「汝曹何敢害宰相！」

衆又殺之。

 rm#r04073@韋見素 聞亂而出，
爲亂兵所檛，
腦血流地。

衆曰：
「勿傷 rm#r04073@韋相公 。」

救之，
得免。

軍士圍驛，
上聞諠譁，
問外何事，
左右以 rm#r02248@國忠 反對。

上杖屨出驛門，
慰勞軍士，
令收隊，
軍士不應。

上使 rm#r04220@高力士 問之，
 rm#r03929@玄禮 對曰：
「 rm#r02248@國忠 謀反，
貴𡚱不宜供奉，
願陛下割恩正法。」

上曰：
「朕當自處之。」

入門，
倚杖傾首而立。

久之，
 dm#dm00427@京兆 司録 rm#r04074@韋諤 前言曰：
「今衆怒難犯，
安危在晷刻，
願陛下速決！」

因叩頭流血。

上曰：
「貴𡚱常居深宮，
安知 rm#r02248@國忠 反謀？」
 rm#r04220@高力士 曰：
「貴𡚱誠無罪，
然將士已殺 rm#r02248@國忠 ，
而貴𡚱在陛下左右，
豈敢自安！

願陛下審思之，
將士安則陛下安矣。」

上乃命 rm#r04220@力士 引貴𡚱於佛堂，
縊殺之。

輿尸置驛庭，
召 rm#r03929@玄禮 等入視之。

 rm#r03929@玄禮 等乃免冑釋甲，
頓首請罪，
上慰勞之，
令曉諭軍士。

 rm#r03929@玄禮 等皆呼萬歳，
再拜而出，
於是始整部伍爲行計。

 rm#r04074@諤 ，
 rm#r04073@見素 之子也。

 rm#r02248@國忠 妻 rm#r06257@裴柔 與其幼子 rm#r06256@晞 及 rm#?@虢國夫人 、夫人子 rm#r06254@裴徽 ，
皆走至 dm#dm08349@陳倉 ，
縣令 rm#r06245@薛景仙 帥吏士追捕，
誅之。

# p 

丁酉，
上將發 dm#dm08814@馬嵬 ，
朝臣惟 rm#r04073@韋見素 一人，
乃以 rm#r04074@韋諤 爲御史中丞，
充置頓使。

將士皆曰：
「 rm#r02248@國忠 謀反，
其將吏皆在 dm#dm07197@蜀 ，
不可往。」

或請之 dm#dm04650@河 、 dm#dm08457@隴 ，
或請之 dm#dm08626@靈武 ，
或請之 dm#dm01774@太原 ，
或言還 dm#dm08170@京師 。

上意在入 dm#dm07197@蜀 ，
慮違衆心，
竟不言所向。

 rm#r04074@韋諤 曰：
「還 dm#dm00426@京 ，
當有禦賊之備。

今兵少，
未易東向，
不如且至 dm#dm03177@扶風 ，
徐圖去就。」

上詢于衆，
衆以爲然，
乃從之。

及行，
父老皆遮道請留，
曰：
「宮闕，
陛下家居，
陵寢，
陛下墳墓，
今捨此，
欲何之？」
上爲之按轡久之，
乃令太子於後宣慰父老。

父老因曰：
「至尊既不肯留，
某等願帥子弟從殿下東破賊，
取 dm#dm08170@長安 。

若殿下與至尊皆入 dm#dm07197@蜀 ，
使中原百姓誰爲之主？」
須臾，
衆至數千人。

太子不可，
曰：
「至尊遠冒險阻，
吾豈忍朝夕離左右。

且吾尚未面辭，
當還白至尊，
更稟進止。」

涕泣，
跋馬欲西。

 rm#r01077@建寧王倓 與 rm#r02010@李輔國 執鞚諫曰：
「逆胡犯闕，
四海分崩，
不因人情，
何以興復！

今殿下從至尊入 dm#dm07197@蜀 ，
若賊兵燒絶棧道，
則中原之地拱手授賊矣。

人情既離，
不可復合，
雖欲復至此，
其可得乎！

不如收西北守邊之兵，
召 rm#r03707@郭 、 rm#r01630@李 於 dm#dm04656@河北 ，
與之併力東討逆賊，
克復兩京，
削平四海，
使社稷危而復安，
宗廟毀而更存，
掃除宮禁以迎至尊，
豈非孝之大者乎！

何必區區温凊，
爲兒女之戀乎！」

 rm#r01617@廣平王俶 亦勸太子留。

父老共擁太子馬，
不得行。

太子乃使 rm#r01617@俶 馳白上。

上總轡待太子，
久不至，
使人偵之，
還白状，
上曰：
「天也！」

乃分後軍二千人及飛龍廐馬從太子，
且諭將士曰：
「太子仁孝，
可奉宗廟，
汝曹善輔佐之。」

又諭太子曰：
「汝勉之，
勿以吾爲念。

西北諸胡，
吾撫之素厚，
汝必得其用。」

太子南向號泣而已。

又使送東宮内人於太子，
且宣旨欲傳位，
太子不受。

 rm#r01617@俶 、 rm#r01077@倓 ，
皆太子之子也。
# p 

己亥，
上至 dm#dm02417@岐山 。

或言賊前鋒且至，
上遽過，
宿 dm#dm03179@扶風郡 。

士卒潛懷去就，
往往流言不遜，
 rm#r03929@陳玄禮 不能制，
上患之。

會 dm#dm03147@成都 貢春綵十餘萬匹，
至 dm#dm03177@扶風 ，
上命悉陳之於庭，
召將士入，
臨軒諭之曰：
「朕比來衰耄，
託任失人，
致逆胡亂常，
須遠避其鋒。

知卿等皆蒼猝從朕，
不得別父母妻子，
茇渉至此，
勞苦至矣，
朕甚愧之。

 dm#dm07197@蜀 路阻長，
郡縣褊小，
人馬衆多，
或不能供，
今聽卿等各還家；
朕獨與子、孫、中官前行入 dm#dm07197@蜀 ，
亦足自達。

今日與卿等訣別，
可共分此綵以備資糧。

若歸，
見父母及 dm#dm08170@長安 父老，
爲朕致意，
各好自愛也！」

因泣下霑襟。

衆皆哭，
曰：
「臣等死生從陛下，
不敢有貳！」

上良久曰：
「去留聽卿。」

自是流言始息。

# p 

太子既留，
莫知所適。

 rm#r01617@廣平王俶 曰：
「日漸晏，
此不可駐，
衆欲何之？」
皆莫對。

 rm#r01077@建寧王倓 曰：
「殿下昔嘗爲 dm#dm03677@朔方 節度大使，
將吏歳時致啓，
 rm#?@倓 略識其姓名。

今 dm#dm04695@河西 、 dm#dm08458@隴右 之衆皆敗降賊，
父兄子弟多在賊中，
或生異圖。

 dm#dm03677@朔方 道近，
士馬全盛，
 rm#r03411@裴冕 衣冠名族，
必無貳心。

賊入 dm#dm08170@長安 方虜掠，
未暇徇地，
乘此速往就之，
徐圖大舉，
此上策也。」

衆皆曰：
「善！」

至 dm#dm05102@渭 濱，
遇 dm#dm05384@潼關 敗卒，
誤與之戰，
死傷甚衆。

已，
乃收餘卒，
擇 dm#dm05117@渭水 淺處，
乘馬渉渡；
無馬者涕泣而返。

太子自 dm#dm01853@奉天 北上，
比至 dm#dm03346@新平 ，
通夜馳三百里，
士卒、器械失亡過半，
所存之衆不過數百。

 dm#dm03346@新平 太守 rm#r05821@薛羽 棄郡走，
太子斬之。

是日，
至 dm#dm02000@安定 ，
太守 rm#r05315@徐瑴 亦走，
又斬之。

# p 

庚子，
以 dm#dm00785@劍南 節度留後 rm#r00908@崔圓 爲 dm#dm00785@劍南 節度等副大使。

辛丑，
上發 dm#dm03177@扶風 ，
宿 dm#dm08349@陳倉 。
# p 

太子至 dm#dm05525@烏氏 ，
 dm#dm02922@彭原 太守 rm#r01994@李遵 出迎，
獻衣及糗糧。

至 dm#dm02922@彭原 ，
募士，
得數百人。

是日至 dm#dm02650@平涼 ，
閲監牧馬，
得數萬匹，
又募士，
得五百餘人，
軍勢稍振。
# p 

壬寅，
上至 dm#dm03283@散關 ，
分扈從將士爲六軍。

使 rm#r02516@潁王璬 先行詣 dm#dm00785@劍南 ，
 rm#r00588@壽王瑁 等分將六軍以次之。

丙午，
上至 dm#dm04682@河池郡 。

 rm#r00908@崔圓 奉表迎車駕，
具陳 dm#dm07197@蜀 土豐稔，
甲兵全盛。

上大悦，
即日，
以 rm#r00908@圓 爲中書侍郎、同平章事，
 dm#dm07205@蜀郡 長史如故。

以 rm#r02498@隴西公瑀 爲 rm#r02498@漢中王 、 dm#dm04043@梁州 都督、 dm#dm02398@山南  dm#dm07383@西道 采訪‧防禦使。

 rm#r02498@瑀 ，
 rm#r02396@璡 之弟也。


# p 

 rm#r02633@王思禮 至 dm#dm02650@平涼 ，
聞 dm#dm04695@河西 諸胡亂，
還，
詣行在。

初，
 dm#dm04695@河西 諸胡部落聞其都護皆從 rm#r00487@哥舒翰 沒於 dm#dm05384@潼關 ，
故爭自立，
相攻撃；
而都護實從 rm#r00487@翰 在北岸，
不死，
又不與 rm#xjts28834@火拔歸仁 倶降賊。

上乃以 dm#dm04695@河西 兵馬使 rm#r05128@周泌 爲 dm#dm04695@河西 節度使，
 dm#dm08458@隴右 兵馬使 rm#r05312@彭元耀 爲 dm#dm08458@隴右 節度使，
與都護 rm@思結進明 等倶之鎭，
招其部落。

以 rm#r02633@思禮 爲行在都知兵馬使。
# p 

戊申，
 dm#dm03177@扶風 民 rm#r05240@康景龍 等自相帥撃賊所署宣慰使 rm#r05820@薛總 ，
斬首二百餘級。

庚戌，
 dm#dm08349@陳倉 令 rm#r06245@薛景仙 殺賊守將，
克 dm#dm03177@扶風 而守之。

# p 

 rm#r00793@安祿山 不意上遽西幸，
遣使止 rm#r06181@崔乾祐 兵留 dm#dm05384@潼關 ，
凡十日，
乃遣 rm#r00716@孫孝哲 將兵入 dm#dm08170@長安 ，
以 rm#r06191@張通儒 爲 dm#dm07290@西京 留守，
 rm#r00901@崔光遠 爲 dm#dm00427@京兆 尹；
使 rm#r05173@安忠順 將兵屯苑中，
以鎭 dm#dm08281@關中 。

 rm#r00716@孝哲 爲 rm#r00793@祿山 所寵任，
尤用事，
常與 rm#r06165@嚴莊 爭權；
 rm#r00793@祿山 使監 dm#dm08281@關中 諸將，
 rm#r06191@通儒 等皆受制於 rm#r00716@孝哲 。

 rm#r00716@孝哲 豪侈，
果於殺戮，
賊黨畏之。

 rm#r00793@祿山 命搜捕百官、宦者、宮女等，
毎獲數百人，
輒以兵衞送 dm#dm04788@洛陽 。

王、侯、將、相扈從車駕、家留 dm#dm08170@長安 者，
誅及嬰孩。

 rm#r03924@陳希烈 以晩節失恩，
怨上，
與 rm#r01127@張均 、 rm#r01088@張垍 等皆降於賊。

 rm#r00793@祿山 以 rm#r03924@希烈 、 rm#r01088@垍 爲相，
自餘朝士皆授以官。

於是賊勢大熾，
西脅 dm#dm00067@汧 、 dm#dm08457@隴 ，
南侵 dm#dm04475@江 、 dm#dm05271@漢 ，
北割 dm#dm04672@河東 之半。

然賊將皆粗猛無遠略，
既克 dm#dm08170@長安 ，
以爲得志，
日夜縱酒，
專以聲色寶賄爲事，
無復西出之意，
故上得安行入 dm#dm07197@蜀 ，
太子北行亦無追迫之患。忠順守忠
# p 

 rm#r01630@李光弼 圍 dm#dm01107@博陵 未下，
聞 dm#dm05384@潼關 不守，
解圍而南。

 rm#r00380@史思明 踵其後，
 rm#r01630@光弼 撃卻之，
與 rm#r03707@郭子儀 皆引兵入 dm#dm00409@井陘 ，
留 dm#dm02597@常山 太守 rm#r02589@王俌 將景城、 dm#dm04700@河間 團練兵守 dm#dm02597@常山 。

 dm#dm02660@平盧 節度使 rm#r05079@劉正臣 將襲 dm#dm06863@范陽 ，
未至，
 rm#r00380@史思明 引兵逆撃之，
 rm#r05079@正臣 大敗，
棄妻子走，
士卒死者七千餘人。

初，
 rm#r04147@顏眞卿 聞 dm#dm04656@河北 節度使 rm#r01630@李光弼 出 dm#dm00409@井陘 ，
即斂軍還 dm#dm02609@平原 ，
以待 rm#r01630@光弼 之命。

聞 rm#r03707@郭 、 rm#r01630@李 西入 dm#dm00409@井陘 ，
 rm#r04147@眞卿 始復區處 dm#dm04656@河北 軍事。

# p 

太子至 dm#dm02650@平涼 數日，
 dm#dm03677@朔方 留後 rm#r02067@杜鴻漸 、六城水陸運使 rm#r04285@魏少遊 、節度判官 rm#r05223@崔漪 、支度判官 rm#r05709@盧簡金 、 dm#dm09057@鹽池 判官 rm#r01844@李涵 相與謀曰：
「 dm#dm02650@平涼 散地，
非屯兵之所，
 dm#dm08626@靈武 兵食完富，
若迎太子至此，
北收諸城兵，
西發 dm#dm04650@河 、 dm#dm08457@隴 勁騎，
南向以定中原，
此萬世一時也。」

乃使 rm#r01844@涵 奉牋於太子，
且籍 dm#dm03677@朔方 士馬、甲兵、穀帛、軍須之數以獻之。

 rm#r01844@涵 至 dm#dm02650@平涼 ，
太子大悦。

會 dm#dm04695@河西 司馬 rm#r03411@裴冕 入爲御史中丞，
至 dm#dm02650@平涼 見太子，
亦勸太子之 dm#dm03677@朔方 ，
太子從之。

 rm#r02067@鴻漸 ，
 rm#r02050@暹 之族子；
 rm#r01844@涵 ，
 rm#r04205@道 之曾孫也。

 rm#r02067@鴻漸 、 rm#r05223@漪 使 rm#r04285@少遊 居後，
葺次舍，
庀資儲，
自迎太子於 dm#dm02650@平涼 北境，
説太子曰：
「 dm#dm03677@朔方 ，
天下勁兵處也。

今吐蕃請和，
囘紇内附，
四方郡縣大抵堅守拒賊以俟興復。

殿下今理兵 dm#dm08626@靈武 ，
按轡長驅，
移檄四方，
收攬忠義，
則逆賊不足屠也。」

 rm#r04285@少遊 盛治宮室，
帷帳皆倣禁中，
飮膳備水陸。

秋，
七月，
辛酉，
太子至 dm#dm08626@靈武 ，
悉命撤之。

# p 

甲子，
上至 dm#dm03575@普安 ，
憲部侍郎 rm#r01381@房琯 來謁見。

上之發 dm#dm08170@長安 也，
羣臣多不知，
至 dm#dm01345@咸陽 ，
謂 rm#r04220@高力士 曰：
「朝臣誰當來，
誰不來？」
對曰：
「 rm#r01127@張均 、 rm#r01088@張垍 父子受陛下恩最深，
且連戚里，
是必先來。

時論皆謂 rm#r01381@房琯 宜爲相，
而陛下不用，
又 rm#r00793@祿山 嘗薦之，
恐或不來。」

上曰：
「事未可知。」

及 rm#r01381@琯 至，
上問 rm#r01127@均 兄弟，
對曰：
「臣帥與偕來，
逗遛不進；
觀其意，
似有所蓄而不能言也。」

上顧 rm#r04220@力士 曰：
「朕固知之矣。」

即日，
以 rm#r01381@琯 爲文部侍郎、同平章事。

# p 

初，
 rm#r01088@張垍 尚 rm#r03134@寧親公主 ，
聽於禁中置宅，
寵渥無比。

 rm#r03924@陳希烈 求解政務，
上幸 rm#r01088@垍 宅，
問可爲相者。

 rm#r01088@垍 未對。

上曰：
「無若愛壻。」

 rm#r01088@垍 降階拜舞。

既而不用，
故 rm#r01088@垍 懷怏怏，
上亦覺之。

是時 rm#r01127@均 、 rm#r01088@垍 兄弟及 rm#r00627@姚崇 之子尚書右丞 rm#xjts19521@奕 、 rm#r03240@蕭嵩 之子兵部侍郎 rm#r03255@華 、 rm#r04019@韋安石 之子禮部侍郎 rm#r04081@陟 、太常少卿 rm#r04038@斌 ，
皆以才望至大官，
上嘗曰：
「吾命相，
當徧舉故相子弟耳。」

既而皆不用。
